/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const DANSK_MATCH_P2: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'da0-m101', type: 'Match', question: 'Form: Cirkel', answer: '⚪', options: ['⚪', '⬜', '📐', '⭐'], instruction: 'Find figuren' },
    { id: 'da0-m102', type: 'Match', question: 'Form: Kvadrat', answer: '⬜', options: ['⚪', '⬜', '📐', '⭐'], instruction: 'Find figuren' },
    { id: 'da0-m103', type: 'Match', question: 'Form: Trekant', answer: '📐', options: ['⚪', '⬜', '📐', '⭐'], instruction: 'Find figuren' },
    { id: 'da0-m104', type: 'Match', question: 'Form: Stjerne', answer: '⭐', options: ['⚪', '⬜', '📐', '⭐'], instruction: 'Find figuren' },
    { id: 'da0-m105', type: 'Match', question: 'Dyr: Hund', answer: '🐶', options: ['🐶', '🐱', '🐭', '🐹'], instruction: 'Find dyret' },
    { id: 'da0-m106', type: 'Match', question: 'Dyr: Kat', answer: '🐱', options: ['🐶', '🐱', '🐭', '🐹'], instruction: 'Find dyret' },
    { id: 'da0-m107', type: 'Match', question: 'Dyr: Mus', answer: '🐭', options: ['🐶', '🐱', '🐭', '🐹'], instruction: 'Find dyret' },
    { id: 'da0-m108', type: 'Match', question: 'Dyr: Hest', answer: '🐴', options: ['🐴', '🐮', '🐷', '🐑'], instruction: 'Find dyret' },
    { id: 'da0-m109', type: 'Match', question: 'Dyr: Ko', answer: '🐮', options: ['🐴', '🐮', '🐷', '🐑'], instruction: 'Find dyret' },
    { id: 'da0-m110', type: 'Match', question: 'Dyr: Gris', answer: '🐷', options: ['🐴', '🐮', '🐷', '🐑'], instruction: 'Find dyret' },
    { id: 'da0-m111', type: 'Match', question: 'Tal: 11', answer: 'Elleve', options: ['Elleve', 'Tolv', 'Tretten', 'Fjorten'], instruction: 'Match tal og ord' },
    { id: 'da0-m112', type: 'Match', question: 'Tal: 12', answer: 'Tolv', options: ['Elleve', 'Tolv', 'Tretten', 'Fjorten'], instruction: 'Match tal og ord' },
    { id: 'da0-m113', type: 'Match', question: 'Tal: 13', answer: 'Tretten', options: ['Elleve', 'Tolv', 'Tretten', 'Fjorten'], instruction: 'Match tal og ord' },
    { id: 'da0-m114', type: 'Match', question: 'Tal: 14', answer: 'Fjorten', options: ['Elleve', 'Tolv', 'Tretten', 'Fjorten'], instruction: 'Match tal og ord' },
    { id: 'da0-m115', type: 'Match', question: 'Tal: 15', answer: 'Femten', options: ['Femten', 'Seksten', 'Sytten', 'Atten'], instruction: 'Match tal og ord' },
    { id: 'da0-m116', type: 'Match', question: 'Tal: 16', answer: 'Seksten', options: ['Femten', 'Seksten', 'Sytten', 'Atten'], instruction: 'Match tal og ord' },
    { id: 'da0-m117', type: 'Match', question: 'Tal: 17', answer: 'Sytten', options: ['Femten', 'Seksten', 'Sytten', 'Atten'], instruction: 'Match tal og ord' },
    { id: 'da0-m118', type: 'Match', question: 'Tal: 18', answer: 'Atten', options: ['Femten', 'Seksten', 'Sytten', 'Atten'], instruction: 'Match tal og ord' },
    { id: 'da0-m119', type: 'Match', question: 'Tal: 19', answer: 'Nitten', options: ['Nitten', 'Tyve', 'Enogtyve', 'Toogtyve'], instruction: 'Match tal og ord' },
    { id: 'da0-m120', type: 'Match', question: 'Tal: 20', answer: 'Tyve', options: ['Nitten', 'Tyve', 'Enogtyve', 'Toogtyve'], instruction: 'Match tal og ord' },
    { id: 'da0-m121', type: 'Match', question: 'Frugt: Banan', answer: '🍌', options: ['🍌', '🍎', '🍐', '🍓'], instruction: 'Find frugten' },
    { id: 'da0-m122', type: 'Match', question: 'Frugt: Jordbær', answer: '🍓', options: ['🍌', '🍎', '🍐', '🍓'], instruction: 'Find frugten' },
    { id: 'da0-m123', type: 'Match', question: 'Frugt: Pære', answer: '🍐', options: ['🍌', '🍎', '🍐', '🍓'], instruction: 'Find frugten' },
    { id: 'da0-m124', type: 'Match', question: 'Frugt: Appelsin', answer: '🍊', options: ['🍊', '🍋', '🍎', '🍏'], instruction: 'Find frugten' },
    { id: 'da0-m125', type: 'Match', question: 'Vejr: Regn', answer: '🌧️', options: ['🌧️', '☀️', '☁️', '❄️'], instruction: 'Find vejret' },
    { id: 'da0-m126', type: 'Match', question: 'Vejr: Sol', answer: '☀️', options: ['🌧️', '☀️', '☁️', '❄️'], instruction: 'Find vejret' },
    { id: 'da0-m127', type: 'Match', question: 'Vejr: Sky', answer: '☁️', options: ['🌧️', '☀️', '☁️', '❄️'], instruction: 'Find vejret' },
    { id: 'da0-m128', type: 'Match', question: 'Vejr: Sne', answer: '❄️', options: ['🌧️', '☀️', '☁️', '❄️'], instruction: 'Find vejret' },
    { id: 'da0-m129', type: 'Match', question: 'Farve: Lilla', answer: '🟣', options: ['🟣', '🟠', '🟤', '⚪'], instruction: 'Find farven' },
    { id: 'da0-m130', type: 'Match', question: 'Farve: Orange', answer: '🟠', options: ['🟣', '🟠', '🟤', '⚪'], instruction: 'Find farven' },
    { id: 'da0-m131', type: 'Match', question: 'Rim: Kat', answer: 'Hat', options: ['Hat', 'Hund', 'Mus', 'Hest'], instruction: 'Find rimordet' },
    { id: 'da0-m132', type: 'Match', question: 'Rim: Mus', answer: 'Hus', options: ['Hus', 'Bus', 'Lus', 'Sus'], instruction: 'Find rimordet' },
    { id: 'da0-m133', type: 'Match', question: 'Rim: Bil', answer: 'Pil', options: ['Pil', 'Mil', 'Sil', 'Vil'], instruction: 'Find rimordet' },
    { id: 'da0-m134', type: 'Match', question: 'Rim: Vand', answer: 'Sand', options: ['Sand', 'Mand', 'Spand', 'Land'], instruction: 'Find rimordet' },
    { id: 'da0-m135', type: 'Match', question: 'Rim: Dør', answer: 'Smør', options: ['Smør', 'Før', 'Gør', 'Tør'], instruction: 'Find rimordet' },
    { id: 'da0-m136', type: 'Match', question: 'Rim: Is', answer: 'Gris', options: ['Gris', 'Pris', 'Ris', 'Vis'], instruction: 'Find rimordet' },
    { id: 'da0-m137', type: 'Match', question: 'Rim: Sol', answer: 'Stol', options: ['Stol', 'Pol', 'Mol', 'Kjole'], instruction: 'Find rimordet' },
    { id: 'da0-m138', type: 'Match', question: 'Rim: Kat', answer: 'Nat', options: ['Nat', 'Skat', 'Mat', 'Pat'], instruction: 'Find rimordet' },
    { id: 'da0-m139', type: 'Match', question: 'Rim: Mand', answer: 'Land', options: ['Land', 'Vand', 'Sand', 'Spand'], instruction: 'Find rimordet' },
    { id: 'da0-m140', type: 'Match', question: 'Rim: Ørn', answer: 'Børn', options: ['Børn', 'Korn', 'Horn', 'Torn'], instruction: 'Find rimordet' },
    { id: 'da0-m141', type: 'Match', question: 'Krop: Hoved', answer: '👤', options: ['👤', '👂', '👃', '👀'], instruction: 'Find kropsdelen' },
    { id: 'da0-m142', type: 'Match', question: 'Krop: Øje', answer: '👀', options: ['👤', '👂', '👃', '👀'], instruction: 'Find kropsdelen' },
    { id: 'da0-m143', type: 'Match', question: 'Krop: Næse', answer: '👃', options: ['👤', '👂', '👃', '👀'], instruction: 'Find kropsdelen' },
    { id: 'da0-m144', type: 'Match', question: 'Krop: Øre', answer: '👂', options: ['👤', '👂', '👃', '👀'], instruction: 'Find kropsdelen' },
    { id: 'da0-m145', type: 'Match', question: 'Krop: Mund', answer: '👄', options: ['👄', '🦷', '👅', '👤'], instruction: 'Find kropsdelen' },
    { id: 'da0-m146', type: 'Match', question: 'Krop: Hånd', answer: '✋', options: ['✋', '🦶', '💪', '🦵'], instruction: 'Find kropsdelen' },
    { id: 'da0-m147', type: 'Match', question: 'Krop: Fod', answer: '🦶', options: ['✋', '🦶', '💪', '🦵'], instruction: 'Find kropsdelen' },
    { id: 'da0-m148', type: 'Match', question: 'Krop: Ben', answer: '🦵', options: ['✋', '🦶', '💪', '🦵'], instruction: 'Find kropsdelen' },
    { id: 'da0-m149', type: 'Match', question: 'Krop: Arm', answer: '💪', options: ['✋', '🦶', '💪', '🦵'], instruction: 'Find kropsdelen' },
    { id: 'da0-m150', type: 'Match', question: 'Tøj: Hat', answer: '👒', options: ['👒', '👕', '👖', '👗'], instruction: 'Find tøjet' },
    { id: 'da0-m151', type: 'Match', question: 'Tøj: Bluse', answer: '👕', options: ['👒', '👕', '👖', '👗'], instruction: 'Find tøjet' },
    { id: 'da0-m152', type: 'Match', question: 'Tøj: Bukser', answer: '👖', options: ['👒', '👕', '👖', '👗'], instruction: 'Find tøjet' },
    { id: 'da0-m153', type: 'Match', question: 'Tøj: Kjole', answer: '👗', options: ['👒', '👕', '👖', '👗'], instruction: 'Find tøjet' },
    { id: 'da0-m154', type: 'Match', question: 'Instrument: Tromme', answer: '🥁', options: ['🥁', '🎸', '🎹', '🎻'], instruction: 'Find instrumentet' },
    { id: 'da0-m155', type: 'Match', question: 'Instrument: Guitar', answer: '🎸', options: ['🥁', '🎸', '🎹', '🎻'], instruction: 'Find instrumentet' },
    { id: 'da0-m156', type: 'Match', question: 'Instrument: Klaver', answer: '🎹', options: ['🥁', '🎸', '🎹', '🎻'], instruction: 'Find instrumentet' },
    { id: 'da0-m157', type: 'Match', question: 'Transport: Bil', answer: '🚗', options: ['🚗', '🚲', '✈️', '🚢'], instruction: 'Find transportmidlet' },
    { id: 'da0-m158', type: 'Match', question: 'Transport: Cykel', answer: '🚲', options: ['🚗', '🚲', '✈️', '🚢'], instruction: 'Find transportmidlet' },
    { id: 'da0-m159', type: 'Match', question: 'Transport: Fly', answer: '✈️', options: ['🚗', '🚲', '✈️', '🚢'], instruction: 'Find transportmidlet' },
    { id: 'da0-m160', type: 'Match', question: 'Transport: Skib', answer: '🚢', options: ['🚗', '🚲', '✈️', '🚢'], instruction: 'Find transportmidlet' },
    { id: 'da0-m161', type: 'Match', question: 'Sport: Bold', answer: '⚽', options: ['⚽', '🏀', '🎾', '🏈'], instruction: 'Find bolden' },
    { id: 'da0-m162', type: 'Match', question: 'Sport: Tennis', answer: '🎾', options: ['⚽', '🏀', '🎾', '🏈'], instruction: 'Find bolden' },
    { id: 'da0-m163', type: 'Match', question: 'Sport: Basket', answer: '🏀', options: ['⚽', '🏀', '🎾', '🏈'], instruction: 'Find bolden' },
    { id: 'da0-m164', type: 'Match', question: 'Husdyr: Kanin', answer: '🐰', options: ['🐰', '🐹', '🐢', '🦜'], instruction: 'Find kæledyret' },
  ],
  1: [
    { id: 'da1-m101', type: 'Match', question: 'Ord: Huset', answer: 'huset', options: ['huset', 'huse', 'husene', 'hus'], instruction: 'Find ordet' },
    { id: 'da1-m102', type: 'Match', question: 'Ord: Bilen', answer: 'bilen', options: ['bilen', 'biler', 'bilerne', 'bil'], instruction: 'Find ordet' },
    { id: 'da1-m103', type: 'Match', question: 'Ord: Katten', answer: 'katten', options: ['katten', 'katte', 'kattene', 'kat'], instruction: 'Find ordet' },
    { id: 'da1-m104', type: 'Match', question: 'Ord: Hunden', answer: 'hunden', options: ['hunden', 'hunde', 'hundene', 'hund'], instruction: 'Find ordet' },
    { id: 'da1-m105', type: 'Match', question: 'Ord: Æblet', answer: 'æblet', options: ['æblet', 'æbler', 'æblerne', 'æble'], instruction: 'Find ordet' },
    { id: 'da1-m106', type: 'Match', question: 'Ord: Pigen', answer: 'pigen', options: ['pigen', 'piger', 'pigerne', 'pige'], instruction: 'Find ordet' },
    { id: 'da1-m107', type: 'Match', question: 'Ord: Drengen', answer: 'drengen', options: ['drengen', 'drenge', 'drengene', 'dreng'], instruction: 'Find ordet' },
    { id: 'da1-m108', type: 'Match', question: 'Ord: Skolen', answer: 'skolen', options: ['skolen', 'skoler', 'skolerne', 'skole'], instruction: 'Find ordet' },
    { id: 'da1-m109', type: 'Match', question: 'Ord: Bordet', answer: 'bordet', options: ['bordet', 'borde', 'bordene', 'bord'], instruction: 'Find ordet' },
    { id: 'da1-m110', type: 'Match', question: 'Ord: Stolen', answer: 'stolen', options: ['stolen', 'stole', 'stolene', 'stol'], instruction: 'Find ordet' },
    { id: 'da1-m111', type: 'Match', question: 'Modsat: Op', answer: 'Ned', options: ['Ned', 'Ind', 'Ud', 'Over'], instruction: 'Find modsætningen' },
    { id: 'da1-m112', type: 'Match', question: 'Modsat: Ind', answer: 'Ud', options: ['Ned', 'Ind', 'Ud', 'Over'], instruction: 'Find modsætningen' },
    { id: 'da1-m113', type: 'Match', question: 'Modsat: Foran', answer: 'Bagved', options: ['Bagved', 'Over', 'Under', 'Ved siden af'], instruction: 'Find modsætningen' },
    { id: 'da1-m114', type: 'Match', question: 'Modsat: Over', answer: 'Under', options: ['Bagved', 'Over', 'Under', 'Ved siden af'], instruction: 'Find modsætningen' },
    { id: 'da1-m115', type: 'Match', question: 'Modsat: Venstre', answer: 'Højre', options: ['Højre', 'Ligeud', 'Tilbage', 'Frem'], instruction: 'Find modsætningen' },
    { id: 'da1-m116', type: 'Match', question: 'Farve: Grå', answer: '🩶', options: ['🩶', '🖤', '🤍', '🤎'], instruction: 'Find farven' },
    { id: 'da1-m117', type: 'Match', question: 'Farve: Brun', answer: '🤎', options: ['🩶', '🖤', '🤍', '🤎'], instruction: 'Find farven' },
    { id: 'da1-m118', type: 'Match', question: 'Farve: Lyserød', answer: '🩷', options: ['🩷', '❤️', '🧡', '💛'], instruction: 'Find farven' },
    { id: 'da1-m119', type: 'Match', question: 'Form: Oval', answer: '🥚', options: ['🥚', '🍪', '🍕', '🍫'], instruction: 'Hvilken form?' },
    { id: 'da1-m120', type: 'Match', question: 'Form: Rektangel', answer: '📱', options: ['📱', '🪙', '📐', '⭐'], instruction: 'Hvilken form?' },
    { id: 'da1-m121', type: 'Match', question: 'Ugedag: Mandag', answer: 'mandag', options: ['mandag', 'tirsdag', 'onsdag', 'torsdag'], instruction: 'Find dagen' },
    { id: 'da1-m122', type: 'Match', question: 'Ugedag: Tirsdag', answer: 'tirsdag', options: ['mandag', 'tirsdag', 'onsdag', 'torsdag'], instruction: 'Find dagen' },
    { id: 'da1-m123', type: 'Match', question: 'Ugedag: Onsdag', answer: 'onsdag', options: ['mandag', 'tirsdag', 'onsdag', 'torsdag'], instruction: 'Find dagen' },
    { id: 'da1-m124', type: 'Match', question: 'Ugedag: Torsdag', answer: 'torsdag', options: ['mandag', 'tirsdag', 'onsdag', 'torsdag'], instruction: 'Find dagen' },
    { id: 'da1-m125', type: 'Match', question: 'Ugedag: Fredag', answer: 'fredag', options: ['fredag', 'lørdag', 'søndag', 'mandag'], instruction: 'Find dagen' },
    { id: 'da1-m126', type: 'Match', question: 'Ugedag: Lørdag', answer: 'lørdag', options: ['fredag', 'lørdag', 'søndag', 'mandag'], instruction: 'Find dagen' },
    { id: 'da1-m127', type: 'Match', question: 'Ugedag: Søndag', answer: 'søndag', options: ['fredag', 'lørdag', 'søndag', 'mandag'], instruction: 'Find dagen' },
    { id: 'da1-m128', type: 'Match', question: 'Måned: Januar', answer: 'januar', options: ['januar', 'februar', 'marts', 'april'], instruction: 'Find måneden' },
    { id: 'da1-m129', type: 'Match', question: 'Måned: Februar', answer: 'februar', options: ['januar', 'februar', 'marts', 'april'], instruction: 'Find måneden' },
    { id: 'da1-m130', type: 'Match', question: 'Måned: Marts', answer: 'marts', options: ['januar', 'februar', 'marts', 'april'], instruction: 'Find måneden' },
    { id: 'da1-m131', type: 'Match', question: 'Stavelser: Bi (🐝)', answer: '1 stavelse', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Tæl stavelser' },
    { id: 'da1-m132', type: 'Match', question: 'Stavelser: Abe (🐒)', answer: '2 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Tæl stavelser' },
    { id: 'da1-m133', type: 'Match', question: 'Stavelser: Elefant (🐘)', answer: '3 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Tæl stavelser' },
    { id: 'da1-m134', type: 'Match', question: 'Stavelser: Sol (☀️)', answer: '1 stavelse', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Tæl stavelser' },
    { id: 'da1-m135', type: 'Match', question: 'Stavelser: Måne (🌙)', answer: '2 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Tæl stavelser' },
    { id: 'da1-m136', type: 'Match', question: 'Rim: Lam', answer: 'Kam', options: ['Kam', 'Ham', 'Dam', 'Stam'], instruction: 'Find rimordet' },
    { id: 'da1-m137', type: 'Match', question: 'Rim: Pil', answer: 'Bil', options: ['Bil', 'Mil', 'Sil', 'Vil'], instruction: 'Find rimordet' },
    { id: 'da1-m138', type: 'Match', question: 'Rim: Tog', answer: 'Bog', options: ['Bog', 'Kog', 'Log', 'Krog'], instruction: 'Find rimordet' },
    { id: 'da1-m139', type: 'Match', question: 'Rim: Sang', answer: 'Tang', options: ['Tang', 'Bang', 'Gang', 'Lang'], instruction: 'Find rimordet' },
    { id: 'da1-m140', type: 'Match', question: 'Rim: Fed', answer: 'Med', options: ['Med', 'Bed', 'Ned', 'Red'], instruction: 'Find rimordet' },
    { id: 'da1-m141', type: 'Match', question: 'Forbogstav: Appelsin', answer: 'A', options: ['A', 'B', 'C', 'D'], instruction: 'Hvad starter ordet med?' },
    { id: 'da1-m142', type: 'Match', question: 'Forbogstav: Banan', answer: 'B', options: ['A', 'B', 'C', 'D'], instruction: 'Hvad starter ordet med?' },
    { id: 'da1-m143', type: 'Match', question: 'Forbogstav: Citron', answer: 'C', options: ['A', 'B', 'C', 'D'], instruction: 'Hvad starter ordet med?' },
    { id: 'da1-m144', type: 'Match', question: 'Forbogstav: Drue', answer: 'D', options: ['A', 'B', 'C', 'D'], instruction: 'Hvad starter ordet med?' },
    { id: 'da1-m145', type: 'Match', question: 'Forbogstav: Elefant', answer: 'E', options: ['E', 'F', 'G', 'H'], instruction: 'Hvad starter ordet med?' },
    { id: 'da1-m146', type: 'Match', question: 'Forbogstav: Fisk', answer: 'F', options: ['E', 'F', 'G', 'H'], instruction: 'Hvad starter ordet med?' },
    { id: 'da1-m147', type: 'Match', question: 'Forbogstav: Giraf', answer: 'G', options: ['E', 'F', 'G', 'H'], instruction: 'Hvad starter ordet med?' },
    { id: 'da1-m148', type: 'Match', question: 'Forbogstav: Hus', answer: 'H', options: ['E', 'F', 'G', 'H'], instruction: 'Hvad starter ordet med?' },
    { id: 'da1-m149', type: 'Match', question: 'Forbogstav: Is', answer: 'I', options: ['I', 'J', 'K', 'L'], instruction: 'Hvad starter ordet med?' },
    { id: 'da1-m150', type: 'Match', question: 'Forbogstav: Jordbær', answer: 'J', options: ['I', 'J', 'K', 'L'], instruction: 'Hvad starter ordet med?' },
  ],
  2: [
    { id: 'da2-m101', type: 'Match', question: 'Ordklasse: Hunden', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-m102', type: 'Match', question: 'Ordklasse: Hopper', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-m103', type: 'Match', question: 'Ordklasse: Smuk', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-m104', type: 'Match', question: 'Ordklasse: Bilen', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-m105', type: 'Match', question: 'Ordklasse: Køber', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-m106', type: 'Match', question: 'Ordklasse: Hurtig', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-m107', type: 'Match', question: 'Ordklasse: Skolen', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-m108', type: 'Match', question: 'Ordklasse: Læser', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-m109', type: 'Match', question: 'Ordklasse: Grøn', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-m110', type: 'Match', question: 'Ordklasse: Pigen', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-m111', type: 'Match', question: 'Bøjning: Spiser', answer: 'Nutid', options: ['Nutid', 'Datid', 'Navneform'], instruction: 'Find tiden' },
    { id: 'da2-m112', type: 'Match', question: 'Bøjning: Spiste', answer: 'Datid', options: ['Nutid', 'Datid', 'Navneform'], instruction: 'Find tiden' },
    { id: 'da2-m113', type: 'Match', question: 'Bøjning: At spise', answer: 'Navneform', options: ['Nutid', 'Datid', 'Navneform'], instruction: 'Find formen' },
    { id: 'da2-m114', type: 'Match', question: 'Bøjning: Løber', answer: 'Nutid', options: ['Nutid', 'Datid', 'Navneform'], instruction: 'Find tiden' },
    { id: 'da2-m115', type: 'Match', question: 'Bøjning: Løb', answer: 'Datid', options: ['Nutid', 'Datid', 'Navneform'], instruction: 'Find tiden' },
    { id: 'da2-m116', type: 'Match', question: 'Bøjning: At løbe', answer: 'Navneform', options: ['Nutid', 'Datid', 'Navneform'], instruction: 'Find formen' },
    { id: 'da2-m117', type: 'Match', question: 'Bøjning: Sov', answer: 'Datid', options: ['Nutid', 'Datid', 'Navneform'], instruction: 'Find tiden' },
    { id: 'da2-m118', type: 'Match', question: 'Bøjning: Sover', answer: 'Nutid', options: ['Nutid', 'Datid', 'Navneform'], instruction: 'Find tiden' },
    { id: 'da2-m119', type: 'Match', question: 'Bøjning: Sang', answer: 'Datid', options: ['Nutid', 'Datid', 'Navneform'], instruction: 'Find tiden' },
    { id: 'da2-m120', type: 'Match', question: 'Bøjning: Synger', answer: 'Nutid', options: ['Nutid', 'Datid', 'Navneform'], instruction: 'Find tiden' },
    { id: 'da2-m121', type: 'Match', question: 'Navneord: En fisk', answer: 'fiskene', options: ['fisken', 'fisk', 'fiskene', 'fiskens'], instruction: 'Bestemt flertal' },
    { id: 'da2-m122', type: 'Match', question: 'Navneord: En fugl', answer: 'fuglene', options: ['fuglen', 'fugle', 'fuglene', 'fuglens'], instruction: 'Bestemt flertal' },
    { id: 'da2-m123', type: 'Match', question: 'Navneord: En sten', answer: 'stenene', options: ['stenen', 'sten', 'stenene', 'stenens'], instruction: 'Bestemt flertal' },
    { id: 'da2-m124', type: 'Match', question: 'Navneord: Et træ', answer: 'træerne', options: ['træet', 'træer', 'træerne', 'træets'], instruction: 'Bestemt flertal' },
    { id: 'da2-m125', type: 'Match', question: 'Navneord: Et hus', answer: 'husene', options: ['huset', 'huse', 'husene', 'husets'], instruction: 'Bestemt flertal' },
    { id: 'da2-m126', type: 'Match', question: 'Sammensat: Skole + gård', answer: 'Skolegård', options: ['Skolegård', 'Skole gård', 'Skole-gård'], instruction: 'Sammensæt ordene' },
    { id: 'da2-m127', type: 'Match', question: 'Sammensat: Vand + kande', answer: 'Vandkande', options: ['Vandkande', 'Vand kande', 'Vand-kande'], instruction: 'Sammensæt ordene' },
    { id: 'da2-m128', type: 'Match', question: 'Sammensat: Mad + pakke', answer: 'Madpakke', options: ['Madpakke', 'Mad pakke', 'Mad-pakke'], instruction: 'Sammensæt ordene' },
    { id: 'da2-m129', type: 'Match', question: 'Sammensat: Sol + skin', answer: 'Solskin', options: ['Solskin', 'Sol skin', 'Sol-skin'], instruction: 'Sammensæt ordene' },
    { id: 'da2-m130', type: 'Match', question: 'Sammensat: Regn + bue', answer: 'Regnbue', options: ['Regnbue', 'Regn bue', 'Regn-bue'], instruction: 'Sammensæt ordene' },
    { id: 'da2-m131', type: 'Match', question: 'Synonym: Lille', answer: 'Små', options: ['Små', 'Stor', 'Høj', 'Bred'], instruction: 'Find synonymet' },
    { id: 'da2-m132', type: 'Match', question: 'Synonym: Glad', answer: 'Fornøjet', options: ['Fornøjet', 'Trist', 'Sur', 'Gal'], instruction: 'Find synonymet' },
    { id: 'da2-m133', type: 'Match', question: 'Synonym: Hurtig', answer: 'Tjep', options: ['Tjep', 'Langsom', 'Stille', 'Lav'], instruction: 'Find synonymet' },
    { id: 'da2-m134', type: 'Match', question: 'Synonym: Pæn', answer: 'Smuk', options: ['Smuk', 'Grim', 'Beskidt', 'Dårlig'], instruction: 'Find synonymet' },
    { id: 'da2-m135', type: 'Match', question: 'Synonym: Ond', answer: 'Slem', options: ['Slem', 'God', 'Sød', 'Venlig'], instruction: 'Find synonymet' },
    { id: 'da2-m136', type: 'Match', question: 'Antonym: Kold', answer: 'Varm', options: ['Varm', 'Våd', 'Tør', 'Lys'], instruction: 'Find modsætningen' },
    { id: 'da2-m137', type: 'Match', question: 'Antonym: Lys', answer: 'Mørk', options: ['Mørk', 'Sort', 'Grå', 'Hvid'], instruction: 'Find modsætningen' },
    { id: 'da2-m138', type: 'Match', question: 'Antonym: Høj', answer: 'Lav', options: ['Lav', 'Lille', 'Kort', 'Smal'], instruction: 'Find modsætningen' },
    { id: 'da2-m139', type: 'Match', question: 'Antonym: Tung', answer: 'Let', options: ['Let', 'Lille', 'Tynd', 'Smal'], instruction: 'Find modsætningen' },
    { id: 'da2-m140', type: 'Match', question: 'Antonym: Tyk', answer: 'Tynd', options: ['Tynd', 'Let', 'Smal', 'Lille'], instruction: 'Find modsætningen' },
    { id: 'da2-m141', type: 'Match', question: 'Morfem: U-held-ig', answer: '3 morfemer', options: ['1 morfem', '2 morfemer', '3 morfemer', '4 morfemer'], instruction: 'Find antal morfemer' },
    { id: 'da2-m142', type: 'Match', question: 'Morfem: Bil-er', answer: '2 morfemer', options: ['1 morfem', '2 morfemer', '3 morfemer', '4 morfemer'], instruction: 'Find antal morfemer' },
    { id: 'da2-m143', type: 'Match', question: 'Morfem: Hus-et', answer: '2 morfemer', options: ['1 morfem', '2 morfemer', '3 morfemer', '4 morfemer'], instruction: 'Find antal morfemer' },
    { id: 'da2-m144', type: 'Match', question: 'Morfem: Løb-er', answer: '2 morfemer', options: ['1 morfem', '2 morfemer', '3 morfemer', '4 morfemer'], instruction: 'Find antal morfemer' },
    { id: 'da2-m145', type: 'Match', question: 'Morfem: Skole-taske', answer: '2 morfemer', options: ['1 morfem', '2 morfemer', '3 morfemer', '4 morfemer'], instruction: 'Find antal morfemer' },
    { id: 'da2-m146', type: 'Match', question: 'Staves med d: Hund', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Er der et stumt d?' },
    { id: 'da2-m147', type: 'Match', question: 'Staves med d: Vand', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Er der et stumt d?' },
    { id: 'da2-m148', type: 'Match', question: 'Staves med d: Mand', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Er der et stumt d?' },
    { id: 'da2-m149', type: 'Match', question: 'Staves med d: Land', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Er der et stumt d?' },
    { id: 'da2-m150', type: 'Match', question: 'Staves med d: Brød', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Er der et stumt d?' },
  ],
};
