/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const ENGELSK_MATCH: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'en0-m1', type: 'Match', question: 'Cat', answer: '🐈', options: ['🐈', '🐕', '🐎', '🐄'], instruction: 'Find the picture' },
    { id: 'en0-m2', type: 'Match', question: 'Sun', answer: '☀️', options: ['🌙', '☀️', '☁️', '🌧️'], instruction: 'Find the picture' },
    { id: 'en0-m3', type: 'Match', question: 'Apple', answer: '🍎', options: ['🍎', '🍐', '🍌', '🥕'], instruction: 'Find the apple' },
    { id: 'en0-m4', type: 'Match', question: 'Mom', answer: 'Mor', options: ['Mor', 'Far', 'Søster', 'Bror'], instruction: 'Translate' },
    { id: 'en0-m5', type: 'Match', question: 'Dad', answer: 'Far', options: ['Mor', 'Far', 'Søster', 'Bror'], instruction: 'Translate' },
    { id: 'en0-m6', type: 'Match', question: 'House', answer: '🏠', options: ['🏠', '🌳', '🌸'], instruction: 'Find the house' },
    { id: 'en0-m7', type: 'Match', question: 'One', answer: '1', options: ['1', '2', '3', '4'], instruction: 'Numbers' },
    { id: 'en0-m8', type: 'Match', question: 'Two', answer: '2', options: ['1', '2', '3', '4'], instruction: 'Numbers' },
    { id: 'en0-m9', type: 'Match', question: 'Three', answer: '3', options: ['1', '2', '3', '4'], instruction: 'Numbers' },
    { id: 'en0-m10', type: 'Match', question: 'Four', answer: '4', options: ['1', '2', '3', '4'], instruction: 'Numbers' },
    { id: 'en0-m11', type: 'Match', question: 'Five', answer: '5', options: ['5', '6', '7', '8'], instruction: 'Numbers' },
    { id: 'en0-m12', type: 'Match', question: 'Six', answer: '6', options: ['5', '6', '7', '8'], instruction: 'Numbers' },
    { id: 'en0-m13', type: 'Match', question: 'Seven', answer: '7', options: ['5', '6', '7', '8'], instruction: 'Numbers' },
    { id: 'en0-m14', type: 'Match', question: 'Eight', answer: '8', options: ['5', '6', '7', '8'], instruction: 'Numbers' },
    { id: 'en0-m15', type: 'Match', question: 'Nine', answer: '9', options: ['9', '10', '11', '12'], instruction: 'Numbers' },
    { id: 'en0-m16', type: 'Match', question: 'Ten', answer: '10', options: ['9', '10', '11', '12'], instruction: 'Numbers' },
    { id: 'en0-m17', type: 'Match', question: 'Ball', answer: '⚽', options: ['⚽', '🏀', '🎾', '🏐'], instruction: 'Find the ball' },
    { id: 'en0-m18', type: 'Match', question: 'Boy', answer: 'Dreng', options: ['Dreng', 'Pige', 'Mand', 'Kvinde'], instruction: 'Translate' },
    { id: 'en0-m19', type: 'Match', question: 'Girl', answer: 'Pige', options: ['Dreng', 'Pige', 'Mand', 'Kvinde'], instruction: 'Translate' },
    { id: 'en0-m20', type: 'Match', question: 'Dog', answer: '🐶', options: ['🐶', '🐱', '🐭', '🐹'], instruction: 'Find the dog' },
    { id: 'en0-m21', type: 'Match', question: 'A', answer: '🍎', options: ['🍎', '🍌', '🍒'], instruction: 'A is for...' },
    { id: 'en0-m22', type: 'Match', question: 'B', answer: '🐻', options: ['🐻', '🐼', '🐨'], instruction: 'B is for...' },
    { id: 'en0-m23', type: 'Match', question: 'C', answer: '🚗', options: ['🚗', '🚲', '🚆'], instruction: 'C is for...' },
    { id: 'en0-m24', type: 'Match', question: 'D', answer: '🐕', options: ['🐕', '🐘', '🦒'], instruction: 'D is for...' },
    { id: 'en0-m25', type: 'Match', question: 'E', answer: '🐘', options: ['🐘', '🦒', '🦓'], instruction: 'E is for...' },
    { id: 'en0-m26', type: 'Match', question: 'F', answer: '🐟', options: ['🐟', '🦆', '🐔'], instruction: 'F is for...' },
    { id: 'en0-m27', type: 'Match', question: 'G', answer: '🦒', options: ['🦒', '🦁', '🐯'], instruction: 'G is for...' },
    { id: 'en0-m28', type: 'Match', question: 'H', answer: '🏠', options: ['🏠', '🌳', '🌸'], instruction: 'H is for...' },
    { id: 'en0-m29', type: 'Match', question: 'I', answer: '🍦', options: ['🍦', '🍭', '🍰'], instruction: 'I is for...' },
    { id: 'en0-m30', type: 'Match', question: 'J', answer: '🍓', options: ['🍓', '🍏', '🍊'], instruction: 'J is for (Jam)?' },
    { id: 'en0-m31', type: 'Match', question: 'Red', answer: '🔴', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Colors' },
    { id: 'en0-m32', type: 'Match', question: 'Blue', answer: '🔵', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Colors' },
    { id: 'en0-m33', type: 'Match', question: 'Green', answer: '🟢', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Colors' },
    { id: 'en0-m34', type: 'Match', question: 'Yellow', answer: '🟡', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Colors' },
    { id: 'en0-m35', type: 'Match', question: 'Black', answer: '⚫', options: ['⚫', '⚪', '🟤', '🟣'], instruction: 'Colors' },
    { id: 'en0-m36', type: 'Match', question: 'White', answer: '⚪', options: ['⚫', '⚪', '🟤', '🟣'], instruction: 'Colors' },
    { id: 'en0-m37', type: 'Match', question: 'M', answer: 'Måne', options: ['Måne', 'Sol', 'Stjerne'], instruction: 'M is for Moon' },
    { id: 'en0-m38', type: 'Match', question: 'S', answer: 'Sol', options: ['Sol', 'Måne', 'Sky'], instruction: 'S is for Sun' },
    { id: 'en0-m39', type: 'Match', question: 'T', answer: 'Træ', options: ['Træ', 'Blomst', 'Busk'], instruction: 'T is for Tree' },
    { id: 'en0-m40', type: 'Match', question: 'W', answer: 'Vand', options: ['Vand', 'Ild', 'Jord'], instruction: 'W is for Water' },
    { id: 'en0-m41', type: 'Match', question: 'Milk', answer: 'Mælk', options: ['Mælk', 'Juice', 'Vand'], instruction: 'Food' },
    { id: 'en0-m42', type: 'Match', question: 'Bread', answer: 'Brød', options: ['Brød', 'Kage', 'Kiks'], instruction: 'Food' },
    { id: 'en0-m43', type: 'Match', question: 'Cheese', answer: 'Ost', options: ['Ost', 'Smør', 'Æg'], instruction: 'Food' },
    { id: 'en0-m44', type: 'Match', question: 'Egg', answer: 'Æg', options: ['Æg', 'Ost', 'Mælk'], instruction: 'Food' },
    { id: 'en0-m45', type: 'Match', question: 'Fish', answer: 'Fisk', options: ['Fisk', 'Kød', 'Kylling'], instruction: 'Food' },
    { id: 'en0-m46', type: 'Match', question: 'Bird', answer: 'Fugl', options: ['Fugl', 'Fisk', 'Mus'], instruction: 'Animals' },
    { id: 'en0-m47', type: 'Match', question: 'Mouse', answer: 'Mus', options: ['Mus', 'Kat', 'Hund'], instruction: 'Animals' },
    { id: 'en0-m48', type: 'Match', question: 'Rabbit', answer: 'Kanin', options: ['Kanin', 'Hare', 'Hamster'], instruction: 'Animals' },
    { id: 'en0-m49', type: 'Match', question: 'Horse', answer: 'Hest', options: ['Hest', 'Ko', 'Gris'], instruction: 'Animals' },
    { id: 'en0-m50', type: 'Match', question: 'Pig', answer: 'Gris', options: ['Gris', 'Får', 'Ged'], instruction: 'Animals' },
  ],
  1: [
    { id: 'en1-m1', type: 'Match', question: 'Hello', answer: 'Hej', options: ['Hej', 'Farvel', 'Tak', 'Ja'], instruction: 'Greetings' },
    { id: 'en1-m2', type: 'Match', question: 'Goodbye', answer: 'Farvel', options: ['Hej', 'Farvel', 'Tak', 'Nej'], instruction: 'Greetings' },
    { id: 'en1-m3', type: 'Match', question: 'Morning', answer: 'Morgen', options: ['Morgen', 'Middag', 'Aften', 'Nat'], instruction: 'Time' },
    { id: 'en1-m4', type: 'Match', question: 'Night', answer: 'Nat', options: ['Morgen', 'Middag', 'Aften', 'Nat'], instruction: 'Time' },
    { id: 'en1-m5', type: 'Match', question: 'Book', answer: 'Bog', options: ['Bog', 'Blyant', 'Taske', 'Bord'], instruction: 'School' },
    { id: 'en1-m6', type: 'Match', question: 'Pencil', answer: 'Blyant', options: ['Bog', 'Blyant', 'Taske', 'Bord'], instruction: 'School' },
    { id: 'en1-m7', type: 'Match', question: 'Chair', answer: 'Stol', options: ['Stol', 'Bord', 'Seng', 'Skab'], instruction: 'Furniture' },
    { id: 'en1-m8', type: 'Match', question: 'Table', answer: 'Bord', options: ['Stol', 'Bord', 'Seng', 'Skab'], instruction: 'Furniture' },
    { id: 'en1-m9', type: 'Match', question: 'Door', answer: 'Dør', options: ['Dør', 'Vindue', 'Tag', 'Gulv'], instruction: 'House' },
    { id: 'en1-m10', type: 'Match', question: 'Window', answer: 'Vindue', options: ['Dør', 'Vindue', 'Tag', 'Gulv'], instruction: 'House' },
    { id: 'en1-m11', type: 'Match', question: 'Big', answer: 'Stor', options: ['Stor', 'Lille', 'Høj', 'Lav'], instruction: 'Opposites' },
    { id: 'en1-m12', type: 'Match', question: 'Small', answer: 'Lille', options: ['Stor', 'Lille', 'Høj', 'Lav'], instruction: 'Opposites' },
    { id: 'en1-m13', type: 'Match', question: 'Happy', answer: 'Glad', options: ['Glad', 'Trist', 'Gal', 'Træt'], instruction: 'Feelings' },
    { id: 'en1-m14', type: 'Match', question: 'Sad', answer: 'Trist', options: ['Glad', 'Trist', 'Gal', 'Træt'], instruction: 'Feelings' },
    { id: 'en1-m15', type: 'Match', question: 'Hot', answer: 'Varm', options: ['Varm', 'Kold', 'Våd', 'Tør'], instruction: 'Environment' },
    { id: 'en1-m16', type: 'Match', question: 'Cold', answer: 'Kold', options: ['Varm', 'Kold', 'Våd', 'Tør'], instruction: 'Environment' },
    { id: 'en1-m17', type: 'Match', question: 'Water', answer: 'Vand', options: ['Vand', 'Ild', 'Luft', 'Jord'], instruction: 'Nature' },
    { id: 'en1-m18', type: 'Match', question: 'Fire', answer: 'Ild', options: ['Vand', 'Ild', 'Luft', 'Jord'], instruction: 'Nature' },
    { id: 'en1-m19', type: 'Match', question: 'Sun', answer: 'Sol', options: ['Sol', 'Måne', 'Stjerne', 'Sky'], instruction: 'Nature' },
    { id: 'en1-m20', type: 'Match', question: 'Moon', answer: 'Måne', options: ['Sol', 'Måne', 'Stjerne', 'Sky'], instruction: 'Nature' },
    { id: 'en1-m21', type: 'Match', question: 'Sunday', answer: 'Søndag', options: ['Mandag', 'Fredag', 'Søndag'], instruction: 'Days' },
    { id: 'en1-m22', type: 'Match', question: 'Monday', answer: 'Mandag', options: ['Mandag', 'Fredag', 'Søndag'], instruction: 'Days' },
    { id: 'en1-m23', type: 'Match', question: 'Tuesday', answer: 'Tirsdag', options: ['Tirsdag', 'Onsdag', 'Torsdag'], instruction: 'Days' },
    { id: 'en1-m24', type: 'Match', question: 'Wednesday', answer: 'Onsdag', options: ['Tirsdag', 'Onsdag', 'Torsdag'], instruction: 'Days' },
    { id: 'en1-m25', type: 'Match', question: 'Thursday', answer: 'Torsdag', options: ['Tirsdag', 'Onsdag', 'Torsdag'], instruction: 'Days' },
    { id: 'en1-m26', type: 'Match', question: 'Friday', answer: 'Fredag', options: ['Mandag', 'Fredag', 'Lørdag'], instruction: 'Days' },
    { id: 'en1-m27', type: 'Match', question: 'Saturday', answer: 'Lørdag', options: ['Mandag', 'Fredag', 'Lørdag'], instruction: 'Days' },
    { id: 'en1-m28', type: 'Match', question: 'Eleven', answer: '11', options: ['11', '12', '13'], instruction: 'Numbers' },
    { id: 'en1-m29', type: 'Match', question: 'Twelve', answer: '12', options: ['11', '12', '13'], instruction: 'Numbers' },
    { id: 'en1-m30', type: 'Match', question: 'Thirteen', answer: '13', options: ['11', '12', '13'], instruction: 'Numbers' },
    { id: 'en1-m31', type: 'Match', question: 'Fourteen', answer: '14', options: ['14', '15', '16'], instruction: 'Numbers' },
    { id: 'en1-m32', type: 'Match', question: 'Fifteen', answer: '15', options: ['14', '15', '16'], instruction: 'Numbers' },
    { id: 'en1-m33', type: 'Match', question: 'Sixteen', answer: '16', options: ['14', '15', '16'], instruction: 'Numbers' },
    { id: 'en1-m34', type: 'Match', question: 'Seventeen', answer: '17', options: ['17', '18', '19'], instruction: 'Numbers' },
    { id: 'en1-m35', type: 'Match', question: 'Eighteen', answer: '18', options: ['17', '18', '19'], instruction: 'Numbers' },
    { id: 'en1-m36', type: 'Match', question: 'Nineteen', answer: '19', options: ['17', '18', '19'], instruction: 'Numbers' },
    { id: 'en1-m37', type: 'Match', question: 'Twenty', answer: '20', options: ['10', '20', '30'], instruction: 'Numbers' },
    { id: 'en1-m38', type: 'Match', question: 'Blueberry', answer: 'Blåbær', options: ['Blåbær', 'Jordbær', 'Hindbær'], instruction: 'Berries' },
    { id: 'en1-m39', type: 'Match', question: 'Strawberry', answer: 'Jordbær', options: ['Blåbær', 'Jordbær', 'Hindbær'], instruction: 'Berries' },
    { id: 'en1-m40', type: 'Match', question: 'Raspberry', answer: 'Hindbær', options: ['Blåbær', 'Jordbær', 'Hindbær'], instruction: 'Berries' },
    { id: 'en1-m41', type: 'Match', question: 'Hand', answer: 'Hånd', options: ['Hånd', 'Fod', 'Arm'], instruction: 'Body' },
    { id: 'en1-m42', type: 'Match', question: 'Foot', answer: 'Fod', options: ['Hånd', 'Fod', 'Arm'], instruction: 'Body' },
    { id: 'en1-m43', type: 'Match', question: 'Arm', answer: 'Arm', options: ['Hånd', 'Fod', 'Arm'], instruction: 'Body' },
    { id: 'en1-m44', type: 'Match', question: 'Leg', answer: 'Ben', options: ['Ben', 'Knæ', 'Fod'], instruction: 'Body' },
    { id: 'en1-m45', type: 'Match', question: 'Head', answer: 'Hoved', options: ['Hoved', 'Hals', 'Skulder'], instruction: 'Body' },
    { id: 'en1-m46', type: 'Match', question: 'Eye', answer: 'Øje', options: ['Øje', 'Øre', 'Næse'], instruction: 'Face' },
    { id: 'en1-m47', type: 'Match', question: 'Ear', answer: 'Øre', options: ['Øje', 'Øre', 'Næse'], instruction: 'Face' },
    { id: 'en1-m48', type: 'Match', question: 'Nose', answer: 'Næse', options: ['Øje', 'Øre', 'Næse'], instruction: 'Face' },
    { id: 'en1-m49', type: 'Match', question: 'Mouth', answer: 'Mund', options: ['Mund', 'Tand', 'Tunge'], instruction: 'Face' },
    { id: 'en1-m50', type: 'Match', question: 'Hair', answer: 'Hår', options: ['Hår', 'Hud', 'Hoved'], instruction: 'Face' },
  ],
  2: [
    { id: 'en2-m1', type: 'Match', question: 'Home', answer: 'Hjem', options: ['Skole', 'Hjem', 'Have', 'Vej'], instruction: 'Oversæt ordet' },
    { id: 'en2-m2', type: 'Match', question: 'School', answer: 'Skole', options: ['Skole', 'Kirke', 'Butik'], instruction: 'Places' },
    { id: 'en2-m3', type: 'Match', question: 'Garden', answer: 'Have', options: ['Have', 'Park', 'Skov'], instruction: 'Places' },
    { id: 'en2-m4', type: 'Match', question: 'Kitchen', answer: 'Køkken', options: ['Køkken', 'Stue', 'Bad'], instruction: 'Rooms' },
    { id: 'en2-m5', type: 'Match', question: 'Bedroom', answer: 'Soveværelse', options: ['Soveværelse', 'Stue', 'Bad'], instruction: 'Rooms' },
    { id: 'en2-m6', type: 'Match', question: 'Bathroom', answer: 'Badeværelse', options: ['Soveværelse', 'Stue', 'Bad'], instruction: 'Rooms' },
    { id: 'en2-m7', type: 'Match', question: 'Living room', answer: 'Stue', options: ['Soveværelse', 'Stue', 'Bad'], instruction: 'Rooms' },
    { id: 'en2-m8', type: 'Match', question: 'Spring', answer: 'Forår', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Seasons' },
    { id: 'en2-m9', type: 'Match', question: 'Summer', answer: 'Sommer', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Seasons' },
    { id: 'en2-m10', type: 'Match', question: 'Autumn', answer: 'Efterår', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Seasons' },
    { id: 'en2-m11', type: 'Match', question: 'Winter', answer: 'Vinter', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Seasons' },
    { id: 'en2-m12', type: 'Match', question: 'January', answer: 'Januar', options: ['Januar', 'Februar', 'Marts'], instruction: 'Months' },
    { id: 'en2-m13', type: 'Match', question: 'February', answer: 'Februar', options: ['Januar', 'Februar', 'Marts'], instruction: 'Months' },
    { id: 'en2-m14', type: 'Match', question: 'March', answer: 'Marts', options: ['Januar', 'Februar', 'Marts'], instruction: 'Months' },
    { id: 'en2-m15', type: 'Match', question: 'April', answer: 'April', options: ['April', 'Maj', 'Juni'], instruction: 'Months' },
    { id: 'en2-m16', type: 'Match', question: 'May', answer: 'Maj', options: ['April', 'Maj', 'Juni'], instruction: 'Months' },
    { id: 'en2-m17', type: 'Match', question: 'June', answer: 'Juni', options: ['April', 'Maj', 'Juni'], instruction: 'Months' },
    { id: 'en2-m18', type: 'Match', question: 'July', answer: 'Juli', options: ['July', 'August', 'September'], instruction: 'Months' },
    { id: 'en2-m19', type: 'Match', question: 'August', answer: 'August', options: ['July', 'August', 'September'], instruction: 'Months' },
    { id: 'en2-m20', type: 'Match', question: 'September', answer: 'September', options: ['July', 'August', 'September'], instruction: 'Months' },
    { id: 'en2-m21', type: 'Match', question: 'October', answer: 'Oktober', options: ['Oktober', 'November', 'December'], instruction: 'Months' },
    { id: 'en2-m22', type: 'Match', question: 'November', answer: 'November', options: ['Oktober', 'November', 'December'], instruction: 'Months' },
    { id: 'en2-m23', type: 'Match', question: 'December', answer: 'December', options: ['Oktober', 'November', 'December'], instruction: 'Months' },
    { id: 'en2-m24', type: 'Match', question: 'Rain', answer: 'Regn', options: ['Regn', 'Sne', 'Sol'], instruction: 'Weather' },
    { id: 'en2-m25', type: 'Match', question: 'Snow', answer: 'Sne', options: ['Regn', 'Sne', 'Sol'], instruction: 'Weather' },
    { id: 'en2-m26', type: 'Match', question: 'Wind', answer: 'Vind', options: ['Vind', 'Sky', 'Storm'], instruction: 'Weather' },
    { id: 'en2-m27', type: 'Match', question: 'Cloud', answer: 'Sky', options: ['Vind', 'Sky', 'Storm'], instruction: 'Weather' },
    { id: 'en2-m28', type: 'Match', question: 'Fast', answer: 'Hurtig', options: ['Hurtig', 'Langsom', 'Høj'], instruction: 'Adjectives' },
    { id: 'en2-m29', type: 'Match', question: 'Slow', answer: 'Langsom', options: ['Hurtig', 'Langsom', 'Høj'], instruction: 'Adjectives' },
    { id: 'en2-m30', type: 'Match', question: 'Tall', answer: 'Høj', options: ['Høj', 'Lav', 'Stor'], instruction: 'Adjectives' },
    { id: 'en2-m31', type: 'Match', question: 'Short', answer: 'Lav', options: ['Høj', 'Lav', 'Kort'], instruction: 'Adjectives' },
    { id: 'en2-m32', type: 'Match', question: 'Old', answer: 'Gammel', options: ['Gammel', 'Ung', 'Ny'], instruction: 'Adjectives' },
    { id: 'en2-m33', type: 'Match', question: 'Young', answer: 'Ung', options: ['Gammel', 'Ung', 'Ny'], instruction: 'Adjectives' },
    { id: 'en2-m34', type: 'Match', question: 'Rich', answer: 'Rig', options: ['Rig', 'Fattig', 'Glad'], instruction: 'Adjectives' },
    { id: 'en2-m35', type: 'Match', question: 'Poor', answer: 'Fattig', options: ['Rig', 'Fattig', 'Glad'], instruction: 'Adjectives' },
    { id: 'en2-m36', type: 'Match', question: 'Run', answer: 'Løbe', options: ['Løbe', 'Gå', 'Hoppe'], instruction: 'Verbs' },
    { id: 'en2-m37', type: 'Match', question: 'Jump', answer: 'Hoppe', options: ['Løbe', 'Gå', 'Hoppe'], instruction: 'Verbs' },
    { id: 'en2-m38', type: 'Match', question: 'Walk', answer: 'Gå', options: ['Løbe', 'Gå', 'Hoppe'], instruction: 'Verbs' },
    { id: 'en2-m39', type: 'Match', question: 'Eat', answer: 'Spise', options: ['Spise', 'Drikke', 'Sove'], instruction: 'Verbs' },
    { id: 'en2-m40', type: 'Match', question: 'Drink', answer: 'Drikke', options: ['Spise', 'Drikke', 'Sove'], instruction: 'Verbs' },
    { id: 'en2-m41', type: 'Match', question: 'Sleep', answer: 'Sove', options: ['Spise', 'Drikke', 'Sove'], instruction: 'Verbs' },
    { id: 'en2-m42', type: 'Match', question: 'Read', answer: 'Læse', options: ['Læse', 'Skrive', 'Tegne'], instruction: 'Verbs' },
    { id: 'en2-m43', type: 'Match', question: 'Write', answer: 'Skrive', options: ['Læse', 'Skrive', 'Tegne'], instruction: 'Verbs' },
    { id: 'en2-m44', type: 'Match', question: 'Draw', answer: 'Tegne', options: ['Læse', 'Skrive', 'Tegne'], instruction: 'Verbs' },
    { id: 'en2-m45', type: 'Match', question: 'Lion', answer: 'Løve', options: ['Løve', 'Tiger', 'Bjørn'], instruction: 'Wild animals' },
    { id: 'en2-m46', type: 'Match', question: 'Tiger', answer: 'Tiger', options: ['Løve', 'Tiger', 'Bjørn'], instruction: 'Wild animals' },
    { id: 'en2-m47', type: 'Match', question: 'Bear', answer: 'Bjørn', options: ['Løve', 'Tiger', 'Bjørn'], instruction: 'Wild animals' },
    { id: 'en2-m48', type: 'Match', question: 'Monkey', answer: 'Abe', options: ['Abe', 'Elefant', 'Giraf'], instruction: 'Wild animals' },
    { id: 'en2-m49', type: 'Match', question: 'Elephant', answer: 'Elefant', options: ['Abe', 'Elefant', 'Giraf'], instruction: 'Wild animals' },
    { id: 'en2-m50', type: 'Match', question: 'Giraffe', answer: 'Giraf', options: ['Abe', 'Elefant', 'Giraf'], instruction: 'Wild animals' },
  ],
  3: [
    { id: 'en3-m1', type: 'Match', question: 'Bus', answer: '🚌', options: ['🚗', '🚌', '🚆', '🚲'], instruction: 'Transportation' },
    { id: 'en3-m2', type: 'Match', question: 'Australia', answer: 'Canberra', options: ['Sydney', 'Canberra', 'Melbourne'], instruction: 'Capitals' },
    { id: 'en3-m3', type: 'Match', question: 'Tomato', answer: 'Tomat', options: ['Tomat', 'Agurk', 'Kartoffel'], instruction: 'Food' },
    { id: 'en3-m4', type: 'Match', question: 'Potato', answer: 'Kartoffel', options: ['Tomat', 'Agurk', 'Kartoffel'], instruction: 'Food' },
    { id: 'en3-m5', type: 'Match', question: 'Bread', answer: 'Brød', options: ['Brød', 'Mælk', 'Ost'], instruction: 'Food' },
    { id: 'en3-m6', type: 'Match', question: 'Cheese', answer: 'Ost', options: ['Brød', 'Mælk', 'Ost'], instruction: 'Food' },
    { id: 'en3-m7', type: 'Match', question: 'Shopping', answer: 'Indkøb', options: ['Indkøb', 'Arbejde', 'Skole'], instruction: 'Activity' },
    { id: 'en3-m8', type: 'Match', question: 'Money', answer: 'Penge', options: ['Penge', 'Kort', 'Taske'], instruction: 'Shopping' },
    { id: 'en3-m9', type: 'Match', question: 'Price', answer: 'Pris', options: ['Pris', 'Farve', 'Navn'], instruction: 'Shopping' },
    { id: 'en3-m10', type: 'Match', question: 'Store', answer: 'Butik', options: ['Butik', 'Hus', 'Vej'], instruction: 'Shopping' },
    { id: 'en3-m11', type: 'Match', question: 'Train', answer: '🚆', options: ['🚆', '🚲', '🚗'], instruction: 'Find the picture' },
    { id: 'en3-m12', type: 'Match', question: 'Plane', answer: '✈️', options: ['✈️', '🚢', '🚆'], instruction: 'Find the picture' },
    { id: 'en3-m13', type: 'Match', question: 'Ship', answer: '🚢', options: ['✈️', '🚢', '🚆'], instruction: 'Find the picture' },
    { id: 'en3-m14', type: 'Match', question: 'Doctor', answer: 'Læge', options: ['Læge', 'Lærer', 'Politi'], instruction: 'Translate' },
    { id: 'en3-m15', type: 'Match', question: 'Teacher', answer: 'Lærer', options: ['Læge', 'Lærer', 'Politi'], instruction: 'Translate' },
    { id: 'en3-m16', type: 'Match', question: 'Police', answer: 'Politi', options: ['Læge', 'Lærer', 'Politi'], instruction: 'Translate' },
    { id: 'en3-m17', type: 'Match', question: 'Milk', answer: 'Mælk', options: ['Mælk', 'Vand', 'Juice'], instruction: 'Translate' },
    { id: 'en3-m18', type: 'Match', question: 'Water', answer: 'Vand', options: ['Mælk', 'Vand', 'Juice'], instruction: 'Translate' },
    { id: 'en3-m19', type: 'Match', question: 'Juice', answer: 'Juice', options: ['Mælk', 'Vand', 'Juice'], instruction: 'Translate' },
    { id: 'en3-m20', type: 'Match', question: 'Carrot', answer: 'Gulerod', options: ['Gulerod', 'Kartoffel', 'Tomat'], instruction: 'Vegetables' },
    { id: 'en3-m21', type: 'Match', question: 'Elephant', answer: '🐘', options: ['🐘', '🦒', '🦁'], instruction: 'Find the animal' },
    { id: 'en3-m22', type: 'Match', question: 'Giraffe', answer: '🦒', options: ['🐘', '🦒', '🦁'], instruction: 'Find the animal' },
    { id: 'en3-m23', type: 'Match', question: 'Lion', answer: '🦁', options: ['🐘', '🦒', '🦁'], instruction: 'Find the animal' },
    { id: 'en3-m24', type: 'Match', question: 'Monkey', answer: '🐒', options: ['🐒', '🐍', '🐸'], instruction: 'Find the animal' },
    { id: 'en3-m25', type: 'Match', question: 'Snake', answer: '🐍', options: ['🐒', '🐍', '🐸'], instruction: 'Find the animal' },
    { id: 'en3-m26', type: 'Match', question: 'Sun', answer: 'Sol', options: ['Sol', 'Måne', 'Stjerne'], instruction: 'Nature' },
    { id: 'en3-m27', type: 'Match', question: 'Moon', answer: 'Måne', options: ['Sol', 'Måne', 'Stjerne'], instruction: 'Nature' },
    { id: 'en3-m28', type: 'Match', question: 'Star', answer: 'Stjerne', options: ['Sol', 'Måne', 'Stjerne'], instruction: 'Nature' },
    { id: 'en3-m29', type: 'Match', question: 'Sky', answer: 'Himmel', options: ['Himmel', 'Jord', 'Hav'], instruction: 'Nature' },
    { id: 'en3-m30', type: 'Match', question: 'Rain', answer: 'Regn', options: ['Regn', 'Sne', 'Sol'], instruction: 'Weather' },
    { id: 'en3-m31', type: 'Match', question: 'Snow', answer: 'Sne', options: ['Regn', 'Sne', 'Sol'], instruction: 'Weather' },
    { id: 'en3-m32', type: 'Match', question: 'Hot', answer: 'Varm', options: ['Varm', 'Kold', 'Våd'], instruction: 'Weather' },
    { id: 'en3-m33', type: 'Match', question: 'Cold', answer: 'Kold', options: ['Varm', 'Kold', 'Våd'], instruction: 'Weather' },
    { id: 'en3-m34', type: 'Match', question: 'Breakfast', answer: 'Morgenmad', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Meals' },
    { id: 'en3-m35', type: 'Match', question: 'Lunch', answer: 'Frokost', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Meals' },
    { id: 'en3-m36', type: 'Match', question: 'Dinner', answer: 'Aftensmad', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Meals' },
    { id: 'en3-m37', type: 'Match', question: 'I see', answer: 'Jeg ser', options: ['Jeg ser', 'Du ser', 'Han ser'], instruction: 'Verbs' },
    { id: 'en3-m38', type: 'Match', question: 'You see', answer: 'Du ser', options: ['Jeg ser', 'Du ser', 'Han ser'], instruction: 'Verbs' },
    { id: 'en3-m39', type: 'Match', question: 'He sees', answer: 'Han ser', options: ['Jeg ser', 'Du ser', 'Han ser'], instruction: 'Verbs' },
    { id: 'en3-m40', type: 'Match', question: 'She sees', answer: 'Hun ser', options: ['Jeg ser', 'Du ser', 'Hun ser'], instruction: 'Verbs' },
    { id: 'en3-m41', type: 'Match', question: 'It sees', answer: 'Det ser', options: ['Jeg ser', 'Du ser', 'Det ser'], instruction: 'Verbs' },
    { id: 'en3-m42', type: 'Match', question: 'We see', answer: 'Vi ser', options: ['Vi ser', 'De ser', 'I ser'], instruction: 'Verbs' },
    { id: 'en3-m43', type: 'Match', question: 'They see', answer: 'De ser', options: ['Vi ser', 'De ser', 'I ser'], instruction: 'Verbs' },
    { id: 'en3-m44', type: 'Match', question: 'Small', answer: 'Little', options: ['Little', 'Big', 'Tall'], instruction: 'Synonyms' },
    { id: 'en3-m45', type: 'Match', question: 'Large', answer: 'Big', options: ['Little', 'Big', 'Short'], instruction: 'Synonyms' },
    { id: 'en3-m46', type: 'Match', question: 'Happy', answer: 'Glad', options: ['Glad', 'Trist', 'Syg'], instruction: 'Translate' },
    { id: 'en3-m47', type: 'Match', question: 'Sad', answer: 'Trist', options: ['Glad', 'Trist', 'Syg'], instruction: 'Translate' },
    { id: 'en3-m48', type: 'Match', question: 'Angry', answer: 'Vred', options: ['Vred', 'Glad', 'Træt'], instruction: 'Translate' },
    { id: 'en3-m49', type: 'Match', question: 'Tired', answer: 'Træt', options: ['Vred', 'Glad', 'Træt'], instruction: 'Translate' },
    { id: 'en3-m50', type: 'Match', question: 'Sick', answer: 'Syg', options: ['Vred', 'Glad', 'Syg'], instruction: 'Translate' },
    { id: 'en3-m51', type: 'Match', question: 'Hungry', answer: 'Sulten', options: ['Sulten', 'Tørstig', 'Mæt'], instruction: 'Translate' },
  ],
  4: [
    { id: 'en4-m1', type: 'Match', question: 'Cowboy', answer: 'Hest', options: ['Hest', 'Bil', 'Cykel'], instruction: 'Western theme' },
    { id: 'en4-m2', type: 'Match', question: 'Spider-Man', answer: 'Superhero', options: ['Superhero', 'Villian', 'Animal'], instruction: 'Heroes' },
    { id: 'en4-m3', type: 'Match', question: 'Batman', answer: 'Gotham', options: ['Gotham', 'London', 'New York'], instruction: 'Heroes' },
    { id: 'en4-m4', type: 'Match', question: 'Hero', answer: 'Helt', options: ['Helt', 'Skurk', 'Ven'], instruction: 'Translation' },
    { id: 'en4-m5', type: 'Match', question: 'Villain', answer: 'Skurk', options: ['Helt', 'Skurk', 'Ven'], instruction: 'Translation' },
    { id: 'en4-m6', type: 'Match', question: 'Shoes', answer: 'Sko', options: ['Sko', 'Sokker', 'Bukser'], instruction: 'Clothing' },
    { id: 'en4-m7', type: 'Match', question: 'Trousers', answer: 'Bukser', options: ['Sko', 'Sokker', 'Bukser'], instruction: 'Clothing' },
    { id: 'en4-m8', type: 'Match', question: 'Shirt', answer: 'Skjorte', options: ['Sko', 'Skjorte', 'Hat'], instruction: 'Clothing' },
    { id: 'en4-m9', type: 'Match', question: 'Dress', answer: 'Kjole', options: ['Kjole', 'Skjorte', 'Hat'], instruction: 'Clothing' },
    { id: 'en4-m10', type: 'Match', question: 'Hat', answer: 'Hat', options: ['Kjole', 'Skjorte', 'Hat'], instruction: 'Clothing' },
    { id: 'en4-m11', type: 'Match', question: 'Always', answer: 'Altid', options: ['Altid', 'Aldrig', 'Ofte'], instruction: 'Frequency' },
    { id: 'en4-m12', type: 'Match', question: 'Never', answer: 'Aldrig', options: ['Altid', 'Aldrig', 'Ofte'], instruction: 'Frequency' },
    { id: 'en4-m13', type: 'Match', question: 'Often', answer: 'Ofte', options: ['Altid', 'Aldrig', 'Ofte'], instruction: 'Frequency' },
    { id: 'en4-m14', type: 'Match', question: 'Sometimes', answer: 'Nogle gange', options: ['Nogle gange', 'Altid', 'Aldrig'], instruction: 'Frequency' },
    { id: 'en4-m15', type: 'Match', question: 'Usually', answer: 'Sædvanligvis', options: ['Sædvanligvis', 'Måske', 'Aldrig'], instruction: 'Frequency' },
    { id: 'en4-m16', type: 'Match', question: 'I was', answer: 'Jeg var', options: ['Jeg var', 'Jeg er', 'Jeg bliver'], instruction: 'Past tense' },
    { id: 'en4-m17', type: 'Match', question: 'You were', answer: 'Du var', options: ['Du var', 'Du er', 'Du bliver'], instruction: 'Past tense' },
    { id: 'en4-m18', type: 'Match', question: 'He was', answer: 'Han var', options: ['Han var', 'Han er', 'Han bliver'], instruction: 'Past tense' },
    { id: 'en4-m19', type: 'Match', question: 'She was', answer: 'Hun var', options: ['Hun var', 'Hun er', 'Hun bliver'], instruction: 'Past tense' },
    { id: 'en4-m20', type: 'Match', question: 'It was', answer: 'Det var', options: ['Det var', 'Det er', 'Det bliver'], instruction: 'Past tense' },
    { id: 'en4-m21', type: 'Match', question: 'We were', answer: 'Vi var', options: ['Vi var', 'De var', 'I var'], instruction: 'Past tense' },
    { id: 'en4-m22', type: 'Match', question: 'They were', answer: 'De var', options: ['Vi var', 'De var', 'I var'], instruction: 'Past tense' },
    { id: 'en4-m23', type: 'Match', question: 'Think', answer: 'Tænke', options: ['Tænke', 'Tænkte', 'Tænkt'], instruction: 'Verb forms' },
    { id: 'en4-m24', type: 'Match', question: 'Thought', answer: 'Tænkte', options: ['Tænke', 'Tænkte', 'Tænkt'], instruction: 'Verb forms' },
    { id: 'en4-m25', type: 'Match', question: 'Buy', answer: 'Købe', options: ['Købe', 'Købte', 'Købt'], instruction: 'Verb forms' },
    { id: 'en4-m26', type: 'Match', question: 'Bought', answer: 'Købte', options: ['Købe', 'Købte', 'Købt'], instruction: 'Verb forms' },
    { id: 'en4-m27', type: 'Match', question: 'Speak', answer: 'Tale', options: ['Tale', 'Talte', 'Talt'], instruction: 'Verb forms' },
    { id: 'en4-m28', type: 'Match', question: 'Spoke', answer: 'Talte', options: ['Tale', 'Talte', 'Talt'], instruction: 'Verb forms' },
    { id: 'en4-m29', type: 'Match', question: 'Winter', answer: 'Vinter', options: ['Forår', 'Sommer', 'Vinter'], instruction: 'Seasons' },
    { id: 'en4-m30', type: 'Match', question: 'Spring', answer: 'Forår', options: ['Forår', 'Sommer', 'Vinter'], instruction: 'Seasons' },
    { id: 'en4-m31', type: 'Match', question: 'Summer', answer: 'Sommer', options: ['Forår', 'Sommer', 'Vinter'], instruction: 'Seasons' },
    { id: 'en4-m32', type: 'Match', question: 'Autumn', answer: 'Efterår', options: ['Efterår', 'Sommer', 'Vinter'], instruction: 'Seasons' },
    { id: 'en4-m33', type: 'Match', question: 'Rainy', answer: 'Regnfuldt', options: ['Regnfuldt', 'Solrigt', 'Snefyldt'], instruction: 'Weather' },
    { id: 'en4-m34', type: 'Match', question: 'Sunny', answer: 'Solrigt', options: ['Regnfuldt', 'Solrigt', 'Snefyldt'], instruction: 'Weather' },
    { id: 'en4-m35', type: 'Match', question: 'Snowy', answer: 'Snefyldt', options: ['Regnfuldt', 'Solrigt', 'Snefyldt'], instruction: 'Weather' },
    { id: 'en4-m36', type: 'Match', question: 'Cloudy', answer: 'Skyet', options: ['Skyet', 'Blæsende', 'Klart'], instruction: 'Weather' },
    { id: 'en4-m37', type: 'Match', question: 'Windy', answer: 'Blæsende', options: ['Skyet', 'Blæsende', 'Klart'], instruction: 'Weather' },
    { id: 'en4-m38', type: 'Match', question: 'Mountain', answer: 'Bjerg', options: ['Bjerg', 'Bakke', 'Dal'], instruction: 'Geography' },
    { id: 'en4-m39', type: 'Match', question: 'River', answer: 'Flod', options: ['Flod', 'Sø', 'Hav'], instruction: 'Geography' },
    { id: 'en4-m40', type: 'Match', question: 'Lake', answer: 'Sø', options: ['Flod', 'Sø', 'Hav'], instruction: 'Geography' },
    { id: 'en4-m41', type: 'Match', question: 'Island', answer: 'Ø', options: ['Ø', 'Land', 'By'], instruction: 'Geography' },
    { id: 'en4-m42', type: 'Match', question: 'Forest', answer: 'Skov', options: ['Skov', 'Park', 'Have'], instruction: 'Nature' },
    { id: 'en4-m43', type: 'Match', question: 'Beach', answer: 'Strand', options: ['Strand', 'Bjerg', 'By'], instruction: 'Nature' },
    { id: 'en4-m44', type: 'Match', question: 'Beautiful', answer: 'Smuk', options: ['Smuk', 'Grim', 'Lille'], instruction: 'Adjectives' },
    { id: 'en4-m45', type: 'Match', question: 'Strong', answer: 'Stærk', options: ['Stærk', 'Svag', 'Hurtig'], instruction: 'Adjectives' },
    { id: 'en4-m46', type: 'Match', question: 'Fast', answer: 'Hurtig', options: ['Hurtig', 'Langsom', 'Stille'], instruction: 'Adjectives' },
    { id: 'en4-m47', type: 'Match', question: 'Quiet', answer: 'Stille', options: ['Stille', 'Larmende', 'Hurtig'], instruction: 'Adjectives' },
    { id: 'en4-m48', type: 'Match', question: 'Rich', answer: 'Rig', options: ['Rig', 'Fattig', 'Glad'], instruction: 'Adjectives' },
    { id: 'en4-m49', type: 'Match', question: 'Poor', answer: 'Fattig', options: ['Rig', 'Fattig', 'Glad'], instruction: 'Adjectives' },
    { id: 'en4-m50', type: 'Match', question: 'Important', answer: 'Vigtig', options: ['Vigtig', 'Sjov', 'Kedelig'], instruction: 'Adjectives' },
    { id: 'en4-m51', type: 'Match', question: 'Dangerous', answer: 'Farlig', options: ['Farlig', 'Sikker', 'Nem'], instruction: 'Adjectives' },
  ],
  5: [
    { id: 'en5-m1', type: 'Match', question: 'London Eye', answer: 'Ferris wheel', options: ['Ferris wheel', 'Tower', 'Bridge'], instruction: 'London' },
    { id: 'en5-m2', type: 'Match', question: 'Big Ben', answer: 'Clock', options: ['Clock', 'River', 'King'], instruction: 'London' },
    { id: 'en5-m3', type: 'Match', question: 'Tower Bridge', answer: 'Bridge', options: ['Bridge', 'Tunnel', 'Road'], instruction: 'London' },
    { id: 'en5-m4', type: 'Match', question: 'Thanksgiving', answer: 'Turkey', options: ['Turkey', 'Chicken', 'Fish'], instruction: 'Traditions' },
    { id: 'en5-m5', type: 'Match', question: 'Formula 1', answer: 'Racing', options: ['Racing', 'Cooking', 'Dancing'], instruction: 'Sports' },
    { id: 'en5-m6', type: 'Match', question: 'Capital', answer: 'Hovedstad', options: ['Hovedstad', 'By', 'Land'], instruction: 'Vocabulary' },
    { id: 'en5-m7', type: 'Match', question: 'Famous', answer: 'Berømt', options: ['Berømt', 'Ukendt', 'Gammel'], instruction: 'Vocabulary' },
    { id: 'en5-m8', type: 'Match', question: 'River', answer: 'Flod', options: ['Flod', 'Sø', 'Hav'], instruction: 'Geography' },
    { id: 'en5-m9', type: 'Match', question: 'History', answer: 'Historie', options: ['Historie', 'Fysik', 'Engelsk'], instruction: 'Subjects' },
    { id: 'en5-m10', type: 'Match', question: 'Science', answer: 'Videnskab', options: ['Videnskab', 'Kunst', 'Musik'], instruction: 'Subjects' },
    { id: 'en5-m11', type: 'Match', question: 'Europe', answer: 'Continents', options: ['Continents', 'Countries', 'Cities'], instruction: 'Geography' },
    { id: 'en5-m12', type: 'Match', question: 'Asia', answer: 'Continents', options: ['Continents', 'Countries', 'Cities'], instruction: 'Geography' },
    { id: 'en5-m13', type: 'Match', question: 'Africa', answer: 'Continents', options: ['Continents', 'Countries', 'Cities'], instruction: 'Geography' },
    { id: 'en5-m14', type: 'Match', question: 'America', answer: 'Continents', options: ['Continents', 'Countries', 'Cities'], instruction: 'Geography' },
    { id: 'en5-m15', type: 'Match', question: 'Ocean', answer: 'Pacific', options: ['Pacific', 'Sahara', 'Amazon'], instruction: 'Geography' },
    { id: 'en5-m16', type: 'Match', question: 'Desert', answer: 'Sahara', options: ['Sahara', 'Pacific', 'Amazon'], instruction: 'Geography' },
    { id: 'en5-m17', type: 'Match', question: 'Amazon', answer: 'Rainforest', options: ['Rainforest', 'Desert', 'Ocean'], instruction: 'Geography' },
    { id: 'en5-m18', type: 'Match', question: 'Mount Everest', answer: 'Highest mountain', options: ['Highest mountain', 'Deepest ocean', 'Largest forest'], instruction: 'World records' },
    { id: 'en5-m19', type: 'Match', question: 'Blue Whale', answer: 'Largest animal', options: ['Largest animal', 'Fastest animal', 'Smallest animal'], instruction: 'World records' },
    { id: 'en5-m20', type: 'Match', question: 'Cheetah', answer: 'Fastest land animal', options: ['Fastest land animal', 'Largest land animal', 'Slowest animal'], instruction: 'World records' },
    { id: 'en5-m21', type: 'Match', question: 'Solar System', answer: 'Planets', options: ['Planets', 'Stars', 'Galaxies'], instruction: 'Space' },
    { id: 'en5-m22', type: 'Match', question: 'Mars', answer: 'Red planet', options: ['Red planet', 'Blue planet', 'Hot planet'], instruction: 'Space' },
    { id: 'en5-m23', type: 'Match', question: 'Jupiter', answer: 'Largest planet', options: ['Largest planet', 'Smallest planet', 'Rings'], instruction: 'Space' },
    { id: 'en5-m24', type: 'Match', question: 'Saturn', answer: 'Rings', options: ['Rings', 'Moons', 'Sun'], instruction: 'Space' },
    { id: 'en5-m25', type: 'Match', question: 'Oxygen', answer: 'Air', options: ['Air', 'Water', 'Fire'], instruction: 'Science' },
    { id: 'en5-m26', type: 'Match', question: 'H2O', answer: 'Water', options: ['Water', 'Oxygen', 'Gas'], instruction: 'Science' },
    { id: 'en5-m27', type: 'Match', question: 'Skeleton', answer: 'Bones', options: ['Bones', 'Muscles', 'Skin'], instruction: 'Human Body' },
    { id: 'en5-m28', type: 'Match', question: 'Heart', answer: 'Pumps blood', options: ['Pumps blood', 'Breaths air', 'Digests food'], instruction: 'Human Body' },
    { id: 'en5-m29', type: 'Match', question: 'Lungs', answer: 'Breath', options: ['Breath', 'Eat', 'See'], instruction: 'Human Body' },
    { id: 'en5-m30', type: 'Match', question: 'Stomach', answer: 'Food', options: ['Food', 'Air', 'Water'], instruction: 'Human Body' },
    { id: 'en5-m31', type: 'Match', question: 'Brain', answer: 'Thinking', options: ['Thinking', 'Walking', 'Sleeping'], instruction: 'Human Body' },
    { id: 'en5-m32', type: 'Match', question: 'Violin', answer: 'Instrument', options: ['Instrument', 'Fruit', 'Tool'], instruction: 'Arts' },
    { id: 'en3-m33', type: 'Match', question: 'Piano', answer: 'Instrument', options: ['Instrument', 'Vehicle', 'Job'], instruction: 'Arts' },
    { id: 'en5-m34', type: 'Match', question: 'Painting', answer: 'Artist', options: ['Artist', 'Doctor', 'Baker'], instruction: 'Arts' },
    { id: 'en5-m35', type: 'Match', question: 'Theater', answer: 'Actor', options: ['Actor', 'Pilot', 'Chef'], instruction: 'Arts' },
    { id: 'en5-m36', type: 'Match', question: 'Poem', answer: 'Writer', options: ['Writer', 'Farmer', 'Driver'], instruction: 'Arts' },
    { id: 'en5-m37', type: 'Match', question: 'Soccer', answer: 'Football', options: ['Football', 'Basketball', 'Tennis'], instruction: 'Sports' },
    { id: 'en5-m38', type: 'Match', question: 'Olympics', answer: 'Gold medal', options: ['Gold medal', 'Silver spoon', 'Bronze bell'], instruction: 'Sports' },
    { id: 'en5-m39', type: 'Match', question: 'Marathon', answer: 'Running', options: ['Running', 'Swiming', 'Cycling'], instruction: 'Sports' },
    { id: 'en5-m40', type: 'Match', question: 'Court', answer: 'Tennis', options: ['Tennis', 'Golf', 'Hockey'], instruction: 'Sports' },
    { id: 'en5-m41', type: 'Match', question: 'Pitch', answer: 'Football', options: ['Football', 'Tennis', 'Baseball'], instruction: 'Sports' },
    { id: 'en5-m42', type: 'Match', question: 'Language', answer: 'English', options: ['English', 'Monday', 'Apple'], instruction: 'Linguistics' },
    { id: 'en5-m43', type: 'Match', question: 'Noun', answer: 'Word for things', options: ['Word for things', 'Action word', 'Describing word'], instruction: 'Grammar' },
    { id: 'en5-m44', type: 'Match', question: 'Verb', answer: 'Action word', options: ['Action word', 'Naming word', 'Color word'], instruction: 'Grammar' },
    { id: 'en5-m45', type: 'Match', question: 'Adjective', answer: 'Describing word', options: ['Describing word', 'Action word', 'Number word'], instruction: 'Grammar' },
    { id: 'en5-m46', type: 'Match', question: 'I will', answer: 'Fremtid', options: ['Fremtid', 'Datid', 'Nutid'], instruction: 'Tenses' },
    { id: 'en5-m47', type: 'Match', question: 'I did', answer: 'Datid', options: ['Datid', 'Nutid', 'Fremtid'], instruction: 'Tenses' },
    { id: 'en5-m48', type: 'Match', question: 'I am', answer: 'Nutid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Tenses' },
    { id: 'en5-m49', type: 'Match', question: 'Fastest', answer: 'Hurtigst', options: ['Hurtigst', 'Hurtigere', 'Hurtig'], instruction: 'Comparison' },
    { id: 'en5-m50', type: 'Match', question: 'Better', answer: 'Bedre', options: ['Bedre', 'Bedst', 'God'], instruction: 'Comparison' },
    { id: 'en5-m51', type: 'Match', question: 'Bigger', answer: 'Større', options: ['Større', 'Størst', 'Stor'], instruction: 'Comparison' },
  ],
  6: [
    { id: 'en6-m1', type: 'Match', question: 'Nelson Mandela', answer: 'South Africa', options: ['South Africa', 'USA', 'UK'], instruction: 'Cultures' },
    { id: 'en6-m2', type: 'Match', question: 'Adjective', answer: 'Beautiful', options: ['Beautiful', 'Quickly', 'Run'], instruction: 'Grammar' },
    { id: 'en6-m3', type: 'Match', question: 'Adverb', answer: 'Quickly', options: ['Beautiful', 'Quickly', 'Run'], instruction: 'Grammar' },
    { id: 'en6-m4', type: 'Match', question: 'Verb', answer: 'Run', options: ['Beautiful', 'Quickly', 'Run'], instruction: 'Grammar' },
    { id: 'en6-m5', type: 'Match', question: 'Noun', answer: 'Table', options: ['Beautiful', 'Quickly', 'Table'], instruction: 'Grammar' },
    { id: 'en6-m6', type: 'Match', question: 'Apartheid', answer: 'Segregation', options: ['Segregation', 'Freedom', 'Peace'], instruction: 'History' },
    { id: 'en6-m7', type: 'Match', question: 'Rhythm', answer: 'Rytme', options: ['Rytme', 'Melodi', 'Tekst'], instruction: 'Music' },
    { id: 'en6-m8', type: 'Match', question: 'Friend', answer: 'Ven', options: ['Ven', 'Fjende', 'Fremmed'], instruction: 'Vocabulary' },
    { id: 'en6-m9', type: 'Match', question: 'Honest', answer: 'Ærlig', options: ['Ærlig', 'Falsk', 'Glad'], instruction: 'Personality' },
    { id: 'en6-m10', type: 'Match', question: 'Brave', answer: 'Modig', options: ['Modig', 'Bange', 'Stille'], instruction: 'Personality' },
    { id: 'en6-m11', type: 'Match', question: 'Environment', answer: 'Miljø', options: ['Miljø', 'Arbejde', 'Skole'], instruction: 'Vocabulary' },
    { id: 'en6-m12', type: 'Match', question: 'Pollution', answer: 'Forurening', options: ['Forurening', 'Rensning', 'Beskyttelse'], instruction: 'Vocabulary' },
    { id: 'en6-m13', type: 'Match', question: 'Sustainable', answer: 'Bæredygtig', options: ['Bæredygtig', 'Dyr', 'Billig'], instruction: 'Vocabulary' },
    { id: 'en6-m14', type: 'Match', question: 'Climate', answer: 'Klima', options: ['Klima', 'Vejr', 'Himmel'], instruction: 'Vocabulary' },
    { id: 'en6-m15', type: 'Match', question: 'Global', answer: 'Verdensomspændende', options: ['Verdensomspændende', 'Lokal', 'Nationalt'], instruction: 'Vocabulary' },
    { id: 'en6-m16', type: 'Match', question: 'Democracy', answer: 'Demokrati', options: ['Demokrati', 'Diktatur', 'Kongerige'], instruction: 'Society' },
    { id: 'en6-m17', type: 'Match', question: 'Election', answer: 'Valg', options: ['Valg', 'Møde', 'Fest'], instruction: 'Society' },
    { id: 'en6-m18', type: 'Match', question: 'Government', answer: 'Regering', options: ['Regering', 'Skole', 'Kirke'], instruction: 'Society' },
    { id: 'en6-m19', type: 'Match', question: 'Citizen', answer: 'Borger', options: ['Borger', 'Turist', 'Gæst'], instruction: 'Society' },
    { id: 'en6-m20', type: 'Match', question: 'Law', answer: 'Lov', options: ['Lov', 'Råd', 'Ønske'], instruction: 'Society' },
    { id: 'en6-m21', type: 'Match', question: 'Martin Luther King', answer: 'Civil rights', options: ['Civil rights', 'Space travel', 'Cooking'], instruction: 'Famous people' },
    { id: 'en6-m22', type: 'Match', question: 'Albert Einstein', answer: 'Physicist', options: ['Physicist', 'Painter', 'Musician'], instruction: 'Famous people' },
    { id: 'en6-m23', type: 'Match', question: 'William Shakespeare', answer: 'Writer', options: ['Writer', 'Pilot', 'Doctor'], instruction: 'Famous people' },
    { id: 'en6-m24', type: 'Match', question: 'Leonardo da Vinci', answer: 'Artist', options: ['Artist', 'Farmer', 'Sailor'], instruction: 'Famous people' },
    { id: 'en6-m25', type: 'Match', question: 'Mozart', answer: 'Composer', options: ['Composer', 'Chef', 'Engineer'], instruction: 'Famous people' },
    { id: 'en6-m26', type: 'Match', question: 'Compass', answer: 'Direction', options: ['Direction', 'Map', 'Clock'], instruction: 'Geography' },
    { id: 'en6-m27', type: 'Match', question: 'Equator', answer: 'Middle of Earth', options: ['Middle of Earth', 'North Pole', 'South Pole'], instruction: 'Geography' },
    { id: 'en6-m28', type: 'Match', question: 'Continent', answer: 'Large land mass', options: ['Large land mass', 'Small island', 'Large lake'], instruction: 'Geography' },
    { id: 'en6-m29', type: 'Match', question: 'Hemisphere', answer: 'Half of Earth', options: ['Half of Earth', 'Whole Earth', 'Quarter of Earth'], instruction: 'Geography' },
    { id: 'en6-m30', type: 'Match', question: 'Border', answer: 'Grænse', options: ['Grænse', 'Vej', 'Bro'], instruction: 'Geography' },
    { id: 'en6-m31', type: 'Match', question: 'Synonym', answer: 'Same meaning', options: ['Same meaning', 'Opposite meaning', 'Different sound'], instruction: 'Language' },
    { id: 'en6-m32', type: 'Match', question: 'Antonym', answer: 'Opposite meaning', options: ['Opposite meaning', 'Same meaning', 'Rhyming word'], instruction: 'Language' },
    { id: 'en6-m33', type: 'Match', question: 'Homonym', answer: 'Same sound', options: ['Same sound', 'Same meaning', 'Same letter'], instruction: 'Language' },
    { id: 'en6-m34', type: 'Match', question: 'Prefix', answer: 'Before word', options: ['Before word', 'After word', 'Inside word'], instruction: 'Language' },
    { id: 'en6-m35', type: 'Match', question: 'Suffix', answer: 'After word', options: ['After word', 'Before word', 'Inside word'], instruction: 'Language' },
    { id: 'en6-m36', type: 'Match', question: 'Evolution', answer: 'Darwin', options: ['Darwin', 'Newton', 'Einstein'], instruction: 'Science' },
    { id: 'en6-m37', type: 'Match', question: 'Gravity', answer: 'Newton', options: ['Newton', 'Darwin', 'Galileo'], instruction: 'Science' },
    { id: 'en6-m38', type: 'Match', question: 'Electricity', answer: 'Power', options: ['Power', 'Water', 'Wind'], instruction: 'Science' },
    { id: 'en6-m39', type: 'Match', question: 'Energy', answer: 'Energi', options: ['Energi', 'Træthed', 'Søvn'], instruction: 'Science' },
    { id: 'en6-m40', type: 'Match', question: 'Reaction', answer: 'Reaktion', options: ['Reaktion', 'Aktion', 'Pause'], instruction: 'Science' },
    { id: 'en6-m41', type: 'Match', question: 'Freedom', answer: 'Frihed', options: ['Frihed', 'Fængsel', 'Arbejde'], instruction: 'Values' },
    { id: 'en6-m42', type: 'Match', question: 'Justice', answer: 'Retfærdighed', options: ['Retfærdighed', 'Uretfærdighed', 'Hævn'], instruction: 'Values' },
    { id: 'en6-m43', type: 'Match', question: 'Peace', answer: 'Fred', options: ['Fred', 'Krig', 'Uro'], instruction: 'Values' },
    { id: 'en6-m44', type: 'Match', question: 'Equality', answer: 'Lighed', options: ['Lighed', 'Ulighed', 'Forskel'], instruction: 'Values' },
    { id: 'en6-m45', type: 'Match', question: 'Human Rights', answer: 'Menneskerettigheder', options: ['Menneskerettigheder', 'Pligter', 'Skoler'], instruction: 'Values' },
    { id: 'en6-m46', type: 'Match', question: 'Internet', answer: 'World Wide Web', options: ['World Wide Web', 'Radio', 'TV'], instruction: 'Technology' },
    { id: 'en6-m47', type: 'Match', question: 'Software', answer: 'Programs', options: ['Programs', 'Hard drive', 'Monitor'], instruction: 'Technology' },
    { id: 'en6-m48', type: 'Match', question: 'Hardware', answer: 'Physical parts', options: ['Physical parts', 'Programs', 'Data'], instruction: 'Technology' },
    { id: 'en6-m49', type: 'Match', question: 'Binary', answer: '0 and 1', options: ['0 and 1', 'A and B', 'Red and Blue'], instruction: 'Technology' },
    { id: 'en6-m50', type: 'Match', question: 'Password', answer: 'Secret word', options: ['Secret word', 'Public name', 'Email'], instruction: 'Technology' },
    { id: 'en6-m51', type: 'Match', question: 'Artificial Intelligence', answer: 'AI', options: ['AI', 'VR', 'AR'], instruction: 'Technology' },
  ],
  7: [
    { id: 'en7-m1', type: 'Match', question: 'Independence Day', answer: '4th of July', options: ['4th of July', '25th of Dec', '31st of Oct'], instruction: 'USA Holidays' },
    { id: 'en7-m2', type: 'Match', question: 'Horror', answer: 'Scary', options: ['Scary', 'Funny', 'Romantic'], instruction: 'Genres' },
    { id: 'en7-m3', type: 'Match', question: 'Comedy', answer: 'Funny', options: ['Scary', 'Funny', 'Romantic'], instruction: 'Genres' },
    { id: 'en7-m4', type: 'Match', question: 'Romance', answer: 'Love', options: ['Scary', 'Funny', 'Love'], instruction: 'Genres' },
    { id: 'en7-m5', type: 'Match', question: 'Future', answer: 'Fremtid', options: ['Fremtid', 'Datid', 'Nutid'], instruction: 'Vocabulary' },
    { id: 'en7-m6', type: 'Match', question: 'Teenager', answer: 'Young person', options: ['Young person', 'Adult', 'Child'], instruction: 'Age' },
    { id: 'en7-m7', type: 'Match', question: 'Vampire', answer: 'Dracula', options: ['Dracula', 'Bond', 'Potter'], instruction: 'Characters' },
    { id: 'en7-m8', type: 'Match', question: 'Zombie', answer: 'Undead', options: ['Undead', 'Wizard', 'Elf'], instruction: 'Characters' },
    { id: 'en7-m9', type: 'Match', question: 'Growth', answer: 'Vækst', options: ['Vækst', 'Fald', 'Stilstand'], instruction: 'Vocabulary' },
    { id: 'en7-m10', type: 'Match', question: 'Hate', answer: 'Had', options: ['Had', 'Kærlighed', 'Venskab'], instruction: 'Emotions' },
    { id: 'en7-m11', type: 'Match', question: 'Success', answer: 'Succes', options: ['Succes', 'Fiasko', 'Forsøg'], instruction: 'Vocabulary' },
    { id: 'en7-m12', type: 'Match', question: 'Failure', answer: 'Fiasko', options: ['Succes', 'Fiasko', 'Forsøg'], instruction: 'Vocabulary' },
    { id: 'en7-m13', type: 'Match', question: 'Ambition', answer: 'Draft', options: ['Draft', 'Dream', 'Goal'], instruction: 'Personality' },
    { id: 'en7-m14', type: 'Match', question: 'Conflict', answer: 'Konflikt', options: ['Konflikt', 'Fred', 'Enighed'], instruction: 'Vocabulary' },
    { id: 'en7-m15', type: 'Match', question: 'Solution', answer: 'Løsning', options: ['Løsning', 'Problem', 'Spørgsmål'], instruction: 'Vocabulary' },
    { id: 'en7-m16', type: 'Match', question: 'Identity', answer: 'Identitet', options: ['Identitet', 'Navn', 'Alder'], instruction: 'Society' },
    { id: 'en7-m17', type: 'Match', question: 'Culture', answer: 'Kultur', options: ['Kultur', 'Natur', 'Teknik'], instruction: 'Society' },
    { id: 'en7-m18', type: 'Match', question: 'Tradition', answer: 'Tradition', options: ['Tradition', 'Nyhed', 'Mode'], instruction: 'Society' },
    { id: 'en7-m19', type: 'Match', question: 'Belief', answer: 'Tro', options: ['Tro', 'Viden', 'Tvivl'], instruction: 'Society' },
    { id: 'en7-m20', type: 'Match', question: 'Values', answer: 'Værdier', options: ['Værdier', 'Penge', 'Ting'], instruction: 'Society' },
    { id: 'en7-m21', type: 'Match', question: 'Environment', answer: 'Miljø', options: ['Miljø', 'Skole', 'By'], instruction: 'Nature' },
    { id: 'en7-m22', type: 'Match', question: 'Pollution', answer: 'Forurening', options: ['Forurening', 'Beskyttelse', 'Rensning'], instruction: 'Nature' },
    { id: 'en7-m23', type: 'Match', question: 'Recycle', answer: 'Genbrug', options: ['Genbrug', 'Affald', 'Smid væk'], instruction: 'Nature' },
    { id: 'en7-m24', type: 'Match', question: 'Ocean', answer: 'Hav', options: ['Hav', 'Sø', 'Flod'], instruction: 'Nature' },
    { id: 'en7-m25', type: 'Match', question: 'Climate', answer: 'Klima', options: ['Klima', 'Vejr', 'Hverdag'], instruction: 'Nature' },
    { id: 'en7-m26', type: 'Match', question: 'Global', answer: 'Verdensomspændende', options: ['Verdensomspændende', 'Lokal', 'Privat'], instruction: 'Nature' },
    { id: 'en7-m27', type: 'Match', question: 'Energy', answer: 'Energi', options: ['Energi', 'Træthed', 'Søvn'], instruction: 'Science' },
    { id: 'en7-m28', type: 'Match', question: 'Science', answer: 'Videnskab', options: ['Videnskab', 'Kunst', 'Sport'], instruction: 'School' },
    { id: 'en7-m29', type: 'Match', question: 'Fiction', answer: 'Opdigtet', options: ['Opdigtet', 'Virkelighed', 'Sandhed'], instruction: 'Literature' },
    { id: 'en7-m30', type: 'Match', question: 'Novel', answer: 'Roman', options: ['Roman', 'Digt', 'Avis'], instruction: 'Literature' },
    { id: 'en7-m31', type: 'Match', question: 'Chapter', answer: 'Kapitel', options: ['Kapitel', 'Side', 'Ord'], instruction: 'Literature' },
    { id: 'en7-m32', type: 'Match', question: 'Author', answer: 'Forfatter', options: ['Forfatter', 'Læser', 'Kritiker'], instruction: 'Literature' },
    { id: 'en7-m33', type: 'Match', question: 'Character', answer: 'Person i bogen', options: ['Person i bogen', 'Forfatter', 'Bogstav'], instruction: 'Literature' },
    { id: 'en7-m34', type: 'Match', question: 'Plot', answer: 'Handling', options: ['Handling', 'Slutning', 'Start'], instruction: 'Literature' },
    { id: 'en7-m35', type: 'Match', question: 'Setting', answer: 'Sted og tid', options: ['Sted og tid', 'Person', 'Navn'], instruction: 'Literature' },
    { id: 'en7-m36', type: 'Match', question: 'Teenage', answer: 'Teenager-år', options: ['Teenager-år', 'Barndom', 'Voksenliv'], instruction: 'Life' },
    { id: 'en7-m37', type: 'Match', question: 'Education', answer: 'Uddannelse', options: ['Uddannelse', 'Arbejde', 'Ferie'], instruction: 'Life' },
    { id: 'en7-m38', type: 'Match', question: 'Future', answer: 'Fremtid', options: ['Fremtid', 'Datid', 'Nutid'], instruction: 'Life' },
    { id: 'en7-m39', type: 'Match', question: 'Choice', answer: 'Valg', options: ['Valg', 'Tvang', 'Ønske'], instruction: 'Life' },
    { id: 'en7-m40', type: 'Match', question: 'Dream', answer: 'Drøm', options: ['Drøm', 'Virkelighed', 'Plan'], instruction: 'Life' },
    { id: 'en7-m41', type: 'Match', question: 'Fear', answer: 'Frygt', options: ['Frygt', 'Mod', 'Glæde'], instruction: 'Emotions' },
    { id: 'en7-m42', type: 'Match', question: 'Courage', answer: 'Mod', options: ['Mod', 'Frygt', 'Træthed'], instruction: 'Emotions' },
    { id: 'en7-m43', type: 'Match', question: 'Trust', answer: 'Tillid', options: ['Tillid', 'Mistillid', 'Had'], instruction: 'Emotions' },
    { id: 'en7-m44', type: 'Match', question: 'Love', answer: 'Kærlighed', options: ['Kærlighed', 'Had', 'Vrede'], instruction: 'Emotions' },
    { id: 'en7-m45', type: 'Match', question: 'Friendship', answer: 'Venskab', options: ['Venskab', 'Fjendskab', 'Familie'], instruction: 'Emotions' },
    { id: 'en7-m46', type: 'Match', question: 'Bullying', answer: 'Mobning', options: ['Mobning', 'Hjælp', 'Leg'], instruction: 'Issues' },
    { id: 'en7-m47', type: 'Match', question: 'Respect', answer: 'Respekt', options: ['Respekt', 'Hån', 'Ligegyldighed'], instruction: 'Values' },
    { id: 'en7-m48', type: 'Match', question: 'Justice', answer: 'Retfærdighed', options: ['Retfærdighed', 'Uretfærdighed', 'Hævn'], instruction: 'Values' },
    { id: 'en7-m49', type: 'Match', question: 'Responsibility', answer: 'Ansvar', options: ['Ansvar', 'Leg', 'Fritid'], instruction: 'Values' },
    { id: 'en7-m50', type: 'Match', question: 'Honesty', answer: 'Ærlighed', options: ['Ærlighed', 'Løgn', 'Tvivl'], instruction: 'Values' },
    { id: 'en7-m51', type: 'Match', question: 'Kindness', answer: 'Venlighed', options: ['Venlighed', 'Ondskab', 'Kulde'], instruction: 'Values' },
  ],
  8: [
    { id: 'en8-m1', type: 'Match', question: 'Lift', answer: 'Elevator', options: ['Elevator', 'Escalator', 'Stairs'], instruction: 'British vs American' },
    { id: 'en8-m2', type: 'Match', question: 'Flat', answer: 'Apartment', options: ['Apartment', 'House', 'Tent'], instruction: 'British vs American' },
    { id: 'en8-m3', type: 'Match', question: 'Chips', answer: 'French Fries', options: ['Crisps', 'French Fries', 'Cookies'], instruction: 'British vs American' },
    { id: 'en8-m4', type: 'Match', question: 'Crisps', answer: 'Potato Chips', options: ['Cookies', 'Potato Chips', 'Cake'], instruction: 'British vs American' },
    { id: 'en8-m5', type: 'Match', question: 'Rosa Parks', answer: 'Bus boycott', options: ['Bus boycott', 'Speech', 'Peace prize'], instruction: 'Civil Rights' },
    { id: 'en8-m6', type: 'Match', question: 'Martin Luther King', answer: 'I have a dream', options: ['I have a dream', 'To be or not to be', 'Yes we can'], instruction: 'Civil Rights' },
    { id: 'en8-m7', type: 'Match', question: 'Go, went...', answer: 'Gone', options: ['Going', 'Gone', 'Goes'], instruction: 'Irregular Verbs' },
    { id: 'en8-m8', type: 'Match', question: 'Eat, ate...', answer: 'Eaten', options: ['Eating', 'Eaten', 'Eats'], instruction: 'Irregular Verbs' },
    { id: 'en8-m9', type: 'Match', question: 'See, saw...', answer: 'Seen', options: ['Seeing', 'Seen', 'Sees'], instruction: 'Irregular Verbs' },
    { id: 'en8-m10', type: 'Match', question: 'Rugby', answer: 'Ball game', options: ['Ball game', 'Racing', 'Skiing'], instruction: 'Sports' },
    { id: 'en8-m11', type: 'Match', question: 'Football', answer: 'Soccer (USA)', options: ['Soccer (USA)', 'Basketball', 'Tennis'], instruction: 'Sports' },
    { id: 'en8-m12', type: 'Match', question: 'Baseball', answer: 'Bat and ball', options: ['Bat and ball', 'Club and ball', 'Kick and ball'], instruction: 'Sports' },
    { id: 'en8-m13', type: 'Match', question: 'Basketball', answer: 'Hoop', options: ['Hoop', 'Net', 'Goal'], instruction: 'Sports' },
    { id: 'en8-m14', type: 'Match', question: 'Cricket', answer: 'Wicket', options: ['Wicket', 'Hole', 'Line'], instruction: 'Sports' },
    { id: 'en8-m15', type: 'Match', question: 'Surfing', answer: 'Waves', options: ['Waves', 'Snow', 'Ice'], instruction: 'Sports' },
    { id: 'en8-m16', type: 'Match', question: 'Civil Rights', answer: 'Borgerrettigheder', options: ['Borgerrettigheder', 'Krig', 'Handel'], instruction: 'History' },
    { id: 'en8-m17', type: 'Match', question: 'Slavery', answer: 'Slaveri', options: ['Slaveri', 'Frihed', 'Valg'], instruction: 'History' },
    { id: 'en8-m18', type: 'Match', question: 'Equality', answer: 'Lighed', options: ['Lighed', 'Ulighed', 'Forskel'], instruction: 'History' },
    { id: 'en8-m19', type: 'Match', question: 'Freedom', answer: 'Frihed', options: ['Frihed', 'Fangenskab', 'Arbejde'], instruction: 'History' },
    { id: 'en8-m20', type: 'Match', question: 'Movement', answer: 'Bevægelse', options: ['Bevægelse', 'Stilstand', 'Fest'], instruction: 'History' },
    { id: 'en8-m21', type: 'Match', question: 'Empire', answer: 'Imperium', options: ['Imperium', 'By', 'Land'], instruction: 'British Empire' },
    { id: 'en8-m22', type: 'Match', question: 'Colony', answer: 'Koloni', options: ['Koloni', 'Hjemsted', 'Ferieø'], instruction: 'British Empire' },
    { id: 'en8-m23', type: 'Match', question: 'Trade', answer: 'Handel', options: ['Handel', 'Gave', 'Tyveri'], instruction: 'British Empire' },
    { id: 'en8-m24', type: 'Match', question: 'Power', answer: 'Magt', options: ['Magt', 'Svaghed', 'Venskab'], instruction: 'British Empire' },
    { id: 'en8-m25', type: 'Match', question: 'Queen', answer: 'Dronning', options: ['Dronning', 'Konge', 'Prins'], instruction: 'British Empire' },
    { id: 'en8-m26', type: 'Match', question: 'Global', answer: 'Verdensomspændende', options: ['Verdensomspændende', 'Lokal', 'Personlig'], instruction: 'British Empire' },
    { id: 'en8-m27', type: 'Match', question: 'Influence', answer: 'Indflydelse', options: ['Indflydelse', 'Ligegyldighed', 'Modstand'], instruction: 'British Empire' },
    { id: 'en8-m28', type: 'Match', question: 'Speak, spoke...', answer: 'Spoken', options: ['Speaking', 'Spoken', 'Speaks'], instruction: 'Irregular Verbs' },
    { id: 'en8-m29', type: 'Match', question: 'Write, wrote...', answer: 'Written', options: ['Writing', 'Written', 'Writes'], instruction: 'Irregular Verbs' },
    { id: 'en8-m30', type: 'Match', question: 'Buy, bought...', answer: 'Bought (p.p.)', options: ['Buying', 'Bought (p.p.)', 'Buys'], instruction: 'Irregular Verbs' },
    { id: 'en8-m31', type: 'Match', question: 'Catch, caught...', answer: 'Caught (p.p.)', options: ['Catching', 'Caught (p.p.)', 'Catches'], instruction: 'Irregular Verbs' },
    { id: 'en8-m32', type: 'Match', question: 'Bring, brought...', answer: 'Brought (p.p.)', options: ['Bringing', 'Brought (p.p.)', 'Brings'], instruction: 'Irregular Verbs' },
    { id: 'en8-m33', type: 'Match', question: 'Think, thought...', answer: 'Thought (p.p.)', options: ['Thinking', 'Thought (p.p.)', 'Thinks'], instruction: 'Irregular Verbs' },
    { id: 'en8-m34', type: 'Match', question: 'Drink, drank...', answer: 'Drunk', options: ['Drinking', 'Drunk', 'Drinks'], instruction: 'Irregular Verbs' },
    { id: 'en8-m35', type: 'Match', question: 'Sing, sang...', answer: 'Sung', options: ['Singing', 'Sung', 'Sings'], instruction: 'Irregular Verbs' },
    { id: 'en8-m36', type: 'Match', question: 'Know, knew...', answer: 'Known', options: ['Knowing', 'Known', 'Knows'], instruction: 'Irregular Verbs' },
    { id: 'en8-m37', type: 'Match', question: 'Show, showed...', answer: 'Shown', options: ['Showing', 'Shown', 'Shows'], instruction: 'Irregular Verbs' },
    { id: 'en8-m38', type: 'Match', question: 'Subway', answer: 'Underground (UK)', options: ['Underground (UK)', 'Overground', 'Bus'], instruction: 'Am. vs Br.' },
    { id: 'en8-m39', type: 'Match', question: 'Cookie', answer: 'Biscuit (UK)', options: ['Biscuit (UK)', 'Cake', 'Bread'], instruction: 'Am. vs Br.' },
    { id: 'en8-m40', type: 'Match', question: 'Movie', answer: 'Film (UK)', options: ['Film (UK)', 'Picture', 'Show'], instruction: 'Am. vs Br.' },
    { id: 'en8-m41', type: 'Match', question: 'Sneakers', answer: 'Trainers (UK)', options: ['Trainers (UK)', 'Slippers', 'Boots'], instruction: 'Am. vs Br.' },
    { id: 'en8-m42', type: 'Match', question: 'Jumper', answer: 'Sweater (USA)', options: ['Sweater (USA)', 'T-shirt', 'Jacket'], instruction: 'Am. vs Br.' },
    { id: 'en8-m43', type: 'Match', question: 'Trousers', answer: 'Pants (USA)', options: ['Pants (USA)', 'Skirts', 'Hats'], instruction: 'Am. vs Br.' },
    { id: 'en8-m44', type: 'Match', question: 'Color', answer: 'Colour (UK)', options: ['Colour (UK)', 'Coloring', 'Colored'], instruction: 'Am. vs Br. Spelling' },
    { id: 'en8-m45', type: 'Match', question: 'Center', answer: 'Centre (UK)', options: ['Centre (UK)', 'Central', 'Centering'], instruction: 'Am. vs Br. Spelling' },
    { id: 'en8-m46', type: 'Match', question: 'Organize', answer: 'Organise (UK)', options: ['Organise (UK)', 'Organizer', 'Organizing'], instruction: 'Am. vs Br. Spelling' },
    { id: 'en8-m47', type: 'Match', question: 'Theater', answer: 'Theatre (UK)', options: ['Theatre (UK)', 'Theatrical', 'Theaters'], instruction: 'Am. vs Br. Spelling' },
    { id: 'en8-m48', type: 'Match', question: 'Defense', answer: 'Defence (UK)', options: ['Defence (UK)', 'Defending', 'Defensive'], instruction: 'Am. vs Br. Spelling' },
    { id: 'en8-m49', type: 'Match', question: 'Favorite', answer: 'Favourite (UK)', options: ['Favourite (UK)', 'Favor', 'Fair'], instruction: 'Am. vs Br. Spelling' },
    { id: 'en8-m50', type: 'Match', question: 'Labor', answer: 'Labour (UK)', options: ['Labour (UK)', 'Label', 'Large'], instruction: 'Am. vs Br. Spelling' },
    { id: 'en8-m51', type: 'Match', question: 'Gray', answer: 'Grey (UK)', options: ['Grey (UK)', 'Grate', 'Great'], instruction: 'Am. vs Br. Spelling' },
  ],
  9: [
    { id: 'en9-m1', type: 'Match', question: 'Prejudice', answer: 'Fordom', options: ['Fordom', 'Viden', 'Respekt'], instruction: 'Vocabulary' },
    { id: 'en9-m2', type: 'Match', question: 'Graffiti', answer: 'Street Art', options: ['Street Art', 'Music', 'Cooking'], instruction: 'Culture' },
    { id: 'en9-m3', type: 'Match', question: 'India', answer: 'New Delhi', options: ['Mumbai', 'New Delhi', 'Kolkata'], instruction: 'Capitals' },
    { id: 'en9-m4', type: 'Match', question: 'Global', answer: 'Verdensomspændende', options: ['Verdensomspændende', 'Lokal', 'Privat'], instruction: 'Vocabulary' },
    { id: 'en9-m5', type: 'Match', question: 'Climate Change', answer: 'Global Warming', options: ['Global Warming', 'New Age', 'Dark Age'], instruction: 'Issues' },
    { id: 'en9-m6', type: 'Match', question: 'Environment', answer: 'Miljø', options: ['Miljø', 'Skole', 'Arbejde'], instruction: 'Vocabulary' },
    { id: 'en9-m7', type: 'Match', question: 'Equality', answer: 'Lighed', options: ['Lighed', 'Ulighed', 'Frihed'], instruction: 'Vocabulary' },
    { id: 'en9-m8', type: 'Match', question: 'Liberty', answer: 'Freedom', options: ['Freedom', 'Prision', 'Work'], instruction: 'Vocabulary' },
    { id: 'en9-m9', type: 'Match', question: 'Protest', answer: 'Demonstration', options: ['Demonstration', 'Party', 'Meeting'], instruction: 'Activity' },
    { id: 'en9-m10', type: 'Match', question: 'History', answer: 'The Past', options: ['The Past', 'The Future', 'The Present'], instruction: 'Vocabulary' },
    { id: 'en9-m11', type: 'Match', question: 'Ghetto', answer: 'Isolated area', options: ['Isolated area', 'Rich area', 'City center'], instruction: 'Society' },
    { id: 'en9-m12', type: 'Match', question: 'Migration', answer: 'Moving countries', options: ['Moving countries', 'Staying home', 'Traveling for a week'], instruction: 'Society' },
    { id: 'en9-m13', type: 'Match', question: 'Diversity', answer: 'Mangfoldighed', options: ['Mangfoldighed', 'Lighed', 'Samme'], instruction: 'Society' },
    { id: 'en9-m14', type: 'Match', question: 'Immigration', answer: 'Moving in', options: ['Moving in', 'Moving out', 'Visiting'], instruction: 'Society' },
    { id: 'en9-m15', type: 'Match', question: 'Emigration', answer: 'Moving out', options: ['Moving out', 'Moving in', 'Staying'], instruction: 'Society' },
    { id: 'en9-m16', type: 'Match', question: 'Colonialism', answer: 'Imperialism', options: ['Imperialism', 'Freedom', 'Independence'], instruction: 'History' },
    { id: 'en9-m17', type: 'Match', question: 'Independence', answer: 'Selvstændighed', options: ['Selvstændighed', 'Afhængighed', 'Samarbejde'], instruction: 'History' },
    { id: 'en9-m18', type: 'Match', question: 'Empire', answer: 'Imperium', options: ['Imperium', 'By', 'Land'], instruction: 'History' },
    { id: 'en9-m19', type: 'Match', question: 'Commonwealth', answer: 'International group', options: ['International group', 'Local club', 'Private bank'], instruction: 'History' },
    { id: 'en9-m20', type: 'Match', question: 'USA', answer: 'Washington D.C.', options: ['Washington D.C.', 'New York', 'Los Angeles'], instruction: 'Capitals' },
    { id: 'en9-m21', type: 'Match', question: 'Canada', answer: 'Ottawa', options: ['Toronto', 'Ottawa', 'Vancouver'], instruction: 'Capitals' },
    { id: 'en9-m22', type: 'Match', question: 'UK', answer: 'London', options: ['London', 'Manchester', 'Edinburgh'], instruction: 'Capitals' },
    { id: 'en9-m23', type: 'Match', question: 'South Africa', answer: 'Pretoria', options: ['Cape Town', 'Pretoria', 'Johannesburg'], instruction: 'Capitals' },
    { id: 'en9-m24', type: 'Match', question: 'New Zealand', answer: 'Wellington', options: ['Auckland', 'Wellington', 'Christchurch'], instruction: 'Capitals' },
    { id: 'en9-m25', type: 'Match', question: 'Economy', answer: 'Økonomi', options: ['Økonomi', 'Kultur', 'Natur'], instruction: 'Vocabulary' },
    { id: 'en9-m26', type: 'Match', question: 'Poverty', answer: 'Fattigdom', options: ['Fattigdom', 'Rigdom', 'Middelklasse'], instruction: 'Global Issues' },
    { id: 'en9-m27', type: 'Match', question: 'Hunger', answer: 'Sult', options: ['Sult', 'Tørst', 'Mæthed'], instruction: 'Global Issues' },
    { id: 'en9-m28', type: 'Match', question: 'Disease', answer: 'Sygdom', options: ['Sygdom', 'Sundhed', 'Liv'], instruction: 'Global Issues' },
    { id: 'en9-m29', type: 'Match', question: 'Pollution', answer: 'Forurening', options: ['Forurening', 'Rensning', 'Beskyttelse'], instruction: 'Global Issues' },
    { id: 'en9-m30', type: 'Match', question: 'Human Rights', answer: 'Menneskerettigheder', options: ['Menneskerettigheder', 'Pligter', 'Lov'], instruction: 'Global Issues' },
    { id: 'en9-m31', type: 'Match', question: 'Sustainable', answer: 'Bæredygtig', options: ['Bæredygtig', 'Dyr', 'Billig'], instruction: 'Global Issues' },
    { id: 'en9-m32', type: 'Match', question: 'Consumerism', answer: 'Forbrugersamfund', options: ['Forbrugersamfund', 'Natur', 'Sparsommelighed'], instruction: 'Society' },
    { id: 'en9-m33', type: 'Match', question: 'Ethics', answer: 'Etik', options: ['Etik', 'Lov', 'Moral'], instruction: 'Philosophy' },
    { id: 'en9-m34', type: 'Match', question: 'Moral', answer: 'Moral', options: ['Moral', 'Drøm', 'Ønske'], instruction: 'Philosophy' },
    { id: 'en9-m35', type: 'Match', question: 'Philosophy', answer: 'Filosofi', options: ['Filosofi', 'Videnskab', 'Kunst'], instruction: 'Philosophy' },
    { id: 'en9-m36', type: 'Match', question: 'Artificial Intelligence', answer: 'Kunstig Intelligens', options: ['Kunstig Intelligens', 'Naturlig Viden', 'Menneske'], instruction: 'Technology' },
    { id: 'en9-m37', type: 'Match', question: 'Virtual Reality', answer: 'VR', options: ['VR', 'AR', 'AI'], instruction: 'Technology' },
    { id: 'en9-m38', type: 'Match', question: 'Privacy', answer: 'Privatliv', options: ['Privatliv', 'Offentlighed', 'Hemmelighed'], instruction: 'Technology' },
    { id: 'en9-m39', type: 'Match', question: 'Security', answer: 'Sikkerhed', options: ['Sikkerhed', 'Fare', 'Frygt'], instruction: 'Technology' },
    { id: 'en9-m40', type: 'Match', question: 'Challenge', answer: 'Udfordring', options: ['Udfordring', 'Løsning', 'Gave'], instruction: 'Vocabulary' },
    { id: 'en9-m41', type: 'Match', question: 'Opportunity', answer: 'Mulighed', options: ['Mulighed', 'Begrænsning', 'Problem'], instruction: 'Vocabulary' },
    { id: 'en9-m42', type: 'Match', question: 'Adventure', answer: 'Eventyr', options: ['Eventyr', 'Hverdag', 'Søvn'], instruction: 'Vocabulary' },
    { id: 'en9-m43', type: 'Match', question: 'Success', answer: 'Succes', options: ['Succes', 'Tab', 'Forsøg'], instruction: 'Vocabulary' },
    { id: 'en9-m44', type: 'Match', question: 'Future', answer: 'The time to come', options: ['The time to come', 'The time that was', 'Right now'], instruction: 'Vocabulary' },
    { id: 'en9-m45', type: 'Match', question: 'Destiny', answer: 'Skæbne', options: ['Skæbne', 'Valg', 'Plan'], instruction: 'Vocabulary' },
    { id: 'en9-m46', type: 'Match', question: 'Ambition', answer: 'Ambitiøsitet', options: ['Ambitiøsitet', 'Ladehed', 'Ro'], instruction: 'Vocabulary' },
    { id: 'en9-m47', type: 'Match', question: 'Inspire', answer: 'Inspirere', options: ['Inspirere', 'Kede', 'Stop'], instruction: 'Vocabulary' },
    { id: 'en9-m48', type: 'Match', question: 'Motivate', answer: 'Motivere', options: ['Motivere', 'Bremse', 'Glemme'], instruction: 'Vocabulary' },
    { id: 'en9-m49', type: 'Match', question: 'Achieve', answer: 'Opnå', options: ['Opnå', 'Miste', 'Prøve'], instruction: 'Vocabulary' },
    { id: 'en9-m50', type: 'Match', question: 'Goal', answer: 'Mål', options: ['Mål', 'Start', 'Vej'], instruction: 'Vocabulary' },
    { id: 'en9-m51', type: 'Match', question: 'Victory', answer: 'Sejr', options: ['Sejr', 'Nederlag', 'Lige'], instruction: 'Vocabulary' },
  ]
};
