/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const FRANSK_MATCH: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'fr0-m1', type: 'Match', question: 'Rouge', answer: '🔴', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Les couleurs' },
    { id: 'fr0-m2', type: 'Match', question: 'Bleu', answer: '🔵', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Les couleurs' },
    { id: 'fr0-m3', type: 'Match', question: 'Vert', answer: '🟢', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Les couleurs' },
    { id: 'fr0-m4', type: 'Match', question: 'Jaune', answer: '🟡', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Les couleurs' },
    { id: 'fr0-m5', type: 'Match', question: 'Un', answer: '1', options: ['1', '2', '3', '4'], instruction: 'Les nombres' },
    { id: 'fr0-m6', type: 'Match', question: 'Deux', answer: '2', options: ['1', '2', '3', '4'], instruction: 'Les nombres' },
    { id: 'fr0-m7', type: 'Match', question: 'Trois', answer: '3', options: ['1', '2', '3', '4'], instruction: 'Les nombres' },
    { id: 'fr0-m8', type: 'Match', question: 'Salut', answer: 'Hej', options: ['Hej', 'Tak', 'Ja'], instruction: 'Salutations' },
    { id: 'fr0-m9', type: 'Match', question: 'Oui', answer: 'Ja', options: ['Ja', 'Nej', 'Måske'], instruction: 'Vocabulaire' },
    { id: 'fr0-m10', type: 'Match', question: 'Non', answer: 'Nej', options: ['Ja', 'Nej', 'Måske'], instruction: 'Vocabulaire' },
    { id: 'fr0-m11', type: 'Match', question: 'Noir', answer: '⚫', options: ['⚫', '⚪', '🟤'], instruction: 'Les couleurs' },
    { id: 'fr0-m12', type: 'Match', question: 'Blanc', answer: '⚪', options: ['⚫', '⚪', '🟤'], instruction: 'Les couleurs' },
    { id: 'fr0-m13', type: 'Match', question: 'Marron', answer: '🟤', options: ['⚫', '⚪', '🟤'], instruction: 'Les couleurs' },
    { id: 'fr0-m14', type: 'Match', question: 'Orange', answer: '🟠', options: ['🟠', '🟣', '💗'], instruction: 'Les couleurs' },
    { id: 'fr0-m15', type: 'Match', question: 'Violet', answer: '🟣', options: ['🟠', '🟣', '💗'], instruction: 'Les couleurs' },
    { id: 'fr0-m16', type: 'Match', question: 'Rose', answer: '💗', options: ['🟠', '🟣', '💗'], instruction: 'Les couleurs' },
    { id: 'fr0-m17', type: 'Match', question: 'Quatre', answer: '4', options: ['4', '5', '6'], instruction: 'Les nombres' },
    { id: 'fr0-m18', type: 'Match', question: 'Cinq', answer: '5', options: ['4', '5', '6'], instruction: 'Les nombres' },
    { id: 'fr0-m19', type: 'Match', question: 'Six', answer: '6', options: ['4', '5', '6'], instruction: 'Les nombres' },
    { id: 'fr0-m20', type: 'Match', question: 'Sept', answer: '7', options: ['7', '8', '9'], instruction: 'Les nombres' },
    { id: 'fr0-m21', type: 'Match', question: 'Huit', answer: '8', options: ['7', '8', '9'], instruction: 'Les nombres' },
    { id: 'fr0-m22', type: 'Match', question: 'Neuf', answer: '9', options: ['7', '8', '9'], instruction: 'Les nombres' },
    { id: 'fr0-m23', type: 'Match', question: 'Dix', answer: '10', options: ['8', '9', '10'], instruction: 'Les nombres' },
    { id: 'fr0-m24', type: 'Match', question: 'Le chien', answer: '🐕', options: ['🐕', '🐈', '🦜'], instruction: 'Les animaux' },
    { id: 'fr0-m25', type: 'Match', question: 'Le chat', answer: '🐈', options: ['🐕', '🐈', '🦜'], instruction: 'Les animaux' },
    { id: 'fr0-m26', type: 'Match', question: 'L’oiseau', answer: '🦜', options: ['🐕', '🐈', '🦜'], instruction: 'Les animaux' },
    { id: 'fr0-m27', type: 'Match', question: 'Le cheval', answer: '🐎', options: ['🐎', '🐄', '🐷'], instruction: 'Les animaux' },
    { id: 'fr0-m28', type: 'Match', question: 'La vache', answer: '🐄', options: ['🐎', '🐄', '🐷'], instruction: 'Les animals' },
    { id: 'fr0-m29', type: 'Match', question: 'Le cochon', answer: '🐷', options: ['🐎', '🐄', '🐷'], instruction: 'Les animals' },
    { id: 'fr0-m30', type: 'Match', question: 'La pomme', answer: '🍎', options: ['🍎', '🍌', '🍐'], instruction: 'La nourriture' },
    { id: 'fr0-m31', type: 'Match', question: 'La banane', answer: '🍌', options: ['🍎', '🍌', '🍐'], instruction: 'La nourriture' },
    { id: 'fr0-m32', type: 'Match', question: 'La poire', answer: '🍐', options: ['🍎', '🍌', '🍐'], instruction: 'La nourriture' },
    { id: 'fr0-m33', type: 'Match', question: 'Le pain', answer: '🍞', options: ['🍞', '🍕', '🍳'], instruction: 'La nourriture' },
    { id: 'fr0-m34', type: 'Match', question: 'La pizza', answer: '🍕', options: ['🍞', '🍕', '🍳'], instruction: 'La nourriture' },
    { id: 'fr0-m35', type: 'Match', question: 'L’oeuf', answer: '🍳', options: ['🍞', '🍕', '🍳'], instruction: 'La nourriture' },
    { id: 'fr0-m36', type: 'Match', question: 'La voiture', answer: '🚗', options: ['🚗', '🚲', '✈️'], instruction: 'Transport' },
    { id: 'fr0-m37', type: 'Match', question: 'Le vélo', answer: '🚲', options: ['🚗', '🚲', '✈️'], instruction: 'Transport' },
    { id: 'fr0-m38', type: 'Match', question: 'L’avion', answer: '✈️', options: ['🚗', '🚲', '✈️'], instruction: 'Transport' },
    { id: 'fr0-m39', type: 'Match', question: 'Le train', answer: '🚆', options: ['🚆', '🚢', '🚀'], instruction: 'Transport' },
    { id: 'fr0-m40', type: 'Match', question: 'Le bateau', answer: '🚢', options: ['🚆', '🚢', '🚀'], instruction: 'Transport' },
    { id: 'fr0-m41', type: 'Match', question: 'La fusée', answer: '🚀', options: ['🚆', '🚢', '🚀'], instruction: 'Transport' },
    { id: 'fr0-m42', type: 'Match', question: 'La maison', answer: '🏠', options: ['🏠', '🌳', '🌸'], instruction: 'Vocabulaire' },
    { id: 'fr0-m43', type: 'Match', question: 'L’arbre', answer: '🌳', options: ['🏠', '🌳', '🌸'], instruction: 'Vocabulaire' },
    { id: 'fr0-m44', type: 'Match', question: 'La fleur', answer: '🌸', options: ['🏠', '🌳', '🌸'], instruction: 'Vocabulaire' },
    { id: 'fr0-m45', type: 'Match', question: 'Le soleil', answer: '☀️', options: ['☀️', '🌧️', '❄️'], instruction: 'La nature' },
    { id: 'fr0-m46', type: 'Match', question: 'La pluie', answer: '🌧️', options: ['☀️', '🌧️', '❄️'], instruction: 'La nature' },
    { id: 'fr0-m47', type: 'Match', question: 'La neige', answer: '❄️', options: ['☀️', '🌧️', '❄️'], instruction: 'La nature' },
    { id: 'fr0-m48', type: 'Match', question: 'Le garçon', answer: 'Dreng', options: ['Dreng', 'Pige', 'Baby'], instruction: 'Les gens' },
    { id: 'fr0-m49', type: 'Match', question: 'La fille', answer: 'Pige', options: ['Dreng', 'Pige', 'Baby'], instruction: 'Les gens' },
    { id: 'fr0-m50', type: 'Match', question: 'Le bébé', answer: 'Baby', options: ['Dreng', 'Pige', 'Baby'], instruction: 'Les gens' },
    { id: 'fr0-m51', type: 'Match', question: 'Bonjour', answer: 'Goddag', options: ['Goddag', 'Hav en god dag', 'Farvel'], instruction: 'Salutations' },
  ],
  1: [
    { id: 'fr1-m1', type: 'Match', question: 'Maman', answer: 'Mor', options: ['Mor', 'Far', 'Bror'], instruction: 'La famille' },
    { id: 'fr1-m2', type: 'Match', question: 'Papa', answer: 'Far', options: ['Mor', 'Far', 'Bror'], instruction: 'La famille' },
    { id: 'fr1-m3', type: 'Match', question: 'Un chat', answer: '🐈', options: ['🐈', '🐕', '🐟'], instruction: 'Les animaux' },
    { id: 'fr1-m4', type: 'Match', question: 'Un chien', answer: '🐕', options: ['🐈', '🐕', '🐟'], instruction: 'Les animaux' },
    { id: 'fr1-m5', type: 'Match', question: 'Un poisson', answer: '🐟', options: ['🐈', '🐕', '🐟'], instruction: 'Les animaux' },
    { id: 'fr1-m6', type: 'Match', question: 'Quatre', answer: '4', options: ['4', '5', '6'], instruction: 'Les nombres' },
    { id: 'fr1-m7', type: 'Match', question: 'Cinq', answer: '5', options: ['4', '5', '6'], instruction: 'Les nombres' },
    { id: 'fr1-m8', type: 'Match', question: 'Six', answer: '6', options: ['4', '5', '6'], instruction: 'Les nombres' },
    { id: 'fr1-m9', type: 'Match', question: 'Le soleil', answer: '☀️', options: ['☀️', '🌙', '☁️'], instruction: 'La nature' },
    { id: 'fr1-m10', type: 'Match', question: 'La lune', answer: '🌙', options: ['☀️', '🌙', '☁️'], instruction: 'La nature' },
    { id: 'fr1-m11', type: 'Match', question: 'Le frère', answer: 'Bror', options: ['Bror', 'Sœur', 'Gram-père'], instruction: 'La famille' },
    { id: 'fr1-m12', type: 'Match', question: 'La sœur', answer: 'Søster', options: ['Bror', 'Sœur', 'Gram-père'], instruction: 'La famille' },
    { id: 'fr1-m13', type: 'Match', question: 'Le grand-père', answer: 'Bedstefar', options: ['Bror', 'Sœur', 'Grand-père'], instruction: 'La famille' },
    { id: 'fr1-m14', type: 'Match', question: 'La grand-mère', answer: 'Bedstemor', options: ['Bedstemor', 'Tante', 'Onkel'], instruction: 'La famille' },
    { id: 'fr1-m15', type: 'Match', question: 'La main', answer: '👋', options: ['👋', '👣', '👀'], instruction: 'Le corps' },
    { id: 'fr1-m16', type: 'Match', question: 'Le pied', answer: '👣', options: ['👋', '👣', '👀'], instruction: 'Le corps' },
    { id: 'fr1-m17', type: 'Match', question: 'L’oeil', answer: '👀', options: ['👋', '👣', '👀'], instruction: 'Le corps' },
    { id: 'fr1-m18', type: 'Match', question: 'La bouche', answer: '👄', options: ['👄', '👃', '👂'], instruction: 'Le corps' },
    { id: 'fr1-m19', type: 'Match', question: 'Le nez', answer: '👃', options: ['👄', '👃', '👂'], instruction: 'Le corps' },
    { id: 'fr1-m20', type: 'Match', question: 'L’oreille', answer: '👂', options: ['👄', '👃', '👂'], instruction: 'Le corps' },
    { id: 'fr1-m21', type: 'Match', question: 'Onze', answer: '11', options: ['11', '12', '13'], instruction: 'Les nombres' },
    { id: 'fr1-m22', type: 'Match', question: 'Douze', answer: '12', options: ['11', '12', '13'], instruction: 'Les nombres' },
    { id: 'fr1-m23', type: 'Match', question: 'Treize', answer: '13', options: ['11', '12', '13'], instruction: 'Les nombres' },
    { id: 'fr1-m24', type: 'Match', question: 'Quatorze', answer: '14', options: ['14', '15', '16'], instruction: 'Les nombres' },
    { id: 'fr1-m25', type: 'Match', question: 'Quinze', answer: '15', options: ['14', '15', '16'], instruction: 'Les nombres' },
    { id: 'fr1-m26', type: 'Match', question: 'Seize', answer: '16', options: ['14', '15', '16'], instruction: 'Les nombres' },
    { id: 'fr1-m27', type: 'Match', question: 'Dix-sept', answer: '17', options: ['17', '18', '19'], instruction: 'Les nombres' },
    { id: 'fr1-m28', type: 'Match', question: 'Dix-huit', answer: '18', options: ['17', '18', '19'], instruction: 'Les nombres' },
    { id: 'fr1-m29', type: 'Match', question: 'Dix-neuf', answer: '19', options: ['17', '18', '19'], instruction: 'Les nombres' },
    { id: 'fr1-m30', type: 'Match', question: 'Vingt', answer: '20', options: ['10', '20', '30'], instruction: 'Les nombres' },
    { id: 'fr1-m31', type: 'Match', question: 'Le fromage', answer: '🧀', options: ['🧀', '🥚', '🥛'], instruction: 'La nourriture' },
    { id: 'fr1-m32', type: 'Match', question: 'L’oeuf', answer: '🥚', options: ['🧀', '🥚', '🥛'], instruction: 'La nourriture' },
    { id: 'fr1-m33', type: 'Match', question: 'Le lait', answer: '🥛', options: ['🧀', '🥚', '🥛'], instruction: 'La nourriture' },
    { id: 'fr1-m34', type: 'Match', question: 'Le jus', answer: '🧃', options: ['🧃', '☕', '🥤'], instruction: 'Les boissons' },
    { id: 'fr1-m35', type: 'Match', question: 'Le café', answer: '☕', options: ['🧃', '☕', '🥤'], instruction: 'Les boissons' },
    { id: 'fr1-m36', type: 'Match', question: 'L’eau', answer: '💧', options: ['💧', '☕', '🍷'], instruction: 'Les boissons' },
    { id: 'fr1-m37', type: 'Match', question: 'Le lion', answer: '🦁', options: ['🦁', '🐯', '🐘'], instruction: 'Les animaux' },
    { id: 'fr1-m38', type: 'Match', question: 'Le tigre', answer: '🐯', options: ['🦁', '🐯', '🐘'], instruction: 'Les animals' },
    { id: 'fr1-m39', type: 'Match', question: 'L’éléphant', answer: '🐘', options: ['🦁', '🐯', '🐘'], instruction: 'Les animals' },
    { id: 'fr1-m40', type: 'Match', question: 'La girafe', answer: '🦒', options: ['🦒', '🐒', '🦓'], instruction: 'Les animals' },
    { id: 'fr1-m41', type: 'Match', question: 'Le singe', answer: '🐒', options: ['🦒', '🐒', '🦓'], instruction: 'Les animals' },
    { id: 'fr1-m42', type: 'Match', question: 'L’herbe', answer: 'Græs', options: ['Græs', 'Træ', 'Blomst'], instruction: 'La nature' },
    { id: 'fr1-m43', type: 'Match', question: 'L’arbre', answer: 'Træ', options: ['Græs', 'Træ', 'Blomst'], instruction: 'La nature' },
    { id: 'fr1-m44', type: 'Match', question: 'La fleur', answer: 'Blomst', options: ['Græs', 'Træ', 'Blomst'], instruction: 'La nature' },
    { id: 'fr1-m45', type: 'Match', question: 'Le ciel', answer: 'Himmel', options: ['Himmel', 'Sky', 'Stjerne'], instruction: 'La nature' },
    { id: 'fr1-m46', type: 'Match', question: 'Le nuage', answer: 'Sky', options: ['Himmel', 'Sky', 'Stjerne'], instruction: 'La nature' },
    { id: 'fr1-m47', type: 'Match', question: 'L’étoile', answer: 'Stjerne', options: ['Himmel', 'Sky', 'Stjerne'], instruction: 'La nature' },
    { id: 'fr1-m48', type: 'Match', question: 'Bonjour', answer: 'Goddag', options: ['Goddag', 'Godnat', 'Ses'], instruction: 'Salutations' },
    { id: 'fr1-m49', type: 'Match', question: 'Bonne nuit', answer: 'Godnat', options: ['Goddag', 'Godnat', 'Ses'], instruction: 'Salutations' },
    { id: 'fr1-m50', type: 'Match', question: 'Au revoir', answer: 'Farvel', options: ['Goddag', 'Godnat', 'Farvel'], instruction: 'Salutations' },
    { id: 'fr1-m51', type: 'Match', question: 'S’il vous plaît', answer: 'Vær så venlig', options: ['Vær så venlig', 'Tak', 'Velbekomme'], instruction: 'Politesse' },
  ],
  2: [
    { id: 'fr2-m1', type: 'Match', question: 'La maison', answer: 'Huset', options: ['Huset', 'Skolen', 'Haven'], instruction: 'Les lieux' },
    { id: 'fr2-m2', type: 'Match', question: 'L’école', answer: 'Skolen', options: ['Huset', 'Skolen', 'Haven'], instruction: 'Les lieux' },
    { id: 'fr2-m3', type: 'Match', question: 'Le jardin', answer: 'Haven', options: ['Huset', 'Skolen', 'Haven'], instruction: 'Les lieux' },
    { id: 'fr2-m4', type: 'Match', question: 'La cuisine', answer: 'Køkkenet', options: ['Køkkenet', 'Værelset', 'Stuen'], instruction: 'Les pièces' },
    { id: 'fr2-m5', type: 'Match', question: 'La chambre', answer: 'Værelset', options: ['Køkkenet', 'Værelset', 'Stuen'], instruction: 'Les pièces' },
    { id: 'fr2-m6', type: 'Match', question: 'La salle de bain', answer: 'Badeværelset', options: ['Køkkenet', 'Badeværelset', 'Stuen'], instruction: 'Les pièces' },
    { id: 'fr2-m7', type: 'Match', question: 'Le salon', answer: 'Stuen', options: ['Køkkenet', 'Værelset', 'Stuen'], instruction: 'Les pièces' },
    { id: 'fr2-m8', type: 'Match', question: 'Le printemps', answer: 'Foråret', options: ['Foråret', 'Sommeren', 'Vinteren'], instruction: 'Les saisons' },
    { id: 'fr2-m9', type: 'Match', question: 'L’été', answer: 'Sommeren', options: ['Foråret', 'Sommeren', 'Vinteren'], instruction: 'Les saisons' },
    { id: 'fr2-m10', type: 'Match', question: 'La pluie', answer: '🌧️', options: ['🌧️', '☀️', '❄️'], instruction: 'La nature' },
  ],
  3: [
    { id: 'fr3-m1', type: 'Match', question: 'Lundi', answer: 'Mandag', options: ['Mandag', 'Tirsdag', 'Onsdag'], instruction: 'Les jours' },
    { id: 'fr3-m2', type: 'Match', question: 'Mardi', answer: 'Tirsdag', options: ['Mandag', 'Tirsdag', 'Onsdag'], instruction: 'Les days' },
    { id: 'fr3-m3', type: 'Match', question: 'Mercredi', answer: 'Onsdag', options: ['Mandag', 'Tirsdag', 'Onsdag'], instruction: 'Les days' },
    { id: 'fr3-m4', type: 'Match', question: 'Jeudi', answer: 'Torsdag', options: ['Torsdag', 'Fredag', 'Lørdag'], instruction: 'Les days' },
    { id: 'fr3-m5', type: 'Match', question: 'Vendredi', answer: 'Fredag', options: ['Torsdag', 'Fredag', 'Lørdag'], instruction: 'Les days' },
    { id: 'fr3-m6', type: 'Match', question: 'Samedi', answer: 'Lørdag', options: ['Torsdag', 'Fredag', 'Lørdag'], instruction: 'Les days' },
    { id: 'fr3-m7', type: 'Match', question: 'Dimanche', answer: 'Søndag', options: ['Torsdag', 'Fredag', 'Søndag'], instruction: 'Les days' },
    { id: 'fr3-m8', type: 'Match', question: 'Onze', answer: '11', options: ['11', '12', '13'], instruction: 'Les nombres' },
    { id: 'fr3-m9', type: 'Match', question: 'Douze', answer: '12', options: ['11', '12', '13'], instruction: 'Les nombres' },
    { id: 'fr3-m10', type: 'Match', question: 'Treize', answer: '13', options: ['11', '12', '13'], instruction: 'Les nombres' },
    { id: 'fr3-m11', type: 'Match', question: 'Quatorze', answer: '14', options: ['14', '15', '16'], instruction: 'Les nombres' },
    { id: 'fr3-m12', type: 'Match', question: 'Quinze', answer: '15', options: ['14', '15', '16'], instruction: 'Les nombres' },
    { id: 'fr3-m13', type: 'Match', question: 'Seize', answer: '16', options: ['14', '15', '16'], instruction: 'Les nombres' },
    { id: 'fr3-m14', type: 'Match', question: 'Dix-sept', answer: '17', options: ['17', '18', '19'], instruction: 'Les nombres' },
    { id: 'fr3-m15', type: 'Match', question: 'Dix-huit', answer: '18', options: ['17', '18', '19'], instruction: 'Les nombres' },
    { id: 'fr3-m16', type: 'Match', question: 'Dix-neuf', answer: '19', options: ['17', '18', '19'], instruction: 'Les nombres' },
    { id: 'fr3-m17', type: 'Match', question: 'Vingt', answer: '20', options: ['10', '20', '30'], instruction: 'Les nombres' },
    { id: 'fr3-m18', type: 'Match', question: 'Janvier', answer: 'Januar', options: ['Januar', 'Februar', 'Mars'], instruction: 'Les mois' },
    { id: 'fr3-m19', type: 'Match', question: 'Février', answer: 'Februar', options: ['Januar', 'Februar', 'Mars'], instruction: 'Les mois' },
    { id: 'fr3-m20', type: 'Match', question: 'Mars', answer: 'Marts', options: ['Januar', 'Februar', 'Marts'], instruction: 'Les mois' },
    { id: 'fr3-m21', type: 'Match', question: 'Avril', answer: 'April', options: ['Avril', 'Mai', 'Juin'], instruction: 'Les mois' },
    { id: 'fr3-m22', type: 'Match', question: 'Mai', answer: 'Maj', options: ['Avril', 'Mai', 'Juin'], instruction: 'Les mois' },
    { id: 'fr3-m23', type: 'Match', question: 'Juin', answer: 'Juni', options: ['Avril', 'Mai', 'Juin'], instruction: 'Les mois' },
    { id: 'fr3-m24', type: 'Match', question: 'Juillet', answer: 'Juli', options: ['Juillet', 'Août', 'Septembre'], instruction: 'Les mois' },
    { id: 'fr3-m25', type: 'Match', question: 'Août', answer: 'August', options: ['Juillet', 'Août', 'Septembre'], instruction: 'Les mois' },
    { id: 'fr3-m26', type: 'Match', question: 'Septembre', answer: 'September', options: ['Juillet', 'Août', 'Septembre'], instruction: 'Les mois' },
    { id: 'fr3-m27', type: 'Match', question: 'Octobre', answer: 'Oktober', options: ['Octobre', 'Novembre', 'Décembre'], instruction: 'Les mois' },
    { id: 'fr3-m28', type: 'Match', question: 'Novembre', answer: 'November', options: ['Octobre', 'Novembre', 'Décembre'], instruction: 'Les mois' },
    { id: 'fr3-m29', type: 'Match', question: 'Décembre', answer: 'December', options: ['Octobre', 'Novembre', 'Décembre'], instruction: 'Les mois' },
    { id: 'fr3-m30', type: 'Match', question: 'Il fait beau', answer: 'Det er godt vejr', options: ['Det er godt vejr', 'Det regner', 'Det sner'], instruction: 'La météo' },
    { id: 'fr3-m31', type: 'Match', question: 'Il pleut', answer: 'Det regner', options: ['Det er godt vejr', 'Det regner', 'Det sner'], instruction: 'La météo' },
    { id: 'fr3-m32', type: 'Match', question: 'Il neige', answer: 'Det sner', options: ['Det er godt vejr', 'Det regner', 'Det sner'], instruction: 'La météo' },
    { id: 'fr3-m33', type: 'Match', question: 'Le soleil', answer: '☀️', options: ['☀️', '☁️', '❄️'], instruction: 'La météo' },
    { id: 'fr3-m34', type: 'Match', question: 'Le nuage', answer: '☁️', options: ['☀️', '☁️', '❄️'], instruction: 'La météo' },
    { id: 'fr3-m35', type: 'Match', question: 'Aujourd’hui', answer: 'I dag', options: ['I dag', 'I går', 'I morgen'], instruction: 'Le temps' },
    { id: 'fr3-m36', type: 'Match', question: 'Hier', answer: 'I går', options: ['I dag', 'I går', 'I morgen'], instruction: 'Le temps' },
    { id: 'fr3-m37', type: 'Match', question: 'Demain', answer: 'I morgen', options: ['I dag', 'I går', 'I morgen'], instruction: 'Le temps' },
    { id: 'fr3-m38', type: 'Match', question: 'Maintenant', answer: 'Nu', options: ['Nu', 'Senere', 'Aldrig'], instruction: 'Le temps' },
    { id: 'fr3-m39', type: 'Match', question: 'Plus tard', answer: 'Senere', options: ['Nu', 'Senere', 'Aldrig'], instruction: 'Le temps' },
    { id: 'fr3-m40', type: 'Match', question: 'Ici', answer: 'Her', options: ['Her', 'Der', 'Overalt'], instruction: 'Les directions' },
    { id: 'fr3-m41', type: 'Match', question: 'Là', answer: 'Der', options: ['Her', 'Der', 'Overalt'], instruction: 'Les directions' },
    { id: 'fr3-m42', type: 'Match', question: 'À gauche', answer: 'Til venstre', options: ['Til venstre', 'Til højre', 'Lige ud'], instruction: 'Les directions' },
    { id: 'fr3-m43', type: 'Match', question: 'À droite', answer: 'Til højre', options: ['Til venstre', 'Til højre', 'Lige ud'], instruction: 'Les directions' },
    { id: 'fr3-m44', type: 'Match', question: 'Tout droit', answer: 'Lige ud', options: ['Til venstre', 'Til højre', 'Lige ud'], instruction: 'Les directions' },
    { id: 'fr3-m45', type: 'Match', question: 'Regarder', answer: 'Se / Kigge', options: ['Se', 'Høre', 'Føle'], instruction: 'Les verbes' },
    { id: 'fr3-m46', type: 'Match', question: 'Écouter', answer: 'Høre / Lytte', options: ['Se', 'Høre', 'Føle'], instruction: 'Les verbes' },
    { id: 'fr3-m47', type: 'Match', question: 'Sentir', answer: 'Føle / Lugte', options: ['Se', 'Høre', 'Føle'], instruction: 'Les verbes' },
    { id: 'fr3-m48', type: 'Match', question: 'Vouloir', answer: 'Ville', options: ['Ville', 'Kunne', 'Skulle'], instruction: 'Les verbes' },
    { id: 'fr3-m49', type: 'Match', question: 'Pouvoir', answer: 'Kunne', options: ['Ville', 'Kunne', 'Skulle'], instruction: 'Les verbes' },
    { id: 'fr3-m50', type: 'Match', question: 'Devoir', answer: 'Skulle / Burde', options: ['Ville', 'Kunne', 'Skulle'], instruction: 'Les verbes' },
    { id: 'fr3-m51', type: 'Match', question: 'Savoir', answer: 'Vide', options: ['Vide', 'Tro', 'Tænke'], instruction: 'Les verbes' },
  ],
  4: [
    { id: 'fr4-m1', type: 'Match', question: 'Le pain', answer: '🍞', options: ['🍞', '🥐', '🥖'], instruction: 'La nourriture' },
    { id: 'fr4-m2', type: 'Match', question: 'La baguette', answer: '🥖', options: ['🍞', '🥐', '🥖'], instruction: 'La nourriture' },
    { id: 'fr4-m3', type: 'Match', question: 'Le fromage', answer: '🧀', options: ['🧀', '🥚', '🥛'], instruction: 'La nourriture' },
    { id: 'fr4-m4', type: 'Match', question: 'Le lait', answer: '🥛', options: ['🧀', '🥚', '🥛'], instruction: 'La nourriture' },
    { id: 'fr4-m5', type: 'Match', question: 'L’oeuf', answer: '🥚', options: ['🧀', '🥚', '🥛'], instruction: 'La nourriture' },
    { id: 'fr4-m6', type: 'Match', question: 'Le livre', answer: 'Bogen', options: ['Bogen', 'Blyanten', 'Tasken'], instruction: 'L’école' },
    { id: 'fr4-m7', type: 'Match', question: 'Le crayon', answer: 'Blyanten', options: ['Bogen', 'Blyanten', 'Tasken'], instruction: 'L’école' },
    { id: 'fr4-m8', type: 'Match', question: 'Le sac', answer: 'Tasken', options: ['Bogen', 'Blyanten', 'Tasken'], instruction: 'L’école' },
    { id: 'fr4-m9', type: 'Match', question: 'La table', answer: 'Bordet', options: ['Bordet', 'Stolen', 'Vinduet'], instruction: 'L’école' },
    { id: 'fr4-m10', type: 'Match', question: 'La chaise', answer: 'Stolen', options: ['Bordet', 'Stolen', 'Vinduet'], instruction: 'L’école' },
    { id: 'fr4-m11', type: 'Match', question: 'Le stylo', answer: 'Kuglepennen', options: ['Kuglepennen', 'Linealen', 'Viskelæderet'], instruction: 'L’école' },
    { id: 'fr4-m12', type: 'Match', question: 'La règle', answer: 'Linealen', options: ['Kuglepennen', 'Linealen', 'Viskelæderet'], instruction: 'L’école' },
    { id: 'fr4-m13', type: 'Match', question: 'La gomme', answer: 'Viskelæderet', options: ['Kuglepennen', 'Linealen', 'Viskelæderet'], instruction: 'L’école' },
    { id: 'fr4-m14', type: 'Match', question: 'La fenêtre', answer: 'Vinduet', options: ['Vinduet', 'Døren', 'Væggen'], instruction: 'L’école' },
    { id: 'fr4-m15', type: 'Match', question: 'La porte', answer: 'Døren', options: ['Vinduet', 'Døren', 'Væggen'], instruction: 'L’école' },
    { id: 'fr4-m16', type: 'Match', question: 'Le mur', answer: 'Væggen', options: ['Vinduet', 'Døren', 'Væggen'], instruction: 'L’école' },
    { id: 'fr4-m17', type: 'Match', question: 'Le professeur', answer: 'Læreren', options: ['Læreren', 'Eleven', 'Rektoren'], instruction: 'L’école' },
    { id: 'fr4-m18', type: 'Match', question: 'L’élève', answer: 'Eleven', options: ['Læreren', 'Eleven', 'Rektoren'], instruction: 'L’école' },
    { id: 'fr4-m19', type: 'Match', question: 'Le manteau', answer: 'Frakken', options: ['Frakken', 'Skjorten', 'Bukserne'], instruction: 'Les vêtements' },
    { id: 'fr4-m20', type: 'Match', question: 'Le pull', answer: 'Trøjen', options: ['Frakken', 'Trøjen', 'Bukserne'], instruction: 'Les vêtements' },
    { id: 'fr4-m21', type: 'Match', question: 'Les chaussettes', answer: 'Strømperne', options: ['Strømperne', 'Skoene', 'Støvlerne'], instruction: 'Les vêtements' },
    { id: 'fr4-m22', type: 'Match', question: 'Les chaussures', answer: 'Skoene', options: ['Strømperne', 'Skoene', 'Støvlerne'], instruction: 'Les vêtements' },
    { id: 'fr4-m23', type: 'Match', question: 'Regarder la télé', answer: 'Se tv', options: ['Se tv', 'Høre musik', 'Læse en bog'], instruction: 'Les hobbys' },
    { id: 'fr4-m24', type: 'Match', question: 'Écouter de la musique', answer: 'Høre musik', options: ['Se tv', 'Høre musik', 'Læse en bog'], instruction: 'Les hobbys' },
    { id: 'fr4-m25', type: 'Match', question: 'Lire un livre', answer: 'Læse en bog', options: ['Se tv', 'Høre musik', 'Læse en bog'], instruction: 'Les hobbys' },
    { id: 'fr4-m26', type: 'Match', question: 'Le dessert', answer: 'Desserten', options: ['Forret', 'Hovedret', 'Dessert'], instruction: 'La nourriture' },
    { id: 'fr4-m27', type: 'Match', question: 'Le gâteau', answer: 'Kagen', options: ['Kage', 'Is', 'Slik'], instruction: 'La nourriture' },
    { id: 'fr4-m28', type: 'Match', question: 'La glace', answer: 'Isen', options: ['Kage', 'Is', 'Slik'], instruction: 'La nourriture' },
    { id: 'fr4-m29', type: 'Match', question: 'Le bonbon', answer: 'Slikket', options: ['Kage', 'Is', 'Slik'], instruction: 'La nourriture' },
    { id: 'fr4-m30', type: 'Match', question: 'Le chocolat', answer: 'Chokoladen', options: ['Chokolade', 'Kaffe', 'The'], instruction: 'La nourriture' },
    { id: 'fr4-m31', type: 'Match', question: 'La viande', answer: 'Kødet', options: ['Kød', 'Fisk', 'Grøntsager'], instruction: 'La nourriture' },
    { id: 'fr4-m32', type: 'Match', question: 'Le poisson', answer: 'Fisken', options: ['Kød', 'Fisk', 'Grøntsager'], instruction: 'La nourriture' },
    { id: 'fr4-m33', type: 'Match', question: 'Les légumes', answer: 'Grøntsagerne', options: ['Kød', 'Fisk', 'Grøntsager'], instruction: 'La nourriture' },
    { id: 'fr4-m34', type: 'Match', question: 'Acheter', answer: 'Købe', options: ['Købe', 'Sælge', 'Bytte'], instruction: 'Les verbes' },
    { id: 'fr4-m35', type: 'Match', question: 'Vendre', answer: 'Sælge', options: ['Købe', 'Sælge', 'Bytte'], instruction: 'Les verbes' },
    { id: 'fr4-m36', type: 'Match', question: 'Préparer', answer: 'Forberede / Tilberede', options: ['Forberede', 'Spise', 'Drikke'], instruction: 'Les verbes' },
    { id: 'fr4-m37', type: 'Match', question: 'Cuisiner', answer: 'Lave mad', options: ['Lave mad', 'Vaske op', 'Rydde op'], instruction: 'Les verbes' },
    { id: 'fr4-m38', type: 'Match', question: 'Nettoyer', answer: 'Rengøre', options: ['Rengøre', 'Svone', 'Lege'], instruction: 'Les verbes' },
    { id: 'fr4-m39', type: 'Match', question: 'Laver', answer: 'Vaske', options: ['Vaske', 'Tørre', 'Stryge'], instruction: 'Les verbes' },
    { id: 'fr4-m40', type: 'Match', question: 'Vite', answer: 'Hurtigt', options: ['Hurtigt', 'Langsomt', 'Nu'], instruction: 'Les adverbes' },
    { id: 'fr4-m41', type: 'Match', question: 'Lentement', answer: 'Langsomt', options: ['Hurtigt', 'Langsomt', 'Nu'], instruction: 'Les adverbes' },
    { id: 'fr4-m42', type: 'Match', question: 'Très', answer: 'Meget', options: ['Meget', 'Lidt', 'Nok'], instruction: 'Les adverbes' },
    { id: 'fr4-m43', type: 'Match', question: 'Beaucoup', answer: 'Meget (mængde)', options: ['Meget', 'Lidt', 'Nok'], instruction: 'Les adverbes' },
    { id: 'fr4-m44', type: 'Match', question: 'Un peu', answer: 'Lidt', options: ['Meget', 'Lidt', 'Nok'], instruction: 'Les adverbes' },
    { id: 'fr4-m45', type: 'Match', question: 'Toujours', answer: 'Altid', options: ['Altid', 'Aldrig', 'Ofte'], instruction: 'Les adverbes' },
    { id: 'fr4-m46', type: 'Match', question: 'Souvent', answer: 'Ofte', options: ['Altid', 'Aldrig', 'Ofte'], instruction: 'Les adverbes' },
    { id: 'fr4-m47', type: 'Match', question: 'Parfois', answer: 'Sommetider', options: ['Altid', 'Aldrig', 'Sommetider'], instruction: 'Les adverbes' },
    { id: 'fr4-m48', type: 'Match', question: 'Jamais', answer: 'Aldrig', options: ['Altid', 'Aldrig', 'Ofte'], instruction: 'Les adverbes' },
    { id: 'fr4-m49', type: 'Match', question: 'Pourquoi', answer: 'Hvorfor', options: ['Hvorfor', 'Fordi', 'Hvem'], instruction: 'Les mots questions' },
    { id: 'fr4-m50', type: 'Match', question: 'Parce que', answer: 'Fordi', options: ['Hvorfor', 'Fordi', 'Hvem'], instruction: 'Les mots questions' },
    { id: 'fr4-m51', type: 'Match', question: 'Qui', answer: 'Hvem', options: ['Hvorfor', 'Fordi', 'Hvem'], instruction: 'Les mots questions' },
  ],
  5: [
    { id: 'fr5-m1', type: 'Match', question: 'Le printemps', answer: 'Forår', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Les saisons' },
    { id: 'fr5-m2', type: 'Match', question: 'L’été', answer: 'Sommer', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Les seasons' },
    { id: 'fr5-m3', type: 'Match', question: 'L’automne', answer: 'Efterår', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Les seasons' },
    { id: 'fr5-m4', type: 'Match', question: 'L’hiver', answer: 'Vinter', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Les seasons' },
    { id: 'fr5-m5', type: 'Match', question: 'Janvier', answer: 'Januar', options: ['Januar', 'Februar', 'Marts'], instruction: 'Les mois' },
    { id: 'fr5-m6', type: 'Match', question: 'Mars', answer: 'Marts', options: ['Januar', 'Februar', 'Marts'], instruction: 'Les mois' },
    { id: 'fr5-m7', type: 'Match', question: 'Mai', answer: 'Maj', options: ['April', 'Maj', 'Juni'], instruction: 'Les mois' },
    { id: 'fr5-m8', type: 'Match', question: 'Juillet', answer: 'Juli', options: ['Juni', 'Juli', 'August'], instruction: 'Les mois' },
    { id: 'fr5-m9', type: 'Match', question: 'Septembre', answer: 'September', options: ['September', 'Oktober', 'November'], instruction: 'Les mois' },
    { id: 'fr5-m10', type: 'Match', question: 'Décembre', answer: 'December', options: ['Oktober', 'November', 'December'], instruction: 'Les mois' },
    { id: 'fr5-m11', type: 'Match', question: 'Février', answer: 'Februar', options: ['Januar', 'Februar', 'Marts'], instruction: 'Les mois' },
    { id: 'fr5-m12', type: 'Match', question: 'Avril', answer: 'April', options: ['April', 'Maj', 'Juni'], instruction: 'Les mois' },
    { id: 'fr5-m13', type: 'Match', question: 'Juin', answer: 'Juni', options: ['April', 'Maj', 'Juni'], instruction: 'Les mois' },
    { id: 'fr5-m14', type: 'Match', question: 'Août', answer: 'August', options: ['Juni', 'Juli', 'August'], instruction: 'Les mois' },
    { id: 'fr5-m15', type: 'Match', question: 'Okobre', answer: 'Oktober', options: ['September', 'Oktober', 'November'], instruction: 'Les mois' },
    { id: 'fr5-m16', type: 'Match', question: 'Novembre', answer: 'November', options: ['September', 'Oktober', 'November'], instruction: 'Les mois' },
    { id: 'fr5-m17', type: 'Match', question: 'Le football', answer: '⚽', options: ['⚽', '🎾', '🏀'], instruction: 'Le sport' },
    { id: 'fr5-m18', type: 'Match', question: 'Le tennis', answer: '🎾', options: ['⚽', '🎾', '🏀'], instruction: 'Le sport' },
    { id: 'fr5-m19', type: 'Match', question: 'Le basket', answer: '🏀', options: ['⚽', '🎾', '🏀'], instruction: 'Le sport' },
    { id: 'fr5-m20', type: 'Match', question: 'Le vélo', answer: '🚲', options: ['🚲', '⛸️', '🛹'], instruction: 'Le sport' },
    { id: 'fr5-m21', type: 'Match', question: 'Le patinage', answer: '⛸️', options: ['🚲', '⛸️', '🛹'], instruction: 'Le sport' },
    { id: 'fr5-m22', type: 'Match', question: 'Le skate', answer: 'Skateboard', options: ['🚲', '⛸️', '🛹'], instruction: 'Le sport' },
    { id: 'fr5-m23', type: 'Match', question: 'La piscine', answer: 'Svømmehal', options: ['Svømmehal', 'Gymnastiksal', 'Stadion'], instruction: 'Le sport' },
    { id: 'fr5-m24', type: 'Match', question: 'Le piano', answer: '🎹', options: ['🎹', '🎸', '🎻'], instruction: 'La musique' },
    { id: 'fr5-m25', type: 'Match', question: 'La guitare', answer: '🎸', options: ['🎹', '🎸', '🎻'], instruction: 'La musique' },
    { id: 'fr5-m26', type: 'Match', question: 'Le violon', answer: '🎻', options: ['🎹', '🎸', '🎻'], instruction: 'La musique' },
    { id: 'fr5-m27', type: 'Match', question: 'La chanson', answer: 'Sangen', options: ['Sangen', 'Malingen', 'Dansen'], instruction: 'La musique' },
    { id: 'fr5-m28', type: 'Match', question: 'Content', answer: 'Glad', options: ['Glad', 'Trist', 'Gal'], instruction: 'Les émotions' },
    { id: 'fr5-m29', type: 'Match', question: 'Triste', answer: 'Trist', options: ['Glad', 'Trist', 'Gal'], instruction: 'Les émotions' },
    { id: 'fr5-m30', type: 'Match', question: 'Fâché', answer: 'Gal', options: ['Glad', 'Trist', 'Gal'], instruction: 'Les émotions' },
    { id: 'fr5-m31', type: 'Match', question: 'Sourire', answer: 'Smile', options: ['Smile', 'Græde', 'Grine'], instruction: 'Les émotions' },
    { id: 'fr5-m32', type: 'Match', question: 'Pleurer', answer: 'Græde', options: ['Smile', 'Græde', 'Grine'], instruction: 'Les émotions' },
    { id: 'fr5-m33', type: 'Match', question: 'Rire', answer: 'Grine', options: ['Smile', 'Græde', 'Grine'], instruction: 'Les émotions' },
    { id: 'fr5-m34', type: 'Match', question: 'La météo', answer: 'Vejret', options: ['Vejret', 'Tiden', 'Stedet'], instruction: 'La météo' },
    { id: 'fr5-m35', type: 'Match', question: 'Le vent', answer: 'Blæst', options: ['Blæst', 'Sol', 'Regn'], instruction: 'La météo' },
    { id: 'fr5-m36', type: 'Match', question: 'L’orage', answer: 'Tordensvejr', options: ['Tordensvejr', 'Sne', 'Tåge'], instruction: 'La météo' },
    { id: 'fr5-m37', type: 'Match', question: 'La brume', answer: 'Tåge', options: ['Tordensvejr', 'Sne', 'Tåge'], instruction: 'La météo' },
    { id: 'fr5-m38', type: 'Match', question: 'Vouloir', answer: 'Ville', instruction: 'Verbe', options: ['Ville', 'Kunne', 'Skulle'] },
    { id: 'fr5-m39', type: 'Match', question: 'Pouvoir', answer: 'Kunne', instruction: 'Verbe', options: ['Ville', 'Kunne', 'Skulle'] },
    { id: 'fr5-m40', type: 'Match', question: 'Savoir', answer: 'Vide', instruction: 'Verbe', options: ['Vide', 'Tro', 'Tænke'] },
    { id: 'fr5-m41', type: 'Match', question: 'Penser', answer: 'Tænke', options: ['Tænke', 'Drømme', 'Håbe'], instruction: 'Les verbes' },
    { id: 'fr5-m42', type: 'Match', question: 'Rêver', answer: 'Drømme', options: ['Tænke', 'Drømme', 'Håbe'], instruction: 'Les verbes' },
    { id: 'fr5-m43', type: 'Match', question: 'Espérer', answer: 'Håbe', options: ['Tænke', 'Drømme', 'Håbe'], instruction: 'Les verbes' },
    { id: 'fr5-m44', type: 'Match', question: 'Moi', answer: 'Mig', options: ['Mig', 'Dig', 'Ham'], instruction: 'Pronoms' },
    { id: 'fr5-m45', type: 'Match', question: 'Toi', answer: 'Dig', options: ['Mig', 'Dig', 'Ham'], instruction: 'Pronoms' },
    { id: 'fr5-m46', type: 'Match', question: 'Lui', answer: 'Ham', options: ['Mig', 'Dig', 'Ham'], instruction: 'Pronoms' },
    { id: 'fr5-m47', type: 'Match', question: 'Elle', answer: 'Hende', options: ['Mig', 'Dig', 'Hende'], instruction: 'Pronoms' },
    { id: 'fr5-m48', type: 'Match', question: 'Nous', answer: 'Os', options: ['Os', 'Jer', 'Dem'], instruction: 'Pronoms' },
    { id: 'fr5-m49', type: 'Match', question: 'Vous', answer: 'Jer', options: ['Os', 'Jer', 'Dem'], instruction: 'Pronoms' },
    { id: 'fr5-m50', type: 'Match', question: 'Eux', answer: 'Dem', options: ['Os', 'Jer', 'Dem'], instruction: 'Pronoms' },
    { id: 'fr5-m51', type: 'Match', question: 'Avec', answer: 'Med', options: ['Med', 'Uden', 'For'], instruction: 'Prépositions' },
  ],
  6: [
    { id: 'fr6-m1', type: 'Match', question: 'Bonjour', answer: 'Goddag', options: ['Goddag', 'Farvel', 'Tak', 'Jeg hedder...'], instruction: 'Hvad betyder hilsnen?' },
    { id: 'fr6-m2', type: 'Match', question: 'Un chat', answer: 'En kat', options: ['En hund', 'En kat', 'En fugl', 'En hest'], instruction: 'Oversæt dyret' },
    { id: 'fr6-m3', type: 'Match', question: 'Un chien', answer: 'En hund', options: ['En kat', 'En hund', 'En mus', 'En kanin'], instruction: 'Un animal de compagnie' },
    { id: 'fr6-m4', type: 'Match', question: 'Salut!', answer: 'Hej!', options: ['Hej!', 'Farvel!', 'Tak!'], instruction: 'Hilsner' },
    { id: 'fr6-m5', type: 'Match', question: 'Je m’appelle Alba', answer: 'Jeg hedder Alba', options: ['Jeg hedder Alba', 'Jeg er Alba', 'Her er Alba'], instruction: 'Présentation' },
    { id: 'fr6-m6', type: 'Match', question: 'Enchanté', answer: 'Hyggeligt at møde dig', options: ['Farvel', 'Hyggeligt at møde dig'], instruction: 'Politesse' },
    { id: 'fr6-m7', type: 'Match', question: 'Voici ma chambre', answer: 'Her er mit værelse', options: ['Her er mit værelse', 'Her er mit hus', 'Her er min seng'], instruction: 'Ma chambre' },
    { id: 'fr6-m8', type: 'Match', question: 'Voilà ma famille', answer: 'Dér er min familie', options: ['Dér er min familie', 'Dér er min ven', 'Dér er min skole'], instruction: 'Ma famille' },
    { id: 'fr6-m9', type: 'Match', question: 'Le marché', answer: 'Markedet', options: ['Skolen', 'Markedet', 'Bageren'], instruction: 'Ville' },
    { id: 'fr6-m10', type: 'Match', question: 'La mode', answer: 'Mode', options: ['Mode', 'Sport', 'Mad'], instruction: 'Vocabulaire' },
    { id: 'fr6-m11', type: 'Match', question: 'Où habites-tu ?', answer: 'Hvor bor du?', options: ['Hvor bor du?', 'Hvad hedder du?', 'Hvordan går det?'], instruction: 'Questions' },
    { id: 'fr6-m12', type: 'Match', question: 'Comment ça va ?', answer: 'Hvordan går det?', options: ['Hvor bor du?', 'Hvordan går det?', 'Hvad laver du?'], instruction: 'Questions' },
    { id: 'fr6-m13', type: 'Match', question: 'Quel âge as-tu ?', answer: 'Hvor gammel er du?', options: ['Hvor gammel er du?', 'Hvad hedder du?', 'Hvor bor du?'], instruction: 'Questions' },
    { id: 'fr6-m14', type: 'Match', question: 'La cuisine', answer: 'Køkkenet', options: ['Køkkenet', 'Badeværelset', 'Stuen'], instruction: 'Maison' },
    { id: 'fr6-m15', type: 'Match', question: 'Le salon', answer: 'Stuen', options: ['Køkkenet', 'Badeværelset', 'Stuen'], instruction: 'Maison' },
    { id: 'fr6-m16', type: 'Match', question: 'La salle de bain', answer: 'Badeværelset', options: ['Køkkenet', 'Badeværelset', 'Stuen'], instruction: 'Maison' },
    { id: 'fr6-m17', type: 'Match', question: 'Le jardin', answer: 'Haven', options: ['Haven', 'Gangen', 'Garagen'], instruction: 'Maison' },
    { id: 'fr6-m18', type: 'Match', question: 'Le canapé', answer: 'Sofaen', options: ['Sofaen', 'Lænestolen', 'Bordet'], instruction: 'Meubles' },
    { id: 'fr6-m19', type: 'Match', question: 'Le fauteuil', answer: 'Lænestolen', options: ['Sofaen', 'Lænestolen', 'Bordet'], instruction: 'Meubles' },
    { id: 'fr6-m20', type: 'Match', question: 'La ville', answer: 'Byen', options: ['Byen', 'Landet', 'Skoven'], instruction: 'Lieux' },
    { id: 'fr6-m21', type: 'Match', question: 'La campagne', answer: 'Landet / Markerne', options: ['Byen', 'Landet', 'Skoven'], instruction: 'Lieux' },
    { id: 'fr6-m22', type: 'Match', question: 'La forêt', answer: 'Skoven', options: ['Byen', 'Landet', 'Skoven'], instruction: 'Lieux' },
    { id: 'fr6-m23', type: 'Match', question: 'Le musée', answer: 'Museet', options: ['Museet', 'Teatret', 'Biografen'], instruction: 'Ville' },
    { id: 'fr6-m24', type: 'Match', question: 'Le théâtre', answer: 'Teatret', options: ['Museet', 'Teatret', 'Biografen'], instruction: 'Ville' },
    { id: 'fr6-m25', type: 'Match', question: 'Le cinéma', answer: 'Biografen', options: ['Museet', 'Teatret', 'Biografen'], instruction: 'Ville' },
    { id: 'fr6-m26', type: 'Match', question: 'Le bus', answer: 'Bussen', options: ['Bussen', 'Toget', 'Bilen'], instruction: 'Transport' },
    { id: 'fr6-m27', type: 'Match', question: 'Le train', answer: 'Toget', options: ['Bussen', 'Toget', 'Bilen'], instruction: 'Transport' },
    { id: 'fr6-m28', type: 'Match', question: 'Le vélo', answer: 'Cyklen', options: ['Bussen', 'Toget', 'Cyklen'], instruction: 'Transport' },
    { id: 'fr6-m29', type: 'Match', question: 'La voiture', answer: 'Bilen', options: ['Bussen', 'Toget', 'Bilen'], instruction: 'Transport' },
    { id: 'fr6-m30', type: 'Match', question: 'Chaud', answer: 'Varmt', options: ['Varmt', 'Koldt', 'Lunkent'], instruction: 'Adjectifs' },
    { id: 'fr6-m31', type: 'Match', question: 'Froid', answer: 'Koldt', options: ['Varmt', 'Koldt', 'Lunkent'], instruction: 'Adjectifs' },
    { id: 'fr6-m32', type: 'Match', question: 'Nouveau', answer: 'Ny', options: ['Ny', 'Gammel', 'Anden'], instruction: 'Adjectifs' },
    { id: 'fr6-m33', type: 'Match', question: 'Vieux', answer: 'Gammel', options: ['Ny', 'Gammel', 'Anden'], instruction: 'Adjectifs' },
    { id: 'fr6-m34', type: 'Match', question: 'Rapide', answer: 'Hurtig', options: ['Hurtig', 'Langsom', 'Stille'], instruction: 'Adjectifs' },
    { id: 'fr6-m35', type: 'Match', question: 'Lent', answer: 'Langsom', options: ['Hurtig', 'Langsom', 'Stille'], instruction: 'Adjectifs' },
    { id: 'fr6-m36', type: 'Match', question: 'Le petit-déjeuner', answer: 'Morgenmad', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Repas' },
    { id: 'fr6-m37', type: 'Match', question: 'Le déjeuner', answer: 'Frokost', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Repas' },
    { id: 'fr6-m38', type: 'Match', question: 'Le dîner', answer: 'Aftensmad', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Repas' },
    { id: 'fr6-m39', type: 'Match', question: 'Manger', answer: 'Spise', options: ['Spise', 'Drikke', 'Sove'], instruction: 'Verbes' },
    { id: 'fr6-m40', type: 'Match', question: 'Boire', answer: 'Drikke', options: ['Spise', 'Drikke', 'Sove'], instruction: 'Verbes' },
    { id: 'fr6-m41', type: 'Match', question: 'Parler', answer: 'Tale', options: ['Tale', 'Læse', 'Skrive'], instruction: 'Verbes' },
    { id: 'fr6-m42', type: 'Match', question: 'Écrire', answer: 'Skrive', options: ['Tale', 'Læse', 'Skrive'], instruction: 'Verbes' },
    { id: 'fr6-m43', type: 'Match', question: 'Lire', answer: 'Læse', options: ['Tale', 'Læse', 'Skrive'], instruction: 'Verbes' },
    { id: 'fr6-m44', type: 'Match', question: 'Aimer', answer: 'Elske / Godt kunne lide', options: ['Elske', 'Hade', 'Glemme'], instruction: 'Verbes' },
    { id: 'fr6-m45', type: 'Match', question: 'Détester', answer: 'Hade', options: ['Elske', 'Hade', 'Glemme'], instruction: 'Verbes' },
    { id: 'fr6-m46', type: 'Match', question: 'La musique', answer: 'Musikken', options: ['Musikken', 'Dansen', 'Kunsten'], instruction: 'Loisirs' },
    { id: 'fr6-m47', type: 'Match', question: 'Le sport', answer: 'Sporten', options: ['Musikken', 'Sporten', 'Kunsten'], instruction: 'Loisirs' },
    { id: 'fr6-m48', type: 'Match', question: 'La danse', answer: 'Dansen', options: ['Musikken', 'Dansen', 'Kunsten'], instruction: 'Loisirs' },
    { id: 'fr6-m49', type: 'Match', question: 'Travailler', answer: 'Arbejde', options: ['Arbejde', 'Lege', 'Sove'], instruction: 'Verbes' },
    { id: 'fr6-m50', type: 'Match', question: 'Étudier', answer: 'Studere / Læse', options: ['Arbejde', 'Studere', 'Sove'], instruction: 'Verbes' },
    { id: 'fr6-m51', type: 'Match', question: 'Finir', answer: 'Afslutte / Blive færdig', options: ['Starte', 'Afslutte', 'Fortsætte'], instruction: 'Verbes' },
  ],
  7: [
    { id: 'fr7-m1', type: 'Match', question: 'Joyeux Noël', answer: 'Glædelig jul', options: ['Glædelig jul', 'Godt nytår', 'Tillykke', 'God påske'], instruction: 'Hilsen ved højtider' },
    { id: 'fr7-m2', type: 'Match', question: 'Le réveillon', answer: 'Juleaften (fest)', options: ['Juleaften (fest)', 'Påske', 'Fødselsdag'], instruction: 'Kultur' },
    { id: 'fr7-m3', type: 'Match', question: 'Faire du ski', answer: 'Stå på ski', options: ['Svømme', 'Stå på ski', 'Spille fodbold', 'Løbe'], instruction: 'Vacances' },
    { id: 'fr7-m4', type: 'Match', question: 'Le Petit Prince', answer: 'St. Exupéry', options: ['St. Exupéry', 'Monet', 'Ribery'], instruction: 'Littérature' },
    { id: 'fr7-m5', type: 'Match', question: 'Monet', answer: 'Peintre', options: ['Peintre', 'Chanteur', 'Sportif'], instruction: 'Art' },
    { id: 'fr7-m6', type: 'Match', question: 'La boulangerie', answer: 'Bageren', options: ['Bageren', 'Slagteren', 'Torvet'], instruction: 'Magasins' },
    { id: 'fr7-m7', type: 'Match', question: 'Le croissant', answer: '🥐', options: ['🥐', '🥖', '🥪'], instruction: 'Nourriture' },
    { id: 'fr7-m8', type: 'Match', question: 'Vingt', answer: '20', options: ['20', '30', '40'], instruction: 'Les nombres' },
    { id: 'fr7-m9', type: 'Match', question: 'Trente', answer: '30', options: ['20', '30', '40'], instruction: 'Les nombres' },
    { id: 'fr7-m10', type: 'Match', question: 'Quarante', answer: '40', options: ['20', '30', '40'], instruction: 'Les nombres' },
    { id: 'fr7-m11', type: 'Match', question: 'Cinquante', answer: '50', options: ['50', '60', '70'], instruction: 'Les nombres' },
    { id: 'fr7-m12', type: 'Match', question: 'Soixante', answer: '60', options: ['50', '60', '70'], instruction: 'Les nombres' },
    { id: 'fr7-m13', type: 'Match', question: 'Soixante-dix', answer: '70', options: ['70', '80', '90'], instruction: 'Les nombres' },
    { id: 'fr7-m14', type: 'Match', question: 'Quatre-vingts', answer: '80', options: ['70', '80', '90'], instruction: 'Les nombres' },
    { id: 'fr7-m15', type: 'Match', question: 'Quatre-vingt-dix', answer: '90', options: ['80', '90', '100'], instruction: 'Les nombres' },
    { id: 'fr7-m16', type: 'Match', question: 'Cent', answer: '100', options: ['80', '90', '100'], instruction: 'Les nombres' },
    { id: 'fr7-m17', type: 'Match', question: 'Mille', answer: '1000', options: ['100', '500', '1000'], instruction: 'Les nombres' },
    { id: 'fr7-m18', type: 'Match', question: 'Paris', answer: 'La France', options: ['La France', 'L’Espagne', 'L’Italie'], instruction: 'Géographie' },
    { id: 'fr7-m19', type: 'Match', question: 'La Tour Eiffel', answer: '🗼', options: ['🗼', '🏛️', '🏰'], instruction: 'Culture' },
    { id: 'fr7-m20', type: 'Match', question: 'Le Louvre', answer: '🏛️', options: ['🗼', '🏛️', '🏰'], instruction: 'Culture' },
    { id: 'fr7-m21', type: 'Match', question: 'Notre-Dame', answer: '⛪', options: ['🗼', '🏛️', '⛪'], instruction: 'Culture' },
    { id: 'fr7-m22', type: 'Match', question: 'Un pantalon', answer: 'Bukser', options: ['Bukser', 'Skjorte', 'Kjole'], instruction: 'Les vêtements' },
    { id: 'fr7-m23', type: 'Match', question: 'Une jupe', answer: 'En nederdel', options: ['Bukser', 'Nederdel', 'Skjorte'], instruction: 'Les vêtements' },
    { id: 'fr7-m24', type: 'Match', question: 'Un chapeau', answer: 'En hat', options: ['And', 'En hat', 'En sko'], instruction: 'Les vêtements' },
    { id: 'fr7-m25', type: 'Match', question: 'Porter', answer: 'Bære / Have på', options: ['Bære', 'Tage', 'Give'], instruction: 'Les verbes' },
    { id: 'fr7-m26', type: 'Match', question: 'Le voyage', answer: 'Rejsen', options: ['Rejsen', 'Skolen', 'Arbejdet'], instruction: 'Les vacances' },
    { id: 'fr7-m27', type: 'Match', question: 'La plage', answer: 'Stranden', options: ['Stranden', 'Skoven', 'Bjerget'], instruction: 'Les vacances' },
    { id: 'fr7-m28', type: 'Match', question: 'La mer', answer: 'Havet', options: ['Stranden', 'Havet', 'Søen'], instruction: 'Les vacances' },
    { id: 'fr7-m29', type: 'Match', question: 'La montagne', answer: 'Bjerget', options: ['Bjerget', 'Dalen', 'Marken'], instruction: 'Les vacances' },
    { id: 'fr7-m30', type: 'Match', question: 'Faire du vélo', answer: 'Cykle', options: ['Cykle', 'Løbe', 'Svømme'], instruction: 'Loisirs' },
    { id: 'fr7-m31', type: 'Match', question: 'Nager', answer: 'Svømme', options: ['Cykle', 'Løbe', 'Svømme'], instruction: 'Loisirs' },
    { id: 'fr7-m32', type: 'Match', question: 'Courir', answer: 'Løbe', options: ['Cykle', 'Løbe', 'Svømme'], instruction: 'Loisirs' },
    { id: 'fr7-m33', type: 'Match', question: 'Écrire', answer: 'Skrive', options: ['Skrive', 'Læse', 'Tegne'], instruction: 'Loisirs' },
    { id: 'fr7-m34', type: 'Match', question: 'Dessiner', answer: 'Tegne', options: ['Skrive', 'Læse', 'Tegne'], instruction: 'Loisirs' },
    { id: 'fr7-m35', type: 'Match', question: 'Bonne route', answer: 'God tur', options: ['God tur', 'Godnat', 'Goddag'], instruction: 'Salutations' },
    { id: 'fr7-m36', type: 'Match', question: 'Tenez', answer: 'Værsgo (hvis man rækker noget)', options: ['Værsgo', 'Tak', 'Hej'], instruction: 'Politesse' },
    { id: 'fr7-m37', type: 'Match', question: 'Voici', answer: 'Her er', options: ['Her er', 'Der er', 'Hvad er'], instruction: 'Politesse' },
    { id: 'fr7-m38', type: 'Match', question: 'Voilà', answer: 'Dér er (det)', options: ['Her er', 'Dér er', 'Hvad er'], instruction: 'Politesse' },
    { id: 'fr7-m39', type: 'Match', question: 'Est-ce que', answer: '(Spørgende indledning)', options: ['Spørgsmål', 'Svar', 'Sætning'], instruction: 'Grammaire' },
    { id: 'fr7-m40', type: 'Match', question: 'Je suis', answer: 'Jeg er', options: ['Jeg er', 'Du er', 'Han er'], instruction: 'Être' },
    { id: 'fr7-m41', type: 'Match', question: 'Tu es', answer: 'Du er', options: ['Jeg er', 'Du er', 'Han er'], instruction: 'Être' },
    { id: 'fr7-m42', type: 'Match', question: 'Il est', answer: 'Han er', options: ['Jeg er', 'Du er', 'Han er'], instruction: 'Être' },
    { id: 'fr7-m43', type: 'Match', question: 'Elle est', answer: 'Hende er', options: ['Hende er', 'Jeg er', 'Vi er'], instruction: 'Être' },
    { id: 'fr7-m44', type: 'Match', question: 'Nous sommes', answer: 'Vi er', options: ['Vi er', 'I er', 'De er'], instruction: 'Être' },
    { id: 'fr7-m45', type: 'Match', question: 'Vous êtes', answer: 'I er / De er', options: ['Vi er', 'I er', 'De er'], instruction: 'Être' },
    { id: 'fr7-m46', type: 'Match', question: 'Ils sont', answer: 'De er (mask.)', options: ['Vi er', 'I er', 'De er'], instruction: 'Être' },
    { id: 'fr7-m47', type: 'Match', question: 'Elles sont', answer: 'De er (fem.)', options: ['Vi er', 'I er', 'De er'], instruction: 'Être' },
    { id: 'fr7-m48', type: 'Match', question: 'J’ai', answer: 'Jeg har', options: ['Jeg har', 'Du har', 'Han har'], instruction: 'Avoir' },
    { id: 'fr7-m49', type: 'Match', question: 'Tu as', answer: 'Du har', options: ['Jeg har', 'Du har', 'Han har'], instruction: 'Avoir' },
    { id: 'fr7-m50', type: 'Match', question: 'Il a', answer: 'Han har', options: ['Jeg har', 'Du har', 'Han har'], instruction: 'Avoir' },
    { id: 'fr7-m51', type: 'Match', question: 'Elle a', answer: 'Hende har', options: ['Jeg har', 'Du har', 'Hende har'], instruction: 'Avoir' },
  ],
  8: [
    { id: 'fr8-m1', type: 'Match', question: 'Stromae', answer: 'Musicien', options: ['Acteur', 'Musicien', 'Designer'], instruction: 'Personnalité' },
    { id: 'fr8-m2', type: 'Match', question: 'Louane Emera', answer: 'Chanteuse', options: ['Chanteuse', 'Actrice', 'Danseuse'], instruction: 'Portrait' },
    { id: 'fr8-m3', type: 'Match', question: 'Audrey Tautou', answer: 'Actrice', options: ['Chanteuse', 'Actrice', 'Designer'], instruction: 'Portrait' },
    { id: 'fr8-m4', type: 'Match', question: 'Coco Chanel', answer: 'Mode', options: ['Mode', 'Sport', 'Musique'], instruction: 'Portrait' },
    { id: 'fr8-m5', type: 'Match', question: 'La Suisse', answer: 'Schweiz', options: ['Schweiz', 'Belgien', 'Canada'], instruction: 'Géographie' },
    { id: 'fr8-m6', type: 'Match', question: 'Le Québec', answer: 'Québec', options: ['Québec', 'Paris', 'Lyon'], instruction: 'Géographie' },
    { id: 'fr8-m7', type: 'Match', question: 'Le message', answer: 'Beskeden', options: ['Beskeden', 'Opkaldet', 'Mailen'], instruction: 'Média' },
    { id: 'fr8-m8', type: 'Match', question: 'Le journal', answer: 'Avisen', options: ['Avisen', 'Bogen', 'Magasinet'], instruction: 'Média' },
    { id: 'fr8-m9', type: 'Match', question: 'La publicité', answer: 'Reklamen', options: ['Reklamen', 'Nyheden', 'Dokumentaren'], instruction: 'Média' },
    { id: 'fr8-m10', type: 'Match', question: 'L’information', answer: 'Nyheden', options: ['Nyheden', 'Underholdningen', 'Sporten'], instruction: 'Média' },
    { id: 'fr8-m11', type: 'Match', question: 'Travailler', answer: 'Arbejde', options: ['Arbejde', 'Lege', 'Sove'], instruction: 'Les métiers' },
    { id: 'fr8-m12', type: 'Match', question: 'Le médecin', answer: 'Lægen', options: ['Lægen', 'Sygeplejersken', 'Patienten'], instruction: 'Les métiers' },
    { id: 'fr8-m13', type: 'Match', question: 'Le policier', answer: 'Politibetjenten', options: ['Betjenten', 'Tyven', 'Dommeren'], instruction: 'Les métiers' },
    { id: 'fr8-m14', type: 'Match', question: 'Le pompier', answer: 'Brandmanden', options: ['Brandmanden', 'Lægen', 'Læreren'], instruction: 'Les métiers' },
    { id: 'fr8-m15', type: 'Match', question: 'Le serveur', answer: 'Tjeneren', options: ['Tjeneren', 'Kokken', 'Gæsten'], instruction: 'Les métiers' },
    { id: 'fr8-m16', type: 'Match', question: 'Le chômage', answer: 'Arbejdsløshed', options: ['Arbejdsløshed', 'Ansættelse', 'Ferie'], instruction: 'Société' },
    { id: 'fr8-m17', type: 'Match', question: 'Le salaire', answer: 'Lønnen', options: ['Lønnen', 'Skatten', 'Prisen'], instruction: 'Société' },
    { id: 'fr8-m18', type: 'Match', question: 'L’argent', answer: 'Pengene', options: ['Pengene', 'Guldet', 'Sølvet'], instruction: 'Société' },
    { id: 'fr8-m19', type: 'Match', question: 'Gagner', answer: 'Vinde / Tjene', options: ['Vinde', 'Tabe', 'Spille'], instruction: 'Les verbes' },
    { id: 'fr8-m20', type: 'Match', question: 'Perdre', answer: 'Tabe', options: ['Vinde', 'Tabe', 'Søge'], instruction: 'Les verbes' },
    { id: 'fr8-m21', type: 'Match', question: 'Chercher', answer: 'Søge / Lede efter', options: ['Søge', 'Finde', 'Glemme'], instruction: 'Les verbes' },
    { id: 'fr8-m22', type: 'Match', question: 'Trouver', answer: 'Finde', options: ['Søge', 'Finde', 'Glemme'], instruction: 'Les verbes' },
    { id: 'fr8-m23', type: 'Match', question: 'Le futur', answer: 'Fremtiden', options: ['Fremtiden', 'Fortiden', 'Nutiden'], instruction: 'Le temps' },
    { id: 'fr8-m24', type: 'Match', question: 'Le passé', answer: 'Fortiden', options: ['Fremtiden', 'Fortiden', 'Nutiden'], instruction: 'Le temps' },
    { id: 'fr8-m25', type: 'Match', question: 'Le présent', answer: 'Nutiden', options: ['Fremtiden', 'Fortiden', 'Nutiden'], instruction: 'Le temps' },
    { id: 'fr8-m26', type: 'Match', question: 'L’espoir', answer: 'Håbet', options: ['Håbet', 'Frygten', 'Glæden'], instruction: 'Émotions' },
    { id: 'fr8-m27', type: 'Match', question: 'La peur', answer: 'Frygten', options: ['Håbet', 'Frygten', 'Glæden'], instruction: 'Émotions' },
    { id: 'fr8-m28', type: 'Match', question: 'La colère', answer: 'Vreden', options: ['Vreden', 'Sorgen', 'Lykken'], instruction: 'Émotions' },
    { id: 'fr8-m29', type: 'Match', question: 'La haine', answer: 'Hadet', options: ['Hadet', 'Kærligheden', 'Venskabet'], instruction: 'Émotions' },
    { id: 'fr8-m30', type: 'Match', question: 'L’amour', answer: 'Kærligheden', options: ['Hadet', 'Kærligheden', 'Venskabet'], instruction: 'Émotions' },
    { id: 'fr8-m31', type: 'Match', question: 'La liberté', answer: 'Friheden', options: ['Friheden', 'Lighed', 'Broderskab'], instruction: 'Valeurs' },
    { id: 'fr8-m32', type: 'Match', question: 'L’égalité', answer: 'Lighed', options: ['Friheden', 'Lighed', 'Broderskab'], instruction: 'Valeurs' },
    { id: 'fr8-m33', type: 'Match', question: 'La fraternité', answer: 'Broderskab', options: ['Friheden', 'Lighed', 'Broderskab'], instruction: 'Valeurs' },
    { id: 'fr8-m34', type: 'Match', question: 'La paix', answer: 'Freden', options: ['Freden', 'Krigen', 'Konflikten'], instruction: 'Valeurs' },
    { id: 'fr8-m35', type: 'Match', question: 'La guerre', answer: 'Krigen', options: ['Freden', 'Krigen', 'Konflikten'], instruction: 'Valeurs' },
    { id: 'fr8-m36', type: 'Match', question: 'Le monde', answer: 'Verden', options: ['Verden', 'Landet', 'Byen'], instruction: 'Géographie' },
    { id: 'fr8-m37', type: 'Match', question: 'La terre', answer: 'Jorden', options: ['Jorden', 'Månen', 'Solen'], instruction: 'Géographie' },
    { id: 'fr8-m38', type: 'Match', question: 'L’environnement', answer: 'Miljøet', options: ['Miljøet', 'Klimaet', 'Naturen'], instruction: 'Société' },
    { id: 'fr8-m39', type: 'Match', question: 'La pollution', answer: 'Forureningen', options: ['Forureningen', 'Beskyttelsen', 'Rensningen'], instruction: 'Société' },
    { id: 'fr8-m40', type: 'Match', question: 'Protéger', answer: 'Beskytte', options: ['Beskytte', 'Ødelægge', 'Ændre'], instruction: 'Les verbes' },
    { id: 'fr8-m41', type: 'Match', question: 'Détruire', answer: 'Ødelægge', options: ['Beskytte', 'Ødelægge', 'Ændre'], instruction: 'Les verbes' },
    { id: 'fr8-m42', type: 'Match', question: 'Changer', answer: 'Ændre / Skifte', options: ['Beskytte', 'Ødelægge', 'Ændre'], instruction: 'Les verbes' },
    { id: 'fr8-m43', type: 'Match', question: 'Décider', answer: 'Beslutte', options: ['Beslutte', 'Tøve', 'Nægte'], instruction: 'Les verbes' },
    { id: 'fr8-m44', type: 'Match', question: 'Comprendre', answer: 'Forstå', options: ['Forstå', 'Glemme', 'Lære'], instruction: 'Les verbes' },
    { id: 'fr8-m45', type: 'Match', question: 'Apprendre', answer: 'Lære', options: ['Forstå', 'Glemme', 'Lære'], instruction: 'Les verbes' },
    { id: 'fr8-m46', type: 'Match', question: 'Oublier', answer: 'Glemme', options: ['Forstå', 'Glemme', 'Lære'], instruction: 'Les verbes' },
    { id: 'fr8-m47', type: 'Match', question: 'Se souvenir', answer: 'Huske', options: ['Glemme', 'Huske', 'Søge'], instruction: 'Les verbes' },
    { id: 'fr8-m48', type: 'Match', question: 'Voyager', answer: 'Rejse', options: ['Rejse', 'Blive', 'Flytte'], instruction: 'Les verbes' },
    { id: 'fr8-m49', type: 'Match', question: 'Partir', answer: 'Tage afsted', options: ['Rejse', 'Tage afsted', 'Ankomme'], instruction: 'Les verbes' },
    { id: 'fr8-m50', type: 'Match', question: 'Arriver', answer: 'Ankomme', options: ['Rejse', 'Tage afsted', 'Ankomme'], instruction: 'Les verbes' },
    { id: 'fr8-m51', type: 'Match', question: 'Rentrer', answer: 'Komme hjem', options: ['Komme hjem', 'Gå ud', 'Blive'], instruction: 'Les verbes' },
  ],
  9: [
    { id: 'fr9-m1', type: 'Match', question: 'Maître Gims', answer: 'Musique', options: ['Musique', 'Cinéma', 'Sport'], instruction: 'Portrait' },
    { id: 'fr9-m2', type: 'Match', question: 'Omar Sy', answer: 'Acteur', options: ['Acteur', 'Chanteur', 'Sportif'], instruction: 'Portrait' },
    { id: 'fr9-m3', type: 'Match', question: 'Intouchables', answer: 'Film', options: ['Film', 'Livre', 'Chanson'], instruction: 'Culture' },
    { id: 'fr9-m4', type: 'Match', question: 'Le Tour de France', answer: 'Cyclisme', options: ['Cyclisme', 'Foot', 'Tennis'], instruction: 'Sport' },
    { id: 'fr9-m5', type: 'Match', question: 'L’île Maurice', answer: 'Île francophone', options: ['Île francophone', 'Ville', 'Montagne'], instruction: 'Géographie' },
    { id: 'fr9-m6', type: 'Match', question: 'La démocratie', answer: 'Demokrati', options: ['Demokrati', 'Diktatur', 'Monarki'], instruction: 'Politique' },
    { id: 'fr9-m7', type: 'Match', question: 'La république', answer: 'Republik', options: ['Republik', 'Kongerige', 'Imperium'], instruction: 'Politique' },
    { id: 'fr9-m8', type: 'Match', question: 'Le government', answer: 'Regeringen', options: ['Regeringen', 'Oppositionen', 'Vælgerne'], instruction: 'Politique' },
    { id: 'fr9-m9', type: 'Match', question: 'L’élection', answer: 'Valget', options: ['Valget', 'Debatten', 'Loven'], instruction: 'Politique' },
    { id: 'fr9-m10', type: 'Match', question: 'Le citoyen', answer: 'Borgeren', options: ['Borgeren', 'Fremmede', 'Turisten'], instruction: 'Politique' },
    { id: 'fr9-m11', type: 'Match', question: 'Les droits de l’homme', answer: 'Menneskerettigheder', options: ['Privilegier', 'Menneskerettigheder', 'Pligter'], instruction: 'Société' },
    { id: 'fr9-m12', type: 'Match', question: 'La solidarité', answer: 'Solidaritet', options: ['Solidaritet', 'Egoisme', 'Konkurrence'], instruction: 'Société' },
    { id: 'fr9-m13', type: 'Match', question: 'L’immigration', answer: 'Indvandring', options: ['Indvandring', 'Udvandring', 'Rejse'], instruction: 'Société' },
    { id: 'fr9-m14', type: 'Match', question: 'La laïcité', answer: 'Sekularisme (adskillelse af kirke og stat)', options: ['Sekularisme', 'Religion', 'Tro'], instruction: 'Société / Culture' },
    { id: 'fr9-m15', type: 'Match', question: 'Le patrimoine', answer: 'Kulturarv', options: ['Kulturarv', 'Fremtid', 'Nutid'], instruction: 'Culture' },
    { id: 'fr9-m16', type: 'Match', question: 'L’héritage', answer: 'Arven', options: ['Arven', 'Gaven', 'Lånet'], instruction: 'Culture' },
    { id: 'fr9-m17', type: 'Match', question: 'La Francophonie', answer: 'Fransktalende lande', options: ['Frankrig', 'Europa', 'Fransktalende lande'], instruction: 'Géographie' },
    { id: 'fr9-m18', type: 'Match', question: 'Le Québec', answer: 'Canada (fransk del)', options: ['USA', 'Canada', 'Brasilien'], instruction: 'Géographie' },
    { id: 'fr9-m19', type: 'Match', question: 'Le Maghreb', answer: 'Nordafrika', options: ['Nordafrika', 'Sydafrika', 'Vestafrika'], instruction: 'Géographie' },
    { id: 'fr9-m20', type: 'Match', question: 'L’Union Européenne', answer: 'EU', options: ['EU', 'FN', 'NATO'], instruction: 'International' },
    { id: 'fr9-m21', type: 'Match', question: 'La science', answer: 'Videnskab', options: ['Videnskab', 'Kunst', 'Sport'], instruction: 'Savoir' },
    { id: 'fr9-m22', type: 'Match', question: 'La recherche', answer: 'Forskning', options: ['Forskning', 'Undervisning', 'Leg'], instruction: 'Savoir' },
    { id: 'fr9-m23', type: 'Match', question: 'L’astronomie', answer: 'Astronomi', options: ['Astronomi', 'Biologi', 'Fysik'], instruction: 'Science' },
    { id: 'fr9-m24', type: 'Match', question: 'La technologie', answer: 'Teknologi', options: ['Teknologi', 'Håndværk', 'Kunst'], instruction: 'Moderne' },
    { id: 'fr9-m25', type: 'Match', question: 'L’intelligence artificielle', answer: 'AI', options: ['AI', 'VR', 'Blockchain'], instruction: 'Moderne' },
    { id: 'fr9-m26', type: 'Match', question: 'Le progrès', answer: 'Fremskridt', options: ['Fremskridt', 'Tilbageskridt', 'Stilstand'], instruction: 'Moderne' },
    { id: 'fr9-m27', type: 'Match', question: 'L’avenir', answer: 'Fremtiden', options: ['Fremtiden', 'Fortiden', 'Nutiden'], instruction: 'Temps' },
    { id: 'fr9-m28', type: 'Match', question: 'Le destin', answer: 'Skæbnen', options: ['Skæbnen', 'Held', 'Uheld'], instruction: 'Abstrait' },
    { id: 'fr9-m29', type: 'Match', question: 'La vérité', answer: 'Sandheden', options: ['Sandheden', 'Løgnen', 'Tvivlen'], instruction: 'Abstrait' },
    { id: 'fr9-m30', type: 'Match', question: 'La justice', answer: 'Retfærdighed', options: ['Retfærdighed', 'Uretfærdighed', 'Straf'], instruction: 'Abstrait' },
    { id: 'fr9-m31', type: 'Match', question: 'L’honneur', answer: 'Ære', options: ['Ære', 'Skam', 'Stolthed'], instruction: 'Abstrait' },
    { id: 'fr9-m32', type: 'Match', question: 'Le courage', answer: 'Mod', options: ['Mod', 'Frygt', 'Fejhed'], instruction: 'Abstrait' },
    { id: 'fr9-m33', type: 'Match', question: 'La sagesse', answer: 'Visdom', options: ['Visdom', 'Dumhed', 'Vid'], instruction: 'Abstrait' },
    { id: 'fr9-m34', type: 'Match', question: 'L’espoir', answer: 'Håbet', options: ['Håbet', 'Fortvivlelsen', 'Tvivlen'], instruction: 'Abstrait' },
    { id: 'fr9-m35', type: 'Match', question: 'Persister', answer: 'Vedholde', options: ['Vedholde', 'Give op', 'Ændre'], instruction: 'Verbes' },
    { id: 'fr9-m36', type: 'Match', question: 'Améliorer', answer: 'Forbedre', options: ['Forbedre', 'Forværre', 'Beholde'], instruction: 'Verbes' },
    { id: 'fr9-m37', type: 'Match', question: 'Développer', answer: 'Udvikle', options: ['Udvikle', 'Afvikle', 'Stoppe'], instruction: 'Verbes' },
    { id: 'fr9-m38', type: 'Match', question: 'Analyser', answer: 'Analysere', options: ['Analysere', 'Syntetisere', 'Ignorere'], instruction: 'Verbes' },
    { id: 'fr9-m39', type: 'Match', question: 'Comparer', answer: 'Sammenligne', options: ['Sammenligne', 'Adskille', 'Forbinde'], instruction: 'Verbes' },
    { id: 'fr9-m40', type: 'Match', question: 'Expliquer', answer: 'Forklare', options: ['Forklare', 'Forvirre', 'Spørge'], instruction: 'Verbes' },
    { id: 'fr9-m41', type: 'Match', question: 'Justifier', answer: 'Retfærdiggøre', options: ['Retfærdiggøre', 'Nægte', 'Tvivle'], instruction: 'Verbes' },
    { id: 'fr9-m42', type: 'Match', question: 'S’exprimer', answer: 'Utrykke sig', options: ['Utrykke sig', 'Tie stille', 'Lytte'], instruction: 'Verbes' },
    { id: 'fr9-m43', type: 'Match', question: 'Convaincre', answer: 'Overbevise', options: ['Overbevise', 'Tvivle', 'Tro'], instruction: 'Verbes' },
    { id: 'fr9-m44', type: 'Match', question: 'Négocier', answer: 'Forhandle', options: ['Forhandle', 'Bestemme', 'Lyde'], instruction: 'Verbes' },
    { id: 'fr9-m45', type: 'Match', question: 'Partager', answer: 'Dele', options: ['Dele', 'Beholde', 'Sælge'], instruction: 'Verbes' },
    { id: 'fr9-m46', type: 'Match', question: 'Collaborer', answer: 'Samarbejde', options: ['Samarbejde', 'Modarbejde', 'Alene'], instruction: 'Verbes' },
    { id: 'fr9-m47', type: 'Match', question: 'Réussir', answer: 'Succes / Lykkes', options: ['Lykkes', 'Fejle', 'Prøve'], instruction: 'Verbes' },
    { id: 'fr9-m48', type: 'Match', question: 'Échouer', answer: 'Fejle', options: ['Lykkes', 'Fejle', 'Prøve'], instruction: 'Verbes' },
    { id: 'fr9-m49', type: 'Match', question: 'Tenter', answer: 'Forsøge', options: ['Forsøge', 'Gøre', 'Vide'], instruction: 'Verbes' },
    { id: 'fr9-m50', type: 'Match', question: 'Accomplir', answer: 'Fuldføre', options: ['Fuldføre', 'Starte', 'Pause'], instruction: 'Verbes' },
    { id: 'fr9-m51', type: 'Match', question: 'Rendre', answer: 'Give tilbage / Gøre', options: ['Give tilbage', 'Tage', 'Låne'], instruction: 'Verbes' },
  ],
};
