/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const SPANSK_MATCH: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'sp0-m1', type: 'Match', question: 'A', answer: '🍎', options: ['🍎', '🍐', '🍌', '🥕'], instruction: '¿Qué empieza por A?' },
    { id: 'sp0-m2', type: 'Match', question: 'B', answer: '🐻', options: ['🐻', '🐘', '🐒', '🐯'], instruction: '¿Qué empieza por B?' },
    { id: 'sp0-m3', type: 'Match', question: 'C', answer: '🐎', options: ['🐎', '🚗', '🚲', '🛴'], instruction: '¿Qué empieza por C (Caballo)?' },
    { id: 'sp0-m4', type: 'Match', question: 'D', answer: '🦕', options: ['🦕', '🐶', '🐭', '🐱'], instruction: '¿Qué empieza por D?' },
    { id: 'sp0-m5', type: 'Match', question: 'E', answer: '🐘', options: ['🐘', '🦒', '🦓', '🦘'], instruction: '¿Qué empieza por E?' },
    { id: 'sp0-m6', type: 'Match', question: 'F', answer: '🍓', options: ['🍓', '🦆', '🐔', '🐮'], instruction: '¿Qué empieza por F (Fresa)?' },
    { id: 'sp0-m7', type: 'Match', question: 'G', answer: '🐈', options: ['🐈', '🦁', '🐯', '🐻'], instruction: '¿Qué empieza por G (Gato)?' },
    { id: 'sp0-m8', type: 'Match', question: 'H', answer: '🥚', options: ['🥚', '🚗', '🚆', '🚢'], instruction: '¿Qué empieza por H (Huevo)?' },
    { id: 'sp0-m9', type: 'Match', question: 'I', answer: '🦎', options: ['🦎', '🍭', '🍰', '🍪'], instruction: '¿Qué empieza por I (Iguana)?' },
    { id: 'sp0-m10', type: 'Match', question: 'J', answer: '🦒', options: ['🦒', '🍏', '🍊', '🍋'], instruction: '¿Qué empieza por J (Jirafa)?' },
    { id: 'sp0-m11', type: 'Match', question: 'L', answer: '🦁', options: ['🦁', '🐩', '🐿️', '🐇'], instruction: '¿Qué empieza por L (León)?' },
    { id: 'sp0-m12', type: 'Match', question: 'M', answer: '🍎', options: ['🍎', '🦒', '🐘', '🦏'], instruction: '¿Qué empieza por M (Manzana)?' },
    { id: 'sp0-m13', type: 'Match', question: 'N', answer: '🍊', options: ['🍊', '☀️', '☁️', '🌧️'], instruction: '¿Qué empieza por N (Naranja)?' },
    { id: 'sp0-m14', type: 'Match', question: 'O', answer: '🐻', options: ['🐻', '👁️', '👂', '👄'], instruction: '¿Qué empieza por O (Oso)?' },
    { id: 'sp0-m15', type: 'Match', question: 'P', answer: '🐕', options: ['🐕', '🐡', '🐚', '🦀'], instruction: '¿Qué empieza por P (Perro)?' },
    { id: 'sp0-m16', type: 'Match', question: 'R', answer: '🐀', options: ['🐀', '🍎', '🍓', '🍋'], instruction: '¿Qué empieza por R (Ratón)?' },
    { id: 'sp0-m17', type: 'Match', question: 'S', answer: '☀️', options: ['☀️', '🕯️', '🔦', '💡'], instruction: '¿Qué empieza por S (Sol)?' },
    { id: 'sp0-m18', type: 'Match', question: 'T', answer: '🐢', options: ['🐢', '❄️', '🌈', '⚡'], instruction: '¿Qué empieza por T (Tortuga)?' },
    { id: 'sp0-m19', type: 'Match', question: 'U', answer: '🍇', options: ['🍇', '🚗', '🚲', '🛴'], instruction: '¿Qué empieza por U (Uva)?' },
    { id: 'sp0-m20', type: 'Match', question: 'V', answer: '🐄', options: ['🐄', '🕶️', '💍', '👜'], instruction: '¿Qué empieza por V (Vaca)?' },
    { id: 'sp0-m21', type: 'Match', question: 'Z', answer: '🥕', options: ['🥕', '🔥', '🌬️', '🌱'], instruction: '¿Qué empieza por Z (Zanahoria)?' },
    { id: 'sp0-m22', type: 'Match', question: 'Color: Rojo', answer: '🔴', options: ['🔴', '🔵', '🟢', '🟡'], instruction: '¿Qué color es?' },
    { id: 'sp0-m23', type: 'Match', question: 'Color: Azul', answer: '🔵', options: ['🔴', '🔵', '🟢', '🟡'], instruction: '¿Qué color es?' },
    { id: 'sp0-m24', type: 'Match', question: 'Color: Verde', answer: '🟢', options: ['🔴', '🔵', '🟢', '🟡'], instruction: '¿Qué color es?' },
    { id: 'sp0-m25', type: 'Match', question: 'Color: Amarillo', answer: '🟡', options: ['🔴', '🔵', '🟢', '🟡'], instruction: '¿Qué color es?' },
  ],
  1: [
    { id: 'sp1-m1', type: 'Match', question: 'Y', answer: 'y', options: ['y', 'yo', 'es', 'un'], instruction: 'Busca la palabra' },
    { id: 'sp1-m2', type: 'Match', question: 'Yo', answer: 'yo', options: ['yo', 'tú', 'él', 'ella'], instruction: 'Busca la palabra' },
    { id: 'sp1-m3', type: 'Match', question: 'Es', answer: 'es', options: ['es', 'fue', 'será', 'puede'], instruction: 'Busca la palabra' },
    { id: 'sp1-m4', type: 'Match', question: 'El', answer: 'el', options: ['el', 'la', 'los', 'las'], instruction: 'Busca la palabra' },
    { id: 'sp1-m5', type: 'Match', question: 'Un', answer: 'un', options: ['un', 'una', 'o', 'no'], instruction: 'Busca la palabra' },
    { id: 'sp1-m6', type: 'Match', question: 'Vocal', answer: 'A', options: ['A', 'B', 'C', 'D'], instruction: 'Busca la vocal' },
    { id: 'sp1-m7', type: 'Match', question: 'Vocal', answer: 'E', options: ['E', 'F', 'G', 'H'], instruction: 'Busca la vocal' },
    { id: 'sp1-m8', type: 'Match', question: 'Vocal', answer: 'I', options: ['I', 'J', 'K', 'L'], instruction: 'Busca la vocal' },
    { id: 'sp1-m9', type: 'Match', question: 'Vocal', answer: 'O', options: ['O', 'M', 'N', 'P'], instruction: 'Busca la vocal' },
    { id: 'sp1-m10', type: 'Match', question: 'Vocal', answer: 'U', options: ['U', 'X', 'Y', 'Z'], instruction: 'Busca la vocal' },
    { id: 'sp1-m11', type: 'Match', question: 'Opuesto: Grande', answer: 'Pequeño', options: ['Pequeño', 'Corto', 'Delgado'], instruction: 'Antónimos' },
    { id: 'sp1-m12', type: 'Match', question: 'Opuesto: Feliz', answer: 'Triste', options: ['Triste', 'Caliente', 'Enfermo'], instruction: 'Antónimos' },
    { id: 'sp1-m13', type: 'Match', question: 'Opuesto: Bueno', answer: 'Malo', options: ['Malo', 'Rápido', 'Lento'], instruction: 'Antónimos' },
    { id: 'sp1-m14', type: 'Match', question: 'Opuesto: Blanco', answer: 'Negro', options: ['Negro', 'Rojo', 'Azul'], instruction: 'Antónimos' },
    { id: 'sp1-m15', type: 'Match', question: 'Él', answer: 'él', options: ['él', 'ella', 'ellos', 'nosotros'], instruction: 'Busca la palabra' },
    { id: 'sp1-m16', type: 'Match', question: 'Ella', answer: 'ella', options: ['ella', 'él', 'usted', 'yo'], instruction: 'Busca la palabra' },
    { id: 'sp1-m17', type: 'Match', question: 'Nosotros', answer: 'nosotros', options: ['nosotros', 'vosotros', 'ellos', 'ustedes'], instruction: 'Busca la palabra' },
    { id: 'sp1-m18', type: 'Match', question: 'Puedo', answer: 'puedo', options: ['puedo', 'quiero', 'debo', 'tengo'], instruction: 'Busca la palabra' },
    { id: 'sp1-m19', type: 'Match', question: 'Quiero', answer: 'quiero', options: ['puedo', 'quiero', 'debo', 'tengo'], instruction: 'Busca la palabra' },
    { id: 'sp1-m20', type: 'Match', question: 'Tengo', answer: 'tengo', options: ['puedo', 'quiero', 'debo', 'tengo'], instruction: 'Busca la palabra' },
    { id: 'sp1-m21', type: 'Match', question: 'Número: 1', answer: 'Uno', options: ['Uno', 'Dos', 'Tres', 'Cuatro'], instruction: 'Números' },
    { id: 'sp1-m22', type: 'Match', question: 'Número: 2', answer: 'Dos', options: ['Uno', 'Dos', 'Tres', 'Cuatro'], instruction: 'Números' },
    { id: 'sp1-m23', type: 'Match', question: 'Número: 3', answer: 'Tres', options: ['Uno', 'Dos', 'Tres', 'Cuatro'], instruction: 'Números' },
    { id: 'sp1-m24', type: 'Match', question: 'Número: 4', answer: 'Cuatro', options: ['Uno', 'Dos', 'Tres', 'Cuatro'], instruction: 'Números' },
    { id: 'sp1-m25', type: 'Match', question: 'Número: 5', answer: 'Cinco', options: ['Cinco', 'Seis', 'Siete', 'Ocho'], instruction: 'Números' },
  ],
  2: [
    { id: 'sp2-m1', type: 'Match', question: 'La casa', answer: 'Huset', options: ['Huset', 'Skolen', 'Haven'], instruction: 'Lugares' },
    { id: 'sp2-m2', type: 'Match', question: 'La escuela', answer: 'Skolen', options: ['Huset', 'Skolen', 'Haven'], instruction: 'Lugares' },
    { id: 'sp2-m3', type: 'Match', question: 'El jardín', answer: 'Haven', options: ['Huset', 'Skolen', 'Haven'], instruction: 'Lugares' },
    { id: 'sp2-m4', type: 'Match', question: 'La cocina', answer: 'Køkkenet', options: ['Køkkenet', 'Værelset', 'Stuen'], instruction: 'Habitaciones' },
    { id: 'sp2-m5', type: 'Match', question: 'La habitación', answer: 'Værelset', options: ['Køkkenet', 'Værelset', 'Stuen'], instruction: 'Habitaciones' },
    { id: 'sp2-m6', type: 'Match', question: 'El baño', answer: 'Badeværelset', options: ['Køkkenet', 'Badeværelset', 'Stuen'], instruction: 'Habitaciones' },
    { id: 'sp2-m7', type: 'Match', question: 'El salón', answer: 'Stuen', options: ['Køkkenet', 'Værelset', 'Stuen'], instruction: 'Habitaciones' },
    { id: 'sp2-m8', type: 'Match', question: 'La primavera', answer: 'Foråret', options: ['Foråret', 'Sommeren', 'Invierno'], instruction: 'Estaciones' },
    { id: 'sp2-m9', type: 'Match', question: 'El verano', answer: 'Sommeren', options: ['Foråret', 'Sommeren', 'Invierno'], instruction: 'Estaciones' },
    { id: 'sp2-m10', type: 'Match', question: 'La lluvia', answer: '🌧️', options: ['🌧️', '☀️', '❄️'], instruction: 'Naturaleza' },
  ],
  3: [
    { id: 'sp3-m1', type: 'Match', question: 'Una vaca, dos...', answer: 'Vacas', options: ['Vacos', 'Vacas', 'Vaquitas'], instruction: 'Plural' },
    { id: 'sp3-m2', type: 'Match', question: 'Un niño, dos...', answer: 'Niños', options: ['Niña', 'Niños', 'Niñes'], instruction: 'Plural' },
    { id: 'sp3-m3', type: 'Match', question: 'Un libro, dos...', answer: 'Libros', options: ['Libros', 'Libres', 'Libras'], instruction: 'Plural' },
    { id: 'sp3-m4', type: 'Match', question: 'Bueno, mejor...', answer: 'Óptimo', options: ['Bueno', 'Mejor', 'Peor'], instruction: 'Grados' },
    { id: 'sp3-m5', type: 'Match', question: 'Grande, mayor...', answer: 'Máximo', options: ['Pequeño', 'Máximo', 'Grande'], instruction: 'Grados' },
    { id: 'sp3-m6', type: 'Match', question: 'Mucho, más...', answer: 'Muchísimo', options: ['Poco', 'Mucho', 'Muchísimo'], instruction: 'Grados' },
    { id: 'sp3-m7', type: 'Match', question: 'Sinónimo: Feliz', answer: 'Alegre', options: ['Triste', 'Alegre', 'Cansado'], instruction: 'Sinónimos' },
    { id: 'sp3-m8', type: 'Match', question: 'Sinónimo: Grande', answer: 'Enorme', options: ['Pequeño', 'Enorme', 'Estrecho'], instruction: 'Sinónimos' },
    { id: 'sp3-m9', type: 'Match', question: 'Sinónimo: Guapo', answer: 'Bello', options: ['Feo', 'Bello', 'Oscuro'], instruction: 'Sinónimos' },
    { id: 'sp3-m10', type: 'Match', question: 'Una casa, dos...', answer: 'Casas', options: ['Casas', 'Casos', 'Caser'], instruction: 'Plural' },
    { id: 'sp3-m11', type: 'Match', question: 'Sustantivo Propio', answer: 'España', options: ['España', 'País', 'Ciudad'], instruction: '¿Es un nombre propio?' },
    { id: 'sp3-m12', type: 'Match', question: 'Sustantivo Propio', answer: 'Madrid', options: ['Madrid', 'Puerto', 'Calle'], instruction: '¿Es un nombre propio?' },
    { id: 'sp3-m13', type: 'Match', question: 'Sustantivo Propio', answer: 'Juan', options: ['Juan', 'Chico', 'Hombre'], instruction: '¿Es un nombre propio?' },
    { id: 'sp3-m14', type: 'Match', question: 'Sustantivo Común', answer: 'Mesa', options: ['España', 'Mesa', 'Juan'], instruction: '¿Es un nombre común?' },
    { id: 'sp3-m15', type: 'Match', question: 'Sustantivo Común', answer: 'Perro', options: ['Madrid', 'Perro', 'Lunes'], instruction: '¿Es un nombre común?' },
    { id: 'sp3-m16', type: 'Match', question: 'Corre', answer: 'Presente', options: ['Presente', 'Pasado', 'Pretérito'], instruction: 'Conjugación' },
    { id: 'sp3-m17', type: 'Match', question: 'Corrió', answer: 'Pasado', options: ['Presente', 'Pasado', 'Futuro'], instruction: 'Conjugación' },
    { id: 'sp3-m18', type: 'Match', question: 'Correrá', answer: 'Futuro', options: ['Presente', 'Pasado', 'Futuro'], instruction: 'Conjugación' },
    { id: 'sp3-m19', type: 'Match', question: 'Él', answer: 'Pronombre', options: ['Sustantivo', 'Pronombre', 'Verbo'], instruction: 'Clase de palabra' },
    { id: 'sp3-m20', type: 'Match', question: 'Nosotros', answer: 'Pronombre', options: ['Sustantivo', 'Pronombre', 'Adjetivo'], instruction: 'Clase de palabra' },
    { id: 'sp3-m21', type: 'Match', question: 'Lunes', answer: 'Día', options: ['Mes', 'Día', 'Año'], instruction: 'Tiempo' },
    { id: 'sp3-m22', type: 'Match', question: 'Enero', answer: 'Mes', options: ['Mes', 'Día', 'Estación'], instruction: 'Tiempo' },
    { id: 'sp3-m23', type: 'Match', question: 'Verano', answer: 'Estación', options: ['Mes', 'Día', 'Estación'], instruction: 'Tiempo' },
    { id: 'sp3-m24', type: 'Match', question: 'Sol', answer: 'Masculino', options: ['Masculino', 'Femenino'], instruction: 'Género' },
    { id: 'sp3-m25', type: 'Match', question: 'Luna', answer: 'Femenino', options: ['Masculino', 'Femenino'], instruction: 'Género' },
  ],
  4: [
    { id: 'sp4-m1', type: 'Match', question: 'Pre-fijo', answer: 'Antes', options: ['Antes', 'Después', 'En medio'], instruction: 'Gramática' },
    { id: 'sp4-m2', type: 'Match', question: 'Su-fijo', answer: 'Después', options: ['Antes', 'Después', 'En medio'], instruction: 'Gramática' },
    { id: 'sp4-m3', type: 'Match', question: 'In-útil', answer: 'Prefijo', options: ['Prefijo', 'Sufijo'], instruction: 'Identifica' },
    { id: 'sp4-m4', type: 'Match', question: 'Rápida-mente', answer: 'Sufijo', options: ['Prefijo', 'Sufijo'], instruction: 'Identifica' },
    { id: 'sp4-m5', type: 'Match', question: 'A-normal', answer: 'Prefijo', options: ['Prefijo', 'Sufijo'], instruction: 'Identifica' },
    { id: 'sp4-m6', type: 'Match', question: 'Refrán: Al que madruga...', answer: 'Dios le ayuda', options: ['Dios le ayuda', 'se cansa', 'llueve'], instruction: 'Completa el refrán' },
    { id: 'sp4-m7', type: 'Match', question: 'Refrán: Más vale tarde...', answer: 'que nunca', options: ['que nunca', 'que hoy', 'que ayer'], instruction: 'Completa el refrán' },
    { id: 'sp4-m8', type: 'Match', question: 'Refrán: Perro que ladra...', answer: 'no muerde', options: ['no muerde', 'corre mucho', 'duerme'], instruction: 'Completa el refrán' },
    { id: 'sp4-m9', type: 'Match', question: 'Refrán: En boca cerrada...', answer: 'no entran moscas', options: ['no entran moscas', 'hay dientes', 'se habla'], instruction: 'Completa el refrán' },
    { id: 'sp4-m10', type: 'Match', question: 'Refrán: El que busca...', answer: 'encuentra', options: ['encuentra', 'pierde', 'llora'], instruction: 'Completa el refrán' },
    { id: 'sp4-m11', type: 'Match', question: 'Texto descriptivo', answer: 'Sentidos', options: ['Sentidos', 'Argumentos', 'Instrucciones'], instruction: '¿Qué lo caracteriza?' },
    { id: 'sp4-m12', type: 'Match', question: 'Adverbio', answer: 'Rápidamente', options: ['Rápidamente', 'Rápido', 'Más rápido'], instruction: 'Busca el adverbio' },
    { id: 'sp4-m13', type: 'Match', question: 'Adverbio', answer: 'Lentamente', options: ['Lentamente', 'Lento', 'Casi'], instruction: 'Busca el adverbio' },
    { id: 'sp4-m14', type: 'Match', question: 'Adverbio', answer: 'Cerca', options: ['Cerca', 'Lejos', 'Ahí'], instruction: 'Busca el adverbio' },
    { id: 'sp4-m15', type: 'Match', question: 'Adverbio', answer: 'Siempre', options: ['Siempre', 'Nunca', 'Hoy'], instruction: 'Busca el adverbio' },
    { id: 'sp4-m16', type: 'Match', question: 'Sinónimo: Casa', answer: 'Vivienda', options: ['Vivienda', 'Coche', 'Jardín'], instruction: 'Sinónimo' },
    { id: 'sp4-m17', type: 'Match', question: 'Sinónimo: Bosque', answer: 'Selva', options: ['Selva', 'Campo', 'Prado'], instruction: 'Sinónimo' },
    { id: 'sp4-m18', type: 'Match', question: 'Sinónimo: Feliz', answer: 'Contento', options: ['Contento', 'Triste', 'Enojado'], instruction: 'Sinónimo' },
    { id: 'sp4-m19', type: 'Match', question: 'Sinónimo: Rápido', answer: 'Veloz', options: ['Veloz', 'Lento', 'Quieto'], instruction: 'Sinónimo' },
    { id: 'sp4-m20', type: 'Match', question: 'Sinónimo: Grande', answer: 'Inmenso', options: ['Inmenso', 'Pequeño', 'Estrecho'], instruction: 'Sinónimo' },
    { id: 'sp4-m21', type: 'Match', question: 'Antónimo: Caro', answer: 'Barato', options: ['Barato', 'Nuevo', 'Viejo'], instruction: 'Antónimo' },
    { id: 'sp4-m22', type: 'Match', question: 'Antónimo: Encendido', answer: 'Apagado', options: ['Apagado', 'Rojo', 'Luz'], instruction: 'Antónimo' },
    { id: 'sp4-m23', type: 'Match', question: 'Antónimo: Lleno', answer: 'Vacío', options: ['Vacío', 'Mucho', 'Poco'], instruction: 'Antonym' },
    { id: 'sp4-m24', type: 'Match', question: 'Antónimo: Ganar', answer: 'Perder', options: ['Perder', 'Jugar', 'Reír'], instruction: 'Antónimo' },
    { id: 'sp4-m25', type: 'Match', question: 'Antónimo: Entrada', answer: 'Salida', options: ['Salida', 'Puerta', 'Ventana'], instruction: 'Antónimo' },
  ],
  5: [
    { id: 'sp5-m1', type: 'Match', question: 'Ficción', answer: 'Inventado', options: ['Real', 'Inventado', 'Noticia'], instruction: 'Definición' },
    { id: 'sp5-m2', type: 'Match', question: 'Fuga', answer: 'Escape', options: ['Escape', 'Entrada', 'Vuelta'], instruction: 'Definición' },
    { id: 'sp5-m3', type: 'Match', question: 'Sujeto', answer: 'Quién hace', options: ['Quién hace', 'Acción', 'Objeto'], instruction: 'Análisis gramatical' },
    { id: 'sp5-m4', type: 'Match', question: 'Predicado', answer: 'Qué hace', options: ['Qué hace', 'Quién es', 'Dónde está'], instruction: 'Análisis gramatical' },
    { id: 'sp5-m5', type: 'Match', question: 'Análisis de imagen', answer: 'Motivo', options: ['Motivo', 'Rima', 'Pausa'], instruction: 'Término técnico' },
    { id: 'sp5-m6', type: 'Match', question: 'Instruccional', answer: 'Receta', options: ['Receta', 'Cuento', 'Poema'], instruction: 'Tipo de texto' },
    { id: 'sp5-m7', type: 'Match', question: 'Informativo', answer: 'Noticia', options: ['Noticia', 'Novela', 'Terror'], instruction: 'Tipo de texto' },
    { id: 'sp5-m8', type: 'Match', question: 'Personaje', answer: 'Persona en obra', options: ['Persona en obra', 'Autor', 'Lector'], instruction: 'Término técnico' },
    { id: 'sp5-m9', type: 'Match', question: 'Trama', answer: 'Acción', options: ['Acción', 'Lugar', 'Tiempo'], instruction: 'Término técnico' },
    { id: 'sp5-m10', type: 'Match', question: 'Escenario', answer: 'Lugar', options: ['Lugar', 'Acción', 'Tema'], instruction: 'Término técnico' },
    { id: 'sp5-m11', type: 'Match', question: 'Metáfora', answer: 'Lenguaje figurado', options: ['Lenguaje figurado', 'Rima', 'Signo'], instruction: 'Recurso' },
    { id: 'sp5-m12', type: 'Match', question: 'Personificación', answer: 'Cosas vivas', options: ['Cosas vivas', 'Animales', 'Humanos'], instruction: 'Recurso' },
    { id: 'sp5-m13', type: 'Match', question: 'Comparación', answer: 'Como un...', options: ['Como un...', 'Es un...', 'Podría ser...'], instruction: 'Recurso' },
    { id: 'sp5-m14', type: 'Match', question: 'Rima', answer: 'Sonido igual', options: ['Sonido igual', 'Color', 'Sabor'], instruction: 'Recurso' },
    { id: 'sp5-m15', type: 'Match', question: 'Aliteración', answer: 'Repetición de letras', options: ['Repetición de letras', 'Rima final', 'Rima media'], instruction: 'Recurso' },
    { id: 'sp5-m16', type: 'Match', question: 'Verbo: Presente', answer: 'Corre', options: ['Corre', 'Corrió', 'Correrá'], instruction: 'Significa' },
    { id: 'sp5-m17', type: 'Match', question: 'Verbo: Pasado', answer: 'Corrió', options: ['Corre', 'Corrió', 'Correrá'], instruction: 'Significa' },
    { id: 'sp5-m18', type: 'Match', question: 'Verbo: Futuro', answer: 'Correrá', options: ['Corre', 'Corrió', 'Correrá'], instruction: 'Significa' },
    { id: 'sp5-m19', type: 'Match', question: 'Adverbio de lugar', answer: 'Aquí', options: ['Aquí', 'Ahora', 'Bien'], instruction: 'Clasifica' },
    { id: 'sp5-m20', type: 'Match', question: 'Adverbio de tiempo', answer: 'Mañana', options: ['Mañana', 'Ahí', 'Mal'], instruction: 'Clasifica' },
    { id: 'sp5-m21', type: 'Match', question: 'Adverbio de modo', answer: 'Así', options: ['Así', 'Ayer', 'Lejos'], instruction: 'Clasifica' },
    { id: 'sp5-m22', type: 'Match', question: 'Sinónimo: Comenzar', answer: 'Empezar', options: ['Empezar', 'Terminar', 'Pausa'], instruction: 'Sinónimo' },
    { id: 'sp5-m23', type: 'Match', question: 'Sinónimo: Terminar', answer: 'Acabar', options: ['Acabar', 'Empezar', 'Ir'], instruction: 'Sinónimo' },
    { id: 'sp5-m24', type: 'Match', question: 'Sinónimo: Rápido', answer: 'Presto', options: ['Presto', 'Enfermo', 'Cansado'], instruction: 'Sinónimo' },
    { id: 'sp5-m25', type: 'Match', question: 'Sinónimo: Sabio', answer: 'Erudito', options: ['Erudito', 'Tonto', 'Dulce'], instruction: 'Sinónimo' },
  ],
  6: [
    { id: 'sp6-m1', type: 'Match', question: 'Ciencia Ficción', answer: 'Futuro', options: ['Futuro', 'Pasado', 'Presente'], instruction: 'Género' },
    { id: 'sp6-m2', type: 'Match', question: 'Terror', answer: 'Miedo', options: ['Miedo', 'Risa', 'Saber'], instruction: 'Género' },
    { id: 'sp6-m3', type: 'Match', question: 'Cuento corto', answer: 'Relato', options: ['Relato', 'Novela larga', 'Periódico'], instruction: 'Género' },
    { id: 'sp6-m4', type: 'Match', question: 'Punto de vista', answer: 'Perspectiva', options: ['Perspectiva', 'Acción', 'Tema'], instruction: 'Término técnico' },
    { id: 'sp6-m5', type: 'Match', question: 'Argumento', answer: 'Resumen', options: ['Resumen', 'Largo', 'Color'], instruction: 'Término técnico' },
    { id: 'sp6-m6', type: 'Match', question: 'H muda', answer: 'Huevo', options: ['Huevo', 'Ojo', 'Boca'], instruction: 'Ortografía' },
    { id: 'sp6-m7', type: 'Match', question: 'H muda', answer: 'Hola', options: ['Hola', 'Oeste', 'Isla'], instruction: 'Ortografía' },
    { id: 'sp6-m8', type: 'Match', question: 'Debate', answer: 'Opinión', options: ['Opinión', 'Hechos', 'Cuento'], instruction: 'Tipo de texto' },
    { id: 'sp6-m9', type: 'Match', question: 'Noticia', answer: 'Actualidad', options: ['Actualidad', 'Historia', 'Privado'], instruction: 'Tipo de texto' },
    { id: 'sp6-m10', type: 'Match', question: 'Diseño', answer: 'Layout', options: ['Layout', 'Contenido', 'Idioma'], instruction: 'Término técnico' },
    { id: 'sp6-m11', type: 'Match', question: 'Mensaje', answer: 'Qué quiere decir', options: ['Qué quiere decir', 'Inicio', 'Fin'], instruction: 'Término técnico' },
    { id: 'sp6-m12', type: 'Match', question: 'Conflicto', answer: 'Problema', options: ['Problema', 'Solución', 'Fiesta'], instruction: 'Término técnico' },
    { id: 'sp6-m13', type: 'Match', question: 'Clímax', answer: 'Punto álgido', options: ['Punto álgido', 'Inicio', 'Pausa'], instruction: 'Término técnico' },
    { id: 'sp6-m14', type: 'Match', question: 'Intro', answer: 'Planteamiento', options: ['Planteamiento', 'Medio', 'Salida'], instruction: 'Término técnico' },
    { id: 'sp6-m15', type: 'Match', question: 'Final', answer: 'Desenlace', options: ['Desenlace', 'Inicio', 'Conflicto'], instruction: 'Término técnico' },
    { id: 'sp6-m16', type: 'Match', question: 'Metáfora', answer: 'Imagen', options: ['Imagen', 'Habla', 'Escritura'], instruction: 'Recurso' },
    { id: 'sp6-m17', type: 'Match', question: 'Ironía', answer: 'Burla', options: ['Burla', 'Realidad', 'Verdad'], instruction: 'Recurso' },
    { id: 'sp6-m18', type: 'Match', question: 'Símbolo', answer: 'Significado', options: ['Significado', 'Color', 'Nombre'], instruction: 'Recurso' },
    { id: 'sp6-m19', type: 'Match', question: 'Personificación', answer: 'Rasgos humanos', options: ['Rasgos humanos', 'Animales', 'Naturaleza'], instruction: 'Recurso' },
    { id: 'sp6-m20', type: 'Match', question: 'Rima', answer: 'Musicalidad', options: ['Musicalidad', 'Color', 'Sabor'], instruction: 'Recurso' },
    { id: 'sp6-m21', type: 'Match', question: 'Sinónimo: Importante', answer: 'Esencial', options: ['Esencial', 'Sjov', 'Lille'], instruction: 'Sinónimo' },
    { id: 'sp6-m22', type: 'Match', question: 'Sinónimo: Frágil', answer: 'Quebradizo', options: ['Quebradizo', 'Fuerte', 'Duro'], instruction: 'Sinónimo' },
    { id: 'sp6-m23', type: 'Match', question: 'Sinónimo: Desaparecer', answer: 'Esfumarse', options: ['Esfumarse', 'Empezar', 'Ver'], instruction: 'Sinónimo' },
    { id: 'sp6-m24', type: 'Match', question: 'Sinónimo: Surgir', answer: 'Aparecer', options: ['Aparecer', 'Terminar', 'Olvidar'], instruction: 'Sinónimo' },
    { id: 'sp6-m25', type: 'Match', question: 'Sinónimo: Declarar', answer: 'Manifestar', options: ['Manifestar', 'Oír', 'Ver'], instruction: 'Sinónimo' },
  ],
  7: [
    { id: 'sp7-m1', type: 'Match', question: 'Novela Gráfica', answer: 'Cómic', options: ['Cómic', 'Poema', 'Novela sin dibujos'], instruction: 'Género' },
    { id: 'sp7-m2', type: 'Match', question: 'Memoria', answer: 'Vivencia', options: ['Vivencia', 'Inventado', 'Futuro'], instruction: 'Género' },
    { id: 'sp7-m3', type: 'Match', question: 'Inciso', answer: 'Entre comas', options: ['Entre comas', 'Sin coma', 'Punto'], instruction: 'Puntuación' },
    { id: 'sp7-m4', type: 'Match', question: 'Imperativo', answer: '¡Corre!', options: ['¡Corre!', 'Corre', 'Corriendo'], instruction: 'Verbos' },
    { id: 'sp7-m5', type: 'Match', question: 'Ortografía', answer: 'Dictado', options: ['Dictado', 'Lectura', 'Habla'], instruction: 'Término técnico' },
    { id: 'sp7-m6', type: 'Match', question: 'Composición', answer: 'Estructura', options: ['Estructura', 'Tema', 'Idioma'], instruction: 'Término técnico' },
    { id: 'sp7-m7', type: 'Match', question: 'Ética', answer: 'Ethos', options: ['Ethos', 'Épico', 'Lírico'], instruction: 'Retórica' },
    { id: 'sp7-m8', type: 'Match', question: 'Lógica', answer: 'Logos', options: ['Logos', 'Saga', 'Drama'], instruction: 'Retórica' },
    { id: 'sp7-m9', type: 'Match', question: 'Emoción', answer: 'Pathos', options: ['Pathos', 'Ironía', 'Metáfora'], instruction: 'Retórica' },
    { id: 'sp7-m10', type: 'Match', question: 'Intertextualidad', answer: 'Referencia a otros textos', options: ['Referencia a otros textos', 'Ortografía', 'Rima'], instruction: 'Término técnico' },
    { id: 'sp7-m11', type: 'Match', question: 'Flashback', answer: 'Retrospección', options: ['Retrospección', 'Prospercción', 'Presente'], instruction: 'Término técnico' },
    { id: 'sp7-m12', type: 'Match', question: 'Flashforward', answer: 'Prospección', options: ['Prospección', 'Retrospección', 'Pasado'], instruction: 'Término técnico' },
    { id: 'sp7-m13', type: 'Match', question: 'In medias res', answer: 'Directo a la acción', options: ['Directo a la acción', 'Inicio lento', 'Final primero'], instruction: 'Término técnico' },
    { id: 'sp7-m14', type: 'Match', question: 'Cliffhanger', answer: 'Final en suspenso', options: ['Final en suspenso', 'Parte aburrida', 'Inicio'], instruction: 'Término técnico' },
    { id: 'sp7-m15', type: 'Match', question: 'Narrador en 1ª persona', answer: 'Yo', options: ['Yo', 'Él/Ella', 'Omnisciente'], instruction: 'Perspectiva' },
    { id: 'sp7-m16', type: 'Match', question: 'Narrador en 3ª persona', answer: 'Él/Ella', options: ['Él/Ella', 'Yo', 'Usted'], instruction: 'Perspectiva' },
    { id: 'sp7-m17', type: 'Match', question: 'Narrador omnisciente', answer: 'Lo sabe todo', options: ['Lo sabe todo', 'Solo ve a uno', 'Punto de vista propio'], instruction: 'Perspectiva' },
    { id: 'sp7-m18', type: 'Match', question: 'Monólogo interior', answer: 'Pensamientos', options: ['Pensamientos', 'Habla', 'Escritura'], instruction: 'Recurso' },
    { id: 'sp7-m19', type: 'Match', question: 'Discurso directo', answer: 'Citas', options: ['Citas', 'Pensamientos', 'Resumen'], instruction: 'Recurso' },
    { id: 'sp7-m20', type: 'Match', question: 'Discurso indirecto', answer: 'Habla referida', options: ['Habla referida', 'Citas', 'Gritos'], instruction: 'Recurso' },
    { id: 'sp7-m21', type: 'Match', question: 'Descripción', answer: 'Muestra, no digas', options: ['Muestra, no digas', 'Di, no muestres', 'Lee alto'], instruction: 'Estilo' },
    { id: 'sp7-m22', type: 'Match', question: 'Subtexto', answer: 'Entre líneas', options: ['Entre líneas', 'El título', 'El pie de foto'], instruction: 'Literatura' },
    { id: 'sp7-m23', type: 'Match', question: 'Antónimo: Complejo', answer: 'Simple', options: ['Simple', 'Difícil', 'Grande'], instruction: 'Antónimo' },
    { id: 'sp7-m24', type: 'Match', question: 'Antónimo: Abstracto', answer: 'Concreto', options: ['Concreto', 'Boceto', 'Pensamiento'], instruction: 'Antónimo' },
    { id: 'sp7-m25', type: 'Match', question: 'Antónimo: Objetivo', answer: 'Subjetivo', options: ['Subjetivo', 'Factual', 'Verdadero'], instruction: 'Antónimo' },
  ],
  8: [
    { id: 'sp8-m1', type: 'Match', question: 'Miguel de Cervantes', answer: 'Don Quijote', options: ['Don Quijote', 'Cuentos', 'Libro de cocina'], instruction: 'Autor' },
    { id: 'sp8-m2', type: 'Match', question: 'Romanticismo', answer: 'Siglo XIX', options: ['Siglo XIX', 'Actualidad', 'Edad Media'], instruction: 'Periodo' },
    { id: 'sp8-m3', type: 'Match', question: 'Narrativo', answer: 'Acción', options: ['Acción', 'Guía', 'Argumento'], instruction: 'Forma de presentación' },
    { id: 'sp8-m4', type: 'Match', question: 'Argumentativo', answer: 'Opiniones', options: ['Opiniones', 'Descripción', 'Información'], instruction: 'Forma de presentación' },
    { id: 'sp8-m5', type: 'Match', question: 'Instructivo', answer: 'Guía', options: ['Guía', 'Reflexión', 'Drama'], instruction: 'Forma de presentación' },
    { id: 'sp8-m6', type: 'Match', question: 'Informativo', answer: 'Hechos', options: ['Hechos', 'Sentimientos', 'Cuentos'], instruction: 'Forma de presentación' },
    { id: 'sp8-m7', type: 'Match', question: 'Reflexivo', answer: 'Consideraciones', options: ['Consideraciones', 'Órdenes', 'Datos'], instruction: 'Forma de presentación' },
    { id: 'sp8-m8', type: 'Match', question: 'Descriptivo', answer: 'Detalles', options: ['Detalles', 'Plot', 'Conclusión'], instruction: 'Forma de presentación' },
    { id: 'sp8-m9', type: 'Match', question: 'Explicativo', answer: 'Contexto', options: ['Contexto', 'Rima', 'Ritmo'], instruction: 'Forma de presentación' },
    { id: 'sp8-m10', type: 'Match', question: 'Lope de Vega', answer: 'Fuenteovejuna', options: ['Fuenteovejuna', 'El Quijote', 'Lazarillo'], instruction: 'Obra' },
    { id: 'sp8-m11', type: 'Match', question: 'Realismo', answer: 'Fiel a la realidad', options: ['Fiel a la realidad', 'Fantasía', 'Mágico'], instruction: 'Ismo' },
    { id: 'sp8-m12', type: 'Match', question: 'Análisis literario', answer: 'Modelo actancial', options: ['Modelo actancial', 'Pitágoras', 'Tabla periódica'], instruction: 'Herramienta' },
    { id: 'sp8-m13', type: 'Match', question: 'Análisis literario', answer: 'Modelo narrativo', options: ['Modelo narrativo', 'Mapa', 'Presupuesto'], instruction: 'Herramienta' },
    { id: 'sp8-m14', type: 'Match', question: 'Análisis literario', answer: 'Caracterización', options: ['Caracterización', 'Geografía', 'Matemáticas'], instruction: 'Herramienta' },
    { id: 'sp8-m15', type: 'Match', question: 'Épica', answer: 'Novelas/Relatos', options: ['Novelas/Relatos', 'Poemas', 'Drama'], instruction: 'Subgénero' },
    { id: 'sp8-m16', type: 'Match', question: 'Lírica', answer: 'Poemas/Canciones', options: ['Poemas/Canciones', 'Novelas', 'Noticias'], instruction: 'Subgénero' },
    { id: 'sp8-m17', type: 'Match', question: 'Drama', answer: 'Teatro/Cine', options: ['Teatro/Cine', 'Periódico', 'Relato'], instruction: 'Subgénero' },
    { id: 'sp8-m18', type: 'Match', question: 'Sinónimo: Transmitir', answer: 'Comunicar', options: ['Comunicar', 'Olvidar', 'Ocultar'], instruction: 'Sinónimo' },
    { id: 'sp8-m19', type: 'Match', question: 'Sinónimo: Analizar', answer: 'Examinar', options: ['Examinar', 'Adivinar', 'Creer'], instruction: 'Sinónimo' },
    { id: 'sp8-m20', type: 'Match', question: 'Sinónimo: Documentar', answer: 'Atestiguar', options: ['Atestiguar', 'Mentir', 'Soñar'], instruction: 'Sinónimo' },
    { id: 'sp8-m21', type: 'Match', question: 'Sinónimo: Reflexionar', answer: 'Meditar', options: ['Meditar', 'Actuar rápido', 'Dormir'], instruction: 'Sinónimo' },
    { id: 'sp8-m22', type: 'Match', question: 'Sinónimo: Valorar', answer: 'Estimar', options: ['Estimar', 'Ver', 'Oír'], instruction: 'Sinónimo' },
    { id: 'sp8-m23', type: 'Match', question: 'Opuesto: Explícito', answer: 'Implícito', options: ['Implícito', 'Directo', 'Claro'], instruction: 'Antónimo' },
    { id: 'sp8-m24', type: 'Match', question: 'Opuesto: Estático', answer: 'Dinámico', options: ['Dinámico', 'Fijo', 'Quieto'], instruction: 'Antónimo' },
    { id: 'sp8-m25', type: 'Match', question: 'Opuesto: Armonioso', answer: 'Caótico', options: ['Caótico', 'Bonito', 'Tranquilo'], instruction: 'Antónimo' },
  ],
  9: [
    { id: 'sp9-m1', type: 'Match', question: 'Ensayo', answer: 'Subjetivo', options: ['Subjetivo', 'Objetivo', 'Impersonal'], instruction: 'Género' },
    { id: 'sp9-m2', type: 'Match', question: 'Examen oral', answer: 'Sorteo', options: ['Sorteo', 'Tema libre', 'Escrito'], instruction: 'Examen' },
    { id: 'sp9-m3', type: 'Match', question: 'Análisis', answer: 'Interpretación', options: ['Interpretación', 'Resumen', 'Título'], instruction: 'Término técnico' },
    { id: 'sp9-m4', type: 'Match', question: 'Síntesis', answer: 'Compendio', options: ['Compendio', 'División', 'Lectura'], instruction: 'Término técnico' },
    { id: 'sp9-m5', type: 'Match', question: 'Novela: In medias res', answer: 'Inicio en medio', options: ['Inicio en medio', 'Intro larga', 'Final primero'], instruction: 'Término' },
    { id: 'sp9-m6', type: 'Match', question: 'Nudging', answer: 'Comportamiento', options: ['Comportamiento', 'Ortografía', 'Rima'], instruction: 'Concepto' },
    { id: 'sp9-m7', type: 'Match', question: 'Modernismo', answer: 'Existencial', options: ['Existencial', 'Nacional', 'Religioso'], instruction: 'Periodo' },
    { id: 'sp9-m8', type: 'Match', question: 'Metáfora', answer: 'Billedsprog', options: ['Imagen', 'Puntuación', 'Ritmo'], instruction: 'Recurso' },
    { id: 'sp9-m9', type: 'Match', question: 'Ironía', answer: 'Opuesto', options: ['Opuesto', 'Igualdad', 'Hechos'], instruction: 'Recurso' },
    { id: 'sp9-m10', type: 'Match', question: 'Tema', answer: 'Mensaje', options: ['Mensaje', 'Acción', 'Personas'], instruction: 'Término técnico' },
    { id: 'sp9-m11', type: 'Match', question: 'Perspectiva', answer: 'Contexto', options: ['Contexto', 'Separación', 'Olvido'], instruction: 'Término técnico' },
    { id: 'sp9-m12', type: 'Match', question: 'Crítica', answer: 'Valoración', options: ['Valoración', 'Acuerdo', 'Admiración'], instruction: 'Término técnico' },
    { id: 'sp9-m13', type: 'Match', question: 'Intertextualidad', answer: 'Referencia', options: ['Referencia', 'Copia', 'Original'], instruction: 'Término técnico' },
    { id: 'sp9-m14', type: 'Match', question: 'Implícito', answer: 'Sobrentendido', options: ['Sobrentendido', 'Directo', 'Claro'], instruction: 'Término técnico' },
    { id: 'sp9-m15', type: 'Match', question: 'Explícito', answer: 'Dicho directamente', options: ['Dicho directamente', 'Oculto', 'Secreto'], instruction: 'Término técnico' },
    { id: 'sp9-m16', type: 'Match', question: 'Gabriel García Márquez', answer: 'Cien años de soledad', options: ['Cien años de soledad', 'Don Quijote', 'Rayuela'], instruction: 'Autor/Obra' },
    { id: 'sp9-m17', type: 'Match', question: 'Federico García Lorca', answer: 'Poeta en Nueva York', options: ['Poeta en Nueva York', 'Novelas Ejemplares', 'Altazor'], instruction: 'Autor/Obra' },
    { id: 'sp9-m18', type: 'Match', question: 'Jorge Luis Borges', answer: 'El Aleph', options: ['El Aleph', 'Pedro Páramo', 'La tregua'], instruction: 'Autor/Obra' },
    { id: 'sp9-m19', type: 'Match', question: 'Julio Cortázar', answer: 'Rayuela', options: ['Rayuela', 'El túnel', 'Sobre héroes y tumbas'], instruction: 'Autor/Obra' },
    { id: 'sp9-m20', type: 'Match', question: 'Existencialismo', answer: 'Sentido de la vida', options: ['Sentido de la vida', 'Comida', 'Deporte'], instruction: 'Filosofía' },
    { id: 'sp9-m21', type: 'Match', question: 'Símbolo: Blanco', answer: 'Pureza', options: ['Pureza', 'Muerte', 'Guerra'], instruction: 'Significado' },
    { id: 'sp9-m22', type: 'Match', question: 'Símbolo: Negro', answer: 'Muerte/Luto', options: ['Muerte/Luto', 'Alegría', 'Vida'], instruction: 'Significado' },
    { id: 'sp9-m23', type: 'Match', question: 'Símbolo: Rojo', answer: 'Amor/Sangre', options: ['Amor/Sangre', 'Frío', 'Paz'], instruction: 'Significado' },
    { id: 'sp9-m24', type: 'Match', question: 'Símbolo: Paloma', answer: 'Paz', options: ['Paz', 'Guerra', 'Bulla'], instruction: 'Significado' },
    { id: 'sp9-m25', type: 'Match', question: 'Sinónimo: Paradoja', answer: 'Contradicción', options: ['Contradicción', 'Igualdad', 'Claro'], instruction: 'Sinónimo' },
  ],
};
