/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const TYSK_MATCH: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'de0-m1', type: 'Match', question: 'Rot', answer: '🔴', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Farben' },
    { id: 'de0-m2', type: 'Match', question: 'Blau', answer: '🔵', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Farben' },
    { id: 'de0-m3', type: 'Match', question: 'Grün', answer: '🟢', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Farben' },
    { id: 'de0-m4', type: 'Match', question: 'Gelb', answer: '🟡', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Farben' },
    { id: 'de0-m5', type: 'Match', question: 'Eins', answer: '1', options: ['1', '2', '3', '4'], instruction: 'Zahlen' },
    { id: 'de0-m6', type: 'Match', question: 'Zwei', answer: '2', options: ['1', '2', '3', '4'], instruction: 'Zahlen' },
    { id: 'de0-m7', type: 'Match', question: 'Drei', answer: '3', options: ['1', '2', '3', '4'], instruction: 'Zahlen' },
    { id: 'de0-m8', type: 'Match', question: 'Vier', answer: '4', options: ['1', '2', '3', '4'], instruction: 'Zahlen' },
    { id: 'de0-m9', type: 'Match', question: 'Hund', answer: '🐕', options: ['🐕', '🐈', '🚗'], instruction: 'Finden Sie' },
    { id: 'de0-m10', type: 'Match', question: 'Haus', answer: '🏠', options: ['🏠', '🌳', '🚲'], instruction: 'Finden Sie' },
    { id: 'de0-m11', type: 'Match', question: 'Apfel', answer: '🍎', options: ['🍎', '🍌', '🥕'], instruction: 'Obst' },
    { id: 'de0-m12', type: 'Match', question: 'Banane', answer: '🍌', options: ['🍎', '🍌', '🥕'], instruction: 'Obst' },
    { id: 'de0-m13', type: 'Match', question: 'Auto', answer: '🚗', options: ['🚗', '🚲', '🚆'], instruction: 'Fahrzeuge' },
    { id: 'de0-m14', type: 'Match', question: 'Baum', answer: '🌳', options: ['🌳', '🌸', '🌵'], instruction: 'Natur' },
    { id: 'de0-m15', type: 'Match', question: 'Blume', answer: '🌸', options: ['🌳', '🌸', '🌵'], instruction: 'Natur' },
    { id: 'de0-m16', type: 'Match', question: 'Fisch', answer: '🐟', options: ['🐟', '🐦', '🐒'], instruction: 'Tiere' },
    { id: 'de0-m17', type: 'Match', question: 'Vogel', answer: '🐦', options: ['🐟', '🐦', '🐒'], instruction: 'Tiere' },
    { id: 'de0-m18', type: 'Match', question: 'Sonne', answer: '☀️', options: ['☀️', '🌙', '☁️'], instruction: 'Himmel' },
    { id: 'de0-m19', type: 'Match', question: 'Mond', answer: '🌙', options: ['☀️', '🌙', '☁️'], instruction: 'Himmel' },
    { id: 'de0-m20', type: 'Match', question: 'Fünf', answer: '5', options: ['5', '6', '7', '8'], instruction: 'Zahlen' },
    { id: 'de0-m21', type: 'Match', question: 'Sechs', answer: '6', options: ['5', '6', '7', '8'], instruction: 'Zahlen' },
    { id: 'de0-m22', type: 'Match', question: 'Sieben', answer: '7', options: ['5', '6', '7', '8'], instruction: 'Zahlen' },
    { id: 'de0-m23', type: 'Match', question: 'Acht', answer: '8', options: ['5', '6', '7', '8'], instruction: 'Zahlen' },
    { id: 'de0-m24', type: 'Match', question: 'Neun', answer: '9', options: ['9', '10', '11', '12'], instruction: 'Zahlen' },
    { id: 'de0-m25', type: 'Match', question: 'Zehn', answer: '10', options: ['9', '10', '11', '12'], instruction: 'Zahlen' },
    { id: 'de0-m26', type: 'Match', question: 'Bär', answer: '🐻', options: ['🐻', '🐯', '🦁'], instruction: 'Tiere' },
    { id: 'de0-m27', type: 'Match', question: 'Elefant', answer: '🐘', options: ['🐘', '🦒', '🦓'], instruction: 'Tiere' },
    { id: 'de0-m28', type: 'Match', question: 'Giraffe', answer: '🦒', options: ['🐘', '🦒', '🦓'], instruction: 'Tiere' },
    { id: 'de0-m29', type: 'Match', question: 'Löwe', answer: '🦁', options: ['🦁', '🐯', '🐼'], instruction: 'Tiere' },
    { id: 'de0-m30', type: 'Match', question: 'Panda', answer: '🐼', options: ['🦁', '🐯', '🐼'], instruction: 'Tiere' },
    { id: 'de0-m31', type: 'Match', question: 'Schwarz', answer: '⚫', options: ['⚫', '⚪', '🟠', '🟣'], instruction: 'Farben' },
    { id: 'de0-m32', type: 'Match', question: 'Weiß', answer: '⚪', options: ['⚫', '⚪', '🟠', '🟣'], instruction: 'Farben' },
    { id: 'de0-m33', type: 'Match', question: 'Orange', answer: '🟠', options: ['⚫', '⚪', '🟠', '🟣'], instruction: 'Farben' },
    { id: 'de0-m34', type: 'Match', question: 'Lila', answer: '🟣', options: ['⚫', '⚪', '🟠', '🟣'], instruction: 'Farben' },
    { id: 'de0-m35', type: 'Match', question: 'Braun', answer: '🟤', options: ['🟤', '🔴', '🔵', '🟢'], instruction: 'Farben' },
    { id: 'de0-m36', type: 'Match', question: 'Brot', answer: '🍞', options: ['🍞', '🧀', '🥚'], instruction: 'Essen' },
    { id: 'de0-m37', type: 'Match', question: 'Käse', answer: '🧀', options: ['🍞', '🧀', '🥚'], instruction: 'Essen' },
    { id: 'de0-m38', type: 'Match', question: 'Ei', answer: '🥚', options: ['🍞', '🧀', '🥚'], instruction: 'Essen' },
    { id: 'de0-m39', type: 'Match', question: 'Milch', answer: '🥛', options: ['🥛', '🧃', '☕'], instruction: 'Trinken' },
    { id: 'de0-m40', type: 'Match', question: 'Saft', answer: '🧃', options: ['🥛', '🧃', '☕'], instruction: 'Trinken' },
    { id: 'de0-m41', type: 'Match', question: 'Tasse', answer: '☕', options: ['🥛', '🧃', '☕'], instruction: 'Gegenstände' },
    { id: 'de0-m42', type: 'Match', question: 'Ball', answer: '⚽', options: ['⚽', '🏀', '🏈'], instruction: 'Spielzeug' },
    { id: 'de0-m43', type: 'Match', question: 'Puppe', answer: '🪆', options: ['⚽', '🪆', '🧸'], instruction: 'Spielzeug' },
    { id: 'de0-m44', type: 'Match', question: 'Teddybär', answer: '🧸', options: ['⚽', '🪆', '🧸'], instruction: 'Spielzeug' },
    { id: 'de0-m45', type: 'Match', question: 'Fahrrad', answer: '🚲', options: ['🚲', '🛹', '🛴'], instruction: 'Fahrzeuge' },
    { id: 'de0-m46', type: 'Match', question: 'Roller', answer: '🛴', options: ['🚲', '🛹', '🛴'], instruction: 'Fahrzeuge' },
    { id: 'de0-m47', type: 'Match', question: 'Skateboard', answer: '🛹', options: ['🚲', '🛹', '🛴'], instruction: 'Fahrzeuge' },
    { id: 'de0-m48', type: 'Match', question: 'Hase', answer: '🐰', options: ['🐰', '🐹', '🐭'], instruction: 'Tiere' },
    { id: 'de0-m49', type: 'Match', question: 'Hamster', answer: '🐹', options: ['🐰', '🐹', '🐭'], instruction: 'Tiere' },
    { id: 'de0-m50', type: 'Match', question: 'Maus', answer: '🐭', options: ['🐰', '🐹', '🐭'], instruction: 'Tiere' },
    { id: 'de0-m51', type: 'Match', question: 'Katze', answer: '🐱', options: ['🐱', '🐶', '🐭'], instruction: 'Tiere' },
  ],
  1: [
    { id: 'de1-m1', type: 'Match', question: 'Mutter', answer: 'Mor', options: ['Mor', 'Far', 'Kind'], instruction: 'Familie' },
    { id: 'de1-m2', type: 'Match', question: 'Vater', answer: 'Far', options: ['Mor', 'Far', 'Kind'], instruction: 'Familie' },
    { id: 'de1-m3', type: 'Match', question: 'Kind', answer: 'Barn', options: ['Mor', 'Far', 'Barn'], instruction: 'Familie' },
    { id: 'de1-m4', type: 'Match', question: 'Schwarz', answer: '⚫', options: ['⚫', '⚪', '🟠'], instruction: 'Farben' },
    { id: 'de1-m5', type: 'Match', question: 'Weiß', answer: '⚪', options: ['⚫', '⚪', '🟠'], instruction: 'Farben' },
    { id: 'de1-m6', type: 'Match', question: 'Fünf', answer: '5', options: ['5', '6', '7'], instruction: 'Zahlen' },
    { id: 'de1-m7', type: 'Match', question: 'Sechs', answer: '6', options: ['5', '6', '7'], instruction: 'Zahlen' },
    { id: 'de1-m8', type: 'Match', question: 'Sieben', answer: '7', options: ['5', '6', '7'], instruction: 'Zahlen' },
    { id: 'de1-m9', type: 'Match', question: 'Hallo', answer: 'Hej', options: ['Hej', 'Farvel', 'Tak'], instruction: 'Grüße' },
    { id: 'de1-m10', type: 'Match', question: 'Tschüss', answer: 'Farvel', options: ['Hej', 'Farvel', 'Tak'], instruction: 'Grüße' },
    { id: 'de1-m11', type: 'Match', question: 'Bruder', answer: 'Bror', options: ['Bror', 'Søster', 'Baby'], instruction: 'Familie' },
    { id: 'de1-m12', type: 'Match', question: 'Schwester', answer: 'Søster', options: ['Bror', 'Søster', 'Baby'], instruction: 'Familie' },
    { id: 'de1-m13', type: 'Match', question: 'Opa', answer: 'Bedstefar', options: ['Bedstefar', 'Bedstemor', 'Onkel'], instruction: 'Familie' },
    { id: 'de1-m14', type: 'Match', question: 'Oma', answer: 'Bedstemor', options: ['Bedstefar', 'Bedstemor', 'Tante'], instruction: 'Familie' },
    { id: 'de1-m15', type: 'Match', question: 'Kopf', answer: 'Hoved', options: ['Hoved', 'Hånd', 'Fod'], instruction: 'Körper' },
    { id: 'de1-m16', type: 'Match', question: 'Hand', answer: 'Hånd', options: ['Hoved', 'Hånd', 'Fod'], instruction: 'Körper' },
    { id: 'de1-m17', type: 'Match', question: 'Fuß', answer: 'Fod', options: ['Hoved', 'Hånd', 'Fod'], instruction: 'Körper' },
    { id: 'de1-m18', type: 'Match', question: 'Finger', answer: 'Finger', options: ['Finger', 'Tå', 'Arm'], instruction: 'Körper' },
    { id: 'de1-m19', type: 'Match', question: 'Bein', answer: 'Ben', options: ['Ben', 'Arm', 'Ryg'], instruction: 'Körper' },
    { id: 'de1-m20', type: 'Match', question: 'Auge', answer: 'Øje', options: ['Øje', 'Øre', 'Næse'], instruction: 'Gesicht' },
    { id: 'de1-m21', type: 'Match', question: 'Ohr', answer: 'Øre', options: ['Øje', 'Øre', 'Næse'], instruction: 'Gesicht' },
    { id: 'de1-m22', type: 'Match', question: 'Nase', answer: 'Næse', options: ['Øje', 'Øre', 'Næse'], instruction: 'Gesicht' },
    { id: 'de1-m23', type: 'Match', question: 'Mund', answer: 'Mund', options: ['Mund', 'Tand', 'Tunge'], instruction: 'Gesicht' },
    { id: 'de1-m24', type: 'Match', question: 'Apfel', answer: 'Æble', options: ['Æble', 'Pære', 'Banan'], instruction: 'Essen' },
    { id: 'de1-m25', type: 'Match', question: 'Pære', answer: 'Pære', options: ['Æble', 'Pære', 'Banan'], instruction: 'Essen' },
    { id: 'de1-m26', type: 'Match', question: 'Banan', answer: 'Banan', options: ['Æble', 'Pære', 'Banan'], instruction: 'Essen' },
    { id: 'de1-m27', type: 'Match', question: 'Tomate', answer: 'Tomat', options: ['Tomat', 'Agurk', 'Gulerod'], instruction: 'Essen' },
    { id: 'de1-m28', type: 'Match', question: 'Kartoffel', answer: 'Kartoffel', options: ['Tomat', 'Agurk', 'Kartoffel'], instruction: 'Essen' },
    { id: 'de1-m29', type: 'Match', question: 'Milch', answer: 'Mælk', options: ['Mælk', 'Vand', 'Juice'], instruction: 'Trinken' },
    { id: 'de1-m30', type: 'Match', question: 'Wasser', answer: 'Vand', options: ['Mælk', 'Vand', 'Juice'], instruction: 'Trinken' },
    { id: 'de1-m31', type: 'Match', question: 'Danke', answer: 'Tak', options: ['Tak', 'Selv tak', 'Undskyld'], instruction: 'Höflichkeit' },
    { id: 'de1-m32', type: 'Match', question: 'Bitte', answer: 'Værsgo / Selv tak', options: ['Tak', 'Selv tak', 'Undskyld'], instruction: 'Höflichkeit' },
    { id: 'de1-m33', type: 'Match', question: 'Ja', answer: 'Ja', options: ['Ja', 'Nej', 'Måske'], instruction: 'Basis' },
    { id: 'de1-m34', type: 'Match', question: 'Nein', answer: 'Nej', options: ['Ja', 'Nej', 'Måske'], instruction: 'Basis' },
    { id: 'de1-m35', type: 'Match', question: 'Elf', answer: '11', options: ['11', '12', '13', '14'], instruction: 'Zahlen' },
    { id: 'de1-m36', type: 'Match', question: 'Zwölf', answer: '12', options: ['11', '12', '13', '14'], instruction: 'Zahlen' },
    { id: 'de1-m37', type: 'Match', question: 'Dreizehn', answer: '13', options: ['11', '12', '13', '14'], instruction: 'Zahlen' },
    { id: 'de1-m38', type: 'Match', question: 'Vierzehn', answer: '14', options: ['11', '12', '13', '14'], instruction: 'Zahlen' },
    { id: 'de1-m39', type: 'Match', question: 'Fünfzehn', answer: '15', options: ['15', '16', '17', '18'], instruction: 'Zahlen' },
    { id: 'de1-m40', type: 'Match', question: 'Sechzehn', answer: '16', options: ['15', '16', '17', '18'], instruction: 'Zahlen' },
    { id: 'de1-m41', type: 'Match', question: 'Siebzehn', answer: '17', options: ['15', '16', '17', '18'], instruction: 'Zahlen' },
    { id: 'de1-m42', type: 'Match', question: 'Achtzehn', answer: '18', options: ['15', '16', '17', '18'], instruction: 'Zahlen' },
    { id: 'de1-m43', type: 'Match', question: 'Neunzehn', answer: '19', options: ['19', '20', '21'], instruction: 'Zahlen' },
    { id: 'de1-m44', type: 'Match', question: 'Zwanzig', answer: '20', options: ['19', '20', '21'], instruction: 'Zahlen' },
    { id: 'de1-m45', type: 'Match', question: 'Guten Morgen', answer: 'Godmorgen', options: ['Godmorgen', 'Goddag', 'Godnat'], instruction: 'Begrüßung' },
    { id: 'de1-m46', type: 'Match', question: 'Guten Tag', answer: 'Goddag', options: ['Godmorgen', 'Goddag', 'Godnat'], instruction: 'Begrüßung' },
    { id: 'de1-m47', type: 'Match', question: 'Gute Nacht', answer: 'Godnat', options: ['Godmorgen', 'Goddag', 'Godnat'], instruction: 'Begrüßung' },
    { id: 'de1-m48', type: 'Match', question: 'Katze', answer: 'Kat', options: ['Kat', 'Hund', 'Mus'], instruction: 'Tiere' },
    { id: 'de1-m49', type: 'Match', question: 'Hund', answer: 'Hund', options: ['Kat', 'Hund', 'Mus'], instruction: 'Tiere' },
    { id: 'de1-m50', type: 'Match', question: 'Maus', answer: 'Mus', options: ['Kat', 'Hund', 'Mus'], instruction: 'Tiere' },
    { id: 'de1-m51', type: 'Match', question: 'Vogel', answer: 'Fugl', options: ['Fugl', 'Fisk', 'Hest'], instruction: 'Tiere' },
  ],
  2: [
    { id: 'de2-m1', type: 'Match', question: 'Das Haus', answer: 'Huset', options: ['Huset', 'Skolen', 'Haven'], instruction: 'Orte' },
    { id: 'de2-m2', type: 'Match', question: 'Die Schule', answer: 'Skolen', options: ['Huset', 'Skolen', 'Haven'], instruction: 'Orte' },
    { id: 'de2-m3', type: 'Match', question: 'Der Garten', answer: 'Haven', options: ['Huset', 'Skolen', 'Haven'], instruction: 'Orte' },
    { id: 'de2-m4', type: 'Match', question: 'Die Küche', answer: 'Køkkenet', options: ['Køkkenet', 'Værelset', 'Stuen'], instruction: 'Zimmer' },
    { id: 'de2-m5', type: 'Match', question: 'Das Zimmer', answer: 'Værelset', options: ['Køkkenet', 'Værelset', 'Stuen'], instruction: 'Zimmer' },
    { id: 'de2-m6', type: 'Match', question: 'Das Badezimmer', answer: 'Badeværelset', options: ['Køkkenet', 'Badeværelset', 'Stuen'], instruction: 'Zimmer' },
    { id: 'de2-m7', type: 'Match', question: 'Das Wohnzimmer', answer: 'Stuen', options: ['Køkkenet', 'Værelset', 'Stuen'], instruction: 'Zimmer' },
    { id: 'de2-m8', type: 'Match', question: 'Der Frühling', answer: 'Foråret', options: ['Foråret', 'Sommeren', 'Winter'], instruction: 'Jahreszeiten' },
    { id: 'de2-m9', type: 'Match', question: 'Der Sommer', answer: 'Sommeren', options: ['Foråret', 'Sommeren', 'Winter'], instruction: 'Jahreszeiten' },
    { id: 'de2-m10', type: 'Match', question: 'Der Regen', answer: '🌧️', options: ['🌧️', '☀️', '❄️'], instruction: 'Natur' },
    { id: 'de2-m11', type: 'Match', question: 'Der Tisch', answer: 'Bordet', options: ['Bordet', 'Stolen', 'Sengen'], instruction: 'Möbel' },
    { id: 'de2-m12', type: 'Match', question: 'Der Stuhl', answer: 'Stolen', options: ['Bordet', 'Stolen', 'Sengen'], instruction: 'Möbel' },
    { id: 'de2-m13', type: 'Match', question: 'Das Bett', answer: 'Sengen', options: ['Bordet', 'Stolen', 'Sengen'], instruction: 'Möbel' },
    { id: 'de2-m14', type: 'Match', question: 'Die Tür', answer: 'Døren', options: ['Døren', 'Vinduet', 'Væggen'], instruction: 'Haus' },
    { id: 'de2-m15', type: 'Match', question: 'Das Fenster', answer: 'Vinduet', options: ['Døren', 'Vinduet', 'Væggen'], instruction: 'Haus' },
    { id: 'de2-m16', type: 'Match', question: 'Die Wand', answer: 'Væggen', options: ['Døren', 'Vinduet', 'Væggen'], instruction: 'Haus' },
    { id: 'de2-m17', type: 'Match', question: 'Der Hund', answer: 'Hunden', options: ['Hunden', 'Katten', 'Musen'], instruction: 'Tiere' },
    { id: 'de2-m18', type: 'Match', question: 'Die Katze', answer: 'Katten', options: ['Hunden', 'Katten', 'Musen'], instruction: 'Tiere' },
    { id: 'de2-m19', type: 'Match', question: 'Die Maus', answer: 'Musen', options: ['Hunden', 'Katten', 'Musen'], instruction: 'Tiere' },
    { id: 'de2-m20', type: 'Match', question: 'Das Pferd', answer: 'Hesten', options: ['Hesten', 'Koen', 'Grisen'], instruction: 'Tiere' },
    { id: 'de2-m21', type: 'Match', question: 'Die Kuh', answer: 'Koen', options: ['Hesten', 'Koen', 'Grisen'], instruction: 'Tiere' },
    { id: 'de2-m22', type: 'Match', question: 'Das Schwein', answer: 'Grisen', options: ['Hesten', 'Koen', 'Grisen'], instruction: 'Tiere' },
    { id: 'de2-m23', type: 'Match', question: 'Der Apfel', answer: 'Æblet', options: ['Æblet', 'Pæren', 'Bananen'], instruction: 'Obst' },
    { id: 'de2-m24', type: 'Match', question: 'Die Birne', answer: 'Pæren', options: ['Æblet', 'Pæren', 'Bananen'], instruction: 'Obst' },
    { id: 'de2-m25', type: 'Match', question: 'Die Banane', answer: 'Bananen', options: ['Æblet', 'Pæren', 'Bananen'], instruction: 'Obst' },
    { id: 'de2-m26', type: 'Match', question: 'Die Milch', answer: 'Mælken', options: ['Mælken', 'Vandet', 'Juicen'], instruction: 'Trinken' },
    { id: 'de2-m27', type: 'Match', question: 'Das Wasser', answer: 'Vandet', options: ['Mælken', 'Vandet', 'Juicen'], instruction: 'Trinken' },
    { id: 'de2-m28', type: 'Match', question: 'Der Saft', answer: 'Juicen', options: ['Mælken', 'Vandet', 'Juicen'], instruction: 'Trinken' },
    { id: 'de2-m29', type: 'Match', question: 'Rot', answer: 'Rød', options: ['Rød', 'Blå', 'Grøn'], instruction: 'Farben' },
    { id: 'de2-m30', type: 'Match', question: 'Blau', answer: 'Blå', options: ['Rød', 'Blå', 'Grøn'], instruction: 'Farben' },
    { id: 'de2-m31', type: 'Match', question: 'Grün', answer: 'Grøn', options: ['Rød', 'Blå', 'Grøn'], instruction: 'Farben' },
    { id: 'de2-m32', type: 'Match', question: 'Gelb', answer: 'Gul', options: ['Gul', 'Sort', 'Hvid'], instruction: 'Farben' },
    { id: 'de2-m33', type: 'Match', question: 'Schwarz', answer: 'Sort', options: ['Gul', 'Sort', 'Hvid'], instruction: 'Farben' },
    { id: 'de2-m34', type: 'Match', question: 'Weiß', answer: 'Hvid', options: ['Gul', 'Sort', 'Hvid'], instruction: 'Farben' },
    { id: 'de2-m35', type: 'Match', question: 'Eins', answer: 'En', options: ['En', 'To', 'Tre'], instruction: 'Zahlen' },
    { id: 'de2-m36', type: 'Match', question: 'Zwei', answer: 'To', options: ['En', 'To', 'Tre'], instruction: 'Zahlen' },
    { id: 'de2-m37', type: 'Match', question: 'Drei', answer: 'Tre', options: ['En', 'To', 'Tre'], instruction: 'Zahlen' },
    { id: 'de2-m38', type: 'Match', question: 'Vier', answer: 'Fire', options: ['Fire', 'Fem', 'Seks'], instruction: 'Zahlen' },
    { id: 'de2-m39', type: 'Match', question: 'Fünf', answer: 'Fem', options: ['Fire', 'Fem', 'Seks'], instruction: 'Zahlen' },
    { id: 'de2-m40', type: 'Match', question: 'Sechs', answer: 'Seks', options: ['Fire', 'Fem', 'Seks'], instruction: 'Zahlen' },
    { id: 'de2-m41', type: 'Match', question: 'Sonne', answer: '☀️', options: ['☀️', '🌙', '☁️'], instruction: 'Natur' },
    { id: 'de2-m42', type: 'Match', question: 'Mond', answer: '🌙', options: ['☀️', '🌙', '☁️'], instruction: 'Natur' },
    { id: 'de2-m43', type: 'Match', question: 'Wolke', answer: '☁️', options: ['☀️', '🌙', '☁️'], instruction: 'Natur' },
    { id: 'de2-m44', type: 'Match', question: 'Groß', answer: 'Stor', options: ['Stor', 'Lille', 'Sjov'], instruction: 'Adjektive' },
    { id: 'de2-m45', type: 'Match', question: 'Klein', answer: 'Lille', options: ['Stor', 'Lille', 'Sjov'], instruction: 'Adjektive' },
    { id: 'de2-m46', type: 'Match', question: 'Gut', answer: 'God', options: ['God', 'Dårlig', 'Sød'], instruction: 'Adjektive' },
    { id: 'de2-m47', type: 'Match', question: 'Schlecht', answer: 'Dårlig', options: ['God', 'Dårlig', 'Sød'], instruction: 'Adjektive' },
    { id: 'de2-m48', type: 'Match', question: 'Schön', answer: 'Smuk', options: ['Smuk', 'Grim', 'Glad'], instruction: 'Adjektive' },
    { id: 'de2-m49', type: 'Match', question: 'Hässlich', answer: 'Grim', options: ['Smuk', 'Grim', 'Glad'], instruction: 'Adjektive' },
    { id: 'de2-m50', type: 'Match', question: 'Schnell', answer: 'Hurtig', options: ['Hurtig', 'Langsom', 'Stille'], instruction: 'Adjektive' },
    { id: 'de2-m51', type: 'Match', question: 'Langsam', answer: 'Langsom', options: ['Hurtig', 'Langsom', 'Stille'], instruction: 'Adjektive' },
    { id: 'de2-m52', type: 'Match', question: 'Die Blume', answer: 'Blomsten', options: ['Blomsten', 'Træet', 'Græsset'], instruction: 'Natur' },
    { id: 'de2-m53', type: 'Match', question: 'Der Baum', answer: 'Træet', options: ['Blomsten', 'Træet', 'Græsset'], instruction: 'Natur' },
    { id: 'de2-m54', type: 'Match', question: 'Das Gras', answer: 'Græsset', options: ['Blomsten', 'Træet', 'Græsset'], instruction: 'Natur' },
    { id: 'de2-m55', type: 'Match', question: 'Der Wald', answer: 'Skoven', options: ['Skoven', 'Haven', 'Marken'], instruction: 'Natur' },
    { id: 'de2-m56', type: 'Match', question: 'Der See', answer: 'Søen', options: ['Søen', 'Havet', 'Aaen'], instruction: 'Natur' },
    { id: 'de2-m57', type: 'Match', question: 'Das Meer', answer: 'Havet', options: ['Søen', 'Havet', 'Aaen'], instruction: 'Natur' },
    { id: 'de2-m58', type: 'Match', question: 'Der Berg', answer: 'Bjerget', options: ['Bjerget', 'Dalen', 'Bakken'], instruction: 'Natur' },
    { id: 'de2-m59', type: 'Match', question: 'Die Luft', answer: 'Luften', options: ['Luften', 'Vandet', 'Jorden'], instruction: 'Elemente' },
    { id: 'de2-m60', type: 'Match', question: 'Das Feuer', answer: 'Ilden', options: ['Ilden', 'Vandet', 'Luften'], instruction: 'Elemente' },
    { id: 'de2-m61', type: 'Match', question: 'Die Erde', answer: 'Jorden', options: ['Jorden', 'Ilden', 'Luften'], instruction: 'Elemente' },
    { id: 'de2-m62', type: 'Match', question: 'Der Teller', answer: 'Tallerkenen', options: ['Tallerkenen', 'Glasset', 'Kniven'], instruction: 'Küche' },
    { id: 'de2-m63', type: 'Match', question: 'Das Glas', answer: 'Glasset', options: ['Tallerkenen', 'Glasset', 'Kniven'], instruction: 'Küche' },
    { id: 'de2-m64', type: 'Match', question: 'Das Messer', answer: 'Kniven', options: ['Kniven', 'Gaffelen', 'Skeen'], instruction: 'Küche' },
    { id: 'de2-m65', type: 'Match', question: 'Die Gabel', answer: 'Gaffelen', options: ['Kniven', 'Gaffelen', 'Skeen'], instruction: 'Küche' },
    { id: 'de2-m66', type: 'Match', question: 'Der Löffel', answer: 'Skeen', options: ['Kniven', 'Gaffelen', 'Skeen'], instruction: 'Küche' },
    { id: 'de2-m67', type: 'Match', question: 'Die Tasse', answer: 'Koppen', options: ['Koppen', 'Glasset', 'Kanden'], instruction: 'Küche' },
    { id: 'de2-m68', type: 'Match', question: 'Der Hut', answer: 'Hatten', options: ['Hatten', 'Huen', 'Skoen'], instruction: 'Kleidung' },
    { id: 'de2-m69', type: 'Match', question: 'Die Mütze', answer: 'Huen', options: ['Hatten', 'Huen', 'Skoen'], instruction: 'Kleidung' },
    { id: 'de2-m70', type: 'Match', question: 'Die Jacke', answer: 'Jakken', options: ['Jakken', 'Frakken', 'Blusen'], instruction: 'Kleidung' },
    { id: 'de2-m71', type: 'Match', question: 'Die Hose', answer: 'Bukserne', options: ['Bukserne', 'Kjolen', 'Nederdelen'], instruction: 'Kleidung' },
    { id: 'de2-m72', type: 'Match', question: 'Das Hemd', answer: 'Skjorten', options: ['Skjorten', 'Blusen', 'Jakken'], instruction: 'Kleidung' },
    { id: 'de2-m73', type: 'Match', question: 'Die Schuhe', answer: 'Skoene', options: ['Skoene', 'Støvlerne', 'Sokkerne'], instruction: 'Kleidung' },
    { id: 'de2-m74', type: 'Match', question: 'Der Kopf', answer: 'Hovedet', options: ['Hovedet', 'Maven', 'Ryg'], instruction: 'Körper' },
    { id: 'de2-m75', type: 'Match', question: 'Der Bauch', answer: 'Maven', options: ['Hovedet', 'Maven', 'Ryg'], instruction: 'Körper' },
    { id: 'de2-m76', type: 'Match', question: 'Der Rücken', answer: 'Ryggen', options: ['Hovedet', 'Maven', 'Ryggen'], instruction: 'Körper' },
    { id: 'de2-m77', type: 'Match', question: 'Der Arm', answer: 'Armen', options: ['Armen', 'Benet', 'Hånden'], instruction: 'Körper' },
    { id: 'de2-m78', type: 'Match', question: 'Das Bein', answer: 'Benet', options: ['Armen', 'Benet', 'Foden'], instruction: 'Körper' },
    { id: 'de2-m79', type: 'Match', question: 'Die Hand', answer: 'Hånden', options: ['Hånden', 'Foden', 'Fingeren'], instruction: 'Körper' },
    { id: 'de2-m80', type: 'Match', question: 'Der Fuß', answer: 'Foden', options: ['Hånden', 'Foden', 'Fingeren'], instruction: 'Körper' },
    { id: 'de2-m81', type: 'Match', question: 'Das Auge', answer: 'Øjet', options: ['Øjet', 'Øret', 'Næsen'], instruction: 'Gesicht' },
    { id: 'de2-m82', type: 'Match', question: 'Das Ohr', answer: 'Øret', options: ['Øjet', 'Øret', 'Næsen'], instruction: 'Gesicht' },
    { id: 'de2-m83', type: 'Match', question: 'Die Nase', answer: 'Næsen', options: ['Øjet', 'Øret', 'Næsen'], instruction: 'Gesicht' },
    { id: 'de2-m84', type: 'Match', question: 'Der Mund', answer: 'Munden', options: ['Munden', 'Tanden', 'Læben'], instruction: 'Gesicht' },
    { id: 'de2-m85', type: 'Match', question: 'Der Zahn', answer: 'Tanden', options: ['Munden', 'Tanden', 'Læben'], instruction: 'Gesicht' },
    { id: 'de2-m86', type: 'Match', question: 'Der Apfelsaft', answer: 'Æblejuice', options: ['Æblejuice', 'Mælk', 'Vand'], instruction: 'Trinken' },
    { id: 'de2-m87', type: 'Match', question: 'Die Schokolade', answer: 'Chokolade', options: ['Chokolade', 'Kage', 'Is'], instruction: 'Essen' },
    { id: 'de2-m88', type: 'Match', question: 'Der Kuchen', answer: 'Kage', options: ['Chokolade', 'Kage', 'Is'], instruction: 'Essen' },
    { id: 'de2-m89', type: 'Match', question: 'Das Eis', answer: 'Is', options: ['Chokolade', 'Kage', 'Is'], instruction: 'Essen' },
    { id: 'de2-m90', type: 'Match', question: 'Süß', answer: 'Sød', options: ['Sød', 'Sur', 'Salt'], instruction: 'Geschmack' },
    { id: 'de2-m91', type: 'Match', question: 'Sauer', answer: 'Sur', options: ['Sød', 'Sur', 'Salt'], instruction: 'Geschmack' },
    { id: 'de2-m92', type: 'Match', question: 'Salzig', answer: 'Salt', options: ['Sød', 'Sur', 'Salt'], instruction: 'Geschmack' },
    { id: 'de2-m93', type: 'Match', question: 'Laut', answer: 'Højlydt', options: ['Højlydt', 'Stille', 'Sjov'], instruction: 'Adjektive' },
    { id: 'de2-m94', type: 'Match', question: 'Leise', answer: 'Stille', options: ['Højlydt', 'Stille', 'Sjov'], instruction: 'Adjektive' },
    { id: 'de2-m95', type: 'Match', question: 'Hart', answer: 'Hård', options: ['Hård', 'Blød', 'Varm'], instruction: 'Adjektive' },
    { id: 'de2-m96', type: 'Match', question: 'Weich', answer: 'Blød', options: ['Hård', 'Blød', 'Varm'], instruction: 'Adjektive' },
    { id: 'de2-m97', type: 'Match', question: 'Neu', answer: 'Ny', options: ['Ny', 'Gammel', 'Hurtig'], instruction: 'Adjektive' },
    { id: 'de2-m98', type: 'Match', question: 'Alt', answer: 'Gammel', options: ['Ny', 'Gammel', 'Hurtig'], instruction: 'Adjektive' },
    { id: 'de2-m99', type: 'Match', question: 'Ich', answer: 'Jeg', options: ['Jeg', 'Du', 'Han/Hun'], instruction: 'Pronomina' },
    { id: 'de2-m100', type: 'Match', question: 'Du', answer: 'Du', options: ['Jeg', 'Du', 'Han/Hun'], instruction: 'Pronomina' },
  ],
  3: [
    { id: 'de3-m1', type: 'Match', question: 'Apfel', answer: '🍎', options: ['🍎', '🍌', '🍐'], instruction: 'Obst' },
    { id: 'de3-m2', type: 'Match', question: 'Banane', answer: '🍌', options: ['🍎', '🍌', '🍐'], instruction: 'Obst' },
    { id: 'de3-m3', type: 'Match', question: 'Brot', answer: '🍞', options: ['🍞', '🥛', '🥚'], instruction: 'Essen' },
    { id: 'de3-m4', type: 'Match', question: 'Milch', answer: '🥛', options: ['🍞', '🥛', '🥚'], instruction: 'Trinken' },
    { id: 'de3-m5', type: 'Match', question: 'Wasser', answer: '💧', options: ['💧', '☕', '🍷'], instruction: 'Trinken' },
    { id: 'de3-m6', type: 'Match', question: 'Ei', answer: '🥚', options: ['🥚', '🍎', '🍞'], instruction: 'Essen' },
    { id: 'de3-m7', type: 'Match', question: 'Sonne', answer: '☀️', options: ['☀️', '🌙', '☁️'], instruction: 'Natur' },
    { id: 'de3-m8', type: 'Match', question: 'Mond', answer: '🌙', options: ['☀️', '🌙', '☁️'], instruction: 'Natur' },
    { id: 'de3-m9', type: 'Match', question: 'Elf', answer: '11', options: ['11', '12', '13'], instruction: 'Zahlen' },
    { id: 'de3-m10', type: 'Match', question: 'Zwölf', answer: '12', options: ['11', '12', '13'], instruction: 'Zahlen' },
    { id: 'de3-m11', type: 'Match', question: 'Kirsche', answer: 'Kirsebær', options: ['Kirsebær', 'Jordbær', 'Hindbær'], instruction: 'Obst' },
    { id: 'de3-m12', type: 'Match', question: 'Erdbeere', answer: 'Jordbær', options: ['Kirsebær', 'Jordbær', 'Hindbær'], instruction: 'Obst' },
    { id: 'de3-m13', type: 'Match', question: 'Himbeere', answer: 'Hindbær', options: ['Kirsebær', 'Jordbær', 'Hindbær'], instruction: 'Obst' },
    { id: 'de3-m14', type: 'Match', question: 'Pfirsich', answer: 'Fersken', options: ['Fersken', 'Blomme', 'Appelsin'], instruction: 'Obst' },
    { id: 'de3-m15', type: 'Match', question: 'Pflaume', answer: 'Blomme', options: ['Fersken', 'Blomme', 'Appelsin'], instruction: 'Obst' },
    { id: 'de3-m16', type: 'Match', question: 'Zitrone', answer: 'Citron', options: ['Citron', 'Lime', 'Grapefrugt'], instruction: 'Obst' },
    { id: 'de3-m17', type: 'Match', question: 'Fleisch', answer: 'Kød', options: ['Kød', 'Fisk', 'Kylling'], instruction: 'Essen' },
    { id: 'de3-m18', type: 'Match', question: 'Fisch', answer: 'Fisk', options: ['Kød', 'Fisk', 'Kylling'], instruction: 'Essen' },
    { id: 'de3-m19', type: 'Match', question: 'Hähnchen', answer: 'Kylling', options: ['Kød', 'Fisk', 'Kylling'], instruction: 'Essen' },
    { id: 'de3-m20', type: 'Match', question: 'Reis', answer: 'Ris', options: ['Ris', 'Pasta', 'Nudler'], instruction: 'Essen' },
    { id: 'de3-m21', type: 'Match', question: 'Nudeln', answer: 'Pasta / Nudler', options: ['Ris', 'Pasta', 'Kartofler'], instruction: 'Essen' },
    { id: 'de3-m22', type: 'Match', question: 'Gemüse', answer: 'Grøntsager', options: ['Grøntsager', 'Frugt', 'Kød'], instruction: 'Essen' },
    { id: 'de3-m23', type: 'Match', question: 'Kaffee', answer: 'Kaffe', options: ['Kaffe', 'Te', 'Kakao'], instruction: 'Trinken' },
    { id: 'de3-m24', type: 'Match', question: 'Tee', answer: 'Te', options: ['Kaffe', 'Te', 'Kakao'], instruction: 'Trinken' },
    { id: 'de3-m25', type: 'Match', question: 'Heiß', answer: 'Varm', options: ['Varm', 'Kold', 'Lunken'], instruction: 'Adjektive' },
    { id: 'de3-m26', type: 'Match', question: 'Kalt', answer: 'Kold', options: ['Varm', 'Kold', 'Lunken'], instruction: 'Adjektive' },
    { id: 'de3-m27', type: 'Match', question: 'Groß', answer: 'Stor', options: ['Stor', 'Lille', 'Mellem'], instruction: 'Adjektive' },
    { id: 'de3-m28', type: 'Match', question: 'Klein', answer: 'Lille', options: ['Stor', 'Lille', 'Mellem'], instruction: 'Adjektive' },
    { id: 'de3-m29', type: 'Match', question: 'Schön', answer: 'Smuk', options: ['Smuk', 'Grim', 'Sjov'], instruction: 'Adjektive' },
    { id: 'de3-m30', type: 'Match', question: 'Hässlich', answer: 'Grim', options: ['Smuk', 'Grim', 'Sjov'], instruction: 'Adjektive' },
    { id: 'de3-m31', type: 'Match', question: 'Wolke', answer: 'Sky', options: ['Sky', 'Regn', 'Sne'], instruction: 'Wetter' },
    { id: 'de3-m32', type: 'Match', question: 'Regen', answer: 'Regn', options: ['Sky', 'Regn', 'Sne'], instruction: 'Wetter' },
    { id: 'de3-m33', type: 'Match', question: 'Schnee', answer: 'Sne', options: ['Sky', 'Regn', 'Sne'], instruction: 'Wetter' },
    { id: 'de3-m34', type: 'Match', question: 'Wind', answer: 'Vind', options: ['Vind', 'Storm', 'Blæst'], instruction: 'Wetter' },
    { id: 'de3-m35', type: 'Match', question: 'Himmel', answer: 'Himmel', options: ['Himmel', 'Jord', 'Hav'], instruction: 'Natur' },
    { id: 'de3-m36', type: 'Match', question: 'Erde', answer: 'Jord', options: ['Himmel', 'Jord', 'Hav'], instruction: 'Natur' },
    { id: 'de3-m37', type: 'Match', question: 'Meer', answer: 'Hav', options: ['Himmel', 'Jord', 'Hav'], instruction: 'Natur' },
    { id: 'de3-m38', type: 'Match', question: 'Berg', answer: 'Bjerg', options: ['Bjerg', 'Dal', 'Skov'], instruction: 'Natur' },
    { id: 'de3-m39', type: 'Match', question: 'Wald', answer: 'Skov', options: ['Bjerg', 'Dal', 'Skov'], instruction: 'Natur' },
    { id: 'de3-m40', type: 'Match', question: 'Wieviel Uhr ist es?', answer: 'Hvad er klokken?', options: ['Hvad er klokken?', 'Hvor bor du?', 'Hvad hedder du?'], instruction: 'Fragen' },
    { id: 'de3-m41', type: 'Match', question: 'Wie heißt du?', answer: 'Hvad hedder du?', options: ['Hvad er klokken?', 'Hvor bor du?', 'Hvad hedder du?'], instruction: 'Fragen' },
    { id: 'de3-m42', type: 'Match', question: 'Ich komme aus...', answer: 'Jeg kommer fra...', options: ['Jeg kommer fra...', 'Jeg bor i...', 'Jeg er...'], instruction: 'Vorstellung' },
    { id: 'de3-m43', type: 'Match', question: 'Tisch', answer: 'Bord', options: ['Bord', 'Stol', 'Seng'], instruction: 'Möbel' },
    { id: 'de3-m44', type: 'Match', question: 'Stuhl', answer: 'Stol', options: ['Bord', 'Stol', 'Seng'], instruction: 'Möbel' },
    { id: 'de3-m45', type: 'Match', question: 'Bett', answer: 'Seng', options: ['Bord', 'Stol', 'Seng'], instruction: 'Möbel' },
    { id: 'de3-m46', type: 'Match', question: 'Fenster', answer: 'Vindue', options: ['Vindue', 'Dør', 'Væg'], instruction: 'Haus' },
    { id: 'de3-m47', type: 'Match', question: 'Tür', answer: 'Dør', options: ['Vindue', 'Dør', 'Væg'], instruction: 'Haus' },
    { id: 'de3-m48', type: 'Match', question: 'Schule', answer: 'Skole', options: ['Skole', 'Hus', 'Kirke'], instruction: 'Orte' },
    { id: 'de3-m49', type: 'Match', question: 'Kirche', answer: 'Kirke', options: ['Skole', 'Hus', 'Kirke'], instruction: 'Orte' },
    { id: 'de3-m50', type: 'Match', question: 'Krankenhaus', answer: 'Sygehus', options: ['Skole', 'Hus', 'Sygehus'], instruction: 'Orte' },
    { id: 'de3-m51', type: 'Match', question: 'Polizei', answer: 'Politi', options: ['Politi', 'Brandvæsen', 'Butik'], instruction: 'Orte' },
  ],
  4: [
    { id: 'de4-m1', type: 'Match', question: 'Montag', answer: 'Mandag', options: ['Mandag', 'Tirsdag', 'Onsdag'], instruction: 'Wochentage' },
    { id: 'de4-m2', type: 'Match', question: 'Dienstag', answer: 'Tirsdag', options: ['Mandag', 'Tirsdag', 'Onsdag'], instruction: 'Wochentage' },
    { id: 'de4-m3', type: 'Match', question: 'Mittwoch', answer: 'Onsdag', options: ['Mandag', 'Tirsdag', 'Onsdag'], instruction: 'Wochentage' },
    { id: 'de4-m4', type: 'Match', question: 'Donnerstag', answer: 'Torsdag', options: ['Torsdag', 'Fredag', 'Samstag'], instruction: 'Wochentage' },
    { id: 'de4-m5', type: 'Match', question: 'Freitag', answer: 'Fredag', options: ['Torsdag', 'Fredag', 'Samstag'], instruction: 'Wochentage' },
    { id: 'de4-m6', type: 'Match', question: 'Samstag', answer: 'Lørdag', options: ['Torsdag', 'Fredag', 'Samstag'], instruction: 'Wochentage' },
    { id: 'de4-m7', type: 'Match', question: 'Sonntag', answer: 'Søndag', options: ['Torsdag', 'Fredag', 'Sonntag'], instruction: 'Wochentage' },
    { id: 'de4-m8', type: 'Match', question: 'Schule', answer: '🏫', options: ['🏫', '🏠', '🏥'], instruction: 'Orte' },
    { id: 'de4-m9', type: 'Match', question: 'Auto', answer: '🚗', options: ['🚗', '🚲', '🚆'], instruction: 'Verkehr' },
    { id: 'de4-m10', type: 'Match', question: 'Fahrrad', answer: '🚲', options: ['🚗', '🚲', '🚆'], instruction: 'Verkehr' },
    { id: 'de4-m11', type: 'Match', question: 'Januar', answer: 'Januar', options: ['Januar', 'Februar', 'Marts'], instruction: 'Monate' },
    { id: 'de4-m12', type: 'Match', question: 'Februar', answer: 'Februar', options: ['Januar', 'Februar', 'Marts'], instruction: 'Monate' },
    { id: 'de4-m13', type: 'Match', question: 'März', answer: 'Marts', options: ['Januar', 'Februar', 'Marts'], instruction: 'Monate' },
    { id: 'de4-m14', type: 'Match', question: 'April', answer: 'April', options: ['April', 'Maj', 'Juni'], instruction: 'Monate' },
    { id: 'de4-m15', type: 'Match', question: 'Mai', answer: 'Maj', options: ['April', 'Maj', 'Juni'], instruction: 'Monate' },
    { id: 'de4-m16', type: 'Match', question: 'Juni', answer: 'Juni', options: ['April', 'Maj', 'Juni'], instruction: 'Monate' },
    { id: 'de4-m17', type: 'Match', question: 'Juli', answer: 'Juli', options: ['Juli', 'August', 'September'], instruction: 'Monate' },
    { id: 'de4-m18', type: 'Match', question: 'August', answer: 'August', options: ['Juli', 'August', 'September'], instruction: 'Monate' },
    { id: 'de4-m19', type: 'Match', question: 'September', answer: 'September', options: ['Juli', 'August', 'September'], instruction: 'Monate' },
    { id: 'de4-m20', type: 'Match', question: 'Oktober', answer: 'Oktober', options: ['Oktober', 'November', 'Dezember'], instruction: 'Monate' },
    { id: 'de4-m21', type: 'Match', question: 'November', answer: 'November', options: ['Oktober', 'November', 'Dezember'], instruction: 'Monate' },
    { id: 'de4-m22', type: 'Match', question: 'Dezember', answer: 'December', options: ['Oktober', 'November', 'Dezember'], instruction: 'Monate' },
    { id: 'de4-m23', type: 'Match', question: 'Frühling', answer: 'Forår', options: ['Forår', 'Sommer', 'Herbst', 'Winter'], instruction: 'Jahreszeiten' },
    { id: 'de4-m24', type: 'Match', question: 'Sommer', answer: 'Sommer', options: ['Forår', 'Sommer', 'Herbst', 'Winter'], instruction: 'Jahreszeiten' },
    { id: 'de4-m25', type: 'Match', question: 'Herbst', answer: 'Efterår', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Jahreszeiten' },
    { id: 'de4-m26', type: 'Match', question: 'Winter', answer: 'Vinter', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Jahreszeiten' },
    { id: 'de4-m27', type: 'Match', question: 'Kleidung', answer: 'Tøj', options: ['Tøj', 'Mad', 'Drikke'], instruction: 'Kategorie' },
    { id: 'de4-m28', type: 'Match', question: 'Hose', answer: 'Bukser', options: ['Bukser', 'Bluse', 'Sko'], instruction: 'Kleidung' },
    { id: 'de4-m29', type: 'Match', question: 'Hemd', answer: 'Skjorte', options: ['Bukser', 'Skjorte', 'Jakke'], instruction: 'Kleidung' },
    { id: 'de4-m30', type: 'Match', question: 'Jacke', answer: 'Jakke', options: ['Bukser', 'Skjorte', 'Jakke'], instruction: 'Kleidung' },
    { id: 'de4-m31', type: 'Match', question: 'Schuhe', answer: 'Sko', options: ['Sko', 'Strømper', 'Hue'], instruction: 'Kleidung' },
    { id: 'de4-m32', type: 'Match', question: 'Socken', answer: 'Strømper', options: ['Sko', 'Strømper', 'Hue'], instruction: 'Kleidung' },
    { id: 'de4-m33', type: 'Match', question: 'Mütze', answer: 'Hue', options: ['Sko', 'Strømper', 'Hue'], instruction: 'Kleidung' },
    { id: 'de4-m34', type: 'Match', question: 'Handschuhe', answer: 'Handsker', options: ['Handsker', 'Tørklæde', 'Bælte'], instruction: 'Kleidung' },
    { id: 'de4-m35', type: 'Match', question: 'Schal', answer: 'Tørklæde', options: ['Handsker', 'Tørklæde', 'Bælte'], instruction: 'Kleidung' },
    { id: 'de4-m36', type: 'Match', question: 'Gürtel', answer: 'Bælte', options: ['Handsker', 'Tørklæde', 'Bælte'], instruction: 'Kleidung' },
    { id: 'de4-m37', type: 'Match', question: 'Kaufen', answer: 'Købe', options: ['Købe', 'Sælge', 'Bytte'], instruction: 'Verben' },
    { id: 'de4-m38', type: 'Match', question: 'Verkaufen', answer: 'Sælge', options: ['Købe', 'Sælge', 'Bytte'], instruction: 'Verben' },
    { id: 'de4-m39', type: 'Match', question: 'Suchen', answer: 'Søge / Lede efter', options: ['Søge', 'Finde', 'Miste'], instruction: 'Verben' },
    { id: 'de4-m40', type: 'Match', question: 'Finden', answer: 'Finde', options: ['Søge', 'Finde', 'Miste'], instruction: 'Verben' },
    { id: 'de4-m41', type: 'Match', question: 'Bringen', answer: 'Bringe / Hente', options: ['Bringe', 'Tage', 'Give'], instruction: 'Verben' },
    { id: 'de4-m42', type: 'Match', question: 'Holen', answer: 'Hente', options: ['Bringe', 'Hente', 'Sende'], instruction: 'Verben' },
    { id: 'de4-m43', type: 'Match', question: 'Senden', answer: 'Sende', options: ['Bringe', 'Hente', 'Sende'], instruction: 'Verben' },
    { id: 'de4-m44', type: 'Match', question: 'Empfangen', answer: 'Modtage', options: ['Modtage', 'Sende', 'Give'], instruction: 'Verben' },
    { id: 'de4-m45', type: 'Match', question: 'Zahlen', answer: 'Betale', options: ['Betale', 'Tælle', 'Regne'], instruction: 'Verben' },
    { id: 'de4-m46', type: 'Match', question: 'Zählen', answer: 'Tælle', options: ['Betale', 'Tælle', 'Regne'], instruction: 'Verben' },
    { id: 'de4-m47', type: 'Match', question: 'Rechnen', answer: 'Regne', options: ['Betale', 'Tælle', 'Regne'], instruction: 'Verben' },
    { id: 'de4-m48', type: 'Match', question: 'Schreiben', answer: 'Skrive', options: ['Skrive', 'Læse', 'Høre'], instruction: 'Verben' },
    { id: 'de4-m49', type: 'Match', question: 'Lesen', answer: 'Læse', options: ['Skrive', 'Læse', 'Høre'], instruction: 'Verben' },
    { id: 'de4-m50', type: 'Match', question: 'Hören', answer: 'Høre', options: ['Skrive', 'Læse', 'Høre'], instruction: 'Verben' },
    { id: 'de4-m51', type: 'Match', question: 'Sehen', answer: 'Se', options: ['Se', 'Høre', 'Føle'], instruction: 'Verben' },
  ],
  5: [
    { id: 'de5-m1', type: 'Match', question: 'Lehrer', answer: 'Lærer', options: ['Lærer', 'Elev', 'Skole'], instruction: 'Schule' },
    { id: 'de5-m2', type: 'Match', question: 'Schüler', answer: 'Elev', options: ['Lærer', 'Elev', 'Skole'], instruction: 'Schule' },
    { id: 'de5-m3', type: 'Match', question: 'Hausaufgabe', answer: 'Lektier', options: ['Lektier', 'Pause', 'Fag'], instruction: 'Schule' },
    { id: 'de5-m4', type: 'Match', question: 'Fußball', answer: 'Fodbold', options: ['Fodbold', 'Tennis', 'Svømning'], instruction: 'Hobbys' },
    { id: 'de5-m5', type: 'Match', question: 'Schwimmen', answer: 'Svømning', options: ['Fodbold', 'Tennis', 'Svømning'], instruction: 'Hobbys' },
    { id: 'de5-m6', type: 'Match', question: 'Singen', answer: 'Synge', options: ['Synge', 'Danse', 'Male'], instruction: 'Hobbys' },
    { id: 'de5-m7', type: 'Match', question: 'Tanzen', answer: 'Danse', options: ['Synge', 'Danse', 'Male'], instruction: 'Hobbys' },
    { id: 'de5-m8', type: 'Match', question: 'Malen', answer: 'Male', options: ['Synge', 'Danse', 'Male'], instruction: 'Hobbys' },
    { id: 'de5-m9', type: 'Match', question: 'Frühling', answer: 'Forår', options: ['Forår', 'Sommer', 'Herbst', 'Winter'], instruction: 'Jahreszeiten' },
    { id: 'de5-m10', type: 'Match', question: 'Winter', answer: 'Vinter', options: ['Frühling', 'Sommer', 'Herbst', 'Winter'], instruction: 'Jahreszeiten' },
    { id: 'de5-m11', type: 'Match', question: 'Klassenzimmer', answer: 'Klasseværelse', options: ['Klasseværelse', 'Gymnastiksal', 'Skolegård'], instruction: 'Schule' },
    { id: 'de5-m12', type: 'Match', question: 'Gymnastikhalle', answer: 'Gymnastiksal', options: ['Klasseværelse', 'Gymnastiksal', 'Skolegård'], instruction: 'Schule' },
    { id: 'de5-m13', type: 'Match', question: 'Pausenhof', answer: 'Skolegård', options: ['Klasseværelse', 'Gymnastiksal', 'Skolegård'], instruction: 'Schule' },
    { id: 'de5-m14', type: 'Match', question: 'Mathe', answer: 'Matematik', options: ['Matematik', 'Tysk', 'Engelsk'], instruction: 'Fächer' },
    { id: 'de5-m15', type: 'Match', question: 'Deutsch', answer: 'Tysk', options: ['Matematik', 'Tysk', 'Engelsk'], instruction: 'Fächer' },
    { id: 'de5-m16', type: 'Match', question: 'Englisch', answer: 'Engelsk', options: ['Matematik', 'Tysk', 'Engelsk'], instruction: 'Fächer' },
    { id: 'de5-m17', type: 'Match', question: 'Sport', answer: 'Idræt', options: ['Idræt', 'Musik', 'Billedkunst'], instruction: 'Fächer' },
    { id: 'de5-m18', type: 'Match', question: 'Musik', answer: 'Musik', options: ['Idræt', 'Musik', 'Billedkunst'], instruction: 'Fächer' },
    { id: 'de5-m19', type: 'Match', question: 'Kunst', answer: 'Billedkunst', options: ['Idræt', 'Musik', 'Billedkunst'], instruction: 'Fächer' },
    { id: 'de5-m20', type: 'Match', question: 'Bleistift', answer: 'Blyant', options: ['Blyant', 'Kuglepen', 'Viskelæder'], instruction: 'Schulmaterial' },
    { id: 'de5-m21', type: 'Match', question: 'Kugelschreiber', answer: 'Kuglepen', options: ['Blyant', 'Kuglepen', 'Viskelæder'], instruction: 'Schulmaterial' },
    { id: 'de5-m22', type: 'Match', question: 'Radiergummi', answer: 'Viskelæder', options: ['Blyant', 'Kuglepen', 'Viskelæder'], instruction: 'Schulmaterial' },
    { id: 'de5-m23', type: 'Match', question: 'Lineal', answer: 'Lineal', options: ['Lineal', 'Bog', 'Hæfte'], instruction: 'Schulmaterial' },
    { id: 'de5-m24', type: 'Match', question: 'Buch', answer: 'Bog', options: ['Lineal', 'Bog', 'Hæfte'], instruction: 'Schulmaterial' },
    { id: 'de5-m25', type: 'Match', question: 'Heft', answer: 'Hæfte', options: ['Lineal', 'Bog', 'Hæfte'], instruction: 'Schulmaterial' },
    { id: 'de5-m26', type: 'Match', question: 'Einfach', answer: 'Nem / Enkel', options: ['Nem', 'Svær', 'Sjov'], instruction: 'Adjektive' },
    { id: 'de5-m27', type: 'Match', question: 'Schwierig', answer: 'Svær', options: ['Nem', 'Svær', 'Sjov'], instruction: 'Adjektive' },
    { id: 'de5-m28', type: 'Match', question: 'Lustig', answer: 'Sjov', options: ['Nem', 'Svær', 'Sjov'], instruction: 'Adjektive' },
    { id: 'de5-m29', type: 'Match', question: 'Langweilig', answer: 'Kedelig', options: ['Kedelig', 'Spændende', 'Hurtig'], instruction: 'Adjektive' },
    { id: 'de5-m30', type: 'Match', question: 'Spannend', answer: 'Spændende', options: ['Kedelig', 'Spændende', 'Hurtig'], instruction: 'Adjektive' },
    { id: 'de5-m31', type: 'Match', question: 'Oft', answer: 'Ofte', options: ['Ofte', 'Sjældent', 'Aldrig'], instruction: 'Adverbien' },
    { id: 'de5-m32', type: 'Match', question: 'Selten', answer: 'Sjældent', options: ['Ofte', 'Sjældent', 'Aldrig'], instruction: 'Adverbien' },
    { id: 'de5-m33', type: 'Match', question: 'Immer', answer: 'Altid', options: ['Altid', 'Aldrig', 'Måske'], instruction: 'Adverbien' },
    { id: 'de5-m34', type: 'Match', question: 'Nie', answer: 'Aldrig', options: ['Altid', 'Aldrig', 'Måske'], instruction: 'Adverbien' },
    { id: 'de5-m35', type: 'Match', question: 'Vielleicht', answer: 'Måske', options: ['Altid', 'Aldrig', 'Måske'], instruction: 'Adverbien' },
    { id: 'de5-m36', type: 'Match', question: 'Gestern', answer: 'I går', options: ['I går', 'I dag', 'I morgen'], instruction: 'Zeit' },
    { id: 'de5-m37', type: 'Match', question: 'Heute', answer: 'I dag', options: ['I går', 'I dag', 'I morgen'], instruction: 'Zeit' },
    { id: 'de5-m38', type: 'Match', question: 'Morgen (Zeit)', answer: 'I morgen', options: ['I går', 'I dag', 'I morgen'], instruction: 'Zeit' },
    { id: 'de5-m39', type: 'Match', question: 'Früh', answer: 'Tidligt', options: ['Tidligt', 'Sent', 'Nu'], instruction: 'Zeit' },
    { id: 'de5-m40', type: 'Match', question: 'Spät', answer: 'Sent', options: ['Tidligt', 'Sent', 'Nu'], instruction: 'Zeit' },
    { id: 'de5-m41', type: 'Match', question: 'Jetzt', answer: 'Nu', options: ['Tidligt', 'Sent', 'Nu'], instruction: 'Zeit' },
    { id: 'de5-m42', type: 'Match', question: 'Kommen', answer: 'Komme', options: ['Komme', 'Gå', 'Blive'], instruction: 'Verben' },
    { id: 'de5-m43', type: 'Match', question: 'Bleiben', answer: 'Blive', options: ['Komme', 'Gå', 'Blive'], instruction: 'Verben' },
    { id: 'de5-m44', type: 'Match', question: 'Haben', answer: 'Have', options: ['Have', 'Være', 'Blive'], instruction: 'Verben' },
    { id: 'de5-m45', type: 'Match', question: 'Sein', answer: 'Være', options: ['Have', 'Være', 'Blive'], instruction: 'Verben' },
    { id: 'de5-m46', type: 'Match', question: 'Tun', answer: 'Gøre', options: ['Gøre', 'Sige', 'Høre'], instruction: 'Verben' },
    { id: 'de5-m47', type: 'Match', question: 'Sagen', answer: 'Sige', options: ['Gøre', 'Sige', 'Høre'], instruction: 'Verben' },
    { id: 'de5-m48', type: 'Match', question: 'Fragen', answer: 'Spørge', options: ['Spørge', 'Svare', 'Lytte'], instruction: 'Verben' },
    { id: 'de5-m49', type: 'Match', question: 'Antworten', answer: 'Svare', options: ['Spørge', 'Svare', 'Lytte'], instruction: 'Verben' },
    { id: 'de5-m50', type: 'Match', question: 'Zuhören', answer: 'Lytte', options: ['Spørge', 'Svare', 'Lytte'], instruction: 'Verben' },
    { id: 'de5-m51', type: 'Match', question: 'Reden', answer: 'Tale', options: ['Tale', 'Skrive', 'Læse'], instruction: 'Verben' },
  ],
  6: [
    { id: 'de6-m1', type: 'Match', question: 'Ich heiße...', answer: 'Jeg hedder...', options: ['Jeg hedder...', 'Jeg er...', 'Jeg kommer fra...'], instruction: 'Vorstellung' },
    { id: 'de6-m2', type: 'Match', question: 'Wo wohnst du?', answer: 'Hvor bor du?', options: ['Hvor bor du?', 'Hvordan har du det?', 'Hvad laver du?'], instruction: 'Fragen' },
    { id: 'de6-m3', type: 'Match', question: 'Wie geht’s?', answer: 'Hvordan går det?', options: ['Hvor bor du?', 'Hvordan har du det?', 'Hvad laver du?'], instruction: 'Fragen' },
    { id: 'de6-m4', type: 'Match', question: 'Der Bruder', answer: 'Bror', options: ['Bror', 'Søster', 'Fætter'], instruction: 'Familie' },
    { id: 'de6-m5', type: 'Match', question: 'Die Schwester', answer: 'Søster', options: ['Bror', 'Søster', 'Fætter'], instruction: 'Familie' },
    { id: 'de6-m6', type: 'Match', question: 'Der Schrank', answer: 'Skabet', options: ['Skabet', 'Bordet', 'Stolen'], instruction: 'Möbel' },
    { id: 'de6-m7', type: 'Match', question: 'Die Stadt', answer: 'Byen', options: ['Byen', 'Landet', 'Skoven'], instruction: 'Orte' },
    { id: 'de6-m8', type: 'Match', question: 'Das Dorf', answer: 'Landsbyen', options: ['Byen', 'Landsbyen', 'Skoven'], instruction: 'Orte' },
    { id: 'de6-m9', type: 'Match', question: 'Zwanzig', answer: '20', options: ['20', '30', '40'], instruction: 'Zahlen' },
    { id: 'de6-m10', type: 'Match', question: 'Dreißig', answer: '30', options: ['20', '30', '40'], instruction: 'Zahlen' },
    { id: 'de6-m11', type: 'Match', question: 'Vierzig', answer: '40', options: ['40', '50', '60', '70'], instruction: 'Zahlen' },
    { id: 'de6-m12', type: 'Match', question: 'Fünfzig', answer: '50', options: ['40', '50', '60', '70'], instruction: 'Zahlen' },
    { id: 'de6-m13', type: 'Match', question: 'Sechzig', answer: '60', options: ['40', '50', '60', '70'], instruction: 'Zahlen' },
    { id: 'de6-m14', type: 'Match', question: 'Siebzig', answer: '70', options: ['40', '50', '60', '70'], instruction: 'Zahlen' },
    { id: 'de6-m15', type: 'Match', question: 'Achtzig', answer: '80', options: ['80', '90', '100'], instruction: 'Zahlen' },
    { id: 'de6-m16', type: 'Match', question: 'Neunzig', answer: '90', options: ['80', '90', '100'], instruction: 'Zahlen' },
    { id: 'de6-m17', type: 'Match', question: 'Hundert', answer: '100', options: ['80', '90', '100'], instruction: 'Zahlen' },
    { id: 'de6-m18', type: 'Match', question: 'Was ist das?', answer: 'Hvad er det?', options: ['Hvad er det?', 'Hvem er det?', 'Hvor er det?'], instruction: 'Fragen' },
    { id: 'de6-m19', type: 'Match', question: 'Wer ist das?', answer: 'Hvem er det?', options: ['Hvad er det?', 'Hvem er det?', 'Hvor er det?'], instruction: 'Fragen' },
    { id: 'de6-m20', type: 'Match', question: 'Wo ist das?', answer: 'Hvor er det?', options: ['Hvad er det?', 'Hvem er det?', 'Hvor er det?'], instruction: 'Fragen' },
    { id: 'de6-m21', type: 'Match', question: 'Die Küche', answer: 'Køkkenet', options: ['Køkkenet', 'Badeværelset', 'Soveværelset'], instruction: 'Haus' },
    { id: 'de6-m22', type: 'Match', question: 'Das Badezimmer', answer: 'Badeværelset', options: ['Køkkenet', 'Badeværelset', 'Soveværelset'], instruction: 'Haus' },
    { id: 'de6-m23', type: 'Match', question: 'Das Schlafzimmer', answer: 'Soveværelset', options: ['Køkkenet', 'Badeværelset', 'Soveværelset'], instruction: 'Haus' },
    { id: 'de6-m24', type: 'Match', question: 'Das Wohnzimmer', answer: 'Stuen', options: ['Stuen', 'Haven', 'Gangen'], instruction: 'Haus' },
    { id: 'de6-m25', type: 'Match', question: 'Der Garten', answer: 'Haven', options: ['Stuen', 'Haven', 'Gangen'], instruction: 'Haus' },
    { id: 'de6-m26', type: 'Match', question: 'Der Flur', answer: 'Gangen', options: ['Stuen', 'Haven', 'Gangen'], instruction: 'Haus' },
    { id: 'de6-m27', type: 'Match', question: 'Das Frühstück', answer: 'Morgenmad', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Essen' },
    { id: 'de6-m28', type: 'Match', question: 'Das Mittagessen', answer: 'Frokost', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Essen' },
    { id: 'de6-m29', type: 'Match', question: 'Das Abendessen', answer: 'Aftensmad', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Essen' },
    { id: 'de6-m30', type: 'Match', question: 'Der Hunger', answer: 'Sult', options: ['Sult', 'Tørst', 'Træthed'], instruction: 'Gefühle' },
    { id: 'de6-m31', type: 'Match', question: 'Der Durst', answer: 'Tørst', options: ['Sult', 'Tørst', 'Træthed'], instruction: 'Gefühle' },
    { id: 'de6-m32', type: 'Match', question: 'Der Sport', answer: 'Sport', options: ['Sport', 'Musik', 'Film'], instruction: 'Hobbys' },
    { id: 'de6-m33', type: 'Match', question: 'Das Kino', answer: 'Biografen', options: ['Biografen', 'Teatret', 'Museet'], instruction: 'Freizeit' },
    { id: 'de6-m34', type: 'Match', question: 'Die Musik', answer: 'Musikken', options: ['Musikken', 'Dansen', 'Kunsten'], instruction: 'Freizeit' },
    { id: 'de6-m35', type: 'Match', question: 'Der Film', answer: 'Filmen', options: ['Filmen', 'Bogen', 'Spillet'], instruction: 'Freizeit' },
    { id: 'de6-m36', type: 'Match', question: 'Sprechen', answer: 'Tale', options: ['Tale', 'Læse', 'Skrive'], instruction: 'Verben' },
    { id: 'de6-m37', type: 'Match', question: 'Verstehen', answer: 'Forstå', options: ['Forstå', 'Glemme', 'Høre'], instruction: 'Verben' },
    { id: 'de6-m38', type: 'Match', question: 'Wissen', answer: 'Vide', options: ['Vide', 'Tro', 'Håbe'], instruction: 'Verben' },
    { id: 'de6-m39', type: 'Match', question: 'Glauben', answer: 'Tro', options: ['Vide', 'Tro', 'Håbe'], instruction: 'Verben' },
    { id: 'de6-m40', type: 'Match', question: 'Hoffen', answer: 'Håbe', options: ['Vide', 'Tro', 'Håbe'], instruction: 'Verben' },
    { id: 'de6-m41', type: 'Match', question: 'Kalt', answer: 'Kold', options: ['Kold', 'Varm', 'Lunken'], instruction: 'Adjektive' },
    { id: 'de6-m42', type: 'Match', question: 'Warm', answer: 'Varm', options: ['Kold', 'Varm', 'Lunken'], instruction: 'Adjektive' },
    { id: 'de6-m43', type: 'Match', question: 'Klein', answer: 'Lille', options: ['Lille', 'Stor', 'Mellem'], instruction: 'Adjektive' },
    { id: 'de6-m44', type: 'Match', question: 'Groß', answer: 'Stor', options: ['Lille', 'Stor', 'Mellem'], instruction: 'Adjektive' },
    { id: 'de6-m45', type: 'Match', question: 'Reich', answer: 'Rig', options: ['Rig', 'Fattig', 'Glad'], instruction: 'Adjektive' },
    { id: 'de6-m46', type: 'Match', question: 'Arm (Adjektiv)', answer: 'Fattig', options: ['Rig', 'Fattig', 'Glad'], instruction: 'Adjektive' },
    { id: 'de6-m47', type: 'Match', question: 'Glücklich', answer: 'Lykkelig', options: ['Lykkelig', 'Trist', 'Gal'], instruction: 'Adjektive' },
    { id: 'de6-m48', type: 'Match', question: 'Traurig', answer: 'Trist', options: ['Lykkelig', 'Trist', 'Gal'], instruction: 'Adjektive' },
    { id: 'de6-m49', type: 'Match', question: 'Alt', answer: 'Gammel', options: ['Gammel', 'Ung', 'Ny'], instruction: 'Adjektive' },
    { id: 'de6-m50', type: 'Match', question: 'Jung', answer: 'Ung', options: ['Gammel', 'Ung', 'Ny'], instruction: 'Adjektive' },
    { id: 'de6-m51', type: 'Match', question: 'Neu', answer: 'Ny', options: ['Gammel', 'Ung', 'Ny'], instruction: 'Adjektive' },
  ],
  7: [
    { id: 'de7-m1', type: 'Match', question: 'Berlin', answer: 'Hauptstadt', options: ['Hauptstadt', 'Fluss', 'Berg'], instruction: 'Kultur' },
    { id: 'de7-m2', type: 'Match', question: 'Brandenburger Tor', answer: 'Berlin', options: ['Berlin', 'München', 'Hamburg'], instruction: 'Sehenswürdigkeiten' },
    { id: 'de7-m3', type: 'Match', question: 'Das T-Shirt', answer: '👕', options: ['👕', '👖', '👗'], instruction: 'Kleidung' },
    { id: 'de7-m4', type: 'Match', question: 'Die Hose', answer: '👖', options: ['👕', '👖', '👗'], instruction: 'Kleidung' },
    { id: 'de7-m5', type: 'Match', question: 'Das Kleid', answer: '👗', options: ['👕', '👖', '👗'], instruction: 'Kleidung' },
    { id: 'de7-m6', type: 'Match', question: 'Die Reise', answer: 'Rejsen', options: ['Rejsen', 'Skolen', 'Arbejdet'], instruction: 'Urlaub' },
    { id: 'de7-m7', type: 'Match', question: 'Der Koffer', answer: 'Kufferten', options: ['Kufferten', 'Bogen', 'Tasken'], instruction: 'Reisen' },
    { id: 'de7-m8', type: 'Match', question: 'Der Bahnhof', answer: 'Banegården', options: ['Banegården', 'Flughafen', 'Hafen'], instruction: 'Transport' },
    { id: 'de7-m9', type: 'Match', question: 'Einhundert', answer: '100', options: ['100', '200', '1000'], instruction: 'Zahlen' },
    { id: 'de7-m10', type: 'Match', question: 'Tausend', answer: '1000', options: ['100', '200', '1000'], instruction: 'Zahlen' },
    { id: 'de7-m11', type: 'Match', question: 'Der Flughafen', answer: 'Lufthavnen', options: ['Lufthavnen', 'Banegården', 'Havnen'], instruction: 'Transport' },
    { id: 'de7-m12', type: 'Match', question: 'Das Flugzeug', answer: 'Flyet', options: ['Flyet', 'Bilen', 'Toget'], instruction: 'Transport' },
    { id: 'de7-m13', type: 'Match', question: 'Der Reisepass', answer: 'Passet', options: ['Passet', 'Billetten', 'Tasken'], instruction: 'Reisen' },
    { id: 'de7-m14', type: 'Match', question: 'Die Fahrkarte', answer: 'Billetten', options: ['Passet', 'Billetten', 'Tasken'], instruction: 'Reisen' },
    { id: 'de7-m15', type: 'Match', question: 'Das Gepäck', answer: 'Bagagen', options: ['Bagagen', 'Tøjet', 'Maden'], instruction: 'Reisen' },
    { id: 'de7-m16', type: 'Match', question: 'Der Urlaub', answer: 'Ferie', options: ['Ferie', 'Arbejde', 'Skole'], instruction: 'Urlaub' },
    { id: 'de7-m17', type: 'Match', question: 'Die Ferien', answer: 'Ferie (flertal)', options: ['Ferie', 'Arbejde', 'Skole'], instruction: 'Urlaub' },
    { id: 'de7-m18', type: 'Match', question: 'Das Hotel', answer: 'Hotellet', options: ['Hotellet', 'Huset', 'Teltet'], instruction: 'Urlaub' },
    { id: 'de7-m19', type: 'Match', question: 'Der Strand', answer: 'Stranden', options: ['Stranden', 'Skoven', 'Bjerget'], instruction: 'Urlaub' },
    { id: 'de7-m20', type: 'Match', question: 'Das Meer', answer: 'Havet', options: ['Havet', 'Søen', 'Floden'], instruction: 'Urlaub' },
    { id: 'de7-m21', type: 'Match', question: 'Der See', answer: 'Søen', options: ['Havet', 'Søen', 'Floden'], instruction: 'Urlaub' },
    { id: 'de7-m22', type: 'Match', question: 'Der Fluss', answer: 'Floden', options: ['Havet', 'Søen', 'Floden'], instruction: 'Urlaub' },
    { id: 'de7-m23', type: 'Match', question: 'Wandern', answer: 'Vandre', options: ['Vandre', 'Svømme', 'Cykle'], instruction: 'Aktivitäten' },
    { id: 'de7-m24', type: 'Match', question: 'Besichtigen', answer: 'Se på seværdigheder', options: ['Se på seværdigheder', 'Spise', 'Sove'], instruction: 'Aktivitäten' },
    { id: 'de7-m25', type: 'Match', question: 'Einkaufen', answer: 'Købe ind', options: ['Købe ind', 'Sælge', 'Bytte'], instruction: 'Aktivitäten' },
    { id: 'de7-m26', type: 'Match', question: 'Der Kanzler', answer: 'Kansleren', options: ['Kansleren', 'Præsidenten', 'Kongen'], instruction: 'Kultur' },
    { id: 'de7-m27', type: 'Match', question: 'Die Politik', answer: 'Politik', options: ['Politik', 'Sport', 'Kunst'], instruction: 'Kultur' },
    { id: 'de7-m28', type: 'Match', question: 'Die Wirtschaft', answer: 'Økonomi', options: ['Økonomi', 'Sprog', 'Historie'], instruction: 'Kultur' },
    { id: 'de7-m29', type: 'Match', question: 'Die Geschichte', answer: 'Historie', options: ['Historie', 'Geografi', 'Biologi'], instruction: 'Kultur' },
    { id: 'de7-m30', type: 'Match', question: 'Die Kunst', answer: 'Kunsten', options: ['Kunsten', 'Musikken', 'Sporten'], instruction: 'Kultur' },
    { id: 'de7-m31', type: 'Match', question: 'Der Sportler', answer: 'Sportsmanden', options: ['Sportsmanden', 'Kunstneren', 'Politikeren'], instruction: 'Personen' },
    { id: 'de7-m32', type: 'Match', question: 'Die Künstlerin', answer: 'Kunstnerinden', options: ['Sportsmanden', 'Kunstnerinden', 'Politikeren'], instruction: 'Personen' },
    { id: 'de7-m33', type: 'Match', question: 'Der Politiker', answer: 'Politikeren', options: ['Sportsmanden', 'Kunstneren', 'Politikeren'], instruction: 'Personen' },
    { id: 'de7-m34', type: 'Match', question: 'Der Arzt', answer: 'Lægen', options: ['Lægen', 'Læreren', 'Bonden'], instruction: 'Personen' },
    { id: 'de7-m35', type: 'Match', question: 'Die Lehrerin', answer: 'Lærerinden', options: ['Lægen', 'Lærerinden', 'Bonden'], instruction: 'Personen' },
    { id: 'de7-m36', type: 'Match', question: 'Der Bauer', answer: 'Bonden', options: ['Lægen', 'Læreren', 'Bonden'], instruction: 'Personen' },
    { id: 'de7-m37', type: 'Match', question: 'Ich habe', answer: 'Jeg har', options: ['Jeg har', 'Du har', 'Han har'], instruction: 'Grammatik' },
    { id: 'de7-m38', type: 'Match', question: 'Du hast', answer: 'Du har', options: ['Jeg har', 'Du har', 'Han har'], instruction: 'Grammatik' },
    { id: 'de7-m39', type: 'Match', question: 'Er/Sie/Es hat', answer: 'Han/hun/det har', options: ['Jeg har', 'Du har', 'Han/hun/det har'], instruction: 'Grammatik' },
    { id: 'de7-m40', type: 'Match', question: 'Wir haben', answer: 'Vi har', options: ['Vi har', 'I har', 'De har'], instruction: 'Grammatik' },
    { id: 'de7-m41', type: 'Match', question: 'Ihr habt', answer: 'I har', options: ['Vi har', 'I har', 'De har'], instruction: 'Grammatik' },
    { id: 'de7-m42', type: 'Match', question: 'Sie haben', answer: 'De/De har', options: ['Vi har', 'I har', 'De har'], instruction: 'Grammatik' },
    { id: 'de7-m43', type: 'Match', question: 'Ich bin', answer: 'Jeg er', options: ['Jeg er', 'Du er', 'Han er'], instruction: 'Grammatik' },
    { id: 'de7-m44', type: 'Match', question: 'Du bist', answer: 'Du er', options: ['Jeg er', 'Du er', 'Han er'], instruction: 'Grammatik' },
    { id: 'de7-m45', type: 'Match', question: 'Er/Sie/Es ist', answer: 'Han/hun/det er', options: ['Jeg er', 'Du er', 'Han/hun/det er'], instruction: 'Grammatik' },
    { id: 'de7-m46', type: 'Match', question: 'Wir sind', answer: 'Vi er', options: ['Vi er', 'I er', 'De er'], instruction: 'Grammatik' },
    { id: 'de7-m47', type: 'Match', question: 'Ihr seid', answer: 'I er (flertal)', options: ['Vi er', 'I er', 'De er'], instruction: 'Grammatik' },
    { id: 'de7-m48', type: 'Match', question: 'Sie sind', answer: 'De/De er', options: ['Vi er', 'I er', 'De er'], instruction: 'Grammatik' },
    { id: 'de7-m49', type: 'Match', question: 'Der Apfel', answer: 'Maskulinum', options: ['Maskulinum', 'Femininum', 'Neutrum'], instruction: 'Artikel' },
    { id: 'de7-m50', type: 'Match', question: 'Die Birne', answer: 'Femininum', options: ['Maskulinum', 'Femininum', 'Neutrum'], instruction: 'Artikel' },
    { id: 'de7-m51', type: 'Match', question: 'Das Buch', answer: 'Neutrum', options: ['Maskulinum', 'Femininum', 'Neutrum'], instruction: 'Artikel' },
  ],
  8: [
    { id: 'de8-m1', type: 'Match', question: 'Umwelt', answer: 'Miljø', options: ['Miljø', 'Skole', 'Sport'], instruction: 'Themen' },
    { id: 'de8-m2', type: 'Match', question: 'Müll', answer: 'Affald', options: ['Affald', 'Mad', 'Vand'], instruction: 'Umwelt' },
    { id: 'de8-m3', type: 'Match', question: 'Recycling', answer: 'Genbrug', options: ['Genbrug', 'Spild', 'Brug'], instruction: 'Umwelt' },
    { id: 'de8-m4', type: 'Match', question: 'Musik', answer: 'Kunst', options: ['Kunst', 'Sport', 'Technik'], instruction: 'Kategorien' },
    { id: 'de8-m5', type: 'Match', question: 'Geschichte', answer: 'Vergangenheit', options: ['Vergangenheit', 'Zukunft', 'Gegenwart'], instruction: 'Begriffe' },
    { id: 'de8-m6', type: 'Match', question: 'Die Mauer', answer: 'Muren', options: ['Muren', 'Huset', 'Vejen'], instruction: 'Geschichte' },
    { id: 'de8-m7', type: 'Match', question: 'Trennung', answer: 'Adskillelse', options: ['Adskillelse', 'Samling', 'Frihed'], instruction: 'Begriffe' },
    { id: 'de8-m8', type: 'Match', question: 'Wiedervereinigung', answer: 'Genforening', options: ['Genforening', 'Krig', 'Fred'], instruction: 'Geschichte' },
    { id: 'de8-m9', type: 'Match', question: 'Gefährlich', answer: 'Farlig', options: ['Farlig', 'Sikker', 'Sjov'], instruction: 'Adjektive' },
    { id: 'de8-m10', type: 'Match', question: 'Wichtig', answer: 'Vigtig', options: ['Vigtig', 'Ligegyldig', 'Lille'], instruction: 'Adjektive' },
    { id: 'de8-m11', type: 'Match', question: 'Die Luftverschmutzung', answer: 'Luftforurening', options: ['Luftforurening', 'Vandforurening', 'Jordforurening'], instruction: 'Umwelt' },
    { id: 'de8-m12', type: 'Match', question: 'Der Klimawandel', answer: 'Klimaforandring', options: ['Klimaforandring', 'Vejrudsigt', 'Solskin'], instruction: 'Umwelt' },
    { id: 'de8-m13', type: 'Match', question: 'Erneuerbare Energien', answer: 'Vedvarende energi', options: ['Vedvarende energi', 'Atomkraft', 'Kul'], instruction: 'Umwelt' },
    { id: 'de8-m14', type: 'Match', question: 'Die Solarenergie', answer: 'Solenergi', options: ['Solenergi', 'Vindenergi', 'Vandkraft'], instruction: 'Umwelt' },
    { id: 'de8-m15', type: 'Match', question: 'Der Windpark', answer: 'Vindmøllepark', options: ['Vindmøllepark', 'Skov', 'Have'], instruction: 'Umwelt' },
    { id: 'de8-m16', type: 'Match', question: 'Schützen', answer: 'Beskytte', options: ['Beskytte', 'Ødelægge', 'Glemme'], instruction: 'Verben' },
    { id: 'de8-m17', type: 'Match', question: 'Verbrauchen', answer: 'Forbruge', options: ['Forbruge', 'Spare', 'Tjene'], instruction: 'Verben' },
    { id: 'de8-m18', type: 'Match', question: 'Sparen', answer: 'Spare', options: ['Spare', 'Forbruge', 'Miste'], instruction: 'Verben' },
    { id: 'de8-m19', type: 'Match', question: 'Verschwenden', answer: 'Spilde / Ødsle', options: ['Spilde', 'Gemme', 'Bruge'], instruction: 'Verben' },
    { id: 'de8-m20', type: 'Match', question: 'Nachhaltigkeit', answer: 'Bæredygtighed', options: ['Bæredygtighed', 'Forbrug', 'Vækst'], instruction: 'Begriffe' },
    { id: 'de8-m21', type: 'Match', question: 'Die Gesellschaft', answer: 'Samfundet', options: ['Samfundet', 'Familien', 'Individet'], instruction: 'Begriffe' },
    { id: 'de8-m22', type: 'Match', question: 'Die Verantwortung', answer: 'Ansvaret', options: ['Ansvaret', 'Friheden', 'Pligten'], instruction: 'Begriffe' },
    { id: 'de8-m23', type: 'Match', question: 'Die Gleichberechtigung', answer: 'Ligestilling', options: ['Ligestilling', 'Forskel', 'Ulighed'], instruction: 'Begriffe' },
    { id: 'de8-m24', type: 'Match', question: 'Das Gesetz', answer: 'Loven', options: ['Loven', 'Reglen', 'Aftalen'], instruction: 'Begriffe' },
    { id: 'de8-m25', type: 'Match', question: 'Das Recht', answer: 'Retten / Rettigheden', options: ['Retten', 'Pligten', 'Skylden'], instruction: 'Begriffe' },
    { id: 'de8-m26', type: 'Match', question: 'Der Richter', answer: 'Dommeren', options: ['Dommeren', 'Advokaten', 'Vidnet'], instruction: 'Personen' },
    { id: 'de8-m27', type: 'Match', question: 'Der Anwalt', answer: 'Advokaten', options: ['Dommeren', 'Advokaten', 'Vidnet'], instruction: 'Personen' },
    { id: 'de8-m28', type: 'Match', question: 'Das Gericht', answer: 'Domstolen', options: ['Domstolen', 'Politiet', 'Fængslet'], instruction: 'Institutionen' },
    { id: 'de8-m29', type: 'Match', question: 'Die Strafe', answer: 'Straffen', options: ['Straffen', 'Belønningen', 'Gaven'], instruction: 'Begriffe' },
    { id: 'de8-m30', type: 'Match', question: 'Schuldig', answer: 'Skyldig', options: ['Skyldig', 'Uskyldig', 'Fri'], instruction: 'Adjektive' },
    { id: 'de8-m31', type: 'Match', question: 'Unschuldig', answer: 'Uskyldig', options: ['Skyldig', 'Uskyldig', 'Fri'], instruction: 'Adjektive' },
    { id: 'de8-m32', type: 'Match', question: 'Interessant', answer: 'Interessant', options: ['Interessant', 'Kedelig', 'Dårlig'], instruction: 'Adjektive' },
    { id: 'de8-m33', type: 'Match', question: 'Wunderschön', answer: 'Vidunderlig', options: ['Vidunderlig', 'Grim', 'Ond'], instruction: 'Adjektive' },
    { id: 'de8-m34', type: 'Match', question: 'Hässlich', answer: 'Grim', options: ['Smuk', 'Grim', 'Sød'], instruction: 'Adjektive' },
    { id: 'de8-m35', type: 'Match', question: 'Böse', answer: 'Ond / Gal', options: ['Ond', 'God', 'Sød'], instruction: 'Adjektive' },
    { id: 'de8-m36', type: 'Match', question: 'Freundlich', answer: 'Venlig', options: ['Venlig', 'Uvenlig', 'Sur'], instruction: 'Adjektive' },
    { id: 'de8-m37', type: 'Match', question: 'Genau', answer: 'Pris præcis / Netop', options: ['Præcis', 'Omkring', 'Måske'], instruction: 'Adverbien' },
    { id: 'de8-m38', type: 'Match', question: 'Bestimmt', answer: 'Bestemt / Helt sikkert', options: ['Bestemt', 'Måske', 'Aldrig'], instruction: 'Adverbien' },
    { id: 'de8-m39', type: 'Match', question: 'Eigentlich', answer: 'Egentlig', options: ['Egentlig', 'Måske', 'Aldrig'], instruction: 'Adverbien' },
    { id: 'de8-m40', type: 'Match', question: 'Natürlich', answer: 'Naturligvis', options: ['Naturligvis', 'Måske', 'Aldrig'], instruction: 'Adverbien' },
    { id: 'de8-m41', type: 'Match', question: 'Besonders', instruction: 'Især / Særligt', answer: 'Især', options: ['Især', 'Sjældent', 'Aldrig'] },
    { id: 'de8-m42', type: 'Match', question: 'Überhaupt', answer: 'Overhovedet', options: ['Overhovedet', 'Måske', 'Ofte'], instruction: 'Adverbien' },
    { id: 'de8-m43', type: 'Match', question: 'Vielleicht', answer: 'Måske', options: ['Måske', 'Helt sikkert', 'Aldrig'], instruction: 'Adverbien' },
    { id: 'de8-m44', type: 'Match', question: 'Wahrscheinlich', answer: 'Sandsynligvis', options: ['Sandsynligvis', 'Måske', 'Aldrig'], instruction: 'Adverbien' },
    { id: 'de8-m45', type: 'Match', question: 'Sicherlich', answer: 'Sikkert', options: ['Sikkert', 'Måske', 'Aldrig'], instruction: 'Adverbien' },
    { id: 'de8-m46', type: 'Match', question: 'Kaum', answer: 'Næppe / Knap nok', options: ['Næppe', 'Ofte', 'Altid'], instruction: 'Adverbien' },
    { id: 'de8-m47', type: 'Match', question: 'Fast', answer: 'Næsten', options: ['Næsten', 'Helt', 'Aldrig'], instruction: 'Adverbien' },
    { id: 'de8-m48', type: 'Match', question: 'Überall', answer: 'Overalt', options: ['Overalt', 'Ingensteds', 'Her'], instruction: 'Adverbien' },
    { id: 'de8-m49', type: 'Match', question: 'Irgendwo', answer: 'Et eller andet sted', options: ['Et sted', 'Overalt', 'Her'], instruction: 'Adverbien' },
    { id: 'de8-m50', type: 'Match', question: 'Nirgendwo', answer: 'Ingensteds', options: ['Ingensteds', 'Overalt', 'Her'], instruction: 'Adverbien' },
    { id: 'de8-m51', type: 'Match', question: 'Irgendwann', answer: 'På et eller andet tidspunkt', options: ['Når som helst', 'Aldrig', 'Nu'], instruction: 'Adverbien' },
  ],
  9: [
    { id: 'de9-m1', type: 'Match', question: 'DDR', answer: 'Ostdeutschland', options: ['Ostdeutschland', 'Westdeutschland', 'Österreich'], instruction: 'Geschichte' },
    { id: 'de9-m2', type: 'Match', question: 'BRD', answer: 'Westdeutschland', options: ['Ostdeutschland', 'Westdeutschland', 'Schweiz'], instruction: 'Geschichte' },
    { id: 'de9-m3', type: 'Match', question: 'Zukunft', answer: 'Fremtid', options: ['Fremtid', 'Datid', 'Nuet'], instruction: 'Vokabeln' },
    { id: 'de9-m4', type: 'Match', question: 'Beruf', answer: 'Erhverv', options: ['Erhverv', 'Hobby', 'Skole'], instruction: 'Karriere' },
    { id: 'de9-m5', type: 'Match', question: 'Studium', answer: 'Studie', options: ['Studie', 'Arbejde', 'Ferie'], instruction: 'Bildung' },
    { id: 'de9-m6', type: 'Match', question: 'Jugendkultur', answer: 'Ungdomskultur', options: ['Ungdomskultur', 'Erwachsene', 'Kinder'], instruction: 'Kultur' },
    { id: 'de9-m7', type: 'Match', question: 'Politik', answer: 'Staat', options: ['Staat', 'Kirche', 'Wald'], instruction: 'Begriffe' },
    { id: 'de9-m8', type: 'Match', question: 'Demokratie', answer: 'Wahlen', options: ['Wahlen', 'König', 'Krieg'], instruction: 'Politik' },
    { id: 'de9-m9', type: 'Match', question: 'Freiheit', answer: 'Frihed', options: ['Frihed', 'Fængsel', 'Pligt'], instruction: 'Werte' },
    { id: 'de9-m10', type: 'Match', question: 'Erfolg', answer: 'Succes', options: ['Succes', 'Fejl', 'Tab'], instruction: 'Begriffe' },
    { id: 'de9-m11', type: 'Match', question: 'Der Kalte Krieg', answer: 'Den kolde krig', options: ['Den kolde krig', 'Anden verdenskrig', 'Middelalderen'], instruction: 'Geschichte' },
    { id: 'de9-m12', type: 'Match', question: 'Der Eiserne Vorhang', answer: 'Jerntæppet', options: ['Jerntæppet', 'Berlinmuren', 'Grænsen'], instruction: 'Geschichte' },
    { id: 'de9-m13', type: 'Match', question: 'Die Besatzungszonen', answer: 'Besættelseszonerne', options: ['Besættelseszonerne', 'Lande', 'Byer'], instruction: 'Geschichte' },
    { id: 'de9-m14', type: 'Match', question: 'Der Fall der Mauer', answer: 'Murens fald', options: ['Murens fald', 'Murens bygning', 'Krigens afslutning'], instruction: 'Geschichte' },
    { id: 'de9-m15', type: 'Match', question: 'Die Einheit', answer: 'Enheden / Samlingen', options: ['Enheden', 'Delingen', 'Striden'], instruction: 'Geschichte' },
    { id: 'de9-m16', type: 'Match', question: 'Globalisierung', answer: 'Globalisering', options: ['Globalisering', 'Isolering', 'Lokalisering'], instruction: 'Wirtschaft' },
    { id: 'de9-m17', type: 'Match', question: 'Die Arbeitslosigkeit', answer: 'Arbejdsløshed', options: ['Arbejdsløshed', 'Beskæftigelse', 'Uddannelse'], instruction: 'Gesellschaft' },
    { id: 'de9-m18', type: 'Match', question: 'Die Inflation', answer: 'Inflation', options: ['Inflation', 'Prisstigning', 'Vækst'], instruction: 'Wirtschaft' },
    { id: 'de9-m19', type: 'Match', question: 'Der Generationskonflikt', answer: 'Generationskonflikt', options: ['Generationskonflikt', 'Samarbejde', 'Venskab'], instruction: 'Gesellschaft' },
    { id: 'de9-m20', type: 'Match', question: 'Die Integration', answer: 'Integration', options: ['Integration', 'Eksklusion', 'Adskillelse'], instruction: 'Gesellschaft' },
    { id: 'de9-m21', type: 'Match', question: 'Die Identität', answer: 'Identitet', options: ['Identitet', 'Navn', 'Pas'], instruction: 'Gesellschaft' },
    { id: 'de9-m22', type: 'Match', question: 'Das Ehrenamt', answer: 'Frivilligt arbejde', options: ['Frivilligt arbejde', 'Betalt arbejde', 'Hobby'], instruction: 'Gesellschaft' },
    { id: 'de9-m23', type: 'Match', question: 'Die Herausforderung', answer: 'Udfordring', options: ['Udfordring', 'Løsning', 'Problem'], instruction: 'Begriffe' },
    { id: 'de9-m24', type: 'Match', question: 'Die Entscheidung', answer: 'Beslutning', options: ['Beslutning', 'Spørgsmål', 'Tanke'], instruction: 'Begriffe' },
    { id: 'de9-m25', type: 'Match', question: 'Die Verantwortung', answer: 'Ansvar', options: ['Ansvar', 'Frihed', 'Skyld'], instruction: 'Begriffe' },
    { id: 'de9-m26', type: 'Match', question: 'Das Vorurteil', answer: 'Fordom', options: ['Fordom', 'Viden', 'Sandhed'], instruction: 'Begriffe' },
    { id: 'de9-m27', type: 'Match', question: 'Die Tolerance', answer: 'Tolerance', options: ['Tolerance', 'Had', 'Modstand'], instruction: 'Werte' },
    { id: 'de9-m28', type: 'Match', question: 'Die Gerechtigkeit', answer: 'Retfærdighed', options: ['Retfærdighed', 'Uretfærdighed', 'Lov'], instruction: 'Werte' },
    { id: 'de9-m29', type: 'Match', question: 'Der Frieden', answer: 'Fred', options: ['Fred', 'Krig', 'Uro'], instruction: 'Werte' },
    { id: 'de9-m30', type: 'Match', question: 'Die Ausbildung', answer: 'Uddannelse', options: ['Uddannelse', 'Job', 'Fritid'], instruction: 'Zukunft' },
    { id: 'de9-m31', type: 'Match', question: 'Die Karriere', answer: 'Karriere', options: ['Karriere', 'Hobby', 'Hjem'], instruction: 'Zukunft' },
    { id: 'de9-m32', type: 'Match', question: 'Das Gehalt', answer: 'Løn', options: ['Løn', 'Skat', 'Pris'], instruction: 'Zukunft' },
    { id: 'de9-m33', type: 'Match', question: 'Die Überstunden', answer: 'Overtid', options: ['Overtid', 'Ferie', 'Pause'], instruction: 'Zukunft' },
    { id: 'de9-m34', type: 'Match', question: 'Die Bewerbung', answer: 'Ansøgning', options: ['Ansøgning', 'Afslag', 'Jobtilbud'], instruction: 'Zukunft' },
    { id: 'de9-m35', type: 'Match', question: 'Das Vorstellungsgespräch', answer: 'Jobsamtale', options: ['Jobsamtale', 'Eksamen', 'Møde'], instruction: 'Zukunft' },
    { id: 'de9-m36', type: 'Match', question: 'Die Erfahrung', answer: 'Erfaring', options: ['Erfaring', 'Viden', 'Drøm'], instruction: 'Begriffe' },
    { id: 'de9-m37', type: 'Match', question: 'Die Komplexität', answer: 'Kompleksitet', options: ['Kompleksitet', 'Enkelhed', 'Klarhed'], instruction: 'Begriffe' },
    { id: 'de9-m38', type: 'Match', question: 'Die Strategie', answer: 'Strategi', options: ['Strategi', 'Tilfælde', 'Held'], instruction: 'Begriffe' },
    { id: 'de9-m39', type: 'Match', question: 'Die Analyse', answer: 'Analyse', options: ['Analyse', 'Resultat', 'Start'], instruction: 'Begriffe' },
    { id: 'de9-m40', type: 'Match', question: 'Die Konsequenz', answer: 'Konsekvens', options: ['Konsekvens', 'Årsag', 'Begyndelse'], instruction: 'Begriffe' },
    { id: 'de9-m41', type: 'Match', question: 'Grammatik: Indikativ', answer: 'Fremsættende måde', options: ['Fremsættende måde', 'Bydemåde', 'Ønskemåde'], instruction: 'Modus' },
    { id: 'de9-m42', type: 'Match', question: 'Grammatik: Konjunktiv', answer: 'Ønskemåde / Hypotetisk', options: ['Ønskemåde', 'Bydemåde', 'Nutid'], instruction: 'Modus' },
    { id: 'de9-m43', type: 'Match', question: 'Grammatik: Passiv', answer: 'Bliver gjort', options: ['Aktiv', 'Passiv', 'Fremtid'], instruction: 'Diatese' },
    { id: 'de9-m44', type: 'Match', question: 'Grammatik: Genitiv', answer: 'Ejefald', options: ['Nominativ', 'Akkusativ', 'Dativ', 'Genitiv'], instruction: 'Kasus' },
    { id: 'de9-m45', type: 'Match', question: 'Grammatik: Dativ', answer: 'Hensynsfald', options: ['Nominativ', 'Akkusativ', 'Dativ', 'Genitiv'], instruction: 'Kasus' },
    { id: 'de9-m46', type: 'Match', question: 'Grammatik: Akkusativ', answer: 'Genstandsfald', options: ['Nominativ', 'Akkusativ', 'Dativ', 'Genitiv'], instruction: 'Kasus' },
    { id: 'de9-m47', type: 'Match', question: 'Grammatik: Nominativ', answer: 'Grundfald', options: ['Nominativ', 'Akkusativ', 'Dativ', 'Genitiv'], instruction: 'Kasus' },
    { id: 'de9-m48', type: 'Match', question: 'Grammatik: Pluskvamperfektum', answer: 'Førdatid', options: ['Førdatid', 'Førnutid', 'Fremtid'], instruction: 'Tempus' },
    { id: 'de9-m49', type: 'Match', question: 'Grammatik: Futurum I', answer: 'Fremtid', options: ['Fremtid', 'Datid', 'Nutid'], instruction: 'Tempus' },
    { id: 'de9-m50', type: 'Match', question: 'Grammatik: Perfekt', answer: 'Førnutid', options: ['Førnutid', 'Datid', 'Nutid'], instruction: 'Tempus' },
    { id: 'de9-m51', type: 'Match', question: 'Grammatik: Präteritum', answer: 'Datid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Tempus' },
  ],
  10: [
    { id: 'de10-m1', type: 'Match', question: 'Globalisierung', answer: 'Globalisering', options: ['Globalisering', 'Isolering', 'Lokalisering'], instruction: 'Wirtschaft' },
    { id: 'de10-m2', type: 'Match', question: 'Klimawandel', answer: 'Klimaforandring', options: ['Klimaforandring', 'Vejr', 'Natur'], instruction: 'Umwelt' },
    { id: 'de10-m3', type: 'Match', question: 'Nachhaltigkeit', answer: 'Bæredygtighed', options: ['Bæredygtighed', 'Forbrug', 'Vækst'], instruction: 'Umwelt' },
    { id: 'de10-m4', type: 'Match', question: 'Demokratie', answer: 'Demokrati', options: ['Demokrati', 'Diktatur', 'Monarki'], instruction: 'Politik' },
    { id: 'de10-m5', type: 'Match', question: 'Gerechtigkeit', answer: 'Retfærdighed', options: ['Retfærdighed', 'Uretfærdighed', 'Lov'], instruction: 'Werte' },
    { id: 'de10-m6', type: 'Match', question: 'Herausforderung', answer: 'Udfordring', options: ['Udfordring', 'Løsning', 'Problem'], instruction: 'Vokabeln' },
    { id: 'de10-m7', type: 'Match', question: 'Verantwortung', answer: 'Ansvar', options: ['Ansvar', 'Frihed', 'Pligt'], instruction: 'Werte' },
    { id: 'de10-m8', type: 'Match', question: 'Entwicklung', answer: 'Udvikling', options: ['Udvikling', 'Stilstand', 'Start'], instruction: 'Vokabeln' },
    { id: 'de10-m9', type: 'Match', question: 'Wirtschaft', answer: 'Økonomi', options: ['Økonomi', 'Politik', 'Kultur'], instruction: 'Gesellschaft' },
    { id: 'de10-m10', type: 'Match', question: 'Gesellschaft', answer: 'Samfund', options: ['Samfund', 'Individ', 'Stat'], instruction: 'Gesellschaft' },
    { id: 'de10-m11', type: 'Match', question: 'Erfolg', answer: 'Succes', options: ['Succes', 'Fiasko', 'Tab'], instruction: 'Vokabeln' },
    { id: 'de10-m12', type: 'Match', question: 'Ziel', answer: 'Mål', options: ['Mål', 'Vej', 'Start'], instruction: 'Vokabeln' },
    { id: 'de10-m13', type: 'Match', question: 'Möglichkeit', answer: 'Mulighed', options: ['Mulighed', 'Forbud', 'Grænse'], instruction: 'Vokabeln' },
    { id: 'de10-m14', type: 'Match', question: 'Unterschied', answer: 'Forskel', options: ['Forskel', 'Lighed', 'Samme'], instruction: 'Vokabeln' },
    { id: 'de10-m15', type: 'Match', question: 'Zukunft', answer: 'Fremtid', options: ['Fremtid', 'Datid', 'Nutid'], instruction: 'Zeit' },
    { id: 'de10-m16', type: 'Match', question: 'Gegenwart', answer: 'Nutid', options: ['Nutid', 'Fremtid', 'Datid'], instruction: 'Zeit' },
    { id: 'de10-m17', type: 'Match', question: 'Vergangenheit', answer: 'Datid', options: ['Datid', 'Nutid', 'Fremtid'], instruction: 'Zeit' },
    { id: 'de10-m18', type: 'Match', question: 'Wissenschaft', answer: 'Videnskab', options: ['Videnskab', 'Kunst', 'Religion'], instruction: 'Bildung' },
    { id: 'de10-m19', type: 'Match', question: 'Bildung', answer: 'Uddannelse', options: ['Uddannelse', 'Job', 'Fritid'], instruction: 'Bildung' },
    { id: 'de10-m20', type: 'Match', question: 'Erfahrung', answer: 'Erfaring', options: ['Erfaring', 'Viden', 'Drøm'], instruction: 'Vokabeln' },
    { id: 'de10-m21', type: 'Match', question: 'Bedeutung', answer: 'Betydning', options: ['Betydning', 'Navn', 'Lyd'], instruction: 'Linguistik' },
    { id: 'de10-m22', type: 'Match', question: 'Zusammenhang', answer: 'Sammenhæng', options: ['Sammenhæng', 'Kaos', 'Brud'], instruction: 'Logik' },
    { id: 'de10-m23', type: 'Match', question: 'Einfluss', answer: 'Indflydelse', options: ['Indflydelse', 'Magt', 'Svaghed'], instruction: 'Soziologie' },
    { id: 'de10-m24', type: 'Match', question: 'Verbindung', answer: 'Forbindelse', options: ['Forbindelse', 'Adskillelse', 'Stop'], instruction: 'Vokabeln' },
    { id: 'de10-m25', type: 'Match', question: 'Entscheidung', answer: 'Beslutning', options: ['Beslutning', 'Spørgsmål', 'Tanke'], instruction: 'Vokabeln' },
    { id: 'de10-m26', type: 'Match', question: 'Gleichberechtigung', answer: 'Ligestilling', options: ['Ligestilling', 'Ulighed', 'Forskel'], instruction: 'Werte' },
    { id: 'de10-m27', type: 'Match', question: 'Freiheit', answer: 'Frihed', options: ['Frihed', 'Fængsel', 'Tvang'], instruction: 'Werte' },
    { id: 'de10-m28', type: 'Match', question: 'Frieden', answer: 'Fred', options: ['Fred', 'Krig', 'Uro'], instruction: 'Werte' },
    { id: 'de10-m29', type: 'Match', question: 'Sicherheit', answer: 'Sikkerhed', options: ['Sikkerhed', 'Fare', 'Frygt'], instruction: 'Werte' },
    { id: 'de10-m30', type: 'Match', question: 'Vertrauen', answer: 'Tillid', options: ['Tillid', 'Tvivl', 'Had'], instruction: 'Werte' },
    { id: 'de10-m31', type: 'Match', question: 'Grammatik: Passiv', answer: 'Passiv', options: ['Passiv', 'Aktiv', 'Modus'], instruction: 'Grammatik' },
    { id: 'de10-m32', type: 'Match', question: 'Grammatik: Konjunktiv', answer: 'Konjunktiv', options: ['Konjunktiv', 'Indikativ', 'Imperativ'], instruction: 'Grammatik' },
    { id: 'de10-m33', type: 'Match', question: 'Grammatik: Genitiv', answer: 'Ejefald', options: ['Nominativ', 'Akkusativ', 'Dativ', 'Genitiv'], instruction: 'Kasus' },
    { id: 'de10-m34', type: 'Match', question: 'Grammatik: Dativ', answer: 'Hensynsfald', options: ['Nominativ', 'Akkusativ', 'Dativ', 'Genitiv'], instruction: 'Kasus' },
    { id: 'de10-m35', type: 'Match', question: 'Grammatik: Akkusativ', answer: 'Genstandsfald', options: ['Nominativ', 'Akkusativ', 'Dativ', 'Genitiv'], instruction: 'Kasus' },
    { id: 'de10-m36', type: 'Match', question: 'Grammatik: Nominativ', answer: 'Grundfald', options: ['Nominativ', 'Akkusativ', 'Dativ', 'Genitiv'], instruction: 'Kasus' },
    { id: 'de10-m37', type: 'Match', question: 'Vergangenheit: War', answer: 'Var', options: ['Var', 'Er', 'Bliver'], instruction: 'Sein (Past)' },
    { id: 'de10-m38', type: 'Match', question: 'Vergangenheit: Hatte', answer: 'Havde', options: ['Havde', 'Har', 'Får'], instruction: 'Haben (Past)' },
    { id: 'de10-m39', type: 'Match', question: 'Bedingung', answer: 'Betingelse', options: ['Betingelse', 'Resultat', 'Start'], instruction: 'Logik' },
    { id: 'de10-m40', type: 'Match', question: 'Folge', answer: 'Følge/Resultat', options: ['Følge', 'Årsag', 'Start'], instruction: 'Logik' },
    { id: 'de10-m41', type: 'Match', question: 'Ursache', answer: 'Årsag', options: ['Årsag', 'Virkning', 'Resultat'], instruction: 'Logik' },
    { id: 'de10-m42', type: 'Match', question: 'Wirkung', answer: 'Virkning', options: ['Virkning', 'Årsag', 'Start'], instruction: 'Logik' },
    { id: 'de10-m43', type: 'Match', question: 'Vorteil', answer: 'Fordel', options: ['Fordel', 'Ulempe', 'Lighed'], instruction: 'Logik' },
    { id: 'de10-m44', type: 'Match', question: 'Nachteil', answer: 'Ulempe', options: ['Ulempe', 'Fordel', 'Lighed'], instruction: 'Logik' },
    { id: 'de10-m45', type: 'Match', question: 'Meinung', answer: 'Holdning/Mening', options: ['Mening', 'Fakta', 'Tal'], instruction: 'Diskussion' },
    { id: 'de10-m46', type: 'Match', question: 'Argument', answer: 'Argument', options: ['Argument', 'Påstand', 'Modbevis'], instruction: 'Diskussion' },
    { id: 'de10-m47', type: 'Match', question: 'Behauptung', answer: 'Påstand', options: ['Påstand', 'Bevis', 'Tvivl'], instruction: 'Diskussion' },
    { id: 'de10-m48', type: 'Match', question: 'Beweis', answer: 'Bevis', options: ['Bevis', 'Gæt', 'Tanke'], instruction: 'Diskussion' },
    { id: 'de10-m49', type: 'Match', question: 'Tatsache', answer: 'Faktum', options: ['Faktum', 'Løgn', 'Ønske'], instruction: 'Diskussion' },
    { id: 'de10-m50', type: 'Match', question: 'Zusammenfassung', answer: 'Resumé', options: ['Resumé', 'Start', 'Indledning'], instruction: 'Analyse' },
    { id: 'de10-m51', type: 'Match', question: 'Identität', answer: 'Identitet', options: ['Identitet', 'Navn', 'Pas'], instruction: 'Soziologie' },
    { id: 'de10-m52', type: 'Match', question: 'Kultur', answer: 'Kultur', options: ['Kultur', 'Kunst', 'Natur'], instruction: 'Soziologie' },
    { id: 'de10-m53', type: 'Match', question: 'Tradition', answer: 'Tradition', options: ['Tradition', 'Nyhed', 'Vane'], instruction: 'Soziologie' },
    { id: 'de10-m54', type: 'Match', question: 'Fortschritt', answer: 'Fremskridt', options: ['Fremskridt', 'Stilstand', 'Tilbagegang'], instruction: 'Technik' },
    { id: 'de10-m55', type: 'Match', question: 'Technik', answer: 'Teknik', options: ['Teknik', 'Metode', 'Måde'], instruction: 'Technik' },
    { id: 'de10-m56', type: 'Match', question: 'Forschung', answer: 'Forskning', options: ['Forskning', 'Undersøgelse', 'Lære'], instruction: 'Wissenschaft' },
    { id: 'de10-m57', type: 'Match', question: 'Theorien', answer: 'Teorier', options: ['Teorier', 'Fakta', 'Gæt'], instruction: 'Wissenschaft' },
    { id: 'de10-m58', type: 'Match', question: 'Hypothese', answer: 'Hypotese', options: ['Hypotese', 'Teori', 'Gæt'], instruction: 'Wissenschaft' },
    { id: 'de10-m59', type: 'Match', question: 'Resultat', answer: 'Resultat', options: ['Resultat', 'Start', 'Proces'], instruction: 'Wissenschaft' },
    { id: 'de10-m60', type: 'Match', question: 'Analyse', answer: 'Analyse', options: ['Analyse', 'Resumé', 'Start'], instruction: 'Methodik' },
    { id: 'de10-m61', type: 'Match', question: 'Interpretation', answer: 'Fortolkning', options: ['Fortolkning', 'Læsning', 'Skrivning'], instruction: 'Methodik' },
    { id: 'de10-m62', type: 'Match', question: 'Perspektive', answer: 'Perspektiv', options: ['Perspektiv', 'Synsvinkel', 'Udsigt'], instruction: 'Methodik' },
    { id: 'de10-m63', type: 'Match', question: 'Struktur', answer: 'Struktur', options: ['Struktur', 'Kaos', 'Orden'], instruction: 'Methodik' },
    { id: 'de10-m64', type: 'Match', question: 'Systematisch', answer: 'Systematisk', options: ['Systematisk', 'Tilfældig', 'Kaotisk'], instruction: 'Methodik' },
    { id: 'de10-m65', type: 'Match', question: 'Effektivitet', answer: 'Effizienz', options: ['Effizienz', 'Befolkning', 'Vækst'], instruction: 'Wirtschaft' },
    { id: 'de10-m66', type: 'Match', question: 'Konkurrenz', answer: 'Konkurrence', options: ['Konkurrence', 'Samarbejde', 'Enighed'], instruction: 'Wirtschaft' },
    { id: 'de10-m67', type: 'Match', question: 'Kapital', answer: 'Kapital', options: ['Kapital', 'Penge', 'Løn'], instruction: 'Wirtschaft' },
    { id: 'de10-m68', type: 'Match', question: 'Investition', answer: 'Investering', options: ['Investering', 'Forbrug', 'Tab'], instruction: 'Wirtschaft' },
    { id: 'de10-m69', type: 'Match', question: 'Ressourcen', answer: 'Ressourcer', options: ['Ressourcer', 'Materialer', 'Ting'], instruction: 'Wirtschaft' },
    { id: 'de10-m70', type: 'Match', question: 'Biodiversität', answer: 'Biodiversitet', options: ['Biodiversitet', 'Natur', 'Miljø'], instruction: 'Umwelt' },
    { id: 'de10-m71', type: 'Match', question: 'Ökosystem', answer: 'Økosystem', options: ['Økosystem', 'Miljø', 'Natur'], instruction: 'Umwelt' },
    { id: 'de10-m72', type: 'Match', question: 'Kohlendioxid', answer: 'Kuldioxid (CO2)', options: ['Kuldioxid', 'Ilt', 'Vand'], instruction: 'Umwelt' },
    { id: 'de10-m73', type: 'Match', question: 'Emissionen', answer: 'Emissioner', options: ['Emissioner', 'Forurening', 'Luft'], instruction: 'Umwelt' },
    { id: 'de10-m74', type: 'Match', question: 'Atmosphäre', answer: 'Atmosfære', options: ['Atmosfære', 'Luft', 'Himmel'], instruction: 'Umwelt' },
    { id: 'de10-m75', type: 'Match', question: 'Gerechtigkeit', answer: 'Retfærdighed', options: ['Retfærdighed', 'Uretfærdighed', 'Lov'], instruction: 'Werte' },
    { id: 'de10-m76', type: 'Match', question: 'Gleichheit', answer: 'Lighed', options: ['Lighed', 'Ulighed', 'Forskel'], instruction: 'Werte' },
    { id: 'de10-m77', type: 'Match', question: 'Solidarität', answer: 'Solidaritet', options: ['Solidaritet', 'Ensomhed', 'Støtte'], instruction: 'Werte' },
    { id: 'de10-m78', type: 'Match', question: 'Toleranz', answer: 'Tolerance', options: ['Tolerance', 'Had', 'Accept'], instruction: 'Werte' },
    { id: 'de10-m79', type: 'Match', question: 'Respekt', answer: 'Respekt', options: ['Respekt', 'Had', 'Foragt'], instruction: 'Werte' },
    { id: 'de10-m80', type: 'Match', question: 'Ehre', answer: 'Ære', options: ['Ære', 'Skam', 'Stolthed'], instruction: 'Werte' },
    { id: 'de10-m81', type: 'Match', question: 'Moral', answer: 'Moral', options: ['Moral', 'Etik', 'Regler'], instruction: 'Werte' },
    { id: 'de10-m82', type: 'Match', question: 'Ethik', answer: 'Etik', options: ['Etik', 'Moral', 'Lov'], instruction: 'Werte' },
    { id: 'de10-m83', type: 'Match', question: 'Philosophie', answer: 'Filosofi', options: ['Filosofi', 'Videnskab', 'Tro'], instruction: 'Geisteswissenschaft' },
    { id: 'de10-m84', type: 'Match', question: 'Literatur', answer: 'Litteratur', options: ['Litteratur', 'Bøger', 'Kunst'], instruction: 'Geisteswissenschaft' },
    { id: 'de10-m85', type: 'Match', question: 'Lyrik', answer: 'Lyrik', options: ['Lyrik', 'Prosa', 'Drama'], instruction: 'Literatur' },
    { id: 'de10-m86', type: 'Match', question: 'Prosa', answer: 'Prosa', options: ['Prosa', 'Lyrik', 'Drama'], instruction: 'Literatur' },
    { id: 'de10-m87', type: 'Match', question: 'Drama', answer: 'Drama', options: ['Drama', 'Lyrik', 'Prosa'], instruction: 'Literatur' },
    { id: 'de10-m88', type: 'Match', question: 'Metapher', answer: 'Metafor', options: ['Metafor', 'Sammenligning', 'Symbol'], instruction: 'Literatur' },
    { id: 'de10-m89', type: 'Match', question: 'Symbol', answer: 'Symbol', options: ['Symbol', 'Metafor', 'Billede'], instruction: 'Literatur' },
    { id: 'de10-m90', type: 'Match', question: 'Hauptperson', answer: 'Hovedperson', options: ['Hovedperson', 'Biperson', 'Skurk'], instruction: 'Literatur' },
    { id: 'de10-m91', type: 'Match', question: 'Antagonist', answer: 'Modstander', options: ['Modstander', 'Ven', 'Hovdeperon'], instruction: 'Literatur' },
    { id: 'de10-m92', type: 'Match', question: 'Konflikt', answer: 'Konflikt', options: ['Konflikt', 'Løsning', 'Enighed'], instruction: 'Literatur' },
    { id: 'de10-m93', type: 'Match', question: 'Spannung', answer: 'Spænding', options: ['Spænding', 'Kedelig', 'Ro'], instruction: 'Literatur' },
    { id: 'de10-m94', type: 'Match', question: 'Epoche', answer: 'Epoke', options: ['Epoke', 'Tid', 'Dag'], instruction: 'Geschichte' },
    { id: 'de10-m95', type: 'Match', question: 'Historish', answer: 'Historisk', options: ['Historisk', 'Nutidig', 'Fremtidig'], instruction: 'Geschichte' },
    { id: 'de10-m96', type: 'Match', question: 'Politisch', answer: 'Politisk', options: ['Politisk', 'Økonomisk', 'Social'], instruction: 'Politik' },
    { id: 'de10-m97', type: 'Match', question: 'Sozial', answer: 'Social', options: ['Social', 'Politisk', 'Økonomisk'], instruction: 'Gesellschaft' },
    { id: 'de10-m98', type: 'Match', question: 'Kulturell', answer: 'Kulturel', options: ['Kulturel', 'Naturlig', 'Teknisk'], instruction: 'Kultur' },
    { id: 'de10-m99', type: 'Match', question: 'International', answer: 'International', options: ['International', 'National', 'Lokal'], instruction: 'Gesellschaft' },
    { id: 'de10-m100', type: 'Match', question: 'National', answer: 'National', options: ['National', 'International', 'Lokal'], instruction: 'Gesellschaft' },
  ]
};
