/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const DANSK_AUDIO: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'da0-a1', type: 'Audio', question: 'Is', answer: '🍦', options: ['🍦', '🍭', '🍕', '🍔'], instruction: 'Find tingen' },
    { id: 'da0-a2', type: 'Audio', question: 'Sol', answer: '☀️', options: ['☀️', '🌧️', '❄️'], instruction: 'Find vejret' },
    { id: 'da0-a3', type: 'Audio', question: 'Bil', answer: '🚗', options: ['🚗', '🚲', '✈️', '🚢'], instruction: 'Find køretøjet' },
    { id: 'da0-a4', type: 'Audio', question: 'Kat', answer: '🐱', options: ['🐱', '🐶', '🐭', '🐰'], instruction: 'Find dyret' },
    { id: 'da0-a5', type: 'Audio', question: 'Æble', answer: '🍎', options: ['🍎', '🍐', '🍌', '🍓'], instruction: 'Find frugten' },
    { id: 'da0-a6', type: 'Audio', question: 'Hus', answer: '🏠', options: ['🏠', '🌳', '🏩', '🏫'], instruction: 'Find bygningen' },
    { id: 'da0-a7', type: 'Audio', question: 'Bog', answer: '📖', options: ['📖', '✏️', '💻', '📺'], instruction: 'Find tingen' },
    { id: 'da0-a8', type: 'Audio', question: 'Mor', answer: '👩', options: ['👩', '👨', '👧', '👦'], instruction: 'Hvem er det?' },
    { id: 'da0-a9', type: 'Audio', question: 'Far', answer: '👨', options: ['👩', '👨', '👧', '👦'], instruction: 'Hvem er det?' },
    { id: 'da0-a10', type: 'Audio', question: 'Bord', answer: '🪑', options: ['🪑', '🛋️', '🛏️', '🚪'], instruction: 'Find møblet' },
    { id: 'da0-a11', type: 'Audio', question: 'Blå', answer: '🔵', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Find farven' },
    { id: 'da0-a12', type: 'Audio', question: 'Rød', answer: '🔴', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Find farven' },
    { id: 'da0-a13', type: 'Audio', question: 'Grøn', answer: '🟢', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Find farven' },
    { id: 'da0-a14', type: 'Audio', question: 'Gul', answer: '🟡', options: ['🔴', '🔵', '🟢', '🟡'], instruction: 'Find farven' },
    { id: 'da0-a15', type: 'Audio', question: 'Hest', answer: '🐎', options: ['🐎', '🐄', '🐖', '🐑'], instruction: 'Find dyret' },
    { id: 'da0-a16', type: 'Audio', question: 'Ko', answer: '🐄', options: ['🐎', '🐄', '🐖', '🐑'], instruction: 'Find dyret' },
    { id: 'da0-a17', type: 'Audio', question: 'Gris', answer: '🐖', options: ['🐎', '🐄', '🐖', '🐑'], instruction: 'Find dyret' },
    { id: 'da0-a18', type: 'Audio', question: 'Får', answer: '🐑', options: ['🐎', '🐄', '🐖', '🐑'], instruction: 'Find dyret' },
    { id: 'da0-a19', type: 'Audio', question: 'Banan', answer: '🍌', options: ['🍎', '🍐', '🍌', '🍓'], instruction: 'Find frugten' },
    { id: 'da0-a20', type: 'Audio', question: 'Pære', answer: '🍐', options: ['🍎', '🍐', '🍌', '🍓'], instruction: 'Find frugten' },
    { id: 'da0-a21', type: 'Audio', question: 'Jordbær', answer: '🍓', options: ['🍎', '🍐', '🍌', '🍓'], instruction: 'Find frugten' },
    { id: 'da0-a22', type: 'Audio', question: 'Cykel', answer: '🚲', options: ['🚗', '🚲', '✈️', '🚢'], instruction: 'Find køretøjet' },
    { id: 'da0-a23', type: 'Audio', question: 'Fly', answer: '✈️', options: ['🚗', '🚲', '✈️', '🚢'], instruction: 'Find køretøjet' },
    { id: 'da0-a24', type: 'Audio', question: 'Skib', answer: '🚢', options: ['🚗', '🚲', '✈️', '🚢'], instruction: 'Find køretøjet' },
    { id: 'da0-a25', type: 'Audio', question: 'Seng', answer: '🛏️', options: ['🪑', '🛋️', '🛏️', '🚪'], instruction: 'Find møblet' },
    { id: 'da0-a26', type: 'Audio', question: 'Dør', answer: '🚪', options: ['🪑', '🛋️', '🛏️', '🚪'], instruction: 'Find møblet' },
    { id: 'da0-a27', type: 'Audio', question: 'Vindue', answer: '🪟', options: ['🪟', '🏠', '🧱', '🪵'], instruction: 'Find tingen' },
    { id: 'da0-a28', type: 'Audio', question: 'Træ', answer: '🌳', options: ['🌳', '🌸', '🌵', '🍄'], instruction: 'Find planten' },
    { id: 'da0-a29', type: 'Audio', question: 'Blomst', answer: '🌸', options: ['🌳', '🌸', '🌵', '🍄'], instruction: 'Find planten' },
    { id: 'da0-a30', type: 'Audio', question: 'Bold', answer: '⚽', options: ['⚽', '🏀', '🏈', '🎾'], instruction: 'Find legetøjet' },
    { id: 'da0-a31', type: 'Audio', question: 'Dukke', answer: '🪆', options: ['🪆', '🧸', '🚂', '🧩'], instruction: 'Find legetøjet' },
    { id: 'da0-a32', type: 'Audio', question: 'Bamse', answer: '🧸', options: ['🪆', '🧸', '🚂', '🧩'], instruction: 'Find legetøjet' },
    { id: 'da0-a33', type: 'Audio', question: 'Tog', answer: '🚂', options: ['🪆', '🧸', '🚂', '🧩'], instruction: 'Find legetøjet' },
    { id: 'da0-a34', type: 'Audio', question: 'Sko', answer: '👟', options: ['👟', '🧦', '🧣', '🧤'], instruction: 'Find tøjet' },
    { id: 'da0-a35', type: 'Audio', question: 'Strømpe', answer: '🧦', options: ['👟', '🧦', '🧣', '🧤'], instruction: 'Find tøjet' },
    { id: 'da0-a36', type: 'Audio', question: 'Hue', answer: '🧢', options: ['🧢', '🧣', '🧤', '🧥'], instruction: 'Find tøjet' },
    { id: 'da0-a37', type: 'Audio', question: 'Jakke', answer: '🧥', options: ['🧢', '🧣', '🧤', '🧥'], instruction: 'Find tøjet' },
    { id: 'da0-a38', type: 'Audio', question: 'Brød', answer: '🍞', options: ['🍞', '🥛', '🍎', '🥩'], instruction: 'Find maden' },
    { id: 'da0-a39', type: 'Audio', question: 'Mælk', answer: '🥛', options: ['🍞', '🥛', '🍎', '🥩'], instruction: 'Find drikken' },
    { id: 'da0-a40', type: 'Audio', question: 'Vand', answer: '💧', options: ['💧', '🥛', '☕', '🥤'], instruction: 'Find drikken' },
    { id: 'da0-a41', type: 'Audio', question: 'Øje', answer: '👁️', options: ['👁️', '👂', '👃', '👄'], instruction: 'Find kropsdelen' },
    { id: 'da0-a42', type: 'Audio', question: 'Øre', answer: '👂', options: ['👁️', '👂', '👃', '👄'], instruction: 'Find kropsdelen' },
    { id: 'da0-a43', type: 'Audio', question: 'Næse', answer: '👃', options: ['👁️', '👂', '👃', '👄'], instruction: 'Find kropsdelen' },
    { id: 'da0-a44', type: 'Audio', question: 'Mund', answer: '👄', options: ['👁️', '👂', '👃', '👄'], instruction: 'Find kropsdelen' },
    { id: 'da0-a45', type: 'Audio', question: 'Hånd', answer: '✋', options: ['✋', '🦶', '💪', '🦵'], instruction: 'Find kropsdelen' },
    { id: 'da0-a46', type: 'Audio', question: 'Fod', answer: '🦶', options: ['✋', '🦶', '💪', '🦵'], instruction: 'Find kropsdelen' },
    { id: 'da0-a47', type: 'Audio', question: 'Skovl', answer: '🧹', options: ['🧹', '🪣', '🪚', '🔨'], instruction: 'Find tingen' },
    { id: 'da0-a48', type: 'Audio', question: 'Spand', answer: '🪣', options: ['🧹', '🪣', '🪚', '🔨'], instruction: 'Find tingen' },
    { id: 'da0-a49', type: 'Audio', question: 'Sav', answer: '🪚', options: ['🧹', '🪣', '🪚', '🔨'], instruction: 'Find værktøjet' },
    { id: 'da0-a50', type: 'Audio', question: 'Hammer', answer: '🔨', options: ['🧹', '🪣', '🪚', '🔨'], instruction: 'Find værktøjet' },
    { id: 'da0-a51', type: 'Audio', question: 'Saks', answer: '✂️', options: ['✂️', '📏', '📎', '✏️'], instruction: 'Find tingen' },
  ],
  1: [
    { id: 'da1-a1', type: 'Audio', question: 'Løbe', answer: '🏃', options: ['🏃', '🚶', '🛌', '🧘'], instruction: 'Find handlingen' },
    { id: 'da1-a2', type: 'Audio', question: 'Gå', answer: '🚶', options: ['🏃', '🚶', '🛌', '🧘'], instruction: 'Find handlingen' },
    { id: 'da1-a3', type: 'Audio', question: 'Sove', answer: '🛌', options: ['🏃', '🚶', '🛌', '🧘'], instruction: 'Find handlingen' },
    { id: 'da1-a4', type: 'Audio', question: 'Spise', answer: '😋', options: ['😋', '😴', '😠', '😢'], instruction: 'Find følelsen/handlingen' },
    { id: 'da1-a5', type: 'Audio', question: 'Glad', answer: '😊', options: ['😊', '😢', '😠', '😱'], instruction: 'Find følelsen' },
    { id: 'da1-a6', type: 'Audio', question: 'Ked af det', answer: '😢', options: ['😊', '😢', '😠', '😱'], instruction: 'Find følelsen' },
    { id: 'da1-a7', type: 'Audio', question: 'Sur', answer: '😠', options: ['😊', '😢', '😠', '😱'], instruction: 'Find følelsen' },
    { id: 'da1-a8', type: 'Audio', question: 'Bange', answer: '😱', options: ['😊', '😢', '😠', '😱'], instruction: 'Find følelsen' },
    { id: 'da1-a9', type: 'Audio', question: 'Regn', answer: '🌧️', options: ['☀️', '🌧️', '❄️', '🌩️'], instruction: 'Find vejret' },
    { id: 'da1-a10', type: 'Audio', question: 'Sne', answer: '❄️', options: ['☀️', '🌧️', '❄️', '🌩️'], instruction: 'Find vejret' },
    { id: 'da1-a11', type: 'Audio', question: 'Torden', answer: '🌩️', options: ['☀️', '🌧️', '❄️', '🌩️'], instruction: 'Find vejret' },
    { id: 'da1-a12', type: 'Audio', question: 'Blæst', answer: '🌬️', options: ['🌬️', '🌈', '🌫️', '☀️'], instruction: 'Find vejret' },
    { id: 'da1-a13', type: 'Audio', question: 'Stor', answer: '🐘', options: ['🐘', '🐭', '🐜', '🦋'], instruction: 'Hvem er størst?' },
    { id: 'da1-a14', type: 'Audio', question: 'Lille', answer: '🐭', options: ['🐘', '🐭', '🐜', '🦋'], instruction: 'Hvem er mindst?' },
    { id: 'da1-a15', type: 'Audio', question: 'Hurtig', answer: '🐆', options: ['🐆', '🐢', '🐌', '🦞'], instruction: 'Hvem er hurtigst?' },
    { id: 'da1-a16', type: 'Audio', question: 'Langsom', answer: '🐢', options: ['🐆', '🐢', '🐌', '🦞'], instruction: 'Hvem er langsomst?' },
    { id: 'da1-a17', type: 'Audio', question: 'Op', answer: '⬆️', options: ['⬆️', '⬇️', '⬅️', '➡️'], instruction: 'Hvilken vej er op?' },
    { id: 'da1-a18', type: 'Audio', question: 'Ned', answer: '⬇️', options: ['⬆️', '⬇️', '⬅️', '➡️'], instruction: 'Hvilken vej er ned?' },
    { id: 'da1-a19', type: 'Audio', question: 'Venstre', answer: '⬅️', options: ['⬆️', '⬇️', '⬅️', '➡️'], instruction: 'Hvilken vej er venstre?' },
    { id: 'da1-a20', type: 'Audio', question: 'Højre', answer: '➡️', options: ['⬆️', '⬇️', '⬅️', '➡️'], instruction: 'Hvilken vej er højre?' },
    { id: 'da1-a21', type: 'Audio', question: 'En', answer: '1️⃣', options: ['1️⃣', '2️⃣', '3️⃣', '4️⃣'], instruction: 'Find tallet' },
    { id: 'da1-a22', type: 'Audio', question: 'To', answer: '2️⃣', options: ['1️⃣', '2️⃣', '3️⃣', '4️⃣'], instruction: 'Find tallet' },
    { id: 'da1-a23', type: 'Audio', question: 'Tre', answer: '3️⃣', options: ['1️⃣', '2️⃣', '3️⃣', '4️⃣'], instruction: 'Find tallet' },
    { id: 'da1-a24', type: 'Audio', question: 'Fire', answer: '4️⃣', options: ['1️⃣', '2️⃣', '3️⃣', '4️⃣'], instruction: 'Find tallet' },
    { id: 'da1-a25', type: 'Audio', question: 'Fem', answer: '5️⃣', options: ['5️⃣', '6️⃣', '7️⃣', '8️⃣'], instruction: 'Find tallet' },
    { id: 'da1-a26', type: 'Audio', question: 'Seks', answer: '6️⃣', options: ['5️⃣', '6️⃣', '7️⃣', '8️⃣'], instruction: 'Find tallet' },
    { id: 'da1-a27', type: 'Audio', question: 'Syv', answer: '7️⃣', options: ['5️⃣', '6️⃣', '7️⃣', '8️⃣'], instruction: 'Find tallet' },
    { id: 'da1-a28', type: 'Audio', question: 'Otte', answer: '8️⃣', options: ['5️⃣', '6️⃣', '7️⃣', '8️⃣'], instruction: 'Find tallet' },
    { id: 'da1-a29', type: 'Audio', question: 'Ni', answer: '9️⃣', options: ['9️⃣', '🔟', '🔢', '0️⃣'], instruction: 'Find tallet' },
    { id: 'da1-a30', type: 'Audio', question: 'Ti', answer: '🔟', options: ['9️⃣', '🔟', '🔢', '0️⃣'], instruction: 'Find tallet' },
    { id: 'da1-a31', type: 'Audio', question: 'Mandag', answer: '📅', options: ['📅', '⏰', '🗺️', '🗞️'], instruction: 'Noget med tid' },
    { id: 'da1-a32', type: 'Audio', question: 'Skole', answer: '🏫', options: ['🏫', '🏩', '🏦', '🏪'], instruction: 'Hvor lærer man noget?' },
    { id: 'da1-a33', type: 'Audio', question: 'Lærer', answer: '👩‍🏫', options: ['👩‍🏫', '👨‍🚒', '👮', '👨‍🍳'], instruction: 'Hvem arbejder på skolen?' },
    { id: 'da1-a34', type: 'Audio', question: 'Elev', answer: '🧒', options: ['🧒', '👴', '👵', '👶'], instruction: 'Hvem går i skole?' },
    { id: 'da1-a35', type: 'Audio', question: 'Tegne', answer: '🖍️', options: ['🖍️', '🔨', '🧹', '🍴'], instruction: 'Hvad bruger man til at tegne?' },
    { id: 'da1-a36', type: 'Audio', question: 'Skrive', answer: '✍️', options: ['✍️', '🏃', '🏊', '🚴'], instruction: 'Find handlingen' },
    { id: 'da1-a37', type: 'Audio', question: 'Læse', answer: '📖', options: ['📖', '📺', '🎮', '⚽'], instruction: 'Find handlingen' },
    { id: 'da1-a38', type: 'Audio', question: 'Synge', answer: '🎤', options: ['🎤', '🎸', '🎹', '🥁'], instruction: 'Find tingen man bruger' },
    { id: 'da1-a39', type: 'Audio', question: 'Hoppe', answer: '🦘', options: ['🦘', '🐍', '🐟', '🐦'], instruction: 'Hvem hopper?' },
    { id: 'da1-a40', type: 'Audio', question: 'Svømme', answer: '🐟', options: ['🦘', '🐍', '🐟', '🐦'], instruction: 'Hvem svømmer?' },
    { id: 'da1-a41', type: 'Audio', question: 'Flyve', answer: '🐦', options: ['🦘', '🐍', '🐟', '🐦'], instruction: 'Hvem flyver?' },
    { id: 'da1-a42', type: 'Audio', question: 'Kravle', answer: '🐍', options: ['🦘', '🐍', '🐟', '🐦'], instruction: 'Hvem kravler?' },
    { id: 'da1-a43', type: 'Audio', question: 'Varm', answer: '🔥', options: ['🔥', '🧊', '☁️', '🧱'], instruction: 'Hvad er varmt?' },
    { id: 'da1-a44', type: 'Audio', question: 'Kold', answer: '🧊', options: ['🔥', '🧊', '☁️', '🧱'], instruction: 'Hvad er koldt?' },
    { id: 'da1-a45', type: 'Audio', question: 'Blød', answer: '☁️', options: ['🔥', '🧊', '☁️', '🧱'], instruction: 'Hvad er blødt?' },
    { id: 'da1-a46', type: 'Audio', question: 'Hård', answer: '🧱', options: ['🔥', '🧊', '☁️', '🧱'], instruction: 'Hvad er hårdt?' },
    { id: 'da1-a47', type: 'Audio', question: 'Sød', answer: '🍭', options: ['🍭', '🍋', '🌶️', '🧂'], instruction: 'Hvad er sødt?' },
    { id: 'da1-a48', type: 'Audio', question: 'Sur', answer: '🍋', options: ['🍭', '🍋', '🌶️', '🧂'], instruction: 'Hvad er surt?' },
    { id: 'da1-a49', type: 'Audio', question: 'Stærk', answer: '🌶️', options: ['🍭', '🍋', '🌶️', '🧂'], instruction: 'Hvad er stærkt?' },
    { id: 'da1-a50', type: 'Audio', question: 'Salt', answer: '🧂', options: ['🍭', '🍋', '🌶️', '🧂'], instruction: 'Hvad er saltet?' },
    { id: 'da1-a51', type: 'Audio', question: 'Lys', answer: '💡', options: ['💡', '🕶️', '🌑', '🕯️'], instruction: 'Hvad giver lys?' },
  ],
  2: [
    { id: 'da2-a1', type: 'Audio', question: 'Hund', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a2', type: 'Audio', question: 'Løbe', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a3', type: 'Audio', question: 'Grøn', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a4', type: 'Audio', question: 'Kat', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a5', type: 'Audio', question: 'Spise', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a6', type: 'Audio', question: 'Sød', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a7', type: 'Audio', question: 'Bord', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a8', type: 'Audio', question: 'Hoppe', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a9', type: 'Audio', question: 'Hurtig', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a10', type: 'Audio', question: 'Bog', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a11', type: 'Audio', question: 'Skrive', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a12', type: 'Audio', question: 'Stor', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a13', type: 'Audio', question: 'Skole', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a14', type: 'Audio', question: 'Sove', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a15', type: 'Audio', question: 'Lille', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a16', type: 'Audio', question: 'Taske', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a17', type: 'Audio', question: 'Drikke', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a18', type: 'Audio', question: 'Varm', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a19', type: 'Audio', question: 'Hus', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a20', type: 'Audio', question: 'Synge', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a21', type: 'Audio', question: 'Kold', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a22', type: 'Audio', question: 'Bil', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a23', type: 'Audio', question: 'Lege', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a24', type: 'Audio', question: 'Blød', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a25', type: 'Audio', question: 'Cykel', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a26', type: 'Audio', question: 'Høre', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a27', type: 'Audio', question: 'Hård', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a28', type: 'Audio', question: 'Æble', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a29', type: 'Audio', question: 'Se', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a30', type: 'Audio', question: 'Sur', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a31', type: 'Audio', question: 'Pære-træ', answer: '2 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a32', type: 'Audio', question: 'Bil', answer: '1 stavelse', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a33', type: 'Audio', question: 'Ban-an', answer: '2 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a34', type: 'Audio', question: 'E-le-fant', answer: '3 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a35', type: 'Audio', question: 'Hus', answer: '1 stavelse', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a36', type: 'Audio', question: 'Sko-le', answer: '2 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a37', type: 'Audio', question: 'Læ-re-bog', answer: '3 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a38', type: 'Audio', question: 'Seng', answer: '1 stavelse', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a39', type: 'Audio', question: 'Vin-due', answer: '2 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a40', type: 'Audio', question: 'Kom-pu-ter', answer: '3 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a41', type: 'Audio', question: 'Hunde', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a42', type: 'Audio', question: 'Hund', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a43', type: 'Audio', question: 'Katte', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a44', type: 'Audio', question: 'Kat', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a45', type: 'Audio', question: 'Biler', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a46', type: 'Audio', question: 'Bil', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a47', type: 'Audio', question: 'Huse', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a48', type: 'Audio', question: 'Hus', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a49', type: 'Audio', question: 'Bøger', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a50', type: 'Audio', question: 'Bog', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a51', type: 'Audio', question: 'Æbler', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a52', type: 'Audio', question: 'Dreng', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a53', type: 'Audio', question: 'Sover', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a54', type: 'Audio', question: 'Gulerod', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a55', type: 'Audio', question: 'Glad', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a56', type: 'Audio', question: 'Hoppe', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a57', type: 'Audio', question: 'Lykkelig', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a58', type: 'Audio', question: 'Taske', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a59', type: 'Audio', question: 'Bringe', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a60', type: 'Audio', question: 'Lyseblå', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a61', type: 'Audio', question: 'Vindue', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a62', type: 'Audio', question: 'Spille', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a63', type: 'Audio', question: 'Langsom', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a64', type: 'Audio', question: 'I morgen', answer: 'Biord', options: ['Navneord', 'Udsagnsord', 'Biord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a65', type: 'Audio', question: 'Hjemme', answer: 'Biord', options: ['Navneord', 'Udsagnsord', 'Biord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a66', type: 'Audio', question: 'Ude', answer: 'Biord', options: ['Navneord', 'Udsagnsord', 'Biord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a67', type: 'Audio', question: 'Aldrig', answer: 'Biord', options: ['Navneord', 'Udsagnsord', 'Biord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a68', type: 'Audio', question: 'Altid', answer: 'Biord', options: ['Navneord', 'Udsagnsord', 'Biord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a69', type: 'Audio', question: 'Og', answer: 'Bindeord', options: ['Navneord', 'Bindeord', 'Biord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a70', type: 'Audio', question: 'Men', answer: 'Bindeord', options: ['Navneord', 'Bindeord', 'Biord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a71', type: 'Audio', question: 'Eller', answer: 'Bindeord', options: ['Navneord', 'Bindeord', 'Biord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da2-a72', type: 'Audio', question: 'Hunde-hus', answer: '2 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a73', type: 'Audio', question: 'Bil-en', answer: '2 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a74', type: 'Audio', question: 'Ban-an-er', answer: '3 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a75', type: 'Audio', question: 'Kat-te-ne', answer: '3 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a76', type: 'Audio', question: 'Bog-hylde', answer: '2 stavelser', options: ['1 stavelse', '2 stavelser', '3 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a77', type: 'Audio', question: 'Sko-le-taske', answer: '4 stavelser', options: ['2 stavelser', '3 stavelser', '4 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a78', type: 'Audio', question: 'Æb-le-træ', answer: '3 stavelser', options: ['2 stavelser', '3 stavelser', '4 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a79', type: 'Audio', question: 'Blomst-er-ne', answer: '3 stavelser', options: ['2 stavelser', '3 stavelser', '4 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a80', type: 'Audio', question: 'Som-mer-fugl', answer: '3 stavelser', options: ['2 stavelser', '3 stavelser', '4 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a81', type: 'Audio', question: 'Cin-e-ma', answer: '3 stavelser', options: ['2 stavelser', '3 stavelser', '4 stavelser'], instruction: 'Hvor mange stavelser?' },
    { id: 'da2-a82', type: 'Audio', question: 'Hunde', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a83', type: 'Audio', question: 'Tand', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a84', type: 'Audio', question: 'Tænder', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a85', type: 'Audio', question: 'Bog', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a86', type: 'Audio', question: 'Bøger', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a87', type: 'Audio', question: 'Barn', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a88', type: 'Audio', question: 'Børn', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a89', type: 'Audio', question: 'Mand', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a90', type: 'Audio', question: 'Mænd', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a91', type: 'Audio', question: 'Fod', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a92', type: 'Audio', question: 'Fødder', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a93', type: 'Audio', question: 'Hus', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a94', type: 'Audio', question: 'Huse', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a95', type: 'Audio', question: 'Dør', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a96', type: 'Audio', question: 'Døre', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a97', type: 'Audio', question: 'Vindue', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a98', type: 'Audio', question: 'Vinduer', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a99', type: 'Audio', question: 'Skovl', answer: 'Ental', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a100', type: 'Audio', question: 'Skovle', answer: 'Flertal', options: ['Ental', 'Flertal'], instruction: 'Ental eller flertal?' },
    { id: 'da2-a101', type: 'Audio', question: 'Hoppe', answer: 'Udsagnsord', options: ['Udsagnsord', 'Navneord'], instruction: 'Ordklasse' },
  ],
  10: [
    { id: 'da10-a1', type: 'Audio', question: 'Ambivalens', answer: 'Substantiv', options: ['Substantiv', 'Verbum', 'Adjektiv'], instruction: 'Grammatik' },
    { id: 'da10-a2', type: 'Audio', question: 'At artikulere', answer: 'Verbum', options: ['Substantiv', 'Verbum', 'Adjektiv'], instruction: 'Grammatik' },
    { id: 'da10-a3', type: 'Audio', question: 'Eksperimentel', answer: 'Adjektiv', options: ['Substantiv', 'Verbum', 'Adjektiv'], instruction: 'Grammatik' },
    { id: 'da10-a4', type: 'Audio', question: 'Interaktion', answer: 'Substantiv', options: ['Substantiv', 'Verbum', 'Adjektiv'], instruction: 'Grammatik' },
    { id: 'da10-a5', type: 'Audio', question: 'At reflektere', answer: 'Verbum', options: ['Substantiv', 'Verbum', 'Adjektiv'], instruction: 'Grammatik' },
    { id: 'da10-a6', type: 'Audio', question: 'Kompleks', answer: 'Adjektiv', options: ['Substantiv', 'Verbum', 'Adjektiv'], instruction: 'Grammatik' },
    { id: 'da10-a7', type: 'Audio', question: 'Transformation', answer: 'Substantiv', options: ['Substantiv', 'Verbum', 'Adjektiv'], instruction: 'Grammatik' },
    { id: 'da10-a8', type: 'Audio', question: 'At optimere', answer: 'Verbum', options: ['Substantiv', 'Verbum', 'Adjektiv'], instruction: 'Grammatik' },
    { id: 'da10-a9', type: 'Audio', question: 'Bæredygtig', answer: 'Adjektiv', options: ['Substantiv', 'Verbum', 'Adjektiv'], instruction: 'Grammatik' },
    { id: 'da10-a10', type: 'Audio', question: 'Legitimitet', answer: 'Substantiv', options: ['Substantiv', 'Verbum', 'Adjektiv'], instruction: 'Grammatik' },
    { id: 'da10-a11', type: 'Audio', question: 'Livet er som en rejse', answer: 'Simile', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Stilistik' },
    { id: 'da10-a12', type: 'Audio', question: 'Du er min solstråle', answer: 'Metafor', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Stilistik' },
    { id: 'da10-a13', type: 'Audio', question: 'Væggen lyttede til dem', answer: 'Besjæling', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Stilistik' },
    { id: 'da10-a14', type: 'Audio', question: 'Hjertet var koldt som is', answer: 'Simile', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Stilistik' },
    { id: 'da10-a15', type: 'Audio', question: 'Tiden læger alle sår', answer: 'Metafor', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Stilistik' },
    { id: 'da10-a16', type: 'Audio', question: 'Solen kyssede marken', answer: 'Besjæling', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Stilistik' },
    { id: 'da10-a17', type: 'Audio', question: 'Stærk som en bjørn', answer: 'Simile', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Stilistik' },
    { id: 'da10-a18', type: 'Audio', question: 'Han er en åben bog', answer: 'Metafor', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Stilistik' },
    { id: 'da10-a19', type: 'Audio', question: 'Vinden peb i ruden', answer: 'Besjæling', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Stilistik' },
    { id: 'da10-a20', type: 'Audio', question: 'Verden er en teaterscene', answer: 'Metafor', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Stilistik' },
    { id: 'da10-a21', type: 'Audio', question: 'Implicit', answer: 'Underforstået', options: ['Underforstået', 'Tydeligt', 'Skjult'], instruction: 'Betydning' },
    { id: 'da10-a22', type: 'Audio', question: 'Eksplicit', answer: 'Tydeligt', options: ['Tydeligt', 'Skjult', 'Uklart'], instruction: 'Betydning' },
    { id: 'da10-a23', type: 'Audio', question: 'Subjektiv', answer: 'Personlig', options: ['Personlig', 'Objektiv', 'Fælles'], instruction: 'Betydning' },
    { id: 'da10-a24', type: 'Audio', question: 'Objektiv', answer: 'Uvildig', options: ['Uvildig', 'Personlig', 'Følsom'], instruction: 'Betydning' },
    { id: 'da10-a25', type: 'Audio', question: 'Pragmatisk', answer: 'Løsningsorienteret', options: ['Løsningsorienteret', 'Drømmende', 'Vred'], instruction: 'Betydning' },
    { id: 'da10-a26', type: 'Audio', question: 'Ambivalent', answer: 'Tvivlende', options: ['Tvivlende', 'Sikker', 'Glad'], instruction: 'Betydning' },
    { id: 'da10-a27', type: 'Audio', question: 'Konsekvent', answer: 'Urokkelig', options: ['Urokkelig', 'Uberegnelig', 'Sjov'], instruction: 'Betydning' },
    { id: 'da10-a28', type: 'Audio', question: 'Relevant', answer: 'Vedkommende', options: ['Vedkommende', 'Lige meget', 'Gammelt'], instruction: 'Betydning' },
    { id: 'da10-a29', type: 'Audio', question: 'Konkret', answer: 'Håndgribelig', options: ['Håndgribelig', 'Abstrakt', 'Svært'], instruction: 'Betydning' },
    { id: 'da10-a30', type: 'Audio', question: 'Abstrakt', answer: 'Teoretisk', options: ['Teoretisk', 'Konkret', 'Nemt'], instruction: 'Betydning' },
    { id: 'da10-a31', type: 'Audio', question: 'Etos', answer: 'Troværdighed', options: ['Troværdighed', 'Følelser', 'Logik'], instruction: 'Appelform' },
    { id: 'da10-a32', type: 'Audio', question: 'Patos', answer: 'Følelser', options: ['Følelser', 'Troværdighed', 'Logik'], instruction: 'Appelform' },
    { id: 'da10-a33', type: 'Audio', question: 'Logos', answer: 'Logik', options: ['Logik', 'Følelser', 'Troværdighed'], instruction: 'Appelform' },
    { id: 'da10-a34', type: 'Audio', question: 'Ironi', answer: 'Det modsatte', options: ['Det modsatte', 'Det samme', 'Alvor'], instruction: 'Virkemiddel' },
    { id: 'da10-a35', type: 'Audio', question: 'Sarkasme', answer: 'Hånlig ironi', options: ['Hånlig ironi', 'Ros', 'Sjov'], instruction: 'Virkemiddel' },
    { id: 'da10-a36', type: 'Audio', question: 'Satire', answer: 'Udstille tåbelighed', options: ['Udstille tåbelighed', 'Hylde helte', 'Skræmme børn'], instruction: 'Virkemiddel' },
    { id: 'da10-a37', type: 'Audio', question: 'Hyperbel', answer: 'Overdrivelse', options: ['Overdrivelse', 'Underdrivelse', 'Gentagelse'], instruction: 'Virkemiddel' },
    { id: 'da10-a38', type: 'Audio', question: 'Litotes', answer: 'Underdrivelse', options: ['Underdrivelse', 'Overdrivelse', 'Gentagelse'], instruction: 'Virkemiddel' },
    { id: 'da10-a39', type: 'Audio', question: 'Allitteration', answer: 'Konsonantrim', options: ['Konsonantrim', 'Vokalrim', 'Enderim'], instruction: 'Virkemiddel' },
    { id: 'da10-a40', type: 'Audio', question: 'Assonans', answer: 'Vokalrim', options: ['Vokalrim', 'Konsonantrim', 'Enderim'], instruction: 'Virkemiddel' },
    { id: 'da10-a41', type: 'Audio', question: 'Substantiv', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Latinske betegnelser' },
    { id: 'da10-a42', type: 'Audio', question: 'Verbum', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Latinske betegnelser' },
    { id: 'da10-a43', type: 'Audio', question: 'Adjektiv', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Latinske betegnelser' },
    { id: 'da10-a44', type: 'Audio', question: 'Adverbium', answer: 'Biord', options: ['Biord', 'Bindeord', 'Stedord'], instruction: 'Latinske betegnelser' },
    { id: 'da10-a45', type: 'Audio', question: 'Konjunktion', answer: 'Bindeord', options: ['Biord', 'Bindeord', 'Stedord'], instruction: 'Latinske betegnelser' },
    { id: 'da10-a46', type: 'Audio', question: 'Pronomen', answer: 'Stedord', options: ['Biord', 'Bindeord', 'Stedord'], instruction: 'Latinske betegnelser' },
    { id: 'da10-a47', type: 'Audio', question: 'Præposition', answer: 'Forholdsord', options: ['Forholdsord', 'Kendeord', 'Talord'], instruction: 'Latinske betegnelser' },
    { id: 'da10-a48', type: 'Audio', question: 'Artikel', answer: 'Kendeord', options: ['Forholdsord', 'Kendeord', 'Talord'], instruction: 'Latinske betegnelser' },
    { id: 'da10-a49', type: 'Audio', question: 'Numerale', answer: 'Talord', options: ['Forholdsord', 'Kendeord', 'Talord'], instruction: 'Latinske betegnelser' },
    { id: 'da10-a50', type: 'Audio', question: 'Interjektion', answer: 'Udråbsord', options: ['Udråbsord', 'Bindeord', 'Biord'], instruction: 'Latinske betegnelser' },
  ],
  3: [
    { id: 'da3-a1', type: 'Audio', question: 'Jeg', answer: 'Stedord', options: ['Navneord', 'Stedord', 'Udsagnsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da3-a2', type: 'Audio', question: 'Vi', answer: 'Stedord', options: ['Navneord', 'Stedord', 'Udsagnsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da3-a3', type: 'Audio', question: 'Han', answer: 'Stedord', options: ['Navneord', 'Stedord', 'Udsagnsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da3-a4', type: 'Audio', question: 'Hun', answer: 'Stedord', options: ['Navneord', 'Stedord', 'Udsagnsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da3-a5', type: 'Audio', question: 'De', answer: 'Stedord', options: ['Navneord', 'Stedord', 'Udsagnsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da3-a6', type: 'Audio', question: 'På', answer: 'Forholdsord', options: ['Forholdsord', 'Navneord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da3-a7', type: 'Audio', question: 'I', answer: 'Forholdsord', options: ['Forholdsord', 'Navneord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da3-a8', type: 'Audio', question: 'Under', answer: 'Forholdsord', options: ['Forholdsord', 'Navneord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da3-a9', type: 'Audio', question: 'Over', answer: 'Forholdsord', options: ['Forholdsord', 'Navneord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da3-a10', type: 'Audio', question: 'Ved', answer: 'Forholdsord', options: ['Forholdsord', 'Navneord', 'Tillægsord'], instruction: 'Hvilken ordklasse?' },
    { id: 'da3-a11', type: 'Audio', question: 'Bordben', answer: 'Sammensat ord', options: ['Enkelt ord', 'Sammensat ord'], instruction: 'Hvilken type ord?' },
    { id: 'da3-a12', type: 'Audio', question: 'Skolegård', answer: 'Sammensat ord', options: ['Enkelt ord', 'Sammensat ord'], instruction: 'Hvilken type ord?' },
    { id: 'da3-a13', type: 'Audio', question: 'Bog', answer: 'Enkelt ord', options: ['Enkelt ord', 'Sammensat ord'], instruction: 'Hvilken type ord?' },
    { id: 'da3-a14', type: 'Audio', question: 'Fodbold', answer: 'Sammensat ord', options: ['Enkelt ord', 'Sammensat ord'], instruction: 'Hvilken type ord?' },
    { id: 'da3-a15', type: 'Audio', question: 'Ismaskine', answer: 'Sammensat ord', options: ['Enkelt ord', 'Sammensat ord'], instruction: 'Hvilken type ord?' },
    { id: 'da3-a16', type: 'Audio', question: 'Madkasse', answer: 'Sammensat ord', options: ['Enkelt ord', 'Sammensat ord'], instruction: 'Hvilken type ord?' },
    { id: 'da3-a17', type: 'Audio', question: 'Træ', answer: 'Enkelt ord', options: ['Enkelt ord', 'Sammensat ord'], instruction: 'Hvilken type ord?' },
    { id: 'da3-a18', type: 'Audio', question: 'Vandflaske', answer: 'Sammensat ord', options: ['Enkelt ord', 'Sammensat ord'], instruction: 'Hvilken type ord?' },
    { id: 'da3-a19', type: 'Audio', question: 'Solbriller', answer: 'Sammensat ord', options: ['Enkelt ord', 'Sammensat ord'], instruction: 'Hvilken type ord?' },
    { id: 'da3-a20', type: 'Audio', question: 'Computer', answer: 'Enkelt ord', options: ['Enkelt ord', 'Sammensat ord'], instruction: 'Hvilken type ord?' },
    { id: 'da3-a21', type: 'Audio', question: 'Glad', answer: 'Tillægsord', options: ['Tillægsord', 'Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a22', type: 'Audio', question: 'Pæn', answer: 'Tillægsord', options: ['Tillægsord', 'Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a23', type: 'Audio', question: 'Grim', answer: 'Tillægsord', options: ['Tillægsord', 'Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a24', type: 'Audio', question: 'Våd', answer: 'Tillægsord', options: ['Tillægsord', 'Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a25', type: 'Audio', question: 'Tør', answer: 'Tillægsord', options: ['Tillægsord', 'Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a26', type: 'Audio', question: 'Altid', answer: 'Biord', options: ['Biord', 'Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a27', type: 'Audio', question: 'Aldrig', answer: 'Biord', options: ['Biord', 'Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a28', type: 'Audio', question: 'Ofte', answer: 'Biord', options: ['Biord', 'Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a29', type: 'Audio', question: 'Hjem', answer: 'Biord', options: ['Biord', 'Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a30', type: 'Audio', question: 'Ude', answer: 'Biord', options: ['Biord', 'Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a31', type: 'Audio', question: 'At løbe', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da3-a32', type: 'Audio', question: 'At spise', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da3-a33', type: 'Audio', question: 'At sove', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da3-a34', type: 'Audio', question: 'At tænke', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da3-a35', type: 'Audio', question: 'At lære', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da3-a36', type: 'Audio', question: 'Løb!', answer: 'Bydemåde', options: ['Nutid', 'Datid', 'Bydemåde'], instruction: 'Hvilken form?' },
    { id: 'da3-a37', type: 'Audio', question: 'Spis!', answer: 'Bydemåde', options: ['Nutid', 'Datid', 'Bydemåde'], instruction: 'Hvilken form?' },
    { id: 'da3-a38', type: 'Audio', question: 'Sov!', answer: 'Bydemåde', options: ['Nutid', 'Datid', 'Bydemåde'], instruction: 'Hvilken form?' },
    { id: 'da3-a39', type: 'Audio', question: 'Hør!', answer: 'Bydemåde', options: ['Nutid', 'Datid', 'Bydemåde'], instruction: 'Hvilken form?' },
    { id: 'da3-a40', type: 'Audio', question: 'Se!', answer: 'Bydemåde', options: ['Nutid', 'Datid', 'Bydemåde'], instruction: 'Hvilken form?' },
    { id: 'da3-a41', type: 'Audio', question: 'Lille - mindre - mindst', answer: 'Gradbøjning', options: ['Gradbøjning', 'Tidsbøjning'], instruction: 'Hvilken bøjning?' },
    { id: 'da3-a42', type: 'Audio', question: 'Stor - større - størst', answer: 'Gradbøjning', options: ['Gradbøjning', 'Tidsbøjning'], instruction: 'Hvilken bøjning?' },
    { id: 'da3-a43', type: 'Audio', question: 'God - bedre - bedst', answer: 'Gradbøjning', options: ['Gradbøjning', 'Tidsbøjning'], instruction: 'Hvilken bøjning?' },
    { id: 'da3-a44', type: 'Audio', question: 'Grim - grimmere - grimmest', answer: 'Gradbøjning', options: ['Gradbøjning', 'Tidsbøjning'], instruction: 'Hvilken bøjning?' },
    { id: 'da3-a45', type: 'Audio', question: 'Hurtig - hurtigere - hurtigst', answer: 'Gradbøjning', options: ['Gradbøjning', 'Tidsbøjning'], instruction: 'Hvilken bøjning?' },
    { id: 'da3-a46', type: 'Audio', question: 'Skov', answer: 'Navneord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a47', type: 'Audio', question: 'Mark', answer: 'Navneord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a48', type: 'Audio', question: 'Vej', answer: 'Navneord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a49', type: 'Audio', question: 'Sky', answer: 'Navneord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a50', type: 'Audio', question: 'Regn', answer: 'Navneord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da3-a51', type: 'Audio', question: 'Slut', answer: 'Navneord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
  ],
  4: [
    { id: 'da4-a1', type: 'Audio', question: 'En hund', answer: 'Ubestemt', options: ['Ubestemt', 'Bestemt'], instruction: 'Ubestemt eller bestemt?' },
    { id: 'da4-a2', type: 'Audio', question: 'Hunden', answer: 'Bestemt', options: ['Ubestemt', 'Bestemt'], instruction: 'Ubestemt eller bestemt?' },
    { id: 'da4-a3', type: 'Audio', question: 'En kat', answer: 'Ubestemt', options: ['Ubestemt', 'Bestemt'], instruction: 'Ubestemt eller bestemt?' },
    { id: 'da4-a4', type: 'Audio', question: 'Katten', answer: 'Bestemt', options: ['Ubestemt', 'Bestemt'], instruction: 'Ubestemt eller bestemt?' },
    { id: 'da4-a5', type: 'Audio', question: 'Et hus', answer: 'Ubestemt', options: ['Ubestemt', 'Bestemt'], instruction: 'Ubestemt eller bestemt?' },
    { id: 'da4-a6', type: 'Audio', question: 'Huset', answer: 'Bestemt', options: ['Ubestemt', 'Bestemt'], instruction: 'Ubestemt eller bestemt?' },
    { id: 'da4-a7', type: 'Audio', question: 'Et barn', answer: 'Ubestemt', options: ['Ubestemt', 'Bestemt'], instruction: 'Ubestemt eller bestemt?' },
    { id: 'da4-a8', type: 'Audio', question: 'Barnet', answer: 'Bestemt', options: ['Ubestemt', 'Bestemt'], instruction: 'Ubestemt eller bestemt?' },
    { id: 'da4-a9', type: 'Audio', question: 'En bil', answer: 'Ubestemt', options: ['Ubestemt', 'Bestemt'], instruction: 'Ubestemt eller bestemt?' },
    { id: 'da4-a10', type: 'Audio', question: 'Bilen', answer: 'Bestemt', options: ['Ubestemt', 'Bestemt'], instruction: 'Ubestemt eller bestemt?' },
    { id: 'da4-a11', type: 'Audio', question: 'Løber', answer: 'Nutid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a12', type: 'Audio', question: 'Løb', answer: 'Datid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a13', type: 'Audio', question: 'Vil løbe', answer: 'Fremtid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a14', type: 'Audio', question: 'Spiser', answer: 'Nutid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a15', type: 'Audio', question: 'Spiste', answer: 'Datid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a16', type: 'Audio', question: 'Vil spise', answer: 'Fremtid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a17', type: 'Audio', question: 'Sover', answer: 'Nutid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a18', type: 'Audio', question: 'Sov', answer: 'Datid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a19', type: 'Audio', question: 'Vil sove', answer: 'Fremtid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a20', type: 'Audio', question: 'Går', answer: 'Nutid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a21', type: 'Audio', question: 'Gik', answer: 'Datid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a22', type: 'Audio', question: 'Vil gå', answer: 'Fremtid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a23', type: 'Audio', question: 'Hører', answer: 'Nutid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a24', type: 'Audio', question: 'Hørte', answer: 'Datid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a25', type: 'Audio', question: 'Vil høre', answer: 'Fremtid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a26', type: 'Audio', question: 'Ligger', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a27', type: 'Audio', question: 'Lå', answer: 'Datid', options: ['Nutid', 'Datid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a28', type: 'Audio', question: 'Sidder', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a29', type: 'Audio', question: 'Sad', answer: 'Datid', options: ['Nutid', 'Datid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a30', type: 'Audio', question: 'Står', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a31', type: 'Audio', question: 'Stod', answer: 'Datid', options: ['Nutid', 'Datid'], instruction: 'Hvilken tid?' },
    { id: 'da4-a32', type: 'Audio', question: 'Rød - rødere - rødest', answer: 'Gradbøjning', options: ['Gradbøjning', 'Navnebøjning'], instruction: 'Hvilken bøjning?' },
    { id: 'da4-a33', type: 'Audio', question: 'Høj - højere - højest', answer: 'Gradbøjning', options: ['Gradbøjning', 'Navnebøjning'], instruction: 'Hvilken bøjning?' },
    { id: 'da4-a34', type: 'Audio', question: 'Lav - lavere - lavest', answer: 'Gradbøjning', options: ['Gradbøjning', 'Navnebøjning'], instruction: 'Hvilken bøjning?' },
    { id: 'da4-a35', type: 'Audio', question: 'Lang - længere - længst', answer: 'Gradbøjning', options: ['Gradbøjning', 'Navnebøjning'], instruction: 'Hvilken bøjning?' },
    { id: 'da4-a36', type: 'Audio', question: 'Kort - kortere - kortest', answer: 'Gradbøjning', options: ['Gradbøjning', 'Navnebøjning'], instruction: 'Hvilken bøjning?' },
    { id: 'da4-a37', type: 'Audio', question: 'Hunde - hundene', answer: 'Bøjning', options: ['Navneord', 'Udsagnsord'], instruction: 'Hvad bøjes?' },
    { id: 'da4-a38', type: 'Audio', question: 'Katte - kattene', answer: 'Bøjning', options: ['Navneord', 'Udsagnsord'], instruction: 'Hvad bøjes?' },
    { id: 'da4-a39', type: 'Audio', question: 'Biler - bilerne', answer: 'Bøjning', options: ['Navneord', 'Udsagnsord'], instruction: 'Hvad bøjes?' },
    { id: 'da4-a40', type: 'Audio', question: 'Huse - husene', answer: 'Bøjning', options: ['Navneord', 'Udsagnsord'], instruction: 'Hvad bøjes?' },
    { id: 'da4-a41', type: 'Audio', question: 'Bøger - bøgerne', answer: 'Bøjning', options: ['Navneord', 'Udsagnsord'], instruction: 'Hvad bøjes?' },
    { id: 'da4-a42', type: 'Audio', question: 'Jeg spiser et æble.', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Tid?' },
    { id: 'da4-a43', type: 'Audio', question: 'Han løb en tur.', answer: 'Datid', options: ['Nutid', 'Datid'], instruction: 'Tid?' },
    { id: 'da4-a44', type: 'Audio', question: 'Vi ser en film.', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Tid?' },
    { id: 'da4-a45', type: 'Audio', question: 'De sang en sang.', answer: 'Datid', options: ['Nutid', 'Datid'], instruction: 'Tid?' },
    { id: 'da4-a46', type: 'Audio', question: 'Solen skinner.', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Tid?' },
    { id: 'da4-a47', type: 'Audio', question: 'Det regnede i går.', answer: 'Datid', options: ['Nutid', 'Datid'], instruction: 'Tid?' },
    { id: 'da4-a48', type: 'Audio', question: 'Vinden blæser.', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Tid?' },
    { id: 'da4-a49', type: 'Audio', question: 'Sneen faldt.', answer: 'Datid', options: ['Nutid', 'Datid'], instruction: 'Tid?' },
    { id: 'da4-a50', type: 'Audio', question: 'Isen smelter.', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Tid?' },
    { id: 'da4-a51', type: 'Audio', question: 'Alt er ok.', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Tid?' },
  ],
  5: [
    { id: 'da5-a1', type: 'Audio', question: 'Løbe', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Tidsform' },
    { id: 'da5-a2', type: 'Audio', question: 'Gik', answer: 'Datid', options: ['Nutid', 'Datid'], instruction: 'Tidsform' },
    { id: 'da5-a3', type: 'Audio', question: 'Sover', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Tidsform' },
    { id: 'da5-a4', type: 'Audio', question: 'Spiste', answer: 'Datid', options: ['Nutid', 'Datid'], instruction: 'Tidsform' },
    { id: 'da5-a5', type: 'Audio', question: 'Tænker', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Tidsform' },
    { id: 'da5-a6', type: 'Audio', question: 'Hørte', answer: 'Datid', options: ['Nutid', 'Datid'], instruction: 'Tidsform' },
    { id: 'da5-a7', type: 'Audio', question: 'Ser', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Tidsform' },
    { id: 'da5-a8', type: 'Audio', question: 'Sang', answer: 'Datid', options: ['Nutid', 'Datid'], instruction: 'Tidsform' },
    { id: 'da5-a9', type: 'Audio', question: 'Finder', answer: 'Nutid', options: ['Nutid', 'Datid'], instruction: 'Tidsform' },
    { id: 'da5-a10', type: 'Audio', question: 'Glemte', answer: 'Datid', options: ['Nutid', 'Datid'], instruction: 'Tidsform' },
    { id: 'da5-a11', type: 'Audio', question: 'Glad', answer: 'Lykkelig', options: ['Lykkelig', 'Trist', 'Vred'], instruction: 'Find synonym' },
    { id: 'da5-a12', type: 'Audio', question: 'Stor', answer: 'Enorm', options: ['Enorm', 'Lille', 'Tynd'], instruction: 'Find synonym' },
    { id: 'da5-a13', type: 'Audio', question: 'Hurtig', answer: 'Tjep', options: ['Tjep', 'Langsom', 'Træt'], instruction: 'Find synonym' },
    { id: 'da5-a14', type: 'Audio', question: 'Pæn', answer: 'Smuk', options: ['Smuk', 'Grim', 'Beskidt'], instruction: 'Find synonym' },
    { id: 'da5-a15', type: 'Audio', question: 'Klog', answer: 'Intelligent', options: ['Intelligent', 'Dum', 'Sjov'], instruction: 'Find synonym' },
    { id: 'da5-a16', type: 'Audio', question: 'Glad', answer: 'Trist', options: ['Lykkelig', 'Trist', 'Vred'], instruction: 'Find antonym (modsat)' },
    { id: 'da5-a17', type: 'Audio', question: 'Stor', answer: 'Lille', options: ['Enorm', 'Lille', 'Tynd'], instruction: 'Find antonym (modsat)' },
    { id: 'da5-a18', type: 'Audio', question: 'Hurtig', answer: 'Langsom', options: ['Tjep', 'Langsom', 'Træt'], instruction: 'Find antonym (modsat)' },
    { id: 'da5-a19', type: 'Audio', question: 'Pæn', answer: 'Grim', options: ['Smuk', 'Grim', 'Beskidt'], instruction: 'Find antonym (modsat)' },
    { id: 'da5-a20', type: 'Audio', question: 'Klog', answer: 'Dum', options: ['Intelligent', 'Dum', 'Sjov'], instruction: 'Find antonym (modsat)' },
    { id: 'da5-a21', type: 'Audio', question: 'Forsigtigt', answer: 'Biord', options: ['Biord', 'Tillægsord', 'Navneord'], instruction: 'Ordklasse' },
    { id: 'da5-a22', type: 'Audio', question: 'Hurtigt', answer: 'Biord', options: ['Biord', 'Tillægsord', 'Navneord'], instruction: 'Ordklasse' },
    { id: 'da5-a23', type: 'Audio', question: 'Langsomt', answer: 'Biord', options: ['Biord', 'Tillægsord', 'Navneord'], instruction: 'Ordklasse' },
    { id: 'da5-a24', type: 'Audio', question: 'Pænt', answer: 'Biord', options: ['Biord', 'Tillægsord', 'Navneord'], instruction: 'Ordklasse' },
    { id: 'da5-a25', type: 'Audio', question: 'Grimt', answer: 'Biord', options: ['Biord', 'Tillægsord', 'Navneord'], instruction: 'Ordklasse' },
    { id: 'da5-a26', type: 'Audio', question: 'Meget', answer: 'Biord', options: ['Biord', 'Tillægsord', 'Navneord'], instruction: 'Ordklasse' },
    { id: 'da5-a27', type: 'Audio', question: 'Ganske', answer: 'Biord', options: ['Biord', 'Tillægsord', 'Navneord'], instruction: 'Ordklasse' },
    { id: 'da5-a28', type: 'Audio', question: 'Særdeles', answer: 'Biord', options: ['Biord', 'Tillægsord', 'Navneord'], instruction: 'Ordklasse' },
    { id: 'da5-a29', type: 'Audio', question: 'Temmelig', answer: 'Biord', options: ['Biord', 'Tillægsord', 'Navneord'], instruction: 'Ordklasse' },
    { id: 'da5-a30', type: 'Audio', question: 'Næsten', answer: 'Biord', options: ['Biord', 'Tillægsord', 'Navneord'], instruction: 'Ordklasse' },
    { id: 'da5-a31', type: 'Audio', question: 'Og', answer: 'Bindeord', options: ['Bindeord', 'Biord', 'Stedord'], instruction: 'Ordklasse' },
    { id: 'da5-a32', type: 'Audio', question: 'Men', answer: 'Bindeord', options: ['Bindeord', 'Biord', 'Stedord'], instruction: 'Ordklasse' },
    { id: 'da5-a33', type: 'Audio', question: 'Eller', answer: 'Bindeord', options: ['Bindeord', 'Biord', 'Stedord'], instruction: 'Ordklasse' },
    { id: 'da5-a34', type: 'Audio', question: 'Fordi', answer: 'Bindeord', options: ['Bindeord', 'Biord', 'Stedord'], instruction: 'Ordklasse' },
    { id: 'da5-a35', type: 'Audio', question: 'Da', answer: 'Bindeord', options: ['Bindeord', 'Biord', 'Stedord'], instruction: 'Ordklasse' },
    { id: 'da5-a36', type: 'Audio', question: 'Hvis', answer: 'Bindeord', options: ['Bindeord', 'Biord', 'Stedord'], instruction: 'Ordklasse' },
    { id: 'da5-a37', type: 'Audio', question: 'At', answer: 'Bindeord', options: ['Bindeord', 'Biord', 'Stedord'], instruction: 'Ordklasse' },
    { id: 'da5-a38', type: 'Audio', question: 'Som', answer: 'Bindeord', options: ['Bindeord', 'Biord', 'Stedord'], instruction: 'Ordklasse' },
    { id: 'da5-a39', type: 'Audio', question: 'Der', answer: 'Bindeord', options: ['Bindeord', 'Biord', 'Stedord'], instruction: 'Ordklasse' },
    { id: 'da5-a40', type: 'Audio', question: 'Skønt', answer: 'Bindeord', options: ['Bindeord', 'Biord', 'Stedord'], instruction: 'Ordklasse' },
    { id: 'da5-a41', type: 'Audio', question: 'Aha!', answer: 'Udråbsord', options: ['Udråbsord', 'Bindeord', 'Biord'], instruction: 'Ordklasse' },
    { id: 'da5-a42', type: 'Audio', question: 'Ups!', answer: 'Udråbsord', options: ['Udråbsord', 'Bindeord', 'Biord'], instruction: 'Ordklasse' },
    { id: 'da5-a43', type: 'Audio', question: 'Hej!', answer: 'Udråbsord', options: ['Udråbsord', 'Bindeord', 'Biord'], instruction: 'Ordklasse' },
    { id: 'da5-a44', type: 'Audio', question: 'Av!', answer: 'Udråbsord', options: ['Udråbsord', 'Bindeord', 'Biord'], instruction: 'Ordklasse' },
    { id: 'da5-a45', type: 'Audio', question: 'Øv!', answer: 'Udråbsord', options: ['Udråbsord', 'Bindeord', 'Biord'], instruction: 'Ordklasse' },
    { id: 'da5-a46', type: 'Audio', question: 'Nå!', answer: 'Udråbsord', options: ['Udråbsord', 'Bindeord', 'Biord'], instruction: 'Ordklasse' },
    { id: 'da5-a47', type: 'Audio', question: 'Hov!', answer: 'Udråbsord', options: ['Udråbsord', 'Bindeord', 'Biord'], instruction: 'Ordklasse' },
    { id: 'da5-a48', type: 'Audio', question: 'Haps!', answer: 'Udråbsord', options: ['Udråbsord', 'Bindeord', 'Biord'], instruction: 'Ordklasse' },
    { id: 'da5-a49', type: 'Audio', question: 'Bums!', answer: 'Udråbsord', options: ['Udråbsord', 'Bindeord', 'Biord'], instruction: 'Ordklasse' },
    { id: 'da5-a50', type: 'Audio', question: 'Vupti!', answer: 'Udråbsord', options: ['Udråbsord', 'Bindeord', 'Biord'], instruction: 'Ordklasse' },
    { id: 'da5-a51', type: 'Audio', question: 'Tadaa!', answer: 'Udråbsord', options: ['Udråbsord', 'Bindeord', 'Biord'], instruction: 'Ordklasse' },
  ],
  6: [
    { id: 'da6-a1', type: 'Audio', question: 'Hjertelig', answer: 'Stumt h', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a2', type: 'Audio', question: 'Hvide', answer: 'Stumt h', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a3', type: 'Audio', question: 'Hjalp', answer: 'Stumt h', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a4', type: 'Audio', question: 'Hvem', answer: 'Stumt h', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a5', type: 'Audio', question: 'Hvor', answer: 'Stumt h', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a6', type: 'Audio', question: 'Blid', answer: 'Stumt d', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a7', type: 'Audio', question: 'Rød', answer: 'Stumt d', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a8', type: 'Audio', question: 'Hvid', answer: 'Stumt d', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a9', type: 'Audio', question: 'Plads', answer: 'Stumt d', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a10', type: 'Audio', question: 'Byld', answer: 'Stumt d', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a11', type: 'Audio', question: 'Fugl', answer: 'Stumt g', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a12', type: 'Audio', question: 'Snegl', answer: 'Stumt g', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a13', type: 'Audio', question: 'Vogn', answer: 'Stumt g', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a14', type: 'Audio', question: 'Løgn', answer: 'Stumt g', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a15', type: 'Audio', question: 'Døgn', answer: 'Stumt g', options: ['Stumt h', 'Stumt d', 'Stumt g'], instruction: 'Hvad er specielt?' },
    { id: 'da6-a16', type: 'Audio', question: 'Han løber hurtigt', answer: 'Hovedsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Sætningstype' },
    { id: 'da6-a17', type: 'Audio', question: 'Da han kom hjem', answer: 'Ledsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Sætningstype' },
    { id: 'da6-a18', type: 'Audio', question: 'Hvis det regner', answer: 'Ledsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Sætningstype' },
    { id: 'da6-a19', type: 'Audio', question: 'Jeg ser tv', answer: 'Hovedsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Sætningstype' },
    { id: 'da6-a20', type: 'Audio', question: 'Fordi mælk er godt', answer: 'Ledsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Sætningstype' },
    { id: 'da6-a21', type: 'Audio', question: 'Man', answer: 'Grundled', options: ['Grundled', 'Udsagnsled'], instruction: 'Sætningsdel' },
    { id: 'da6-a22', type: 'Audio', question: 'Løber', answer: 'Udsagnsled', options: ['Grundled', 'Udsagnsled'], instruction: 'Sætningsdel' },
    { id: 'da6-a23', type: 'Audio', question: 'Hunden gøer', answer: 'Hunden = Grundled', options: ['Grundled', 'Udsagnsled'], instruction: 'Find grundled' },
    { id: 'da6-a24', type: 'Audio', question: 'Bilen kørte', answer: 'kørte = Udsagnsled', options: ['Grundled', 'Udsagnsled'], instruction: 'Find udsagnsled' },
    { id: 'da6-a25', type: 'Audio', question: 'Solen skinner', answer: 'Solen = Grundled', options: ['Grundled', 'Udsagnsled'], instruction: 'Find grundled' },
    { id: 'da6-a26', type: 'Audio', question: 'Enlig', answer: 'Uden h', options: ['Stumt h', 'Uden h'], instruction: 'Stavning' },
    { id: 'da6-a27', type: 'Audio', question: 'Hvert', answer: 'Stumt h', options: ['Stumt h', 'Uden h'], instruction: 'Stavning' },
    { id: 'da6-a28', type: 'Audio', question: 'Hverken', answer: 'Stumt h', options: ['Stumt h', 'Uden h'], instruction: 'Stavning' },
    { id: 'da6-a29', type: 'Audio', question: 'Vilkår', answer: 'Uden h', options: ['Stumt h', 'Uden h'], instruction: 'Stavning' },
    { id: 'da6-a30', type: 'Audio', question: 'Værk', answer: 'Uden h', options: ['Stumt h', 'Uden h'], instruction: 'Stavning' },
    { id: 'da6-a31', type: 'Audio', question: 'Køre', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da6-a32', type: 'Audio', question: 'Kørsel', answer: 'Navneord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da6-a33', type: 'Audio', question: 'Spise', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da6-a34', type: 'Audio', question: 'Spisebord', answer: 'Navneord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da6-a35', type: 'Audio', question: 'Læse', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da6-a36', type: 'Audio', question: 'Læselyst', answer: 'Navneord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da6-a37', type: 'Audio', question: 'Skrive', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da6-a38', type: 'Audio', question: 'Skrivemaskine', answer: 'Navneord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da6-a39', type: 'Audio', question: 'Hoppe', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da6-a40', type: 'Audio', question: 'Hop', answer: 'Navneord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da6-a41', type: 'Audio', question: 'Hvilken farve har bilen?', answer: 'Spørgende', options: ['Spørgende', 'Fortællende'], instruction: 'Sætningstype' },
    { id: 'da6-a42', type: 'Audio', question: 'Bilen er blå.', answer: 'Fortællende', options: ['Spørgende', 'Fortællende'], instruction: 'Sætningstype' },
    { id: 'da6-a43', type: 'Audio', question: 'Hvor bor du?', answer: 'Spørgende', options: ['Spørgende', 'Fortællende'], instruction: 'Sætningstype' },
    { id: 'da6-a44', type: 'Audio', question: 'Jeg bor i Aarhus.', answer: 'Fortællende', options: ['Spørgende', 'Fortællende'], instruction: 'Sætningstype' },
    { id: 'da6-a45', type: 'Audio', question: 'Hvad laver du?', answer: 'Spørgende', options: ['Spørgende', 'Fortællende'], instruction: 'Sætningstype' },
    { id: 'da6-a46', type: 'Audio', question: 'Jeg læser.', answer: 'Fortællende', options: ['Spørgende', 'Fortællende'], instruction: 'Sætningstype' },
    { id: 'da6-a47', type: 'Audio', question: 'Hvornår kommer du?', answer: 'Spørgende', options: ['Spørgende', 'Fortællende'], instruction: 'Sætningstype' },
    { id: 'da6-a48', type: 'Audio', question: 'Jeg kommer nu.', answer: 'Fortællende', options: ['Spørgende', 'Fortællende'], instruction: 'Sætningstype' },
    { id: 'da6-a49', type: 'Audio', question: 'Hvem vandt?', answer: 'Spørgende', options: ['Spørgende', 'Fortællende'], instruction: 'Sætningstype' },
    { id: 'da6-a50', type: 'Audio', question: 'Vi vandt alle sammen.', answer: 'Fortællende', options: ['Spørgende', 'Fortællende'], instruction: 'Sætningstype' },
    { id: 'da6-a51', type: 'Audio', question: 'Tillykke!', answer: 'Udråb', options: ['Fortællende', 'Udråb'], instruction: 'Sætningstype' },
  ],
  7: [
    { id: 'da7-a1', type: 'Audio', question: 'Maden spises', answer: 'Passiv', options: ['Aktiv', 'Passiv'], instruction: 'Aktiv eller passiv?' },
    { id: 'da7-a2', type: 'Audio', question: 'Jeg spiser maden', answer: 'Aktiv', options: ['Aktiv', 'Passiv'], instruction: 'Aktiv eller passiv?' },
    { id: 'da7-a3', type: 'Audio', question: 'Bogen læses', answer: 'Passiv', options: ['Aktiv', 'Passiv'], instruction: 'Aktiv eller passiv?' },
    { id: 'da7-a4', type: 'Audio', question: 'Han læser bogen', answer: 'Aktiv', options: ['Aktiv', 'Passiv'], instruction: 'Aktiv eller passiv?' },
    { id: 'da7-a5', type: 'Audio', question: 'Døren åbnes', answer: 'Passiv', options: ['Aktiv', 'Passiv'], instruction: 'Aktiv eller passiv?' },
    { id: 'da7-a6', type: 'Audio', question: 'Hun åbner døren', answer: 'Aktiv', options: ['Aktiv', 'Passiv'], instruction: 'Aktiv eller passiv?' },
    { id: 'da7-a7', type: 'Audio', question: 'Bilen køres', answer: 'Passiv', options: ['Aktiv', 'Passiv'], instruction: 'Aktiv eller passiv?' },
    { id: 'da7-a8', type: 'Audio', question: 'De kører bilen', answer: 'Aktiv', options: ['Aktiv', 'Passiv'], instruction: 'Aktiv eller passiv?' },
    { id: 'da7-a9', type: 'Audio', question: 'Sangen synges', answer: 'Passiv', options: ['Aktiv', 'Passiv'], instruction: 'Aktiv eller passiv?' },
    { id: 'da7-a10', type: 'Audio', question: 'Vi synger sangen', answer: 'Aktiv', options: ['Aktiv', 'Passiv'], instruction: 'Aktiv eller passiv?' },
    { id: 'da7-a11', type: 'Audio', question: 'Chauffør', answer: 'Låneord', options: ['Dansk ord', 'Låneord'], instruction: 'Oprindelse' },
    { id: 'da7-a12', type: 'Audio', question: 'Computer', answer: 'Låneord', options: ['Dansk ord', 'Låneord'], instruction: 'Oprindelse' },
    { id: 'da7-a13', type: 'Audio', question: 'Bord', answer: 'Dansk ord', options: ['Dansk ord', 'Låneord'], instruction: 'Oprindelse' },
    { id: 'da7-a14', type: 'Audio', question: 'Hus', answer: 'Dansk ord', options: ['Dansk ord', 'Låneord'], instruction: 'Oprindelse' },
    { id: 'da7-a15', type: 'Audio', question: 'Station', answer: 'Låneord', options: ['Dansk ord', 'Låneord'], instruction: 'Oprindelse' },
    { id: 'da7-a16', type: 'Audio', question: 'Skole', answer: 'Låneord', options: ['Dansk ord', 'Låneord'], instruction: 'Oprindelse' },
    { id: 'da7-a17', type: 'Audio', question: 'Mad', answer: 'Dansk ord', options: ['Dansk ord', 'Låneord'], instruction: 'Oprindelse' },
    { id: 'da7-a18', type: 'Audio', question: 'Telefon', answer: 'Låneord', options: ['Dansk ord', 'Låneord'], instruction: 'Oprindelse' },
    { id: 'da7-a19', type: 'Audio', question: 'Vindue', answer: 'Låneord', options: ['Dansk ord', 'Låneord'], instruction: 'Oprindelse' },
    { id: 'da7-a20', type: 'Audio', question: 'Skov', answer: 'Dansk ord', options: ['Dansk ord', 'Låneord'], instruction: 'Oprindelse' },
    { id: 'da7-a21', type: 'Audio', question: 'At bringe - bragte - bragt', answer: 'Uregelmæssig', options: ['Regelmæssig', 'Uregelmæssig'], instruction: 'Bøjning' },
    { id: 'da7-a22', type: 'Audio', question: 'At hoppe - hoppede - hoppet', answer: 'Regelmæssig', options: ['Regelmæssig', 'Uregelmæssig'], instruction: 'Bøjning' },
    { id: 'da7-a23', type: 'Audio', question: 'At gå - gik - gået', answer: 'Uregelmæssig', options: ['Regelmæssig', 'Uregelmæssig'], instruction: 'Bøjning' },
    { id: 'da7-a24', type: 'Audio', question: 'At løbe - løb - løbet', answer: 'Uregelmæssig', options: ['Regelmæssig', 'Uregelmæssig'], instruction: 'Bøjning' },
    { id: 'da7-a25', type: 'Audio', question: 'At smile - smilede - smilet', answer: 'Regelmæssig', options: ['Regelmæssig', 'Uregelmæssig'], instruction: 'Bøjning' },
    { id: 'da7-a26', type: 'Audio', question: 'At synge - sang - sunget', answer: 'Uregelmæssig', options: ['Regelmæssig', 'Uregelmæssig'], instruction: 'Bøjning' },
    { id: 'da7-a27', type: 'Audio', question: 'At danse - dansede - danset', answer: 'Regelmæssig', options: ['Regelmæssig', 'Uregelmæssig'], instruction: 'Bøjning' },
    { id: 'da7-a28', type: 'Audio', question: 'At se - så - set', answer: 'Uregelmæssig', options: ['Regelmæssig', 'Uregelmæssig'], instruction: 'Bøjning' },
    { id: 'da7-a29', type: 'Audio', question: 'At male - malede - malet', answer: 'Regelmæssig', options: ['Regelmæssig', 'Uregelmæssig'], instruction: 'Bøjning' },
    { id: 'da7-a30', type: 'Audio', question: 'At bære - bar - båret', answer: 'Uregelmæssig', options: ['Regelmæssig', 'Uregelmæssig'], instruction: 'Bøjning' },
    { id: 'da7-a31', type: 'Audio', question: 'Demokrati', answer: 'Navneord', options: ['Navneord', 'Tillægsord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da7-a32', type: 'Audio', question: 'Demokratisk', answer: 'Tillægsord', options: ['Navneord', 'Tillægsord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da7-a33', type: 'Audio', question: 'Frihed', answer: 'Navneord', options: ['Navneord', 'Tillægsord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da7-a34', type: 'Audio', question: 'Fri', answer: 'Tillægsord', options: ['Navneord', 'Tillægsord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da7-a35', type: 'Audio', question: 'Ansvar', answer: 'Navneord', options: ['Navneord', 'Tillægsord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da7-a36', type: 'Audio', question: 'Ansvarlig', answer: 'Tillægsord', options: ['Navneord', 'Tillægsord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da7-a37', type: 'Audio', question: 'Mulighed', answer: 'Navneord', options: ['Navneord', 'Tillægsord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da7-a38', type: 'Audio', question: 'Mulig', answer: 'Tillægsord', options: ['Navneord', 'Tillægsord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da7-a39', type: 'Audio', question: 'Virkelighed', answer: 'Navneord', options: ['Navneord', 'Tillægsord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da7-a40', type: 'Audio', question: 'Virkelig', answer: 'Tillægsord', options: ['Navneord', 'Tillægsord', 'Udsagnsord'], instruction: 'Ordklasse' },
    { id: 'da7-a41', type: 'Audio', question: 'Jeg spiser mad, og han drikker vand.', answer: 'Sammensat sætning', options: ['Enkel sætning', 'Sammensat sætning'], instruction: 'Type' },
    { id: 'da7-a42', type: 'Audio', question: 'Hunden løber.', answer: 'Enkel sætning', options: ['Enkel sætning', 'Sammensat sætning'], instruction: 'Type' },
    { id: 'da7-a43', type: 'Audio', question: 'Da det blev lyst, stod jeg op.', answer: 'Sammensat sætning', options: ['Enkel sætning', 'Sammensat sætning'], instruction: 'Type' },
    { id: 'da7-a44', type: 'Audio', question: 'Solen skinner altid.', answer: 'Enkel sætning', options: ['Enkel sætning', 'Sammensat sætning'], instruction: 'Type' },
    { id: 'da7-a45', type: 'Audio', question: 'Hvis du vinder, bliver jeg glad.', answer: 'Sammensat sætning', options: ['Enkel sætning', 'Sammensat sætning'], instruction: 'Type' },
    { id: 'da7-a46', type: 'Audio', question: 'Vi vandt kampen i går.', answer: 'Enkel sætning', options: ['Enkel sætning', 'Sammensat sætning'], instruction: 'Type' },
    { id: 'da7-a47', type: 'Audio', question: 'Han sagde, at han var træt.', answer: 'Sammensat sætning', options: ['Enkel sætning', 'Sammensat sætning'], instruction: 'Type' },
    { id: 'da7-a48', type: 'Audio', question: 'Hun smiler pænt.', answer: 'Enkel sætning', options: ['Enkel sætning', 'Sammensat sætning'], instruction: 'Type' },
    { id: 'da7-a49', type: 'Audio', question: 'Selvom det regner, går vi tur.', answer: 'Sammensat sætning', options: ['Enkel sætning', 'Sammensat sætning'], instruction: 'Type' },
    { id: 'da7-a50', type: 'Audio', question: 'Huset er meget gammelt.', answer: 'Enkel sætning', options: ['Enkel sætning', 'Sammensat sætning'], instruction: 'Type' },
    { id: 'da7-a51', type: 'Audio', question: 'Færdig!', answer: 'Udråb', options: ['Enkel sætning', 'Udråb'], instruction: 'Type' },
  ],
  8: [
    { id: 'da8-a1', type: 'Audio', question: 'Hendes øjne var som stjerner', answer: 'Simile', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Sprogligt billede' },
    { id: 'da8-a2', type: 'Audio', question: 'Du er min klippe', answer: 'Metafor', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Sprogligt billede' },
    { id: 'da8-a3', type: 'Audio', question: 'Vinden sang i træerne', answer: 'Besjæling', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Sprogligt billede' },
    { id: 'da8-a4', type: 'Audio', question: 'Hjertet bankede som en tromme', answer: 'Simile', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Sprogligt billede' },
    { id: 'da8-a5', type: 'Audio', question: 'Livet er en rejse', answer: 'Metafor', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Sprogligt billede' },
    { id: 'da8-a6', type: 'Audio', question: 'Væggene har ører', answer: 'Besjæling', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Sprogligt billede' },
    { id: 'da8-a7', type: 'Audio', question: 'Han er en ræv', answer: 'Metafor', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Sprogligt billede' },
    { id: 'da8-a8', type: 'Audio', question: 'Blød som smør', answer: 'Simile', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Sprogligt billede' },
    { id: 'da8-a9', type: 'Audio', question: 'Solen smilede til os', answer: 'Besjæling', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Sprogligt billede' },
    { id: 'da8-a10', type: 'Audio', question: 'Tiden flyver', answer: 'Metafor', options: ['Simile', 'Metafor', 'Besjæling'], instruction: 'Sprogligt billede' },
    { id: 'da8-a11', type: 'Audio', question: 'Eksistens', answer: 'Latin', options: ['Latin', 'Græsk', 'Nordisk'], instruction: 'Oprindelse' },
    { id: 'da8-a12', type: 'Audio', question: 'Biologi', answer: 'Græsk', options: ['Latin', 'Græsk', 'Nordisk'], instruction: 'Oprindelse' },
    { id: 'da8-a13', type: 'Audio', question: 'Odin', answer: 'Nordisk', options: ['Latin', 'Græsk', 'Nordisk'], instruction: 'Oprindelse' },
    { id: 'da8-a14', type: 'Audio', question: 'Natur', answer: 'Latin', options: ['Latin', 'Græsk', 'Nordisk'], instruction: 'Oprindelse' },
    { id: 'da8-a15', type: 'Audio', question: 'Filosofi', answer: 'Græsk', options: ['Latin', 'Græsk', 'Nordisk'], instruction: 'Oprindelse' },
    { id: 'da8-a16', type: 'Audio', question: 'Viking', answer: 'Nordisk', options: ['Latin', 'Græsk', 'Nordisk'], instruction: 'Oprindelse' },
    { id: 'da8-a17', type: 'Audio', question: 'Kultur', answer: 'Latin', options: ['Latin', 'Græsk', 'Nordisk'], instruction: 'Oprindelse' },
    { id: 'da8-a18', type: 'Audio', question: 'Logik', answer: 'Græsk', options: ['Latin', 'Græsk', 'Nordisk'], instruction: 'Oprindelse' },
    { id: 'da8-a19', type: 'Audio', question: 'Runer', answer: 'Nordisk', options: ['Latin', 'Græsk', 'Nordisk'], instruction: 'Oprindelse' },
    { id: 'da8-a20', type: 'Audio', question: 'Sprog', answer: 'Nordisk', options: ['Latin', 'Græsk', 'Nordisk'], instruction: 'Oprindelse' },
    { id: 'da8-a21', type: 'Audio', question: 'Analyse', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da8-a22', type: 'Audio', question: 'Analysere', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da8-a23', type: 'Audio', question: 'Analytisk', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da8-a24', type: 'Audio', question: 'Konstruktion', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da8-a25', type: 'Audio', question: 'Konstruere', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da8-a26', type: 'Audio', question: 'Konstruktiv', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da8-a27', type: 'Audio', question: 'Definition', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da8-a28', type: 'Audio', question: 'Definere', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da8-a29', type: 'Audio', question: 'Definitiv', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da8-a30', type: 'Audio', question: 'Abstrakt', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Ordklasse' },
    { id: 'da8-a31', type: 'Audio', question: 'Fordi han var træt', answer: 'Ledsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Type' },
    { id: 'da8-a32', type: 'Audio', question: 'Han gik i seng', answer: 'Hovedsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Type' },
    { id: 'da8-a33', type: 'Audio', question: 'Da solen stod op', answer: 'Ledsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Type' },
    { id: 'da8-a34', type: 'Audio', question: 'Fuglene begyndte at synge', answer: 'Hovedsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Type' },
    { id: 'da8-a35', type: 'Audio', question: 'Hvis du vinder', answer: 'Ledsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Type' },
    { id: 'da8-a36', type: 'Audio', question: 'Bliver du glad', answer: 'Hovedsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Type' },
    { id: 'da8-a37', type: 'Audio', question: 'Selvom det sneer', answer: 'Ledsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Type' },
    { id: 'da8-a38', type: 'Audio', question: 'Går vi i skole', answer: 'Hovedsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Type' },
    { id: 'da8-a39', type: 'Audio', question: 'Inden vi spiser', answer: 'Ledsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Type' },
    { id: 'da8-a40', type: 'Audio', question: 'Skal vi vaske hænder', answer: 'Hovedsætning', options: ['Hovedsætning', 'Ledsætning'], instruction: 'Type' },
    { id: 'da8-a41', type: 'Audio', question: 'Konjunktion', answer: 'Bindeord', options: ['Bindeord', 'Biord', 'Stedord'], instruction: 'Latinsk betegnelse' },
    { id: 'da8-a42', type: 'Audio', question: 'Adverbium', answer: 'Biord', options: ['Bindeord', 'Biord', 'Stedord'], instruction: 'Latinsk betegnelse' },
    { id: 'da8-a43', type: 'Audio', question: 'Pronomen', answer: 'Stedord', options: ['Bindeord', 'Biord', 'Stedord'], instruction: 'Latinsk betegnelse' },
    { id: 'da8-a44', type: 'Audio', question: 'Substantiv', answer: 'Navneord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Latinsk betegnelse' },
    { id: 'da8-a45', type: 'Audio', question: 'Verbum', answer: 'Udsagnsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Latinsk betegnelse' },
    { id: 'da8-a46', type: 'Audio', question: 'Adjektiv', answer: 'Tillægsord', options: ['Navneord', 'Udsagnsord', 'Tillægsord'], instruction: 'Latinsk betegnelse' },
    { id: 'da8-a47', type: 'Audio', question: 'Præposition', answer: 'Forholdsord', options: ['Forholdsord', 'Kendeord', 'Talord'], instruction: 'Latinsk betegnelse' },
    { id: 'da8-a48', type: 'Audio', question: 'Artikel', answer: 'Kendeord', options: ['Forholdsord', 'Kendeord', 'Talord'], instruction: 'Latinsk betegnelse' },
    { id: 'da8-a49', type: 'Audio', question: 'Numerale', answer: 'Talord', options: ['Forholdsord', 'Kendeord', 'Talord'], instruction: 'Latinsk betegnelse' },
    { id: 'da8-a50', type: 'Audio', question: 'Interjektion', answer: 'Udråbsord', options: ['Udråbsord', 'Bindeord', 'Biord'], instruction: 'Latinsk betegnelse' },
    { id: 'da8-a51', type: 'Audio', question: 'Verbalform', answer: 'Udsagnsled', options: ['Udsagnsled', 'Grundled'], instruction: 'Sætningsdel' },
  ],
  9: [
    { id: 'da9-a1', type: 'Audio', question: 'Ambivalent', answer: 'Splittet', options: ['Splittet', 'Bestemt', 'Glad'], instruction: 'Hvad betyder ordet?' },
    { id: 'da9-a2', type: 'Audio', question: 'Konsekvent', answer: 'Gennemført', options: ['Gennemført', 'Tilfældig', 'Sjov'], instruction: 'Hvad betyder ordet?' },
    { id: 'da9-a3', type: 'Audio', question: 'Implicit', answer: 'Underforstået', options: ['Underforstået', 'Tydelig', 'Mangler'], instruction: 'Hvad betyder ordet?' },
    { id: 'da9-a4', type: 'Audio', question: 'Eksplicit', answer: 'Tydelig', options: ['Tydelig', 'Skjult', 'Svær'], instruction: 'Hvad betyder ordet?' },
    { id: 'da9-a5', type: 'Audio', question: 'Pragmatisk', answer: 'Praktisk', options: ['Praktisk', 'Drømmende', 'Vred'], instruction: 'Hvad betyder ordet?' },
    { id: 'da9-a6', type: 'Audio', question: 'Subjektiv', answer: 'Personlig', options: ['Personlig', 'Saglig', 'Fælles'], instruction: 'Hvad betyder ordet?' },
    { id: 'da9-a7', type: 'Audio', question: 'Objektiv', answer: 'Saglig', options: ['Saglig', 'Personlig', 'Følsom'], instruction: 'Hvad betyder ordet?' },
    { id: 'da9-a8', type: 'Audio', question: 'Individuel', answer: 'Enkeltvis', options: ['Enkeltvis', 'Fælles', 'Mange'], instruction: 'Hvad betyder ordet?' },
    { id: 'da9-a9', type: 'Audio', question: 'Kollektiv', answer: 'Fælles', options: ['Fælles', 'Enlig', 'Lille'], instruction: 'Hvad betyder ordet?' },
    { id: 'da9-a10', type: 'Audio', question: 'Ironi', answer: 'Modsætning', options: ['Modsætning', 'Lighed', 'Alvor'], instruction: 'Hvad er kendetegnet?' },
    { id: 'da9-a11', type: 'Audio', question: 'Sarkasme', answer: 'Bidende ironi', options: ['Bidende ironi', 'Ros', 'Sjov'], instruction: 'Hvad er kendetegnet?' },
    { id: 'da9-a12', type: 'Audio', question: 'Satire', answer: 'Samfundskritik', options: ['Samfundskritik', 'Eventyr', 'Digte'], instruction: 'Hvad er kendetegnet?' },
    { id: 'da9-a13', type: 'Audio', question: 'Metafor', answer: 'Overført betydning', options: ['Overført betydning', 'Direkte tale', 'Rim'], instruction: 'Sprogligt begreb' },
    { id: 'da9-a14', type: 'Audio', question: 'Simile', answer: 'Sammenligning', options: ['Sammenligning', 'Modsætning', 'Rim'], instruction: 'Sprogligt begreb' },
    { id: 'da9-a15', type: 'Audio', question: 'Personifikation', answer: 'Begreb bliver levende', options: ['Begreb bliver levende', 'Dyr bliver levende', 'Ting bliver levende'], instruction: 'Sprogligt begreb' },
    { id: 'da9-a16', type: 'Audio', question: 'Besjæling', answer: 'Ting bliver levende', options: ['Ting bliver levende', 'Dyr bliver levende', 'Begreb bliver levende'], instruction: 'Sprogligt begreb' },
    { id: 'da9-a17', type: 'Audio', question: 'Alitteration', answer: 'Bogstavrim', options: ['Bogstavrim', 'Enderim', 'Midterrim'], instruction: 'Sprogligt begreb' },
    { id: 'da9-a18', type: 'Audio', question: 'Assonans', answer: 'Vokalrim', options: ['Vokalrim', 'Konsonantrim', 'Enderim'], instruction: 'Sprogligt begreb' },
    { id: 'da9-a19', type: 'Audio', question: 'Hyperbel', answer: 'Overdrivelse', options: ['Overdrivelse', 'Underdrivelse', 'Gentagelse'], instruction: 'Sprogligt begreb' },
    { id: 'da9-a20', type: 'Audio', question: 'Litotes', answer: 'Underdrivelse', options: ['Underdrivelse', 'Overdrivelse', 'Gentagelse'], instruction: 'Sprogligt begreb' },
    { id: 'da9-a21', type: 'Audio', question: 'At være eller ikke at være', answer: 'Shakespeare', options: ['Shakespeare', 'H.C. Andersen', 'Grundtvig'], instruction: 'Hvem sagde det?' },
    { id: 'da9-a22', type: 'Audio', question: 'At rejse er at leve', answer: 'H.C. Andersen', options: ['H.C. Andersen', 'Søren Kierkegaard', 'Karen Blixen'], instruction: 'Hvem sagde det?' },
    { id: 'da9-a23', type: 'Audio', question: 'Tænk selv', answer: 'Oplysningstiden', options: ['Oplysningstiden', 'Middelalderen', 'Nutiden'], instruction: 'Hvilken tid?' },
    { id: 'da9-a24', type: 'Audio', question: 'Jeg tænker, derfor er jeg', answer: 'Descartes', options: ['Descartes', 'Platon', 'Kant'], instruction: 'Hvem sagde det?' },
    { id: 'da9-a25', type: 'Audio', question: 'Gud er død', answer: 'Nietzsche', options: ['Nietzsche', 'Freud', 'Marx'], instruction: 'Hvem sagde det?' },
    { id: 'da9-a26', type: 'Audio', question: 'Alt er relativt', answer: 'Einstein', options: ['Einstein', 'Newton', 'Darwin'], instruction: 'Hvem sagde det?' },
    { id: 'da9-a27', type: 'Audio', question: 'Viden er magt', answer: 'Bacon', options: ['Bacon', 'Locke', 'Hume'], instruction: 'Hvem sagde det?' },
    { id: 'da9-a28', type: 'Audio', question: 'Lighed for loven', answer: 'Demokrati', options: ['Demokrati', 'Diktatur', 'Monarki'], instruction: 'Princip' },
    { id: 'da9-a29', type: 'Audio', question: 'Ytringsfrihed', answer: 'Menneskeret', options: ['Menneskeret', 'Pligt', 'Lovkrav'], instruction: 'Type' },
    { id: 'da9-a30', type: 'Audio', question: 'Tolerance', answer: 'Respekt', options: ['Respekt', 'Had', 'Frygt'], instruction: 'Hvad betyder det?' },
    { id: 'da9-a31', type: 'Audio', question: 'Etos', answer: 'Troværdighed', options: ['Troværdighed', 'Følelser', 'Logik'], instruction: 'Retorisk begreb' },
    { id: 'da9-a32', type: 'Audio', question: 'Patos', answer: 'Følelser', options: ['Følelser', 'Troværdighed', 'Logik'], instruction: 'Retorisk begreb' },
    { id: 'da9-a33', type: 'Audio', question: 'Logos', answer: 'Logik', options: ['Logik', 'Følelser', 'Troværdighed'], instruction: 'Retorisk begreb' },
    { id: 'da9-a34', type: 'Audio', question: 'Kairos', answer: 'Det rette øjeblik', options: ['Det rette øjeblik', 'Det forkerte sted', 'Den lange tale'], instruction: 'Retorisk begreb' },
    { id: 'da9-a35', type: 'Audio', question: 'Aptum', answer: 'Det passende', options: ['Det passende', 'Det vilde', 'Det korte'], instruction: 'Retorisk begreb' },
    { id: 'da9-a36', type: 'Audio', question: 'Inventio', answer: 'At finde stof', options: ['At finde stof', 'At skrive ned', 'At øve'], instruction: 'Retorisk fase' },
    { id: 'da9-a37', type: 'Audio', question: 'Dispositio', answer: 'At ordne stof', options: ['At ordne stof', 'At finde på', 'At tale højt'], instruction: 'Retorisk fase' },
    { id: 'da9-a38', type: 'Audio', question: 'Elocutio', answer: 'At formulere', options: ['At formulere', 'At huske', 'At lytte'], instruction: 'Retorisk fase' },
    { id: 'da9-a39', type: 'Audio', question: 'Memoria', answer: 'At huske', options: ['At huske', 'At glemme', 'At læse'], instruction: 'Retorisk fase' },
    { id: 'da9-a40', type: 'Audio', question: 'Actio', answer: 'At fremføre', options: ['At fremføre', 'At sidde stille', 'At skrive'], instruction: 'Retorisk fase' },
    { id: 'da9-a41', type: 'Audio', question: 'Dialekt', answer: 'Regionalt sprog', options: ['Regionalt sprog', 'Slang', 'Fagsprog'], instruction: 'Sproglig variant' },
    { id: 'da9-a42', type: 'Audio', question: 'Sociolekt', answer: 'Socialt sprog', options: ['Socialt sprog', 'Dialekt', 'Nationalsprog'], instruction: 'Sproglig variant' },
    { id: 'da9-a43', type: 'Audio', question: 'Multietnoлект', answer: 'Blandet sprog', options: ['Blandet sprog', 'Rent sprog', 'Gammelt sprog'], instruction: 'Sproglig variant' },
    { id: 'da9-a44', type: 'Audio', question: 'Slang', answer: 'Uformelt sprog', options: ['Uformelt sprog', 'Formelt sprog', 'Højtideligt sprog'], instruction: 'Sproglig variant' },
    { id: 'da9-a45', type: 'Audio', question: 'Jargon', answer: 'Indforstået sprog', options: ['Indforstået sprog', 'Alle forstår det', 'Børnesprog'], instruction: 'Sproglig variant' },
    { id: 'da9-a46', type: 'Audio', question: 'Arkaisme', answer: 'Gammelt ord', options: ['Gammelt ord', 'Nyt ord', 'Sjovt ord'], instruction: 'Sproglig variant' },
    { id: 'da9-a47', type: 'Audio', question: 'Neologisme', answer: 'Nyt ord', options: ['Nyt ord', 'Gammelt ord', 'Fremmedord'], instruction: 'Sproglig variant' },
    { id: 'da9-a48', type: 'Audio', question: 'Eufemisme', answer: 'Forskønnelse', options: ['Forskønnelse', 'Grovhed', 'Korthed'], instruction: 'Sproglig variant' },
    { id: 'da9-a49', type: 'Audio', question: 'Dysfemisme', answer: 'Grov omskrivning', options: ['Grov omskrivning', 'Pæn omskrivning', 'Ingen omskrivning'], instruction: 'Sproglig variant' },
    { id: 'da9-a50', type: 'Audio', question: 'Meta-sprog', answer: 'Sprog om sprog', options: ['Sprog om sprog', 'Sprog om mad', 'Sprog om sport'], instruction: 'Sproglig variant' },
    { id: 'da9-a51', type: 'Audio', question: 'Finale!', answer: 'Navneord', options: ['Navneord', 'Udsagnsord'], instruction: 'Ordklasse' },
  ],
};