/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const ENGELSK_AUDIO: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'en0-a1', type: 'Audio', question: 'Yellow', answer: 'Gul', options: ['Rød', 'Blå', 'Gul', 'Grøn'], instruction: 'Hvilken farve?' },
    { id: 'en0-a2', type: 'Audio', question: 'Blue', answer: 'Blå', options: ['Rød', 'Blå', 'Gul', 'Grøn'], instruction: 'Hvilken farve?' },
    { id: 'en0-a3', type: 'Audio', question: 'Red', answer: 'Rød', options: ['Rød', 'Blå', 'Gul', 'Grøn'], instruction: 'Hvilken farve?' },
    { id: 'en0-a4', type: 'Audio', question: 'Green', answer: 'Grøn', options: ['Rød', 'Blå', 'Gul', 'Grøn'], instruction: 'Hvilken farve?' },
    { id: 'en0-a5', type: 'Audio', question: 'Black', answer: 'Sort', options: ['Sort', 'Hvid', 'Grå'], instruction: 'Hvilken farve?' },
    { id: 'en0-a6', type: 'Audio', question: 'White', answer: 'Hvid', options: ['Sort', 'Hvid', 'Grå'], instruction: 'Hvilken farve?' },
    { id: 'en0-a7', type: 'Audio', question: 'One', answer: '1', options: ['1', '2', '3'], instruction: 'Tal' },
    { id: 'en0-a8', type: 'Audio', question: 'Two', answer: '2', options: ['1', '2', '3'], instruction: 'Tal' },
    { id: 'en0-a9', type: 'Audio', question: 'Three', answer: '3', options: ['1', '2', '3'], instruction: 'Tal' },
    { id: 'en0-a10', type: 'Audio', question: 'Four', answer: '4', options: ['4', '5', '6'], instruction: 'Tal' },
    { id: 'en0-a11', type: 'Audio', question: 'Five', answer: '5', options: ['4', '5', '6'], instruction: 'Tal' },
    { id: 'en0-a12', type: 'Audio', question: 'Six', answer: '6', options: ['4', '5', '6'], instruction: 'Tal' },
    { id: 'en0-a13', type: 'Audio', question: 'Seven', answer: '7', options: ['7', '8', '9'], instruction: 'Tal' },
    { id: 'en0-a14', type: 'Audio', question: 'Eight', answer: '8', options: ['7', '8', '9'], instruction: 'Tal' },
    { id: 'en0-a15', type: 'Audio', question: 'Nine', answer: '9', options: ['7', '8', '9'], instruction: 'Tal' },
    { id: 'en0-a16', type: 'Audio', question: 'Ten', answer: '10', options: ['8', '9', '10'], instruction: 'Tal' },
    { id: 'en0-a17', type: 'Audio', question: 'Dog', answer: 'Hund', options: ['Hund', 'Kat', 'Fugl'], instruction: 'Dyr' },
    { id: 'en0-a18', type: 'Audio', question: 'Cat', answer: 'Kat', options: ['Hund', 'Kat', 'Fugl'], instruction: 'Dyr' },
    { id: 'en0-a19', type: 'Audio', question: 'Bird', answer: 'Fugl', options: ['Hund', 'Kat', 'Fugl'], instruction: 'Dyr' },
    { id: 'en0-a20', type: 'Audio', question: 'Fish', answer: 'Fisk', options: ['Fisk', 'Slange', 'Mus'], instruction: 'Dyr' },
    { id: 'en0-a21', type: 'Audio', question: 'Mouse', answer: 'Mus', options: ['Fisk', 'Slange', 'Mus'], instruction: 'Dyr' },
    { id: 'en0-a22', type: 'Audio', question: 'Horse', answer: 'Hest', options: ['Hest', 'Ko', 'Gris'], instruction: 'Dyr' },
    { id: 'en0-a23', type: 'Audio', question: 'Cow', answer: 'Ko', options: ['Hest', 'Ko', 'Gris'], instruction: 'Dyr' },
    { id: 'en0-a24', type: 'Audio', question: 'Pig', answer: 'Gris', options: ['Hest', 'Ko', 'Gris'], instruction: 'Dyr' },
    { id: 'en0-a25', type: 'Audio', question: 'Apple', answer: 'Æble', options: ['Æble', 'Banan', 'Pære'], instruction: 'Frugt' },
    { id: 'en0-a26', type: 'Audio', question: 'Banana', answer: 'Banan', options: ['Æble', 'Banan', 'Pære'], instruction: 'Frugt' },
    { id: 'en0-a27', type: 'Audio', question: 'Pear', answer: 'Pære', options: ['Æble', 'Banan', 'Pære'], instruction: 'Frugt' },
    { id: 'en0-a28', type: 'Audio', question: 'Milk', answer: 'Mælk', options: ['Mælk', 'Vand', 'Juice'], instruction: 'Drik' },
    { id: 'en0-a29', type: 'Audio', question: 'Water', answer: 'Vand', options: ['Mælk', 'Vand', 'Juice'], instruction: 'Drik' },
    { id: 'en0-a30', type: 'Audio', question: 'Sun', answer: 'Sol', options: ['Sol', 'Måne', 'Sky'], instruction: 'Natur' },
    { id: 'en0-a31', type: 'Audio', question: 'Moon', answer: 'Måne', options: ['Sol', 'Måne', 'Sky'], instruction: 'Natur' },
    { id: 'en0-a32', type: 'Audio', question: 'Cloud', answer: 'Sky', options: ['Sol', 'Måne', 'Sky'], instruction: 'Natur' },
    { id: 'en0-a33', type: 'Audio', question: 'Boy', answer: 'Dreng', options: ['Dreng', 'Pige', 'Mand'], instruction: 'Menneske' },
    { id: 'en0-a34', type: 'Audio', question: 'Girl', answer: 'Pige', options: ['Dreng', 'Pige', 'Mand'], instruction: 'Menneske' },
    { id: 'en0-a35', type: 'Audio', question: 'Man', answer: 'Mand', options: ['Dreng', 'Pige', 'Mand'], instruction: 'Menneske' },
    { id: 'en0-a36', type: 'Audio', question: 'Woman', answer: 'Kvinde', options: ['Mand', 'Kvinde', 'Barn'], instruction: 'Menneske' },
    { id: 'en0-a37', type: 'Audio', question: 'Hello', answer: 'Hej', options: ['Hej', 'Farvel', 'Tak'], instruction: 'Hilsen' },
    { id: 'en0-a38', type: 'Audio', question: 'Goodbye', answer: 'Farvel', options: ['Hej', 'Farvel', 'Tak'], instruction: 'Hilsen' },
    { id: 'en0-a39', type: 'Audio', question: 'Yes', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Svar' },
    { id: 'en0-a40', type: 'Audio', question: 'No', answer: 'Nej', options: ['Ja', 'Nej'], instruction: 'Svar' },
    { id: 'en0-a41', type: 'Audio', question: 'Ball', answer: 'Bold', options: ['Bold', 'Dukke', 'Bil'], instruction: 'Legetøj' },
    { id: 'en0-a42', type: 'Audio', question: 'Car', answer: 'Bil', options: ['Bold', 'Dukke', 'Bil'], instruction: 'Legetøj' },
    { id: 'en0-a43', type: 'Audio', question: 'Book', answer: 'Bog', options: ['Bog', 'Pen', 'Taske'], instruction: 'Skole' },
    { id: 'en0-a44', type: 'Audio', question: 'Pen', answer: 'Pen', options: ['Bog', 'Pen', 'Taske'], instruction: 'Skole' },
    { id: 'en0-a45', type: 'Audio', question: 'House', answer: 'Hus', options: ['Hus', 'Have', 'Vej'], instruction: 'Hjem' },
    { id: 'en0-a46', type: 'Audio', question: 'Garden', answer: 'Have', options: ['Hus', 'Have', 'Vej'], instruction: 'Hjem' },
    { id: 'en0-a47', type: 'Audio', question: 'Big', answer: 'Stor', options: ['Stor', 'Lille'], instruction: 'Modsætning' },
    { id: 'en0-a48', type: 'Audio', question: 'Small', answer: 'Lille', options: ['Stor', 'Lille'], instruction: 'Modsætning' },
    { id: 'en0-a49', type: 'Audio', question: 'Happy', answer: 'Glad', options: ['Glad', 'Trist'], instruction: 'Humør' },
    { id: 'en0-a50', type: 'Audio', question: 'Sad', answer: 'Trist', options: ['Glad', 'Trist'], instruction: 'Humør' },
    { id: 'en0-a51', type: 'Audio', question: 'The end', answer: 'Slut', options: ['Start', 'Slut'], instruction: 'Ord' },
  ],
  1: [
    { id: 'en1-a1', type: 'Audio', question: 'Eleven', answer: '11', options: ['1', '11', '21'], instruction: 'Tal' },
    { id: 'en1-a2', type: 'Audio', question: 'Twelve', answer: '12', options: ['2', '12', '22'], instruction: 'Tal' },
    { id: 'en1-a3', type: 'Audio', question: 'Thirteen', answer: '13', options: ['3', '13', '23'], instruction: 'Tal' },
    { id: 'en1-a4', type: 'Audio', question: 'Fourteen', answer: '14', options: ['4', '14', '24'], instruction: 'Tal' },
    { id: 'en1-a5', type: 'Audio', question: 'Fifteen', answer: '15', options: ['5', '15', '25'], instruction: 'Tal' },
    { id: 'en1-a6', type: 'Audio', question: 'Sixteen', answer: '16', options: ['6', '16', '26'], instruction: 'Tal' },
    { id: 'en1-a7', type: 'Audio', question: 'Seventeen', answer: '17', options: ['7', '17', '27'], instruction: 'Tal' },
    { id: 'en1-a8', type: 'Audio', question: 'Eighteen', answer: '18', options: ['8', '18', '28'], instruction: 'Tal' },
    { id: 'en1-a9', type: 'Audio', question: 'Nineteen', answer: '19', options: ['9', '19', '29'], instruction: 'Tal' },
    { id: 'en1-a10', type: 'Audio', question: 'Twenty', answer: '20', options: ['2', '10', '20'], instruction: 'Tal' },
    { id: 'en1-a11', type: 'Audio', question: 'Monday', answer: 'Mandag', options: ['Mandag', 'Tirsdag', 'Onsdag'], instruction: 'Ugedag' },
    { id: 'en1-a12', type: 'Audio', question: 'Tuesday', answer: 'Tirsdag', options: ['Mandag', 'Tirsdag', 'Onsdag'], instruction: 'Ugedag' },
    { id: 'en1-a13', type: 'Audio', question: 'Wednesday', answer: 'Onsdag', options: ['Mandag', 'Tirsdag', 'Onsdag'], instruction: 'Ugedag' },
    { id: 'en1-a14', type: 'Audio', question: 'Thursday', answer: 'Torsdag', options: ['Torsdag', 'Fredag', 'Lørdag'], instruction: 'Ugedag' },
    { id: 'en1-a15', type: 'Audio', question: 'Friday', answer: 'Fredag', options: ['Torsdag', 'Fredag', 'Lørdag'], instruction: 'Ugedag' },
    { id: 'en1-a16', type: 'Audio', question: 'Saturday', answer: 'Lørdag', options: ['Torsdag', 'Fredag', 'Lørdag'], instruction: 'Ugedag' },
    { id: 'en1-a17', type: 'Audio', question: 'Sunday', answer: 'Søndag', options: ['Fredag', 'Lørdag', 'Søndag'], instruction: 'Ugedag' },
    { id: 'en1-a18', type: 'Audio', question: 'Father', answer: 'Far', options: ['Far', 'Mor', 'Bror'], instruction: 'Familie' },
    { id: 'en1-a19', type: 'Audio', question: 'Mother', answer: 'Mor', options: ['Far', 'Mor', 'Søster'], instruction: 'Familie' },
    { id: 'en1-a20', type: 'Audio', question: 'Brother', answer: 'Bror', options: ['Bror', 'Søster', 'Baby'], instruction: 'Familie' },
    { id: 'en1-a21', type: 'Audio', question: 'Sister', answer: 'Søster', options: ['Bror', 'Søster', 'Baby'], instruction: 'Familie' },
    { id: 'en1-a22', type: 'Audio', question: 'Baby', answer: 'Baby', options: ['Bror', 'Søster', 'Baby'], instruction: 'Familie' },
    { id: 'en1-a23', type: 'Audio', question: 'Shirt', answer: 'Skjorte', options: ['Skjorte', 'Bukser', 'Sko'], instruction: 'Tøj' },
    { id: 'en1-a24', type: 'Audio', question: 'Pants', answer: 'Bukser', options: ['Skjorte', 'Bukser', 'Sko'], instruction: 'Tøj' },
    { id: 'en1-a25', type: 'Audio', question: 'Shoes', answer: 'Sko', options: ['Skjorte', 'Bukser', 'Sko'], instruction: 'Tøj' },
    { id: 'en1-a26', type: 'Audio', question: 'Hat', answer: 'Hat', options: ['Hat', 'Jakke', 'Sokker'], instruction: 'Tøj' },
    { id: 'en1-a27', type: 'Audio', question: 'Jacket', answer: 'Jakke', options: ['Hat', 'Jakke', 'Sokker'], instruction: 'Tøj' },
    { id: 'en1-a28', type: 'Audio', question: 'Socks', answer: 'Sokker', options: ['Hat', 'Jakke', 'Sokker'], instruction: 'Tøj' },
    { id: 'en1-a29', type: 'Audio', question: 'Run', answer: 'Løbe', options: ['Løbe', 'Gå', 'Sidde'], instruction: 'Handling' },
    { id: 'en1-a30', type: 'Audio', question: 'Walk', answer: 'Gå', options: ['Løbe', 'Gå', 'Sidde'], instruction: 'Handling' },
    { id: 'en1-a31', type: 'Audio', question: 'Sit', answer: 'Sidde', options: ['Løbe', 'Gå', 'Sidde'], instruction: 'Handling' },
    { id: 'en1-a32', type: 'Audio', question: 'Stand', answer: 'Stå', options: ['Stå', 'Hop', 'Sov'], instruction: 'Handling' },
    { id: 'en1-a33', type: 'Audio', question: 'Jump', answer: 'Hop', options: ['Stå', 'Hop', 'Sov'], instruction: 'Handling' },
    { id: 'en1-a34', type: 'Audio', question: 'Sleep', answer: 'Sove', options: ['Stå', 'Hop', 'Sov'], instruction: 'Handling' },
    { id: 'en1-a35', type: 'Audio', question: 'Eat', answer: 'Spise', options: ['Spise', 'Drikke', 'Tale'], instruction: 'Handling' },
    { id: 'en1-a36', type: 'Audio', question: 'Drink', answer: 'Drikke', options: ['Spise', 'Drikke', 'Tale'], instruction: 'Handling' },
    { id: 'en1-a37', type: 'Audio', question: 'Talk', answer: 'Tale', options: ['Spise', 'Drikke', 'Tale'], instruction: 'Handling' },
    { id: 'en1-a38', type: 'Audio', question: 'Red apple', answer: 'Rødt æble', options: ['Rødt æble', 'Grønt æble'], instruction: 'Hvad hører du?' },
    { id: 'en1-a39', type: 'Audio', question: 'Small cat', answer: 'Lille kat', options: ['Stor kat', 'Lille kat'], instruction: 'Hvad hører du?' },
    { id: 'en1-a40', type: 'Audio', question: 'Blue car', answer: 'Blå bil', options: ['Gul bil', 'Blå bil'], instruction: 'Hvad hører du?' },
    { id: 'en1-a41', type: 'Audio', question: 'Big house', answer: 'Stort hus', options: ['Stort hus', 'Lille hus'], instruction: 'Hvad hører du?' },
    { id: 'en1-a42', type: 'Audio', question: 'Fast dog', answer: 'Hurtig hund', options: ['Hurtig hund', 'Langsom hund'], instruction: 'Hvad hører du?' },
    { id: 'en1-a43', type: 'Audio', question: 'Hot soup', answer: 'Varm suppe', options: ['Varm suppe', 'Kold suppe'], instruction: 'Hvad hører du?' },
    { id: 'en1-a44', type: 'Audio', question: 'Cold water', answer: 'Koldt vand', options: ['Varmt vand', 'Koldt vand'], instruction: 'Hvad hører du?' },
    { id: 'en1-a45', type: 'Audio', question: 'Old man', answer: 'Gammel mand', options: ['Ung mand', 'Gammel mand'], instruction: 'Hvad hører du?' },
    { id: 'en1-a46', type: 'Audio', question: 'Young girl', answer: 'Ung pige', options: ['Ung pige', 'Gammel pige'], instruction: 'Hvad hører du?' },
    { id: 'en1-a47', type: 'Audio', question: 'Long hair', answer: 'Langt hår', options: ['Kort hår', 'Langt hår'], instruction: 'Hvad hører du?' },
    { id: 'en1-a48', type: 'Audio', question: 'Short legs', answer: 'Korte ben', options: ['Lange ben', 'Korte ben'], instruction: 'Hvad hører du?' },
    { id: 'en1-a49', type: 'Audio', question: 'Heavy bag', answer: 'Tung taske', options: ['Let taske', 'Tung taske'], instruction: 'Hvad hører du?' },
    { id: 'en1-a50', type: 'Audio', question: 'Light ball', answer: 'Let bold', options: ['Tung bold', 'Let bold'], instruction: 'Hvad hører du?' },
    { id: 'en1-a51', type: 'Audio', question: 'Happy day', answer: 'Glad dag', options: ['Trist dag', 'Glad dag'], instruction: 'Hvad hører du?' },
  ],
  2: [
    { id: 'en2-a1', type: 'Audio', question: 'Head', answer: 'Hoved', options: ['Hoved', 'Hånd', 'Fod'], instruction: 'Krop' },
    { id: 'en2-a2', type: 'Audio', question: 'Hand', answer: 'Hånd', options: ['Hoved', 'Hånd', 'Fod'], instruction: 'Krop' },
    { id: 'en2-a3', type: 'Audio', question: 'Foot', answer: 'Fod', options: ['Hoved', 'Hånd', 'Fod'], instruction: 'Krop' },
    { id: 'en2-a4', type: 'Audio', question: 'Eye', answer: 'Øje', options: ['Øje', 'Øre', 'Næse'], instruction: 'Krop' },
    { id: 'en2-a5', type: 'Audio', question: 'Ear', answer: 'Øre', options: ['Øje', 'Øre', 'Næse'], instruction: 'Krop' },
    { id: 'en2-a6', type: 'Audio', question: 'Nose', answer: 'Næse', options: ['Øje', 'Øre', 'Næse'], instruction: 'Krop' },
    { id: 'en2-a7', type: 'Audio', question: 'Mouth', answer: 'Mund', options: ['Mund', 'Tænder', 'Tunge'], instruction: 'Krop' },
    { id: 'en2-a8', type: 'Audio', question: 'Teeth', answer: 'Tænder', options: ['Mund', 'Tænder', 'Tunge'], instruction: 'Krop' },
    { id: 'en2-a9', type: 'Audio', question: 'Arm', answer: 'Arm', options: ['Arm', 'Ben', 'Knæ'], instruction: 'Krop' },
    { id: 'en2-a10', type: 'Audio', question: 'Leg', answer: 'Ben', options: ['Arm', 'Ben', 'Knæ'], instruction: 'Krop' },
    { id: 'en2-a11', type: 'Audio', question: 'Knee', answer: 'Knæ', options: ['Arm', 'Ben', 'Knæ'], instruction: 'Krop' },
    { id: 'en2-a12', type: 'Audio', question: 'Rain', answer: 'Regn', options: ['Sol', 'Regn', 'Sne'], instruction: 'Vejr' },
    { id: 'en2-a13', type: 'Audio', question: 'Snow', answer: 'Sne', options: ['Sol', 'Regn', 'Sne'], instruction: 'Vejr' },
    { id: 'en2-a14', type: 'Audio', question: 'Wind', answer: 'Vind', options: ['Vejr', 'Vind', 'Varmt'], instruction: 'Vejr' },
    { id: 'en2-a15', type: 'Audio', question: 'Thunder', answer: 'Torden', options: ['Torden', 'Lyn', 'Storm'], instruction: 'Vejr' },
    { id: 'en2-a16', type: 'Audio', question: 'One o\'clock', answer: '1:00', options: ['1:00', '2:00', '3:00'], instruction: 'Klokken' },
    { id: 'en2-a17', type: 'Audio', question: 'Half past two', answer: '2:30', options: ['2:00', '2:30', '3:00'], instruction: 'Klokken' },
    { id: 'en2-a18', type: 'Audio', question: 'Quarter to four', answer: '3:45', options: ['3:45', '4:00', '4:15'], instruction: 'Klokken' },
    { id: 'en2-a19', type: 'Audio', question: 'One dog', answer: 'Singular', options: ['Singular', 'Plural'], instruction: 'Grammar' },
    { id: 'en2-a20', type: 'Audio', question: 'Two dogs', answer: 'Plural', options: ['Singular', 'Plural'], instruction: 'Grammar' },
    { id: 'en2-a21', type: 'Audio', question: 'Many trees', answer: 'Plural', options: ['Singular', 'Plural'], instruction: 'Grammar' },
    { id: 'en2-a22', type: 'Audio', question: 'One box', answer: 'Singular', options: ['Singular', 'Plural'], instruction: 'Grammar' },
    { id: 'en2-a23', type: 'Audio', question: 'Some birds', answer: 'Plural', options: ['Singular', 'Plural'], instruction: 'Grammar' },
    { id: 'en2-a24', type: 'Audio', question: 'Kitchen', answer: 'Køkken', options: ['Stue', 'Køkken', 'Bad'], instruction: 'Rum' },
    { id: 'en2-a25', type: 'Audio', question: 'Living room', answer: 'Stue', options: ['Stue', 'Køkken', 'Bad'], instruction: 'Rum' },
    { id: 'en2-a26', type: 'Audio', question: 'Bedroom', answer: 'Soveværelse', options: ['Stue', 'Køkken', 'Soveværelse'], instruction: 'Rum' },
    { id: 'en2-a27', type: 'Audio', question: 'Bathroom', answer: 'Badeværelse', options: ['Stue', 'Bad', 'Badeværelse'], instruction: 'Rum' },
    { id: 'en2-a28', type: 'Audio', question: 'School bag', answer: 'Skoletaske', options: ['Taske', 'Skoletaske'], instruction: 'Ord' },
    { id: 'en2-a29', type: 'Audio', question: 'Lunch box', answer: 'Madpakke', options: ['Mad', 'Madpakke'], instruction: 'Ord' },
    { id: 'en2-a30', type: 'Audio', question: 'Pencil case', answer: 'Penalhus', options: ['Blyant', 'Penalhus'], instruction: 'Ord' },
    { id: 'en2-a31', type: 'Audio', question: 'Bread', answer: 'Brød', options: ['Brød', 'Ost', 'Mælk'], instruction: 'Mad' },
    { id: 'en2-a32', type: 'Audio', question: 'Cheese', answer: 'Ost', options: ['Brød', 'Ost', 'Mælk'], instruction: 'Mad' },
    { id: 'en2-a33', type: 'Audio', question: 'Butter', answer: 'Smør', options: ['Smør', 'Salt', 'Sukker'], instruction: 'Mad' },
    { id: 'en2-a34', type: 'Audio', question: 'Fruit', answer: 'Frugt', options: ['Frugt', 'Kød', 'Brød'], instruction: 'Mad' },
    { id: 'en2-a35', type: 'Audio', question: 'Meat', answer: 'Kød', options: ['Frugt', 'Kød', 'Brød'], instruction: 'Mad' },
    { id: 'en2-a36', type: 'Audio', question: 'Doctor', answer: 'Læge', options: ['Læge', 'Lærer', 'Politi'], instruction: 'Job' },
    { id: 'en2-a37', type: 'Audio', question: 'Teacher', answer: 'Lærer', options: ['Læge', 'Lærer', 'Politi'], instruction: 'Job' },
    { id: 'en2-a38', type: 'Audio', question: 'Policeman', answer: 'Politibetjent', options: ['Læge', 'Lærer', 'Politibetjent'], instruction: 'Job' },
    { id: 'en2-a39', type: 'Audio', question: 'Farmer', answer: 'Landmand', options: ['Landmand', 'Kok', 'Skovly'], instruction: 'Job' },
    { id: 'en2-a40', type: 'Audio', question: 'Chef', answer: 'Kok', options: ['Landmand', 'Kok', 'Skovly'], instruction: 'Job' },
    { id: 'en2-a41', type: 'Audio', question: 'The ball is on the table', answer: 'På', options: ['På', 'Under', 'I'], instruction: 'Find forholdsord' },
    { id: 'en2-a42', type: 'Audio', question: 'The cat is under the bed', answer: 'Under', options: ['På', 'Under', 'I'], instruction: 'Find forholdsord' },
    { id: 'en2-a43', type: 'Audio', question: 'The pen is in the box', answer: 'I', options: ['På', 'Under', 'I'], instruction: 'Find forholdsord' },
    { id: 'en2-a44', type: 'Audio', question: 'Behind', answer: 'Bagved', options: ['Foran', 'Bagved'], instruction: 'Hvad betyder det?' },
    { id: 'en2-a45', type: 'Audio', question: 'Between', answer: 'Imellem', options: ['Imellem', 'Ved siden af'], instruction: 'Hvad betyder det?' },
    { id: 'en2-a46', type: 'Audio', question: 'Next to', answer: 'Ved siden af', options: ['Imellem', 'Ved siden af'], instruction: 'Hvad betyder det?' },
    { id: 'en2-a47', type: 'Audio', question: 'Listen carefully', answer: 'Hør efter', options: ['Hør efter', 'Se efter'], instruction: 'Hvad betyder det?' },
    { id: 'en2-a48', type: 'Audio', question: 'Look at me', answer: 'Se på mig', options: ['Se på mig', 'Kom til mig'], instruction: 'Hvad betyder det?' },
    { id: 'en2-a49', type: 'Audio', question: 'Open your book', answer: 'Åben din bog', options: ['Åben din bog', 'Luk din bog'], instruction: 'Hvad betyder det?' },
    { id: 'en2-a50', type: 'Audio', question: 'Close the door', answer: 'Luk døren', options: ['Åben døren', 'Luk døren'], instruction: 'Hvad betyder det?' },
    { id: 'en2-a51', type: 'Audio', question: 'Ready, set, go!', answer: 'Klar, parat, start!', options: ['Slut', 'Start'], instruction: 'Hvad betyder det?' },
  ],
  3: [
    { id: 'en3-a1', type: 'Audio', question: 'I am happy', answer: 'Glad', options: ['Glad', 'Trist', 'Sulten'], instruction: 'Hvad betyder det?' },
    { id: 'en3-a2', type: 'Audio', question: 'She is tired', answer: 'Træt', options: ['Træt', 'Sur', 'Varm'], instruction: 'Hvad betyder det?' },
    { id: 'en3-a3', type: 'Audio', question: 'We are hungry', answer: 'Sultne', options: ['Tørstige', 'Sultne', 'Kolde'], instruction: 'Hvad betyder det?' },
    { id: 'en3-a4', type: 'Audio', question: 'He is angry', answer: 'Vred', options: ['Vred', 'Glad', 'Bange'], instruction: 'Hvad betyder det?' },
    { id: 'en3-a5', type: 'Audio', question: 'They are scared', answer: 'Bange', options: ['Bange', 'Stolte', 'Sjove'], instruction: 'Hvad betyder det?' },
    { id: 'en3-a6', type: 'Audio', question: 'Football', answer: 'Fodbold', options: ['Fodbold', 'Håndbold', 'Tennis'], instruction: 'Sport' },
    { id: 'en3-a7', type: 'Audio', question: 'Swimming', answer: 'Svømning', options: ['Svømning', 'Cykling', 'Løb'], instruction: 'Sport' },
    { id: 'en3-a8', type: 'Audio', question: 'Cycling', answer: 'Cykling', options: ['Svømning', 'Cykling', 'Løb'], instruction: 'Sport' },
    { id: 'en3-a9', type: 'Audio', question: 'Tennis', answer: 'Tennis', options: ['Fodbold', 'Tennis', 'Basket'], instruction: 'Sport' },
    { id: 'en3-a10', type: 'Audio', question: 'Basketball', answer: 'Basketball', options: ['Fodbold', 'Tennis', 'Basketball'], instruction: 'Sport' },
    { id: 'en3-a11', type: 'Audio', question: 'Train', answer: 'Tog', options: ['Tog', 'Bil', 'Fly'], instruction: 'Transport' },
    { id: 'en3-a12', type: 'Audio', question: 'Plane', answer: 'Fly', options: ['Tog', 'Bil', 'Fly'], instruction: 'Transport' },
    { id: 'en3-a13', type: 'Audio', question: 'Boat', answer: 'Båd', options: ['Båd', 'Cykel', 'Bus'], instruction: 'Transport' },
    { id: 'en3-a14', type: 'Audio', question: 'Bike', answer: 'Cykel', options: ['Båd', 'Cykel', 'Bus'], instruction: 'Transport' },
    { id: 'en3-a15', type: 'Audio', question: 'Bus', answer: 'Bus', options: ['Båd', 'Cykel', 'Bus'], instruction: 'Transport' },
    { id: 'en3-a16', type: 'Audio', question: 'Bigger', answer: 'Større', options: ['Større', 'Mindre'], instruction: 'Sammenligning' },
    { id: 'en3-a17', type: 'Audio', question: 'Smaller', answer: 'Mindre', options: ['Større', 'Mindre'], instruction: 'Sammenligning' },
    { id: 'en3-a18', type: 'Audio', question: 'Faster', answer: 'Hurtigere', options: ['Hurtigere', 'Langsommere'], instruction: 'Sammenligning' },
    { id: 'en3-a19', type: 'Audio', question: 'Slower', answer: 'Langsommere', options: ['Hurtigere', 'Langsommere'], instruction: 'Sammenligning' },
    { id: 'en3-a20', type: 'Audio', question: 'Higher', answer: 'Højere', options: ['Højere', 'Lavere'], instruction: 'Sammenligning' },
    { id: 'en3-a21', type: 'Audio', question: 'English', answer: 'Engelsk', options: ['Engelsk', 'Dansk', 'Tysk'], instruction: 'Sprog' },
    { id: 'en3-a22', type: 'Audio', question: 'Danish', answer: 'Dansk', options: ['Engelsk', 'Dansk', 'Tysk'], instruction: 'Sprog' },
    { id: 'en3-a23', type: 'Audio', question: 'German', answer: 'Tysk', options: ['Engelsk', 'Dansk', 'Tysk'], instruction: 'Sprog' },
    { id: 'en3-a24', type: 'Audio', question: 'French', answer: 'Fransk', options: ['Engelsk', 'Fransk', 'Spansk'], instruction: 'Sprog' },
    { id: 'en3-a25', type: 'Audio', question: 'Spanish', answer: 'Spansk', options: ['Engelsk', 'Fransk', 'Spansk'], instruction: 'Sprog' },
    { id: 'en3-a26', type: 'Audio', question: 'Monday morning', answer: 'Mandag morgen', options: ['Mandag morgen', 'Mandag aften'], instruction: 'Tid' },
    { id: 'en3-a27', type: 'Audio', question: 'Friday night', answer: 'Fredag aften', options: ['Fredag morgen', 'Fredag aften'], instruction: 'Tid' },
    { id: 'en3-a28', type: 'Audio', question: 'Sunny day', answer: 'Solskinsdag', options: ['Solskinsdag', 'Regnvejrsdag'], instruction: 'Vejr' },
    { id: 'en3-a29', type: 'Audio', question: 'Rainy afternoon', answer: 'Regnfuld eftermiddag', options: ['Solskinsdag', 'Regnfuld eftermiddag'], instruction: 'Vejr' },
    { id: 'en3-a30', type: 'Audio', question: 'Cold winter', answer: 'Kold vinter', options: ['Kold vinter', 'Varm sommer'], instruction: 'Vejr' },
    { id: 'en3-a31', type: 'Audio', question: 'Warm summer', answer: 'Varm sommer', options: ['Kold vinter', 'Varm sommer'], instruction: 'Vejr' },
    { id: 'en3-a32', type: 'Audio', question: 'Morning', answer: 'Morgen', options: ['Morgen', 'Middag', 'Aften'], instruction: 'Tid' },
    { id: 'en3-a33', type: 'Audio', question: 'Afternoon', answer: 'Eftermiddag', options: ['Morgen', 'Eftermiddag', 'Aften'], instruction: 'Tid' },
    { id: 'en3-a34', type: 'Audio', question: 'Evening', answer: 'Aften', options: ['Morgen', 'Eftermiddag', 'Aften'], instruction: 'Tid' },
    { id: 'en3-a35', type: 'Audio', question: 'Night', answer: 'Nat', options: ['Dag', 'Nat'], instruction: 'Tid' },
    { id: 'en3-a36', type: 'Audio', question: 'January', answer: 'Januar', options: ['Januar', 'Februar', 'Marts'], instruction: 'Måned' },
    { id: 'en3-a37', type: 'Audio', question: 'July', answer: 'Juli', options: ['Juli', 'August', 'September'], instruction: 'Måned' },
    { id: 'en3-a38', type: 'Audio', question: 'December', answer: 'December', options: ['Oktober', 'November', 'December'], instruction: 'Måned' },
    { id: 'en3-a39', type: 'Audio', question: 'Spring', answer: 'Forår', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Årstid' },
    { id: 'en3-a40', type: 'Audio', question: 'Autumn', answer: 'Efterår', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Årstid' },
    { id: 'en3-a41', type: 'Audio', question: 'Winter', answer: 'Vinter', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Årstid' },
    { id: 'en3-a42', type: 'Audio', question: 'Summer', answer: 'Sommer', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Årstid' },
    { id: 'en3-a43', type: 'Audio', question: 'Blue eyes', answer: 'Blå øjne', options: ['Blå øjne', 'Brune øjne'], instruction: 'Beskrivelse' },
    { id: 'en3-a44', type: 'Audio', question: 'Brown hair', answer: 'Brunt hår', options: ['Sort hår', 'Brunt hår'], instruction: 'Beskrivelse' },
    { id: 'en3-a45', type: 'Audio', question: 'Long nose', answer: 'Lang næse', options: ['Lang næse', 'Kort næse'], instruction: 'Beskrivelse' },
    { id: 'en3-a46', type: 'Audio', question: 'Wide mouth', answer: 'Bred mund', options: ['Bred mund', 'Lille mund'], instruction: 'Beskrivelse' },
    { id: 'en3-a47', type: 'Audio', question: 'Strong man', answer: 'Stærk mand', options: ['Stærk mand', 'Svag mand'], instruction: 'Beskrivelse' },
    { id: 'en3-a48', type: 'Audio', question: 'Beautiful flower', answer: 'Smuk blomst', options: ['Grim blomst', 'Smuk blomst'], instruction: 'Beskrivelse' },
    { id: 'en3-a49', type: 'Audio', question: 'Quiet room', answer: 'Stille rum', options: ['Larmende rum', 'Stille rum'], instruction: 'Beskrivelse' },
    { id: 'en3-a50', type: 'Audio', question: 'Loud noise', answer: 'Høj lyd', options: ['Høj lyd', 'Lav lyd'], instruction: 'Beskrivelse' },
    { id: 'en3-a51', type: 'Audio', question: 'Correct', answer: 'Rigtigt', options: ['Rigtigt', 'Forkert'], instruction: 'Svar' },
  ],
  4: [
    { id: 'en4-a1', type: 'Audio', question: 'Market', answer: 'Marked', options: ['Butik', 'Marked', 'Supermarked'], instruction: 'Sted' },
    { id: 'en4-a2', type: 'Audio', question: 'Supermarket', answer: 'Supermarked', options: ['Butik', 'Marked', 'Supermarked'], instruction: 'Sted' },
    { id: 'en4-a3', type: 'Audio', question: 'Clothes shop', answer: 'Tøjbutik', options: ['Tøjbutik', 'Boghandler', 'Bager'], instruction: 'Sted' },
    { id: 'en4-a4', type: 'Audio', question: 'Bakery', answer: 'Bager', options: ['Tøjbutik', 'Boghandler', 'Bager'], instruction: 'Sted' },
    { id: 'en4-a5', type: 'Audio', question: 'Cinema', answer: 'Biograf', options: ['Biograf', 'Teater', 'Museum'], instruction: 'Sted' },
    { id: 'en4-a6', type: 'Audio', question: 'Mountain', answer: 'Bjerg', options: ['Bjerg', 'Bakke', 'Dal'], instruction: 'Natur' },
    { id: 'en4-a7', type: 'Audio', question: 'River', answer: 'Flod', options: ['Sø', 'Hav', 'Flod'], instruction: 'Natur' },
    { id: 'en4-a8', type: 'Audio', question: 'Island', answer: 'Ø', options: ['Ø', 'Land', 'Kyst'], instruction: 'Natur' },
    { id: 'en4-a9', type: 'Audio', question: 'Forest', answer: 'Skov', options: ['Skov', 'Park', 'Eng'], instruction: 'Natur' },
    { id: 'en4-a10', type: 'Audio', question: 'Beach', answer: 'Strand', options: ['Strand', 'Havn', 'Klippe'], instruction: 'Natur' },
    { id: 'en4-a11', type: 'Audio', question: 'I went', answer: 'Jeg gik', options: ['Jeg går', 'Jeg gik', 'Jeg vil gå'], instruction: 'Tid' },
    { id: 'en4-a12', type: 'Audio', question: 'He saw', answer: 'Han så', options: ['Han ser', 'Han så', 'Han vil se'], instruction: 'Tid' },
    { id: 'en4-a13', type: 'Audio', question: 'We played', answer: 'Vi spillede', options: ['Vi spiller', 'Vi spillede'], instruction: 'Tid' },
    { id: 'en4-a14', type: 'Audio', question: 'They ate', answer: 'De spiste', options: ['De spiser', 'De spiste'], instruction: 'Tid' },
    { id: 'en4-a15', type: 'Audio', question: 'She ran', answer: 'Hun løb', options: ['Hun løber', 'Hun løb'], instruction: 'Tid' },
    { id: 'en4-a16', type: 'Audio', question: 'Yesterday', answer: 'I går', options: ['I dag', 'I morgen', 'I går'], instruction: 'Tidsudtryk' },
    { id: 'en4-a17', type: 'Audio', question: 'Today', answer: 'I dag', options: ['I dag', 'I morgen', 'I går'], instruction: 'Tidsudtryk' },
    { id: 'en4-a18', type: 'Audio', question: 'Tomorrow', answer: 'I morgen', options: ['I dag', 'I morgen', 'I går'], instruction: 'Tidsudtryk' },
    { id: 'en4-a19', type: 'Audio', question: 'Last week', answer: 'Sidste uge', options: ['Sidste uge', 'Næste uge'], instruction: 'Tidsudtryk' },
    { id: 'en4-a20', type: 'Audio', question: 'Next year', answer: 'Næste år', options: ['Sidste år', 'Næste år'], instruction: 'Tidsudtryk' },
    { id: 'en4-a21', type: 'Audio', question: 'Painting', answer: 'At male', options: ['At male', 'At tegne', 'At skrive'], instruction: 'Hobby' },
    { id: 'en4-a22', type: 'Audio', question: 'Drawing', answer: 'At tegne', options: ['At male', 'At tegne', 'At skrive'], instruction: 'Hobby' },
    { id: 'en4-a23', type: 'Audio', question: 'Singing', answer: 'At synge', options: ['At synge', 'At danse', 'At spille'], instruction: 'Hobby' },
    { id: 'en4-a24', type: 'Audio', question: 'Dancing', answer: 'At danse', options: ['At synge', 'At danse', 'At spille'], instruction: 'Hobby' },
    { id: 'en4-a25', type: 'Audio', question: 'Playing music', answer: 'Spille musik', options: ['Lytte til musik', 'Spille musik'], instruction: 'Hobby' },
    { id: 'en4-a26', type: 'Audio', question: 'Computer games', answer: 'Computerspil', options: ['Brætspil', 'Computerspil'], instruction: 'Hobby' },
    { id: 'en4-a27', type: 'Audio', question: 'Reading', answer: 'Læsning', options: ['Læsning', 'Skrivning'], instruction: 'Hobby' },
    { id: 'en4-a28', type: 'Audio', question: 'Cooking', answer: 'Madlavning', options: ['Madlavning', 'Bagning'], instruction: 'Hobby' },
    { id: 'en4-a29', type: 'Audio', question: 'Gardening', answer: 'Havearbejde', options: ['Havearbejde', 'Skovtur'], instruction: 'Hobby' },
    { id: 'en4-a30', type: 'Audio', question: 'Travelling', answer: 'At rejse', options: ['At rejse', 'At blive hjemme'], instruction: 'Hobby' },
    { id: 'en4-a31', type: 'Audio', question: 'How much?', answer: 'Hvor meget?', options: ['Hvor meget?', 'Hvor mange?', 'Hvorfor?'], instruction: 'Spørgsmål' },
    { id: 'en4-a32', type: 'Audio', question: 'How many?', answer: 'Hvor mange?', options: ['Hvor meget?', 'Hvor mange?', 'Hvornår?'], instruction: 'Spørgsmål' },
    { id: 'en4-a33', type: 'Audio', question: 'Which one?', answer: 'Hvilken en?', options: ['Hvilken en?', 'Hvem?', 'Hvad?'], instruction: 'Spørgsmål' },
    { id: 'en4-a34', type: 'Audio', question: 'Where is...?', answer: 'Hvor er...?', options: ['Hvor er...?', 'Hvem er...?', 'Hvad er...?'], instruction: 'Spørgsmål' },
    { id: 'en4-a35', type: 'Audio', question: 'When is...?', answer: 'Hvornår er...?', options: ['Hvornår er...?', 'Hvorfor er...?', 'Hvordan er...?'], instruction: 'Spørgsmål' },
    { id: 'en4-a36', type: 'Audio', question: 'I would like...', answer: 'Jeg vil gerne have...', options: ['Jeg har...', 'Jeg vil gerne have...'], instruction: 'Høflighed' },
    { id: 'en4-a37', type: 'Audio', question: 'Can I have...?', answer: 'Må jeg få...?', options: ['Har du...?', 'Må jeg få...?'], instruction: 'Høflighed' },
    { id: 'en4-a38', type: 'Audio', question: 'Please', answer: 'Vær så venlig', options: ['Tak', 'Vær så venlig'], instruction: 'Høflighed' },
    { id: 'en4-a39', type: 'Audio', question: 'Thank you', answer: 'Tak', options: ['Goddag', 'Tak'], instruction: 'Høflighed' },
    { id: 'en4-a40', type: 'Audio', question: 'You\'re welcome', answer: 'Selv tak', options: ['Selv tak', 'Godnat'], instruction: 'Høflighed' },
    { id: 'en4-a41', type: 'Audio', question: 'Large', answer: 'Stor', options: ['Stor', 'Lille', 'Medium'], instruction: 'Størrelse' },
    { id: 'en4-a42', type: 'Audio', question: 'Medium', answer: 'Mellem', options: ['Stor', 'Lille', 'Mellem'], instruction: 'Størrelse' },
    { id: 'en4-a43', type: 'Audio', question: 'Small', answer: 'Lille', options: ['Stor', 'Lille', 'Mellem'], instruction: 'Størrelse' },
    { id: 'en4-a44', type: 'Audio', question: 'Breakfast', answer: 'Morgenmad', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Måltid' },
    { id: 'en4-a45', type: 'Audio', question: 'Lunch', answer: 'Frokost', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Måltid' },
    { id: 'en4-a46', type: 'Audio', question: 'Dinner', answer: 'Aftensmad', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Måltid' },
    { id: 'en4-a47', type: 'Audio', question: 'Snack', answer: 'Mellemmåltid', options: ['Måltid', 'Mellemmåltid'], instruction: 'Mad' },
    { id: 'en4-a48', type: 'Audio', question: 'Dessert', answer: 'Dessert', options: ['Forret', 'Dessert'], instruction: 'Mad' },
    { id: 'en4-a49', type: 'Audio', question: 'Healthy', answer: 'Sund', options: ['Sund', 'Usund'], instruction: 'Sundhed' },
    { id: 'en4-a50', type: 'Audio', question: 'Unhealthy', answer: 'Usund', options: ['Sund', 'Usund'], instruction: 'Sundhed' },
    { id: 'en4-a51', type: 'Audio', question: 'Final count', answer: 'Slut', options: ['Start', 'Slut'], instruction: 'Ord' },
  ],
  5: [
    { id: 'en5-a1', type: 'Audio', question: 'Vacation', answer: 'Ferie', options: ['Ferie', 'Arbejde', 'Skole'], instruction: 'Fritid' },
    { id: 'en5-a2', type: 'Audio', question: 'Holiday', answer: 'Helligdag/Ferie', options: ['Helligdag/Ferie', 'Hverdag'], instruction: 'Fritid' },
    { id: 'en5-a3', type: 'Audio', question: 'Airport', answer: 'Lufthavn', options: ['Lufthavn', 'Banegård', 'Havn'], instruction: 'Rejse' },
    { id: 'en5-a4', type: 'Audio', question: 'Hotel', answer: 'Hotel', options: ['Hus', 'Hotel', 'Telt'], instruction: 'Rejse' },
    { id: 'en5-a5', type: 'Audio', question: 'Suitcase', answer: 'Kuffert', options: ['Taske', 'Kuffert', 'Pose'], instruction: 'Rejse' },
    { id: 'en5-a6', type: 'Audio', question: 'Environment', answer: 'Miljø', options: ['Miljø', 'Natur', 'By'], instruction: 'Samfund' },
    { id: 'en5-a7', type: 'Audio', question: 'Pollution', answer: 'Forurening', options: ['Forurening', 'Rensning', 'Luft'], instruction: 'Samfund' },
    { id: 'en5-a8', type: 'Audio', question: 'Recycling', answer: 'Genbrug', options: ['Affald', 'Genbrug', 'Salg'], instruction: 'Samfund' },
    { id: 'en5-a9', type: 'Audio', question: 'Climate change', answer: 'Klimaforandring', options: ['Vejrudsigt', 'Klimaforandring'], instruction: 'Samfund' },
    { id: 'en5-a10', type: 'Audio', question: 'Save water', answer: 'Spar på vandet', options: ['Brug vand', 'Spar på vandet'], instruction: 'Handling' },
    { id: 'en5-a11', type: 'Audio', question: 'Technology', answer: 'Teknologi', options: ['Teknologi', 'Historie', 'Kunst'], instruction: 'Tema' },
    { id: 'en5-a12', type: 'Audio', question: 'Internet', answer: 'Internet', options: ['Internet', 'Radio', 'TV'], instruction: 'Teknologi' },
    { id: 'en5-a13', type: 'Audio', question: 'Social media', answer: 'Sociale medier', options: ['Aviser', 'Sociale medier'], instruction: 'Teknologi' },
    { id: 'en5-a14', type: 'Audio', question: 'Smartphone', answer: 'Smartphone', options: ['Telefon', 'Smartphone', 'Radio'], instruction: 'Teknologi' },
    { id: 'en5-a15', type: 'Audio', question: 'Laptop', answer: 'Bærbar computer', options: ['Computer', 'Bærbar computer'], instruction: 'Teknologi' },
    { id: 'en5-a16', type: 'Audio', question: 'At 5 o\'clock', answer: 'Præposition', options: ['Præposition', 'Bindeord'], instruction: 'Grammatik' },
    { id: 'en5-a17', type: 'Audio', question: 'In the morning', answer: 'Præposition', options: ['Præposition', 'Bindeord'], instruction: 'Grammatik' },
    { id: 'en5-a18', type: 'Audio', question: 'On Monday', answer: 'Præposition', options: ['Præposition', 'Bindeord'], instruction: 'Grammatik' },
    { id: 'en5-a19', type: 'Audio', question: 'Because', answer: 'Bindeord', options: ['Præposition', 'Bindeord'], instruction: 'Grammatik' },
    { id: 'en5-a20', type: 'Audio', question: 'Although', answer: 'Bindeord', options: ['Præposition', 'Bindeord'], instruction: 'Grammatik' },
    { id: 'en5-a21', type: 'Audio', question: 'However', answer: 'Bindeord', options: ['Præposition', 'Bindeord'], instruction: 'Grammatik' },
    { id: 'en5-a22', type: 'Audio', question: 'Therefore', answer: 'Bindeord', options: ['Præposition', 'Bindeord'], instruction: 'Grammatik' },
    { id: 'en5-a23', type: 'Audio', question: 'Beautiful', answer: 'Smuk', options: ['Grim', 'Smuk', 'Grimmeste'], instruction: 'Bøjning' },
    { id: 'en5-a24', type: 'Audio', question: 'More beautiful', answer: 'Smukkere', options: ['Smuk', 'Smukkere', 'Smukkest'], instruction: 'Bøjning' },
    { id: 'en5-a25', type: 'Audio', question: 'Most beautiful', answer: 'Smukkest', options: ['Smuk', 'Smukkere', 'Smukkest'], instruction: 'Bøjning' },
    { id: 'en5-a26', type: 'Audio', question: 'Interesting', answer: 'Interessant', options: ['Interessant', 'Kedelig'], instruction: 'Ord' },
    { id: 'en5-a27', type: 'Audio', question: 'Boring', answer: 'Kedelig', options: ['Interessant', 'Kedelig'], instruction: 'Ord' },
    { id: 'en5-a28', type: 'Audio', question: 'Exciting', answer: 'Spændende', options: ['Spændende', 'Ubehagelig'], instruction: 'Ord' },
    { id: 'en5-a29', type: 'Audio', question: 'Frightening', answer: 'Skræmmende', options: ['Spændende', 'Skræmmende'], instruction: 'Ord' },
    { id: 'en5-a30', type: 'Audio', question: 'Surprising', answer: 'Overraskende', options: ['Overraskende', 'Vant'], instruction: 'Ord' },
    { id: 'en5-a31', type: 'Audio', question: 'London is the capital', answer: 'Fakta', options: ['Fakta', 'Mening'], instruction: 'Type' },
    { id: 'en5-a32', type: 'Audio', question: 'I think it is good', answer: 'Mening', options: ['Fakta', 'Mening'], instruction: 'Type' },
    { id: 'en5-a33', type: 'Audio', question: 'In my opinion...', answer: 'Mening', options: ['Fakta', 'Mening'], instruction: 'Type' },
    { id: 'en5-a34', type: 'Audio', question: 'Water boils at 100 degrees', answer: 'Fakta', options: ['Fakta', 'Mening'], instruction: 'Type' },
    { id: 'en5-a35', type: 'Audio', question: 'I like chocolate', answer: 'Mening', options: ['Fakta', 'Mening'], instruction: 'Type' },
    { id: 'en5-a36', type: 'Audio', question: 'Science', answer: 'Videnskab', options: ['Videnskab', 'Historie', 'Geografi'], instruction: 'Skolefag' },
    { id: 'en5-a37', type: 'Audio', question: 'History', answer: 'Historie', options: ['Videnskab', 'Historie', 'Geografi'], instruction: 'Skolefag' },
    { id: 'en5-a38', type: 'Audio', question: 'Geography', answer: 'Geografi', options: ['Videnskab', 'Historie', 'Geografi'], instruction: 'Skolefag' },
    { id: 'en5-a39', type: 'Audio', question: 'Math', answer: 'Matematik', options: ['Matematik', 'Engelsk', 'Idræt'], instruction: 'Skolefag' },
    { id: 'en5-a40', type: 'Audio', question: 'Physical Education', answer: 'Idræt', options: ['Matematik', 'Engelsk', 'Idræt'], instruction: 'Skolefag' },
    { id: 'en5-a41', type: 'Audio', question: 'Art', answer: 'Billedkunst', options: ['Musik', 'Billedkunst'], instruction: 'Skolefag' },
    { id: 'en5-a42', type: 'Audio', question: 'Music', answer: 'Musik', options: ['Musik', 'Billedkunst'], instruction: 'Skolefag' },
    { id: 'en5-a43', type: 'Audio', question: 'Drama', answer: 'Drama', options: ['Drama', 'Film'], instruction: 'Skolefag' },
    { id: 'en5-a44', type: 'Audio', question: 'Language', answer: 'Sprog', options: ['Sprog', 'Tale', 'Skrift'], instruction: 'Begreb' },
    { id: 'en5-a45', type: 'Audio', question: 'Vocabulary', answer: 'Ordforråd', options: ['Ordforråd', 'Udtale'], instruction: 'Begreb' },
    { id: 'en5-a46', type: 'Audio', question: 'Pronunciation', answer: 'Udtale', options: ['Ordforråd', 'Udtale'], instruction: 'Begreb' },
    { id: 'en5-a47', type: 'Audio', question: 'Grammar', answer: 'Grammatik', options: ['Grammatik', 'Stavning'], instruction: 'Begreb' },
    { id: 'en5-a48', type: 'Audio', question: 'Spelling', answer: 'Stavning', options: ['Grammatik', 'Stavning'], instruction: 'Begreb' },
    { id: 'en5-a49', type: 'Audio', question: 'Sentence', answer: 'Sætning', options: ['Ord', 'Sætning'], instruction: 'Begreb' },
    { id: 'en5-a50', type: 'Audio', question: 'Paragraph', answer: 'Afsnit', options: ['Sætning', 'Afsnit'], instruction: 'Begreb' },
    { id: 'en5-a51', type: 'Audio', question: 'Done', answer: 'Færdig', options: ['Start', 'Færdig'], instruction: 'Ord' },
  ],
  6: [
    { id: 'en6-a1', type: 'Audio', question: 'The cake was eaten by the dog', answer: 'Passive', options: ['Active', 'Passive'], instruction: 'Voice' },
    { id: 'en6-a2', type: 'Audio', question: 'The dog ate the cake', answer: 'Active', options: ['Active', 'Passive'], instruction: 'Voice' },
    { id: 'en6-a3', type: 'Audio', question: 'The book was written by him', answer: 'Passive', options: ['Active', 'Passive'], instruction: 'Voice' },
    { id: 'en6-a4', type: 'Audio', question: 'He wrote the book', answer: 'Active', options: ['Active', 'Passive'], instruction: 'Voice' },
    { id: 'en6-a5', type: 'Audio', question: 'The window was broken', answer: 'Passive', options: ['Active', 'Passive'], instruction: 'Voice' },
    { id: 'en6-a6', type: 'Audio', question: 'A piece of cake', answer: 'Easy', options: ['Easy', 'Hard', 'Delicious'], instruction: 'Idiom meaning' },
    { id: 'en6-a7', type: 'Audio', question: 'Under the weather', answer: 'Sick', options: ['Sick', 'Rainy', 'Cold'], instruction: 'Idiom meaning' },
    { id: 'en6-a8', type: 'Audio', question: 'Break a leg', answer: 'Good luck', options: ['Good luck', 'Bad luck', 'Injury'], instruction: 'Idiom meaning' },
    { id: 'en6-a9', type: 'Audio', question: 'Once in a blue moon', answer: 'Rarely', options: ['Rarely', 'Often', 'Never'], instruction: 'Idiom meaning' },
    { id: 'en6-a10', type: 'Audio', question: 'Cry over spilt milk', answer: 'Useless regret', options: ['Useless regret', 'Sadness', 'Mistake'], instruction: 'Idiom meaning' },
    { id: 'en6-a11', type: 'Audio', question: 'Fiction', answer: 'Opdigtet', options: ['Sandt', 'Opdigtet'], instruction: 'Genre' },
    { id: 'en6-a12', type: 'Audio', question: 'Non-fiction', answer: 'Virkeligt', options: ['Sandt', 'Opdigtet'], instruction: 'Genre' },
    { id: 'en6-a13', type: 'Audio', question: 'Biography', answer: 'Biografi', options: ['Biografi', 'Roman', 'Digt'], instruction: 'Genre' },
    { id: 'en6-a14', type: 'Audio', question: 'Fantasy', answer: 'Fantasy', options: ['Gyser', 'Fantasy', 'Krimi'], instruction: 'Genre' },
    { id: 'en6-a15', type: 'Audio', question: 'Mystery', answer: 'Mysterium/Krimi', options: ['Mysterium/Krimi', 'Komedie'], instruction: 'Genre' },
    { id: 'en6-a16', type: 'Audio', question: 'However', answer: 'Kontrast', options: ['Kontrast', 'Addition', 'Tid'], instruction: 'Bindeord' },
    { id: 'en6-a17', type: 'Audio', question: 'Moreover', answer: 'Addition', options: ['Kontrast', 'Addition', 'Tid'], instruction: 'Bindeord' },
    { id: 'en6-a18', type: 'Audio', question: 'Suddenly', answer: 'Tid', options: ['Kontrast', 'Addition', 'Tid'], instruction: 'Bindeord' },
    { id: 'en6-a19', type: 'Audio', question: 'In conclusion', answer: 'Afslutning', options: ['Start', 'Afslutning'], instruction: 'Bindeord' },
    { id: 'en6-a20', type: 'Audio', question: 'Firstly', answer: 'Rækkefølge', options: ['Rækkefølge', 'Resultat'], instruction: 'Bindeord' },
    { id: 'en6-a21', type: 'Audio', question: 'Advice', answer: 'Råd', options: ['Råd', 'Råde'], instruction: 'Stavning' },
    { id: 'en6-a22', type: 'Audio', question: 'Advise', answer: 'Råde', options: ['Råd', 'Råde'], instruction: 'Stavning' },
    { id: 'en6-a23', type: 'Audio', question: 'Practice', answer: 'Øvelse', options: ['Øvelse', 'Øve'], instruction: 'Stavning' },
    { id: 'en6-a24', type: 'Audio', question: 'Practise', answer: 'Øve', options: ['Øvelse', 'Øve'], instruction: 'Stavning' },
    { id: 'en6-a25', type: 'Audio', question: 'Stationery', answer: 'Papirvarer', options: ['Papirvarer', 'Stillemående'], instruction: 'Stavning' },
    { id: 'en6-a26', type: 'Audio', question: 'Stationary', answer: 'Stillemående', options: ['Papirvarer', 'Stillemående'], instruction: 'Stavning' },
    { id: 'en6-a27', type: 'Audio', question: 'Accept', answer: 'Modtage', options: ['Modtage', 'Undtagen'], instruction: 'Stavning' },
    { id: 'en6-a28', type: 'Audio', question: 'Except', answer: 'Undtagen', options: ['Modtage', 'Undtagen'], instruction: 'Stavning' },
    { id: 'en6-a29', type: 'Audio', question: 'Affect', answer: 'Påvirke', options: ['Påvirke', 'Effekt'], instruction: 'Stavning' },
    { id: 'en6-a30', type: 'Audio', question: 'Effect', answer: 'Effekt', options: ['Påvirke', 'Effekt'], instruction: 'Stavning' },
    { id: 'en6-a31', type: 'Audio', question: 'Could you help me?', answer: 'Request', options: ['Request', 'Order', 'Offer'], instruction: 'Function' },
    { id: 'en6-a32', type: 'Audio', question: 'Sit down now!', answer: 'Order', options: ['Request', 'Order', 'Offer'], instruction: 'Function' },
    { id: 'en6-a33', type: 'Audio', question: 'Would you like some tea?', answer: 'Offer', options: ['Request', 'Order', 'Offer'], instruction: 'Function' },
    { id: 'en6-a34', type: 'Audio', question: 'I am sorry', answer: 'Apology', options: ['Apology', 'Greeting'], instruction: 'Function' },
    { id: 'en6-a35', type: 'Audio', question: 'Congratulations', answer: 'Celebration', options: ['Celebration', 'Apology'], instruction: 'Function' },
    { id: 'en6-a36', type: 'Audio', question: 'British English', answer: 'UK', options: ['UK', 'US'], instruction: 'Variety' },
    { id: 'en6-a37', type: 'Audio', question: 'American English', answer: 'US', options: ['UK', 'US'], instruction: 'Variety' },
    { id: 'en6-a38', type: 'Audio', question: 'Colour', answer: 'UK', options: ['UK', 'US'], instruction: 'Spelling' },
    { id: 'en6-a39', type: 'Audio', question: 'Color', answer: 'US', options: ['UK', 'US'], instruction: 'Spelling' },
    { id: 'en6-a40', type: 'Audio', question: 'Lift', answer: 'UK', options: ['UK', 'US'], instruction: 'Vocabulary' },
    { id: 'en6-a41', type: 'Audio', question: 'Elevator', answer: 'US', options: ['UK', 'US'], instruction: 'Vocabulary' },
    { id: 'en6-a42', type: 'Audio', question: 'Biscuit', answer: 'UK', options: ['UK', 'US'], instruction: 'Vocabulary' },
    { id: 'en6-a43', type: 'Audio', question: 'Cookie', answer: 'US', options: ['UK', 'US'], instruction: 'Vocabulary' },
    { id: 'en6-a44', type: 'Audio', question: 'Flat', answer: 'UK', options: ['UK', 'US'], instruction: 'Vocabulary' },
    { id: 'en6-a45', type: 'Audio', question: 'Apartment', answer: 'US', options: ['UK', 'US'], instruction: 'Vocabulary' },
    { id: 'en6-a46', type: 'Audio', question: 'Pavement', answer: 'UK', options: ['UK', 'US'], instruction: 'Vocabulary' },
    { id: 'en6-a47', type: 'Audio', question: 'Sidewalk', answer: 'US', options: ['UK', 'US'], instruction: 'Vocabulary' },
    { id: 'en6-a48', type: 'Audio', question: 'Football', answer: 'UK', options: ['UK', 'US'], instruction: 'Vocabulary' },
    { id: 'en6-a49', type: 'Audio', question: 'Soccer', answer: 'US', options: ['UK', 'US'], instruction: 'Vocabulary' },
    { id: 'en6-a50', type: 'Audio', question: 'Holiday', answer: 'UK', options: ['UK', 'US'], instruction: 'Vocabulary' },
    { id: 'en6-a51', type: 'Audio', question: 'Vacation', answer: 'US', options: ['UK', 'US'], instruction: 'Vocabulary' },
  ],
  7: [
    { id: 'en7-a1', type: 'Audio', question: 'Simile', answer: 'Sammenligning', options: ['Sammenligning', 'Metafor'], instruction: 'Litterært begreb' },
    { id: 'en7-a2', type: 'Audio', question: 'Metaphor', answer: 'Metafor', options: ['Sammenligning', 'Metafor'], instruction: 'Litterært begreb' },
    { id: 'en7-a3', type: 'Audio', question: 'Personification', answer: 'Besjæling', options: ['Besjæling', 'Ironi'], instruction: 'Litterært begreb' },
    { id: 'en7-a4', type: 'Audio', question: 'Alliteration', answer: 'Bogstavrim', options: ['Bogstavrim', 'Enderim'], instruction: 'Litterært begreb' },
    { id: 'en7-a5', type: 'Audio', question: 'Onomatopoeia', answer: 'Lydord', options: ['Lydord', 'Billedsprog'], instruction: 'Litterært begreb' },
    { id: 'en7-a6', type: 'Audio', question: 'I have seen it', answer: 'Present Perfect', options: ['Present Perfect', 'Past Perfect'], instruction: 'Tense' },
    { id: 'en7-a7', type: 'Audio', question: 'I had seen it', answer: 'Past Perfect', options: ['Present Perfect', 'Past Perfect'], instruction: 'Tense' },
    { id: 'en7-a8', type: 'Audio', question: 'I am seeing it', answer: 'Present Continuous', options: ['Present Simple', 'Present Continuous'], instruction: 'Tense' },
    { id: 'en7-a9', type: 'Audio', question: 'I was seeing it', answer: 'Past Continuous', options: ['Past Simple', 'Past Continuous'], instruction: 'Tense' },
    { id: 'en7-a10', type: 'Audio', question: 'I will be seeing it', answer: 'Future Continuous', options: ['Future Simple', 'Future Continuous'], instruction: 'Tense' },
    { id: 'en7-a11', type: 'Audio', question: 'Shakespeare', answer: 'Author', options: ['Author', 'King', 'Scientist'], instruction: 'Culture' },
    { id: 'en7-a12', type: 'Audio', question: 'Hamlet', answer: 'Play', options: ['Play', 'Novel', 'Poem'], instruction: 'Culture' },
    { id: 'en7-a13', type: 'Audio', question: 'Globe Theatre', answer: 'London', options: ['London', 'New York', 'Paris'], instruction: 'Culture' },
    { id: 'en7-a14', type: 'Audio', question: 'Elizabethan Era', answer: '16th Century', options: ['16th Century', '18th Century'], instruction: 'Culture' },
    { id: 'en7-a15', type: 'Audio', question: 'Romeo and Juliet', answer: 'Tragedy', options: ['Tragedy', 'Comedy'], instruction: 'Culture' },
    { id: 'en7-a16', type: 'Audio', question: 'Formal', answer: 'Formelt', options: ['Formelt', 'Uformelt'], instruction: 'Register' },
    { id: 'en7-a17', type: 'Audio', question: 'Informal', answer: 'Uformelt', options: ['Formelt', 'Uformelt'], instruction: 'Register' },
    { id: 'en7-a18', type: 'Audio', question: 'Slang', answer: 'Gadesprog', options: ['Gadesprog', 'Akademisk sprog'], instruction: 'Register' },
    { id: 'en7-a19', type: 'Audio', question: 'Dialect', answer: 'Dialekt', options: ['Dialekt', 'Standard'], instruction: 'Register' },
    { id: 'en7-a20', type: 'Audio', question: 'Accent', answer: 'Accent/Udtale', options: ['Accent/Udtale', 'Grammatik'], instruction: 'Register' },
    { id: 'en7-a21', type: 'Audio', question: 'I am going to...', answer: 'Intent', options: ['Intent', 'Fact'], instruction: 'Future meaning' },
    { id: 'en7-a22', type: 'Audio', question: 'I will...', answer: 'Prediction/Offer', options: ['Prediction/Offer', 'Plan'], instruction: 'Future meaning' },
    { id: 'en7-a23', type: 'Audio', question: 'Must', answer: 'Obligation', options: ['Obligation', 'Possibility'], instruction: 'Modal verb' },
    { id: 'en7-a24', type: 'Audio', question: 'Might', answer: 'Possibility', options: ['Obligation', 'Possibility'], instruction: 'Modal verb' },
    { id: 'en7-a25', type: 'Audio', question: 'Should', answer: 'Advice', options: ['Advice', 'Rule'], instruction: 'Modal verb' },
    { id: 'en7-a26', type: 'Audio', question: 'Can', answer: 'Ability', options: ['Ability', 'Permission'], instruction: 'Modal verb' },
    { id: 'en7-a27', type: 'Audio', question: 'May', answer: 'Permission', options: ['Ability', 'Permission'], instruction: 'Modal verb' },
    { id: 'en7-a28', type: 'Audio', question: 'Could', answer: 'Past ability', options: ['Past ability', 'Future intent'], instruction: 'Modal verb' },
    { id: 'en7-a29', type: 'Audio', question: 'Would', answer: 'Conditional', options: ['Conditional', 'Certainty'], instruction: 'Modal verb' },
    { id: 'en7-a30', type: 'Audio', question: 'Ought to', answer: 'Duty', options: ['Duty', 'Option'], instruction: 'Modal verb' },
    { id: 'en7-a31', type: 'Audio', question: 'Analysis', answer: 'Analyse', options: ['Analyse', 'Beskrivelse'], instruction: 'Ord' },
    { id: 'en7-a32', type: 'Audio', question: 'Evaluation', answer: 'Evaluering', options: ['Evaluering', 'Præsentation'], instruction: 'Ord' },
    { id: 'en7-a33', type: 'Audio', question: 'Synthesis', answer: 'Syntese/Samling', options: ['Syntese/Samling', 'Opdeling'], instruction: 'Ord' },
    { id: 'en7-a34', type: 'Audio', question: 'Perspective', answer: 'Perspektiv', options: ['Perspektiv', 'Fokus'], instruction: 'Ord' },
    { id: 'en7-a35', type: 'Audio', question: 'Evidence', answer: 'Bevis', options: ['Bevis', 'Gæt'], instruction: 'Ord' },
    { id: 'en7-a36', type: 'Audio', question: 'Conclusion', answer: 'Konklusion', options: ['Start', 'Midte', 'Konklusion'], instruction: 'Ord' },
    { id: 'en7-a37', type: 'Audio', question: 'Structure', answer: 'Struktur', options: ['Struktur', 'Indhold'], instruction: 'Ord' },
    { id: 'en7-a38', type: 'Audio', question: 'Theme', answer: 'Tema', options: ['Tema', 'Handling'], instruction: 'Ord' },
    { id: 'en7-a39', type: 'Audio', question: 'Plot', answer: 'Handling', options: ['Tema', 'Handling'], instruction: 'Ord' },
    { id: 'en7-a40', type: 'Audio', question: 'Character', answer: 'Karakter/Person', options: ['Karakter/Person', 'Sted'], instruction: 'Ord' },
    { id: 'en7-a41', type: 'Audio', question: 'Setting', answer: 'Miljø/Sted', options: ['Miljø/Sted', 'Tid'], instruction: 'Ord' },
    { id: 'en7-a42', type: 'Audio', question: 'Narrator', answer: 'Fortæller', options: ['Fortæller', 'Læser'], instruction: 'Ord' },
    { id: 'en7-a43', type: 'Audio', question: 'Protagonist', answer: 'Hovedperson', options: ['Hovedperson', 'Modstander'], instruction: 'Ord' },
    { id: 'en7-a44', type: 'Audio', question: 'Antagonist', answer: 'Modstander', options: ['Hovedperson', 'Modstander'], instruction: 'Ord' },
    { id: 'en7-a45', type: 'Audio', question: 'Climax', answer: 'Højdepunkt', options: ['Højdepunkt', 'Slutning'], instruction: 'Ord' },
    { id: 'en7-a46', type: 'Audio', question: 'Foreshadowing', answer: 'Varsel', options: ['Varsel', 'Tilbageblik'], instruction: 'Ord' },
    { id: 'en7-a47', type: 'Audio', question: 'Flashback', answer: 'Tilbageblik', options: ['Varsel', 'Tilbageblik'], instruction: 'Ord' },
    { id: 'en7-a48', type: 'Audio', question: 'Imagery', answer: 'Billedsprog', options: ['Billedsprog', 'Direkte tale'], instruction: 'Ord' },
    { id: 'en7-a49', type: 'Audio', question: 'Symbolism', answer: 'Symbolik', options: ['Symbolik', 'Realistisk'], instruction: 'Ord' },
    { id: 'en7-a50', type: 'Audio', question: 'Irony', answer: 'Ironi', options: ['Ironi', 'Sarkasme'], instruction: 'Ord' },
    { id: 'en7-a51', type: 'Audio', question: 'Satire', answer: 'Satire', options: ['Satire', 'Komedie'], instruction: 'Ord' },
  ],
  8: [
    { id: 'en8-a1', type: 'Audio', question: 'I am going to the shop', answer: 'Fremtid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Tense' },
    { id: 'en8-a2', type: 'Audio', question: 'He had already left', answer: 'Past Perfect', options: ['Past Simple', 'Past Perfect'], instruction: 'Tense' },
    { id: 'en8-a3', type: 'Audio', question: 'I have been working', answer: 'Present Perfect Continuous', options: ['Present Perfect', 'Present Perfect Continuous'], instruction: 'Tense' },
    { id: 'en8-a4', type: 'Audio', question: 'They will have finished', answer: 'Future Perfect', options: ['Future Simple', 'Future Perfect'], instruction: 'Tense' },
    { id: 'en8-a5', type: 'Audio', question: 'If I were you', answer: 'Subjunctive', options: ['Indicative', 'Subjunctive'], instruction: 'Mood' },
    { id: 'en8-a6', type: 'Audio', question: 'Ambiguity', answer: 'Flertydighed', options: ['Flertydighed', 'Klarhed'], instruction: 'Academic word' },
    { id: 'en8-a7', type: 'Audio', question: 'Context', answer: 'Kontekst/Sammenhæng', options: ['Kontekst/Sammenhæng', 'Isolering'], instruction: 'Academic word' },
    { id: 'en8-a8', type: 'Audio', question: 'Hierarchy', answer: 'Hierarki/Rangorden', options: ['Hierarki/Rangorden', 'Kaos'], instruction: 'Academic word' },
    { id: 'en8-a9', type: 'Audio', question: 'Hypothesis', answer: 'Hypotese/Gæt', options: ['Hypotese/Gæt', 'Bevis'], instruction: 'Academic word' },
    { id: 'en8-a10', type: 'Audio', question: 'Infrastructure', answer: 'Infrastruktur', options: ['Infrastruktur', 'Natur'], instruction: 'Academic word' },
    { id: 'en8-a11', type: 'Audio', question: 'Legislation', answer: 'Lovgivning', options: ['Lovgivning', 'Regler'], instruction: 'Academic word' },
    { id: 'en8-a12', type: 'Audio', question: 'Paradigm', answer: 'Paradigme/Mønster', options: ['Paradigme/Mønster', 'Fejl'], instruction: 'Academic word' },
    { id: 'en8-a13', type: 'Audio', question: 'Phenomenon', answer: 'Fænomen', options: ['Fænomen', 'Normalitet'], instruction: 'Academic word' },
    { id: 'en8-a14', type: 'Audio', question: 'Significant', answer: 'Betydningsfuld', options: ['Betydningsfuld', 'Ligegyldig'], instruction: 'Academic word' },
    { id: 'en8-a15', type: 'Audio', question: 'Sustainable', answer: 'Bæredygtig', options: ['Bæredygtig', 'Skadelig'], instruction: 'Academic word' },
    { id: 'en8-a16', type: 'Audio', question: 'Debate', answer: 'Debat', options: ['Debat', 'Samtale', 'Skænderi'], instruction: 'Communication' },
    { id: 'en8-a17', type: 'Audio', question: 'Argument', answer: 'Argument', options: ['Argument', 'Påstand', 'Bevis'], instruction: 'Communication' },
    { id: 'en8-a18', type: 'Audio', question: 'Claim', answer: 'Påstand', options: ['Argument', 'Påstand', 'Bevis'], instruction: 'Communication' },
    { id: 'en8-a19', type: 'Audio', question: 'Counter-argument', answer: 'Modargument', options: ['Argument', 'Modargument'], instruction: 'Communication' },
    { id: 'en8-a20', type: 'Audio', question: 'Rebuttal', answer: 'Gendrivelse', options: ['Gendrivelse', 'Enighed'], instruction: 'Communication' },
    { id: 'en8-a21', type: 'Audio', question: 'Bias', answer: 'Forudindtagethed', options: ['Forudindtagethed', 'Neutralitet'], instruction: 'Communication' },
    { id: 'en8-a22', type: 'Audio', question: 'Neutral', answer: 'Neutral', options: ['Neutral', 'Partisk'], instruction: 'Communication' },
    { id: 'en8-a23', type: 'Audio', question: 'Objective', answer: 'Objektiv', options: ['Objektiv', 'Subjektiv'], instruction: 'Communication' },
    { id: 'en8-a24', type: 'Audio', question: 'Subjective', answer: 'Subjektiv', options: ['Objektiv', 'Subjektiv'], instruction: 'Communication' },
    { id: 'en8-a25', type: 'Audio', question: 'Persuasive', answer: 'Overbevisende', options: ['Overbevisende', 'Svag'], instruction: 'Communication' },
    { id: 'en8-a26', type: 'Audio', question: 'Rhetoric', answer: 'Retorik/Talekunst', options: ['Retorik/Talekunst', 'Skrift'], instruction: 'Communication' },
    { id: 'en8-a27', type: 'Audio', question: 'Audience', answer: 'Publikum/Modtager', options: ['Publikum/Modtager', 'Sender'], instruction: 'Communication' },
    { id: 'en8-a28', type: 'Audio', question: 'Message', answer: 'Budskab', options: ['Budskab', 'Støj'], instruction: 'Communication' },
    { id: 'en8-a29', type: 'Audio', question: 'Medium', answer: 'Medie/Kanal', options: ['Medie/Kanal', 'Indhold'], instruction: 'Communication' },
    { id: 'en8-a30', type: 'Audio', question: 'Context', answer: 'Sammenhæng', options: ['Sammenhæng', 'Ord'], instruction: 'Communication' },
    { id: 'en8-a31', type: 'Audio', question: 'Metaphorical', answer: 'Metaforisk', options: ['Metaforisk', 'Bogstavelig'], instruction: 'Meaning' },
    { id: 'en8-a32', type: 'Audio', question: 'Literal', answer: 'Bogstavelig', options: ['Metaforisk', 'Bogstavelig'], instruction: 'Meaning' },
    { id: 'en8-a33', type: 'Audio', question: 'Denotation', answer: 'Grundbetydning', options: ['Grundbetydning', 'Medbetydning'], instruction: 'Meaning' },
    { id: 'en8-a34', type: 'Audio', question: 'Connotation', answer: 'Medbetydning', options: ['Grundbetydning', 'Medbetydning'], instruction: 'Meaning' },
    { id: 'en8-a35', type: 'Audio', question: 'Abstract', answer: 'Abstrakt', options: ['Abstrakt', 'Konkret'], instruction: 'Meaning' },
    { id: 'en8-a36', type: 'Audio', question: 'Concrete', answer: 'Konkret', options: ['Abstrakt', 'Konkret'], instruction: 'Meaning' },
    { id: 'en8-a37', type: 'Audio', question: 'Vague', answer: 'Upræcis', options: ['Upræcis', 'Præcis'], instruction: 'Meaning' },
    { id: 'en8-a38', type: 'Audio', question: 'Precise', answer: 'Præcis', options: ['Upræcis', 'Præcis'], instruction: 'Meaning' },
    { id: 'en8-a39', type: 'Audio', question: 'Ambiguous', answer: 'Tvetydig', options: ['Tvetydig', 'Klar'], instruction: 'Meaning' },
    { id: 'en8-a40', type: 'Audio', question: 'Explicit', answer: 'Tydelig/Direkte', options: ['Tydelig/Direkte', 'Skjult'], instruction: 'Meaning' },
    { id: 'en8-a41', type: 'Audio', question: 'Implicit', answer: 'Indirekte', options: ['Tydelig/Direkte', 'Indirekte'], instruction: 'Meaning' },
    { id: 'en8-a42', type: 'Audio', question: 'Etymology', answer: 'Ordhistorie', options: ['Ordhistorie', 'Grammatik'], instruction: 'Linguistics' },
    { id: 'en8-a43', type: 'Audio', question: 'Syntax', answer: 'Sætningsbygning', options: ['Sætningsbygning', 'Udtale'], instruction: 'Linguistics' },
    { id: 'en8-a44', type: 'Audio', question: 'Semantics', answer: 'Betydningslære', options: ['Betydningslære', 'Lydlære'], instruction: 'Linguistics' },
    { id: 'en8-a45', type: 'Audio', question: 'Phonology', answer: 'Lydlære', options: ['Betydningslære', 'Lydlære'], instruction: 'Linguistics' },
    { id: 'en8-a46', type: 'Audio', question: 'Pragmatics', answer: 'Sprogbrug i praksis', options: ['Sprogbrug i praksis', 'Regler'], instruction: 'Linguistics' },
    { id: 'en8-a47', type: 'Audio', question: 'Morphology', answer: 'Ordlære/Bøjning', options: ['Ordlære/Bøjning', 'Tekstanalyse'], instruction: 'Linguistics' },
    { id: 'en8-a48', type: 'Audio', question: 'Dialectology', answer: 'Dialektlære', options: ['Dialektlære', 'Sproghistorie'], instruction: 'Linguistics' },
    { id: 'en8-a49', type: 'Audio', question: 'Sociolinguistics', answer: 'Sprog og samfund', options: ['Sprog og samfund', 'Sprog og hjerne'], instruction: 'Linguistics' },
    { id: 'en8-a50', type: 'Audio', question: 'Psycholinguistics', answer: 'Sprog og sind', options: ['Sprog og samfund', 'Sprog og sind'], instruction: 'Linguistics' },
    { id: 'en8-a51', type: 'Audio', question: 'Historical linguistics', answer: 'Sproghistorie', options: ['Sproghistorie', 'Nutidssprog'], instruction: 'Linguistics' },
  ],
  9: [
    { id: 'da9-a1', type: 'Audio', question: 'Ambivalent', answer: 'Splittet', options: ['Splittet', 'Bestemt', 'Glad'], instruction: 'Hvad betyder ordet?' },
    { id: 'en9-a1', type: 'Audio', question: 'Comprehensive', answer: 'Omfattende', options: ['Omfattende', 'Lille', 'Enkel'], instruction: 'Vocabulary' },
    { id: 'en9-a2', type: 'Audio', question: 'Contradictory', answer: 'Modstridende', options: ['Modstridende', 'Ens', 'Klar'], instruction: 'Vocabulary' },
    { id: 'en9-a3', type: 'Audio', question: 'Conventional', answer: 'Traditionel', options: ['Traditionel', 'Moderne', 'Vild'], instruction: 'Vocabulary' },
    { id: 'en9-a4', type: 'Audio', question: 'Evolutionary', answer: 'Udviklingsmæssig', options: ['Udviklingsmæssig', 'Statisk'], instruction: 'Vocabulary' },
    { id: 'en9-a5', type: 'Audio', question: 'Fundamental', answer: 'Grundlæggende', options: ['Grundlæggende', 'Overfladisk'], instruction: 'Vocabulary' },
    { id: 'en9-a6', type: 'Audio', question: 'Inherent', answer: 'Iboende', options: ['Iboende', 'Ydre'], instruction: 'Vocabulary' },
    { id: 'en9-a7', type: 'Audio', question: 'Justification', answer: 'Begrundelse', options: ['Begrundelse', 'Udtalelse'], instruction: 'Vocabulary' },
    { id: 'en9-a8', type: 'Audio', question: 'Paradoxical', answer: 'Paradoksalt', options: ['Paradoksalt', 'Logisk'], instruction: 'Vocabulary' },
    { id: 'en9-a9', type: 'Audio', question: 'Prerequisite', answer: 'Forudsætning', options: ['Forudsætning', 'Resultat'], instruction: 'Vocabulary' },
    { id: 'en9-a10', type: 'Audio', question: 'Theoretical', answer: 'Teoretisk', options: ['Teoretisk', 'Praktisk'], instruction: 'Vocabulary' },
    { id: 'en9-a11', type: 'Audio', question: 'Utopia', answer: 'Idealsamfund', options: ['Idealsamfund', 'Skrækscenarie'], instruction: 'Concept' },
    { id: 'en9-a12', type: 'Audio', question: 'Dystopia', answer: 'Skrækscenarie', options: ['Idealsamfund', 'Skrækscenarie'], instruction: 'Concept' },
    { id: 'en9-a13', type: 'Audio', question: 'Globalization', answer: 'Globalisering', options: ['Globalisering', 'Lokalisering'], instruction: 'Concept' },
    { id: 'en9-a14', type: 'Audio', question: 'Sustainability', answer: 'Bæredygtighed', options: ['Bæredygtighed', 'Forbrug'], instruction: 'Concept' },
    { id: 'en9-a15', type: 'Audio', question: 'Ethics', answer: 'Etik/Moral', options: ['Etik/Moral', 'Lov'], instruction: 'Concept' },
    { id: 'en9-a16', type: 'Audio', question: 'Identity', answer: 'Identitet', options: ['Identitet', 'Gruppe'], instruction: 'Concept' },
    { id: 'en9-a17', type: 'Audio', question: 'Diversity', answer: 'Mangfoldighed', options: ['Mangfoldighed', 'Ensidighed'], instruction: 'Concept' },
    { id: 'en9-a18', type: 'Audio', question: 'Innovation', answer: 'Innovation/Nyskabelse', options: ['Innovation/Nyskabelse', 'Kopi'], instruction: 'Concept' },
    { id: 'en9-a19', type: 'Audio', question: 'Migration', answer: 'Folkevandring', options: ['Migration', 'Bosættelse'], instruction: 'Concept' },
    { id: 'en9-a20', type: 'Audio', question: 'Urbanization', answer: 'Urbanisering', options: ['Urbanisering', 'Affolkning'], instruction: 'Concept' },
    { id: 'en9-a21', type: 'Audio', question: 'To be or not to be', answer: 'Shakespeare', options: ['Shakespeare', 'Dickens', 'Austen'], instruction: 'Literature' },
    { id: 'en9-a22', type: 'Audio', question: 'I have a dream', answer: 'Martin Luther King', options: ['MLK', 'Obama', 'Lincoln'], instruction: 'Famous quote' },
    { id: 'en9-a23', type: 'Audio', question: 'One small step for man', answer: 'Neil Armstrong', options: ['Armstrong', 'Aldrin', 'Collins'], instruction: 'Famous quote' },
    { id: 'en9-a24', type: 'Audio', question: 'Knowledge is power', answer: 'Francis Bacon', options: ['Bacon', 'Power', 'Wisdom'], instruction: 'Famous quote' },
    { id: 'en9-a25', type: 'Audio', question: 'I think, therefore I am', answer: 'Descartes', options: ['Descartes', 'Kant', 'Hegel'], instruction: 'Famous quote' },
    { id: 'en9-a26', type: 'Audio', question: 'Ironie', answer: 'Irony', options: ['Irony', 'Sarcasm'], instruction: 'Term' },
    { id: 'en9-a27', type: 'Audio', question: 'Sarkasmus', answer: 'Sarcasm', options: ['Irony', 'Sarcasm'], instruction: 'Term' },
    { id: 'en9-a28', type: 'Audio', question: 'Understatement', answer: 'Underdrivelse', options: ['Underdrivelse', 'Overdrivelse'], instruction: 'Term' },
    { id: 'en9-a29', type: 'Audio', question: 'Hyperbole', answer: 'Overdrivelse', options: ['Underdrivelse', 'Overdrivelse'], instruction: 'Term' },
    { id: 'en9-a30', type: 'Audio', question: 'Oxymoron', answer: 'Selvmodsigelse', options: ['Selvmodsigelse', 'Lighed'], instruction: 'Term' },
    { id: 'en9-a31', type: 'Audio', question: 'Ethos', answer: 'Credibility', options: ['Credibility', 'Emotion', 'Logic'], instruction: 'Rhetoric' },
    { id: 'en9-a32', type: 'Audio', question: 'Pathos', answer: 'Emotion', options: ['Credibility', 'Emotion', 'Logic'], instruction: 'Rhetoric' },
    { id: 'en9-a33', type: 'Audio', question: 'Logos', answer: 'Logic', options: ['Credibility', 'Emotion', 'Logic'], instruction: 'Rhetoric' },
    { id: 'en9-a34', type: 'Audio', question: 'Kairos', answer: 'Timing', options: ['Timing', 'Place'], instruction: 'Rhetoric' },
    { id: 'en9-a35', type: 'Audio', question: 'Aptum', answer: 'Appropriateness', options: ['Appropriateness', 'Style'], instruction: 'Rhetoric' },
    { id: 'en9-a36', type: 'Audio', question: 'Perspective', answer: 'Synsvinkel', options: ['Synsvinkel', 'Fokus'], instruction: 'Analysis' },
    { id: 'en9-a37', type: 'Audio', question: 'Interpretation', answer: 'Fortolkning', options: ['Fortolkning', 'Beskrivelse'], instruction: 'Analysis' },
    { id: 'en9-a38', type: 'Audio', question: 'Critique', answer: 'Kritik', options: ['Kritik', 'Ros'], instruction: 'Analysis' },
    { id: 'en9-a39', type: 'Audio', question: 'Validity', answer: 'Gyldighed', options: ['Gyldighed', 'Fejl'], instruction: 'Analysis' },
    { id: 'en9-a40', type: 'Audio', question: 'Reliability', answer: 'Pålidelighed', options: ['Pålidelighed', 'Usikkerhed'], instruction: 'Analysis' },
    { id: 'en9-a41', type: 'Audio', question: 'Global perspective', answer: 'Verdenssyn', options: ['Verdenssyn', 'Lokalsyn'], instruction: 'Analysis' },
    { id: 'en9-a42', type: 'Audio', question: 'Historical context', answer: 'Historisk sammenhæng', options: ['Historisk sammenhæng', 'Nutidig'], instruction: 'Analysis' },
    { id: 'en9-a43', type: 'Audio', question: 'Social implications', answer: 'Sociale konsekvenser', options: ['Sociale konsekvenser', 'Økonomiske'], instruction: 'Analysis' },
    { id: 'en9-a44', type: 'Audio', question: 'Moral dilemma', answer: 'Moralsk dilemma', options: ['Moralsk dilemma', 'Nem beslutning'], instruction: 'Analysis' },
    { id: 'en9-a45', type: 'Audio', question: 'Aesthetic value', answer: 'Æstetisk værdi', options: ['Æstetisk værdi', 'Praktisk værdi'], instruction: 'Analysis' },
    { id: 'en9-a46', type: 'Audio', question: 'Synthesized', answer: 'Syntetiseret/Samlet', options: ['Samlet', 'Delt'], instruction: 'Analysis' },
    { id: 'en9-a47', type: 'Audio', question: 'Correlated', answer: 'Korreleret/Hænger sammen', options: ['Hænger sammen', 'Uafhængig'], instruction: 'Analysis' },
    { id: 'en9-a48', type: 'Audio', question: 'Causality', answer: 'Kausalitet/Årsag', options: ['Årsag', 'Tilfældighed'], instruction: 'Analysis' },
    { id: 'en9-a49', type: 'Audio', question: 'Variable', answer: 'Variabel', options: ['Variabel', 'Konstant'], instruction: 'Analysis' },
    { id: 'en9-a50', type: 'Audio', question: 'Data analysis', answer: 'Dataanalyse', options: ['Dataanalyse', 'Gæt'], instruction: 'Analysis' },
    { id: 'en9-a51', type: 'Audio', question: 'Conclusion reached', answer: 'Konklusion', options: ['Start', 'Konklusion'], instruction: 'Analysis' },
  ],
};
