/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const FRANSK_AUDIO_P2: Partial<Record<Grade, GameContent[]>> = {
  5: [
    { id: 'fr5-a1', type: 'Audio', question: 'Le futur', answer: 'Fremtiden', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Tid' },
    { id: 'fr5-a2', type: 'Audio', question: 'Le passé', answer: 'Fortiden', options: ['Fortid', 'Fremtid'], instruction: 'Tid' },
    { id: 'fr5-a3', type: 'Audio', question: 'La technologie', answer: 'Teknologien', options: ['Biologi', 'Teknologi'], instruction: 'Tema' },
    { id: 'fr5-a4', type: 'Audio', question: 'L’environnement', answer: 'Miljøet', options: ['Miljøet', 'Skolen'], instruction: 'Tema' },
    { id: 'fr5-a5', type: 'Audio', question: 'Le changement climatique', answer: 'Klimaforandringer', options: ['Vejrudsigt', 'Klimaforandringer'], instruction: 'Tema' },
    { id: 'fr5-a6', type: 'Audio', question: 'Une expérience', answer: 'En erfaring/eksperiment', options: ['Oplevelse', 'Hobby'], instruction: 'Begreb' },
    { id: 'fr5-a7', type: 'Audio', question: 'Un défi', answer: 'En udfordring', options: ['Leg', 'Udfordring'], instruction: 'Begreb' },
    { id: 'fr5-a8', type: 'Audio', question: 'Une réussite', answer: 'En succes', options: ['Nederlag', 'Succes'], instruction: 'Begreb' },
    { id: 'fr5-a9', type: 'Audio', question: 'Un échec', answer: 'En fiasko', options: ['Nederlag', 'Succes'], instruction: 'Begreb' },
    { id: 'fr5-a10', type: 'Audio', question: 'Le gouvernement', answer: 'Regeringen', options: ['Byrådet', 'Regeringen'], instruction: 'Samfund' },
    { id: 'fr5-a11', type: 'Audio', question: 'Les actualités', answer: 'Nyhederne', options: ['Nyhederne', 'Film'], instruction: 'Samfund' },
    { id: 'fr5-a12', type: 'Audio', question: 'La justice', answer: 'Retfærdighed', options: ['Lov', 'Retfærdighed'], instruction: 'Værdi' },
    { id: 'fr5-a13', type: 'Audio', question: 'La liberté', answer: 'Frihed', options: ['Frihed', 'Tvång'], instruction: 'Værdi' },
    { id: 'fr5-a14', type: 'Audio', question: 'L’égalité', answer: 'Lighed', options: ['Lighed', 'Forskel'], instruction: 'Værdi' },
    { id: 'fr5-a15', type: 'Audio', question: 'La fraternité', answer: 'Broderskab', options: ['Broderskab', 'Venskab'], instruction: 'Værdi' },
    { id: 'fr5-a16', type: 'Audio', question: 'Vivre ensemble', answer: 'Leve sammen', options: ['Leve sammen', 'Leve alene'], instruction: 'Udtryk' },
    { id: 'fr5-a17', type: 'Audio', question: 'Prendre soin de...', answer: 'Passe på...', options: ['Ødelægge', 'Passe på'], instruction: 'Udtryk' },
    { id: 'fr5-a18', type: 'Audio', question: 'Faire attention', answer: 'Være opmærksom', options: ['Glem det', 'Pas på'], instruction: 'Udtryk' },
    { id: 'fr5-a19', type: 'Audio', question: 'Développer', answer: 'Udvikle', options: ['Stop', 'Udvikle'], instruction: 'Handling' },
    { id: 'fr5-a20', type: 'Audio', question: 'Protéger', answer: 'Beskytte', options: ['Beskytte', 'Angribe'], instruction: 'Handling' },
    { id: 'fr5-a21', type: 'Audio', question: 'Améliorer', answer: 'Forbedre', options: ['Forbedre', 'Forringe'], instruction: 'Handling' },
    { id: 'fr5-a22', type: 'Audio', question: 'Réduire', answer: 'Reducere', options: ['Øge', 'Reducere'], instruction: 'Handling' },
    { id: 'fr5-a23', type: 'Audio', question: 'Polluer', answer: 'Forurene', options: ['Rense', 'Forurene'], instruction: 'Handling' },
    { id: 'fr5-a24', type: 'Audio', question: 'Recycler', answer: 'Genbruge', options: ['Smid ud', 'Genbruge'], instruction: 'Handling' },
    { id: 'fr5-a25', type: 'Audio', question: 'Économiser', answer: 'Spare', options: ['Bruge', 'Spare'], instruction: 'Handling' },
    { id: 'fr5-a26', type: 'Audio', question: 'Gaspiller', answer: 'Spilde', options: ['Spare', 'Spilde'], instruction: 'Handling' },
    { id: 'fr5-a27', type: 'Audio', question: 'Une application', answer: 'En App', options: ['Hjemmeside', 'App'], instruction: 'Teknologi' },
    { id: 'fr5-a28', type: 'Audio', question: 'Un écran', answer: 'En skærm', options: ['Skærm', 'Tastatur'], instruction: 'Teknologi' },
    { id: 'fr5-a29', type: 'Audio', question: 'Un compte', answer: 'En konto', options: ['Bruger', 'Konto'], instruction: 'Teknologi' },
    { id: 'fr5-a30', type: 'Audio', question: 'Un mot de passe', answer: 'Adgangskode', options: ['Navn', 'Password'], instruction: 'Teknologi' },
    { id: 'fr5-a31', type: 'Audio', question: 'Naviguer', answer: 'Surfe/navigere', options: ['Skrive', 'Surfe'], instruction: 'Teknologi' },
    { id: 'fr5-a32', type: 'Audio', question: 'Télécharger', answer: 'Downloade', options: ['Oploade', 'Downloade'], instruction: 'Teknologi' },
    { id: 'fr5-a33', type: 'Audio', question: 'Une annonce', answer: 'En annonce', options: ['Nyhed', 'Annonce'], instruction: 'Medier' },
    { id: 'fr5-a34', type: 'Audio', question: 'La publicité', answer: 'Reklame', options: ['Film', 'Reklame'], instruction: 'Medier' },
    { id: 'fr5-a35', type: 'Audio', question: 'Un article', answer: 'En artikel', options: ['Digt', 'Artikel'], instruction: 'Medier' },
    { id: 'fr5-a36', type: 'Audio', question: 'Le journal', answer: 'Avisen', options: ['Avisen', 'Bogen'], instruction: 'Medier' },
    { id: 'fr5-a37', type: 'Audio', question: 'Un magazine', answer: 'Et blad', options: ['Dagblad', 'Ugeblad'], instruction: 'Medier' },
    { id: 'fr5-a38', type: 'Audio', question: 'Une émission', answer: 'Udsendelse', options: ['Udsendelse', 'Reklame'], instruction: 'Medier' },
    { id: 'fr5-a39', type: 'Audio', question: 'Les réseaux sociaux', answer: 'Sociale medier', options: ['Skole', 'Sociale medier'], instruction: 'Medier' },
    { id: 'fr5-a40', type: 'Audio', question: 'Partager', answer: 'Dele', options: ['Dele', 'Gemme'], instruction: 'Handling' },
    { id: 'fr5-a41', type: 'Audio', question: 'S’inscrire', answer: 'Melde sig til', options: ['Afmelde', 'Tilmeld'], instruction: 'Handling' },
    { id: 'fr5-a42', type: 'Audio', question: 'Découvrir', answer: 'Opdage', options: ['Opdage', 'Miste'], instruction: 'Handling' },
    { id: 'fr5-a43', type: 'Audio', question: 'Inventer', answer: 'Opfinde', options: ['Opfinde', 'Kopiere'], instruction: 'Handling' },
    { id: 'fr5-a44', type: 'Audio', question: 'Imaginer', answer: 'Forestille sig', options: ['Vide', 'Drømme/Forestille'], instruction: 'Handling' },
    { id: 'fr5-a45', type: 'Audio', question: 'Réfléchir', answer: 'Tænke over', options: ['Handle', 'Reflektere'], instruction: 'Handling' },
    { id: 'fr5-a46', type: 'Audio', question: 'Expliquer', answer: 'Forklare', options: ['Lytte', 'Forklare'], instruction: 'Handling' },
    { id: 'fr5-a47', type: 'Audio', question: 'Comprendre', answer: 'Forstå', options: ['Glemme', 'Forstå'], instruction: 'Handling' },
    { id: 'fr5-a48', type: 'Audio', question: 'Apprendre', answer: 'Lære', options: ['Lære', 'Undervise'], instruction: 'Handling' },
    { id: 'fr5-a49', type: 'Audio', question: 'Enseigner', answer: 'Undervise', options: ['Lære', 'Undervise'], instruction: 'Handling' },
    { id: 'fr5-a50', type: 'Audio', question: 'Réussir', answer: 'Lykkes', options: ['Lykkes', 'Fejle'], instruction: 'Handling' },
    { id: 'fr5-a51', type: 'Audio', question: 'Échouer', answer: 'Fejle', options: ['Lykkes', 'Fejle'], instruction: 'Handling' },
  ],
  6: [
    { id: 'fr6-a1', type: 'Audio', question: 'Un roman', answer: 'En roman', options: ['Digt', 'Roman', 'Novelle'], instruction: 'Litteratur' },
    { id: 'fr6-a2', type: 'Audio', question: 'Un conte de fées', answer: 'Et eventyr', options: ['Fabel', 'Eventyr'], instruction: 'Litteratur' },
    { id: 'fr6-a3', type: 'Audio', question: 'Un poème', answer: 'Et digt', options: ['Digt', 'Sang'], instruction: 'Litteratur' },
    { id: 'fr6-a4', type: 'Audio', question: 'Un auteur', answer: 'En forfatter', options: ['Læser', 'Forfatter'], instruction: 'Litteratur' },
    { id: 'fr6-a5', type: 'Audio', question: 'L’écriture', answer: 'Skriften', options: ['Talen', 'Skriften'], instruction: 'Sprog' },
    { id: 'fr6-a6', type: 'Audio', question: 'La lecture', answer: 'Læsningen', options: ['Skriften', 'Læsningen'], instruction: 'Sprog' },
    { id: 'fr6-a7', type: 'Audio', question: 'Analyser', answer: 'Analysere', options: ['Beskrive', 'Analysere'], instruction: 'Metode' },
    { id: 'fr6-a8', type: 'Audio', question: 'Comparer', answer: 'Sammenligne', options: ['Sammenligne', 'Adskille'], instruction: 'Metode' },
    { id: 'fr6-a9', type: 'Audio', question: 'Décrire', answer: 'Beskrive', options: ['Tegne', 'Beskrive'], instruction: 'Metode' },
    { id: 'fr6-a10', type: 'Audio', question: 'Expliquer', answer: 'Forklare', options: ['Spørge', 'Forklare'], instruction: 'Metode' },
    { id: 'fr6-a11', type: 'Audio', question: 'L’histoire', answer: 'Historien', options: ['Nutid', 'Historie'], instruction: 'Fag' },
    { id: 'fr6-a12', type: 'Audio', question: 'La géographie', answer: 'Geografi', options: ['Geografi', 'Historie'], instruction: 'Fag' },
    { id: 'fr6-a13', type: 'Audio', question: 'Les sciences', answer: 'Naturfag', options: ['Sprog', 'Videnskab'], instruction: 'Fag' },
    { id: 'fr6-a14', type: 'Audio', question: 'Les mathématiques', answer: 'Matematik', options: ['Matematik', 'Kunst'], instruction: 'Fag' },
    { id: 'fr6-a15', type: 'Audio', question: 'L’art', answer: 'Kunst', options: ['Kunst', 'Idræt'], instruction: 'Fag' },
    { id: 'fr6-a16', type: 'Audio', question: 'La musique', answer: 'Musik', options: ['Film', 'Musik'], instruction: 'Fag' },
    { id: 'fr6-a17', type: 'Audio', question: 'L’éducation physique', answer: 'Idræt', options: ['Idræt', 'Dans'], instruction: 'Fag' },
    { id: 'fr6-a18', type: 'Audio', question: 'Un citoyen', answer: 'En borger', options: ['Turist', 'Borger'], instruction: 'Samfund' },
    { id: 'fr6-a19', type: 'Audio', question: 'La démocratie', answer: 'Demokrati', options: ['Kongedømme', 'Demokrati'], instruction: 'Samfund' },
    { id: 'fr6-a20', type: 'Audio', question: 'Le vote', answer: 'Afstemning', options: ['Valg', 'Salg'], instruction: 'Samfund' },
    { id: 'fr6-a21', type: 'Audio', question: 'Élire', answer: 'Vælge/stemme', options: ['Kaste', 'Vælge'], instruction: 'Samfund' },
    { id: 'fr6-a22', type: 'Audio', question: 'Un roi', answer: 'En konge', options: ['Konge', 'Dronning'], instruction: 'Historie' },
    { id: 'fr6-a23', type: 'Audio', question: 'Une reine', answer: 'En dronning', options: ['Konge', 'Dronning'], instruction: 'Historie' },
    { id: 'fr6-a24', type: 'Audio', question: 'Un château', answer: 'Et slot', options: ['Hus', 'Slot'], instruction: 'Historie' },
    { id: 'fr6-a25', type: 'Audio', question: 'Une guerre', answer: 'En krig', options: ['Fred', 'Krig'], instruction: 'Historie' },
    { id: 'fr6-a26', type: 'Audio', question: 'La paix', answer: 'Fred', options: ['Fred', 'Krig'], instruction: 'Historie' },
    { id: 'fr6-a27', type: 'Audio', question: 'Une révolution', answer: 'En revolution', options: ['Evolution', 'Revolution'], instruction: 'Historie' },
    { id: 'fr6-a28', type: 'Audio', question: 'Un symbole', answer: 'Et symbol', options: ['Tegn', 'Symbol'], instruction: 'Begreb' },
    { id: 'fr6-a29', type: 'Audio', question: 'Le drapeau', answer: 'Flaget', options: ['Flaget', 'Landet'], instruction: 'Symbol' },
    { id: 'fr6-a30', type: 'Audio', question: 'L’hymne national', answer: 'Nationalsangen', options: ['Sangen', 'Flaget'], instruction: 'Symbol' },
    { id: 'fr6-a31', type: 'Audio', question: 'La culture', answer: 'Kultur', options: ['Natur', 'Kultur'], instruction: 'Begreb' },
    { id: 'fr6-a32', type: 'Audio', question: 'Une tradition', answer: 'En tradition', options: ['Nyhed', 'Tradition'], instruction: 'Begreb' },
    { id: 'fr6-a33', type: 'Audio', question: 'La diversité', answer: 'Mangfoldighed', options: ['Enhed', 'Mangfoldighed'], instruction: 'Værdi' },
    { id: 'fr6-a34', type: 'Audio', question: 'Le respect', answer: 'Respekt', options: ['Had', 'Respekt'], instruction: 'Værdi' },
    { id: 'fr6-a35', type: 'Audio', question: 'La tolérance', answer: 'Tolerance', options: ['Had', 'Tolerance'], instruction: 'Værdi' },
    { id: 'fr6-a36', type: 'Audio', question: 'Bénévole', answer: 'Frivillig', options: ['Betalt', 'Frivillig'], instruction: 'Samfund' },
    { id: 'fr6-a37', type: 'Audio', question: 'Une association', answer: 'En forening', options: ['Firma', 'Forening'], instruction: 'Samfund' },
    { id: 'fr6-a38', type: 'Audio', question: 'S’engager', answer: 'Forpligte sig/engagere', options: ['Slappe af', 'Engagere'], instruction: 'Handling' },
    { id: 'fr6-a39', type: 'Audio', question: 'Participer', answer: 'Deltage', options: ['Se på', 'Deltage'], instruction: 'Handling' },
    { id: 'fr6-a40', type: 'Audio', question: 'Collaborer', answer: 'Samarbejde', options: ['Kæmpe', 'Samarbejde'], instruction: 'Handling' },
    { id: 'fr6-a41', type: 'Audio', question: 'L’avenir', answer: 'Fremtiden', options: ['Fremtid', 'Datid'], instruction: 'Tid' },
    { id: 'fr6-a42', type: 'Audio', question: 'L’espoir', answer: 'Håbet', options: ['Had', 'Håb'], instruction: 'Følelse' },
    { id: 'fr6-a43', type: 'Audio', question: 'Une ambition', answer: 'En ambition', options: ['Drøm', 'Ambition'], instruction: 'Følelse' },
    { id: 'fr6-a44', type: 'Audio', question: 'Le courage', answer: 'Mod', options: ['Frygt', 'Mod'], instruction: 'Følelse' },
    { id: 'fr6-a45', type: 'Audio', question: 'La peur', answer: 'Frygt', options: ['Mod', 'Frygt'], instruction: 'Følelse' },
    { id: 'fr6-a46', type: 'Audio', question: 'Une opinion', answer: 'En mening', options: ['Fakta', 'Mening'], instruction: 'Tanke' },
    { id: 'fr6-a47', type: 'Audio', question: 'Un argument', answer: 'Et argument', options: ['Påstand', 'Argument'], instruction: 'Tanke' },
    { id: 'fr6-a48', type: 'Audio', question: 'Débattre', answer: 'Debattere', options: ['Skændes', 'Debattere'], instruction: 'Tanke' },
    { id: 'fr6-a49', type: 'Audio', question: 'Convaincre', answer: 'Overbevise', options: ['Spørge', 'Overbevise'], instruction: 'Tanke' },
    { id: 'fr6-a50', type: 'Audio', question: 'Partager', answer: 'Dele', options: ['Gemme', 'Dele'], instruction: 'Tanke' },
    { id: 'fr6-a51', type: 'Audio', question: 'Conclusion', answer: 'Afslutning', options: ['Start', 'Afslutning'], instruction: 'Tid' },
  ],
  7: [
    { id: 'fr7-a1', type: 'Audio', question: 'Le réalisme', answer: 'Realisme', options: ['Fantasie', 'Realisme'], instruction: 'Litteratur' },
    { id: 'fr7-a2', type: 'Audio', question: 'Le romantisme', answer: 'Romantikken', options: ['Romantik', 'Oplysning'], instruction: 'Litteratur' },
    { id: 'fr7-a3', type: 'Audio', question: 'La poésie moderne', answer: 'Moderne poesi', options: ['Klassisk', 'Moderne'], instruction: 'Litteratur' },
    { id: 'fr7-a4', type: 'Audio', question: 'Un dramaturge', answer: 'En dramatiker', options: ['Skuespiller', 'Dramatiker'], instruction: 'Litteratur' },
    { id: 'fr7-a5', type: 'Audio', question: 'Une tragédie', answer: 'En tragedie', options: ['Komedie', 'Tragedie'], instruction: 'Genre' },
    { id: 'fr7-a6', type: 'Audio', question: 'Une comédie', answer: 'En komedie', options: ['Komedie', 'Tragedie'], instruction: 'Genre' },
    { id: 'fr7-a7', type: 'Audio', question: 'L’ironie', answer: 'Ironi', options: ['Alvor', 'Ironi'], instruction: 'Billedsprog' },
    { id: 'fr7-a8', type: 'Audio', question: 'Une métaphore', answer: 'En metafor', options: ['Metafor', 'Billede'], instruction: 'Billedsprog' },
    { id: 'fr7-a9', type: 'Audio', question: 'Une comparaison', answer: 'En sammenligning', options: ['Modsætning', 'Sammenligning'], instruction: 'Billedsprog' },
    { id: 'fr7-a10', type: 'Audio', question: 'L’implication', answer: 'Implikation/inddragelse', options: ['Udelukkelse', 'Implikation'], instruction: 'Begreb' },
    { id: 'fr7-a11', type: 'Audio', question: 'La structure sociale', answer: 'Social struktur', options: ['Økonomi', 'Social struktur'], instruction: 'Samfund' },
    { id: 'fr7-a12', type: 'Audio', question: 'La hiérarchie', answer: 'Hierarki', options: ['Kaos', 'Hierarki'], instruction: 'Samfund' },
    { id: 'fr7-a13', type: 'Audio', question: 'Un conflit', answer: 'En konflikt', options: ['Fred', 'Konflikt'], instruction: 'Samfund' },
    { id: 'fr7-a14', type: 'Audio', question: 'La résolution', answer: 'Løsningen', options: ['Problem', 'Løsning'], instruction: 'Samfund' },
    { id: 'fr7-a15', type: 'Audio', question: 'Une négociation', answer: 'En forhandling', options: ['Krig', 'Forhandling'], instruction: 'Samfund' },
    { id: 'fr7-a16', type: 'Audio', question: 'Le développement durable', answer: 'Bæredygtig udvikling', options: ['Industri', 'Bæredygtighed'], instruction: 'Miljø' },
    { id: 'fr7-a17', type: 'Audio', question: 'Les énergies renouvelables', answer: 'Vedvarende energi', options: ['Kul', 'Vedvarende energi'], instruction: 'Miljø' },
    { id: 'fr7-a18', type: 'Audio', question: 'L’écologie', answer: 'Økologi', options: ['Økonomi', 'Økologi'], instruction: 'Miljø' },
    { id: 'fr7-a19', type: 'Audio', question: 'La biodiversité', answer: 'Biodiversitet', options: ['Forurening', 'Biodiversitet'], instruction: 'Miljø' },
    { id: 'fr7-a20', type: 'Audio', question: 'La préservation', answer: 'Bevarelse', options: ['Ødelæggelse', 'Bevarelse'], instruction: 'Miljø' },
    { id: 'fr7-a21', type: 'Audio', question: 'Une identité culturelle', answer: 'Kulturel identitet', options: ['Personlig', 'Kulturel'], instruction: 'Kultur' },
    { id: 'fr7-a22', type: 'Audio', question: 'Le patrimoine', answer: 'Kulturarv', options: ['Penge', 'Kulturarv'], instruction: 'Kultur' },
    { id: 'fr7-a23', type: 'Audio', question: 'Un monument', answer: 'Et monument', options: ['Hus', 'Monument'], instruction: 'Kultur' },
    { id: 'fr7-a24', type: 'Audio', question: 'La gastronomie', answer: 'Gastronomi/madkunst', options: ['Sport', 'Madkunst'], instruction: 'Kultur' },
    { id: 'fr7-a25', type: 'Audio', question: 'L’artisanat', answer: 'Håndværk', options: ['Industri', 'Håndværk'], instruction: 'Kultur' },
    { id: 'fr7-a26', type: 'Audio', question: 'Évoluer', answer: 'Udvikle sig/evolvere', options: ['Sidde fast', 'Evolvere'], instruction: 'Verber' },
    { id: 'fr7-a27', type: 'Audio', question: 'Transformer', answer: 'Forvandle', options: ['Beholde', 'Forvandle'], instruction: 'Verber' },
    { id: 'fr7-a28', type: 'Audio', question: 'Interpréter', answer: 'Fortolke', options: ['Læse', 'Fortolke'], instruction: 'Verber' },
    { id: 'fr7-a29', type: 'Audio', question: 'Évaluer', answer: 'Evaluere', options: ['Gætte', 'Evaluere'], instruction: 'Verber' },
    { id: 'fr7-a30', type: 'Audio', question: 'Justifier', answer: 'Begrunde', options: ['Sige', 'Begrunde'], instruction: 'Verber' },
    { id: 'fr7-a31', type: 'Audio', question: 'Globalisation', answer: 'Globalisering', options: ['Lokal', 'Globalisering'], instruction: 'Økonomi' },
    { id: 'fr7-a32', type: 'Audio', question: 'L’économie mondiale', answer: 'Verdensøkonomien', options: ['Lokal økonomi', 'Verdensøkonomi'], instruction: 'Økonomi' },
    { id: 'fr7-a33', type: 'Audio', question: 'La consommation', answer: 'Forbrug', options: ['Produktion', 'Forbrug'], instruction: 'Økonomi' },
    { id: 'fr7-a34', type: 'Audio', question: 'La production', answer: 'Produktion', options: ['Køb', 'Produktion'], instruction: 'Økonomi' },
    { id: 'fr7-a35', type: 'Audio', question: 'Le commerce équitable', answer: 'Fair trade', options: ['Gratis', 'Fair trade'], instruction: 'Økonomi' },
    { id: 'fr7-a36', type: 'Audio', question: 'Un média', answer: 'Et medie', options: ['Bog', 'Medie'], instruction: 'Kommunikation' },
    { id: 'fr7-a37', type: 'Audio', question: 'L’information', answer: 'Information', options: ['Løgn', 'Information'], instruction: 'Kommunikation' },
    { id: 'fr7-a38', type: 'Audio', question: 'La désinformation', answer: 'Desinformation', options: ['Sandhed', 'Falske nyheder'], instruction: 'Kommunikation' },
    { id: 'fr7-a39', type: 'Audio', question: 'La source', answer: 'Kilden', options: ['Bogen', 'Kilden'], instruction: 'Kommunikation' },
    { id: 'fr7-a40', type: 'Audio', question: 'Vérifier', answer: 'Tjekke/verificere', options: ['Tro', 'Verificere'], instruction: 'Kommunikation' },
    { id: 'fr7-a41', type: 'Audio', question: 'La psychologie', answer: 'Psykologi', options: ['Fysisk', 'Psykologi'], instruction: 'Videnskab' },
    { id: 'fr7-a42', type: 'Audio', question: 'Le subconscient', answer: 'Underbevidstheden', options: ['Sindet', 'Underbevidstheden'], instruction: 'Videnskab' },
    { id: 'fr7-a43', type: 'Audio', question: 'Une émotion', answer: 'En følelse', options: ['Tanke', 'Følelse'], instruction: 'Følelse' },
    { id: 'fr7-a44', type: 'Audio', question: 'La motivation', answer: 'Motivation', options: ['Lyst', 'Motivation'], instruction: 'Følelse' },
    { id: 'fr7-a45', type: 'Audio', question: 'L’empathie', answer: 'Empati', options: ['Had', 'Empati'], instruction: 'Følelse' },
    { id: 'fr7-a46', type: 'Audio', question: 'La solidarité', answer: 'Solidaritet', options: ['Ensomhed', 'Solidaritet'], instruction: 'Værdi' },
    { id: 'fr7-a47', type: 'Audio', question: 'La responsabilité', answer: 'Ansvar', options: ['Leg', 'Ansvar'], instruction: 'Værdi' },
    { id: 'fr7-a48', type: 'Audio', question: 'L’éthique', answer: 'Etik', options: ['Lov', 'Etik'], instruction: 'Værdi' },
    { id: 'fr7-a49', type: 'Audio', question: 'Le dilemme', answer: 'Dilemma', options: ['Valg', 'Dilemma'], instruction: 'Værdi' },
    { id: 'fr7-a50', type: 'Audio', question: 'La philosophie', answer: 'Filosofi', options: ['Tro', 'Filosofi'], instruction: 'Videnskab' },
    { id: 'fr7-a51', type: 'Audio', question: 'Fin du niveau', answer: 'Slut', options: ['Start', 'Slut'], instruction: 'Besked' },
  ],
  8: [
    { id: 'fr8-a1', type: 'Audio', question: 'La mondialisation', answer: 'Globalisering', options: ['International', 'Lokal'], instruction: 'Global' },
    { id: 'fr8-a2', type: 'Audio', question: 'Socio-économique', answer: 'Socioøkonomisk', options: ['Social', 'Økonomisk'], instruction: 'Begreb' },
    { id: 'fr8-a3', type: 'Audio', question: 'Infrastructure', answer: 'Infrastruktur', options: ['Natur', 'Infrastruktur'], instruction: 'Samfund' },
    { id: 'fr8-a4', type: 'Audio', question: 'Urbanisme', answer: 'Byplanlægning', options: ['Arkitektur', 'Byplanlægning'], instruction: 'Samfund' },
    { id: 'fr8-a5', type: 'Audio', question: 'Le développement local', answer: 'Lokal udvikling', options: ['Global', 'Lokal'], instruction: 'Samfund' },
    { id: 'fr8-a6', type: 'Audio', question: 'L’intelligence artificielle', answer: 'Kunstig intelligens', options: ['Menneskelig', 'Kunstig'], instruction: 'Teknologi' },
    { id: 'fr8-a7', type: 'Audio', question: 'Le cryptage', answer: 'Kryptering', options: ['Lås', 'Password', 'Kryptering'], instruction: 'Teknologi' },
    { id: 'fr8-a8', type: 'Audio', question: 'La cybersécurité', answer: 'Cybersikkerhed', options: ['Hacking', 'Sikkerhed'], instruction: 'Teknologi' },
    { id: 'fr8-a9', type: 'Audio', question: 'Le stockage de données', answer: 'Datatastring', options: ['Skyen', 'Data'], instruction: 'Teknologi' },
    { id: 'fr8-a10', type: 'Audio', question: 'L’algorithme', answer: 'Algoritmen', options: ['Koden', 'Algoritmen'], instruction: 'Teknologi' },
    { id: 'fr8-a11', type: 'Audio', question: 'Pragmatique', answer: 'Pragmatisk', options: ['Idealistisk', 'Pragmatisk'], instruction: 'Filosofi' },
    { id: 'fr8-a12', type: 'Audio', question: 'Idéologie', answer: 'Ideologi', options: ['Tanke', 'Ideologi'], instruction: 'Filosofi' },
    { id: 'fr8-a13', type: 'Audio', question: 'La métaphysique', answer: 'Metafysik', options: ['Fysik', 'Metafysik'], instruction: 'Filosofi' },
    { id: 'fr8-a14', type: 'Audio', question: 'L’existentialisme', answer: 'Eksistentialisme', options: ['Livet', 'Eksistentialisme'], instruction: 'Filosofi' },
    { id: 'fr8-a15', type: 'Audio', question: 'L’humanisme', answer: 'Humanisme', options: ['Natur', 'Mennesket'], instruction: 'Filosofi' },
    { id: 'fr8-a16', type: 'Audio', question: 'Le libre arbitre', answer: 'Den frie vilje', options: ['Skæbne', 'Fri vilje'], instruction: 'Filosofi' },
    { id: 'fr8-a17', type: 'Audio', question: 'Le déterminisme', answer: 'Determinisme', options: ['Skæbne', 'Fri vilje'], instruction: 'Filosofi' },
    { id: 'fr8-a18', type: 'Audio', question: 'Une synthèse', answer: 'En syntese', options: ['Analyse', 'Syntese'], instruction: 'Akademisk' },
    { id: 'fr8-a19', type: 'Audio', question: 'Une hypothèse', answer: 'En hypotese', options: ['Bevis', 'Gæt'], instruction: 'Akademisk' },
    { id: 'fr8-a20', type: 'Audio', question: 'Un paradigme', answer: 'Et paradigme', options: ['Model', 'Paradigme'], instruction: 'Akademisk' },
    { id: 'fr8-a21', type: 'Audio', question: 'Épistémologie', answer: 'Erkendelsesteori', options: ['Viden', 'Logik'], instruction: 'Akademisk' },
    { id: 'fr8-a22', type: 'Audio', question: 'Une thèse', answer: 'En tese', options: ['Svar', 'Tese'], instruction: 'Akademisk' },
    { id: 'fr8-a23', type: 'Audio', question: 'Un argumentaire', answer: 'En argumentation', options: ['Digt', 'Argumentation'], instruction: 'Akademisk' },
    { id: 'fr8-a24', type: 'Audio', question: 'Une corrélation', answer: 'En korrelation/sammenhæng', options: ['Forskel', 'Sammenhæng'], instruction: 'Akademisk' },
    { id: 'fr8-a25', type: 'Audio', question: 'Une contradiction', answer: 'En modstrid', options: ['Enighed', 'Modstrid'], instruction: 'Akademisk' },
    { id: 'fr8-a26', type: 'Audio', question: 'La souveraineté', answer: 'Suverænitet', options: ['Magt', 'Selvstændighed'], instruction: 'Politik' },
    { id: 'fr8-a27', type: 'Audio', question: 'Le fédéralisme', answer: 'Føderalisme', options: ['Union', 'Delstater'], instruction: 'Politik' },
    { id: 'fr8-a28', type: 'Audio', question: 'La diplomatie', answer: 'Diplomati', options: ['Krig', 'Forhandling'], instruction: 'Politik' },
    { id: 'fr8-a29', type: 'Audio', question: 'Une ambassade', answer: 'En ambassade', options: ['Hotel', 'Kontor', 'Ambassade'], instruction: 'Politik' },
    { id: 'fr8-a30', type: 'Audio', question: 'Le droit international', answer: 'Folkeret', options: ['Dansk lov', 'International lov'], instruction: 'Politik' },
    { id: 'fr8-a31', type: 'Audio', question: 'Littérature classique', answer: 'Klassisk litteratur', options: ['Gammel', 'Ny'], instruction: 'Kultur' },
    { id: 'fr8-a32', type: 'Audio', question: 'Un chef-d’œuvre', answer: 'Et mesterværk', options: ['Dårligt', 'Mesterværk'], instruction: 'Kultur' },
    { id: 'fr8-a33', type: 'Audio', question: 'L’avant-garde', answer: 'Avantgarde', options: ['Moderne', 'Traditionel'], instruction: 'Kultur' },
    { id: 'fr8-a34', type: 'Audio', question: 'Le surréalisme', answer: 'Surrealisme', options: ['Drømmeagtig', 'Virkelig'], instruction: 'Kultur' },
    { id: 'fr8-a35', type: 'Audio', question: 'L’impressionnisme', answer: 'Impressionisme', options: ['Lys og farve', 'Detaljer'], instruction: 'Kultur' },
    { id: 'fr8-a36', type: 'Audio', question: 'La Renaissance', answer: 'Renæssancen', options: ['Middelalder', 'Renæssance'], instruction: 'Historie' },
    { id: 'fr8-a37', type: 'Audio', question: 'Le siècle des Lumières', answer: 'Oplysningstiden', options: ['Mørketid', 'Oplysning'], instruction: 'Historie' },
    { id: 'fr8-a38', type: 'Audio', question: 'La colonisation', answer: 'Kolonisering', options: ['Bosættelse', 'Magtovertagelse'], instruction: 'Historie' },
    { id: 'fr8-a39', type: 'Audio', question: 'La décolonisation', answer: 'Afkolonisering', options: ['Frihed', 'Besættelse'], instruction: 'Historie' },
    { id: 'fr8-a40', type: 'Audio', question: 'Le monde francophone', answer: 'Den fransktalende verden', options: ['Europa', 'Hele verden'], instruction: 'Geografi' },
    { id: 'fr8-a41', type: 'Audio', question: 'L’urbanisation galopante', answer: 'Hurtig byvækst', options: ['Langsom', 'Hurtig'], instruction: 'Samfund' },
    { id: 'fr8-a42', type: 'Audio', question: 'La gentrification', answer: 'Gentrificering', options: ['Renovering', 'Nedrivning'], instruction: 'Samfund' },
    { id: 'fr8-a43', type: 'Audio', question: 'La ségrégation', answer: 'Segregering/adskillelse', options: ['Samling', 'Adskillelse'], instruction: 'Samfund' },
    { id: 'fr8-a44', type: 'Audio', question: 'L’intégration', answer: 'Integration', options: ['Integration', 'Isolation'], instruction: 'Samfund' },
    { id: 'fr8-a45', type: 'Audio', question: 'Le multiculturalisme', answer: 'Multikulturalisme', options: ['En kultur', 'Mange kulturer'], instruction: 'Samfund' },
    { id: 'fr8-a46', type: 'Audio', question: 'Une perspective critique', answer: 'Et kritisk perspektiv', options: ['Enighed', 'Kritik'], instruction: 'Tanke' },
    { id: 'fr8-a47', type: 'Audio', question: 'La remise en question', answer: 'At stille spørgsmålstegn', options: ['Tro', 'Tvivl'], instruction: 'Tanke' },
    { id: 'fr8-a48', type: 'Audio', question: 'L’objectivité', answer: 'Objektivitet', options: ['Følelse', 'Fakta'], instruction: 'Tanke' },
    { id: 'fr8-a49', type: 'Audio', question: 'La subjectivité', answer: 'Subjektivitet', options: ['Følelse', 'Fakta'], instruction: 'Tanke' },
    { id: 'fr8-a50', type: 'Audio', question: 'Le raisonnement', answer: 'Ræsonnement/tanke', options: ['Gæt', 'Logik'], instruction: 'Tanke' },
    { id: 'fr8-a51', type: 'Audio', question: 'Examen final', answer: 'Slut', options: ['Prøve', 'Slut'], instruction: 'Info' },
  ],
  9: [
    { id: 'fr9-a1', type: 'Audio', question: 'La condition humaine', answer: 'Menneskets vilkår', options: ['Livet', 'Vilkår'], instruction: 'Filosofi' },
    { id: 'fr9-a2', type: 'Audio', question: 'L’éthique professionnelle', answer: 'Professionel etik', options: ['Arbejde', 'Moral'], instruction: 'Profession' },
    { id: 'fr9-a3', type: 'Audio', question: 'La responsabilité sociale', answer: 'Socialt ansvar', options: ['Firma', 'Samfund'], instruction: 'Samfund' },
    { id: 'fr9-a4', type: 'Audio', question: 'Le marché du travail', answer: 'Arbejdsmarkedet', options: ['Job', 'Salg'], instruction: 'Samfund' },
    { id: 'fr9-a5', type: 'Audio', question: 'Le chômage', answer: 'Arbejdsløshed', options: ['Arbejde', 'Ledighed'], instruction: 'Samfund' },
    { id: 'fr9-a6', type: 'Audio', question: 'La croissance économique', answer: 'Økonomisk vækst', options: ['Fald', 'Vækst'], instruction: 'Økonomi' },
    { id: 'fr9-a7', type: 'Audio', question: 'L’inflation', answer: 'Inflation', options: ['Billigere', 'Dyrere'], instruction: 'Økonomi' },
    { id: 'fr9-a8', type: 'Audio', question: 'Le pouvoir d’achat', answer: 'Købekraft', options: ['Penge', 'Magt'], instruction: 'Økonomi' },
    { id: 'fr9-a9', type: 'Audio', question: 'La dette publique', answer: 'Statsgæld', options: ['Formue', 'Gæld'], instruction: 'Politik' },
    { id: 'fr9-a10', type: 'Audio', question: 'La fiscalité', answer: 'Beskatning', options: ['Skat', 'Løn'], instruction: 'Politik' },
    { id: 'fr9-a11', type: 'Audio', question: 'L’innovation disruptive', answer: 'Banebrydende innovation', options: ['Kopi', 'Nyskabelse'], instruction: 'Teknologi' },
    { id: 'fr9-a12', type: 'Audio', question: 'La biotechnologie', answer: 'Bioteknologi', options: ['Biologi', 'Teknologi'], instruction: 'Videnskab' },
    { id: 'fr9-a13', type: 'Audio', question: 'Le génie génétique', answer: 'Gensplejsning', options: ['DNA', 'Gensplejsning'], instruction: 'Videnskab' },
    { id: 'fr9-a14', type: 'Audio', question: 'L’éthique des sciences', answer: 'Videnskabsetik', options: ['Regler', 'Moral'], instruction: 'Videnskab' },
    { id: 'fr9-a15', type: 'Audio', question: 'Le transhumanisme', answer: 'Transhumanisme', options: ['Robot', 'Menneske'], instruction: 'Filosofi' },
    { id: 'fr9-a16', type: 'Audio', question: 'La géopolitique', answer: 'Geopolitik', options: ['Landkort', 'Magtspil'], instruction: 'Politik' },
    { id: 'fr9-a17', type: 'Audio', question: 'Les relations internationales', answer: 'Internationale relationer', options: ['Indenrigs', 'Udenrigs'], instruction: 'Politik' },
    { id: 'fr9-a18', type: 'Audio', question: 'Un traité', answer: 'En traktat', options: ['Aftale', 'Krig'], instruction: 'Politik' },
    { id: 'fr9-a19', type: 'Audio', question: 'Une alliance', answer: 'En alliance', options: ['Venskab', 'Alliance'], instruction: 'Politik' },
    { id: 'fr9-a20', type: 'Audio', question: 'La diplomatie culturelle', answer: 'Kulturel diplomati', options: ['Sprog', 'Kultur'], instruction: 'Politik' },
    { id: 'fr9-a21', type: 'Audio', question: 'L’analyse textuelle', answer: 'Tekstanalyse', options: ['Læsning', 'Dykning i teksten'], instruction: 'Litteratur' },
    { id: 'fr9-a22', type: 'Audio', question: 'L’intertextualité', answer: 'Intertekstualitet', options: ['Bøger', 'Referencer'], instruction: 'Litteratur' },
    { id: 'fr9-a23', type: 'Audio', question: 'Le courant littéraire', answer: 'Litterær strømning', options: ['Bølge', 'Stilart'], instruction: 'Litteratur' },
    { id: 'fr9-a24', type: 'Audio', question: 'L’engagement de l’auteur', answer: 'Forfatterens engagement', options: ['Skrift', 'Holdning'], instruction: 'Litteratur' },
    { id: 'fr9-a25', type: 'Audio', question: 'La réception critique', answer: 'Kritisk modtagelse', options: ['Anmeldelse', 'Læsning'], instruction: 'Litteratur' },
    { id: 'fr9-a26', type: 'Audio', question: 'L’esthétique', answer: 'Æstetik', options: ['Udseende', 'Skønhed'], instruction: 'Kunst' },
    { id: 'fr9-a27', type: 'Audio', question: 'La composition', answer: 'Komposition', options: ['Farve', 'Opbygning'], instruction: 'Kunst' },
    { id: 'fr9-a28', type: 'Audio', question: 'Le contraste', answer: 'Kontrast', options: ['Forskel', 'Lighed'], instruction: 'Kunst' },
    { id: 'fr9-a29', type: 'Audio', question: 'Le symbolisme abstrait', answer: 'Abstrakt symbolisme', options: ['Tegn', 'Drømme'], instruction: 'Kunst' },
    { id: 'fr9-a30', type: 'Audio', question: 'Une œuvre d’art', answer: 'Et kunstværk', options: ['Maleri', 'Billede'], instruction: 'Kunst' },
    { id: 'fr9-a31', type: 'Audio', question: 'La réflexion critique', answer: 'Kritisk refleksion', options: ['Tanke', 'Overvejelse'], instruction: 'Tanke' },
    { id: 'fr9-a32', type: 'Audio', question: 'Le jugement moral', answer: 'Moralsk dom', options: ['Valg', 'Dom'], instruction: 'Tanke' },
    { id: 'fr9-a33', type: 'Audio', question: 'Le libre-penseur', answer: 'Fritænker', options: ['Religiøs', 'Uafhængig'], instruction: 'Tanke' },
    { id: 'fr9-a34', type: 'Audio', question: 'La rhétorique', answer: 'Retorik', options: ['Tale', 'Skrift'], instruction: 'Tanke' },
    { id: 'fr9-a35', type: 'Audio', question: 'La dialectique', answer: 'Dialektik', options: ['Samtale', 'Logisk dialog'], instruction: 'Tanke' },
    { id: 'fr9-a36', type: 'Audio', question: 'L’aliénation', answer: 'Fremmedgørelse', options: ['Venskab', 'Fjernhed'], instruction: 'Psykologi' },
    { id: 'fr9-a37', type: 'Audio', question: 'L’inconscient collectif', answer: 'Den kollektive underbevidsthed', options: ['Drømme', 'Fælles minder'], instruction: 'Psykologi' },
    { id: 'fr9-a38', type: 'Audio', question: 'Le complexe d’Oedipe', answer: 'Ødipuskompleks', options: ['Familie', 'Psykologi'], instruction: 'Psykologi' },
    { id: 'fr9-a39', type: 'Audio', question: 'La résilience', answer: 'Modstandskraft/resiliens', options: ['Svaghed', 'Styrke'], instruction: 'Psykologi' },
    { id: 'fr9-a40', type: 'Audio', question: 'La catharsis', answer: 'Katarsis/udrensning', options: ['Film', 'Renselse'], instruction: 'Psykologi' },
    { id: 'fr9-a41', type: 'Audio', question: 'La sociologie', answer: 'Sociologi', options: ['Historie', 'Samfundslære'], instruction: 'Samfund' },
    { id: 'fr9-a42', type: 'Audio', question: 'Le capital social', answer: 'Social kapital', options: ['Penge', 'Netværk'], instruction: 'Samfund' },
    { id: 'fr9-a43', type: 'Audio', question: 'La stratification sociale', answer: 'Social lagdeling', options: ['Klasser', 'Grupper'], instruction: 'Samfund' },
    { id: 'fr9-a44', type: 'Audio', question: 'L’urbanisme durable', answer: 'Bæredygtig byudvikling', options: ['Grøn by', 'Beton'], instruction: 'Miljø' },
    { id: 'fr9-a45', type: 'Audio', question: 'La justice climatique', answer: 'Klimaretfærdighed', options: ['Vejr', 'Ansvar'], instruction: 'Miljø' },
    { id: 'fr9-a46', type: 'Audio', question: 'Un postulat', answer: 'En forudsætning/postulat', options: ['Svar', 'Tanke'], instruction: 'Logik' },
    { id: 'fr9-a47', type: 'Audio', question: 'Un syllogisme', answer: 'En syllogisme/logisk slutning', options: ['Fejl', 'Logik'], instruction: 'Logik' },
    { id: 'fr9-a48', type: 'Audio', question: 'Une tautologie', answer: 'En tautologi/selvfølgelighed', options: ['Gåde', 'Gentagelse'], instruction: 'Logik' },
    { id: 'fr9-a49', type: 'Audio', question: 'L’inférence', answer: 'Følgeslutning', options: ['Gæt', 'Slutning'], instruction: 'Logik' },
    { id: 'fr9-a50', type: 'Audio', question: 'La cohérence', answer: 'Sammenhængskraft', options: ['Rod', 'Orden'], instruction: 'Logik' },
    { id: 'fr9-a51', type: 'Audio', question: 'Adieu', answer: 'Farvel (for altid)', options: ['Farvel', 'Goddag'], instruction: 'Hilsen' },
  ],
};
