/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const FRANSK_AUDIO_P1: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'fr0-a1', type: 'Audio', question: 'Un', answer: '1', options: ['1', '2', '3'], instruction: 'Tal' },
    { id: 'fr0-a2', type: 'Audio', question: 'Deux', answer: '2', options: ['1', '2', '3'], instruction: 'Tal' },
    { id: 'fr0-a3', type: 'Audio', question: 'Trois', answer: '3', options: ['1', '2', '3'], instruction: 'Tal' },
    { id: 'fr0-a4', type: 'Audio', question: 'Quatre', answer: '4', options: ['4', '5', '6'], instruction: 'Tal' },
    { id: 'fr0-a5', type: 'Audio', question: 'Cinq', answer: '5', options: ['4', '5', '6'], instruction: 'Tal' },
    { id: 'fr0-a6', type: 'Audio', question: 'Six', answer: '6', options: ['4', '5', '6'], instruction: 'Tal' },
    { id: 'fr0-a7', type: 'Audio', question: 'Sept', answer: '7', options: ['7', '8', '9'], instruction: 'Tal' },
    { id: 'fr0-a8', type: 'Audio', question: 'Huit', answer: '8', options: ['7', '8', '9'], instruction: 'Tal' },
    { id: 'fr0-a9', type: 'Audio', question: 'Neuf', answer: '9', options: ['7', '8', '9'], instruction: 'Tal' },
    { id: 'fr0-a10', type: 'Audio', question: 'Dix', answer: '10', options: ['8', '9', '10'], instruction: 'Tal' },
    { id: 'fr0-a11', type: 'Audio', question: 'Rouge', answer: 'Rød', options: ['Rød', 'Blå', 'Gul'], instruction: 'Farve' },
    { id: 'fr0-a12', type: 'Audio', question: 'Bleu', answer: 'Blå', options: ['Rød', 'Blå', 'Gul'], instruction: 'Farve' },
    { id: 'fr0-a13', type: 'Audio', question: 'Jaune', answer: 'Gul', options: ['Rød', 'Blå', 'Gul'], instruction: 'Farve' },
    { id: 'fr0-a14', type: 'Audio', question: 'Vert', answer: 'Grøn', options: ['Grøn', 'Sort', 'Hvid'], instruction: 'Farve' },
    { id: 'fr0-a15', type: 'Audio', question: 'Noir', answer: 'Sort', options: ['Grøn', 'Sort', 'Hvid'], instruction: 'Farve' },
    { id: 'fr0-a16', type: 'Audio', question: 'Blanc', answer: 'Hvid', options: ['Grøn', 'Sort', 'Hvid'], instruction: 'Farve' },
    { id: 'fr0-a17', type: 'Audio', question: 'Bonjour', answer: 'Goddag', options: ['Goddag', 'Farvel', 'Tak'], instruction: 'Hilsen' },
    { id: 'fr0-a18', type: 'Audio', question: 'Salut', answer: 'Hej', options: ['Hej', 'Farvel', 'Tak'], instruction: 'Hilsen' },
    { id: 'fr0-a19', type: 'Audio', question: 'Merci', answer: 'Tak', options: ['Hej', 'Tak', 'Ja'], instruction: 'Hilsen' },
    { id: 'fr0-a20', type: 'Audio', question: 'Oui', answer: 'Ja', options: ['Ja', 'Nej', 'Måske'], instruction: 'Svar' },
    { id: 'fr0-a21', type: 'Audio', question: 'Non', answer: 'Nej', options: ['Ja', 'Nej', 'Tak'], instruction: 'Svar' },
    { id: 'fr0-a22', type: 'Audio', question: 'Chat', answer: 'Kat', options: ['Hund', 'Kat', 'Fugl'], instruction: 'Dyr' },
    { id: 'fr0-a23', type: 'Audio', question: 'Chien', answer: 'Hund', options: ['Hund', 'Kat', 'Fugl'], instruction: 'Dyr' },
    { id: 'fr0-a24', type: 'Audio', question: 'Oiseau', answer: 'Fugl', options: ['Hund', 'Kat', 'Fugl'], instruction: 'Dyr' },
    { id: 'fr0-a25', type: 'Audio', question: 'Poisson', answer: 'Fisk', options: ['Fisk', 'Slange', 'Ko'], instruction: 'Dyr' },
    { id: 'fr0-a26', type: 'Audio', question: 'Pomme', answer: 'Æble', options: ['Æble', 'Banan', 'Pære'], instruction: 'Frugt' },
    { id: 'fr0-a27', type: 'Audio', question: 'Banane', answer: 'Banan', options: ['Æble', 'Banan', 'Pære'], instruction: 'Frugt' },
    { id: 'fr0-a28', type: 'Audio', question: 'Lait', answer: 'Mælk', options: ['Mælk', 'Vand', 'Juice'], instruction: 'Drik' },
    { id: 'fr0-a29', type: 'Audio', question: 'Eau', answer: 'Vand', options: ['Mælk', 'Vand', 'Juice'], instruction: 'Drik' },
    { id: 'fr0-a30', type: 'Audio', question: 'Livre', answer: 'Bog', options: ['Bog', 'Pen', 'Taske'], instruction: 'Skole' },
    { id: 'fr0-a31', type: 'Audio', question: 'Maison', answer: 'Hus', options: ['Hus', 'Vej', 'Have'], instruction: 'Sted' },
    { id: 'fr0-a32', type: 'Audio', question: 'Fille', answer: 'Pige', options: ['Dreng', 'Pige', 'Barn'], instruction: 'Person' },
    { id: 'fr0-a33', type: 'Audio', question: 'Garçon', answer: 'Dreng', options: ['Dreng', 'Pige', 'Barn'], instruction: 'Person' },
    { id: 'fr0-a34', type: 'Audio', question: 'Maman', answer: 'Mor', options: ['Mor', 'Far', 'Bror'], instruction: 'Familie' },
    { id: 'fr0-a35', type: 'Audio', question: 'Papa', answer: 'Far', options: ['Mor', 'Far', 'Bror'], instruction: 'Familie' },
    { id: 'fr0-a36', type: 'Audio', question: 'Ciel', answer: 'Himmel', options: ['Himmel', 'Sol', 'Regn'], instruction: 'Natur' },
    { id: 'fr0-a37', type: 'Audio', question: 'Soleil', answer: 'Sol', options: ['Himmel', 'Sol', 'Regn'], instruction: 'Natur' },
    { id: 'fr0-a38', type: 'Audio', question: 'Fleur', answer: 'Blomst', options: ['Blomst', 'Træ', 'Græs'], instruction: 'Natur' },
    { id: 'fr0-a39', type: 'Audio', question: 'Pain', answer: 'Brød', options: ['Brød', 'Ost', 'Kød'], instruction: 'Mad' },
    { id: 'fr0-a40', type: 'Audio', question: 'Fromage', answer: 'Ost', options: ['Brød', 'Ost', 'Kød'], instruction: 'Mad' },
    { id: 'fr0-a41', type: 'Audio', question: 'Ecole', answer: 'Skole', options: ['Skole', 'Kirke', 'Park'], instruction: 'Sted' },
    { id: 'fr0-a42', type: 'Audio', question: 'Parler', answer: 'Tale', options: ['Tale', 'Løbe', 'Spise'], instruction: 'Handling' },
    { id: 'fr0-a43', type: 'Audio', question: 'Manger', answer: 'Spise', options: ['Tale', 'Løbe', 'Spise'], instruction: 'Handling' },
    { id: 'fr0-a44', type: 'Audio', question: 'Courir', answer: 'Løbe', options: ['Tale', 'Løbe', 'Spise'], instruction: 'Handling' },
    { id: 'fr0-a45', type: 'Audio', question: 'Petit', answer: 'Lille', options: ['Lille', 'Stor'], instruction: 'Modsætning' },
    { id: 'fr0-a46', type: 'Audio', question: 'Grand', answer: 'Stor', options: ['Lille', 'Stor'], instruction: 'Modsætning' },
    { id: 'fr0-a47', type: 'Audio', question: 'Bonne nuit', answer: 'Godnat', options: ['Goddag', 'Godnat'], instruction: 'Hilsen' },
    { id: 'fr0-a48', type: 'Audio', question: 'Aurevoir', answer: 'Farvel', options: ['Goddag', 'Farvel'], instruction: 'Hilsen' },
    { id: 'fr0-a49', type: 'Audio', question: 'Velo', answer: 'Cykel', options: ['Bil', 'Cykel', 'Tog'], instruction: 'Transport' },
    { id: 'fr0-a50', type: 'Audio', question: 'Auto', answer: 'Bil', options: ['Bil', 'Cykel', 'Tog'], instruction: 'Transport' },
    { id: 'fr0-a51', type: 'Audio', question: 'Avion', answer: 'Fly', options: ['Skov', 'Fly', 'Hav'], instruction: 'Transport' },
  ],
  1: [
    { id: 'fr1-a1', type: 'Audio', question: 'Onze', answer: '11', options: ['11', '12', '13'], instruction: 'Tal' },
    { id: 'fr1-a2', type: 'Audio', question: 'Douze', answer: '12', options: ['11', '12', '13'], instruction: 'Tal' },
    { id: 'fr1-a3', type: 'Audio', question: 'Treize', answer: '13', options: ['11', '12', '13'], instruction: 'Tal' },
    { id: 'fr1-a4', type: 'Audio', question: 'Quatorze', answer: '14', options: ['14', '15', '16'], instruction: 'Tal' },
    { id: 'fr1-a5', type: 'Audio', question: 'Quinze', answer: '15', options: ['14', '15', '16'], instruction: 'Tal' },
    { id: 'fr1-a6', type: 'Audio', question: 'Seize', answer: '16', options: ['14', '15', '16'], instruction: 'Tal' },
    { id: 'fr1-a7', type: 'Audio', question: 'Dix-sept', answer: '17', options: ['17', '18', '19'], instruction: 'Tal' },
    { id: 'fr1-a8', type: 'Audio', question: 'Dix-huit', answer: '18', options: ['17', '18', '19'], instruction: 'Tal' },
    { id: 'fr1-a9', type: 'Audio', question: 'Dix-neuf', answer: '19', options: ['17', '18', '19'], instruction: 'Tal' },
    { id: 'fr1-a10', type: 'Audio', question: 'Vingt', answer: '20', options: ['10', '20', '30'], instruction: 'Tal' },
    { id: 'fr1-a11', type: 'Audio', question: 'Lundi', answer: 'Mandag', options: ['Mandag', 'Tirsdag', 'Onsdag'], instruction: 'Ugedag' },
    { id: 'fr1-a12', type: 'Audio', question: 'Mardi', answer: 'Tirsdag', options: ['Mandag', 'Tirsdag', 'Onsdag'], instruction: 'Ugedag' },
    { id: 'fr1-a13', type: 'Audio', question: 'Mercredi', answer: 'Onsdag', options: ['Mandag', 'Tirsdag', 'Onsdag'], instruction: 'Ugedag' },
    { id: 'fr1-a14', type: 'Audio', question: 'Jeudi', answer: 'Torsdag', options: ['Torsdag', 'Fredag', 'Lørdag'], instruction: 'Ugedag' },
    { id: 'fr1-a15', type: 'Audio', question: 'Vendredi', answer: 'Fredag', options: ['Torsdag', 'Fredag', 'Lørdag'], instruction: 'Ugedag' },
    { id: 'fr1-a16', type: 'Audio', question: 'Samedi', answer: 'Lørdag', options: ['Torsdag', 'Fredag', 'Lørdag'], instruction: 'Ugedag' },
    { id: 'fr1-a17', type: 'Audio', question: 'Dimanche', answer: 'Søndag', options: ['Fredag', 'Lørdag', 'Søndag'], instruction: 'Ugedag' },
    { id: 'fr1-a18', type: 'Audio', question: 'La tête', answer: 'Hovedet', options: ['Hovedet', 'Foden', 'Hånden'], instruction: 'Krop' },
    { id: 'fr1-a19', type: 'Audio', question: 'La main', answer: 'Hånden', options: ['Hovedet', 'Foden', 'Hånden'], instruction: 'Krop' },
    { id: 'fr1-a20', type: 'Audio', question: 'Le pied', answer: 'Foden', options: ['Hovedet', 'Foden', 'Hånden'], instruction: 'Krop' },
    { id: 'fr1-a21', type: 'Audio', question: 'Le nez', answer: 'Næsen', options: ['Næsen', 'Øjet', 'Øret'], instruction: 'Krop' },
    { id: 'fr1-a22', type: 'Audio', question: 'L’œil', answer: 'Øjet', options: ['Næsen', 'Øjet', 'Øret'], instruction: 'Krop' },
    { id: 'fr1-a23', type: 'Audio', question: 'S’il vous plaît', answer: 'Vær så venlig', options: ['Tak', 'Vær så venlig', 'Farvel'], instruction: 'Høflighed' },
    { id: 'fr1-a24', type: 'Audio', question: 'De rien', answer: 'Selv tak', options: ['Selv tak', 'Undskyld'], instruction: 'Høflighed' },
    { id: 'fr1-a25', type: 'Audio', question: 'Pardon', answer: 'Undskyld', options: ['Undskyld', 'Tak'], instruction: 'Høflighed' },
    { id: 'fr1-a26', type: 'Audio', question: 'Un pantalon', answer: 'Bukser', options: ['Bukser', 'Skjorte', 'Jakke'], instruction: 'Tøj' },
    { id: 'fr1-a27', type: 'Audio', question: 'Une chemise', answer: 'Skjorte', options: ['Bukser', 'Skjorte', 'Jakke'], instruction: 'Tøj' },
    { id: 'fr1-a28', type: 'Audio', question: 'Des chaussures', answer: 'Sko', options: ['Sko', 'Sokker', 'Hat'], instruction: 'Tøj' },
    { id: 'fr1-a29', type: 'Audio', question: 'Un chapeau', answer: 'En hat', options: ['Sko', 'Hat'], instruction: 'Tøj' },
    { id: 'fr1-a30', type: 'Audio', question: 'Frère', answer: 'Bror', options: ['Bror', 'Søster', 'Baby'], instruction: 'Familie' },
    { id: 'fr1-a31', type: 'Audio', question: 'Sœur', answer: 'Søster', options: ['Bror', 'Søster', 'Baby'], instruction: 'Familie' },
    { id: 'fr1-a32', type: 'Audio', question: 'Grand-père', answer: 'Bedstefar', options: ['Bedstefar', 'Bedstemor'], instruction: 'Familie' },
    { id: 'fr1-a33', type: 'Audio', question: 'Grand-mère', answer: 'Bedstemor', options: ['Bedstefar', 'Bedstemor'], instruction: 'Familie' },
    { id: 'fr1-a34', type: 'Audio', question: 'Un cahier', answer: 'Et hæfte', options: ['Et hæfte', 'En bog', 'En pen'], instruction: 'Skole' },
    { id: 'fr1-a35', type: 'Audio', question: 'Un stylo', answer: 'En pen', options: ['Et hæfte', 'En bog', 'En pen'], instruction: 'Skole' },
    { id: 'fr1-a36', type: 'Audio', question: 'Une règle', answer: 'En lineal', options: ['Lineal', 'Viskelæder'], instruction: 'Skole' },
    { id: 'fr1-a37', type: 'Audio', question: 'Une gomme', answer: 'Et viskelæder', options: ['Lineal', 'Viskelæder'], instruction: 'Skole' },
    { id: 'fr1-a38', type: 'Audio', question: 'Il pleut', answer: 'Det regner', options: ['Det regner', 'Solen skinner', 'Det sner'], instruction: 'Vejr' },
    { id: 'fr1-a39', type: 'Audio', question: 'Il fait beau', answer: 'Det er godt vejr', options: ['Det regner', 'Det er godt vejr'], instruction: 'Vejr' },
    { id: 'fr1-a40', type: 'Audio', question: 'Il y a du vent', answer: 'Det blæser', options: ['Det blæser', 'Det lyner'], instruction: 'Vejr' },
    { id: 'fr1-a41', type: 'Audio', question: 'Je suis content', answer: 'Jeg er glad', options: ['Jeg er glad', 'Jeg er trist'], instruction: 'Humør' },
    { id: 'fr1-a42', type: 'Audio', question: 'Je suis triste', answer: 'Jeg er trist', options: ['Jeg er glad', 'Jeg er trist'], instruction: 'Humør' },
    { id: 'fr1-a43', type: 'Audio', question: 'J’ai faim', answer: 'Jeg er sulten', options: ['Jeg er sulten', 'Jeg er tørstig'], instruction: 'Behov' },
    { id: 'fr1-a44', type: 'Audio', question: 'J’ai soif', answer: 'Jeg er tørstig', options: ['Jeg er sulten', 'Jeg er tørstig'], instruction: 'Behov' },
    { id: 'fr1-a45', type: 'Audio', question: 'Regardez!', answer: 'Se!', options: ['Se!', 'Lyt!', 'Kom!'], instruction: 'Ordre' },
    { id: 'fr1-a46', type: 'Audio', question: 'Ecoutez!', answer: 'Lyt!', options: ['Se!', 'Lyt!', 'Kom!'], instruction: 'Ordre' },
    { id: 'fr1-a47', type: 'Audio', question: 'Asseyez-vous', answer: 'Sid ned', options: ['Rejs jer', 'Sid ned'], instruction: 'Ordre' },
    { id: 'fr1-a48', type: 'Audio', question: 'Levez-vous', answer: 'Rejs jer', options: ['Rejs jer', 'Sid ned'], instruction: 'Ordre' },
    { id: 'fr1-a49', type: 'Audio', question: 'Un jouet', answer: 'Legetøj', options: ['Legetøj', 'Mad', 'Bil'], instruction: 'Ting' },
    { id: 'fr1-a50', type: 'Audio', question: 'Un ballon', answer: 'En bold', options: ['Bold', 'Dukke'], instruction: 'Ting' },
    { id: 'fr1-a51', type: 'Audio', question: 'Une poupée', answer: 'En dukke', options: ['Bold', 'Dukke'], instruction: 'Ting' },
  ],
  2: [
    { id: 'fr2-a1', type: 'Audio', question: 'Vingt-et-un', answer: '21', options: ['21', '22', '31'], instruction: 'Tal' },
    { id: 'fr2-a2', type: 'Audio', question: 'Trente', answer: '30', options: ['20', '30', '40'], instruction: 'Tal' },
    { id: 'fr2-a3', type: 'Audio', question: 'Quarante', answer: '40', options: ['30', '40', '50'], instruction: 'Tal' },
    { id: 'fr2-a4', type: 'Audio', question: 'Cinquante', answer: '50', options: ['40', '50', '60'], instruction: 'Tal' },
    { id: 'fr2-a5', type: 'Audio', question: 'Janvier', answer: 'Januar', options: ['Januar', 'Februar', 'Marts'], instruction: 'Måned' },
    { id: 'fr2-a6', type: 'Audio', question: 'Février', answer: 'Februar', options: ['Januar', 'Februar', 'Marts'], instruction: 'Måned' },
    { id: 'fr2-a7', type: 'Audio', question: 'Mars', answer: 'Marts', options: ['Januar', 'Februar', 'Marts'], instruction: 'Måned' },
    { id: 'fr2-a8', type: 'Audio', question: 'Avril', answer: 'April', options: ['April', 'Maj', 'Juni'], instruction: 'Måned' },
    { id: 'fr2-a9', type: 'Audio', question: 'Mai', answer: 'Maj', options: ['April', 'Maj', 'Juni'], instruction: 'Måned' },
    { id: 'fr2-a10', type: 'Audio', question: 'Juin', answer: 'Juni', options: ['April', 'Maj', 'Juni'], instruction: 'Måned' },
    { id: 'fr2-a11', type: 'Audio', question: 'Juillet', answer: 'Juli', options: ['Juli', 'August', 'September'], instruction: 'Måned' },
    { id: 'fr2-a12', type: 'Audio', question: 'Août', answer: 'August', options: ['Juli', 'August', 'September'], instruction: 'Måned' },
    { id: 'fr2-a13', type: 'Audio', question: 'Septembre', answer: 'September', options: ['Juli', 'August', 'September'], instruction: 'Måned' },
    { id: 'fr2-a14', type: 'Audio', question: 'Octobre', answer: 'Oktober', options: ['Oktober', 'November', 'December'], instruction: 'Måned' },
    { id: 'fr2-a15', type: 'Audio', question: 'Novembre', answer: 'November', options: ['Oktober', 'November', 'December'], instruction: 'Måned' },
    { id: 'fr2-a16', type: 'Audio', question: 'Décembre', answer: 'December', options: ['Oktober', 'November', 'December'], instruction: 'Måned' },
    { id: 'fr2-a17', type: 'Audio', question: 'Le printemps', answer: 'Forår', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Årstid' },
    { id: 'fr2-a18', type: 'Audio', question: 'L’été', answer: 'Sommer', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Årstid' },
    { id: 'fr2-a19', type: 'Audio', question: 'L’automne', answer: 'Efterår', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Årstid' },
    { id: 'fr2-a20', type: 'Audio', question: 'L’hiver', answer: 'Vinter', options: ['Forår', 'Sommer', 'Efterår', 'Vinter'], instruction: 'Årstid' },
    { id: 'fr2-a21', type: 'Audio', question: 'Une horloge', answer: 'Et ur', options: ['Ur', 'Billede', 'Væg'], instruction: 'Ting' },
    { id: 'fr2-a22', type: 'Audio', question: 'Quelle heure est-il?', answer: 'Hvad er klokken?', options: ['Hvor er du?', 'Hvad er klokken?'], instruction: 'Udtryk' },
    { id: 'fr2-a23', type: 'Audio', question: 'Il est midi', answer: 'Den er 12 (middag)', options: ['12 dag', '12 nat'], instruction: 'Tid' },
    { id: 'fr2-a24', type: 'Audio', question: 'Il est minuit', answer: 'Den er 12 (nat)', options: ['12 dag', '12 nat'], instruction: 'Tid' },
    { id: 'fr2-a25', type: 'Audio', question: 'Une cuisine', answer: 'Et køkken', options: ['Køkken', 'Stue', 'Bad'], instruction: 'Hjem' },
    { id: 'fr2-a26', type: 'Audio', question: 'Un salon', answer: 'En stue', options: ['Køkken', 'Stue', 'Bad'], instruction: 'Hjem' },
    { id: 'fr2-a27', type: 'Audio', question: 'Une chambre', answer: 'Et værelse', options: ['Værelse', 'Have'], instruction: 'Hjem' },
    { id: 'fr2-a28', type: 'Audio', question: 'La salle de bain', answer: 'Badeværelse', options: ['Bad', 'Køkken'], instruction: 'Hjem' },
    { id: 'fr2-a29', type: 'Audio', question: 'J’habite à...', answer: 'Jeg bor i...', options: ['Jeg bor i', 'Jeg er fra'], instruction: 'Præsentation' },
    { id: 'fr2-a30', type: 'Audio', question: 'Je viens de...', answer: 'Jeg kommer fra...', options: ['Jeg bor i', 'Jeg kommer fra'], instruction: 'Præsentation' },
    { id: 'fr2-a31', type: 'Audio', question: 'Quel âge as-tu?', answer: 'Hvor gammel er du?', options: ['Hvad hedder du?', 'Hvor gammel er du?'], instruction: 'Spørgsmål' },
    { id: 'fr2-a32', type: 'Audio', question: 'Comment ça va?', answer: 'Hvordan går det?', options: ['Hvem er du?', 'Hvordan går det?'], instruction: 'Spørgsmål' },
    { id: 'fr2-a33', type: 'Audio', question: 'Ça va bien', answer: 'Det går godt', options: ['Godt', 'Dårligt'], instruction: 'Svar' },
    { id: 'fr2-a34', type: 'Audio', question: 'Pas mal', answer: 'Ikke dårligt', options: ['Ikke dårligt', 'Meget dårligt'], instruction: 'Svar' },
    { id: 'fr2-a35', type: 'Audio', question: 'Enchanté', answer: 'Hyggeligt at møde dig', options: ['Goddag', 'Hyggeligt at møde dig'], instruction: 'Hilsen' },
    { id: 'fr2-a36', type: 'Audio', question: 'Un animal', answer: 'Et dyr', options: ['Dyr', 'Plante', 'Menneske'], instruction: 'Begreb' },
    { id: 'fr2-a37', type: 'Audio', question: 'Un lion', answer: 'En løve', options: ['Løve', 'Tiger', 'Elefant'], instruction: 'Dyr' },
    { id: 'fr2-a38', type: 'Audio', question: 'Un éléphant', answer: 'En elefant', options: ['Løve', 'Tiger', 'Elefant'], instruction: 'Dyr' },
    { id: 'fr2-a39', type: 'Audio', question: 'Un singe', answer: 'En abe', options: ['Abe', 'Bjørn'], instruction: 'Dyr' },
    { id: 'fr2-a40', type: 'Audio', question: 'Une glace', answer: 'En is', options: ['Is', 'Kage', 'Slik'], instruction: 'Mad' },
    { id: 'fr2-a41', type: 'Audio', question: 'Un gâteau', answer: 'En kage', options: ['Is', 'Kage', 'Slik'], instruction: 'Mad' },
    { id: 'fr2-a42', type: 'Audio', question: 'Le chocolat', answer: 'Chokolade', options: ['Chokolade', 'Vanilje'], instruction: 'Mad' },
    { id: 'fr2-a43', type: 'Audio', question: 'Qu’est-ce que c’est?', answer: 'Hvad er det?', options: ['Hvem er det?', 'Hvad er det?'], instruction: 'Spørgsmål' },
    { id: 'fr2-a44', type: 'Audio', question: 'C\'est un...', answer: 'Det er en...', options: ['Det er en', 'Her er'], instruction: 'Svar' },
    { id: 'fr2-a45', type: 'Audio', question: 'Je t’aime', answer: 'Jeg elsker dig', options: ['Elsker', 'Hader'], instruction: 'Følelse' },
    { id: 'fr2-a46', type: 'Audio', question: 'D’accord', answer: 'Helt i orden', options: ['Nej tak', 'Helt i orden'], instruction: 'Svar' },
    { id: 'fr2-a47', type: 'Audio', question: 'Bien sûr', answer: 'Selvfølgelig', options: ['Måske', 'Selvfølgelig'], instruction: 'Svar' },
    { id: 'fr2-a48', type: 'Audio', question: 'Attend!', answer: 'Vent!', options: ['Kom!', 'Vent!'], instruction: 'Ordre' },
    { id: 'fr2-a49', type: 'Audio', question: 'Dépêche-toi!', answer: 'Skynd dig!', options: ['Vent!', 'Skynd dig!'], instruction: 'Ordre' },
    { id: 'fr2-a50', type: 'Audio', question: 'Bravo!', answer: 'Flot!', options: ['Flot!', 'Øv!'], instruction: 'Udbrud' },
    { id: 'fr2-a51', type: 'Audio', question: 'Santé!', answer: 'Skål!', options: ['Skål!', 'Tak for mad'], instruction: 'Udbrud' },
  ],
  3: [
    { id: 'fr3-a1', type: 'Audio', question: 'Soixante', answer: '60', options: ['60', '70', '80'], instruction: 'Tal' },
    { id: 'fr3-a2', type: 'Audio', question: 'Soixante-dix', answer: '70', options: ['60', '70', '80'], instruction: 'Tal' },
    { id: 'fr3-a3', type: 'Audio', question: 'Quatre-vingts', answer: '80', options: ['80', '90', '100'], instruction: 'Tal' },
    { id: 'fr3-a4', type: 'Audio', question: 'Quatre-vingt-dix', answer: '90', options: ['80', '90', '100'], instruction: 'Tal' },
    { id: 'fr3-a5', type: 'Audio', question: 'Cent', answer: '100', options: ['100', '1000'], instruction: 'Tal' },
    { id: 'fr3-a6', type: 'Audio', question: 'Un médecin', answer: 'En læge', options: ['Læge', 'Lærer', 'Politi'], instruction: 'Profession' },
    { id: 'fr3-a7', type: 'Audio', question: 'Un professeur', answer: 'En lærer', options: ['Læge', 'Lærer', 'Politi'], instruction: 'Profession' },
    { id: 'fr3-a8', type: 'Audio', question: 'Un policier', answer: 'En politibetjent', options: ['Læge', 'Lærer', 'Politi'], instruction: 'Profession' },
    { id: 'fr3-a9', type: 'Audio', question: 'Un pompier', answer: 'Brandmand', options: ['Brandmand', 'Soldat'], instruction: 'Profession' },
    { id: 'fr3-a10', type: 'Audio', question: 'À gauche', answer: 'Til venstre', options: ['Venstre', 'Højre', 'Lige ud'], instruction: 'Retning' },
    { id: 'fr3-a11', type: 'Audio', question: 'À droite', answer: 'Til højre', options: ['Venstre', 'Højre', 'Lige ud'], instruction: 'Retning' },
    { id: 'fr3-a12', type: 'Audio', question: 'Tout droit', answer: 'Lige ud', options: ['Venstre', 'Højre', 'Lige ud'], instruction: 'Retning' },
    { id: 'fr3-a13', type: 'Audio', question: 'Le cinéma', answer: 'Biograf', options: ['Biograf', 'Museum', 'Park'], instruction: 'Sted' },
    { id: 'fr3-a14', type: 'Audio', question: 'Le musée', answer: 'Museum', options: ['Biograf', 'Museum', 'Park'], instruction: 'Sted' },
    { id: 'fr3-a15', type: 'Audio', question: 'Le parc', answer: 'Park', options: ['Biograf', 'Museum', 'Park'], instruction: 'Sted' },
    { id: 'fr3-a16', type: 'Audio', question: 'La plage', answer: 'Strand', options: ['Strand', 'Bjerg', 'Skov'], instruction: 'Natur' },
    { id: 'fr3-a17', type: 'Audio', question: 'La montagne', answer: 'Bjerg', options: ['Strand', 'Bjerg', 'Skov'], instruction: 'Natur' },
    { id: 'fr3-a18', type: 'Audio', question: 'La forêt', answer: 'Skov', options: ['Strand', 'Bjerg', 'Skov'], instruction: 'Natur' },
    { id: 'fr3-a19', type: 'Audio', question: 'Une voiture', answer: 'En bil', options: ['Bil', 'Bus', 'Tog'], instruction: 'Transport' },
    { id: 'fr3-a20', type: 'Audio', question: 'Un bus', answer: 'En bus', options: ['Bil', 'Bus', 'Tog'], instruction: 'Transport' },
    { id: 'fr3-a21', type: 'Audio', question: 'Un train', answer: 'Et tog', options: ['Bil', 'Bus', 'Tog'], instruction: 'Transport' },
    { id: 'fr3-a22', type: 'Audio', question: 'Un bateau', answer: 'Et skib', options: ['Skib', 'Fly'], instruction: 'Transport' },
    { id: 'fr3-a23', type: 'Audio', question: 'Un avion', answer: 'Et fly', options: ['Skib', 'Fly'], instruction: 'Transport' },
    { id: 'fr3-a24', type: 'Audio', question: 'Faire du sport', answer: 'Dyrke sport', options: ['Sport', 'Musik', 'Læsning'], instruction: 'Hobby' },
    { id: 'fr3-a25', type: 'Audio', question: 'Jouer du piano', answer: 'Spille klaver', options: ['Sport', 'Musik', 'Læsning'], instruction: 'Hobby' },
    { id: 'fr3-a26', type: 'Audio', question: 'Lire un livre', answer: 'Læse en bog', options: ['Sport', 'Musik', 'Læsning'], instruction: 'Hobby' },
    { id: 'fr3-a27', type: 'Audio', question: 'Écouter de la musique', answer: 'Høre musik', options: ['Høre musik', 'Se TV'], instruction: 'Hobby' },
    { id: 'fr3-a28', type: 'Audio', question: 'Regarder la télé', answer: 'Se fjernsyn', options: ['Høre musik', 'Se TV'], instruction: 'Hobby' },
    { id: 'fr3-a29', type: 'Audio', question: 'Manger une pomme', answer: 'Spise et æble', options: ['Spise', 'Drikke'], instruction: 'Sætning' },
    { id: 'fr3-a30', type: 'Audio', question: 'Boire du jus', answer: 'Drikke juice', options: ['Spise', 'Drikke'], instruction: 'Sætning' },
    { id: 'fr3-a31', type: 'Audio', question: 'Je voudrais...', answer: 'Jeg vil gerne have...', options: ['Jeg har', 'Jeg vil gerne have'], instruction: 'Bestilling' },
    { id: 'fr3-a32', type: 'Audio', question: 'Combien ça coûte?', answer: 'Hvad koster det?', options: ['Hvad er det?', 'Hvad koster det?'], instruction: 'Spørgsmål' },
    { id: 'fr3-a33', type: 'Audio', question: 'C’est cher', answer: 'Det er dyrt', options: ['Billigt', 'Dyrt'], instruction: 'Beskrivelse' },
    { id: 'fr3-a34', type: 'Audio', question: 'C’est bon marché', answer: 'Det er billigt', options: ['Billigt', 'Dyrt'], instruction: 'Beskrivelse' },
    { id: 'fr3-a35', type: 'Audio', question: 'Où est la gare?', answer: 'Hvor er togstationen?', options: ['Hvor er hotellet?', 'Hvor er togstationen?'], instruction: 'Spørgsmål' },
    { id: 'fr3-a36', type: 'Audio', question: 'Je suis perdu', answer: 'Jeg er faret vild', options: ['Jeg er faret vild', 'Jeg er her'], instruction: 'Udtryk' },
    { id: 'fr3-a37', type: 'Audio', question: 'Aidez-moi', answer: 'Hjælp mig', options: ['Hjælp mig', 'Lad mig være'], instruction: 'Udtryk' },
    { id: 'fr3-a38', type: 'Audio', question: 'Un manteau', answer: 'En frakke', options: ['Frakke', 'Skjorte', 'Kjole'], instruction: 'Tøj' },
    { id: 'fr3-a39', type: 'Audio', question: 'Une robe', answer: 'En kjole', options: ['Frakke', 'Skjorte', 'Kjole'], instruction: 'Tøj' },
    { id: 'fr3-a40', type: 'Audio', question: 'Une jupe', answer: 'En nederdel', options: ['Bukser', 'Nederdel'], instruction: 'Tøj' },
    { id: 'fr3-a41', type: 'Audio', question: 'Un pull', answer: 'En trøje', options: ['Trøje', 'Skjorte'], instruction: 'Tøj' },
    { id: 'fr3-a42', type: 'Audio', question: 'J’ai chaud', answer: 'Jeg har det varmt', options: ['Varmt', 'Koldt'], instruction: 'Følelse' },
    { id: 'fr3-a43', type: 'Audio', question: 'J’ai froid', answer: 'Jeg har det koldt', options: ['Varmt', 'Koldt'], instruction: 'Følelse' },
    { id: 'fr3-a44', type: 'Audio', question: 'C’est délicieux', answer: 'Det smager dejligt', options: ['Dejligt', 'Dårligt'], instruction: 'Mad' },
    { id: 'fr3-a45', type: 'Audio', question: 'Beurk!', answer: 'Ad!', options: ['Mums!', 'Ad!'], instruction: 'Mad' },
    { id: 'fr3-a46', type: 'Audio', question: 'Un cadeau', answer: 'En gave', options: ['Gave', 'Køb'], instruction: 'Ting' },
    { id: 'fr3-a47', type: 'Audio', question: 'Joyeux anniversaire', answer: 'Tillykke med fødselsdagen', options: ['God jul', 'Tillykke'], instruction: 'Hilsen' },
    { id: 'fr3-a48', type: 'Audio', question: 'Bonne année', answer: 'Godt nytår', options: ['Goddag', 'Godt nytår'], instruction: 'Hilsen' },
    { id: 'fr3-a49', type: 'Audio', question: 'C’est facile', answer: 'Det er nemt', options: ['Nemt', 'Svært'], instruction: 'Beskrivelse' },
    { id: 'fr3-a50', type: 'Audio', question: 'C’est difficile', answer: 'Det er svært', options: ['Nemt', 'Svært'], instruction: 'Beskrivelse' },
    { id: 'fr3-a51', type: 'Audio', question: 'Peut-être', answer: 'Måske', options: ['Ja', 'Nej', 'Måske'], instruction: 'Svar' },
  ],
  4: [
    { id: 'fr4-a1', type: 'Audio', question: 'Mille', answer: '1000', options: ['100', '1000', '10000'], instruction: 'Tal' },
    { id: 'fr4-a2', type: 'Audio', question: 'Un million', answer: 'En million', options: ['Tusind', 'Million'], instruction: 'Tal' },
    { id: 'fr4-a3', type: 'Audio', question: 'Petit-déjeuner', answer: 'Morgenmad', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Måltid' },
    { id: 'fr4-a4', type: 'Audio', question: 'Déjeuner', answer: 'Frokost', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Måltid' },
    { id: 'fr4-a5', type: 'Audio', question: 'Dîner', answer: 'Aftensmad', options: ['Morgenmad', 'Frokost', 'Aftensmad'], instruction: 'Måltid' },
    { id: 'fr4-a6', type: 'Audio', question: 'Le menu', answer: 'Menukortet', options: ['Mad', 'Regning', 'Menu'], instruction: 'Restaurant' },
    { id: 'fr4-a7', type: 'Audio', question: 'L’addition', answer: 'Regningen', options: ['Mad', 'Regning', 'Menu'], instruction: 'Restaurant' },
    { id: 'fr4-a8', type: 'Audio', question: 'Un serveur', answer: 'En tjener', options: ['Tjener', 'Kok', 'Gæst'], instruction: 'Restaurant' },
    { id: 'fr4-a9', type: 'Audio', question: 'Un restaurant', answer: 'En restaurant', options: ['Cafe', 'Restaurant', 'Bager'], instruction: 'Sted' },
    { id: 'fr4-a10', type: 'Audio', question: 'Un supermarché', answer: 'Et supermarked', options: ['Butik', 'Marked', 'Supermarked'], instruction: 'Sted' },
    { id: 'fr4-a11', type: 'Audio', question: 'Faire les courses', answer: 'Købe ind', options: ['Løbe', 'Købe ind', 'Sove'], instruction: 'Handling' },
    { id: 'fr4-a12', type: 'Audio', question: 'Acheter', answer: 'Købe', options: ['Købe', 'Sælge', 'Give'], instruction: 'Handling' },
    { id: 'fr4-a13', type: 'Audio', question: 'Vendre', answer: 'Sælge', options: ['Købe', 'Sælge', 'Give'], instruction: 'Handling' },
    { id: 'fr4-a14', type: 'Audio', question: 'Chercher', answer: 'Lede efter', options: ['Find', 'Lede efter'], instruction: 'Handling' },
    { id: 'fr4-a15', type: 'Audio', question: 'Trouver', answer: 'Finde', options: ['Find', 'Lede efter'], instruction: 'Handling' },
    { id: 'fr4-a16', type: 'Audio', question: 'Une ville', answer: 'En by', options: ['By', 'Landsby', 'Land'], instruction: 'Sted' },
    { id: 'fr4-a17', type: 'Audio', question: 'Un village', answer: 'En landsby', options: ['By', 'Landsby', 'Land'], instruction: 'Sted' },
    { id: 'fr4-a18', type: 'Audio', question: 'La campagne', answer: 'Landet', options: ['By', 'Landet'], instruction: 'Sted' },
    { id: 'fr4-a19', type: 'Audio', question: 'Travailler', answer: 'Arbejde', options: ['Arbejde', 'Hvile'], instruction: 'Handling' },
    { id: 'fr4-a20', type: 'Audio', question: 'Se reposer', answer: 'Hvile sig', options: ['Arbejde', 'Hvile'], instruction: 'Handling' },
    { id: 'fr4-a21', type: 'Audio', question: 'Vacances', answer: 'Ferie', options: ['Ferie', 'Hverdage'], instruction: 'Fritid' },
    { id: 'fr4-a22', type: 'Audio', question: 'Voyager', answer: 'Rejse', options: ['Rejse', 'Blive hjemme'], instruction: 'Fritid' },
    { id: 'fr4-a23', type: 'Audio', question: 'Une valise', answer: 'En kuffert', options: ['Taske', 'Kuffert'], instruction: 'Rejse' },
    { id: 'fr4-a24', type: 'Audio', question: 'Un passeport', answer: 'Et pas', options: ['Pas', 'Biljet'], instruction: 'Rejse' },
    { id: 'fr4-a25', type: 'Audio', question: 'Un billet', answer: 'En billet', options: ['Pas', 'Billet'], instruction: 'Rejse' },
    { id: 'fr4-a26', type: 'Audio', question: 'L’été prochain', answer: 'Næste sommer', options: ['Sidste sommer', 'Næste sommer'], instruction: 'Tid' },
    { id: 'fr4-a27', type: 'Audio', question: 'L’année dernière', answer: 'Sidste år', options: ['Sidste år', 'Næste år'], instruction: 'Tid' },
    { id: 'fr4-a28', type: 'Audio', question: 'Bientôt', answer: 'Snart', options: ['Nu', 'Snart', 'Aldrig'], instruction: 'Tid' },
    { id: 'fr4-a29', type: 'Audio', question: 'Maintenant', answer: 'Nu', options: ['Nu', 'Snart', 'Aldrig'], instruction: 'Tid' },
    { id: 'fr4-a30', type: 'Audio', question: 'Plus tard', answer: 'Senere', options: ['Nu', 'Senere'], instruction: 'Tid' },
    { id: 'fr4-a31', type: 'Audio', question: 'Hier soir', answer: 'I går aftes', options: ['I går aftes', 'I morges'], instruction: 'Tid' },
    { id: 'fr4-a32', type: 'Audio', question: 'Ce matin', answer: 'I morges', options: ['I går aftes', 'I morges'], instruction: 'Tid' },
    { id: 'fr4-a33', type: 'Audio', question: 'Une idée', answer: 'En idé', options: ['Tanke', 'Idé'], instruction: 'Abstrakte' },
    { id: 'fr4-a34', type: 'Audio', question: 'Un problème', answer: 'Et problem', options: ['Problem', 'Løsning'], instruction: 'Abstrakte' },
    { id: 'fr4-a35', type: 'Audio', question: 'Une solution', answer: 'En løsning', options: ['Problem', 'Løsning'], instruction: 'Abstrakte' },
    { id: 'fr4-a36', type: 'Audio', question: 'Le monde', answer: 'Verden', options: ['Verden', 'Landet'], instruction: 'Geografi' },
    { id: 'fr4-a37', type: 'Audio', question: 'La terre', answer: 'Jorden', options: ['Solen', 'Jorden'], instruction: 'Natur' },
    { id: 'fr4-a38', type: 'Audio', question: 'L’espace', answer: 'Rummet', options: ['Rummet', 'Jorden'], instruction: 'Natur' },
    { id: 'fr4-a39', type: 'Audio', question: 'Une étoile', answer: 'En stjerne', options: ['Måne', 'Stjerne'], instruction: 'Natur' },
    { id: 'fr4-a40', type: 'Audio', question: 'La lune', answer: 'Månen', options: ['Måne', 'Stjerne'], instruction: 'Natur' },
    { id: 'fr4-a41', type: 'Audio', question: 'Écrire un e-mail', answer: 'Skrive en mail', options: ['Skrive', 'Læse'], instruction: 'Teknologi' },
    { id: 'fr4-a42', type: 'Audio', question: 'Utiliser internet', answer: 'Bruge internettet', options: ['Bruge', 'Slukke'], instruction: 'Teknologi' },
    { id: 'fr4-a43', type: 'Audio', question: 'Un ordinateur', answer: 'En computer', options: ['PC', 'Telefon', 'Tablet'], instruction: 'Teknologi' },
    { id: 'fr4-a44', type: 'Audio', question: 'Allumer', answer: 'Tænde', options: ['Tænde', 'Slukke'], instruction: 'Verber' },
    { id: 'fr4-a45', type: 'Audio', question: 'Éteindre', answer: 'Slukke', options: ['Tænde', 'Slukke'], instruction: 'Verber' },
    { id: 'fr4-a46', type: 'Audio', question: 'Ouvrir', answer: 'Åbne', options: ['Åbne', 'Lukke'], instruction: 'Verber' },
    { id: 'fr4-a47', type: 'Audio', question: 'Fermer', answer: 'Lukke', options: ['Åbne', 'Lukke'], instruction: 'Verber' },
    { id: 'fr4-a48', type: 'Audio', question: 'Plus', answer: 'Mere', options: ['Mere', 'Mindre'], instruction: 'Mængde' },
    { id: 'fr4-a49', type: 'Audio', question: 'Moins', answer: 'Mindre', options: ['Mere', 'Mindre'], instruction: 'Mængde' },
    { id: 'fr4-a50', type: 'Audio', question: 'Beaucoup', answer: 'Meget', options: ['Lidt', 'Meget'], instruction: 'Mængde' },
    { id: 'fr4-a51', type: 'Audio', question: 'Un peu', answer: 'En lille smule', options: ['Lidt', 'Meget'], instruction: 'Mængde' },
  ]
};
