/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const TYSK_AUDIO_P1: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'de0-a1', type: 'Audio', question: 'Eins', answer: '1', options: ['1', '2', '3'], instruction: 'Zahlen' },
    { id: 'de0-a2', type: 'Audio', question: 'Zwei', answer: '2', options: ['1', '2', '3'], instruction: 'Zahlen' },
    { id: 'de0-a3', type: 'Audio', question: 'Drei', answer: '3', options: ['1', '2', '3'], instruction: 'Zahlen' },
    { id: 'de0-a4', type: 'Audio', question: 'Vier', answer: '4', options: ['4', '5', '6'], instruction: 'Zahlen' },
    { id: 'de0-a5', type: 'Audio', question: 'Fünf', answer: '5', options: ['4', '5', '6'], instruction: 'Zahlen' },
    { id: 'de0-a6', type: 'Audio', question: 'Sechs', answer: '6', options: ['4', '5', '6'], instruction: 'Zahlen' },
    { id: 'de0-a7', type: 'Audio', question: 'Sieben', answer: '7', options: ['7', '8', '9'], instruction: 'Zahlen' },
    { id: 'de0-a8', type: 'Audio', question: 'Acht', answer: '8', options: ['7', '8', '9'], instruction: 'Zahlen' },
    { id: 'de0-a9', type: 'Audio', question: 'Neun', answer: '9', options: ['7', '8', '9'], instruction: 'Zahlen' },
    { id: 'de0-a10', type: 'Audio', question: 'Zehn', answer: '10', options: ['8', '9', '10'], instruction: 'Zahlen' },
    { id: 'de0-a11', type: 'Audio', question: 'Rot', answer: 'Rød', options: ['Rød', 'Blå', 'Gul'], instruction: 'Farbe' },
    { id: 'de0-a12', type: 'Audio', question: 'Blau', answer: 'Blå', options: ['Rød', 'Blå', 'Gul'], instruction: 'Farbe' },
    { id: 'de0-a13', type: 'Audio', question: 'Gelb', answer: 'Gul', options: ['Rød', 'Blå', 'Gul'], instruction: 'Farbe' },
    { id: 'de0-a14', type: 'Audio', question: 'Grün', answer: 'Grøn', options: ['Grøn', 'Sort', 'Hvid'], instruction: 'Farbe' },
    { id: 'de0-a15', type: 'Audio', question: 'Schwarz', answer: 'Sort', options: ['Grøn', 'Sort', 'Hvid'], instruction: 'Farbe' },
    { id: 'de0-a16', type: 'Audio', question: 'Weiß', answer: 'Hvid', options: ['Grøn', 'Sort', 'Hvid'], instruction: 'Farbe' },
    { id: 'de0-a17', type: 'Audio', question: 'Hallo', answer: 'Hej', options: ['Hej', 'Farvel', 'Tak'], instruction: 'Begrüßung' },
    { id: 'de0-a18', type: 'Audio', question: 'Guten Tag', answer: 'Goddag', options: ['Goddag', 'Farvel', 'Tak'], instruction: 'Begrüßung' },
    { id: 'de0-a19', type: 'Audio', question: 'Danke', answer: 'Tak', options: ['Hej', 'Tak', 'Ja'], instruction: 'Begrüßung' },
    { id: 'de0-a20', type: 'Audio', question: 'Ja', answer: 'Ja', options: ['Ja', 'Nej', 'Måske'], instruction: 'Antwort' },
    { id: 'de0-a21', type: 'Audio', question: 'Nein', answer: 'Nej', options: ['Ja', 'Nej', 'Danke'], instruction: 'Antwort' },
    { id: 'de0-a22', type: 'Audio', question: 'Hund', answer: 'Hund', options: ['Hund', 'Katze', 'Vogel'], instruction: 'Tiere' },
    { id: 'de0-a23', type: 'Audio', question: 'Katze', answer: 'Kat', options: ['Hund', 'Katze', 'Vogel'], instruction: 'Tiere' },
    { id: 'de0-a24', type: 'Audio', question: 'Vogel', answer: 'Fugl', options: ['Hund', 'Katze', 'Vogel'], instruction: 'Tiere' },
    { id: 'de0-a25', type: 'Audio', question: 'Fisch', answer: 'Fisk', options: ['Fisch', 'Slange', 'Kuh'], instruction: 'Tiere' },
    { id: 'de0-a26', type: 'Audio', question: 'Apfel', answer: 'Æble', options: ['Æble', 'Banane', 'Birne'], instruction: 'Früchte' },
    { id: 'de0-a27', type: 'Audio', question: 'Banane', answer: 'Banan', options: ['Æble', 'Banane', 'Birne'], instruction: 'Früchte' },
    { id: 'de0-a28', type: 'Audio', question: 'Milch', answer: 'Mælk', options: ['Milch', 'Wasser', 'Saft'], instruction: 'Getränke' },
    { id: 'de0-a29', type: 'Audio', question: 'Wasser', answer: 'Vand', options: ['Milch', 'Wasser', 'Saft'], instruction: 'Getränke' },
    { id: 'de0-a30', type: 'Audio', question: 'Buch', answer: 'Bog', options: ['Buch', 'Stift', 'Tasche'], instruction: 'Schule' },
    { id: 'de0-a31', type: 'Audio', question: 'Haus', answer: 'Hus', options: ['Haus', 'Straße', 'Garten'], instruction: 'Ort' },
    { id: 'de0-a32', type: 'Audio', question: 'Mädchen', answer: 'Pige', options: ['Junge', 'Mädchen', 'Kind'], instruction: 'Person' },
    { id: 'de0-a33', type: 'Audio', question: 'Junge', answer: 'Dreng', options: ['Junge', 'Mädchen', 'Kind'], instruction: 'Person' },
    { id: 'de0-a34', type: 'Audio', question: 'Mama', answer: 'Mor', options: ['Mutter', 'Vater', 'Bruder'], instruction: 'Familie' },
    { id: 'de0-a35', type: 'Audio', question: 'Papa', answer: 'Far', options: ['Mutter', 'Vater', 'Bruder'], instruction: 'Familie' },
    { id: 'de0-a36', type: 'Audio', question: 'Himmel', answer: 'Himmel', options: ['Himmel', 'Sonne', 'Regen'], instruction: 'Natur' },
    { id: 'de0-a37', type: 'Audio', question: 'Sonne', answer: 'Sol', options: ['Himmel', 'Sonne', 'Regen'], instruction: 'Natur' },
    { id: 'de0-a38', type: 'Audio', question: 'Blume', answer: 'Blomst', options: ['Blume', 'Baum', 'Gras'], instruction: 'Natur' },
    { id: 'de0-a39', type: 'Audio', question: 'Brot', answer: 'Brød', options: ['Brot', 'Käse', 'Fleisch'], instruction: 'Essen' },
    { id: 'de0-a40', type: 'Audio', question: 'Käse', answer: 'Ost', options: ['Brot', 'Käse', 'Fleisch'], instruction: 'Essen' },
    { id: 'de0-a41', type: 'Audio', question: 'Schule', answer: 'Skole', options: ['Schule', 'Kirche', 'Park'], instruction: 'Ort' },
    { id: 'de0-a42', type: 'Audio', question: 'Sprechen', answer: 'Tale', options: ['Sprechen', 'Laufen', 'Essen'], instruction: 'Aktion' },
    { id: 'de0-a43', type: 'Audio', question: 'Essen', answer: 'Spise', options: ['Sprechen', 'Laufen', 'Essen'], instruction: 'Aktion' },
    { id: 'de0-a44', type: 'Audio', question: 'Laufen', answer: 'Løbe', options: ['Sprechen', 'Laufen', 'Essen'], instruction: 'Aktion' },
    { id: 'de0-a45', type: 'Audio', question: 'Klein', answer: 'Lille', options: ['Lille', 'Groß'], instruction: 'Gegensatz' },
    { id: 'de0-a46', type: 'Audio', question: 'Groß', answer: 'Stor', options: ['Lille', 'Groß'], instruction: 'Gegensatz' },
    { id: 'de0-a47', type: 'Audio', question: 'Gute Nacht', answer: 'Godnat', options: ['Guten Tag', 'Gute Nacht'], instruction: 'Gruß' },
    { id: 'de0-a48', type: 'Audio', question: 'Auf Wiedersehen', answer: 'Farvel', options: ['Hallo', 'Auf Wiedersehen'], instruction: 'Gruß' },
    { id: 'de0-a49', type: 'Audio', question: 'Fahrrad', answer: 'Cykel', options: ['Auto', 'Fahrrad', 'Zug'], instruction: 'Transport' },
    { id: 'de0-a50', type: 'Audio', question: 'Auto', answer: 'Bil', options: ['Auto', 'Fahrrad', 'Zug'], instruction: 'Transport' },
    { id: 'de0-a51', type: 'Audio', question: 'Flugzeug', answer: 'Fly', options: ['Wald', 'Flugzeug', 'Meer'], instruction: 'Transport' },
  ],
  1: [
    { id: 'de1-a1', type: 'Audio', question: 'Elf', answer: '11', options: ['11', '12', '13'], instruction: 'Zahlen' },
    { id: 'de1-a2', type: 'Audio', question: 'Zwölf', answer: '12', options: ['11', '12', '13'], instruction: 'Zahlen' },
    { id: 'de1-a3', type: 'Audio', question: 'Dreizehn', answer: '13', options: ['11', '12', '13'], instruction: 'Zahlen' },
    { id: 'de1-a4', type: 'Audio', question: 'Vierzehn', answer: '14', options: ['14', '15', '16'], instruction: 'Zahlen' },
    { id: 'de1-a5', type: 'Audio', question: 'Fünfzehn', answer: '15', options: ['14', '15', '16'], instruction: 'Zahlen' },
    { id: 'de1-a6', type: 'Audio', question: 'Sechzehn', answer: '16', options: ['14', '15', '16'], instruction: 'Zahlen' },
    { id: 'de1-a7', type: 'Audio', question: 'Siebzehn', answer: '17', options: ['17', '18', '19'], instruction: 'Zahlen' },
    { id: 'de1-a8', type: 'Audio', question: 'Achtzehn', answer: '18', options: ['17', '18', '19'], instruction: 'Zahlen' },
    { id: 'de1-a9', type: 'Audio', question: 'Neunzehn', answer: '19', options: ['17', '18', '19'], instruction: 'Zahlen' },
    { id: 'de1-a10', type: 'Audio', question: 'Zwanzig', answer: '20', options: ['10', '20', '30'], instruction: 'Zahlen' },
    { id: 'de1-a11', type: 'Audio', question: 'Montag', answer: 'Mandag', options: ['Montag', 'Dienstag', 'Mittwoch'], instruction: 'Wochentag' },
    { id: 'de1-a12', type: 'Audio', question: 'Dienstag', answer: 'Tirsdag', options: ['Montag', 'Dienstag', 'Mittwoch'], instruction: 'Wochentag' },
    { id: 'de1-a13', type: 'Audio', question: 'Mittwoch', answer: 'Onsdag', options: ['Montag', 'Dienstag', 'Mittwoch'], instruction: 'Wochentag' },
    { id: 'de1-a14', type: 'Audio', question: 'Donnerstag', answer: 'Torsdag', options: ['Donnerstag', 'Freitag', 'Samstag'], instruction: 'Wochentag' },
    { id: 'de1-a15', type: 'Audio', question: 'Freitag', answer: 'Fredag', options: ['Donnerstag', 'Freitag', 'Samstag'], instruction: 'Wochentag' },
    { id: 'de1-a16', type: 'Audio', question: 'Samstag', answer: 'Lørdag', options: ['Donnerstag', 'Freitag', 'Samstag'], instruction: 'Wochentag' },
    { id: 'de1-a17', type: 'Audio', question: 'Sonntag', answer: 'Søndag', options: ['Freitag', 'Samstag', 'Sonntag'], instruction: 'Wochentag' },
    { id: 'de1-a18', type: 'Audio', question: 'Der Kopf', answer: 'Hovedet', options: ['Hovedet', 'Fuss', 'Hand'], instruction: 'Körper' },
    { id: 'de1-a19', type: 'Audio', question: 'Die Hand', answer: 'Hånden', options: ['Hovedet', 'Fuss', 'Hand'], instruction: 'Körper' },
    { id: 'de1-a20', type: 'Audio', question: 'Der Fuss', answer: 'Foden', options: ['Hovedet', 'Fuss', 'Hand'], instruction: 'Körper' },
    { id: 'de1-a21', type: 'Audio', question: 'Die Nase', answer: 'Næsen', options: ['Nase', 'Auge', 'Ohr'], instruction: 'Körper' },
    { id: 'de1-a22', type: 'Audio', question: 'Das Auge', answer: 'Øjet', options: ['Nase', 'Auge', 'Ohr'], instruction: 'Körper' },
    { id: 'de1-a23', type: 'Audio', question: 'Bitte', answer: 'Vær så venlig', options: ['Danke', 'Bitte', 'Tschüss'], instruction: 'Höflichkeit' },
    { id: 'de1-a24', type: 'Audio', question: 'Gern geschehen', answer: 'Selv tak', options: ['Gern geschehen', 'Entschuldigung'], instruction: 'Höflichkeit' },
    { id: 'de1-a25', type: 'Audio', question: 'Entschuldigung', answer: 'Undskyld', options: ['Entschuldigung', 'Danke'], instruction: 'Höflichkeit' },
    { id: 'de1-a26', type: 'Audio', question: 'Eine Hose', answer: 'Bukser', options: ['Bukser', 'Hemd', 'Jacke'], instruction: 'Kleidung' },
    { id: 'de1-a27', type: 'Audio', question: 'Ein Hemd', answer: 'Skjorte', options: ['Bukser', 'Hemd', 'Jacke'], instruction: 'Kleidung' },
    { id: 'de1-a28', type: 'Audio', question: 'Schuhe', answer: 'Sko', options: ['Schuhe', 'Socken', 'Hut'], instruction: 'Kleidung' },
    { id: 'de1-a29', type: 'Audio', question: 'Ein Hut', answer: 'En hat', options: ['Schuhe', 'Hut'], instruction: 'Kleidung' },
    { id: 'de1-a30', type: 'Audio', question: 'Bruder', answer: 'Bror', options: ['Bruder', 'Schwester', 'Baby'], instruction: 'Familie' },
    { id: 'de1-a31', type: 'Audio', question: 'Schwester', answer: 'Søster', options: ['Bruder', 'Schwester', 'Baby'], instruction: 'Familie' },
    { id: 'de1-a32', type: 'Audio', question: 'Grossvater', answer: 'Bedstefar', options: ['Grossvater', 'Grossmutter'], instruction: 'Familie' },
    { id: 'de1-a33', type: 'Audio', question: 'Grossmutter', answer: 'Bedstemor', options: ['Grossvater', 'Grossmutter'], instruction: 'Familie' },
    { id: 'de1-a34', type: 'Audio', question: 'Ein Heft', answer: 'Et hæfte', options: ['Heft', 'Buch', 'Stift'], instruction: 'Schule' },
    { id: 'de1-a35', type: 'Audio', question: 'Ein Stift', answer: 'En pen', options: ['Heft', 'Buch', 'Stift'], instruction: 'Schule' },
    { id: 'de1-a36', type: 'Audio', question: 'Ein Lineal', answer: 'En lineal', options: ['Lineal', 'Radiergummi'], instruction: 'Schule' },
    { id: 'de1-a37', type: 'Audio', question: 'Ein Radiergummi', answer: 'Et viskelæder', options: ['Lineal', 'Radiergummi'], instruction: 'Schule' },
    { id: 'de1-a38', type: 'Audio', question: 'Es regnet', answer: 'Det regner', options: ['Regen', 'Sonne', 'Schnee'], instruction: 'Wetter' },
    { id: 'de1-a39', type: 'Audio', question: 'Die Sonne scheint', answer: 'Solen skinner', options: ['Regen', 'Sonne'], instruction: 'Wetter' },
    { id: 'de1-a40', type: 'Audio', question: 'Es ist windig', answer: 'Det blæser', options: ['Windig', 'Blitz'], instruction: 'Wetter' },
    { id: 'de1-a41', type: 'Audio', question: 'Ich bin froh', answer: 'Jeg er glad', options: ['Froh', 'Traurig'], instruction: 'Laune' },
    { id: 'de1-a42', type: 'Audio', question: 'Ich bin traurig', answer: 'Jeg er trist', options: ['Froh', 'Traurig'], instruction: 'Laune' },
    { id: 'de1-a43', type: 'Audio', question: 'Ich habe Hunger', answer: 'Jeg er sulten', options: ['Hunger', 'Durst'], instruction: 'Bedürfnis' },
    { id: 'de1-a44', type: 'Audio', question: 'Ich habe Durst', answer: 'Jeg er tørstig', options: ['Hunger', 'Durst'], instruction: 'Bedürfnis' },
    { id: 'de1-a45', type: 'Audio', question: 'Schau mal!', answer: 'Se!', options: ['Schau!', 'Hör!', 'Komm!'], instruction: 'Befehl' },
    { id: 'de1-a46', type: 'Audio', question: 'Hör mal!', answer: 'Lyt!', options: ['Schau!', 'Hör!', 'Komm!'], instruction: 'Befehl' },
    { id: 'de1-a47', type: 'Audio', question: 'Setz dich', answer: 'Sid ned', options: ['Steh auf', 'Setz dich'], instruction: 'Befehl' },
    { id: 'de1-a48', type: 'Audio', question: 'Steh auf', answer: 'Rejs jer', options: ['Steh auf', 'Setz dich'], instruction: 'Befehl' },
    { id: 'de1-a49', type: 'Audio', question: 'Ein Spielzeug', answer: 'Legetøj', options: ['Spielzeug', 'Essen', 'Auto'], instruction: 'Ding' },
    { id: 'de1-a50', type: 'Audio', question: 'Ein Ball', answer: 'En bold', options: ['Ball', 'Puppe'], instruction: 'Ding' },
    { id: 'de1-a51', type: 'Audio', question: 'Eine Puppe', answer: 'En dukke', options: ['Ball', 'Puppe'], instruction: 'Ding' },
  ],
  2: [
    { id: 'de2-a2', type: 'Audio', question: 'Einundzwanzig', answer: '21', options: ['21', '22', '31'], instruction: 'Zahlen' },
    { id: 'de2-a3', type: 'Audio', question: 'Dreissig', answer: '30', options: ['20', '30', '40'], instruction: 'Zahlen' },
    { id: 'de2-a4', type: 'Audio', question: 'Vierzig', answer: '40', options: ['30', '40', '50'], instruction: 'Zahlen' },
    { id: 'de2-a5', type: 'Audio', question: 'Fünfzig', answer: '50', options: ['40', '50', '60'], instruction: 'Zahlen' },
    { id: 'de2-a6', type: 'Audio', question: 'Januar', answer: 'Januar', options: ['Januar', 'Februar', 'März'], instruction: 'Monat' },
    { id: 'de2-a7', type: 'Audio', question: 'Februar', answer: 'Februar', options: ['Januar', 'Februar', 'März'], instruction: 'Monat' },
    { id: 'de2-a8', type: 'Audio', question: 'März', answer: 'Marts', options: ['Januar', 'Februar', 'März'], instruction: 'Monat' },
    { id: 'de2-a9', type: 'Audio', question: 'April', answer: 'April', options: ['April', 'Mai', 'Juni'], instruction: 'Monat' },
    { id: 'de2-a10', type: 'Audio', question: 'Mai', answer: 'Maj', options: ['April', 'Mai', 'Juni'], instruction: 'Monat' },
    { id: 'de2-a11', type: 'Audio', question: 'Juni', answer: 'Juni', options: ['April', 'Mai', 'Juni'], instruction: 'Monat' },
    { id: 'de2-a12', type: 'Audio', question: 'Juli', answer: 'Juli', options: ['Juli', 'August', 'September'], instruction: 'Monat' },
    { id: 'de2-a13', type: 'Audio', question: 'August', answer: 'August', options: ['Juli', 'August', 'September'], instruction: 'Monat' },
    { id: 'de2-a14', type: 'Audio', question: 'September', answer: 'September', options: ['Juli', 'August', 'September'], instruction: 'Monat' },
    { id: 'de2-a15', type: 'Audio', question: 'Oktober', answer: 'Oktober', options: ['Oktober', 'November', 'Dezember'], instruction: 'Monat' },
    { id: 'de2-a16', type: 'Audio', question: 'November', answer: 'November', options: ['Oktober', 'November', 'Dezember'], instruction: 'Monat' },
    { id: 'de2-a17', type: 'Audio', question: 'Dezember', answer: 'December', options: ['Oktober', 'November', 'Dezember'], instruction: 'Monat' },
    { id: 'de2-a18', type: 'Audio', question: 'Der Frühling', answer: 'Forår', options: ['Frühling', 'Sommer', 'Herbst', 'Winter'], instruction: 'Jahreszeit' },
    { id: 'de2-a19', type: 'Audio', question: 'Der Sommer', answer: 'Sommer', options: ['Frühling', 'Sommer', 'Herbst', 'Winter'], instruction: 'Jahreszeit' },
    { id: 'de2-a20', type: 'Audio', question: 'Der Herbst', answer: 'Efterår', options: ['Frühling', 'Sommer', 'Herbst', 'Winter'], instruction: 'Jahreszeit' },
    { id: 'de2-a21', type: 'Audio', question: 'Der Winter', answer: 'Vinter', options: ['Frühling', 'Sommer', 'Herbst', 'Winter'], instruction: 'Jahreszeit' },
    { id: 'de2-a22', type: 'Audio', question: 'Eine Uhr', answer: 'Et ur', options: ['Uhr', 'Bild', 'Wand'], instruction: 'Ding' },
    { id: 'de2-a23', type: 'Audio', question: 'Wie spät ist es?', answer: 'Hvad er klokken?', options: ['Wo bist du?', 'Wie spät ist es?'], instruction: 'Ausdruck' },
    { id: 'de2-a24', type: 'Audio', question: 'Es ist Mittag', answer: 'Den er 12 (middag)', options: ['Mittag', 'Mitternacht'], instruction: 'Zeit' },
    { id: 'de2-a25', type: 'Audio', question: 'Es ist Mitternacht', answer: 'Den er 12 (nat)', options: ['Mittag', 'Mitternacht'], instruction: 'Zeit' },
    { id: 'de2-a26', type: 'Audio', question: 'Eine Küche', answer: 'Et køkken', options: ['Küche', 'Wohnzimmer', 'Bad'], instruction: 'Heim' },
    { id: 'de2-a27', type: 'Audio', question: 'Ein Wohnzimmer', answer: 'En stue', options: ['Küche', 'Wohnzimmer', 'Bad'], instruction: 'Heim' },
    { id: 'de2-a28', type: 'Audio', question: 'Ein Schlafzimmer', answer: 'Et værelse', options: ['Zimmer', 'Garten'], instruction: 'Heim' },
    { id: 'de2-a29', type: 'Audio', question: 'Das Badezimmer', answer: 'Badeværelse', options: ['Bad', 'Küche'], instruction: 'Heim' },
    { id: 'de2-a30', type: 'Audio', question: 'Ich wohne in...', answer: 'Jeg bor i...', options: ['Ich wohne', 'Ich komme aus'], instruction: 'Präsentation' },
    { id: 'de2-a31', type: 'Audio', question: 'Ich komme aus...', answer: 'Jeg kommer fra...', options: ['Ich wohne', 'Ich komme aus'], instruction: 'Präsentation' },
    { id: 'de2-a32', type: 'Audio', question: 'Wie alt bist du?', answer: 'Hvor gammel er du?', options: ['Wie heißt du?', 'Wie alt bist du?'], instruction: 'Frage' },
    { id: 'de2-a33', type: 'Audio', question: 'Wie geht es dir?', answer: 'Hvordan går det?', options: ['Wer bist du?', 'Wie geht es dir?'], instruction: 'Frage' },
    { id: 'de2-a34', type: 'Audio', question: 'Es geht mir gut', answer: 'Det går godt', options: ['Gut', 'Schlecht'], instruction: 'Antwort' },
    { id: 'de2-a35', type: 'Audio', question: 'Nicht schlecht', answer: 'Ikke dårligt', options: ['Nicht schlecht', 'Sehr schlecht'], instruction: 'Antwort' },
    { id: 'de2-a36', type: 'Audio', question: 'Freut mich', answer: 'Hyggeligt at møde dig', options: ['Tag', 'Freut mich'], instruction: 'Gruß' },
    { id: 'de2-a37', type: 'Audio', question: 'Ein Tier', answer: 'Et dyr', options: ['Tier', 'Pflanze', 'Mensch'], instruction: 'Begriff' },
    { id: 'de2-a38', type: 'Audio', question: 'Ein Löwe', answer: 'En løve', options: ['Löwe', 'Tiger', 'Elefant'], instruction: 'Tiere' },
    { id: 'de2-a39', type: 'Audio', question: 'Ein Elefant', answer: 'En elefant', options: ['Löwe', 'Tiger', 'Elefant'], instruction: 'Tiere' },
    { id: 'de2-a40', type: 'Audio', question: 'Ein Affe', answer: 'En abe', options: ['Affe', 'Bär'], instruction: 'Tiere' },
    { id: 'de2-a41', type: 'Audio', question: 'Ein Eis', answer: 'En is', options: ['Eis', 'Kuchen', 'Süßigk.'], instruction: 'Essen' },
    { id: 'de2-a42', type: 'Audio', question: 'Ein Kuchen', answer: 'En kage', options: ['Eis', 'Kuchen', 'Süßigk.'], instruction: 'Essen' },
    { id: 'de2-a43', type: 'Audio', question: 'Die Schokolade', answer: 'Chokolade', options: ['Schoko', 'Vanille'], instruction: 'Essen' },
    { id: 'de2-a44', type: 'Audio', question: 'Was ist das?', answer: 'Hvad er det?', options: ['Wer?', 'Was?'], instruction: 'Frage' },
    { id: 'de2-a45', type: 'Audio', question: 'Das ist ein...', answer: 'Det er en...', options: ['Das ist', 'Hier ist'], instruction: 'Antwort' },
    { id: 'de2-a46', type: 'Audio', question: 'Ich liebe dich', answer: 'Jeg elsker dig', options: ['Liebe', 'Hasse'], instruction: 'Gefühl' },
    { id: 'de2-a47', type: 'Audio', question: 'In Ordnung', answer: 'Helt i orden', options: ['Nein danke', 'In Ordnung'], instruction: 'Antwort' },
    { id: 'de2-a48', type: 'Audio', question: 'Natürlich', answer: 'Selvfølgelig', options: ['Vielleicht', 'Natürlich'], instruction: 'Antwort' },
    { id: 'de2-a49', type: 'Audio', question: 'Warte!', answer: 'Vent!', options: ['Komm!', 'Warte!'], instruction: 'Befehl' },
    { id: 'de2-a50', type: 'Audio', question: 'Beeil dich!', answer: 'Skynd dig!', options: ['Warte!', 'Beeil dich!'], instruction: 'Befehl' },
    { id: 'de2-a51', type: 'Audio', question: 'Toll!', answer: 'Flot!', options: ['Toll!', 'Schade!'], instruction: 'Ausruf' },
  ],
  3: [
    { id: 'de3-a1', type: 'Audio', question: 'Sechzig', answer: '60', options: ['60', '70', '80'], instruction: 'Zahlen' },
    { id: 'de3-a2', type: 'Audio', question: 'Siebzig', answer: '70', options: ['60', '70', '80'], instruction: 'Zahlen' },
    { id: 'de3-a3', type: 'Audio', question: 'Achtzig', answer: '80', options: ['80', '90', '100'], instruction: 'Zahlen' },
    { id: 'de3-a4', type: 'Audio', question: 'Neunzig', answer: '90', options: ['80', '90', '100'], instruction: 'Zahlen' },
    { id: 'de3-a5', type: 'Audio', question: 'Hundert', answer: '100', options: ['100', '1000'], instruction: 'Zahlen' },
    { id: 'de3-a6', type: 'Audio', question: 'Ein Arzt', answer: 'En læge', options: ['Arzt', 'Lehrer', 'Polizei'], instruction: 'Beruf' },
    { id: 'de3-a7', type: 'Audio', question: 'Ein Lehrer', answer: 'En lærer', options: ['Arzt', 'Lehrer', 'Polizei'], instruction: 'Beruf' },
    { id: 'de3-a8', type: 'Audio', question: 'Ein Polizist', answer: 'En politibetjent', options: ['Arzt', 'Lehrer', 'Polizei'], instruction: 'Beruf' },
    { id: 'de3-a9', type: 'Audio', question: 'Ein Feuerwehrmann', answer: 'Brandmand', options: ['Feuerwehrmann', 'Soldat'], instruction: 'Beruf' },
    { id: 'de3-a10', type: 'Audio', question: 'Links', answer: 'Til venstre', options: ['Links', 'Rechts', 'Geradeaus'], instruction: 'Richtung' },
    { id: 'de3-a11', type: 'Audio', question: 'Rechts', answer: 'Til højre', options: ['Links', 'Rechts', 'Geradeaus'], instruction: 'Richtung' },
    { id: 'de3-a12', type: 'Audio', question: 'Geradeaus', answer: 'Lige ud', options: ['Links', 'Rechts', 'Geradeaus'], instruction: 'Richtung' },
    { id: 'de3-a13', type: 'Audio', question: 'Das Kino', answer: 'Biograf', options: ['Kino', 'Museum', 'Park'], instruction: 'Ort' },
    { id: 'de3-a14', type: 'Audio', question: 'Das Museum', answer: 'Museum', options: ['Kino', 'Museum', 'Park'], instruction: 'Ort' },
    { id: 'de3-a15', type: 'Audio', question: 'Der Park', answer: 'Park', options: ['Kino', 'Museum', 'Park'], instruction: 'Ort' },
    { id: 'de3-a16', type: 'Audio', question: 'Der Strand', answer: 'Strand', options: ['Strand', 'Berg', 'Wald'], instruction: 'Natur' },
    { id: 'de3-a17', type: 'Audio', question: 'Der Berg', answer: 'Bjerg', options: ['Strand', 'Berg', 'Wald'], instruction: 'Natur' },
    { id: 'de3-a18', type: 'Audio', question: 'Der Wald', answer: 'Skov', options: ['Strand', 'Berg', 'Wald'], instruction: 'Natur' },
    { id: 'de3-a19', type: 'Audio', question: 'Ein Auto', answer: 'En bil', options: ['Auto', 'Bus', 'Zug'], instruction: 'Transport' },
    { id: 'de3-a20', type: 'Audio', question: 'Ein Bus', answer: 'En bus', options: ['Auto', 'Bus', 'Zug'], instruction: 'Transport' },
    { id: 'de3-a21', type: 'Audio', question: 'Ein Zug', answer: 'Et tog', options: ['Auto', 'Bus', 'Zug'], instruction: 'Transport' },
    { id: 'de3-a22', type: 'Audio', question: 'Ein Schiff', answer: 'Et skib', options: ['Schiff', 'Flugzeug'], instruction: 'Transport' },
    { id: 'de3-a23', type: 'Audio', question: 'Ein Flugzeug', answer: 'Et fly', options: ['Schiff', 'Flugzeug'], instruction: 'Transport' },
    { id: 'de3-a24', type: 'Audio', question: 'Sport treiben', answer: 'Dyrke sport', options: ['Sport', 'Musik', 'Lesen'], instruction: 'Hobby' },
    { id: 'de3-a25', type: 'Audio', question: 'Klavier spielen', answer: 'Spille klaver', options: ['Sport', 'Musik', 'Lesen'], instruction: 'Hobby' },
    { id: 'de3-a26', type: 'Audio', question: 'Ein Buch lesen', answer: 'Læse en bog', options: ['Sport', 'Musik', 'Lesen'], instruction: 'Hobby' },
    { id: 'de3-a27', type: 'Audio', question: 'Musik hören', answer: 'Høre musik', options: ['Musik hören', 'TV schauen'], instruction: 'Hobby' },
    { id: 'de3-a28', type: 'Audio', question: 'Fernsehen', answer: 'Se fjernsyn', options: ['Musik hören', 'TV schauen'], instruction: 'Hobby' },
    { id: 'de3-a29', type: 'Audio', question: 'Einen Apfel essen', answer: 'Spise et æble', options: ['Essen', 'Trinken'], instruction: 'Satz' },
    { id: 'de3-a30', type: 'Audio', question: 'Einen Saft trinken', answer: 'Drikke juice', options: ['Essen', 'Trinken'], instruction: 'Satz' },
    { id: 'de3-a31', type: 'Audio', question: 'Ich möchte...', answer: 'Jeg vil gerne have...', options: ['Ich habe', 'Ich möchte'], instruction: 'Bestellung' },
    { id: 'de3-a32', type: 'Audio', question: 'Was kostet das?', answer: 'Hvad koster det?', options: ['Was ist das?', 'Was kostet das?'], instruction: 'Frage' },
    { id: 'de3-a33', type: 'Audio', question: 'Es ist teuer', answer: 'Det er dyrt', options: ['Billig', 'Teuer'], instruction: 'Beschreibung' },
    { id: 'de3-a34', type: 'Audio', question: 'Es ist billig', answer: 'Det er billigt', options: ['Billig', 'Teuer'], instruction: 'Beschreibung' },
    { id: 'de3-a35', type: 'Audio', question: 'Wo ist der Bahnhof?', answer: 'Hvor er togstationen?', options: ['Bahnhof?', 'Hotel?'], instruction: 'Frage' },
    { id: 'de3-a36', type: 'Audio', question: 'Ich habe mich verlaufen', answer: 'Jeg er faret vild', options: ['Verlaufen', 'Hier'], instruction: 'Ausdruck' },
    { id: 'de3-a37', type: 'Audio', question: 'Hilf mir', answer: 'Hjælp mig', options: ['Helfen', 'Lassen'], instruction: 'Ausdruck' },
    { id: 'de3-a38', type: 'Audio', question: 'Ein Mantel', answer: 'En frakke', options: ['Mantel', 'Hemd', 'Kleid'], instruction: 'Kleidung' },
    { id: 'de3-a39', type: 'Audio', question: 'Ein Kleid', answer: 'En kjole', options: ['Mantel', 'Hemd', 'Kleid'], instruction: 'Kleidung' },
    { id: 'de3-a40', type: 'Audio', question: 'Ein Rock', answer: 'En nederdel', options: ['Hose', 'Rock'], instruction: 'Kleidung' },
    { id: 'de3-a41', type: 'Audio', question: 'Ein Pullover', answer: 'En trøje', options: ['Pulli', 'Hemd'], instruction: 'Kleidung' },
    { id: 'de3-a42', type: 'Audio', question: 'Mir ist warm', answer: 'Jeg har det varmt', options: ['Warm', 'Kalt'], instruction: 'Gefühl' },
    { id: 'de3-a43', type: 'Audio', question: 'Mir ist kalt', answer: 'Jeg har det koldt', options: ['Warm', 'Kalt'], instruction: 'Gefühl' },
    { id: 'de3-a44', type: 'Audio', question: 'Es ist lecker', answer: 'Det smager dejligt', options: ['Lecker', 'Schlecht'], instruction: 'Essen' },
    { id: 'de3-a45', type: 'Audio', question: 'Igitt!', answer: 'Ad!', options: ['Lecker!', 'Igitt!'], instruction: 'Essen' },
    { id: 'de3-a46', type: 'Audio', question: 'Ein Geschenk', answer: 'En gave', options: ['Gabe', 'Kauf'], instruction: 'Ding' },
    { id: 'de3-a47', type: 'Audio', question: 'Alles Gute zum Geburtstag', answer: 'Tillykke med fødselsdagen', options: ['Frohes Fest', 'Tillykke'], instruction: 'Gruß' },
    { id: 'de3-a48', type: 'Audio', question: 'Ein frohes neues Jahr', answer: 'Godt nytår', options: ['Tag', 'Neues Jahr'], instruction: 'Gruß' },
    { id: 'de3-a49', type: 'Audio', question: 'Es ist einfach', answer: 'Det er nemt', options: ['Einfach', 'Schwer'], instruction: 'Beschreibung' },
    { id: 'de3-a50', type: 'Audio', question: 'Es ist schwierig', answer: 'Det er svært', options: ['Einfach', 'Schwer'], instruction: 'Beschreibung' },
    { id: 'de3-a51', type: 'Audio', question: 'Vielleicht', answer: 'Måske', options: ['Ja', 'Nein', 'Vielleicht'], instruction: 'Antwort' },
  ],
  4: [
    { id: 'de4-a1', type: 'Audio', question: 'Tausend', answer: '1000', options: ['100', '1000', '10000'], instruction: 'Zahlen' },
    { id: 'de4-a2', type: 'Audio', question: 'Eine Million', answer: 'En million', options: ['Tausend', 'Million'], instruction: 'Zahlen' },
    { id: 'de4-a3', type: 'Audio', question: 'Frühstück', answer: 'Morgenmad', options: ['Frühstück', 'Mittag', 'Abend'], instruction: 'Mahlzeit' },
    { id: 'de4-a4', type: 'Audio', question: 'Mittagessen', answer: 'Frokost', options: ['Frühstück', 'Mittag', 'Abend'], instruction: 'Mahlzeit' },
    { id: 'de4-a5', type: 'Audio', question: 'Abendessen', answer: 'Aftensmad', options: ['Frühstück', 'Mittag', 'Abend'], instruction: 'Mahlzeit' },
    { id: 'de4-a6', type: 'Audio', question: 'Die Speisekarte', answer: 'Menukortet', options: ['Essen', 'Rechnung', 'Karte'], instruction: 'Restaurant' },
    { id: 'de4-a7', type: 'Audio', question: 'Die Rechnung', answer: 'Regningen', options: ['Essen', 'Rechnung', 'Karte'], instruction: 'Restaurant' },
    { id: 'de4-a8', type: 'Audio', question: 'Ein Kellner', answer: 'En tjener', options: ['Kellner', 'Koch', 'Gast'], instruction: 'Restaurant' },
    { id: 'de4-a9', type: 'Audio', question: 'Ein Restaurant', answer: 'En restaurant', options: ['Cafe', 'Rest.', 'Bäcker'], instruction: 'Ort' },
    { id: 'de4-a10', type: 'Audio', question: 'Ein Supermarkt', answer: 'Et supermarked', options: ['Laden', 'Markt', 'Superm.'], instruction: 'Ort' },
    { id: 'de4-a11', type: 'Audio', question: 'Einkaufen gehen', answer: 'Købe ind', options: ['Laufen', 'Einkaufen', 'Schlafen'], instruction: 'Aktion' },
    { id: 'de4-a12', type: 'Audio', question: 'Kaufen', answer: 'Købe', options: ['Kaufen', 'Verkaufen', 'Geben'], instruction: 'Aktion' },
    { id: 'de4-a13', type: 'Audio', question: 'Verkaufen', answer: 'Sælge', options: ['Kaufen', 'Verkaufen', 'Geben'], instruction: 'Aktion' },
    { id: 'de4-a14', type: 'Audio', question: 'Suchen', answer: 'Lede efter', options: ['Finden', 'Suchen'], instruction: 'Aktion' },
    { id: 'de4-a15', type: 'Audio', question: 'Finden', answer: 'Finde', options: ['Finden', 'Suchen'], instruction: 'Aktion' },
    { id: 'de4-a16', type: 'Audio', question: 'Eine Stadt', answer: 'En by', options: ['Stadt', 'Dorf', 'Land'], instruction: 'Ort' },
    { id: 'de4-a17', type: 'Audio', question: 'Ein Dorf', answer: 'En landsby', options: ['Stadt', 'Dorf', 'Land'], instruction: 'Ort' },
    { id: 'de4-a18', type: 'Audio', question: 'Das Land', answer: 'Landet', options: ['Stadt', 'Land'], instruction: 'Ort' },
    { id: 'de4-a19', type: 'Audio', question: 'Arbeiten', answer: 'Arbejde', options: ['Arbeiten', 'Ruhen'], instruction: 'Aktion' },
    { id: 'de4-a20', type: 'Audio', question: 'Sich ausruhen', answer: 'Hvile sig', options: ['Arbeiten', 'Ruhen'], instruction: 'Aktion' },
    { id: 'de4-a21', type: 'Audio', question: 'Ferien', answer: 'Ferie', options: ['Ferien', 'Wochentage'], instruction: 'Freizeit' },
    { id: 'de4-a22', type: 'Audio', question: 'Reisen', answer: 'Rejse', options: ['Reisen', 'Bleiben'], instruction: 'Freizeit' },
    { id: 'de4-a23', type: 'Audio', question: 'Ein Koffer', answer: 'En kuffert', options: ['Tasche', 'Koffer'], instruction: 'Reise' },
    { id: 'de4-a24', type: 'Audio', question: 'Ein Reisepass', answer: 'Et pas', options: ['Pass', 'Ticket'], instruction: 'Reise' },
    { id: 'de4-a25', type: 'Audio', question: 'Ein Ticket', answer: 'En billet', options: ['Pass', 'Ticket'], instruction: 'Reise' },
    { id: 'de4-a26', type: 'Audio', question: 'Nächster Sommer', answer: 'Næste sommer', options: ['Letzter S.', 'Nächster S.'], instruction: 'Zeit' },
    { id: 'de4-a27', type: 'Audio', question: 'Letztes Jahr', answer: 'Sidste år', options: ['Letztes J.', 'Nächstes J.'], instruction: 'Zeit' },
    { id: 'de4-a28', type: 'Audio', question: 'Bald', answer: 'Snart', options: ['Jetzt', 'Bald', 'Nie'], instruction: 'Zeit' },
    { id: 'de4-a29', type: 'Audio', question: 'Jetzt', answer: 'Nu', options: ['Jetzt', 'Bald', 'Nie'], instruction: 'Zeit' },
    { id: 'de4-a30', type: 'Audio', question: 'Später', answer: 'Senere', options: ['Jetzt', 'Später'], instruction: 'Zeit' },
    { id: 'de4-a31', type: 'Audio', question: 'Gestern Abend', answer: 'I går aftes', options: ['Gestern A.', 'Heute M.'], instruction: 'Zeit' },
    { id: 'de4-a32', type: 'Audio', question: 'Heute Morgen', answer: 'I morges', options: ['Gestern A.', 'Heute M.'], instruction: 'Zeit' },
    { id: 'de4-a33', type: 'Audio', question: 'Eine Idee', answer: 'En idé', options: ['Gedanke', 'Idee'], instruction: 'Abstraktes' },
    { id: 'de4-a34', type: 'Audio', question: 'Ein Problem', answer: 'Et problem', options: ['Problem', 'Lösung'], instruction: 'Abstraktes' },
    { id: 'de4-a35', type: 'Audio', question: 'Eine Lösung', answer: 'En løsning', options: ['Problem', 'Lösung'], instruction: 'Abstraktes' },
    { id: 'de4-a36', type: 'Audio', question: 'Die Welt', answer: 'Verden', options: ['Welt', 'Land'], instruction: 'Geografie' },
    { id: 'de4-a37', type: 'Audio', question: 'Die Erde', answer: 'Jorden', options: ['Sonne', 'Erde'], instruction: 'Natur' },
    { id: 'de4-a38', type: 'Audio', question: 'Der Weltraum', answer: 'Rummet', options: ['Raum', 'Erde'], instruction: 'Natur' },
    { id: 'de4-a39', type: 'Audio', question: 'Ein Stern', answer: 'En stjerne', options: ['Mond', 'Stern'], instruction: 'Natur' },
    { id: 'de4-a40', type: 'Audio', question: 'Der Mond', answer: 'Månen', options: ['Mond', 'Stern'], instruction: 'Natur' },
    { id: 'de4-a41', type: 'Audio', question: 'Eine E-Mail schreiben', answer: 'Skrive en mail', options: ['Schreiben', 'Lesen'], instruction: 'Technik' },
    { id: 'de4-a42', type: 'Audio', question: 'Internet benutzen', answer: 'Bruge internettet', options: ['Nutzen', 'Aus'], instruction: 'Technik' },
    { id: 'de4-a43', type: 'Audio', question: 'Ein Computer', answer: 'En computer', options: ['PC', 'Handy', 'Tablet'], instruction: 'Technik' },
    { id: 'de4-a44', type: 'Audio', question: 'Einschalten', answer: 'Tænde', options: ['An', 'Aus'], instruction: 'Verben' },
    { id: 'de4-a45', type: 'Audio', question: 'Ausschalten', answer: 'Slukke', options: ['An', 'Aus'], instruction: 'Verben' },
    { id: 'de4-a46', type: 'Audio', question: 'Öffnen', answer: 'Åbne', options: ['Auf', 'Zu'], instruction: 'Verben' },
    { id: 'de4-a47', type: 'Audio', question: 'Schliessen', answer: 'Lukke', options: ['Auf', 'Zu'], instruction: 'Verben' },
    { id: 'de4-a48', type: 'Audio', question: 'Mehr', answer: 'Mere', options: ['Mehr', 'Weniger'], instruction: 'Menge' },
    { id: 'de4-a49', type: 'Audio', question: 'Weniger', answer: 'Mindre', options: ['Mehr', 'Weniger'], instruction: 'Menge' },
    { id: 'de4-a50', type: 'Audio', question: 'Viel', answer: 'Meget', options: ['Wenig', 'Viel'], instruction: 'Menge' },
    { id: 'de4-a51', type: 'Audio', question: 'Ein bisschen', answer: 'En lille smule', options: ['Wenig', 'Viel'], instruction: 'Menge' },
  ]
};
