/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const DANSK_LETTERORDER: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'da0-lo1', type: 'LetterOrder', question: 'Stav til "is"', answer: 'is', instruction: 'Noget koldt man spiser' },
    { id: 'da0-lo2', type: 'LetterOrder', question: 'Stav til "sol"', answer: 'sol', instruction: 'Den skinner på himlen' },
    { id: 'da0-lo3', type: 'LetterOrder', question: 'Stav til "hat"', answer: 'hat', instruction: 'Man har den på hovedet' },
    { id: 'da0-lo4', type: 'LetterOrder', question: 'Stav til "mor"', answer: 'mor', instruction: 'Din kvindelige forælder' },
    { id: 'da0-lo5', type: 'LetterOrder', question: 'Stav til "far"', answer: 'far', instruction: 'Din mandlige forælder' },
    { id: 'da0-lo6', type: 'LetterOrder', question: 'Stav til "ko"', answer: 'ko', instruction: 'Et dyr der giver mælk' },
    { id: 'da0-lo7', type: 'LetterOrder', question: 'Stav til "bi"', answer: 'bi', instruction: 'Et lille dyr der kan stikke' },
    { id: 'da0-lo8', type: 'LetterOrder', question: 'Stav til "sø"', answer: 'sø', instruction: 'Vand man kan fiske i' },
    { id: 'da0-lo9', type: 'LetterOrder', question: 'Stav til "te"', answer: 'te', instruction: 'En varm drik' },
    { id: 'da0-lo10', type: 'LetterOrder', question: 'Stav til "ske"', answer: 'ske', instruction: 'Den spiser man suppe med' },
    { id: 'da0-lo11', type: 'LetterOrder', question: 'Stav til "bil"', answer: 'bil', instruction: 'Den kører på vejen' },
    { id: 'da0-lo12', type: 'LetterOrder', question: 'Stav til "kat"', answer: 'kat', instruction: 'Et dyr der siger mjav' },
    { id: 'da0-lo13', type: 'LetterOrder', question: 'Stav til "mus"', answer: 'mus', instruction: 'Et lille dyr der spiser ost' },
    { id: 'da0-lo14', type: 'LetterOrder', question: 'Stav til "bus"', answer: 'bus', instruction: 'Den kører mange mennesker' },
    { id: 'da0-lo15', type: 'LetterOrder', question: 'Stav til "tog"', answer: 'tog', instruction: 'Det kører på skinner' },
    { id: 'da0-lo16', type: 'LetterOrder', question: 'Stav til "lys"', answer: 'lys', instruction: 'Det fjerner mørket' },
    { id: 'da0-lo17', type: 'LetterOrder', question: 'Stav til "mål"', answer: 'mål', instruction: 'Når man sparker bolden i nettet' },
    { id: 'da0-lo18', type: 'LetterOrder', question: 'Stav til "ris"', answer: 'ris', instruction: 'Noget hvidt man spiser' },
    { id: 'da0-lo19', type: 'LetterOrder', question: 'Stav til "sav"', answer: 'sav', instruction: 'Man bruger den til træ' },
    { id: 'da0-lo20', type: 'LetterOrder', question: 'Stav til "ven"', answer: 'ven', instruction: 'En man leger med' },
    { id: 'da0-lo21', type: 'LetterOrder', question: 'Stav til "bog"', answer: 'bog', instruction: 'Den kan man læse i' },
    { id: 'da0-lo22', type: 'LetterOrder', question: 'Stav til "tøj"', answer: 'tøj', instruction: 'Man har det på kroppen' },
    { id: 'da0-lo23', type: 'LetterOrder', question: 'Stav til "øje"', answer: 'øje', instruction: 'Det ser man med' },
    { id: 'da0-lo24', type: 'LetterOrder', question: 'Stav til "ben"', answer: 'ben', instruction: 'Dem går man på' },
    { id: 'da0-lo25', type: 'LetterOrder', question: 'Stav til "fod"', answer: 'fod', instruction: 'Den sidder for enden af benet' },
    { id: 'da0-lo26', type: 'LetterOrder', question: 'Stav til "arm"', answer: 'arm', instruction: 'Den sidder ved skulderen' },
    { id: 'da0-lo27', type: 'LetterOrder', question: 'Stav til "mad"', answer: 'mad', instruction: 'Det spiser man' },
    { id: 'da0-lo28', type: 'LetterOrder', question: 'Stav til "hår"', answer: 'hår', instruction: 'Det groer på hovedet' },
    { id: 'da0-lo29', type: 'LetterOrder', question: 'Stav til "blå"', answer: 'blå', instruction: 'Himlens farve' },
    { id: 'da0-lo30', type: 'LetterOrder', question: 'Stav til "rød"', answer: 'rød', instruction: 'Blodets farve' },
    { id: 'da0-lo31', type: 'LetterOrder', question: 'Stav til "gul"', answer: 'gul', instruction: 'Solen er denne farve' },
    { id: 'da0-lo32', type: 'LetterOrder', question: 'Stav til "mur"', answer: 'mur', instruction: 'Den bygger man huse med' },
    { id: 'da0-lo33', type: 'LetterOrder', question: 'Stav til "dyr"', answer: 'dyr', instruction: 'En hund er et ___' },
    { id: 'da0-lo34', type: 'LetterOrder', question: 'Stav til "får"', answer: 'får', instruction: 'Et dyr med uld' },
    { id: 'da0-lo35', type: 'LetterOrder', question: 'Stav til "ræv"', answer: 'ræv', instruction: 'Et rødt dyr i skoven' },
    { id: 'da0-lo36', type: 'LetterOrder', question: 'Stav til "sky"', answer: 'sky', instruction: 'Den er hvid og på himlen' },
    { id: 'da0-lo37', type: 'LetterOrder', question: 'Stav til "vej"', answer: 'vej', instruction: 'Her kører bilerne' },
    { id: 'da0-lo38', type: 'LetterOrder', question: 'Stav til "hus"', answer: 'hus', instruction: 'Her bor man' },
    { id: 'da0-lo39', type: 'LetterOrder', question: 'Stav til "skib"', answer: 'skib', instruction: 'Det sejler på vandet' },
    { id: 'da0-lo40', type: 'LetterOrder', question: 'Stav til "gave"', answer: 'gave', instruction: 'Man får den til fødselsdag' },
    { id: 'da0-lo41', type: 'LetterOrder', question: 'Stav til "lam"', answer: 'lam', instruction: 'En lille unge af et får' },
    { id: 'da0-lo42', type: 'LetterOrder', question: 'Stav til "pil"', answer: 'pil', instruction: 'Man skyder med bue og ___' },
    { id: 'da0-lo43', type: 'LetterOrder', question: 'Stav til "kop"', answer: 'kop', instruction: 'Man drikker mælk af den' },
    { id: 'da0-lo44', type: 'LetterOrder', question: 'Stav til "and"', answer: 'and', instruction: 'En fugl i søen' },
    { id: 'da0-lo45', type: 'LetterOrder', question: 'Stav til "ost"', answer: 'ost', instruction: 'Den er gul og ligger på brødet' },
    { id: 'da0-lo46', type: 'LetterOrder', question: 'Stav til "æg"', answer: 'æg', instruction: 'Hønen lægger det' },
    { id: 'da0-lo47', type: 'LetterOrder', question: 'Stav til "is"', answer: 'is', instruction: 'Koldt slik' },
    { id: 'da0-lo48', type: 'LetterOrder', question: 'Stav til "jul"', answer: 'jul', instruction: 'En fest i december' },
    { id: 'da0-lo49', type: 'LetterOrder', question: 'Stav til "dag"', answer: 'dag', instruction: 'Det modsatte af nat' },
    { id: 'da0-lo50', type: 'LetterOrder', question: 'Stav til "nat"', answer: 'nat', instruction: 'Når man sover er det ___' },
    { id: 'da0-lo51', type: 'LetterOrder', question: 'Stav til "du"', answer: 'du', instruction: 'Det modsatte af jeg' },
  ],
  1: [
    { id: 'da1-lo1', type: 'LetterOrder', question: 'Stav til "hest"', answer: 'hest', instruction: 'Et dyr man kan ride på' },
    { id: 'da1-lo2', type: 'LetterOrder', question: 'Stav til "skole"', answer: 'skole', instruction: 'Her lærer man ting' },
    { id: 'da1-lo3', type: 'LetterOrder', question: 'Stav til "cykel"', answer: 'cykel', instruction: 'Den har to hjul' },
    { id: 'da1-lo4', type: 'LetterOrder', question: 'Stav til "æble"', answer: 'æble', instruction: 'En rød eller grøn frugt' },
    { id: 'da1-lo5', type: 'LetterOrder', question: 'Stav til "bord"', answer: 'bord', instruction: 'Man sidder ved det og spiser' },
    { id: 'da1-lo6', type: 'LetterOrder', question: 'Stav til "stol"', answer: 'stol', instruction: 'Den sidder man på' },
    { id: 'da1-lo7', type: 'LetterOrder', question: 'Stav til "pige"', answer: 'pige', instruction: 'Et barn af hunkøn' },
    { id: 'da1-lo8', type: 'LetterOrder', question: 'Stav til "dreng"', answer: 'dreng', instruction: 'Et barn af hankøn' },
    { id: 'da1-lo9', type: 'LetterOrder', question: 'Stav til "vand"', answer: 'vand', instruction: 'Det drikker man når man er tørstig' },
    { id: 'da1-lo10', type: 'LetterOrder', question: 'Stav til "mælk"', answer: 'mælk', instruction: 'En hvid drik fra koen' },
    { id: 'da1-lo11', type: 'LetterOrder', question: 'Stav til "brød"', answer: 'brød', instruction: 'Man laver madder med det' },
    { id: 'da1-lo12', type: 'LetterOrder', question: 'Stav til "smør"', answer: 'smør', instruction: 'Man smører det på brødet' },
    { id: 'da1-lo13', type: 'LetterOrder', question: 'Stav til "kage"', answer: 'kage', instruction: 'Noget sødt man bager' },
    { id: 'da1-lo14', type: 'LetterOrder', question: 'Stav til "bold"', answer: 'bold', instruction: 'Den sparker man til' },
    { id: 'da1-lo15', type: 'LetterOrder', question: 'Stav til "bane"', answer: 'bane', instruction: 'Her spiller man fodbold' },
    { id: 'da1-lo16', type: 'LetterOrder', question: 'Stav til "træ"', answer: 'træ', instruction: 'Det groer i skoven' },
    { id: 'da1-lo17', type: 'LetterOrder', question: 'Stav til "græs"', answer: 'græs', instruction: 'Det er grønt og groer i haven' },
    { id: 'da1-lo18', type: 'LetterOrder', question: 'Stav til "vejr"', answer: 'vejr', instruction: 'Det kan være sol eller regn' },
    { id: 'da1-lo19', type: 'LetterOrder', question: 'Stav til "regn"', answer: 'regn', instruction: 'Vand der falder fra himlen' },
    { id: 'da1-lo20', type: 'LetterOrder', question: 'Stav til "sne"', answer: 'sne', instruction: 'Hvidt og koldt fra himlen' },
    { id: 'da1-lo21', type: 'LetterOrder', question: 'Stav til "vind"', answer: 'vind', instruction: 'Luft der bevæger sig' },
    { id: 'da1-lo22', type: 'LetterOrder', question: 'Stav til "taske"', answer: 'taske', instruction: 'Man har sine ting i den' },
    { id: 'da1-lo23', type: 'LetterOrder', question: 'Stav til "bog"', answer: 'bog', instruction: 'Noget man læser' },
    { id: 'da1-lo24', type: 'LetterOrder', question: 'Stav til "blad"', answer: 'blad', instruction: 'Det sidder på træet' },
    { id: 'da1-lo25', type: 'LetterOrder', question: 'Stav til "sang"', answer: 'sang', instruction: 'Noget man synger' },
    { id: 'da1-lo26', type: 'LetterOrder', question: 'Stav til "dans"', answer: 'dans', instruction: 'Man bevæger sig til musik' },
    { id: 'da1-lo27', type: 'LetterOrder', question: 'Stav til "glad"', answer: 'glad', instruction: 'Man smiler når man er ___' },
    { id: 'da1-lo28', type: 'LetterOrder', question: 'Stav til "trist"', answer: 'trist', instruction: 'Man græder når man er ___' },
    { id: 'da1-lo29', type: 'LetterOrder', question: 'Stav til "sur"', answer: 'sur', instruction: 'Man skælder ud når man er ___' },
    { id: 'da1-lo30', type: 'LetterOrder', question: 'Stav til "søvn"', answer: 'søvn', instruction: 'Det man får når man sover' },
    { id: 'da1-lo31', type: 'LetterOrder', question: 'Stav til "drøm"', answer: 'drøm', instruction: 'Billeder man ser mens man sover' },
    { id: 'da1-lo32', type: 'LetterOrder', question: 'Stav til "morgen"', answer: 'morgen', instruction: 'Når man står op' },
    { id: 'da1-lo33', type: 'LetterOrder', question: 'Stav til "aften"', answer: 'aften', instruction: 'Når man snart skal sove' },
    { id: 'da1-lo34', type: 'LetterOrder', question: 'Stav til "nat"', answer: 'nat', instruction: 'Når det er mørkt' },
    { id: 'da1-lo35', type: 'LetterOrder', question: 'Stav til "uge"', answer: 'uge', instruction: 'Syv dage er en ___' },
    { id: 'da1-lo36', type: 'LetterOrder', question: 'Stav til "år"', answer: 'år', instruction: 'Tolv måneder er et ___' },
    { id: 'da1-lo37', type: 'LetterOrder', question: 'Stav til "navn"', answer: 'navn', instruction: 'Det du hedder' },
    { id: 'da1-lo38', type: 'LetterOrder', question: 'Stav til "by"', answer: 'by', instruction: 'Et sted med mange huse' },
    { id: 'da1-lo39', type: 'LetterOrder', question: 'Stav til "skov"', answer: 'skov', instruction: 'Et sted med mange træer' },
    { id: 'da1-lo40', type: 'LetterOrder', question: 'Stav til "mark"', answer: 'mark', instruction: 'Her groer kornet' },
    { id: 'da1-lo41', type: 'LetterOrder', question: 'Stav til "have"', answer: 'have', instruction: 'Ved huset hvor græsset groer' },
    { id: 'da1-lo42', type: 'LetterOrder', question: 'Stav til "blomst"', answer: 'blomst', instruction: 'Den er pæn og dufter' },
    { id: 'da1-lo43', type: 'LetterOrder', question: 'Stav til "dyr"', answer: 'dyr', instruction: 'Hund, kat og hest' },
    { id: 'da1-lo44', type: 'LetterOrder', question: 'Stav til "fisk"', answer: 'fisk', instruction: 'Den svømmer i vandet' },
    { id: 'da1-lo45', type: 'LetterOrder', question: 'Stav til "fugl"', answer: 'fugl', instruction: 'Den flyver i luften' },
    { id: 'da1-lo46', type: 'LetterOrder', question: 'Stav til "mus"', answer: 'mus', instruction: 'Lille gråt dyr' },
    { id: 'da1-lo47', type: 'LetterOrder', question: 'Stav til "ræv"', answer: 'ræv', instruction: 'Rødt dyr i skoven' },
    { id: 'da1-lo48', type: 'LetterOrder', question: 'Stav til "ulv"', answer: 'ulv', instruction: 'Den ligner en hund og tuder' },
    { id: 'da1-lo49', type: 'LetterOrder', question: 'Stav til "ko"', answer: 'ko', instruction: 'Stor og brun og giver mælk' },
    { id: 'da1-lo50', type: 'LetterOrder', question: 'Stav til "gris"', instruction: 'Lyserødt dyr på gården', answer: 'gris' },
    { id: 'da1-lo51', type: 'LetterOrder', question: 'Stav til "får"', instruction: 'Dyr med meget uld', answer: 'får' },
  ],
  2: [
    { id: 'da2-lo1', type: 'LetterOrder', question: 'Stav til "pølse"', answer: 'pølse', instruction: 'Noget man spiser i en hotdog' },
    { id: 'da2-lo2', type: 'LetterOrder', question: 'Stav til "flyve"', answer: 'flyve', instruction: 'Det gør fugle og flymaskiner' },
    { id: 'da2-lo3', type: 'LetterOrder', question: 'Stav til "vindue"', answer: 'vindue', instruction: 'Man kan kigge ud gennem glasset' },
    { id: 'da2-lo4', type: 'LetterOrder', question: 'Stav til "trappe"', answer: 'trappe', instruction: 'Man går op af den til 1. sal' },
    { id: 'da2-lo5', type: 'LetterOrder', question: 'Stav til "køkken"', answer: 'køkken', instruction: 'Her laver man mad' },
    { id: 'da2-lo6', type: 'LetterOrder', question: 'Stav til "stue"', answer: 'stue', instruction: 'Her ser man fjernsyn' },
    { id: 'da2-lo7', type: 'LetterOrder', question: 'Stav til "sove"', answer: 'sove', instruction: 'Det gør man om natten' },
    { id: 'da2-lo8', type: 'LetterOrder', question: 'Stav til "drømme"', answer: 'drømme', instruction: 'Det gør man når man sover' },
    { id: 'da2-lo9', type: 'LetterOrder', question: 'Stav til "vågne"', answer: 'vågne', instruction: 'Det gør man om morgenen' },
    { id: 'da2-lo10', type: 'LetterOrder', question: 'Stav til "drikke"', answer: 'drikke', instruction: 'Man ___ vand' },
    { id: 'da2-lo11', type: 'LetterOrder', question: 'Stav til "spise"', answer: 'spise', instruction: 'Man ___ mad' },
    { id: 'da2-lo12', type: 'LetterOrder', question: 'Stav til "løbe"', answer: 'løbe', instruction: 'At bevæge sig hurtigt med benene' },
    { id: 'da2-lo13', type: 'LetterOrder', question: 'Stav til "hoppe"', answer: 'hoppe', instruction: 'At springe op i luften' },
    { id: 'da2-lo14', type: 'LetterOrder', question: 'Stav til "danse"', answer: 'danse', instruction: 'At bevæge sig til musik' },
    { id: 'da2-lo15', type: 'LetterOrder', question: 'Stav til "synge"', answer: 'synge', instruction: 'At lave musik med stemmen' },
    { id: 'da2-lo16', type: 'LetterOrder', question: 'Stav til "lytte"', answer: 'lytte', instruction: 'At bruge sine ører' },
    { id: 'da2-lo17', type: 'LetterOrder', question: 'Stav til "kigge"', answer: 'kigge', instruction: 'At bruge sine øjne' },
    { id: 'da2-lo18', type: 'LetterOrder', question: 'Stav til "lugte"', answer: 'lugte', instruction: 'At bruge sin næse' },
    { id: 'da2-lo19', type: 'LetterOrder', question: 'Stav til "smage"', answer: 'smage', instruction: 'At bruge sin tunge' },
    { id: 'da2-lo20', type: 'LetterOrder', question: 'Stav til "føle"', answer: 'føle', instruction: 'At bruge sine hænder' },
    { id: 'da2-lo21', type: 'LetterOrder', question: 'Stav til "varm"', answer: 'varm', instruction: 'Det modsatte af kold' },
    { id: 'da2-lo22', type: 'LetterOrder', question: 'Stav til "kold"', answer: 'kold', instruction: 'Det modsatte af varm' },
    { id: 'da2-lo23', type: 'LetterOrder', question: 'Stav til "sød"', answer: 'sød', instruction: 'Kage smager ___' },
    { id: 'da2-lo24', type: 'LetterOrder', question: 'Stav til "sur"', answer: 'sur', instruction: 'Citron smager ___' },
    { id: 'da2-lo25', type: 'LetterOrder', question: 'Stav til "salt"', answer: 'salt', instruction: 'Chips smager af ___' },
    { id: 'da2-lo26', type: 'LetterOrder', question: 'Stav til "stærk"', answer: 'stærk', instruction: 'Peber og chili er ___' },
    { id: 'da2-lo27', type: 'LetterOrder', question: 'Stav til "blød"', answer: 'blød', instruction: 'En pude er ___' },
    { id: 'da2-lo28', type: 'LetterOrder', question: 'Stav til "hård"', answer: 'hård', instruction: 'En sten er ___' },
    { id: 'da2-lo29', type: 'LetterOrder', question: 'Stav til "tung"', answer: 'tung', instruction: 'Det modsatte af let' },
    { id: 'da2-lo30', type: 'LetterOrder', question: 'Stav til "let"', answer: 'let', instruction: 'Det modsatte af tung' },
    { id: 'da2-lo31', type: 'LetterOrder', question: 'Stav til "hurtig"', answer: 'hurtig', instruction: 'Det modsatte af langsom' },
    { id: 'da2-lo32', type: 'LetterOrder', question: 'Stav til "langsom"', answer: 'langsom', instruction: 'Det modsatte af hurtig' },
    { id: 'da2-lo33', type: 'LetterOrder', question: 'Stav til "stor"', answer: 'stor', instruction: 'Det modsatte af lille' },
    { id: 'da2-lo34', type: 'LetterOrder', question: 'Stav til "lille"', answer: 'lille', instruction: 'Det modsatte af stor' },
    { id: 'da2-lo35', type: 'LetterOrder', question: 'Stav til "glad"', answer: 'glad', instruction: 'Det modsatte af ked af det' },
    { id: 'da2-lo36', type: 'LetterOrder', question: 'Stav til "træt"', answer: 'træt', instruction: 'Man er ___ når man vil sove' },
    { id: 'da2-lo37', type: 'LetterOrder', question: 'Stav til "syg"', answer: 'syg', instruction: 'Man er ___ når man har feber' },
    { id: 'da2-lo38', type: 'LetterOrder', question: 'Stav til "rask"', answer: 'rask', instruction: 'Når man ikke er syg mere' },
    { id: 'da2-lo39', type: 'LetterOrder', question: 'Stav til "barn"', answer: 'barn', instruction: 'En lille person' },
    { id: 'da2-lo40', type: 'LetterOrder', question: 'Stav til "voksen"', answer: 'voksen', instruction: 'En stor person' },
    { id: 'da2-lo41', type: 'LetterOrder', question: 'Stav til "familie"', answer: 'familie', instruction: 'Mor, far og børn' },
    { id: 'da2-lo42', type: 'LetterOrder', question: 'Stav til "venner"', answer: 'venner', instruction: 'Dem man kan lide at lege med' },
    { id: 'da2-lo43', type: 'LetterOrder', question: 'Stav til "skole"', answer: 'skole', instruction: 'Her lærer man at læse og regne' },
    { id: 'da2-lo44', type: 'LetterOrder', question: 'Stav til "lærer"', answer: 'lærer', instruction: 'Den person der forklarer tingene' },
    { id: 'da2-lo45', type: 'LetterOrder', question: 'Stav til "elev"', answer: 'elev', instruction: 'En person der går i skole' },
    { id: 'da2-lo46', type: 'LetterOrder', question: 'Stav til "bogstav"', answer: 'bogstav', instruction: 'A, B, C er et ___' },
    { id: 'da2-lo47', type: 'LetterOrder', question: 'Stav til "tal"', answer: 'tal', instruction: '1, 2, 3 er et ___' },
    { id: 'da2-lo48', type: 'LetterOrder', question: 'Stav til "ord"', answer: 'ord', instruction: 'Når man sætter bogstaver sammen' },
    { id: 'da2-lo49', type: 'LetterOrder', question: 'Stav til "sætning"', answer: 'sætning', instruction: 'Når man sætter ord sammen' },
    { id: 'da2-lo50', type: 'LetterOrder', question: 'Stav til "point"', answer: 'point', instruction: 'Det får man når man svarer rigtigt' },
    { id: 'da2-lo51', type: 'LetterOrder', question: 'Stav til "slut"', answer: 'slut', instruction: 'Når det er færdigt' },
  ],
  3: [
    { id: 'da3-lo1', type: 'LetterOrder', question: 'Stav til "vigtig"', answer: 'vigtig', instruction: 'Noget man skal huske' },
    { id: 'da3-lo2', type: 'LetterOrder', question: 'Stav til "mange"', answer: 'mange', instruction: 'Det modsatte af få' },
    { id: 'da3-lo3', type: 'LetterOrder', question: 'Stav til "meget"', answer: 'meget', instruction: 'En stor mængde' },
    { id: 'da3-lo4', type: 'LetterOrder', question: 'Stav til "hvilken"', answer: 'hvilken', instruction: 'Et spørgeord' },
    { id: 'da3-lo5', type: 'LetterOrder', question: 'Stav til "fordi"', answer: 'fordi', instruction: 'Når man forklarer noget' },
    { id: 'da3-lo6', type: 'LetterOrder', question: 'Stav til "måske"', answer: 'måske', instruction: 'Når man ikke er helt sikker' },
    { id: 'da3-lo7', type: 'LetterOrder', question: 'Stav til "aldrig"', answer: 'aldrig', instruction: 'Det modsatte af altid' },
    { id: 'da3-lo8', type: 'LetterOrder', question: 'Stav til "altid"', answer: 'altid', instruction: 'Det modsatte af aldrig' },
    { id: 'da3-lo9', type: 'LetterOrder', question: 'Stav til "ofte"', answer: 'ofte', instruction: 'Når det sker mange gange' },
    { id: 'da3-lo10', type: 'LetterOrder', question: 'Stav til "sjældent"', answer: 'sjældent', instruction: 'Når det næsten aldrig sker' },
    { id: 'da3-lo11', type: 'LetterOrder', question: 'Stav til "spændende"', answer: 'spændende', instruction: 'Bogen var meget ___' },
    { id: 'da3-lo12', type: 'LetterOrder', question: 'Stav til "kedelig"', answer: 'kedelig', instruction: 'Det modsatte af spændende' },
    { id: 'da3-lo13', type: 'LetterOrder', question: 'Stav til "farlig"', answer: 'farlig', instruction: 'En løve kan være ___' },
    { id: 'da3-lo14', type: 'LetterOrder', question: 'Stav til "sikker"', answer: 'sikker', instruction: 'Det modsatte af farlig' },
    { id: 'da3-lo15', type: 'LetterOrder', question: 'Stav til "hurtig"', answer: 'hurtig', instruction: 'En bil er ___' },
    { id: 'da3-lo16', type: 'LetterOrder', question: 'Stav til "langsom"', answer: 'langsom', instruction: 'En snegl er ___' },
    { id: 'da3-lo17', type: 'LetterOrder', question: 'Stav til "dygtig"', answer: 'dygtig', instruction: 'Når man er god til noget' },
    { id: 'da3-lo18', type: 'LetterOrder', question: 'Stav til "stærk"', answer: 'stærk', instruction: 'Når man kan løfte meget' },
    { id: 'da3-lo19', type: 'LetterOrder', question: 'Stav til "svag"', answer: 'svag', instruction: 'Det modsatte af stærk' },
    { id: 'da3-lo20', type: 'LetterOrder', question: 'Stav til "klog"', answer: 'klog', instruction: 'Når man ved meget' },
    { id: 'da3-lo21', type: 'LetterOrder', question: 'Stav til "dum"', answer: 'dum', instruction: 'Det modsatte af klog' },
    { id: 'da3-lo22', type: 'LetterOrder', question: 'Stav til "pæn"', answer: 'pæn', instruction: 'Det modsatte af grim' },
    { id: 'da3-lo23', type: 'LetterOrder', question: 'Stav til "grim"', answer: 'grim', instruction: 'Det modsatte af pæn' },
    { id: 'da3-lo24', type: 'LetterOrder', question: 'Stav til "dejlig"', answer: 'dejlig', instruction: 'Noget der er rigtig godt' },
    { id: 'da3-lo25', type: 'LetterOrder', question: 'Stav til "træls"', answer: 'træls', instruction: 'Jysk ord for irriterende' },
    { id: 'da3-lo26', type: 'LetterOrder', question: 'Stav til "mandag"', answer: 'mandag', instruction: 'Den første dag i ugen' },
    { id: 'da3-lo27', type: 'LetterOrder', question: 'Stav til "tirsdag"', answer: 'tirsdag', instruction: 'Dagen efter mandag' },
    { id: 'da3-lo28', type: 'LetterOrder', question: 'Stav til "onsdag"', answer: 'onsdag', instruction: 'Dagen efter tirsdag' },
    { id: 'da3-lo29', type: 'LetterOrder', question: 'Stav til "torsdag"', answer: 'torsdag', instruction: 'Dagen efter onsdag' },
    { id: 'da3-lo30', type: 'LetterOrder', question: 'Stav til "fredag"', answer: 'fredag', instruction: 'Sidste hverdag i ugen' },
    { id: 'da3-lo31', type: 'LetterOrder', question: 'Stav til "lørdag"', answer: 'lørdag', instruction: 'Den første dag i weekenden' },
    { id: 'da3-lo32', type: 'LetterOrder', question: 'Stav til "søndag"', answer: 'søndag', instruction: 'Den sidste dag i ugen' },
    { id: 'da3-lo33', type: 'LetterOrder', question: 'Stav til "januar"', answer: 'januar', instruction: 'Årets første måned' },
    { id: 'da3-lo34', type: 'LetterOrder', question: 'Stav til "februar"', answer: 'februar', instruction: 'Årets korteste måned' },
    { id: 'da3-lo35', type: 'LetterOrder', question: 'Stav til "marts"', answer: 'marts', instruction: 'Dagen hvor foråret starter' },
    { id: 'da3-lo36', type: 'LetterOrder', question: 'Stav til "april"', answer: 'april', instruction: 'Måneden hvor man narrer folk' },
    { id: 'da3-lo37', type: 'LetterOrder', question: 'Stav til "maj"', answer: 'maj', instruction: 'En måned om foråret' },
    { id: 'da3-lo38', type: 'LetterOrder', question: 'Stav til "juni"', answer: 'juni', instruction: 'Måneden hvor sommeren starter' },
    { id: 'da3-lo39', type: 'LetterOrder', question: 'Stav til "juli"', answer: 'juli', instruction: 'Den varmeste sommermåned' },
    { id: 'da3-lo40', type: 'LetterOrder', question: 'Stav til "august"', answer: 'august', instruction: 'Måneden hvor skolen starter igen' },
    { id: 'da3-lo41', type: 'LetterOrder', question: 'Stav til "september"', answer: 'september', instruction: 'Måneden hvor efteråret starter' },
    { id: 'da3-lo42', type: 'LetterOrder', question: 'Stav til "oktober"', answer: 'oktober', instruction: 'Måneden med efterårsferie' },
    { id: 'da3-lo43', type: 'LetterOrder', question: 'Stav til "november"', answer: 'november', instruction: 'Måneden før jul' },
    { id: 'da3-lo44', type: 'LetterOrder', question: 'Stav til "december"', answer: 'december', instruction: 'Årets sidste måned' },
    { id: 'da3-lo45', type: 'LetterOrder', question: 'Stav til "vinter"', answer: 'vinter', instruction: 'Årstiden med sne' },
    { id: 'da3-lo46', type: 'LetterOrder', question: 'Stav til "forår"', answer: 'forår', instruction: 'Årstiden hvor blomsterne kommer' },
    { id: 'da3-lo47', type: 'LetterOrder', question: 'Stav til "sommer"', answer: 'sommer', instruction: 'Årstiden med sol og strand' },
    { id: 'da3-lo48', type: 'LetterOrder', question: 'Stav til "efterår"', answer: 'efterår', instruction: 'Årstiden hvor bladene falder' },
    { id: 'da3-lo49', type: 'LetterOrder', question: 'Stav til "ferie"', answer: 'ferie', instruction: 'Når man har fri fra skole' },
    { id: 'da3-lo50', type: 'LetterOrder', question: 'Stav til "rejse"', answer: 'rejse', instruction: 'Når man tager til et andet land' },
    { id: 'da3-lo51', type: 'LetterOrder', question: 'Stav til "hjemme"', answer: 'hjemme', instruction: 'Der hvor man bor' },
  ],
  4: [
    { id: 'da4-lo1', type: 'LetterOrder', question: 'Stav til "begyndelse"', answer: 'begyndelse', instruction: 'Der hvor noget starter' },
    { id: 'da4-lo2', type: 'LetterOrder', question: 'Stav til "afslutning"', answer: 'afslutning', instruction: 'Der hvor noget slutter' },
    { id: 'da4-lo3', type: 'LetterOrder', question: 'Stav til "menneske"', answer: 'menneske', instruction: 'En person' },
    { id: 'da4-lo4', type: 'LetterOrder', question: 'Stav til "verden"', answer: 'verden', instruction: 'Hele jorden' },
    { id: 'da4-lo5', type: 'LetterOrder', question: 'Stav til "land")', answer: 'land', instruction: 'Danmark er et ___' },
    { id: 'da4-lo6', type: 'LetterOrder', question: 'Stav til "hovedstad"', answer: 'hovedstad', instruction: 'Den vigtigste by i et land' },
    { id: 'da4-lo7', type: 'LetterOrder', question: 'Stav til "København"', answer: 'København', instruction: 'Danmarks hovedstad' },
    { id: 'da4-lo8', type: 'LetterOrder', question: 'Stav til "historie"', answer: 'historie', instruction: 'Noget der er sket før i tiden' },
    { id: 'da4-lo9', type: 'LetterOrder', question: 'Stav til "fremtid"', answer: 'fremtid', instruction: 'Det der skal ske senere' },
    { id: 'da4-lo10', type: 'LetterOrder', question: 'Stav til "morgenmad"', answer: 'morgenmad', instruction: 'Det man spiser når man står op' },
    { id: 'da4-lo11', type: 'LetterOrder', question: 'Stav til "frokost"', answer: 'frokost', instruction: 'Det man spiser midt på dagen' },
    { id: 'da4-lo12', type: 'LetterOrder', question: 'Stav til "aftensmad"', answer: 'aftensmad', instruction: 'Det man spiser sidst på dagen' },
    { id: 'da4-lo13', type: 'LetterOrder', question: 'Stav til "kartofler"', answer: 'kartofler', instruction: 'Noget man graver op af jorden og spiser' },
    { id: 'da4-lo14', type: 'LetterOrder', question: 'Stav til "grøntsager"', answer: 'grøntsager', instruction: 'Gulerødder, ærter og bønner' },
    { id: 'da4-lo15', type: 'LetterOrder', question: 'Stav til "frugter"', answer: 'frugter', instruction: 'Æbler, pærer og bananer' },
    { id: 'da4-lo16', type: 'LetterOrder', question: 'Stav til "dessert"', answer: 'dessert', instruction: 'Det søde efter maden' },
    { id: 'da4-lo17', type: 'LetterOrder', question: 'Stav til "restaurant"', answer: 'restaurant', instruction: 'Et sted hvor man køber mad' },
    { id: 'da4-lo18', type: 'LetterOrder', question: 'Stav til "chauffør"', answer: 'chauffør', instruction: 'En der kører bil eller bus' },
    { id: 'da4-lo19', type: 'LetterOrder', question: 'Stav til "betjent"', answer: 'betjent', instruction: 'En der arbejder ved politiet' },
    { id: 'da4-lo20', type: 'LetterOrder', question: 'Stav til "læge"', answer: 'læge', instruction: 'En der hjælper syge folk' },
    { id: 'da4-lo21', type: 'LetterOrder', question: 'Stav til "sygeplejerske"', answer: 'sygeplejerske', instruction: 'En der arbejder på hospitalet' },
    { id: 'da4-lo22', type: 'LetterOrder', question: 'Stav til "brandmand"', answer: 'brandmand', instruction: 'En der slukker ildebrande' },
    { id: 'da4-lo23', type: 'LetterOrder', question: 'Stav til "bibliotek"', answer: 'bibliotek', instruction: 'Her kan man låne bøger' },
    { id: 'da4-lo24', type: 'LetterOrder', question: 'Stav til "museum"', answer: 'museum', instruction: 'Her kan man se gamle ting' },
    { id: 'da4-lo25', type: 'LetterOrder', question: 'Stav til "biograf"', answer: 'biograf', instruction: 'Her ser man film på et stort lærred' },
    { id: 'da4-lo26', type: 'LetterOrder', question: 'Stav til "teater"', answer: 'teater', instruction: 'Her ser man skuespil' },
    { id: 'da4-lo27', type: 'LetterOrder', question: 'Stav til "musik"', answer: 'musik', instruction: 'Noget man lytter til' },
    { id: 'da4-lo28', type: 'LetterOrder', question: 'Stav til "guitar"', answer: 'guitar', instruction: 'Et instrument med strenge' },
    { id: 'da4-lo29', type: 'LetterOrder', question: 'Stav til "klaver"', answer: 'klaver', instruction: 'Et instrument med tangenter' },
    { id: 'da4-lo30', type: 'LetterOrder', question: 'Stav til "trommer"', answer: 'trommer', instruction: 'Dem slår man på' },
    { id: 'da4-lo31', type: 'LetterOrder', question: 'Stav til "orkester"', answer: 'orkester', instruction: 'Mange der spiller musik sammen' },
    { id: 'da4-lo32', type: 'LetterOrder', question: 'Stav til "koncert"', answer: 'koncert', instruction: 'Når man hører musik live' },
    { id: 'da4-lo33', type: 'LetterOrder', question: 'Stav til "computer"', answer: 'computer', instruction: 'En maskine man kan spille på' },
    { id: 'da4-lo34', type: 'LetterOrder', question: 'Stav til "internet"', answer: 'internet', instruction: 'Her finder man hjemmesider' },
    { id: 'da4-lo35', type: 'LetterOrder', question: 'Stav til "telefon"', answer: 'telefon', instruction: 'Den ringer man med' },
    { id: 'da4-lo36', type: 'LetterOrder', question: 'Stav til "fjernsyn"', answer: 'fjernsyn', instruction: 'Her ser man nyheder og serier' },
    { id: 'da4-lo37', type: 'LetterOrder', question: 'Stav til "avis"', answer: 'avis', instruction: 'Noget man læser nyheder i' },
    { id: 'da4-lo38', type: 'LetterOrder', question: 'Stav til "magasin"', answer: 'magasin', instruction: 'Et tykt ugeblad' },
    { id: 'da4-lo39', type: 'LetterOrder', question: 'Stav til "reklame"', answer: 'reklame', instruction: 'Noget der vil sælge noget' },
    { id: 'da4-lo40', type: 'LetterOrder', question: 'Stav til "penge"', answer: 'penge', instruction: 'Dem betaler man med' },
    { id: 'da4-lo41', type: 'LetterOrder', question: 'Stav til "butik"', answer: 'butik', instruction: 'Her køber man ting' },
    { id: 'da4-lo42', type: 'LetterOrder', question: 'Stav til "marked"', answer: 'marked', instruction: 'Et sted med mange boder' },
    { id: 'da4-lo43', type: 'LetterOrder', question: 'Stav til "pris"', answer: 'pris', instruction: 'Hvad noget koster' },
    { id: 'da4-lo44', type: 'LetterOrder', question: 'Stav til "rabat"', answer: 'rabat', instruction: 'Når noget er billigere' },
    { id: 'da4-lo45', type: 'LetterOrder', question: 'Stav til "kvittering"', answer: 'kvittering', instruction: 'Den får man efter købet' },
    { id: 'da4-lo46', type: 'LetterOrder', question: 'Stav til "taske"', answer: 'taske', instruction: 'Her har man sine ting i' },
    { id: 'da4-lo47', type: 'LetterOrder', question: 'Stav til "pung"', answer: 'pung', instruction: 'Her har man sine penge i' },
    { id: 'da4-lo48', type: 'LetterOrder', question: 'Stav til "nøgle"', answer: 'nøgle', instruction: 'Den låser man døre op med' },
    { id: 'da4-lo49', type: 'LetterOrder', question: 'Stav til "briller"', answer: 'briller', instruction: 'Dem har man på hvis man ser dårligt' },
    { id: 'da4-lo50', type: 'LetterOrder', question: 'Stav til "ur"', answer: 'ur', instruction: 'Det viser hvad klokken er' },
    { id: 'da4-lo51', type: 'LetterOrder', question: 'Stav til "armbånd"', answer: 'armbånd', instruction: 'Et smykke til armen' },
  ],
  5: [
    { id: 'da5-lo1', type: 'LetterOrder', question: 'Stav til "astronaut"', answer: 'astronaut', instruction: 'En person der rejser i rummet' },
    { id: 'da5-lo2', type: 'LetterOrder', question: 'Stav til "planeter"', answer: 'planeter', instruction: 'Jorden, Mars og Jupiter' },
    { id: 'da5-lo3', type: 'LetterOrder', question: 'Stav til "stjerner"', answer: 'stjerner', instruction: 'De lyser på nattehimlen' },
    { id: 'da5-lo4', type: 'LetterOrder', question: 'Stav til "univers"', answer: 'univers', instruction: 'Alt hvad der findes i rummet' },
    { id: 'da5-lo5', type: 'LetterOrder', question: 'Stav til "teleskop"', answer: 'teleskop', instruction: 'Det man kigger på stjerner med' },
    { id: 'da5-lo6', type: 'LetterOrder', question: 'Stav til "satellit"', answer: 'satellit', instruction: 'Noget der flyver rundt om jorden' },
    { id: 'da5-lo7', type: 'LetterOrder', question: 'Stav til "raket"', answer: 'raket', instruction: 'Den flyver ud i rummet' },
    { id: 'da5-lo8', type: 'LetterOrder', question: 'Stav til "tyngdekraft"', answer: 'tyngdekraft', instruction: 'Den kraft der holder os på jorden' },
    { id: 'da5-lo9', type: 'LetterOrder', question: 'Stav til "atmosfære"', answer: 'atmosfære', instruction: 'Luften omkring jorden' },
    { id: 'da5-lo10', type: 'LetterOrder', question: 'Stav til "ilt"', answer: 'ilt', instruction: 'Det vi trækker vejret med' },
    { id: 'da5-lo11', type: 'LetterOrder', question: 'Stav til "kuldioxid"', answer: 'kuldioxid', instruction: 'Det vi puster ud' },
    { id: 'da5-lo12', type: 'LetterOrder', question: 'Stav til "kvælstof"', answer: 'kvælstof', instruction: 'Den største del af luften' },
    { id: 'da5-lo13', type: 'LetterOrder', question: 'Stav til "temperatur"', answer: 'temperatur', instruction: 'Hvor varmt eller koldt det er' },
    { id: 'da5-lo14', type: 'LetterOrder', question: 'Stav til "termometer"', answer: 'termometer', instruction: 'Det man måler varme med' },
    { id: 'da5-lo15', type: 'LetterOrder', question: 'Stav til "vejrudsigt"', answer: 'vejrudsigt', instruction: 'Når de fortæller om vejret i TV' },
    { id: 'da5-lo16', type: 'LetterOrder', question: 'Stav til "oversvømmelse"', answer: 'oversvømmelse', instruction: 'Når der er for meget vand' },
    { id: 'da5-lo17', type: 'LetterOrder', question: 'Stav til "tørke"', answer: 'tørke', instruction: 'Når der mangler vand' },
    { id: 'da5-lo18', type: 'LetterOrder', question: 'Stav til "orkan"', answer: 'orkan', instruction: 'En meget stærk vind' },
    { id: 'da5-lo19', type: 'LetterOrder', question: 'Stav til "jordskælv"', answer: 'jordskælv', instruction: 'Når jorden ryster' },
    { id: 'da5-lo20', type: 'LetterOrder', question: 'Stav til "vulkan"', answer: 'vulkan', instruction: 'Et bjerg med lava' },
    { id: 'da5-lo21', type: 'LetterOrder', question: 'Stav til "kontinent"', answer: 'kontinent', instruction: 'Europa, Asien og Afrika' },
    { id: 'da5-lo22', type: 'LetterOrder', question: 'Stav til "ocean"', answer: 'ocean', instruction: 'Et meget stort hav' },
    { id: 'da5-lo23', type: 'LetterOrder', question: 'Stav til "ø"', answer: 'ø', instruction: 'Land omgivet af vand' },
    { id: 'da5-lo24', type: 'LetterOrder', question: 'Stav til "halvø"', answer: 'halvø', instruction: 'Land næsten omgivet af vand' },
    { id: 'da5-lo25', type: 'LetterOrder', question: 'Stav til "kyst"', answer: 'kyst', instruction: 'Hvor landet møder havet' },
    { id: 'da5-lo26', type: 'LetterOrder', question: 'Stav til "strand"', answer: 'strand', instruction: 'Her bader man om sommeren' },
    { id: 'da5-lo27', type: 'LetterOrder', question: 'Stav til "klit"', answer: 'klit', instruction: 'En bakke af sand' },
    { id: 'da5-lo28', type: 'LetterOrder', question: 'Stav til "hede"', answer: 'hede', instruction: 'Et fladt område med lyng' },
    { id: 'da5-lo29', type: 'LetterOrder', question: 'Stav til "mose"', answer: 'mose', instruction: 'Et vådt område med tørv' },
    { id: 'da5-lo30', type: 'LetterOrder', question: 'Stav til "eng"', answer: 'eng', instruction: 'Et grønt område ved en å' },
    { id: 'da5-lo31', type: 'LetterOrder', question: 'Stav til "å"', answer: 'å', instruction: 'Et lille vandløb' },
    { id: 'da5-lo32', type: 'LetterOrder', question: 'Stav til "flod"', answer: 'flod', instruction: 'Et stort vandløb' },
    { id: 'da5-lo33', type: 'LetterOrder', question: 'Stav til "sø"', answer: 'sø', instruction: 'Stille vand i naturen' },
    { id: 'da5-lo34', type: 'LetterOrder', question: 'Stav til "bjerg"', answer: 'bjerg', instruction: 'Himmelebjerget er ikke et rigtigt ___' },
    { id: 'da5-lo35', type: 'LetterOrder', question: 'Stav til "dal"', answer: 'dal', instruction: 'Området mellem to bjerge' },
    { id: 'da5-lo36', type: 'LetterOrder', question: 'Stav til "skov"', answer: 'skov', instruction: 'Mange træer samlet' },
    { id: 'da5-lo37', type: 'LetterOrder', question: 'Stav til "natur"', answer: 'natur', instruction: 'Alt det grønne og dyrene' },
    { id: 'da5-lo38', type: 'LetterOrder', question: 'Stav til "miljø"', answer: 'miljø', instruction: 'Vour omgivelser' },
    { id: 'da5-lo39', type: 'LetterOrder', question: 'Stav til "forurening"', answer: 'forurening', instruction: 'Når naturen bliver beskidt' },
    { id: 'da5-lo40', type: 'LetterOrder', question: 'Stav til "genbrug"', answer: 'genbrug', instruction: 'Når man bruger ting igen' },
    { id: 'da5-lo41', type: 'LetterOrder', question: 'Stav til "energi"', answer: 'energi', instruction: 'Strøm og varme' },
    { id: 'da5-lo42', type: 'LetterOrder', question: 'Stav til "elektricitet"', answer: 'elektricitet', instruction: 'Det der er i stikkontakten' },
    { id: 'da5-lo43', type: 'LetterOrder', question: 'Stav til "batteri"', answer: 'batteri', instruction: 'Det giver strøm til legetøj' },
    { id: 'da5-lo44', type: 'LetterOrder', question: 'Stav til "magnet"', answer: 'magnet', instruction: 'Den kan tiltrække jern' },
    { id: 'da5-lo45', type: 'LetterOrder', question: 'Stav til "kompas"', answer: 'kompas', instruction: 'Det viser vej mod nord' },
    { id: 'da5-lo46', type: 'LetterOrder', question: 'Stav til "kort"', answer: 'kort', instruction: 'Et billede af et land' },
    { id: 'da5-lo47', type: 'LetterOrder', question: 'Stav til "atlas"', answer: 'atlas', instruction: 'En bog med mange kort' },
    { id: 'da5-lo48', type: 'LetterOrder', question: 'Stav til "globus"', answer: 'globus', instruction: 'En rund model af jorden' },
    { id: 'da5-lo49', type: 'LetterOrder', question: 'Stav til "kikkert"', answer: 'kikkert', instruction: 'Den ser man langt med' },
    { id: 'da5-lo50', type: 'LetterOrder', question: 'Stav til "mikroskop"', answer: 'mikroskop', instruction: 'Den ser man små ting med' },
    { id: 'da5-lo51', type: 'LetterOrder', question: 'Stav til "forsøg"', answer: 'forsøg', instruction: 'Når man tester noget i naturfag' },
  ],
  6: [
    { id: 'da6-lo1', type: 'LetterOrder', question: 'Stav til "demokrati"', answer: 'demokrati', instruction: 'Når folket bestemmer' },
    { id: 'da6-lo2', type: 'LetterOrder', question: 'Stav til "parlament"', answer: 'parlament', instruction: 'Her sidder politikerne' },
    { id: 'da6-lo3', type: 'LetterOrder', question: 'Stav til "regering"', answer: 'regering', instruction: 'De der leder landet' },
    { id: 'da6-lo4', type: 'LetterOrder', question: 'Stav til "minister"', answer: 'minister', instruction: 'En politiker med et særligt område' },
    { id: 'da6-lo5', type: 'LetterOrder', question: 'Stav til "valg"', answer: 'valg', instruction: 'Når vi stemmer' },
    { id: 'da6-lo6', type: 'LetterOrder', question: 'Stav til "stemme"', answer: 'stemme', instruction: 'Det man afgiver ved et valg' },
    { id: 'da6-lo7', type: 'LetterOrder', question: 'Stav til "lov"', answer: 'lov', instruction: 'En regel i samfundet' },
    { id: 'da6-lo8', type: 'LetterOrder', question: 'Stav til "ret"', answer: 'ret', instruction: 'Her dømmer man folk' },
    { id: 'da6-lo9', type: 'LetterOrder', question: 'Stav til "domstol"', answer: 'domstol', instruction: 'Stedet hvor dommeren er' },
    { id: 'da6-lo10', type: 'LetterOrder', question: 'Stav til "politi"', answer: 'politi', instruction: 'De sørger for lov og orden' },
    { id: 'da6-lo11', type: 'LetterOrder', question: 'Stav til "fængsel"', answer: 'fængsel', instruction: 'Her kommer tyve hen' },
    { id: 'da6-lo12', type: 'LetterOrder', question: 'Stav til "frihed"', answer: 'frihed', instruction: 'At kunne gøre som man vil' },
    { id: 'da6-lo13', type: 'LetterOrder', question: 'Stav til "rettighed"', answer: 'rettighed', instruction: 'Noget man har krav på' },
    { id: 'da6-lo14', type: 'LetterOrder', question: 'Stav til "ansvar"', answer: 'ansvar', instruction: 'Når man skal stå inde for noget' },
    { id: 'da6-lo15', type: 'LetterOrder', question: 'Stav til "pligt"', answer: 'pligt', instruction: 'Noget man skal gøre' },
    { id: 'da6-lo16', type: 'LetterOrder', question: 'Stav til "skat"', answer: 'skat', instruction: 'Penge til fællesskabet' },
    { id: 'da6-lo17', type: 'LetterOrder', question: 'Stav til "velfærd"', answer: 'velfærd', instruction: 'At alle har det godt' },
    { id: 'da6-lo18', type: 'LetterOrder', question: 'Stav til "hospital"', answer: 'hospital', instruction: 'Her bliver syge raske' },
    { id: 'da6-lo19', type: 'LetterOrder', question: 'Stav til "uddannelse"', answer: 'uddannelse', instruction: 'Når man lærer et fag' },
    { id: 'da6-lo20', type: 'LetterOrder', question: 'Stav til "kollektiv"', answer: 'kollektiv', instruction: 'Når man er mange sammen' },
    { id: 'da6-lo21', type: 'LetterOrder', question: 'Stav til "individ"', answer: 'individ', instruction: 'En enkelt person' },
    { id: 'da6-lo22', type: 'LetterOrder', question: 'Stav til "kultur"', answer: 'kultur', instruction: 'Kunst, musik og traditioner' },
    { id: 'da6-lo23', type: 'LetterOrder', question: 'Stav til "tradition"', answer: 'tradition', instruction: 'Noget man gør hvert år' },
    { id: 'da6-lo24', type: 'LetterOrder', question: 'Stav til "religion"', answer: 'religion', instruction: 'Tro på Gud' },
    { id: 'da6-lo25', type: 'LetterOrder', question: 'Stav til "kirke"', answer: 'kirke', instruction: 'Her går man hen om søndagen' },
    { id: 'da6-lo26', type: 'LetterOrder', question: 'Stav til "moske"', answer: 'moske', instruction: 'Muslimernes kirke' },
    { id: 'da6-lo27', type: 'LetterOrder', question: 'Stav til "synagoge"', answer: 'synagoge', instruction: 'Jødernes kirke' },
    { id: 'da6-lo28', type: 'LetterOrder', question: 'Stav til "tro"', answer: 'tro', instruction: 'Når man tror på noget' },
    { id: 'da6-lo29', type: 'LetterOrder', question: 'Stav til "håb"', answer: 'håb', instruction: 'Når man ønsker det bedste' },
    { id: 'da6-lo30', type: 'LetterOrder', question: 'Stav til "kærlighed"', answer: 'kærlighed', instruction: 'At holde meget af nogen' },
    { id: 'da6-lo31', type: 'LetterOrder', question: 'Stav til "venskab"', answer: 'venskab', instruction: 'Relation mellem gode venner' },
    { id: 'da6-lo32', type: 'LetterOrder', question: 'Stav til "respekt"', answer: 'respekt', instruction: 'At anerkende andre' },
    { id: 'da6-lo33', type: 'LetterOrder', question: 'Stav til "tolerance"', answer: 'tolerance', instruction: 'At acceptere forskelle' },
    { id: 'da6-lo34', type: 'LetterOrder', question: 'Stav til "konflikt"', answer: 'konflikt', instruction: 'Når man er uenig' },
    { id: 'da6-lo35', type: 'LetterOrder', question: 'Stav til "løsning"', answer: 'løsning', instruction: 'Når problemet fjernes' },
    { id: 'da6-lo36', type: 'LetterOrder', question: 'Stav til "samarbejde"', answer: 'samarbejde', instruction: 'At arbejde sammen' },
    { id: 'da6-lo37', type: 'LetterOrder', question: 'Stav til "kommunikation"', answer: 'kommunikation', instruction: 'At tale eller skrive sammen' },
    { id: 'da6-lo38', type: 'LetterOrder', question: 'Stav til "sprog"', answer: 'sprog', instruction: 'Dansk, engelsk eller tysk' },
    { id: 'da6-lo39', type: 'LetterOrder', question: 'Stav til "litteratur"', answer: 'litteratur', instruction: 'Bøger og digte' },
    { id: 'da6-lo40', type: 'LetterOrder', question: 'Stav til "forfatter"', answer: 'forfatter', instruction: 'En person der skriver bøger' },
    { id: 'da6-lo41', type: 'LetterOrder', question: 'Stav til "poesi"', answer: 'poesi', instruction: 'Digte' },
    { id: 'da6-lo42', type: 'LetterOrder', question: 'Stav til "roman"', answer: 'roman', instruction: 'En lang historie i en bog' },
    { id: 'da6-lo43', type: 'LetterOrder', question: 'Stav til "novelle"', answer: 'novelle', instruction: 'En kort historie' },
    { id: 'da6-lo44', type: 'LetterOrder', question: 'Stav til "eventyr"', answer: 'eventyr', instruction: 'En historie med magi' },
    { id: 'da6-lo45', type: 'LetterOrder', question: 'Stav til "fiktion"', answer: 'fiktion', instruction: 'Noget der er fundet på' },
    { id: 'da6-lo46', type: 'LetterOrder', question: 'Stav til "virkelighed"', answer: 'virkelighed', instruction: 'Det der er sandt' },
    { id: 'da6-lo47', type: 'LetterOrder', question: 'Stav til "fantasi"', answer: 'fantasi', instruction: 'Når man finder på ting' },
    { id: 'da6-lo48', type: 'LetterOrder', question: 'Stav til "viden"', answer: 'viden', instruction: 'Noget man har lært' },
    { id: 'da6-lo49', type: 'LetterOrder', question: 'Stav til "lære"', answer: 'lære', instruction: 'At få ny viden' },
    { id: 'da6-lo50', type: 'LetterOrder', question: 'Stav til "huske"', answer: 'huske', instruction: 'At ikke glemme' },
    { id: 'da6-lo51', type: 'LetterOrder', question: 'Stav til "glemme"', answer: 'glemme', instruction: 'Når man ikke kan huske det' },
  ],
  7: [
    { id: 'da7-lo1', type: 'LetterOrder', question: 'Stav til "analyse"', answer: 'analyse', instruction: 'At undersøge noget grundigt' },
    { id: 'da7-lo2', type: 'LetterOrder', question: 'Stav til "interpretation"', answer: 'interpretation', instruction: 'At finde en betydning' },
    { id: 'da7-lo3', type: 'LetterOrder', question: 'Stav til "perspektiv"', answer: 'perspektiv', instruction: 'En måde at se tingene på' },
    { id: 'da7-lo4', type: 'LetterOrder', question: 'Stav til "kontekst"', answer: 'kontekst', instruction: 'Sammenhængen noget indgår i' },
    { id: 'da7-lo5', type: 'LetterOrder', question: 'Stav til "argumentation"', answer: 'argumentation', instruction: 'Når man begrunder sine holdninger' },
    { id: 'da7-lo6', type: 'LetterOrder', question: 'Stav til "påstand"', answer: 'påstand', instruction: 'Det man mener er rigtigt' },
    { id: 'da7-lo7', type: 'LetterOrder', question: 'Stav til "belæg"', answer: 'belæg', instruction: 'Bevis for en påstand' },
    { id: 'da7-lo8', type: 'LetterOrder', question: 'Stav til "hjemmel"', answer: 'hjemmel', instruction: 'Broen mellem påstand og belæg' },
    { id: 'da7-lo9', type: 'LetterOrder', question: 'Stav til "retorik"', answer: 'retorik', instruction: 'Læren om at tale godt' },
    { id: 'da7-lo10', type: 'LetterOrder', question: 'Stav til "etik"', answer: 'etik', instruction: 'Læren om rigtigt og forkert' },
    { id: 'da7-lo11', type: 'LetterOrder', question: 'Stav til "moral"', answer: 'moral', instruction: 'En persons regler for adfærd' },
    { id: 'da7-lo12', type: 'LetterOrder', question: 'Stav til "filosofi"', answer: 'filosofi', instruction: 'Kærlighed til visdom' },
    { id: 'da7-lo13', type: 'LetterOrder', question: 'Stav til "eksistens"', answer: 'eksistens', instruction: 'Det at være til' },
    { id: 'da7-lo14', type: 'LetterOrder', question: 'Stav til "identitet"', answer: 'identitet', instruction: 'Hvem man er' },
    { id: 'da7-lo15', type: 'LetterOrder', question: 'Stav til "samfund"', answer: 'samfund', instruction: 'Mennesker der lever sammen' },
    { id: 'da7-lo16', type: 'LetterOrder', question: 'Stav til "globalisering"', answer: 'globalisering', instruction: 'Når verden hænger sammen' },
    { id: 'da7-lo17', type: 'LetterOrder', question: 'Stav til "økonomi"', answer: 'økonomi', instruction: 'Handel med penge og varer' },
    { id: 'da7-lo18', type: 'LetterOrder', question: 'Stav til "politik"', answer: 'politik', instruction: 'Kampen om magten i samfundet' },
    { id: 'da7-lo19', type: 'LetterOrder', question: 'Stav til "ideologi"', answer: 'ideologi', instruction: 'Et sæt af politiske idéer' },
    { id: 'da7-lo20', type: 'LetterOrder', question: 'Stav til "liberalisme"', answer: 'liberalisme', instruction: 'Frihed for individet' },
    { id: 'da7-lo21', type: 'LetterOrder', question: 'Stav til "socialisme"', answer: 'socialisme', instruction: 'Lighed og fællesskab' },
    { id: 'da7-lo22', type: 'LetterOrder', question: 'Stav til "konservatisme"', answer: 'konservatisme', instruction: 'Bevaring af værdier' },
    { id: 'da7-lo23', type: 'LetterOrder', question: 'Stav til "miljø"', answer: 'miljø', instruction: 'Naturen omkring os' },
    { id: 'da7-lo24', type: 'LetterOrder', question: 'Stav til "klima"', answer: 'klima', instruction: 'Vejret over lang tid' },
    { id: 'da7-lo25', type: 'LetterOrder', question: 'Stav til "bæredygtighed"', answer: 'bæredygtighed', instruction: 'At passe på fremtiden' },
    { id: 'da7-lo26', type: 'LetterOrder', question: 'Stav til "ressource"', answer: 'ressource', instruction: 'Noget we kan bruge fra naturen' },
    { id: 'da7-lo27', type: 'LetterOrder', question: 'Stav til "forurening"', answer: 'forurening', instruction: 'Når miljøet ødelægges' },
    { id: 'da7-lo28', type: 'LetterOrder', question: 'Stav til "teknologi"', answer: 'teknologi', instruction: 'Maskiner og it' },
    { id: 'da7-lo29', type: 'LetterOrder', question: 'Stav til "innovation"', answer: 'innovation', instruction: 'Når man finder på noget nyt' },
    { id: 'da7-lo30', type: 'LetterOrder', question: 'Stav til "internet"', answer: 'internet', instruction: 'Det verdensomspændende net' },
    { id: 'da7-lo31', type: 'LetterOrder', question: 'Stav til "digitalisering"', answer: 'digitalisering', instruction: 'Når alt bliver til it' },
    { id: 'da7-lo32', type: 'LetterOrder', question: 'Stav til "medier"', answer: 'medier', instruction: 'Aviser, TV og internet' },
    { id: 'da7-lo33', type: 'LetterOrder', question: 'Stav til "journalistik"', answer: 'journalistik', instruction: 'At skrive nyheder' },
    { id: 'da7-lo34', type: 'LetterOrder', question: 'Stav til "nyhed"', answer: 'nyhed', instruction: 'Noget nyt der er sket' },
    { id: 'da7-lo35', type: 'LetterOrder', question: 'Stav til "information"', answer: 'information', instruction: 'Viden der formidles' },
    { id: 'da7-lo36', type: 'LetterOrder', question: 'Stav til "kommunikation"', answer: 'kommunikation', instruction: 'At dele budskaber' },
    { id: 'da7-lo37', type: 'LetterOrder', question: 'Stav til "modtager"', answer: 'modtager', instruction: 'Den der får budskabet' },
    { id: 'da7-lo38', type: 'LetterOrder', question: 'Stav til "afsender"', answer: 'afsender', instruction: 'Den der sender budskabet' },
    { id: 'da7-lo39', type: 'LetterOrder', question: 'Stav til "budskab"', answer: 'budskab', instruction: 'Det man vil sige' },
    { id: 'da7-lo40', type: 'LetterOrder', question: 'Stav til "genre"', answer: 'genre', instruction: 'En type tekst eller film' },
    { id: 'da7-lo41', type: 'LetterOrder', question: 'Stav til "stil"', answer: 'stil', instruction: 'Måden man udtrykker sig på' },
    { id: 'da7-lo42', type: 'LetterOrder', question: 'Stav til "sprog"', answer: 'sprog', instruction: 'Menneskets vigtigste værktøj' },
    { id: 'da7-lo43', type: 'LetterOrder', question: 'Stav til "grammatik"', answer: 'grammatik', instruction: 'Sprogets regler' },
    { id: 'da7-lo44', type: 'LetterOrder', question: 'Stav til "stavning"', answer: 'stavning', instruction: 'At sætte bogstaver rigtigt sammen' },
    { id: 'da7-lo45', type: 'LetterOrder', question: 'Stav til "tegnsætning"', answer: 'tegnsætning', instruction: 'Korrekt brug af punktum og komma' },
    { id: 'da7-lo46', type: 'LetterOrder', question: 'Stav til "punktum"', answer: 'punktum', instruction: 'Det man sætter efter en sætning' },
    { id: 'da7-lo47', type: 'LetterOrder', question: 'Stav til "komma"', answer: 'komma', instruction: 'En lille pause i sætningen' },
    { id: 'da7-lo48', type: 'LetterOrder', question: 'Stav til "udtryk"', answer: 'udtryk', instruction: 'En måde at sige noget på' },
    { id: 'da7-lo49', type: 'LetterOrder', question: 'Stav til "betydning"', answer: 'betydning', instruction: 'Det et ord står for' },
    { id: 'da7-lo50', type: 'LetterOrder', question: 'Stav til "bevidsthed"', answer: 'bevidsthed', instruction: 'Når man ved man er til' },
    { id: 'da7-lo51', type: 'LetterOrder', question: 'Stav til "indsigt"', answer: 'indsigt', instruction: 'En dyb forståelse' },
  ],
  8: [
    { id: 'da8-lo1', type: 'LetterOrder', question: 'Stav til "konsekvens"', answer: 'konsekvens', instruction: 'Følgen af en handling' },
    { id: 'da8-lo2', type: 'LetterOrder', question: 'Stav til "kompetence"', answer: 'kompetence', instruction: 'Noget man er god til' },
    { id: 'da8-lo3', type: 'LetterOrder', question: 'Stav til "kvalificeret"', answer: 'kvalificeret', instruction: 'Når man har de rette evner' },
    { id: 'da8-lo4', type: 'LetterOrder', question: 'Stav til "professionel"', answer: 'professionel', instruction: 'Når man arbejder med noget' },
    { id: 'da8-lo5', type: 'LetterOrder', question: 'Stav til "erfaring"', answer: 'erfaring', instruction: 'Viden man har fået gennem livet' },
    { id: 'da8-lo6', type: 'LetterOrder', question: 'Stav til "uddannelse"', answer: 'uddannelse', instruction: 'Vejen til et fag' },
    { id: 'da8-lo7', type: 'LetterOrder', question: 'Stav til "universitet"', answer: 'universitet', instruction: 'Hvor man studerer efter gymnasiet' },
    { id: 'da8-lo8', type: 'LetterOrder', question: 'Stav til "gymnasium"', answer: 'gymnasium', instruction: 'Hvor man går hen efter 9. klasse' },
    { id: 'da8-lo9', type: 'LetterOrder', question: 'Stav til "fremtid"', answer: 'fremtid', instruction: 'Det der ligger foran os' },
    { id: 'da8-lo10', type: 'LetterOrder', question: 'Stav til "ambition"', answer: 'ambition', instruction: 'At ville opnå noget stort' },
    { id: 'da8-lo11', type: 'LetterOrder', question: 'Stav til "motivation"', answer: 'motivation', instruction: 'Drivkraften til at gøre noget' },
    { id: 'da8-lo12', type: 'LetterOrder', question: 'Stav til "inspiration"', answer: 'inspiration', instruction: 'Når man får gode idéer fra andre' },
    { id: 'da8-lo13', type: 'LetterOrder', question: 'Stav til "kreativitet"', answer: 'kreativitet', instruction: 'Evnen til at skabe noget nyt' },
    { id: 'da8-lo14', type: 'LetterOrder', question: 'Stav til "originalitet"', answer: 'originalitet', instruction: 'At være helt sig selv' },
    { id: 'da8-lo15', type: 'LetterOrder', question: 'Stav til "autenticitet"', answer: 'autenticitet', instruction: 'At være ægte' },
    { id: 'da8-lo16', type: 'LetterOrder', question: 'Stav til "integritet"', answer: 'integritet', instruction: 'At være hel i sin personlighed' },
    { id: 'da8-lo17', type: 'LetterOrder', question: 'Stav til "solidaritet"', answer: 'solidaritet', instruction: 'At står sammen med andre' },
    { id: 'da8-lo18', type: 'LetterOrder', question: 'Stav til "demokrati"', answer: 'demokrati', instruction: 'Folkestyre' },
    { id: 'da8-lo19', type: 'LetterOrder', question: 'Stav til "republik"', answer: 'republik', instruction: 'Et land uden konge eller dronning' },
    { id: 'da8-lo20', type: 'LetterOrder', question: 'Stav til "monarki"', answer: 'monarki', instruction: 'Et land med konge eller dronning' },
    { id: 'da8-lo21', type: 'LetterOrder', question: 'Stav til "grundlov"', answer: 'grundlov', instruction: 'Danmarks vigtigste lov' },
    { id: 'da8-lo22', type: 'LetterOrder', question: 'Stav til "parlamentarisme"', answer: 'parlamentarisme', instruction: 'Når regeringen skal have flertal' },
    { id: 'da8-lo23', type: 'LetterOrder', question: 'Stav til "opposition"', answer: 'opposition', instruction: 'De partier der ikke er i regering' },
    { id: 'da8-lo24', type: 'LetterOrder', question: 'Stav til "koalition"', answer: 'koalition', instruction: 'Når partier arbejder sammen' },
    { id: 'da8-lo25', type: 'LetterOrder', question: 'Stav til "kompromis"', answer: 'kompromis', instruction: 'Når man mødes på midten' },
    { id: 'da8-lo26', type: 'LetterOrder', question: 'Stav til "konsensus"', answer: 'konsensus', instruction: 'Når alle er enige' },
    { id: 'da8-lo27', type: 'LetterOrder', question: 'Stav til "konflikt"', answer: 'konflikt', instruction: 'Uenighed' },
    { id: 'da8-lo28', type: 'LetterOrder', question: 'Stav til "diplomati"', answer: 'diplomati', instruction: 'At tale sig til rette mellem lande' },
    { id: 'da8-lo29', type: 'LetterOrder', question: 'Stav til "ambassadør"', answer: 'ambassadør', instruction: 'En udsending fra et andet land' },
    { id: 'da8-lo30', type: 'LetterOrder', question: 'Stav til "traktat"', answer: 'traktat', instruction: 'En aftale mellem lande' },
    { id: 'da8-lo31', type: 'LetterOrder', question: 'Stav til "økologi"', answer: 'økologi', instruction: 'Når man passer på naturen' },
    { id: 'da8-lo32', type: 'LetterOrder', question: 'Stav til "biodiversitet"', answer: 'biodiversitet', instruction: 'Mange forskellige dyr og planter' },
    { id: 'da8-lo33', type: 'LetterOrder', question: 'Stav til "genetik"', answer: 'genetik', instruction: 'Læren om arveanlæg' },
    { id: 'da8-lo34', type: 'LetterOrder', question: 'Stav til "evolution"', answer: 'evolution', instruction: 'Udviklingen af liv' },
    { id: 'da8-lo35', type: 'LetterOrder', question: 'Stav til "psykologi"', answer: 'psykologi', instruction: 'Læren om sindet' },
    { id: 'da8-lo36', type: 'LetterOrder', question: 'Stav til "sociologi"', answer: 'sociologi', instruction: 'Læren om samfundet' },
    { id: 'da8-lo37', type: 'LetterOrder', question: 'Stav til "antropologi"', answer: 'antropologi', instruction: 'Læren om mennesker i kulturer' },
    { id: 'da8-lo38', type: 'LetterOrder', question: 'Stav til "arkæologi"', answer: 'arkæologi', instruction: 'Læren om fortidens ting' },
    { id: 'da8-lo39', type: 'LetterOrder', question: 'Stav til "historie"', answer: 'historie', instruction: 'Fortællingen om fortiden' },
    { id: 'da8-lo40', type: 'LetterOrder', question: 'Stav til "geografi"', answer: 'geografi', instruction: 'Læren om jordens overflade' },
    { id: 'da8-lo41', type: 'LetterOrder', question: 'Stav til "matematik"', answer: 'matematik', instruction: 'Læren om tal og figurer' },
    { id: 'da8-lo42', type: 'LetterOrder', question: 'Stav til "geometri"', answer: 'geometri', instruction: 'Læren om punkter og linjer' },
    { id: 'da8-lo43', type: 'LetterOrder', question: 'Stav til "algebra"', answer: 'algebra', instruction: 'Regning med bogstaver' },
    { id: 'da8-lo44', type: 'LetterOrder', question: 'Stav til "fysik"', answer: 'fysik', instruction: 'Læren om kræfter og energi' },
    { id: 'da8-lo45', type: 'LetterOrder', question: 'Stav til "kemi"', answer: 'kemi', instruction: 'Læren om stoffer' },
    { id: 'da8-lo46', type: 'LetterOrder', question: 'Stav til "biologi"', answer: 'biologi', instruction: 'Læren om levende væsner' },
    { id: 'da8-lo47', type: 'LetterOrder', question: 'Stav til "teknologi"', answer: 'teknologi', instruction: 'Læren om maskiner' },
    { id: 'da8-lo48', type: 'LetterOrder', question: 'Stav til "filosofi"', answer: 'filosofi', instruction: 'Læren om at tænke' },
    { id: 'da8-lo49', type: 'LetterOrder', question: 'Stav til "etik"', answer: 'etik', instruction: 'Læren om moral' },
    { id: 'da8-lo50', type: 'LetterOrder', question: 'Stav til "religion"', answer: 'religion', instruction: 'Læren om tro' },
    { id: 'da8-lo51', type: 'LetterOrder', question: 'Stav til "videnskab"', answer: 'videnskab', instruction: 'Søgen efter sandheden' },
  ],
  9: [
    { id: 'da9-lo1', type: 'LetterOrder', question: 'Stav til "acceleration"', answer: 'acceleration', instruction: 'Når farten øges' },
    { id: 'da9-lo2', type: 'LetterOrder', question: 'Stav til "akkumulere"', answer: 'akkumulere', instruction: 'At samle sammen over tid' },
    { id: 'da9-lo3', type: 'LetterOrder', question: 'Stav til "ambivalent"', answer: 'ambivalent', instruction: 'At have delte følelser' },
    { id: 'da9-lo4', type: 'LetterOrder', question: 'Stav til "anarkisme"', answer: 'anarkisme', instruction: 'Samfund uden stat' },
    { id: 'da9-lo5', type: 'LetterOrder', question: 'Stav til "autonom"', answer: 'autonom', instruction: 'Selvstyrende' },
    { id: 'da9-lo6', type: 'LetterOrder', question: 'Stav til "bureaukrati"', answer: 'bureaukrati', instruction: 'Mange regler og kontorer' },
    { id: 'da9-lo7', type: 'LetterOrder', question: 'Stav til "civilisation"', answer: 'civilisation', instruction: 'Et velordnet samfund' },
    { id: 'da9-lo8', type: 'LetterOrder', question: 'Stav til "dekadence"', answer: 'dekadence', instruction: 'Forfald i moral og kultur' },
    { id: 'da9-lo9', type: 'LetterOrder', question: 'Stav til "differentiering"', answer: 'differentiering', instruction: 'Når noget bliver forskelligt' },
    { id: 'da9-lo10', type: 'LetterOrder', question: 'Stav til "diskurs"', answer: 'diskurs', instruction: 'Måden man taler om et emne' },
    { id: 'da9-lo11', type: 'LetterOrder', question: 'Stav til "eksistentiel"', answer: 'eksistentiel', instruction: 'Noget der rører ved livets kerne' },
    { id: 'da9-lo12', type: 'LetterOrder', question: 'Stav til "ekspansion"', answer: 'ekspansion', instruction: 'Udvidelse' },
    { id: 'da9-lo13', type: 'LetterOrder', question: 'Stav til "fundamentalism"', answer: 'fundamentalism', instruction: 'Bogstavelig tro' },
    { id: 'da9-lo14', type: 'LetterOrder', question: 'Stav til "globalisering"', answer: 'globalisering', instruction: 'Verdensomspændende proces' },
    { id: 'da9-lo15', type: 'LetterOrder', question: 'Stav til "hegemoni"', answer: 'hegemoni', instruction: 'At have førende magt' },
    { id: 'da9-lo16', type: 'LetterOrder', question: 'Stav til "hykleri"', answer: 'hykleri', instruction: 'At sige ét og gøre noget andet' },
    { id: 'da9-lo17', type: 'LetterOrder', question: 'Stav til "idealist"', answer: 'idealist', instruction: 'En der tror på de gode idéer' },
    { id: 'da9-lo18', type: 'LetterOrder', question: 'Stav til "implementere"', answer: 'implementere', instruction: 'At føre noget ud i livet' },
    { id: 'da9-lo19', type: 'LetterOrder', question: 'Stav til "innovation"', answer: 'innovation', instruction: 'Nytænkning' },
    { id: 'da9-lo20', type: 'LetterOrder', question: 'Stav til "integritet"', answer: 'integritet', instruction: 'Selvstændighed og ærlighed' },
    { id: 'da9-lo21', type: 'LetterOrder', question: 'Stav til "intervention"', answer: 'intervention', instruction: 'Indgriben' },
    { id: 'da9-lo22', type: 'LetterOrder', question: 'Stav til "journalist"', answer: 'journalist', instruction: 'En der skriver i avisen' },
    { id: 'da9-lo23', type: 'LetterOrder', question: 'Stav til "kapitalisme"', answer: 'kapitalisme', instruction: 'Økonomisk system med fri handel' },
    { id: 'da9-lo24', type: 'LetterOrder', question: 'Stav til "kompleksitet"', answer: 'kompleksitet', instruction: 'Når noget er meget indviklet' },
    { id: 'da9-lo25', type: 'LetterOrder', question: 'Stav til "kompromis"', answer: 'kompromis', instruction: 'En gylden middelvej' },
    { id: 'da9-lo26', type: 'LetterOrder', question: 'Stav til "konfrontation"', answer: 'konfrontation', instruction: 'Når man mødes i strid' },
    { id: 'da9-lo27', type: 'LetterOrder', question: 'Stav til "konsulent"', answer: 'konsulent', instruction: 'En rådgiver' },
    { id: 'da9-lo28', type: 'LetterOrder', question: 'Stav til "kontroversiel"', answer: 'kontroversiel', instruction: 'Noget der skaber debat' },
    { id: 'da9-lo29', type: 'LetterOrder', question: 'Stav til "legitimitet"', answer: 'legitimitet', instruction: 'Lovlighed eller berettigelse' },
    { id: 'da9-lo30', type: 'LetterOrder', question: 'Stav til "liberalisering"', answer: 'liberalisering', instruction: 'At gøre mere fri' },
    { id: 'da9-lo31', type: 'LetterOrder', question: 'Stav til "manifest"', answer: 'manifest', instruction: 'En offentlig erklæring' },
    { id: 'da9-lo32', type: 'LetterOrder', question: 'Stav til "manipulation"', answer: 'manipulation', instruction: 'At påvirke andre hemmeligt' },
    { id: 'da9-lo33', type: 'LetterOrder', question: 'Stav til "marginalisere"', answer: 'marginalisere', instruction: 'At skubbe nogen ud på sidelinjen' },
    { id: 'da9-lo34', type: 'LetterOrder', question: 'Stav til "materialisme"', answer: 'materialisme', instruction: 'At gå meget op i ting' },
    { id: 'da9-lo35', type: 'LetterOrder', question: 'Stav til "mentalitet"', answer: 'mentalitet', instruction: 'Måden man tænker på' },
    { id: 'da9-lo36', type: 'LetterOrder', question: 'Stav til "metafor"', answer: 'metafor', instruction: 'Et sprogligt billede' },
    { id: 'da9-lo37', type: 'LetterOrder', question: 'Stav til "minoritet"', answer: 'minoritet', instruction: 'En lille del af befolkningen' },
    { id: 'da9-lo38', type: 'LetterOrder', question: 'Stav til "modernisering"', answer: 'modernisering', instruction: 'At gøre noget nutidigt' },
    { id: 'da9-lo39', type: 'LetterOrder', question: 'Stav til "nationalisme"', answer: 'nationalisme', instruction: 'Stor kærlighed til fædrelandet' },
    { id: 'da9-lo40', type: 'LetterOrder', question: 'Stav til "objektivitet"', answer: 'objektivitet', instruction: 'Saglighed uden følelser' },
    { id: 'da9-lo41', type: 'LetterOrder', question: 'Stav til "optimisme"', answer: 'optimisme', instruction: 'Tro på det gode' },
    { id: 'da9-lo42', type: 'LetterOrder', question: 'Stav til "paradox"', answer: 'paradox', instruction: 'En selvmodsigelse' },
    { id: 'da9-lo43', type: 'LetterOrder', question: 'Stav til "pessimisme"', answer: 'pessimisme', instruction: 'Tro på det dårlige' },
    { id: 'da9-lo44', type: 'LetterOrder', question: 'Stav til "pluralisme"', answer: 'pluralisme', instruction: 'Mange forskellige holdninger' },
    { id: 'da9-lo45', type: 'LetterOrder', question: 'Stav til "pragmatiker"', answer: 'pragmatiker', instruction: 'En person der ser på det praktiske' },
    { id: 'da9-lo46', type: 'LetterOrder', question: 'Stav til "prioritere"', answer: 'prioritere', instruction: 'At vælge hvad der er vigtigst' },
    { id: 'da9-lo47', type: 'LetterOrder', question: 'Stav til "privatisering"', answer: 'privatisering', instruction: 'Når staten sælger til private' },
    { id: 'da9-lo48', type: 'LetterOrder', question: 'Stav til "provokation"', answer: 'provokation', instruction: 'At gøre noget for at få en reaktion' },
    { id: 'da9-lo49', type: 'LetterOrder', question: 'Stav til "ræsonnement"', answer: 'ræsonnement', instruction: 'En tankegang' },
    { id: 'da9-lo50', type: 'LetterOrder', question: 'Stav til "sekularisering"', answer: 'sekularisering', instruction: 'Adskillelse af kirke og stat' },
    { id: 'da9-lo51', type: 'LetterOrder', question: 'Stav til "subjektivitet"', answer: 'subjektivitet', instruction: 'Når man ser tingene selv' },
  ]
};
