/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const DANSK_GRAMMAR_P2: Partial<Record<Grade, GameContent[]>> = {
  5: [
    { id: 'da5-g1', type: 'Grammar', question: 'Find grundleddet i: "Hunden sover i kurven"', answer: 'Hunden', options: ['Hunden', 'sover', 'i kurven'], instruction: 'Sætningsanalyse' },
    { id: 'da5-g2', type: 'Grammar', question: 'Find udsagnsleddet i: "Pigen løber hurtigt"', answer: 'løber', options: ['Pigen', 'løber', 'hurtigt'], instruction: 'Sætningsanalyse' },
    { id: 'da5-g3', type: 'Grammar', question: 'Find genstandsleddet i: "Manden køber en bil"', answer: 'en bil', options: ['en bil', 'Manden', 'køber'], instruction: 'Sætningsanalyse' },
    { id: 'da5-g4', type: 'Grammar', question: 'Hvad er ordklassen for "hurtigt" i: "Han kører hurtigt"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Adjektiv (tillægsord)', 'Verbum (udsagnsord)'], instruction: 'Ordklasser' },
    { id: 'da5-g5', type: 'Grammar', question: 'Hvad er ordklassen for "hurtig" i: "En hurtig bil"?', answer: 'Adjektiv (tillægsord)', options: ['Adjektiv (tillægsord)', 'Adverbium (biord)', 'Substantiv (navneord)'], instruction: 'Ordklasser' },
    { id: 'da5-g6', type: 'Grammar', question: 'Hvilken tid er: "De har set filmen"?', answer: 'Førnutid', options: ['Førnutid', 'Nutid', 'Førdatid'], instruction: 'Verbaltid' },
    { id: 'da5-g7', type: 'Grammar', question: 'Hvilken tid er: "De havde set filmen"?', answer: 'Førdatid', options: ['Førdatid', 'Førnutid', 'Datid'], instruction: 'Verbaltid' },
    { id: 'da5-g8', type: 'Grammar', question: 'Hvad er forholdsordet i: "Han hoppede over hegnet"?', answer: 'over', options: ['over', 'hoppede', 'hegnet'], instruction: 'Ordklasser' },
    { id: 'da5-g9', type: 'Grammar', question: 'Hvad er bindeordet i: "Jeg kommer, hvis det regner"?', answer: 'hvis', options: ['hvis', 'regner', 'kommer'], instruction: 'Ordklasser' },
    { id: 'da5-g10', type: 'Grammar', question: 'Find navneordet i: "At flyve er sjovt"', answer: 'flyve (infinitiv som subjekt)', options: ['flyve', 'sjovt', 'er'], instruction: 'Analyse' },
    { id: 'da5-g11', type: 'Grammar', question: 'Hvad er flertal af "bog"?', answer: 'Bøger', options: ['Bøger', 'Bogger', 'Bogene'], instruction: 'Bøjning' },
    { id: 'da5-g12', type: 'Grammar', question: 'Hvad er flertal af "hånd"?', answer: 'Hænder', options: ['Hænder', 'Hånder', 'Håndene'], instruction: 'Bøjning' },
    { id: 'da5-g13', type: 'Grammar', question: 'Find fejlen: "Han er mere klogere end mig"', answer: 'mere klogere', options: ['mere klogere', 'klogere', 'mig'], instruction: 'Fejlfinding' },
    { id: 'da5-g14', type: 'Grammar', question: 'Find fejlen: "Pigen løbte hjem"', answer: 'løbte', options: ['løbte', 'løb', 'hjem'], instruction: 'Fejlfinding' },
    { id: 'da5-g15', type: 'Grammar', question: 'Hvilken tid er "vil komme"?', answer: 'Fremtid', options: ['Fremtid', 'Nutid', 'Datid'], instruction: 'Verbaltid' },
    { id: 'da5-g16', type: 'Grammar', question: 'Hvad er "os" for en ordklasse?', answer: 'Personligt stedord', options: ['Personligt stedord', 'Ejestedord', 'Navneord'], instruction: 'Ordklasser' },
    { id: 'da5-g17', type: 'Grammar', question: 'Hvad er "jeres" for en ordklasse?', answer: 'Ejestedord', options: ['Ejestedord', 'Personligt stedord', 'Tillægsord'], instruction: 'Ordklasser' },
    { id: 'da5-g18', type: 'Grammar', question: 'Hvad er "hvis" i: "Hvis det regner, bliver vi inde"?', answer: 'Bindeord', options: ['Bindeord', 'Forholdsord', 'Biord'], instruction: 'Ordklasser' },
    { id: 'da5-g19', type: 'Grammar', question: 'Find grundleddet: "At spise is er dejligt"', answer: 'At spise is', options: ['At spise is', 'er', 'dejligt'], instruction: 'Sætningsanalyse' },
    { id: 'da5-g20', type: 'Grammar', question: 'Find udsagnsleddet: "De har arbejdet hele dagen"', answer: 'har arbejdet', options: ['har arbejdet', 'De', 'hele dagen'], instruction: 'Sætningsanalyse' },
    { id: 'da5-g21', type: 'Grammar', question: 'Hvad er ordklassen for "tit"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Præposition (forholdsord)', 'Konjunktion (bindeord)'], instruction: 'Ordklasser' },
    { id: 'da5-g22', type: 'Grammar', question: 'Hvad er ordklassen for "bag"?', answer: 'Præposition (forholdsord)', options: ['Præposition (forholdsord)', 'Adverbium (biord)', 'Konjunktion (bindeord)'], instruction: 'Ordklasser' },
    { id: 'da5-g23', type: 'Grammar', question: 'Hvad er ordklassen for "men"?', answer: 'Konjunktion (bindeord)', options: ['Konjunktion (bindeord)', 'Adverbium (biord)', 'Præposition (forholdsord)'], instruction: 'Ordklasser' },
    { id: 'da5-g24', type: 'Grammar', question: 'Bøj "god" i grader:', answer: 'God, bedre, bedst', options: ['God, bedre, bedst', 'God, godere, godest', 'God, godes, bedst'], instruction: 'Gradbøjning' },
    { id: 'da5-g25', type: 'Grammar', question: 'Bøj "mange" i grader:', answer: 'Mange, flere, flest', options: ['Mange, flere, flest', 'Mange, mangere, mangest', 'Mange, mere, mest'], instruction: 'Gradbøjning' },
    { id: 'da5-g26', type: 'Grammar', question: 'Bøj "få" i grader:', answer: 'Få, færre, færrest', options: ['Få, færre, færrest', 'Få, fåre, fåest', 'Få, mindre, mindst'], instruction: 'Gradbøjning' },
    { id: 'da5-g27', type: 'Grammar', question: 'Hvordan staves "linje"?', answer: 'Linje', options: ['Linje', 'Linie', 'Linje'], instruction: 'Stavning' },
    { id: 'da5-g28', type: 'Grammar', question: 'Hvordan staves "disciplin"?', answer: 'Disciplin', options: ['Disciplin', 'Disiplin', 'Dissiplin'], instruction: 'Stavning' },
    { id: 'da5-g29', type: 'Grammar', question: 'Hvordan staves "interessant"?', answer: 'Interessant', options: ['Interessant', 'Interesant', 'Interessat'], instruction: 'Stavning' },
    { id: 'da5-g30', type: 'Grammar', question: 'Hvad betyder "synonym"?', answer: 'At ordene betyder det samme', options: ['At ordene betyder det samme', 'At ordene betyder det modsatte', 'At ordene rimer'], instruction: 'Begreber' },
    { id: 'da5-g31', type: 'Grammar', question: 'Find synonym til "hurtig":', answer: 'Stærk (i fart)', options: ['Stærk (i fart)', 'Langsom', 'Flot'], instruction: 'Synonymer' },
    { id: 'da5-g32', type: 'Grammar', question: 'Find antonym til "tung":', answer: 'Let', options: ['Let', 'Varm', 'Stor'], instruction: 'Antonymer' },
    { id: 'da5-g33', type: 'Grammar', question: 'Hvad er navneordet i: "Friheden er vigtig"?', answer: 'Friheden', options: ['Friheden', 'vigtig', 'er'], instruction: 'Ordklasser' },
    { id: 'da5-g34', type: 'Grammar', question: 'Hvad er grundleddet i: "Hvem kommer nu?"', answer: 'Hvem', options: ['Hvem', 'kommer', 'nu'], instruction: 'Sætningsanalyse' },
    { id: 'da5-g35', type: 'Grammar', question: 'Bestemt flertal af "ø"?', answer: 'Øerne', options: ['Øerne', 'Øer', 'Øen'], instruction: 'Bøjning' },
    { id: 'da5-g36', type: 'Grammar', question: 'Bestemt flertal af "tå"?', answer: 'Tæerne', options: ['Tæerne', 'Tæer', 'Tåerne'], instruction: 'Bøjning' },
    { id: 'da5-g37', type: 'Grammar', question: 'Hvad er ordklassen for "hvilken"?', answer: 'Spørgende stedord', options: ['Spørgende stedord', 'Personligt stedord', 'Ejestedord'], instruction: 'Ordklasser' },
    { id: 'da5-g38', type: 'Grammar', question: 'Hvad er ordklassen for "den"?', answer: 'Påpegende stedord', options: ['Påpegende stedord', 'Udsagnsord', 'Navneord'], instruction: 'Ordklasser' },
    { id: 'da5-g39', type: 'Grammar', question: 'Er "løbende" en lang tillægsform (præsens participium)?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Verber' },
    { id: 'da5-g40', type: 'Grammar', question: 'Er "løbet" en kort tillægsform (perfektum participium)?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Verber' },
    { id: 'da5-g41', type: 'Grammar', question: 'Find genstandsleddet: "Vi elsker kage"', answer: 'kage', options: ['kage', 'Vi', 'elsker'], instruction: 'Sætningsanalyse' },
    { id: 'da5-g42', type: 'Grammar', question: 'Hvad er "meget" i: "En meget stor hund"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Adjektiv (tillægsord)', 'Navneord'], instruction: 'Ordklasser' },
    { id: 'da5-g43', type: 'Grammar', question: 'Hvad er "vigtigt" i: "Han arbejder vigtigt"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Adjektiv (tillægsord)', 'Udsagnsord'], instruction: 'Ordklasser' },
    { id: 'da5-g44', type: 'Grammar', question: 'Hvordan staves "desværre"?', answer: 'Desværre', options: ['Desværre', 'Desvære', 'Dæsværre'], instruction: 'Stavning' },
    { id: 'da5-g45', type: 'Grammar', question: 'Hvordan staves "i går"?', answer: 'I går', options: ['I går', 'Igår', 'I-går'], instruction: 'Stavning' },
    { id: 'da5-g46', type: 'Grammar', question: 'Hvordan staves "i morgen"?', answer: 'I morgen', options: ['I morgen', 'Imorgen', 'I-morgen'], instruction: 'Stavning' },
    { id: 'da5-g47', type: 'Grammar', question: 'Find bindeordet: "Jeg er træt, fordi jeg sov sent"', answer: 'fordi', options: ['fordi', 'træt', 'sov'], instruction: 'Ordklasser' },
    { id: 'da5-g48', type: 'Grammar', question: 'Hvad er "jeg" i sætningen?', answer: 'Grundled', options: ['Grundled', 'Genstandsled', 'Hensynsled'], instruction: 'Sætningsanalyse' },
    { id: 'da5-g49', type: 'Grammar', question: 'Bøj "skarp" i køn og tal: et ___ sværd', answer: 'skarpt', options: ['skarpt', 'skarp', 'skarpe'], instruction: 'Kongruens' },
    { id: 'da5-g50', type: 'Grammar', question: 'Find navneordet i: "Svømning er sundt"', answer: 'Svømning', options: ['Svømning', 'sundt', 'er'], instruction: 'Ordklasser' },
    { id: 'da5-g51', type: 'Grammar', question: 'Det går ___ .', answer: 'fremad', options: ['fremad', 'opad', 'nedad'], instruction: 'Besked' },
  ],
  6: [
    { id: 'da6-g1', type: 'Grammar', question: 'Hvad er hensynsleddet i: "Jeg giver ham en gave"?', answer: 'ham', options: ['ham', 'gave', 'Jeg'], instruction: 'Sætningsanalyse' },
    { id: 'da6-g2', type: 'Grammar', question: 'Hvad er genstandsleddet i: "Jeg giver ham en gave"?', answer: 'en gave', options: ['en gave', 'ham', 'Jeg'], instruction: 'Sætningsanalyse' },
    { id: 'da6-g3', type: 'Grammar', question: 'Hvad er udsagnsleddet i: "Jeg giver ham en gave"?', answer: 'giver', options: ['giver', 'gave', 'ham'], instruction: 'Sætningsanalyse' },
    { id: 'da6-g4', type: 'Grammar', question: 'Hvad er grundleddet i: "Jeg giver ham en gave"?', answer: 'Jeg', options: ['Jeg', 'giver', 'gave'], instruction: 'Sætningsanalyse' },
    { id: 'da6-g5', type: 'Grammar', question: 'HVad er ordklassen for "giver"?', answer: 'Verbum (udsagnsord)', options: ['Verbum (udsagnsord)', 'Substantiv (navneord)', 'Pronomen (stedord)'], instruction: 'Ordklasser' },
    { id: 'da6-g6', type: 'Grammar', question: 'Hvad er "ham"?', answer: 'Personligt pronomen', options: ['Personligt pronomen', 'Navneord', 'Tillægsord'], instruction: 'Ordklasser' },
    { id: 'da6-g7', type: 'Grammar', question: 'Hvad er "en"?', answer: 'Ubestemt artikel (kendeord)', options: ['Ubestemt artikel (kendeord)', 'Bestemt kendeord', 'Talord'], instruction: 'Ordklasser' },
    { id: 'da6-g8', type: 'Grammar', question: 'Find bindeordet: "Vi blev inde, da det regnede"', answer: 'da', options: ['da', 'inde', 'regnede'], instruction: 'Ordklasser' },
    { id: 'da6-g9', type: 'Grammar', question: 'Find forholdsordet: "Vi satte os ved bordet"', answer: 'ved', options: ['ved', 'os', 'bordet'], instruction: 'Ordklasser' },
    { id: 'da6-g10', type: 'Grammar', question: 'Bøj "at tage" i datid:', answer: 'Tog', options: ['Tog', 'Tager', 'Taget'], instruction: 'Verber' },
    { id: 'da6-g11', type: 'Grammar', question: 'Bøj "at tage" i førnutid:', answer: 'Har taget', options: ['Har taget', 'Havde taget', 'Tager'], instruction: 'Verber' },
    { id: 'da6-g12', type: 'Grammar', question: 'Hvordan staves "selvfølgelig"?', answer: 'Selvfølgelig', options: ['Selvfølgelig', 'Selvfølgeli', 'Selvfølgellig'], instruction: 'Stavning' },
    { id: 'da6-g13', type: 'Grammar', question: 'Hvordan staves "overraskelse"?', answer: 'Overraskelse', options: ['Overraskelse', 'Overaskelse', 'Overraskelses'], instruction: 'Stavning' },
    { id: 'da6-g14', type: 'Grammar', question: 'Find fejlen i: "Huset’s tag er rødt"', answer: 'Huset’s', options: ['Huset’s', 'tag', 'rødt'], instruction: 'Fejlfinding' },
    { id: 'da6-g15', type: 'Grammar', question: 'Hedder det "hans" eller "sin" i: "Manden tog ___ hat" (sin egen)?', answer: 'sin', options: ['sin', 'hans'], instruction: 'Pronominer' },
    { id: 'da6-g16', type: 'Grammar', question: 'Hedder det "hans" eller "sin" i: "Manden tog ___ hat" (en andens)?', answer: 'hans', options: ['hans', 'sin'], instruction: 'Pronominer' },
    { id: 'da6-g17', type: 'Grammar', question: 'Hvad er ordklassen for "ikke"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Konjunktion', 'Præposition'], instruction: 'Ordklasser' },
    { id: 'da6-g18', type: 'Grammar', question: 'Hvad er ordklassen for "aldrig"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Adjektiv', 'Verbum'], instruction: 'Ordklasser' },
    { id: 'da6-g19', type: 'Grammar', question: 'Hvad er ordklassen for "ofte"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Adjektiv', 'Verbum'], instruction: 'Ordklasser' },
    { id: 'da6-g20', type: 'Grammar', question: 'Bøj "god" i grader:', answer: 'God, bedre, bedst', options: ['God, bedre, bedst', 'God, godere, godest', 'God, godt, godest'], instruction: 'Gradbøjning' },
    { id: 'da6-g21', type: 'Grammar', question: 'Bøj "ond" i grader:', answer: 'Ond, værre, værst', options: ['Ond, værre, værst', 'Ond, ondere, ondest', 'Ond, mere ond, mest ond'], instruction: 'Gradbøjning' },
    { id: 'da6-g22', type: 'Grammar', question: 'Find grundleddet: "At vinde kræver træning"', answer: 'At vinde', options: ['At vinde', 'kræver', 'træning'], instruction: 'Sætningsanalyse' },
    { id: 'da6-g23', type: 'Grammar', question: 'HVad er udsagnsleddet i: "De har lige spist"?', answer: 'har spist', options: ['har spist', 'De', 'lige'], instruction: 'Sætningsanalyse' },
    { id: 'da6-g24', type: 'Grammar', question: 'Find biordet i: "Han kører desværre galt"', answer: 'desværre', options: ['desværre', 'kører', 'galt'], instruction: 'Ordklasser' },
    { id: 'da6-g25', type: 'Grammar', question: 'Hvad er ordklassen for "min"?', answer: 'Possessivt pronomen (ejestedord)', options: ['Possessivt pronomen (ejestedord)', 'Personligt stedord', 'Relativt stedord'], instruction: 'Ordklasser' },
    { id: 'da6-g26', type: 'Grammar', question: 'Hvad er ordklassen for "hvem"?', answer: 'Interrogativt pronomen (spørgende stedord)', options: ['Interrogativt pronomen (spørgende stedord)', 'Relativt stedord', 'Navneord'], instruction: 'Ordklasser' },
    { id: 'da6-g27', type: 'Grammar', question: 'Bøj "stærk" i køn og tal: to ___ mænd', answer: 'stærke', options: ['stærke', 'stærk', 'stærkt'], instruction: 'Kongruens' },
    { id: 'da6-g28', type: 'Grammar', question: 'Bøj "stærk" i køn og tal: et ___ reb', answer: 'stærkt', options: ['stærkt', 'stærk', 'stærke'], instruction: 'Kongruens' },
    { id: 'da6-g29', type: 'Grammar', question: 'Find fejlen i: "Han hoppede over bordet og spist"', answer: 'spist', options: ['spist', 'hoppede', 'og'], instruction: 'Fejlfinding' },
    { id: 'da6-g30', type: 'Grammar', question: 'Hvordan staves "nysgerrig"?', answer: 'Nysgerrig', options: ['Nysgerrig', 'Nysgerig', 'Nyskerrig'], instruction: 'Stavning' },
    { id: 'da6-g31', type: 'Grammar', question: 'Hvordan staves "interessant"?', answer: 'Interessant', options: ['Interessant', 'Interesant', 'Interessat'], instruction: 'Stavning' },
    { id: 'da6-g32', type: 'Grammar', question: 'Hvordan staves "yderligere"?', answer: 'Yderligere', options: ['Yderligere', 'Yderlier', 'Yderligre'], instruction: 'Stavning' },
    { id: 'da6-g33', type: 'Grammar', question: 'Find bindeordet: "Hverken jeg eller du kommer"', answer: 'hverken...eller', options: ['hverken...eller', 'jeg', 'du'], instruction: 'Ordklasser' },
    { id: 'da6-g34', type: 'Grammar', question: 'Find forholdsordet: "Han løb rundt om huset"', answer: 'rundt om', options: ['rundt om', 'løb', 'huset'], instruction: 'Ordklasser' },
    { id: 'da6-g35', type: 'Grammar', question: 'Er "hvilken" et stedord?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Ordklasser' },
    { id: 'da6-g36', type: 'Grammar', question: 'Hvad er tid: "De havde lige været der"?', answer: 'Førdatid', options: ['Førdatid', 'Førnutid', 'Datid'], instruction: 'Verbaltid' },
    { id: 'da6-g37', type: 'Grammar', question: 'Hvad er tid: "De vil være der i morgen"?', answer: 'Fremtid', options: ['Fremtid', 'Nutid', 'Datid'], instruction: 'Verbaltid' },
    { id: 'da6-g38', type: 'Grammar', question: 'Find sammensat ord: "fod" + "bold" + "bane" = ?', answer: 'Fodboldbane', options: ['Fodboldbane', 'Fodbold bane', 'Fodbold-bane'], instruction: 'Morfologi' },
    { id: 'da6-g39', type: 'Grammar', question: 'Hvad er "faktisk" i: "Han er faktisk sød"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Adjektiv', 'Konjunktion'], instruction: 'Ordklasser' },
    { id: 'da6-g40', type: 'Grammar', question: 'Find navneordet i: "Løben gav ham motion"', answer: 'Løben (substantiveret verbum)', options: ['Løben', 'motion', 'ham'], instruction: 'Analyse' },
    { id: 'da6-g41', type: 'Grammar', question: 'Find hensynsleddet: "Giv mig bolden"', answer: 'mig', options: ['mig', 'bolden', 'Giv'], instruction: 'Sætningsanalyse' },
    { id: 'da6-g42', type: 'Grammar', question: 'Find genstandsleddet: "Giv mig bolden"', answer: 'bolden', options: ['bolden', 'mig', 'Giv'], instruction: 'Sætningsanalyse' },
    { id: 'da6-g43', type: 'Grammar', question: 'Bøj "gammel" i grader:', answer: 'Gammel, ældre, ældst', options: ['Gammel, ældre, ældst', 'Gammel, gamlere, gamlest', 'Gammel, mere gammel, mest gammel'], instruction: 'Gradbøjning' },
    { id: 'da6-g44', type: 'Grammar', question: 'Bøj "ung" i grader:', answer: 'Ung, yngre, yngst', options: ['Ung, yngre, yngst', 'Ung, ungere, ungest', 'Ung, mere ung, mest ung'], instruction: 'Gradbøjning' },
    { id: 'da6-g45', type: 'Grammar', question: 'Hvad er "at" i: "Vi håber at komme"?', answer: 'Navnemærke', options: ['Navnemærke', 'Forholdsord', 'Udsagnsord'], instruction: 'Ordklasser' },
    { id: 'da6-g46', type: 'Grammar', question: 'Find fortrydelsesord (interjektion):', answer: 'Øv', options: ['Øv', 'Hej', 'Gå'], instruction: 'Ordklasser' },
    { id: 'da6-g47', type: 'Grammar', question: 'Find udråbsord (interjektion):', answer: 'Av', options: ['Av', 'Bil', 'Hund'], instruction: 'Ordklasser' },
    { id: 'da6-g48', type: 'Grammar', question: 'Hvad kaldes det, når to ord bliver til ét?', answer: 'En sammensætning', options: ['En sammensætning', 'En deling', 'En bøjning'], instruction: 'Begreber' },
    { id: 'da6-g49', type: 'Grammar', question: 'Find fejlen: "Tre store bilerne"', answer: 'bilerne', options: ['bilerne', 'Tre', 'store'], instruction: 'Fejlfinding' },
    { id: 'da6-g50', type: 'Grammar', question: 'Find fejlen: "Han er bedst til dansk end mig"', answer: 'bedst', options: ['bedst', 'dansk', 'mig'], instruction: 'Fejlfinding' },
    { id: 'da6-g51', type: 'Grammar', question: 'Du er på ___ vej.', answer: 'rette', options: ['rette', 'gale', 'blå'], instruction: 'Besked' },
  ],
  7: [
    { id: 'da7-g1', type: 'Grammar', question: 'Hvad er bøjningen af "at bære" i datid?', answer: 'Bar', options: ['Bar', 'Bærede', 'Båret'], instruction: 'Uregelmæssige verber' },
    { id: 'da7-g2', type: 'Grammar', question: 'Hvad er bøjningen af "at bære" i førnutid?', answer: 'Har båret', options: ['Har båret', 'Bar', 'Bærer'], instruction: 'Uregelmæssige verber' },
    { id: 'da7-g3', type: 'Grammar', question: 'Hvad er bøjningen af "at bede" i datid?', answer: 'Bad', options: ['Bad', 'Bedte', 'Bedt'], instruction: 'Uregelmæssige verber' },
    { id: 'da7-g4', type: 'Grammar', question: 'Find omsagnsled til grundled (subjektsprædikat) i: "Han er læreren"', answer: 'læreren', options: ['læreren', 'Han', 'er'], instruction: 'Sætningsanalyse' },
    { id: 'da7-g5', type: 'Grammar', question: 'Find omsagnsled til grundled i: "Pigen blev glad"', answer: 'glad', options: ['glad', 'Pigen', 'blev'], instruction: 'Sætningsanalyse' },
    { id: 'da7-g6', type: 'Grammar', question: 'Hvad er ordklassen for "glad" i: "Pigen blev glad"?', answer: 'Adjektiv', options: ['Adjektiv', 'Adverbium', 'Substantiv'], instruction: 'Ordklasser' },
    { id: 'da7-g7', type: 'Grammar', question: 'Find biordet i: "Han sang virkelig smukt"', answer: 'virkelig, smukt', options: ['virkelig, smukt', 'sang', 'Han'], instruction: 'Ordklasser' },
    { id: 'da7-g8', type: 'Grammar', question: 'Understreg grundleddet: "De store huse på vejen skal rives ned"', answer: 'De store huse på vejen', options: ['De store huse på vejen', 'skal rives ned', 'huse'], instruction: 'Sætningsanalyse' },
    { id: 'da7-g9', type: 'Grammar', question: 'Understreg udsagnsleddet: "De store huse på vejen skal rives ned"', answer: 'skal rives ned', options: ['skal rives ned', 'De store huse', 'på vejen'], instruction: 'Sætningsanalyse' },
    { id: 'da7-g10', type: 'Grammar', question: 'Find bindeordet i: "Selvom det var koldt, gik vi en tur"', answer: 'selvom', options: ['selvom', 'koldt', 'gik'], instruction: 'Ordklasser' },
    { id: 'da7-g11', type: 'Grammar', question: 'Find forholdsordet i: "Vi løb imod stien"', answer: 'imod', options: ['imod', 'løb', 'stien'], instruction: 'Ordklasser' },
    { id: 'da7-g12', type: 'Grammar', question: 'Hvad kaldes "sin" i: "Han tog sin hat"?', answer: 'Refleksivt possessivt pronomen', options: ['Refleksivt possessivt pronomen', 'Personligt pronomen', 'Relativt pronomen'], instruction: 'Ordklasser' },
    { id: 'da7-g13', type: 'Grammar', question: 'Hvad kaldes "hans" i: "Pigen tog hans hat"?', answer: 'Possessivt pronomen', options: ['Possessivt pronomen', 'Refleksivt pronomen', 'Demonstrativt pronomen'], instruction: 'Ordklasser' },
    { id: 'da7-g14', type: 'Grammar', question: 'Bøj "små" i grader:', answer: 'Små, færre, færrest (som mængde)', options: ['Små, færre, færrest', 'Små, mindre, mindst', 'Små, småere, småest'], instruction: 'Gradbøjning (Mængde)' },
    { id: 'da7-g15', type: 'Grammar', question: 'Bøj "lille" i grader:', answer: 'Lille, mindre, mindst', options: ['Lille, mindre, mindst', 'Lille, små, mindst', 'Lille, lillere, lillest'], instruction: 'Gradbøjning' },
    { id: 'da7-g16', type: 'Grammar', question: 'Hvordan staves "identitet"?', answer: 'Identitet', options: ['Identitet', 'Indentitet', 'Idenditet'], instruction: 'Stavning' },
    { id: 'da7-g17', type: 'Grammar', question: 'Hvordan staves "kvalitet"?', answer: 'Kvalitet', options: ['Kvalitet', 'Kvallitet', 'Kvalitæt'], instruction: 'Stavning' },
    { id: 'da7-g18', type: 'Grammar', question: 'Find fejlen: "Jeg har læste bogen"', answer: 'læste', options: ['læste', 'læst', 'Jeg'], instruction: 'Fejlfinding' },
    { id: 'da7-g19', type: 'Grammar', question: 'Find fejlen: "Bilernes hjul rulle"', answer: 'rulle', options: ['rulle', 'ruller', 'hjul'], instruction: 'Fejlfinding' },
    { id: 'da7-g20', type: 'Grammar', question: 'Hvad er ordklassen for "der" i: "Manden, der kom ind"?', answer: 'Relativt pronomen (henvisende stedord)', options: ['Relativt pronomen (henvisende stedord)', 'Adverbium', 'Substantiv'], instruction: 'Ordklasser' },
    { id: 'da7-g21', type: 'Grammar', question: 'Hvad er ordklassen for "som" i: "Huset, som vi så"?', answer: 'Relativt pronomen (henvisende stedord)', options: ['Relativt pronomen (henvisende stedord)', 'Konjunktion', 'Præposition'], instruction: 'Ordklasser' },
    { id: 'da7-g22', type: 'Grammar', question: 'Hvilken tid er: "De ville have gjort det"?', answer: 'Førfremtid (hypotetisk)', options: ['Førfremtid', 'Datid', 'Nutid'], instruction: 'Verbaltid' },
    { id: 'da7-g23', type: 'Grammar', question: 'Hvad er "passiv" i: "Bogen læses"?', answer: 'Verbet står i passiv', options: ['Verbet står i passiv', 'Verbet står i aktiv', 'Verbet er et navneord'], instruction: 'Diatese' },
    { id: 'da7-g24', type: 'Grammar', question: 'Find genstandsleddet: "Vi drak en liter mælk"', answer: 'en liter mælk', options: ['en liter mælk', 'Vi', 'drak'], instruction: 'Sætningsanalyse' },
    { id: 'da7-g25', type: 'Grammar', question: 'Find hensynsleddet: "Manden gav barnet en is"', answer: 'barnet', options: ['barnet', 'en is', 'Manden'], instruction: 'Sætningsanalyse' },
    { id: 'da7-g26', type: 'Grammar', question: 'Hvad er udsagnsleddet: "De har lige været ude"?', answer: 'har været', options: ['har været', 'De', 'ude'], instruction: 'Sætningsanalyse' },
    { id: 'da7-g27', type: 'Grammar', question: 'Hvad er ordklassen for "ude"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Præposition', 'Adjektiv'], instruction: 'Ordklasser' },
    { id: 'da7-g28', type: 'Grammar', question: 'Hvad kaldes "og" i en sætning?', answer: 'Sideordnende konjunktion', options: ['Sideordnende konjunktion', 'Underordnende konjunktion', 'Adverbium'], instruction: 'Ordklasser' },
    { id: 'da7-g29', type: 'Grammar', question: 'Hvad kaldes "at" i en sætning?', answer: 'Underordnende konjunktion (eller navnemærke)', options: ['Underordnende konjunktion', 'Sideordnende konjunktion', 'Adjektiv'], instruction: 'Ordklasser' },
    { id: 'da7-g30', type: 'Grammar', question: 'Hvordan staves "anerkendelse"?', answer: 'Anerkendelse', options: ['Anerkendelse', 'Annerkendelse', 'Anerkenelse'], instruction: 'Stavning' },
    { id: 'da7-g31', type: 'Grammar', question: 'Hvordan staves "efterretning"?', answer: 'Efterretning', options: ['Efterretning', 'Efteretning', 'Efterettning'], instruction: 'Stavning' },
    { id: 'da7-g32', type: 'Grammar', question: 'Find fejlen: "To røde biler kører hurtigt"', answer: 'Ingen fejl', options: ['Ingen fejl', 'røde', 'hurtigt'], instruction: 'Fejlfinding' },
    { id: 'da7-g33', type: 'Grammar', question: 'Find fejlen: "Hun er den dygtigst pige"', answer: 'dygtigst', options: ['dygtigst', 'den', 'pige'], instruction: 'Fejlfinding' },
    { id: 'da7-g34', type: 'Grammar', question: 'Bøj "meget" i grader:', answer: 'Meget, mere, mest', options: ['Meget, mere, mest', 'Meget, merere, merest', 'Meget, flere, flest'], instruction: 'Gradbøjning' },
    { id: 'da7-g35', type: 'Grammar', question: 'Hvornår bruger man "sin" versus "hans"?', answer: 'Sin viser tilbage til grundleddet i samme sætning', options: ['Sin viser tilbage til grundleddet', 'Hans viser tilbage til grundleddet', 'Der er ingen forskel'], instruction: 'Pronominer' },
    { id: 'da7-g36', type: 'Grammar', question: 'Hvad er ordklassen for "denne"?', answer: 'Demonstrativt pronomen', options: ['Demonstrativt pronomen', 'Personligt pronomen', 'Relativt pronomen'], instruction: 'Ordklasser' },
    { id: 'da7-g37', type: 'Grammar', question: 'Hvad er ordklassen for "hinanden"?', answer: 'Reciprokt pronomen', options: ['Reciprokt pronomen', 'Personligt pronomen', 'Refleksivt pronomen'], instruction: 'Ordklasser' },
    { id: 'da7-g38', type: 'Grammar', question: 'Find omsagnsled til grundled: "Han kaldes for mesteren"', answer: 'mesteren', options: ['mesteren', 'Han', 'for'], instruction: 'Sætningsanalyse' },
    { id: 'da7-g39', type: 'Grammar', question: 'Er "løb" både navneord og udsagnsord?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Betydning' },
    { id: 'da7-g40', type: 'Grammar', question: 'Er "leg" både navneord og udsagnsord?', answer: 'Nej (legen/lege)', options: ['Nej', 'Ja'], instruction: 'Betydning' },
    { id: 'da7-g41', type: 'Grammar', question: 'Hvad kaldes bøjning af navneord?', answer: 'Deklination', options: ['Deklination', 'Konjugation', 'Komparation'], instruction: 'Begreber' },
    { id: 'da7-g42', type: 'Grammar', question: 'Hvad kaldes bøjning af udsagnsord?', answer: 'Konjugation', options: ['Konjugation', 'Deklination', 'Komparation'], instruction: 'Begreber' },
    { id: 'da7-g43', type: 'Grammar', question: 'Hvad kaldes bøjning af tillægsord?', answer: 'Komparation', options: ['Komparation', 'Konjugation', 'Deklination'], instruction: 'Begreber' },
    { id: 'da7-g44', type: 'Grammar', question: 'Hvordan staves "parallelt"?', answer: 'Parallelt', options: ['Parallelt', 'Paralelt', 'Parallellt'], instruction: 'Stavning' },
    { id: 'da7-g45', type: 'Grammar', question: 'Hvordan staves "kontinuerligt"?', answer: 'Kontinuerligt', options: ['Kontinuerligt', 'Kontinuert', 'Kontinuerlig'], instruction: 'Stavning' },
    { id: 'da7-g46', type: 'Grammar', question: 'Find grundleddet: "At tale er sølv, men at tie er guld"', answer: 'At tale, at tie', options: ['At tale, at tie', 'sølv, guld', 'at'], instruction: 'Sætningsanalyse' },
    { id: 'da7-g47', type: 'Grammar', question: 'Find bindeordet i: "Manden, som vi så, er væk"', answer: 'som', options: ['som', 'Manden', 'væk'], instruction: 'Ordklasser' },
    { id: 'da7-g48', type: 'Grammar', question: 'Hvad er "væk"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Adjektiv', 'Preposition'], instruction: 'Ordklasser' },
    { id: 'da7-g49', type: 'Grammar', question: 'Hvilken tid er "jeg spiser"?', answer: 'Nutid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Verbaltid' },
    { id: 'da7-g50', type: 'Grammar', question: 'Hvilken tid er "jeg spiste"?', answer: 'Datid', options: ['Datid', 'Nutid', 'Fremtid'], instruction: 'Verbaltid' },
    { id: 'da7-g51', type: 'Grammar', question: 'Bliv ___ .', answer: 'ved', options: ['ved', 'op', 'ned'], instruction: 'Besked' },
  ],
};
