/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const DANSK_GRAMMAR_P1: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'da0-g1', type: 'Grammar', question: 'Hvilket ord er en ting?', answer: 'Bold', options: ['Bold', 'Løbe', 'Glad'], instruction: 'Ordforståelse' },
    { id: 'da0-g2', type: 'Grammar', question: 'Hvilket ord er en farve?', answer: 'Rød', options: ['Rød', 'Hund', 'Sove'], instruction: 'Ordforståelse' },
    { id: 'da0-g3', type: 'Grammar', question: 'Hvilket ord er noget man gør?', answer: 'Hoppe', options: ['Hoppe', 'Stol', 'Grøn'], instruction: 'Ordforståelse' },
    { id: 'da0-g4', type: 'Grammar', question: 'Hvilket ord rimer på kat?', answer: 'Hat', options: ['Hat', 'Hund', 'Mus'], instruction: 'Rim' },
    { id: 'da0-g5', type: 'Grammar', question: 'Hvilket ord rimer på mus?', answer: 'Hus', options: ['Hus', 'Ost', 'Kat'], instruction: 'Rim' },
    { id: 'da0-g6', type: 'Grammar', question: 'Hvilket ord rimer på bi?', answer: 'Si', options: ['Si', 'Honning', 'Blomst'], instruction: 'Rim' },
    { id: 'da0-g7', type: 'Grammar', question: 'Hvilket ord starter med S?', answer: 'Sol', options: ['Sol', 'Måne', 'Sky'], instruction: 'Bogstaver' },
    { id: 'da0-g8', type: 'Grammar', question: 'Hvilket ord starter med B?', answer: 'Bil', options: ['Bil', 'Cykel', 'Bus'], instruction: 'Bogstaver' },
    { id: 'da0-g9', type: 'Grammar', question: 'Find det lange ord:', answer: 'Elefant', options: ['Elefant', 'Is', 'Bil'], instruction: 'Ordforståelse' },
    { id: 'da0-g10', type: 'Grammar', question: 'Hvor mange stavelser er der i "sol"?', answer: '1', options: ['1', '2', '3'], instruction: 'Stavelser' },
    { id: 'da0-g11', type: 'Grammar', question: 'Hvor many stavelser er der i "æble"?', answer: '2', options: ['2', '1', '3'], instruction: 'Stavelser' },
    { id: 'da0-g12', type: 'Grammar', question: 'Hvor mange stavelser er der i "banan"?', answer: '2', options: ['2', '3', '1'], instruction: 'Stavelser' },
    { id: 'da0-g13', type: 'Grammar', question: 'Find ordet der er "farligt":', answer: 'Løve', options: ['Løve', 'Lam', 'Kanin'], instruction: 'Ordforståelse' },
    { id: 'da0-g14', type: 'Grammar', question: 'Hvad er det modsatte af stor?', answer: 'Lille', options: ['Lille', 'Høj', 'Blå'], instruction: 'Antonymer' },
    { id: 'da0-g15', type: 'Grammar', question: 'Hvad er det modsatte af glad?', answer: 'Sur', options: ['Sur', 'Sød', 'Sjov'], instruction: 'Antonymer' },
    { id: 'da0-g16', type: 'Grammar', question: 'Hvad er det modsatte af dag?', answer: 'Nat', options: ['Nat', 'Sol', 'Morgen'], instruction: 'Antonymer' },
    { id: 'da0-g17', type: 'Grammar', question: 'Find bogstavet A:', answer: 'A', options: ['A', 'E', 'O'], instruction: 'Bogstaver' },
    { id: 'da0-g18', type: 'Grammar', question: 'Find bogstavet M:', answer: 'M', options: ['M', 'N', 'W'], instruction: 'Bogstaver' },
    { id: 'da0-g19', type: 'Grammar', question: 'Find et ord med O:', answer: 'Ost', options: ['Ost', 'Is', 'And'], instruction: 'Bogstaver' },
    { id: 'da0-g20', type: 'Grammar', question: 'Hvad siger koen?', answer: 'Muuh', options: ['Muuh', 'Mjav', 'Vov'], instruction: 'Lyde' },
    { id: 'da0-g21', type: 'Grammar', question: 'Hvad siger katten?', answer: 'Mjav', options: ['Mjav', 'Vov', 'Muuh'], instruction: 'Lyde' },
    { id: 'da0-g22', type: 'Grammar', question: 'Hvad siger hunden?', answer: 'Vov', options: ['Vov', 'Gok', 'Pip'], instruction: 'Lyde' },
    { id: 'da0-g23', type: 'Grammar', question: 'Hvilken farve har en banan?', answer: 'Gul', options: ['Gul', 'Rød', 'Blå'], instruction: 'Ordforståelse' },
    { id: 'da0-g24', type: 'Grammar', question: 'Hvilken farve har en agurk?', answer: 'Grøn', options: ['Grøn', 'Lilla', 'Orange'], instruction: 'Ordforståelse' },
    { id: 'da0-g25', type: 'Grammar', question: 'Find et dyr med fire ben:', answer: 'Hest', options: ['Hest', 'Fugl', 'Slange'], instruction: 'Ordforståelse' },
    { id: 'da0-g26', type: 'Grammar', question: 'Find et dyr der kan flyve:', answer: 'Fugl', options: ['Fugl', 'Fisk', 'Hund'], instruction: 'Ordforståelse' },
    { id: 'da0-g27', type: 'Grammar', question: 'Hvilket bogstav starter "is" med?', answer: 'i', options: ['i', 'e', 'a'], instruction: 'Bogstaver' },
    { id: 'da0-g28', type: 'Grammar', question: 'Hvilket bogstav starter "abe" med?', answer: 'a', options: ['a', 'o', 'u'], instruction: 'Bogstaver' },
    { id: 'da0-g29', type: 'Grammar', question: 'Hvilket bogstav starter "tog" med?', answer: 't', options: ['t', 'd', 'p'], instruction: 'Bogstaver' },
    { id: 'da0-g30', type: 'Grammar', question: 'Find det lille bogstav b:', answer: 'b', options: ['b', 'd', 'p'], instruction: 'Bogstaver' },
    { id: 'da0-g31', type: 'Grammar', question: 'Find det lille bogstav p:', answer: 'p', options: ['p', 'q', 'g'], instruction: 'Bogstaver' },
    { id: 'da0-g32', type: 'Grammar', question: 'Hvad er det første bogstav i alfabetet?', answer: 'A', options: ['A', 'B', 'C'], instruction: 'Bogstaver' },
    { id: 'da0-g33', type: 'Grammar', question: 'Hvad er det sidste bogstav i alfabetet?', answer: 'Å', options: ['Å', 'Z', 'Æ'], instruction: 'Bogstaver' },
    { id: 'da0-g34', type: 'Grammar', question: 'Er "en" eller "et" bil?', answer: 'En', options: ['En', 'Et'], instruction: 'Kendeord' },
    { id: 'da0-g35', type: 'Grammar', question: 'Er "en" eller "et" barn?', answer: 'Et', options: ['Et', 'En'], instruction: 'Kendeord' },
    { id: 'da0-g36', type: 'Grammar', question: 'Er "en" eller "et" hus?', answer: 'Et', options: ['Et', 'En'], instruction: 'Kendeord' },
    { id: 'da0-g37', type: 'Grammar', question: 'Er "en" eller "et" sol?', answer: 'En', options: ['En', 'Et'], instruction: 'Kendeord' },
    { id: 'da0-g38', type: 'Grammar', question: 'Hvor mange ben har en hund?', answer: '4', options: ['4', '2', '0'], instruction: 'Ordforståelse' },
    { id: 'da0-g39', type: 'Grammar', question: 'Hvilket ord er kort?', answer: 'Ø', options: ['Ø', 'Vandmelon', 'Appelsin'], instruction: 'Ordforståelse' },
    { id: 'da0-g40', type: 'Grammar', question: 'Hvad spiser en kanin?', answer: 'Gulerod', options: ['Gulerod', 'Kød', 'Is'], instruction: 'Ordforståelse' },
    { id: 'da0-g41', type: 'Grammar', question: 'Find ordet med flest bogstaver:', answer: 'Sommerfugl', options: ['Sommerfugl', 'Bi', 'Kat'], instruction: 'Ordforståelse' },
    { id: 'da0-g42', type: 'Grammar', question: 'Hvad er varmt?', answer: 'Bål', options: ['Bål', 'Is', 'Sne'], instruction: 'Ordforståelse' },
    { id: 'da0-g43', type: 'Grammar', question: 'Hvad er koldt?', answer: 'Sne', options: ['Sne', 'Sol', 'Suppe'], instruction: 'Ordforståelse' },
    { id: 'da0-g44', type: 'Grammar', question: 'Find vokalen:', answer: 'a', options: ['a', 'b', 'c'], instruction: 'Vokaler' },
    { id: 'da0-g45', type: 'Grammar', question: 'Find konsonanten:', answer: 'k', options: ['k', 'e', 'u'], instruction: 'Konsonanter' },
    { id: 'da0-g46', type: 'Grammar', question: 'Hvad siger uret?', answer: 'Tik tak', options: ['Tik tak', 'Brum', 'Plask'], instruction: 'Lyde' },
    { id: 'da0-g47', type: 'Grammar', question: 'Find det glade ord:', answer: 'Grine', options: ['Grine', 'Græde', 'Slå'], instruction: 'Ordforståelse' },
    { id: 'da0-g48', type: 'Grammar', question: 'Hvor bor en fisk?', answer: 'Vand', options: ['Vand', 'Land', 'Luft'], instruction: 'Ordforståelse' },
    { id: 'da0-g49', type: 'Grammar', question: 'Find vinter ordet:', answer: 'Snefrit', options: ['Snefrit', 'Solcreme', 'Sandaler'], instruction: 'Ordforståelse' },
    { id: 'da0-g50', type: 'Grammar', question: 'Find sommer ordet:', answer: 'Solskin', options: ['Solskin', 'Vanter', 'Halstørklæde'], instruction: 'Ordforståelse' },
    { id: 'da0-g51', type: 'Grammar', question: 'Godt ___.', answer: 'gået', options: ['gået', 'spist', 'sovet'], instruction: 'Besked' },
  ],
  1: [
    { id: 'da1-g1', type: 'Grammar', question: 'Hvilket ord er et navneord (substantiv)?', answer: 'Hus', options: ['Hus', 'Løbe', 'Blå'], instruction: 'Ordklasser' },
    { id: 'da1-g2', type: 'Grammar', question: 'Hvilket ord er et udsagnsord (verbum)?', answer: 'Spise', options: ['Spise', 'Kop', 'Rød'], instruction: 'Ordklasser' },
    { id: 'da1-g3', type: 'Grammar', question: 'Hvilket ord er et tillægsord (adjektiv)?', answer: 'Sød', options: ['Sød', 'Mand', 'Gå'], instruction: 'Ordklasser' },
    { id: 'da1-g4', type: 'Grammar', question: 'Hedder det "en" eller "et" stol?', answer: 'En', options: ['En', 'Et'], instruction: 'Kendeord' },
    { id: 'da1-g5', type: 'Grammar', question: 'Hedder det "en" eller "et" bord?', answer: 'Et', options: ['Et', 'En'], instruction: 'Kendeord' },
    { id: 'da1-g6', type: 'Grammar', question: 'Find flertalsformen af "hund":', answer: 'Hunde', options: ['Hunde', 'Hunden', 'Hundene'], instruction: 'Bøjning' },
    { id: 'da1-g7', type: 'Grammar', question: 'Find flertalsformen af "kat":', answer: 'Katte', options: ['Katte', 'Katten', 'Kattene'], instruction: 'Bøjning' },
    { id: 'da1-g8', type: 'Grammar', question: 'Hvilket bogstav mangler i _ol?', answer: 'S', options: ['S', 'B', 'M'], instruction: 'Stavning' },
    { id: 'da1-g9', type: 'Grammar', question: 'Hvilket bogstav mangler i ba_ane?', answer: 'n', options: ['n', 'm', 'l'], instruction: 'Stavning' },
    { id: 'da1-g10', type: 'Grammar', question: 'Hvilket ord starter med en vokal?', answer: 'Æble', options: ['Æble', 'Pære', 'Banan'], instruction: 'Vokaler' },
    { id: 'da1-g11', type: 'Grammar', question: 'Hvilket ord starter med en konsonant?', answer: 'Bil', options: ['Bil', 'Is', 'Ø'], instruction: 'Konsonanter' },
    { id: 'da1-g12', type: 'Grammar', question: 'Bøj "at hoppe" i nutid:', answer: 'Hopper', options: ['Hopper', 'Hoppede', 'Hoppet'], instruction: 'Verber' },
    { id: 'da1-g13', type: 'Grammar', question: 'Bøj "at løbe" i nutid:', answer: 'Løber', options: ['Løber', 'Løb', 'Løbet'], instruction: 'Verber' },
    { id: 'da1-g14', type: 'Grammar', question: 'Find navneordet i: "Pigen leger"', answer: 'Pigen', options: ['Pigen', 'leger'], instruction: 'Ordklasser' },
    { id: 'da1-g15', type: 'Grammar', question: 'Find udsagnsordet i: "Drengen spiser"', answer: 'spiser', options: ['Drengen', 'spiser'], instruction: 'Ordklasser' },
    { id: 'da1-g16', type: 'Grammar', question: 'Hvilket ord er et navn?', answer: 'Peter', options: ['Peter', 'Dreng', 'Løbe'], instruction: 'Egennavne' },
    { id: 'da1-g17', type: 'Grammar', question: 'Skal navne altid med stort?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Stort bogstav' },
    { id: 'da1-g18', type: 'Grammar', question: 'Starter en sætning med stort?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Stort bogstav' },
    { id: 'da1-g19', type: 'Grammar', question: 'Slutter en sætning med et punktum?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Tegnsætning' },
    { id: 'da1-g20', type: 'Grammar', question: 'Hvornår bruger man spørgsmålstegn?', answer: 'Ved spørgsmål', options: ['Ved spørgsmål', 'Ved svar', 'Ved råb'], instruction: 'Tegnsætning' },
    { id: 'da1-g21', type: 'Grammar', question: 'Hvilket ord rimer på "sø"?', answer: 'Ø', options: ['Ø', 'Hav', 'Å'], instruction: 'Rim' },
    { id: 'da1-g22', type: 'Grammar', question: 'Find sammensat ord: "fod" + "bold" = ?', answer: 'Fodbold', options: ['Fodbold', 'Fod bold', 'Fod-bold'], instruction: 'Sammensatte ord' },
    { id: 'da1-g23', type: 'Grammar', question: 'Find sammensat ord: "is" + "bil" = ?', answer: 'Isbil', options: ['Isbil', 'Is bil', 'I-sbil'], instruction: 'Sammensatte ord' },
    { id: 'da1-g24', type: 'Grammar', question: 'Find sammensat ord: "skole" + "taske" = ?', answer: 'Skoletaske', options: ['Skoletaske', 'Skole taske', 'Skoletasken'], instruction: 'Sammensatte ord' },
    { id: 'da1-g25', type: 'Grammar', question: 'Hvad er det modsatte af kold?', answer: 'Varm', options: ['Varm', 'Is', 'Sne'], instruction: 'Antonymer' },
    { id: 'da1-g26', type: 'Grammar', question: 'Hvad er det modsatte af ung?', answer: 'Gammel', options: ['Gammel', 'Barn', 'Ny'], instruction: 'Antonymer' },
    { id: 'da1-g27', type: 'Grammar', question: 'Find ordet der betyder det samme som "glad":', answer: 'Lykkelig', options: ['Lykkelig', 'Sur', 'Træt'], instruction: 'Synonymer' },
    { id: 'da1-g28', type: 'Grammar', question: 'Find ordet der betyder det samme som "sur":', answer: 'Vred', options: ['Vred', 'Glad', 'Sjov'], instruction: 'Synonymer' },
    { id: 'da1-g29', type: 'Grammar', question: 'Er "ugle" et navneord?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Ordklasser' },
    { id: 'da1-g30', type: 'Grammar', question: 'Er "gul" et tillægsord?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Ordklasser' },
    { id: 'da1-g31', type: 'Grammar', question: 'Er "synger" et udsagnsord?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Ordklasser' },
    { id: 'da1-g32', type: 'Grammar', question: 'Hvad er "jeg"?', answer: 'Stedord', options: ['Stedord', 'Navneord', 'Udsagnsord'], instruction: 'Ordklasser' },
    { id: 'da1-g33', type: 'Grammar', question: 'Hvad er "du"?', answer: 'Stedord', options: ['Stedord', 'Tillægsord', 'Udsagnsord'], instruction: 'Ordklasser' },
    { id: 'da1-g34', type: 'Grammar', question: 'Hedder det "min" eller "mit" bold?', answer: 'Min', options: ['Min', 'Mit'], instruction: 'Ejestedord' },
    { id: 'da1-g35', type: 'Grammar', question: 'Hedder det "min" eller "mit" hus?', answer: 'Mit', options: ['Mit', 'Min'], instruction: 'Ejestedord' },
    { id: 'da1-g36', type: 'Grammar', question: 'Find navneordet i "Hesten løber":', answer: 'Hesten', options: ['Hesten', 'løber'], instruction: 'Ordklasser' },
    { id: 'da1-g37', type: 'Grammar', question: 'Er "hurtig" et tillægsord?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Ordklasser' },
    { id: 'da1-g38', type: 'Grammar', question: 'Hedder det "stor" eller "stort" bord?', answer: 'Stort', options: ['Stort', 'Stor'], instruction: 'Adjektiver' },
    { id: 'da1-g39', type: 'Grammar', question: 'Hedder det "stor" eller "stort" bil?', answer: 'Stor', options: ['Stor', 'Stort'], instruction: 'Adjektiver' },
    { id: 'da1-g40', type: 'Grammar', question: 'Find det rigtige: "en rød ___"', answer: 'bil', options: ['bil', 'æble', 'hus'], instruction: 'Kongruens' },
    { id: 'da1-g41', type: 'Grammar', question: 'Find det rigtige: "et rødt ___"', answer: 'æble', options: ['æble', 'bil', 'stol'], instruction: 'Kongruens' },
    { id: 'da1-g42', type: 'Grammar', question: 'Er "og" et bindeord?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Bindeord' },
    { id: 'da1-g43', type: 'Grammar', question: 'Er "men" et bindeord?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Bindeord' },
    { id: 'da1-g44', type: 'Grammar', question: 'Hvad mangler: "Hunden ___ i går"', answer: 'sov', options: ['sov', 'sover', 'sove'], instruction: 'Datid' },
    { id: 'da1-g45', type: 'Grammar', question: 'Hvad mangler: "Pigen ___ i går"', answer: 'løb', options: ['løb', 'løber', 'løbe'], instruction: 'Datid' },
    { id: 'da1-g46', type: 'Grammar', question: 'Er "under" et forholdsord?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Forholdsord' },
    { id: 'da1-g47', type: 'Grammar', question: 'Er "på" et forholdsord?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Forholdsord' },
    { id: 'da1-g48', type: 'Grammar', question: 'Find navnet: "Jeg hedder Lise"', answer: 'Lise', options: ['Lise', 'Jeg', 'hedder'], instruction: 'Egennavne' },
    { id: 'da1-g49', type: 'Grammar', question: 'Hvad er "hun"?', answer: 'Stedord', options: ['Stedord', 'Navneord', 'Tillægsord'], instruction: 'Ordklasser' },
    { id: 'da1-g50', type: 'Grammar', question: 'Hvad er "han"?', answer: 'Stedord', options: ['Stedord', 'Navneord', 'Tillægsord'], instruction: 'Ordklasser' },
    { id: 'da1-g51', type: 'Grammar', question: 'Næste ___.', answer: 'stop', options: ['stop', 'mad', 'bil'], instruction: 'Besked' },
  ],
  2: [
    { id: 'da2-g1', type: 'Grammar', question: 'Find navneordet (substantiv):', answer: 'Bil', options: ['Bil', 'Hoppe', 'Blå', 'Hej'], instruction: 'Ordklasser' },
    { id: 'da2-g2', type: 'Grammar', question: 'Find udsagnsordet (verbum):', answer: 'Spise', options: ['Spise', 'Kop', 'Rød', 'Her'], instruction: 'Ordklasser' },
    { id: 'da2-g3', type: 'Grammar', question: 'Find tillægsordet (adjektiv):', answer: 'Gul', options: ['Hoppe', 'Gul', 'Hest'], instruction: 'Ordklasser' },
    { id: 'da2-g4', type: 'Grammar', question: 'Hvad er bøjningen af "bil" i bestemt ental?', answer: 'Bilen', options: ['Bilen', 'Bilene', 'Biler'], instruction: 'Bøjning' },
    { id: 'da2-g5', type: 'Grammar', question: 'Hvad er bøjningen af "bil" i ubestemt flertal?', answer: 'Biler', options: ['Biler', 'Bilen', 'Bilerne'], instruction: 'Bøjning' },
    { id: 'da2-g6', type: 'Grammar', question: 'Hvad er bøjningen af "bil" i bestemt flertal?', answer: 'Bilerne', options: ['Bilerne', 'Biler', 'Bilen'], instruction: 'Bøjning' },
    { id: 'da2-g7', type: 'Grammar', question: 'Find udsagnsordet i nutid: "Han ___"', answer: 'løber', options: ['løber', 'løb', 'løbe'], instruction: 'Verbaltid' },
    { id: 'da2-g8', type: 'Grammar', question: 'Find udsagnsordet i datid: "Han ___ i går"', answer: 'løb', options: ['løb', 'løber', 'løbe'], instruction: 'Verbaltid' },
    { id: 'da2-g9', type: 'Grammar', question: 'Hvordan staves "cykel" i flertal?', answer: 'Cykler', options: ['Cykler', 'Cykeler', 'Cyklerne'], instruction: 'Stavning' },
    { id: 'da2-g10', type: 'Grammar', question: 'Hvordan staves "æble" i flertal?', answer: 'Æbler', options: ['Æbler', 'Æbleer', 'Æblere'], instruction: 'Stavning' },
    { id: 'da2-g11', type: 'Grammar', question: 'Hvad er "vi" for en ordklasse?', answer: 'Personligt stedord', options: ['Personligt stedord', 'Ejestedord', 'Navneord'], instruction: 'Ordklasser' },
    { id: 'da2-g12', type: 'Grammar', question: 'Hvad er "vores" for en ordklasse?', answer: 'Ejestedord', options: ['Ejestedord', 'Personligt stedord', 'Navneord'], instruction: 'Ordklasser' },
    { id: 'da2-g13', type: 'Grammar', question: 'Hvad er modsætningen til "langsom"?', answer: 'Hurtig', options: ['Hurtig', 'Snegl', 'Gå'], instruction: 'Antonymer' },
    { id: 'da2-g14', type: 'Grammar', question: 'Hvad er modsætningen til "mørk"?', answer: 'Lys', options: ['Lys', 'Nat', 'Sort'], instruction: 'Antonymer' },
    { id: 'da2-g15', type: 'Grammar', question: 'Find navneordet: "Solen skinner"', answer: 'Solen', options: ['Solen', 'skinner'], instruction: 'Ordklasser' },
    { id: 'da2-g16', type: 'Grammar', question: 'Find udsagnsordet: "Solen skinner"', answer: 'skinner', options: ['skinner', 'Solen'], instruction: 'Ordklasser' },
    { id: 'da2-g17', type: 'Grammar', question: 'Find tillægsordet: "En rød bold"', answer: 'rød', options: ['rød', 'En', 'bold'], instruction: 'Ordklasser' },
    { id: 'da2-g18', type: 'Grammar', question: 'Hvilket ord er et talord?', answer: 'Fem', options: ['Fem', 'Mange', 'Stor'], instruction: 'Ordklasser' },
    { id: 'da2-g19', type: 'Grammar', question: 'Hvilket ord er et stedord?', answer: 'De', options: ['De', 'Hus', 'Glad'], instruction: 'Ordklasser' },
    { id: 'da2-g20', type: 'Grammar', question: 'Hvilket ord er en præposition (forholdsord)?', answer: 'På', options: ['På', 'Gå', 'Gul'], instruction: 'Ordklasser' },
    { id: 'da2-g21', type: 'Grammar', question: 'Hvilket ord er en konjunktion (bindeord)?', answer: 'Fordi', options: ['Fordi', 'Måske', 'Altid'], instruction: 'Ordklasser' },
    { id: 'da2-g22', type: 'Grammar', question: 'Bøj "god" i grader:', answer: 'God, bedre, bedst', options: ['God, bedre, bedst', 'God, goder, godest', 'God, mere god, mest god'], instruction: 'Gradbøjning' },
    { id: 'da2-g23', type: 'Grammar', question: 'Bøj "lille" i grader:', answer: 'Lille, mindre, mindst', options: ['Lille, mindre, mindst', 'Lille, lillere, lillest', 'Lille, mere lille, mest lille'], instruction: 'Gradbøjning' },
    { id: 'da2-g24', type: 'Grammar', question: 'Finder du navneordet i: "Manden kører bil"', answer: 'Manden, bil', options: ['Manden, bil', 'kører', 'Manden kører'], instruction: 'Sætningsanalyse' },
    { id: 'da2-g25', type: 'Grammar', question: 'Hvilket ord har store begyndelsesbogstaver?', answer: 'Danmark', options: ['Danmark', 'land', 'sprog'], instruction: 'Egennavne' },
    { id: 'da2-g26', type: 'Grammar', question: 'Hvor mange stavelser i "sommerfugl"?', answer: '3', options: ['3', '2', '4'], instruction: 'Stavelser' },
    { id: 'da2-g27', type: 'Grammar', question: 'Hvor mange stavelser i "fodboldbane"?', answer: '4', options: ['4', '3', '5'], instruction: 'Stavelser' },
    { id: 'da2-g28', type: 'Grammar', question: 'Hvilken vokal mangler: h_s (ting man bor i)?', answer: 'u', options: ['u', 'e', 'a'], instruction: 'Stavning' },
    { id: 'da2-g29', type: 'Grammar', question: 'Hvilken konsonant mangler: k_tte?', answer: 'a', options: ['a', 'e', 'o'], instruction: 'Vokaler (Ups, det var en vokal)' },
    { id: 'da2-g30', type: 'Grammar', question: 'Find fejlen: "Jeg har to hund"', answer: 'hund', options: ['hund', 'Jeg', 'har'], instruction: 'Fejlfinding' },
    { id: 'da2-g31', type: 'Grammar', question: 'Find fejlen: "En lille huse"', answer: 'huse', options: ['huse', 'En', 'lille'], instruction: 'Fejlfinding' },
    { id: 'da2-g32', type: 'Grammar', question: 'Er "at" et navnemærke?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Ordklasser' },
    { id: 'da2-g33', type: 'Grammar', question: 'Hvilken tid er "jeg spiste"?', answer: 'Datid', options: ['Datid', 'Nutid', 'Fremtid'], instruction: 'Verbaltid' },
    { id: 'da2-g34', type: 'Grammar', question: 'Hvilken tid er "jeg vil spise"?', answer: 'Fremtid', options: ['Fremtid', 'Nutid', 'Datid'], instruction: 'Verbaltid' },
    { id: 'da2-g35', type: 'Grammar', question: 'Hvilken tid er "jeg spiser"?', answer: 'Nutid', options: ['Nutid', 'Datid', 'Fremtid'], instruction: 'Verbaltid' },
    { id: 'da2-g36', type: 'Grammar', question: 'Hvad er ental af "børn"?', answer: 'Barn', options: ['Barn', 'Børne', 'Børnen'], instruction: 'Bøjning' },
    { id: 'da2-g37', type: 'Grammar', question: 'Hvad er ental af "mænd"?', answer: 'Mand', options: ['Mand', 'Mænden', 'Mænder'], instruction: 'Bøjning' },
    { id: 'da2-g38', type: 'Grammar', question: 'Hvad er flertal af "bog"?', answer: 'Bøger', options: ['Bøger', 'Bogger', 'Bogene'], instruction: 'Bøjning' },
    { id: 'da2-g39', type: 'Grammar', question: 'Hedder det "en" eller "et" æble?', answer: 'Et', options: ['Et', 'En'], instruction: 'Kendeord' },
    { id: 'da2-g40', type: 'Grammar', question: 'Hedder det "en" eller "et" banan?', answer: 'En', options: ['En', 'Et'], instruction: 'Kendeord' },
    { id: 'da2-g41', type: 'Grammar', question: 'Find det sammensatte ord:', answer: 'Vandflaske', options: ['Vandflaske', 'Løbe', 'Gul'], instruction: 'Morfologi' },
    { id: 'da2-g42', type: 'Grammar', question: 'Find udråbsordet:', answer: 'Av', options: ['Av', 'Hej', 'Bil'], instruction: 'Ordklasser' },
    { id: 'da2-g43', type: 'Grammar', question: 'Hvad er "hans"?', answer: 'Ejestedord', options: ['Ejestedord', 'Personligt stedord', 'Tillægsord'], instruction: 'Ordklasser' },
    { id: 'da2-g44', type: 'Grammar', question: 'Hvad er "hendes"?', answer: 'Ejestedord', options: ['Ejestedord', 'Personligt stedord', 'Udsagnsord'], instruction: 'Ordklasser' },
    { id: 'da2-g45', type: 'Grammar', question: 'Find grundleddet: "Isen smelter"', answer: 'Isen', options: ['Isen', 'smelter'], instruction: 'Sætningsanalyse' },
    { id: 'da2-g46', type: 'Grammar', question: 'Find udsagnsleddet: "Isen smelter"', answer: 'smelter', options: ['smelter', 'Isen'], instruction: 'Sætningsanalyse' },
    { id: 'da2-g47', type: 'Grammar', question: 'Hvilket ord rhimer på "hest"?', answer: 'Fest', options: ['Fest', 'Hund', 'Kat'], instruction: 'Rim' },
    { id: 'da2-g48', type: 'Grammar', question: 'Hvilket ord rhimer på "hus"?', answer: 'Mus', options: ['Mus', 'Hus', 'Ost'], instruction: 'Rim' },
    { id: 'da2-g49', type: 'Grammar', question: 'Hvilket ord rhimer på "bil"?', answer: 'Smil', options: ['Smil', 'Bil', 'Vej'], instruction: 'Rim' },
    { id: 'da2-g50', type: 'Grammar', question: 'Hvilket ord rhimer på "dag"?', answer: 'Tag', options: ['Tag', 'Dag', 'Nat'], instruction: 'Rim' },
    { id: 'da2-g51', type: 'Grammar', question: 'Super ___.', answer: 'klaret', options: ['klaret', 'spist', 'sovet'], instruction: 'Besked' },
  ],
  3: [
    { id: 'da3-g1', type: 'Grammar', question: 'Hvad er ordklassen for "hurtigt" i: "Han løber hurtigt"?', answer: 'Biord (adverbium)', options: ['Biord (adverbium)', 'Tillægsord (adjektiv)', 'Udsagnsord (verbum)'], instruction: 'Ordklasser' },
    { id: 'da3-g2', type: 'Grammar', question: 'Hvad er ordklassen for "smuk" i: "En smuk blomst"?', answer: 'Tillægsord (adjektiv)', options: ['Tillægsord (adjektiv)', 'Biord (adverbium)', 'Navneord (substantiv)'], instruction: 'Ordklasser' },
    { id: 'da3-g3', type: 'Grammar', question: 'Find navneordet i: "Bilerne kører stærkt"', answer: 'Bilerne', options: ['Bilerne', 'kører', 'stærkt'], instruction: 'Ordklasser' },
    { id: 'da3-g4', type: 'Grammar', question: 'Find udsagnsordet i: "Bilerne kører stærkt"', answer: 'kører', options: ['kører', 'Bilerne', 'stærkt'], instruction: 'Ordklasser' },
    { id: 'da3-g5', type: 'Grammar', question: 'Find biordet i: "Bilerne kører stærkt"', answer: 'stærkt', options: ['stærkt', 'kører', 'Bilerne'], instruction: 'Ordklasser' },
    { id: 'da3-g6', type: 'Grammar', question: 'Hvordan bøjes "stor" i grader?', answer: 'Stor, større, størst', options: ['Stor, større, størst', 'Stor, mere stor, mest stor', 'Stor, god, bedst'], instruction: 'Gradbøjning' },
    { id: 'da3-g7', type: 'Grammar', question: 'Hvordan bøjes "lille" i grader?', answer: 'Lille, mindre, mindst', options: ['Lille, mindre, mindst', 'Lille, lillere, lillest', 'Lille, små, mindst'], instruction: 'Gradbøjning' },
    { id: 'da3-g8', type: 'Grammar', question: 'Hvilken tid er: "Vi har leget"?', answer: 'Førnutid', options: ['Førnutid', 'Nutid', 'Datid'], instruction: 'Verbaltid' },
    { id: 'da3-g9', type: 'Grammar', question: 'Hvilken tid er: "Vi havde leget"?', answer: 'Førdatid', options: ['Førdatid', 'Førnutid', 'Datid'], instruction: 'Verbaltid' },
    { id: 'da3-g10', type: 'Grammar', question: 'Hvilket ord er et bindeord?', answer: 'Men', options: ['Men', 'Løbe', 'Stor'], instruction: 'Ordklasser' },
    { id: 'da3-g11', type: 'Grammar', question: 'Hvilket ord er et forholdsord?', answer: 'Mellem', options: ['Mellem', 'Mange', 'Men'], instruction: 'Ordklasser' },
    { id: 'da3-g12', type: 'Grammar', question: 'Hvad er grundleddet i: "Min far vasker op"?', answer: 'Min far', options: ['Min far', 'vasker', 'op'], instruction: 'Sætningsanalyse' },
    { id: 'da3-g13', type: 'Grammar', question: 'Hvad er udsagnsleddet i: "Min far vasker op"?', answer: 'vasker op', options: ['vasker op', 'Min far', 'op'], instruction: 'Sætningsanalyse' },
    { id: 'da3-g14', type: 'Grammar', question: 'Hvad er genstandsleddet i: "Han spiser et æble"?', answer: 'et æble', options: ['et æble', 'Han', 'spiser'], instruction: 'Sætningsanalyse' },
    { id: 'da3-g15', type: 'Grammar', question: 'Hvordan staves "lærer" i flertal?', answer: 'Lærere', options: ['Lærere', 'Lærerne', 'Lærerer'], instruction: 'Stavning' },
    { id: 'da3-g16', type: 'Grammar', question: 'Hvordan staves "elev" i flertal?', answer: 'Elever', options: ['Elever', 'Elevene', 'Eleverer'], instruction: 'Stavning' },
    { id: 'da3-g17', type: 'Grammar', question: 'Find det rigtige sammensatte ord:', answer: 'Vandmelon', options: ['Vandmelon', 'Vand melon', 'Vand-melon'], instruction: 'Morfologi' },
    { id: 'da3-g18', type: 'Grammar', question: 'Find det rigtige sammensatte ord:', answer: 'Blomsterkrukke', options: ['Blomsterkrukke', 'Blomster krukke', 'Blomster-krukke'], instruction: 'Morfologi' },
    { id: 'da3-g19', type: 'Grammar', question: 'Er "hvilken" et spørgeord?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Spørgeord' },
    { id: 'da3-g20', type: 'Grammar', question: 'Er "fordi" en konjunktion?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Ordklasser' },
    { id: 'da3-g21', type: 'Grammar', question: 'Hvad kaldes "smukt" i: "Hun synger smukt"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Adjektiv (tillægsord)', 'Verbum (udsagnsord)'], instruction: 'Ordklasser' },
    { id: 'da3-g22', type: 'Grammar', question: 'Hvad kaldes "smuk" i: "Hun er smuk"?', answer: 'Adjektiv (tillægsord)', options: ['Adjektiv (tillægsord)', 'Adverbium (biord)', 'Substantiv (navneord)'], instruction: 'Ordklasser' },
    { id: 'da3-g23', type: 'Grammar', question: 'Find flertal af "mand":', answer: 'Mænd', options: ['Mænd', 'Mænder', 'Mandene'], instruction: 'Bøjning' },
    { id: 'da3-g24', type: 'Grammar', question: 'Find flertal af "barn":', answer: 'Børn', options: ['Børn', 'Børner', 'Barnene'], instruction: 'Bøjning' },
    { id: 'da3-g25', type: 'Grammar', question: 'Find flertal af "fod":', answer: 'Fødder', options: ['Fødder', 'Foder', 'Fodene'], instruction: 'Bøjning' },
    { id: 'da3-g26', type: 'Grammar', question: 'Find flertal af "tand":', answer: 'Tænder', options: ['Tænder', 'Tander', 'Tandene'], instruction: 'Bøjning' },
    { id: 'da3-g27', type: 'Grammar', question: 'Find flertal af "hånd":', answer: 'Hænder', options: ['Hænder', 'Hånder', 'Håndene'], instruction: 'Bøjning' },
    { id: 'da3-g28', type: 'Grammar', question: 'Hvad er "min"?', answer: 'Possessivt pronomen', options: ['Possessivt pronomen', 'Personligt pronomen', 'Demonstrativt pronomen'], instruction: 'Ordklasser' },
    { id: 'da3-g29', type: 'Grammar', question: 'Hvad er "din"?', answer: 'Possessivt pronomen', options: ['Possessivt pronomen', 'Personligt pronomen', 'Relativt pronomen'], instruction: 'Ordklasser' },
    { id: 'da3-g30', type: 'Grammar', question: 'Find fejlen: "Han løbet i går"', answer: 'løbet', options: ['løbet', 'Han', 'går'], instruction: 'Fejlfinding' },
    { id: 'da3-g31', type: 'Grammar', question: 'Find fejlen: "Vi har se filmen"', answer: 'se', options: ['se', 'Vi', 'har'], instruction: 'Fejlfinding' },
    { id: 'da3-g32', type: 'Grammar', question: 'Find fejlen: "De spiser mange æble"', answer: 'æble', options: ['æble', 'De', 'mange'], instruction: 'Fejlfinding' },
    { id: 'da3-g33', type: 'Grammar', question: 'Hvilken vokaltrappe: i, e, ___', answer: 'æ', options: ['æ', 'o', 'u'], instruction: 'Vokaltrappen' },
    { id: 'da3-g34', type: 'Grammar', question: 'Hvilken vokaltrappe: y, ø, ___', answer: 'å', options: ['å', 'u', 'i'], instruction: 'Vokaltrappen' },
    { id: 'da3-g35', type: 'Grammar', question: 'Hvordan staves "mor": m-o-r eller m-å-r?', answer: 'm-o-r', options: ['m-o-r', 'm-å-r'], instruction: 'Stavning' },
    { id: 'da3-g36', type: 'Grammar', question: 'Hvordan staves "sove": s-o-v-e eller s-å-v-e?', answer: 's-o-v-e', options: ['s-o-v-e', 's-å-v-e'], instruction: 'Stavning' },
    { id: 'da3-g37', type: 'Grammar', question: 'Hvordan staves "bord": b-o-r-d eller b-å-r-d?', answer: 'b-o-r-d', options: ['b-o-r-d', 'b-å-r-d'], instruction: 'Stavning' },
    { id: 'da3-g38', type: 'Grammar', question: 'Hvilken konsonant er stum i "glad"?', answer: 'd', options: ['d', 'g', 'l'], instruction: 'Stumme bogstaver' },
    { id: 'da3-g39', type: 'Grammar', question: 'Hvilken konsonant er stum i "hvad"?', answer: 'h', options: ['h', 'v', 'a'], instruction: 'Stumme bogstaver' },
    { id: 'da3-g40', type: 'Grammar', question: 'Hvilken konsonant er stum i "knæ"?', answer: 'k', options: ['k', 'n', 'æ'], instruction: 'Stumme bogstaver' },
    { id: 'da3-g41', type: 'Grammar', question: 'Find forholdsordet (præposition):', answer: 'Gennem', options: ['Gennem', 'Glad', 'Gå'], instruction: 'Ordklasser' },
    { id: 'da3-g42', type: 'Grammar', question: 'Find forholdsordet (præposition):', answer: 'Mod', options: ['Mod', 'Mange', 'Men'], instruction: 'Ordklasser' },
    { id: 'da3-g43', type: 'Grammar', question: 'Find forholdsordet (præposition):', answer: 'Fra', options: ['Fra', 'Fem', 'Før'], instruction: 'Ordklasser' },
    { id: 'da3-g44', type: 'Grammar', question: 'Hvad er "mig"?', answer: 'Personligt pronomen', options: ['Personligt pronomen', 'Ejestedord', 'Tillægsord'], instruction: 'Ordklasser' },
    { id: 'da3-g45', type: 'Grammar', question: 'Hvad er "dig"?', answer: 'Personligt pronomen', options: ['Personligt pronomen', 'Navneord', 'Udsagnsord'], instruction: 'Ordklasser' },
    { id: 'da3-g46', type: 'Grammar', question: 'Hvordan staves "være": v-æ-r-e eller v-e-r-e?', answer: 'v-æ-r-e', options: ['v-æ-r-e', 'v-e-r-e'], instruction: 'Stavning' },
    { id: 'da3-g47', type: 'Grammar', question: 'Hvordan staves "hver": h-v-e-r eller v-e-r?', answer: 'h-v-e-r', options: ['h-v-e-r', 'v-e-r'], instruction: 'Stavning' },
    { id: 'da3-g48', type: 'Grammar', question: 'Hvilket ord er et overbegreb for "æble, banan, pære"?', answer: 'Frugt', options: ['Frugt', 'Mad', 'Grøntsag'], instruction: 'Betydning' },
    { id: 'da3-g49', type: 'Grammar', question: 'Hvilket ord er et overbegreb for "bil, bus, tog"?', answer: 'Transport', options: ['Transport', 'Rejse', 'Hjul'], instruction: 'Betydning' },
    { id: 'da3-g50', type: 'Grammar', question: 'Hvilket ord er et overbegreb for "hund, kat, mus"?', answer: 'Dyr', options: ['Dyr', 'Natur', 'Pels'], instruction: 'Betydning' },
    { id: 'da3-g51', type: 'Grammar', question: 'Du er ___.', answer: 'sej', options: ['sej', 'blå', 'hus'], instruction: 'Besked' },
  ],
  4: [
    { id: 'da4-g1', type: 'Grammar', question: 'Sammensat ord: Sol + skin = ?', answer: 'Solskin', options: ['Solskin', 'Sol skin', 'Sol-skin'], instruction: 'Morfologi' },
    { id: 'da4-g2', type: 'Grammar', question: 'Find biordet i: "De sang utrolig flot"', answer: 'utrolig', options: ['utrolig', 'flot', 'sang'], instruction: 'Ordklasser' },
    { id: 'da4-g3', type: 'Grammar', question: 'Find biordet i: "Huset er meget gammelt"', answer: 'meget', options: ['meget', 'gammelt', 'Huset'], instruction: 'Ordklasser' },
    { id: 'da4-g4', type: 'Grammar', question: 'Hvordan bøjes "lang" i grader?', answer: 'Lang, længere, længst', options: ['Lang, længere, længst', 'Lang, langere, langest', 'Lang, mest lang, lang'], instruction: 'Gradbøjning' },
    { id: 'da4-g5', type: 'Grammar', question: 'Hvordan bøjes "tung" i grader?', answer: 'Tung, tungere, tungest', options: ['Tung, tungere, tungest', 'Tung, mere tung, tungest', 'Tung, tyngere, tyngst'], instruction: 'Gradbøjning' },
    { id: 'da4-g6', type: 'Grammar', question: 'Bøj "at skrive" i nutid:', answer: 'Skriver', options: ['Skriver', 'Skrev', 'Skrevet'], instruction: 'Verber' },
    { id: 'da4-g7', type: 'Grammar', question: 'Bøj "at skrive" i datid:', answer: 'Skrev', options: ['Skrev', 'Skriver', 'Skrevet'], instruction: 'Verber' },
    { id: 'da4-g8', type: 'Grammar', question: 'Bøj "at skrive" i førnutid:', answer: 'Har skrevet', options: ['Har skrevet', 'Havde skrevet', 'Skriver'], instruction: 'Verber' },
    { id: 'da4-g9', type: 'Grammar', question: 'Hvad er navneformen af "løber"?', answer: 'At løbe', options: ['At løbe', 'Løb', 'Løber'], instruction: 'Infinitiv' },
    { id: 'da4-g10', type: 'Grammar', question: 'Hvad er navneformen af "svømmer"?', answer: 'At svømme', options: ['At svømme', 'Svømmede', 'Svømmet'], instruction: 'Infinitiv' },
    { id: 'da4-g11', type: 'Grammar', question: 'Find grundleddet: "Isen blev spist af barnet"', answer: 'Isen', options: ['Isen', 'barnet', 'spist'], instruction: 'Sætningsanalyse' },
    { id: 'da4-g12', type: 'Grammar', question: 'Find udsagnsleddet: "Isen blev spist af barnet"', answer: 'blev spist', options: ['blev spist', 'Isen', 'barnet'], instruction: 'Sætningsanalyse' },
    { id: 'da4-g13', type: 'Grammar', question: 'Hvad er "af" i sætningen?', answer: 'Forholdsord', options: ['Forholdsord', 'Bindeord', 'Biord'], instruction: 'Ordklasser' },
    { id: 'da4-g14', type: 'Grammar', question: 'Hvordan staves "hvis" (betingelse)?', answer: 'Hvis', options: ['Hvis', 'Vis', 'Vish'], instruction: 'Stavning' },
    { id: 'da4-g15', type: 'Grammar', question: 'Hvordan staves "vis" (at vise noget)?', answer: 'Vis', options: ['Vis', 'Hvis', 'Vise'], instruction: 'Stavning' },
    { id: 'da4-g16', type: 'Grammar', question: 'Hvordan staves "hvid" (farve)?', answer: 'Hvid', options: ['Hvid', 'Vid', 'Hvidt'], instruction: 'Stavning' },
    { id: 'da4-g17', type: 'Grammar', question: 'Find flertal af "bog":', answer: 'Bøger', options: ['Bøger', 'Bogger', 'Bøgene'], instruction: 'Bøjning' },
    { id: 'da4-g18', type: 'Grammar', question: 'Find flertal af "træ":', answer: 'Træer', options: ['Træer', 'Træner', 'Træ'], instruction: 'Bøjning' },
    { id: 'da4-g19', type: 'Grammar', question: 'Find flertal af "hus":', answer: 'Huse', options: ['Huse', 'Husene', 'Huser'], instruction: 'Bøjning' },
    { id: 'da4-g20', type: 'Grammar', question: 'Hvilken tid er: "De vil rejse"?', answer: 'Fremtid', options: ['Fremtid', 'Nutid', 'Datid'], instruction: 'Verbaltid' },
    { id: 'da4-g21', type: 'Grammar', question: 'Find forholdsordet i: "Bogen ligger under sengen"', answer: 'under', options: ['under', 'Bogen', 'sengen'], instruction: 'Ordklasser' },
    { id: 'da4-g22', type: 'Grammar', question: 'Find forholdsordet i: "Vi går over broen"', answer: 'over', options: ['over', 'Vi', 'broen'], instruction: 'Ordklasser' },
    { id: 'da4-g23', type: 'Grammar', question: 'Hvornår bruger man "og"?', answer: 'For at binde ord eller sætninger sammen', options: ['For at binde ord eller sætninger sammen', 'Ved spørgsmål', 'Ved afslutning'], instruction: 'Bindeord' },
    { id: 'da4-g24', type: 'Grammar', question: 'Hvornår bruger man "at"?', answer: 'Foran navneform eller ledsætning', options: ['Foran navneform eller ledsætning', 'Foran navneord', 'Foran tillægsord'], instruction: 'Navnemærke/Konjunktion' },
    { id: 'da4-g25', type: 'Grammar', question: 'Hvad er ordklassen for "ham"?', answer: 'Personligt stedord', options: ['Personligt stedord', 'Ejestedord', 'Navneord'], instruction: 'Ordklasser' },
    { id: 'da4-g26', type: 'Grammar', question: 'Hvad er ordklassen for "hende"?', answer: 'Personligt stedord', options: ['Personligt stedord', 'Ejestedord', 'Navneord'], instruction: 'Ordklasser' },
    { id: 'da4-g27', type: 'Grammar', question: 'Bøj "smuk" i køn og tal: en ___ pige', answer: 'smuk', options: ['smuk', 'smukt', 'smukke'], instruction: 'Kongruens' },
    { id: 'da4-g28', type: 'Grammar', question: 'Bøj "smuk" i køn og tal: et ___ hus', answer: 'smukt', options: ['smukt', 'smuk', 'smukke'], instruction: 'Kongruens' },
    { id: 'da4-g29', type: 'Grammar', question: 'Bøj "smuk" i køn og tal: to ___ blomster', answer: 'smukke', options: ['smukke', 'smuk', 'smukt'], instruction: 'Kongruens' },
    { id: 'da4-g30', type: 'Grammar', question: 'Hvilket ord er ikke et navneord?', answer: 'Løbe', options: ['Løbe', 'Løve', 'Lampe'], instruction: 'Ordklasser' },
    { id: 'da4-g31', type: 'Grammar', question: 'Hvilket ord er ikke et udsagnsord?', answer: 'Gul', options: ['Gul', 'Gå', 'Give'], instruction: 'Ordklasser' },
    { id: 'da4-g32', type: 'Grammar', question: 'Hvilket ord er ikke et tillægsord?', answer: 'Kat', options: ['Kat', 'Kold', 'Kort'], instruction: 'Ordklasser' },
    { id: 'da4-g33', type: 'Grammar', question: 'Hvordan staves "egentlig"?', answer: 'Egentlig', options: ['Egentlig', 'Egentlig', 'Entlig'], instruction: 'Stavning' },
    { id: 'da4-g34', type: 'Grammar', question: 'Hvordan staves "måske"?', answer: 'Måske', options: ['Måske', 'Moske', 'Morske'], instruction: 'Stavning' },
    { id: 'da4-g35', type: 'Grammar', question: 'Hvordan staves "aldrig"?', answer: 'Aldrig', options: ['Aldrig', 'Alrig', 'Aldri'], instruction: 'Stavning' },
    { id: 'da4-g36', type: 'Grammar', question: 'Find det rigtige: "Jeg ___ i morgen"', answer: 'kommer', options: ['kommer', 'kom', 'kommet'], instruction: 'Syntaks' },
    { id: 'da4-g37', type: 'Grammar', question: 'Find det rigtige: "Hun ___ her i går"', answer: 'var', options: ['var', 'er', 'bliver'], instruction: 'Syntaks' },
    { id: 'da4-g38', type: 'Grammar', question: 'Hvilket ord er et biord?', answer: 'Ofte', options: ['Ofte', 'Ost', 'Op'], instruction: 'Ordklasser' },
    { id: 'da4-g39', type: 'Grammar', question: 'Hvilket ord er et biord?', answer: 'Her', options: ['Her', 'Hest', 'Han'], instruction: 'Ordklasser' },
    { id: 'da4-g40', type: 'Grammar', question: 'Hvilket ord er et biord?', answer: 'Nu', options: ['Nu', 'Navn', 'Nat'], instruction: 'Ordklasser' },
    { id: 'da4-g41', type: 'Grammar', question: 'Hvad betyder "synonym"?', answer: 'Et ord der betyder det samme', options: ['Et ord der betyder det samme', 'Et ord der betyder det modsatte', 'Et ord der staves ens'], instruction: 'Begreber' },
    { id: 'da4-g42', type: 'Grammar', question: 'Hvad betyder "antonym"?', answer: 'Et ord der betyder det modsatte', options: ['Et ord der betyder det modsatte', 'Et ord der betyder det samme', 'Et ord med to betydninger'], instruction: 'Begreber' },
    { id: 'da4-g43', type: 'Grammar', question: 'Hvilket ord mangler i "at ___, hopper, hoppede, hoppet"?', answer: 'hoppe', options: ['hoppe', 'hoppende', 'hop'], instruction: 'Bøjning' },
    { id: 'da4-g44', type: 'Grammar', question: 'Find grundleddet: "Drengen og pigen løber om kap"', answer: 'Drengen og pigen', options: ['Drengen og pigen', 'løber', 'om kap'], instruction: 'Sætningsanalyse' },
    { id: 'da4-g45', type: 'Grammar', question: 'Find udsagnsleddet: "De har lige spist"', answer: 'har spist', options: ['har spist', 'De', 'lige'], instruction: 'Sætningsanalyse' },
    { id: 'da4-g46', type: 'Grammar', question: 'Er "hvorfor" et spørgeord?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Spørgeord' },
    { id: 'da4-g47', type: 'Grammar', question: 'Er "hvordan" et spørgeord?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Spørgeord' },
    { id: 'da4-g48', type: 'Grammar', question: 'Hvad kaldes det, når man sammensætter ord?', answer: 'Sammensætning', options: ['Sammensætning', 'Deling', 'Bøjning'], instruction: 'Begreber' },
    { id: 'da4-g49', type: 'Grammar', question: 'Find sammensat ord: "tøj" + "skab" = ?', answer: 'Tøjskab', options: ['Tøjskab', 'Tøj skab', 'Tøjskabet'], instruction: 'Morfologi' },
    { id: 'da4-g50', type: 'Grammar', question: 'Find sammensat ord: "mad" + "pakke" = ?', answer: 'Madpakke', options: ['Madpakke', 'Mad pakke', 'Mad-pakke'], instruction: 'Morfologi' },
    { id: 'da4-g51', type: 'Grammar', question: 'Godt ___.', answer: 'arbejde', options: ['arbejde', 'mad', 'sove'], instruction: 'Besked' },
  ],
};
