/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const DANSK_GRAMMAR_P3: Partial<Record<Grade, GameContent[]>> = {
  8: [
    { id: 'da8-g1', type: 'Grammar', question: 'Hvilken tid er: "Jeg havde spist"?', answer: 'Førdatid', options: ['Datid', 'Førdatid', 'Førnutid'], instruction: 'Verber' },
    { id: 'da8-g2', type: 'Grammar', question: 'Find omsagnsled til genstandsled (objektsprædikat) i: "Vi malede huset rødt"', answer: 'rødt', options: ['rødt', 'huset', 'Vi'], instruction: 'Sætningsanalyse' },
    { id: 'da8-g3', type: 'Grammar', question: 'Find genstandsleddet i: "Vi malede huset rødt"', answer: 'huset', options: ['huset', 'rødt', 'Vi'], instruction: 'Sætningsanalyse' },
    { id: 'da8-g4', type: 'Grammar', question: 'Find grundleddet i: "Det sner"', answer: 'Det', options: ['Det', 'sner'], instruction: 'Sætningsanalyse' },
    { id: 'da8-g5', type: 'Grammar', question: 'Find det relative pronomen i: "Manden, hvis bil blev stjålet, er her"', answer: 'hvis', options: ['hvis', 'Manden', 'bil'], instruction: 'Ordklasser' },
    { id: 'da8-g6', type: 'Grammar', question: 'Hvad er ordklassen for "hvis" i: "Manden, hvis bil..."?', answer: 'Relativt pronomen', options: ['Relativt pronomen', 'Konjunktion', 'Adjektiv'], instruction: 'Ordklasser' },
    { id: 'da8-g7', type: 'Grammar', question: 'Hvad er ordklassen for "hvis" i: "Spørg ham, hvis du er i tvivl"?', answer: 'Konjunktion (bindeord)', options: ['Konjunktion (bindeord)', 'Pronomen', 'Adverbium'], instruction: 'Ordklasser' },
    { id: 'da8-g8', type: 'Grammar', question: 'Bøj "at springe" i datid:', answer: 'Sprang', options: ['Sprang', 'Springede', 'Sprunget'], instruction: 'Verber' },
    { id: 'da8-g9', type: 'Grammar', question: 'Bøj "at springe" i førnutid:', answer: 'Har sprunget', options: ['Har sprunget', 'Sprang', 'Springer'], instruction: 'Verber' },
    { id: 'da8-g10', type: 'Grammar', question: 'Find fejlen: "Han er den klogeste af de to"', answer: 'klogeste (skal være klogere ved to)', options: ['klogeste', 'den', 'to'], instruction: 'Gradbøjning' },
    { id: 'da8-g11', type: 'Grammar', question: 'Hvordan staves "succes"?', answer: 'Succes', options: ['Succes', 'Succes', 'Success'], instruction: 'Stavning' },
    { id: 'da8-g12', type: 'Grammar', question: 'Hvordan staves "ressource"?', answer: 'Ressource', options: ['Ressource', 'Resource', 'Ressourse'], instruction: 'Stavning' },
    { id: 'da8-g13', type: 'Grammar', question: 'Hvordan staves "privilegeret"?', answer: 'Privilegeret', options: ['Privilegeret', 'Priviligeret', 'Previligeret'], instruction: 'Stavning' },
    { id: 'da8-g14', type: 'Grammar', question: 'Hvad er diatesen i: "Huset blev bygget af min far"?', answer: 'Passiv', options: ['Passiv', 'Aktiv', 'Medium'], instruction: 'Verber' },
    { id: 'da8-g15', type: 'Grammar', question: 'Find det logiske subjekt i: "Huset blev bygget af min far"', answer: 'min far', options: ['min far', 'Huset', 'bygget'], instruction: 'Sætningsanalyse' },
    { id: 'da8-g16', type: 'Grammar', question: 'Find det formelle grundled i: "Der var engang en konge"', answer: 'Der', options: ['Der', 'en konge', 'engang'], instruction: 'Sætningsanalyse' },
    { id: 'da8-g17', type: 'Grammar', question: 'Find det egentlige grundled i: "Der var engang en konge"', answer: 'en konge', options: ['en konge', 'Der', 'var'], instruction: 'Sætningsanalyse' },
    { id: 'da8-g18', type: 'Grammar', question: 'Er "at" et navnemærke i: "Jeg elsker at danse"?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Ordklasser' },
    { id: 'da8-g19', type: 'Grammar', question: 'Er "at" en konjunktion i: "Jeg sagde, at han kom"?', answer: 'Ja', options: ['Ja', 'Nej'], instruction: 'Ordklasser' },
    { id: 'da8-g20', type: 'Grammar', question: 'Find adverbialleddet i: "Han løber hurtigt i skoven"', answer: 'hurtigt, i skoven', options: ['hurtigt, i skoven', 'Han', 'løber'], instruction: 'Sætningsanalyse' },
    { id: 'da8-g21', type: 'Grammar', question: 'Find biordet (adverbiet) i: "Han kommer måske i morgen"', answer: 'måske, i morgen', options: ['måske, i morgen', 'kommer', 'Han'], instruction: 'Ordklasser' },
    { id: 'da8-g22', type: 'Grammar', question: 'Bøj "lille" i grader:', answer: 'Lille, mindre, mindst', options: ['Lille, mindre, mindst', 'Lille, små, mindst', 'Lille, lillere, lillest'], instruction: 'Gradbøjning' },
    { id: 'da8-g23', type: 'Grammar', question: 'Hvad betyder "at konjugere"?', answer: 'At bøje udsagnsord', options: ['At bøje udsagnsord', 'At bøje navneord', 'At skille ord ad'], instruction: 'Begreber' },
    { id: 'da8-g24', type: 'Grammar', question: 'Hvad betyder "at deklinere"?', answer: 'At bøje navneord', options: ['At bøje navneord', 'At bøje udsagnsord', 'At analysere sætninger'], instruction: 'Begreber' },
    { id: 'da8-g25', type: 'Grammar', question: 'Find fejlen: "Han er ligeså høj som mig"', answer: 'mig (skal være jeg)', options: ['mig', 'høj', 'ligeså'], instruction: 'Fejlfinding' },
    { id: 'da8-g26', type: 'Grammar', question: 'Find fejlen: "Bogen ligger på bordet, og dens farve er rød"', answer: 'Ingen fejl', options: ['Ingen fejl', 'dens', 'ligger'], instruction: 'Fejlfinding' },
    { id: 'da8-g27', type: 'Grammar', question: 'Hvilken ordklasse er "denne"?', answer: 'Demonstrativt pronomen', options: ['Demonstrativt pronomen', 'Personligt pronomen', 'Relativt pronomen'], instruction: 'Ordklasser' },
    { id: 'da8-g28', type: 'Grammar', question: 'Hvilken ordklasse er "selv"?', answer: 'Identitetspronomen', options: ['Identitetspronomen', 'Refleksivt pronomen', 'Personligt pronomen'], instruction: 'Ordklasser' },
    { id: 'da8-g29', type: 'Grammar', question: 'Bøj "at vide" i nutid:', answer: 'Ved', options: ['Ved', 'Vider', 'Vidst'], instruction: 'Verber' },
    { id: 'da8-g30', type: 'Grammar', question: 'Bøj "at vide" i datid:', answer: 'Vidste', options: ['Vidste', 'Ved', 'Vidt'], instruction: 'Verber' },
    { id: 'da8-g31', type: 'Grammar', question: 'Bøj "at vide" i førnutid:', answer: 'Har vidst', options: ['Har vidst', 'Vidste', 'Videt'], instruction: 'Verber' },
    { id: 'da8-g32', type: 'Grammar', question: 'Hvordan staves "arrangement"?', answer: 'Arrangement', options: ['Arrangement', 'Arangement', 'Arrangemang'], instruction: 'Stavning' },
    { id: 'da8-g33', type: 'Grammar', question: 'Hvordan staves "institution"?', answer: 'Institution', options: ['Institution', 'Instittution', 'Institusion'], instruction: 'Stavning' },
    { id: 'da8-g34', type: 'Grammar', question: 'Hvad er et "homonym"?', answer: 'Ord der staves ens, men betyder noget forskelligt', options: ['Ord der staves ens, men betyder noget forskelligt', 'Ord der betyder det samme', 'Ord der betyder det modsatte'], instruction: 'Begreber' },
    { id: 'da8-g35', type: 'Grammar', question: 'Find et homonym til "fyr":', answer: 'Et træ, en mand eller en lygte', options: ['Et træ, en mand eller en lygte', 'En bil', 'En fugl'], instruction: 'Homonymer' },
    { id: 'da8-g36', type: 'Grammar', question: 'Hvad er ordklassen for "endnu"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Præposition', 'Konjunktion'], instruction: 'Ordklasser' },
    { id: 'da8-g37', type: 'Grammar', question: 'Hvad er ordklassen for "for"?', answer: 'Præposition eller konjunktion', options: ['Præposition eller konjunktion', 'Adjektiv', 'Pronomen'], instruction: 'Ordklasser' },
    { id: 'da8-g38', type: 'Grammar', question: 'Find bindeordet i: "Vi går, for vi er trætte"', answer: 'for', options: ['for', 'går', 'trætte'], instruction: 'Ordklasser' },
    { id: 'da8-g39', type: 'Grammar', question: 'Find forholdsordet i: "Dette er til dig"', answer: 'til', options: ['til', 'dette', 'dig'], instruction: 'Ordklasser' },
    { id: 'da8-g40', type: 'Grammar', question: 'Find genstandsleddet: "Hun lærte ham at læse"', answer: 'at læse', options: ['at læse', 'ham', 'Hun'], instruction: 'Sætningsanalyse' },
    { id: 'da8-g41', type: 'Grammar', question: 'Find hensynsleddet: "Hun lærte ham at læse"', answer: 'ham', options: ['ham', 'at læse', 'Hun'], instruction: 'Sætningsanalyse' },
    { id: 'da8-g42', type: 'Grammar', question: 'Hvordan staves "diskussion"?', answer: 'Diskussion', options: ['Diskussion', 'Diskusion', 'Disekussion'], instruction: 'Stavning' },
    { id: 'da8-g43', type: 'Grammar', question: 'Hvordan staves "eksisterer"?', answer: 'Eksisterer', options: ['Eksisterer', 'Existerer', 'Eksistere'], instruction: 'Stavning' },
    { id: 'da8-g44', type: 'Grammar', question: 'Hvad er infinitiv af "løber"?', answer: 'At løbe', options: ['At løbe', 'Løb', 'Løbet'], instruction: 'Infinitiv' },
    { id: 'da8-g45', type: 'Grammar', question: 'Hvad er perfektum participium af "løber"?', answer: 'Løbet', options: ['Løbet', 'Løbe', 'Løber'], instruction: 'Participium' },
    { id: 'da8-g46', type: 'Grammar', question: 'Hvad er præsens participium af "løber"?', answer: 'Løbende', options: ['Løbende', 'Løber', 'Løb'], instruction: 'Participium' },
    { id: 'da8-g47', type: 'Grammar', question: 'Hvad er imperativ af "løber"?', answer: 'Løb!', options: ['Løb!', 'Løbe', 'Løber'], instruction: 'Imperativ' },
    { id: 'da8-g48', type: 'Grammar', question: 'Find det personlige pronomen i objektform:', answer: 'Mig', options: ['Mig', 'Jeg', 'Min'], instruction: 'Ordklasser' },
    { id: 'da8-g49', type: 'Grammar', question: 'Find det possessive pronomen:', answer: 'Vores', options: ['Vores', 'Vi', 'Os'], instruction: 'Ordklasser' },
    { id: 'da8-g50', type: 'Grammar', question: 'Find det demonstrative pronomen:', answer: 'Disse', options: ['Disse', 'De', 'Dem'], instruction: 'Ordklasser' },
    { id: 'da8-g51', type: 'Grammar', question: 'Næsten ___ .', answer: 'færdig', options: ['færdig', 'væk', 'her'], instruction: 'Besked' },
  ],
  9: [
    { id: 'da9-g1', type: 'Grammar', question: 'Hvad er syntaks?', answer: 'Læren om sætningsopbygning', options: ['Læren om sætningsopbygning', 'Læren om ords bøjning', 'Læren om ords betydning'], instruction: 'Begreber' },
    { id: 'da9-g2', type: 'Grammar', question: 'Hvad er morfologi?', answer: 'Læren om ords form og opbygning', options: ['Læren om ords form og opbygning', 'Læren om udtale', 'Læren om tegnsætning'], instruction: 'Begreber' },
    { id: 'da9-g3', type: 'Grammar', question: 'Hvad er semantik?', answer: 'Læren om ords betydning', options: ['Læren om ords betydning', 'Læren om lydene i sproget', 'Læren om bøjning'], instruction: 'Begreber' },
    { id: 'da9-g4', type: 'Grammar', question: 'Find prædikatsleddet (omsagnsled til grundled) i: "Han blev valgt som formand"', answer: 'valgt som formand', options: ['valgt som formand', 'Han', 'blev'], instruction: 'Sætningsanalyse' },
    { id: 'da9-g5', type: 'Grammar', question: 'Find adverbialleddet i: "Han gjorde det med vilje"', answer: 'med vilje', options: ['med vilje', 'gjorde', 'det'], instruction: 'Sætningsanalyse' },
    { id: 'da9-g6', type: 'Grammar', question: 'Hvad er diatesen i: "Æblet spises"?', answer: 'Passiv (s-passiv)', options: ['Passiv (s-passiv)', 'Aktiv', 'Perifrastisk passiv'], instruction: 'Diatese' },
    { id: 'da9-g7', type: 'Grammar', question: 'Hvad er diatesen i: "Æblet bliver spist"?', answer: 'Perifrastisk passiv (blive-passiv)', options: ['Perifrastisk passiv (blive-passiv)', 's-passiv', 'Aktiv'], instruction: 'Diatese' },
    { id: 'da9-g8', type: 'Grammar', question: 'Hvad kaldes "at" i: "Vi ved, at han kommer"?', answer: 'Underordningskonjunktion', options: ['Underordningskonjunktion', 'Sideordningskonjunktion', 'Præposition'], instruction: 'Ordklasser' },
    { id: 'da9-g9', type: 'Grammar', question: 'Hvad kaldes "men" i: "Jeg vil, men jeg kan ikke"?', answer: 'Sideordningskonjunktion', options: ['Sideordningskonjunktion', 'Underordningskonjunktion', 'Adverbium'], instruction: 'Ordklasser' },
    { id: 'da9-g10', type: 'Grammar', question: 'HVad er ordklassen for "selv" i: "Han gjorde det selv"?', answer: 'Identitetspronomen (eller adverbialt)', options: ['Identitetspronomen', 'Refleksivt pronomen', 'Relativt pronomen'], instruction: 'Ordklasser' },
    { id: 'da9-g11', type: 'Grammar', question: 'Find det refleksive pronomen i: "Han vasker sig"', answer: 'sig', options: ['sig', 'Han', 'vasker'], instruction: 'Ordklasser' },
    { id: 'da9-g12', type: 'Grammar', question: 'Find det reciproke pronomen i: "De elsker hinanden"', answer: 'hinanden', options: ['hinanden', 'De', 'elsker'], instruction: 'Ordklasser' },
    { id: 'da9-g13', type: 'Grammar', question: 'Bøj "at turde" i nutid:', answer: 'Tør', options: ['Tør', 'Turde', 'Turdre'], instruction: 'Uregelmæssige verber' },
    { id: 'da9-g14', type: 'Grammar', question: 'Bøj "at turde" i datid:', answer: 'Turde', options: ['Turde', 'Tør', 'Turdet'], instruction: 'Uregelmæssige verber' },
    { id: 'da9-g15', type: 'Grammar', question: 'Bøj "at turde" i førnutid:', answer: 'Har turdet', options: ['Har turdet', 'Turde', 'Tør'], instruction: 'Uregelmæssige verber' },
    { id: 'da9-g16', type: 'Grammar', question: 'Hvad er bøjningen af "at kunne" i nutid?', answer: 'Kan', options: ['Kan', 'Kunne', 'Kunder'], instruction: 'Modalverber' },
    { id: 'da9-g17', type: 'Grammar', question: 'Hvad er bøjningen af "at skulle" i nutid?', answer: 'Skal', options: ['Skal', 'Skulle', 'Skulder'], instruction: 'Modalverber' },
    { id: 'da9-g18', type: 'Grammar', question: 'Hvad er bøjningen af "at ville" i nutid?', answer: 'Vil', options: ['Vil', 'Ville', 'Vilder'], instruction: 'Modalverber' },
    { id: 'da9-g19', type: 'Grammar', question: 'Hvad er bøjningen af "at måtte" i nutid?', answer: 'Må', options: ['Må', 'Måtte', 'Måtter'], instruction: 'Modalverber' },
    { id: 'da9-g20', type: 'Grammar', question: 'Hvad er bøjningen af "at burde" i nutid?', answer: 'Bør', options: ['Bør', 'Burde', 'Burder'], instruction: 'Modalverber' },
    { id: 'da9-g21', type: 'Grammar', question: 'Find præpositionsforbindelsen i: "Vi mødtes efter skole"', answer: 'efter skole', options: ['efter skole', 'mødtes', 'Vi'], instruction: 'Sætningsanalyse' },
    { id: 'da9-g22', type: 'Grammar', question: 'Hvordan staves "bevidsthed"?', answer: 'Bevidsthed', options: ['Bevidsthed', 'Bevisthed', 'Bevidsted'], instruction: 'Stavning' },
    { id: 'da9-g23', type: 'Grammar', question: 'Hvordan staves "karriere"?', answer: 'Karriere', options: ['Karriere', 'Kariere', 'Karrere'], instruction: 'Stavning' },
    { id: 'da9-g24', type: 'Grammar', question: 'Hvordan staves "miljø"?', answer: 'Miljø', options: ['Miljø', 'Milljø', 'Miljøe'], instruction: 'Stavning' },
    { id: 'da9-g25', type: 'Grammar', question: 'Find fejlen: "Han er mere klog end mig"', answer: 'mere klog (skal være klogere)', options: ['mere klog', 'end', 'mig'], instruction: 'Gradbøjning' },
    { id: 'da9-g26', type: 'Grammar', question: 'Find fejlen: "Grundet regnen blev vi inde"', answer: 'Grundet (skal være På grund af)', options: ['Grundet', 'regnen', 'blev'], instruction: 'Præcision' },
    { id: 'da9-g27', type: 'Grammar', question: 'Hvad er "at" i: "Det er vigtigt at sove"?', answer: 'Navnemærke', options: ['Navnemærke', 'Konjunktion', 'Præposition'], instruction: 'Ordklasser' },
    { id: 'da9-g28', type: 'Grammar', question: 'Find det relative pronomen: "Pigen, __ jeg mødte"', answer: 'som (eller som jeg mødte)', options: ['som', 'der', 'hvem'], instruction: 'Ordklasser' },
    { id: 'da9-g29', type: 'Grammar', question: 'Find det relative pronomen: "Det, __ skete, var mærkeligt"', answer: 'der (eller som)', options: ['der', 'hvem', 'hvis'], instruction: 'Ordklasser' },
    { id: 'da9-g30', type: 'Grammar', question: 'Hvad er "hvem" i: "Jeg ved ikke, hvem han er"?', answer: 'Relativt pronomen (eller interrogativt afhængigt af analyse)', options: ['Relativt pronomen', 'Personligt pronomen', 'Ejestedord'], instruction: 'Ordklasser' },
    { id: 'da9-g31', type: 'Grammar', question: 'Find bindeordet: "Vi kom, skønt vi var trætte"', answer: 'skønt', options: ['skønt', 'kom', 'trætte'], instruction: 'Ordklasser' },
    { id: 'da9-g32', type: 'Grammar', question: 'Find bindeordet: "Vi venter, indtil de kommer"', answer: 'indtil', options: ['indtil', 'venter', 'kommer'], instruction: 'Ordklasser' },
    { id: 'da9-g33', type: 'Grammar', question: 'Hvad kaldes "og" i: "Du og jeg"?', answer: 'Konjunktion', options: ['Konjunktion', 'Adverbium', 'Præposition'], instruction: 'Ordklasser' },
    { id: 'da9-g34', type: 'Grammar', question: 'Hvad kaldes "foran" i: "Bilen står foran huset"?', answer: 'Præposition', options: ['Præposition', 'Adverbium', 'Konjunktion'], instruction: 'Ordklasser' },
    { id: 'da9-g35', type: 'Grammar', question: 'Find fejlen: "Han lagde sig på sengen"', answer: 'Ingen fejl (lagde vs lå)', options: ['Ingen fejl', 'lagde', 'sengen'], instruction: 'Fejlfinding' },
    { id: 'da9-g36', type: 'Grammar', question: 'Find fejlen: "Han liggede bogen på bordet"', answer: 'liggede (skal være lagde)', options: ['liggede', 'bogen', 'bordet'], instruction: 'Fejlfinding' },
    { id: 'da9-g37', type: 'Grammar', question: 'Hvad er forskellen på "ligge" og "lægge"?', answer: 'Ligge er statisk, lægge er en bevægelse', options: ['Ligge er statisk, lægge er en bevægelse', 'Der er ingen forskel', 'Ligge er fremtid, lægge er datid'], instruction: 'Begreber' },
    { id: 'da9-g38', type: 'Grammar', question: 'Hvad er forskellen på "nogen" og "nogle"?', answer: 'Nogen er ental/negativ, nogle er flertal/positiv', options: ['Nogen er ental/negativ, nogle er flertal/positiv', 'Nogen er flertal, nogle er ental', 'Der er ingen forskel'], instruction: 'Begreber' },
    { id: 'da9-g39', type: 'Grammar', question: 'Find det rigtige: "Jeg har ___ spørgsmål"', answer: 'nogle', options: ['nogle', 'nogen'], instruction: 'Mængde' },
    { id: 'da9-g40', type: 'Grammar', question: 'Find det rigtige: "Har du ___ penge?"', answer: 'nogen', options: ['nogen', 'nogle'], instruction: 'Mængde' },
    { id: 'da9-g41', type: 'Grammar', question: 'Hvad er ordklassen for "forhåbentlig"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Adjektiv', 'Verbum'], instruction: 'Ordklasser' },
    { id: 'da9-g42', type: 'Grammar', question: 'Hvad er "op" i: "Stå op"?', answer: 'Adverbium (biord)', options: ['Adverbium (biord)', 'Præposition', 'Konjunktion'], instruction: 'Ordklasser' },
    { id: 'da9-g43', type: 'Grammar', question: 'Find grundleddet: "At svømme i havet er forfriskende"', answer: 'At svømme i havet', options: ['At svømme i havet', 'er', 'forfriskende'], instruction: 'Sætningsanalyse' },
    { id: 'da9-g44', type: 'Grammar', question: 'Find prædikatsleddet: "De blev rige"', answer: 'rige', options: ['rige', 'De', 'blev'], instruction: 'Sætningsanalyse' },
    { id: 'da9-g45', type: 'Grammar', question: 'Find det egentlige subjekt: "Der mangler mad"', answer: 'mad', options: ['mad', 'Der', 'mangler'], instruction: 'Sætningsanalyse' },
    { id: 'da9-g46', type: 'Grammar', question: 'Hvordan staves "psykologi"?', answer: 'Psykologi', options: ['Psykologi', 'Psykologi', 'Sykologi'], instruction: 'Stavning' },
    { id: 'da9-g47', type: 'Grammar', question: 'Hvordan staves "æstetik"?', answer: 'Æstetik', options: ['Æstetik', 'Estetik', 'Æstettik'], instruction: 'Stavning' },
    { id: 'da9-g48', type: 'Grammar', question: 'Hvilken tid er: "De har lige fået det gjort"?', answer: 'Førnutid', options: ['Førnutid', 'Nutid', 'Datid'], instruction: 'Verbaltid' },
    { id: 'da9-g49', type: 'Grammar', question: 'Hvad er ordklassen for "end"?', answer: 'Konjunktion (bindeord)', options: ['Konjunktion', 'Adjektiv', 'Adverbium'], instruction: 'Ordklasser' },
    { id: 'da9-g50', type: 'Grammar', question: 'Hvad er ordklassen for "ligeså"?', answer: 'Adverbium (biord)', options: ['Adverbium', 'Konjunktion', 'Præposition'], instruction: 'Ordklasser' },
    { id: 'da9-g51', type: 'Grammar', question: 'Du er i ___.', answer: 'mål', options: ['mål', 'væk', 'her'], instruction: 'Besked' },
  ],
  10: [
    { id: 'da10-g1', type: 'Grammar', question: 'Hvad betyder "implicitte"?', answer: 'Underforstået', options: ['Underforstået', 'Tydelig', 'Vigtig'], instruction: 'Ordforråd' },
    { id: 'da10-g2', type: 'Grammar', question: 'Hvad betyder "eksplicitte"?', answer: 'Udtrykt direkte', options: ['Udtrykt direkte', 'Skjult', 'Lille'], instruction: 'Ordforråd' },
    { id: 'da10-g3', type: 'Grammar', question: 'Hvad betyder "paradoksalt"?', answer: 'Modstridende', options: ['Modstridende', 'Naturligt', 'Hurtigt'], instruction: 'Ordforråd' },
    { id: 'da10-g4', type: 'Grammar', question: 'Hvad betyder "konsolidere"?', answer: 'Styrke / Befæste', options: ['Styrke / Befæste', 'Svække', 'Fjerne'], instruction: 'Ordforråd' },
    { id: 'da10-g5', type: 'Grammar', question: 'Hvad betyder "innovativt"?', answer: 'Nyskabende', options: ['Nyskabende', 'Gammelt', 'Kedeligt'], instruction: 'Ordforråd' },
    { id: 'da10-g6', type: 'Grammar', question: 'Find fejlen: "Han er i tvivl om, hvorvidt han må komme"', answer: 'Ingen fejl', options: ['Ingen fejl', 'hvorvidt', 'må'], instruction: 'Fejlfinding' },
    { id: 'da10-g7', type: 'Grammar', question: 'Find fejlen: "De to piger hjalp hinanden"', answer: 'Ingen fejl (reciprokt pronomen)', options: ['Ingen fejl', 'hinanden', 'hjalp'], instruction: 'Fejlfinding' },
    { id: 'da10-g8', type: 'Grammar', question: 'Hvad er "at" i: "Vi håber på at vinde"?', answer: 'Navnemærke', options: ['Navnemærke', 'Konjunktion', 'Præposition'], instruction: 'Ordklasser' },
    { id: 'da10-g9', type: 'Grammar', question: 'Angiv diatese: "Beslutningen blev truffet i går"', answer: 'Passiv', options: ['Passiv', 'Aktiv', 'Medium'], instruction: 'Diatese' },
    { id: 'da10-g10', type: 'Grammar', question: 'Find det logiske grundled: "Madpakken blev spist af hunden"', answer: 'hunden', options: ['hunden', 'Madpakken', 'blev spist'], instruction: 'Sætningsanalyse' },
    { id: 'da10-g11', type: 'Grammar', question: 'Find det formelle grundled: "Der er ingen vej udenom"', answer: 'Der', options: ['Der', 'ingen vej', 'udenom'], instruction: 'Sætningsanalyse' },
    { id: 'da10-g12', type: 'Grammar', question: 'Oversæt til latin: Hensynsled', answer: 'Dativ', options: ['Dativ', 'Akkusativ', 'Genitiv'], instruction: 'Latinske termer' },
    { id: 'da10-g13', type: 'Grammar', question: 'Oversæt til latin: Genstandsled', answer: 'Akkusativ', options: ['Akkusativ', 'Dativ', 'Nominativ'], instruction: 'Latinske termer' },
    { id: 'da10-g14', type: 'Grammar', question: 'Oversæt til latin: Grundled', answer: 'Nominativ', options: ['Nominativ', 'Akkusativ', 'Dativ'], instruction: 'Latinske termer' },
    { id: 'da10-g15', type: 'Grammar', question: 'Hvilken tid er: "De ville have gjort det, hvis..."?', answer: 'Førdatid (konditionalis)', options: ['Førdatid', 'Datid', 'Nutid'], instruction: 'Verber' },
    { id: 'da10-g16', type: 'Grammar', question: 'Hvad kaldes "ih!"?', answer: 'Interjektion (udråbsord)', options: ['Interjektion', 'Konjunktion', 'Pronomen'], instruction: 'Ordklasser' },
    { id: 'da10-g17', type: 'Grammar', question: 'Hvad kaldes "og", "men", "eller"?', answer: 'Sideordningskonjunktioner', options: ['Sideordningskonjunktioner', 'Underordningskonjunktioner', 'Præpositioner'], instruction: 'Ordklasser' },
    { id: 'da10-g18', type: 'Grammar', question: 'Hvad kaldes "da", "fordi", "hvis"?', answer: 'Underordningskonjunktioner', options: ['Underordningskonjunktioner', 'Sideordningskonjunktioner', 'Adverbier'], instruction: 'Ordklasser' },
    { id: 'da10-g19', type: 'Grammar', question: 'Statisk eller bevægelse? "Hæng billedet op!"', answer: 'Bevægelse (lægge-type)', options: ['Bevægelse', 'Statisk'], instruction: 'Verber' },
    { id: 'da10-g20', type: 'Grammar', question: 'Statisk eller bevægelse? "Billedet hænger på væggen"', answer: 'Statisk (ligge-type)', options: ['Statisk', 'Bevægelse'], instruction: 'Verber' },
    { id: 'da10-g21', type: 'Grammar', question: 'Bøj "at få" i datid:', answer: 'Fik', options: ['Fik', 'Fåede', 'Fået'], instruction: 'Verber' },
    { id: 'da10-g22', type: 'Grammar', question: 'Bøj "at bære" i datid:', answer: 'Bar', options: ['Bar', 'Bærerede', 'Båret'], instruction: 'Verber' },
    { id: 'da10-g23', type: 'Grammar', question: 'Bøj "at trække" i datid:', answer: 'Trak', options: ['Trak', 'Trækkede', 'Trukket'], instruction: 'Verber' },
    { id: 'da10-g24', type: 'Grammar', question: 'Bøj "at flyve" i datid:', answer: 'Fløj', options: ['Fløj', 'Flyvede', 'Fløjet'], instruction: 'Verber' },
    { id: 'da10-g25', type: 'Grammar', question: 'Hvad betyder "at dechifrere"?', answer: 'At afkode / Tyde', options: ['At afkode / Tyde', 'At skrive', 'At glemme'], instruction: 'Ordforråd' },
    { id: 'da10-g26', type: 'Grammar', question: 'Hvad betyder "at revidere"?', answer: 'At gennemgå / Ændre', options: ['At gennemgå / Ændre', 'At slette', 'At gemme'], instruction: 'Ordforråd' },
    { id: 'da10-g27', type: 'Grammar', question: 'Hvad betyder "at implementere"?', answer: 'At indføre / Iværksætte', options: ['At indføre / Iværksætte', 'At fjerne', 'At se'], instruction: 'Ordforråd' },
    { id: 'da10-g28', type: 'Grammar', question: 'Hvordan staves "chauffør"?', answer: 'Chauffør', options: ['Chauffør', 'Shauffør', 'Chaufør'], instruction: 'Stavning' },
    { id: 'da10-g29', type: 'Grammar', question: 'Hvordan staves "nysgerrig"?', answer: 'Nysgerrig', options: ['Nysgerrig', 'Nysgerig', 'Nyskerrig'], instruction: 'Stavning' },
    { id: 'da10-g30', type: 'Grammar', question: 'Hvordan staves "overraskelse"?', answer: 'Overraskelse', options: ['Overraskelse', 'Overaskelse', 'Overraskelse'], instruction: 'Stavning' },
    { id: 'da10-g31', type: 'Grammar', question: 'Find adverbialleddet i: "Han kommer måske senere"', answer: 'måske, senere', options: ['måske, senere', 'Han', 'kommer'], instruction: 'Sætningsanalyse' },
    { id: 'da10-g32', type: 'Grammar', question: 'Find omsagnsleddet i: "Filmen var god"', answer: 'god', options: ['god', 'Filmen', 'var'], instruction: 'Sætningsanalyse' },
    { id: 'da10-g33', type: 'Grammar', question: 'Er "der" et relativt pronomen i: "Manden, der bor der"?', answer: 'Det første "der"', options: ['Det første "der"', 'Det sidste "der"', 'Begge'], instruction: 'Ordklasser' },
    { id: 'da10-g34', type: 'Grammar', question: 'Er "som" et relativt pronomen i: "Han er som sin far"?', answer: 'Nej (her præposition/adverbium)', options: ['Nej', 'Ja'], instruction: 'Ordklasser' },
    { id: 'da10-g35', type: 'Grammar', question: 'Find det reciproke pronomen:', answer: 'Hinanden', options: ['Hinanden', 'Sig', 'Dem'], instruction: 'Ordklasser' },
    { id: 'da10-g36', type: 'Grammar', question: 'Find det refleksive pronomen:', answer: 'Sig', options: ['Sig', 'Han', 'Ham'], instruction: 'Ordklasser' },
    { id: 'da10-g37', type: 'Grammar', question: 'Hvad betyder "at pointere"?', answer: 'At fremhæve', options: ['At fremhæve', 'At tegne', 'At glemme'], instruction: 'Ordforråd' },
    { id: 'da10-g38', type: 'Grammar', question: 'Hvad betyder "at reflektere"?', answer: 'At overveje / Spejle', options: ['At overveje / Spejle', 'At løbe', 'At se'], instruction: 'Ordforråd' },
    { id: 'da10-g39', type: 'Grammar', question: 'Hvad betyder "at kvalificere"?', answer: 'At gøre duelig', options: ['At gøre duelig', 'At fjerne', 'At bære'], instruction: 'Ordforråd' },
    { id: 'da10-g40', type: 'Grammar', question: 'Find fejlen: "De har lige spist"', answer: 'Ingen fejl', options: ['Ingen fejl', 'spist', 'lige'], instruction: 'Fejlfinding' },
    { id: 'da10-g41', type: 'Grammar', question: 'Find fejlen: "Vi skal ha\' kage"', answer: "ha' (skal være have)", options: ["ha'", 'kage', 'skal'], instruction: 'Fejlfinding' },
    { id: 'da10-g42', type: 'Grammar', question: 'Hvilken ordklasse er "hvis" i: "Hvis det regner, bliver vi inde"?', answer: 'Konjunktion', options: ['Konjunktion', 'Pronomen', 'Adverbium'], instruction: 'Ordklasser' },
    { id: 'da10-g43', type: 'Grammar', question: 'Hvilken ordklasse er "hvis" i: "Manden, hvis hund bed mig"?', answer: 'Relativt pronomen', options: ['Relativt pronomen', 'Konjunktion', 'Adjektiv'], instruction: 'Ordklasser' },
    { id: 'da10-g44', type: 'Grammar', question: 'Hvad betyder "urbanisering"?', answer: 'Byudvikling / Flytte til byen', options: ['Byudvikling / Flytte til byen', 'Skovdrift', 'Landbrug'], instruction: 'Ordforråd' },
    { id: 'da10-g45', type: 'Grammar', question: 'Hvad betyder "demokrati"?', answer: 'Folkestyre', options: ['Folkestyre', 'Enevælde', 'Kaos'], instruction: 'Ordforråd' },
    { id: 'da10-g46', type: 'Grammar', question: 'Hvad betyder "dilemma"?', answer: 'Valg mellem to svære ting', options: ['Valg mellem to svære ting', 'Løsning', 'Problem'], instruction: 'Ordforråd' },
    { id: 'da10-g47', type: 'Grammar', question: 'Hvad betyder "integritet"?', answer: 'Selvstændighed / Ukrænkelighed', options: ['Selvstændighed / Ukrænkelighed', 'Venlighed', 'Viden'], instruction: 'Ordforråd' },
    { id: 'da10-g48', type: 'Grammar', question: 'Hvad betyder "tolerance"?', answer: 'Udholdenhed / Overbærenhed', options: ['Udholdenhed / Overbærenhed', 'Had', 'Uvidenhed'], instruction: 'Ordforråd' },
    { id: 'da10-g49', type: 'Grammar', question: 'Hvad betyder "solidaritet"?', answer: 'Sammenhold', options: ['Sammenhold', 'Egoisme', 'Frihed'], instruction: 'Ordforråd' },
    { id: 'da10-g50', type: 'Grammar', question: 'Hvad betyder "etisk"?', answer: 'Moralsk rigtigt', options: ['Moralsk rigtigt', 'Ulovligt', 'Hurtigt'], instruction: 'Ordforråd' },
    { id: 'da10-g51', type: 'Grammar', question: 'Du er en ___!', answer: 'mester', options: ['mester', 'begynder', 'elev'], instruction: 'Besked' },
  ],
};
