/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const ENGELSK_GRAMMAR_P1: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'en0-g1', type: 'Grammar', question: 'Which word is a color?', answer: 'Red', options: ['Red', 'Dog', 'Run'], instruction: 'Vocabulary' },
    { id: 'en0-g2', type: 'Grammar', question: 'Which word is an animal?', answer: 'Cat', options: ['Cat', 'Blue', 'Jump'], instruction: 'Vocabulary' },
    { id: 'en0-g3', type: 'Grammar', question: 'Which word is a number?', answer: 'One', options: ['One', 'Apple', 'Green'], instruction: 'Vocabulary' },
    { id: 'en0-g4', type: 'Grammar', question: 'What is the opposite of "Big"?', answer: 'Small', options: ['Small', 'Tall', 'Hot'], instruction: 'Opposites' },
    { id: 'en0-g5', type: 'Grammar', question: 'What is the opposite of "Happy"?', answer: 'Sad', options: ['Sad', 'Angry', 'Glad'], instruction: 'Opposites' },
    { id: 'en0-g6', type: 'Grammar', question: 'Which letter comes after A?', answer: 'B', options: ['B', 'C', 'D'], instruction: 'Alphabet' },
    { id: 'en0-g7', type: 'Grammar', question: 'Which letter comes before Z?', answer: 'Y', options: ['Y', 'X', 'W'], instruction: 'Alphabet' },
    { id: 'en0-g8', type: 'Grammar', question: 'Which word rimes with "Hat"?', answer: 'Cat', options: ['Cat', 'Dog', 'Pig'], instruction: 'Rhymes' },
    { id: 'en0-g9', type: 'Grammar', question: 'Which word rimes with "Sun"?', answer: 'Run', options: ['Run', 'Sky', 'Moon'], instruction: 'Rhymes' },
    { id: 'en0-g10', type: 'Grammar', question: 'Is "Apple" a fruit?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Vocabulary' },
    { id: 'en0-g11', type: 'Grammar', question: 'Is "Cow" a bird?', answer: 'No', options: ['Yes', 'No'], instruction: 'Vocabulary' },
    { id: 'en0-g12', type: 'Grammar', question: 'Complete: One, Two, ___', answer: 'Three', options: ['Three', 'Four', 'Five'], instruction: 'Counting' },
    { id: 'en0-g13', type: 'Grammar', question: 'Complete: Monday, Tuesday, ___', answer: 'Wednesday', options: ['Wednesday', 'Thursday', 'Friday'], instruction: 'Days' },
    { id: 'en0-g14', type: 'Grammar', question: 'Is a ball "Round" or "Square"?', answer: 'Round', options: ['Round', 'Square'], instruction: 'Shapes' },
    { id: 'en0-g15', type: 'Grammar', question: 'Which one is "Cold"?', answer: 'Ice', options: ['Ice', 'Fire', 'Sun'], instruction: 'Vocabulary' },
    { id: 'en0-g16', type: 'Grammar', question: 'Which one is "Hot"?', answer: 'Sun', options: ['Sun', 'Ice', 'Rain'], instruction: 'Vocabulary' },
    { id: 'en0-g17', type: 'Grammar', question: 'Can a bird fly?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Nature' },
    { id: 'en0-g18', type: 'Grammar', question: 'Can a fish walk?', answer: 'No', options: ['Yes', 'No'], instruction: 'Nature' },
    { id: 'en0-g19', type: 'Grammar', question: 'Find the capital letter:', answer: 'A', options: ['A', 'b', 'c'], instruction: 'Letters' },
    { id: 'en0-g20', type: 'Grammar', question: 'Find the small letter:', answer: 'e', options: ['E', 'e'], instruction: 'Letters' },
    { id: 'en0-g21', type: 'Grammar', question: 'How many fingers on one hand?', answer: 'Five', options: ['Five', 'Ten', 'Two'], instruction: 'Counting' },
    { id: 'en0-g22', type: 'Grammar', question: 'What color is the sky?', answer: 'Blue', options: ['Blue', 'Green', 'Yellow'], instruction: 'Nature' },
    { id: 'en0-g23', type: 'Grammar', question: 'What color is grass?', answer: 'Green', options: ['Green', 'Red', 'Blue'], instruction: 'Nature' },
    { id: 'en0-g24', type: 'Grammar', question: 'Is a mouse big or small?', answer: 'Small', options: ['Small', 'Big'], instruction: 'Comparison' },
    { id: 'en0-g25', type: 'Grammar', question: 'Is an elephant big or small?', answer: 'Big', options: ['Big', 'Small'], instruction: 'Comparison' },
    { id: 'en0-g26', type: 'Grammar', question: 'Which word starts with "B"?', answer: 'Ball', options: ['Ball', 'Apple', 'Cat'], instruction: 'First letter' },
    { id: 'en0-g27', type: 'Grammar', question: 'Which word starts with "S"?', answer: 'Sun', options: ['Sun', 'Moon', 'Star'], instruction: 'First letter' },
    { id: 'en0-g28', type: 'Grammar', question: 'What sound does a cat make?', answer: 'Meow', options: ['Meow', 'Woof', 'Moo'], instruction: 'Sounds' },
    { id: 'en0-g29', type: 'Grammar', question: 'What sound does a dog make?', answer: 'Woof', options: ['Woof', 'Meow', 'Moo'], instruction: 'Sounds' },
    { id: 'en0-g30', type: 'Grammar', question: 'How many legs does a dog have?', answer: 'Four', options: ['Four', 'Two', 'Six'], instruction: 'Counting' },
    { id: 'en0-g31', type: 'Grammar', question: 'Is a banana yellow?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Colors' },
    { id: 'en0-g32', type: 'Grammar', question: 'Is a tomato blue?', answer: 'No', options: ['Yes', 'No'], instruction: 'Colors' },
    { id: 'en0-g33', type: 'Grammar', question: 'Which word is a "Thing"?', answer: 'Book', options: ['Book', 'Run', 'Fast'], instruction: 'Nouns' },
    { id: 'en0-g34', type: 'Grammar', question: 'Which word is an "Action"?', answer: 'Jump', options: ['Jump', 'Table', 'Red'], instruction: 'Verbs' },
    { id: 'en0-g35', type: 'Grammar', question: 'Find the letter O:', answer: 'O', options: ['O', 'Q', 'C'], instruction: 'Alphabet' },
    { id: 'en0-g36', type: 'Grammar', question: 'Find the letter M:', answer: 'M', options: ['M', 'N', 'W'], instruction: 'Alphabet' },
    { id: 'en0-g37', type: 'Grammar', question: 'What is the opposite of "Up"?', answer: 'Down', options: ['Down', 'Left', 'Right'], instruction: 'Opposites' },
    { id: 'en0-g38', type: 'Grammar', question: 'What is the opposite of "Day"?', answer: 'Night', options: ['Night', 'Evening', 'Morning'], instruction: 'Opposites' },
    { id: 'en0-g39', type: 'Grammar', question: 'Which word is "Funny"?', answer: 'Clown', options: ['Clown', 'Rock', 'Sad'], instruction: 'Vocabulary' },
    { id: 'en0-g40', type: 'Grammar', question: 'Is the ocean wet or dry?', answer: 'Wet', options: ['Wet', 'Dry'], instruction: 'Properties' },
    { id: 'en0-g41', type: 'Grammar', question: 'Is fire hot or cold?', answer: 'Hot', options: ['Hot', 'Cold'], instruction: 'Properties' },
    { id: 'en0-g42', type: 'Grammar', question: 'Find the word with 3 letters:', answer: 'Cat', options: ['Cat', 'Fish', 'Bird'], instruction: 'Counting letters' },
    { id: 'en0-g43', type: 'Grammar', question: 'Find the word with 4 letters:', answer: 'Fish', options: ['Fish', 'Cat', 'Bee'], instruction: 'Counting letters' },
    { id: 'en0-g44', type: 'Grammar', question: 'Is a bee small?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Size' },
    { id: 'en0-g45', type: 'Grammar', question: 'Which word means "Hi"?', answer: 'Hello', options: ['Hello', 'Bye', 'No'], instruction: 'Greetings' },
    { id: 'en0-g46', type: 'Grammar', question: 'Which word means "Goodbye"?', answer: 'Bye', options: ['Bye', 'Hi', 'Yes'], instruction: 'Greetings' },
    { id: 'en0-g47', type: 'Grammar', question: 'Can you eat a stone?', answer: 'No', options: ['Yes', 'No'], instruction: 'Logic' },
    { id: 'en0-g48', type: 'Grammar', question: 'Can you drink juice?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Logic' },
    { id: 'en0-g49', type: 'Grammar', question: 'Is a lion a pet?', answer: 'No', options: ['Yes', 'No'], instruction: 'Animals' },
    { id: 'en0-g50', type: 'Grammar', question: 'Is a dog a pet?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Animals' },
    { id: 'en0-g51', type: 'Grammar', question: 'Good ___.', answer: 'job', options: ['job', 'bad', 'car'], instruction: 'Feedback' },
  ],
  1: [
    { id: 'en1-g1', type: 'Grammar', question: 'Is it "a" or "an" apple?', answer: 'an', options: ['a', 'an'], instruction: 'Articles' },
    { id: 'en1-g2', type: 'Grammar', question: 'Is it "a" or "an" ball?', answer: 'a', options: ['a', 'an'], instruction: 'Articles' },
    { id: 'en1-g3', type: 'Grammar', question: '"I ___ happy."', answer: 'am', options: ['am', 'is', 'are'], instruction: 'To be' },
    { id: 'en1-g4', type: 'Grammar', question: '"You ___ happy."', answer: 'are', options: ['am', 'is', 'are'], instruction: 'To be' },
    { id: 'en1-g5', type: 'Grammar', question: '"He ___ happy."', answer: 'is', options: ['am', 'is', 'are'], instruction: 'To be' },
    { id: 'en1-g6', type: 'Grammar', question: 'Plural of "Cat":', answer: 'Cats', options: ['Cats', 'Cates', 'Cat'], instruction: 'Plurals' },
    { id: 'en1-g7', type: 'Grammar', question: 'Plural of "Dog":', answer: 'Dogs', options: ['Dogs', 'Doges', 'Dog'], instruction: 'Plurals' },
    { id: 'en1-g8', type: 'Grammar', question: 'What is the "Past" of "Play"?', answer: 'Played', options: ['Played', 'Plays', 'Play'], instruction: 'Verbs' },
    { id: 'en1-g9', type: 'Grammar', question: 'What is the "Past" of "Walk"?', answer: 'Walked', options: ['Walked', 'Walks', 'Walk'], instruction: 'Verbs' },
    { id: 'en1-g10', type: 'Grammar', question: 'Which one is a "Noun" (thing)?', answer: 'Table', options: ['Table', 'Run', 'Slow'], instruction: 'Word classes' },
    { id: 'en1-g11', type: 'Grammar', question: 'Which one is a "Verb" (action)?', answer: 'Run', options: ['Run', 'Table', 'Big'], instruction: 'Word classes' },
    { id: 'en1-g12', type: 'Grammar', question: 'Which one is an "Adjective"?', answer: 'Beautiful', options: ['Beautiful', 'Phone', 'Talk'], instruction: 'Word classes' },
    { id: 'en1-g13', type: 'Grammar', question: 'Is "The" an article?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Grammar terms' },
    { id: 'en1-g14', type: 'Grammar', question: 'Change to plural: Boy', answer: 'Boys', options: ['Boys', 'Boyes', 'Boies'], instruction: 'Plurals' },
    { id: 'en1-g15', type: 'Grammar', question: 'Change to plural: Girl', answer: 'Girls', options: ['Girls', 'Girles', 'Girlys'], instruction: 'Plurals' },
    { id: 'en1-g16', type: 'Grammar', question: 'What follows "I"?', answer: 'am', options: ['am', 'is', 'are'], instruction: 'Pronouns' },
    { id: 'en1-g17', type: 'Grammar', question: 'What follows "They"?', answer: 'are', options: ['are', 'is', 'am'], instruction: 'Pronouns' },
    { id: 'en1-g18', type: 'Grammar', question: 'Correct order: "I like cake" or "Cake like I"?', answer: 'I like cake', options: ['I like cake', 'Cake like I'], instruction: 'Sentence structure' },
    { id: 'en1-g19', type: 'Grammar', question: 'Which is a "Pronoun"?', answer: 'He', options: ['He', 'Jump', 'Green'], instruction: 'Word classes' },
    { id: 'en1-g20', type: 'Grammar', question: 'Capitalize correctly: "i am here"', answer: 'I am here', options: ['I am here', 'i Am here', 'i am Here'], instruction: 'Capitalization' },
    { id: 'en1-g21', type: 'Grammar', question: 'Is "English" capitalized?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Proper nouns' },
    { id: 'en1-g22', type: 'Grammar', question: 'Find the verb: "She sleeps."', answer: 'sleeps', options: ['sleeps', 'She'], instruction: 'Word classes' },
    { id: 'en1-g23', type: 'Grammar', question: 'Find the noun: "The ball."', answer: 'ball', options: ['ball', 'The'], instruction: 'Word classes' },
    { id: 'en1-g24', type: 'Grammar', question: 'Which word is "Small"?', answer: 'Ant', options: ['Ant', 'House', 'Tree'], instruction: 'Comparison' },
    { id: 'en1-g25', type: 'Grammar', question: 'Which word is "Fast"?', answer: 'Plane', options: ['Plane', 'Snail', 'Turtle'], instruction: 'Comparison' },
    { id: 'en1-g26', type: 'Grammar', question: 'What is 1 + 1 in English?', answer: 'Two', options: ['Two', 'One', 'Three'], instruction: 'Numbers' },
    { id: 'en1-g27', type: 'Grammar', question: 'What is 2 + 2 in English?', answer: 'Four', options: ['Four', 'Three', 'Five'], instruction: 'Numbers' },
    { id: 'en1-g28', type: 'Grammar', question: 'Which day is first?', answer: 'Monday', options: ['Monday', 'Sunday', 'Friday'], instruction: 'Days' },
    { id: 'en1-g29', type: 'Grammar', question: 'Which day is last in week?', answer: 'Sunday', options: ['Sunday', 'Monday', 'Saturday'], instruction: 'Days' },
    { id: 'en1-g30', type: 'Grammar', question: 'Is "Sun" or "Moon" seen at night?', answer: 'Moon', options: ['Moon', 'Sun'], instruction: 'Vocabulary' },
    { id: 'en1-g31', type: 'Grammar', question: 'Is "Fruit" for "Apple"?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Categorization' },
    { id: 'en1-g32', type: 'Grammar', question: 'Is "Veggie" for "Carrot"?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Categorization' },
    { id: 'en1-g33', type: 'Grammar', question: 'Opposite of "Hot":', answer: 'Cold', options: ['Cold', 'Warm', 'Dry'], instruction: 'Vocabulary' },
    { id: 'en1-g34', type: 'Grammar', question: 'Opposite of "Black":', answer: 'White', options: ['White', 'Grey', 'Red'], instruction: 'Vocabulary' },
    { id: 'en1-g35', type: 'Grammar', question: 'Plural of "Box":', answer: 'Boxes', options: ['Boxes', 'Boxs', 'Boxies'], instruction: 'Plurals' },
    { id: 'en1-g36', type: 'Grammar', question: 'Plural of "Bus":', answer: 'Buses', options: ['Buses', 'Buss', 'Busies'], instruction: 'Plurals' },
    { id: 'en1-g37', type: 'Grammar', question: 'Plural of "Child":', answer: 'Children', options: ['Children', 'Childs', 'Childes'], instruction: 'Irregular plurals' },
    { id: 'en1-g38', type: 'Grammar', question: 'Plural of "Foot":', answer: 'Feet', options: ['Feet', 'Foots', 'Footes'], instruction: 'Irregular plurals' },
    { id: 'en1-g39', type: 'Grammar', question: 'Correct: "a egg" or "an egg"?', answer: 'an egg', options: ['an egg', 'a egg'], instruction: 'Articles' },
    { id: 'en1-g40', type: 'Grammar', question: 'Correct: "a car" or "an car"?', answer: 'a car', options: ['a car', 'an car'], instruction: 'Articles' },
    { id: 'en1-g41', type: 'Grammar', question: 'Which starts with a vowel?', answer: 'Orange', options: ['Orange', 'Banana', 'Pear'], instruction: 'Phonics' },
    { id: 'en1-g42', type: 'Grammar', question: 'Which starts with a consonant?', answer: 'Cat', options: ['Cat', 'Apple', 'Ice'], instruction: 'Phonics' },
    { id: 'en1-g43', type: 'Grammar', question: 'Finish: A, B, C, ___', answer: 'D', options: ['D', 'E', 'F'], instruction: 'Alphabet' },
    { id: 'en1-g44', type: 'Grammar', question: 'Finish: X, Y, ___', answer: 'Z', options: ['Z', 'W', 'V'], instruction: 'Alphabet' },
    { id: 'en1-g45', type: 'Grammar', question: 'Is "Jump" a verb?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en1-g46', type: 'Grammar', question: 'Is "Red" a noun?', answer: 'No', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en1-g47', type: 'Grammar', question: 'Do you "eat" or "drink" water?', answer: 'drink', options: ['drink', 'eat'], instruction: 'Verbs' },
    { id: 'en1-g48', type: 'Grammar', question: 'Do you "eat" or "drink" bread?', answer: 'eat', options: ['eat', 'drink'], instruction: 'Verbs' },
    { id: 'en1-g49', type: 'Grammar', question: 'How do you say "Hello" in the morning?', answer: 'Good morning', options: ['Good morning', 'Good night', 'Good evening'], instruction: 'Greetings' },
    { id: 'en1-g50', type: 'Grammar', question: 'How do you say "Goodbye" at night?', answer: 'Good night', options: ['Good night', 'Good morning', 'Hello'], instruction: 'Greetings' },
    { id: 'en1-g51', type: 'Grammar', question: 'Great ___!', answer: 'job', options: ['job', 'bad', 'car'], instruction: 'Feedback' },
  ],
  2: [
    { id: 'en2-g1', type: 'Grammar', question: 'I ___ a student.', answer: 'am', options: ['am', 'is', 'are'], instruction: 'To be' },
    { id: 'en2-g2', type: 'Grammar', question: 'You ___ my friend.', answer: 'are', options: ['am', 'is', 'are'], instruction: 'To be' },
    { id: 'en2-g3', type: 'Grammar', question: 'He ___ very tall.', answer: 'is', options: ['am', 'is', 'are'], instruction: 'To be' },
    { id: 'en2-g4', type: 'Grammar', question: 'We ___ in the garden.', answer: 'are', options: ['am', 'is', 'are'], instruction: 'To be' },
    { id: 'en2-g5', type: 'Grammar', question: 'It ___ a beautiful day.', answer: 'is', options: ['am', 'is', 'are'], instruction: 'To be' },
    { id: 'en2-g6', type: 'Grammar', question: 'They ___ playing football.', answer: 'are', options: ['am', 'is', 'are'], instruction: 'To be' },
    { id: 'en2-g7', type: 'Grammar', question: 'I ___ my homework now.', answer: 'do', options: ['do', 'does', 'did'], instruction: 'Do/Does' },
    { id: 'en2-g8', type: 'Grammar', question: 'He ___ his homework now.', answer: 'does', options: ['do', 'does', 'did'], instruction: 'Do/Does' },
    { id: 'en2-g9', type: 'Grammar', question: '___ you like pizza?', answer: 'Do', options: ['Do', 'Does', 'Is'], instruction: 'Questions' },
    { id: 'en2-g10', type: 'Grammar', question: '___ she like apples?', answer: 'Does', options: ['Do', 'Does', 'Is'], instruction: 'Questions' },
    { id: 'en2-g11', type: 'Grammar', question: 'I ___ not like spiders.', answer: 'do', options: ['do', 'does', 'am'], instruction: 'Negatives' },
    { id: 'en2-g12', type: 'Grammar', question: 'He ___ not like spiders.', answer: 'does', options: ['do', 'does', 'is'], instruction: 'Negatives' },
    { id: 'en2-g13', type: 'Grammar', question: 'Plural of "Mouse":', answer: 'Mice', options: ['Mice', 'Mouses', 'Mices'], instruction: 'Irregular plural' },
    { id: 'en2-g14', type: 'Grammar', question: 'Plural of "Man":', answer: 'Men', options: ['Men', 'Mans', 'Manes'], instruction: 'Irregular plural' },
    { id: 'en2-g15', type: 'Grammar', question: 'Plural of "Woman":', answer: 'Women', options: ['Women', 'Womans', 'Womanes'], instruction: 'Irregular plural' },
    { id: 'en2-g16', type: 'Grammar', question: 'Plural of "Tooth":', answer: 'Teeth', options: ['Teeth', 'Tooths', 'Toothes'], instruction: 'Irregular plural' },
    { id: 'en2-g17', type: 'Grammar', question: 'The dog is ___ the table.', answer: 'under', options: ['under', 'sky', 'blue'], instruction: 'Prepositions' },
    { id: 'en2-g18', type: 'Grammar', question: 'The bird is ___ the tree.', answer: 'in', options: ['in', 'at', 'on'], instruction: 'Prepositions' },
    { id: 'en2-g19', type: 'Grammar', question: 'The computer is ___ the desk.', answer: 'on', options: ['on', 'in', 'at'], instruction: 'Prepositions' },
    { id: 'en2-g20', type: 'Grammar', question: 'I go ___ school.', answer: 'to', options: ['to', 'at', 'in'], instruction: 'Prepositions' },
    { id: 'en2-g21', type: 'Grammar', question: 'This is ___ book.', answer: 'my', options: ['my', 'mine', 'me'], instruction: 'Possessives' },
    { id: 'en2-g22', type: 'Grammar', question: 'That is ___ car (belonging to him).', answer: 'his', options: ['his', 'him', 'he'], instruction: 'Possessives' },
    { id: 'en2-g23', type: 'Grammar', question: 'That is ___ car (belonging to her).', answer: 'her', options: ['her', 'hers', 'she'], instruction: 'Possessives' },
    { id: 'en2-g24', type: 'Grammar', question: 'Whose bag is this? It is ___.', answer: 'mine', options: ['mine', 'my', 'me'], instruction: 'Possessives' },
    { id: 'en2-g25', type: 'Grammar', question: 'I ___ (play) yesterday.', answer: 'played', options: ['played', 'play', 'playing'], instruction: 'Past tense' },
    { id: 'en2-g26', type: 'Grammar', question: 'I ___ (watch) TV last night.', answer: 'watched', options: ['watched', 'watch', 'watching'], instruction: 'Past tense' },
    { id: 'en2-g27', type: 'Grammar', question: 'What is the past of "Go"?', answer: 'Went', options: ['Went', 'Goes', 'Gone'], instruction: 'Irregular past' },
    { id: 'en2-g28', type: 'Grammar', question: 'What is the past of "See"?', answer: 'Saw', options: ['Saw', 'Sees', 'Seen'], instruction: 'Irregular past' },
    { id: 'en2-g29', type: 'Grammar', question: 'What is the past of "Eat"?', answer: 'Ate', options: ['Ate', 'Eats', 'Eaten'], instruction: 'Irregular past' },
    { id: 'en2-g30', type: 'Grammar', question: 'Which one is a "Verb"?', answer: 'Dance', options: ['Dance', 'Shoe', 'Soft'], instruction: 'Word classes' },
    { id: 'en2-g31', type: 'Grammar', question: 'Which one is a "Noun"?', answer: 'Apple', options: ['Apple', 'Tasty', 'Pick'], instruction: 'Word classes' },
    { id: 'en2-g32', type: 'Grammar', question: 'Which one is an "Adjective"?', answer: 'Green', options: ['Green', 'Grass', 'Grow'], instruction: 'Word classes' },
    { id: 'en2-g33', type: 'Grammar', question: 'How many "vowels" are there in English?', answer: '5', options: ['5', '7', '21'], instruction: 'Phonics' },
    { id: 'en2-g34', type: 'Grammar', question: 'Name the vowels:', answer: 'A, E, I, O, U', options: ['A, E, I, O, U', 'B, C, D, F, G', 'X, Y, Z'], instruction: 'Phonics' },
    { id: 'en2-g35', type: 'Grammar', question: 'An ___ (apple).', answer: 'apple', options: ['apple', 'car', 'ball'], instruction: 'Articles' },
    { id: 'en2-g36', type: 'Grammar', question: 'A ___ (banana).', answer: 'banana', options: ['banana', 'orange', 'egg'], instruction: 'Articles' },
    { id: 'en2-g37', type: 'Grammar', question: 'Which is a plural word?', answer: 'Dogs', options: ['Dogs', 'Dog', 'One dog'], instruction: 'Plurals' },
    { id: 'en2-g38', type: 'Grammar', question: 'Which is a singular word?', answer: 'Cat', options: ['Cat', 'Cats', 'Two cats'], instruction: 'Singular' },
    { id: 'en2-g39', type: 'Grammar', question: 'Is "Always" an adverb?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en2-g40', type: 'Grammar', question: 'Is "Fast" an adjective?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en2-g41', type: 'Grammar', question: 'Identify the verb: "The cat runs."', answer: 'runs', options: ['runs', 'cat', 'The'], instruction: 'Word classes' },
    { id: 'en2-g42', type: 'Grammar', question: 'Identify the noun: "The cat runs."', answer: 'cat', options: ['cat', 'runs', 'The'], instruction: 'Word classes' },
    { id: 'en2-g43', type: 'Grammar', question: 'Identify the adjective: "The black cat runs."', answer: 'black', options: ['black', 'cat', 'runs'], instruction: 'Word classes' },
    { id: 'en2-g44', type: 'Grammar', question: 'Opposite of "Heavy":', answer: 'Light', options: ['Light', 'Hard', 'Big'], instruction: 'Vocabulary' },
    { id: 'en2-g45', type: 'Grammar', question: 'Opposite of "Old":', answer: 'Young', options: ['Young', 'Small', 'New'], instruction: 'Vocabulary' },
    { id: 'en2-g46', type: 'Grammar', question: 'How do you say 12 in English?', answer: 'Twelve', options: ['Twelve', 'Twenty', 'Two'], instruction: 'Numbers' },
    { id: 'en2-g47', type: 'Grammar', question: 'How do you say 20 in English?', answer: 'Twenty', options: ['Twenty', 'Twelve', 'Two'], instruction: 'Numbers' },
    { id: 'en2-g48', type: 'Grammar', question: 'What is "She"?', answer: 'Pronoun', options: ['Pronoun', 'Noun', 'Verb'], instruction: 'Word classes' },
    { id: 'en2-g49', type: 'Grammar', question: 'What is "It"?', answer: 'Pronoun', options: ['Pronoun', 'Noun', 'Verb'], instruction: 'Word classes' },
    { id: 'en2-g50', type: 'Grammar', question: 'What is "Them"?', answer: 'Pronoun', options: ['Pronoun', 'Noun', 'Verb'], instruction: 'Word classes' },
    { id: 'en2-g51', type: 'Grammar', question: 'Nice ___!', answer: 'work', options: ['work', 'sad', 'blue'], instruction: 'Feedback' },
  ],
  3: [
    { id: 'en3-g1', type: 'Grammar', question: 'He ___ (walk) to school every day.', answer: 'walks', options: ['walks', 'walk', 'walking'], instruction: 'Present tense' },
    { id: 'en3-g2', type: 'Grammar', question: 'They ___ (walk) to school every day.', answer: 'walk', options: ['walk', 'walks', 'walking'], instruction: 'Present tense' },
    { id: 'en3-g3', type: 'Grammar', question: 'She ___ (like) chocolate.', answer: 'likes', options: ['likes', 'like', 'liking'], instruction: 'Present tense' },
    { id: 'en3-g4', type: 'Grammar', question: 'I ___ (like) chocolate.', answer: 'like', options: ['like', 'likes', 'liking'], instruction: 'Present tense' },
    { id: 'en3-g5', type: 'Grammar', question: 'It ___ (rain) a lot in autumn.', answer: 'rains', options: ['rains', 'rain', 'raining'], instruction: 'Present tense' },
    { id: 'en3-g6', type: 'Grammar', question: 'They ___ (play) football now.', answer: 'are playing', options: ['are playing', 'is playing', 'play'], instruction: 'Present continuous' },
    { id: 'en3-g7', type: 'Grammar', question: 'I ___ (eat) an apple now.', answer: 'am eating', options: ['am eating', 'is eating', 'are eating'], instruction: 'Present continuous' },
    { id: 'en3-g8', type: 'Grammar', question: 'He ___ (sleep) in his bed now.', answer: 'is sleeping', options: ['is sleeping', 'are sleeping', 'am sleeping'], instruction: 'Present continuous' },
    { id: 'en3-g9', type: 'Grammar', question: 'Does he ___ (have) a car?', answer: 'have', options: ['have', 'has', 'having'], instruction: 'Auxiliary verbs' },
    { id: 'en3-g10', type: 'Grammar', question: 'I ___ (have) a new bike.', answer: 'have', options: ['have', 'has', 'having'], instruction: 'Verbs' },
    { id: 'en3-g11', type: 'Grammar', question: 'She ___ (has) a blue dress.', answer: 'has', options: ['has', 'have', 'having'], instruction: 'Verbs' },
    { id: 'en3-g12', type: 'Grammar', question: 'Past of "Buy":', answer: 'Bought', options: ['Bought', 'Buyed', 'Buyer'], instruction: 'Irregular past' },
    { id: 'en3-g13', type: 'Grammar', question: 'Past of "Bring":', answer: 'Brought', options: ['Brought', 'Bringed', 'Bringer'], instruction: 'Irregular past' },
    { id: 'en3-g14', type: 'Grammar', question: 'Past of "Catch":', answer: 'Caught', options: ['Caught', 'Catched', 'Catcher'], instruction: 'Irregular past' },
    { id: 'en3-g15', type: 'Grammar', question: 'Past of "Sleep":', answer: 'Slept', options: ['Slept', 'Sleeped', 'Sleeper'], instruction: 'Irregular past' },
    { id: 'en3-g16', type: 'Grammar', question: 'Past of "Read":', answer: 'Read', options: ['Read', 'Readed', 'Ready'], instruction: 'Irregular past' },
    { id: 'en3-g17', type: 'Grammar', question: 'Past of "Run":', answer: 'Ran', options: ['Ran', 'Runned', 'Runner'], instruction: 'Irregular past' },
    { id: 'en3-g18', type: 'Grammar', question: 'Comparative: "Big" -> "___"', answer: 'Bigger', options: ['Bigger', 'Bigest', 'More big'], instruction: 'Degrees' },
    { id: 'en3-g19', type: 'Grammar', question: 'Superlative: "Big" -> "___"', answer: 'Biggest', options: ['Biggest', 'Bigger', 'Most big'], instruction: 'Degrees' },
    { id: 'en3-g20', type: 'Grammar', question: 'Comparative: "Happy" -> "___"', answer: 'Happier', options: ['Happier', 'Happiest', 'More happy'], instruction: 'Degrees' },
    { id: 'en3-g21', type: 'Grammar', question: 'Superlative: "Happy" -> "___"', answer: 'Happiest', options: ['Happiest', 'Happier', 'Most happy'], instruction: 'Degrees' },
    { id: 'en3-g22', type: 'Grammar', question: 'Is "Quickly" an adverb?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en3-g23', type: 'Grammar', question: 'Is "Fast" an adverb?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en3-g24', type: 'Grammar', question: 'Preposition: "I am ___ home."', answer: 'at', options: ['at', 'in', 'on'], instruction: 'Prepositions' },
    { id: 'en3-g25', type: 'Grammar', question: 'Preposition: "I listen ___ music."', answer: 'to', options: ['to', 'at', 'with'], instruction: 'Prepositions' },
    { id: 'en3-g26', type: 'Grammar', question: 'Preposition: "I am waiting ___ you."', answer: 'for', options: ['for', 'to', 'at'], instruction: 'Prepositions' },
    { id: 'en3-g27', type: 'Grammar', question: 'What is a "Noun"?', answer: 'A person, place or thing', options: ['A person, place or thing', 'An action word', 'A describing word'], instruction: 'Grammar terms' },
    { id: 'en3-g28', type: 'Grammar', question: 'What is a "Verb"?', answer: 'An action word', options: ['An action word', 'A describing word', 'A person'], instruction: 'Grammar terms' },
    { id: 'en3-g29', type: 'Grammar', question: 'What is an "Adjective"?', answer: 'A describing word', options: ['A describing word', 'An action word', 'A thing'], instruction: 'Grammar terms' },
    { id: 'en3-g30', type: 'Grammar', question: 'Is "And" a conjunction?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en3-g31', type: 'Grammar', question: 'Is "But" a conjunction?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en3-g32', type: 'Grammar', question: 'How do you say 100 in English?', answer: 'One hundred', options: ['One hundred', 'Ten ten', 'Thousand'], instruction: 'Numbers' },
    { id: 'en3-g33', type: 'Grammar', question: 'How do you say 1000 in English?', answer: 'One thousand', options: ['One thousand', 'One hundred', 'Ten hundred'], instruction: 'Numbers' },
    { id: 'en3-g34', type: 'Grammar', question: 'Is "Sun" a proper noun?', answer: 'No (unless specific name)', options: ['No', 'Yes'], instruction: 'Proper nouns' },
    { id: 'en3-g35', type: 'Grammar', question: 'Is "London" a proper noun?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Proper nouns' },
    { id: 'en3-g36', type: 'Grammar', question: 'Correct: "I can dance" or "I can dances"?', answer: 'I can dance', options: ['I can dance', 'I can dances', 'I can dancing'], instruction: 'Modal verbs' },
    { id: 'en3-g37', type: 'Grammar', question: 'Correct: "Would you like" or "Will you like"?', answer: 'Would you like', options: ['Would you like', 'Will you like'], instruction: 'Politeness' },
    { id: 'en3-g38', type: 'Grammar', question: 'Identify the subject: "The cat jumps."', answer: 'The cat', options: ['The cat', 'jumps'], instruction: 'Sentence analysis' },
    { id: 'en3-g39', type: 'Grammar', question: 'Identify the verb: "The cat jumps."', answer: 'jumps', options: ['jumps', 'The cat'], instruction: 'Sentence analysis' },
    { id: 'en3-g40', type: 'Grammar', question: 'Identify the object: "I eat an apple."', answer: 'an apple', options: ['an apple', 'I', 'eat'], instruction: 'Sentence analysis' },
    { id: 'en3-g41', type: 'Grammar', question: 'Is "Apple" countable?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Countable nouns' },
    { id: 'en3-g42', type: 'Grammar', question: 'Is "Water" countable?', answer: 'No', options: ['No', 'Yes'], instruction: 'Uncountable nouns' },
    { id: 'en3-g43', type: 'Grammar', question: 'Use "Much" or "Many" with water?', answer: 'Much', options: ['Much', 'Many'], instruction: 'Quantifiers' },
    { id: 'en3-g44', type: 'Grammar', question: 'Use "Much" or "Many" with apples?', answer: 'Many', options: ['Many', 'Much'], instruction: 'Quantifiers' },
    { id: 'en3-g45', type: 'Grammar', question: 'Opposite of "Sharp":', answer: 'Blunt', options: ['Blunt', 'Soft', 'Hard'], instruction: 'Vocabulary' },
    { id: 'en3-g46', type: 'Grammar', question: 'Opposite of "Narrow":', answer: 'Wide', options: ['Wide', 'Small', 'Thin'], instruction: 'Vocabulary' },
    { id: 'en3-g47', type: 'Grammar', question: 'Past of "Do":', answer: 'Did', options: ['Did', 'Done', 'Doed'], instruction: 'Irregular past' },
    { id: 'en3-g48', type: 'Grammar', question: 'Past of "Go":', answer: 'Went', options: ['Went', 'Goed', 'Gone'], instruction: 'Irregular past' },
    { id: 'en3-g49', type: 'Grammar', question: 'How many months in a year?', answer: 'Twelve', options: ['Twelve', 'Ten', 'Eleven'], instruction: 'General knowledge' },
    { id: 'en3-g50', type: 'Grammar', question: 'Which month is first?', answer: 'January', options: ['January', 'February', 'December'], instruction: 'Months' },
    { id: 'en3-g51', type: 'Grammar', question: 'Excellent ___!', answer: 'job', options: ['job', 'bad', 'blue'], instruction: 'Feedback' },
  ],
};
