/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const ENGELSK_GRAMMAR_P2: Partial<Record<Grade, GameContent[]>> = {
  4: [
    { id: 'en4-g1', type: 'Grammar', question: 'I ___ (be) at home yesterday.', answer: 'was', options: ['was', 'were', 'am'], instruction: 'Past: To be' },
    { id: 'en4-g2', type: 'Grammar', question: 'They ___ (be) at home yesterday.', answer: 'were', options: ['were', 'was', 'are'], instruction: 'Past: To be' },
    { id: 'en4-g3', type: 'Grammar', question: 'We ___ (not / study) for the test.', answer: 'didn\'t study', options: ['didn\'t study', 'don\'t study', 'not study'], instruction: 'Past negative' },
    { id: 'en4-g4', type: 'Grammar', question: '___ you (see) the film?', answer: 'Did', options: ['Did', 'Do', 'Have'], instruction: 'Past questions' },
    { id: 'en4-g5', type: 'Grammar', question: 'She ___ (sing) beautifully last night.', answer: 'sang', options: ['sang', 'singed', 'sings'], instruction: 'Irregular past' },
    { id: 'en4-g6', type: 'Grammar', question: 'I ___ (make) a cake for you.', answer: 'made', options: ['made', 'make', 'maked'], instruction: 'Irregular past' },
    { id: 'en4-g7', type: 'Grammar', question: 'He ___ (take) my pen.', answer: 'took', options: ['took', 'taked', 'take'], instruction: 'Irregular past' },
    { id: 'en4-g8', type: 'Grammar', question: 'We ___ (build) a treehouse.', answer: 'built', options: ['built', 'builded', 'build'], instruction: 'Irregular past' },
    { id: 'en4-g9', type: 'Grammar', question: 'Listen! She ___ (play) the piano.', answer: 'is playing', options: ['is playing', 'plays', 'played'], instruction: 'Present continuous' },
    { id: 'en4-g10', type: 'Grammar', question: 'Look! It ___ (snow).', answer: 'is snowing', options: ['is snowing', 'snows', 'snowed'], instruction: 'Present continuous' },
    { id: 'en4-g11', type: 'Grammar', question: 'They ___ (dance) at the moment.', answer: 'are dancing', options: ['are dancing', 'dance', 'dancing'], instruction: 'Present continuous' },
    { id: 'en4-g12', type: 'Grammar', question: 'I like ___ (swim) in the sea.', answer: 'swimming', options: ['swimming', 'swim', 'swims'], instruction: 'Gerunds' },
    { id: 'en4-g13', type: 'Grammar', question: 'He is good at ___ (draw).', answer: 'drawing', options: ['drawing', 'draw', 'draws'], instruction: 'Gerunds' },
    { id: 'en4-g14', type: 'Grammar', question: 'Stop ___ (shout)!', answer: 'shouting', options: ['shouting', 'shout', 'shouted'], instruction: 'Gerunds' },
    { id: 'en4-g15', type: 'Grammar', question: 'Comparative: "Big" -> "___"', answer: 'Bigger', options: ['Bigger', 'Bigged', 'More big'], instruction: 'Adjectives' },
    { id: 'en4-g16', type: 'Grammar', question: 'Superlative: "High" -> "___"', answer: 'Highest', options: ['Highest', 'Higher', 'Most high'], instruction: 'Adjectives' },
    { id: 'en4-g17', type: 'Grammar', question: 'Comparative: "Expensive" -> "___"', answer: 'More expensive', options: ['More expensive', 'Expensiver', 'Most expensive'], instruction: 'Adjectives' },
    { id: 'en4-g18', type: 'Grammar', question: 'Superlative: "Interesting" -> "___"', answer: 'Most interesting', options: ['Most interesting', 'Interestingest', 'More interesting'], instruction: 'Adjectives' },
    { id: 'en4-g19', type: 'Grammar', question: '___ is your birthday?', answer: 'When', options: ['When', 'Where', 'Whose'], instruction: 'Question words' },
    { id: 'en4-g20', type: 'Grammar', question: '___ bag is this?', answer: 'Whose', options: ['Whose', 'Who', 'Where'], instruction: 'Question words' },
    { id: 'en4-g21', type: 'Grammar', question: '___ is the train station?', answer: 'Where', options: ['Where', 'How', 'Who'], instruction: 'Question words' },
    { id: 'en4-g22', type: 'Grammar', question: '___ are you crying?', answer: 'Why', options: ['Why', 'What', 'Where'], instruction: 'Question words' },
    { id: 'en4-g23', type: 'Grammar', question: 'I have ___ money (some / any).', answer: 'some', options: ['some', 'any'], instruction: 'Some/Any' },
    { id: 'en4-g24', type: 'Grammar', question: 'I don\'t have ___ money.', answer: 'any', options: ['any', 'some'], instruction: 'Some/Any' },
    { id: 'en4-g25', type: 'Grammar', question: 'Do you have ___ questions?', answer: 'any', options: ['any', 'some'], instruction: 'Some/Any' },
    { id: 'en4-g26', type: 'Grammar', question: 'There is ___ milk in the fridge.', answer: 'some', options: ['some', 'any'], instruction: 'Some/Any' },
    { id: 'en4-g27', type: 'Grammar', question: 'Would you like ___ juice?', answer: 'some', options: ['some', 'any'], instruction: 'Offering (Exception)' },
    { id: 'en4-g28', type: 'Grammar', question: 'Whose car is it? It\'s ___ car (belonging to us).', answer: 'our', options: ['our', 'ours', 'us'], instruction: 'Possessives' },
    { id: 'en4-g29', type: 'Grammar', question: 'The house is ___ (belonging to them).', answer: 'theirs', options: ['theirs', 'their', 'them'], instruction: 'Possessives' },
    { id: 'en4-g30', type: 'Grammar', question: 'I saw ___ (him / he) in the park.', answer: 'him', options: ['him', 'he'], instruction: 'Object pronouns' },
    { id: 'en4-g31', type: 'Grammar', question: 'Can you help ___ (me / I)?', answer: 'me', options: ['me', 'I'], instruction: 'Object pronouns' },
    { id: 'en4-g32', type: 'Grammar', question: 'We told ___ (them / they) a secret.', answer: 'them', options: ['them', 'they'], instruction: 'Object pronouns' },
    { id: 'en4-g33', type: 'Grammar', question: 'Is "Always" a frequency adverb?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en4-g34', type: 'Grammar', question: '"I ___ never been to Paris."', answer: 'have', options: ['have', 'has', 'am'], instruction: 'Present perfect' },
    { id: 'en4-g35', type: 'Grammar', question: '"She ___ lost her keys."', answer: 'has', options: ['has', 'have', 'is'], instruction: 'Present perfect' },
    { id: 'en4-g36', type: 'Grammar', question: 'Identify the preposition: "He sits next to me."', answer: 'next to', options: ['next to', 'He', 'me'], instruction: 'Word classes' },
    { id: 'en4-g37', type: 'Grammar', question: 'Identify the conjunction: "I am tired but happy."', answer: 'but', options: ['but', 'tired', 'happy'], instruction: 'Word classes' },
    { id: 'en4-g38', type: 'Grammar', question: 'The cat is ___ the mat.', answer: 'on', options: ['on', 'in', 'at'], instruction: 'Prepositions' },
    { id: 'en4-g39', type: 'Grammar', question: 'He is arriving ___ 5 o\'clock.', answer: 'at', options: ['at', 'on', 'in'], instruction: 'Time prepositions' },
    { id: 'en4-g40', type: 'Grammar', question: 'See you ___ Monday.', answer: 'on', options: ['on', 'at', 'in'], instruction: 'Time prepositions' },
    { id: 'en4-g41', type: 'Grammar', question: 'I was born ___ May.', answer: 'in', options: ['in', 'at', 'on'], instruction: 'Time prepositions' },
    { id: 'en4-g42', type: 'Grammar', question: 'Write 50 in letters:', answer: 'Fifty', options: ['Fifty', 'Fifteen', 'Five thousand'], instruction: 'Numbers' },
    { id: 'en4-g43', type: 'Grammar', question: 'Write 15 in letters:', answer: 'Fifteen', options: ['Fifteen', 'Fifty', 'Five'], instruction: 'Numbers' },
    { id: 'en4-g44', type: 'Grammar', question: 'What is the subject: "The children played?"', answer: 'The children', options: ['The children', 'played'], instruction: 'Sentence analysis' },
    { id: 'en4-g45', type: 'Grammar', question: 'What is the verb: "The children played?"', answer: 'played', options: ['played', 'The children'], instruction: 'Sentence analysis' },
    { id: 'en4-g46', type: 'Grammar', question: 'Opposite of "Empty":', answer: 'Full', options: ['Full', 'New', 'Old'], instruction: 'Vocabulary' },
    { id: 'en4-g47', type: 'Grammar', question: 'Opposite of "First":', answer: 'Last', options: ['Last', 'Second', 'Third'], instruction: 'Vocabulary' },
    { id: 'en4-g48', type: 'Grammar', question: 'Wait ___ me!', answer: 'for', options: ['for', 'on', 'at'], instruction: 'Prepositions' },
    { id: 'en4-g49', type: 'Grammar', question: 'Listen ___ the music!', answer: 'to', options: ['to', 'on', 'at'], instruction: 'Prepositions' },
    { id: 'en4-g50', type: 'Grammar', question: 'Talk ___ your friend.', answer: 'to', options: ['to', 'on', 'at'], instruction: 'Prepositions' },
    { id: 'en4-g51', type: 'Grammar', question: 'Keep it ___!', answer: 'up', options: ['up', 'down', 'left'], instruction: 'Feedback' },
  ],
  5: [
    { id: 'en5-g1', type: 'Grammar', question: 'I have ___ (live) here for 5 years.', answer: 'lived', options: ['lived', 'live', 'living'], instruction: 'Present perfect' },
    { id: 'en5-g2', type: 'Grammar', question: 'She has ___ (see) that film twice.', answer: 'seen', options: ['seen', 'saw', 'see'], instruction: 'Present perfect' },
    { id: 'en5-g3', type: 'Grammar', question: 'We haven\'t ___ (finish) yet.', answer: 'finished', options: ['finished', 'finish', 'finishing'], instruction: 'Present perfect' },
    { id: 'en5-g4', type: 'Grammar', question: 'Have you ever ___ (eat) sushi?', answer: 'eaten', options: ['eaten', 'ate', 'eat'], instruction: 'Present perfect' },
    { id: 'en5-g5', type: 'Grammar', question: 'I ___ (be) tired because I ___ (work) all day.', answer: 'am / have worked', options: ['am / have worked', 'was / am working', 'be / work'], instruction: 'Tense consistency' },
    { id: 'en5-g6', type: 'Grammar', question: 'It is the ___ (good) book ever.', answer: 'best', options: ['best', 'goodest', 'better'], instruction: 'Irregular forms' },
    { id: 'en5-g7', type: 'Grammar', question: 'This is ___ (bad) than that.', answer: 'worse', options: ['worse', 'badder', 'worst'], instruction: 'Irregular forms' },
    { id: 'en5-g8', type: 'Grammar', question: 'He is the ___ (bad) player.', answer: 'worst', options: ['worst', 'worse', 'badly'], instruction: 'Irregular forms' },
    { id: 'en5-g9', type: 'Grammar', question: 'I think science is ___ (interesting) than art.', answer: 'more interesting', options: ['more interesting', 'interestinger', 'most interesting'], instruction: 'Comparison' },
    { id: 'en5-g10', type: 'Grammar', question: 'This is the ___ (interesting) movie.', answer: 'most interesting', options: ['most interesting', 'more interesting', 'interestingest'], instruction: 'Comparison' },
    { id: 'en5-g11', type: 'Grammar', question: '___ you swim?', answer: 'Can', options: ['Can', 'Do', 'Are'], instruction: 'Modal verbs' },
    { id: 'en5-g12', type: 'Grammar', question: 'You ___ (must) do your homework.', answer: 'must', options: ['must', 'can', 'will'], instruction: 'Modal verbs' },
    { id: 'en5-g13', type: 'Grammar', question: 'They ___ (will) arrive at 6.', answer: 'will', options: ['will', 'must', 'shall'], instruction: 'Modal verbs' },
    { id: 'en5-g14', type: 'Grammar', question: 'I ___ (should) study more.', answer: 'should', options: ['should', 'can', 'must'], instruction: 'Modal verbs' },
    { id: 'en5-g15', type: 'Grammar', question: 'A person who writes books is an ___.', answer: 'author', options: ['author', 'actor', 'artist'], instruction: 'Vocabulary' },
    { id: 'en5-g16', type: 'Grammar', question: 'A person who paints is an ___.', answer: 'artist', options: ['artist', 'author', 'athlete'], instruction: 'Vocabulary' },
    { id: 'en5-g17', type: 'Grammar', question: 'A person who does sport is an ___.', answer: 'athlete', options: ['athlete', 'author', 'artist'], instruction: 'Vocabulary' },
    { id: 'en5-g18', type: 'Grammar', question: 'Past of "Fall":', answer: 'Fell', options: ['Fell', 'Felled', 'Fallen'], instruction: 'Irregular past' },
    { id: 'en5-g19', type: 'Grammar', question: 'Past of "Fly":', answer: 'Flew', options: ['Flew', 'Flown', 'Flyed'], instruction: 'Irregular past' },
    { id: 'en5-g20', type: 'Grammar', question: 'Past of "Forget":', answer: 'Forgot', options: ['Forgot', 'Forgotten', 'Forgetted'], instruction: 'Irregular past' },
    { id: 'en5-g21', type: 'Grammar', question: 'Past of "Begin":', answer: 'Began', options: ['Began', 'Begun', 'Beginned'], instruction: 'Irregular past' },
    { id: 'en5-g22', type: 'Grammar', question: 'Past of "Speak":', answer: 'Spoke', options: ['Spoke', 'Spoken', 'Speaked'], instruction: 'Irregular past' },
    { id: 'en5-g23', type: 'Grammar', question: 'Past of "Write":', answer: 'Wrote', options: ['Wrote', 'Written', 'Writed'], instruction: 'Irregular past' },
    { id: 'en5-g24', type: 'Grammar', question: 'Past of "Drive":', answer: 'Drove', options: ['Drove', 'Driven', 'Drived'], instruction: 'Irregular past' },
    { id: 'en5-g25', type: 'Grammar', question: 'Which is a "Determiner"?', answer: 'The', options: ['The', 'Run', 'Big'], instruction: 'Word classes' },
    { id: 'en5-g26', type: 'Grammar', question: 'Which is a "Preposition"?', answer: 'Behind', options: ['Behind', 'Quickly', 'He'], instruction: 'Word classes' },
    { id: 'en5-g27', type: 'Grammar', question: 'Which is an "Adjunction"?', answer: 'Although', options: ['Although', 'Always', 'Blue'], instruction: 'Word classes' },
    { id: 'en5-g28', type: 'Grammar', question: 'Correct order: "I have already eaten" or "I already have eaten"?', answer: 'I have already eaten', options: ['I have already eaten', 'I already have eaten'], instruction: 'Adverb position' },
    { id: 'en5-g29', type: 'Grammar', question: 'Correct: "I am listening to music" or "I am listening music"?', answer: 'listening to', options: ['listening to', 'listening'], instruction: 'Verb patterns' },
    { id: 'en5-g30', type: 'Grammar', question: 'Correct: "Tell me a story" or "Say me a story"?', answer: 'Tell me', options: ['Tell me', 'Say me', 'Tell to me'], instruction: 'Verb patterns' },
    { id: 'en5-g31', type: 'Grammar', question: '"___ are you going?" "To London."', answer: 'Where', options: ['Where', 'How', 'Who'], instruction: 'Question words' },
    { id: 'en5-g32', type: 'Grammar', question: '"___ are you?" "Fine, thanks."', answer: 'How', options: ['How', 'What', 'Where'], instruction: 'Question words' },
    { id: 'en5-g33', type: 'Grammar', question: 'Identify the object pronoun: "Give it to her."', answer: 'her', options: ['her', 'she', 'Give'], instruction: 'Word classes' },
    { id: 'en5-g34', type: 'Grammar', question: 'Identify the possessive adjective: "My dog is big."', answer: 'My', options: ['My', 'dog', 'big'], instruction: 'Word classes' },
    { id: 'en5-g35', type: 'Grammar', question: 'Opposite of "True":', answer: 'False', options: ['False', 'Wrong', 'Right'], instruction: 'Vocabulary' },
    { id: 'en5-g36', type: 'Grammar', question: 'Opposite of "Alive":', answer: 'Dead', options: ['Dead', 'Live', 'New'], instruction: 'Vocabulary' },
    { id: 'en5-g37', type: 'Grammar', question: 'Is "Beautiful" a three-syllable word?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Syllables' },
    { id: 'en5-g38', type: 'Grammar', question: 'Is "Dog" a one-syllable word?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Syllables' },
    { id: 'en5-g39', type: 'Grammar', question: 'Plural of "Sheep":', answer: 'Sheep', options: ['Sheep', 'Sheeps', 'Sheepes'], instruction: 'Irregular plural' },
    { id: 'en5-g40', type: 'Grammar', question: 'Plural of "Fish":', answer: 'Fish', options: ['Fish', 'Fishes', 'Fishy'], instruction: 'Irregular plural' },
    { id: 'en5-g41', type: 'Grammar', question: 'Plural of "Deer":', answer: 'Deer', options: ['Deer', 'Deers', 'Deeres'], instruction: 'Irregular plural' },
    { id: 'en5-g42', type: 'Grammar', question: 'How do you spell 40?', answer: 'Forty', options: ['Forty', 'Fourty', 'Forthi'], instruction: 'Spelling' },
    { id: 'en5-g43', type: 'Grammar', question: 'How do you spell 14?', answer: 'Fourteen', options: ['Fourteen', 'Forteen', 'Forty'], instruction: 'Spelling' },
    { id: 'en5-g44', type: 'Grammar', question: 'Which is a "Main clause"?', answer: 'I like cake', options: ['I like cake', 'because I am happy', 'when it rains'], instruction: 'Clauses' },
    { id: 'en5-g45', type: 'Grammar', question: 'Which is a "Subordinate clause"?', answer: 'because it is late', options: ['because it is late', 'I study English', 'He runs fast'], instruction: 'Clauses' },
    { id: 'en5-g46', type: 'Grammar', question: 'Use "For" or "Since": 10 years.', answer: 'for', options: ['for', 'since'], instruction: 'Time' },
    { id: 'en5-g47', type: 'Grammar', question: 'Use "For" or "Since": 1990.', answer: 'since', options: ['since', 'for'], instruction: 'Time' },
    { id: 'en5-g48', type: 'Grammar', question: 'Use "For" or "Since": last week.', answer: 'since', options: ['since', 'for'], instruction: 'Time' },
    { id: 'en5-g49', type: 'Grammar', question: 'Use "For" or "Since": two hours.', answer: 'for', options: ['for', 'since'], instruction: 'Time' },
    { id: 'en5-g50', type: 'Grammar', question: 'He is arriving ___ Friday.', answer: 'on', options: ['on', 'at', 'in'], instruction: 'Time prepositions' },
    { id: 'en5-g51', type: 'Grammar', question: 'Well ___!', answer: 'done', options: ['done', 'had', 'car'], instruction: 'Feedback' },
  ],
  6: [
    { id: 'en6-g1', type: 'Grammar', question: 'He is as ___ (tall) as me.', answer: 'tall', options: ['tall', 'taller', 'tallest'], instruction: 'Equality comparison' },
    { id: 'en6-g2', type: 'Grammar', question: 'She sings ___ (good / well).', answer: 'well', options: ['well', 'good'], instruction: 'Adverbs' },
    { id: 'en6-g3', type: 'Grammar', question: 'He runs ___ (fast / fastly).', answer: 'fast', options: ['fast', 'fastly'], instruction: 'Irregular adverbs' },
    { id: 'en6-g4', type: 'Grammar', question: 'They play ___ (loud / loudly).', answer: 'loudly', options: ['loudly', 'loud'], instruction: 'Adverbs' },
    { id: 'en6-g5', type: 'Grammar', question: 'I work ___ (hard / hardly).', answer: 'hard', options: ['hard', 'hardly'], instruction: 'Irregular adverbs' },
    { id: 'en6-g6', type: 'Grammar', question: 'Passive: "He makes pizza" -> "Pizza ___ by him."', answer: 'is made', options: ['is made', 'was made', 'has made'], instruction: 'Passive voice' },
    { id: 'en6-g7', type: 'Grammar', question: 'Passive: "They built the bridge" -> "The bridge ___."', answer: 'was built', options: ['was built', 'is built', 'built'], instruction: 'Passive voice' },
    { id: 'en6-g8', type: 'Grammar', question: 'If it ___ (rain), we will stay inside.', answer: 'rains', options: ['rains', 'rain', 'rained'], instruction: 'Conditional 1' },
    { id: 'en6-g9', type: 'Grammar', question: 'If you study, you ___ (pass).', answer: 'will pass', options: ['will pass', 'would pass', 'pass'], instruction: 'Conditional 1' },
    { id: 'en6-g10', type: 'Grammar', question: 'I will call you when I ___ (arrive).', answer: 'arrive', options: ['arrive', 'will arrive', 'arriving'], instruction: 'Future time clauses' },
    { id: 'en6-g11', type: 'Grammar', question: 'By the time he came, I ___ (finish).', answer: 'had finished', options: ['had finished', 'finished', 'have finished'], instruction: 'Past perfect' },
    { id: 'en6-g12', type: 'Grammar', question: 'She ___ (already / leave) before I arrived.', answer: 'had already left', options: ['had already left', 'already left', 'has left'], instruction: 'Past perfect' },
    { id: 'en6-g13', type: 'Grammar', question: 'Which is a "Reflexive pronoun"?', answer: 'Myself', options: ['Myself', 'My', 'Mine'], instruction: 'Word classes' },
    { id: 'en6-g14', type: 'Grammar', question: 'He hurt ___ (himself / him).', answer: 'himself', options: ['himself', 'him'], instruction: 'Reflexive pronouns' },
    { id: 'en6-g15', type: 'Grammar', question: 'They did it ___ (themselves / them).', answer: 'themselves', options: ['themselves', 'them'], instruction: 'Reflexive pronouns' },
    { id: 'en6-g16', type: 'Grammar', question: 'Do it ___ (yourself / you)!', answer: 'yourself', options: ['yourself', 'you'], instruction: 'Reflexive pronouns' },
    { id: 'en6-g17', type: 'Grammar', question: 'Relative: The man ___ lives next door.', answer: 'who', options: ['who', 'which', 'whom'], instruction: 'Relative pronouns' },
    { id: 'en6-g18', type: 'Grammar', question: 'Relative: The book ___ I read was good.', answer: 'which', options: ['which', 'who', 'whose'], instruction: 'Relative pronouns' },
    { id: 'en6-g19', type: 'Grammar', question: 'Relative: The girl ___ car was stolen.', answer: 'whose', options: ['whose', 'who', 'which'], instruction: 'Relative pronouns' },
    { id: 'en6-g20', type: 'Grammar', question: '___ do you work? At a bank.', answer: 'Where', options: ['Where', 'How', 'When'], instruction: 'Question words' },
    { id: 'en6-g21', type: 'Grammar', question: '___ do you work? In the morning.', answer: 'When', options: ['When', 'Where', 'How'], instruction: 'Question words' },
    { id: 'en6-g22', type: 'Grammar', question: '___ do you work? Very hard.', answer: 'How', options: ['How', 'Who', 'Where'], instruction: 'Question words' },
    { id: 'en6-g23', type: 'Grammar', question: 'I ___ (live) here since 2010.', answer: 'have lived', options: ['have lived', 'live', 'lived'], instruction: 'Present perfect' },
    { id: 'en6-g24', type: 'Grammar', question: 'She ___ (not / see) him recently.', answer: 'hasn\'t seen', options: ['hasn\'t seen', 'doesn\'t see', 'didn\'t see'], instruction: 'Present perfect' },
    { id: 'en6-g25', type: 'Grammar', question: 'Have you ___ (ever) been to London?', answer: 'ever', options: ['ever', 'never', 'just'], instruction: 'Adverb usage' },
    { id: 'en6-g26', type: 'Grammar', question: 'I have ___ (just) finished my lunch.', answer: 'just', options: ['just', 'ever', 'yet'], instruction: 'Adverb usage' },
    { id: 'en6-g27', type: 'Grammar', question: 'He hasn\'t arrived ___ (yet).', answer: 'yet', options: ['yet', 'already', 'ever'], instruction: 'Adverb usage' },
    { id: 'en6-g28', type: 'Grammar', question: 'I have ___ (already) done it.', answer: 'already', options: ['already', 'yet', 'ever'], instruction: 'Adverb usage' },
    { id: 'en6-g29', type: 'Grammar', question: 'Is "Information" a countable noun?', answer: 'No', options: ['No', 'Yes'], instruction: 'Uncountable nouns' },
    { id: 'en6-g30', type: 'Grammar', question: 'Is "Furniture" a countable noun?', answer: 'No', options: ['No', 'Yes'], instruction: 'Uncountable nouns' },
    { id: 'en6-g31', type: 'Grammar', question: 'Is "Sugar" a countable noun?', answer: 'No', options: ['No', 'Yes'], instruction: 'Uncountable nouns' },
    { id: 'en6-g32', type: 'Grammar', question: 'Use "A little" or "A few": sugar.', answer: 'A little', options: ['A little', 'A few'], instruction: 'Quantifiers' },
    { id: 'en6-g33', type: 'Grammar', question: 'Use "A little" or "A few": apples.', answer: 'A few', options: ['A few', 'A little'], instruction: 'Quantifiers' },
    { id: 'en6-g34', type: 'Grammar', question: 'Use "A little" or "A few": time.', answer: 'A little', options: ['A little', 'A few'], instruction: 'Quantifiers' },
    { id: 'en6-g35', type: 'Grammar', question: 'Use "A little" or "A few": books.', answer: 'A few', options: ['A few', 'A little'], instruction: 'Quantifiers' },
    { id: 'en6-g36', type: 'Grammar', question: 'Opposite of "Public":', answer: 'Private', options: ['Private', 'Social', 'Crowded'], instruction: 'Vocabulary' },
    { id: 'en6-g37', type: 'Grammar', question: 'Opposite of "Ancient":', answer: 'Modern', options: ['Modern', 'Old', 'Historical'], instruction: 'Vocabulary' },
    { id: 'en6-g38', type: 'Grammar', question: 'Opposite of "Dangerous":', answer: 'Safe', options: ['Safe', 'Risky', 'Hard'], instruction: 'Vocabulary' },
    { id: 'en6-g39', type: 'Grammar', question: 'Plural of "Life":', answer: 'Lives', options: ['Lives', 'Lifes', 'Life'], instruction: 'Nouns in -f/fe' },
    { id: 'en6-g40', type: 'Grammar', question: 'Plural of "Knife":', answer: 'Knives', options: ['Knives', 'Knifes', 'Knifey'], instruction: 'Nouns in -f/fe' },
    { id: 'en6-g41', type: 'Grammar', question: 'Plural of "Leaf":', answer: 'Leaves', options: ['Leaves', 'Leafs', 'Leafes'], instruction: 'Nouns in -f/fe' },
    { id: 'en6-g42', type: 'Grammar', question: 'Spell 1000 correctly:', answer: 'Thousand', options: ['Thousand', 'Thousend', 'Tousend'], instruction: 'Spelling' },
    { id: 'en6-g43', type: 'Grammar', question: 'Identify the indirect object: "I gave her a gift."', answer: 'her', options: ['her', 'gift', 'gave'], instruction: 'Sentence analysis' },
    { id: 'en6-g44', type: 'Grammar', question: 'Identify the direct object: "I gave her a gift."', answer: 'a gift', options: ['a gift', 'her', 'gave'], instruction: 'Sentence analysis' },
    { id: 'en6-g45', type: 'Grammar', question: 'Reported: "I am happy" -> He said he ___ happy.', answer: 'was', options: ['was', 'is', 'be'], instruction: 'Reported speech' },
    { id: 'en6-g46', type: 'Grammar', question: 'Reported: "I like cake" -> She said she ___ cake.', answer: 'liked', options: ['liked', 'likes', 'like'], instruction: 'Reported speech' },
    { id: 'en6-g47', type: 'Grammar', question: 'Is "Because" a subordinating conjunction?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en6-g48', type: 'Grammar', question: 'Is "Since" a subordinating conjunction?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en6-g49', type: 'Grammar', question: 'He is good ___ English.', answer: 'at', options: ['at', 'in', 'to'], instruction: 'Prepositions' },
    { id: 'en6-g50', type: 'Grammar', question: 'He is interested ___ politics.', answer: 'in', options: ['in', 'at', 'on'], instruction: 'Prepositions' },
    { id: 'en6-g51', type: 'Grammar', question: 'Keep it ___!', answer: 'going', options: ['going', 'bad', 'car'], instruction: 'Feedback' },
  ],
};
