/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const ENGELSK_GRAMMAR_P3: Partial<Record<Grade, GameContent[]>> = {
  7: [
    { id: 'en7-g1', type: 'Grammar', question: 'If I ___ (be) you, I would go.', answer: 'were', options: ['were', 'was', 'am'], instruction: 'Conditional 2' },
    { id: 'en7-g2', type: 'Grammar', question: 'If I had money, I ___ (buy) a car.', answer: 'would buy', options: ['would buy', 'will buy', 'bought'], instruction: 'Conditional 2' },
    { id: 'en7-g3', type: 'Grammar', question: 'She ___ (visit) London twice this year.', answer: 'has visited', options: ['has visited', 'visited', 'visit'], instruction: 'Present perfect' },
    { id: 'en7-g4', type: 'Grammar', question: 'They ___ (be) married for ten years.', answer: 'have been', options: ['have been', 'were', 'had been'], instruction: 'Present perfect' },
    { id: 'en7-g5', type: 'Grammar', question: 'I ___ (think) about it for a long time.', answer: 'have been thinking', options: ['have been thinking', 'think', 'thought'], instruction: 'Present perfect continuous' },
    { id: 'en7-g6', type: 'Grammar', question: 'He ___ (work) here since 2012.', answer: 'has been working', options: ['has been working', 'works', 'worked'], instruction: 'Present perfect continuous' },
    { id: 'en7-g7', type: 'Grammar', question: 'The book ___ (write) by a famous author.', answer: 'was written', options: ['was written', 'wrote', 'is writing'], instruction: 'Passive voice' },
    { id: 'en7-g8', type: 'Grammar', question: 'The walls ___ (paint) last week.', answer: 'were painted', options: ['were painted', 'painted', 'are painted'], instruction: 'Passive voice' },
    { id: 'en7-g9', type: 'Grammar', question: 'You ___ (not / smoke) here; it\'s forbidden.', answer: 'mustn\'t', options: ['mustn\'t', 'don\'t have to', 'can\'t'], instruction: 'Modal verbs' },
    { id: 'en7-g10', type: 'Grammar', question: 'You ___ (not / come) if you don\'t want to.', answer: 'don\'t have to', options: ['don\'t have to', 'mustn\'t', 'shouldn\'t'], instruction: 'Modal verbs' },
    { id: 'en7-g11', type: 'Grammar', question: 'Relative: The car ___ he bought is fast.', answer: 'which', options: ['which', 'who', 'whose'], instruction: 'Relative pronouns' },
    { id: 'en7-g12', type: 'Grammar', question: 'Relative: The boy ___ father is a doctor.', answer: 'whose', options: ['whose', 'who', 'whom'], instruction: 'Relative pronouns' },
    { id: 'en7-g13', type: 'Grammar', question: 'Relative: The place ___ I was born.', answer: 'where', options: ['where', 'when', 'which'], instruction: 'Relative adverbs' },
    { id: 'en7-g14', type: 'Grammar', question: 'Relative: The day ___ we met.', answer: 'when', options: ['when', 'where', 'which'], instruction: 'Relative adverbs' },
    { id: 'en7-g15', type: 'Grammar', question: 'Question tag: You are happy, ___?', answer: 'aren\'t you', options: ['aren\'t you', 'are you', 'don\'t you'], instruction: 'Question tags' },
    { id: 'en7-g16', type: 'Grammar', question: 'Question tag: He likes cake, ___?', answer: 'doesn\'t he', options: ['doesn\'t he', 'does he', 'isn\'t he'], instruction: 'Question tags' },
    { id: 'en7-g17', type: 'Grammar', question: 'Question tag: They won the game, ___?', answer: 'didn\'t they', options: ['didn\'t they', 'won\'t they', 'did they'], instruction: 'Question tags' },
    { id: 'en7-g18', type: 'Grammar', question: 'Question tag: I am right, ___?', answer: 'aren\'t I', options: ['aren\'t I', 'am I not', 'don\'t I'], instruction: 'Irregular tags' },
    { id: 'en7-g19', type: 'Grammar', question: 'Use "Used to" to describe ___ habits.', answer: 'past', options: ['past', 'present', 'future'], instruction: 'Used to' },
    { id: 'en7-g20', type: 'Grammar', question: 'I ___ (play) piano when I was young.', answer: 'used to play', options: ['used to play', 'am playing', 'play'], instruction: 'Used to' },
    { id: 'en7-g21', type: 'Grammar', question: 'Gerund or Infinitive: I enjoy ___ (read).', answer: 'reading', options: ['reading', 'to read'], instruction: 'Verb patterns' },
    { id: 'en7-g22', type: 'Grammar', question: 'Gerund or Infinitive: I hope ___ (see) you.', answer: 'to see', options: ['to see', 'seeing'], instruction: 'Verb patterns' },
    { id: 'en7-g23', type: 'Grammar', question: 'Gerund or Infinitive: He decided ___ (go).', answer: 'to go', options: ['to go', 'going'], instruction: 'Verb patterns' },
    { id: 'en7-g24', type: 'Grammar', question: 'Gerund or Infinitive: She suggested ___ (wait).', answer: 'waiting', options: ['waiting', 'to wait'], instruction: 'Verb patterns' },
    { id: 'en7-g25', type: 'Grammar', question: 'Which is an "Abstract noun"?', answer: 'Love', options: ['Love', 'Table', 'Dog'], instruction: 'Word classes' },
    { id: 'en7-g26', type: 'Grammar', question: 'Which is a "Proper noun"?', answer: 'Paris', options: ['Paris', 'City', 'Place'], instruction: 'Word classes' },
    { id: 'en7-g27', type: 'Grammar', question: 'Which is a "Collective noun"?', answer: 'Team', options: ['Team', 'Player', 'He'], instruction: 'Word classes' },
    { id: 'en7-g28', type: 'Grammar', question: 'Comparative of "Bad":', answer: 'Worse', options: ['Worse', 'Badder', 'Worst'], instruction: 'Adjectives' },
    { id: 'en7-g29', type: 'Grammar', question: 'Superlative of "Far":', answer: 'Farthest/Furthest', options: ['Farthest/Furthest', 'Farrest', 'Most far'], instruction: 'Adjectives' },
    { id: 'en7-g30', type: 'Grammar', question: '"He sings ___ (well / good)." (Adverb)', answer: 'well', options: ['well', 'good'], instruction: 'Adverbs' },
    { id: 'en7-g31', type: 'Grammar', question: '"The cake smells ___ (good / well)." (Adjective)', answer: 'good', options: ['good', 'well'], instruction: 'Sense verbs' },
    { id: 'en7-g32', type: 'Grammar', question: '"She looks ___ (beautiful / beautifully)." (Adjective)', answer: 'beautiful', options: ['beautiful', 'beautifully'], instruction: 'Sense verbs' },
    { id: 'en7-g33', type: 'Grammar', question: 'Identify the conjunction: "I went because I was invited."', answer: 'because', options: ['because', 'went', 'invited'], instruction: 'Word classes' },
    { id: 'en7-g34', type: 'Grammar', question: 'Identify the interjection: "Wow! That was great."', answer: 'Wow', options: ['Wow', 'That', 'great'], instruction: 'Word classes' },
    { id: 'en7-g35', type: 'Grammar', question: '"___ he arrives, I will leave."', answer: 'When', options: ['When', 'How', 'Who'], instruction: 'Temporal clauses' },
    { id: 'en7-g36', type: 'Grammar', question: '"I haven\'t finished ___."', answer: 'yet', options: ['yet', 'already', 'ever'], instruction: 'Perfect markers' },
    { id: 'en7-g37', type: 'Grammar', question: '"I have ___ finished."', answer: 'already', options: ['already', 'yet', 'ever'], instruction: 'Perfect markers' },
    { id: 'en7-g38', type: 'Grammar', question: 'Reported: "I am hungry" -> He said he ___ hungry.', answer: 'was', options: ['was', 'is', 'be'], instruction: 'Reported speech' },
    { id: 'en7-g39', type: 'Grammar', question: 'Reported: "We will go" -> They said they ___ go.', answer: 'would', options: ['would', 'will', 'shall'], instruction: 'Reported speech' },
    { id: 'en7-g40', type: 'Grammar', question: 'Plural of "Series":', answer: 'Series', options: ['Series', 'Serieses', 'Seri'], instruction: 'Number' },
    { id: 'en7-g41', type: 'Grammar', question: 'Plural of "Criterion":', answer: 'Criteria', options: ['Criteria', 'Criterions', 'Criterias'], instruction: 'Foreign plurals' },
    { id: 'en7-g42', type: 'Grammar', question: 'Plural of "Phenomenon":', answer: 'Phenomena', options: ['Phenomena', 'Phenomenons', 'Phenomenas'], instruction: 'Foreign plurals' },
    { id: 'en7-g43', type: 'Grammar', question: 'Opposite of "Arrive":', answer: 'Depart', options: ['Depart', 'Enter', 'Stay'], instruction: 'Vocabulary' },
    { id: 'en7-g44', type: 'Grammar', question: 'Opposite of "Success":', answer: 'Failure', options: ['Failure', 'Win', 'Gain'], instruction: 'Vocabulary' },
    { id: 'en7-g45', type: 'Grammar', question: 'Correct: "Its" or "It\'s" (possessive)?', answer: 'Its', options: ['Its', 'It\'s'], instruction: 'Punctuation' },
    { id: 'en7-g46', type: 'Grammar', question: 'Correct: "It\'s" or "Its" (it is)?', answer: 'It\'s', options: ['It\'s', 'Its'], instruction: 'Punctuation' },
    { id: 'en7-g47', type: 'Grammar', question: 'Correct: "Their", "There", or "They\'re" (place)?', answer: 'There', options: ['There', 'Their', 'They\'re'], instruction: 'Homophones' },
    { id: 'en7-g48', type: 'Grammar', question: 'Correct: "Their", "There", or "They\'re" (possessive)?', answer: 'Their', options: ['Their', 'There', 'They\'re'], instruction: 'Homophones' },
    { id: 'en7-g49', type: 'Grammar', question: 'Correct: "Their", "There", or "They\'re" (they are)?', answer: 'They\'re', options: ['They\'re', 'Their', 'There'], instruction: 'Homophones' },
    { id: 'en7-g50', type: 'Grammar', question: 'Which is a "Determiner"?', answer: 'Every', options: ['Every', 'Always', 'Quickly'], instruction: 'Word classes' },
    { id: 'en7-g51', type: 'Grammar', question: 'Doing ___!', answer: 'great', options: ['great', 'bad', 'car'], instruction: 'Feedback' },
  ],
  8: [
    { id: 'en8-g1', type: 'Grammar', question: 'If he ___ (study) harder, he would have passed.', answer: 'had studied', options: ['had studied', 'studied', 'did study'], instruction: 'Conditional 3' },
    { id: 'en8-g2', type: 'Grammar', question: 'I would have gone if I ___ (know).', answer: 'had known', options: ['had known', 'knew', 'known'], instruction: 'Conditional 3' },
    { id: 'en8-g3', type: 'Grammar', question: 'The report ___ (finish) by tomorrow.', answer: 'will be finished', options: ['will be finished', 'is finished', 'was finished'], instruction: 'Passive voice' },
    { id: 'en8-g4', type: 'Grammar', question: 'By next year, I ___ (live) here for a decade.', answer: 'will have lived', options: ['will have lived', 'will live', 'have lived'], instruction: 'Future perfect' },
    { id: 'en8-g5', type: 'Grammar', question: 'Used for an action completed before another past action:', answer: 'Past perfect', options: ['Past perfect', 'Present perfect', 'Future perfect'], instruction: 'Tenses' },
    { id: 'en8-g6', type: 'Grammar', question: 'I ___ (think) of you when I called.', answer: 'was thinking', options: ['was thinking', 'thought', 'think'], instruction: 'Past continuous' },
    { id: 'en8-g7', type: 'Grammar', question: 'They ___ (play) cards while waiting.', answer: 'were playing', options: ['were playing', 'played', 'play'], instruction: 'Past continuous' },
    { id: 'en8-g8', type: 'Grammar', question: 'I wish I ___ (be) taller.', answer: 'were', options: ['were', 'was', 'am'], instruction: 'Subjunctive' },
    { id: 'en8-g9', type: 'Grammar', question: 'I wish I ___ (have) more time.', answer: 'had', options: ['had', 'have', 'did have'], instruction: 'Wish clauses' },
    { id: 'en8-g10', type: 'Grammar', question: 'Relative: The company ___ makes the cars.', answer: 'that/which', options: ['that/which', 'who', 'whom'], instruction: 'Relative pronouns' },
    { id: 'en8-g11', type: 'Grammar', question: 'Relative: The person ___ you spoke to.', answer: 'whom/that', options: ['whom/that', 'whose', 'which'], instruction: 'Relative pronouns' },
    { id: 'en8-g12', type: 'Grammar', question: 'Gerund or Infinitive: I stop ___ (smoke). (Habit)', answer: 'smoking', options: ['smoking', 'to smoke'], instruction: 'Verb patterns' },
    { id: 'en8-g13', type: 'Grammar', question: 'Gerund or Infinitive: I stopped ___ (smoke). (Interruption)', answer: 'to smoke', options: ['to smoke', 'smoking'], instruction: 'Verb patterns' },
    { id: 'en8-g14', type: 'Grammar', question: 'Modal of deduction (sure): He ___ be at home.', answer: 'must', options: ['must', 'might', 'can\'t'], instruction: 'Modals' },
    { id: 'en8-g15', type: 'Grammar', question: 'Modal of deduction (possible): He ___ be at home.', answer: 'might', options: ['might', 'must', 'can\'t'], instruction: 'Modals' },
    { id: 'en8-g16', type: 'Grammar', question: 'Modal of deduction (impossible): He ___ be at home.', answer: 'can\'t', options: ['can\'t', 'must', 'might'], instruction: 'Modals' },
    { id: 'en8-g17', type: 'Grammar', question: 'Is "Nonetheless" a conjunctive adverb?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en8-g18', type: 'Grammar', question: 'Is "Furthermore" a conjunctive adverb?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en8-g19', type: 'Grammar', question: 'Phrasal Verb: "Look ___" (to investigate).', answer: 'into', options: ['into', 'at', 'for'], instruction: 'Phrasal verbs' },
    { id: 'en8-g20', type: 'Grammar', question: 'Phrasal Verb: "Give ___" (to stop doing something).', answer: 'up', options: ['up', 'in', 'away'], instruction: 'Phrasal verbs' },
    { id: 'en8-g21', type: 'Grammar', question: 'Phrasal Verb: "Run ___" (to meet by chance).', answer: 'into', options: ['into', 'after', 'with'], instruction: 'Phrasal verbs' },
    { id: 'en8-g22', type: 'Grammar', question: '"Despite ___ the rain, we went out."', answer: 'of', options: ['(nothing)', 'of'], instruction: 'Prepositions' },
    { id: 'en8-g23', type: 'Grammar', question: '"In spite ___ the rain, we went out."', answer: 'of', options: ['of', '(nothing)'], instruction: 'Prepositions' },
    { id: 'en8-g24', type: 'Grammar', question: 'Reported: "What are you doing?" -> He asked me what I ___ doing.', answer: 'was', options: ['was', 'is', 'be'], instruction: 'Reported speech' },
    { id: 'en8-g25', type: 'Grammar', question: 'Reported: "Can you help?" -> She asked if I ___ help.', answer: 'could', options: ['could', 'can', 'will'], instruction: 'Reported speech' },
    { id: 'en8-g26', type: 'Grammar', question: 'Which is a "Compound sentence"?', answer: 'I like tea and she likes coffee', options: ['I like tea and she likes coffee', 'I like tea because it is hot', 'I like tea'], instruction: 'Sentence types' },
    { id: 'en8-g27', type: 'Grammar', question: 'Which is a "Complex sentence"?', answer: 'I will go if you stay', options: ['I will go if you stay', 'I will go and you stay', 'I will go'], instruction: 'Sentence types' },
    { id: 'en8-g28', type: 'Grammar', question: 'Is "Neither... nor" a correlative conjunction?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en8-g29', type: 'Grammar', question: 'Is "Either... or" a correlative conjunction?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Word classes' },
    { id: 'en8-g30', type: 'Grammar', question: 'Collective noun for birds: A ___ of birds.', answer: 'flock', options: ['flock', 'herd', 'pack'], instruction: 'Nouns' },
    { id: 'en8-g31', type: 'Grammar', question: 'Collective noun for wolves: A ___ of wolves.', answer: 'pack', options: ['pack', 'flock', 'herd'], instruction: 'Nouns' },
    { id: 'en8-g32', type: 'Grammar', question: 'Collective noun for cows: A ___ of cows.', answer: 'herd', options: ['herd', 'pack', 'school'], instruction: 'Nouns' },
    { id: 'en8-g33', type: 'Grammar', question: 'Collective noun for fish: A ___ of fish.', answer: 'school', options: ['school', 'flock', 'troop'], instruction: 'Nouns' },
    { id: 'en8-g34', type: 'Grammar', question: 'Opposite of "Broad":', answer: 'Narrow', options: ['Narrow', 'Wide', 'Flat'], instruction: 'Vocabulary' },
    { id: 'en8-g35', type: 'Grammar', question: 'Opposite of "Rough":', answer: 'Smooth', options: ['Smooth', 'Hard', 'Big'], instruction: 'Vocabulary' },
    { id: 'en8-g36', type: 'Grammar', question: 'Opposite of "Complex":', answer: 'Simple', options: ['Simple', 'Hard', 'Tough'], instruction: 'Vocabulary' },
    { id: 'en8-g37', type: 'Grammar', question: 'Opposite of "Modern":', answer: 'Ancient', options: ['Ancient', 'New', 'Fresh'], instruction: 'Vocabulary' },
    { id: 'en8-g38', type: 'Grammar', question: 'Spell 1,000,000 correctly:', answer: 'Million', options: ['Million', 'Milion', 'Millyon'], instruction: 'Spelling' },
    { id: 'en8-g39', type: 'Grammar', question: 'Identify the "Appositive": "My friend, John, is tall."', answer: 'John', options: ['John', 'friend', 'tall'], instruction: 'Sentence analysis' },
    { id: 'en8-g40', type: 'Grammar', question: 'Identify the "Adverbial clause": "I left when it rained."', answer: 'when it rained', options: ['when it rained', 'I left'], instruction: 'Sentence analysis' },
    { id: 'en8-g41', type: 'Grammar', question: 'Identify the "Noun clause": "What he said was true."', answer: 'What he said', options: ['What he said', 'was true'], instruction: 'Sentence analysis' },
    { id: 'en8-g42', type: 'Grammar', question: 'Is "To be or not to be" an infinitive phrase?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Phrases' },
    { id: 'en8-g43', type: 'Grammar', question: 'Is "Walking down the street" a participial phrase?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Phrases' },
    { id: 'en8-g44', type: 'Grammar', question: 'Which is "Ambitious"?', answer: 'Wanting success', options: ['Wanting success', 'Being lazy', 'Sleeping a lot'], instruction: 'Vocabulary' },
    { id: 'en8-g45', type: 'Grammar', question: 'Which is "Generous"?', answer: 'Giving to others', options: ['Giving to others', 'Keeping for self', 'Being mean'], instruction: 'Vocabulary' },
    { id: 'en8-g46', type: 'Grammar', question: 'Correct: "Who\'s" or "Whose" (who is)?', answer: 'Who\'s', options: ['Who\'s', 'Whose'], instruction: 'Punctuation' },
    { id: 'en8-g47', type: 'Grammar', question: 'Correct: "Whose" or "Who\'s" (possessive)?', answer: 'Whose', options: ['Whose', 'Who\'s'], instruction: 'Punctuation' },
    { id: 'en8-g48', type: 'Grammar', question: 'Correct: "Effect" (noun) or "Affect" (verb)?', answer: 'Effect', options: ['Effect', 'Affect'], instruction: 'Homophones' },
    { id: 'en8-g49', type: 'Grammar', question: 'Correct: "Affect" (verb) or "Effect" (noun)?', answer: 'Affect', options: ['Affect', 'Effect'], instruction: 'Homophones' },
    { id: 'en8-g50', type: 'Grammar', question: 'Identify the gerund: "Dancing is fun."', answer: 'Dancing', options: ['Dancing', 'fun', 'is'], instruction: 'Word classes' },
    { id: 'en8-g51', type: 'Grammar', question: 'Phenomenal ___!', answer: 'effort', options: ['effort', 'bad', 'car'], instruction: 'Feedback' },
  ],
  9: [
    { id: 'en9-g1', type: 'Grammar', question: 'If I ___ (win) the lottery, I would travel.', answer: 'won', options: ['won', 'had won', 'win'], instruction: 'Conditional 2' },
    { id: 'en9-g2', type: 'Grammar', question: 'If you had asked, I ___ (help).', answer: 'would have helped', options: ['would have helped', 'will help', 'helped'], instruction: 'Conditional 3' },
    { id: 'en9-g3', type: 'Grammar', question: 'Hardly had I arrived ___ he left.', answer: 'when', options: ['when', 'than', 'before'], instruction: 'Inversion/Markers' },
    { id: 'en9-g4', type: 'Grammar', question: 'No sooner had I eaten ___ I felt sick.', answer: 'than', options: ['than', 'when', 'so'], instruction: 'Inversion/Markers' },
    { id: 'en9-g5', type: 'Grammar', question: 'Had I known, I ___ (stay) longer.', answer: 'would have stayed', options: ['would have stayed', 'will stay', 'stayed'], instruction: 'Inversion' },
    { id: 'en9-g6', type: 'Grammar', question: 'The project ___ (complete) by next Monday.', answer: 'will have been completed', options: ['will have been completed', 'is completed', 'has completed'], instruction: 'Future perfect passive' },
    { id: 'en9-g7', type: 'Grammar', question: 'He is reported ___ (live) in USA.', answer: 'to live', options: ['to live', 'lives', 'living'], instruction: 'Reporting structure' },
    { id: 'en9-g8', type: 'Grammar', question: 'I suggest that he ___ (be) present.', answer: 'be', options: ['be', 'is', 'am'], instruction: 'Subjunctive' },
    { id: 'en9-g9', type: 'Grammar', question: 'It is important that they ___ (decide) soon.', answer: 'decide', options: ['decide', 'decides', 'decided'], instruction: 'Subjunctive' },
    { id: 'en9-g10', type: 'Grammar', question: 'Should you ___ (need) help, call me.', answer: 'need', options: ['need', 'needs', 'needed'], instruction: 'Inversion (Conditional)' },
    { id: 'en9-g11', type: 'Grammar', question: 'Were I ___ (be) king, I\'d be happy.', answer: 'to be', options: ['to be', 'be', 'being'], instruction: 'Inversion (Conditional)' },
    { id: 'en9-g12', type: 'Grammar', question: 'The man ___ I spoke with is nice.', answer: 'whom', options: ['whom', 'who', 'which'], instruction: 'Relative pronouns' },
    { id: 'en9-g13', type: 'Grammar', question: 'Whose dog is that? It\'s ___ (possessive pronoun).', answer: 'ours', options: ['ours', 'our', 'us'], instruction: 'Possessives' },
    { id: 'en9-g14', type: 'Grammar', question: 'Gerund after preposition: I look forward to ___ you.', answer: 'seeing', options: ['seeing', 'see', 'seen'], instruction: 'Gerunds' },
    { id: 'en9-g15', type: 'Grammar', question: 'Phrasal Verb: "Call ___" (to cancel).', answer: 'off', options: ['off', 'on', 'up'], instruction: 'Phrasal verbs' },
    { id: 'en9-g16', type: 'Grammar', question: 'Phrasal Verb: "Put ___ with" (to tolerate).', answer: 'up', options: ['up', 'off', 'on'], instruction: 'Phrasal verbs' },
    { id: 'en9-g17', type: 'Grammar', question: 'Phrasal Verb: "Make ___ for" (to compensate).', answer: 'up', options: ['up', 'off', 'on'], instruction: 'Phrasal verbs' },
    { id: 'en9-g18', type: 'Grammar', question: 'Which is a "Transitive verb"?', answer: 'Eat (needs object)', options: ['Eat', 'Sleep', 'Run'], instruction: 'Verb types' },
    { id: 'en9-g19', type: 'Grammar', question: 'Which is an "Intransitive verb"?', answer: 'Sleep', options: ['Sleep', 'Eat', 'Watch'], instruction: 'Verb types' },
    { id: 'en9-g20', type: 'Grammar', question: 'Identify the "Dangling participle":', answer: 'Walking home, the rain started', options: ['Walking home, the rain started', 'Walking home, I saw him'], instruction: 'Error analysis' },
    { id: 'en9-g21', type: 'Grammar', question: 'Parallelism: "I like swimming and ___."', answer: 'dancing', options: ['dancing', 'to dance', 'dance'], instruction: 'Sentence structure' },
    { id: 'en9-g22', type: 'Grammar', question: 'Which is an "Oxymoron"?', answer: 'Deafening silence', options: ['Deafening silence', 'Running water', 'Blue sky'], instruction: 'Figures of speech' },
    { id: 'en9-g23', type: 'Grammar', question: 'Which is a "Metaphor"?', answer: 'He has a heart of stone', options: ['He has a heart of stone', 'He is like a rock', 'He runs fast'], instruction: 'Figures of speech' },
    { id: 'en9-g24', type: 'Grammar', question: 'Which is a "Simile"?', answer: 'He is as brave as a lion', options: ['He is as brave as a lion', 'He is a lion', 'The lion roared'], instruction: 'Figures of speech' },
    { id: 'en9-g25', type: 'Grammar', question: 'Which word is "Pretentious"?', answer: 'Showing off', options: ['Showing off', 'Being shy', 'Working hard'], instruction: 'Vocabulary' },
    { id: 'en9-g26', type: 'Grammar', question: 'Opposite of "Vague":', answer: 'Specific', options: ['Specific', 'Loose', 'Large'], instruction: 'Vocabulary' },
    { id: 'en9-g27', type: 'Grammar', question: 'Opposite of "Obscure":', answer: 'Well-known', options: ['Well-known', 'Hidden', 'Strange'], instruction: 'Vocabulary' },
    { id: 'en9-g28', type: 'Grammar', question: 'Opposite of "Fragile":', answer: 'Robust', options: ['Robust', 'Soft', 'Weak'], instruction: 'Vocabulary' },
    { id: 'en9-g29', type: 'Grammar', question: 'Identify the "Subject-Verb disagreement":', answer: 'They is here', options: ['They is here', 'They are here', 'He is here'], instruction: 'Error analysis' },
    { id: 'en9-g30', type: 'Grammar', question: 'Countable or Uncountable: Progress.', answer: 'Uncountable', options: ['Uncountable', 'Countable'], instruction: 'Nouns' },
    { id: 'en9-g31', type: 'Grammar', question: 'Countable or Uncountable: Idea.', answer: 'Countable', options: ['Countable', 'Uncountable'], instruction: 'Nouns' },
    { id: 'en9-g32', type: 'Grammar', question: 'Countable or Uncountable: Knowledge.', answer: 'Uncountable', options: ['Uncountable', 'Countable'], instruction: 'Nouns' },
    { id: 'en9-g33', type: 'Grammar', question: 'Is "Nonetheless" a transition word?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Writing' },
    { id: 'en9-g34', type: 'Grammar', question: 'Is "Therefore" a transition word?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Writing' },
    { id: 'en9-g35', type: 'Grammar', question: 'Is "Moreover" a transition word?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Writing' },
    { id: 'en9-g36', type: 'Grammar', question: 'Spell "Environment" correctly:', answer: 'Environment', options: ['Environment', 'Enviroment', 'Enviremont'], instruction: 'Spelling' },
    { id: 'en9-g37', type: 'Grammar', question: 'Spell "Sovereignty" correctly:', answer: 'Sovereignty', options: ['Sovereignty', 'Soverignty', 'Sovereinty'], instruction: 'Spelling' },
    { id: 'en9-g38', type: 'Grammar', question: 'What is a "Syntactic" error?', answer: 'Error in sentence structure', options: ['Error in sentence structure', 'Error in spelling', 'Error in meaning'], instruction: 'Grammar terms' },
    { id: 'en9-g39', type: 'Grammar', question: 'What is "Morphology"?', answer: 'Study of word forms', options: ['Study of word forms', 'Study of sentence structure', 'Study of sounds'], instruction: 'Grammar terms' },
    { id: 'en9-g40', type: 'Grammar', question: 'Identify the "Passive" voice:', answer: 'The letter was sent', options: ['The letter was sent', 'I sent the letter'], instruction: 'Verbs' },
    { id: 'en9-g41', type: 'Grammar', question: 'Identify the "Active" voice:', answer: 'I ate the apple', options: ['I ate the apple', 'The apple was eaten'], instruction: 'Verbs' },
    { id: 'en9-g42', type: 'Grammar', question: 'Correct: "Whom did you see?" or "Who did you see?" (Formal)', answer: 'Whom', options: ['Whom', 'Who'], instruction: 'Style' },
    { id: 'en9-g43', type: 'Grammar', question: '"___ he arrived early, he would have waited outside."', answer: 'Had', options: ['Had', 'Did', 'If'], instruction: 'Inversion (Conditional)' },
    { id: 'en9-g44', type: 'Grammar', question: 'Relative: The theory ___ he based his book on.', answer: 'which', options: ['which', 'who', 'whom'], instruction: 'Relative pronouns' },
    { id: 'en9-g45', type: 'Grammar', question: 'Use "For" or "Since": eternity.', answer: 'for', options: ['for', 'since'], instruction: 'Time' },
    { id: 'en9-g46', type: 'Grammar', question: 'Use "For" or "Since": time immemorial.', answer: 'since', options: ['since', 'for'], instruction: 'Time' },
    { id: 'en9-g47', type: 'Grammar', question: 'Is "Shall" more formal than "Will"?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Style' },
    { id: 'en9-g48', type: 'Grammar', question: 'Identify the "Gerund phrase": "Running marathons is hard."', answer: 'Running marathons', options: ['Running marathons', 'is hard'], instruction: 'Phrases' },
    { id: 'en9-g49', type: 'Grammar', question: 'Identify the "Prep phrase": "In the house."', answer: 'In the house', options: ['In the house'], instruction: 'Phrases' },
    { id: 'en9-g50', type: 'Grammar', question: 'Is "Irony" when the opposite happens?', answer: 'Yes', options: ['Yes', 'No'], instruction: 'Literary terms' },
    { id: 'en9-g51', type: 'Grammar', question: 'Stellar ___!', answer: 'performance', options: ['performance', 'bad', 'car'], instruction: 'Feedback' },
  ],
};
