/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const FRANSK_GRAMMAR_P2: Partial<Record<Grade, GameContent[]>> = {
  5: [
    { id: 'fr5-g1', type: 'Grammar', question: 'Hvad betyder "Finir"?', answer: 'At slutte', options: ['At slutte', 'At starte', 'At se'], instruction: 'Verbes en -ir' },
    { id: 'fr5-g2', type: 'Grammar', question: 'Hvordan bøjes "Finir" i "Je"?', answer: 'finis', options: ['finis', 'finit', 'finissons'], instruction: 'Verbes en -ir' },
    { id: 'fr5-g3', type: 'Grammar', question: 'Hvordan bøjes "Finir" i "Nous"?', answer: 'finissons', options: ['finissons', 'finissez', 'finissent'], instruction: 'Verbes en -ir' },
    { id: 'fr5-g4', type: 'Grammar', question: 'Hvad betyder "Choisir"?', answer: 'At vælge', options: ['At vælge', 'At gemme', 'At finde'], instruction: 'Verbes en -ir' },
    { id: 'fr5-g5', type: 'Grammar', question: 'Hvad betyder "Attendre"?', answer: 'At vente', options: ['At vente', 'At høre', 'At se'], instruction: 'Verbes en -re' },
    { id: 'fr5-g6', type: 'Grammar', question: 'Hvordan bøjes "Attendre" i "Je"?', answer: 'attends', options: ['attends', 'attend', 'attendons'], instruction: 'Verbes en -re' },
    { id: 'fr5-g7', type: 'Grammar', question: 'Hvordan bøjes "Attendre" i "Nous"?', answer: 'attendons', options: ['attendons', 'attendez', 'attendent'], instruction: 'Verbes en -re' },
    { id: 'fr5-g8', type: 'Grammar', question: 'Hvad betyder "Vendre"?', answer: 'At sælge', options: ['At sælge', 'At købe', 'At bytte'], instruction: 'Verbes en -re' },
    { id: 'fr5-g9', type: 'Grammar', question: 'Hvad betyder "Répondre"?', answer: 'At svare', options: ['At svare', 'At spørge', 'At råbe'], instruction: 'Verbes en -re' },
    { id: 'fr5-g10', type: 'Grammar', question: 'Hvad betyder "Prise"?', answer: 'Taget', options: ['Taget', 'Givet', 'Set'], instruction: 'Participes passés' },
    { id: 'fr5-g11', type: 'Grammar', question: 'Hvad betyder "Mis"?', answer: 'Sat/lagt', options: ['Sat/lagt', 'Gået', 'Kommet'], instruction: 'Participes passés' },
    { id: 'fr5-g12', type: 'Grammar', question: 'Hvad betyder "Vu"?', answer: 'Set', options: ['Set', 'Hørt', 'Læst'], instruction: 'Participes passés' },
    { id: 'fr5-g13', type: 'Grammar', question: 'Hvad betyder "Dû"?', answer: 'Skullet', options: ['Skullet', 'Kunnet', 'Villet'], instruction: 'Participes passés' },
    { id: 'fr5-g14', type: 'Grammar', question: 'Hvad betyder "Pu"?', answer: 'Kunnet', options: ['Kunnet', 'Skullet', 'Villet'], instruction: 'Participes passés' },
    { id: 'fr5-g15', type: 'Grammar', question: 'Hvad betyder "Voulu"?', answer: 'Villet', options: ['Villet', 'Kunnet', 'Skullet'], instruction: 'Participes passés' },
    { id: 'fr5-g16', type: 'Grammar', question: 'Hvad betyder "Inquiète"?', answer: 'Bekymret', options: ['Bekymret', 'Rolig', 'Glad'], instruction: 'Adjectifs' },
    { id: 'fr5-g17', type: 'Grammar', question: 'Hvad betyder "Tranquille"?', answer: 'Rolig', options: ['Rolig', 'Larmende', 'Hurtig'], instruction: 'Adjectifs' },
    { id: 'fr5-g18', type: 'Grammar', question: 'Hvad betyder "Bruit"?', answer: 'Støj', options: ['Støj', 'Musik', 'Stilhed'], instruction: 'Vocabulaire' },
    { id: 'fr5-g19', type: 'Grammar', question: 'Hvad betyder "Silence"?', answer: 'Stilhed', options: ['Stilhed', 'Støj', 'Larm'], instruction: 'Vocabulaire' },
    { id: 'fr5-g20', type: 'Grammar', question: 'Hvad betyder "L\’avenir"?', answer: 'Fremtiden', options: ['Fremtiden', 'Fortiden', 'Nutiden'], instruction: 'Vocabulaire' },
    { id: 'fr5-g21', type: 'Grammar', question: 'Hvad betyder "Le passé"?', answer: 'Fortiden', options: ['Fortiden', 'Fremtiden', 'Nutiden'], instruction: 'Vocabulaire' },
    { id: 'fr5-g22', type: 'Grammar', question: 'Hvad betyder "Le présent"?', answer: 'Nutiden', options: ['Nutiden', 'Fremtiden', 'Fortiden'], instruction: 'Vocabulaire' },
    { id: 'fr5-g23', type: 'Grammar', question: 'Hvordan siger man "Næste år"?', answer: 'L’année prochaine', options: ['L’année prochaine', 'L’année dernière', 'Cette année'], instruction: 'Temps' },
    { id: 'fr5-g24', type: 'Grammar', question: 'Hvordan siger man "Sidste år"?', answer: 'L’année dernière', options: ['L’année dernière', 'L’année prochaine', 'Cette år'], instruction: 'Temps' },
    { id: 'fr5-g25', type: 'Grammar', question: '"Son" eller "Sa"? ___ frère (hans bror)', answer: 'Son', options: ['Son', 'Sa'], instruction: 'Possessifs' },
    { id: 'fr5-g26', type: 'Grammar', question: '"Son" eller "Sa"? ___ sœur (hans søster)', answer: 'Sa', options: ['Sa', 'Son'], instruction: 'Possessifs' },
    { id: 'fr5-g27', type: 'Grammar', question: '"Leur" eller "Leurs"? ___ maison (deres hus)', answer: 'Leur', options: ['Leur', 'Leurs'], instruction: 'Possessifs (plural)' },
    { id: 'fr5-g28', type: 'Grammar', question: '"Leur" eller "Leurs"? ___ amis (deres venner)', answer: 'Leurs', options: ['Leurs', 'Leur'], instruction: 'Possessifs (plural)' },
    { id: 'fr5-g29', type: 'Grammar', question: 'Hvad betyder "Se lever"?', answer: 'At stå op', options: ['At stå op', 'At gå i seng', 'At vaske sig'], instruction: 'Verbes réfléchis' },
    { id: 'fr5-g30', type: 'Grammar', question: 'Hvad betyder "Se coucher"?', answer: 'At gå i seng', options: ['At gå i seng', 'At stå op', 'At spise'], instruction: 'Verbes réfléchis' },
    { id: 'fr5-g31', type: 'Grammar', question: 'Indsæt refleksivt: Je ___ lave.', answer: 'me', options: ['me', 'te', 'se'], instruction: 'Verbes réfléchis' },
    { id: 'fr5-g32', type: 'Grammar', question: 'Indsæt refleksivt: Tu ___ laves.', answer: 'te', options: ['te', 'me', 'se'], instruction: 'Verbes réfléchis' },
    { id: 'fr5-g33', type: 'Grammar', question: 'Indsæt refleksivt: Il ___ lave.', answer: 'se', options: ['se', 'me', 'te'], instruction: 'Verbes réfléchis' },
    { id: 'fr5-g34', type: 'Grammar', question: 'Indsæt refleksivt: Nous ___ lavons.', answer: 'nous', options: ['nous', 'vous', 'se'], instruction: 'Verbes réfléchis' },
    { id: 'fr5-g35', type: 'Grammar', question: 'Indsæt refleksivt: Vous ___ lavez.', answer: 'vous', options: ['vous', 'nous', 'se'], instruction: 'Verbes réfléchis' },
    { id: 'fr5-g36', type: 'Grammar', question: 'Indsæt refleksivt: Ils ___ lavent.', answer: 'se', options: ['se', 'nous', 'vous'], instruction: 'Verbes réfléchis' },
    { id: 'fr5-g37', type: 'Grammar', question: 'Hvad betyder "L\’argents"?', answer: 'Pengene', options: ['Pengene', 'Sølv', 'Guld'], instruction: 'Vocabulaire' },
    { id: 'fr5-g38', type: 'Grammar', question: 'Hvad betyder "Le temps"?', answer: 'Tiden / Vejret', options: ['Tiden / Vejret', 'Landet', 'Byen'], instruction: 'Vocabulaire' },
    { id: 'fr5-g39', type: 'Grammar', question: 'Hvad betyder "Le travail"?', answer: 'Arbejdet', options: ['Arbejdet', 'Fritiden', 'Skolen'], instruction: 'Vocabulaire' },
    { id: 'fr5-g40', type: 'Grammar', question: 'Hvad betyder "La santé"?', answer: 'Sundheden', options: ['Sundheden', 'Sygdommen', 'Medicinen'], instruction: 'Vocabulaire' },
    { id: 'fr5-g41', type: 'Grammar', question: '"Du", "de la" eller "des"? ___ pain (noget brød)', answer: 'Du', options: ['Du', 'De la', 'Des'], instruction: 'Partitifs' },
    { id: 'fr5-g42', type: 'Grammar', question: '"Du", "de la" eller "des"? ___ viande (noget kød)', answer: 'De la', options: ['De la', 'Du', 'Des'], instruction: 'Partitifs' },
    { id: 'fr5-g43', type: 'Grammar', question: '"Du", "de la" eller "des"? ___ pommes (nogle æbler)', answer: 'Des', options: ['Des', 'Du', 'De la'], instruction: 'Partitifs' },
    { id: 'fr5-g44', type: 'Grammar', question: 'Hvad betyder "Il fait chaud"?', answer: 'Det er varmt', options: ['Det er varmt', 'Det er koldt', 'Det regner'], instruction: 'Météo' },
    { id: 'fr5-g45', type: 'Grammar', question: 'Hvad betyder "Il fait froid"?', answer: 'Det er koldt', options: ['Det er koldt', 'Det er varmt', 'Det blæser'], instruction: 'Météo' },
    { id: 'fr5-g46', type: 'Grammar', question: 'Hvad betyder "Il pleut"?', answer: 'Det regner', options: ['Det regner', 'Det sner', 'Solen skinner'], instruction: 'Météo' },
    { id: 'fr5-g47', type: 'Grammar', question: 'Hvad betyder "Il neige"?', answer: 'Det sner', options: ['Det sner', 'Det regner', 'Det tordner'], instruction: 'Météo' },
    { id: 'fr5-g48', type: 'Grammar', question: 'Indsæt bøjning: Je ___ (finir).', answer: 'finis', options: ['finis', 'finit', 'finissent'], instruction: 'Verbes -ir' },
    { id: 'fr5-g49', type: 'Grammar', question: 'Indsæt bøjning: Vous ___ (finir).', answer: 'finissez', options: ['finissez', 'finissons', 'finissent'], instruction: 'Verbes -ir' },
    { id: 'fr5-g50', type: 'Grammar', question: 'Indsæt bøjning: Elles ___ (finir).', answer: 'finissent', options: ['finissent', 'finis', 'finit'], instruction: 'Verbes -ir' },
    { id: 'fr5-g51', type: 'Grammar', question: 'C\'est ___!', answer: 'brilliant', options: ['brilliant', 'mal', 'noir'], instruction: 'Feedback' },
  ],
  6: [
    { id: 'fr6-g1', type: 'Grammar', question: 'Hvordan siger man "Jeg"?', answer: 'Je', options: ['Je', 'Tu', 'Il'], instruction: 'Stedord' },
    { id: 'fr6-g2', type: 'Grammar', question: 'Hvordan siger man "Du"?', answer: 'Tu', options: ['Tu', 'Je', 'Elle'], instruction: 'Stedord' },
    { id: 'fr6-g3', type: 'Grammar', question: 'Indsæt: Je ___ Alba.', answer: 'm’appelle', options: ['m’appelle', 'suis', 'ai'], instruction: 'Præsentation' },
    { id: 'fr6-g4', type: 'Grammar', question: 'Hvad betyder "Salut"?', answer: 'Hej / Hej hej', options: ['Hej / Hej hej', 'Goddag', 'Farvel'], instruction: 'Hilsen' },
    { id: 'fr6-g5', type: 'Grammar', question: 'Hvilken kendeord bruges til piger? "___ fille"', answer: 'Une', options: ['Une', 'Un'], instruction: 'Kendeord' },
    { id: 'fr6-g6', type: 'Grammar', question: 'Hvilken kendeord bruges til drenge? "___ garçon"', answer: 'Un', options: ['Un', 'Une'], instruction: 'Kendeord' },
    { id: 'fr6-g7', type: 'Grammar', question: 'Oversæt: "Jeg er" (être).', answer: 'Je suis', options: ['Je suis', 'J’ai', 'Je vais'], instruction: 'Verber' },
    { id: 'fr6-g8', type: 'Grammar', question: 'Oversæt: "Jeg har" (avoir).', answer: 'J’ai', options: ['J’ai', 'Je suis', 'Tu as'], instruction: 'Verber' },
    { id: 'fr6-g9', type: 'Grammar', question: 'Hvad betyder "Ma famille"?', answer: 'Min familie', options: ['Min familie', 'Min ven', 'Min hund'], instruction: 'Besiddelse' },
    { id: 'fr6-g10', type: 'Grammar', question: 'Hvordan siger man "12"?', answer: 'Douze', options: ['Douze', 'Deux', 'Dix'], instruction: 'Tal' },
    { id: 'fr6-g11', type: 'Grammar', question: 'Hvad betyder "Au camping"?', answer: 'På campingpladsen', options: ['På campingpladsen', 'I skolen', 'Hjemme'], instruction: 'Sted' },
  ],
  7: [
    { id: 'fr7-g1', type: 'Grammar', question: '"Le", "La" eller "Les"? ___ pomme.', answer: 'La', options: ['Le', 'La', 'Les'], instruction: 'Articles' },
    { id: 'fr7-g2', type: 'Grammar', question: '"Le", "La" eller "Les"? ___ garçons.', answer: 'Les', options: ['Les', 'Le', 'La'], instruction: 'Articles (plural)' },
    { id: 'fr7-g3', type: 'Grammar', question: 'Hvilket tal er "Cinquante"?', answer: '50', options: ['50', '60', '40'], instruction: 'Nombres' },
    { id: 'fr7-g4', type: 'Grammar', question: 'Hvilket tal er "Soixante"?', answer: '60', options: ['60', '70', '50'], instruction: 'Nombres' },
    { id: 'fr7-g5', type: 'Grammar', question: 'Hvad betyder "Vouloir"?', answer: 'At ville', options: ['At ville', 'At skulle', 'At kunne'], instruction: 'Verbes' },
    { id: 'fr7-g6', type: 'Grammar', question: 'Bøjning af "Vouloir" (Je):', answer: 'veux', options: ['veux', 'veut', 'voulons'], instruction: 'Verbes' },
    { id: 'fr7-g7', type: 'Grammar', question: 'Hvad betyder "Pouvoir"?', answer: 'At kunne', options: ['At kunne', 'At ville', 'At måtte'], instruction: 'Verbes' },
    { id: 'fr7-g8', type: 'Grammar', question: 'Bøjning af "Pouvoir" (Je):', answer: 'peux', options: ['peux', 'peut', 'pouvons'], instruction: 'Verbes' },
    { id: 'fr7-g9', type: 'Grammar', question: 'Hvad betyder "Devoir"?', answer: 'At skulle', options: ['At skulle', 'At ville', 'At kunne'], instruction: 'Verbes' },
    { id: 'fr7-g10', type: 'Grammar', question: 'Bøjning af "Devoir" (Je):', answer: 'dois', options: ['dois', 'doit', 'devons'], instruction: 'Verbes' },
    { id: 'fr7-g11', type: 'Grammar', question: 'Hvilket ord betyder "Hvor"?', answer: 'Où', options: ['Où', 'Quand', 'Comment'], instruction: 'Interrogatif' },
    { id: 'fr7-g12', type: 'Grammar', question: 'Hvilket ord betyder "Hvornår"?', answer: 'Quand', options: ['Quand', 'Où', 'Pourquoi'], instruction: 'Interrogatif' },
    { id: 'fr7-g13', type: 'Grammar', question: 'Hvilket ord betyder "Hvordan"?', answer: 'Comment', options: ['Comment', 'Combien', 'Quel'], instruction: 'Interrogatif' },
    { id: 'fr7-g14', type: 'Grammar', question: 'Hvilket ord betyder "Hvor meget"?', answer: 'Combien', options: ['Combien', 'Comment', 'Qui'], instruction: 'Interrogatif' },
    { id: 'fr7-g15', type: 'Grammar', question: 'Hvilket ord betyder "Hvorfor"?', answer: 'Pourquoi', options: ['Pourquoi', 'Parce que', 'Quand'], instruction: 'Interrogatif' },
    { id: 'fr7-g16', type: 'Grammar', question: 'Hvor mange taler man om ved "Ils"?', answer: 'Flere (mænd)', options: ['Flere (mænd)', 'Én mand', 'Flere kvinder'], instruction: 'Pronoms' },
    { id: 'fr7-g17', type: 'Grammar', question: 'Hvor mange taler man om ved "Elles"?', answer: 'Flere (kvinder)', options: ['Flere (kvinder)', 'Én kvinde', 'Flere mænd'], instruction: 'Pronoms' },
    { id: 'fr7-g18', type: 'Grammar', question: 'Hvad betyder "Nous"?', answer: 'Vi', options: ['Vi', 'I', 'De'], instruction: 'Pronoms' },
    { id: 'fr7-g19', type: 'Grammar', question: 'Hvad betyder "Vous"?', answer: 'I / De (høfligt)', options: ['I / De (høfligt)', 'Vi', 'Du'], instruction: 'Pronoms' },
    { id: 'fr7-g20', type: 'Grammar', question: 'Hvad betyder "Aller"?', answer: 'At gå / tage til', options: ['At gå / tage til', 'At komme fra', 'At spise'], instruction: 'Verbes' },
    { id: 'fr7-g21', type: 'Grammar', question: 'Bøjning af "Aller" (Je):', answer: 'vais', options: ['vais', 'vas', 'va'], instruction: 'Verbes' },
    { id: 'fr7-g22', type: 'Grammar', question: 'Bøjning af "Aller" (Nous):', answer: 'allons', options: ['allons', 'allez', 'vont'], instruction: 'Verbes' },
    { id: 'fr7-g23', type: 'Grammar', question: 'Bøjning af "Aller" (Ils):', answer: 'vont', options: ['vont', 'vas', 'allons'], instruction: 'Verbes' },
    { id: 'fr7-g24', type: 'Grammar', question: 'Hvad betyder "Faire"?', answer: 'At gøre / lave', options: ['At gøre / lave', 'At have', 'At være'], instruction: 'Verbes' },
    { id: 'fr7-g25', type: 'Grammar', question: 'Bøjning af "Faire" (Je):', answer: 'fais', options: ['fais', 'fait', 'faisons'], instruction: 'Verbes' },
    { id: 'fr7-g26', type: 'Grammar', question: 'Bøjning af "Faire" (Nous):', answer: 'faisons', options: ['faisons', 'faites', 'font'], instruction: 'Verbes' },
    { id: 'fr7-g27', type: 'Grammar', question: 'Bøjning af "Faire" (Vous):', answer: 'faites', options: ['faites', 'faisons', 'font'], instruction: 'Verbes' },
    { id: 'fr7-g28', type: 'Grammar', question: 'Bøjning af "Faire" (Ils):', answer: 'font', options: ['font', 'faites', 'faisons'], instruction: 'Verbes' },
    { id: 'fr7-g29', type: 'Grammar', question: '"Ce" eller "Cette"? ___ livre.', answer: 'Ce', options: ['Ce', 'Cette'], instruction: 'Démonstratif' },
    { id: 'fr7-g30', type: 'Grammar', question: '"Ce" eller "Cette"? ___ fleur.', answer: 'Cette', options: ['Cette', 'Ce'], instruction: 'Démonstratif' },
    { id: 'fr7-g31', type: 'Grammar', question: '"Ces" bruges til:', answer: 'Flertal', options: ['Flertal', 'Ental hunkøn', 'Ental hankøn'], instruction: 'Démonstratif' },
    { id: 'fr7-g32', type: 'Grammar', question: 'Hvad betyder "Manger"?', answer: 'At spise', options: ['At spise', 'At drikke', 'At sove'], instruction: 'Verbes' },
    { id: 'fr7-g33', type: 'Grammar', question: 'Hvad betyder "Boire"?', answer: 'At drikke', options: ['At drikke', 'At spise', 'At se'], instruction: 'Verbes' },
    { id: 'fr7-g34', type: 'Grammar', question: 'Hvad er modsætningen til "Grand"?', answer: 'Petit', options: ['Petit', 'Gros', 'Haut'], instruction: 'Antonyme' },
    { id: 'fr7-g35', type: 'Grammar', question: 'Hvad er modsætningen til "Bon"?', answer: 'Mauvais', options: ['Mauvais', 'Bien', 'Petit'], instruction: 'Antonyme' },
    { id: 'fr7-g36', type: 'Grammar', question: 'Hvad betyder "Toujours"?', answer: 'Altid', options: ['Altid', 'Aldrig', 'Ofte'], instruction: 'Adverbe' },
    { id: 'fr7-g37', type: 'Grammar', question: 'Hvad betyder "Jamais"?', answer: 'Aldrig', options: ['Aldrig', 'Altid', 'Ofte'], instruction: 'Adverbe' },
    { id: 'fr7-g38', type: 'Grammar', question: 'Tal: 100', answer: 'Cent', options: ['Cent', 'Mille', 'Cinquante'], instruction: 'Nombres' },
    { id: 'fr7-g39', type: 'Grammar', question: 'Tal: 1000', answer: 'Mille', options: ['Mille', 'Cent', 'Million'], instruction: 'Nombres' },
    { id: 'fr7-g40', type: 'Grammar', question: 'Hvad betyder "Le ciel"?', answer: 'Himlen', options: ['Himlen', 'Havet', 'Jorden'], instruction: 'Vocabulaire' },
    { id: 'fr7-g41', type: 'Grammar', question: 'Hvad betyder "La terre"?', answer: 'Jorden', options: ['Jorden', 'Himlen', 'Solen'], instruction: 'Vocabulaire' },
    { id: 'fr7-g42', type: 'Grammar', question: 'Hvad betyder "Le soleil"?', answer: 'Solen', options: ['Solen', 'Månen', 'Stjernen'], instruction: 'Vocabulaire' },
    { id: 'fr7-g43', type: 'Grammar', question: 'Hvad betyder "La lune"?', answer: 'Månen', options: ['Månen', 'Solen', 'Skyen'], instruction: 'Vocabulaire' },
    { id: 'fr7-g44', type: 'Grammar', question: 'Hvordan siger man "Tak"?', answer: 'Merci', options: ['Merci', 'S’il vous plait', 'Bonjour'], instruction: 'Politesse' },
    { id: 'fr7-g45', type: 'Grammar', question: 'Hvordan siger man "Selv tak"?', answer: 'De rien', options: ['De rien', 'Merci', 'Pardon'], instruction: 'Politesse' },
    { id: 'fr7-g46', type: 'Grammar', question: 'Hvad betyder "Un ami"?', answer: 'En ven', options: ['En ven', 'En fjende', 'En nabo'], instruction: 'Vocabulaire' },
    { id: 'fr7-g47', type: 'Grammar', question: 'Hvad betyder "Une amie"?', answer: 'En veninde', options: ['En veninde', 'En ven', 'En søster'], instruction: 'Vocabulaire' },
    { id: 'fr7-g48', type: 'Grammar', question: 'Hvad betyder "Parler"?', answer: 'At tale', options: ['At tale', 'At se', 'At skrive'], instruction: 'Verbes' },
    { id: 'fr7-g49', type: 'Grammar', question: 'Hvad betyder "Écouter"?', answer: 'At lytte', options: ['At lytte', 'At se', 'At lugte'], instruction: 'Verbes' },
    { id: 'fr7-g50', type: 'Grammar', question: 'Hvad betyder "Rider"?', answer: 'At grine', options: ['At grine', 'At græde', 'At sove'], instruction: 'Verbes' },
    { id: 'fr7-g51', type: 'Grammar', question: 'Trés ___!', answer: 'bien', options: ['bien', 'mal', 'blanc'], instruction: 'Feedback' },
  ],
  8: [
    { id: 'fr8-g1', type: 'Grammar', question: 'Nutid af "Être" (Je):', answer: 'suis', options: ['suis', 'es', 'est'], instruction: 'Être' },
    { id: 'fr8-g2', type: 'Grammar', question: 'Nutid af "Avoir" (Je):', answer: 'ai', options: ['ai', 'as', 'a'], instruction: 'Avoir' },
    { id: 'fr8-g3', type: 'Grammar', question: 'Nutid af "Faire" (Ils):', answer: 'font', options: ['font', 'fait', 'fais'], instruction: 'Faire' },
    { id: 'fr8-g4', type: 'Grammar', question: 'Hvordan bøjes uregelmæssige "Aller" (Je):', answer: 'vais', options: ['vais', 'vas', 'allez'], instruction: 'Aller' },
    { id: 'fr8-g5', type: 'Grammar', question: 'Passé composé (datid) af "Manger" (Je):', answer: 'J’ai mangé', options: ['J’ai mangé', 'Je suis mangé', 'Je mangeais'], instruction: 'Passé composé' },
    { id: 'fr8-g6', type: 'Grammar', question: 'Hvilket hjælpeverbum bruges til datid af "Aller"?', answer: 'Être', options: ['Être', 'Avoir', 'Faire'], instruction: 'Grammaire' },
    { id: 'fr8-g7', type: 'Grammar', question: 'Passé composé af "Aller" (Je - hankøn):', answer: 'Je suis allé', options: ['Je suis allé', 'J’ai allé', 'Je suis allée'], instruction: 'Passé composé' },
    { id: 'fr8-g8', type: 'Grammar', question: 'Passé composé af "Aller" (Je - hunkøn):', answer: 'Je suis allée', options: ['Je suis allée', 'Je suis allé', 'J’ai allé'], instruction: 'Passé composé' },
    { id: 'fr8-g9', type: 'Grammar', question: 'Hvad betyder benægtelsen "ne ... pas"?', answer: 'ikke', options: ['ikke', 'aldrig', 'intet'], instruction: 'Négation' },
    { id: 'fr8-g10', type: 'Grammar', question: 'Oversæt: "Jeg spiser ikke" (manger).', answer: 'Je ne mange pas', options: ['Je ne mange pas', 'Je ne pas mange', 'Je mange pas'], instruction: 'Négation' },
    { id: 'fr8-g11', type: 'Grammar', question: 'Hvad betyder "ne ... jamais"?', answer: 'aldrig', options: ['aldrig', 'ikke', 'intet'], instruction: 'Négation' },
    { id: 'fr8-g12', type: 'Grammar', question: 'Hvad betyder "ne ... rien"?', answer: 'intet', options: ['intet', 'aldrig', 'ikke'], instruction: 'Négation' },
    { id: 'fr8-g13', type: 'Grammar', question: 'Hvilken endelse har regelmæssige -er verber i "Nous"?', answer: '-ons', options: ['-ons', '-ez', '-ent'], instruction: 'Verbes' },
    { id: 'fr8-g14', type: 'Grammar', question: 'Hvilken endelse har regelmæssige -er verber i "Ils/Elles"?', answer: '-ent', options: ['-ent', '-ons', '-ez'], instruction: 'Verbes' },
    { id: 'fr8-g15', type: 'Grammar', question: 'Hvad betyder "Ce" i "Ce garçon"?', answer: 'Denne / Dette', options: ['Denne / Dette', 'Min', 'Din'], instruction: 'Démonstratif' },
    { id: 'fr8-g16', type: 'Grammar', question: 'Hvad betyder "Ma" i "Ma mère"?', answer: 'Min (hunkøn)', options: ['Min (hunkøn)', 'Mit (hankøn)', 'Vores'], instruction: 'Possessif' },
    { id: 'fr8-g17', type: 'Grammar', question: 'Hvad betyder "Nos" i "Nos amis"?', answer: 'Vores (flertal)', options: ['Vores (flertal)', 'Deres', 'Hendes'], instruction: 'Possessif' },
    { id: 'fr8-g18', type: 'Grammar', question: 'Flertal af "Le/La":', answer: 'Les', options: ['Les', 'Des', 'Un'], instruction: 'Article' },
    { id: 'fr8-g19', type: 'Grammar', question: 'Ubestemt flertal af "Un/Une":', answer: 'Des', options: ['Des', 'Les', 'Une'], instruction: 'Article' },
    { id: 'fr8-g20', type: 'Grammar', question: 'Hvad betyder "Beau"?', answer: 'Smuk', options: ['Smuk', 'Grim', 'Lille'], instruction: 'Adjectif' },
    { id: 'fr8-g21', type: 'Grammar', question: 'Hvad betyder "Vieux"?', answer: 'Gammel', options: ['Gammel', 'Ung', 'Ny'], instruction: 'Adjectif' },
    { id: 'fr8-g22', type: 'Grammar', question: 'Hvad betyder "Petit"?', answer: 'Lille', options: ['Lille', 'Stor', 'Tynd'], instruction: 'Adjectif' },
    { id: 'fr8-g23', type: 'Grammar', question: 'Bøjning af "Aller" (Vous):', answer: 'allez', options: ['allez', 'allons', 'vont'], instruction: 'Aller' },
    { id: 'fr8-g24', type: 'Grammar', question: 'Bøjning af "Être" (Ils):', answer: 'sont', options: ['sont', 'suis', 'êtes'], instruction: 'Être' },
    { id: 'fr8-g25', type: 'Grammar', question: 'Hvad betyder "Imparfait"?', answer: 'Beskrivende datid', options: ['Beskrivende datid', 'Nutid', 'Fremtid'], instruction: 'Datid' },
    { id: 'fr8-g26', type: 'Grammar', question: 'Hvordan dannes "Futur proche"?', answer: 'Aller + infinitiv', options: ['Aller + infinitiv', 'Avoir + infinitiv', 'Être + infinitiv'], instruction: 'Fremtid' },
    { id: 'fr8-g27', type: 'Grammar', question: 'Oversæt: "Jeg skal spise" (futur proche).', answer: 'Je vais manger', options: ['Je vais manger', 'Jeg spiser', 'Jeg spiste'], instruction: 'Fremtid' },
    { id: 'fr8-g28', type: 'Grammar', question: 'Relative: "Pigen, ___ taler" (qui / que).', answer: 'qui', options: ['qui', 'que'], instruction: 'Relativt pronomen' },
    { id: 'fr8-g29', type: 'Grammar', question: 'Relative: "Bogen, ___ jeg læser" (que / qui).', answer: 'que', options: ['que', 'qui'], instruction: 'Relativt pronomen' },
    { id: 'fr8-g30', type: 'Grammar', question: 'Hvad betyder "Dont"?', answer: 'Som / hvis / af hvilken', options: ['Som / hvis / af hvilken', 'Da', 'Hvor'], instruction: 'Relativt pronomen' },
    { id: 'fr8-g31', type: 'Grammar', question: 'Tal: 70', answer: 'Soixante-dix', options: ['Soixante-dix', 'Septante', 'Soixante'], instruction: 'Nombres' },
    { id: 'fr8-g32', type: 'Grammar', question: 'Tal: 80', answer: 'Quatre-vingts', options: ['Quatre-vingts', 'Huitante', 'Octante'], instruction: 'Nombres' },
    { id: 'fr8-g33', type: 'Grammar', question: 'Tal: 90', answer: 'Quatre-vingt-dix', options: ['Quatre-vingt-dix', 'Nonante', 'Quatre-vingts'], instruction: 'Nombres' },
    { id: 'fr8-g34', type: 'Grammar', question: 'Hvad betyder "La France"?', answer: 'Frankrig', options: ['Frankrig', 'Danmark', 'Tyskland'], instruction: 'Géographie' },
    { id: 'fr8-g35', type: 'Grammar', question: 'Hvad betyder "Le Danemark"?', answer: 'Danmark', options: ['Danmark', 'Frankrig', 'Norge'], instruction: 'Géographie' },
    { id: 'fr8-g36', type: 'Grammar', question: 'Hvad betyder "Allemagne"?', answer: 'Tyskland', options: ['Tyskland', 'England', 'Spanien'], instruction: 'Géographie' },
    { id: 'fr8-g37', type: 'Grammar', question: 'Hvad betyder "Anglais"?', answer: 'Engelsk / Englænder', options: ['Engelsk / Englænder', 'Fransk', 'Dansk'], instruction: 'Langue' },
    { id: 'fr8-g38', type: 'Grammar', question: 'Hvad betyder "Espagnol"?', answer: 'Spansk / Spanier', options: ['Spansk / Spanier', 'Tysk', 'Italiensk'], instruction: 'Langue' },
    { id: 'fr8-g39', type: 'Grammar', question: 'Hvad betyder "Prendre"?', answer: 'At tage', options: ['At tage', 'At give', 'At se'], instruction: 'Verbe' },
    { id: 'fr8-g40', type: 'Grammar', question: 'Bøjning af "Prendre" (Je):', answer: 'prends', options: ['prends', 'prend', 'prenons'], instruction: 'Verbe' },
    { id: 'fr8-g41', type: 'Grammar', question: 'Bøjning af "Prendre" (Nous):', answer: 'prenons', options: ['prenons', 'prenez', 'prennent'], instruction: 'Verbe' },
    { id: 'fr8-g42', type: 'Grammar', question: 'Hvad betyder "Lire"?', answer: 'At læse', options: ['At læse', 'At skrive', 'At tegne'], instruction: 'Verbe' },
    { id: 'fr8-g43', type: 'Grammar', question: 'Hvordan bøjes "Lire" (Je):', answer: 'lis', options: ['lis', 'lit', 'lisons'], instruction: 'Verbe' },
    { id: 'fr8-g44', type: 'Grammar', question: 'Hvad betyder "Écrire"?', answer: 'At skrive', options: ['At skrive', 'At læse', 'At tale'], instruction: 'Verbe' },
    { id: 'fr8-g45', type: 'Grammar', question: 'Hvordan bøjes "Écrire" (Je):', answer: 'écris', options: ['écris', 'écrit', 'écrivons'], instruction: 'Verbe' },
    { id: 'fr8-g46', type: 'Grammar', question: 'Hvordan bøjes "Écrire" (Nous):', answer: 'écrivons', options: ['écrivons', 'écrivez', 'écrivent'], instruction: 'Verbe' },
    { id: 'fr8-g47', type: 'Grammar', question: 'Hvad betyder "Pouvoir"?', answer: 'At kunne', options: ['At kunne', 'At ville', 'At måtte'], instruction: 'Verbe modal' },
    { id: 'fr8-g48', type: 'Grammar', question: 'Hvordan bøjes "Pouvoir" (Je):', answer: 'peux', options: ['peux', 'peut', 'pouvons'], instruction: 'Verbe modal' },
    { id: 'fr8-g49', type: 'Grammar', question: 'Hvad betyder "Vouloir"?', answer: 'At ville', options: ['At ville', 'At skulle', 'At vide'], instruction: 'Verbe modal' },
    { id: 'fr8-g50', type: 'Grammar', question: 'Hvordan bøjes "Vouloir" (Je):', answer: 'veux', options: ['veux', 'veut', 'voulons'], instruction: 'Verbe modal' },
    { id: 'fr8-g51', type: 'Grammar', question: 'Excellent ___!', answer: 'travail', options: ['travail', 'mal', 'blanc'], instruction: 'Feedback' },
  ],
  9: [
    { id: 'fr9-g1', type: 'Grammar', question: 'Hvad hedder "Subjonctif" på dansk?', answer: 'Konjunktiv / Ønskemåde', options: ['Konjunktiv / Ønskemåde', 'Fremtid', 'Datid'], instruction: 'Subjonctif' },
    { id: 'fr9-g2', type: 'Grammar', question: 'Hvilken vending udløser subjonctif?', answer: 'Il faut que...', options: ['Il faut que...', 'Je pense que...', 'Il dit que...'], instruction: 'Subjonctif' },
    { id: 'fr9-g3', type: 'Grammar', question: 'Oversæt: "Det er nødvendigt, at du går" (aller).', answer: 'Il faut que tu ailles', options: ['Il faut que tu ailles', 'Il faut que tu vas', 'Il faut tu vas'], instruction: 'Subjonctif' },
    { id: 'fr9-g4', type: 'Grammar', question: 'Hvad betyder "Passé simple"?', answer: 'Litterær datid', options: ['Litterær datid', 'Hverdagslig datid', 'Fremtid'], instruction: 'Temps' },
    { id: 'fr9-g5', type: 'Grammar', question: 'Hvordan dannes passiv form?', answer: 'Être + participium', options: ['Être + participium', 'Avoir + participium', 'Aller + infinitiv'], instruction: 'Passif' },
    { id: 'fr9-g6', type: 'Grammar', question: 'Oversæt: "Maden blev spist" (manger).', answer: 'Le repas a été mangé', options: ['Le repas a été mangé', 'Le repas a mangé', 'Le repas est mangé'], instruction: 'Passif' },
    { id: 'fr9-g7', type: 'Grammar', question: 'Hvad betyder "Gérondif"?', answer: 'Ved-at-form (en ...-ant)', options: ['Ved-at-form (en ...-ant)', 'Fremtid', 'Datid'], instruction: 'Gérondif' },
    { id: 'fr9-g8', type: 'Grammar', question: 'Oversæt: "Ved at tale" (parler).', answer: 'En parlant', options: ['En parlant', 'Pour parler', 'Par parler'], instruction: 'Gérondif' },
    { id: 'fr9-g9', type: 'Grammar', question: 'Hvad betyder "Celui-ci"?', answer: 'Denne her (hankøn)', options: ['Denne her (hankøn)', 'Denne her (hunkøn)', 'De der'], instruction: 'Démonstratifs' },
    { id: 'fr9-g10', type: 'Grammar', question: 'Hvad betyder "Celle-là"?', answer: 'Den der (hunkøn)', options: ['Den der (hunkøn)', 'Denne her (hankøn)', 'De der'], instruction: 'Démonstratifs' },
    { id: 'fr9-g11', type: 'Grammar', question: 'Hvilket ord betyder "Hvilken" (hunkøn flertal)?', answer: 'Quelles', options: ['Quelles', 'Quels', 'Quel'], instruction: 'Interrogatifs' },
    { id: 'fr9-g12', type: 'Grammar', question: 'Oversæt: "Hvis jeg var rig..." (être).', answer: 'Si j’étais riche...', options: ['Si j’étais riche...', 'Si je suis riche...', 'Si je serais riche...'], instruction: 'Conditionnel' },
    { id: 'fr9-g13', type: 'Grammar', question: 'Oversæt: "...ville jeg rejse" (voyager).', answer: '...je voyagerais.', options: ['...je voyagerais.', '...je voyagerai.', '...je voyage.'], instruction: 'Conditionnel' },
    { id: 'fr9-g14', type: 'Grammar', question: 'Hvad betyder "Dont"?', answer: 'Som / hvis / af hvilken', options: ['Som / hvis / af hvilken', 'Da', 'Hvor'], instruction: 'Relatifs' },
    { id: 'fr9-g15', type: 'Grammar', question: 'Hvilken præposition bruges før lande i hunkøn?', answer: 'en', options: ['en', 'au', 'à'], instruction: 'Prépositions' },
    { id: 'fr9-g16', type: 'Grammar', question: 'Hvilken præposition bruges før lande i hankøn?', answer: 'au', options: ['au', 'en', 'à'], instruction: 'Prépositions' },
    { id: 'fr9-g17', type: 'Grammar', question: 'Hvilken præposition bruges før byer?', answer: 'à', options: ['à', 'en', 'au'], instruction: 'Prépositions' },
    { id: 'fr9-g18', type: 'Grammar', question: 'Hvad betyder "Y" i en sætning?', answer: 'Der / dertil', options: ['Der / dertil', 'Det / den', 'Dem'], instruction: 'Pronoms' },
    { id: 'fr9-g19', type: 'Grammar', question: 'Hvad betyder "En" som pronomen?', answer: 'Noget af det / derfra', options: ['Noget af det / derfra', 'Der', 'Hende'], instruction: 'Pronoms' },
    { id: 'fr9-g20', type: 'Grammar', question: 'Oversæt: "Jeg har brug for det" (avoir besoin de).', answer: 'J’en ai besoin', options: ['J’en ai besoin', 'Je y ai besoin', 'J’ai besoin le'], instruction: 'Pronoms' },
    { id: 'fr9-g21', type: 'Grammar', question: 'Oversæt: "Jeg tager dertil" (aller).', answer: 'J’y vais', options: ['J’y vais', 'Je vais le', 'Je vais en'], instruction: 'Pronoms' },
    { id: 'fr9-g22', type: 'Grammar', question: 'Hvordan bøjes "Mourir" (at dø) i passé composé?', answer: 'Je suis mort(e)', options: ['Je suis mort(e)', 'J’ai mort', 'Je mourais'], instruction: 'Être avec passé composé' },
    { id: 'fr9-g23', type: 'Grammar', question: 'Hvordan bøjes "Naître" (at fødes) i passé composé?', answer: 'Je suis né(e)', options: ['Je suis né(e)', 'J’ai né', 'Je naissais'], instruction: 'Être avec passé composé' },
    { id: 'fr9-g24', type: 'Grammar', question: 'Hvad betyder "Malheureusement"?', answer: 'Desværre', options: ['Desværre', 'Heldigvis', 'Måske'], instruction: 'Adverbe' },
    { id: 'fr9-g25', type: 'Grammar', question: 'Hvad betyder "Heureusement"?', answer: 'Heldigvis', options: ['Heldigvis', 'Desværre', 'Tit'], instruction: 'Adverbe' },
    { id: 'fr9-g26', type: 'Grammar', question: 'Hvad betyder "D\’ailleurs"?', answer: 'I øvrigt / Forresten', options: ['I øvrigt / Forresten', 'Derfor', 'Ellers'], instruction: 'Adverbe' },
    { id: 'fr9-g27', type: 'Grammar', question: 'Hvad betyder "Pourtant"?', answer: 'Alligevel', options: ['Alligevel', 'Fordi', 'Men'], instruction: 'Adverbe' },
    { id: 'fr9-g28', type: 'Grammar', question: 'Hvad betyder "Cependant"?', answer: 'Ikke desto mindre', options: ['Ikke desto mindre', 'Også', 'Kun'], instruction: 'Adverbe' },
    { id: 'fr9-g29', type: 'Grammar', question: 'Hvordan siger man "80" på belgisk fransk?', answer: 'Octante / Huitante', options: ['Octante / Huitante', 'Quatre-vingts', 'Septante'], instruction: 'Variations' },
    { id: 'fr9-g30', type: 'Grammar', question: 'Hvordan siger man "70" på belgisk fransk?', answer: 'Septante', options: ['Septante', 'Soixante-dix', 'Nonante'], instruction: 'Variations' },
    { id: 'fr9-g31', type: 'Grammar', question: 'Hvordan siger man "90" på belgisk fransk?', answer: 'Nonante', options: ['Nonante', 'Quatre-vingt-dix', 'Septante'], instruction: 'Variations' },
    { id: 'fr9-g32', type: 'Grammar', question: 'Hvad betyder "Le chômage"?', answer: 'Arbejdsløshed', options: ['Arbejdsløshed', 'Arbejde', 'Ferie'], instruction: 'Société' },
    { id: 'fr9-g33', type: 'Grammar', question: 'Hvad betyder "La grève"?', answer: 'Strejke', options: ['Strejke', 'Fest', 'Skole'], instruction: 'Société' },
    { id: 'fr9-g34', type: 'Grammar', question: 'Hvad betyder "L\’environnement"?', answer: 'Miljøet', options: ['Miljøet', 'Byen', 'Huset'], instruction: 'Vocabulaire' },
    { id: 'fr9-g35', type: 'Grammar', question: 'Hvad betyder "Le réchauffement climatique"?', answer: 'Den globale opvarmning', options: ['Den globale opvarmning', 'Istiden', 'Regnvejr'], instruction: 'Vocabulaire' },
    { id: 'fr9-g36', type: 'Grammar', question: 'Hvad betyder "La pollution"?', answer: 'Forureningen', options: ['Forureningen', 'Renheden', 'Naturen'], instruction: 'Vocabulaire' },
    { id: 'fr9-g37', type: 'Grammar', question: 'Hvad betyder "Égalité"?', answer: 'Lighed', options: ['Lighed', 'Frihed', 'Broderskab'], instruction: 'Valeurs' },
    { id: 'fr9-g38', type: 'Grammar', question: 'Hvad betyder "Liberté"?', answer: 'Frihed', options: ['Frihed', 'Lighed', 'Broderskab'], instruction: 'Valeurs' },
    { id: 'fr9-g39', type: 'Grammar', question: 'Hvad betyder "Fraternité"?', answer: 'Broderskab', options: ['Broderskab', 'Frihed', 'Lighed'], instruction: 'Valeurs' },
    { id: 'fr9-g40', type: 'Grammar', question: 'Bøjning: Je ___ (vil / futur simple).', answer: 'voudrai', options: ['voudrai', 'voulais', 'veux'], instruction: 'Futur simple' },
    { id: 'fr9-g41', type: 'Grammar', question: 'Bøjning: Je ___ (vil / conditionnel).', answer: 'voudrais', options: ['voudrais', 'voudrai', 'voulais'], instruction: 'Conditionnel' },
    { id: 'fr9-g42', type: 'Grammar', question: 'Hvad betyder "Venir de" + infinitiv?', answer: 'Lige at have gjort noget', options: ['Lige at have gjort noget', 'At komme fra', 'At skulle gøre noget'], instruction: 'Passé récent' },
    { id: 'fr9-g43', type: 'Grammar', question: 'Oversæt: "Jeg har lige spist" (manger).', answer: 'Je viens de manger', options: ['Je viens de manger', 'J’ai mangé', 'Je mangeais'], instruction: 'Passé récent' },
    { id: 'fr9-g44', type: 'Grammar', question: 'Hvad betyder "Être en train de" + infinitiv?', answer: 'At være i gang med', options: ['At være i gang med', 'At have gjort', 'At skulle gøre'], instruction: 'Présent continu' },
    { id: 'fr9-g45', type: 'Grammar', question: 'Oversæt: "Jeg er i gang med at læse" (lire).', answer: 'Je suis en train de lire', options: ['Je suis en train de lire', 'Je lis', 'J’ai lu'], instruction: 'Présent continu' },
    { id: 'fr9-g46', type: 'Grammar', question: 'Hvad betyder "Le subjonctif" af "Être" (Je)?', answer: 'sois', options: ['sois', 'suis', 'serais'], instruction: 'Subjonctif' },
    { id: 'fr9-g47', type: 'Grammar', question: 'Hvad betyder "Le subjonctif" af "Avoir" (Je)?', answer: 'aie', options: ['aie', 'ai', 'aurais'], instruction: 'Subjonctif' },
    { id: 'fr9-g48', type: 'Grammar', question: 'Indsæt: Il faut que nous ___ (partir).', answer: 'partions', options: ['partions', 'partons', 'partent'], instruction: 'Subjonctif' },
    { id: 'fr9-g49', type: 'Grammar', question: 'Hvilket ord betyder "Selvom"?', answer: 'Bien que', options: ['Bien que', 'Parce que', 'Si'], instruction: 'Conjonctions' },
    { id: 'fr9-g50', type: 'Grammar', question: 'Hvad følger altid efter "Bien que"?', answer: 'Subjonctif', options: ['Subjonctif', 'Indikativ', 'Infinitiv'], instruction: 'Grammaire' },
    { id: 'fr9-g51', type: 'Grammar', question: 'Incroyable ___!', answer: 'effort', options: ['effort', 'mal', 'gris'], instruction: 'Feedback' },
  ],
};
