/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const FRANSK_GRAMMAR_P3: Partial<Record<Grade, GameContent[]>> = {
  8: [
    { id: 'fr8-g1', type: 'Grammar', question: 'Le futur simple: Je ___ (parler).', answer: 'parlerai', options: ['parlerai', 'parleras', 'parlera'], instruction: 'Futur simple' },
    { id: 'fr8-g2', type: 'Grammar', question: 'Le futur simple: Tu ___ (parler).', answer: 'parleras', options: ['parleras', 'parlerai', 'parlere'], instruction: 'Futur simple' },
    { id: 'fr8-g3', type: 'Grammar', question: 'Le futur simple: Il ___ (manger).', answer: 'mangera', options: ['mangera', 'mangerai', 'mangent'], instruction: 'Futur simple' },
    { id: 'fr8-g4', type: 'Grammar', question: 'Le futur simple: Nous ___ (chanter).', answer: 'chanterons', options: ['chanterons', 'chanterez', 'chantons'], instruction: 'Futur simple' },
    { id: 'fr8-g5', type: 'Grammar', question: 'Le futur simple: Vous ___ (danser).', answer: 'danserez', options: ['danserez', 'danserons', 'dansez'], instruction: 'Futur simple' },
    { id: 'fr8-g6', type: 'Grammar', question: 'Le futur simple: Ils ___ (regarder).', answer: 'regarderont', options: ['regarderont', 'regardent', 'regardera'], instruction: 'Futur simple' },
    { id: 'fr8-g7', type: 'Grammar', question: 'L\'imparfait: Je ___ (être).', answer: 'étais', options: ['étais', 'était', 'étions'], instruction: 'Imparfait' },
    { id: 'fr8-g8', type: 'Grammar', question: 'L\'imparfait: Tu ___ (avoir).', answer: 'avais', options: ['avais', 'avait', 'avaient'], instruction: 'Imparfait' },
    { id: 'fr8-g9', type: 'Grammar', question: 'L\'imparfait: Il ___ (faire).', answer: 'faisait', options: ['faisait', 'faisais', 'faisions'], instruction: 'Imparfait' },
    { id: 'fr8-g10', type: 'Grammar', question: 'L\'imparfait: Nous ___ (parler).', answer: 'parlions', options: ['parlions', 'parliez', 'parlaient'], instruction: 'Imparfait' },
    { id: 'fr8-g11', type: 'Grammar', question: 'L\'imparfait: Vous ___ (finir).', answer: 'finissiez', options: ['finissiez', 'finissions', 'finissait'], instruction: 'Imparfait' },
    { id: 'fr8-g12', type: 'Grammar', question: 'L\'imparfait: Ils ___ (manger).', answer: 'mangeaient', options: ['mangeaient', 'mangeait', 'mangeons'], instruction: 'Imparfait' },
    { id: 'fr8-g13', type: 'Grammar', question: 'Hvad betyder "Déjà"?', answer: 'Allerede', options: ['Allerede', 'Aldrig', 'Tit'], instruction: 'Adverbes' },
    { id: 'fr8-g14', type: 'Grammar', question: 'Hvad betyder "Encore"?', answer: 'Stadig/Igen', options: ['Stadig/Igen', 'Aldrig', 'Lidt'], instruction: 'Adverbes' },
    { id: 'fr8-g15', type: 'Grammar', question: 'Præposition: "Jeg går ___ bageren" (chez / à).', answer: 'chez', options: ['chez', 'à', 'en'], instruction: 'Prépositions (personnes)' },
    { id: 'fr8-g16', type: 'Grammar', question: 'Hvad betyder "Le travail"?', answer: 'Arbejdet', options: ['Arbejdet', 'Fritiden', 'Skolen'], instruction: 'Vocabulaire' },
    { id: 'fr8-g17', type: 'Grammar', question: 'Hvad betyder "Le chômage"?', answer: 'Arbejdsløshed', options: ['Arbejdsløshed', 'Arbejde', 'Penge'], instruction: 'Vocabulaire' },
    { id: 'fr8-g18', type: 'Grammar', question: 'Hvilket ord betyder "At vinde"?', answer: 'Gagner', options: ['Gagner', 'Perdre', 'Jouer'], instruction: 'Verbes' },
    { id: 'fr8-g19', type: 'Grammar', question: 'Hvilket ord betyder "At tabe"?', answer: 'Perdre', options: ['Perdre', 'Gagner', 'Chercher'], instruction: 'Verbes' },
    { id: 'fr8-g20', type: 'Grammar', question: 'Hvad betyder "La santé"?', answer: 'Sundheden', options: ['Sundheden', 'Sygdommen', 'Mad'], instruction: 'Vocabulaire' },
    { id: 'fr8-g21', type: 'Grammar', question: 'Hvad betyder "L\'environnement"?', answer: 'Miljøet', options: ['Miljøet', 'Byen', 'Skoven'], instruction: 'Vocabulaire' },
    { id: 'fr8-g22', type: 'Grammar', question: 'Passé composé: J\'___ (manger).', answer: 'ai mangé', options: ['ai mangé', 'suis mangé', 'avais mangé'], instruction: 'Passé composé' },
    { id: 'fr8-g23', type: 'Grammar', question: 'Passé composé: Tu ___ (finir).', answer: 'as fini', options: ['as fini', 'es fini', 'avais fini'], instruction: 'Passé composé' },
    { id: 'fr8-g24', type: 'Grammar', question: 'Passé composé: Il ___ (partir). (Verbe de mouvement)', answer: 'est parti', options: ['est parti', 'a parti', 'était parti'], instruction: 'Passé composé (être)' },
    { id: 'fr8-g25', type: 'Grammar', question: 'Passé composé: Elle ___ (venir). (Accord!)', answer: 'est venue', options: ['est venue', 'a venu', 'est venu'], instruction: 'Passé composé (accord)' },
    { id: 'fr8-g26', type: 'Grammar', question: 'Passé composé: Nous ___ (aller). (Accord!)', answer: 'sommes allés', options: ['sommes allés', 'avons allé', 'étions allés'], instruction: 'Passé composé (accord)' },
    { id: 'fr8-g27', type: 'Grammar', question: 'Hvad betyder "Depuis"?', answer: 'Siden / I (tidsrum)', options: ['Siden / I (tidsrum)', 'Efter', 'Før'], instruction: 'Prépositions' },
    { id: 'fr8-g28', type: 'Grammar', question: 'Hvad betyder "Pendant"?', answer: 'I løbet af / Under', options: ['I løbet af / Under', 'Efter', 'Siden'], instruction: 'Prépositions' },
    { id: 'fr8-g29', type: 'Grammar', question: 'Hvad betyder "Avant"?', answer: 'Før', options: ['Før', 'Efter', 'Nu'], instruction: 'Prépositions' },
    { id: 'fr8-g30', type: 'Grammar', question: 'Hvad betyder "Après"?', answer: 'Efter', options: ['Efter', 'Før', 'Under'], instruction: 'Prépositions' },
    { id: 'fr8-g31', type: 'Grammar', question: 'Hvad betyder "Vraiment"?', answer: 'Virkelig', options: ['Virkelig', 'Måske', 'Aldrig'], instruction: 'Adverbes' },
    { id: 'fr8-g32', type: 'Grammar', question: 'Hvad betyder "Heureusement"?', answer: 'Heldigvis', options: ['Heldigvis', 'Desværre', 'Måske'], instruction: 'Adverbes' },
    { id: 'fr8-g33', type: 'Grammar', question: 'Hvad betyder "Malheureusement"?', answer: 'Desværre', options: ['Desværre', 'Heldigvis', 'Tit'], instruction: 'Adverbes' },
    { id: 'fr8-g34', type: 'Grammar', question: 'Hvad betyder "Probablement"?', answer: 'Sandsynligvis', options: ['Sandsynligvis', 'Helt sikkert', 'Aldrig'], instruction: 'Adverbes' },
    { id: 'fr8-g35', type: 'Grammar', question: '"Ce", "Cette" eller "Cet"? ___ homme', answer: 'Cet', options: ['Cet', 'Ce', 'Cette'], instruction: 'Démonstratifs' },
    { id: 'fr8-g36', type: 'Grammar', question: '"Lequel", "Laquelle" eller "Lesquels"? (Hvilken)', answer: 'Lequel', options: ['Lequel', 'Laquelle', 'Lesquels'], instruction: 'Pronoms interrogatifs' },
    { id: 'fr8-g37', type: 'Grammar', question: 'Hvad betyder "Chacun"?', answer: 'Hver især', options: ['Hver især', 'Alle', 'Ingen'], instruction: 'Pronoms' },
    { id: 'fr3-g38', type: 'Grammar', question: 'Hvad betyder "Quelqu\'un"?', answer: 'Nogen / En person', options: ['Nogen / En person', 'Ingen', 'Alle'], instruction: 'Pronoms' },
    { id: 'fr8-g39', type: 'Grammar', question: 'Hvad betyder "Quelque chose"?', answer: 'Noget', options: ['Noget', 'Intet', 'Alt'], instruction: 'Pronoms' },
    { id: 'fr8-g40', type: 'Grammar', question: 'Hvad betyder "Tout le monde"?', answer: 'Alle / Hele verden', options: ['Alle / Hele verden', 'Nogen', 'Ingen'], instruction: 'Pronoms' },
    { id: 'fr8-g41', type: 'Grammar', question: 'Indsæt: Je ___ (kunne - pouvoir).', answer: 'peux', options: ['peux', 'pouvez', 'pouvons'], instruction: 'Pouvoir' },
    { id: 'fr8-g42', type: 'Grammar', question: 'Indsæt: Nous ___ (skulle - devoir).', answer: 'devons', options: ['devons', 'devez', 'doivent'], instruction: 'Devoir' },
    { id: 'fr8-g43', type: 'Grammar', question: 'Indsæt: Ils ___ (ville - vouloir).', answer: 'veulent', options: ['veulent', 'veut', 'voulons'], instruction: 'Vouloir' },
    { id: 'fr8-g44', type: 'Grammar', question: 'Hvilket ord betyder "At vide"?', answer: 'Savoir', options: ['Savoir', 'Connaître', 'Voir'], instruction: 'Savoir' },
    { id: 'fr8-g45', type: 'Grammar', question: 'Hvilket ord betyder "At kende"?', answer: 'Connaître', options: ['Connaître', 'Savoir', 'Lire'], instruction: 'Connaître' },
    { id: 'fr8-g46', type: 'Grammar', question: 'Hvordan bøjes "Savoir" ved "Je"?', answer: 'sais', options: ['sais', 'sait', 'savons'], instruction: 'Savoir' },
    { id: 'fr8-g47', type: 'Grammar', question: 'Hvordan bøjes "Connaître" ved "Je"?', answer: 'connais', options: ['connais', 'connaît', 'connaissons'], instruction: 'Connaître' },
    { id: 'fr8-g48', type: 'Grammar', question: 'Hvad betyder "Le gouvernement"?', answer: 'Regeringen', options: ['Regeringen', 'Byen', 'Folket'], instruction: 'Vocabulaire' },
    { id: 'fr8-g49', type: 'Grammar', question: 'Hvad betyder "La loi"?', answer: 'Loven', options: ['Loven', 'Retten', 'Friheden'], instruction: 'Vocabulaire' },
    { id: 'fr8-g50', type: 'Grammar', question: 'Hvad betyder "La liberté"?', answer: 'Friheden', options: ['Friheden', 'Loven', 'Staten'], instruction: 'Vocabulaire' },
    { id: 'fr8-g51', type: 'Grammar', question: 'Excellent ___!', answer: 'travail', options: ['travail', 'mal', 'rouge'], instruction: 'Feedback' },
  ],
  9: [
    { id: 'fr9-g1', type: 'Grammar', question: 'Le conditionnel présent: Je ___ (aimer).', answer: 'aimerais', options: ['aimerais', 'aimerai', 'aimais'], instruction: 'Conditionnel' },
    { id: 'fr9-g2', type: 'Grammar', question: 'Le conditionnel présent: Tu ___ (finir).', answer: 'finirais', options: ['finirais', 'finiras', 'finissais'], instruction: 'Conditionnel' },
    { id: 'fr9-g3', type: 'Grammar', question: 'Le conditionnel présent: Il ___ (être).', answer: 'serait', options: ['serait', 'sera', 'était'], instruction: 'Conditionnel' },
    { id: 'fr9-g4', type: 'Grammar', question: 'Le conditionnel présent: Nous ___ (avoir).', answer: 'aurions', options: ['aurions', 'aurons', 'avions'], instruction: 'Conditionnel' },
    { id: 'fr9-g5', type: 'Grammar', question: 'Le subjonctif: Il faut que tu ___ (faire).', answer: 'fasses', options: ['fasses', 'fais', 'faites'], instruction: 'Subjonctif' },
    { id: 'fr9-g6', type: 'Grammar', question: 'Le subjonctif: Il faut que je ___ (être).', answer: 'sois', options: ['sois', 'suis', 'soit'], instruction: 'Subjonctif' },
    { id: 'fr9-g7', type: 'Grammar', question: 'Le subjonctif: Bien que ce ___ (être) difficile.', answer: 'soit', options: ['soit', 'est', 'sois'], instruction: 'Subjonctif' },
    { id: 'fr9-g8', type: 'Grammar', question: 'Hvad betyder "Bien que"?', answer: 'Selvom', options: ['Selvom', 'Fordi', 'Da'], instruction: 'Conjonctions' },
    { id: 'fr9-g9', type: 'Grammar', question: 'Hvad betyder "Puisque"?', answer: 'Eftersom', options: ['Eftersom', 'Selvom', 'Hvis'], instruction: 'Conjonctions' },
    { id: 'fr9-g10', type: 'Grammar', question: 'Hvad betyder "Quoique"?', answer: 'Skønt / Selvom', options: ['Skønt / Selvom', 'Hvad', 'Hvor'], instruction: 'Conjonctions' },
    { id: 'fr9-g11', type: 'Grammar', question: 'Pronoms relatifs: L\'homme ___ je parle.', answer: 'dont', options: ['dont', 'que', 'qui'], instruction: 'Dont' },
    { id: 'fr9-g12', type: 'Grammar', question: 'Pronoms relatifs: La chose ___ j\'ai besoin.', answer: 'dont', options: ['dont', 'que', 'lequel'], instruction: 'Dont' },
    { id: 'fr9-g13', type: 'Grammar', question: 'Pronoms relatifs: La ville ___ j\'habite.', answer: 'où', options: ['où', 'que', 'dont'], instruction: 'Relative pronouns' },
    { id: 'fr9-g14', type: 'Grammar', question: 'Hvad betyder "Cependant"?', answer: 'Dog / Ikke desto mindre', options: ['Dog / Ikke desto mindre', 'Derfor', 'Også'], instruction: 'Adverbes' },
    { id: 'fr9-g15', type: 'Grammar', question: 'Hvad betyder "Néanmoins"?', answer: 'Uanset / Ikke desto mindre', options: ['Uanset / Ikke desto mindre', 'Fordi', 'Desuden'], instruction: 'Adverbes' },
    { id: 'fr9-g16', type: 'Grammar', question: 'Hvad betyder "Par contre"?', answer: 'Derimod', options: ['Derimod', 'Fordi', 'Også'], instruction: 'Adverbes' },
    { id: 'fr9-g17', type: 'Grammar', question: 'Hvad betyder "En effet"?', answer: 'Faktisk / Nemlig', options: ['Faktisk / Nemlig', 'Måske', 'Aldrig'], instruction: 'Locutions' },
    { id: 'fr9-g18', type: 'Grammar', question: 'Hvad er "Plus-que-parfait"?', answer: 'Førdatid', options: ['Førdatid', 'Datid', 'Nutid'], instruction: 'Temps' },
    { id: 'fr9-g19', type: 'Grammar', question: 'Plus-que-parfait: J\'___ (manger).', answer: 'avais mangé', options: ['avais mangé', 'ai mangé', 'aurais mangé'], instruction: 'Plus-que-parfait' },
    { id: 'fr9-g20', type: 'Grammar', question: 'Plus-que-parfait: Il ___ (partir).', answer: 'était parti', options: ['était parti', 'est parti', 'partirait'], instruction: 'Plus-que-parfait' },
    { id: 'fr9-g21', type: 'Grammar', question: 'Hvem er "On"?', answer: 'Man / Vi', options: ['Man / Vi', 'Han', 'De'], instruction: 'Pronoms' },
    { id: 'fr9-g22', type: 'Grammar', question: 'Hvad betyder "Se passer"?', answer: 'At ske / At gå for sig', options: ['At ske / At gå for sig', 'At gå forbi', 'At vente'], instruction: 'Verbes pronominaux' },
    { id: 'fr9-g23', type: 'Grammar', question: 'Hvad betyder "Se souvenir de"?', answer: 'At huske', options: ['At huske', 'At glemme', 'At se'], instruction: 'Verbes pronominaux' },
    { id: 'fr9-g24', type: 'Grammar', question: 'Hvad betyder "S\'intéresser à"?', answer: 'At interessere sig for', options: ['At interessere sig for', 'At kede sig', 'At arbejde'], instruction: 'Verbes pronominaux' },
    { id: 'fr9-g25', type: 'Grammar', question: 'Hvad betyder "Le climat"?', answer: 'Klimaet', options: ['Klimaet', 'Vejret', 'Økonomien'], instruction: 'Vocabulaire' },
    { id: 'fr9-g26', type: 'Grammar', question: 'Hvad betyder "L\'avenir"?', answer: 'Fremtiden', options: ['Fremtiden', 'Fortiden', 'Nutiden'], instruction: 'Vocabulaire' },
    { id: 'fr9-g27', type: 'Grammar', question: 'Hvad betyder "Le passé"?', answer: 'Fortiden', options: ['Fortiden', 'Fremtiden', 'Nutiden'], instruction: 'Vocabulaire' },
    { id: 'fr9-g28', type: 'Grammar', question: 'Hvad betyder "La société"?', answer: 'Samfundet', options: ['Samfundet', 'Byen', 'Familien'], instruction: 'Vocabulaire' },
    { id: 'fr9-g29', type: 'Grammar', question: 'Hvad betyder "Les droits de l\'homme"?', answer: 'Menneskerettigheder', options: ['Menneskerettigheder', 'Loven', 'Friheden'], instruction: 'Vocabulaire' },
    { id: 'fr9-g30', type: 'Grammar', question: 'Hvilket ord betyder "At rejse"?', answer: 'Voyager', options: ['Voyager', 'Visiter', 'Aller'], instruction: 'Verbes' },
    { id: 'fr9-g31', type: 'Grammar', question: 'Hvilket ord betyder "At besøge (steder)"?', answer: 'Visiter', options: ['Visiter', 'Rendre visite à', 'Aller'], instruction: 'Verbes' },
    { id: 'fr9-g32', type: 'Grammar', question: 'Hvilket ord betyder "At besøge (personer)"?', answer: 'Rendre visite à', options: ['Rendre visite à', 'Visiter', 'Voir'], instruction: 'Verbes' },
    { id: 'fr9-g33', type: 'Grammar', question: 'Hvad betyder "Grâce à"?', answer: 'Takket være', options: ['Takket være', 'På grund af', 'Uden'], instruction: 'Locutions' },
    { id: 'fr9-g34', type: 'Grammar', question: 'Hvad betyder "À cause de"?', answer: 'På grund af (negativt)', options: ['På grund af (negativt)', 'Takket være', 'Med'], instruction: 'Locutions' },
    { id: 'fr9-g35', type: 'Grammar', question: 'Hvilket tal er "Mille"?', answer: '1000', options: ['1000', '100', '1.000.000'], instruction: 'Nombres' },
    { id: 'fr9-g36', type: 'Grammar', question: 'Hvilket tal er "Un million"?', answer: '1.000.000', options: ['1.000.000', '1000', '10.000'], instruction: 'Nombres' },
    { id: 'fr9-g37', type: 'Grammar', question: 'Hvad betyder "Le sens"?', answer: 'Meningen / Sansen', options: ['Meningen / Sansen', 'Ordet', 'Ting'], instruction: 'Vocabulaire' },
    { id: 'fr9-g38', type: 'Grammar', question: 'Hvad betyder "La vérité"?', answer: 'Sandheden', options: ['Sandheden', 'Løgnen', 'Meningen'], instruction: 'Vocabulaire' },
    { id: 'fr9-g39', type: 'Grammar', question: 'Hvad betyder "Le mensonge"?', answer: 'Løgnen', options: ['Løgnen', 'Sandheden', 'Drømmen'], instruction: 'Vocabulaire' },
    { id: 'fr9-g40', type: 'Grammar', question: 'Indsæt: Si j\'avais de l\'argent, je ___ (købe - conditionnel).', answer: 'achèterais', options: ['achèterais', 'achèterai', 'achetais'], instruction: 'Second conditionnel' },
    { id: 'fr9-g41', type: 'Grammar', question: 'Indsæt: Si tu viens, nous ___ (spise - futur simple).', answer: 'mangerons', options: ['mangerons', 'mangerions', 'mangons'], instruction: 'Premier conditionnel' },
    { id: 'fr9-g42', type: 'Grammar', question: 'Hvad betyder "D\'un côté... de l\'autre côté"?', answer: 'På den ene side... på den anden side', options: ['På den ene side... på den anden side', 'Her og der', 'Før og efter'], instruction: 'Connecteurs' },
    { id: 'fr9-g43', type: 'Grammar', question: 'Hvad betyder "En conclusion"?', answer: 'Afslutningsvis', options: ['Afslutningsvis', 'I begyndelsen', 'Her'], instruction: 'Connecteurs' },
    { id: 'fr9-g44', type: 'Grammar', question: 'Indsæt: Je cherche quelqu\'un qui ___ (kunne - subjonctif).', answer: 'puisse', options: ['puisse', 'peut', 'peuvent'], instruction: 'Subjonctif' },
    { id: 'fr9-g45', type: 'Grammar', question: 'Hvad betyder "Le but"?', answer: 'Målet / Formålet', options: ['Målet / Formålet', 'Byen', 'Vejen'], instruction: 'Vocabulaire' },
    { id: 'fr9-g46', type: 'Grammar', question: 'Hvad betyder "Réussir"?', answer: 'At lykkes / Bestå', options: ['At lykkes / Bestå', 'At fejle', 'At prøve'], instruction: 'Verbes' },
    { id: 'fr9-g47', type: 'Grammar', question: 'Hvad betyder "Échouer"?', answer: 'At fejle / Dumpe', options: ['At fejle / Dumpe', 'At lykkes', 'At vinde'], instruction: 'Verbes' },
    { id: 'fr9-g48', type: 'Grammar', question: 'Hvad betyder "Autour de"?', answer: 'Omkring', options: ['Omkring', 'Gennem', 'Under'], instruction: 'Prépositions' },
    { id: 'fr9-g49', type: 'Grammar', question: 'Hvad betyder "À travers"?', answer: 'Igennem', options: ['Igennem', 'Mod', 'Bagved'], instruction: 'Prépositions' },
    { id: 'fr9-g50', type: 'Grammar', question: 'Hvad betyder "Malgré"?', answer: 'Til trods for', options: ['Til trods for', 'Fordi', 'Uden'], instruction: 'Prépositions' },
    { id: 'fr9-g51', type: 'Grammar', question: 'Magnifique ___!', answer: 'effort', options: ['effort', 'mal', 'blanc'], instruction: 'Feedback' },
  ],
  10: [
    { id: 'fr10-g1', type: 'Grammar', question: 'Le futur antérieur: J\'___ (manger).', answer: 'aurai mangé', options: ['aurai mangé', 'ai mangé', 'avais mangé'], instruction: 'Futur antérieur' },
    { id: 'fr10-g2', type: 'Grammar', question: 'Le futur antérieur: Il ___ (partir).', answer: 'sera parti', options: ['sera parti', 'est parti', 'était parti'], instruction: 'Futur antérieur' },
    { id: 'fr10-g3', type: 'Grammar', question: 'Le subjonctif passé: Bien qu\'il ___ (manger).', answer: 'ait mangé', options: ['ait mangé', 'a mangé', 'aveit mangé'], instruction: 'Subjonctif passé' },
    { id: 'fr10-g4', type: 'Grammar', question: 'Le conditionnel passé: J\'___ (vouloir).', answer: 'aurais voulu', options: ['aurais voulu', 'aurai voulu', 'avais voulu'], instruction: 'Conditionnel passé' },
    { id: 'fr10-g5', type: 'Grammar', question: 'Hvad betyder "Le patrimoine"?', answer: 'Arv / Kulturarv', options: ['Arv / Kulturarv', 'Penge', 'Land'], instruction: 'Vocabulaire' },
    { id: 'fr10-g6', type: 'Grammar', question: 'Hvad betyder "La citoyenneté"?', answer: 'Statsborgerskab', options: ['Statsborgerskab', 'Byen', 'Folket'], instruction: 'Vocabulaire' },
    { id: 'fr10-g7', type: 'Grammar', question: 'Hvad betyder "L\'égalité"?', answer: 'Lighed', options: ['Lighed', 'Frihed', 'Broderskab'], instruction: 'Vocabulaire' },
    { id: 'fr10-g8', type: 'Grammar', question: 'Hvad betyder "La fraternité"?', answer: 'Broderskab', options: ['Broderskab', 'Frihed', 'Lighed'], instruction: 'Vocabulaire' },
    { id: 'fr10-g9', type: 'Grammar', question: 'Hvad betyder "La laïcité"?', answer: 'Sekularisme', options: ['Sekularisme', 'Religion', 'Staten'], instruction: 'Vocabulaire' },
    { id: 'fr10-g10', type: 'Grammar', question: 'Hvad betyder "Désormais"?', answer: 'Fra nu af', options: ['Fra nu af', 'Førhen', 'Aldrig'], instruction: 'Adverbes' },
    { id: 'fr10-g11', type: 'Grammar', question: 'Hvad betyder "Jadis"?', answer: 'I gamle dage', options: ['I gamle dage', 'Nu', 'Snart'], instruction: 'Adverbes' },
    { id: 'fr10-g12', type: 'Grammar', question: 'Hvad betyder "Dorénavant"?', answer: 'Fremover', options: ['Fremover', 'Tidligere', 'Aldrig'], instruction: 'Adverbes' },
    { id: 'fr10-g13', type: 'Grammar', question: 'Indsæt: Si j\'avais su, j\'___ (komme - conditionnel passé).', answer: 'serais venu', options: ['serais venu', 'serai venu', 'suis venu'], instruction: 'Troisième conditionnel' },
    { id: 'fr10-g14', type: 'Grammar', question: 'Hvad betyder "Quoiqu\'il en soit"?', answer: 'Uanset hvad', options: ['Uanset hvad', 'Hvad det er', 'Uden tvivl'], instruction: 'Locutions' },
    { id: 'fr10-g15', type: 'Grammar', question: 'Hvad betyder "Sans l\'ombre d\'un doute"?', answer: 'Uden skyggen af tvivl', options: ['Uden skyggen af tvivl', 'Måske', 'Helt sikkert'], instruction: 'Locutions' },
    { id: 'fr10-g16', type: 'Grammar', question: 'Hvad betyder "Au fur et à mesure"?', answer: 'Efterhånden som', options: ['Efterhånden som', 'Pludselig', 'Aldrig'], instruction: 'Locutions' },
    { id: 'fr10-g17', type: 'Grammar', question: 'Hvad betyder "D\'ailleurs"?', answer: 'Desuden / For øvrigt', options: ['Desuden / For øvrigt', 'Derovre', 'Herfra'], instruction: 'Adverbes' },
    { id: 'fr10-g18', type: 'Grammar', question: 'Hvad betyder "Par ailleurs"?', answer: 'Desuden / På den anden side', options: ['Desuden / På den anden side', 'Her', 'Væk'], instruction: 'Adverbes' },
    { id: 'fr10-g19', type: 'Grammar', question: 'Hvad betyder "Quant à"?', answer: 'Hvad angår', options: ['Hvad angår', 'Hvornår', 'Hvor meget'], instruction: 'Locutions' },
    { id: 'fr10-g20', type: 'Grammar', question: 'Indsæt: Je doute que ce ___ (være - subjonctif) possible.', answer: 'soit', options: ['soit', 'est', 'sois'], instruction: 'Subjonctif' },
    { id: 'fr10-g21', type: 'Grammar', question: 'Hvilket ord betyder "At udfordre"?', answer: 'Défier', options: ['Défier', 'Aider', 'Accepter'], instruction: 'Verbes' },
    { id: 'fr10-g22', type: 'Grammar', question: 'Hvilket ord betyder "At støtte"?', answer: 'Soutenir', options: ['Soutenir', 'Porter', 'Laisser'], instruction: 'Verbes' },
    { id: 'fr10-g23', type: 'Grammar', question: 'Hvilket ord betyder "At forhindre"?', answer: 'Empêcher', options: ['Empêcher', 'Permettre', 'Chercher'], instruction: 'Verbes' },
    { id: 'fr10-g24', type: 'Grammar', question: 'Hvilket ord betyder "At foreslå"?', answer: 'Proposer', options: ['Proposer', 'Dire', 'Faire'], instruction: 'Verbes' },
    { id: 'fr10-g25', type: 'Grammar', question: 'Hvad betyder "Le développement durable"?', answer: 'Bæredygtig udvikling', options: ['Bæredygtig udvikling', 'Økonomisk vækst', 'Miljø'], instruction: 'Vocabulaire' },
    { id: 'fr10-g26', type: 'Grammar', question: 'Hvad betyder "Le réchauffement climatique"?', answer: 'Global opvarmning', options: ['Global opvarmning', 'Vejret', 'Sommer'], instruction: 'Vocabulaire' },
    { id: 'fr10-g27', type: 'Grammar', question: 'Hvad betyder "L\'intelligence artificielle"?', answer: 'Kunstig intelligens', options: ['Kunstig intelligens', 'Teknologi', 'Forskning'], instruction: 'Vocabulaire' },
    { id: 'fr10-g28', type: 'Grammar', question: 'Hvad betyder "Le réseau social"?', answer: 'Socialt netværk', options: ['Socialt netværk', 'Internet', 'Computer'], instruction: 'Vocabulaire' },
    { id: 'fr10-g29', type: 'Grammar', question: 'Hvad betyder "La mondialisation"?', answer: 'Globaliseringen', options: ['Globaliseringen', 'Landet', 'Handel'], instruction: 'Vocabulaire' },
    { id: 'fr10-g30', type: 'Grammar', question: 'Hvad betyder "L\'engagement"?', answer: 'Engagement / Forpligtelse', options: ['Engagement / Forpligtelse', 'Aftale', 'Arbejde'], instruction: 'Vocabulaire' },
    { id: 'fr10-g31', type: 'Grammar', question: 'Hvad betyder "Estimer"?', answer: 'At vurdere / Skønne', options: ['At vurdere / Skønne', 'At tælle', 'At se'], instruction: 'Verbes' },
    { id: 'fr10-g32', type: 'Grammar', question: 'Hvad betyder "S\'épanouir"?', answer: 'At blomstre / Udvikle sig', options: ['At blomstre / Udvikle sig', 'At visne', 'At sove'], instruction: 'Verbes' },
    { id: 'fr10-g33', type: 'Grammar', question: 'Hvad betyder "Prétendre"?', answer: 'At påstå', options: ['At påstå', 'At vente', 'At sige'], instruction: 'Verbes' },
    { id: 'fr10-g34', type: 'Grammar', question: 'Hvad betyder "Supposer"?', answer: 'At antage', options: ['At antage', 'At vide', 'At bevise'], instruction: 'Verbes' },
    { id: 'fr10-g35', type: 'Grammar', question: 'Hvad betyder "Constater"?', answer: 'At konstatere', options: ['At konstatere', 'At gætte', 'At drømme'], instruction: 'Verbes' },
    { id: 'fr10-g36', type: 'Grammar', question: 'Hvad betyder "Contredire"?', answer: 'At modstige', options: ['At modstige', 'At være enig', 'At tale'], instruction: 'Verbes' },
    { id: 'fr10-g37', type: 'Grammar', question: 'Hvad betyder "L\'amitié"?', answer: 'Venskab', options: ['Venskab', 'Kærlighed', 'Hade'], instruction: 'Vocabulaire' },
    { id: 'fr10-g38', type: 'Grammar', question: 'Hvad betyder "La haine"?', answer: 'Hadet', options: ['Hadet', 'Kærligheden', 'Venskabet'], instruction: 'Vocabulaire' },
    { id: 'fr10-g39', type: 'Grammar', question: 'Hvad betyder "L\'espoir"?', answer: 'Håbet', options: ['Håbet', 'Frygten', 'Drømmen'], instruction: 'Vocabulaire' },
    { id: 'fr10-g40', type: 'Grammar', question: 'Indsæt: Il est probable qu\'il ___ (komme - subjonctif).', answer: 'vienne', options: ['vienne', 'vient', 'viendra'], instruction: 'Subjonctif' },
    { id: 'fr10-g41', type: 'Grammar', question: 'Hvad betyder "N\'importe qui"?', answer: 'Hvem som helst', options: ['Hvem som helst', 'Ingen', 'Nogen'], instruction: 'Pronoms' },
    { id: 'fr10-g42', type: 'Grammar', question: 'Hvad betyder "N\'importe quoi"?', answer: 'Hvad som helst', options: ['Hvad som helst', 'Intet', 'Noget'], instruction: 'Pronoms' },
    { id: 'fr10-g43', type: 'Grammar', question: 'Hvad betyder "N\'importe où"?', answer: 'Hvor som helst', options: ['Hvor som helst', 'Ingensteds', 'Et sted'], instruction: 'Pronoms' },
    { id: 'fr10-g44', type: 'Grammar', question: 'Hvad betyder "N\'importe quand"?', answer: 'Hvornår som helst', options: ['Hvornår som helst', 'Aldrig', 'Engang'], instruction: 'Pronoms' },
    { id: 'fr10-g45', type: 'Grammar', question: 'Hvad betyder "Même si"?', answer: 'Selv hvis', options: ['Selv hvis', 'Fordi', 'Da'], instruction: 'Conjonctions' },
    { id: 'fr10-g46', type: 'Grammar', question: 'Hvad betyder "Pourvu que"?', answer: 'Forudsat at / Bare', options: ['Forudsat at / Bare', 'Fordi', 'Uden'], instruction: 'Conjonctions' },
    { id: 'fr10-g47', type: 'Grammar', question: 'Hvad betyder "À condition que"?', answer: 'På betingelse af at', options: ['På betingelse af at', 'Selvom', 'Da'], instruction: 'Conjonctions' },
    { id: 'fr10-g48', type: 'Grammar', question: 'Indsæt: Sans que je ___ (vide - subjonctif: le sache).', answer: 'le sache', options: ['le sache', 'le sais', 'le saurais'], instruction: 'Subjonctif' },
    { id: 'fr10-g49', type: 'Grammar', question: 'Hvad betyder "De toute façon"?', answer: 'Under alle omstændigheder', options: ['Under alle omstændigheder', 'Måske', 'Aldrig'], instruction: 'Locutions' },
    { id: 'fr10-g50', type: 'Grammar', question: 'Hvad betyder "Bref"?', answer: 'Kort sagt / Kort', options: ['Kort sagt / Kort', 'Langt', 'Meget'], instruction: 'Adverbes' },
    { id: 'fr10-g51', type: 'Grammar', question: 'Félicitations ___!', answer: 'incroyables', options: ['incroyables', 'mal', 'noir'], instruction: 'Feedback' },
  ],
};
