/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const FRANSK_GRAMMAR_P1: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'fr0-g1', type: 'Grammar', question: 'Quelle couleur er "Rouge"?', answer: 'Rød', options: ['Rød', 'Blå', 'Grøn'], instruction: 'Couleurs' },
    { id: 'fr0-g2', type: 'Grammar', question: 'Quelle couleur er "Bleu"?', answer: 'Blå', options: ['Blå', 'Gul', 'Hvid'], instruction: 'Couleurs' },
    { id: 'fr0-g3', type: 'Grammar', question: 'Quelle couleur er "Vert"?', answer: 'Grøn', options: ['Grøn', 'Sort', 'Rød'], instruction: 'Couleurs' },
    { id: 'fr0-g4', type: 'Grammar', question: 'Quel animal er "Le chat"?', answer: 'Katten', options: ['Katten', 'Hunden', 'Hesten'], instruction: 'Animaux' },
    { id: 'fr0-g5', type: 'Grammar', question: 'Quel animal er "Le chien"?', answer: 'Hunden', options: ['Hunden', 'Fuglen', 'Fisken'], instruction: 'Animaux' },
    { id: 'fr0-g6', type: 'Grammar', question: 'Hvad betyder "Bonjour"?', answer: 'Goddag', options: ['Goddag', 'Farvel', 'Tak'], instruction: 'Salutations' },
    { id: 'fr0-g7', type: 'Grammar', question: 'Hvad betyder "Merci"?', answer: 'Tak', options: ['Tak', 'Ja', 'Nej'], instruction: 'Politesse' },
    { id: 'fr0-g8', type: 'Grammar', question: 'Est-ce un fruit? "La pomme"', answer: 'Oui', options: ['Oui', 'Non'], instruction: 'Vocabulaire' },
    { id: 'fr0-g9', type: 'Grammar', question: 'Est-ce un fruit? "Le pain"', answer: 'Non', options: ['Oui', 'Non'], instruction: 'Vocabulaire' },
    { id: 'fr0-g10', type: 'Grammar', question: 'Hvor mange er "Un"?', answer: '1', options: ['1', '2', '3'], instruction: 'Nombres' },
    { id: 'fr0-g11', type: 'Grammar', question: 'Hvor mange er "Deux"?', answer: '2', options: ['2', '1', '4'], instruction: 'Nombres' },
    { id: 'fr0-g12', type: 'Grammar', question: 'Hvor mange er "Trois"?', answer: '3', options: ['3', '5', '10'], instruction: 'Nombres' },
    { id: 'fr0-g13', type: 'Grammar', question: '"Un" eller "Une"? ___ garçon', answer: 'Un', options: ['Un', 'Une'], instruction: 'Articles' },
    { id: 'fr0-g14', type: 'Grammar', question: '"Un" eller "Une"? ___ fille', answer: 'Une', options: ['Un', 'Une'], instruction: 'Articles' },
    { id: 'fr0-g15', type: 'Grammar', question: '"Le" eller "La"? ___ soleil', answer: 'Le', options: ['Le', 'La'], instruction: 'Articles' },
    { id: 'fr0-g16', type: 'Grammar', question: '"Le" eller "La"? ___ lune', answer: 'La', options: ['Le', 'La'], instruction: 'Articles' },
    { id: 'fr0-g17', type: 'Grammar', question: 'Hvad er modsætningen til "Petit"?', answer: 'Grand', options: ['Grand', 'Beau', 'Vite'], instruction: 'Antonymes' },
    { id: 'fr0-g18', type: 'Grammar', question: 'Hvad betyder "Oui"?', answer: 'Ja', options: ['Ja', 'Nej', 'Måske'], instruction: 'Vocabulaire' },
    { id: 'fr0-g19', type: 'Grammar', question: 'Hvad betyder "Non"?', answer: 'Nej', options: ['Nej', 'Ja', 'Tak'], instruction: 'Vocabulaire' },
    { id: 'fr0-g20', type: 'Grammar', question: 'Find det franske ord for "Mor":', answer: 'Maman', options: ['Maman', 'Papa', 'Frère'], instruction: 'Famille' },
    { id: 'fr0-g21', type: 'Grammar', question: 'Find det franske ord for "Far":', answer: 'Papa', options: ['Papa', 'Maman', 'Sœur'], instruction: 'Famille' },
    { id: 'fr0-g22', type: 'Grammar', question: 'Quelle couleur er "Jaune"?', answer: 'Gul', options: ['Gul', 'Lilla', 'Brun'], instruction: 'Couleurs' },
    { id: 'fr0-g23', type: 'Grammar', question: 'Quelle couleur er "Noir"?', answer: 'Sort', options: ['Sort', 'Hvid', 'Grå'], instruction: 'Couleurs' },
    { id: 'fr0-g24', type: 'Grammar', question: 'Quelle couleur er "Blanc"?', answer: 'Hvid', options: ['Hvid', 'Sort', 'Rød'], instruction: 'Couleurs' },
    { id: 'fr0-g25', type: 'Grammar', question: '"Un" eller "Une"? ___ pomme', answer: 'Une', options: ['Un', 'Une'], instruction: 'Articles' },
    { id: 'fr0-g26', type: 'Grammar', question: '"Un" eller "Une"? ___ chien', answer: 'Un', options: ['Un', 'Une'], instruction: 'Articles' },
    { id: 'fr0-g27', type: 'Grammar', question: 'Hvad betyder "S\’il vous plaît"?', answer: 'Vær så venlig', options: ['Vær så venlig', 'Farvel', 'Goddag'], instruction: 'Politesse' },
    { id: 'fr0-g28', type: 'Grammar', question: 'Hvad betyder "Au revoir"?', answer: 'Farvel', options: ['Farvel', 'Hej', 'Godmorgen'], instruction: 'Salutations' },
    { id: 'fr0-g29', type: 'Grammar', question: 'Find tallet 4:', answer: 'Quatre', options: ['Quatre', 'Cinq', 'Six'], instruction: 'Nombres' },
    { id: 'fr0-g30', type: 'Grammar', question: 'Find tallet 5:', answer: 'Cinq', options: ['Cinq', 'Quatre', 'Trois'], instruction: 'Nombres' },
    { id: 'fr0-g31', type: 'Grammar', question: 'Find tallet 6:', answer: 'Six', options: ['Six', 'Sept', 'Huit'], instruction: 'Nombres' },
    { id: 'fr0-g32', type: 'Grammar', question: 'Find tallet 0:', answer: 'Zéro', options: ['Zéro', 'Dix', 'Un'], instruction: 'Nombres' },
    { id: 'fr0-g33', type: 'Grammar', question: 'Er en elefant "Petit" eller "Grand"?', answer: 'Grand', options: ['Grand', 'Petit'], instruction: 'Taille' },
    { id: 'fr0-g34', type: 'Grammar', question: 'Er en mus "Petit" eller "Grand"?', answer: 'Petit', options: ['Petit', 'Grand'], instruction: 'Taille' },
    { id: 'fr0-g35', type: 'Grammar', question: 'Hvad betyder "L\’eau"?', answer: 'Vandet', options: ['Vandet', 'Mælken', 'Juicen'], instruction: 'Boissons' },
    { id: 'fr0-g36', type: 'Grammar', question: 'Hvad betyder "Le lait"?', answer: 'Mælken', options: ['Mælken', 'Vandet', 'Vinen'], instruction: 'Boissons' },
    { id: 'fr0-g37', type: 'Grammar', question: 'Er en "Lion" farlig?', answer: 'Oui', options: ['Oui', 'Non'], instruction: 'Animaux' },
    { id: 'fr0-g38', type: 'Grammar', question: 'Hvad betyder "Le ciel"?', answer: 'Himlen', options: ['Himlen', 'Jorden', 'Havet'], instruction: 'Nature' },
    { id: 'fr0-g39', type: 'Grammar', question: 'Hvad betyder "La mer"?', answer: 'Havet', options: ['Havet', 'Himlen', 'Skoven'], instruction: 'Nature' },
    { id: 'fr0-g40', type: 'Grammar', question: '"Le" eller "La"? ___ fleur', answer: 'La', options: ['Le', 'La'], instruction: 'Articles' },
    { id: 'fr0-g41', type: 'Grammar', question: '"Le" eller "La"? ___ arbre', answer: 'L\’', options: ['L\’', 'Le', 'La'], instruction: 'Articles (vowel)' },
    { id: 'fr0-g42', type: 'Grammar', question: 'Hvor mange ben har en hund?', answer: 'Quatre', options: ['Quatre', 'Deux', 'Un'], instruction: 'Nombres/Animaux' },
    { id: 'fr0-g43', type: 'Grammar', question: 'Hvad siger en kat på fransk?', answer: 'Miaou', options: ['Miaou', 'Ouaf', 'Meuh'], instruction: 'Sons' },
    { id: 'fr0-g44', type: 'Grammar', question: 'Hvad siger en hund på fransk?', answer: 'Ouaf', options: ['Ouaf', 'Miaou', 'Cocoricó'], instruction: 'Sons' },
    { id: 'fr0-g45', type: 'Grammar', question: 'Hvad betyder "Pain"?', answer: 'Brød', options: ['Brød', 'Kage', 'Æble'], instruction: 'Nourriture' },
    { id: 'fr0-g46', type: 'Grammar', question: 'Quelle couleur er "Rose"?', answer: 'Lyserød', options: ['Lyserød', 'Violet', 'Blå'], instruction: 'Couleurs' },
    { id: 'fr0-g47', type: 'Grammar', question: 'Quelle couleur er "Orange"?', answer: 'Orange', options: ['Orange', 'Gul', 'Hvid'], instruction: 'Couleurs' },
    { id: 'fr0-g48', type: 'Grammar', question: 'Find det franske ord for "Ven":', answer: 'Ami', options: ['Ami', 'Ennemi', 'Livre'], instruction: 'Vocabulaire' },
    { id: 'fr0-g49', type: 'Grammar', question: 'Betyder "Salut" både Hej og Hej Hej?', answer: 'Oui', options: ['Oui', 'Non'], instruction: 'Salutations' },
    { id: 'fr0-g50', type: 'Grammar', question: 'Hvilket bogstav starter "Français" med?', answer: 'F', options: ['F', 'P', 'E'], instruction: 'Lettres' },
    { id: 'fr0-g51', type: 'Grammar', question: 'Bravo ___!', answer: 'beaucoup', options: ['beaucoup', 'petit', 'noir'], instruction: 'Feedback' },
  ],
  1: [
    { id: 'fr1-g1', type: 'Grammar', question: 'Hvad betyder "Je"?', answer: 'Jeg', options: ['Jeg', 'Du', 'Han'], instruction: 'Pronoms' },
    { id: 'fr1-g2', type: 'Grammar', question: 'Hvad betyder "Tu"?', answer: 'Du', options: ['Du', 'Jeg', 'Hun'], instruction: 'Pronoms' },
    { id: 'fr1-g3', type: 'Grammar', question: 'Hvad betyder "Il"?', answer: 'Han', options: ['Han', 'Hun', 'Vi'], instruction: 'Pronoms' },
    { id: 'fr1-g4', type: 'Grammar', question: 'Hvad betyder "Elle"?', answer: 'Hun', options: ['Hun', 'Han', 'De'], instruction: 'Pronoms' },
    { id: 'fr1-g5', type: 'Grammar', question: 'Indsæt: Je ___ (være).', answer: 'suis', options: ['suis', 'es', 'est'], instruction: 'Être' },
    { id: 'fr1-g6', type: 'Grammar', question: 'Indsæt: Tu ___ (være).', answer: 'es', options: ['es', 'suis', 'est'], instruction: 'Être' },
    { id: 'fr1-g7', type: 'Grammar', question: 'Indsæt: Il ___ (være).', answer: 'est', options: ['est', 'es', 'sommes'], instruction: 'Être' },
    { id: 'fr1-g8', type: 'Grammar', question: 'Flertal af "Le":', answer: 'Les', options: ['Les', 'La', 'Des'], instruction: 'Articles' },
    { id: 'fr1-g9', type: 'Grammar', question: 'Flertal af "La":', answer: 'Les', options: ['Les', 'Le', 'Des'], instruction: 'Articles' },
    { id: 'fr1-g10', type: 'Grammar', question: 'Flertal af "Un":', answer: 'Des', options: ['Des', 'Les', 'Une'], instruction: 'Articles' },
    { id: 'fr1-g11', type: 'Grammar', question: 'Flertal af "Une":', answer: 'Des', options: ['Des', 'Les', 'Un'], instruction: 'Articles' },
    { id: 'fr1-g12', type: 'Grammar', question: 'Hvad betyder "Manger"?', answer: 'At spise', options: ['At spise', 'At drikke', 'At sove'], instruction: 'Verbes' },
    { id: 'fr1-g13', type: 'Grammar', question: 'Hvad betyder "Dormir"?', answer: 'At sove', options: ['At sove', 'At løbe', 'At synge'], instruction: 'Verbes' },
    { id: 'fr1-g14', type: 'Grammar', question: 'Hvad betyder "Parler"?', answer: 'At tale', options: ['At tale', 'At se', 'At købe'], instruction: 'Verbes' },
    { id: 'fr1-g15', type: 'Grammar', question: 'Find tallet 7:', answer: 'Sept', options: ['Sept', 'Six', 'Huit'], instruction: 'Nombres' },
    { id: 'fr1-g16', type: 'Grammar', question: 'Find tallet 8:', answer: 'Huit', options: ['Huit', 'Neuf', 'Dix'], instruction: 'Nombres' },
    { id: 'fr1-g17', type: 'Grammar', question: 'Find tallet 9:', answer: 'Neuf', options: ['Neuf', 'Huit', 'Dix'], instruction: 'Nombres' },
    { id: 'fr1-g18', type: 'Grammar', question: 'Find tallet 10:', answer: 'Dix', options: ['Dix', 'Zéro', 'Un'], instruction: 'Nombres' },
    { id: 'fr1-g19', type: 'Grammar', question: 'Hvordan siger man "Godmorgen"?', answer: 'Bonjour', options: ['Bonjour', 'Bonsoir', 'Bonne nuit'], instruction: 'Salutations' },
    { id: 'fr1-g20', type: 'Grammar', question: 'Hvordan siger man "Godaften"?', answer: 'Bonsoir', options: ['Bonsoir', 'Bonjour', 'Bonne nuit'], instruction: 'Salutations' },
    { id: 'fr1-g21', type: 'Grammar', question: 'Hvordan siger man "Godnat"?', answer: 'Bonne nuit', options: ['Bonne nuit', 'Bonsoir', 'Bonjour'], instruction: 'Salutations' },
    { id: 'fr1-g22', type: 'Grammar', question: 'Hvad betyder "L\’école"?', answer: 'Skolen', options: ['Skolen', 'Huset', 'Haven'], instruction: 'Vocabulaire' },
    { id: 'fr1-g23', type: 'Grammar', question: 'Hvad betyder "Le livre"?', answer: 'Bogen', options: ['Bogen', 'Blyanten', 'Tasken'], instruction: 'Vocabulaire' },
    { id: 'fr1-g24', type: 'Grammar', question: 'Hvad betyder "Le professeur"?', answer: 'Læreren', options: ['Læreren', 'Eleven', 'Rektoren'], instruction: 'Vocabulaire' },
    { id: 'fr1-g25', type: 'Grammar', question: 'Hvad betyder "Rouge" og "Jaune"?', answer: 'Rød og Gul', options: ['Rød og Gul', 'Blå og Grøn', 'Sort og Hvid'], instruction: 'Couleurs' },
    { id: 'fr1-g26', type: 'Grammar', question: 'Hvad betyder "Blanc" og "Noir"?', answer: 'Hvid og Sort', options: ['Hvid og Sort', 'Rød og Blå', 'Gul og Lilla'], instruction: 'Couleurs' },
    { id: 'fr1-g27', type: 'Grammar', question: 'Hvad betyder "L\’ami"?', answer: 'Vennen', options: ['Vennen', 'Fjenden', 'Naboen'], instruction: 'Vocabulaire' },
    { id: 'fr1-g28', type: 'Grammar', question: '"Un" eller "Une"? ___ maison (hus)', answer: 'Une', options: ['Une', 'Un'], instruction: 'Articles' },
    { id: 'fr1-g29', type: 'Grammar', question: '"Un" eller "Une"? ___ vélo (cykel)', answer: 'Un', options: ['Un', 'Une'], instruction: 'Articles' },
    { id: 'fr1-g30', type: 'Grammar', question: 'Hvad betyder "Petit"?', answer: 'Lille', options: ['Lille', 'Stor', 'Mellem'], instruction: 'Adjectifs' },
    { id: 'fr1-g31', type: 'Grammar', question: 'Hvad betyder "Grand"?', answer: 'Stor', options: ['Stor', 'Lille', 'Tynd'], instruction: 'Adjectifs' },
    { id: 'fr1-g32', type: 'Grammar', question: 'Hvad betyder "Vite"?', answer: 'Hurtigt', options: ['Hurtigt', 'Langsomt', 'Stille'], instruction: 'Adverbes' },
    { id: 'fr1-g33', type: 'Grammar', question: 'Indsæt: Elle ___ (være).', answer: 'est', options: ['est', 'es', 'suis'], instruction: 'Être' },
    { id: 'fr1-g34', type: 'Grammar', question: 'Betyder "Merci beaucoup" Tak mange gange?', answer: 'Oui', options: ['Oui', 'Non'], instruction: 'Politesse' },
    { id: 'fr1-g35', type: 'Grammar', question: 'Hvad betyder "La famille"?', answer: 'Familien', options: ['Familien', 'Vennerne', 'Byen'], instruction: 'Vocabulaire' },
    { id: 'fr1-g36', type: 'Grammar', question: 'Find det franske ord for "Søster":', answer: 'Sœur', options: ['Sœur', 'Frère', 'Mère'], instruction: 'Famille' },
    { id: 'fr1-g37', type: 'Grammar', question: 'Find det franske ord for "Bror":', answer: 'Frère', options: ['Frère', 'Sœur', 'Père'], instruction: 'Famille' },
    { id: 'fr1-g38', type: 'Grammar', question: 'Hvad betyder "Ici"?', answer: 'Her', options: ['Her', 'Der', 'Ovre'], instruction: 'Vocabulaire' },
    { id: 'fr1-g39', type: 'Grammar', question: 'Hvad betyder "Là-bas"?', answer: 'Derovre', options: ['Derovre', 'Her', 'Bagved'], instruction: 'Vocabulaire' },
    { id: 'fr1-g40', type: 'Grammar', question: 'Find ordet for "Ja":', answer: 'Oui', options: ['Oui', 'Non', 'Mais'], instruction: 'Vocabulaire' },
    { id: 'fr1-g41', type: 'Grammar', question: 'Find ordet for "Nej":', answer: 'Non', options: ['Non', 'Oui', 'Aussi'], instruction: 'Vocabulaire' },
    { id: 'fr1-g42', type: 'Grammar', question: 'Hvor mange fingre har du? (10)', answer: 'Dix', options: ['Dix', 'Cinq', 'Deux'], instruction: 'Nombres' },
    { id: 'fr1-g43', type: 'Grammar', question: 'Hvor mange næser har du? (1)', answer: 'Une', options: ['Une', 'Deux', 'Dix'], instruction: 'Nombres' },
    { id: 'fr1-g44', type: 'Grammar', question: 'Hvor mange øjne har du? (2)', answer: 'Deux', options: ['Deux', 'Un', 'Trois'], instruction: 'Nombres' },
    { id: 'fr1-g45', type: 'Grammar', question: 'Hvad betyder "Chanter"?', answer: 'At synge', options: ['At synge', 'At danse', 'At græde'], instruction: 'Verbes' },
    { id: 'fr1-g46', type: 'Grammar', question: 'Hvad betyder "Jouer"?', answer: 'At spille/lege', options: ['At spille/lege', 'At arbejde', 'At læse'], instruction: 'Verbes' },
    { id: 'fr1-g47', type: 'Grammar', question: 'Hvad betyder "Lire"?', answer: 'At læse', options: ['At læse', 'At skrive', 'At tegne'], instruction: 'Verbes' },
    { id: 'fr1-g48', type: 'Grammar', question: 'Indsæt: Je ___ (have).', answer: 'ai', options: ['ai', 'as', 'a'], instruction: 'Avoir' },
    { id: 'fr1-g49', type: 'Grammar', question: 'Indsæt: Tu ___ (have).', answer: 'as', options: ['as', 'ai', 'a'], instruction: 'Avoir' },
    { id: 'fr1-g50', type: 'Grammar', question: 'Indsæt: Il ___ (have).', answer: 'a', options: ['a', 'as', 'ai'], instruction: 'Avoir' },
    { id: 'fr1-g51', type: 'Grammar', question: 'Trés ___!', answer: 'bien', options: ['bien', 'mal', 'rouge'], instruction: 'Feedback' },
  ],
  2: [
    { id: 'fr2-g1', type: 'Grammar', question: 'Hvordan bøjes "Être" ved "Nous"?', answer: 'sommes', options: ['sommes', 'êtes', 'sont'], instruction: 'Être' },
    { id: 'fr2-g2', type: 'Grammar', question: 'Hvordan bøjes "Être" ved "Vous"?', answer: 'êtes', options: ['êtes', 'sommes', 'es'], instruction: 'Être' },
    { id: 'fr2-g3', type: 'Grammar', question: 'Hvordan bøjes "Être" ved "Ils"?', answer: 'sont', options: ['sont', 'suis', 'es'], instruction: 'Être' },
    { id: 'fr2-g4', type: 'Grammar', question: 'Indsæt: Nous ___ (have).', answer: 'avons', options: ['avons', 'avez', 'ont'], instruction: 'Avoir' },
    { id: 'fr2-g5', type: 'Grammar', question: 'Indsæt: Vous ___ (have).', answer: 'avez', options: ['avez', 'avons', 'ont'], instruction: 'Avoir' },
    { id: 'fr2-g6', type: 'Grammar', question: 'Indsæt: Ils ___ (have).', answer: 'ont', options: ['ont', 'avez', 'as'], instruction: 'Avoir' },
    { id: 'fr2-g7', type: 'Grammar', question: 'Hvad betyder "Regarder"?', answer: 'At kigge', options: ['At kigge', 'At lytte', 'At spise'], instruction: 'Verbes' },
    { id: 'fr2-g8', type: 'Grammar', question: 'Hvad betyder "Écouter"?', answer: 'At lytte', options: ['At lytte', 'At tale', 'At synge'], instruction: 'Verbes' },
    { id: 'fr2-g9', type: 'Grammar', question: 'Hvad betyder "Aimer"?', answer: 'At elske/kunne lide', options: ['At elske/kunne lide', 'At hade', 'At ville have'], instruction: 'Verbes' },
    { id: 'fr2-g10', type: 'Grammar', question: 'Hvad betyder "Détester"?', answer: 'At hade', options: ['At hade', 'At elske', 'At se'], instruction: 'Verbes' },
    { id: 'fr2-g11', type: 'Grammar', question: 'Tal: 11', answer: 'Onze', options: ['Onze', 'Douze', 'Treize'], instruction: 'Nombres' },
    { id: 'fr2-g12', type: 'Grammar', question: 'Tal: 12', answer: 'Douze', options: ['Douze', 'Onze', 'Treize'], instruction: 'Nombres' },
    { id: 'fr2-g13', type: 'Grammar', question: 'Tal: 13', answer: 'Treize', options: ['Treize', 'Quatorze', 'Quinze'], instruction: 'Nombres' },
    { id: 'fr2-g14', type: 'Grammar', question: 'Tal: 14', answer: 'Quatorze', options: ['Quatorze', 'Quinze', 'Seize'], instruction: 'Nombres' },
    { id: 'fr2-g15', type: 'Grammar', question: 'Tal: 15', answer: 'Quinze', options: ['Quinze', 'Seize', 'Dix-sept'], instruction: 'Nombres' },
    { id: 'fr2-g16', type: 'Grammar', question: 'Tal: 16', answer: 'Seize', options: ['Seize', 'Quinze', 'Treize'], instruction: 'Nombres' },
    { id: 'fr2-g17', type: 'Grammar', question: 'Tal: 20', answer: 'Vingt', options: ['Vingt', 'Trente', 'Dix'], instruction: 'Nombres' },
    { id: 'fr2-g18', type: 'Grammar', question: 'Hvad betyder "Bleu claire"?', answer: 'Lyseblå', options: ['Lyseblå', 'Mørkeblå', 'Blå'], instruction: 'Couleurs' },
    { id: 'fr2-g19', type: 'Grammar', question: 'Hvad betyder "Bleu foncé"?', answer: 'Mørkeblå', options: ['Mørkeblå', 'Lyseblå', 'Blå'], instruction: 'Couleurs' },
    { id: 'fr2-g20', type: 'Grammar', question: 'Hvilken farve er "Marron"?', answer: 'Brun', options: ['Brun', 'Grå', 'Lilla'], instruction: 'Couleurs' },
    { id: 'fr2-g21', type: 'Grammar', question: 'Hvilken farve er "Gris"?', answer: 'Grå', options: ['Grå', 'Sort', 'Brun'], instruction: 'Couleurs' },
    { id: 'fr2-g22', type: 'Grammar', question: 'Hvad betyder "Maintenant"?', answer: 'Nu', options: ['Nu', 'Senere', 'I går'], instruction: 'Temps' },
    { id: 'fr2-g23', type: 'Grammar', question: 'Hvad betyder "Demain"?', answer: 'I morgen', options: ['I morgen', 'I dag', 'I går'], instruction: 'Temps' },
    { id: 'fr2-g24', type: 'Grammar', question: 'Hvad betyder "Hier"?', answer: 'I går', options: ['I går', 'I dag', 'I morgen'], instruction: 'Temps' },
    { id: 'fr2-g25', type: 'Grammar', question: '"Le" eller "La"? ___ voiture (bil)', answer: 'La', options: ['La', 'Le'], instruction: 'Articles' },
    { id: 'fr2-g26', type: 'Grammar', question: '"Le" eller "La"? ___ train (tog)', answer: 'Le', options: ['Le', 'La'], instruction: 'Articles' },
    { id: 'fr2-g27', type: 'Grammar', question: 'Hvad betyder "Beau"?', answer: 'Smuk (hankøn)', options: ['Smuk (hankøn)', 'Grim', 'Lille'], instruction: 'Adjectifs' },
    { id: 'fr2-g28', type: 'Grammar', question: 'Hvad betyder "Belle"?', answer: 'Smuk (hunkøn)', options: ['Smuk (hunkøn)', 'Smuk (hankøn)', 'Lille'], instruction: 'Adjectifs' },
    { id: 'fr2-g29', type: 'Grammar', question: 'Hvad betyder "Content"?', answer: 'Glad', options: ['Glad', 'Trist', 'Vred'], instruction: 'Adjectifs' },
    { id: 'fr2-g30', type: 'Grammar', question: 'Hvad betyder "Triste"?', answer: 'Trist', options: ['Trist', 'Glad', 'Sjov'], instruction: 'Adjectifs' },
    { id: 'fr2-g31', type: 'Grammar', question: 'Hvad betyder "Rapide"?', answer: 'Hurtig', options: ['Hurtig', 'Langsom', 'Tung'], instruction: 'Adjectifs' },
    { id: 'fr2-g32', type: 'Grammar', question: 'Hvilket ord betyder "Hvor"?', answer: 'Où', options: ['Où', 'Quand', 'Comment'], instruction: 'Interrogatifs' },
    { id: 'fr2-g33', type: 'Grammar', question: 'Hvilket ord betyder "Hvornår"?', answer: 'Quand', options: ['Quand', 'Pourquoi', 'Qui'], instruction: 'Interrogatifs' },
    { id: 'fr2-g34', type: 'Grammar', question: 'Hvilket ord betyder "Hvorfor"?', answer: 'Pourquoi', options: ['Pourquoi', 'Comment', 'Combien'], instruction: 'Interrogatifs' },
    { id: 'fr2-g35', type: 'Grammar', question: 'Hvilket ord betyder "Hvem"?', answer: 'Qui', options: ['Qui', 'Quoi', 'Quel'], instruction: 'Interrogatifs' },
    { id: 'fr2-g36', type: 'Grammar', question: 'Hvad betyder "Boire"?', answer: 'At drikke', options: ['At drikke', 'At spise', 'At løbe'], instruction: 'Verbes' },
    { id: 'fr2-g37', type: 'Grammar', question: 'Hvad betyder "Vouloir"?', answer: 'At ville', options: ['At ville', 'At kunne', 'At skulle'], instruction: 'Verbes' },
    { id: 'fr2-g38', type: 'Grammar', question: 'Hvad betyder "Pouvoir"?', answer: 'At kunne', options: ['At kunne', 'At ville', 'At måtte'], instruction: 'Verbes' },
    { id: 'fr2-g39', type: 'Grammar', question: 'Hvad betyder "Devoir"?', answer: 'At skulle/være nødt til', options: ['At skulle/være nødt til', 'At kunne', 'At ville'], instruction: 'Verbes' },
    { id: 'fr2-g40', type: 'Grammar', question: '"Mon" eller "Ma"? ___ père', answer: 'Mon', options: ['Mon', 'Ma'], instruction: 'Possessifs' },
    { id: 'fr2-g41', type: 'Grammar', question: '"Mon" eller "Ma"? ___ mère', answer: 'Ma', options: ['Ma', 'Mon'], instruction: 'Possessifs' },
    { id: 'fr2-g42', type: 'Grammar', question: '"Ton" eller "Ta"? ___ livre (din bog)', answer: 'Ton', options: ['Ton', 'Ta'], instruction: 'Possessifs' },
    { id: 'fr2-g43', type: 'Grammar', question: '"Ton" eller "Ta"? ___ pomme (dit æble)', answer: 'Ta', options: ['Ta', 'Ton'], instruction: 'Possessifs' },
    { id: 'fr2-g44', type: 'Grammar', question: 'Hvad betyder "Et"?', answer: 'Og', options: ['Og', 'Men', 'Eller'], instruction: 'Conjonctions' },
    { id: 'fr2-g45', type: 'Grammar', question: 'Hvad betyder "Ou"?', answer: 'Eller', options: ['Eller', 'Og', 'Hvor'], instruction: 'Conjonctions' },
    { id: 'fr2-g46', type: 'Grammar', question: 'Hvad betyder "Mais"?', answer: 'Men', options: ['Men', 'Fordi', 'Selvom'], instruction: 'Conjonctions' },
    { id: 'fr2-g47', type: 'Grammar', question: 'Indsæt: Nous ___ (være) contents.', answer: 'sommes', options: ['sommes', 'êtes', 'sont'], instruction: 'Être' },
    { id: 'fr2-g48', type: 'Grammar', question: 'Indsæt: Ils ___ (være) grands.', answer: 'sont', options: ['sont', 'suis', 'es'], instruction: 'Être' },
    { id: 'fr2-g49', type: 'Grammar', question: 'Hvad betyder "Hunde" i flertal på fransk?', answer: 'Chiens', options: ['Chiens', 'Chien', 'Chienses'], instruction: 'Pluriel' },
    { id: 'fr2-g50', type: 'Grammar', question: 'Hvad betyder "Katte" i flertal på fransk?', answer: 'Chats', options: ['Chats', 'Chat', 'Chattes'], instruction: 'Pluriel' },
    { id: 'fr2-g51', type: 'Grammar', question: 'Bonne ___!', answer: 'chance', options: ['chance', 'mal', 'gris'], instruction: 'Feedback' },
  ],
  3: [
    { id: 'fr3-g1', type: 'Grammar', question: 'Indsæt bøjning: Je ___ (parler).', answer: 'parle', options: ['parle', 'parles', 'parlent'], instruction: 'Verbes en -er' },
    { id: 'fr3-g2', type: 'Grammar', question: 'Indsæt bøjning: Tu ___ (parler).', answer: 'parles', options: ['parles', 'parle', 'parlez'], instruction: 'Verbes en -er' },
    { id: 'fr3-g3', type: 'Grammar', question: 'Indsæt bøjning: Il ___ (parler).', answer: 'parle', options: ['parle', 'parlent', 'parles'], instruction: 'Verbes en -er' },
    { id: 'fr3-g4', type: 'Grammar', question: 'Indsæt bøjning: Nous ___ (parler).', answer: 'parlons', options: ['parlons', 'parlez', 'parle'], instruction: 'Verbes en -er' },
    { id: 'fr3-g5', type: 'Grammar', question: 'Indsæt bøjning: Vous ___ (parler).', answer: 'parlez', options: ['parlez', 'parlons', 'parlent'], instruction: 'Verbes en -er' },
    { id: 'fr3-g6', type: 'Grammar', question: 'Indsæt bøjning: Ils ___ (parler).', answer: 'parlent', options: ['parlent', 'parle', 'parlons'], instruction: 'Verbes en -er' },
    { id: 'fr3-g7', type: 'Grammar', question: 'Hvilket ord betyder "I dag"?', answer: 'Aujourd\'hui', options: ['Aujourd\'hui', 'Demain', 'Hier'], instruction: 'Temps' },
    { id: 'fr3-g8', type: 'Grammar', question: 'Hvilket ord betyder "Uger"?', answer: 'Semaines', options: ['Semaines', 'Mois', 'Jours'], instruction: 'Temps' },
    { id: 'fr3-g9', type: 'Grammar', question: 'Hvilket ord betyder "Måneder"?', answer: 'Mois', options: ['Mois', 'Années', 'Siècles'], instruction: 'Temps' },
    { id: 'fr3-g10', type: 'Grammar', question: 'Hvilket ord betyder "År"?', answer: 'Années', options: ['Années', 'Mois', 'Semaines'], instruction: 'Temps' },
    { id: 'fr3-g11', type: 'Grammar', question: '"Ce" eller "Cette"? ___ garçon (denne dreng)', answer: 'Ce', options: ['Ce', 'Cette'], instruction: 'Démonstratifs' },
    { id: 'fr3-g12', type: 'Grammar', question: '"Ce" eller "Cette"? ___ fille (denne pige)', answer: 'Cette', options: ['Cette', 'Ce'], instruction: 'Démonstratifs' },
    { id: 'fr3-g13', type: 'Grammar', question: 'Flertal af "Ce/Cette":', answer: 'Ces', options: ['Ces', 'Cet', 'Cettes'], instruction: 'Démonstratifs' },
    { id: 'fr3-g14', type: 'Grammar', question: 'Hvad betyder "Aller"?', answer: 'At gå/tage til', options: ['At gå/tage til', 'At komme fra', 'At blive'], instruction: 'Verbes' },
    { id: 'fr3-g15', type: 'Grammar', question: 'Hvordan bøjes "Aller" ved "Je"?', answer: 'vais', options: ['vais', 'vas', 'va'], instruction: 'Aller' },
    { id: 'fr3-g16', type: 'Grammar', question: 'Hvordan bøjes "Aller" ved "Tu"?', answer: 'vas', options: ['vas', 'vais', 'va'], instruction: 'Aller' },
    { id: 'fr3-g17', type: 'Grammar', question: 'Hvordan bøjes "Aller" ved "Il"?', answer: 'va', options: ['va', 'vais', 'vont'], instruction: 'Aller' },
    { id: 'fr3-g18', type: 'Grammar', question: 'Hvordan bøjes "Aller" ved "Nous"?', answer: 'allons', options: ['allons', 'allez', 'vont'], instruction: 'Aller' },
    { id: 'fr3-g19', type: 'Grammar', question: 'Hvordan bøjes "Aller" ved "Vous"?', answer: 'allez', options: ['allez', 'allons', 'vas'], instruction: 'Aller' },
    { id: 'fr3-g20', type: 'Grammar', question: 'Hvordan bøjes "Aller" ved "Ils"?', answer: 'vont', options: ['vont', 'va', 'allons'], instruction: 'Aller' },
    { id: 'fr3-g21', type: 'Grammar', question: 'Hvad betyder "Faire"?', answer: 'At gøre/lave', options: ['At gøre/lave', 'At have', 'At være'], instruction: 'Verbes' },
    { id: 'fr3-g22', type: 'Grammar', question: 'Hvordan bøjes "Faire" ved "Je"?', answer: 'fais', options: ['fais', 'fait', 'font'], instruction: 'Faire' },
    { id: 'fr3-g23', type: 'Grammar', question: 'Hvordan bøjes "Faire" ved "Nous"?', answer: 'faisons', options: ['faisons', 'faites', 'fais'], instruction: 'Faire' },
    { id: 'fr3-g24', type: 'Grammar', question: 'Hvordan bøjes "Faire" ved "Vous"?', answer: 'faites', options: ['faites', 'font', 'faisons'], instruction: 'Faire' },
    { id: 'fr3-g25', type: 'Grammar', question: 'Hvordan bøjes "Faire" ved "Ils"?', answer: 'font', options: ['font', 'fait', 'faites'], instruction: 'Faire' },
    { id: 'fr3-g26', type: 'Grammar', question: 'Præposition: "Jeg bor ___ København" (à / en).', answer: 'à', options: ['à', 'en', 'au'], instruction: 'Prépositions' },
    { id: 'fr3-g27', type: 'Grammar', question: 'Præposition: "Jeg bor ___ Frankrig" (en / au).', answer: 'en', options: ['en', 'au', 'à'], instruction: 'Prépositions (countries)' },
    { id: 'fr3-g28', type: 'Grammar', question: 'Præposition: "Jeg bor ___ Danmark" (au / en).', answer: 'au', options: ['au', 'en', 'à'], instruction: 'Prépositions (countries)' },
    { id: 'fr3-g29', type: 'Grammar', question: 'Hvad betyder "Le printemps"?', answer: 'Foråret', options: ['Foråret', 'Sommeren', 'Vinteren'], instruction: 'Saisons' },
    { id: 'fr3-g30', type: 'Grammar', question: 'Hvad betyder "L\’été"?', answer: 'Sommeren', options: ['Sommeren', 'Foråret', 'Efteråret'], instruction: 'Saisons' },
    { id: 'fr3-g31', type: 'Grammar', question: 'Hvad betyder "L\’automne"?', answer: 'Efteråret', options: ['Efteråret', 'Sommeren', 'Vinteren'], instruction: 'Saisons' },
    { id: 'fr3-g32', type: 'Grammar', question: 'Hvad betyder "L\’hiver"?', answer: 'Vinteren', options: ['Vinteren', 'Efteråret', 'Sommeren'], instruction: 'Saisons' },
    { id: 'fr3-g33', type: 'Grammar', question: 'Tal: 70', answer: 'Soixante-dix', options: ['Soixante-dix', 'Septante', 'Soixante'], instruction: 'Nombres' },
    { id: 'fr3-g34', type: 'Grammar', question: 'Tal: 80', answer: 'Quatre-vingts', options: ['Quatre-vingts', 'Huitante', 'Octante'], instruction: 'Nombres' },
    { id: 'fr3-g35', type: 'Grammar', question: 'Tal: 90', answer: 'Quatre-vingt-dix', options: ['Quatre-vingt-dix', 'Nonante', 'Quatre-vingts'], instruction: 'Nombres' },
    { id: 'fr3-g36', type: 'Grammar', question: 'Tal: 100', answer: 'Cent', options: ['Cent', 'Mille', 'Cinquante'], instruction: 'Nombres' },
    { id: 'fr3-g37', type: 'Grammar', question: 'Hvad betyder "Beaucoup"?', answer: 'Meget', options: ['Meget', 'Lidt', 'Nok'], instruction: 'Adverbes' },
    { id: 'fr3-g38', type: 'Grammar', question: 'Hvad betyder "Un peu"?', answer: 'Lidt', options: ['Lidt', 'Meget', 'Tit'], instruction: 'Adverbes' },
    { id: 'fr3-g39', type: 'Grammar', question: 'Hvad betyder "Très"?', answer: 'Meget/Rigtig', options: ['Meget/Rigtig', 'Tit', 'Aldrig'], instruction: 'Adverbes' },
    { id: 'fr3-g40', type: 'Grammar', question: 'Indsæt bøjning: Je ___ (aimer).', answer: 'aime', options: ['aime', 'aimes', 'aiment'], instruction: 'Verbes en -er' },
    { id: 'fr3-g41', type: 'Grammar', question: 'Indsæt bøjning: Tu ___ (aimer).', answer: 'aimes', options: ['aimes', 'aime', 'aimez'], instruction: 'Verbes en -er' },
    { id: 'fr3-g42', type: 'Grammar', question: 'Hvad betyder "Les devoirs"?', answer: 'Lektierne', options: ['Lektierne', 'Ferie', 'Skole'], instruction: 'Vocabulaire' },
    { id: 'fr3-g43', type: 'Grammar', question: 'Hvad betyder "Le déjeuner"?', answer: 'Frokosten', options: ['Frokosten', 'Morgenmaden', 'Aftensmaden'], instruction: 'Nourriture' },
    { id: 'fr3-g44', type: 'Grammar', question: 'Hvad betyder "Le dîner"?', answer: 'Aftensmaden', options: ['Aftensmaden', 'Frokosten', 'Mellemmåltid'], instruction: 'Nourriture' },
    { id: 'fr3-g45', type: 'Grammar', question: 'Hvad betyder "Le petit-déjeuner"?', answer: 'Morgenmaden', options: ['Morgenmaden', 'Aftensmaden', 'Frokos'], instruction: 'Nourriture' },
    { id: 'fr3-g46', type: 'Grammar', question: 'Hvad betyder "S\’il te plaît"?', answer: 'Vær så venlig (du)', options: ['Vær så venlig (du)', 'Tak', 'Ja tak'], instruction: 'Politesse' },
    { id: 'fr3-g47', type: 'Grammar', question: 'Betyder "Comment ça va?" Hvordan går det?', answer: 'Oui', options: ['Oui', 'Non'], instruction: 'Phrases' },
    { id: 'fr3-g48', type: 'Grammar', question: 'Betyder "Ça va bien" Det går godt?', answer: 'Oui', options: ['Oui', 'Non'], instruction: 'Phrases' },
    { id: 'fr3-g49', type: 'Grammar', question: 'Hvad betyder "Pourquoi"?', answer: 'Hvorfor', options: ['Hvorfor', 'Hvor', 'Hvornår'], instruction: 'Interrogatifs' },
    { id: 'fr3-g50', type: 'Grammar', question: 'Hvad betyder "Parce que"?', answer: 'Fordi', options: ['Fordi', 'Men', 'Derfor'], instruction: 'Conjonctions' },
    { id: 'fr3-g51', type: 'Grammar', question: 'C\'est ___!', answer: 'super', options: ['super', 'mal', 'gris'], instruction: 'Feedback' },
  ],
  4: [
    { id: 'fr4-g1', type: 'Grammar', question: 'Hvilket ord betyder "Altid"?', answer: 'Toujours', options: ['Toujours', 'Souvent', 'Jamais'], instruction: 'Adverbes de fréquence' },
    { id: 'fr4-g2', type: 'Grammar', question: 'Hvilket ord betyder "Ofte"?', answer: 'Souvent', options: ['Souvent', 'Toujours', 'Parfois'], instruction: 'Adverbes de fréquence' },
    { id: 'fr4-g3', type: 'Grammar', question: 'Hvilket ord betyder "Sommetider"?', answer: 'Parfois', options: ['Parfois', 'Jamais', 'Souvent'], instruction: 'Adverbes de fréquence' },
    { id: 'fr4-g4', type: 'Grammar', question: 'Hvilket ord betyder "Aldrig"?', answer: 'Jamais', options: ['Jamais', 'Toujours', 'Souvent'], instruction: 'Adverbes de fréquence' },
    { id: 'fr4-g5', type: 'Grammar', question: 'Hvad betyder "Pouvoir"?', answer: 'At kunne', options: ['At kunne', 'At ville', 'At skulle'], instruction: 'Verbes modaux' },
    { id: 'fr4-g6', type: 'Grammar', question: 'Hvordan bøjes "Pouvoir" ved "Je"?', answer: 'peux', options: ['peux', 'pouvez', 'peuvent'], instruction: 'Pouvoir' },
    { id: 'fr4-g7', type: 'Grammar', question: 'Hvordan bøjes "Pouvoir" ved "Nous"?', answer: 'pouvons', options: ['pouvons', 'pouvez', 'peuvent'], instruction: 'Pouvoir' },
    { id: 'fr4-g8', type: 'Grammar', question: 'Hvordan bøjes "Pouvoir" ved "Ils"?', answer: 'peuvent', options: ['peuvent', 'peux', 'peut'], instruction: 'Pouvoir' },
    { id: 'fr4-g9', type: 'Grammar', question: 'Hvad betyder "Vouloir"?', answer: 'At ville', options: ['At ville', 'At kunne', 'At have'], instruction: 'Verbes modaux' },
    { id: 'fr4-g10', type: 'Grammar', question: 'Hvordan bøjes "Vouloir" ved "Je"?', answer: 'veux', options: ['veux', 'voulons', 'voulez'], instruction: 'Vouloir' },
    { id: 'fr4-g11', type: 'Grammar', question: 'Hvordan bøjes "Vouloir" ved "Ils"?', answer: 'veulent', options: ['veulent', 'veux', 'veut'], instruction: 'Vouloir' },
    { id: 'fr4-g12', type: 'Grammar', question: 'Præposition: "Der er en bog ___ bordet" (sur / sous).', answer: 'sur', options: ['sur', 'sous', 'dans'], instruction: 'Prépositions' },
    { id: 'fr4-g13', type: 'Grammar', question: 'Præposition: "Hunden er ___ bordet" (under).', answer: 'sous', options: ['sous', 'sur', 'divant'], instruction: 'Prépositions' },
    { id: 'fr4-g14', type: 'Grammar', question: 'Præposition: "Han er ___ huset" (i).', answer: 'dans', options: ['dans', 'sur', 'derrière'], instruction: 'Prépositions' },
    { id: 'fr4-g15', type: 'Grammar', question: 'Hvordan dannes benægtelse på fransk?', answer: 'ne ... pas', options: ['ne ... pas', 'non pas', 'pas de'], instruction: 'Négation' },
    { id: 'fr4-g16', type: 'Grammar', question: 'Indsæt benægtelse: Je ___ mange ___ (jeg spiser ikke).', answer: 'ne / pas', options: ['ne / pas', 'no / pas', 'ne / non'], instruction: 'Négation' },
    { id: 'fr4-g17', type: 'Grammar', question: 'Hvad betyder "Je ne sais pas"?', answer: 'Jeg ved det ikke', options: ['Jeg ved det ikke', 'Jeg kan ikke', 'Jeg vil ikke'], instruction: 'Négation' },
    { id: 'fr4-g18', type: 'Grammar', question: 'Hvad betyder "Main"?', answer: 'Hånd', options: ['Hånd', 'Fod', 'Hoved'], instruction: 'Corps' },
    { id: 'fr4-g19', type: 'Grammar', question: 'Hvad betyder "Pied"?', answer: 'Fod', options: ['Fod', 'Hånd', 'Mave'], instruction: 'Corps' },
    { id: 'fr4-g20', type: 'Grammar', question: 'Hvad betyder "Tête"?', answer: 'Hoved', options: ['Hoved', 'Arm', 'Ben'], instruction: 'Corps' },
    { id: 'fr4-g21', type: 'Grammar', question: 'Hvad betyder "Bras"?', answer: 'Arm', options: ['Arm', 'Ben', 'Ryg'], instruction: 'Corps' },
    { id: 'fr4-g22', type: 'Grammar', question: 'Hvad betyder "Jambe"?', answer: 'Ben', options: ['Ben', 'Fod', 'Mave'], instruction: 'Corps' },
    { id: 'fr4-g23', type: 'Grammar', question: 'Tal: 1000', answer: 'Mille', options: ['Mille', 'Cent', 'Million'], instruction: 'Nombres' },
    { id: 'fr4-g24', type: 'Grammar', question: 'Tal: 2000', answer: 'Deux mille', options: ['Deux mille', 'Mille deux', 'Deux cents'], instruction: 'Nombres' },
    { id: 'fr4-g25', type: 'Grammar', question: 'Hvad betyder "Cher"?', answer: 'Dyr', options: ['Dyr', 'Billig', 'Smuk'], instruction: 'Adjectifs' },
    { id: 'fr4-g26', type: 'Grammar', question: 'Hvad betyder "Bon marché"?', answer: 'Billig', options: ['Billig', 'Dyr', 'Grim'], instruction: 'Adjectifs' },
    { id: 'fr4-g27', type: 'Grammar', question: 'Hvad betyder "Nouveau"?', answer: 'Ny', options: ['Ny', 'Gammel', 'Hurtig'], instruction: 'Adjectifs' },
    { id: 'fr4-g28', type: 'Grammar', question: 'Hvad betyder "Vieux"?', answer: 'Gammel', options: ['Gammel', 'Ny', 'Langsom'], instruction: 'Adjectifs' },
    { id: 'fr4-g29', type: 'Grammar', question: 'Hvad betyder "Travailler"?', answer: 'At arbejde', options: ['At arbejde', 'At sove', 'At lege'], instruction: 'Verbes' },
    { id: 'fr4-g30', type: 'Grammar', question: 'Hvordan bøjes "Travailler" ved "Nous"?', answer: 'travaillons', options: ['travaillons', 'travaillez', 'travaillent'], instruction: 'Verbes -er' },
    { id: 'fr4-g31', type: 'Grammar', question: 'Hvad betyder "Aider"?', answer: 'At hjælpe', options: ['At hjælpe', 'At spørge', 'At svare'], instruction: 'Verbes' },
    { id: 'fr4-g32', type: 'Grammar', question: 'Hvad betyder "Chercher"?', answer: 'At lede efter', options: ['At lede efter', 'At finde', 'At gemme'], instruction: 'Verbes' },
    { id: 'fr4-g33', type: 'Grammar', question: 'Hvad betyder "Trouver"?', answer: 'At finde', options: ['At finde', 'At lede efter', 'At tabe'], instruction: 'Verbes' },
    { id: 'fr4-g34', type: 'Grammar', question: 'Hvilket ord betyder "Hvor meget"?', answer: 'Combien', options: ['Combien', 'Comment', 'Où'], instruction: 'Interrogatifs' },
    { id: 'fr4-g35', type: 'Grammar', question: 'Hvilket ord betyder "Hvilken"?', answer: 'Quel', options: ['Quel', 'Qui', 'Quoi'], instruction: 'Interrogatifs' },
    { id: 'fr4-g36', type: 'Grammar', question: 'Hvilket ord betyder "Hvordan"?', answer: 'Comment', options: ['Comment', 'Pourquoi', 'Où'], instruction: 'Interrogatifs' },
    { id: 'fr4-g37', type: 'Grammar', question: '"Le" eller "La"? ___ ville (by)', answer: 'La', options: ['La', 'Le'], instruction: 'Articles' },
    { id: 'fr4-g38', type: 'Grammar', question: '"Le" eller "La"? ___ village (landsby)', answer: 'Le', options: ['Le', 'La'], instruction: 'Articles' },
    { id: 'fr4-g39', type: 'Grammar', question: 'Hvad betyder "Le pays"?', answer: 'Landet', options: ['Landet', 'Byen', 'Skoven'], instruction: 'Vocabulaire' },
    { id: 'fr4-g40', type: 'Grammar', question: 'Hvad betyder "Le monde"?', answer: 'Verden', options: ['Verden', 'Landet', 'Hovedet'], instruction: 'Vocabulaire' },
    { id: 'fr4-g41', type: 'Grammar', question: 'Er "France" hunkøn?', answer: 'Oui (la France)', options: ['Oui', 'Non'], instruction: 'Genre' },
    { id: 'fr4-g42', type: 'Grammar', question: 'Er "Danemark" hankøn?', answer: 'Oui (le Danemark)', options: ['Oui', 'Non'], instruction: 'Genre' },
    { id: 'fr4-g43', type: 'Grammar', question: 'Hvad betyder "Aussi"?', answer: 'Også', options: ['Også', 'Kun', 'Måske'], instruction: 'Vocabulaire' },
    { id: 'fr4-g44', type: 'Grammar', question: 'Hvad betyder "Seulement"?', answer: 'Kun', options: ['Kun', 'Tit', 'Aldrig'], instruction: 'Adverbes' },
    { id: 'fr4-g45', type: 'Grammar', question: 'Hvad betyder "Peut-être"?', answer: 'Måske', options: ['Måske', 'Helt sikkert', 'Aldrig'], instruction: 'Adverbes' },
    { id: 'fr4-g46', type: 'Grammar', question: 'Hvad betyder "Bien sûr"?', answer: 'Selvfølgelig', options: ['Selvfølgelig', 'Måske', 'Nej'], instruction: 'Adverbes' },
    { id: 'fr4-g47', type: 'Grammar', question: 'Indsæt bøjning: Elles ___ (parler).', answer: 'parlent', options: ['parlent', 'parle', 'parles'], instruction: 'Verbes -er' },
    { id: 'fr4-g48', type: 'Grammar', question: 'Indsæt bøjning: Vous ___ (aimer).', answer: 'aimez', options: ['aimez', 'aimons', 'aiment'], instruction: 'Verbes -er' },
    { id: 'fr4-g49', type: 'Grammar', question: 'Hvad betyder "Il y a"?', answer: 'Der er / Der findes', options: ['Der er / Der findes', 'Han er', 'Han har'], instruction: 'Locution' },
    { id: 'fr4-g50', type: 'Grammar', question: 'Hvad betyder "D\’accord"?', answer: 'Enig / Okay', options: ['Enig / Okay', 'Uenig', 'Nej'], instruction: 'Vocabulaire' },
    { id: 'fr4-g51', type: 'Grammar', question: 'C\'est ___!', answer: 'parfait', options: ['parfait', 'mal', 'blanc'], instruction: 'Feedback' },
  ],
};
