/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const SPANSK_GRAMMAR: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'sp0-g1', type: 'Grammar', question: '¿Cuál palabra es una cosa?', answer: 'Pelota', options: ['Pelota', 'Correr', 'Feliz'], instruction: 'Comprensión' },
    { id: 'sp0-g2', type: 'Grammar', question: '¿Cuál palabra es un color?', answer: 'Rojo', options: ['Rojo', 'Perro', 'Dormir'], instruction: 'Comprensión' },
    { id: 'sp0-g3', type: 'Grammar', question: '¿Cuál palabra es algo que haces?', answer: 'Saltar', options: ['Saltar', 'Silla', 'Verde'], instruction: 'Comprensión' },
    { id: 'sp0-g4', type: 'Grammar', question: '¿Qué palabra rima con "gato"?', answer: 'Pato', options: ['Pato', 'Perro', 'Ratón'], instruction: 'Rimas' },
    { id: 'sp0-g5', type: 'Grammar', question: '¿Qué palabra rima con "casa"?', answer: 'Masa', options: ['Masa', 'Sol', 'Luna'], instruction: 'Rimas' },
    { id: 'sp0-g6', type: 'Grammar', question: '¿Qué palabra rima con "limón"?', answer: 'Avión', options: ['Avión', 'Sopa', 'Pan'], instruction: 'Rimas' },
    { id: 'sp0-g7', type: 'Grammar', question: '¿Qué palabra empieza con S?', answer: 'Sol', options: ['Sol', 'Luna', 'Nube'], instruction: 'Letras' },
    { id: 'sp0-g8', type: 'Grammar', question: '¿Qué palabra empieza con B?', answer: 'Barco', options: ['Barco', 'Coche', 'Tren'], instruction: 'Letras' },
    { id: 'sp0-g9', type: 'Grammar', question: 'Encuentra la palabra larga:', answer: 'Elefante', options: ['Elefante', 'Pan', 'Luz'], instruction: 'Comprensión' },
    { id: 'sp0-g10', type: 'Grammar', question: '¿Cuántas sílabas tiene "sol"?', answer: '1', options: ['1', '2', '3'], instruction: 'Sílabas' },
    { id: 'sp0-g11', type: 'Grammar', question: '¿Cuántas sílabas tiene "casa"?', answer: '2', options: ['2', '1', '3'], instruction: 'Sílabas' },
    { id: 'sp0-g12', type: 'Grammar', question: '¿Cuántas sílabas tiene "mariposa"?', answer: '4', options: ['4', '3', '2'], instruction: 'Sílabas' },
    { id: 'sp0-g13', type: 'Grammar', question: '¿Qué animal es peligroso?', answer: 'León', options: ['León', 'Conejo', 'Oveja'], instruction: 'Comprensión' },
    { id: 'sp0-g14', type: 'Grammar', question: '¿Qué es lo opuesto de grande?', answer: 'Pequeño', options: ['Pequeño', 'Alto', 'Azul'], instruction: 'Antónimos' },
    { id: 'sp0-g15', type: 'Grammar', question: '¿Qué es lo opuesto de feliz?', answer: 'Triste', options: ['Triste', 'Dulce', 'Rápido'], instruction: 'Antónimos' },
    { id: 'sp0-g16', type: 'Grammar', question: '¿Qué es lo opuesto de día?', answer: 'Noche', options: ['Noche', 'Sol', 'Mañana'], instruction: 'Antónimos' },
    { id: 'sp0-g17', type: 'Grammar', question: 'Encuentra la letra A:', answer: 'A', options: ['A', 'E', 'O'], instruction: 'Letras' },
    { id: 'sp0-g18', type: 'Grammar', question: 'Encuentra la letra M:', answer: 'M', options: ['M', 'N', 'W'], instruction: 'Letras' },
    { id: 'sp0-g19', type: 'Grammar', question: 'Encuentra una palabra con O:', answer: 'Oso', options: ['Oso', 'Isla', 'Árbol'], instruction: 'Letras' },
    { id: 'sp0-g20', type: 'Grammar', question: '¿Qué dice la vaca?', answer: 'Muuu', options: ['Muuu', 'Miau', 'Guau'], instruction: 'Sonidos' },
    { id: 'sp0-g21', type: 'Grammar', question: '¿Qué dice el gato?', answer: 'Miau', options: ['Miau', 'Guau', 'Muuu'], instruction: 'Sonidos' },
    { id: 'sp0-g22', type: 'Grammar', question: '¿Qué dice el perro?', answer: 'Guau', options: ['Guau', 'Pío', 'Cua'], instruction: 'Sonidos' },
    { id: 'sp0-g23', type: 'Grammar', question: '¿De qué color es un plátano?', answer: 'Amarillo', options: ['Amarillo', 'Rojo', 'Azul'], instruction: 'Comprensión' },
    { id: 'sp0-g24', type: 'Grammar', question: '¿De qué color es la hierba?', answer: 'Verde', options: ['Verde', 'Lila', 'Naranja'], instruction: 'Comprensión' },
    { id: 'sp0-g25', type: 'Grammar', question: 'Encuentra un animal con cuatro patas:', answer: 'Perro', options: ['Perro', 'Pájaro', 'Serpiente'], instruction: 'Comprensión' },
  ],
  1: [
    { id: 'sp1-g1', type: 'Grammar', question: '¿Cuál palabra es un sustantivo?', answer: 'Casa', options: ['Casa', 'Correr', 'Azul'], instruction: 'Clases de palabras' },
    { id: 'sp1-g2', type: 'Grammar', question: '¿Cuál palabra es un verbo?', answer: 'Comer', options: ['Comer', 'Taza', 'Rojo'], instruction: 'Clases de palabras' },
    { id: 'sp1-g3', type: 'Grammar', question: '¿Cuál palabra es un adjetivo?', answer: 'Dulce', options: ['Dulce', 'Hombre', 'Ir'], instruction: 'Clases de palabras' },
    { id: 'sp1-g4', type: 'Grammar', question: '¿Es "el" o "la" silla?', answer: 'La', options: ['La', 'El'], instruction: 'Artículos' },
    { id: 'sp1-g5', type: 'Grammar', question: '¿Es "el" o "la" coche?', answer: 'El', options: ['El', 'La'], instruction: 'Artículos' },
    { id: 'sp1-g6', type: 'Grammar', question: 'Plural de "perro":', answer: 'Perros', options: ['Perros', 'Perra', 'Perrito'], instruction: 'Bøjning (Plural)' },
    { id: 'sp1-g7', type: 'Grammar', question: 'Plural de "flor":', answer: 'Flores', options: ['Flores', 'Flors', 'Florez'], instruction: 'Bøjning (Plural)' },
    { id: 'sp1-g8', type: 'Grammar', question: '¿Qué letra falta en _ol?', answer: 'S', options: ['S', 'B', 'M'], instruction: 'Ortografía' },
    { id: 'sp1-g9', type: 'Grammar', question: '¿Qué letra falta en ca_a?', answer: 's', options: ['s', 'z', 'm'], instruction: 'Ortografía' },
    { id: 'sp1-g10', type: 'Grammar', question: '¿Cuál palabra empieza con vocal?', answer: 'Árbol', options: ['Árbol', 'Perro', 'Gato'], instruction: 'Vocales' },
    { id: 'sp1-g11', type: 'Grammar', question: '¿Cuál palabra empieza con consonante?', answer: 'Casa', options: ['Casa', 'Osito', 'Uva'], instruction: 'Consonantes' },
    { id: 'sp1-g12', type: 'Grammar', question: 'Conjuga "saltar" en presente:', answer: 'Salto', options: ['Salto', 'Salté', 'Saltado'], instruction: 'Verbos' },
    { id: 'sp1-g13', type: 'Grammar', question: 'Conjuga "comer" en presente:', answer: 'Como', options: ['Como', 'Comí', 'Comido'], instruction: 'Verbos' },
    { id: 'sp1-g14', type: 'Grammar', question: 'Encuentra el sustantivo en: "La niña juega"', answer: 'niña', options: ['niña', 'juega'], instruction: 'Análisis' },
    { id: 'sp1-g15', type: 'Grammar', question: 'Encuentra el verbo en: "El niño come"', answer: 'come', options: ['niño', 'come'], instruction: 'Análisis' },
    { id: 'sp1-g16', type: 'Grammar', question: '¿Cuál es un nombre propio?', answer: 'María', options: ['María', 'Niña', 'Saltar'], instruction: 'Nombres propios' },
    { id: 'sp1-g17', type: 'Grammar', question: '¿Los nombres propios van con mayúscula?', answer: 'Sí', options: ['Sí', 'No'], instruction: 'Ortografía' },
    { id: 'sp1-g18', type: 'Grammar', question: '¿Se empieza una oración con mayúscula?', answer: 'Sí', options: ['Sí', 'No'], instruction: 'Ortografía' },
    { id: 'sp1-g19', type: 'Grammar', question: '¿Se termina una oración con punto?', answer: 'Sí', options: ['Sí', 'No'], instruction: 'Ortografía' },
    { id: 'sp1-g20', type: 'Grammar', question: '¿Cuándo usamos el signo interrogativo (?)?', answer: 'En preguntas', options: ['En preguntas', 'En respuestas', 'En gritos'], instruction: 'Puntuación' },
    { id: 'sp1-g21', type: 'Grammar', question: '¿Qué palabra rima con "mar"?', answer: 'Cantar', options: ['Cantar', 'Tierra', 'Agua'], instruction: 'Rimas' },
    { id: 'sp1-g22', type: 'Grammar', question: '¿Qué es lo opuesto de frío?', answer: 'Caliente', options: ['Caliente', 'Hielo', 'Nieve'], instruction: 'Antónimos' },
    { id: 'sp1-g23', type: 'Grammar', question: '¿Qué es lo opuesto de joven?', answer: 'Viejo', options: ['Viejo', 'Niño', 'Nuevo'], instruction: 'Antónimos' },
    { id: 'sp1-g24', type: 'Grammar', question: 'Sinónimo de "feliz":', answer: 'Contento', options: ['Contento', 'Triste', 'Cansado'], instruction: 'Sinónimos' },
    { id: 'sp1-g25', type: 'Grammar', question: 'Sinónimo de "enojado":', answer: 'Enfadado', options: ['Enfadado', 'Alegre', 'Divertido'], instruction: 'Sinónimos' },
  ],
  2: [
    { id: 'sp2-g1', type: 'Grammar', question: 'Encuentra el sustantivo:', answer: 'Coche', options: ['Coche', 'Saltar', 'Azul', 'Hola'], instruction: 'Clases de palabras' },
    { id: 'sp2-g2', type: 'Grammar', question: 'Encuentra el verbo:', answer: 'Beber', options: ['Beber', 'Taza', 'Rojo', 'Aquí'], instruction: 'Clases de palabras' },
    { id: 'sp2-g3', type: 'Grammar', question: 'Encuentra el adjetivo:', answer: 'Verde', options: ['Saltar', 'Verde', 'Perro'], instruction: 'Clases de palabras' },
    { id: 'sp2-g4', type: 'Grammar', question: 'Plural de "casa":', answer: 'Casas', options: ['Casas', 'Casitos', 'Caser'], instruction: 'Plural' },
    { id: 'sp2-g5', type: 'Grammar', question: 'Plural de "lápiz":', answer: 'Lápices', options: ['Lápices', 'Lápizs', 'Lapizes'], instruction: 'Plural' },
    { id: 'sp2-g6', type: 'Grammar', question: 'Plural de "pez":', answer: 'Peces', options: ['Peces', 'Pezs', 'Pezez'], instruction: 'Plural' },
    { id: 'sp2-g7', type: 'Grammar', question: 'Encuentra el verbo en presente: "Él ___"', answer: 'corre', options: ['corre', 'corrió', 'correr'], instruction: 'Tiempos verbales' },
    { id: 'sp2-g8', type: 'Grammar', question: 'Encuentra el verbo en pasado: "Él ___ ayer"', answer: 'corrió', options: ['corrió', 'corre', 'correr'], instruction: 'Tiempos verbales' },
    { id: 'sp2-g9', type: 'Grammar', question: '¿Cómo se escribe "niños" en femenino?', answer: 'Niñas', options: ['Niñas', 'Niños', 'Niñes'], instruction: 'Género' },
    { id: 'sp2-g10', type: 'Grammar', question: '¿Cómo se escribe "doctor" en femenino?', answer: 'Doctora', options: ['Doctora', 'Doctor', 'Doctoras'], instruction: 'Género' },
    { id: 'sp2-g11', type: 'Grammar', question: '¿Qué clase de palabra es "nosotros"?', answer: 'Pronombre personal', options: ['Pronombre personal', 'Pronombre posesivo', 'Sustantivo'], instruction: 'Gramática' },
    { id: 'sp2-g12', type: 'Grammar', question: '¿Qué clase de palabra es "nuestro"?', answer: 'Pronombre posesivo', options: ['Pronombre posesivo', 'Pronombre personal', 'Sustantivo'], instruction: 'Gramática' },
    { id: 'sp2-g13', type: 'Grammar', question: 'Opuesto de "lento":', answer: 'Rápido', options: ['Rápido', 'Caracol', 'Ir'], instruction: 'Antónimos' },
    { id: 'sp2-g14', type: 'Grammar', question: 'Opuesto de "calor":', answer: 'Frío', options: ['Frío', 'Sol', 'Verano'], instruction: 'Antónimos' },
    { id: 'sp2-g15', type: 'Grammar', question: 'Encuentra el sustantivo: "El sol brilla"', answer: 'sol', options: ['sol', 'brilla'], instruction: 'Análisis' },
    { id: 'sp2-g16', type: 'Grammar', question: 'Encuentra el verbo: "El sol brilla"', answer: 'brilla', options: ['brilla', 'sol'], instruction: 'Análisis' },
    { id: 'sp2-g17', type: 'Grammar', question: 'Encuentra el adjetivo: "Una pelota roja"', answer: 'roja', options: ['roja', 'Una', 'pelota'], instruction: 'Análisis' },
    { id: 'sp2-g18', type: 'Grammar', question: '¿Qué palabra es un número?', answer: 'Cinco', options: ['Cinco', 'Muchos', 'Grande'], instruction: 'Clases de palabras' },
    { id: 'sp2-g19', type: 'Grammar', question: '¿Qué palabra es un pronombre?', answer: 'Ellos', options: ['Ellos', 'Casa', 'Alegre'], instruction: 'Clases de palabras' },
    { id: 'sp2-g20', type: 'Grammar', question: '¿Qué palabra es una preposición?', answer: 'En', options: ['En', 'Ir', 'Verde'], instruction: 'Clases de palabras' },
    { id: 'sp2-g21', type: 'Grammar', question: '¿Qué palabra es una conjunción?', answer: 'Porque', options: ['Porque', 'Quizás', 'Siempre'], instruction: 'Clases de palabras' },
    { id: 'sp2-g22', type: 'Grammar', question: 'Grados de "bueno":', answer: 'Bueno, mejor, óptimo', options: ['Bueno, mejor, óptimo', 'Bueno, buenoe, buenost', 'Bueno, muy bueno, el más bueno'], instruction: 'Comparativos' },
    { id: 'sp2-g23', type: 'Grammar', question: 'Grados de "malo":', answer: 'Malo, peor, pésimo', options: ['Malo, peor, pésimo', 'Malo, maloe, malost', 'Malo, malito, muy malo'], instruction: 'Comparativos' },
    { id: 'sp2-g24', type: 'Grammar', question: 'Mayúscula en nombres propios:', answer: 'España', options: ['España', 'país', 'lengua'], instruction: 'Ortografía' },
    { id: 'sp2-g25', type: 'Grammar', question: '¿Cuántas sílabas tiene "mariposa"?', answer: '4', options: ['4', '3', '2'], instruction: 'Sílabas' },
  ],
  3: [
    { id: 'sp3-g1', type: 'Grammar', question: '¿Cuál es la clase de "rápidamente" en: "Corre rápidamente"?', answer: 'Adverbio', options: ['Adverbio', 'Adjetivo', 'Verbo'], instruction: 'Clases de palabras' },
    { id: 'sp3-g2', type: 'Grammar', question: '¿Cuál es la clase de "hermoso" en: "Un día hermoso"?', answer: 'Adjetivo', options: ['Adjetivo', 'Adverbio', 'Sustantivo'], instruction: 'Clases de palabras' },
    { id: 'sp3-g3', type: 'Grammar', question: 'Encuentra el sustantivo: "Los coches corren velozmente"', answer: 'coches', options: ['coches', 'corren', 'velozmente'], instruction: 'Análisis' },
    { id: 'sp3-g4', type: 'Grammar', question: 'Encuentra el verbo: "Los coches corren velozmente"', answer: 'corren', options: ['corren', 'coches', 'velozmente'], instruction: 'Análisis' },
    { id: 'sp3-g5', type: 'Grammar', question: 'Encuentra el adverbio: "Los coches corren velozmente"', answer: 'velozmente', options: ['velozmente', 'corren', 'coches'], instruction: 'Análisis' },
    { id: 'sp3-g6', type: 'Grammar', question: 'Comparativo de "grande":', answer: 'Más grande que', options: ['Más grande que', 'Grande que', 'Muy grande que'], instruction: 'Comparativos' },
    { id: 'sp3-g7', type: 'Grammar', question: 'Superlativo de "grande":', answer: 'Grandísimo', options: ['Grandísimo', 'Más grande', 'El más grande'], instruction: 'Superlativos' },
    { id: 'sp3-g8', type: 'Grammar', question: '¿Qué tiempo es: "Nosotros hemos jugado"?', answer: 'Pretérito perfecto', options: ['Pretérito perfecto', 'Presente', 'Pasado'], instruction: 'Tiempos verbales' },
    { id: 'sp3-g9', type: 'Grammar', question: '¿Qué tiempo es: "Nosotros jugaremos"?', answer: 'Futuro', options: ['Futuro', 'Presente', 'Pasado'], instruction: 'Tiempos verbales' },
    { id: 'sp3-g10', type: 'Grammar', question: '¿Cuál es una conjunción?', answer: 'Pero', options: ['Pero', 'Correr', 'Grande'], instruction: 'Gramática' },
    { id: 'sp3-g11', type: 'Grammar', question: '¿Cuál es una preposición?', answer: 'Sobre', options: ['Sobre', 'Muchos', 'Pero'], instruction: 'Gramática' },
    { id: 'sp3-g12', type: 'Grammar', question: 'Sujeto en: "Mi padre cocina la cena"', answer: 'Mi padre', options: ['Mi padre', 'cocina', 'la cena'], instruction: 'Sintaxis' },
    { id: 'sp3-g13', type: 'Grammar', question: 'Verbo en: "Mi padre cocina la cena"', answer: 'cocina', options: ['cocina', 'Mi padre', 'cena'], instruction: 'Sintaxis' },
    { id: 'sp3-g14', type: 'Grammar', question: 'Objeto directo en: "Él come una manzana"', answer: 'una manzana', options: ['una manzana', 'Él', 'come'], instruction: 'Sintaxis' },
    { id: 'sp3-g15', type: 'Grammar', question: 'Plural de "lección":', answer: 'Lecciones', options: ['Lecciones', 'Leccion', 'Leccións'], instruction: 'Ortografía' },
    { id: 'sp3-g16', type: 'Grammar', question: 'Plural de "corazón":', answer: 'Corazones', options: ['Corazones', 'Corazon', 'Corazónes'], instruction: 'Ortografía' },
    { id: 'sp3-g17', type: 'Grammar', question: 'Encuentra la palabra compuesta:', answer: 'Sacapuntas', options: ['Sacapuntas', 'Lápiz', 'Goma'], instruction: 'Morfología' },
    { id: 'sp3-g18', type: 'Grammar', question: 'Encuentra la palabra compuesta:', answer: 'Paraguas', options: ['Paraguas', 'Agua', 'Lluvia'], instruction: 'Morfología' },
    { id: 'sp3-g19', type: 'Grammar', question: '¿"Cuál" es una palabra interrogativa?', answer: 'Sí', options: ['Sí', 'No'], instruction: 'Gramática' },
    { id: 'sp3-g20', type: 'Grammar', question: '¿"Porque" indica causa?', answer: 'Sí', options: ['Sí', 'No'], instruction: 'Gramática' },
    { id: 'sp3-g21', type: 'Grammar', question: '¿Qué es "mío"?', answer: 'Pronombre posesivo', options: ['Pronombre posesivo', 'Pronombre personal', 'Pronombre demostrativo'], instruction: 'Clases de palabras' },
    { id: 'sp3-g22', type: 'Grammar', question: '¿Qué es "tuyo"?', answer: 'Pronombre posesivo', options: ['Pronombre posesivo', 'Pronombre personal', 'Pronombre relativo'], instruction: 'Clases de palabras' },
    { id: 'sp3-g23', type: 'Grammar', question: 'Encuentra el error: "Ellos come pan"', answer: 'come', options: ['come', 'Ellos', 'pan'], instruction: 'Corrección' },
    { id: 'sp3-g24', type: 'Grammar', question: 'Encuentra el error: "La perro es blanco"', answer: 'La', options: ['La', 'perro', 'es'], instruction: 'Corrección' },
    { id: 'sp3-g25', type: 'Grammar', question: '¿Cómo se dice "doctor" en femenino?', answer: 'Doctora', options: ['Doctora', 'Doctor', 'Doctoras'], instruction: 'Género' },
  ],
  4: [
    { id: 'sp4-g1', type: 'Grammar', question: 'Prefijo: "des-" + "hacer" = ?', answer: 'Deshacer', options: ['Deshacer', 'Hacer des', 'Dehacer'], instruction: 'Morfología' },
    { id: 'sp4-g2', type: 'Grammar', question: 'Sufijo: "feliz" + "-mente" = ?', answer: 'Felizmente', options: ['Felizmente', 'Felicidad', 'Mente feliz'], instruction: 'Morfología' },
    { id: 'sp4-g3', type: 'Grammar', question: 'Encuentra el adverbio: "Cantaron muy bien"', answer: 'muy', options: ['muy', 'bien', 'Cantaron'], instruction: 'Clases de palabras' },
    { id: 'sp4-g4', type: 'Grammar', question: 'Encuentra el adverbio: "La casa es muy antigua"', answer: 'muy', options: ['muy', 'antigua', 'casa'], instruction: 'Clases de palabras' },
    { id: 'sp4-g5', type: 'Grammar', question: 'Grados de "alto":', answer: 'Alto, más alto, el más alto', options: ['Alto, más alto, el más alto', 'Alto, altor, altost', 'Alto, muy alto, altísimo'], instruction: 'Comparativos' },
    { id: 'sp4-g6', type: 'Grammar', question: 'Grados de "bajo":', answer: 'Bajo, menos bajo, el menos bajo', options: ['Bajo, menos bajo, el menos bajo', 'Bajo, bajor, bajost', 'Bajo, bajísimo, muy bajo'], instruction: 'Comparativos' },
    { id: 'sp4-g7', type: 'Grammar', question: 'Conjuga "escribir" en presente:', answer: 'Escribo', options: ['Escribo', 'Escribí', 'Escribido'], instruction: 'Verbos' },
    { id: 'sp4-g8', type: 'Grammar', question: 'Conjuga "escribir" en pasado:', answer: 'Escribí', options: ['Escribí', 'Escribo', 'Escribiré'], instruction: 'Verbos' },
    { id: 'sp4-g9', type: 'Grammar', question: 'Conjuga "escribir" en futuro:', answer: 'Escribiré', options: ['Escribiré', 'Escribí', 'Escribo'], instruction: 'Verbos' },
    { id: 'sp4-g10', type: 'Grammar', question: 'Infinitivo de "corro":', answer: 'Correr', options: ['Correr', 'Corrido', 'Corriendo'], instruction: 'Infinitivos' },
    { id: 'sp4-g11', type: 'Grammar', question: 'Infinitivo de "bebo":', answer: 'Beber', options: ['Beber', 'Bebido', 'Bebiendo'], instruction: 'Infinitivos' },
    { id: 'sp4-g12', type: 'Grammar', question: 'Infinitivo de "vivo":', answer: 'Vivir', options: ['Vivir', 'Vivido', 'Viviendo'], instruction: 'Infinitivos' },
    { id: 'sp4-g13', type: 'Grammar', question: 'Sujeto: "El pastel fue comido por el niño"', answer: 'El pastel', options: ['El pastel', 'el niño', 'comido'], instruction: 'Voz pasiva' },
    { id: 'sp4-g14', type: 'Grammar', question: 'Complemento agente: "El pastel fue comido por el niño"', answer: 'por el niño', options: ['por el niño', 'El pastel', 'fue comido'], instruction: 'Voz pasiva' },
    { id: 'sp4-g15', type: 'Grammar', question: '¿"Haber" es un verbo auxiliar?', answer: 'Sí', options: ['Sí', 'No'], instruction: 'Verbos' },
    { id: 'sp4-g16', type: 'Grammar', question: '¿"Ser" y "Estar" significan lo mismo?', answer: 'No', options: ['Sí', 'No'], instruction: 'Verbos' },
    { id: 'sp4-g17', type: 'Grammar', question: 'Plural de "pared":', answer: 'Paredes', options: ['Paredes', 'Pareds', 'Paredez'], instruction: 'Ortografía' },
    { id: 'sp4-g18', type: 'Grammar', question: 'Plural de "verdad":', answer: 'Verdades', options: ['Verdades', 'Verdads', 'Verdadz'], instruction: 'Ortografía' },
    { id: 'sp4-g19', type: 'Grammar', question: '¿Qué tiempo es: "Ellos viajarán"?', answer: 'Futuro', options: ['Futuro', 'Presente', 'Pasado'], instruction: 'Tiempos verbales' },
    { id: 'sp4-g20', type: 'Grammar', question: '¿En qué persona está "nosotros"?', answer: '1ª persona plural', options: ['1ª persona plural', '2ª persona plural', '3ª persona plural'], instruction: 'Pronombres' },
    { id: 'sp4-g21', type: 'Grammar', question: '¿En qué persona está "ustedes"?', answer: '2ª persona plural', options: ['2ª persona plural', '1ª persona plural', '3ª persona plural'], instruction: 'Pronombres' },
    { id: 'sp4-g22', type: 'Grammar', question: '¿En qué persona está "ellos"?', answer: '3ª persona plural', options: ['3ª persona plural', '1ª persona plural', '2ª persona plural'], instruction: 'Pronombres' },
    { id: 'sp4-g23', type: 'Grammar', question: '¿Cómo se dice "hermoso" en femenino?', answer: 'Hermosa', options: ['Hermosa', 'Hermosos', 'Hermosoes'], instruction: 'Género' },
    { id: 'sp4-g24', type: 'Grammar', question: '¿Cómo se dice "hermoso" en plural?', answer: 'Hermosos', options: ['Hermosos', 'Hermosa', 'Hermosas'], instruction: 'Número' },
    { id: 'sp4-g25', type: 'Grammar', question: '¿Cómo se dice "hermosa" en plural?', answer: 'Hermosas', options: ['Hermosas', 'Hermosos', 'Hermosa'], instruction: 'Número' },
  ],
  5: [
    { id: 'sp5-g1', type: 'Grammar', question: '¿Qué es el "predicado"?', answer: 'Lo que se dice del sujeto', options: ['Lo que se dice del sujeto', 'Quien hace la acción', 'El nombre de la persona'], instruction: 'Sintaxis' },
    { id: 'sp5-g2', type: 'Grammar', question: '¿Qué es el "núcleo" del sujeto?', answer: 'El sustantivo o pronombre', options: ['El sustantivo o pronombre', 'El verbo', 'El adjetivo'], instruction: 'Sintaxis' },
    { id: 'sp5-g3', type: 'Grammar', question: '¿Qué es el "núcleo" del predicado?', answer: 'El verbo', options: ['El verbo', 'El sustantivo', 'El adverbio'], instruction: 'Sintaxis' },
    { id: 'sp5-g4', type: 'Grammar', question: '¿Cuál es un adverbio de modo?', answer: 'Bien', options: ['Bien', 'Hoy', 'Aquí'], instruction: 'Adverbios' },
    { id: 'sp5-g5', type: 'Grammar', question: '¿Cuál es un adverbio de tiempo?', answer: 'Mañana', options: ['Mañana', 'Cerca', 'Así'], instruction: 'Adverbios' },
    { id: 'sp5-g6', type: 'Grammar', question: '¿Cuál es un adverbio de lugar?', answer: 'Lejos', options: ['Lejos', 'Jamás', 'Mal'], instruction: 'Adverbios' },
    { id: 'sp5-g7', type: 'Grammar', question: '¿Cuál es un adverbio de cantidad?', answer: 'Mucho', options: ['Mucho', 'Siempre', 'Despacio'], instruction: 'Adverbios' },
    { id: 'sp5-g8', type: 'Grammar', question: '¿Cuál es un adverbio de negación?', answer: 'Nunca', options: ['Nunca', 'Sí', 'También'], instruction: 'Adverbios' },
    { id: 'sp5-g9', type: 'Grammar', question: '¿Cuál es un adverbio de duda?', answer: 'Acaso', options: ['Acaso', 'Claro', 'No'], instruction: 'Adverbios' },
    { id: 'sp5-g10', type: 'Grammar', question: 'Grado de "bueno":', answer: 'Óptimo', options: ['Óptimo', 'Bueno', 'Mejor'], instruction: 'Superlativos' },
    { id: 'sp5-g11', type: 'Grammar', question: 'Grado de "malo":', answer: 'Pésimo', options: ['Pésimo', 'Malo', 'Peor'], instruction: 'Superlativos' },
    { id: 'sp5-g12', type: 'Grammar', question: 'Grado de "grande":', answer: 'Máximo', options: ['Máximo', 'Grande', 'Mayor'], instruction: 'Superlativos' },
    { id: 'sp5-g13', type: 'Grammar', question: 'Grado de "pequeño":', answer: 'Mínimo', options: ['Mínimo', 'Pequeño', 'Menor'], instruction: 'Superlativos' },
    { id: 'sp5-g14', type: 'Grammar', question: '¿Qué es un triptongo?', answer: 'Tres vocales juntas', options: ['Tres vocales juntas', 'Dos vocales juntas', 'Una vocal sola'], instruction: 'Ortografía' },
    { id: 'sp5-g15', type: 'Grammar', question: '¿Qué es un diptongo?', answer: 'Dos vocales juntas', options: ['Dos vocales juntas', 'Tres vocales juntas', 'Consonantes juntas'], instruction: 'Ortografía' },
    { id: 'sp5-g16', type: 'Grammar', question: '¿Las palabras agudas se acentúan si terminan en...?', answer: 'n, s o vocal', options: ['n, s o vocal', 'consonante cualquiera', 'nunca'], instruction: 'Acentuación' },
    { id: 'sp5-g17', type: 'Grammar', question: '¿Las palabras llanas se acentúan si NO terminan en...?', answer: 'n, s o vocal', options: ['n, s o vocal', 'vocal solamente', 'siempre'], instruction: 'Acentuación' },
    { id: 'sp5-g18', type: 'Grammar', question: '¿Las palabras esdrújulas se acentúan...?', answer: 'Siempre', options: ['Siempre', 'A veces', 'Nunca'], instruction: 'Acentuación' },
    { id: 'sp5-g19', type: 'Grammar', question: 'Sinónimo de "sabio":', answer: 'Erudito', options: ['Erudito', 'Ignorante', 'Sencillo'], instruction: 'Léxico' },
    { id: 'sp5-g20', type: 'Grammar', question: 'Sinónimo de "rápido":', answer: 'Veloz', options: ['Veloz', 'Pausado', 'Tranquilo'], instruction: 'Léxico' },
    { id: 'sp5-g21', type: 'Grammar', question: 'Sinónimo de "hermoso":', answer: 'Bello', options: ['Bello', 'Horrible', 'Oscuro'], instruction: 'Léxico' },
    { id: 'sp5-g22', type: 'Grammar', question: 'Antónimo de "ganar":', answer: 'Perder', options: ['Perder', 'Lograr', 'Tener'], instruction: 'Léxico' },
    { id: 'sp5-g23', type: 'Grammar', question: 'Antónimo de "valiente":', answer: 'Cobarde', options: ['Cobarde', 'Fuerte', 'Héroe'], instruction: 'Léxico' },
    { id: 'sp5-g24', type: 'Grammar', question: 'Antónimo de "ruidoso":', answer: 'Silencioso', options: ['Silencioso', 'Fuerte', 'Gritón'], instruction: 'Léxico' },
    { id: 'sp5-g25', type: 'Grammar', question: 'Antónimo de "ancho":', answer: 'Estrecho', options: ['Estrecho', 'Largo', 'Alto'], instruction: 'Léxico' },
  ],
  6: [
    { id: 'sp6-g1', type: 'Grammar', question: '¿Qué es una palabra homónima?', answer: 'Se escribe igual, significa diferente', options: ['Se escribe igual, significa diferente', 'Se escribe diferente, significa igual', 'Solo tiene un significado'], instruction: 'Léxico' },
    { id: 'sp6-g2', type: 'Grammar', question: '¿Qué es una palabra parónima?', answer: 'Se parecen pero son diferentes', options: ['Se parecen pero son diferentes', 'Son idénticas', 'Son opuestas'], instruction: 'Léxico' },
    { id: 'sp6-g3', type: 'Grammar', question: 'Uso de la "b" ante...', answer: 'consonante (r, l)', options: ['consonante (r, l)', 'vocal', 'al final siempre'], instruction: 'Ortografía' },
    { id: 'sp6-g4', type: 'Grammar', question: 'Uso de la "v" después de...', answer: 'n', options: ['n', 'm', 'p'], instruction: 'Ortografía' },
    { id: 'sp6-g5', type: 'Grammar', question: '¿Qué es el "sujeto omitido"?', answer: 'No aparece pero se sobreentiende', options: ['No aparece pero se sobreentiende', 'Es el objeto directo', 'Es el verbo'], instruction: 'Sintaxis' },
    { id: 'sp6-g6', type: 'Grammar', question: '¿Cuál es el pretérito imperfecto de "ser"?', answer: 'Era', options: ['Era', 'Fui', 'Sería'], instruction: 'Verbos' },
    { id: 'sp6-g7', type: 'Grammar', question: '¿Cuál es el pretérito indefinido de "ser"?', answer: 'Fui', options: ['Fui', 'Era', 'Seré'], instruction: 'Verbos' },
    { id: 'sp6-g8', type: 'Grammar', question: '¿Cuál es el futuro de "ser"?', answer: 'Seré', options: ['Seré', 'Soy', 'He sido'], instruction: 'Verbos' },
    { id: 'sp6-g9', type: 'Grammar', question: '¿Qué es un verbo reflexivo?', answer: 'La acción recae sobre el sujeto', options: ['La acción recae sobre el sujeto', 'Es un verbo sin sujeto', 'Es un verbo impersonal'], instruction: 'Verbos' },
    { id: 'sp6-g10', type: 'Grammar', question: 'Ejemplo de verbo reflexivo:', answer: 'Lavarse', options: ['Lavarse', 'Cantar', 'Escribir'], instruction: 'Verbos' },
    { id: 'sp6-g11', type: 'Grammar', question: '¿Qué es el "gerundio"?', answer: 'Acción en progreso (-ando, -iendo)', options: ['Acción en progreso (-ando, -iendo)', 'Acción terminada', 'Futuro'], instruction: 'Verbos' },
    { id: 'sp6-g12', type: 'Grammar', question: '¿Qué es el "participio"?', answer: 'Acción terminada (-ado, -ido)', options: ['Acción terminada (-ado, -ido)', 'Acción en progreso', 'Modo imperativo'], instruction: 'Verbos' },
    { id: 'sp6-g13', type: 'Grammar', question: '¿Cuál es un pronombre demostrativo?', answer: 'Este', options: ['Este', 'Mío', 'Él'], instruction: 'Pronombres' },
    { id: 'sp6-g14', type: 'Grammar', question: '¿Cuál es un pronombre relativo?', answer: 'Que', options: ['Que', 'Nosotros', 'Esos'], instruction: 'Pronombres' },
    { id: 'sp6-g15', type: 'Grammar', question: '¿Cuál es un pronombre indefinido?', answer: 'Alguien', options: ['Alguien', 'Usted', 'Mío'], instruction: 'Pronombres' },
    { id: 'sp6-g16', type: 'Grammar', question: '¿Cuál es un determinante posesivo?', answer: 'Mi', options: ['Mi', 'Mío', 'Me'], instruction: 'Gramática' },
    { id: 'sp6-g17', type: 'Grammar', question: '¿Cuál es un determinante demostrativo?', answer: 'Aquella', options: ['Aquella', 'Él', 'Usted'], instruction: 'Gramática' },
    { id: 'sp6-g18', type: 'Grammar', question: '¿Qué es el "complemento directo"?', answer: 'Recibe la acción del verbo', options: ['Recibe la acción del verbo', 'Es el sujeto', 'Es el adverbio'], instruction: 'Sintaxis' },
    { id: 'sp6-g19', type: 'Grammar', question: '¿Qué prueba se usa para el C.D.?', answer: 'Pasarlo a pasiva o sustituir por lo/la', options: ['Pasarlo a pasiva o sustituir por lo/la', 'Preguntar "¿dónde?"', 'Ver si es un nombre'], instruction: 'Sintaxis' },
    { id: 'sp6-g20', type: 'Grammar', question: '¿Qué es el "complemento indirecto"?', answer: 'Indica el destinatario (le/les)', options: ['Indica el destinatario (le/les)', 'Indica el lugar', 'Indica el tiempo'], instruction: 'Sintaxis' },
    { id: 'sp6-g21', type: 'Grammar', question: '¿Cuál es el imperativo de "tú" para "comer"?', answer: 'Come', options: ['Come', 'Coma', 'Comed'], instruction: 'Modos' },
    { id: 'sp6-g22', type: 'Grammar', question: '¿Cuál es el imperativo de "usted" para "comer"?', answer: 'Coma', options: ['Coma', 'Come', 'Comid'], instruction: 'Modos' },
    { id: 'sp6-g23', type: 'Grammar', question: '¿Cuál es el imperativo de "vosotros" para "comer"?', answer: 'Comed', options: ['Comed', 'Coman', 'Comen'], instruction: 'Modos' },
    { id: 'sp6-g24', type: 'Grammar', question: '¿Las preposiciones son palabras invariables?', answer: 'Sí', options: ['Sí', 'No'], instruction: 'Clases de palabras' },
    { id: 'sp6-g25', type: 'Grammar', question: '¿Los adverbios son palabras invariables?', answer: 'Sí', options: ['Sí', 'No'], instruction: 'Clases de palabras' },
  ],
  7: [
    { id: 'sp7-g1', type: 'Grammar', question: '¿Qué es una oración compuesta?', answer: 'Tiene más de un verbo', options: ['Tiene más de un verbo', 'Es muy larga', 'Tiene muchos adjetivos'], instruction: 'Sintaxis' },
    { id: 'sp7-g2', type: 'Grammar', question: '¿Qué es la coordinación?', answer: 'Oraciones independientes unidas', options: ['Oraciones independientes unidas', 'Una depende de otra', 'No tienen verbo'], instruction: 'Sintaxis' },
    { id: 'sp7-g3', type: 'Grammar', question: '¿Qué es la subordinación?', answer: 'Una oración depende de otra', options: ['Una depende de otra', 'Son independientes', 'Están separadas por punto'], instruction: 'Sintaxis' },
    { id: 'sp7-g4', type: 'Grammar', question: '¿Qué es una oración nominal?', answer: 'No tiene verbo explícito', options: ['No tiene verbo explícito', 'Solo tiene sustantivos', 'Es muy corta'], instruction: 'Sintaxis' },
    { id: 'sp7-g5', type: 'Grammar', question: 'Uso de "por qué" (separado y con tilde):', answer: 'Interrogación o exclamación', options: ['Interrogación o exclamación', 'Respuesta', 'Sustantivo'], instruction: 'Ortografía' },
    { id: 'sp7-g6', type: 'Grammar', question: 'Uso de "porque" (junto y sin tilde):', answer: 'Causa o respuesta', options: ['Causa o respuesta', 'Pregunta', 'Sentido de motivo'], instruction: 'Ortografía' },
    { id: 'sp7-g7', type: 'Grammar', question: 'Uso de "porqué" (junto y con tilde):', answer: 'Sustantivo (el motivo)', options: ['Sustantivo (el motivo)', 'Respuesta', 'Pregunta'], instruction: 'Ortografía' },
    { id: 'sp7-g8', type: 'Grammar', question: 'Uso de "por que" (separado y sin tilde):', answer: 'Relativo (por el cual)', options: ['Relativo (por el cual)', 'Pregunta', 'Causa'], instruction: 'Ortografía' },
    { id: 'sp7-g9', type: 'Grammar', question: '¿Qué es el "vulgarismo"?', answer: 'Error de uso en el habla', options: ['Error de uso en el habla', 'Palabra antigua', 'Palabra técnica'], instruction: 'Lenguaje' },
    { id: 'sp7-g10', type: 'Grammar', question: '¿Qué es el "neologismo"?', answer: 'Palabra nueva en el idioma', options: ['Palabra nueva en el idioma', 'Palabra que ya no se usa', 'Sinónimo raro'], instruction: 'Lenguaje' },
    { id: 'sp7-g11', type: 'Grammar', question: '¿Qué es el "arcaísmo"?', answer: 'Palabra antigua o en desuso', options: ['Palabra antigua o en desuso', 'Palabra de otro idioma', 'Insulto'], instruction: 'Lenguaje' },
    { id: 'sp7-g12', type: 'Grammar', question: '¿Cuál es el modo subjuntivo?', answer: 'Expresa deseo, duda o hipótesis', options: ['Expresa deseo, duda o hipótesis', 'Expresa hechos reales', 'Expresa órdenes'], instruction: 'Verbos' },
    { id: 'sp7-g13', type: 'Grammar', question: 'Ejemplo de presente de subjuntivo (él):', answer: 'Coma', options: ['Coma', 'Come', 'Comió'], instruction: 'Verbos' },
    { id: 'sp7-g14', type: 'Grammar', question: '¿Qué es una locución prepositiva?', answer: 'Grupo de palabras que funciona como preposición', options: ['Grupo de palabras que funciona como preposición', 'Un adverbio largo', 'Un verbo compuesto'], instruction: 'Gramática' },
    { id: 'sp7-g15', type: 'Grammar', question: 'Ejemplo de locución prepositiva:', answer: 'Encima de', options: ['Encima de', 'Para', 'Muy'], instruction: 'Gramática' },
    { id: 'sp7-g16', type: 'Grammar', question: '¿Qué es una locución adverbial?', answer: 'Grupo de palabras que funciona como adverbio', options: ['Grupo de palabras que funciona como adverbio', 'Un adjetivo calificativo', 'Un pronombre'], instruction: 'Gramática' },
    { id: 'sp7-g17', type: 'Grammar', question: 'Ejemplo de locución adverbial:', answer: 'De repente', options: ['De repente', 'Aquí', 'Veloz'], instruction: 'Gramática' },
    { id: 'sp7-g18', type: 'Grammar', question: '¿Qué es un campo semántico?', answer: 'Palabras relacionadas por significado', options: ['Palabras relacionadas por significado', 'Palabras que riman', 'Palabras de la misma familia'], instruction: 'Léxico' },
    { id: 'sp7-g19', type: 'Grammar', question: 'Ejemplo de campo semántico "muebles":', answer: 'Silla, mesa, sofá', options: ['Silla, mesa, sofá', 'Azul, rojo, verde', 'Correr, saltar, ir'], instruction: 'Léxico' },
    { id: 'sp7-g20', type: 'Grammar', question: '¿Qué es una familia léxica?', answer: 'Palabras con la misma raíz', options: ['Palabras con la misma raíz', 'Palabras con el mismo sentido', 'Palabras de un juego'], instruction: 'Léxico' },
    { id: 'sp7-g21', type: 'Grammar', question: 'Ejemplo de familia léxica de "pan":', answer: 'Panadero, panadería, panecillo', options: ['Panadero, panadería, panecillo', 'Trigo, harina, horno', 'Comer, alimento, cena'], instruction: 'Léxico' },
    { id: 'sp7-g22', type: 'Grammar', question: 'Uso de "haya" (verbo haber):', answer: 'Espero que haya pan', options: ['Espero que haya pan', 'Busca en la guía', 'La haya es un árbol'], instruction: 'Ortografía' },
    { id: 'sp7-g23', type: 'Grammar', question: 'Uso de "halla" (verbo hallar/encontrar):', answer: 'Él halla la solución', options: ['Él halla la solución', 'Espero que halla pan', 'Vive en la calle'], instruction: 'Ortografía' },
    { id: 'sp7-g24', type: 'Grammar', question: 'Uso de "aya" (cuidadora):', answer: 'La aya cuida al niño', options: ['La aya cuida al niño', 'No aya problemas', 'Aya tú'], instruction: 'Ortografía' },
    { id: 'sp7-g25', type: 'Grammar', question: 'Uso de "ahí" (lugar):', answer: 'Ponlo ahí', options: ['Ponlo ahí', '¡Ay! me duele', 'No hay nada'], instruction: 'Ortografía' },
  ],
  8: [
    { id: 'sp8-g1', type: 'Grammar', question: '¿Qué es la denotación?', answer: 'Significado literal y objetivo', options: ['Significado literal y objetivo', 'Significado figurado y subjetivo', 'El origen de la palabra'], instruction: 'Semántica' },
    { id: 'sp8-g2', type: 'Grammar', question: '¿Qué es la connotación?', answer: 'Significado figurado y sugerido', options: ['Significado figurado y sugerido', 'Significado de diccionario', 'La pronunciación'], instruction: 'Semántica' },
    { id: 'sp8-g3', type: 'Grammar', question: '¿Qué es el "idíoma"?', answer: 'Sistema de signos compartido', options: ['Sistema de signos compartido', 'Habla individual', 'Variante regional'], instruction: 'Lingüística' },
    { id: 'sp8-g4', type: 'Grammar', question: '¿Qué es el "habla"?', answer: 'Uso individual de la lengua', options: ['Uso individual de la lengua', 'Gramática oficial', 'Diccionario'], instruction: 'Lingüística' },
    { id: 'sp8-g5', type: 'Grammar', question: '¿Qué es un dialecto?', answer: 'Variante regional de una lengua', options: ['Variante regional de una lengua', 'Un idioma diferente', 'Una forma de escribir'], instruction: 'Lingüística' },
    { id: 'sp8-g6', type: 'Grammar', question: '¿Qué es la "jerga"?', answer: 'Lenguaje de un grupo específico', options: ['Lenguaje de un grupo específico', 'Idioma de otro país', 'Lenguaje formal'], instruction: 'Lingüística' },
    { id: 'sp8-g7', type: 'Grammar', question: '¿Qué es el registro formal?', answer: 'Uso cuidado y preciso del idioma', options: ['Uso cuidado y preciso del idioma', 'Uso con amigos y familia', 'Lenguaje con insultos'], instruction: 'Sociolingüística' },
    { id: 'sp8-g8', type: 'Grammar', question: '¿Qué es el registro informal?', answer: 'Uso cotidiano y relajado', options: ['Uso cotidiano y relajado', 'Uso en una tesis doctoral', 'Uso en leyes'], instruction: 'Sociolingüística' },
    { id: 'sp8-g9', type: 'Grammar', question: '¿Cuál es el valor semántico de un prefijo negativo?', answer: 'Oposición o privación', options: ['Oposición o privación', 'Dirección', 'Tiempo'], instruction: 'Morfología' },
    { id: 'sp8-g10', type: 'Grammar', question: 'Ejemplo de prefijo negativo:', answer: 'In-mortal', options: ['In-mortal', 'Sub-terráneo', 'Pre-decir'], instruction: 'Morfología' },
    { id: 'sp8-g11', type: 'Grammar', question: '¿Qué es una oración impersonal?', answer: 'No tiene sujeto (ni omitido)', options: ['No tiene sujeto (ni omitido)', 'Es una oración muy larga', 'Es una oración con pronombre'], instruction: 'Sintaxis' },
    { id: 'sp8-g12', type: 'Grammar', question: 'Ejemplo de oración impersonal:', answer: 'Nieva mucho', options: ['Nieva mucho', 'Él nieva', 'Nosotros nevamos'], instruction: 'Sintaxis' },
    { id: 'sp8-g13', type: 'Grammar', question: '¿Qué es la perífrasis verbal?', answer: 'Combinación de dos o más verbos', options: ['Combinación de dos o más verbos', 'Un verbo con muchos adornos', 'Un adverbio'], instruction: 'Verbos' },
    { id: 'sp8-g14', type: 'Grammar', question: 'Ejemplo de perífrasis verbal:', answer: 'Tengo que estudiar', options: ['Tengo que estudiar', 'Estudio', 'Estudiaba'], instruction: 'Verbos' },
    { id: 'sp8-g15', type: 'Grammar', question: '¿Qué es la voz pasiva?', answer: 'El sujeto recibe la acción', options: ['El sujeto recibe la acción', 'El sujeto realiza la acción', 'No hay sujeto'], instruction: 'Sintaxis' },
    { id: 'sp8-g16', type: 'Grammar', question: '¿Cómo se forma la pasiva propia?', answer: 'Ser + participio', options: ['Ser + participio', 'Haber + participio', 'Estar + gerundio'], instruction: 'Sintaxis' },
    { id: 'sp8-g17', type: 'Grammar', question: '¿Qué es la cohesión textual?', answer: 'Unión lógica de las partes del texto', options: ['Unión lógica de las partes del texto', 'La longitud del texto', 'El color del papel'], instruction: 'Texto' },
    { id: 'sp8-g18', type: 'Grammar', question: '¿Qué es la coherencia textual?', answer: 'Sentido global del texto', options: ['Sentido global del texto', 'Uso de puntos y comas', 'Correcta ortografía'], instruction: 'Texto' },
    { id: 'sp8-g19', type: 'Grammar', question: '¿Cuál es un conector de oposición?', answer: 'Sin embargo', options: ['Sin embargo', 'Además', 'Primero'], instruction: 'Marcadores textuales' },
    { id: 'sp8-g20', type: 'Grammar', question: '¿Cuál es un conector de adición?', answer: 'Asimismo', options: ['Asimismo', 'Pero', 'En conclusión'], instruction: 'Marcadores textuales' },
    { id: 'sp8-g21', type: 'Grammar', question: '¿Cuál es un conector consecutivo?', answer: 'Por lo tanto', options: ['Por lo tanto', 'Quizás', 'Antes'], instruction: 'Marcadores textuales' },
    { id: 'sp8-g22', type: 'Grammar', question: '¿Qué es un calco semántico?', answer: 'Traducción literal de otro idioma', options: ['Traducción literal de otro idioma', 'Una rima perfecta', 'Una falta de ortografía'], instruction: 'Lenguaje' },
    { id: 'sp8-g23', type: 'Grammar', question: '¿Qué es el "eufemismo"?', answer: 'Palabra suave para algo tabú o desagradable', options: ['Palabra suave para algo tabú o desagradable', 'Palabra que suena mal', 'Palabra extranjera'], instruction: 'Semántica' },
    { id: 'sp8-g24', type: 'Grammar', question: 'Antónimo de eufemismo:', answer: 'Disfemismo', options: ['Disfemismo', 'Sinónimo', 'Metáfora'], instruction: 'Semántica' },
    { id: 'sp8-g25', type: 'Grammar', question: '¿Qué es la polisemia?', answer: 'Una palabra con varios significados', options: ['Una palabra con varios significados', 'Varias palabras con un significado', 'Palabras que no significan nada'], instruction: 'Semántica' },
  ],
  9: [
    { id: 'sp9-g1', type: 'Grammar', question: '¿Qué es el "análisis morfosintáctico"?', answer: 'Estudio de forma y función', options: ['Estudio de forma y función', 'Estudio del origen histórico', 'Estudio de los sonidos'], instruction: 'Gramática' },
    { id: 'sp9-g2', type: 'Grammar', question: '¿Qué es la "deíxis"?', answer: 'Señalamiento que depende del contexto', options: ['Señalamiento que depende del contexto', 'Una falta de concordancia', 'Un tipo de rima'], instruction: 'Pragmática' },
    { id: 'sp9-g3', type: 'Grammar', question: 'Ejemplo de deíxis:', answer: 'Mañana allá', options: ['Mañana allá', 'Casa roja', 'Comer pan'], instruction: 'Pragmática' },
    { id: 'sp9-g4', type: 'Grammar', question: '¿Qué es la "elipsis"?', answer: 'Omisión de elementos obvios', options: ['Omisión de elementos obvios', 'Repetición de palabras', 'Cambio de orden'], instruction: 'Recursos textuales' },
    { id: 'sp9-g5', type: 'Grammar', question: '¿Qué es la "anáfora"?', answer: 'Referirse a algo ya mencionado', options: ['Referirse a algo ya mencionado', 'Referirse a algo nuevo', 'No referirse a nada'], instruction: 'Cohesión' },
    { id: 'sp9-g6', type: 'Grammar', question: '¿Qué es la "catáfora"?', answer: 'Anticipar algo que se mencionará después', options: ['Anticipar algo que se mencionará después', 'Repetir lo anterior', 'Omitir el verbo'], instruction: 'Cohesión' },
    { id: 'sp9-g7', type: 'Grammar', question: '¿Qué es el "predicado nominal"?', answer: 'Verbo copulativo (ser, estar, parecer)', options: ['Verbo copulativo (ser, estar, parecer)', 'Verbo de acción', 'Frase sin verbo'], instruction: 'Sintaxis' },
    { id: 'sp9-g8', type: 'Grammar', question: '¿Qué es el "atributo"?', answer: 'Complemento del predicado nominal', options: ['Complemento del predicado nominal', 'El sujeto de la oración', 'El objeto directo'], instruction: 'Sintaxis' },
    { id: 'sp9-g9', type: 'Grammar', question: '¿Qué es el "predicado verbal"?', answer: 'Verbo predicativo (acción)', options: ['Verbo predicativo (acción)', 'Verbo ser o estar', 'Verbo auxiliar solamente'], instruction: 'Sintaxis' },
    { id: 'sp9-g10', type: 'Grammar', question: '¿Qué es el "complemento de régimen"?', answer: 'Preposición exigida por el verbo', options: ['Preposición exigida por el verbo', 'Acompaña al sustantivo', 'Indica el modo'], instruction: 'Sintaxis' },
    { id: 'sp9-g11', type: 'Grammar', question: 'Ejemplo de C. de Régimen:', answer: 'Confiar en...', options: ['Confiar en...', 'Comer pan', 'Ir rápido'], instruction: 'Sintaxis' },
    { id: 'sp9-g12', type: 'Grammar', question: '¿Qué es el "complemento predicativo"?', answer: 'Adjetivo que modifica a verbo y a nombre', options: ['Adjetivo que modifica a verbo y a nombre', 'Un adverbio común', 'Un pronombre'], instruction: 'Sintaxis' },
    { id: 'sp9-g13', type: 'Grammar', question: '¿Qué es una proposición adjetiva (o de relativo)?', answer: 'Funciona como un adjetivo', options: ['Funciona como un adjetivo', 'Funciona como un sustantivo', 'Funciona como un adverbio'], instruction: 'Sintaxis' },
    { id: 'sp9-g14', type: 'Grammar', question: '¿Qué es una proposición sustantiva?', answer: 'Funciona como un sustantivo', options: ['Funciona como un sustantivo', 'Indica el lugar', 'Modifica al verbo'], instruction: 'Sintaxis' },
    { id: 'sp9-g15', type: 'Grammar', question: '¿Qué es una proposición adverbial?', answer: 'Funciona como un adverbio', options: ['Funciona como un adverbio', 'Es el sujeto', 'Es el nombre propio'], instruction: 'Sintaxis' },
    { id: 'sp9-g16', type: 'Grammar', question: '¿Qué es la modalidad oracional?', answer: 'Actitud del hablante (enunciativa, duda...)', options: ['Actitud del hablante (enunciativa, duda...)', 'El tiempo del verbo', 'El número de palabras'], instruction: 'Gramática' },
    { id: 'sp9-g17', type: 'Grammar', question: '¿Cuál es la función apelativa?', answer: 'Influir en el receptor', options: ['Influir en el receptor', 'Expresar sentimientos', 'Dar información pura'], instruction: 'Funciones del lenguaje' },
    { id: 'sp9-g18', type: 'Grammar', question: '¿Cuál es la función expresiva?', answer: 'Manifestar sentimientos', options: ['Manifestar sentimientos', 'Pedir algo', 'Hablar del idioma'], instruction: 'Funciones del lenguaje' },
    { id: 'sp9-g19', type: 'Grammar', question: '¿Cuál es la función fática?', answer: 'Verificar el canal de comunicación', options: ['Verificar el canal de comunicación', 'Crear belleza', 'Informar hechos'], instruction: 'Funciones del lenguaje' },
    { id: 'sp9-g20', type: 'Grammar', question: '¿Cuál es la función poética?', answer: 'Centrarse en el mensaje y su estética', options: ['Centrarse en el mensaje y su estética', 'Preguntar algo', 'Hablar por teléfono'], instruction: 'Funciones del lenguaje' },
    { id: 'sp9-g21', type: 'Grammar', question: '¿Cuál es la función metalingüística?', answer: 'Hablar sobre el propio lenguaje', options: ['Hablar sobre el propio lenguaje', 'Mentir', 'Gritar mucho'], instruction: 'Funciones del lenguaje' },
    { id: 'sp9-g22', type: 'Grammar', question: '¿Qué es la etimología?', answer: 'Estudio del origen de las palabras', options: ['Estudio del origen de las palabras', 'Estudio de la escritura correcta', 'Estudio de los diccionarios'], instruction: 'Lingüística' },
    { id: 'sp9-g23', type: 'Grammar', question: '¿De dónde proviene la mayoría de palabras españolas?', answer: 'Del Latín', options: ['Del Latín', 'Del Inglés', 'Del Chino'], instruction: 'Historia' },
    { id: 'sp9-g24', type: 'Grammar', question: '¿Qué es el "seseo"?', answer: 'Pronunciar "c" y "z" como "s"', options: ['Pronunciar "c" y "z" como "s"', 'Repetir la letra "S" mucho', 'Hablar muy bajito'], instruction: 'Fonética' },
    { id: 'sp9-g25', type: 'Grammar', question: '¿Qué es el "yeísmo"?', answer: 'Pronunciar "ll" como "y"', options: ['Pronunciar "ll" como "y"', 'Decir "sí" many veces', 'Escribir con many "Y"'], instruction: 'Fonética' },
  ],
  10: [
    { id: 'sp10-g1', type: 'Grammar', question: '¿Qué es la "yuxtaposición"?', answer: 'Unir oraciones por signos de puntuación', options: ['Unir oraciones por signos de puntuación', 'Unir oraciones por nexos', 'Son oraciones simples'], instruction: 'Sintaxis' },
    { id: 'sp10-g2', type: 'Grammar', question: '¿Qué es una proposición causal?', answer: 'Indica el motivo o causa', options: ['Indica el motivo o causa', 'Indica el tiempo', 'Indica el lugar'], instruction: 'Sintaxis' },
    { id: 'sp10-g3', type: 'Grammar', question: '¿Qué es una proposición concesiva?', answer: 'Indica un obstáculo que no impide la acción', options: ['Indica un obstáculo que no impide la acción', 'Indica una condición', 'Indica una consecuencia'], instruction: 'Sintaxis' },
    { id: 'sp10-g4', type: 'Grammar', question: '¿Cuál es un nexo posesivo?', answer: 'Cuyo/Cuyos', options: ['Cuyo/Cuyos', 'Cual', 'Donde'], instruction: 'Relativos' },
    { id: 'sp10-g5', type: 'Grammar', question: '¿Qué es el "leísmo"?', answer: 'Uso de "le" como objeto directo', options: ['Uso de "le" como objeto directo', 'Uso de "la" como objeto directo', 'Uso de "lo" como objeto directo'], instruction: 'Gramática' },
    { id: 'sp10-g6', type: 'Grammar', question: '¿Qué significa "impertérrito"?', answer: 'Que no se asusta ni se altera', options: ['Que no se asusta ni se altera', 'Que está muy asustado', 'Que es muy pequeño'], instruction: 'Léxico' },
    { id: 'sp10-g7', type: 'Grammar', question: '¿Qué significa "efímero"?', answer: 'Que dura poco tiempo', options: ['Que dura poco tiempo', 'Que es eterno', 'Que es muy brillante'], instruction: 'Léxico' },
    { id: 'sp10-g8', type: 'Grammar', question: '¿Qué significa "obsoleto"?', answer: 'Anticuado / Fuera de uso', options: ['Anticuado / Fuera de uso', 'Nuevo', 'Útil'], instruction: 'Léxico' },
    { id: 'sp10-g9', type: 'Grammar', question: '¿Qué es una oración exhortativa?', answer: 'Expresa ruego o mandato', options: ['Expresa ruego o mandato', 'Expresa duda', 'Expresa alegría'], instruction: 'Modalidad' },
    { id: 'sp10-g10', type: 'Grammar', question: '¿Qué es una oración desiderativa?', answer: 'Expresa deseo', options: ['Expresa deseo', 'Expresa temor', 'Expresa mandato'], instruction: 'Modalidad' },
    { id: 'sp10-g11', type: 'Grammar', question: '¿Qué es una oración dubitativa?', answer: 'Expresa duda', options: ['Expresa duda', 'Expresa certeza', 'Expresa informativ'], instruction: 'Modalidad' },
    { id: 'sp10-g12', type: 'Grammar', question: '¿Qué es el "sujeto paciente"?', answer: 'Sujeto en la voz pasiva', options: ['Sujeto en la voz pasiva', 'Sujeto que no hace nada', 'Sujeto omitido'], instruction: 'Sintaxis' },
    { id: 'sp10-g13', type: 'Grammar', question: '¿Qué es un "anglicismo"?', answer: 'Palabra tomada del inglés', options: ['Palabra tomada del inglés', 'Palabra tomada del latín', 'Palabra inventada'], instruction: 'Léxico' },
    { id: 'sp10-g14', type: 'Grammar', question: '¿Qué es un "galicismo"?', answer: 'Palabra tomada del francés', options: ['Palabra tomada del francés', 'Palabra tomada del alemán', 'Palabra tomada del italiano'], instruction: 'Léxico' },
    { id: 'sp10-g15', type: 'Grammar', question: '¿Qué es un "arabismo"?', answer: 'Palabra tomada del árabe', options: ['Palabra tomada del árabe', 'Palabra tomada del griego', 'Palabra tomada del ruso'], instruction: 'Léxico' },
    { id: 'sp10-g16', type: 'Grammar', question: '¿Qué tiempo es: "Si yo fuera rico..."?', answer: 'Pretérito imperfecto de subjuntivo', options: ['Pretérito imperfecto de subjuntivo', 'Futuro', 'Presente'], instruction: 'Verbos' },
    { id: 'sp10-g17', type: 'Grammar', question: '¿Qué tiempo es: "Habría comido"?', answer: 'Condicional compuesto', options: ['Condicional compuesto', 'Futuro perfecto', 'Pretérito anterior'], instruction: 'Verbos' },
    { id: 'sp10-g18', type: 'Grammar', question: '¿Qué tiempo es: "Hubiera comido"?', answer: 'Pretérito pluscuamperfecto de subjuntivo', options: ['Pretérito pluscuamperfecto de subjuntivo', 'Condicional', 'Presente'], instruction: 'Verbos' },
    { id: 'sp10-g19', type: 'Grammar', question: '¿Qué es la "metáfora"?', answer: 'Identificación de un término real con uno imaginario', options: ['Identificación de un término real con uno imaginario', 'Exageración de la realidad', 'Repetición de sonidos'], instruction: 'Retórica' },
    { id: 'sp10-g20', type: 'Grammar', question: '¿Qué es el "hipérbaton"?', answer: 'Alteración del orden lógico de las palabras', options: ['Alteración del orden lógico de las palabras', 'Comparación usando "como"', 'Dar cualidades humanas a objetos'], instruction: 'Retórica' },
    { id: 'sp10-g21', type: 'Grammar', question: '¿Qué es la "personificación"?', answer: 'Dar cualidades humanas a seres inanimados', options: ['Dar cualidades humanas a seres inanimados', 'Exagerar mucho', 'Repetir una palabra al inicio'], instruction: 'Retórica' },
    { id: 'sp10-g22', type: 'Grammar', question: '¿Qué es la "aliteración"?', answer: 'Repetición de sonidos similares', options: ['Repetición de sonidos similares', 'Uso de palabras opuestas', 'Pregunta que no espera respuesta'], instruction: 'Retórica' },
    { id: 'sp10-g23', type: 'Grammar', question: '¿Qué es la "ironía"?', answer: 'Decir lo contrario de lo que se piensa (con humor)', options: ['Decir lo contrario de lo que se piensa (con humor)', 'Gritar mucho', 'Hablar en verso'], instruction: 'Retórica' },
    { id: 'sp10-g24', type: 'Grammar', question: '¿Qué es la "sinestesia"?', answer: 'Mezcla de sensaciones de sentidos distintos', options: ['Mezcla de sensaciones de sentidos distintos', 'Un tipo de enfermedad', 'Escribir sin verbos'], instruction: 'Retórica' },
    { id: 'sp10-g25', type: 'Grammar', question: '¿Qué es un "solecismo"?', answer: 'Error en la structure de la oración', options: ['Error en la structure de la oración', 'Error de ortografía', 'Error de pronunciación'], instruction: 'Gramática' },
    { id: 'sp10-g26', type: 'Grammar', question: '¿Qué es la "ambigüedad"?', answer: 'Que tiene más de un sentido posible', options: ['Que tiene más de un sentido posible', 'Que es muy claro', 'Que es mentira'], instruction: 'Semántica' },
    { id: 'sp10-g27', type: 'Grammar', question: '¿Qué es una palabra "compuesta"?', answer: 'Formada por dos o más raíces', options: ['Formada por dos o más raíces', 'Que tiene muchos prefijos', 'Que no tiene sufijos'], instruction: 'Morfología' },
    { id: 'sp10-g28', type: 'Grammar', question: '¿Qué es una palabra "parasintética"?', answer: 'Usa prefijación y sufijación simultáneas', options: ['Usa prefijación og sufijación simultáneas', 'Es una palabra muy larga', 'Es un sinónimo'], instruction: 'Morfología' },
    { id: 'sp10-g29', type: 'Grammar', question: '¿Qué es "RAE"?', answer: 'Real Academia Española', options: ['Real Academia Española', 'Red de Ayuda Escolar', 'Radio Alerta España'], instruction: 'Cultura' },
    { id: 'sp10-g30', type: 'Grammar', question: '¡Lo has ___!', answer: 'logrado', options: ['logrado', 'perdido', 'intentado'], instruction: '¡Felicidades!' },
  ],
};
