/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const TYSK_GRAMMAR_P3: Partial<Record<Grade, GameContent[]>> = {
  8: [
    { id: 'de8-g1', type: 'Grammar', question: 'Hvad betyder "Konjunktiv II"?', answer: 'Ønskeform / Høflighed', options: ['Ønskeform / Høflighed', 'Fortid', 'Navneform'], instruction: 'Konjunktiv' },
    { id: 'de8-g2', type: 'Grammar', question: 'Hvordan siger man "Jeg ville gerne have"?', answer: 'Ich hätte gern', options: ['Ich hätte gern', 'Ich habe gern', 'Ich hatte gern'], instruction: 'Konjunktiv II' },
    { id: 'de8-g3', type: 'Grammar', question: 'Hvordan siger man "Jeg ville gerne være"?', answer: 'Ich wäre gern', options: ['Ich wäre gern', 'Ich bin gern', 'Ich war gern'], instruction: 'Konjunktiv II' },
    { id: 'de8-g4', type: 'Grammar', question: 'Hvad betyder "Würden" + infinitiv?', answer: 'Ville (gøre noget)', options: ['Ville (gøre noget)', 'Skulle', 'Kunne'], instruction: 'Konjunktiv II' },
    { id: 'de8-g5', type: 'Grammar', question: 'Oversæt: "Jeg ville rejse" (voyager).', answer: 'Ich würde reisen', options: ['Ich würde reisen', 'Ich reise', 'Ich reiste'], instruction: 'Konjunktiv II' },
    { id: 'de8-g6', type: 'Grammar', question: 'Hvilket ord betyder "Hvis (hypotetisk)"?', answer: 'Wenn', options: ['Wenn', 'Als', 'Ob'], instruction: 'Konjunktionen' },
    { id: 'de8-g7', type: 'Grammar', question: 'Hvornår bruges "Man" (one) på tysk?', answer: 'Ved generelle udsagn', options: ['Ved generelle udsagn', 'Ved mænd', 'Ved kvinder'], instruction: 'Pronomen' },
    { id: 'de8-g8', type: 'Grammar', question: 'Hvilken kasus styrer præpositionen "Seit"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ', 'Nominativ'], instruction: 'Dativ' },
    { id: 'de8-g9', type: 'Grammar', question: 'Oversæt: "Siden et år" (Jahr - das).', answer: 'Seit einem Jahr', options: ['Seit einem Jahr', 'Seit ein Jahr', 'Seit eines Jahres'], instruction: 'Dativ' },
    { id: 'de8-g10', type: 'Grammar', question: 'Hvilken kasus styrer præpositionen "Mit"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ'], instruction: 'Dativ' },
    { id: 'de8-g11', type: 'Grammar', question: 'Oversæt: "Med toget" (Zug - der).', answer: 'Mit dem Zug', options: ['Mit dem Zug', 'Mit den Zug', 'Mit der Zug'], instruction: 'Dativ' },
    { id: 'de8-g12', type: 'Grammar', question: 'Hvilken kasus styrer præpositionen "Nach"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ'], instruction: 'Dativ' },
    { id: 'de8-g13', type: 'Grammar', question: 'Hvilken kasus styrer præpositionen "Zu"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ'], instruction: 'Dativ' },
    { id: 'de8-g14', type: 'Grammar', question: 'Oversæt: "Til skole" (Schule - die).', answer: 'Zur Schule (Zu der)', options: ['Zur Schule (Zu der)', 'Zu die Schule', 'Zum Schule'], instruction: 'Kontraktion' },
    { id: 'de8-g15', type: 'Grammar', question: 'Hvad betyder "Zum" en sammentrækning af?', answer: 'Zu + dem', options: ['Zu + dem', 'Zu + den', 'Zu + der'], instruction: 'Kontraktion' },
    { id: 'de8-g16', type: 'Grammar', question: 'Hvad betyder "Im" en sammentrækning af?', answer: 'In + dem', options: ['In + dem', 'In + den', 'In + das'], instruction: 'Kontraktion' },
    { id: 'de8-g17', type: 'Grammar', question: 'Hvad betyder "Ans" en sammentrækning af?', answer: 'An + das', options: ['An + das', 'An + dem', 'An + den'], instruction: 'Kontraktion' },
    { id: 'de8-g18', type: 'Grammar', question: 'Relativ: "Huset, ___ jeg bor i" (wo / das).', answer: 'in dem / in welchem', options: ['in dem / in welchem', 'wo', 'das'], instruction: 'Relativsatz' },
    { id: 'de8-g19', type: 'Grammar', question: 'Relativ: "Manden, ___ jeg kender" (der / den).', answer: 'den', options: ['den', 'der', 'dem'], instruction: 'Relativsatz' },
    { id: 'de8-g20', type: 'Grammar', question: 'Relativ: "Kvinden, ___ her bor" (die / der).', answer: 'die', options: ['die', 'der', 'den'], instruction: 'Relativsatz' },
    { id: 'de8-g21', type: 'Grammar', question: 'Hvad betyder "Passiv" på tysk?', answer: 'Handlingen bliver udført', options: ['Handlingen bliver udført', 'Handlingen er i fremtid', 'Handlingen er i fortid'], instruction: 'Passiv' },
    { id: 'de8-g22', type: 'Grammar', question: 'Hvordan dannes Passiv?', answer: 'Werden + participium', options: ['Werden + participium', 'Sein + participium', 'Haben + participium'], instruction: 'Passiv' },
    { id: 'de8-g23', type: 'Grammar', question: 'Oversæt: "Bilen bliver vasket" (waschen).', answer: 'Das Auto wird gewaschen', options: ['Das Auto wird gewaschen', 'Das Auto ist gewaschen', 'Das Auto hat gewaschen'], instruction: 'Passiv' },
    { id: 'de8-g24', type: 'Grammar', question: 'Hvad betyder "Wurde"?', answer: 'Blev (passiv datid)', options: ['Blev (passiv datid)', 'Vil blive', 'Er blevet'], instruction: 'Passiv' },
    { id: 'de8-g25', type: 'Grammar', question: 'Oversæt: "Bilen blev vasket".', answer: 'Das Auto wurde gewaschen', options: ['Das Auto wurde gewaschen', 'Das Auto wird gewaschen', 'Das Auto ist gewaschen'], instruction: 'Passiv' },
    { id: 'de8-g26', type: 'Grammar', question: 'Hvad betyder "Zukunft"?', answer: 'Fremtid', options: ['Fremtid', 'Fortid', 'Nutid'], instruction: 'Vokabeln' },
    { id: 'de8-g27', type: 'Grammar', question: 'Hvad betyder "Vergangenheit"?', answer: 'Fortid', options: ['Fortid', 'Fremtid', 'Nutid'], instruction: 'Vokabeln' },
    { id: 'de8-g28', type: 'Grammar', question: 'Hvad betyder "Gegenwart"?', answer: 'Nutid', options: ['Nutid', 'Fortid', 'Fremtid'], instruction: 'Vokabeln' },
    { id: 'de8-g29', type: 'Grammar', question: 'Hvordan bøjes "Wissen" ved "Ihr"?', answer: 'wisst', options: ['wisst', 'wissest', 'wissen'], instruction: 'Wissen' },
    { id: 'de8-g30', type: 'Grammar', question: 'Hvad betyder "Bescheid wissen"?', answer: 'At vide besked', options: ['At vide besked', 'At spørge', 'At glemme'], instruction: 'Ausdruck' },
    { id: 'de8-g31', type: 'Grammar', question: 'Hvad betyder "Unterstützung"?', answer: 'Understøttelse / Støtte', options: ['Understøttelse / Støtte', 'Modstand', 'Hjælp'], instruction: 'Vokabeln' },
    { id: 'de8-g32', type: 'Grammar', question: 'Hvad betyder "Entweder ... oder"?', answer: 'Enten ... eller', options: ['Enten ... eller', 'Hverken ... eller', 'Både ... og'], instruction: 'Doppelkonjunktion' },
    { id: 'de8-g33', type: 'Grammar', question: 'Hvad betyder "Weder ... noch"?', answer: 'Hverken ... eller', options: ['Hverken ... eller', 'Enten ... eller', 'Både ... og'], instruction: 'Doppelkonjunktion' },
    { id: 'de8-g34', type: 'Grammar', question: 'Hvad betyder "Sowohl ... als auch"?', answer: 'Både ... og', options: ['Både ... og', 'Hverken ... eller', 'Men også'], instruction: 'Doppelkonjunktion' },
    { id: 'de8-g35', type: 'Grammar', question: 'Hvad betyder "Nicht nur ... sondern auch"?', answer: 'Ikke kun ... men også', options: ['Ikke kun ... men også', 'Enten ... eller', 'Hverken ... eller'], instruction: 'Doppelkonjunktion' },
    { id: 'de8-g36', type: 'Grammar', question: 'Hvad betyder "Teils ... teils"?', answer: 'Dels ... dels', options: ['Dels ... dels', 'Halvt ... halvt', 'Hverken ... eller'], instruction: 'Doppelkonjunktion' },
    { id: 'de8-g37', type: 'Grammar', question: 'Hvad betyder "Überhaupt nicht"?', answer: 'Overhovedet ikke', options: ['Overhovedet ikke', 'Næsten ikke', 'Måske ikke'], instruction: 'Adverbien' },
    { id: 'de8-g38', type: 'Grammar', question: 'Hvad betyder "Sowieso"?', answer: 'Alligevel / Under alle omstændigheder', options: ['Alligevel / Under alle omstændigheder', 'Måske', 'Aldrig'], instruction: 'Adverbien' },
    { id: 'de8-g39', type: 'Grammar', question: 'Hvad betyder "Ganz und gar nicht"?', answer: 'Slet og ret ikke', options: ['Slet og ret ikke', 'Næsten ikke', 'Altid'], instruction: 'Adverbien' },
    { id: 'de8-g40', type: 'Grammar', question: 'Indsæt: Ich ___ (kunne / Präteritum) nicht kommen.', answer: 'konnte', options: ['konnte', 'kann', 'könnte'], instruction: 'Modalverben' },
    { id: 'de8-g41', type: 'Grammar', question: 'Indsæt: Wir ___ (skulle / Präteritum) lernen.', answer: 'mussten', options: ['mussten', 'müssen', 'müssten'], instruction: 'Modalverben' },
    { id: 'de8-g42', type: 'Grammar', question: 'Hvad betyder "Anfangen"?', answer: 'At begynde', options: ['At begynde', 'At slutte', 'At stoppe'], instruction: 'Trennbare Verben' },
    { id: 'de8-g43', type: 'Grammar', question: 'Hvordan deles "Anfangen"? Ich ___ (begynder).', answer: 'fange an', options: ['fange an', 'anfange', 'fangt an'], instruction: 'Trennbare Verben' },
    { id: 'de8-g44', type: 'Grammar', question: 'Hvad betyder "Aufhören"?', answer: 'At holde op', options: ['At holde op', 'At begynde', 'At fortsætte'], instruction: 'Trennbare Verben' },
    { id: 'de8-g45', type: 'Grammar', question: 'Hvordan deles "Aufhören"? Ich ___ (holder op).', answer: 'höre auf', options: ['höre auf', 'aufhöre', 'hört auf'], instruction: 'Trennbare Verben' },
    { id: 'de8-g46', type: 'Grammar', question: 'Hvad betyder "Einladen"?', answer: 'At invitere', options: ['At invitere', 'At komme', 'At gå'], instruction: 'Trennbare Verben' },
    { id: 'de8-g47', type: 'Grammar', question: 'Hvordan deles "Einladen"? Ich ___ (inviterer) dich ___ .', answer: 'lade ... ein', options: ['lade ... ein', 'einlade', 'ladt ein'], instruction: 'Trennbare Verben' },
    { id: 'de8-g48', type: 'Grammar', question: 'Hvad betyder "Aussehen"?', answer: 'At se ud', options: ['At se ud', 'At se hen', 'At se efter'], instruction: 'Trennbare Verben' },
    { id: 'de8-g49', type: 'Grammar', question: 'Hvordan deles "Aussehen"? Du ___ (ser godt ud).', answer: 'siehst gut aus', options: ['siehst gut aus', 'aussiehst gut', 'sieht gut aus'], instruction: 'Trennbare Verben' },
    { id: 'de8-g50', type: 'Grammar', question: 'Hvad betyder "Vorbereiten"?', answer: 'At forberede', options: ['At forberede', 'At kigge på', 'At gemme'], instruction: 'Trennbare Verben' },
    { id: 'de8-g51', type: 'Grammar', question: 'Großartiger ___!', answer: 'Erfolg', options: ['Erfolg', 'Fehler', 'Wald'], instruction: 'Feedback' },
  ],
  9: [
    { id: 'de9-g1', type: 'Grammar', question: 'Hvad betyder "Genitiv"?', answer: 'Ejefald', options: ['Ejefald', 'Hensynsled', 'Grundled'], instruction: 'Kasus' },
    { id: 'de9-g2', type: 'Grammar', question: 'Hvilken endelse får hankøn i genitiv ental?', answer: '-es', options: ['-es', '-en', '-em'], instruction: 'Kasus' },
    { id: 'de9-g3', type: 'Grammar', question: 'Hvad betyder "Des Hauses"?', answer: 'Husets', options: ['Husets', 'Huset', 'Huse'], instruction: 'Kasus' },
    { id: 'de9-g4', type: 'Grammar', question: 'Hvad betyder "Der Frau" i genitiv?', answer: 'Kvindens', options: ['Kvindens', 'Kvinden', 'Kvinder'], instruction: 'Kasus' },
    { id: 'de9-g5', type: 'Grammar', question: 'Hvilket ord betyder "Selvom"?', answer: 'Obwohl', options: ['Obwohl', 'Weil', 'Dass'], instruction: 'Konjunktionen' },
    { id: 'de9-g6', type: 'Grammar', question: 'Hvad betyder "Trotz"?', answer: 'Til trods for', options: ['Til trods for', 'Efter', 'Under'], instruction: 'Präpositionen' },
    { id: 'de9-g7', type: 'Grammar', question: 'Hvilken kasus styrer "Trotz"?', answer: 'Genitiv', options: ['Genitiv', 'Dativ', 'Akkusativ'], instruction: 'Kasus' },
    { id: 'de9-g8', type: 'Grammar', question: 'Hvad betyder "Während"?', answer: 'Under / Mens', options: ['Under / Mens', 'Efter', 'Foran'], instruction: 'Präpositionen' },
    { id: 'de9-g9', type: 'Grammar', question: 'Hvilken kasus styrer "Während"?', answer: 'Genitiv', options: ['Genitiv', 'Dativ', 'Akkusativ'], instruction: 'Kasus' },
    { id: 'de9-g10', type: 'Grammar', question: 'Hvad betyder "Wegen"?', answer: 'På grund af', options: ['På grund af', 'Uden', 'Mod'], instruction: 'Präpositionen' },
    { id: 'de9-g11', type: 'Grammar', question: 'Hvilken kasus styrer "Wegen"?', answer: 'Genitiv', options: ['Genitiv', 'Dativ', 'Akkusativ'], instruction: 'Kasus' },
    { id: 'de9-g12', type: 'Grammar', question: 'Hvad betyder "Statt"?', answer: 'I stedet for', options: ['I stedet for', 'Sammen med', 'Uden'], instruction: 'Präpositionen' },
    { id: 'de9-g13', type: 'Grammar', question: 'Hvilken kasus styrer "Statt"?', answer: 'Genitiv', options: ['Genitiv', 'Dativ', 'Akkusativ'], instruction: 'Kasus' },
    { id: 'de9-g14', type: 'Grammar', question: 'Hvad betyder "Passiv"?', answer: 'At noget bliver gjort ved én', options: ['At noget bliver gjort ved én', 'At man gør noget', 'At man har gjort noget'], instruction: 'Grammatik' },
    { id: 'de9-g15', type: 'Grammar', question: 'Hvordan dannes passiv?', answer: 'Werden + participium', options: ['Werden + participium', 'Sein + participium', 'Haben + participium'], instruction: 'Grammatik' },
    { id: 'de9-g16', type: 'Grammar', question: 'Oversæt: "Bilen vaskes" (passiv).', answer: 'Das Auto wird gewaschen', options: ['Das Auto wird gewaschen', 'Das Auto ist gewaschen', 'Das Auto hat gewaschen'], instruction: 'Passiv' },
    { id: 'de9-g17', type: 'Grammar', question: 'Oversæt: "Bilen blev vasket" (passiv datid).', answer: 'Das Auto wurde gewaschen', options: ['Das Auto wurde gewaschen', 'Das Auto wird gewaschen', 'Das Auto ist gewaschen'], instruction: 'Passiv' },
    { id: 'de9-g18', type: 'Grammar', question: 'Oversæt: "Bilen er blevet vasket" (passiv førnutid).', answer: 'Das Auto ist gewaschen worden', options: ['Das Auto ist gewaschen worden', 'Das Auto hat gewaschen worden', 'Das Auto wird gewaschen'], instruction: 'Passiv' },
    { id: 'de9-g19', type: 'Grammar', question: 'Hvad betyder "Plusquamperfekt"?', answer: 'Førdatid', options: ['Førdatid', 'Datid', 'Fremtid'], instruction: 'Temps' },
    { id: 'de9-g20', type: 'Grammar', question: 'Hvordan dannes Plusquamperfekt?', answer: 'Hjælpeverbum i datid + participium', options: ['Hjælpeverbum i datid + participium', 'Hjælpeverbum i nutid + participium', 'Kun participium'], instruction: 'Grammatik' },
    { id: 'de9-g21', type: 'Grammar', question: 'Oversæt: "Jeg havde spist".', answer: 'Ich hatte gegessen', options: ['Ich hatte gegessen', 'Ich habe gegessen', 'Ich werde gegessen'], instruction: 'Plusquamperfekt' },
    { id: 'de9-g22', type: 'Grammar', question: 'Oversæt: "Jeg var gået".', answer: 'Ich war gegangen', options: ['Ich war gegangen', 'Ich bin gegangen', 'Ich hatte gegangen'], instruction: 'Plusquamperfekt' },
    { id: 'de9-g23', type: 'Grammar', question: 'Hvad betyder "Futur I"?', answer: 'Fremtid', options: ['Fremtid', 'Datid', 'Nutid'], instruction: 'Temps' },
    { id: 'de9-g24', type: 'Grammar', question: 'Hvordan dannes Futur I?', answer: 'Werden + infinitiv', options: ['Werden + infinitiv', 'Sein + infinitiv', 'Haben + participium'], instruction: 'Grammatik' },
    { id: 'de9-g25', type: 'Grammar', question: 'Oversæt: "Jeg vil rejse".', answer: 'Ich werde reisen', options: ['Ich werde reisen', 'Ich würde reisen', 'Ich reist'], instruction: 'Futur' },
    { id: 'de9-g26', type: 'Grammar', question: 'Hvad betyder "Futur II"?', answer: 'Førfremtid', options: ['Førfremtid', 'Fremtid', 'Datid'], instruction: 'Temps' },
    { id: 'de9-g27', type: 'Grammar', question: 'Hvad betyder "Um ... zu" + infinitiv?', answer: 'For at', options: ['For at', 'Uden at', 'Ved at'], instruction: 'Infinitivsætning' },
    { id: 'de9-g28', type: 'Grammar', question: 'Oversæt: "For at lære tysk".', answer: 'Um Deutsch zu lernen', options: ['Um Deutsch zu lernen', 'Für Deutsch lernen', 'Zu Deutsch lernen'], instruction: 'Infinitivsætning' },
    { id: 'de9-g29', type: 'Grammar', question: 'Hvad betyder "Ohne ... zu" + infinitiv?', answer: 'Uden at', options: ['Uden at', 'Ved at', 'For at'], instruction: 'Infinitivsætning' },
    { id: 'de9-g30', type: 'Grammar', question: 'Oversæt: "Uden at sige noget".', answer: 'Ohne etwas zu sagen', options: ['Ohne etwas zu sagen', 'Ohne etwas sagen', 'Nicht etwas zu sagen'], instruction: 'Infinitivsætning' },
    { id: 'de9-g31', type: 'Grammar', question: 'Hvad betyder "Anstatt ... zu" + infinitiv?', answer: 'I stedet for at', options: ['I stedet for at', 'For at', 'Mens'], instruction: 'Infinitivsætning' },
    { id: 'de9-g32', type: 'Grammar', question: 'Oversæt: "I stedet for at sove".', answer: 'Anstatt zu schlafen', options: ['Anstatt zu schlafen', 'Anstatt schlafen', 'Statt schlafe'], instruction: 'Infinitivsætning' },
    { id: 'de9-g33', type: 'Grammar', question: 'Hvilket ord betyder "Betydning"?', answer: 'Bedeutung', options: ['Bedeutung', 'Meinung', 'Gefühl'], instruction: 'Vokabeln' },
    { id: 'de9-g34', type: 'Grammar', question: 'Hvilket ord betyder "Hukommelse"?', answer: 'Gedächtnis', options: ['Gedächtnis', 'Gedanke', 'Gefühl'], instruction: 'Vokabeln' },
    { id: 'de9-g35', type: 'Grammar', question: 'Hvilket ord betyder "Mulighed"?', answer: 'Möglichkeit', options: ['Möglichkeit', 'Notwendigkeit', 'Sicherheit'], instruction: 'Vokabeln' },
    { id: 'de9-g36', type: 'Grammar', question: 'Hvilket ord betyder "Nødvendighed"?', answer: 'Notwendigkeit', options: ['Notwendigkeit', 'Möglichkeit', 'Wichtigkeit'], instruction: 'Vokabeln' },
    { id: 'de9-g37', type: 'Grammar', question: 'Hvilket ord betyder "Beslutning"?', answer: 'Entscheidung', options: ['Entscheidung', 'Besprechung', 'Erzählung'], instruction: 'Vokabeln' },
    { id: 'de9-g38', type: 'Grammar', question: 'Hvilket ord betyder "Erfaring"?', answer: 'Erfahrung', options: ['Erfahrung', 'Erfindung', 'Erzählung'], instruction: 'Vokabeln' },
    { id: 'de9-g39', type: 'Grammar', question: 'Hvilket ord betyder "Udvikling"?', answer: 'Entwicklung', options: ['Entwicklung', 'Entscheidung', 'Erfahrung'], instruction: 'Vokabeln' },
    { id: 'de9-g40', type: 'Grammar', question: 'Hvad betyder "Zusammenhang"?', answer: 'Sammenhæng', options: ['Sammenhæng', 'Samarbejde', 'Sammentræf'], instruction: 'Vokabeln' },
    { id: 'de9-g41', type: 'Grammar', question: 'Hvad betyder "Unterschied"?', answer: 'Forskel', options: ['Forskel', 'Lighed', 'Årsag'], instruction: 'Vokabeln' },
    { id: 'de9-g42', type: 'Grammar', question: 'Hvad betyder "Ursache"?', answer: 'Årsag', options: ['Årsag', 'Virkning', 'Forskel'], instruction: 'Vokabeln' },
    { id: 'de9-g43', type: 'Grammar', question: 'Hvad betyder "Wirkung"?', answer: 'Virkning / Effekt', options: ['Virkning / Effekt', 'Årsag', 'Betydning'], instruction: 'Vokabeln' },
    { id: 'de9-g44', type: 'Grammar', question: 'Hvad betyder "Zustand"?', answer: 'Tilstand', options: ['Tilstand', 'Sted', 'Tid'], instruction: 'Vokabeln' },
    { id: 'de9-g45', type: 'Grammar', question: 'Hvad betyder "Verantwortung"?', answer: 'Ansvar', options: ['Ansvar', 'Pligt', 'Rettighed'], instruction: 'Vokabeln' },
    { id: 'de9-g46', type: 'Grammar', question: 'Hvad betyder "Gerechtigkeit"?', answer: 'Retfærdighed', options: ['Retfærdighed', 'Frihed', 'Lighed'], instruction: 'Vokabeln' },
    { id: 'de9-g47', type: 'Grammar', question: 'Hvad betyder "Herausforderung"?', answer: 'Udfordring', options: ['Udfordring', 'Løsning', 'Problem'], instruction: 'Vokabeln' },
    { id: 'de9-g48', type: 'Grammar', question: 'Hvad betyder "Lösung"?', answer: 'Løsning', options: ['Løsning', 'Problem', 'Udfordring'], instruction: 'Vokabeln' },
    { id: 'de9-g49', type: 'Grammar', question: 'Hvad betyder "Überzeugung"?', answer: 'Overbevisning', options: ['Overbevisning', 'Tro', 'Tvivl'], instruction: 'Vokabeln' },
    { id: 'de9-g50', type: 'Grammar', question: 'Hvad betyder "Zweifel"?', answer: 'Tvivl', options: ['Tvivl', 'Tro', 'Vished'], instruction: 'Vokabeln' },
    { id: 'de9-g51', type: 'Grammar', question: 'Perfekte ___!', answer: 'Leistung', options: ['Leistung', 'Fehler', 'Wald'], instruction: 'Feedback' },
  ],
};
