/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const TYSK_GRAMMAR_P2: Partial<Record<Grade, GameContent[]>> = {
  5: [
    { id: 'de5-g1', type: 'Grammar', question: 'Hvilken kasus styrer "Durch"?', answer: 'Akkusativ', options: ['Akkusativ', 'Dativ', 'Genitiv'], instruction: 'Präpositionen' },
    { id: 'de5-g2', type: 'Grammar', question: 'Hvilken kasus styrer "Für"?', answer: 'Akkusativ', options: ['Akkusativ', 'Dativ'], instruction: 'Präpositionen' },
    { id: 'de5-g3', type: 'Grammar', question: 'Hvilken kasus styrer "Gegen"?', answer: 'Akkusativ', options: ['Akkusativ', 'Dativ'], instruction: 'Präpositionen' },
    { id: 'de5-g4', type: 'Grammar', question: 'Hvilken kasus styrer "Ohne"?', answer: 'Akkusativ', options: ['Akkusativ', 'Dativ'], instruction: 'Präpositionen' },
    { id: 'de5-g5', type: 'Grammar', question: 'Hvilken kasus styrer "Um"?', answer: 'Akkusativ', options: ['Akkusativ', 'Dativ'], instruction: 'Präpositionen' },
    { id: 'de5-g6', type: 'Grammar', question: 'Indsæt: Ich sehe ___ Hund (der - akkusativ).', answer: 'den', options: ['den', 'der', 'dem'], instruction: 'Akkusativ' },
    { id: 'de5-g7', type: 'Grammar', question: 'Indsæt: Wir haben ___ Apfel (der - akkusativ).', answer: 'einen', options: ['einen', 'ein', 'einem'], instruction: 'Akkusativ' },
    { id: 'de5-g8', type: 'Grammar', question: 'Hvilken endelse får hankøn i akkusativ?', answer: '-en', options: ['-en', '-er', '-em'], instruction: 'Akkusativ' },
    { id: 'de5-g9', type: 'Grammar', question: 'Ændrer hunkøn sig i akkusativ?', answer: 'Nej', options: ['Nej', 'Ja'], instruction: 'Akkusativ' },
    { id: 'de5-g10', type: 'Grammar', question: 'Ændrer intetkøn sig i akkusativ?', answer: 'Nej', options: ['Nej', 'Ja'], instruction: 'Akkusativ' },
    { id: 'de5-g11', type: 'Grammar', question: 'Hvad betyder "Werden"?', answer: 'At blive', options: ['At blive', 'At have', 'At være'], instruction: 'Verben' },
    { id: 'de5-g12', type: 'Grammar', question: 'Hvordan bøjes "Werden" ved "Ich"?', answer: 'werde', options: ['werde', 'wirst', 'wird'], instruction: 'Werden' },
    { id: 'de5-g13', type: 'Grammar', question: 'Hvordan bøjes "Werden" ved "Du"?', answer: 'wirst', options: ['wirst', 'werde', 'wird'], instruction: 'Werden' },
    { id: 'de5-g14', type: 'Grammar', question: 'Hvordan bøjes "Werden" ved "Er"?', answer: 'wird', options: ['wird', 'wirst', 'werden'], instruction: 'Werden' },
    { id: 'de5-g15', type: 'Grammar', question: 'Hvordan bøjes "Werden" ved "Wir"?', answer: 'werden', options: ['werden', 'werdet', 'wird'], instruction: 'Werden' },
    { id: 'de5-g16', type: 'Grammar', question: 'Hvad betyder "Laufen"?', answer: 'At løbe', options: ['At løbe', 'At gå', 'At stå'], instruction: 'Verben' },
    { id: 'de5-g17', type: 'Grammar', question: 'Hvordan bøjes "Laufen" ved "Du"?', answer: 'läufst', options: ['läufst', 'laufst', 'lauft'], instruction: 'Vokalwechsel' },
    { id: 'de5-g18', type: 'Grammar', question: 'Hvordan bøjes "Laufen" ved "Er"?', answer: 'läuft', options: ['läuft', 'lauft', 'läufst'], instruction: 'Vokalwechsel' },
    { id: 'de5-g19', type: 'Grammar', question: 'Hvad betyder "Essen"?', answer: 'At spise', options: ['At spise', 'At drikke', 'At sove'], instruction: 'Verben' },
    { id: 'de5-g20', type: 'Grammar', question: 'Hvordan bøjes "Essen" ved "Du"?', answer: 'isst', options: ['isst', 'esst', 'essen'], instruction: 'Vokalwechsel' },
    { id: 'de5-g21', type: 'Grammar', question: 'Hvordan bøjes "Essen" ved "Er"?', answer: 'isst', options: ['isst', 'esst', 'essen'], instruction: 'Vokalwechsel' },
    { id: 'de5-g22', type: 'Grammar', question: 'Hvad betyder "Geben"?', answer: 'At give', options: ['At give', 'At tage', 'At se'], instruction: 'Verben' },
    { id: 'de5-g23', type: 'Grammar', question: 'Hvordan bøjes "Geben" ved "Er"?', answer: 'gibt', options: ['gibt', 'gebt', 'geben'], instruction: 'Vokalwechsel' },
    { id: 'de5-g24', type: 'Grammar', question: 'Hvor mange "Kasus" er der på tysk?', answer: 'Vier (4)', options: ['Vier (4)', 'Tre (3)', 'Fem (5)'], instruction: 'Grammatik' },
    { id: 'de5-g25', type: 'Grammar', question: 'Hvad kaldes grundleddet?', answer: 'Nominativ', options: ['Nominativ', 'Akkusativ', 'Dativ'], instruction: 'Kasus' },
    { id: 'de5-g26', type: 'Grammar', question: 'Hvad kaldes genstandsleddet?', answer: 'Akkusativ', options: ['Akkusativ', 'Nominativ', 'Dativ'], instruction: 'Kasus' },
    { id: 'de5-g27', type: 'Grammar', question: 'Hvad kaldes hensynsleddet?', answer: 'Dativ', options: ['Dativ', 'Akkusativ', 'Nominativ'], instruction: 'Kasus' },
    { id: 'de5-g28', type: 'Grammar', question: 'Hvad kaldes ejefald?', answer: 'Genitiv', options: ['Genitiv', 'Dativ', 'Nominativ'], instruction: 'Kasus' },
    { id: 'de5-g29', type: 'Grammar', question: 'Tal: 1/2', answer: 'Halb', options: ['Halb', 'Viertel', 'Ganz'], instruction: 'Zahlen' },
    { id: 'de5-g30', type: 'Grammar', question: 'Hvilket ord betyder "Klokken"?', answer: 'Uhr', options: ['Uhr', 'Zeit', 'Minute'], instruction: 'Zeit' },
    { id: 'de5-g31', type: 'Grammar', question: 'Hvilket ord betyder "Halv"?', answer: 'Halb', options: ['Halb', 'Viertel', 'Nach'], instruction: 'Uhrzeit' },
    { id: 'de5-g32', type: 'Grammar', question: 'Hvad er modsætningen til "Interessant"?', answer: 'Langweilig', options: ['Langweilig', 'Lustig', 'Schön'], instruction: 'Adjektive' },
    { id: 'de5-g33', type: 'Grammar', question: 'Hvad betyder "Schwierig"?', answer: 'Svært', options: ['Svært', 'Nemt', 'Hurtigt'], instruction: 'Adjektive' },
    { id: 'de5-g34', type: 'Grammar', question: 'Hvad betyder "Einfach"?', answer: 'Nemt / Enkelt', options: ['Nemt / Enkelt', 'Svært', 'Langt'], instruction: 'Adjektive' },
    { id: 'de5-g35', type: 'Grammar', question: 'Hvad betyder "Überall"?', answer: 'Overalt', options: ['Overalt', 'Ingensteds', 'Her'], instruction: 'Adverbien' },
    { id: 'de5-g36', type: 'Grammar', question: 'Hvad betyder "Irgendwo"?', answer: 'Et eller andet sted', options: ['Et eller andet sted', 'Her', 'Der'], instruction: 'Adverbien' },
    { id: 'de5-g37', type: 'Grammar', question: 'Hvad betyder "Nirgendwo"?', answer: 'Ingensteds', options: ['Ingensteds', 'Overalt', 'Derovre'], instruction: 'Adverbien' },
    { id: 'de5-g38', type: 'Grammar', question: 'Hvilken præposition betyder "Mellem"?', answer: 'Zwischen', options: ['Zwischen', 'Unter', 'Hinter'], instruction: 'Präpositionen' },
    { id: 'de5-g39', type: 'Grammar', question: 'Hvilken præposition betyder "Bagved"?', answer: 'Hinter', options: ['Hinter', 'Vor', 'Über'], instruction: 'Präpositionen' },
    { id: 'de5-g40', type: 'Grammar', question: 'Hvilken præposition betyder "Foran"?', answer: 'Vor', options: ['Vor', 'Hinter', 'Neben'], instruction: 'Präpositionen' },
    { id: 'de5-g41', type: 'Grammar', question: 'Hvilken præposition betyder "Ved siden af"?', answer: 'Neben', options: ['Neben', 'Zwischen', 'An'], instruction: 'Präpositionen' },
    { id: 'de5-g42', type: 'Grammar', question: 'Indsæt bøjning: Ich ___ (spise).', answer: 'esse', options: ['esse', 'isst', 'esst'], instruction: 'Präsens' },
    { id: 'de5-g43', type: 'Grammar', question: 'Indsæt bøjning: Du ___ (sige).', answer: 'sagst', options: ['sagst', 'sage', 'sagt'], instruction: 'Präsens' },
    { id: 'de5-g44', type: 'Grammar', question: 'Hvad betyder "Das Wetter"?', answer: 'Vejret', options: ['Vejret', 'Vandet', 'Luften'], instruction: 'Vokabeln' },
    { id: 'de5-g45', type: 'Grammar', question: 'Hvad betyder "Es regnet"?', answer: 'Det regner', options: ['Det regner', 'Det sner', 'Solen skinner'], instruction: 'Wetter' },
    { id: 'de5-g46', type: 'Grammar', question: 'Hvad betyder "Die Sonne scheint"?', answer: 'Solen skinner', options: ['Solen skinner', 'Det regner', 'Det blæser'], instruction: 'Wetter' },
    { id: 'de5-g47', type: 'Grammar', question: 'Hvad betyder "Kalt" og "Warm"?', answer: 'Koldt og Varmt', options: ['Koldt og Varmt', 'Lyst og Mørkt', 'Dyrt og Billigt'], instruction: 'Wetter' },
    { id: 'de5-g48', type: 'Grammar', question: '"Ein" eller "Einen"? Er kauft ___ Pullover (der).', answer: 'einen', options: ['einen', 'ein'], instruction: 'Akkusativ' },
    { id: 'de5-g49', type: 'Grammar', question: '"Ein" eller "Eine"? Er kauft ___ Hose (die).', answer: 'eine', options: ['eine', 'ein'], instruction: 'Akkusativ' },
    { id: 'de5-g50', type: 'Grammar', question: '"Ein" eller "Ein"? Er kauft ___ Hemd (das).', answer: 'ein', options: ['ein', 'einen'], instruction: 'Akkusativ' },
    { id: 'de5-g51', type: 'Grammar', question: 'Gut ___!', answer: 'gearbeitet', options: ['gearbeitet', 'schlecht', 'grün'], instruction: 'Feedback' },
  ],
  6: [
    { id: 'de6-g1', type: 'Grammar', question: 'Hvilken kasus styrer "Aus"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ', 'Genitiv'], instruction: 'Präpositionen' },
    { id: 'de6-g2', type: 'Grammar', question: 'Hvilken kasus styrer "Bei"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ'], instruction: 'Präpositionen' },
    { id: 'de6-g3', type: 'Grammar', question: 'Hvilken kasus styrer "Mit"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ'], instruction: 'Präpositionen' },
    { id: 'de6-g4', type: 'Grammar', question: 'Hvilken kasus styrer "Nach"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ'], instruction: 'Präpositionen' },
    { id: 'de6-g5', type: 'Grammar', question: 'Hvilken kasus styrer "Seit"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ'], instruction: 'Präpositionen' },
    { id: 'de6-g6', type: 'Grammar', question: 'Hvilken kasus styrer "Von"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ'], instruction: 'Präpositionen' },
    { id: 'de6-g7', type: 'Grammar', question: 'Hvilken kasus styrer "Zu"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ'], instruction: 'Präpositionen' },
    { id: 'de6-g8', type: 'Grammar', question: 'Hvilken endelse får hankøn i dativ?', answer: '-em (dem)', options: ['-em (dem)', '-en (den)', '-er (der)'], instruction: 'Dativ' },
    { id: 'de6-g9', type: 'Grammar', question: 'Hvilken endelse får hunkøn i dativ?', answer: '-er (der)', options: ['-er (der)', '-em (dem)', '-en (den)'], instruction: 'Dativ' },
    { id: 'de6-g10', type: 'Grammar', question: 'Hvilken endelse får intetkøn i dativ?', answer: '-em (dem)', options: ['-em (dem)', '-er (der)', '-en (den)'], instruction: 'Dativ' },
    { id: 'de6-g11', type: 'Grammar', question: 'Hvilken endelse får flertal i dativ?', answer: '-en (den)', options: ['-en (den)', '-er (der)', '-em (dem)'], instruction: 'Dativ' },
    { id: 'de6-g12', type: 'Grammar', question: 'Hvad betyder "Wissen"?', answer: 'At vide', options: ['At vide', 'At tro', 'At mene'], instruction: 'Verben' },
    { id: 'de6-g13', type: 'Grammar', question: 'Hvordan bøjes "Wissen" ved "Ich"?', answer: 'weiß', options: ['weiß', 'wisse', 'wisst'], instruction: 'Wissen' },
    { id: 'de6-g14', type: 'Grammar', question: 'Hvordan bøjes "Wissen" ved "Du"?', answer: 'weißt', options: ['weißt', 'weiß', 'wissest'], instruction: 'Wissen' },
    { id: 'de6-g15', type: 'Grammar', question: 'Hvordan bøjes "Wissen" ved "Er"?', answer: 'weiß', options: ['weiß', 'wisst', 'wissen'], instruction: 'Wissen' },
    { id: 'de6-g16', type: 'Grammar', question: 'Hvad betyder "Leidenschaft"?', answer: 'Lidenskab', options: ['Lidenskab', 'Sygdom', 'Venskab'], instruction: 'Vokabeln' },
    { id: 'de6-g17', type: 'Grammar', question: 'Hvad betyder "Eigenschaft"?', answer: 'Egenskab', options: ['Egenskab', 'Venskab', 'Selskab'], instruction: 'Vokabeln' },
    { id: 'de6-g18', type: 'Grammar', question: 'Hvad betyder "Freundschaft"?', answer: 'Venskab', options: ['Venskab', 'Fjendskab', 'Lidenskab'], instruction: 'Vokabeln' },
    { id: 'de6-g19', type: 'Grammar', question: 'Hvad betyder "Man"?', answer: 'Man (upersonlig)', options: ['Man (upersonlig)', 'Mand', 'Menneske'], instruction: 'Pronomen' },
    { id: 'de6-g20', type: 'Grammar', question: 'Står "ikke" foran eller efter udsagnsordet i hovedsætninger?', answer: 'Efter', options: ['Efter', 'Foran'], instruction: 'Satzbau' },
    { id: 'de6-g21', type: 'Grammar', question: 'Hvor står udsagnsordet i en spørgesætning (uden hv-ord)?', answer: 'Først', options: ['Først', 'Sidst', 'I midten'], instruction: 'Satzbau' },
    { id: 'de6-g22', type: 'Grammar', question: 'Hvad betyder "Dürfen"?', answer: 'At måtte / have lov til', options: ['At måtte / have lov til', 'At skulle', 'At ville'], instruction: 'Modalverben' },
    { id: 'de6-g23', type: 'Grammar', question: 'Hvordan bøjes "Dürfen" ved "Ich"?', answer: 'darf', options: ['darf', 'dürfe', 'darfst'], instruction: 'Dürfen' },
    { id: 'de6-g24', type: 'Grammar', question: 'Hvad betyder "Mögen"?', answer: 'At kunne lide', options: ['At kunne lide', 'At ville', 'At skulle'], instruction: 'Modalverben' },
    { id: 'de6-g25', type: 'Grammar', question: 'Hvordan bøjes "Mögen" ved "Ich"?', answer: 'mag', options: ['mag', 'möge', 'möchte'], instruction: 'Mögen' },
    { id: 'de6-g26', type: 'Grammar', question: 'Hvad betyder "Möchte"?', answer: 'Ville gerne', options: ['Ville gerne', 'Kan lide', 'Skal'], instruction: 'Möchte' },
    { id: 'de6-g27', type: 'Grammar', question: 'Hvordan dannes "Perfekt" (førnutid)?', answer: 'Hjælpeverbum + participium', options: ['Hjælpeverbum + participium', 'Kun participium', 'Infinitiv'], instruction: 'Perfekt' },
    { id: 'de6-g28', type: 'Grammar', question: 'Hvilket hjælpeverbum bruges mest i Perfekt?', answer: 'Haben', options: ['Haben', 'Sein', 'Werden'], instruction: 'Perfekt' },
    { id: 'de6-g29', type: 'Grammar', question: 'Hvilket hjælpeverbum bruges ved bevægelse (gehe, fahre)?', answer: 'Sein', options: ['Sein', 'Haben', 'Werden'], instruction: 'Perfekt' },
    { id: 'de6-g30', type: 'Grammar', question: 'Oversæt: "Jeg har spist" (Perfekt).', answer: 'Ich habe gegessen', options: ['Ich habe gegessen', 'Ich gegessen habe', 'Ich habe essen'], instruction: 'Perfekt' },
    { id: 'de6-g31', type: 'Grammar', question: 'Oversæt: "Jeg er gået" (Perfekt).', answer: 'Ich bin gegangen', options: ['Ich bin gegangen', 'Ich habe gegangen', 'Ich gegangen bin'], instruction: 'Perfekt' },
    { id: 'de6-g32', type: 'Grammar', question: 'Hvor placeres "ge-" iet participium typisk?', answer: 'Forrest', options: ['Forrest', 'Bagest', 'I midten'], instruction: 'Participium' },
    { id: 'de6-g33', type: 'Grammar', question: 'Hvad betyder "Erzählen"?', answer: 'At fortælle', options: ['At fortælle', 'At tælle', 'At betale'], instruction: 'Verben' },
    { id: 'de6-g34', type: 'Grammar', question: 'Hvad betyder "Verkaufen"?', answer: 'At sælge', options: ['At sælge', 'At købe', 'At give'], instruction: 'Verben' },
    { id: 'de6-g35', type: 'Grammar', question: 'Hvad betyder "Kaufen"?', answer: 'At købe', options: ['At købe', 'At sælge', 'At bytte'], instruction: 'Verben' },
    { id: 'de6-g36', type: 'Grammar', question: 'Hvilket ord betyder "Fordi"?', answer: 'Weil', options: ['Weil', 'Denn', 'Dass'], instruction: 'Konjunktionen' },
    { id: 'de6-g37', type: 'Grammar', question: 'Hvilket ord betyder "At (konjunktion)"?', answer: 'Dass', options: ['Dass', 'Das', 'Weil'], instruction: 'Konjunktionen' },
    { id: 'de6-g38', type: 'Grammar', question: 'Hvor står udsagnsordet i en "Weil"-sætning?', answer: 'Sidst', options: ['Sidst', 'Først', 'Andenpladsen'], instruction: 'Nebensatz' },
    { id: 'de6-g39', type: 'Grammar', question: 'Hvor står udsagnsordet i en "Dass"-sætning?', answer: 'Sidst', options: ['Sidst', 'Først', 'I midten'], instruction: 'Nebensatz' },
    { id: 'de6-g40', type: 'Grammar', question: 'Hvad betyder "Ob"?', answer: 'Om', options: ['Om', 'Hvis', 'Når'], instruction: 'Konjunktionen' },
    { id: 'de6-g41', type: 'Grammar', question: 'Hvad betyder "Wenn"?', answer: 'Hvis / Når', options: ['Hvis / Når', 'Da', 'Men'], instruction: 'Konjunktionen' },
    { id: 'de6-g42', type: 'Grammar', question: 'Hvad betyder "Als"?', answer: 'Da (engangs i fortid)', options: ['Da (engangs i fortid)', 'Hvis', 'Fordi'], instruction: 'Konjunktionen' },
    { id: 'de6-g43', type: 'Grammar', question: 'Indsæt: Hilfe ___ (dativ). Ich helfe ___ Vater (der).', answer: 'dem', options: ['dem', 'den', 'der'], instruction: 'Dativ' },
    { id: 'de6-g44', type: 'Grammar', question: 'Indsæt: Ich helfe ___ Mutter (die).', answer: 'der', options: ['der', 'die', 'dem'], instruction: 'Dativ' },
    { id: 'de6-g45', type: 'Grammar', question: 'Hvad betyder "Das Geschenk"?', answer: 'Gaven', options: ['Gaven', 'Opvasken', 'Arbejdet'], instruction: 'Vokabeln' },
    { id: 'de6-g46', type: 'Grammar', question: 'Hvad betyder "Schenken"?', answer: 'At forære', options: ['At forære', 'At tage', 'At købe'], instruction: 'Verben' },
    { id: 'de6-g47', type: 'Grammar', question: 'Hvilken kasus bruges til den person, man giver noget?', answer: 'Dativ', options: ['Dativ', 'Akkusativ', 'Nominativ'], instruction: 'Hensynsled' },
    { id: 'de6-g48', type: 'Grammar', question: 'Hvilken kasus bruges til den ting, man giver?', answer: 'Akkusativ', options: ['Akkusativ', 'Dativ', 'Nominativ'], instruction: 'Genstandsled' },
    { id: 'de6-g49', type: 'Grammar', question: 'Indsæt: Er gibt ___ (drengen - dativ) den Ball.', answer: 'dem Jungen', options: ['dem Jungen', 'den Jungen', 'der Jungen'], instruction: 'Dativ' },
    { id: 'de6-g50', type: 'Grammar', question: 'Hvad betyder "Wichtig"?', answer: 'Vigtigt', options: ['Vigtigt', 'Svært', 'Nemt'], instruction: 'Adjektive' },
    { id: 'de6-g51', type: 'Grammar', question: 'Prima ___!', answer: 'gemacht', options: ['gemacht', 'schlecht', 'rot'], instruction: 'Feedback' },
  ],
  7: [
    { id: 'de7-g1', type: 'Grammar', question: 'Hvad betyder "Präteritum"?', answer: 'Datid (skriftlig)', options: ['Datid (skriftlig)', 'Nutid', 'Fremtid'], instruction: 'Temps' },
    { id: 'de7-g2', type: 'Grammar', question: 'Hvordan bøjes "Machen" i Präteritum (Jeg)?', answer: 'machte', options: ['machte', 'machtet', 'machst'], instruction: 'Präteritum' },
    { id: 'de7-g3', type: 'Grammar', question: 'Hvordan bøjes "Haben" i Präteritum (Jeg)?', answer: 'hatte', options: ['hatte', 'hast', 'hat'], instruction: 'Präteritum' },
    { id: 'de7-g4', type: 'Grammar', question: 'Hvordan bøjes "Sein" i Präteritum (Jeg)?', answer: 'war', options: ['war', 'bin', 'ist'], instruction: 'Präteritum' },
    { id: 'de7-g5', type: 'Grammar', question: 'Hvad betyder "Können" i Präteritum (Jeg)?', answer: 'konnte', options: ['konnte', 'kann', 'könnte'], instruction: 'Präteritum' },
    { id: 'de7-g6', type: 'Grammar', question: 'Hvad betyder "Müssen" i Präteritum (Jeg)?', answer: 'musste', options: ['musste', 'muss', 'müsste'], instruction: 'Präteritum' },
    { id: 'de7-g7', type: 'Grammar', question: 'Hvad betyder "Wollen" i Präteritum (Jeg)?', answer: 'wollte', options: ['wollte', 'will', 'wollte'], instruction: 'Präteritum' },
    { id: 'de7-g8', type: 'Grammar', question: 'Hvornår bruges "Akkusativ"?', answer: 'Ved direkte genstand', options: ['Ved direkte genstand', 'Ved hensyn', 'Ved ejefald'], instruction: 'Kasus' },
    { id: 'de7-g9', type: 'Grammar', question: 'Hvornår bruges "Dativ"?', answer: 'Ved indirekte genstand / hensyn', options: ['Ved indirekte genstand / hensyn', 'Ved direkte genstand', 'Ved grundled'], instruction: 'Kasus' },
    { id: 'de7-g10', type: 'Grammar', question: 'Hvilken kasus styrer "Helfen"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ', 'Nominativ'], instruction: 'Dativ-Verben' },
    { id: 'de7-g11', type: 'Grammar', question: 'Hvilken kasus styrer "Danken"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ'], instruction: 'Dativ-Verben' },
    { id: 'de7-g12', type: 'Grammar', question: 'Hvilken kasus styrer "Glauben"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ'], instruction: 'Dativ-Verben' },
    { id: 'de7-g13', type: 'Grammar', question: 'Hvilken kasus styrer "Gehören"?', answer: 'Dativ', options: ['Dativ', 'Akkusativ'], instruction: 'Dativ-Verben' },
    { id: 'de7-g14', type: 'Grammar', question: 'Hvad betyder "Das Auto gehört ___ Vater" (der).', answer: 'dem', options: ['dem', 'den', 'der'], instruction: 'Dativ' },
    { id: 'de7-g15', type: 'Grammar', question: 'Hvad betyder "Genitiv"?', answer: 'Ejefald', options: ['Ejefald', 'Hensynsled', 'Genstandsled'], instruction: 'Kasus' },
    { id: 'de7-g16', type: 'Grammar', question: 'Hvad er endelsen for hankøn i Genitiv?', answer: '-es (des)', options: ['-es (des)', '-en (den)', '-er (der)'], instruction: 'Genitiv' },
    { id: 'de7-g17', type: 'Grammar', question: 'Hvad er endelsen for hunkøn i Genitiv?', answer: '-er (der)', options: ['-er (der)', '-es (des)', '-en (den)'], instruction: 'Genitiv' },
    { id: 'de7-g18', type: 'Grammar', question: 'Hvilken præposition styrer Genitiv?', answer: 'Während', options: ['Während', 'Mit', 'Durch'], instruction: 'Genitiv-Präpositionen' },
    { id: 'de7-g19', type: 'Grammar', question: 'Hvad betyder "Wegen"?', answer: 'På grund af (styrer genitiv)', options: ['På grund af (styrer genitiv)', 'Mod', 'Uden'], instruction: 'Präpositionen' },
    { id: 'de7-g20', type: 'Grammar', question: 'Hvad betyder "Statt"?', answer: 'I stedet for (styrer genitiv)', options: ['I stedet for (styrer genitiv)', 'Med', 'Hos'], instruction: 'Präpositionen' },
    { id: 'de7-g21', type: 'Grammar', question: 'Hvad betyder "Trotz"?', answer: 'Til trods for (styrer genitiv)', options: ['Til trods for (styrer genitiv)', 'Bagved', 'Under'], instruction: 'Präpositionen' },
    { id: 'de7-g22', type: 'Grammar', question: 'Oversæt: "I stedet for bogen" (Buch - das).', answer: 'Statt des Buches', options: ['Statt des Buches', 'Statt dem Buch', 'Statt das Buch'], instruction: 'Genitiv' },
    { id: 'de7-g23', type: 'Grammar', question: 'Hvad betyder "Gestern" og "Heute"?', answer: 'I går og i dag', options: ['I går og i dag', 'I dag og i morgen', 'Nu og senere'], instruction: 'Zeit' },
    { id: 'de7-g24', type: 'Grammar', question: 'Hvad betyder "Vorgestern"?', answer: 'I forgårs', options: ['I forgårs', 'Overmorgen', 'I går'], instruction: 'Zeit' },
    { id: 'de7-g25', type: 'Grammar', question: 'Hvad betyder "Übermorgen"?', answer: 'I overmorgen', options: ['I overmorgen', 'I forgårs', 'Nu'], instruction: 'Zeit' },
    { id: 'de7-g26', type: 'Grammar', question: 'Hvad betyder "Vielleicht"?', answer: 'Måske', options: ['Måske', 'Selvfølgelig', 'Aldrig'], instruction: 'Adverbien' },
    { id: 'de7-g27', type: 'Grammar', question: 'Hvad betyder "Sicherlich"?', answer: 'Sikkert', options: ['Sikkert', 'Måske', 'Ikke'], instruction: 'Adverbien' },
    { id: 'de7-g28', type: 'Grammar', question: 'Hvad betyder "Besonders"?', answer: 'Især / Særligt', options: ['Især / Særligt', 'Almindeligt', 'Dårligt'], instruction: 'Adverbien' },
    { id: 'de7-g29', type: 'Grammar', question: 'Hvad betyder "Ganz"?', answer: 'Helt / Temmelig', options: ['Helt / Temmelig', 'Lidt', 'Næsten'], instruction: 'Adverbien' },
    { id: 'de7-g30', type: 'Grammar', question: 'Hvad betyder "Fast"?', answer: 'Næsten', options: ['Næsten', 'Hurtigt', 'Altid'], instruction: 'Adverbien' },
    { id: 'de7-g31', type: 'Grammar', question: '"Dass" eller "Das"? Ich hoffe, ___ du kommst.', answer: 'dass', options: ['dass', 'das'], instruction: 'Konjunktionen' },
    { id: 'de7-g32', type: 'Grammar', question: '"Dass" eller "Das"? ___ Buch ist gut.', answer: 'Das', options: ['Das', 'Dass'], instruction: 'Artikel' },
    { id: 'de7-g33', type: 'Grammar', question: 'Hvor står udsagnsordet i en "Dass"-sætning?', answer: 'Sidst', options: ['Sidst', 'Først', 'Andenpladsen'], instruction: 'Nebensatz' },
    { id: 'de7-g34', type: 'Grammar', question: 'Hvor står udsagnsordet i en "Weil"-sætning?', answer: 'Sidst', options: ['Sidst', 'I midten', 'Først'], instruction: 'Nebensatz' },
    { id: 'de7-g35', type: 'Grammar', question: 'Hvad betyder "Obwohl"?', answer: 'Selvom', options: ['Selvom', 'Fordi', 'Da'], instruction: 'Nebensatz' },
    { id: 'de7-g36', type: 'Grammar', question: 'Hvad betyder "Nachdem"?', answer: 'Efter at', options: ['Efter at', 'Før at', 'Da'], instruction: 'Nebensatz' },
    { id: 'de7-g37', type: 'Grammar', question: 'Hvad betyder "Während" (konjunktion)?', answer: 'Mens', options: ['Mens', 'Efter', 'Da'], instruction: 'Nebensatz' },
    { id: 'de7-g38', type: 'Grammar', question: 'Hvad betyder "Bevor"?', answer: 'Før at', options: ['Før at', 'Efter at', 'Når'], instruction: 'Nebensatz' },
    { id: 'de7-g39', type: 'Grammar', question: 'Hvad betyder "Seitdem"?', answer: 'Siden at', options: ['Siden at', 'Selvom', 'Fordi'], instruction: 'Nebensatz' },
    { id: 'de7-g40', type: 'Grammar', question: 'Indsæt: Wir ___ (war) im Wald.', answer: 'waren', options: ['waren', 'war', 'wart'], instruction: 'Präteritum' },
    { id: 'de7-g41', type: 'Grammar', question: 'Indsæt: Ihr ___ (war) zu Hause.', answer: 'wart', options: ['wart', 'war', 'waren'], instruction: 'Präteritum' },
    { id: 'de7-g42', type: 'Grammar', question: 'Hvad betyder "Das Dorf"?', answer: 'Landsbyen', options: ['Landsbyen', 'Byen', 'Skolen'], instruction: 'Vokabeln' },
    { id: 'de7-g43', type: 'Grammar', question: 'Hvad betyder "Die Stadt"?', answer: 'Byen', options: ['Byen', 'Landsbyen', 'Landet'], instruction: 'Vokabeln' },
    { id: 'de7-g44', type: 'Grammar', question: 'Hvad betyder "Das Land"?', answer: 'Landet', options: ['Landet', 'Byen', 'Øen'], instruction: 'Vokabeln' },
    { id: 'de7-g45', type: 'Grammar', question: 'Hvad betyder "Der Fluss"?', answer: 'Floden', options: ['Floden', 'Søen', 'Havet'], instruction: 'Vokabeln' },
    { id: 'de7-g46', type: 'Grammar', question: 'Hvad betyder "Der Berg"?', answer: 'Bjerget', options: ['Bjerget', 'Dalen', 'Skoven'], instruction: 'Vokabeln' },
    { id: 'de7-g47', type: 'Grammar', question: 'Hvad betyder "Der Wald"?', answer: 'Skoven', options: ['Skoven', 'Marken', 'Haven'], instruction: 'Vokabeln' },
    { id: 'de7-g48', type: 'Grammar', question: 'Indsæt bøjning: Ich ___ (finden) es gut.', answer: 'finde', options: ['finde', 'findest', 'findet'], instruction: 'Präsens' },
    { id: 'de3-g49', type: 'Grammar', question: 'Indsæt bøjning: Er ___ (finden) det snavset.', answer: 'findet', options: ['findet', 'findest', 'finde'], instruction: 'Präsens' },
    { id: 'de7-g50', type: 'Grammar', question: 'Hvad betyder "Ganz genau"?', answer: 'Helt præcis', options: ['Helt præcis', 'Måske', 'Slet ikke'], instruction: 'Vokabeln' },
    { id: 'de7-g51', type: 'Grammar', question: 'Wunderbar ___!', answer: 'gemacht', options: ['gemacht', 'schlecht', 'gelb'], instruction: 'Feedback' },
  ],
};
