/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const ENGELSK_MEMORY_P1: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'en0-me1', type: 'Memory', question: 'Numbers (1-6)', instruction: 'Match numeral to word', answer: '', context: '1:One|2:Two|3:Three|4:Four|5:Five|6:Six' },
    { id: 'en0-me2', type: 'Memory', question: 'Colors', instruction: 'Match the colors', answer: '', context: 'Red:Red|Blue:Blue|Yellow:Yellow|Green:Green|Orange:Orange|Purple:Purple' },
    { id: 'en0-me3', type: 'Memory', question: 'Family', instruction: 'Match family members', answer: '', context: 'Mother:Mother|Father:Father|Sister:Sister|Brother:Brother|Baby:Baby|Grandma:Grandma' },
    { id: 'en0-me4', type: 'Memory', question: 'Animals', instruction: 'Match the animals', answer: '', context: 'Cat:Cat|Dog:Dog|Bird:Bird|Fish:Fish|Mouse:Mouse|Rabbit:Rabbit' },
    { id: 'en0-me5', type: 'Memory', question: 'Body Parts', instruction: 'Match body parts', answer: '', context: 'Head:Head|Hands:Hands|Feet:Feet|Eyes:Eyes|Nose:Nose|Mouth:Mouth' },
    { id: 'en0-me6', type: 'Memory', question: 'School Objects', instruction: 'Match objects', answer: '', context: 'Book:Book|Pencil:Pencil|Bag:Bag|Chair:Chair|Table:Table|Paper:Paper' },
    { id: 'en0-me7', type: 'Memory', question: 'Actions', instruction: 'Match actions', answer: '', context: 'Jump:Jump|Run:Run|Sing:Sing|Dance:Dance|Sit:Sit|Stand:Stand' },
    { id: 'en0-me8', type: 'Memory', question: 'Fruits', instruction: 'Match fruits', answer: '', context: 'Apple:Apple|Banana:Banana|Orange:Orange|Pear:Pear|Grape:Grape|Strawberry:Strawberry' },
    { id: 'en0-me9', type: 'Memory', question: 'Nature', instruction: 'Match nature words', answer: '', context: 'Sun:Sun|Moon:Moon|Star:Star|Tree:Tree|Flower:Flower|Grass:Grass' },
    { id: 'en0-me10', type: 'Memory', question: 'Toys', instruction: 'Match toys', answer: '', context: 'Ball:Ball|Doll:Doll|Car:Car|Train:Train|Block:Block|Teddy:Teddy' },
    { id: 'en0-me11', type: 'Memory', question: 'Animal Sounds', instruction: 'Match animal to sound', answer: '', context: 'Dog:Woof|Cat:Meow|Cow:Moo|Duck:Quack|Sheep:Baa|Lion:Roar' },
    { id: 'en0-me12', type: 'Memory', question: 'Simple Rhymes 1', instruction: 'Match rhyming words', answer: '', context: 'Cat:Hat|Dog:Log|Pig:Wig|Bat:Mat|Fox:Box|Hen:Pen' },
    { id: 'en0-me13', type: 'Memory', question: 'Simple Rhymes 2', instruction: 'Match rhyming words', answer: '', context: 'Sun:Fun|Bee:Tree|Star:Car|Fly:Sky|Moon:Spoon|Bed:Red' },
    { id: 'en0-me14', type: 'Memory', question: 'Listen & Do', instruction: 'Match command', answer: '', context: 'Listen:Listen|Repeat:Repeat|Jump:Jump|Sit:Sit|Look:Look|Stop:Stop' },
    { id: 'en0-me15', type: 'Memory', question: 'Household Items', instruction: 'Match items', answer: '', context: 'Bed:Bed|Cup:Cup|Spoon:Spoon|Key:Key|TV:TV|Phone:Phone' },
    { id: 'en0-me16', type: 'Memory', question: 'Weather (Simple)', instruction: 'Match weather', answer: '', context: 'Sun:Sun|Rain:Rain|Snow:Snow|Wind:Wind|Cloud:Cloud|Hot:Hot' },
    { id: 'en0-me17', type: 'Memory', question: 'Feelings (Simple)', instruction: 'Match feelings', answer: '', context: 'Happy:Happy|Sad:Sad|Angry:Angry|Sleepy:Sleepy|Funny:Funny|Nice:Nice' },
    { id: 'en0-me18', type: 'Memory', question: 'Food (Simple)', instruction: 'Match foods', answer: '', context: 'Milk:Milk|Water:Water|Bread:Bread|Egg:Egg|Cake:Cake|Rice:Rice' },
    { id: 'en0-me19', type: 'Memory', question: 'More Animals', instruction: 'Match animals', answer: '', context: 'Lion:Lion|Elephant:Elephant|Monkey:Monkey|Zebra:Zebra|Giraffe:Giraffe|Snake:Snake' },
    { id: 'en0-me20', type: 'Memory', question: 'My Room', instruction: 'Match items', answer: '', context: 'Bed:Bed|Desk:Desk|Lamp:Lamp|Toy:Toy|Book:Book|Poster:Poster' },
    { id: 'en0-me21', type: 'Memory', question: 'Body Sounds', instruction: 'Match action to sound', answer: '', context: 'Clap:Hands|Stomp:Feet|Snap:Fingers|Whistle:Mouth|Hum:Throat|Sneeze:Nose' },
    { id: 'en0-me22', type: 'Memory', question: 'Daily Routine (Short)', instruction: 'Match actions', answer: '', context: 'Wake:Sleep|Eat:Food|Play:Toys|Go:School|Wash:Water|Brush:Teeth' },
    { id: 'en0-me23', type: 'Memory', question: 'Colors & Fruit', instruction: 'Match color to fruit', answer: '', context: 'Red:Apple|Yellow:Banana|Orange:Orange|Green:Pear|Purple:Grape|Pink:Strawberry' },
    { id: 'en0-me24', type: 'Memory', question: 'Big & Small', instruction: 'Match opposites', answer: '', context: 'Big:Small|Tall:Short|Fast:Slow|Hot:Cold|Up:Down|In:Out' },
    { id: 'en0-me25', type: 'Memory', question: 'Garden things', instruction: 'Match words', answer: '', context: 'Bird:Bird|Bee:Bee|Grass:Grass|Flower:Flower|Tree:Tree|Ant:Ant' },
  ],
  1: [
    { id: 'en1-me1', type: 'Memory', question: 'Numbers (7-12)', instruction: 'Match numeral to word', answer: '', context: '7:Seven|8:Eight|9:Nine|10:Ten|11:Eleven|12:Twelve' },
    { id: 'en1-me2', type: 'Memory', question: 'Colors (Shades)', instruction: 'Match colors', answer: '', context: 'Pink:Pink|Brown:Brown|Grey:Grey|Black:Black|White:White|Light blue:Light blue' },
    { id: 'en1-me3', type: 'Memory', question: 'Farm Animals', instruction: 'Match farm animals', answer: '', context: 'Cow:Cow|Pig:Pig|Horse:Horse|Sheep:Sheep|Chicken:Chicken|Duck:Duck' },
    { id: 'en1-me4', type: 'Memory', question: 'Food', instruction: 'Match food items', answer: '', context: 'Bread:Bread|Cheese:Cheese|Milk:Milk|Egg:Egg|Cake:Cake|Ice cream:Ice cream' },
    { id: 'en1-me5', type: 'Memory', question: 'The House', instruction: 'Match house words', answer: '', context: 'Door:Door|Window:Window|Roof:Roof|Wall:Wall|Floor:Floor|Garden:Garden' },
    { id: 'en1-me6', type: 'Memory', question: 'Feelings', instruction: 'Match feelings', answer: '', context: 'Happy:Happy|Sad:Sad|Angry:Angry|Tired:Tired|Hungry:Hungry|Thirsty:Thirsty' },
    { id: 'en1-me7', type: 'Memory', question: 'Vehicles', instruction: 'Match vehicles', answer: '', context: 'Bus:Bus|Bike:Bike|Plane:Plane|Boat:Boat|Truck:Truck|Helicopter:Helicopter' },
    { id: 'en1-me8', type: 'Memory', question: 'Weather', instruction: 'Match weather', answer: '', context: 'Rain:Rain|Snow:Snow|Wind:Wind|Cloud:Cloud|Storm:Storm|Rainbow:Rainbow' },
    { id: 'en1-me9', type: 'Memory', question: 'Clothes', instruction: 'Match clothes', answer: '', context: 'Hat:Hat|T-shirt:T-shirt|Shoes:Shoes|Socks:Socks|Pants:Pants|Coat:Coat' },
    { id: 'en1-me10', type: 'Memory', question: 'Opposites', instruction: 'Match opposites', answer: '', context: 'Big:Small|Hot:Cold|Up:Down|In:Out|Fast:Slow|Long:Short' },
    { id: 'en1-me11', type: 'Memory', question: 'Numbers (13-18)', instruction: 'Match numeral to word', answer: '', context: '13:Thirteen|14:Fourteen|15:Fifteen|16:Sixteen|17:Seventeen|18:Eighteen' },
    { id: 'en1-me12', type: 'Memory', question: 'School Supplies', instruction: 'Match objects', answer: '', context: 'Ruler:Lineal|Eraser:Viskelæder|Glue:Lim|Scissors:Saks|Notebook:Notesbog|Pen:Pen' },
    { id: 'en1-me13', type: 'Memory', question: 'Daily Routine', instruction: 'Match actions', answer: '', context: 'Get up:Stå op|Wash face:Vaske ansigt|Brush teeth:Børste tænder|Get dressed:Tag tøj på|Go to school:Gå i skole|Study:Studere' },
    { id: 'en1-me14', type: 'Memory', question: 'Pets', instruction: 'Match pets', answer: '', context: 'Hamster:Hamster|Guinea pig:Marsvin|Parrot:Papegøje|Goldfish:Guldfisk|Turtle:Skildpadde|Pony:Pony' },
    { id: 'en1-me15', type: 'Memory', question: 'In the Town', instruction: 'Match places', answer: '', context: 'Shop:Butik|Park:Park|School:Skole|Hospital:Hospital|Bank:Bank|Street:Gade' },
    { id: 'en1-me16', type: 'Memory', question: 'Grammar: to be (I/You)', instruction: 'Match the phrases', answer: '', context: 'I am:Jeg er|You are:Du er|I am happy:Jeg er glad|You are tall:Du er høj|Am I?:Er jeg?|Are you?:Er du?' },
    { id: 'en1-me17', type: 'Memory', question: 'Grammar: it is', instruction: 'Match the phrases', answer: '', context: 'It is a dog:Det er en hund|It is a cat:Det er en kat|It is red:Det er rød|It is blue:Det er blå|What is it?:Hvad er det?|It is...:Det er...' },
    { id: 'en1-me18', type: 'Memory', question: 'Grammar: can/can\'t', instruction: 'Match the phrases', answer: '', context: 'I can jump:Jeg kan hoppe|I can\'t fly:Jeg kan ikke flyve|Can you?:Kan du?|Yes, I can:Ja, jeg kan|No, I can\'t:Nej, jeg kan ikke|He can run:Han kan løbe' },
    { id: 'en1-me19', type: 'Memory', question: 'Body Parts 2', instruction: 'Match body parts', answer: '', context: 'Ears:Ører|Hair:Hår|Neck:Hals|Shoulders:Skuldre|Arms:Arme|Legs:Ben' },
    { id: 'en1-me20', type: 'Memory', question: 'Food & Drink Mix', instruction: 'Match items', answer: '', context: 'Juice:Juice|Apple:Æble|Bread:Brød|Water:Vand|Milk:Mælk|Banana:Banan' },
    { id: 'en1-me21', type: 'Memory', question: 'Wild Animals', instruction: 'Match animals', answer: '', context: 'Lion:Løve|Tiger:Tiger|Elephant:Elefant|Giraffe:Giraf|Monkey:Abe|Zebra:Zebra' },
    { id: 'en1-me22', type: 'Memory', question: 'At Sea', instruction: 'Match words', answer: '', context: 'Ship:Skib|Boat:Båd|Water:Vand|Fish:Fisk|Island:Ø|Beach:Strand' },
    { id: 'en1-me23', type: 'Memory', question: 'Time of Day', instruction: 'Match words', answer: '', context: 'Morning:Morgen|Noon:Middag|Afternoon:Eftermiddag|Evening:Aften|Night:Nat|Day:Dag' },
    { id: 'en1-me24', type: 'Memory', question: 'Activity Mix', instruction: 'Match actions', answer: '', context: 'Write:Skrive|Read:Læse|Draw:Tegne|Paint:Male|Cook:Lave mad|Bake:Bage' },
    { id: 'en1-me25', type: 'Memory', question: 'Nature Mix', instruction: 'Match words', answer: '', context: 'Mountain:Bjerg|Lake:Sø|River:Flod|Forest:Skov|Field:Mark|Path:Sti' },
  ],
  2: [
    { id: 'en2-me1', type: 'Memory', question: 'Numbers (11-20)', instruction: 'Match numeral to word', answer: '', context: '11:Eleven|12:Twelve|13:Thirteen|14:Fourteen|15:Fifteen|20:Twenty' },
    { id: 'en2-me2', type: 'Memory', question: 'Body Parts', instruction: 'Match body parts', answer: '', context: 'Shoulder:Skulder|Elbow:Albue|Knee:Knæ|Ankle:Ankel|Head:Hoved|Back:Ryg' },
    { id: 'en2-me3', type: 'Memory', question: 'Family', instruction: 'Match relations', answer: '', context: 'Aunt:Tante|Uncle:Onkel|Cousin:Fætter/Kusine|Grandmother:Bedstemor|Grandfather:Bedstefar|Family:Familie' },
    { id: 'en2-me4', type: 'Memory', question: 'Breakfast', instruction: 'Match breakfast foods', answer: '', context: 'Cereal:Morgenmadsprodukt|Toast:Ristet brød|Jam:Syltetøj|Milk:Mælk|Honey:Honning|Butter:Smør' },
    { id: 'en2-me5', type: 'Memory', question: 'Holidays', instruction: 'Match holiday words', answer: '', context: 'Easter:Påske|Christmas:Jul|Halloween:Halloween|Santa:Julemand|Tree:Træ|Egg:Æg' },
    { id: 'en2-me6', type: 'Memory', question: 'Daily Actions', instruction: 'Match actions', answer: '', context: 'Wake up:Vågne op|Wash:Vaske|Eat:Spise|Go:Gå|Play:Lege|Sleep:Sove' },
    { id: 'en2-me7', type: 'Memory', question: 'Clothes', instruction: 'Match clothes', answer: '', context: 'Shirt:Skjorte|Hat:Hat|Shoes:Sko|Socks:Strømper|Pants:Bukser|Coat:Frakke' },
    { id: 'en2-me8', type: 'Memory', question: 'Colors', instruction: 'Match colors', answer: '', context: 'Pink:Lyserød|Brown:Brun|Grey:Grå|Black:Sort|White:Hvid|Orange:Orange' },
    { id: 'en2-me9', type: 'Memory', question: 'Pets', instruction: 'Match pets', answer: '', context: 'Dog:Hund|Cat:Kat|Hamster:Hamster|Rabbit:Kanin|Bird:Fugl|Fish:Fisk' },
    { id: 'en2-me10', type: 'Memory', question: 'Questions', instruction: 'Match questions', answer: '', context: 'Who:Hvem|What:Hvad|Where:Hvor|How:Hvordan|Why:Hvorfor|When:Hvornår' },
    { id: 'en2-me11', type: 'Memory', question: 'Days of the week', instruction: 'Match words', answer: '', context: 'Monday:Mandag|Tuesday:Tirsdag|Wednesday:Onsdag|Thursday:Torsdag|Friday:Fredag|Saturday:Lørdag' },
    { id: 'en2-me12', type: 'Memory', question: 'Months of the year', instruction: 'Match words', answer: '', context: 'January:Januar|February:Februar|March:Marts|April:April|May:Maj|June:Juni' },
    { id: 'en2-me13', type: 'Memory', question: 'Seasons', instruction: 'Match words', answer: '', context: 'Spring:Forår|Summer:Sommer|Autumn:Efterår|Winter:Vinter|Sun:Sol|Rain:Regn' },
    { id: 'en2-me14', type: 'Memory', question: 'School Objects 2', instruction: 'Match words', answer: '', context: 'Pencil:Blyant|Book:Bog|Notebook:Hæfte|Bag:Taske|Teacher:Lærer|School:Skole' },
    { id: 'en2-me15', type: 'Memory', question: 'Transport', instruction: 'Match words', answer: '', context: 'Car:Bil|Bike:Cykel|Bus:Bus|Train:Tog|Plane:Fly|Boat:Skib' },
    { id: 'en2-me16', type: 'Memory', question: 'Fruits 2', instruction: 'Match words', answer: '', context: 'Strawberry:Jordbær|Lemon:Citron|Cherry:Kirsebær|Watermelon:Vandmelon|Peach:Fersken|Plum:Blomme' },
    { id: 'en2-me17', type: 'Memory', question: 'Vegetables', instruction: 'Match words', answer: '', context: 'Tomato:Tomat|Carrot:Gulerod|Potato:Kartoffel|Onion:Løg|Lettuce:Salat|Cucumber:Agurk' },
    { id: 'en2-me18', type: 'Memory', question: 'Classroom Actions', instruction: 'Match words', answer: '', context: 'Read:Læse|Write:Skrive|Draw:Tegne|Listen:Lytte|Speak:Tale|Sing:Synge' },
    { id: 'en2-me19', type: 'Memory', question: 'In the House', instruction: 'Match words', answer: '', context: 'House:Hus|Door:Dør|Window:Vindue|Chair:Stol|Table:Bord|Bed:Seng' },
    { id: 'en2-me20', type: 'Memory', question: 'Drinks', instruction: 'Match words', answer: '', context: 'Water:Vand|Milk:Mælk|Juice:Juice|Soda:Sodavand|Milkshake:Milkshake|Tea:Te' },
    { id: 'en2-me21', type: 'Memory', question: 'Nature', instruction: 'Match words', answer: '', context: 'Tree:Træ|Flower:Blomst|Grass:Græs|Mountain:Bjerg|River:Flod|Sea:Hav' },
    { id: 'en2-me22', type: 'Memory', question: 'Weather 2', instruction: 'Match words', answer: '', context: 'Sun:Sol|Clouds:Skyer|Wind:Vind|Snow:Sne|Thunder:Torden|Fog:Tåge' },
    { id: 'en2-me23', type: 'Memory', question: 'Instruments', instruction: 'Match words', answer: '', context: 'Guitar:Guitar|Piano:Klaver|Drum:Tromme|Flute:Fløjte|Violin:Violin|Trumpet:Trompet' },
    { id: 'en2-me24', type: 'Memory', question: 'Sports', instruction: 'Match words', answer: '', context: 'Football:Fodbold|Basketball:Basketball|Tenis:Tennis|Swimming:Svømning|Running:Løbe|Jumping:Hoppe' },
    { id: 'en2-me25', type: 'Memory', question: 'Wild Animals', instruction: 'Match words', answer: '', context: 'Lion:Løve|Elephant:Elefant|Monkey:Abe|Giraffe:Giraf|Tiger:Tiger|Snake:Slange' },
    { id: 'en2-me26', type: 'Memory', question: 'Sea Animals', instruction: 'Match words', answer: '', context: 'Dolphin:Delfin|Shark:Haj|Whale:Hval|Octopus:Blæksprutte|Crab:Krabbe|Jellyfish:Vandmand' },
    { id: 'en2-me27', type: 'Memory', question: 'In the Town 2', instruction: 'Match words', answer: '', context: 'Street:Gade|Park:Park|Shop:Butik|Cinema:Biograf|Hospital:Hospital|Bank:Bank' },
    { id: 'en2-me28', type: 'Memory', question: 'Prepositions', instruction: 'Match words', answer: '', context: 'On:På|Under:Under|In:I|In front of:Foran|Behind:Bag|Next to:Ved siden af' },
    { id: 'en2-me29', type: 'Memory', question: 'Adjectives', instruction: 'Match words', answer: '', context: 'Big:Stor|Small:Lille|Tall:Høj|Short:Lav|Fast:Hurtig|Slow:Langsom' },
    { id: 'en2-me30', type: 'Memory', question: 'In the Bathroom', instruction: 'Match words', answer: '', context: 'Soap:Sæbe|Towal:Håndklæde|Brush:Børste|Mirror:Spejl|Water:Vand|Paper:Papir' },
    { id: 'en2-me31', type: 'Memory', question: 'In the Kitchen', instruction: 'Match words', answer: '', context: 'Plate:Tallerken|Glass:Glas|Spoon:Ske|Knife:Kniv|Fork:Gaffel|Pot:Gryde' },
    { id: 'en2-me32', type: 'Memory', question: 'Clothes 2', instruction: 'Match words', answer: '', context: 'Skirt:Nederdel|Dress:Kjole|Jacket:Jakke|Hat:Hue|Gloves:Vanter|Scarf:Tørklæde' },
    { id: 'en2-me33', type: 'Memory', question: 'Shapes', instruction: 'Match words', answer: '', context: 'Circle:Cirkel|Square:Kvadrat|Triangle:Trekant|Star:Stjerne|Heart:Hjerte|Rectangle:Rektangel' },
    { id: 'en2-me34', type: 'Memory', question: 'Opposites 2', instruction: 'Match words', answer: '', context: 'Hot:Varm|Cold:Kold|Open:Åben|Closed:Lukket|Clean:Ren|Dirty:Beskidt' },
    { id: 'en2-me35', type: 'Memory', question: 'Jobs', instruction: 'Match words', answer: '', context: 'Doctor:Læge|Police:Politi|Fireman:Brandmand|Pilot:Pilot|Cook:Kok|Dentist:Tandlæge' },
    { id: 'en2-me36', type: 'Memory', question: 'Insects', instruction: 'Match words', answer: '', context: 'Butterfly:Sommerfugl|Bee:Bi|Ant:Myre|Spider:Edderkop|Fly:Flue|Ladybug:Mariehøne' },
    { id: 'en2-me37', type: 'Memory', question: 'Furniture', instruction: 'Match words', answer: '', context: 'Armchair:Lænestol|Shelf:Reol|Wardrobe:Skab|Carpet:Tæppe|Lamp:Lampe|Clock:Ur' },
    { id: 'en2-me38', type: 'Memory', question: 'Feelings 2', instruction: 'Match words', answer: '', context: 'Surprised:Overrasket|Bored:Ked af det|Proud:Stolt|Shy:Genert|Excited:Spændt|Calm:Rolig' },
    { id: 'en2-me39', type: 'Memory', question: 'Common Verbs', instruction: 'Match words', answer: '', context: 'Give:Give|Have:Have|Do:Gøre|Come:Komme|Know:Vide|Put:Sætte' },
    { id: 'en2-me40', type: 'Memory', question: 'Body - face', instruction: 'Match words', answer: '', context: 'Eye:Øje|Ear:Øre|Nose:Næse|Mouth:Mund|Tooth:Tand|Hair:Hår' },
    { id: 'en2-me41', type: 'Memory', question: 'Numbers 30-80', instruction: 'Match words', answer: '', context: 'Thirty:30|Forty:40|Fifty:50|Sixty:60|Seventy:70|Eighty:80' },
    { id: 'en2-me42', type: 'Memory', question: 'Personality', instruction: 'Match words', answer: '', context: 'Kind:Sød|Brave:Modig|Smart:Klog|Funny:Sjov|Good:God|Nice:Flink' },
    { id: 'en2-me43', type: 'Memory', question: 'On the Farm', instruction: 'Match words', answer: '', context: 'Cow:Ko|Pig:Gris|Sheep:Får|Duck:And|Hen:Høne|Tractor:Traktor' },
    { id: 'en2-me44', type: 'Memory', question: 'Rooms', instruction: 'Match words', answer: '', context: 'Kitchen:Køkken|Living room:Stue|Bathroom:Badeværelse|Bedroom:Soveværelse|Hall:Gang|Garage:Garage' },
    { id: 'en2-me45', type: 'Memory', question: 'Toys 2', instruction: 'Match words', answer: '', context: 'Ball:Bold|Doll:Dukke|Car:Bil|Puzzle:Puslespil|Teddy:Bamse|Kite:Drage' },
    { id: 'en2-me46', type: 'Memory', question: 'Food 2', instruction: 'Match words', answer: '', context: 'Egg:Æg|Cheese:Ost|Chicken:Kylling|Rice:Ris|Pasta:Pasta|Salad:Salat' },
    { id: 'en2-me47', type: 'Memory', question: 'Events', instruction: 'Match words', answer: '', context: 'Party:Fest|Birthday:Fødselsdag|Wedding:Bryllup|Concert:Koncert|Dinner:Middag|Trip:Rejse' },
    { id: 'en2-me48', type: 'Memory', question: 'Tools', instruction: 'Match words', answer: '', context: 'Hammer:Hammer|Saw:Sav|Wrench:Nøgle|Screwdriver:Skruetrækker|Nail:Søm|Scissors:Saks' },
    { id: 'en2-me49', type: 'Memory', question: 'Space', instruction: 'Match words', answer: '', context: 'Moon:Måne|Star:Stjerne|Planet:Planet|Sun:Sol|Earth:Jorden|Rocket:Raket' },
    { id: 'en2-me50', type: 'Memory', question: 'Mix final Grade 2 English', instruction: 'Match words', answer: '', context: 'Hello:Hej|Goodbye:Farvel|Thanks:Tak|Sorry:Undskyld|Yes:Ja|No:Nej' },
  ]
};

