/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const FRANSK_MEMORY: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'fr0-me1', type: 'Memory', question: 'Nombres (1-6)', instruction: 'Trouvez les paires', answer: '', context: '1:Un|2:Deux|3:Trois|4:Quatre|5:Cinq|6:Six' },
    { id: 'fr0-me2', type: 'Memory', question: 'Couleurs', instruction: 'Trouvez les paires', answer: '', context: 'Rouge:Rouge|Bleu:Bleu|Jaune:Jaune|Vert:Vert|Noir:Noir|Blanc:Blanc' },
    { id: 'fr0-me3', type: 'Memory', question: 'Animaux', instruction: 'Trouvez les paires', answer: '', context: 'Chien:Chien|Chat:Chat|Oiseau:Oiseau|Cheval:Cheval|Poisson:Poisson|Souris:Souris' },
    { id: 'fr0-me4', type: 'Memory', question: 'Famille', instruction: 'Trouvez les paires', answer: '', context: 'Mère:Mère|Père:Père|Sœur:Sœur|Frère:Frère|Grand-mère:Grand-mère|Grand-père:Grand-père' },
    { id: 'fr0-me5', type: 'Memory', question: 'Corps', instruction: 'Trouvez les paires', answer: '', context: 'Tête:Tête|Main:Main|Pied:Pied|Œil:Œil|Nez:Nez|Bouche:Bouche' },
    { id: 'fr0-me6', type: 'Memory', question: 'Manger', instruction: 'Trouvez les paires', answer: '', context: 'Pain:Pain|Pomme:Pomme|Lait:Lait|Eau:Eau|Gâteau:Gâteau|Fromage:Fromage' },
  ],
  1: [
    { id: 'fr1-me1', type: 'Memory', question: 'Nombres (7-12)', instruction: 'Trouvez les paires', answer: '', context: '7:Sept|8:Huit|9:Neuf|10:Dix|11:Onze|12:Douze' },
    { id: 'fr1-me2', type: 'Memory', question: 'École', instruction: 'Trouvez les paires', answer: '', context: 'Livre:Livre|Stylo:Stylo|Table:Table|Chaise:Chaise|École:École|Professeur:Professeur' },
    { id: 'fr1-me3', type: 'Memory', question: 'Sentiments', instruction: 'Trouvez les paires', answer: '', context: 'Heureux:Heureux|Triste:Triste|Fatigué:Fatigué|Affamé:Affamé|Assoiffé:Assoiffé|Fâché:Fâché' },
    { id: 'fr1-me4', type: 'Memory', question: 'Maison', instruction: 'Trouvez les paires', answer: '', context: 'Maison:Maison|Porte:Porte|Fenêtre:Fenêtre|Lit:Lit|Cuisine:Cuisine|Jardin:Jardin' },
    { id: 'fr1-me5', type: 'Memory', question: 'Nature', instruction: 'Trouvez les paires', answer: '', context: 'Soleil:Soleil|Lune:Lune|Étoile:Étoile|Arbre:Arbre|Fleur:Fleur|Pluie:Pluie' },
  ],
  2: [
    { id: 'fr2-me1', type: 'Memory', question: 'Nombres (11-20)', instruction: 'Trouvez les paires', answer: '', context: '11:Onze|12:Douze|13:Treize|14:Quatorze|15:Quinze|20:Vingt' },
    { id: 'fr2-me2', type: 'Memory', question: 'Le corps', instruction: 'Trouvez les paires', answer: '', context: 'Épaule:Skulder|Coude:Albue|Genou:Knæ|Cheville:Ankel|Tête:Hoved|Dos:Ryg' },
    { id: 'fr2-me3', type: 'Memory', question: 'La famille', instruction: 'Trouvez les paires', answer: '', context: 'Tante:Tante|Oncle:Onkel|Cousin:Fætter/Kusine|Grand-mère:Bedstemor|Grand-père:Bedstefar|Famille:Familie' },
    { id: 'fr2-me4', type: 'Memory', question: 'Le petit déjeuner', instruction: 'Trouvez les paires', answer: '', context: 'Céréales:Morgenmadsprodukt|Toast:Ristet brød|Confiture:Syltetøj|Lait:Mælk|Miel:Honning|Beurre:Smør' },
    { id: 'fr2-me5', type: 'Memory', question: 'Højtider', instruction: 'Trouvez les paires', answer: '', context: 'Pâques:Påske|Noël:Jul|Halloween:Halloween|Père Noël:Julemand|Sapin:Grantræ|Œuf:Æg' },
    { id: 'fr2-me6', type: 'Memory', question: 'Actions quotidiennes', instruction: 'Trouvez les paires', answer: '', context: 'Se réveiller:Vågne op|Se laver:Vaske sig|Manger:Spise|Aller:Gå|Jouer:Lege|Dormir:Sove' },
    { id: 'fr2-me7', type: 'Memory', question: 'Vêtements', instruction: 'Trouvez les paires', answer: '', context: 'Chemise:Skjorte|Chapeau:Hat|Chaussures:Sko|Chaussettes:Strømper|Pantalon:Bukser|Manteau:Frakke' },
    { id: 'fr2-me8', type: 'Memory', question: 'Couleurs', instruction: 'Trouvez les paires', answer: '', context: 'Rose:Lyserød|Marron:Brun|Gris:Grå|Noir:Sort|Blanc:Hvid|Orange:Orange' },
    { id: 'fr2-me9', type: 'Memory', question: 'Animaux domestiques', instruction: 'Trouvez les paires', answer: '', context: 'Chien:Hund|Chat:Kat|Hamster:Hamster|Lapin:Kanin|Oiseau:Fugl|Poisson:Fisk' },
    { id: 'fr2-me10', type: 'Memory', question: 'Questions', instruction: 'Trouvez les paires', answer: '', context: 'Qui:Hvem|Quoi:Hvad|Où:Hvor|Comment:Hvordan|Pourquoi:Hvorfor|Quand:Hvornår' },
    { id: 'fr2-me11', type: 'Memory', question: 'Instruments de musique', instruction: 'Trouvez les paires', answer: '', context: 'Piano:Klaver|Guitare:Guitar|Violon:Violin|Flûte:Fløjte|Tambour:Tromme|Trompette:Trompet' },
    { id: 'fr2-me12', type: 'Memory', question: 'Dans la salle de classe', instruction: 'Trouvez les paires', answer: '', context: 'Tableau:Tavle|Craie:Kridt|Cahier:Hæfte|Gomme:Viskelæder|Règle:Lineal|Sac:Taske' },
    { id: 'fr2-me13', type: 'Memory', question: 'Le calendrier', instruction: 'Trouvez les paires', answer: '', context: 'Lundi:Mandag|Mardi:Tirsdag|Mercredi:Onsdag|Jeudi:Torsdag|Vendredi:Fredag|Samedi:Lørdag' },
    { id: 'fr2-me14', type: 'Memory', question: 'Les mois', instruction: 'Trouvez les paires', answer: '', context: 'Janvier:Januar|Février:Februar|Mars:Marts|Avril:April|Mai:Maj|Juin:Juni' },
    { id: 'fr2-me15', type: 'Memory', question: 'Les fruits', instruction: 'Trouvez les paires', answer: '', context: 'Orange:Appelsin|Citron:Citron|Fraise:Jordbær|Cerise:Kirsebær|Raisin:Vi|Abricot:Abrikos' },
    { id: 'fr2-me16', type: 'Memory', question: 'Les légumes', instruction: 'Trouvez les paires', answer: '', context: 'Carotte:Gulerod|Pomme de terre:Kartoffel|Tomate:Tomat|Salade:Salat|Oignon:Løg|Ail:Hvidløg' },
    { id: 'fr2-me17', type: 'Memory', question: 'Transport', instruction: 'Trouvez les paires', answer: '', context: 'Voiture:Bil|Velo:Cykel|Train:Tog|Avion:Fly|Bateau:Skib|Bus:Bus' },
    { id: 'fr2-me18', type: 'Memory', question: 'Au parc', instruction: 'Trouvez les paires', answer: '', context: 'Banc:Bænk|Arbre:Træ|Herbe:Græs|Lac:Sø|Oiseau:Fugl|Fleur:Blomst' },
    { id: 'fr2-me19', type: 'Memory', question: 'Adjectifs', instruction: 'Trouvez les paires', answer: '', context: 'Petit:Lille|Grand:Stor|Rapide:Hurtig|Lent:Langsom|Fort:Stærk|Faible:Svag' },
    { id: 'fr2-me20', type: 'Memory', question: 'Météo', instruction: 'Trouvez les paires', answer: '', context: 'Soleil:Sol|Pluie:Regn|Neige:Sne|Orage:Torden|Vent:Vind|Nuage:Sky' },
    { id: 'fr2-me21', type: 'Memory', question: 'Verbes d\'action', instruction: 'Trouvez les paires', answer: '', context: 'Sauter:Hoppe|Courir:Løbe|Marcher:Gå|Nager:Svømme|Lire:Læse|Écrire:Skrive' },
    { id: 'fr2-me22', type: 'Memory', question: 'Objets du salon', instruction: 'Trouvez les paires', answer: '', context: 'Canapé:Sofa|Télévision:Fjernsyn|Tapis:Tæppe|Lampe:Lampe|Rideaux:Gardiner|Étagère:Hylde' },
    { id: 'fr2-me23', type: 'Memory', question: 'La salle de bain', instruction: 'Trouvez les paires', answer: '', context: 'Savon:Sæbe|Serviette:Håndklæde|Douche:Brusebad|Baignoire:Badekar|Miroir:Spejl|Peigne:Kam' },
    { id: 'fr2-me24', type: 'Memory', question: 'Le corps (visage)', instruction: 'Trouvez les paires', answer: '', context: 'Nez:Næse|Yeux:Øjne|Oreilles:Ører|Bouche:Mund|Cheveux:Hår|Dents:Tænder' },
    { id: 'fr2-me25', type: 'Memory', question: 'Les vêtements d\'hiver', instruction: 'Trouvez les paires', answer: '', context: 'Manteau:Frakke|Écharpe:Halstørklæde|Gants:Vanter|Bonnet:Hue|Bottes:Støvler|Pull:Trøje' },
    { id: 'fr2-me26', type: 'Memory', question: 'Les insectes', instruction: 'Trouvez les paires', answer: '', context: 'Abeille:Bi|Papillon:Sommerfugl|Fourmi:Myre|Araignée:Edderkop|Mouche:Flue|Coccinelle:Mariehøne' },
    { id: 'fr2-me27', type: 'Memory', question: 'La plage', instruction: 'Trouvez les paires', answer: '', context: 'Sable:Sand|Mer:Hav|Coquillage:Muslingeskal|Crabe:Krabbe|Soleil:Sol|Parasol:Parasol' },
    { id: 'fr2-me28', type: 'Memory', question: 'Les émotions', instruction: 'Trouvez les paires', answer: '', context: 'Joie:Glæde|Tristesse:Sorg|Colère:Vrede|Peur:Frygt|Surprise:Overraskelse|Calme:Rolig' },
    { id: 'fr2-me29', type: 'Memory', question: 'La cuisine (ustensiles)', instruction: 'Trouvez les paires', answer: '', context: 'Cuillère:Ske|Fourchette:Gaffel|Couteau:Kniv|Assiette:Tallerken|Verre:Glas|Poêle:Pande' },
    { id: 'fr2-me30', type: 'Memory', question: 'Les jouets', instruction: 'Trouvez les paires', answer: '', context: 'Ballon:Bold|Poupée:Dukke|Voiture:Bil|Train:Tog|Robot:Robot|Blocs:Klodser' },
    { id: 'fr2-me31', type: 'Memory', question: 'Nombres (20-30)', instruction: 'Trouvez les paires', answer: '', context: 'Vingt-et-un:21|Vingt-deux:22|Vingt-trois:23|Vingt-quatre:24|Vingt-cinq:25|Trente:30' },
    { id: 'fr2-me32', type: 'Memory', question: 'Les métiers', instruction: 'Trouvez les paires', answer: '', context: 'Médecin:Læge|Pompier:Brandmand|Policier:Politibetjent|Enseignant:Lærer|Boulanger:Bager|Chef:Kok' },
    { id: 'fr2-me33', type: 'Memory', question: 'Les boissons', instruction: 'Trouvez les paires', answer: '', context: 'Eau:Vand|Lait:Mælk|Jus:Juice|Thé:Te|Café:Kaffe|Chocolat:Chokolade' },
    { id: 'fr2-me34', type: 'Memory', question: 'Dans la forêt', instruction: 'Trouvez les paires', answer: '', context: 'Loup:Ulv|Ours:Bjørn|Renard:Ræv|Écureuil:Egern|Cerf:Hjort|Hibou:Ugle' },
    { id: 'fr2-me35', type: 'Memory', question: 'Les formes', instruction: 'Trouvez les paires', answer: '', context: 'Cercle:Cirkel|Carré:Kvadrat|Triangle:Trekant|Rectangle:Rektangel|Étoile:Stjerne|Cœur:Hjerte' },
    { id: 'fr2-me36', type: 'Memory', question: 'Le jardin', instruction: 'Trouvez les paires', answer: '', context: 'Pelle:Skovl|Râteau:Rive|Arrosoir:Vandkande|Fleur:Blomst|Herbe:Græs|Terre:Jord' },
    { id: 'fr2-me37', type: 'Memory', question: 'Supermarché', instruction: 'Trouvez les paires', answer: '', context: 'Panier:Kurv|Chariot:Vogn|Caisse:Kasse|Client:Kunde|Rayon:Hylde|Produit:Produkt' },
    { id: 'fr2-me38', type: 'Memory', question: 'La nuit', instruction: 'Trouvez les paires', answer: '', context: 'Lune:Måne|Étoiles:Stjerner|Sommeil:Søvn|Rêve:Drøm|Pyjama:Pyjamas|Lit:Seng' },
    { id: 'fr2-me39', type: 'Memory', question: 'La ferme', instruction: 'Trouvez les paires', answer: '', context: 'Vache:Ko|Cochon:Gris|Poule:Høne|Mouton:Får|Chèvre:Ged|Canard:And' },
    { id: 'fr2-me40', type: 'Memory', question: 'Fêtes', instruction: 'Trouvez les paires', answer: '', context: 'Noël:Jul|Pâques:Påske|Anniversaire:Fødselsdag|Cadeau:Gave|Gâteau:Kage|Bougie:Lys' },
    { id: 'fr2-me41', type: 'Memory', question: 'L\'espace', instruction: 'Trouvez les paires', answer: '', context: 'Planète:Planet|Fusée:Raket|Astronaute:Astronaut|Soleil:Sol|Comète:Komet|Terre:Jord' },
    { id: 'fr2-me42', type: 'Memory', question: 'Sports d\'équipe', instruction: 'Trouvez les paires', answer: '', context: 'Football:Fodbold|Basketball:Basketball|Volleyball:Volleyball|Handball:Håndbold|Rugby:Rugby|Hockey:Hockey' },
    { id: 'fr2-me43', type: 'Memory', question: 'Instruments à vent', instruction: 'Trouvez les paires', answer: '', context: 'Flûte:Fløjte|Clarinette:Klarinet|Saxophone:Saxofon|Trompette:Trompet|Hautbois:Obo|Basson:Fagot' },
    { id: 'fr2-me44', type: 'Memory', question: 'Dans la rue', instruction: 'Trouvez les paires', answer: '', context: 'Trottoir:Fortov|Passage piéton:Fodgængerfelt|Feu:Lysregulering|Voiture:Bil|Vélo:Cykel|Maison:Hus' },
    { id: 'fr2-me45', type: 'Memory', question: 'Au zoo', instruction: 'Trouvez les paires', answer: '', context: 'Girafe:Giraf|Éléphant:Elefant|Lion:Løve|Zèbre:Zebra|Singe:Abe|Serpent:Slange' },
    { id: 'fr2-me46', type: 'Memory', question: 'Hygiène', instruction: 'Trouvez les paires', answer: '', context: 'Brosser:Børste|Laver:Vaske|Douche:Bad|Dents:Tænder|Main:Hånd|Savon:Sæbe' },
    { id: 'fr2-me47', type: 'Memory', question: 'Petit déjeuner (boisson)', instruction: 'Trouvez les paires', answer: '', context: 'Chocolat chaud:Varm kakao|Café:Kaffe|Thé:Te|Lait:Mælk|Jus d\'orange:Appelsinjuice|Eau:Vand' },
    { id: 'fr2-me48', type: 'Memory', question: 'Vêtements d\'été', instruction: 'Trouvez les paires', answer: '', context: 'Short:Shorts|Maillot:Badedragt|Lunettes:Briller|Chapeau:Hat|Tong:Klip-klapper|Sandales:Sandaler' },
    { id: 'fr2-me49', type: 'Memory', question: 'La salle de classe (mobilier)', instruction: 'Trouvez les paires', answer: '', context: 'Table:Bord|Chaise:Stol|Bureau:Skrivebord|Étagère:Hylde|Tableau:Tavle|Placard:Skab' },
    { id: 'fr2-me50', type: 'Memory', question: 'Adjectifs de couleur', instruction: 'Trouvez les paires', answer: '', context: 'Rouge:Rød|Bleu:Blå|Vert:Grøn|Jaune:Gul|Noir:Sort|Blanc:Hvid' },
  ],
  10: [
    { id: 'fr10-me1', type: 'Memory', question: 'La littérature', instruction: 'Trouvez les paires', answer: '', context: 'Roman:Roman|Poésie:Poesi|Théâtre:Teater|Essai:Essay|Auteur:Forfatter|Lecture:Læsning' },
    { id: 'fr10-me2', type: 'Memory', question: 'La politique', instruction: 'Trouvez les paires', answer: '', context: 'Démocratie:Demokrati|République:Republik|Élection:Valg|Liberté:Frihed|Égalité:Lighed|Fraternité:Broderskab' },
    { id: 'fr10-me3', type: 'Memory', question: 'L\'environnement', instruction: 'Trouvez les paires', answer: '', context: 'Pollution:Forurening|Énergie:Energi|Climat:Klima|Planète:Planet|Nature:Natur|Protection:Beskyttelse' },
    { id: 'fr10-me4', type: 'Memory', question: 'La technologie', instruction: 'Trouvez les paires', answer: '', context: 'Internet:Internet|Ordinateur:Computer|Science:Videnskab|Futur:Fremtid|Robot:Robot|Données:Data' },
    { id: 'fr10-me5', type: 'Memory', question: 'L\'art', instruction: 'Trouvez les paires', answer: '', context: 'Peinture:Maleri|Sculpture:Skulptur|Musée:Museum|Galerie:Galleri|Artiste:Kunstner|Chef-d\'œuvre:Mesterværk' },
    { id: 'fr10-me6', type: 'Memory', question: 'La philosophie', instruction: 'Trouvez les paires', answer: '', context: 'Raison:Fornuft|Morale:Moral|Éthique:Etik|Pensée:Tanke|Existence:Eksistens|Vérité:Sandhed' },
    { id: 'fr10-me7', type: 'Memory', question: 'L\'économie', instruction: 'Trouvez les paires', answer: '', context: 'Marché:Marked|Argent:Penge|Banque:Bank|Investissement:Investering|Profit:Overskud|Crise:Krise' },
    { id: 'fr10-me8', type: 'Memory', question: 'La société', instruction: 'Trouvez les paires', answer: '', context: 'Citoyen:Borger|Culture:Kultur|Tradition:Tradition|Éducation:Uddannelse|Famille:Familie|Travail:Arbejde' },
    { id: 'fr10-me9', type: 'Memory', question: 'Les médias', instruction: 'Trouvez les paires', answer: '', context: 'Journal:Avis|Presse:Presse|Information:Information|Publicité:Reklame|Radio:Radio|Télévision:TV' },
    { id: 'fr10-me10', type: 'Memory', question: 'Le monde francophone', instruction: 'Trouvez les paires', answer: '', context: 'France:Frankrig|Québec:Québec|Belgique:Belgien|Suisse:Schweiz|Afrique:Afrika|Algérie:Algeriet' },
    { id: 'fr10-me11', type: 'Memory', question: 'La justice', instruction: 'Trouvez les paires', answer: '', context: 'Loi:Lov|Droit:Ret|Juge:Dommer|Tribunal:Retssal|Verdict:Dom|Peine:Straf' },
    { id: 'fr10-me12', type: 'Memory', question: 'Les sciences', instruction: 'Trouvez les paires', answer: '', context: 'Biologie:Biologi|Chimie:Kemi|Physique:Fysik|Maths:Matematik|Recherche:Forskning|Laboratoire:Laboratorium' },
    { id: 'fr10-me13', type: 'Memory', question: 'L\'histoire', instruction: 'Trouvez les paires', answer: '', context: 'Passé:Fortid|Révolution:Revolution|Guerre:Krig|Paix:Fred|Ancêtre:Forfader|Siècle:Århundrede' },
    { id: 'fr10-me14', type: 'Memory', question: 'La santé', instruction: 'Trouvez les paires', answer: '', context: 'Hôpital:Hospital|Maladie:Sygdom|Médecin:Læge|Remède:Kur|Vaccin:Vaccine|Sport:Sport' },
    { id: 'fr10-me15', type: 'Memory', question: 'Le voyage', instruction: 'Trouvez les paires', answer: '', context: 'Destination:Destination|Bagages:Bagage|Hôtel:Hotel|Vol:Flyvning|Aventure:Eventyr|Tourisme:Turisme' },
    { id: 'fr10-me16', type: 'Memory', question: 'La psychologie', instruction: 'Trouvez les paires', answer: '', context: 'Esprit:Sind|Sentiment:Følelse|Comportement:Adfærd|Inconscient:Underbevidst|Rêve:Drøm|Mémoire:Hukommelse' },
    { id: 'fr10-me17', type: 'Memory', question: 'Le théâtre', instruction: 'Trouvez les paires', answer: '', context: 'Scène:Scene|Acteur:Skuespiller|Spectacle:Forestilling|Drame:Drama|Comédie:Komedie|Rideau:Tæppe' },
    { id: 'fr10-me18', type: 'Memory', question: 'La poésie', instruction: 'Trouvez les paires', answer: '', context: 'Rime:Rim|Vers:Vers|Strophe:Strofe|Image:Billede|Rythme:Rytme|Sentiment:Følelse' },
    { id: 'fr10-me19', type: 'Memory', question: 'L\'identité', instruction: 'Trouvez les paires', answer: '', context: 'Origine:Oprindelse|Racine:Rod|Valeur:Værdi|Choix:Valg|Futur:Fremtid|Soi-même:Sig selv' },
    { id: 'fr10-me20', type: 'Memory', question: 'Le cinéma', instruction: 'Trouvez les paires', answer: '', context: 'Réalisateur:Instruktør|Film:Film|Écran:Skærm|Caméra:Kamera|Acteur:Skuespiller|Scénario:Manuskript' },
    { id: 'fr10-me21', type: 'Memory', question: 'La mode', instruction: 'Trouvez les paires', answer: '', context: 'Style:Stil|Marque:Mærke|Vêtement:Tøj|Défilé:Show|Créateur:Designer|Tendance:Tendens' },
    { id: 'fr10-me22', type: 'Memory', question: 'Le travail (futur)', instruction: 'Trouvez les paires', answer: '', context: 'Carrière:Karriere|Emploi:Job|Salaire:Løn|Réunion:Møde|Bureau:Kontor|Projet:Projekt' },
    { id: 'fr10-me23', type: 'Memory', question: 'La mondialisation', instruction: 'Trouvez les paires', answer: '', context: 'Global:Global|Échange:Udveksling|Frontière:Grænse|Commerce:Handel|Transport:Transport|Internet:Internet' },
    { id: 'fr10-me24', type: 'Memory', question: 'Les droits humains', instruction: 'Trouvez les paires', answer: '', context: 'Dignité:Værdighed|Liberté:Frihed|Justice:Retfærdighed|Égalité:Lighed|Respect:Respekt|Solidarité:Solidaritet' },
    { id: 'fr10-me25', type: 'Memory', question: 'La biodiversité', instruction: 'Trouvez les paires', answer: '', context: 'Espèce:Art|Forêt:Skov|Océan:Hav|Espace:Rum|Protection:Beskyttelse|Survie:Overlevelse' },
    { id: 'fr10-me26', type: 'Memory', question: 'L\'espace (univers)', instruction: 'Trouvez les paires', answer: '', context: 'Galaxie:Galakse|Étoile:Stjerne|Planète:Planet|Univers:Univers|Télescope:Teleskop|Fusée:Raket' },
    { id: 'fr10-me27', type: 'Memory', question: 'La gastronomie', instruction: 'Trouvez les paires', answer: '', context: 'Cuisine:Køkken|Saveur:Smag|Recette:Opskrift|Chef:Kok|Restaurant:Restaurant|Menu:Menu' },
    { id: 'fr10-me28', type: 'Memory', question: 'Les conflits', instruction: 'Trouvez les paires', answer: '', context: 'Guerre:Krig|Paix:Fred|Armée:Hær|Arme:Våben|Bataille:Slag|Victoire:Sejr' },
    { id: 'fr10-me29', type: 'Memory', question: 'Le sport de haut niveau', instruction: 'Trouvez les paires', answer: '', context: 'Champion:Mester|Entraînement:Træning|Compétition:Konkurrence|Médaille:Medalje|Équipe:Hold|Stade:Stadion' },
    { id: 'fr10-me30', type: 'Memory', question: 'L\'éducation', instruction: 'Trouvez les paires', answer: '', context: 'Apprentissage:Læring|École:Skole|Université:Universitet|Diplôme:Diplom|Étude:Studie|Livre:Bog' },
    { id: 'fr10-me31', type: 'Memory', question: 'Les changements sociaux', instruction: 'Trouvez les paires', answer: '', context: 'Évolution:Udvikling|Mouvement:Bevægelse|Progrès:Fremskridt|Changement:Ændring|Modernité:Modernitet|Avenir:Fremtid' },
    { id: 'fr10-me32', type: 'Memory', question: 'La communication', instruction: 'Trouvez les paires', answer: '', context: 'Langue:Sprog|Dialogue:Dialog|Écoute:Lytning|Message:Besked|Savoir:Viden|Partage:Deling' },
    { id: 'fr10-me33', type: 'Memory', question: 'Les ressources naturelles', instruction: 'Trouvez les paires', answer: '', context: 'Pétrole:Olie|Eau:Vand|Soleil:Sol|Vent:Vind|Or:Guld|Forêt:Skov' },
    { id: 'fr10-me34', type: 'Memory', question: 'La géographie', instruction: 'Trouvez les paires', answer: '', context: 'Montagne:Bjerg|Fleuve:Flod|Désert:Ørken|Continent:Kontinent|Pays:Land|Frontière:Grænse' },
    { id: 'fr10-me35', type: 'Memory', question: 'L\'humour', instruction: 'Trouvez les paires', answer: '', context: 'Rire:Grine|Blague:Vits|Sourire:Smil|Ironie:Ironi|Sarkasme:Sarkasme|Comédie:Komedie' },
    { id: 'fr10-me36', type: 'Memory', question: 'La famille moderne', instruction: 'Trouvez les paires', answer: '', context: 'Parent:Forælder|Enfant:Barn|Mariage:Ægteskab|Divorce:Skilsmisse|Union:Forbindelse|Foyer:Hjem' },
    { id: 'fr10-me37', type: 'Memory', question: 'L\'immigration', instruction: 'Trouvez les paires', answer: '', context: 'Départ:Afrejse|Arrivée:Ankomst|Intégration:Integration|Accueil:Modtagelse|Visa:Visa|Exil:Eksil' },
    { id: 'fr10-me38', type: 'Memory', question: 'La religion', instruction: 'Trouvez les paires', answer: '', context: 'Foi:Tro|Culte:Gudstjeneste|Croyance:Overbevisning|Dieu:Gud|Temple:Tempel|Rituel:Ritual' },
    { id: 'fr10-me39', type: 'Memory', question: 'La technologie durable', instruction: 'Trouvez les paires', answer: '', context: 'Solaire:Solenergi|Éolien:Vindenergi|Électrique:Elektrisk|Propre:Ren|Vert:Grøn|Soutien:Støtte' },
    { id: 'fr10-me40', type: 'Memory', question: 'Le droit international', instruction: 'Trouvez les paires', answer: '', context: 'Traité:Traktat|Accord:Aftale|Organisation:Organisation|Nations:Nationer|Paix:Fred|Loi:Lov' },
    { id: 'fr10-me41', type: 'Memory', question: 'Les problèmes urbains', instruction: 'Trouvez les paires', answer: '', context: 'Trafic:Trafik|Bruit:Støj|Logement:Bolig|Ville:By|Banlieue:Forstad|Pollution:Forurening' },
    { id: 'fr10-me42', type: 'Memory', question: 'La psychologie sociale', instruction: 'Trouvez les paires', answer: '', context: 'Groupe:Gruppe|Individu:Individ|Influence:Indflydelse|Norme:Norm|Valeur:Værdi|Rôle:Rolle' },
    { id: 'fr10-me43', type: 'Memory', question: 'La génétique', instruction: 'Trouvez les paires', answer: '', context: 'ADN:DNA|Gène:Gen|Hérédité:Arvelighed|Évolution:Udvikling|Science:Videnskab|Cellule:Celle' },
    { id: 'fr10-me44', type: 'Memory', question: 'Les émotions profondes', instruction: 'Trouvez les paires', answer: '', context: 'Amour:Kærlighed|Haine:Had|Tristesse:Sorg|Espoir:Håb|Désespoir:Fortvivlelse|Passion:Lidenskab' },
    { id: 'fr10-me45', type: 'Memory', question: 'La citoyenneté', instruction: 'Trouvez les paires', answer: '', context: 'Vote:Stemme|Droit:Ret|Devoir:Pligt|Engagement:Engagement|Participation:Deltagelse|Loi:Lov' },
    { id: 'fr10-me46', type: 'Memory', question: 'La bioéthique', instruction: 'Trouvez les paires', answer: '', context: 'Clonage:Kloning|Éthique:Etik|Recherche:Forskning|Vie:Liv|Dignité:Værdighed|Choix:Valg' },
    { id: 'fr10-me47', type: 'Memory', question: 'Les relations internationales', instruction: 'Trouvez les paires', answer: '', context: 'Ambassade:Ambassade|Diplomate:Diplomat|Alliance:Alliance|Accord:Aftale|Conflit:Konflikt|Paix:Fred' },
    { id: 'fr10-me48', type: 'Memory', question: 'L\'archéologie', instruction: 'Trouvez les paires', answer: '', context: 'Fouilles:Udgravninger|Découverte:Opdagelse|Objet:Genstand|Ancien:Gammel|Histoire:Historie|Musée:Museum' },
    { id: 'fr10-me49', type: 'Memory', question: 'Les nouvelles énergies', instruction: 'Trouvez les paires', answer: '', context: 'Hydrogène:Brint|Nucléaire:Atomkraft|Fusion:Fusion|Énergie:Energi|Futur:Fremtid|Efficace:Effektiv' },
    { id: 'fr10-me50', type: 'Memory', question: 'La liberté d\'expression', instruction: 'Trouvez les paires', answer: '', context: 'Parole:Ord|Presse:Presse|Censurer:Censurere|Dire:Sige|Penser:Tænke|Oser:Turde' },
  ],
  3: [
    { id: 'fr3-me1', type: 'Memory', question: 'Passe-temps', instruction: 'Trouvez les activités', answer: '', context: 'Lire:Læse|Jouer:Spille|Chanter:Synge|Danser:Danse|Nager:Svømme|Courir:Løbe' },
    { id: 'fr3-me2', type: 'Memory', question: 'En ville', instruction: 'Trouvez les lieux', answer: '', context: 'Parc:Park|Cinéma:Biograf|Gare:Station|Hôtel:Hotel|Église:Kirke|Magasin:Butik' },
    { id: 'fr3-me3', type: 'Memory', question: 'Prépositions', instruction: 'Trouvez les prépositions', answer: '', context: 'Sur:På|Sous:Under|Dans:I|Derrière:Bag|Devant:Foran|À côté de:Ved siden af' },
    { id: 'fr3-me4', type: 'Memory', question: 'Verbes', instruction: 'Trouvez les actions', answer: '', context: 'Écrire:Skrive|Écouter:Høre|Voir:Se|Faire:Gøre|Venir:Komme|Aller:Gå' },
    { id: 'fr3-me5', type: 'Memory', question: 'Grands animaux', instruction: 'Trouvez les animaux sauvages', answer: '', context: 'Lion:Løve|Tigre:Tiger|Éléphant:Elefant|Girafe:Giraf|Singe:Abe|Zèbre:Zebra' },
  ],
  4: [
    { id: 'fr4-me1', type: 'Memory', question: 'Pays', instruction: 'Trouvez les pays', answer: '', context: 'Allemagne:Tyskland|Danemark:Danmark|France:Frankrig|Espagne:Spanien|Angleterre:England|Italie:Italien' },
    { id: 'fr4-me2', type: 'Memory', question: 'Environnement', instruction: 'Trouvez les mots', answer: '', context: 'Déchets:Affald|Recyclage:Genbrug|Eau:Vand|Forêt:Skov|Climat:Klima|Terre:Jord' },
    { id: 'fr4-me3', type: 'Memory', question: 'Médias', instruction: 'Trouvez les mots', answer: '', context: 'Ordinateur:Computer|Portable:Mobil|Internet:Internet|Radio:Radio|Télévision:TV|Journal:Avis' },
    { id: 'fr4-me4', type: 'Memory', question: 'Grammaire: Pluriel', instruction: 'Trouvez le singulier au pluriel', answer: '', context: 'Maison:Maisons|Enfant:Enfants|Homme:Hommes|Femme:Femmes|Arbre:Arbres|Pomme:Pommes' },
    { id: 'fr4-me5', type: 'Memory', question: 'Achats', instruction: 'Trouvez les mots', answer: '', context: 'Prix:Pris|Argent:Penge|Acheter:Købe|Vendre:Sælge|Cher:Dyr|Bon marché:Billig' },
  ],
  5: [
    { id: 'fr5-me1', type: 'Memory', question: 'Grammaire: Articles', instruction: 'Trouvez le genre', answer: '', context: 'Le:Chien|La:Porte|Le:Livre|La:Maison|Le:Tableau|La:Chaise' },
    { id: 'fr5-me2', type: 'Memory', question: 'Culture', instruction: 'Trouvez les icônes', answer: '', context: 'Paris:Capitale|Tour Eiffel:Symbole|Baguette:Pain|Fromage:Aliment|Napoléon:Histoire|Louvre:Musée' },
    { id: 'fr5-me3', type: 'Memory', question: 'Temps', instruction: 'Trouvez les unités', answer: '', context: 'Seconde:60|Minute:60|Heure:24|Jour:7|Semaine:52|Année:12' },
    { id: 'fr5-me4', type: 'Memory', question: 'Opposés', instruction: 'Trouvez les contraires', answer: '', context: 'Grand:Petit|Vieux:Nouveau|Chaud:Froid|Rapide:Lent|Bon:Mauvais|Clair:Sombre' },
    { id: 'fr5-me5', type: 'Memory', question: 'Politesse', instruction: 'Trouvez les phrases', answer: '', context: 'S\'il vous plaît:Vær så venlig|Merci:Tak|Bonjour:Goddag|Au revoir:Farvel|Pardon:Undskyld|Salut:Hej' },
  ],
  6: [
    { id: 'fr6-me1', type: 'Memory', question: 'Salut !', instruction: 'Trouvez les paires', answer: '', context: 'Bonjour:Goddag|Salut:Hej|Bonsoir:Godaften|Au revoir:Farvel|À bientôt:Vi ses snart|Bonne nuit:Godnat' },
    { id: 'fr6-me2', type: 'Memory', question: 'Ça c\'est moi !', instruction: 'Trouvez les paires', answer: '', context: 'Je m’appelle:Jeg hedder|J’ai... ans:Jeg er... år|J’habite:Jeg bor|Garçon:Dreng|Fille:Pige|Moi:Mig' },
    { id: 'fr6-me3', type: 'Memory', question: 'Ma chambre', instruction: 'Trouvez les paires', answer: '', context: 'Lit:Seng|Bureau:Skrivebord|Chaise:Stol|Armoire:Skab|Fenêtre:Vindue|Porte:Dør' },
    { id: 'fr6-me4', type: 'Memory', question: 'Ma famille', instruction: 'Trouvez les paires', answer: '', context: 'Père:Far|Mère:Mor|Frère:Bror|Sœur:Søster|Grand-père:Bedstefar|Grand-mère:Bedstemor' },
    { id: 'fr6-me5', type: 'Memory', question: 'Au marché', instruction: 'Trouvez les paires', answer: '', context: 'Pain:Brød|Fromage:Ost|Lait:Mælk|Œuf:Æg|Fruit:Frugt|Légume:Grøntsag' },
    { id: 'fr6-me6', type: 'Memory', question: 'Les animaux', instruction: 'Trouvez les paires', answer: '', context: 'Chien:Hund|Chat:Kat|Lapin:Kanin|Hamster:Hamster|Oiseau:Fugl|Poisson:Fisk' },
    { id: 'fr6-me7', type: 'Memory', question: 'Vive la mode', instruction: 'Trouvez les paires', answer: '', context: 'T-shirt:T-shirt|Pantalon:Bukser|Jupe:Nederdel|Robe:Kjole|Chaussures:Sko|Chapeau:Hat' },
    { id: 'fr6-me8', type: 'Memory', question: 'Le sport', instruction: 'Trouvez les paires', answer: '', context: 'Foot:Fodbold|Tennis:Tennis|Natation:Svømning|Danse:Dans|Vélo:Cykling|Ski:Ski' },
    { id: 'fr6-me9', type: 'Memory', question: 'Anniversaire', instruction: 'Trouvez les paires', answer: '', context: 'Cadeau:Gave|Gâteau:Kage|Bougie:Lys|Fête:Fest|Musique:Musik|Amis:Venner' },
    { id: 'fr6-me10', type: 'Memory', question: 'Le temps', instruction: 'Trouvez les paires', answer: '', context: 'Soleil:Sol|Pluie:Regn|Neige:Sne|Vent:Vind|Froid:Koldt|Chaud:Varmt' },
  ],
  7: [
    { id: 'fr7-me1', type: 'Memory', question: 'On fait les courses', instruction: 'Trouvez les paires', answer: '', context: 'Boulangerie:Bageri|Supermarché:Supermarked|Boucherie:Slagter|Pharmacie:Apotek|Marché:Marked|Épicerie:Købmand' },
    { id: 'fr7-me2', type: 'Memory', question: 'La nourriture', instruction: 'Trouvez les paires', answer: '', context: 'Poulet:Kylling|Poisson:Fisk|Viande:Kød|Riz:Ris|Pâtes:Pasta|Beurre:Smør' },
    { id: 'fr7-me3', type: 'Memory', question: 'Histoire et Art', instruction: 'Trouvez les paires', answer: '', context: 'Artiste:Kunstner|Peinture:Maleri|Musée:Museum|Histoire:Historie|Célèbre:Berømt|Tableau:Maleri' },
    { id: 'fr7-me4', type: 'Memory', question: 'Joyeux Noël', instruction: 'Trouvez les paires', answer: '', context: 'Sapin:Juletræ|Noël:Jul|Lumières:Lys|Étoile:Stjerne|Hiver:Vinter|Froid:Koldt' },
    { id: 'fr7-me5', type: 'Memory', question: 'En vacances au ski', instruction: 'Trouvez les paires', answer: '', context: 'Montagne:Bjerg|Ski:Ski|Neige:Sne|Vacances:Ferie|Froid:Koldt|Gants:Vanter' },
    { id: 'fr7-me6', type: 'Memory', question: 'Les jeux vidéo', instruction: 'Trouvez les paires', answer: '', context: 'Manette:Controller|Écran:Skærm|Jeu:Spil|Jouer:Spille|Gagner:Vinde|Perdre:Tabe' },
  ],
  8: [
    { id: 'fr8-me1', type: 'Memory', question: 'Musique', instruction: 'Trouvez les paires', answer: '', context: 'Chanteur:Sanger|Chanson:Sang|Concert:Koncert|Radio:Radio|Guitare:Guitar|Piano:Klaver' },
    { id: 'fr8-me2', type: 'Memory', question: 'Le Cinéma', instruction: 'Trouvez les paires', answer: '', context: 'Film:Film|Acteur:Skuespiller|Salles de ciné:Biografsale|Écran:Skærm|Pop-corn:Popcorn|Star:Stjerne' },
    { id: 'fr8-me3', type: 'Memory', question: 'Gastronomie', instruction: 'Trouvez les paires', answer: '', context: 'Restaurant:Restaurant|Chef:Kok|Menu:Menu|Plat:Ret|Cuisine:Køkken|Délicieux:Lækkert' },
    { id: 'fr8-me4', type: 'Memory', question: 'Monde francophone', instruction: 'Trouvez les paires', answer: '', context: 'Suisse:Schweiz|Québec:Québec|Belgique:Belgien|Maroc:Marokko|Sénégal:Sénégal|Haïti:Haïti' },
    { id: 'fr8-me5', type: 'Memory', question: 'La vie des jeunes', instruction: 'Trouvez les paires', answer: '', context: 'École:Skole|Amis:Venner|Hobby:Hobby|Portable:Mobiltelefon|Réseaux sociaux:Sociale medier|Études:Studier' },
  ],
  9: [
    { id: 'fr9-me1', type: 'Memory', question: 'Maître Gims', instruction: 'Trouvez les paires', answer: '', context: 'Chanteur:Sanger|Rap:Rap|Style:Stil|Lunettes:Briller|Succès:Succes|Voix:Stemme' },
    { id: 'fr9-me2', type: 'Memory', question: 'Intouchables', instruction: 'Trouvez les paires', answer: '', context: 'Film:Film|Amitié:Venskab|Humour:Humor|Histoire:Historie|Acteur:Skuespiller|Émotion:Følelse' },
    { id: 'fr9-me3', type: 'Memory', question: 'L’île Maurice', instruction: 'Trouvez les paires', answer: '', context: 'Île:Ø|Océan:Hav|Plage:Strand|Soleil:Sol|Nature:Natur|Voyage:Rejse' },
    { id: 'fr9-me4', type: 'Memory', question: 'Le Tour de France', instruction: 'Trouvez les paires', answer: '', context: 'Vélo:Cykel|Course:Løb|Maillot jaune:Gul førertrøje|Étape:Etape|Montagne:Bjerg|Vitesse:Fart' },
    { id: 'fr9-me5', type: 'Memory', question: 'L’IA (Intelligence Artificielle)', instruction: 'Trouvez les paires', answer: '', context: 'Ordinateur:Computer|Futur:Fremtid|Robot:Robot|Apprendre:Lære|Technologie:Teknologi|Science:Videnskab' },
  ],
};
