/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const SPANSK_MEMORY_P3: Partial<Record<Grade, GameContent[]>> = {
  2: [
    { id: 'es2-me1', type: 'Memory', question: 'Tal (11-20)', instruction: 'Find parrene', answer: '', context: '11:Once|12:Doce|13:Trece|14:Catorce|15:Quince|20:Veinte' },
    { id: 'es2-me2', type: 'Memory', question: 'Kroppen', instruction: 'Find parrene', answer: '', context: 'Hombro:Skulder|Codo:Albue|Rodilla:Knæ|Tobillo:Ankel|Cabeza:Hoved|Espalda:Ryg' },
    { id: 'es2-me3', type: 'Memory', question: 'Familien', instruction: 'Find parrene', answer: '', context: 'Tía:Tante|Tío:Onkel|Primo:Fætter|Abuela:Bedstemor|Abuelo:Bedstefar|Familia:Familie' },
    { id: 'es2-me4', type: 'Memory', question: 'Morgenmad', instruction: 'Find parrene', answer: '', context: 'Cereales:Morgenmadsprodukt|Tostada:Ristet brød|Mermelada:Syltetøj|Leche:Mælk|Miel:Honning|Mantequilla:Smør' },
    { id: 'es2-me5', type: 'Memory', question: 'Daglige handlinger', instruction: 'Find parrene', answer: '', context: 'Despertar:Vågne op|Lavar:Vaske|Comer:Spise|Ir:Gå|Jugar:Lege|Dormir:Sove' },
    { id: 'es2-me6', type: 'Memory', question: 'Tøj', instruction: 'Find parrene', answer: '', context: 'Camisa:Skjorte|Sombrero:Hat|Zapatos:Sko|Calcetines:Strømper|Pantalones:Bukser|Abrigo:Frakke' },
    { id: 'es2-me7', type: 'Memory', question: 'Farver', instruction: 'Find parrene', answer: '', context: 'Rosa:Lyserød|Marrón:Brun|Gris:Grå|Negro:Sort|Blanco:Hvid|Naranja:Orange' },
    { id: 'es2-me8', type: 'Memory', question: 'Kæledyr', instruction: 'Find parrene', answer: '', context: 'Perro:Hund|Gato:Kat|Hámster:Hamster|Conejo:Kanin|Pájaro:Fugl|Pez:Fisk' },
    { id: 'es2-me9', type: 'Memory', question: 'Frugter', instruction: 'Find parrene', answer: '', context: 'Manzana:Æble|Plátano:Banan|Naranja:Appelsin|Uva:Drue|Pera:Pære|Piña:Ananas' },
    { id: 'es2-me10', type: 'Memory', question: 'Følelser', instruction: 'Find parrene', answer: '', context: 'Feliz:Glad|Triste:Trist|Enfadado:Sur|Cansado:Træt|Hambriento:Sulten|Asustado:Bange' },
    { id: 'es2-me11', type: 'Memory', question: 'Días de la semana', instruction: 'Find parrene', answer: '', context: 'Lunes:Mandag|Martes:Tirsdag|Miércoles:Onsdag|Jueves:Torsdag|Viernes:Fredag|Sábado:Lørdag' },
    { id: 'es2-me12', type: 'Memory', question: 'Meses del año', instruction: 'Find parrene', answer: '', context: 'Enero:Januar|Febrero:Februar|Marzo:Marts|Abril:April|Mayo:Maj|Junio:Juni' },
    { id: 'es2-me13', type: 'Memory', question: 'Estaciones', instruction: 'Find parrene', answer: '', context: 'Primavera:Forår|Verano:Sommer|Otoño:Efterår|Invierno:Vinter|Sol:Sol|Lluvia:Regn' },
    { id: 'es2-me14', type: 'Memory', question: 'En la escuela', instruction: 'Find parrene', answer: '', context: 'Lápiz:Blyant|Libro:Bog|Cuaderno:Hæfte|Mochila:Taske|Profesor:Lærer|Escuela:Skole' },
    { id: 'es2-me15', type: 'Memory', question: 'Transportes', instruction: 'Find parrene', answer: '', context: 'Coche:Bil|Bicicleta:Cykel|Autobús:Bus|Tren:Tog|Avión:Fly|Barco:Skib' },
    { id: 'es2-me16', type: 'Memory', question: 'Frutas 2', instruction: 'Find parrene', answer: '', context: 'Fresa:Jordbær|Limón:Citron|Cereza:Kirsebær|Sandía:Vandmelon|Melocotón:Fersken|Ciruela:Blomme' },
    { id: 'es2-me17', type: 'Memory', question: 'Verduras', instruction: 'Find parrene', answer: '', context: 'Tomate:Tomat|Zanahoria:Gulerod|Patata:Kartoffel|Cebolla:Løg|Lechuga:Salat|Pepino:Agurk' },
    { id: 'es2-me18', type: 'Memory', question: 'Acciones de clase', instruction: 'Find parrene', answer: '', context: 'Leer:Læse|Escribir:Skrive|Dibujar:Tegne|Escuchar:Lytte|Hablar:Tale|Cantar:Synge' },
    { id: 'es2-me19', type: 'Memory', question: 'En casa', instruction: 'Find parrene', answer: '', context: 'Casa:Hus|Puerta:Dør|Ventana:Vindue|Silla:Stol|Mesa:Bord|Cama:Seng' },
    { id: 'es2-me20', type: 'Memory', question: 'Bebidas', instruction: 'Find parrene', answer: '', context: 'Agua:Vand|Leche:Mælk|Zumo:Juice|Refresco:Sodavand|Batido:Milkshake|Té:Te' },
    { id: 'es2-me21', type: 'Memory', question: 'Naturaleza', instruction: 'Find parrene', answer: '', context: 'Árbol:Træ|Flor:Blomst|Hierba:Græs|Montaña:Bjerg|Río:Flod|Mar:Hav' },
    { id: 'es2-me22', type: 'Memory', question: 'Tiempo atmosférico', instruction: 'Find parrene', answer: '', context: 'Sol:Sol|Nubes:Skyer|Viento:Vind|Nieve:Sne|Trueno:Torden|Niebla:Tåge' },
    { id: 'es2-me23', type: 'Memory', question: 'Instrumentos', instruction: 'Find parrene', answer: '', context: 'Guitarra:Guitar|Piano:Klaver|Tambor:Tromme|Flauta:Fløjte|Violín:Violin|Trompeta:Trompet' },
    { id: 'es2-me24', type: 'Memory', question: 'Deportes', instruction: 'Find parrene', answer: '', context: 'Fútbol:Fodbold|Baloncesto:Basketball|Tenis:Tennis|Natación:Svømning|Correr:Løbe|Saltar:Hoppe' },
    { id: 'es2-me25', type: 'Memory', question: 'Animales salvajes', instruction: 'Find parrene', answer: '', context: 'León:Løve|Elefante:Elefant|Mono:Abe|Jirafa:Giraf|Tigre:Tiger|Serpiente:Slange' },
    { id: 'es2-me26', type: 'Memory', question: 'Animales del mar', instruction: 'Find parrene', answer: '', context: 'Delfín:Delfin|Tiburón:Haj|Ballena:Hval|Pulpo:Blæksprutte|Cangrejo:Krabbe|Medusa:Vandmand' },
    { id: 'es2-me27', type: 'Memory', question: 'La ciudad', instruction: 'Find parrene', answer: '', context: 'Calle:Gade|Parque:Park|Tienda:Butik|Cine:Biograf|Hospital:Hospital|Banco:Bank' },
    { id: 'es2-me28', type: 'Memory', question: 'Preposiciones', instruction: 'Find parrene', answer: '', context: 'Sobre:På|Debajo:Under|Dentro:I|Delante:Foran|Detrás:Bag|Al lado:Ved siden af' },
    { id: 'es2-me29', type: 'Memory', question: 'Adjetivos cortas', instruction: 'Find parrene', answer: '', context: 'Grande:Stor|Pequeño:Lille|Alto:Høj|Bajo:Lav|Rápido:Hurtig|Lento:Langsom' },
    { id: 'es2-me30', type: 'Memory', question: 'En el baño', instruction: 'Find parrene', answer: '', context: 'Jabón:Sæbe|Toalla:Håndklæde|Cepillo:Børste|Espejo:Spejl|Agua:Vand|Papel:Papir' },
    { id: 'es2-me31', type: 'Memory', question: 'La cocina', instruction: 'Find parrene', answer: '', context: 'Plato:Tallerken|Vaso:Glas|Cuchara:Ske|Cuchillo:Kniv|Tenedor:Gaffel|Olla:Gryde' },
    { id: 'es2-me32', type: 'Memory', question: 'Ropa 2', instruction: 'Find parrene', answer: '', context: 'Falda:Nederdel|Vestido:Kjole|Chaqueta:Jakke|Gorro:Hue|Guantes:Vanter|Bufanda:Tørklæde' },
    { id: 'es2-me33', type: 'Memory', question: 'Formas', instruction: 'Find parrene', answer: '', context: 'Círculo:Cirkel|Cuadrado:Kvadrat|Triángulo:Trekant|Estrella:Stjerne|Corazón:Hjerte|Rectángulo:Rektangel' },
    { id: 'es2-me34', type: 'Memory', question: 'Opuestos 2', instruction: 'Find parrene', answer: '', context: 'Caliente:Varm|Frío:Kold|Abierto:Åben|Cerrado:Lukket|Limpio:Ren|Sucio:Beskidt' },
    { id: 'es2-me35', type: 'Memory', question: 'Profesiones', instruction: 'Find parrene', answer: '', context: 'Médico:Læge|Policía:Politi|Bombero:Brandmand|Piloto:Pilot|Cocinero:Kok|Dentista:Tandlæge' },
    { id: 'es2-me36', type: 'Memory', question: 'Insectos', instruction: 'Find parrene', answer: '', context: 'Mariposa:Sommerfugl|Abeja:Bi|Hormiga:Myre|Araña:Edderkop|Mosca:Flue|Mariquita:Mariehøne' },
    { id: 'es2-me37', type: 'Memory', question: 'Muebles', instruction: 'Find parrene', answer: '', context: 'Sillón:Lænestol|Estantería:Reol|Armario:Skab|Alfombra:Tæppe|Lámpara:Lampe|Reloj:Ur' },
    { id: 'es2-me38', type: 'Memory', question: 'Sentimientos 2', instruction: 'Find parrene', answer: '', context: 'Sorprendido:Overrasket|Aburrido:Ked af det|Orgulloso:Stolt|Tímido:Genert|Emocionado:Spændt|Calmado:Rolig' },
    { id: 'es2-me39', type: 'Memory', question: 'Verbos comunes', instruction: 'Find parrene', answer: '', context: 'Dar:Give|Tener:Have|Hacer:Gøre|Venir:Komme|Saber:Vide|Poner:Sætte' },
    { id: 'es2-me40', type: 'Memory', question: 'Cuerpo - cara', instruction: 'Find parrene', answer: '', context: 'Ojo:Øje|Oreja:Øre|Nariz:Næse|Boca:Mund|Diente:Tand|Pelo:Hår' },
    { id: 'es2-me41', type: 'Memory', question: 'Números 30-80', instruction: 'Find parrene', answer: '', context: 'Treinta:30|Cuarenta:40|Cincuenta:50|Sesenta:60|Setenta:70|Ochenta:80' },
    { id: 'es2-me42', type: 'Memory', question: 'Adjetivos de personalidad', instruction: 'Find parrene', answer: '', context: 'Amable:Sød|Valiente:Modig|Listo:Klog|Divertido:Sjov|Bueno:God|Simpático:Flink' },
    { id: 'es2-me43', type: 'Memory', question: 'En la granja', instruction: 'Find parrene', answer: '', context: 'Vaca:Ko|Cerdo:Gris|Oveja:Får|Pato:And|Gallina:Høne|Tractor:Traktor' },
    { id: 'es2-me44', type: 'Memory', question: 'Habitaciones', instruction: 'Find parrene', answer: '', context: 'Cocina:Køkken|Salón:Stue|Baño:Badeværelse|Dormitorio:Soveværelse|Pasillo:Gang|Garaje:Garage' },
    { id: 'es2-me45', type: 'Memory', question: 'Juguetes', instruction: 'Find parrene', answer: '', context: 'Pelota:Bold|Muñeca:Dukke|Coche:Bil|Puzle:Puslespil|Peluche:Bamse|Cometa:Drage' },
    { id: 'es2-me46', type: 'Memory', question: 'Comida 2', instruction: 'Find parrene', answer: '', context: 'Huevo:Æg|Queso:Ost|Pollo:Kylling|Arroz:Ris|Pasta:Pasta|Ensalada:Salat' },
    { id: 'es2-me47', type: 'Memory', question: 'Eventos', instruction: 'Find parrene', answer: '', context: 'Fiesta:Fest|Cumpleaños:Fødselsdag|Boda:Bryllup|Concierto:Koncert|Cena:Middag|Viaje:Rejse' },
    { id: 'es2-me48', type: 'Memory', question: 'Herramientas', instruction: 'Find parrene', answer: '', context: 'Martillo:Hammer|Sierra:Sav|Llave:Nøgle|Destornillador:Skruetrækker|Clavo:Søm|Tijeras:Saks' },
    { id: 'es2-me49', type: 'Memory', question: 'El espacio', instruction: 'Find parrene', answer: '', context: 'Luna:Måne|Estrella:Stjerne|Planeta:Planet|Sol:Sol|Tierra:Jorden|Cohete:Raket' },
    { id: 'es2-me50', type: 'Memory', question: 'Mix final Grade 2', instruction: 'Find parrene', answer: '', context: 'Hola:Hej|Adiós:Farvel|Gracias:Tak|Perdón:Undskyld|Si:Ja|No:Nej' },
    { id: 'es2-me51', type: 'Memory', question: 'Frutas 3', instruction: 'Relaciona las palabras', answer: '', context: 'Uva:Drue|Piña:Ananas|Mango:Mango|Coco:Kokos|Kiwi:Kiwi|Pera:Pære' },
    { id: 'es2-me52', type: 'Memory', question: 'Animales de Granja 2', instruction: 'Relaciona las palabras', answer: '', context: 'Cabra:Ged|Burro:Æsel|Pato:And|Gallo:Hane|Gallina:Høne|Oveja:Får' },
    { id: 'es2-me53', type: 'Memory', question: 'La Escuela (objetos)', instruction: 'Relaciona las palabras', answer: '', context: 'Goma:Viskelæder|Regla:Lineal|Sacapuntas:Blyantspidser|Estuche:Penalhus|Mochila:Taske|Pizarra:Tavle' },
    { id: 'es2-me54', type: 'Memory', question: 'Verbos de Movimiento', instruction: 'Relaciona las palabras', answer: '', context: 'Caminar:Gå|Correr:Løbe|Saltar:Hoppe|Bailar:Danse|Nadar:Svømme|Volar:Flyve' },
    { id: 'es2-me55', type: 'Memory', question: 'Adjetivos de Tamaño', instruction: 'Relaciona las palabras', answer: '', context: 'Grande:Stor|Pequeño:Lille|Largo:Lang|Corto:Kort|Alto:Høj|Bajo:Lav' },
    { id: 'es2-me56', type: 'Memory', question: 'En el Parque', instruction: 'Relaciona las palabras', answer: '', context: 'Árbol:Træ|Banco:Bænk|Flor:Blomst|Hierba:Græs|Camino:Sti|Lago:Sø' },
    { id: 'es2-me57', type: 'Memory', question: 'Bebidas 2', instruction: 'Relaciona las palabras', answer: '', context: 'Agua:Vand|Leche:Mælk|Zumo:Juice|Refresco:Sodavand|Batido:Milkshake|Té:Te' },
    { id: 'es2-me58', type: 'Memory', question: 'La Cara', instruction: 'Relaciona las palabras', answer: '', context: 'Ojo:Øje|Nariz:Næse|Boca:Mund|Oreja:Øre|Pelo:Hår|Diente:Tand' },
    { id: 'es2-me59', type: 'Memory', question: 'Instrumentos 2', instruction: 'Relaciona las palabras', answer: '', context: 'Tambor:Tromme|Flauta:Fløjte|Trompeta:Trompet|Violín:Violin|Piano:Klaver|Arpa:Harpe' },
    { id: 'es2-me60', type: 'Memory', question: 'Ropa de Verano', instruction: 'Relaciona las palabras', answer: '', context: 'Camiseta:T-shirt|Bañador:Badedragt|Gafas:Briller|Sombrero:Hat|Sandalias:Sandaler|Pantalones cortos:Shorts' },
    { id: 'es2-me61', type: 'Memory', question: 'Ropa de Invierno', instruction: 'Relaciona las palabras', answer: '', context: 'Abrigo:Frakke|Bufanda:Halstørklæde|Guantes:Vanter|Gorro:Hue|Botas:Støvler|Jersey:Trøje' },
    { id: 'es2-me62', type: 'Memory', question: 'Acciones de Clase', instruction: 'Relaciona las palabras', answer: '', context: 'Leer:Læse|Escribir:Skrive|Dibujar:Tegne|Escuchar:Lytte|Cantar:Synge|Mirar:Se' },
    { id: 'es2-me63', type: 'Memory', question: 'En la Cocina', instruction: 'Relaciona las palabras', answer: '', context: 'Plato:Tallerken|Vaso:Glas|Cuchara:Ske|Cuchillo:Kniv|Tenedor:Gaffel|Olla:Gryde' },
    { id: 'es2-me64', type: 'Memory', question: 'En el Baño', instruction: 'Relaciona las palabras', answer: '', context: 'Jabón:Sæbe|Toalla:Håndklæde|Espejo:Spejl|Cepillo:Børste|Agua:Vand|Papel:Papir' },
    { id: 'es2-me65', type: 'Memory', question: 'Días de la Semana', instruction: 'Relaciona las palabras', answer: '', context: 'Lunes:Mandag|Martes:Tirsdag|Miércoles:Onsdag|Jueves:Torsdag|Viernes:Fredag|Sábado:Lørdag' },
    { id: 'es2-me66', type: 'Memory', question: 'Meses del Año', instruction: 'Relaciona las palabras', answer: '', context: 'Enero:Januar|Febrero:Februar|Marzo:Marts|Abril:April|Mayo:Maj|Junio:Juni' },
    { id: 'es2-me67', type: 'Memory', question: 'Las Estaciones', instruction: 'Relaciona las palabras', answer: '', context: 'Primavera:Forår|Verano:Sommer|Otoño:Efterår|Invierno:Vinter|Calor:Varme|Frío:Kulde' },
    { id: 'es2-me68', type: 'Memory', question: 'Partes de la Casa 2', instruction: 'Relaciona las palabras', answer: '', context: 'Salón:Stue|Cocina:Køkken|Baño:Badeværelse|Dormitorio:Soveværelse|Jardín:Have|Garaje:Garage' },
    { id: 'es2-me69', type: 'Memory', question: 'Muebles 2', instruction: 'Relaciona las palabras', answer: '', context: 'Silla:Stol|Mesa:Bord|Sofá:Sofa|Cama:Seng|Armario:Skab|Lámpara:Lampe' },
    { id: 'es2-me70', type: 'Memory', question: 'Preposiciones 2', instruction: 'Relaciona las palabras', answer: '', context: 'Sobre:På|Debajo:Under|En:I|Delante:Foran|Detrás:Bag|Al lado de:Ved siden af' },
    { id: 'es2-me71', type: 'Memory', question: 'Adjetivos de Estado', instruction: 'Relaciona las palabras', answer: '', context: 'Abierto:Åben|Cerrado:Lukket|Limpio:Ren|Sucio:Beskidt|Lleno:Fyldt|Vacío:Tom' },
    { id: 'es2-me72', type: 'Memory', question: 'Sensaciones', instruction: 'Relaciona las palabras', answer: '', context: 'Caliente:Varm|Frío:Kold|Hambre:Sult|Sed:Tørst|Sueño:Søvn (træt)|Miedo:Frygt' },
    { id: 'es2-me73', type: 'Memory', question: 'Ocupaciones 2', instruction: 'Relaciona las palabras', answer: '', context: 'Médico:Læge|Policía:Politi|Bombero:Brandmand|Piloto:Pilot|Cocinero:Kok|Dentista:Tandlæge' },
    { id: 'es2-me74', type: 'Memory', question: 'Deportes 2', instruction: 'Relaciona las palabras', answer: '', context: 'Fútbol:Fodbold|Baloncesto:Basketball|Tenis:Tennis|Natación:Svømning|Atletismo:Løb|Ciclismo:Cykling' },
    { id: 'es2-me75', type: 'Memory', question: 'Transportes 2', instruction: 'Relaciona las palabras', answer: '', context: 'Coche:Bil|Bici:Cykel|Autobús:Bus|Tren:Tog|Avión:Fly|Barco:Skib' },
    { id: 'es2-me76', type: 'Memory', question: 'Insectos 2', instruction: 'Relaciona las palabras', answer: '', context: 'Mariposa:Sommerfugl|Abeja:Bi|Hormiga:Myre|Araña:Edderkop|Mosca:Flue|Mariquita:Mariehøne' },
    { id: 'es2-me77', type: 'Memory', question: 'Animales Salvajes 2', instruction: 'Relaciona las palabras', answer: '', context: 'León:Løve|Elefante:Elefant|Mono:Abe|Jirafa:Giraf|Tigre:Tiger|Serpiente:Slange' },
    { id: 'es2-me78', type: 'Memory', question: 'Animales Marinos 2', instruction: 'Relaciona las palabras', answer: '', context: 'Delfín:Delfin|Tiburón:Haj|Ballena:Hval|Pulpo:Blæksprutte|Cangrejo:Krabbe|Medusa:Vandmand' },
    { id: 'es2-me79', type: 'Memory', question: 'En la Ciudad 3', instruction: 'Relaciona las palabras', answer: '', context: 'Calle:Gade|Plaza:Plads|Tienda:Butik|Cine:Biograf|Hospital:Hospital|Banco:Bank' },
    { id: 'es2-me80', type: 'Memory', question: 'Tecnología 2', instruction: 'Relaciona las palabras', answer: '', context: 'Ordenador:Computer|Móvil:Mobil|Tablet:Tablet|Internet:Internet|Ratón:Mus|Teclado:Tastatur' },
    { id: 'es2-me81', type: 'Memory', question: 'Formas Geométricas 2', instruction: 'Relaciona las palabras', answer: '', context: 'Círculo:Cirkel|Cuadrado:Kvadrat|Triángulo:Trekant|Estrella:Stjerne|Corazón:Hjerte|Rectángulo:Rektangel' },
    { id: 'es2-me82', type: 'Memory', question: 'Adjetivos de Apariencia', instruction: 'Relaciona las palabras', answer: '', context: 'Bonito:Smuk|Feo:Grim|Nuevo:Ny|Viejo:Gammel|Rápido:Hurtig|Lento:Langsom' },
    { id: 'es2-me83', type: 'Memory', question: 'Sentimientos 3', instruction: 'Relaciona las palabras', answer: '', context: 'Feliz:Glad|Triste:Triste|Enojao:Vred|Cansado:Træt|Aburrido:Ked af det|Asustado:Bange' },
    { id: 'es2-me84', type: 'Memory', question: 'Números 20-100', instruction: 'Relaciona las palabras', answer: '', context: 'Veinte:20|Treinta:30|Cuarenta:40|Cincuenta:50|Cien:100|Mil:1000' },
    { id: 'es2-me85', type: 'Memory', question: 'Naturaleza 2', instruction: 'Relaciona las palabras', answer: '', context: 'Montaña:Bjerg|Río:Flod|Mar:Hav|Nube:Sky|Sol:Sol|Bosque:Skov' },
    { id: 'es2-me86', type: 'Memory', question: 'Colores 3', instruction: 'Relaciona las palabras', answer: '', context: 'Rojo:Rød|Azul:Blå|Amarillo:Gul|Verde:Grøn|Rosa:Lyserød|Gris:Grå' },
    { id: 'es2-me87', type: 'Memory', question: 'Cuerpo - cara 2', instruction: 'Relaciona las palabras', answer: '', context: 'Frente:Pande|Mejilla:Kind|Barbilla:Hage|Ceja:Øjenbryn|Pestaña:Øjenvippe|Labio:Læbe' },
    { id: 'es2-me88', type: 'Memory', question: 'Higiene 2', instruction: 'Relaciona las palabras', answer: '', context: 'Cepillo de dientes:Tandbørste|Pasta de dientes:Tandpasta|Peine:Kam|Champú:Shampoo|Esponja:Svamp|Ducha:Bad' },
    { id: 'es2-me89', type: 'Memory', question: 'Verbos Comunes 3', instruction: 'Relaciona las palabras', answer: '', context: 'Dar:Give|Tener:Have|Hacer:Gøre|Venir:Komme|Saber:Vide|Poner:Sætte' },
    { id: 'es2-me90', type: 'Memory', question: 'Personalidad 2', instruction: 'Relaciona las palabras', answer: '', context: 'Amable:Sød|Valiente:Modig|Inteligente:Klog|Divertido:Sjov|Bueno:God|Simpático:Flink' },
    { id: 'es2-me91', type: 'Memory', question: 'Habitaciones 2', instruction: 'Relaciona las palabras', answer: '', context: 'Cocina:Køkken|Comedor:Spisestue|Despacho:Kontor|Sótano:Kælder|Ático:Loft|Entrada:Indgang' },
    { id: 'es2-me92', type: 'Memory', question: 'Materiales 2', instruction: 'Relaciona las palabras', answer: '', context: 'Madera:Træ|Metal:Metal|Plástico:Plastik|Cristal:Glas|Papel:Papir|Tela:Stof' },
    { id: 'es2-me93', type: 'Memory', question: 'El Clima 3', instruction: 'Relaciona las palabras', answer: '', context: 'Soleado:Solskin|Lluvioso:Regnvejr|Nevado:Snevejr|Ventoso:Blæsevejr|Nublado:Overskyet|Tormenta:Tordenvejr' },
    { id: 'es2-me94', type: 'Memory', question: 'Instrumentos de Cuerda', instruction: 'Relaciona las palabras', answer: '', context: 'Guitarra:Guitar|Violín:Violin|Arpa:Harpe|Ukelele:Ukelele|Contrabajo:Kontrabas|Chelo:Cello' },
    { id: 'es2-me95', type: 'Memory', question: 'Instrumentos de Viento', instruction: 'Relaciona las palabras', answer: '', context: 'Flauta:Fløjte|Trompeta:Trompet|Saxofón:Saxofon|Clarinete:Klarinet|Trombón:Basun|Fagot:Fagot' },
    { id: 'es2-me96', type: 'Memory', question: 'Instrumentos de Percusión', instruction: 'Relaciona las palabras', answer: '', context: 'Tambor:Tromme|Batería:Trommesæt|Xilófono:Xylofon|Pandereta:Pandero|Castañuelas:Kastanjetter|Platillos:Bækkener' },
    { id: 'es2-me97', type: 'Memory', question: 'En el Cuarto de Estar', instruction: 'Relaciona las palabras', answer: '', context: 'Televisor:TV|Mando a distancia:Fjernbetjening|Cojín:Pude|Alfombra:Tæppe|Cortina:Gardin|Cuadro:Maleri' },
    { id: 'es2-me98', type: 'Memory', question: 'En el Cuarto de Baño 2', instruction: 'Relaciona las palabras', answer: '', context: 'Lavabo:Håndvask|Inodoro:Toilet|Bañera:Badekar|Ducha:Brusebad|Grifo:Vandhane|Bidé:Bidet' },
    { id: 'es2-me99', type: 'Memory', question: 'Final Grado 2 Español 1', instruction: 'Relaciona las palabras', answer: '', context: 'Buen trabajo:Godt arbejde|Felicidades:Tillykke|Terminado:Færdig|Siguiente:Næste|Hasta luego:Vi ses|Adiós:Farvel' },
    { id: 'es2-me100', type: 'Memory', question: 'Final Grado 2 Español 2', instruction: 'Relaciona las palabras', answer: '', context: 'Excelente:Fremragende|Genial:Genialt|Perfecto:Perfekt|Logro:Bedrift|Nivel:Niveau|Fin:Slut' },
  ]
};
