/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const SPANSK_MEMORY_P8: Partial<Record<Grade, GameContent[]>> = {
  7: [
    { id: 'es7-me1', type: 'Memory', question: 'Verbos: Futuro Compuesto', instruction: 'Encuentra las parejas', answer: '', context: 'Habré hablado:Yo|Habrás hablado:Tú|Habrá hablado:Él/Ella|Habremos hablado:Nosotros|Habréis hablado:Vosotros|Habrán hablado:Ellos' },
    { id: 'es7-me2', type: 'Memory', question: 'Verbos: Condicional Compuesto', instruction: 'Encuentra las parejas', answer: '', context: 'Habría hablado:Yo|Habrías hablado:Tú|Habría hablado:Él/Ella|Habríamos hablado:Nosotros|Habríais hablado:Vosotros|Habrían hablado:Ellos' },
    { id: 'es7-me3', type: 'Memory', question: 'Sustantivos Irregulares de Género', instruction: 'Encuentra las parejas', answer: '', context: 'El mapa:La mano|El poema:La foto|El sistema:La moto|El clima:La radio|El sofá:La flor|El día:La ley' },
    { id: 'es7-me4', type: 'Memory', question: 'Adjetivos Comparativos Irregulares', instruction: 'Encuentra las parejas', answer: '', context: 'Bueno:Mejor|Malo:Peor|Grande:Mayor|Pequeño:Menor|Alto:Superior|Bajo:Inferior' },
    { id: 'es7-me5', type: 'Memory', question: 'Adverbios de Afirmación y Negación', instruction: 'Encuentra las parejas', answer: '', context: 'Sí:También|Claro:Exacto|Seguro:Cierto|No:Tampoco|Nunca:Jamás|Nada:Ninguno' },
    { id: 'es7-me6', type: 'Memory', question: 'Preposiciones compuestas', instruction: 'Encuentra las parejas', answer: '', context: 'Debajo de:Bajo|Encima de:Sobre|Delante de:Ante|Detrás de:Tras|Al rededor de:En torno|A través de:Por' },
    { id: 'es7-me7', type: 'Memory', question: 'Locuciones adverbiales', instruction: 'Encuentra las parejas', answer: '', context: 'De repente:Súbito|A ciegas:Sin ver|De veras:En serio|Al azar:Suerte|Por fin:Finalmente|De vez en cuando:A veces' },
    { id: 'es7-me8', type: 'Memory', question: 'Palabras agudas sin tilde', instruction: 'Encuentra las parejas', answer: '', context: 'Feliz:z|Amor:r|Papel:l|Cantar:r|Reloj:j|Pared:d' },
    { id: 'es7-me9', type: 'Memory', question: 'Palabras llanas sin tilde', instruction: 'Encuentra las parejas', answer: '', context: 'Casa:vocal|Perro:vocal|Libro:vocal|Gato:vocal|Examen:n|Lunes:s' },
    { id: 'es7-me10', type: 'Memory', question: 'Palabras sobreesdrújulas', instruction: 'Encuentra las parejas', answer: '', context: 'Cántamelo:Tilde|Dígaselo:Tilde|Tráetelo:Tilde|Pásatelo:Tilde|Escríbemelo:Tilde|Juégatela:Tilde' },
    { id: 'es7-me11', type: 'Memory', question: 'Vocabulario: Sinónimos (Formales)', instruction: 'Encuentra las parejas', answer: '', context: 'Suministrar:Dar|Notificar:Avisar|Proceder:Empezar|Suprimir:Quitar|Incrementar:Subir|Atribuir:Culpar' },
    { id: 'es7-me12', type: 'Memory', question: 'Vocabulario: Antónimos (Formales)', instruction: 'Encuentra las parejas', answer: '', context: 'Eficaz:Inútil|Explícito:Implícito|Íntimo:Público|Efímero:Duradero|Adverso:Favorable|Nocivo:Sano' },
    { id: 'es7-me13', type: 'Memory', question: 'Matemáticas: Ecuaciones 1er Grado', instruction: 'Encuentra las parejas', answer: '', context: 'x + 2 = 5:3|2x = 10:5|x - 3 = 10:13|x / 2 = 4:8|3x = 9:3|x + x = 4:2' },
    { id: 'es7-me14', type: 'Memory', question: 'Matemáticas: Proporcionalidad Inversa', instruction: 'Encuentra las parejas', answer: '', context: 'Más velocidad:Menos tiempo|Más gente:Menos comida|Más obreros:Menos días|Doble:Mitad|Triple:Tercio|Mitad:Doble' },
    { id: 'es7-me15', type: 'Memory', question: 'Matemáticas: Geometría de Sólidos', instruction: 'Encuentra las parejas', answer: '', context: 'Cubo:6 caras|Pirámide:Vértice arriba|Cilindro:Bases circulares|Cono:Vértice y base|Esfera:Sin caras|Prisma:Lados rectos' },
    { id: 'es7-me16', type: 'Memory', question: 'Ciencias: Citología Avanzada', instruction: 'Encuentra las parejas', answer: '', context: 'Mitocondria:Energía|Ribosoma:Proteína|Aparato Golgi:Envío|Retículo:Transporte|Lisosoma:Limpieza|Vacuola:Reserva' },
    { id: 'es7-me17', type: 'Memory', question: 'Ciencias: Geología Dinámica', instruction: 'Encuentra las parejas', answer: '', context: 'Tectónica:Placas|Falla:Grieta|Volcán:Magma|Sismo:Vibración|Tsunami:Ola|Epicentro:Origen' },
    { id: 'es7-me18', type: 'Memory', question: 'Geografía: Europa Orografía', instruction: 'Encuentra las parejas', answer: '', context: 'Mont Blanc:Alpes|Elbrus:Cáucaso|Ben Nevis:Escocia|Galdhøpiggen:Noruega|Mulhacén:España|Etna:Volcán' },
    { id: 'es7-me19', type: 'Memory', question: 'Geografía: Asia Orografía', instruction: 'Encuentra las parejas', answer: '', context: 'Everest:Himalaya|K2:Karakórum|Fuji:Japón|Urales:Límites|Gobi:Desierto|Tíbet:Meseta' },
    { id: 'es7-me20', type: 'Memory', question: 'Historia: Revolución Francesa', instruction: 'Encuentra las parejas', answer: '', context: '1789:Inicio|Bastilla:Prisión|Luis XVI:Guillotina|Napoleón:Final|Robespierre:Terror|Derechos:Leyes' },
    { id: 'es7-me21', type: 'Memory', question: 'Historia: Revolución Americana', instruction: 'Encuentra las parejas', answer: '', context: '1776:Independencia|Washington:General|Tea Party:Protesta|Colonias:Trece|Jefferson:Declaración|Inglaterra:Rey' },
    { id: 'es7-me22', type: 'Memory', question: 'Física: Cinemática', instruction: 'Encuentra las parejas', answer: '', context: 'Velocidad:m/s|Aceleración:m/s2|Tiempo:Segundos|Distancia:Metros|Fuerza:Newtons|Masa:Kilos' },
    { id: 'es7-me23', type: 'Memory', question: 'Química: Elementos 1', instruction: 'Encuentra las parejas', answer: '', context: 'Hidrógeno:H|Helio:He|Litio:Li|Boro:B|Carbono:C|Nitrógeno:N' },
    { id: 'es7-me24', type: 'Memory', question: 'Química: Elementos 2', instruction: 'Encuentra las parejas', answer: '', context: 'Oxígeno:O|Flúor:F|Neón:Ne|Sodio:Na|Magnesio:Mg|Aluminio:Al' },
    { id: 'es7-me25', type: 'Memory', question: 'Lengua: Oraciones Coordinadas', instruction: 'Encuentra las parejas', answer: '', context: 'Copulativas:Y|Disyuntivas:O|Adversativas:Pero|Explicativas:Es decir|Distributivas:Bien...bien|Iuxtapuestas:Coma' },
    { id: 'es7-me26', type: 'Memory', question: 'Lengua: Oraciones Subordinadas', instruction: 'Encuentra las parejas', answer: '', context: 'Sustantivas:Eso|Adjetivas:Cual|Adverbiales:Allí|Causales:Porque|Finales:Para|Concesivas:Aunque' },
    { id: 'es7-me27', type: 'Memory', question: 'Vocabulario: Latinismos', instruction: 'Encuentra las parejas', answer: '', context: 'Alma mater:Madre|Carpe diem:Vive|Caveat:Cuidado|Et cetera:Y más|In situ:Lugar|Persona non grata:No querida' },
    { id: 'es7-me28', type: 'Memory', question: 'Vocabulario: Helenismos', instruction: 'Encuentra las parejas', answer: '', context: 'Psico-:Mente|Tele-:Lejos|Bio-:Vida|Foto-:Luz|Demo-:Pueblo|Antropo-:Hombre' },
    { id: 'es7-me29', type: 'Memory', question: 'Ortografía: Letras C, S, Z', instruction: 'Encuentra las parejas', answer: '', context: 'Casa:c|Sopa:s|Zapato:z|Cero:c|Silla:s|Zorro:z' },
    { id: 'es7-me30', type: 'Memory', question: 'Ortografía: Letras G, J (Verbos)', instruction: 'Encuentra las parejas', answer: '', context: 'Recoger:g|Crujir:j|Traer:j (traje)|Decir:j (dije)|Elegir:g|Dirigir:g' },
    { id: 'es7-me31', type: 'Memory', question: 'Literatura: El Romanticismo', instruction: 'Encuentra las parejas', answer: '', context: 'Bécquer:Rimas|Espronceda:Pirata|Larra:Artículos|Rosalía:Gallego|Sentimiento:Libertad|Naturaleza:Salvaje' },
    { id: 'es7-me32', type: 'Memory', question: 'Literatura: El Realismo', instruction: 'Encuentra las parejas', answer: '', context: 'Galdós:Misericordia|Clarín:La Regenta|Pardo Bazán:Naturaleza|Realidad:Espejo|Detalle:Mundo|Sociedad:Crítica' },
    { id: 'es7-me33', type: 'Memory', question: 'Matemáticas: Probabilidad II', instruction: 'Encuentra las parejas', answer: '', context: 'Evento:Suceso|Espacio:Total|Laplace:Fracción|Moneda:1/2|Dado:1/6|Baraja:40/48 cards' },
    { id: 'es7-me34', type: 'Memory', question: 'Ciencias: El Átomo Partes', instruction: 'Encuentra las parejas', answer: '', context: 'Protón:Positivo|Neutrón:Neutro|Electrón:Negativo|Núcleo:Centro|Corteza:Borde|Átomo:Pequeño' },
    { id: 'es7-me35', type: 'Memory', question: 'Biología: Reinos Avanzado', instruction: 'Encuentra las parejas', answer: '', context: 'Arqueas:Extremo|Procariotas:Sin núcleo|Eucariotas:Núcleo|Saprofitos:Comen muertos|Parásitos:Viven de otros|Simbiotes:Ayuda' },
    { id: 'es7-me36', type: 'Memory', question: 'Astronomía: Estrellas y Galaxias', instruction: 'Encuentra las parejas', answer: '', context: 'Supernova:Explosión|Agujero negro:Gravedad|Constelación:Dibujo|Nebulosa:Gas|Galaxia:Sistemas|Universo:Todo' },
    { id: 'es7-me37', type: 'Memory', question: 'Historia: Antigua Grecia Filosofía', instruction: 'Encuentra las parejas', answer: '', context: 'Sócrates:Ética|Platón:Ideas|Aristóteles:Lógica|Academia:Lugar|Liceo:Lugar|Duda:Método' },
    { id: 'es7-me38', type: 'Memory', question: 'Historia: Antiguo Egipto Dioses', instruction: 'Encuentra las parejas', answer: '', context: 'Ra:Sol|Osiris:Muerte|Isis:Magia|Horus:Cielo|Anubis:Embalsama|Thot:Sabiduría' },
    { id: 'es7-me39', type: 'Memory', question: 'Geografía: África Orografía', instruction: 'Encuentra las parejas', answer: '', context: 'Kilimanjaro:Kenia|Atlas:Norte|Drakensberg:Sur|Victoria:Cataratas|Sahara:Desierto|Congo:Selva' },
    { id: 'es7-me40', type: 'Memory', question: 'Geografía: América Orografía', instruction: 'Encuentra las parejas', answer: '', context: 'Aconcagua:Andes|McKinley:Alaska|Amazonas:Selva|Niágara:Cataratas|Pampa:Llanura|Patagonia:Sur' },
    { id: 'es7-me41', type: 'Memory', question: 'Arte: Modernismo (Arquitectura)', instruction: 'Encuentra las parejas', answer: '', context: 'Gaudí:Sagrada Familia|Curvatura:Forma|Azulejos:Color|Naturaleza:Inspiración|Barcelona:Ciudad|Hierro/Cristal:Material' },
    { id: 'es7-me42', type: 'Memory', question: 'Música: Instrumentos Asia', instruction: 'Encuentra las parejas', answer: '', context: 'Coto:Japón|Sitar:India|Pipa:China|Guzheng:China|Biwa:Japón|Erhu:China' },
    { id: 'es7-me43', type: 'Memory', question: 'Deporte: Atletismo Pruebas', instruction: 'Encuentra las parejas', answer: '', context: 'Maratón:Largo|Velocidad:100m|Vallas:Salto|Longitud:Foso|Altura:Listón|Lanzamiento:Peso' },
    { id: 'es7-me44', type: 'Memory', question: 'Tecnología: Codificación', instruction: 'Encuentra las parejas', answer: '', context: 'Binario:0 y 1|Hexadecimal:16 base|Bit:Mínimo|Byte:8 bits|ASCII:Texto|Unicode:Emoji' },
    { id: 'es7-me45', type: 'Memory', question: 'Ciudadanía: Constitución Española', instruction: 'Encuentra las parejas', answer: '', context: '1978:Año|Derechos:Título I|Corona:Jefe|Cortes:Leyes|Justicia:Independiente|Democracia:Lema' },
    { id: 'es7-me46', type: 'Memory', question: 'Economía: La Bolsa', instruction: 'Encuentra las parejas', answer: '', context: 'Acción:Parte|Dividendo:Ganancia|Bróker:Agente|Mercado:Bolsa|Índice:IBEX 35|Inversor:Socio' },
    { id: 'es7-me47', type: 'Memory', question: 'Valores: Ética y Moral', instruction: 'Encuentra las parejas', answer: '', context: 'Norma:Lugar|Valor:Bueno|Responsabilidad:Actuar|Deber:Hacer|Justicia:Reparto|Paz:Lema' },
    { id: 'es7-me48', type: 'Memory', question: 'Ciencias: Descubrimientos Españoles', instruction: 'Encuentra las parejas', answer: '', context: 'Neurona:Cajal|Circulación:Servet|Submarino:Isaac Peral|Autogiro:La Cierva|Calculadora:Torres Quevedo|Traje Espacial:Emilio Herrera' },
    { id: 'es7-me49', type: 'Memory', question: 'Geografía: España Costas', instruction: 'Encuentra las parejas', answer: '', context: 'Brava:Girona|Blanca:Alicante|Sol:Málaga|Luz:Huelva|Cantábrico:Norte|Atlántico:Estepona (no)' },
    { id: 'es7-me50', type: 'Memory', question: 'Historia: La Invasión Napoleónica', instruction: 'Encuentra las parejas', answer: '', context: '1808:Inicio|Pepe Botella:José I|Bailén:Batalla|Guerrilla:Táctica|Wellington:Aliado|1814:Fin' },
    { id: 'es7-me100', type: 'Memory', question: 'Final del curso', instruction: 'Encuentra las parejas', answer: '', context: 'Exámenes:Aprobado|Vacaciones:Verano|Próximo:8º|Saber:Poder|Amigos:Fiesta|Fin:Fin' },
  ],
};
