/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const SPANSK_MEMORY_P9: Partial<Record<Grade, GameContent[]>> = {
  8: [
    { id: 'es8-me1', type: 'Memory', question: 'Verbos: Presente de Subjuntivo (Irregulares)', instruction: 'Encuentra las parejas', answer: '', context: 'Sea:Ser|Vaya:Ir|Haga:Hacer|Diga:Decir|Tenga:Tener|Sepa:Saber' },
    { id: 'es8-me2', type: 'Memory', question: 'Verbos: Imperfecto de Subjuntivo', instruction: 'Encuentra las parejas', answer: '', context: 'Hablara:Hablase|Comiera:Comiese|Viviera:Viviese|Fuera:Fuese|Tuviera:Tuviese|Pudiera:Pudiese' },
    { id: 'es8-me3', type: 'Memory', question: 'Nexos condicionales', instruction: 'Encuentra las parejas', answer: '', context: 'Si:Condición|En caso de que:Condición|A condición de que:Condición|Siempre que:Condición|Como:Condición|Con tal de que:Condición' },
    { id: 'es8-me4', type: 'Memory', question: 'Nexos causales y finales', instruction: 'Encuentra las parejas', answer: '', context: 'Porque:Causa|Puesto que:Causa|Ya que:Causa|Para que:Finalidad|A fin de que:Finalidad|Con el objeto de:Finalidad' },
    { id: 'es8-me5', type: 'Memory', question: 'Preposiciones (A-D)', instruction: 'Encuentra las parejas', answer: '', context: 'A:Dirección|Ante:Delante|Bajo:Debajo|Cabe:Junto (ant)|Con:Compañía|Contra:Oposición' },
    { id: 'es8-me6', type: 'Memory', question: 'Preposiciones (D-H)', instruction: 'Encuentra las parejas', answer: '', context: 'De:Origen|Desde:Inicio|Durante:Tiempo|En:Lugar|Entre:Medio|Hacia:Dirección' },
    { id: 'es8-me7', type: 'Memory', question: 'Preposiciones (H-S)', instruction: 'Encuentra las parejas', answer: '', context: 'Hasta:Fin|Mediante:Por|Para:Final|Por:Causa|Según:Modo|Sin:Carencia' },
    { id: 'es8-me8', type: 'Memory', question: 'Preposiciones (S-V)', instruction: 'Encuentra las parejas', answer: '', context: 'So:Bajo (ant)|Sobre:Encima|Tras:Después|Versus:Contra|Vía:Por medio|Mediante:Instrumento' },
    { id: 'es8-me9', type: 'Memory', question: 'Ortografía: Letra G/GU/GÜ', instruction: 'Encuentra las parejas', answer: '', context: 'Gato:g|Guerra:gu|Cigüeña:gü|Agua:gu|Guitarra:gu|Pingüino:gü' },
    { id: 'es8-me10', type: 'Memory', question: 'Ortografía: Letra C/QU/K', instruction: 'Encuentra las parejas', answer: '', context: 'Casa:c|Queso:qu|Kilo:k|Querer:qu|Calor:c|Kiwi:k' },
    { id: 'es8-me11', type: 'Memory', question: 'Vocabulario: Arcaísmos II', instruction: 'Encuentra las parejas', answer: '', context: 'Alberca:Piscina|Fierro:Hierro|Anteojos:Gafas|Botica:Farmacia|Recámara:Cuarto|Ponerse:Vestirse' },
    { id: 'es8-me12', type: 'Memory', question: 'Vocabulario: Neologismos II', instruction: 'Encuentra las parejas', answer: '', context: 'Streamer:Emisor|Influencer:Influyente|Hashtag:Etiqueta|Podcast:Audio|App:Aplicación|Smart:Inteligente' },
    { id: 'es8-me13', type: 'Memory', question: 'Matemáticas: Radicales', instruction: 'Encuentra las parejas', answer: '', context: 'Raíz 100:10|Raíz 64:8|Raíz 144:12|Raíz 81:9|Raíz 400:20|Raíz 625:25' },
    { id: 'es8-me14', type: 'Memory', question: 'Matemáticas: Semejanza', instruction: 'Encuentra las parejas', answer: '', context: 'Thales:Teorema|Escala:Mapa|Proporción:Relación|Semejante:Forma igual|Directa:K|Triángulos:Ángulos' },
    { id: 'es8-me15', type: 'Memory', question: 'Matemáticas: Funciones', instruction: 'Encuentra las parejas', answer: '', context: 'Lineal:Recta|Afín:Recta (no 0)|Continua:No salta|Dominio:X|Recorrido:Y|Pendiente:M' },
    { id: 'es8-me16', type: 'Memory', question: 'Ciencias: Física (Leyes Newton)', instruction: 'Encuentra las parejas', answer: '', context: 'I:Inercia|II:Fuerza|III:Acción/Reacción|F = m x a:Fuerza|Masa:Kg|Aceleración:m/s2' },
    { id: 'es8-me17', type: 'Memory', question: 'Ciencias: Química (Estados)', instruction: 'Encuentra las parejas', answer: '', context: 'Sublimación:Gas|Fusión:Líquido|Solidificación:Sólido|Vaporización:Gas|Condensación:Líquido|Materia:Átomo' },
    { id: 'es8-me18', type: 'Memory', question: 'Geografía: Asia Conflictos', instruction: 'Encuentra las parejas', answer: '', context: 'Palestina:Israel|Siria:Guerra|Afganistán:Kabul|Corea:Norte/Sur|Tíbet:China|Kashmir:India/Pakistán' },
    { id: 'es8-me19', type: 'Memory', question: 'Geografía: África Economías', instruction: 'Encuentra las parejas', answer: '', context: 'Petróleo:Nigeria|Diamantes:Sudáfrica|Turismo:Egipto|Cacao:Costa Marfil|Café:Etiopía|Mina:Recursos' },
    { id: 'es8-me20', type: 'Memory', question: 'Historia: Guerra Civil Española', instruction: 'Encuentra las parejas', answer: '', context: '1936-39:Años|Franco:Bando|Guernica:Picasso|Madrid:Sede|Exilio:Gente|Posguerra:Hambre' },
    { id: 'es8-me21', type: 'Memory', question: 'Historia: I Guerra Mundial', instruction: 'Encuentra las parejas', answer: '', context: 'Sarajevo:Chispa|Trincheras:Lucha|Versalles:Tratado|Triple Entente:Aliados|Tanque:Nuevo|1918:Fin' },
    { id: 'es8-me22', type: 'Memory', question: 'Ciencias: El Sol', instruction: 'Encuentra las parejas', answer: '', context: 'Helios:Griego|Núcleo:Calor|Fotosfera:Luz|Cromosfera:Color|Corona:Fuera|Manchas:Frías' },
    { id: 'es8-me23', type: 'Memory', question: 'Ciencias: Energía Nuclear', instruction: 'Encuentra las parejas', answer: '', context: 'Fisión:Dividir|Fusión:Unir|Uranio:Combustible|Residuo:Peligro|Central:Luz|Chernóbil:Fallo' },
    { id: 'es8-me24', type: 'Memory', question: 'Lengua: Análisis Sintáctico IV', instruction: 'Encuentra las parejas', answer: '', context: 'Aposición:Explicación|Vocativo:Llamar|Atributo:Ser|Comp. Agente:Por|Predicativo:Cómo|C. Régimen:Preposición' },
    { id: 'es8-me25', type: 'Memory', question: 'Lengua: Análisis Morfológico Avanzado', instruction: 'Encuentra las parejas', answer: '', context: 'Hablara:Imperfecto Subj.|He dicho:Compuesto|Comiendo:Gerundio|Amado:Participio|Saltar:Infinitivo|¡Ah!:Interjección' },
    { id: 'es8-me26', type: 'Memory', question: 'Vocabulario: Sinonimia Absoluta', instruction: 'Encuentra las parejas', answer: '', context: 'Marido:Esposo|Dentista:Odontólogo|Siniestro:Izquierdo|Alfombra:Tapete|Agujero:Hueco|Plátano:Banano' },
    { id: 'es8-me27', type: 'Memory', question: 'Vocabulario: Antonimia Recíproca', instruction: 'Encuentra las parejas', answer: '', context: 'Comprar:Vender|Padre:Hijo|Profesor:Alumno|Dar:Recibir|Pagar:Cobrar|Preguntar:Responder' },
    { id: 'es8-me28', type: 'Memory', question: 'Ortografía: Acentuación Grupos', instruction: 'Encuentra las parejas', answer: '', context: 'Diptongo:vocal cerrada+abierta|Hiato:dos abiertas|Triptongo:tres vocales|Limpia:ia|País:a-í|Uruguay:uay' },
    { id: 'es8-me29', type: 'Memory', question: 'Ortografía: Letra X', instruction: 'Encuentra las parejas', answer: '', context: 'Estructura:es|Examen:ex|Extraer:ex|Espléndido:es|Texto:ex|Éxtasis:ex' },
    { id: 'es8-me30', type: 'Memory', question: 'Literatura: Modernismo (Rubén Darío)', instruction: 'Encuentra las parejas', answer: '', context: 'Azul:Libro|Prosas profanas:Libro|Cisne:Símbolo|Color:Palabra|Ritmo:Música|Princesas:Tema' },
    { id: 'es8-me31', type: 'Memory', question: 'Literatura: Generación del 27', instruction: 'Encuentra las parejas', answer: '', context: 'Lorca:Poeta|Dalí:Pintor|Buñuel:Cine|Poesía:Góngora|Surrealismo:Vanguardia|Nueva York:Poeta' },
    { id: 'es8-me32', type: 'Memory', question: 'Matemáticas: Trigonometría Básica', instruction: 'Encuentra las parejas', answer: '', context: 'Seno:Opuesto/H|Coseno:Contiguo/H|Tangente:O/C|Grados:Mida|Radián:Ángulo|90:Recto' },
    { id: 'es8-me33', type: 'Memory', question: 'Ciencias: El Ojo (Defectos)', instruction: 'Encuentra las parejas', answer: '', context: 'Miopía:Cerca bien|Hipermetropía:Lejos bien|Astigmatismo:Borroso|Catarata:Opacidad|Gafas:Lentes|Láser:Operar' },
    { id: 'es8-me34', type: 'Memory', question: 'Biología: Genética Mendel', instruction: 'Encuentra las parejas', answer: '', context: 'Guisante:Planta|Leyes:Mendel|Dominante:A|Recesivo:a|Genotipo:Genes|Fenotipo:Ver' },
    { id: 'es8-me35', type: 'Memory', question: 'Astronomía: El Big Bang', instruction: 'Encuentra las parejas', answer: '', context: 'Origen:Explosión|Expansión:Crecer|Luz:Pasado|Galaxias:Alejan|Tiempo:Cero|Universo:Todo' },
    { id: 'es8-me36', type: 'Memory', question: 'Historia: Imperio Romano II', instruction: 'Encuentra las parejas', answer: '', context: 'Julio César:Dictador|Augusto:Emperador|Pax Romana:Paz|Coliseo:Juegos|Calzadas:Transporte|Caída:476' },
    { id: 'es8-me37', type: 'Memory', question: 'Historia: El Islam', instruction: 'Encuentra las parejas', answer: '', context: 'Mahoma:Profeta|Corán:Libro|Mezquita:Lugar|Alá:Dios|Cinco pilares:Ley|Al-Ándalus:España' },
    { id: 'es8-me38', type: 'Memory', question: 'Geografía: Océano Índico', instruction: 'Encuentra las parejas', answer: '', context: 'Madagascar:Isla|Monzón:Viento|Tiburón:Pez|Coral:Arrecife|India:Costa|Calor:Agua' },
    { id: 'es8-me39', type: 'Memory', question: 'Geografía: Océano Ártico', instruction: 'Encuentra las parejas', answer: '', context: 'Polo Norte:Centro|Hielo:Capa|Oso Polar:Animal|Foca:Animal|Frío:Grados|Rusia:Límite' },
    { id: 'es8-me40', type: 'Memory', question: 'Arte: Cubismo', instruction: 'Encuentra las parejas', answer: '', context: 'Picasso:Avignon|Braque:Collage|Juan Gris:España|Geometría:Forma|Puntos de vista:Muchos|Gris:Color' },
    { id: 'es8-me41', type: 'Memory', question: 'Música: Instrumentos de Jazz', instruction: 'Encuentra las parejas', answer: '', context: 'Saxofón:Melodía|Trompeta:Brillo|Contrabajo:Ritmo|Piano:Armonía|Batería:Pulso|Voz:Scat' },
    { id: 'es8-me42', type: 'Memory', question: 'Tecnología: Impresión 3D', instruction: 'Encuentra las parejas', answer: '', context: 'Filamento:Material|Capa:Adición|Diseño:CAD|Prototipo:Modelo|Medicina:Prótesis|Casa:Obra' },
    { id: 'es8-me43', type: 'Memory', question: 'Ciudadanía: Los Poderes del Estado', instruction: 'Encuentra las parejas', answer: '', context: 'Legislativo:Congreso|Ejecutivo:Gobierno|Judicial:Jueces|Montesquieu:Autor|Separación:Independencia|Voto:Pueblo' },
    { id: 'es8-me44', type: 'Memory', question: 'Economía: La Oferta y la Demanda', instruction: 'Encuentra las parejas', answer: '', context: 'Oferta:Vender|Demanda:Comprar|Precio:Punto|Equilibrio:Cruce|Escasez:Poco|Abundancia:Mucho' },
    { id: 'es8-me45', type: 'Memory', question: 'Valores: Objetivos de Desarrollo (ODS)', instruction: 'Encuentra las parejas', answer: '', context: 'Pobreza:Fin|Hambre:Cero|Educación:Calidad|Clima:Acción|Océanos:Vida|Paz:Justicia' },
    { id: 'es8-me46', type: 'Memory', question: 'Ciencias: El Microscopio', instruction: 'Encuentra las parejas', answer: '', context: 'Lente:Cristal|Ocular:Ojo|Objetivo:Cerca|Platina:Soporte|Luz:Ver|Enfoque:Nitidez' },
    { id: 'es8-me47', type: 'Memory', question: 'Geografía: España Paisajes', instruction: 'Encuentra las parejas', answer: '', context: 'Altamira:Cantabria|Gaudí:Cataluña|Alhambra:Granada|Giralda:Sevilla|Tablas:Daimiel|Doñana:Huelva' },
    { id: 'es8-me48', type: 'Memory', question: 'Historia: La Transición Española', instruction: 'Encuentra las parejas', answer: '', context: 'Suárez:Presidente|Rey:Juan Carlos|Amnistía:Perdón|Pactos:Moncloa|Constitución:1978|1975:Inicio' },
    { id: 'es8-me49', type: 'Memory', question: 'Deporte: El Tour de Francia', instruction: 'Encuentra las parejas', answer: '', context: 'Maillot:Amarillo|Montaña:Lunares|Velocidad:Verde|Joven:Blanco|Pelotón:Grupo|Contrarreloj:Solo' },
    { id: 'es8-me50', type: 'Memory', question: 'Tecnología: Realidad Virtual', instruction: 'Encuentra las parejas', answer: '', context: 'Casco:Vista|Gafas:3D|Inmersión:Dentro|Control:Manos|Simulación:Juego|Aumentada:Realidad' },
    { id: 'es8-me100', type: 'Memory', question: 'Final de 2º ESO', instruction: 'Encuentra las parejas', answer: '', context: 'Siguiente:3º ESO|Graduación:Fiesta|Verano:Libre|Amigos:Colegas|Libros:Guardados|Fin:Fin' },
  ],
};
