/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const TYSK_MEMORY: Partial<Record<Grade, GameContent[]>> = {
  2: [
    { id: 'de2-me1', type: 'Memory', question: 'Zahlen (11-20)', instruction: 'Finde die Paare', answer: '', context: '11:Elf|12:Zwölf|13:Dreizehn|14:Vierzehn|15:Fünfzehn|20:Zwanzig' },
    { id: 'de2-me2', type: 'Memory', question: 'Körperteile', instruction: 'Finde die Paare', answer: '', context: 'Schulter:Skulder|Ellbogen:Albue|Knie:Knæ|Knöchel:Ankel|Kopf:Hoved|Rücken:Ryg' },
    { id: 'de2-me3', type: 'Memory', question: 'Familie', instruction: 'Finde die Paare', answer: '', context: 'Tante:Tante|Onkel:Onkel|Cousin:Fætter/Kusine|Oma:Bedstemor|Opa:Bedstefar|Familie:Familie' },
    { id: 'de2-me4', type: 'Memory', question: 'Frühstück', instruction: 'Finde die Paare', answer: '', context: 'Müsli:Morgenmadsprodukt|Toast:Ristet brød|Marmelade:Syltetøj|Milch:Mælk|Honig:Honning|Butter:Smør' },
    { id: 'de2-me5', type: 'Memory', question: 'Feiertage', instruction: 'Finde die Paare', answer: '', context: 'Ostern:Påske|Weihnachten:Jul|Halloween:Halloween|Nikolaus:Julemand|Tannenbaum:Grantræ|Ei:Æg' },
    { id: 'de2-me6', type: 'Memory', question: 'Tagesablauf', instruction: 'Finde die Paare', answer: '', context: 'Aufwachen:Vågne op|Waschen:Vaske|Essen:Spise|Gehen:Gå|Spielen:Lege|Schlafen:Sove' },
    { id: 'de2-me7', type: 'Memory', question: 'Kleidung', instruction: 'Finde die Paare', answer: '', context: 'Hemd:Skjorte|Hut:Hat|Schuhe:Sko|Socken:Strømper|Hose:Bukser|Mantel:Frakke' },
    { id: 'de2-me8', type: 'Memory', question: 'Farben', instruction: 'Finde die Paare', answer: '', context: 'Rosa:Lyserød|Braun:Brun|Grau:Grå|Schwarz:Sort|Weiß:Hvid|Orange:Orange' },
    { id: 'de2-me9', type: 'Memory', question: 'Haustiere', instruction: 'Finde die Paare', answer: '', context: 'Hund:Hund|Katze:Katze|Hamster:Hamster|Kaninchen:Kanin|Vogel:Fugl|Fisch:Fisk' },
    { id: 'de2-me10', type: 'Memory', question: 'Fragen', instruction: 'Finde die Paare', answer: '', context: 'Wer:Hvem|Was:Hvad|Wo:Hvor|Wie:Hvordan|Warum:Hvorfor|Wann:Hvornår' },
    { id: 'de2-me11', type: 'Memory', question: 'Wochentage', instruction: 'Finde die Paare', answer: '', context: 'Montag:Mandag|Dienstag:Tirsdag|Mittwoch:Onsdag|Donnerstag:Torsdag|Freitag:Fredag|Samstag:Lørdag' },
    { id: 'de2-me12', type: 'Memory', question: 'Monate', instruction: 'Finde die Paare', answer: '', context: 'Januar:Januar|Februar:Februar|März:Marts|April:April|Mai:Maj|Juni:Juni' },
    { id: 'de2-me13', type: 'Memory', question: 'Jahreszeiten', instruction: 'Finde die Paare', answer: '', context: 'Frühling:Forår|Sommer:Sommer|Herbst:Efterår|Winter:Vinter|Sonne:Sol|Regen:Regn' },
    { id: 'de2-me14', type: 'Memory', question: 'In der Schule', instruction: 'Finde die Paare', answer: '', context: 'Bleistift:Blyant|Buch:Bog|Heft:Hæfte|Rucksack:Taske|Lehrer:Lærer|Schule:Skole' },
    { id: 'de2-me15', type: 'Memory', question: 'Transportmittel', instruction: 'Finde die Paare', answer: '', context: 'Auto:Bil|Fahrrad:Cykel|Bus:Bus|Zug:Tog|Flugzeug:Fly|Schiff:Skib' },
    { id: 'de2-me16', type: 'Memory', question: 'Früchte 2', instruction: 'Finde die Paare', answer: '', context: 'Erdbeere:Jordbær|Zitrone:Citron|Kirsche:Kirsebær|Wassermelone:Vandmelon|Pfirsich:Fersken|Pflaume:Blomme' },
    { id: 'de2-me17', type: 'Memory', question: 'Gemüse', instruction: 'Finde die Paare', answer: '', context: 'Tomate:Tomat|Karotte:Gulerod|Kartoffel:Kartoffel|Zwiebel:Løg|Salat:Salat|Gurke:Agurk' },
    { id: 'de2-me18', type: 'Memory', question: 'Aktionen in der Klasse', instruction: 'Finde die Paare', answer: '', context: 'Lesen:Læse|Schreiben:Skrive|Zeichnen:Tegne|Hören:Lytte|Sprechen:Tale|Singen:Synge' },
    { id: 'de2-me19', type: 'Memory', question: 'Im Haus', instruction: 'Finde die Paare', answer: '', context: 'Haus:Hus|Tür:Dør|Fenster:Vindue|Stuhl:Stol|Tisch:Bord|Bett:Seng' },
    { id: 'de2-me20', type: 'Memory', question: 'Getränke', instruction: 'Finde die Paare', answer: '', context: 'Wasser:Vand|Milch:Mælk|Saft:Juice|Limo:Sodavand|Schorle:Juice/Vand|Tee:Te' },
    { id: 'de2-me21', type: 'Memory', question: 'Natur', instruction: 'Finde die Paare', answer: '', context: 'Baum:Træ|Blume:Blomst|Gras:Græs|Berg:Bjerg|Fluss:Flod|Meer:Hav' },
    { id: 'de2-me22', type: 'Memory', question: 'Wetter 2', instruction: 'Finde die Paare', answer: '', context: 'Sonne:Sol|Wolken:Skyer|Wind:Vind|Schnee:Sne|Donner:Torden|Nebel:Tåge' },
    { id: 'de2-me23', type: 'Memory', question: 'Instrumente', instruction: 'Finde die Paare', answer: '', context: 'Gitarre:Guitar|Klavier:Klaver|Trommel:Tromme|Flöte:Fløjte|Geige:Violin|Trompete:Trompet' },
    { id: 'de2-me24', type: 'Memory', question: 'Sport', instruction: 'Finde die Paare', answer: '', context: 'Fußball:Fodbold|Basketball:Basketball|Tennis:Tennis|Schwimmen:Svømning|Laufen:Løbe|Springen:Hoppe' },
    { id: 'de2-me25', type: 'Memory', question: 'Wildtiere', instruction: 'Finde die Paare', answer: '', context: 'Löwe:Løve|Elefant:Elefant|Affe:Abe|Giraffe:Giraf|Tiger:Tiger|Schlange:Slange' },
    { id: 'de2-me26', type: 'Memory', question: 'Meerestiere', instruction: 'Finde die Paare', answer: '', context: 'Delfin:Delfin|Hai:Haj|Wal:Hval|Krake:Blæksprutte|Krabbe:Krabbe|Qualle:Vandmand' },
    { id: 'de2-me27', type: 'Memory', question: 'In der Stadt 2', instruction: 'Finde die Paare', answer: '', context: 'Straße:Gade|Park:Park|Laden:Butik|Kino:Biograf|Krankenhaus:Hospital|Bank:Bank' },
    { id: 'de2-me28', type: 'Memory', question: 'Präpositionen', instruction: 'Finde die Paare', answer: '', context: 'Auf:På|Unter:Under|In:I|Vor:Foran|Hinter:Bag|Neben:Ved siden af' },
    { id: 'de2-me29', type: 'Memory', question: 'Adjektive 2', instruction: 'Finde die Paare', answer: '', context: 'Groß:Stor|Klein:Lille|Hoch:Høj|Niedrig:Lav|Schnell:Hurtig|Langsam:Langsom' },
    { id: 'de2-me30', type: 'Memory', question: 'Im Badezimmer', instruction: 'Finde die Paare', answer: '', context: 'Seife:Sæbe|Handtuch:Håndklæde|Bürste:Børste|Spiegel:Spejl|Wasser:Vand|Papier:Papir' },
    { id: 'de2-me31', type: 'Memory', question: 'In der Küche', instruction: 'Finde die Paare', answer: '', context: 'Teller:Tallerken|Glas:Glas|Löffel:Ske|Messer:Kniv|Gabel:Gaffel|Topf:Gryde' },
    { id: 'de2-me32', type: 'Memory', question: 'Kleidung 2', instruction: 'Finde die Paare', answer: '', context: 'Rock:Nederdel|Kleid:Kjole|Jacke:Jakke|Mütze:Hue|Handschuhe:Vanter|Schal:Tørklæde' },
    { id: 'de2-me33', type: 'Memory', question: 'Formen', instruction: 'Finde die Paare', answer: '', context: 'Kreis:Cirkel|Quadrat:Kvadrat|Dreieck:Trekant|Stern:Stjerne|Herz:Hjerte|Rechteck:Rektangel' },
    { id: 'de2-me34', type: 'Memory', question: 'Gegenteile 2', instruction: 'Finde die Paare', answer: '', context: 'Heiß:Varm|Kalt:Kold|Offen:Åben|Geschlossen:Lukket|Sauber:Ren|Schmutzig:Beskidt' },
    { id: 'de2-me35', type: 'Memory', question: 'Berufe', instruction: 'Finde die Paare', answer: '', context: 'Arzt:Læge|Polizei:Politi|Feuerwehr:Brandmand|Pilot:Pilot|Koch:Kok|Zahnarzt:Tandlæge' },
    { id: 'de2-me36', type: 'Memory', question: 'Insekten', instruction: 'Finde die Paare', answer: '', context: 'Schmetterling:Sommerfugl|Biene:Bi|Ameise:Myre|Spinne:Edderkop|Fliege:Flue|Marienkäfer:Mariehøne' },
    { id: 'de2-me37', type: 'Memory', question: 'Möbel', instruction: 'Finde die Paare', answer: '', context: 'Sessel:Lænestol|Regal:Reol|Schrank:Skab|Teppich:Tæppe|Lampe:Lampe|Uhr:Ur' },
    { id: 'de2-me38', type: 'Memory', question: 'Gefühle 2', instruction: 'Finde die Paare', answer: '', context: 'Überrascht:Overrasket|Langweilig:Ked af det|Stolz:Stolt|Schüchtern:Genert|Aufgeregt:Spændt|Ruhig:Rolig' },
    { id: 'de2-me39', type: 'Memory', question: 'Verben 2', instruction: 'Finde die Paare', answer: '', context: 'Geben:Give|Haben:Have|Machen:Gøre|Kommen:Komme|Wissen:Vide|Setzen:Sætte' },
    { id: 'de2-me40', type: 'Memory', question: 'Körper - Gesicht', instruction: 'Finde die Paare', answer: '', context: 'Auge:Øje|Ohr:Øre|Nase:Næse|Mund:Mund|Zahn:Tand|Haar:Hår' },
    { id: 'de2-me41', type: 'Memory', question: 'Zahlen 30-80', instruction: 'Finde die Paare', answer: '', context: 'Dreißig:30|Vierzig:40|Fünfzig:50|Sechzig:60|Siebzig:70|Achtzig:80' },
    { id: 'de2-me42', type: 'Memory', question: 'Persönlichkeit', instruction: 'Finde die Paare', answer: '', context: 'Nett:Sød|Mutig:Modig|Schlau:Klog|Lustig:Sjov|Gut:God|Freundlich:Flink' },
    { id: 'de2-me43', type: 'Memory', question: 'Auf dem Bauernhof', instruction: 'Finde die Paare', answer: '', context: 'Kuh:Ko|Schwein:Gris|Schaf:Får|Ente:And|Huhn:Høne|Traktor:Traktor' },
    { id: 'de2-me44', type: 'Memory', question: 'Zimmer', instruction: 'Finde die Paare', answer: '', context: 'Küche:Køkken|Wohnzimmer:Stue|Badezimmer:Badeværelse|Schlafzimmer:Soveværelse|Flur:Gang|Garage:Garage' },
    { id: 'de2-me45', type: 'Memory', question: 'Spielzeug 2', instruction: 'Finde die Paare', answer: '', context: 'Ball:Bold|Puppe:Dukke|Auto:Bil|Puzzle:Puslespil|Teddy:Bamse|Drachen:Drage' },
    { id: 'de2-me46', type: 'Memory', question: 'Essen 2', instruction: 'Finde die Paare', answer: '', context: 'Ei:Æg|Käse:Ost|Hähnchen:Kylling|Reis:Ris|Nudeln:Pasta|Salat:Salat' },
    { id: 'de2-me47', type: 'Memory', question: 'Events', instruction: 'Finde die Paare', answer: '', context: 'Party:Fest|Geburtstag:Fødselsdag|Hochzeit:Bryllup|Konzert:Koncert|Abendessen:Middag|Reise:Rejse' },
    { id: 'de2-me48', type: 'Memory', question: 'Werkzeuge', instruction: 'Finde die Paare', answer: '', context: 'Hammer:Hammer|Säge:Sav|Schlüssel:Nøgle|Schraubenzieher:Skruetrækker|Nagel:Søm|Schere:Saks' },
    { id: 'de2-me49', type: 'Memory', question: 'Weltall', instruction: 'Finde die Paare', answer: '', context: 'Mond:Måne|Stern:Stjerne|Planet:Planet|Sonne:Sol|Erde:Jorden|Rakete:Raket' },
    { id: 'de2-me50', type: 'Memory', question: 'Mix final Grade 2 German', instruction: 'Finde die Paare', answer: '', context: 'Hallo:Hej|Tschüss:Farvel|Danke:Tak|Entschuldigung:Undskyld|Ja:Ja|Nej:Nej' },
  ],
  3: [
    { id: 'de3-me1', type: 'Memory', question: 'Zahlen (1-10)', instruction: 'Match numerals', answer: '', context: '1:Eins|2:Zwei|3:Drei|4:Vier|5:Fünf|10:Zehn' },
    { id: 'de3-me2', type: 'Memory', question: 'Farben', instruction: 'Match colors', answer: '', context: 'Rot:Rot|Blau:Blau|Gelb:Gelb|Grün:Grün|Schwarz:Schwarz|Weiß:Weiß' },
    { id: 'de3-me3', type: 'Memory', question: 'Familie', instruction: 'Match family', answer: '', context: 'Mutter:Mutter|Vater:Vater|Schwester:Schwester|Bruder:Bruder|Oma:Oma|Opa:Opa' },
    { id: 'de3-me4', type: 'Memory', question: 'Freunde & Adjektive', instruction: 'Match adjectives', answer: '', context: 'Gut:Dårlig (no)|Sød:Gutte|Lustig:Funny|Schön:Smuk|Groß:Stor|Stark:Stærk' },
  ],
  4: [
    { id: 'de4-me1', type: 'Memory', question: 'Ugedage', instruction: 'Match days', answer: '', context: 'Montag:Mandag|Dienstag:Tirsdag|Mittwoch:Onsdag|Donnerstag:Torsdag|Freitag:Fredag|Sonntag:Søndag' },
    { id: 'de4-me2', type: 'Memory', question: 'Schule', instruction: 'Match school items', answer: '', context: 'Buch:Buch|Heft:Heft|Stift:Stift|Schule:Schule|Lehrer:Lehrer|Tisch:Tisch' },
    { id: 'de4-me3', type: 'Memory', question: 'Tiere', instruction: 'Match animals', answer: '', context: 'Hund:Hund|Katze:Katze|Pferd:Pferd|Vogel:Vogel|Maus:Maus|Fisch:Fisch' },
    { id: 'de4-me4', type: 'Memory', question: 'Freizeit & Hobbys', instruction: 'Match hobbies', answer: '', context: 'Fußball:Fodbold|Singen:Synge|Tanzen:Danse|Schwimmen:Svømme|Malen:Male|Lesen:Læse' },
    { id: 'de4-me5', type: 'Memory', question: 'Årstider & Vejr', instruction: 'Match seasons/weather', answer: '', context: 'Winter:Vinter|Sommer:Sommer|Regen:Regn|Sonne:Sol|Kalt:Koldt|Heiß:Varmt' },
  ],
  5: [
    { id: 'de5-me1', type: 'Memory', question: 'Grammatik: Substantiver', instruction: 'Store begyndelsesbogstaver', answer: '', context: 'Haus:Das Haus|Schule:Die Schule|Apfel:Der Apfel|Kind:Das Kind|Frau:Die Frau|Mann:Der Mann' },
    { id: 'de5-me2', type: 'Memory', question: 'Essen & Trinken', instruction: 'Match food', answer: '', context: 'Brot:Brot|Apfel:Apfel|Wasser:Wasser|Milch:Milch|Käse:Käse|Kuchen:Kuchen' },
    { id: 'de5-me3', type: 'Memory', question: 'Körperteile', instruction: 'Match body parts', answer: '', context: 'Hand:Hand|Fuß:Fuß|Kopf:Kopf|Auge:Auge|Nase:Nase|Mund:Mund' },
  ],
  6: [
    { id: 'de6-me1', type: 'Memory', question: 'Begegnungen', instruction: 'Match hilsner', answer: '', context: 'Guten Tag:Goddag|Hallo:Hej|Wie geht es dir?:Hvordan går det?|Mir geht es gut:Jeg har det godt|Tschüss:Farvel|Auf Wiedersehen:På gensyn' },
    { id: 'de6-me2', type: 'Memory', question: 'Meine Schule: Schultüte', instruction: 'Match school items', answer: '', context: 'Schultüte:Kræmmerhus|Stundenplan:Skema|Mathe:Matematik|Deutsch:Tysk|Pause:Pause|Klassenzimmer:Klasselov' },
    { id: 'de6-me3', type: 'Memory', question: 'Taschengeld & Freizeit', instruction: 'Match job/money', answer: '', context: 'Job:Arbeid|Geld:Penge|Sparen:Spare|Kaufen:Købe|Teuer:Dyr|Billig:Billig' },
    { id: 'de6-me4', type: 'Memory', question: 'Weihnachten & Silvester', instruction: 'Match holiday words', answer: '', context: 'Weihnachtsbaum:Juletræ|Geschenk:Gave|Feuerwerk:Fyrværkeri|Neujahr:Nytår|Vorsatz:Forsæt|Sekt:Bobler' },
    { id: 'de6-me5', type: 'Memory', question: 'Eisdiele & Essen', instruction: 'Match ice cream shop terms', answer: '', context: 'Kugel:Kugle|Waffel:Vaffel|Schokolade:Chokolade|Vanille:Vanilje|Erdbeere:Jordbær|Zitrone:Citron' },
  ],
  7: [
    { id: 'de7-me1', type: 'Memory', question: 'Körper & Gesundheit', instruction: 'Match health terms', answer: '', context: 'Gesund:Sund|Krank:Syg|Arzt:Læge|Medizin:Medicin|Apotheke:Apotek|Fitness:Træning' },
    { id: 'de7-me2', type: 'Memory', question: 'Landeskunde: Berlin', instruction: 'Match Berlin sights', answer: '', context: 'Fernsehturm:TV-tårn|Mauer:Mur|Brandenburger Tor:Port|Spree:Flod|Hauptstadt:Hovedstad|Kiez:Kvarter' },
    { id: 'de7-me3', type: 'Memory', question: 'Grammatik: Noun Categories', instruction: 'Match gender', answer: '', context: 'Maskulin:Der|Feminin:Die|Neutrum:Das|Plural:Die|Substantiv:Navneord|Großschreibung:Stort bogstav' },
    { id: 'de7-me4', type: 'Memory', question: 'Märchen & Grimm', instruction: 'Match fairytales', answer: '', context: 'Wolf:Ulv|Hexe:Heks|Prinz:Prins|Schloss:Slot|Grimm:Brødre|Wald:Skov' },
    { id: 'de7-me5', type: 'Memory', question: 'Hamborg & Østrig', instruction: 'Match places', answer: '', context: 'Hafen:Havn|Alster:Sø|Wien:Hovedstad|Alpen:Bjerge|Sachertorte:Kage|Mozart:Musik' },
  ],
  8: [
    { id: 'de8-me1', type: 'Memory', question: 'Horror & Grusel', instruction: 'Match spooky words', answer: '', context: 'Geist:Spøgelse|Angst:Frygt|Dunkel:Mørk|Blut:Blod|Vampir:Vampyr|Gruselig:Uhyggelig' },
    { id: 'de8-me2', type: 'Memory', question: 'Umwelt & Klima', instruction: 'Match eco words', answer: '', context: 'Müll:Affald|Recycling:Genbrug|Wasser:Vand|Erde:Jord|Rettung:Redning|Klima:Klima' },
    { id: 'de8-me3', type: 'Memory', question: 'Geschichte: Anne Frank', instruction: 'Match WWII words', answer: '', context: 'Tagebuch:Dagbog|Versteck:Skjulested|Krieg:Krig|Frieden:Fred|Jude:Jøde|Zweiter Weltkrieg:WW2' },
    { id: 'de8-me4', type: 'Memory', question: 'Berliner Mauer', instruction: 'Match Wall history', answer: '', context: 'Ost:Øst|West:Vest|Grenze:Grænse|Fall:Fald|Einheit:Enhed|DDR:DDR' },
    { id: 'de8-me5', type: 'Memory', question: 'Musik & Rammstein', instruction: 'Match music terms', answer: '', context: 'Band:Gruppe|Sänger:Sanger|Lied:Sang|Konzert:Koncert|Bühne:Scene|Gitarre:Guitar' },
  ],
  9: [
    { id: 'de9-me1', type: 'Memory', question: 'Identität & Teenager', instruction: 'Match social terms', answer: '', context: 'Liebe:Kærlighed|Dating:Dating|Zukunft:Fremtid|Gefühl:Følelse|Selbst:Selv|Einsam:Ensom' },
    { id: 'de9-me2', type: 'Memory', question: 'Online Leben', instruction: 'Match digital terms', answer: '', context: 'Social Media:SoMe|Selfie:Billede|Handy:Mobil|Internet:Internet|KI:AI|Sicherheit:Sikkerhed' },
    { id: 'de9-me3', type: 'Memory', question: 'Geschichte: Wunden', instruction: 'Match political history', answer: '', context: 'Blockade:Blokade|Luftbrücke:Luftbro|RAF:Terror|Widerstand:Modstand|Gedenken:Mindes|Opfer:Offer' },
    { id: 'de9-me4', type: 'Memory', question: 'Hygge & Kultur', instruction: 'Match culture', answer: '', context: 'Gemütlich:Hyggeligt|Tradition:Tradition|Dänemark:Danmark|Nationalität:Nationalitet|Sprache:Sprog|Verbindung:Forbindelse' },
    { id: 'de9-me5', type: 'Memory', question: 'Film & Sido', instruction: 'Match media/rap', answer: '', context: 'Regisseur:Instruktør|Schauspieler:Skuespiller|Rapper:Rapper|Maske:Maske|Leben:Liv|Text:Tekst' },
  ],
  10: [
    { id: 'de10-me1', type: 'Memory', question: 'Globalisierung', instruction: 'Finde die Paare', answer: '', context: 'Welt:Verden|Handel:Handel|Grenze:Grænse|Internet:Internet|Kultur:Kultur|Austausch:Udveksling' },
    { id: 'de10-me2', type: 'Memory', question: 'Klimawandel', instruction: 'Finde die Paare', answer: '', context: 'Erwärmung:Opvarmning|CO2:CO2|Umwelt:Miljø|Natur:Natur|Schutz:Beskyttelse|Energie:Energi' },
    { id: 'de10-me3', type: 'Memory', question: 'Nachhaltigkeit', instruction: 'Finde die Paare', answer: '', context: 'Zukunft:Fremtid|Ressourcen:Ressourcer|Bio:Bio|Öko:Øko|Recycling:Genbrug|Verantwortung:Ansvar' },
    { id: 'de10-me4', type: 'Memory', question: 'Demokratie', instruction: 'Finde die Paare', answer: '', context: 'Wahl:Valg|Stimme:Stemme|Politik:Politik|Freiheit:Frihed|Recht:Ret|Gesetz:Lov' },
    { id: 'de10-me5', type: 'Memory', question: 'Künstliche Intelligenz', instruction: 'Finde die Paare', answer: '', context: 'KI:AI|Computer:Computer|Daten:Data|Algorithmus:Algoritme|Zukunft:Fremtid|Roboter:Robot' },
    { id: 'de10-me6', type: 'Memory', question: 'Soziale Netzwerke', instruction: 'Finde die Paare', answer: '', context: 'Media:Medier|Profil:Profil|Post:Opslag|Like:Like|Online:Online|Sicherheit:Sikkerhed' },
    { id: 'de10-me7', type: 'Memory', question: 'Wirtschaft', instruction: 'Finde die Paare', answer: '', context: 'Geld:Penge|Bank:Bank|Markt:Marked|Preis:Pris|Job:Job|Firma:Firma' },
    { id: 'de10-me8', type: 'Memory', question: 'Gesellschaft', instruction: 'Finde die Paare', answer: '', context: 'Mensch:Menneske|Gruppe:Gruppe|Norm:Norm|Wert:Værdi|Vielfalt:Mangfoldighed|Integration:Integration' },
    { id: 'de10-me9', type: 'Memory', question: 'Bildung', instruction: 'Finde die Paare', answer: '', context: 'Schule:Skole|Uni:Uni|Lernen:Lære|Diplom:Diplom|Wissen:Viden|Erfolg:Succes' },
    { id: 'de10-me10', type: 'Memory', question: 'Ethik', instruction: 'Finde die Paare', answer: '', context: 'Moral:Moral|Gut:Godt|Böse:Ondt|Wahl:Valg|Gewissen:Samvittighed|Frage:Spørgsmål' },
    { id: 'de10-me11', type: 'Memory', question: 'Menschenrechte', instruction: 'Finde die Paare', answer: '', context: 'Recht:Ret|Würde:Værdighed|Leben:Liv|Gleichheit:Lighed|Freiheit:Frihed|Schutz:Beskyttelse' },
    { id: 'de10-me12', type: 'Memory', question: 'Migration', instruction: 'Finde die Paare', answer: '', context: 'Heimat:Hjemland|Fremde:Fremmede|Flucht:Flugt|Grenze:Grænse|Visum:Visum|Reise:Rejse' },
    { id: 'de10-me13', type: 'Memory', question: 'Innovation', instruction: 'Finde die Paare', answer: '', context: 'Idee:Ide|Neu:Ny|Erfindung:Opfindelse|Technik:Teknik|Fortschritt:Fremskridt|Plan:Plan' },
    { id: 'de10-me14', type: 'Memory', question: 'Medienkritik', instruction: 'Finde die Paare', answer: '', context: 'Fake:Falsk|Fakt:Fakta|Quelle:Kilde|Information:Information|Lüge:Løgn|Wahrheit:Sandhed' },
    { id: 'de10-me15', type: 'Memory', question: 'Berufswelt', instruction: 'Finde die Paare', answer: '', context: 'Karriere:Karriere|Gehalt:Løn|Büro:Kontor|Chef:Chef|Team:Team|Arbeit:Arbejde' },
    { id: 'de10-me16', type: 'Memory', question: 'Literatur', instruction: 'Finde die Paare', answer: '', context: 'Roman:Roman|Autor:Forfatter|Buch:Bog|Text:Tekst|Lesen:Læse|Geschichte:Historie' },
    { id: 'de10-me17', type: 'Memory', question: 'Wissenschaft', instruction: 'Finde die Paare', answer: '', context: 'Labor:Laboratorium|Forschung:Forskning|Hypothese:Hypotese|Beweis:Bevis|Theorie:Teori|Faktum:Faktum' },
    { id: 'de10-me18', type: 'Memory', question: 'Philosophie', instruction: 'Finde die Paare', answer: '', context: 'Denken:Tænke|Logik:Logik|Geist:Ånd|Existenz:Eksistens|Frage:Spørgsmål|Antwort:Svar' },
    { id: 'de10-me19', type: 'Memory', question: 'Psychologie', instruction: 'Finde die Paare', answer: '', context: 'Seele:Sjæl|Gefühl:Følelse|Angst:Frygt|Glück:Lykke|Traum:Drøm|Ich:Jeg' },
    { id: 'de10-me20', type: 'Memory', question: 'Soziologie', instruction: 'Finde die Paare', answer: '', context: 'Klasse:Klasse|System:System|Rolle:Rolle|Macht:Magt|Struktur:Struktur|Wandel:Skift' },
    { id: 'de10-me21', type: 'Memory', question: 'Rechtssystem', instruction: 'Finde die Paare', answer: '', context: 'Gericht:Ret|Richter:Dommer|Anwalt:Advokat|Urteil:Dom|Strafe:Straf|Klage:Klage' },
    { id: 'de10-me22', type: 'Memory', question: 'Internationalpolitik', instruction: 'Finde die Paare', answer: '', context: 'EU:EU|UN:FN|Bündnis:Alliance|Frieden:Fred|Krieg:Krig|Diplomatie:Diplomati' },
    { id: 'de10-me23', type: 'Memory', question: 'Biodiversität', instruction: 'Finde die Paare', answer: '', context: 'Art:Art|Vielfalt:Mangfoldighed|Wald:Skov|Ozean:Hav|Tier:Dyr|Pflanze:Plante' },
    { id: 'de10-me24', type: 'Memory', question: 'Energiequellen', instruction: 'Finde die Paare', answer: '', context: 'Sonne:Sol|Wind:Vind|Atom:Atom|Kohle:Kul|Öl:Olie|Gas:Gas' },
    { id: 'de10-me25', type: 'Memory', question: 'Kulturphänomene', instruction: 'Finde die Paare', answer: '', context: 'Pop:Pop|Tradition:Tradition|Trend:Trend|Mode:Mode|Kunst:Kunst|Musik:Musik' },
    { id: 'de10-me26', type: 'Memory', question: 'Religionswissenschaft', instruction: 'Finde die Paare', answer: '', context: 'Glauben:Tro|Gott:Gud|Kirke:Kirke|Bibel:Bibel|Koran:Koran|Kult:Kult' },
    { id: 'de10-me27', type: 'Memory', question: 'Sprachwissenschaft', instruction: 'Finde die Paare', answer: '', context: 'Grammatik:Grammatik|Wort:Ord|Satz:Sætning|Sinn:Mening|Zeichen:Tegn|Laut:Lyd' },
    { id: 'de10-me28', type: 'Memory', question: 'Architektur', instruction: 'Finde die Paare', answer: '', context: 'Bau:Byggeri|Stil:Stil|Haus:Hus|Stadt:By|Plan:Plan|Design:Design' },
    { id: 'de10-me29', type: 'Memory', question: 'Medizin', instruction: 'Finde die Paare', answer: '', context: 'Gesundheit:Sundhed|Krankheit:Sygdom|Heilung:Helbredelse|Arzt:Læge|Klinik:Klinik|Pille:Pille' },
    { id: 'de10-me30', type: 'Memory', question: 'Raumfahrt', instruction: 'Finde die Paare', answer: '', context: 'Mars:Mars|Mond:Måne|Sterne:Stjerner|Rakete:Raket|Weltraum:Rummet|Planet:Planet' },
    { id: 'de10-me31', type: 'Memory', question: 'Identität (vertieft)', instruction: 'Finde die Paare', answer: '', context: 'Ich:Mig|Selbst:Selv|Ego:Ego|Wesen:Væsen|Natur:Natur|Kultur:Kultur' },
    { id: 'de10-me32', type: 'Memory', question: 'Zeitmanagement', instruction: 'Finde die Paare', answer: '', context: 'Plan:Plan|Uhr:Ur|Frist:Frist|Dauer:Varighed|Moment:Øjeblik|Ewigkeit:Evighed' },
    { id: 'de10-me33', type: 'Memory', question: 'Kommunikationstheorie', instruction: 'Finde die Paare', answer: '', context: 'Sender:Sender|Empfänger:Modtager|Code:Kode|Medium:Medium|Lärm:Støj|Feedback:Respons' },
    { id: 'de10-me34', type: 'Memory', question: 'Logik', instruction: 'Finde die Paare', answer: '', context: 'Wahr:Sandt|Falsch:Falsk|Grund:Grund|Folge:Følge|Schluss:Konklusion|Argument:Argument' },
    { id: 'de10-me35', type: 'Memory', question: 'Ästhetik', instruction: 'Finde die Paare', answer: '', context: 'Schön:Smukt|Hässlich:Grimt|Form:Form|Farbe:Farve|Stil:Stil|Geschmack:Smag' },
    { id: 'de10-me36', type: 'Memory', question: 'Städtebau', instruction: 'Finde die Paare', answer: '', context: 'Zentrum:Centrum|Vorort:Forstad|Platz:Plads|Park:Park|Straße:Vej|Viertel:Kvarter' },
    { id: 'de10-me37', type: 'Memory', question: 'Demographie', instruction: 'Finde die Paare', answer: '', context: 'Geburt:Fødsel|Tod:Død|Alter:Alder|Jugend:Ungdom|Zahl:Tal|Wachstum:Vækst' },
    { id: 'de10-me38', type: 'Memory', question: 'Ökologie', instruction: 'Finde die Paare', answer: '', context: 'Kreislauf:Kredsløb|Schutz:Beskyttelse|Wald:Skov|Meer:Hav|Luft:Luft|Boden:Jord' },
    { id: 'de10-me39', type: 'Memory', question: 'Mythologie', instruction: 'Finde die Paare', answer: '', context: 'Held:Helt|Sage:Sagn|Legende:Legende|Gott:Gud|Ungeheuer:Uhyre|Symbol:Symbol' },
    { id: 'de10-me40', type: 'Memory', question: 'Gerechtigkeit (vertieft)', instruction: 'Finde die Paare', answer: '', context: 'Fair:Fair|Gleich:Ens|Recht:Ret|Urteil:Dom|Lohn:Løn|Strafe:Straf' },
    { id: 'de10-me41', type: 'Memory', question: 'Finanzwelt', instruction: 'Finde die Paare', answer: '', context: 'Aktie:Aktie|Börse:Børs|Zins:Rente|Invest:Investering|Gewinn:Overskud|Verlust:Tab' },
    { id: 'de10-me42', type: 'Memory', question: 'Digitaler Wandel', instruction: 'Finde die Paare', answer: '', context: 'Wandel:Skift|Techno:Tekno|Smart:Smart|Virtual:Virtuel|Cloud:Sky|Bit:Bit' },
    { id: 'de10-me43', type: 'Memory', question: 'Kreativwirtschaft', instruction: 'Finde die Paare', answer: '', context: 'Idee:Ide|Design:Design|Medien:Medier|Kultur:Kultur|Film:Film|Spiel:Spil' },
    { id: 'de10-me44', type: 'Memory', question: 'Zivilcourage', instruction: 'Finde die Paare', answer: '', context: 'Mut:Mod|Helfen:Hjælpe|Sehen:Se|Handeln:Handle|Stopp:Stop|Wort:Ord' },
    { id: 'de10-me45', type: 'Memory', question: 'Globales Lernen', instruction: 'Finde die Paare', answer: '', context: 'Perspektive:Perspektiv|Welt:Verden|Lernen:Lære|Verstehen:Forstå|Handeln:Handle|Zukunft:Fremtid' },
    { id: 'de10-me46', type: 'Memory', question: 'Utopie & Dystopie', instruction: 'Finde die Paare', answer: '', context: 'Traum:Drøm|Alptraum:Mareridt|Perfekt:Perfekt|Chaos:Kaos|Zukunft:Fremtid|Staat:Stat' },
    { id: 'de10-me47', type: 'Memory', question: 'Kulturschock', instruction: 'Finde die Paare', answer: '', context: 'Fremd:Fremmed|Neu:Nyt|Angst:Frygt|Staunen:Forundring|Anpassen:Tilpasse|Lernen:Lære' },
    { id: 'de10-me48', type: 'Memory', question: 'Solidarität (vertieft)', instruction: 'Finde die Paare', answer: '', context: 'Zusammen:Sammen|Halt:Hold|Hilfe:Hjælp|Teilen:Dele|Kraft:Kraft|Einheit:Enhed' },
    { id: 'de10-me49', type: 'Memory', question: 'Rhetorik (vertieft)', instruction: 'Finde die Paare', answer: '', context: 'Rede:Tale|Wort:Ord|Überzeugen:Overbevise|Stimme:Stemme|Pause:Pause|Geste:Gis' },
    { id: 'de10-me50', type: 'Memory', question: 'Abschlussreflexion', instruction: 'Finde die Paare', answer: '', context: 'Ende:Slut|Start:Start|Weg:Vej|Ziel:Mål|Wissen:Viden|Können:Kunne' },
  ],
};
