/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const ENGELSK_READING: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'en0-r1', type: 'Reading', question: 'I see a cat.', answer: 'cat', instruction: 'Read' },
    { id: 'en0-r2', type: 'Reading', question: 'The sun is hot.', answer: 'sun', instruction: 'Read' },
    { id: 'en0-r3', type: 'Reading', question: 'My dog is big.', answer: 'dog', instruction: 'Read' },
    { id: 'en0-r4', type: 'Reading', question: 'A red apple.', answer: 'apple', instruction: 'Read' },
    { id: 'en0-r5', type: 'Reading', question: 'I am happy.', answer: 'happy', instruction: 'Read' },
    { id: 'en0-r6', type: 'Reading', question: 'Go to bed.', answer: 'bed', instruction: 'Read' },
    { id: 'en0-r7', type: 'Reading', question: 'Run in the sun.', answer: 'run', instruction: 'Read' },
    { id: 'en0-r8', type: 'Reading', question: 'A blue car.', answer: 'car', instruction: 'Read' },
    { id: 'en0-r9', type: 'Reading', question: 'Sit on the mat.', answer: 'mat', instruction: 'Read' },
    { id: 'en0-r10', type: 'Reading', question: 'The pig is fat.', answer: 'pig', instruction: 'Read' },
    { id: 'en0-r11', type: 'Reading', question: 'Look at the moon.', answer: 'moon', instruction: 'Read' },
    { id: 'en0-r12', type: 'Reading', question: 'A hot cup.', answer: 'cup', instruction: 'Read' },
    { id: 'en0-r13', type: 'Reading', question: 'I like milk.', answer: 'milk', instruction: 'Read' },
    { id: 'en0-r14', type: 'Reading', question: 'Open the door.', answer: 'door', instruction: 'Read' },
    { id: 'en0-r15', type: 'Reading', question: 'A yellow bird.', answer: 'bird', instruction: 'Read' },
    { id: 'en0-r16', type: 'Reading', question: 'In the box.', answer: 'box', instruction: 'Read' },
    { id: 'en0-r17', type: 'Reading', question: 'See the sea.', answer: 'sea', instruction: 'Read' },
    { id: 'en0-r18', type: 'Reading', question: 'A green frog.', answer: 'frog', instruction: 'Read' },
    { id: 'en0-r19', type: 'Reading', question: 'Play with a ball.', answer: 'ball', instruction: 'Read' },
    { id: 'en0-r20', type: 'Reading', question: 'Sing a song.', answer: 'song', instruction: 'Read' },
    { id: 'en0-r21', type: 'Reading', question: 'A little bug.', answer: 'bug', instruction: 'Read' },
    { id: 'en0-r22', type: 'Reading', question: 'He is tall.', answer: 'tall', instruction: 'Read' },
    { id: 'en0-r23', type: 'Reading', question: 'She is small.', answer: 'small', instruction: 'Read' },
    { id: 'en0-r24', type: 'Reading', question: 'Eat a nut.', answer: 'nut', instruction: 'Read' },
    { id: 'en0-r25', type: 'Reading', question: 'The sky is up.', answer: 'up', instruction: 'Read' },
    { id: 'en0-r26', type: 'Reading', question: 'Down on the ground.', answer: 'down', instruction: 'Read' },
    { id: 'en0-r27', type: 'Reading', question: 'One, two, three.', answer: 'three', instruction: 'Read' },
    { id: 'en0-r28', type: 'Reading', question: 'Ten little toes.', answer: 'toes', instruction: 'Read' },
    { id: 'en0-r29', type: 'Reading', question: 'Five big fingers.', answer: 'fingers', instruction: 'Read' },
    { id: 'en0-r30', type: 'Reading', question: 'Wash your face.', answer: 'face', instruction: 'Read' },
    { id: 'en0-r31', type: 'Reading', question: 'Brush your hair.', answer: 'hair', instruction: 'Read' },
    { id: 'en0-r32', type: 'Reading', question: 'A clean room.', answer: 'room', instruction: 'Read' },
    { id: 'en0-r33', type: 'Reading', question: 'A fast bus.', answer: 'bus', instruction: 'Read' },
    { id: 'en0-r34', type: 'Reading', question: 'Stop at the sign.', answer: 'stop', instruction: 'Read' },
    { id: 'en0-r35', type: 'Reading', question: 'Go on green.', answer: 'go', instruction: 'Read' },
    { id: 'en0-r36', type: 'Reading', question: 'Wait for the train.', answer: 'wait', instruction: 'Read' },
    { id: 'en0-r37', type: 'Reading', question: 'Fly in a plane.', answer: 'fly', instruction: 'Read' },
    { id: 'en0-r38', type: 'Reading', question: 'Swim in the lake.', answer: 'swim', instruction: 'Read' },
    { id: 'en0-r39', type: 'Reading', question: 'Bake a cake.', answer: 'bake', instruction: 'Read' },
    { id: 'en0-r40', type: 'Reading', question: 'Make a wish.', answer: 'wish', instruction: 'Read' },
    { id: 'en0-r41', type: 'Reading', question: 'Catch a fish.', answer: 'fish', instruction: 'Read' },
    { id: 'en0-r42', type: 'Reading', question: 'A sweet dish.', answer: 'sweet', instruction: 'Read' },
    { id: 'en0-r43', type: 'Reading', question: 'Soft white snow.', answer: 'soft', instruction: 'Read' },
    { id: 'en0-r44', type: 'Reading', question: 'Watch the grass grow.', answer: 'grow', instruction: 'Read' },
    { id: 'en0-r45', type: 'Reading', question: 'Blow the wind.', answer: 'blow', instruction: 'Read' },
    { id: 'en0-r46', type: 'Reading', question: 'Kind and nice.', answer: 'kind', instruction: 'Read' },
    { id: 'en0-r47', type: 'Reading', question: 'Cold as ice.', answer: 'ice', instruction: 'Read' },
    { id: 'en0-r48', type: 'Reading', question: 'Sugar and spice.', answer: 'sugar', instruction: 'Read' },
    { id: 'en0-r49', type: 'Reading', question: 'Mice love cheese.', answer: 'mice', instruction: 'Read' },
    { id: 'en0-r50', type: 'Reading', question: 'Say yes please.', answer: 'please', instruction: 'Read' },
    { id: 'en0-r51', type: 'Reading', question: 'Trees in the breeze.', answer: 'trees', instruction: 'Read' },
  ],
  1: [
    { id: 'en1-r1', type: 'Reading', question: 'The cat is on the mat.', answer: 'on the mat', instruction: 'Read' },
    { id: 'en1-r2', type: 'Reading', question: 'A big red ball is here.', answer: 'red ball', instruction: 'Read' },
    { id: 'en1-r3', type: 'Reading', question: 'I have a little sister.', answer: 'little sister', instruction: 'Read' },
    { id: 'en1-r4', type: 'Reading', question: 'We can play today.', answer: 'play today', instruction: 'Read' },
    { id: 'en1-r5', type: 'Reading', question: 'The sun is in the sky.', answer: 'in the sky', instruction: 'Read' },
    { id: 'en1-r6', type: 'Reading', question: 'It is a sunny day.', answer: 'sunny day', instruction: 'Read' },
    { id: 'en1-r7', type: 'Reading', question: 'Look at the tall tree.', answer: 'tall tree', instruction: 'Read' },
    { id: 'en1-r8', type: 'Reading', question: 'I see a brown dog.', answer: 'brown dog', instruction: 'Read' },
    { id: 'en1-r9', type: 'Reading', question: 'The dog says woof.', answer: 'woof', instruction: 'Read' },
    { id: 'en1-r10', type: 'Reading', question: 'My mom is very kind.', answer: 'very kind', instruction: 'Read' },
    { id: 'en1-r11', type: 'Reading', question: 'Dad works in the city.', answer: 'in the city', instruction: 'Read' },
    { id: 'en1-r12', type: 'Reading', question: 'We go to the park.', answer: 'to the park', instruction: 'Read' },
    { id: 'en1-r13', type: 'Reading', question: 'I like to jump high.', answer: 'jump high', instruction: 'Read' },
    { id: 'en1-r14', type: 'Reading', question: 'She plays with a doll.', answer: 'with a doll', instruction: 'Read' },
    { id: 'en1-r15', type: 'Reading', question: 'He has a fast car.', answer: 'fast car', instruction: 'Read' },
    { id: 'en1-r16', type: 'Reading', question: 'The water is blue.', answer: 'water is blue', instruction: 'Read' },
    { id: 'en1-r17', type: 'Reading', question: 'Fishes swim in the sea.', answer: 'swim in the sea', instruction: 'Read' },
    { id: 'en1-r18', type: 'Reading', question: 'Can you help me?', answer: 'help me', instruction: 'Read' },
    { id: 'en1-r19', type: 'Reading', question: 'I want to eat now.', answer: 'eat now', instruction: 'Read' },
    { id: 'en1-r20', type: 'Reading', question: 'Apple juice is sweet.', answer: 'apple juice', instruction: 'Read' },
    { id: 'en1-r21', type: 'Reading', question: 'Milk is white and good.', answer: 'milk is white', instruction: 'Read' },
    { id: 'en1-r22', type: 'Reading', question: 'A bird is in the nest.', answer: 'in the nest', instruction: 'Read' },
    { id: 'en1-r23', type: 'Reading', question: 'The moon is very bright.', answer: 'very bright', instruction: 'Read' },
    { id: 'en1-r24', type: 'Reading', question: 'Good night to everyone.', answer: 'good night', instruction: 'Read' },
    { id: 'en1-r25', type: 'Reading', question: 'Time to go to sleep.', answer: 'to sleep', instruction: 'Read' },
    { id: 'en1-r26', type: 'Reading', question: 'Wake up in the morning.', answer: 'wake up', instruction: 'Read' },
    { id: 'en1-r27', type: 'Reading', question: 'The grass is green.', answer: 'grass is green', instruction: 'Read' },
    { id: 'en1-r28', type: 'Reading', question: 'Yellow flowers grow.', answer: 'yellow flowers', instruction: 'Read' },
    { id: 'en1-r29', type: 'Reading', question: 'I have ten fingers.', answer: 'ten fingers', instruction: 'Read' },
    { id: 'en1-r30', type: 'Reading', question: 'Smile for the photo.', answer: 'smile', instruction: 'Read' },
    { id: 'en1-r31', type: 'Reading', question: 'A big fat pig.', answer: 'fat pig', instruction: 'Read' },
    { id: 'en1-r32', type: 'Reading', question: 'Horses can run fast.', answer: 'run fast', instruction: 'Read' },
    { id: 'en1-r33', type: 'Reading', question: 'Sheep are very soft.', answer: 'very soft', instruction: 'Read' },
    { id: 'en1-r34', type: 'Reading', question: 'The cow says moo.', answer: 'moo', instruction: 'Read' },
    { id: 'en1-r35', type: 'Reading', question: 'A duck is in the pond.', answer: 'in the pond', instruction: 'Read' },
    { id: 'en1-r36', type: 'Reading', question: 'Rain falls from sky.', answer: 'rain falls', instruction: 'Read' },
    { id: 'en1-r37', type: 'Reading', question: 'Clouds are big and white.', answer: 'big and white', instruction: 'Read' },
    { id: 'en1-r38', type: 'Reading', question: 'I wear a warm coat.', answer: 'warm coat', instruction: 'Read' },
    { id: 'en1-r39', type: 'Reading', question: 'Hat on my head.', answer: 'on my head', instruction: 'Read' },
    { id: 'en1-r40', type: 'Reading', question: 'Shoes on my feet.', answer: 'on my feet', instruction: 'Read' },
    { id: 'en1-r41', type: 'Reading', question: 'I jump in puddles.', answer: 'jump in puddles', instruction: 'Read' },
    { id: 'en1-r42', type: 'Reading', question: 'It is a lot of fun.', answer: 'lot of fun', instruction: 'Read' },
    { id: 'en1-r43', type: 'Reading', question: 'My house is small.', answer: 'house is small', instruction: 'Read' },
    { id: 'en1-r44', type: 'Reading', question: 'Open your new book.', answer: 'new book', instruction: 'Read' },
    { id: 'en1-r45', type: 'Reading', question: 'Draw a pretty flower.', answer: 'pretty flower', instruction: 'Read' },
    { id: 'en1-r46', type: 'Reading', question: 'Sit down on a chair.', answer: 'on a chair', instruction: 'Read' },
    { id: 'en1-r47', type: 'Reading', question: 'The food is on table.', answer: 'on table', instruction: 'Read' },
    { id: 'en1-r48', type: 'Reading', question: 'Give me a hug.', answer: 'a hug', instruction: 'Read' },
    { id: 'en1-r49', type: 'Reading', question: 'I love my family.', answer: 'my family', instruction: 'Read' },
    { id: 'en1-r50', type: 'Reading', question: 'We are moving now.', answer: 'moving now', instruction: 'Read' },
    { id: 'en1-r51', type: 'Reading', question: 'This is the end.', answer: 'the end', instruction: 'Read' },
  ],
  3: [
    { id: 'en3-r1', type: 'Reading', question: 'I like to play outside with my friends after school.', answer: 'play outside', instruction: 'Friends' },
    { id: 'en3-r2', type: 'Reading', question: 'Reading stories helps us learn many new English words.', answer: 'learn new words', instruction: 'Books' },
    { id: 'en3-r3', type: 'Reading', question: 'My favorite color is bright blue like the summer sky.', answer: 'bright blue', instruction: 'Colors' },
    { id: 'en3-r4', type: 'Reading', question: 'We have a big breakfast every Sunday morning together.', answer: 'big breakfast', instruction: 'Family' },
    { id: 'en3-r5', type: 'Reading', question: 'Summer holidays are great for swimming in the pool.', answer: 'swimming in pool', instruction: 'Holidays' },
    { id: 'en3-r6', type: 'Reading', question: 'I enjoy drawing pictures of animals and tall trees.', answer: 'drawing pictures', instruction: 'Hobbies' },
    { id: 'en3-r7', type: 'Reading', question: 'Eating fresh fruit is very good for your health.', answer: 'good for health', instruction: 'Health' },
    { id: 'en3-r8', type: 'Reading', question: 'Can you please pass me the salt for my soup?', answer: 'pass the salt', instruction: 'Eating' },
    { id: 'en3-r9', type: 'Reading', question: 'The museum has many interesting historical things to see.', answer: 'historical things', instruction: 'Museum' },
    { id: 'en3-r10', type: 'Reading', question: 'I want to be a famous doctor when I grow up.', answer: 'be a doctor', instruction: 'Future' },
    { id: 'en3-r11', type: 'Reading', question: 'A library is a quiet place where you can study.', answer: 'quiet place', instruction: 'Library' },
    { id: 'en3-r12', type: 'Reading', question: 'Playing music is a fun way to spend the afternoon.', answer: 'playing music', instruction: 'Music' },
    { id: 'en3-r13', type: 'Reading', question: 'The park is full of people walking their dogs.', answer: 'walking dogs', instruction: 'Park' },
    { id: 'en3-r14', type: 'Reading', question: 'I am helping my brother with his difficult homework.', answer: 'helping brother', instruction: 'Family' },
    { id: 'en3-r15', type: 'Reading', question: 'Autumn leaves are turning orange, red and yellow.', answer: 'turning orange', instruction: 'Seasons' },
    { id: 'en3-r16', type: 'Reading', question: 'Winter is the time for warm coats and hot cocoa.', answer: 'warm coats', instruction: 'Seasons' },
    { id: 'en3-r17', type: 'Reading', question: 'Spring brings beautiful flowers and singing birds.', answer: 'beautiful flowers', instruction: 'Seasons' },
    { id: 'en3-r18', type: 'Reading', question: 'I share my toys with my little sister at home.', answer: 'share my toys', instruction: 'Family' },
    { id: 'en3-r19', type: 'Reading', question: 'Recycling helps protect our environment from pollution.', answer: 'protect environment', instruction: 'Earth' },
    { id: 'en3-r20', type: 'Reading', question: 'The supermarket is very busy on Saturday mornings.', answer: 'very busy', instruction: 'Shopping' },
    { id: 'en3-r21', type: 'Reading', question: 'Bicycles are a healthy way to travel around town.', answer: 'healthy way', instruction: 'Transport' },
    { id: 'en3-r22', type: 'Reading', question: 'I love the smell of fresh bread from the bakery.', answer: 'fresh bread', instruction: 'Shopping' },
    { id: 'en3-r23', type: 'Reading', question: 'Learning English is exciting and very useful for me.', answer: 'very useful', instruction: 'Learning' },
    { id: 'en3-r24', type: 'Reading', question: 'We should always be kind to our classmates and teachers.', answer: 'be kind', instruction: 'School' },
    { id: 'en3-r25', type: 'Reading', question: 'The post office is next to the big city hall.', answer: 'post office', instruction: 'Town' },
    { id: 'en3-r26', type: 'Reading', question: 'I brush my teeth twice a day to keep them clean.', answer: 'brush my teeth', instruction: 'Health' },
    { id: 'en3-r27', type: 'Reading', question: 'The teacher is writing on the whiteboard in class.', answer: 'writing on whiteboard', instruction: 'School' },
    { id: 'en3-r28', type: 'Reading', question: 'My grandmother tells us funny stories from the past.', answer: 'funny stories', instruction: 'Family' },
    { id: 'en3-r29', type: 'Reading', question: 'We are planning a surprise party for our friend.', answer: 'surprise party', instruction: 'Friends' },
    { id: 'en3-r30', type: 'Reading', question: 'Vegetables are important part of a balanced diet.', answer: 'balanced diet', instruction: 'Food' },
    { id: 'en3-r31', type: 'Reading', question: 'I like watching movies at the cinema with popcorn.', answer: 'watching movies', instruction: 'Leisure' },
    { id: 'en3-r32', type: 'Reading', question: 'A compass helps you find your way in the woods.', answer: 'find your way', instruction: 'Hiking' },
    { id: 'en3-r33', type: 'Reading', question: 'Rainy days are perfect for playing board games.', answer: 'board games', instruction: 'Leisure' },
    { id: 'en3-r34', type: 'Reading', question: 'The baker makes delicious cakes and sweet pastries.', answer: 'delicious cakes', instruction: 'Food' },
    { id: 'en3-r35', type: 'Reading', question: 'A doctor helps people who are feeling sick or hurt.', answer: 'helps people', instruction: 'Jobs' },
    { id: 'en3-r36', type: 'Reading', question: 'Firefighters work hard to keep our city safe.', answer: 'keep city safe', instruction: 'Jobs' },
    { id: 'en3-r37', type: 'Reading', question: 'Police officers help us when we are in trouble.', answer: 'help us', instruction: 'Jobs' },
    { id: 'en3-r38', type: 'Reading', question: 'I want to travel to many different countries.', answer: 'travel countries', instruction: 'Travel' },
    { id: 'en3-r39', type: 'Reading', question: 'My passport is ready for my next big adventure.', answer: 'big adventure', instruction: 'Travel' },
    { id: 'en3-r40', type: 'Reading', question: 'I packed my suitcase with clothes and two books.', answer: 'packed suitcase', instruction: 'Travel' },
    { id: 'en3-r41', type: 'Reading', question: 'The airplane is flying high above the white clouds.', answer: 'flying high', instruction: 'Transport' },
    { id: 'en3-r42', type: 'Reading', question: 'Ships carry cargo across the deep blue ocean.', answer: 'deep blue ocean', instruction: 'Transport' },
    { id: 'en3-r43', type: 'Reading', question: 'Trains are a fast way to get to the city center.', answer: 'fast way', instruction: 'Transport' },
    { id: 'en3-r44', type: 'Reading', question: 'I use a map to find the secret treasure.', answer: 'secret treasure', instruction: 'Game' },
    { id: 'en3-r45', type: 'Reading', question: 'The forest is a home to many wild animals.', answer: 'wild animals', instruction: 'Nature' },
    { id: 'en3-r46', type: 'Reading', question: 'Mountains are covered with snow during the winter.', answer: 'covered with snow', instruction: 'Nature' },
    { id: 'en3-r47', type: 'Reading', question: 'Rivers flow down from the high mountains to the sea.', answer: 'flow down', instruction: 'Nature' },
    { id: 'en3-r48', type: 'Reading', question: 'Islands are surrounded by water on all sides.', answer: 'surrounded by water', instruction: 'Geography' },
    { id: 'en3-r49', type: 'Reading', question: 'Deserts are very hot and have very little rain.', answer: 'very hot', instruction: 'Geography' },
    { id: 'en3-r50', type: 'Reading', question: 'Valleys are low areas between hills and mountains.', answer: 'low areas', instruction: 'Geography' },
    { id: 'en3-r51', type: 'Reading', question: 'Our world is a beautiful place for everyone.', answer: 'beautiful place', instruction: 'Read' },
  ],
  4: [
    { id: 'en4-r1', type: 'Reading', question: 'Nice to meet you.', answer: 'Nice to meet you', instruction: 'Greetings' },
    { id: 'en4-r2', type: 'Reading', question: 'What is your name?', answer: 'What is your name', instruction: 'Questions' },
    { id: 'en4-r3', type: 'Reading', question: 'Where are you from?', answer: 'Where are you from', instruction: 'Questions' },
    { id: 'en4-r4', type: 'Reading', question: 'How old are you?', answer: 'How old are you', instruction: 'Questions' },
    { id: 'en4-r5', type: 'Reading', question: 'What is your favorite food?', answer: 'favorite food', instruction: 'Questions' },
    { id: 'en4-r6', type: 'Reading', question: 'I enjoy swimming in the summer.', answer: 'swimming', instruction: 'Activities' },
    { id: 'en4-r7', type: 'Reading', question: 'Do you like to play football?', answer: 'play football', instruction: 'Sports' },
    { id: 'en4-r8', type: 'Reading', question: 'My hobby is playing computer games.', answer: 'computer games', instruction: 'Hobbies' },
    { id: 'en4-r9', type: 'Reading', question: 'She is my best friend at school.', answer: 'best friend', instruction: 'Social' },
    { id: 'en4-r10', type: 'Reading', question: 'We study English every Monday morning.', answer: 'every Monday', instruction: 'School' },
    { id: 'en4-r11', type: 'Reading', question: 'The weather is very sunny today.', answer: 'sunny today', instruction: 'Weather' },
    { id: 'en4-r12', type: 'Reading', question: 'I have a small brother and a big sister.', answer: 'small brother', instruction: 'Family' },
    { id: 'en4-r13', type: 'Reading', question: 'My father works in a big office.', answer: 'big office', instruction: 'Family' },
    { id: 'en4-r14', type: 'Reading', question: 'My mother is a very good cook.', answer: 'good cook', instruction: 'Family' },
    { id: 'en4-r15', type: 'Reading', question: 'We live in a nice house with a garden.', answer: 'nice house', instruction: 'Home' },
    { id: 'en4-r16', type: 'Reading', question: 'I have a black cat and a brown dog.', answer: 'black cat', instruction: 'Pets' },
    { id: 'en4-r17', type: 'Reading', question: 'Do you have any pets at home?', answer: 'any pets', instruction: 'Questions' },
    { id: 'en4-r18', type: 'Reading', question: 'I like to eat pizza and pasta.', answer: 'pizza and pasta', instruction: 'Food' },
    { id: 'en4-r19', type: 'Reading', question: 'Apple is my favorite fruit to eat.', answer: 'favorite fruit', instruction: 'Food' },
    { id: 'en4-r20', type: 'Reading', question: 'I drink water when I am thirsty.', answer: 'drink water', instruction: 'Health' },
    { id: 'en4-r21', type: 'Reading', question: 'Milk is good for your bones.', answer: 'good for bones', instruction: 'Health' },
    { id: 'en4-r22', type: 'Reading', question: 'I go to bed at nine o\'clock.', answer: 'nine o\'clock', instruction: 'Daily routine' },
    { id: 'en4-r23', type: 'Reading', question: 'I wake up at seven in the morning.', answer: 'seven in morning', instruction: 'Daily routine' },
    { id: 'en4-r24', type: 'Reading', question: 'I like my school and my teachers.', answer: 'school and teachers', instruction: 'School' },
    { id: 'en4-r25', type: 'Reading', question: 'The library is a quiet place to read.', answer: 'quiet place', instruction: 'School' },
    { id: 'en4-r26', type: 'Reading', question: 'I use a pen to write in my book.', answer: 'use a pen', instruction: 'School' },
    { id: 'en4-r27', type: 'Reading', question: 'Maths is my favorite subject at school.', answer: 'favorite subject', instruction: 'School' },
    { id: 'en4-r28', type: 'Reading', question: 'I can speak two languages fluently.', answer: 'two languages', instruction: 'Skills' },
    { id: 'en4-r29', type: 'Reading', question: 'Learning new things is very important.', answer: 'very important', instruction: 'Advice' },
    { id: 'en4-r30', type: 'Reading', question: 'The sun provides light and heat.', answer: 'light and heat', instruction: 'Science' },
    { id: 'en4-r31', type: 'Reading', question: 'Plants need water and light to grow.', answer: 'water and light', instruction: 'Science' },
    { id: 'en4-r32', type: 'Reading', question: 'The earth is round like a ball.', answer: 'earth is round', instruction: 'Science' },
    { id: 'en4-r33', type: 'Reading', question: 'I see a rainbow in the sky.', answer: 'rainbow in sky', instruction: 'Nature' },
    { id: 'en4-r34', type: 'Reading', question: 'The ocean is very deep and blue.', answer: 'deep and blue', instruction: 'Nature' },
    { id: 'en4-r35', type: 'Reading', question: 'Mountains are very high and cold.', answer: 'high and cold', instruction: 'Nature' },
    { id: 'en4-r36', type: 'Reading', question: 'I like to go hiking in the forest.', answer: 'hiking in forest', instruction: 'Activities' },
    { id: 'en4-r37', type: 'Reading', question: 'Please open the window for fresh air.', answer: 'fresh air', instruction: 'Request' },
    { id: 'en4-r38', type: 'Reading', question: 'Close the door when you leave.', answer: 'close the door', instruction: 'Request' },
    { id: 'en4-r39', type: 'Reading', question: 'Turn off the lights to save energy.', answer: 'save energy', instruction: 'Environment' },
    { id: 'en4-r40', type: 'Reading', question: 'Recycling is good for our planet.', answer: 'good for planet', instruction: 'Environment' },
    { id: 'en4-r41', type: 'Reading', question: 'I love to listen to music.', answer: 'listen to music', instruction: 'Hobbies' },
    { id: 'en4-r42', type: 'Reading', question: 'Can you play a musical instrument?', answer: 'musical instrument', instruction: 'Questions' },
    { id: 'en4-r43', type: 'Reading', question: 'I play the piano every day.', answer: 'play the piano', instruction: 'Hobbies' },
    { id: 'en4-r44', type: 'Reading', question: 'Watching movies is a lot of fun.', answer: 'lot of fun', instruction: 'Leisure' },
    { id: 'en4-r45', type: 'Reading', question: 'I like reading stories about magic.', answer: 'stories about magic', instruction: 'Reading' },
    { id: 'en4-r46', type: 'Reading', question: 'The dragon was big and green.', answer: 'big and green', instruction: 'Fiction' },
    { id: 'en4-r47', type: 'Reading', question: 'The princess lived in a castle.', answer: 'in a castle', instruction: 'Fiction' },
    { id: 'en4-r48', type: 'Reading', question: 'The knight had a shiny sword.', answer: 'shiny sword', instruction: 'Stories' },
    { id: 'en4-r49', type: 'Reading', question: 'They lived happily ever after.', answer: 'happily ever after', instruction: 'Ending' },
    { id: 'en4-r50', type: 'Reading', question: 'Dreams can come true sometimes.', answer: 'come true', instruction: 'Life' },
    { id: 'en4-r51', type: 'Reading', question: 'Always try your best in life.', answer: 'try your best', instruction: 'Advice' },
  ],
  5: [
    { id: 'en5-r1', type: 'Reading', question: 'Welcome to the capital of the UK.', answer: 'Welcome to the capital', instruction: 'Læs om London' },
    { id: 'en5-r2', type: 'Reading', question: 'The Tower of London is very old.', answer: 'Tower of London', instruction: 'History' },
    { id: 'en5-r3', type: 'Reading', question: 'Big Ben is a famous clock tower in London.', answer: 'clock tower', instruction: 'London' },
    { id: 'en5-r4', type: 'Reading', question: 'The River Thames flows through the city center.', answer: 'Thames', instruction: 'London' },
    { id: 'en5-r5', type: 'Reading', question: 'London is a very multicultural city.', answer: 'multicultural city', instruction: 'Culture' },
    { id: 'en5-r6', type: 'Reading', question: 'The Queen lived in Buckingham Palace.', answer: 'Buckingham Palace', instruction: 'Royals' },
    { id: 'en5-r7', type: 'Reading', question: 'Hyde Park is a huge green space in London.', answer: 'green space', instruction: 'London' },
    { id: 'en5-r8', type: 'Reading', question: 'Double-decker buses are red and very iconic.', answer: 'Double-decker buses', instruction: 'Transport' },
    { id: 'en5-r9', type: 'Reading', question: 'The London Eye offers a great view of the city.', answer: 'London Eye', instruction: 'Tourism' },
    { id: 'en5-r10', type: 'Reading', question: 'Stratford was the home of William Shakespeare.', answer: 'William Shakespeare', instruction: 'Literature' },
    { id: 'en5-r11', type: 'Reading', question: 'English is spoken by millions of people.', answer: 'millions of people', instruction: 'Language' },
    { id: 'en5-r12', type: 'Reading', question: 'The climate in the UK is often cool and wet.', answer: 'cool and wet', instruction: 'Weather' },
    { id: 'en5-r13', type: 'Reading', question: 'Stonehenge is a mysterious ancient stone circle.', answer: 'Stonehenge', instruction: 'History' },
    { id: 'en5-r14', type: 'Reading', question: 'Cricket is a traditional sport in England.', answer: 'Cricket', instruction: 'Sports' },
    { id: 'en5-r15', type: 'Reading', question: 'Fish and chips is a very popular British meal.', answer: 'Fish and chips', instruction: 'Food' },
    { id: 'en5-r16', type: 'Reading', question: 'Afternoon tea is a famous English tradition.', answer: 'Afternoon tea', instruction: 'Tradition' },
    { id: 'en5-r17', type: 'Reading', question: 'The Beatles were a very famous band from Liverpool.', answer: 'The Beatles', instruction: 'Music' },
    { id: 'en5-r18', type: 'Reading', question: 'London Underground is often called the Tube.', answer: 'The Tube', instruction: 'Transport' },
    { id: 'en5-r19', type: 'Reading', question: 'Wimbledon is the oldest tennis tournament.', answer: 'Wimbledon', instruction: 'Sports' },
    { id: 'en5-r20', type: 'Reading', question: 'Cambridge and Oxford are famous university cities.', answer: 'universities', instruction: 'Education' },
    { id: 'en5-r21', type: 'Reading', question: 'The Industrial Revolution started in Britain.', answer: 'Industrial Revolution', instruction: 'History' },
    { id: 'en5-r22', type: 'Reading', question: 'Halloween originated from ancient Celtic festivals.', answer: 'Halloween', instruction: 'Culture' },
    { id: 'en5-r23', type: 'Reading', question: 'Guy Fawkes Night is celebrated on November 5th.', answer: 'November 5th', instruction: 'Celebration' },
    { id: 'en5-r24', type: 'Reading', question: 'King Arthur is a legendary British figure.', answer: 'King Arthur', instruction: 'Legends' },
    { id: 'en5-r25', type: 'Reading', question: 'Blarney Stone is located in an Irish castle.', answer: 'Blarney Stone', instruction: 'Ireland' },
    { id: 'en5-r26', type: 'Reading', question: 'The Loch Ness Monster is a Scottish legend.', answer: 'Loch Ness', instruction: 'Scotland' },
    { id: 'en5-r27', type: 'Reading', question: 'Haggis is a traditional food from Scotland.', answer: 'Haggis', instruction: 'Scotland' },
    { id: 'en5-r28', type: 'Reading', question: 'Bagpipes are typical musical instruments in Scotland.', answer: 'Bagpipes', instruction: 'Music' },
    { id: 'en5-r29', type: 'Reading', question: 'Wales is known for its beautiful green valleys.', answer: 'green valleys', instruction: 'Wales' },
    { id: 'en5-r30', type: 'Reading', question: 'Welsh is a Celtic language spoken in Wales.', answer: 'Welsh', instruction: 'Language' },
    { id: 'en5-r31', type: 'Reading', question: 'Dublin is the capital city of Ireland.', answer: 'Dublin', instruction: 'Ireland' },
    { id: 'en5-r32', type: 'Reading', question: 'Shamrocks are the national symbol of Ireland.', answer: 'Shamrocks', instruction: 'Ireland' },
    { id: 'en5-r33', type: 'Reading', question: 'Saint Patrick is the patron saint of Ireland.', answer: 'Saint Patrick', instruction: 'Ireland' },
    { id: 'en5-r34', type: 'Reading', question: 'Sherlock Holmes solved crimes in London.', answer: 'Sherlock Holmes', instruction: 'Stories' },
    { id: 'en5-r35', type: 'Reading', question: 'Harry Potter was written by J.K. Rowling.', answer: 'J.K. Rowling', instruction: 'Literature' },
    { id: 'en5-r36', type: 'Reading', question: 'The Titanic was built in Belfast, Northern Ireland.', answer: 'Belfast', instruction: 'History' },
    { id: 'en5-r37', type: 'Reading', question: 'The British Museum has collections from all over world.', answer: 'British Museum', instruction: 'Culture' },
    { id: 'en5-r38', type: 'Reading', question: 'Piccadilly Circus is a busy junction in London.', answer: 'Piccadilly Circus', instruction: 'London' },
    { id: 'en5-r39', type: 'Reading', question: 'Tower Bridge can open to let large ships through.', answer: 'Tower Bridge', instruction: 'London' },
    { id: 'en5-r40', type: 'Reading', question: 'The BBC is a world-famous broadcasting company.', answer: 'BBC', instruction: 'Media' },
    { id: 'en5-r41', type: 'Reading', question: 'Tennis is played on grass at the Wimbledon club.', answer: 'grass', instruction: 'Sports' },
    { id: 'en5-r42', type: 'Reading', question: 'The White Cliffs of Dover are very famous.', answer: 'Whites Cliffs', instruction: 'Geography' },
    { id: 'en5-r43', type: 'Reading', question: 'Hadrian\'s Wall was built by the ancient Romans.', answer: 'Romans', instruction: 'History' },
    { id: 'en5-r44', type: 'Reading', question: 'Magna Carta was signed in 1215 by King John.', answer: '1215', instruction: 'History' },
    { id: 'en5-r45', type: 'Reading', question: 'The Commonwealth is a group of fifty-six states.', answer: 'Commonwealth', instruction: 'Politics' },
    { id: 'en5-r46', type: 'Reading', question: 'Notting Hill Carnival is a huge street festival.', answer: 'Carnival', instruction: 'Culture' },
    { id: 'en5-r47', type: 'Reading', question: 'Westminster Abbey is where kings are crowned.', answer: 'Westminster Abbey', instruction: 'Royals' },
    { id: 'en5-r48', type: 'Reading', question: 'The Prime Minister lives at 10 Downing Street.', answer: '10 Downing Street', instruction: 'Politics' },
    { id: 'en5-r49', type: 'Reading', question: 'Sherwood Forest was the home of Robin Hood.', answer: 'Robin Hood', instruction: 'Legends' },
    { id: 'en5-r50', type: 'Reading', question: 'Oxford Street is one of the busiest shopping streets.', answer: 'Oxford Street', instruction: 'London' },
    { id: 'en5-r51', type: 'Reading', question: 'Travel is the best way to learn about the world.', answer: 'travel', instruction: 'Advice' },
  ],
  6: [
    { id: 'en6-r1', type: 'Reading', question: 'The United States is a huge country with fifty states.', answer: 'fifty states', instruction: 'USA' },
    { id: 'en6-r2', type: 'Reading', question: 'Washington D.C. is the capital city of the USA.', answer: 'Washington D.C.', instruction: 'USA' },
    { id: 'en6-r3', type: 'Reading', question: 'New York City is often called "The Big Apple".', answer: 'Big Apple', instruction: 'Cities' },
    { id: 'en6-r4', type: 'Reading', question: 'The Statue of Liberty was a gift from France.', answer: 'Statue of Liberty', instruction: 'USA' },
    { id: 'en6-r5', type: 'Reading', question: 'The Declaration of Independence was signed in 1776.', answer: '1776', instruction: 'History' },
    { id: 'en6-r6', type: 'Reading', question: 'Hollywood is the center of the film industry.', answer: 'Hollywood', instruction: 'Culture' },
    { id: 'en6-r7', type: 'Reading', question: 'The Grand Canyon is a massive natural wonder.', answer: 'Grand Canyon', instruction: 'Nature' },
    { id: 'en6-r8', type: 'Reading', question: 'Mount Rushmore shows the faces of four presidents.', answer: 'four presidents', instruction: 'USA' },
    { id: 'en6-r9', type: 'Reading', question: 'The American flag has thirteen stripes and fifty stars.', answer: 'fifty stars', instruction: 'USA' },
    { id: 'en6-r10', type: 'Reading', question: 'The White House is the home of the US President.', answer: 'White House', instruction: 'Politics' },
    { id: 'en6-r11', type: 'Reading', question: 'Silicon Valley is famous for technology companies.', answer: 'Silicon Valley', instruction: 'Technology' },
    { id: 'en6-r12', type: 'Reading', question: 'Yellowstone was the first national park in the world.', answer: 'Yellowstone', instruction: 'Nature' },
    { id: 'en6-r13', type: 'Reading', question: 'The Mississippi is one of the longest rivers in USA.', answer: 'Mississippi', instruction: 'Geography' },
    { id: 'en6-r14', type: 'Reading', question: 'Basketball was invented by James Naismith in 1891.', answer: 'Basketball', instruction: 'Sports' },
    { id: 'en6-r15', type: 'Reading', question: 'Baseball is often called the national pastime.', answer: 'Baseball', instruction: 'Sports' },
    { id: 'en6-r16', type: 'Reading', question: 'Jazz music originated in New Orleans at early 1900s.', answer: 'Jazz', instruction: 'Music' },
    { id: 'en6-r17', type: 'Reading', question: 'The US Civil War happened from 1861 to 1865.', answer: 'Civil War', instruction: 'History' },
    { id: 'en6-r18', type: 'Reading', question: 'Martin Luther King Jr. was a civil rights leader.', answer: 'Martin Luther King', instruction: 'History' },
    { id: 'en6-r19', type: 'Reading', question: 'The moon landing happened in 1969 with Apollo 11.', answer: '1969', instruction: 'Science' },
    { id: 'en6-r20', type: 'Reading', question: 'NASA is the US space agency based in Washington.', answer: 'NASA', instruction: 'Science' },
    { id: 'en6-r21', type: 'Reading', question: 'Route 66 is a famous historic highway across USA.', answer: 'Route 66', instruction: 'Travel' },
    { id: 'en6-r22', type: 'Reading', question: 'Las Vegas is known as the entertainment capital.', answer: 'Las Vegas', instruction: 'Cities' },
    { id: 'en6-r23', type: 'Reading', question: 'The Great Lakes contain 21 percent of world fresh water.', answer: 'Great Lakes', instruction: 'Geography' },
    { id: 'en6-r24', type: 'Reading', question: 'Florida is known as "The Sunshine State".', answer: 'Sunshine State', instruction: 'States' },
    { id: 'en6-r25', type: 'Reading', question: 'Alaska is the largest state in the United States.', answer: 'Alaska', instruction: 'States' },
    { id: 'en6-r26', type: 'Reading', question: 'Hawaii is a chain of volcanic islands in Pacific.', answer: 'Hawaii', instruction: 'States' },
    { id: 'en6-r27', type: 'Reading', question: 'The Super Bowl is the most watched TV event in USA.', answer: 'Super Bowl', instruction: 'Culture' },
    { id: 'en6-r28', type: 'Reading', question: 'Thanksgiving is celebrated on the fourth Thursday.', answer: 'Thanksgiving', instruction: 'Holidays' },
    { id: 'en6-r29', type: 'Reading', question: 'Broadway is famous for its world-class theaters.', answer: 'Broadway', instruction: 'Culture' },
    { id: 'en6-r30', type: 'Reading', question: 'The Golden Gate Bridge is located in San Francisco.', answer: 'Golden Gate', instruction: 'Cities' },
    { id: 'en6-r31', type: 'Reading', question: 'Canada is the second largest country in the world.', answer: 'Canada', instruction: 'North America' },
    { id: 'en6-r32', type: 'Reading', question: 'Ottawa is the capital city of Canada.', answer: 'Ottawa', instruction: 'Canada' },
    { id: 'en6-r33', type: 'Reading', question: 'English and French are the languages of Canada.', answer: 'English and French', instruction: 'Canada' },
    { id: 'en6-r34', type: 'Reading', question: 'The maple leaf is the national symbol of Canada.', answer: 'maple leaf', instruction: 'Canada' },
    { id: 'en6-r35', type: 'Reading', question: 'Ice hockey is the national winter sport of Canada.', answer: 'Ice hockey', instruction: 'Sports' },
    { id: 'en6-r36', type: 'Reading', question: 'The Rocky Mountains run through Canada and US.', answer: 'Rocky Mountains', instruction: 'Geography' },
    { id: 'en6-r37', type: 'Reading', question: 'Niagara Falls is located on the border with USA.', answer: 'Niagara Falls', instruction: 'Geography' },
    { id: 'en6-r38', type: 'Reading', question: 'Australia is both a continent and a country.', answer: 'Australia', instruction: 'Oceania' },
    { id: 'en6-r39', type: 'Reading', question: 'Canberra is the capital city of Australia.', answer: 'Canberra', instruction: 'Australia' },
    { id: 'en6-r40', type: 'Reading', question: 'The Great Barrier Reef is a huge coral system.', answer: 'Great Barrier Reef', instruction: 'Nature' },
    { id: 'en6-r41', type: 'Reading', question: 'Sydney Opera House is a famous landmark.', answer: 'Opera House', instruction: 'Australia' },
    { id: 'en6-r42', type: 'Reading', question: 'Uluru is a massive sandstone rock in the center.', answer: 'Uluru', instruction: 'Nature' },
    { id: 'en6-r43', type: 'Reading', question: 'New Zealand consists of two main islands.', answer: 'New Zealand', instruction: 'Oceania' },
    { id: 'en6-r44', type: 'Reading', question: 'Wellington is the capital city of New Zealand.', answer: 'Wellington', instruction: 'New Zealand' },
    { id: 'en6-r45', type: 'Reading', question: 'The Maori are the indigenous people of New Zealand.', answer: 'Maori', instruction: 'Culture' },
    { id: 'en6-r46', type: 'Reading', question: 'Cape Town is one of the capitals of South Africa.', answer: 'South Africa', instruction: 'Africa' },
    { id: 'en6-r47', type: 'Reading', question: 'Nelson Mandela was a leader in South Africa.', answer: 'Nelson Mandela', instruction: 'History' },
    { id: 'en6-r48', type: 'Reading', question: 'India has the second largest population in world.', answer: 'India', instruction: 'Asia' },
    { id: 'en6-r49', type: 'Reading', question: 'New Delhi is the capital city of India.', answer: 'New Delhi', instruction: 'India' },
    { id: 'en6-r50', type: 'Reading', question: 'The Taj Mahal is a famous white marble tomb.', answer: 'Taj Mahal', instruction: 'History' },
    { id: 'en6-r51', type: 'Reading', question: 'Every country has its own unique story and path.', answer: 'unique story', instruction: 'World' },
  ],
  7: [
    { id: 'en7-r1', type: 'Reading', question: 'Global communication has been transformed by the internet.', answer: 'transformed by internet', instruction: 'Technology' },
    { id: 'en7-r2', type: 'Reading', question: 'Social media platforms allow people to connect worldwide.', answer: 'connect worldwide', instruction: 'Internet' },
    { id: 'en7-r3', type: 'Reading', question: 'Privacy online is an important concern for many users.', answer: 'privacy online', instruction: 'Safety' },
    { id: 'en7-r4', type: 'Reading', question: 'Artificial intelligence is becoming more common in daily life.', answer: 'more common', instruction: 'Technology' },
    { id: 'en7-r5', type: 'Reading', question: 'Sustainable energy sources help reduce carbon emissions.', answer: 'reduce emissions', instruction: 'Environment' },
    { id: 'en7-r6', type: 'Reading', question: 'Climate change is a global issue that affects us all.', answer: 'global issue', instruction: 'Earth' },
    { id: 'en7-r7', type: 'Reading', question: 'Protecting the environment is vital for our future.', answer: 'vital for future', instruction: 'Earth' },
    { id: 'en7-r8', type: 'Reading', question: 'Many species of animals are endangered due to habitat loss.', answer: 'endangered animals', instruction: 'Nature' },
    { id: 'en7-r9', type: 'Reading', question: 'Rainforests are often described as the lungs of the Earth.', answer: 'lungs of Earth', instruction: 'Nature' },
    { id: 'en7-r10', type: 'Reading', question: 'Ocean pollution is a major threat to marine ecosystems.', answer: 'marine ecosystems', instruction: 'Sea' },
    { id: 'en7-r11', type: 'Reading', question: 'Volcanic eruptions can change the landscape very quickly.', answer: 'change landscape', instruction: 'Geology' },
    { id: 'en7-r12', type: 'Reading', question: 'Plate tectonics explain the movement of the continents.', answer: 'plate tectonics', instruction: 'Geology' },
    { id: 'en7-r13', type: 'Reading', question: 'The solar system consists of eight planets and the sun.', answer: 'eight planets', instruction: 'Science' },
    { id: 'en7-r14', type: 'Reading', question: 'Mars is known as the Red Planet due to its dusty surface.', answer: 'Red Planet', instruction: 'Space' },
    { id: 'en7-r15', type: 'Reading', question: 'Jupiter is the largest planet in our solar system.', answer: 'largest planet', instruction: 'Space' },
    { id: 'en7-r16', type: 'Reading', question: 'Saturn is famous for its beautiful and large rings.', answer: 'beautiful rings', instruction: 'Space' },
    { id: 'en7-r17', type: 'Reading', question: 'The Milky Way is the galaxy that contains our sun.', answer: 'Milky Way', instruction: 'Space' },
    { id: 'en7-r18', type: 'Reading', question: 'Black holes are regions of space with intense gravity.', answer: 'intense gravity', instruction: 'Science' },
    { id: 'en7-r19', type: 'Reading', question: 'Galileo Galilei was an Italian astronomer and physicist.', answer: 'astronomer', instruction: 'History' },
    { id: 'en7-r20', type: 'Reading', question: 'Isaac Newton formulated the laws of motion and gravity.', answer: 'laws of motion', instruction: 'History' },
    { id: 'en7-r21', type: 'Reading', question: 'Albert Einstein developed the theory of relativity.', answer: 'theory of relativity', instruction: 'Science' },
    { id: 'en7-r22', type: 'Reading', question: 'Marie Curie discovered radioactivity and won Nobel Prizes.', answer: 'radioactivity', instruction: 'History' },
    { id: 'en7-r23', type: 'Reading', question: 'The Wright brothers made the first controlled flight.', answer: 'first flight', instruction: 'History' },
    { id: 'en7-r24', type: 'Reading', question: 'Alexander Graham Bell is credited with inventing telephone.', answer: 'telephone', instruction: 'History' },
    { id: 'en7-r25', type: 'Reading', question: 'Thomas Edison invented the long-lasting light bulb.', answer: 'light bulb', instruction: 'History' },
    { id: 'en7-r26', type: 'Reading', question: 'The Renaissance was a period of cultural rebirth.', answer: 'cultural rebirth', instruction: 'History' },
    { id: 'en7-r27', type: 'Reading', question: 'Leonardo da Vinci painted the famous Mona Lisa.', answer: 'Mona Lisa', instruction: 'Art' },
    { id: 'en7-r28', type: 'Reading', question: 'Michelangelo sculpted the impressive statue of David.', answer: 'statue of David', instruction: 'Art' },
    { id: 'en7-r29', type: 'Reading', question: 'Shakespeare wrote many famous plays and sonnets.', answer: 'plays and sonnets', instruction: 'Literature' },
    { id: 'en7-r30', type: 'Reading', question: 'The Industrial Revolution began in Great Britain.', answer: 'Great Britain', instruction: 'History' },
    { id: 'en7-r31', type: 'Reading', question: 'World War I changed the borders of many countries.', answer: 'changed borders', instruction: 'History' },
    { id: 'en7-r32', type: 'Reading', question: 'The United Nations was formed after World War II.', answer: 'United Nations', instruction: 'Politics' },
    { id: 'en7-r33', type: 'Reading', question: 'Democracy is a system where the people hold power.', answer: 'people hold power', instruction: 'Politics' },
    { id: 'en7-r34', type: 'Reading', question: 'Human rights are the basic rights for all people.', answer: 'basic rights', instruction: 'Society' },
    { id: 'en7-r35', type: 'Reading', question: 'Education is a key factor in reducing poverty globally.', answer: 'reducing poverty', instruction: 'Society' },
    { id: 'en7-r36', type: 'Reading', question: 'Literacy rates are improving in many parts of the world.', answer: 'improving', instruction: 'Society' },
    { id: 'en7-r37', type: 'Reading', question: 'Healthy eating includes plenty of fruits and vegetables.', answer: 'fruits and vegetables', instruction: 'Health' },
    { id: 'en7-r38', type: 'Reading', question: 'Regular exercise is important for physical well-being.', answer: 'regular exercise', instruction: 'Health' },
    { id: 'en7-r39', type: 'Reading', question: 'Mental health is just as important as physical health.', answer: 'mental health', instruction: 'Health' },
    { id: 'en7-r40', type: 'Reading', question: 'Volunteering is a great way to help the local community.', answer: 'volunteering', instruction: 'Society' },
    { id: 'en7-r41', type: 'Reading', question: 'Tolerance is accepting different opinions and beliefs.', answer: 'different opinions', instruction: 'Society' },
    { id: 'en7-r42', type: 'Reading', question: 'Teamwork is essential to achieve complicated goals.', answer: 'teamwork', instruction: 'Success' },
    { id: 'en7-r43', type: 'Reading', question: 'Creativity allows us to solve problems in new ways.', answer: 'solve problems', instruction: 'Success' },
    { id: 'en7-r44', type: 'Reading', question: 'Persistence is keep going despite facing difficulties.', answer: 'keep going', instruction: 'Success' },
    { id: 'en7-r45', type: 'Reading', question: 'Empathy is understanding the feelings of others.', answer: 'feelings of others', instruction: 'Social' },
    { id: 'en7-r46', type: 'Reading', question: 'Integrity is being honest and having strong morals.', answer: 'being honest', instruction: 'Social' },
    { id: 'en7-r47', type: 'Reading', question: 'Respect for others is a basis for a peaceful society.', answer: 'respect for others', instruction: 'Social' },
    { id: 'en7-r48', type: 'Reading', question: 'Traveling allows us to experience different cultures.', answer: 'different cultures', instruction: 'Travel' },
    { id: 'en7-r49', type: 'Reading', question: 'Learning a new language opens up many opportunities.', answer: 'new language', instruction: 'Travel' },
    { id: 'en7-r50', type: 'Reading', question: 'Photography is a way to capture special moments.', answer: 'capture moments', instruction: 'Hobbies' },
    { id: 'en7-r51', type: 'Reading', question: 'The world is full of wonders waiting to be explored.', answer: 'world of wonders', instruction: 'World' },
  ],
  8: [
    { id: 'en8-r1', type: 'Reading', question: 'To be or not to be, that is the question.', answer: 'that is the question', instruction: 'Shakespeare' },
    { id: 'en8-r2', type: 'Reading', question: 'All the world\'s a stage, and all the men and women merely players.', answer: 'merely players', instruction: 'Shakespeare' },
    { id: 'en8-r3', type: 'Reading', question: 'The pen is mightier than the sword.', answer: 'mightier than sword', instruction: 'Philosophy' },
    { id: 'en8-r4', type: 'Reading', question: 'Knowledge is power, but character is even more important.', answer: 'knowledge is power', instruction: 'Philosophy' },
    { id: 'en8-r5', type: 'Reading', question: 'Injustice anywhere is a threat to justice everywhere.', answer: 'justice everywhere', instruction: 'Civil Rights' },
    { id: 'en8-r6', type: 'Reading', question: 'I have a dream that one day this nation will rise up.', answer: 'reach one day', instruction: 'Civil Rights' },
    { id: 'en8-r7', type: 'Reading', question: 'The only thing we have to fear is fear itself.', answer: 'fear itself', instruction: 'History' },
    { id: 'en8-r8', type: 'Reading', question: 'That\'s one small step for man, one giant leap for mankind.', answer: 'giant leap', instruction: 'Space' },
    { id: 'en8-r9', type: 'Reading', question: 'Genius is one percent inspiration and ninety-nine percent perspiration.', answer: 'perspiration', instruction: 'Science' },
    { id: 'en8-r10', type: 'Reading', question: 'Innovation distinguishes between a leader and a follower.', answer: 'distinguishes', instruction: 'Business' },
    { id: 'en8-r11', type: 'Reading', question: 'The future belongs to those who believe in the beauty of their dreams.', answer: 'beauty of dreams', instruction: 'Advice' },
    { id: 'en8-r12', type: 'Reading', question: 'Education is the most powerful weapon which you can use to change world.', answer: 'change world', instruction: 'Quotes' },
    { id: 'en8-r13', type: 'Reading', question: 'Be the change that you wish to see in the world.', answer: 'be the change', instruction: 'Quotes' },
    { id: 'en8-r14', type: 'Reading', question: 'Success is not final, failure is not fatal: it is the courage to continue.', answer: 'courage to continue', instruction: 'Quotes' },
    { id: 'en8-r15', type: 'Reading', question: 'A journey of a thousand miles begins with a single step.', answer: 'single step', instruction: 'Quotes' },
    { id: 'en8-r16', type: 'Reading', question: 'Life is what happens when you\'re busy making other plans.', answer: 'making other plans', instruction: 'Quotes' },
    { id: 'en8-r17', type: 'Reading', question: 'Spread love everywhere you go. Let no one ever come to you without leaving.', answer: 'spread love', instruction: 'Quotes' },
    { id: 'en8-r18', type: 'Reading', question: 'When you reach the end of your rope, tie a knot in it and hang on.', answer: 'hang on', instruction: 'Quotes' },
    { id: 'en8-r19', type: 'Reading', question: 'Always remember that you are absolutely unique. Just like everyone else.', answer: 'absolutely unique', instruction: 'Quotes' },
    { id: 'en8-r20', type: 'Reading', question: 'Don\'t judge each day by the harvest you reap but by the seeds that you plant.', answer: 'seeds you plant', instruction: 'Quotes' },
    { id: 'en8-r21', type: 'Reading', question: 'Tell me and I forget. Teach me and I remember. Involve me and I learn.', answer: 'I learn', instruction: 'Education' },
    { id: 'en8-r22', type: 'Reading', question: 'The best and most beautiful things in the world cannot be seen or touched.', answer: 'cannot be seen', instruction: 'Quotes' },
    { id: 'en8-r23', type: 'Reading', question: 'It is during our darkest moments that we must focus to see the light.', answer: 'see the light', instruction: 'Quotes' },
    { id: 'en8-r24', type: 'Reading', question: 'Whoever is happy will make others happy too.', answer: 'make others happy', instruction: 'Quotes' },
    { id: 'en8-r25', type: 'Reading', question: 'Go confidently in the direction of your dreams! Live the life imagine.', answer: 'direction of dreams', instruction: 'Quotes' },
    { id: 'en8-r26', type: 'Reading', question: 'Globalization has led to an interconnected world economy.', answer: 'interconnected world', instruction: 'Economy' },
    { id: 'en8-r27', type: 'Reading', question: 'Digital citizenship is about using technology responsibly.', answer: 'using technology', instruction: 'Digital life' },
    { id: 'en8-r28', type: 'Reading', question: 'Sustainable development meets the needs of the present.', answer: 'needs of present', instruction: 'Environment' },
    { id: 'en8-r29', type: 'Reading', question: 'Biodiversity is essential for maintaining healthy ecosystems.', answer: 'healthy ecosystems', instruction: 'Science' },
    { id: 'en8-r30', type: 'Reading', question: 'Renewable energy sources include solar and wind power.', answer: 'solar and wind', instruction: 'Environment' },
    { id: 'en8-r31', type: 'Reading', question: 'Artificial Intelligence can process vast amounts of data.', answer: 'process data', instruction: 'Technology' },
    { id: 'en8-r32', type: 'Reading', question: 'Coding is becoming a foundational skill in the modern world.', answer: 'foundational skill', instruction: 'Education' },
    { id: 'en8-r33', type: 'Reading', question: 'Critical thinking helps individuals evaluate arguments.', answer: 'evaluate arguments', instruction: 'Philosophy' },
    { id: 'en8-r34', type: 'Reading', question: 'Media literacy is crucial for identifying bias in news.', answer: 'identifying bias', instruction: 'Social' },
    { id: 'en8-r35', type: 'Reading', question: 'The UN Sustainable Development Goals aim for a better world.', answer: 'better world', instruction: 'Global' },
    { id: 'en8-r36', type: 'Reading', question: 'Volunteering abroad can provide life-changing experiences.', answer: 'life-changing', instruction: 'Travel' },
    { id: 'en8-r37', type: 'Reading', question: 'Cultural exchange promotes mutual understanding between nations.', answer: 'mutual understanding', instruction: 'Global' },
    { id: 'en8-r38', type: 'Reading', question: 'Financial literacy is important for managing personal wealth.', answer: 'managing wealth', instruction: 'Economy' },
    { id: 'en8-r39', type: 'Reading', question: 'Entrepeneurship requires risk-taking and perseverance.', answer: 'risk-taking', instruction: 'Business' },
    { id: 'en8-r40', type: 'Reading', question: 'Public speaking is a skill that can be developed over time.', answer: 'developed over time', instruction: 'Social' },
    { id: 'en8-r41', type: 'Reading', question: 'Time management is key to balancing work and life.', answer: 'balancing work', instruction: 'Advice' },
    { id: 'en8-r42', type: 'Reading', question: 'Emotional intelligence involves recognizing your own feelings.', answer: 'recognizing feelings', instruction: 'Psychology' },
    { id: 'en8-r43', type: 'Reading', question: 'Self-reflection leads to personal growth and self-awareness.', answer: 'personal growth', instruction: 'Psychology' },
    { id: 'en8-r44', type: 'Reading', question: 'Community service helps build stronger neighborhoods.', answer: 'stronger neighborhoods', instruction: 'Social' },
    { id: 'en8-r45', type: 'Reading', question: 'Active listening is a fundamental communication skill.', answer: 'communication skill', instruction: 'Social' },
    { id: 'en8-r46', type: 'Reading', question: 'Problem-solving is needed in every career path.', answer: 'every career path', instruction: 'Jobs' },
    { id: 'en8-r47', type: 'Reading', question: 'Adaptability is crucial in a fast-changing job market.', answer: 'job market', instruction: 'Jobs' },
    { id: 'en8-r48', type: 'Reading', question: 'Collaboration often leads to more creative solutions.', answer: 'creative solutions', instruction: 'Success' },
    { id: 'en8-r49', type: 'Reading', question: 'Diversity in the workplace fosters different perspectives.', answer: 'different perspectives', instruction: 'Business' },
    { id: 'en8-r50', type: 'Reading', question: 'Inclusion means creating an environment where everyone belongs.', answer: 'where everyone belongs', instruction: 'Social' },
    { id: 'en8-r51', type: 'Reading', question: 'Ethics should guide our decisions in both personal and life.', answer: 'guide our decisions', instruction: 'Philosophy' },
  ],
  9: [
    { id: 'en9-r1', type: 'Reading', question: 'Post-colonial literature examines the legacy of colonialism.', answer: 'legacy of colonialism', instruction: 'Literature' },
    { id: 'en9-r2', type: 'Reading', question: 'Magical realism blends realistic world with elements of fantasy.', answer: 'blends realistic world', instruction: 'Literature' },
    { id: 'en9-r3', type: 'Reading', question: 'Dystopian novels explore societies that are dark and oppressive.', answer: 'dark and oppressive', instruction: 'Literature' },
    { id: 'en9-r4', type: 'Reading', question: 'Feminist theory analyzes gender inequality in text and society.', answer: 'gender inequality', instruction: 'Sociology' },
    { id: 'en9-r5', type: 'Reading', question: 'Modernism was a movement that broke away from tradition.', answer: 'broke from tradition', instruction: 'History' },
    { id: 'en9-r6', type: 'Reading', question: 'Post-modernism questions the existence of objective truths.', answer: 'objective truths', instruction: 'Philosophy' },
    { id: 'en9-r7', type: 'Reading', question: 'A metaphor is a figure of speech that describes one thing.', answer: 'figure of speech', instruction: 'Language' },
    { id: 'en9-r8', type: 'Reading', question: 'Symbolism uses objects to represent larger ideas or themes.', answer: 'represent ideas', instruction: 'Literature' },
    { id: 'en9-r9', type: 'Reading', question: 'Irony is a contrast between expectation and reality.', answer: 'expectation and reality', instruction: 'Language' },
    { id: 'en9-r10', type: 'Reading', question: 'Allegory is a story that can be interpreted to reveal meanings.', answer: 'reveal meanings', instruction: 'Literature' },
    { id: 'en9-r11', type: 'Reading', question: 'Symmetry in nature is often an indicator of health and beauty.', answer: 'health and beauty', instruction: 'Science' },
    { id: 'en9-r12', type: 'Reading', question: 'Quantum mechanics is a fundamental theory in physics.', answer: 'fundamental theory', instruction: 'Science' },
    { id: 'en9-r13', type: 'Reading', question: 'General relativity explains gravity as the curvature of space.', answer: 'curvature of space', instruction: 'Science' },
    { id: 'en9-r14', type: 'Reading', question: 'The Industrial Revolution significantly changed human society.', answer: 'changed society', instruction: 'History' },
    { id: 'en9-r15', type: 'Reading', question: 'The Enlightenment emphasized reason and individualism.', answer: 'emphasized reason', instruction: 'History' },
    { id: 'en9-r16', type: 'Reading', question: 'Urbanization is the process of people moving to cities.', answer: 'moving to cities', instruction: 'Geography' },
    { id: 'en9-r17', type: 'Reading', question: 'Globalization connects people through trade and culture.', answer: 'trade and culture', instruction: 'Economy' },
    { id: 'en9-r18', type: 'Reading', question: 'Sustainability aims to preserve resources for next generation.', answer: 'preserve resources', instruction: 'Environment' },
    { id: 'en9-r19', type: 'Reading', question: 'Geopolitics is the study of the influence of geography here.', answer: 'influence of geography', instruction: 'Social' },
    { id: 'en9-r20', type: 'Reading', question: 'Macroeconomics deals with the performance of whole city.', answer: 'whole city', instruction: 'Economy' },
    { id: 'en9-r21', type: 'Reading', question: 'Microeconomics focuses on individual choices and markets.', answer: 'choices and markets', instruction: 'Economy' },
    { id: 'en9-r22', type: 'Reading', question: 'Supply and demand determines the prices in a market economy.', answer: 'determines prices', instruction: 'Economy' },
    { id: 'en9-r23', type: 'Reading', question: 'Demography is the study of human populations and changes.', answer: 'human populations', instruction: 'Social' },
    { id: 'en9-r24', type: 'Reading', question: 'Nationalism is an ideology that emphasizes national identity.', answer: 'national identity', instruction: 'Politics' },
    { id: 'en9-r25', type: 'Reading', question: 'Imperialism is the policy of extending a country\'s power.', answer: 'extending power', instruction: 'Politics' },
    { id: 'en9-r26', type: 'Reading', question: 'Cognitive dissonance is a state of mental discomfort in mind.', answer: 'mental discomfort', instruction: 'Psychology' },
    { id: 'en9-r27', type: 'Reading', question: 'The placebo effect shows the power of belief on health.', answer: 'power of belief', instruction: 'Science' },
    { id: 'en9-r28', type: 'Reading', question: 'Classical conditioning is a type of learning through association.', answer: 'learning through association', instruction: 'Psychology' },
    { id: 'en9-r29', type: 'Reading', question: 'Epistemology is the branch of philosophy about knowledge.', answer: 'about knowledge', instruction: 'Philosophy' },
    { id: 'en9-r30', type: 'Reading', question: 'Aesthetics explores the nature of beauty and art.', answer: 'beauty and art', instruction: 'Philosophy' },
    { id: 'en9-r31', type: 'Reading', question: 'Phenomenology focuses on the experience of consciousness.', answer: 'consciousness', instruction: 'Philosophy' },
    { id: 'en9-r32', type: 'Reading', question: 'Utilitarianism promotes the greatest good for many people.', answer: 'greatest good', instruction: 'Ethics' },
    { id: 'en9-r33', type: 'Reading', question: 'Deontology focuses on moral duties and rules for everyone.', answer: 'moral duties', instruction: 'Ethics' },
    { id: 'en9-r34', type: 'Reading', question: 'Virtue ethics emphasizes character and virtues in life.', answer: 'character and virtues', instruction: 'Ethics' },
    { id: 'en9-r35', type: 'Reading', question: 'The scientific method is a systematic way to study world.', answer: 'systematic way', instruction: 'Science' },
    { id: 'en9-r36', type: 'Reading', question: 'Hypothesis is a testable explanation for an observation.', answer: 'testable explanation', instruction: 'Science' },
    { id: 'en9-r37', type: 'Reading', question: 'Correlation does not necessarily imply causation at all.', answer: 'imply causation', instruction: 'Science' },
    { id: 'en9-r38', type: 'Reading', question: 'An ecosystem is a community of living organisms here.', answer: 'living organisms', instruction: 'Nature' },
    { id: 'en9-r39', type: 'Reading', question: 'Mitigation is the action of reducing the severity.', answer: 'reducing severity', instruction: 'Social' },
    { id: 'en9-r40', type: 'Reading', question: 'Philanthropy is the desire to promote the welfare of others.', answer: 'promote welfare', instruction: 'Social' },
    { id: 'en9-r41', type: 'Reading', question: 'Civil society includes organizations outside the state.', answer: 'outside the state', instruction: 'Social' },
    { id: 'en9-r42', type: 'Reading', question: 'Advocacy is public support for a particular cause.', answer: 'support for cause', instruction: 'Social' },
    { id: 'en9-r43', type: 'Reading', question: 'Stewardship is the responsible management of something.', answer: 'responsible management', instruction: 'Advice' },
    { id: 'en9-r44', type: 'Reading', question: 'Resilience is the capacity to recover from difficulties.', answer: 'recover from difficulties', instruction: 'Advice' },
    { id: 'en9-r45', type: 'Reading', question: 'Mindfulness is the quality of being present in the moment.', answer: 'being present', instruction: 'Advice' },
    { id: 'en9-r46', type: 'Reading', question: 'Embodied cognition suggests thoughts are linked to body.', answer: 'thoughts linked to body', instruction: 'Psychology' },
    { id: 'en9-r47', type: 'Reading', question: 'Big data refers to extremely large data sets that exist.', answer: 'large data sets', instruction: 'Technology' },
    { id: 'en9-r48', type: 'Reading', question: 'The Turing test measures machine intelligence for us.', answer: 'machine intelligence', instruction: 'Technology' },
    { id: 'en9-r49', type: 'Reading', question: 'Encryption is the process of converting information into code.', answer: 'converting to code', instruction: 'IT' },
    { id: 'en9-r50', type: 'Reading', question: 'Open source software is publicly accessible for everyone.', answer: 'publicly accessible', instruction: 'IT' },
    { id: 'en9-r51', type: 'Reading', question: 'Lifelong learning is essential in a dynamic world.', answer: 'lifelong learning', instruction: 'Education' },
  ],
};
