/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const FRANSK_READING: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'fr0-r1', type: 'Reading', question: 'A', answer: 'A', instruction: 'Læs bogstavet' },
    { id: 'fr0-r2', type: 'Reading', question: 'B', answer: 'B', instruction: 'Læs bogstavet' },
    { id: 'fr0-r3', type: 'Reading', question: 'C', answer: 'C', instruction: 'Læs bogstavet' },
    { id: 'fr0-r4', type: 'Reading', question: 'Un', answer: 'Un', instruction: 'Læs tallet (1)' },
    { id: 'fr0-r5', type: 'Reading', question: 'Deux', answer: 'Deux', instruction: 'Læs tallet (2)' },
    { id: 'fr0-r6', type: 'Reading', question: 'Trois', answer: 'Trois', instruction: 'Læs tallet (3)' },
    { id: 'fr0-r7', type: 'Reading', question: 'Chat', answer: 'Chat', instruction: 'Læs ordet (Kat)' },
    { id: 'fr0-r8', type: 'Reading', question: 'Chien', answer: 'Chien', instruction: 'Læs ordet (Hund)' },
    { id: 'fr0-r9', type: 'Reading', question: 'Bonjour', answer: 'Bonjour', instruction: 'Hilsen' },
    { id: 'fr0-r10', type: 'Reading', question: 'Salut', answer: 'Salut', instruction: 'Hilsen' },
    { id: 'fr0-r11', type: 'Reading', question: 'Rouge', answer: 'Rouge', instruction: 'Læs farven (Rød)' },
    { id: 'fr0-r12', type: 'Reading', question: 'Bleu', answer: 'Bleu', instruction: 'Læs farven (Blå)' },
    { id: 'fr0-r13', type: 'Reading', question: 'Vert', answer: 'Vert', instruction: 'Læs farven (Grøn)' },
    { id: 'fr0-r14', type: 'Reading', question: 'Jaune', answer: 'Jaune', instruction: 'Læs farven (Gul)' },
    { id: 'fr0-r15', type: 'Reading', question: 'Noir', answer: 'Noir', instruction: 'Læs farven (Sort)' },
    { id: 'fr0-r16', type: 'Reading', question: 'Blanc', answer: 'Blanc', instruction: 'Læs farven (Hvid)' },
    { id: 'fr0-r17', type: 'Reading', question: 'Un chat', answer: 'Un chat', instruction: 'Læs frasen' },
    { id: 'fr0-r18', type: 'Reading', question: 'Un chien', answer: 'Un chien', instruction: 'Læs frasen' },
    { id: 'fr0-r19', type: 'Reading', question: 'Un oiseau', answer: 'Un oiseau', instruction: 'Læs frasen (Fugl)' },
    { id: 'fr0-r20', type: 'Reading', question: 'Un lapin', answer: 'Un lapin', instruction: 'Læs frasen (Kanin)' },
    { id: 'fr0-r21', type: 'Reading', question: 'Une vâche', answer: 'Une vâche', instruction: 'Læs frasen (Ko)' },
    { id: 'fr0-r22', type: 'Reading', question: 'Un cheval', answer: 'Un cheval', instruction: 'Læs frasen (Hest)' },
    { id: 'fr0-r23', type: 'Reading', question: 'Maman', answer: 'Maman', instruction: 'Familie' },
    { id: 'fr0-r24', type: 'Reading', question: 'Papa', answer: 'Papa', instruction: 'Familie' },
    { id: 'fr0-r25', type: 'Reading', question: 'Non', answer: 'Non', instruction: 'Læs ordet' },
    { id: 'fr0-r26', type: 'Reading', question: 'Oui', answer: 'Oui', instruction: 'Læs ordet' },
    { id: 'fr0-r27', type: 'Reading', question: 'Merci', answer: 'Merci', instruction: 'Høflighed' },
    { id: 'fr0-r28', type: 'Reading', question: 'Pardon', answer: 'Pardon', instruction: 'Høflighed' },
    { id: 'fr0-r29', type: 'Reading', question: 'S’il vous plaît', answer: 'S’il vous plaît', instruction: 'Høflighed' },
    { id: 'fr0-r30', type: 'Reading', question: 'Bonne nuit', answer: 'Bonne nuit', instruction: 'Godnat' },
    { id: 'fr0-r31', type: 'Reading', question: 'Au revoir', answer: 'Au revoir', instruction: 'Farvel' },
    { id: 'fr0-r32', type: 'Reading', question: 'Petit', answer: 'Petit', instruction: 'Lille' },
    { id: 'fr0-r33', type: 'Reading', question: 'Grand', answer: 'Grand', instruction: 'Stor' },
    { id: 'fr0-r34', type: 'Reading', question: 'Fille', answer: 'Fille', instruction: 'Pige' },
    { id: 'fr0-r35', type: 'Reading', question: 'Garçon', answer: 'Garçon', instruction: 'Dreng' },
    { id: 'fr0-r36', type: 'Reading', question: 'La mer', answer: 'La mer', instruction: 'Havet' },
    { id: 'fr0-r37', type: 'Reading', question: 'La terre', answer: 'La terre', instruction: 'Jorden' },
    { id: 'fr0-r38', type: 'Reading', question: 'Le soleil', answer: 'Le soleil', instruction: 'Solen' },
    { id: 'fr0-r39', type: 'Reading', question: 'La lune', answer: 'La lune', instruction: 'Månen' },
    { id: 'fr0-r40', type: 'Reading', question: 'Un pomme', answer: 'Un pomme', instruction: 'Frugt' },
    { id: 'fr0-r41', type: 'Reading', question: 'Banane', answer: 'Banane', instruction: 'Frugt' },
    { id: 'fr0-r42', type: 'Reading', question: 'Pain', answer: 'Pain', instruction: 'Mad' },
    { id: 'fr0-r43', type: 'Reading', question: 'Eau', answer: 'Eau', instruction: 'Drik' },
    { id: 'fr0-r44', type: 'Reading', question: 'Lait', answer: 'Lait', instruction: 'Drik' },
    { id: 'fr0-r45', type: 'Reading', question: 'Manger', answer: 'Manger', instruction: 'Verbe' },
    { id: 'fr0-r46', type: 'Reading', question: 'Boire', answer: 'Boire', instruction: 'Verbe' },
    { id: 'fr0-r47', type: 'Reading', question: 'Dormir', answer: 'Dormir', instruction: 'Verbe' },
    { id: 'fr0-r48', type: 'Reading', question: 'Jouer', answer: 'Jouer', instruction: 'Verbe' },
    { id: 'fr0-r49', type: 'Reading', question: 'Un, deux, trois', answer: 'Un, deux, trois', instruction: 'Tæl' },
    { id: 'fr0-r50', type: 'Reading', question: 'Quatre, cinq, six', answer: 'Quatre, cinq, six', instruction: 'Tæl' },
    { id: 'fr0-r51', type: 'Reading', question: 'Sept, huit, neuf, dix', answer: 'Sept, huit, neuf, dix', instruction: 'Tæl' },
  ],
  1: [
    { id: 'fr1-r1', type: 'Reading', question: 'Comment t’appelles-tu?', answer: 'Comment t’appelles-tu?', instruction: 'Spørgsmål' },
    { id: 'fr1-r2', type: 'Reading', question: 'Je m’appelle Paul.', answer: 'Je m’appelle Paul', instruction: 'Svar' },
    { id: 'fr1-r3', type: 'Reading', question: 'Quel âge as-tu?', answer: 'Quel âge as-tu?', instruction: 'Spørgsmål' },
    { id: 'fr1-r4', type: 'Reading', question: 'J’ai sept ans.', answer: 'J’ai sept ans', instruction: 'Svar' },
    { id: 'fr1-r5', type: 'Reading', question: 'Ça va bien, merci.', answer: 'Ça va bien', instruction: 'Svar' },
    { id: 'fr1-r6', type: 'Reading', question: 'Où habites-tu?', answer: 'Où habites-tu?', instruction: 'Spørgsmål' },
    { id: 'fr1-r7', type: 'Reading', question: 'J’habite au Danemark.', answer: 'J’habite au Danemark', instruction: 'Svar' },
    { id: 'fr1-r8', type: 'Reading', question: 'Ma famille est petite.', answer: 'Ma famille', instruction: 'Familie' },
    { id: 'fr1-r9', type: 'Reading', question: 'Mon frère est gentil.', answer: 'Mon frère', instruction: 'Familie' },
    { id: 'fr1-r10', type: 'Reading', question: 'Ma sœur est drôle.', answer: 'Ma sœur', instruction: 'Familie' },
    { id: 'fr1-r11', type: 'Reading', question: 'J’aime les frites.', answer: 'J’aime les frites', instruction: 'Mad' },
    { id: 'fr1-r12', type: 'Reading', question: 'Je n’aime pas le fromage.', answer: 'Je n’aime pas', instruction: 'Mad' },
    { id: 'fr1-r13', type: 'Reading', question: 'C’est un livre rouge.', answer: 'livre rouge', instruction: 'Skole' },
    { id: 'fr1-r14', type: 'Reading', question: 'C’est un stylo bleu.', answer: 'stylo bleu', instruction: 'Skole' },
    { id: 'fr1-r15', type: 'Reading', question: 'Où est le chat?', answer: 'Où est le chat?', instruction: 'Dyr' },
    { id: 'fr1-r16', type: 'Reading', question: 'Le chat est sur la table.', answer: 'sur la table', instruction: 'Dyr' },
    { id: 'fr1-r17', type: 'Reading', question: 'Le chien est sous le lit.', answer: 'sous le lit', instruction: 'Dyr' },
    { id: 'fr1-r18', type: 'Reading', question: 'Il y a une souris.', answer: 'une souris', instruction: 'Dyr' },
    { id: 'fr1-r19', type: 'Reading', question: 'Regarde le soleil!', answer: 'le soleil', instruction: 'Vejr' },
    { id: 'fr1-r20', type: 'Reading', question: 'Il pleut aujourd’hui.', answer: 'Il pleut', instruction: 'Vejr' },
    { id: 'fr1-r21', type: 'Reading', question: 'Il fait froid.', answer: 'Il fait froid', instruction: 'Vejr' },
    { id: 'fr1-r22', type: 'Reading', question: 'Il fait chaud.', answer: 'Il fait chaud', instruction: 'Vejr' },
    { id: 'fr1-r23', type: 'Reading', question: 'J’aime chanter.', answer: 'chanter', instruction: 'Hobby' },
    { id: 'fr1-r24', type: 'Reading', question: 'J’aime danser.', answer: 'danser', instruction: 'Hobby' },
    { id: 'fr1-r25', type: 'Reading', question: 'J’aime jouer au foot.', answer: 'jouer au foot', instruction: 'Hobby' },
    { id: 'fr1-r26', type: 'Reading', question: 'Ma maison est blanche.', answer: 'maison blanche', instruction: 'Huset' },
    { id: 'fr1-r27', type: 'Reading', question: 'La porte est verte.', answer: 'porte est verte', instruction: 'Huset' },
    { id: 'fr1-r28', type: 'Reading', question: 'La fenêtre est grande.', answer: 'fenêtre est grande', instruction: 'Huset' },
    { id: 'fr1-r29', type: 'Reading', question: 'Le jardin er beau.', answer: 'jardin er beau', instruction: 'Huset' },
    { id: 'fr1-r30', type: 'Reading', question: 'Un, deux, trois, quatre.', answer: 'un, deux, tre, fire', instruction: 'Tæl' },
    { id: 'fr1-r31', type: 'Reading', question: 'Cinq, six, sept, huit.', answer: 'fem, seks, syv, otte', instruction: 'Tæl' },
    { id: 'fr1-r32', type: 'Reading', question: 'Neuf, dix, onze, douze.', answer: 'ni, ti, elleve, tolv', instruction: 'Tæl' },
    { id: 'fr1-r33', type: 'Reading', question: 'Treize, quatorze, quinze.', answer: 'tretten, fjorten, femten', instruction: 'Tæl' },
    { id: 'fr1-r34', type: 'Reading', question: 'Seize, dix-sept, dix-huit.', answer: 'seksten, sytten, atten', instruction: 'Tæl' },
    { id: 'fr1-r35', type: 'Reading', question: 'Dix-neuf, vingt.', answer: 'nitten, tyve', instruction: 'Tæl' },
    { id: 'fr1-r36', type: 'Reading', question: 'Lundi, Mardi, Mercredi.', answer: 'mån, tirs, ons', instruction: 'Ugedage' },
    { id: 'fr1-r37', type: 'Reading', question: 'Jeudi, Vendredi.', answer: 'tors, fredage', instruction: 'Ugedage' },
    { id: 'fr1-r38', type: 'Reading', question: 'Samedi, Dimanche.', answer: 'lør, søndage', instruction: 'Weekend' },
    { id: 'fr1-r39', type: 'Reading', question: 'Bon anniversaire!', answer: 'Bon anniversaire', instruction: 'Hilsen' },
    { id: 'fr1-r40', type: 'Reading', question: 'Joyeux Noël!', answer: 'Joyeux Noël', instruction: 'Hilsen' },
    { id: 'fr1-r41', type: 'Reading', question: 'Bonne année!', answer: 'Bonne année', instruction: 'Hilsen' },
    { id: 'fr1-r42', type: 'Reading', question: 'Je suis content.', answer: 'Je suis content', instruction: 'Følelse' },
    { id: 'fr1-r43', type: 'Reading', question: 'Je suis triste.', answer: 'Je suis triste', instruction: 'Følelse' },
    { id: 'fr1-r44', type: 'Reading', question: 'J’ai faim.', answer: 'J’ai faim', instruction: 'Følelse' },
    { id: 'fr1-r45', type: 'Reading', question: 'J’ai soif.', answer: 'J’ai soif', instruction: 'Følelse' },
    { id: 'fr1-r46', type: 'Reading', question: 'C’est une petite voiture.', answer: 'petite voiture', instruction: 'Transport' },
    { id: 'fr1-r47', type: 'Reading', question: 'C’est un grand bus.', answer: 'grand bus', instruction: 'Transport' },
    { id: 'fr1-r48', type: 'Reading', question: 'Regarde l’avion!', answer: 'l’avion', instruction: 'Transport' },
    { id: 'fr1-r49', type: 'Reading', question: 'Le bateau est bleu.', answer: 'bateau bleu', instruction: 'Transport' },
    { id: 'fr1-r50', type: 'Reading', question: 'Je marche à l’école.', answer: 'marche à l’école', instruction: 'Transport' },
    { id: 'fr1-r51', type: 'Reading', question: 'J’aime ma famille.', answer: 'J’aime ma famille', instruction: 'Afslutning' },
  ],
  2: [
    { id: 'fr2-r1', type: 'Reading', question: 'Le ciel er bleu.', answer: 'ciel er bleu', instruction: 'Natur' },
    { id: 'fr2-r2', type: 'Reading', question: 'L’herbe er verte.', answer: 'herbe er verte', instruction: 'Natur' },
    { id: 'fr2-r3', type: 'Reading', question: 'Le chat noir dort.', answer: 'chat noir dort', instruction: 'Dyr' },
    { id: 'fr2-r4', type: 'Reading', question: 'Le petit chien court.', answer: 'chien court', instruction: 'Dyr' },
    { id: 'fr2-r5', type: 'Reading', question: 'Une pomme rouge.', answer: 'pomme rouge', instruction: 'Frugt' },
    { id: 'fr2-r6', type: 'Reading', question: 'Une banane jaune.', answer: 'banane jaune', instruction: 'Frugt' },
    { id: 'fr2-r7', type: 'Reading', question: 'Un bonbon sucré.', answer: 'bonbon sucré', instruction: 'Slik' },
    { id: 'fr2-r8', type: 'Reading', question: 'J’ai un vélo.', answer: 'un vélo', instruction: 'Transport' },
    { id: 'fr2-r9', type: 'Reading', question: 'Elle a une poupée.', answer: 'une poupée', instruction: 'Legetøj' },
    { id: 'fr2-r10', type: 'Reading', question: 'Il a un ballon.', answer: 'un ballon', instruction: 'Legetøj' },
    { id: 'fr2-r11', type: 'Reading', question: 'Maman prépare le dîner.', answer: 'prépare le dîner', instruction: 'Familie' },
    { id: 'fr2-r12', type: 'Reading', question: 'Papa lit un journal.', answer: 'lit un journal', instruction: 'Familie' },
    { id: 'fr2-r13', type: 'Reading', question: 'Le bébé pleure.', answer: 'bébé pleure', instruction: 'Familie' },
    { id: 'fr2-r14', type: 'Reading', question: 'Je porte un t-shirt.', answer: 't-shirt', instruction: 'Tøj' },
    { id: 'fr2-r15', type: 'Reading', question: 'Tu portes un pantalon.', answer: 'pantalon', instruction: 'Tøj' },
    { id: 'fr2-r16', type: 'Reading', question: 'Il fait beau.', answer: 'fait beau', instruction: 'Vejr' },
    { id: 'fr2-r17', type: 'Reading', question: 'Il y a du vent.', answer: 'du vent', instruction: 'Vejr' },
    { id: 'fr2-r18', type: 'Reading', question: 'La neige est froide.', answer: 'neige est froide', instruction: 'Vejr' },
    { id: 'fr2-r19', type: 'Reading', question: 'Je mange une glace.', answer: 'mange une glace', instruction: 'Mad' },
    { id: 'fr2-r20', type: 'Reading', question: 'Elle boit du jus.', answer: 'boit du jus', instruction: 'Drik' },
    { id: 'fr2-r21', type: 'Reading', question: 'Le cartable est lourd.', answer: 'cartable est lourd', instruction: 'Skole' },
    { id: 'fr2-r22', type: 'Reading', question: 'Le cahier est ouvert.', answer: 'cahier est ouvert', instruction: 'Skole' },
    { id: 'fr2-r23', type: 'Reading', question: 'La règle est longue.', answer: 'règle est longue', instruction: 'Skole' },
    { id: 'fr2-r24', type: 'Reading', question: 'La gomme est petite.', answer: 'gomme est petite', instruction: 'Skole' },
    { id: 'fr2-r25', type: 'Reading', question: 'Où est ma trousse?', answer: 'ma trousse', instruction: 'Skole' },
    { id: 'fr2-r26', type: 'Reading', question: 'Je dessine une fleur.', answer: 'dessine une fleur', instruction: 'Fritid' },
    { id: 'fr2-r27', type: 'Reading', question: 'Nous regardons la télé.', answer: 'regardons la télé', instruction: 'Fritid' },
    { id: 'fr2-r28', type: 'Reading', question: 'Il joue du piano.', answer: 'joue du piano', instruction: 'Fritid' },
    { id: 'fr2-r29', type: 'Reading', question: 'Elle aime le chocolat.', answer: 'aime le chocolat', instruction: 'Smag' },
    { id: 'fr2-r30', type: 'Reading', question: 'Le poisson nage.', answer: 'poisson nage', instruction: 'Dyr' },
    { id: 'fr2-r31', type: 'Reading', question: 'L’oiseau chante.', answer: 'oiseau chante', instruction: 'Dyr' },
    { id: 'fr2-r32', type: 'Reading', question: 'Le lion rugit.', answer: 'lion rugit', instruction: 'Dyr' },
    { id: 'fr2-r33', type: 'Reading', question: 'La tortue est lente.', answer: 'tortue est lente', instruction: 'Dyr' },
    { id: 'fr2-r34', type: 'Reading', question: 'Le lapin saute.', answer: 'lapin saute', instruction: 'Dyr' },
    { id: 'fr2-r35', type: 'Reading', question: 'Je suis à la maison.', answer: 'à la maison', instruction: 'Sted' },
    { id: 'fr2-r36', type: 'Reading', question: 'Tu es à l’école.', answer: 'à l’école', instruction: 'Sted' },
    { id: 'fr2-r37', type: 'Reading', question: 'Il court vite.', answer: 'court vite', instruction: 'Handling' },
    { id: 'fr2-r38', type: 'Reading', question: 'Elle marche doucement.', answer: 'marche doucement', instruction: 'Handling' },
    { id: 'fr2-r39', type: 'Reading', question: 'Nous écoutons de la musique.', answer: 'écoutons de la musique', instruction: 'Handling' },
    { id: 'fr2-r40', type: 'Reading', question: 'Ils parlent français.', answer: 'parlent français', instruction: 'Sprog' },
    { id: 'fr2-r41', type: 'Reading', question: 'Un chapeau noir.', answer: 'chapeau noir', instruction: 'Tøj' },
    { id: 'fr2-r42', type: 'Reading', question: 'Une robe rose.', answer: 'robe rose', instruction: 'Tøj' },
    { id: 'fr2-r43', type: 'Reading', question: 'Des chaussures bleues.', answer: 'chaussures bleues', instruction: 'Tøj' },
    { id: 'fr2-r44', type: 'Reading', question: 'Ma main est propre.', answer: 'main est propre', instruction: 'Krop' },
    { id: 'fr2-r45', type: 'Reading', question: 'Ton visage est sale.', answer: 'visage est sale', instruction: 'Krop' },
    { id: 'fr2-r46', type: 'Reading', question: 'Le lit est mou.', answer: 'lit est mou', instruction: 'Møbler' },
    { id: 'fr2-r47', type: 'Reading', question: 'La chaise est dure.', answer: 'chaise est dure', instruction: 'Møbler' },
    { id: 'fr2-r48', type: 'Reading', question: 'La table est ronde.', answer: 'table est ronde', instruction: 'Møbler' },
    { id: 'fr2-r49', type: 'Reading', question: 'La voiture démarre.', answer: 'voiture démarre', instruction: 'Transport' },
    { id: 'fr2-r50', type: 'Reading', question: 'Arrête-toi!', answer: 'Arrête-toi', instruction: 'Besked' },
    { id: 'fr2-r51', type: 'Reading', question: 'C’est fini.', answer: 'C’est fini', instruction: 'Besked' },
  ],
  3: [
    { id: 'fr3-r1', type: 'Reading', question: 'Quelle heure est-il?', answer: 'Quelle heure est-il?', instruction: 'Tiden' },
    { id: 'fr3-r2', type: 'Reading', question: 'Il est huit heures.', answer: 'huit heures', instruction: 'Tiden' },
    { id: 'fr3-r3', type: 'Reading', question: 'C’est le matin.', answer: 'le matin', instruction: 'Tiden' },
    { id: 'fr3-r4', type: 'Reading', question: 'C’est l’après-midi.', answer: 'l’après-midi', instruction: 'Tiden' },
    { id: 'fr3-r5', type: 'Reading', question: 'Il est midi.', answer: 'midi', instruction: 'Tiden' },
    { id: 'fr3-r6', type: 'Reading', question: 'Quelle est la date?', answer: 'Quelle est la date?', instruction: 'Dato' },
    { id: 'fr3-r7', type: 'Reading', question: 'Aujourd’hui, c’est lundi.', answer: 'c’est lundi', instruction: 'Uge' },
    { id: 'fr3-r8', type: 'Reading', question: 'Demain, c’est mardi.', answer: 'c’est mardi', instruction: 'Uge' },
    { id: 'fr3-r9', type: 'Reading', question: 'Les mois de l’année.', answer: 'mois de l’année', instruction: 'Kalender' },
    { id: 'fr3-r10', type: 'Reading', question: 'Janvier er froid.', answer: 'Janvier er froid', instruction: 'Måneder' },
    { id: 'fr3-r11', type: 'Reading', question: 'Juillet er chaud.', answer: 'Juillet er chaud', instruction: 'Måneder' },
    { id: 'fr3-r12', type: 'Reading', question: 'Où sont mes clefs?', answer: 'mes clefs', instruction: 'Huset' },
    { id: 'fr3-r13', type: 'Reading', question: 'Elles sont dans la cuisine.', answer: 'dans la cuisine', instruction: 'Rum' },
    { id: 'fr3-r14', type: 'Reading', question: 'Je vais dans le salon.', answer: 'dans le salon', instruction: 'Rum' },
    { id: 'fr3-r15', type: 'Reading', question: 'La chambre est calme.', answer: 'chambre est calme', instruction: 'Rum' },
    { id: 'fr3-r16', type: 'Reading', question: 'La salle de bain.', answer: 'salle de bain', instruction: 'Rum' },
    { id: 'fr3-r17', type: 'Reading', question: 'Je me brosse les dents.', answer: 'brosse les dents', instruction: 'Hygiejne' },
    { id: 'fr3-r18', type: 'Reading', question: 'Je me lave les mains.', answer: 'lave les mains', instruction: 'Hygiejne' },
    { id: 'fr3-r19', type: 'Reading', question: 'Je peigne mes cheveux.', answer: 'peigne mes cheveux', instruction: 'Hygiejne' },
    { id: 'fr3-r20', type: 'Reading', question: 'J’ai mal à la tête.', answer: 'mal à la tête', instruction: 'Sundhed' },
    { id: 'fr3-r21', type: 'Reading', question: 'J’ai mal au ventre.', answer: 'mal au ventre', instruction: 'Sundhed' },
    { id: 'fr3-r22', type: 'Reading', question: 'Le médecin est là.', answer: 'le médecin', instruction: 'Sundhed' },
    { id: 'fr3-r23', type: 'Reading', question: 'Prends ton médicament.', answer: 'ton médicament', instruction: 'Sundhed' },
    { id: 'fr3-r24', type: 'Reading', question: 'Le ciel est nuageux.', answer: 'ciel nuageux', instruction: 'Vejr' },
    { id: 'fr3-r25', type: 'Reading', question: 'Il va pleuvoir.', answer: 'va pleuvoir', instruction: 'Vejr' },
    { id: 'fr3-r26', type: 'Reading', question: 'J’ai un parapluie.', answer: 'un parapluie', instruction: 'Vejr' },
    { id: 'fr3-r27', type: 'Reading', question: 'Où est la station de métro?', answer: 'station de métro', instruction: 'Byen' },
    { id: 'fr3-r28', type: 'Reading', question: 'Prenez le bus numéro dix.', answer: 'bus numéro dix', instruction: 'Transport' },
    { id: 'fr3-r29', type: 'Reading', question: 'Le train arrive.', answer: 'train arrive', instruction: 'Transport' },
    { id: 'fr3-r30', type: 'Reading', question: 'Le billet coûte cher.', answer: 'billet coûte cher', instruction: 'Penge' },
    { id: 'fr3-r31', type: 'Reading', question: 'Je voudrais payer.', answer: 'voudrais payer', instruction: 'Butik' },
    { id: 'fr3-r32', type: 'Reading', question: 'C’est trop cher.', answer: 'trop cher', instruction: 'Butik' },
    { id: 'fr3-r33', type: 'Reading', question: 'C’est bon marché.', answer: 'bon marché', instruction: 'Butik' },
    { id: 'fr3-r34', type: 'Reading', question: 'Quelle est ta couleur préférée?', answer: 'couleur préférée', instruction: 'Farver' },
    { id: 'fr3-r35', type: 'Reading', question: 'J’aime l’orange.', answer: 'J’aime l’orange', instruction: 'Farver' },
    { id: 'fr3-r36', type: 'Reading', question: 'Le violet er beau.', answer: 'Le violet', instruction: 'Farver' },
    { id: 'fr3-r37', type: 'Reading', question: 'Le marron er foncé.', answer: 'Le marron', instruction: 'Farver' },
    { id: 'fr3-r38', type: 'Reading', question: 'Le gris er clair.', answer: 'Le gris', instruction: 'Farver' },
    { id: 'fr3-r39', type: 'Reading', question: 'Qu’est-ce que tu manges?', answer: 'tu manges', instruction: 'Mad' },
    { id: 'fr3-r40', type: 'Reading', question: 'Je mange du poulet.', answer: 'du poulet', instruction: 'Mad' },
    { id: 'fr3-r41', type: 'Reading', question: 'Je mange du riz.', answer: 'du riz', instruction: 'Mad' },
    { id: 'fr3-r42', type: 'Reading', question: 'Le gâteau er délicieux.', answer: 'gâteau délicieux', instruction: 'Mad' },
    { id: 'fr3-r43', type: 'Reading', question: 'Voulez-vous du dessert?', answer: 'du dessert', instruction: 'Mad' },
    { id: 'fr3-r44', type: 'Reading', question: 'Les vacances sont super.', answer: 'vacances super', instruction: 'Rejse' },
    { id: 'fr3-r45', type: 'Reading', question: 'Nous allons à la plage.', answer: 'à la plage', instruction: 'Rejse' },
    { id: 'fr3-r46', type: 'Reading', question: 'La mer est chaude.', answer: 'mer chaude', instruction: 'Natur' },
    { id: 'fr3-r47', type: 'Reading', question: 'Je construis un château de sable.', answer: 'château de sable', instruction: 'Leg' },
    { id: 'fr3-r48', type: 'Reading', question: 'Il y a des montagnes.', answer: 'des montagnes', instruction: 'Landskab' },
    { id: 'fr3-r49', type: 'Reading', question: 'La forêt est sombre.', answer: 'forêt sombre', instruction: 'Landskab' },
    { id: 'fr3-r50', type: 'Reading', question: 'La rivière coule.', answer: 'rivière coule', instruction: 'Landskab' },
    { id: 'fr3-r51', type: 'Reading', question: 'C’est une belle journée.', answer: 'belle journée', instruction: 'Afslutning' },
  ],
  4: [
    { id: 'fr4-r1', type: 'Reading', question: 'Comment vas-tu aujourd’hui?', answer: 'Comment vas-tu', instruction: 'Hilsen' },
    { id: 'fr4-r2', type: 'Reading', question: 'Je vais très bien, et toi?', answer: 'très bien', instruction: 'Hilsen' },
    { id: 'fr4-r3', type: 'Reading', question: 'Quelle est ta profession préférée?', answer: 'profession préférée', instruction: 'Job' },
    { id: 'fr4-r4', type: 'Reading', question: 'Je veux être pilote.', answer: 'être pilote', instruction: 'Job' },
    { id: 'fr4-r5', type: 'Reading', question: 'Mon oncle est architecte.', answer: 'architecte', instruction: 'Job' },
    { id: 'fr4-r6', type: 'Reading', question: 'Ma tante est infirmière.', answer: 'infirmière', instruction: 'Job' },
    { id: 'fr4-r7', type: 'Reading', question: 'Où travailles-tu?', answer: 'Où travailles-tu', instruction: 'Job' },
    { id: 'fr4-r8', type: 'Reading', question: 'Je travaille dans un bureau.', answer: 'dans un bureau', instruction: 'Job' },
    { id: 'fr4-r9', type: 'Reading', question: 'Le magasin est ouvert de neuf à dix-huit heures.', answer: 'ouvert de neuf à dix-huit', instruction: 'Butik' },
    { id: 'fr4-r10', type: 'Reading', question: 'Je voudrais acheter des vêtements.', answer: 'acheter des vêtements', instruction: 'Shopping' },
    { id: 'fr4-r11', type: 'Reading', question: 'Une chemise blanche et un pantalon noir.', answer: 'chemise blanche', instruction: 'Tøj' },
    { id: 'fr4-r12', type: 'Reading', question: 'Quelle taille faites-vous?', answer: 'Quelle taille', instruction: 'Shopping' },
    { id: 'fr4-r13', type: 'Reading', question: 'Je fais du quarante.', answer: 'du quarante', instruction: 'Shopping' },
    { id: 'fr4-r14', type: 'Reading', question: 'Où sont les cabines d’essayage?', answer: 'cabines d’essayage', instruction: 'Shopping' },
    { id: 'fr4-r15', type: 'Reading', question: 'Puis-je essayer cette jupe?', answer: 'essayer cette jupe', instruction: 'Shopping' },
    { id: 'fr4-r16', type: 'Reading', question: 'C’est trop grand pour moi.', answer: 'trop grand', instruction: 'Shopping' },
    { id: 'fr4-r17', type: 'Reading', question: 'C’est parfait.', answer: 'C’est parfait', instruction: 'Shopping' },
    { id: 'fr4-r18', type: 'Reading', question: 'Je prends cet article.', answer: 'prends cet article', instruction: 'Shopping' },
    { id: 'fr4-r19', type: 'Reading', question: 'Acceptez-vous les cartes de crédit?', answer: 'cartes de crédit', instruction: 'Betaling' },
    { id: 'fr4-r20', type: 'Reading', question: 'Désolé, seulement de l’espèce.', answer: 'seulement de l’espèce', instruction: 'Betaling' },
    { id: 'fr4-r21', type: 'Reading', question: 'Voici votre monnaie.', answer: 'votre monnaie', instruction: 'Betaling' },
    { id: 'fr4-r22', type: 'Reading', question: 'Gardez la monnaie.', answer: 'Gardez la monnaie', instruction: 'Betaling' },
    { id: 'fr4-r23', type: 'Reading', question: 'Quel temps fait-il à Paris?', answer: 'Quel temps', instruction: 'Vejr' },
    { id: 'fr4-r24', type: 'Reading', question: 'Il y a de l’orage.', answer: 'de l’orage', instruction: 'Vejr' },
    { id: 'fr4-r25', type: 'Reading', question: 'Attention aux éclairs!', answer: 'aux éclairs', instruction: 'Vejr' },
    { id: 'fr4-r26', type: 'Reading', question: 'Le vent souffle fort.', answer: 'vent souffle fort', instruction: 'Vejr' },
    { id: 'fr4-r27', type: 'Reading', question: 'Le ciel est couvert.', answer: 'ciel est couvert', instruction: 'Vejr' },
    { id: 'fr4-r28', type: 'Reading', question: 'Il commence à neiger.', answer: 'commence à neiger', instruction: 'Vejr' },
    { id: 'fr4-r29', type: 'Reading', question: 'J’aime skier en hiver.', answer: 'skier en hiver', instruction: 'Sport' },
    { id: 'fr4-r30', type: 'Reading', question: 'Faisons un bonhomme de neige.', answer: 'bonhomme de neige', instruction: 'Vejr' },
    { id: 'fr4-r31', type: 'Reading', question: 'Où se trouve la banque?', answer: 'se trouve la banque', instruction: 'Byen' },
    { id: 'fr4-r32', type: 'Reading', question: 'Tournez à gauche au feu rouge.', answer: 'Tournez à gauche', instruction: 'Vejvending' },
    { id: 'fr4-r33', type: 'Reading', question: 'Allez tout droit jusqu’au pont.', answer: 'Allez tout droit', instruction: 'Vejvending' },
    { id: 'fr4-r34', type: 'Reading', question: 'C’est à côté de la pharmacie.', answer: 'à côté de la pharmacie', instruction: 'Byen' },
    { id: 'fr4-r35', type: 'Reading', question: 'Près du parc, il y a un café.', answer: 'Près du parc', instruction: 'Byen' },
    { id: 'fr4-r36', type: 'Reading', question: 'Je cherche la poste.', answer: 'cherche la poste', instruction: 'Byen' },
    { id: 'fr4-r37', type: 'Reading', question: 'Le timbre coûte un euro.', answer: 'timbre coûte un euro', instruction: 'Post' },
    { id: 'fr4-r38', type: 'Reading', question: 'Envoyez cette lettre en France.', answer: 'Envoyez cette lettre', instruction: 'Post' },
    { id: 'fr4-r39', type: 'Reading', question: 'Avez-vous des colis?', answer: 'avez-vous des colis', instruction: 'Post' },
    { id: 'fr4-r40', type: 'Reading', question: 'Bonne journée, monsieur.', answer: 'Bonne journée', instruction: 'Hilsen' },
    { id: 'fr4-r41', type: 'Reading', question: 'À bientôt, mademoiselle.', answer: 'À bientôt', instruction: 'Hilsen' },
    { id: 'fr4-r42', type: 'Reading', question: 'Pardon, madame, je suis perdu.', answer: 'je suis perdu', instruction: 'Hjælp' },
    { id: 'fr4-r43', type: 'Reading', question: 'Pouvez-vous m’aider?', answer: 'm’aider', instruction: 'Hjælp' },
    { id: 'fr4-r44', type: 'Reading', question: 'Quel est votre numéro de téléphone?', answer: 'numéro de téléphone', instruction: 'Info' },
    { id: 'fr4-r45', type: 'Reading', question: 'Mon adresse est rue de la Paix.', answer: 'rue de la Paix', instruction: 'Info' },
    { id: 'fr4-r46', type: 'Reading', question: 'Voulez-vous sortir ce soir?', answer: 'sortir ce soir', instruction: 'Fritid' },
    { id: 'fr4-r47', type: 'Reading', question: 'Allons au cinéma.', answer: 'au cinéma', instruction: 'Fritid' },
    { id: 'fr4-r48', type: 'Reading', question: 'Le film commence à vingt heures.', answer: 'film commence', instruction: 'Fritid' },
    { id: 'fr4-r49', type: 'Reading', question: 'C’est un film d’aventure.', answer: 'film d’aventure', instruction: 'Fritid' },
    { id: 'fr4-r50', type: 'Reading', question: 'J’adore les pop-corn.', answer: 'J’adore les pop-corn', instruction: 'Fritid' },
    { id: 'fr4-r51', type: 'Reading', question: 'C’était une soirée amusante.', answer: 'soirée amusante', instruction: 'Afslutning' },
  ],
  5: [
    { id: 'fr5-r1', type: 'Reading', question: 'Quelles sont vos activités préférées?', answer: 'activités préférées', instruction: 'Hobby' },
    { id: 'fr5-r2', type: 'Reading', question: 'J’aime pratiquer de la natation.', answer: 'la natation', instruction: 'Sport' },
    { id: 'fr5-r3', type: 'Reading', question: 'Je joue au tennis le samedi.', answer: 'tennis le samedi', instruction: 'Sport' },
    { id: 'fr5-r4', type: 'Reading', question: 'Nous faisons de la randonnée.', answer: 'la randonnée', instruction: 'Fritid' },
    { id: 'fr5-r5', type: 'Reading', question: 'Elle adore lire des romans.', answer: 'lire des romans', instruction: 'Fritid' },
    { id: 'fr5-r6', type: 'Reading', question: 'Mon frère fait de la guitare.', answer: 'de la guitare', instruction: 'Musik' },
    { id: 'fr5-r7', type: 'Reading', question: 'Quelles matières préfères-tu à l’école?', answer: 'matières préfères-tu', instruction: 'Skole' },
    { id: 'fr5-r8', type: 'Reading', question: 'J’aime les mathématiques et l’histoire.', answer: 'mathématiques et l’histoire', instruction: 'Skole' },
    { id: 'fr5-r9', type: 'Reading', question: 'Le professeur explique la leçon.', answer: 'explique la leçon', instruction: 'Skole' },
    { id: 'fr5-r10', type: 'Reading', question: 'Nous avons un examen demain.', answer: 'un examen demain', instruction: 'Skole' },
    { id: 'fr5-r11', type: 'Reading', question: 'Étudiez bien pour réussir.', answer: 'Étudiez bien', instruction: 'Skole' },
    { id: 'fr5-r12', type: 'Reading', question: 'La bibliothèque est un lieu calme.', answer: 'lieu calme', instruction: 'Skole' },
    { id: 'fr5-r13', type: 'Reading', question: 'Je loue des livres chaque semaine.', answer: 'loue des livres', instruction: 'Skole' },
    { id: 'fr5-r14', type: 'Reading', question: 'Quel est votre plat français favori?', answer: 'plat français favori', instruction: 'Mad' },
    { id: 'fr5-r15', type: 'Reading', question: 'J’adore les crêpes au chocolat.', answer: 'crêpes au chocolat', instruction: 'Mad' },
    { id: 'fr5-r16', type: 'Reading', question: 'La ratatouille est délicieuse.', answer: 'ratatouille', instruction: 'Mad' },
    { id: 'fr5-r17', type: 'Reading', question: 'Voulez-vous commander un dessert?', answer: 'commander un dessert', instruction: 'Restaurant' },
    { id: 'fr5-r18', type: 'Reading', question: 'Garçon, l’addition s’il vous plaît.', answer: 'l’addition', instruction: 'Restaurant' },
    { id: 'fr5-r19', type: 'Reading', question: 'Quelles sont vos prochaines vacances?', answer: 'prochaines vacances', instruction: 'Rejse' },
    { id: 'fr5-r20', type: 'Reading', question: 'Je pars en Provence cet été.', answer: 'en Provence', instruction: 'Rejse' },
    { id: 'fr5-r21', type: 'Reading', question: 'Nous visitons les châteaux de la Loire.', answer: 'châteaux de la Loire', instruction: 'Rejse' },
    { id: 'fr5-r22', type: 'Reading', question: 'La tour Eiffel est magnifique.', answer: 'magnifique', instruction: 'Seværdighed' },
    { id: 'fr5-r23', type: 'Reading', question: 'Avez-vous vu le musée du Louvre?', answer: 'musée du Louvre', instruction: 'Seværdighed' },
    { id: 'fr5-r24', type: 'Reading', question: 'Paris est la ville lumière.', answer: 'ville lumière', instruction: 'Info' },
    { id: 'fr5-r25', type: 'Reading', question: 'Le métro de Paris est très vieux.', answer: 'métro de Paris', instruction: 'Transport' },
    { id: 'fr5-r26', type: 'Reading', question: 'Je prends un taxi pour l’aéroport.', answer: 'taxi pour l’aéroport', instruction: 'Transport' },
    { id: 'fr5-r27', type: 'Reading', question: 'Le vol dure deux heures.', answer: 'vol dure deux heures', instruction: 'Transport' },
    { id: 'fr5-r28', type: 'Reading', question: 'N’oubliez pas votre passeport.', answer: 'votre passeport', instruction: 'Transport' },
    { id: 'fr5-r29', type: 'Reading', question: 'Bon voyage et amusez-vous!', answer: 'Bon voyage', instruction: 'Hilsen' },
    { id: 'fr5-r30', type: 'Reading', question: 'Dites bonjour à votre famille.', answer: 'bonjour à votre famille', instruction: 'Hilsen' },
    { id: 'fr5-r31', type: 'Reading', question: 'Quel est votre animal domestique?', answer: 'animal domestique', instruction: 'Dyr' },
    { id: 'fr5-r32', type: 'Reading', question: 'J’ai un chat très paresseux.', answer: 'très paresseux', instruction: 'Dyr' },
    { id: 'fr5-r33', type: 'Reading', question: 'Les chevaux sont des animaux nobles.', answer: 'animaux nobles', instruction: 'Dyr' },
    { id: 'fr5-r34', type: 'Reading', question: 'La nature est importante pour nous.', answer: 'nature est importante', instruction: 'Miljø' },
    { id: 'fr5-r35', type: 'Reading', question: 'Il faut protéger l’environnement.', answer: 'protéger l’environnement', instruction: 'Miljø' },
    { id: 'fr5-r36', type: 'Reading', question: 'Je recycle le papier et le verre.', answer: 'Je recycle', instruction: 'Miljø' },
    { id: 'fr5-r37', type: 'Reading', question: 'Quelles sont vos résolutions?', answer: 'résolutions', instruction: 'Livet' },
    { id: 'fr5-r38', type: 'Reading', question: 'Je veux apprendre à cuisiner.', answer: 'apprendre à cuisiner', instruction: 'Fritid' },
    { id: 'fr5-r39', type: 'Reading', question: 'Cuisiner est une forme d’art.', answer: 'forme d’art', instruction: 'Fritid' },
    { id: 'fr5-r40', type: 'Reading', question: 'Mélangez le sucre et la farine.', answer: 'sucre et la farine', instruction: 'Opskrift' },
    { id: 'fr5-r41', type: 'Reading', question: 'Ajoutez trois œufs dans le bol.', answer: 'trois œufs', instruction: 'Opskrift' },
    { id: 'fr5-r42', type: 'Reading', question: 'Cuisez au four pendant vingt minutes.', answer: 'au four', instruction: 'Opskrift' },
    { id: 'fr5-r43', type: 'Reading', question: 'Laissez refroidir avant de servir.', answer: 'Laissez refroidir', instruction: 'Opskrift' },
    { id: 'fr5-r44', type: 'Reading', question: 'C’est une recette de grand-mère.', answer: 'recette de grand-mère', instruction: 'Tradition' },
    { id: 'fr5-r45', type: 'Reading', question: 'Quel est votre plus grand rêve?', answer: 'plus grand rêve', instruction: 'Livet' },
    { id: 'fr5-r46', type: 'Reading', question: 'Je rêve de visiter le monde entier.', answer: 'monde entier', instruction: 'Livet' },
    { id: 'fr5-r47', type: 'Reading', question: 'Le bonheur est dans les petites choses.', answer: 'bonheur', instruction: 'Filosofi' },
    { id: 'fr5-r48', type: 'Reading', question: 'Soyez toujours gentil avec les autres.', answer: 'toujours gentil', instruction: 'Filosofi' },
    { id: 'fr5-r49', type: 'Reading', question: 'L’amitié est un trésor.', answer: 'L’amitié', instruction: 'Filosofi' },
    { id: 'fr5-r50', type: 'Reading', question: 'La persévérance mène au succès.', answer: 'succès', instruction: 'Filosofi' },
    { id: 'fr5-r51', type: 'Reading', question: 'Merci pour votre attention.', answer: 'votre attention', instruction: 'Afslutning' },
  ],
  6: [
    { id: 'fr6-r1', type: 'Reading', question: 'Bonjour !', answer: 'Bonjour !', instruction: 'Læs hilsnen' },
    { id: 'fr6-r2', type: 'Reading', question: 'Salut, ça va ?', answer: 'Salut, ça va ?', instruction: 'Læs spørgsmålet' },
    { id: 'fr6-r3', type: 'Reading', question: 'Je m’appelle Alba.', answer: 'Je m’appelle Alba.', instruction: 'Læs navnet' },
    { id: 'fr6-r4', type: 'Reading', question: 'J’ai douze ans.', answer: 'J’ai douze ans.', instruction: 'Læs alderen' },
    { id: 'fr6-r5', type: 'Reading', question: 'J’habite au Danemark.', answer: 'J’habite au Danemark.', instruction: 'Læs bopæl' },
    { id: 'fr6-r6', type: 'Reading', question: 'Ma famille est super.', answer: 'Ma famille est super.', instruction: 'Læs om familie' },
    { id: 'fr6-r7', type: 'Reading', question: 'J’aime le foot.', answer: 'J’aime le foot.', instruction: 'Læs om hobby' },
    { id: 'fr6-r8', type: 'Reading', question: 'Au revoir !', answer: 'Au revoir !', instruction: 'Læs farvel' },
    { id: 'fr6-r9', type: 'Reading', question: 'Merci beaucoup.', answer: 'Merci beaucoup.', instruction: 'Høflighed' },
    { id: 'fr6-r10', type: 'Reading', question: 'S’il vous plaît.', answer: 'S’il vous plaît.', instruction: 'Høflighed' },
    { id: 'fr6-r11', type: 'Reading', question: 'Un, deux, trois.', answer: 'Un, deux, tre.', instruction: 'Tal' },
    { id: 'fr6-r12', type: 'Reading', question: 'Quatre, cinq, six.', answer: 'Fire, fem, seks.', instruction: 'Tal' },
  ],
  7: [
    { id: 'fr7-r1', type: 'Reading', question: 'Je voudrais une baguette, s’il vous plaît.', answer: 'une baguette', instruction: 'À la boulangerie' },
    { id: 'fr7-r2', type: 'Reading', question: 'Avez-vous des croissants frais ce matin?', answer: 'croissants frais', instruction: 'À la boulangerie' },
    { id: 'fr7-r3', type: 'Reading', question: 'Je prends aussi un pain au chocolat.', answer: 'pain au chocolat', instruction: 'À la boulangerie' },
    { id: 'fr7-r4', type: 'Reading', question: 'Est-ce que vous faites des gâteaux pour les anniversaires?', answer: 'gâteaux pour les anniversaires', instruction: 'À la boulangerie' },
    { id: 'fr7-r5', type: 'Reading', question: 'Ce sera tout, merci beaucoup.', answer: 'Ce sera tout', instruction: 'À la boulangerie' },
    { id: 'fr7-r6', type: 'Reading', question: 'Quelle est la spécialité de la région?', answer: 'spécialité de la région', instruction: 'Tourisme' },
    { id: 'fr7-r7', type: 'Reading', question: 'Le Mont Saint-Michel est un lieu historique.', answer: 'Mont Saint-Michel', instruction: 'Géographie' },
    { id: 'fr7-r8', type: 'Reading', question: 'La marée monte très rapidement ici.', answer: 'marée monte', instruction: 'Géographie' },
    { id: 'fr7-r9', type: 'Reading', question: 'Avez-vous une carte de la ville?', answer: 'carte de la ville', instruction: 'Tourisme' },
    { id: 'fr7-r10', type: 'Reading', question: 'Le centre-ville est piétonnier.', answer: 'centre-ville est piétonnier', instruction: 'Tourisme' },
    { id: 'fr7-r11', type: 'Reading', question: 'Il y a beaucoup de cafés en terrasse.', answer: 'cafés en terrasse', instruction: 'Vie sociale' },
    { id: 'fr7-r12', type: 'Reading', question: 'Les Français aiment discuter pendant des heures.', answer: 'discuter pendant des heures', instruction: 'Culture' },
    { id: 'fr7-r13', type: 'Reading', question: 'Le café au lait est servi le matin.', answer: 'café au lait', instruction: 'Cuisine' },
    { id: 'fr7-r14', type: 'Reading', question: 'Le petit-déjeuner français est souvent sucré.', answer: 'souvent sucré', instruction: 'Cuisine' },
    { id: 'fr7-r15', type: 'Reading', question: 'Voulez-vous du beurre avec votre tartine?', answer: 'beurre avec votre tartine', instruction: 'Cuisine' },
    { id: 'fr7-r16', type: 'Reading', question: 'La confiture d’abricot est ma préférée.', answer: 'confiture d’abricot', instruction: 'Cuisine' },
    { id: 'fr7-r17', type: 'Reading', question: 'Quel est votre loisir préféré pendant le weekend?', answer: 'loisir préféré', instruction: 'Loisirs' },
    { id: 'fr7-r18', type: 'Reading', question: 'J’aime aller au marché le dimanche matin.', answer: 'aller au marché', instruction: 'Vie sociale' },
    { id: 'fr7-r19', type: 'Reading', question: 'On y trouve des produits locaux et frais.', answer: 'produits locaux', instruction: 'Commerce' },
    { id: 'fr7-r20', type: 'Reading', question: 'Les fromages français sont renommés mondialement.', answer: 'fromages français', instruction: 'Culture' },
    { id: 'fr7-r21', type: 'Reading', question: 'Le camembert est un fromage très connu.', answer: 'camembert', instruction: 'Cuisine' },
    { id: 'fr7-r22', type: 'Reading', question: 'Il y a plus de mille variétés de fromages.', answer: 'mille variétés', instruction: 'Cuisine' },
    { id: 'fr7-r23', type: 'Reading', question: 'Aimez-vous le fromage à pâte dure eller molle?', answer: 'dure eller molle', instruction: 'Cuisine' },
    { id: 'fr7-r24', type: 'Reading', question: 'Le roquefort est un fromage blet.', answer: 'roquefort', instruction: 'Cuisine' },
    { id: 'fr7-r25', type: 'Reading', question: 'C’est une question de goût personnel.', answer: 'goût personnel', instruction: 'Vie sociale' },
    { id: 'fr7-r26', type: 'Reading', question: 'Le sport le plus populaire en France est le football.', answer: 'football', instruction: 'Sports' },
    { id: 'fr7-r27', type: 'Reading', question: 'L’équipe nationale s’appelle les Bleus.', answer: 'les Bleus', instruction: 'Sports' },
    { id: 'fr7-r28', type: 'Reading', question: 'Ils ont gagné la coupe du monde.', answer: 'coupe du monde', instruction: 'Sports' },
    { id: 'fr7-r29', type: 'Reading', question: 'Le cyclisme est aussi très apprécié.', answer: 'cyclisme', instruction: 'Sports' },
    { id: 'fr7-r30', type: 'Reading', question: 'Le Tour de France a lieu chaque mois de juillet.', answer: 'Tour de France', instruction: 'Sports' },
    { id: 'fr7-r31', type: 'Reading', question: 'Les coureurs traversent tout le pays.', answer: 'traversent tout le pays', instruction: 'Sports' },
    { id: 'fr7-r32', type: 'Reading', question: 'L’arrivée se fait sur les Champs-Élysées.', answer: 'Champs-Élysées', instruction: 'Sports' },
    { id: 'fr7-r33', type: 'Reading', question: 'C’est un événement sportif majeur.', answer: 'événement sportif', instruction: 'Sports' },
    { id: 'fr7-r34', type: 'Reading', question: 'Quel temps fait-il dans le sud de la France?', answer: 'sud de la France', instruction: 'Météo' },
    { id: 'fr7-r35', type: 'Reading', question: 'Il y a beaucoup de soleil en été.', answer: 'beaucoup de soleil', instruction: 'Météo' },
    { id: 'fr7-r36', type: 'Reading', question: 'Le mistral est un vent très fort et froid.', answer: 'le mistral', instruction: 'Météo' },
    { id: 'fr7-r37', type: 'Reading', question: 'Les cigales chantent dans les pins.', answer: 'cigales chantent', instruction: 'Nature' },
    { id: 'fr7-r38', type: 'Reading', question: 'L’odeur de la lavande est relaxante.', answer: 'odeur de la lavande', instruction: 'Nature' },
    { id: 'fr7-r39', type: 'Reading', question: 'Provence est célèbre pour ses paysages.', answer: 'Provence', instruction: 'Géographie' },
    { id: 'fr7-r40', type: 'Reading', question: 'Voulez-vous visiter un domaine viticole?', answer: 'domaine viticole', instruction: 'Tourisme' },
    { id: 'fr7-r41', type: 'Reading', question: 'La France est le premier producteur de vin.', answer: 'producteur de vin', instruction: 'Économie' },
    { id: 'fr7-r42', type: 'Reading', question: 'La consommation est modérée mais courante.', answer: 'courante', instruction: 'Vie sociale' },
    { id: 'fr7-r43', type: 'Reading', question: 'Le champagne est utilisé pour les célébrations.', answer: 'champagne', instruction: 'Célébration' },
    { id: 'fr7-r44', type: 'Reading', question: 'C’est un produit de luxe exporté partout.', answer: 'produit de luxe', instruction: 'Économie' },
    { id: 'fr7-r45', type: 'Reading', question: 'Quel est le fleuve qui traverse Paris?', answer: 'fleuve qui traverse Paris', instruction: 'Géographie' },
    { id: 'fr7-r46', type: 'Reading', question: 'La Seine divise la ville en deux rives.', answer: 'La Seine', instruction: 'Géographie' },
    { id: 'fr7-r47', type: 'Reading', question: 'On peut faire des croisières en bateau-mouche.', answer: 'bateau-mouche', instruction: 'Tourisme' },
    { id: 'fr7-r48', type: 'Reading', question: 'Les ponts de Paris sont très anciens.', answer: 'ponts de Paris', instruction: 'Architecture' },
    { id: 'fr7-r49', type: 'Reading', question: 'Le Pont Neuf est paradoxalement le plus vieux.', answer: 'Pont Neuf', instruction: 'Architecture' },
    { id: 'fr7-r50', type: 'Reading', question: 'C’est un symbole de la capitale française.', answer: 'symbole de la capitale', instruction: 'Symbol' },
    { id: 'fr7-r51', type: 'Reading', question: 'La vie à Paris est très animée.', answer: 'vie à Paris', instruction: 'Société' },
    { id: 'fr7-r52', type: 'Reading', question: 'Claude Monet aimait peindre son jardin à Giverny.', answer: 'Monet', instruction: 'Art/Histoire' },
    { id: 'fr7-r53', type: 'Reading', question: 'Saint-Exupéry est l’auteur du Petit Prince.', answer: 'Saint-Exupéry', instruction: 'Littérature' },
    { id: 'fr7-r54', type: 'Reading', question: 'En hiver, nous allons faire du ski à la montagne.', answer: 'vacances au ski', instruction: 'Loisirs' },
    { id: 'fr7-r55', type: 'Reading', question: 'Il y a beaucoup de neige dans les Alpes.', answer: 'neige dans les Alpes', instruction: 'Météo' },
    { id: 'fr7-r56', type: 'Reading', question: 'Vive les animaux ! J’adore les chiens et les chats.', answer: 'les animaux', instruction: 'Nature' },
  ],
  8: [
    { id: 'fr8-r1', type: 'Reading', question: 'Stromae est un chanteur belge.', answer: 'chanteur belge', instruction: 'Kultur' },
    { id: 'fr8-r2', type: 'Reading', question: 'La musique francophone est très diversifiée.', answer: 'musique francophone', instruction: 'Culture' },
    { id: 'fr8-r3', type: 'Reading', question: 'Connaissez-vous Édith Piaf et sa vie en rose?', answer: 'Édith Piaf', instruction: 'Musique' },
    { id: 'fr8-r4', type: 'Reading', question: 'Le rap français est le deuxième plus grand marché.', answer: 'rap français', instruction: 'Musique' },
    { id: 'fr8-r5', type: 'Reading', question: 'Les paroles sont souvent engagées socialement.', answer: 'paroles engagées', instruction: 'Société' },
    { id: 'fr8-r6', type: 'Reading', question: 'La littérature du XIXe siècle est passionnante.', answer: 'littérature du XIXe', instruction: 'Littérature' },
    { id: 'fr8-r7', type: 'Reading', question: 'Honoré de Balzac a écrit la Comédie humaine.', answer: 'Balzac', instruction: 'Littérature' },
    { id: 'fr8-r8', type: 'Reading', question: 'C’est une fresque monumentale de la société.', answer: 'fresque monumentale', instruction: 'Littérature' },
    { id: 'fr8-r9', type: 'Reading', question: 'Gustave Flaubert est connu pour Madame Bovary.', answer: 'Flaubert', instruction: 'Littérature' },
    { id: 'fr8-r10', type: 'Reading', question: 'Le style est précis et très travaillé.', answer: 'style précis', instruction: 'Littérature' },
    { id: 'fr8-r11', type: 'Reading', question: 'Quelles sont les valeurs de la République?', answer: 'valeurs de la République', instruction: 'Civisme' },
    { id: 'fr8-r12', type: 'Reading', question: 'La laïcité est un principe fondamental en France.', answer: 'laïcité', instruction: 'Civisme' },
    { id: 'fr8-r13', type: 'Reading', question: 'Elle garantit la liberté de conscience.', answer: 'liberté de conscience', instruction: 'Politique' },
    { id: 'fr8-r14', type: 'Reading', question: 'L’école publique est gratuite et obligatoire.', answer: 'gratuite et obligatoire', instruction: 'Éducation' },
    { id: 'fr8-r15', type: 'Reading', question: 'Le baccalauréat est l’examen de fin de lycée.', answer: 'baccalauréat', instruction: 'Éducation' },
    { id: 'fr8-r16', type: 'Reading', question: 'C’est une étape cruciale pour les jeunes.', answer: 'étape cruciale', instruction: 'Éducation' },
    { id: 'fr8-r17', type: 'Reading', question: 'Quelles sont vos ambitions professionnelles?', answer: 'ambitions professionnelles', instruction: 'Avenir' },
    { id: 'fr8-r18', type: 'Reading', question: 'Je voudrais faire des études d’ingénieur.', answer: 'études d’ingénieur', instruction: 'Projet' },
    { id: 'fr8-r19', type: 'Reading', question: 'Les grandes écoles sont très sélectives.', answer: 'sélectives', instruction: 'Éducation' },
    { id: 'fr8-r20', type: 'Reading', question: 'Le monde du travail change avec la technologie.', answer: 'travail change', instruction: 'Économie' },
    { id: 'fr8-r21', type: 'Reading', question: 'Le télétravail devient une pratique courante.', answer: 'télétravail', instruction: 'Société' },
    { id: 'fr8-r22', type: 'Reading', question: 'Quels sont les avantages de la vie citadine?', answer: 'avantages de la vie citadine', instruction: 'Urbanisme' },
    { id: 'fr8-r23', type: 'Reading', question: 'L’accès à la culture est plus facile.', answer: 'accès à la culture', instruction: 'Société' },
    { id: 'fr8-r24', type: 'Reading', question: 'Mais la pollution est un problème majeur.', answer: 'pollution', instruction: 'Environnement' },
    { id: 'fr8-r25', type: 'Reading', question: 'Le transport en commun réduit l’empreinte carbone.', answer: 'empreinte carbone', instruction: 'Écologie' },
    { id: 'fr8-r26', type: 'Reading', question: 'La gastronomie française est inscrite à l’UNESCO.', answer: 'gastronomie française', instruction: 'Culture' },
    { id: 'fr8-r27', type: 'Reading', question: 'C’est un patrimoine immatériel de l’humanité.', answer: 'patrimoine immatériel', instruction: 'Culture' },
    { id: 'fr8-r28', type: 'Reading', question: 'Le repas gastronomique est un rituel social.', answer: 'rituel social', instruction: 'Tradition' },
    { id: 'fr8-r29', type: 'Reading', question: 'Il comprend une succession de plats précis.', answer: 'succession de plats', instruction: 'Cuisine' },
    { id: 'fr8-r30', type: 'Reading', question: 'L’art de la table est très respecté.', answer: 'art de la table', instruction: 'Savoir-vivre' },
    { id: 'fr8-r31', type: 'Reading', question: 'Quelles sont les fêtes traditionnelles en France?', answer: 'fêtes traditionnelles', instruction: 'Folklore' },
    { id: 'fr8-r32', type: 'Reading', question: 'Le quatorze juillet célèbre la prise de la Bastille.', answer: 'prise de la Bastille', instruction: 'Histoire' },
    { id: 'fr8-r33', type: 'Reading', question: 'C’est la fête nationale avec des défilés.', answer: 'défilés', instruction: 'Célébration' },
    { id: 'fr8-r34', type: 'Reading', question: 'Noël est une fête familiale importante.', answer: 'fête familiale', instruction: 'Célébration' },
    { id: 'fr8-r35', type: 'Reading', question: 'On mange souvent de la dinde et des marrons.', answer: 'dinde et marrons', instruction: 'Cuisine' },
    { id: 'fr8-r36', type: 'Reading', question: 'La galette des rois se mange en janvier.', answer: 'galette des rois', instruction: 'Tradition' },
    { id: 'fr8-r37', type: 'Reading', question: 'Celui qui trouve la fève devient roi.', answer: 'trouve la fève', instruction: 'Tradition' },
    { id: 'fr8-r38', type: 'Reading', question: 'Le cinéma français est appelé le septième art.', answer: 'septième art', instruction: 'Culture' },
    { id: 'fr8-r39', type: 'Reading', question: 'Les frères Lumière ont inventé le cinématographe.', answer: 'Lumière', instruction: 'Histoire' },
    { id: 'fr8-r40', type: 'Reading', question: 'La France produit beaucoup de films chaque année.', answer: 'produit beaucoup de films', instruction: 'Industrie' },
    { id: 'fr8-r41', type: 'Reading', question: 'Les comédies sont très populaires auprès du public.', answer: 'comédies', instruction: 'Cinéma' },
    { id: 'fr8-r42', type: 'Reading', question: 'Quelle est l’influence de la mode française?', answer: 'influence de la mode', instruction: 'Style' },
    { id: 'fr8-r43', type: 'Reading', question: 'Paris est considérée comme la capitale de la mode.', answer: 'capitale de la mode', instruction: 'Économique' },
    { id: 'fr8-r44', type: 'Reading', question: 'La haute couture est un savoir-faire unique.', answer: 'haute couture', instruction: 'Artisanat' },
    { id: 'fr8-r45', type: 'Reading', question: 'Les défilés de mode attirent les célébrités.', answer: 'défilés de mode', instruction: 'Événement' },
    { id: 'fr8-r46', type: 'Reading', question: 'Quels sont les enjeux de la francophonie?', answer: 'francophonie', instruction: 'Géopolitique' },
    { id: 'fr8-r47', type: 'Reading', question: 'La langue française est parlée sur cinq continents.', answer: 'cinq continents', instruction: 'Langue' },
    { id: 'fr8-r48', type: 'Reading', question: 'Elle favorise les échanges culturels et économiques.', answer: 'échanges culturels', instruction: 'Diplomatie' },
    { id: 'fr8-r49', type: 'Reading', question: 'C’est un lien entre des peuples divers.', answer: 'lien entre des peuples', instruction: 'Humanisme' },
    { id: 'fr8-r50', type: 'Reading', question: 'Apprendre le français ouvre de nombreuses portes.', answer: 'nombreuses portes', instruction: 'Éducation' },
    { id: 'fr8-r51', type: 'Reading', question: 'Nous finissons ce chapitre sur la culture.', answer: 'finissons ce chapitre', instruction: 'Conclusion' },
    { id: 'fr8-r52', type: 'Reading', question: 'Stromae chante "Papaoutai" et "Formidable".', answer: 'Stromae', instruction: 'Musique' },
    { id: 'fr8-r53', type: 'Reading', question: 'Louane est une jeune chanteuse très talentueuse.', answer: 'Louane', instruction: 'Musique' },
    { id: 'fr8-r54', type: 'Reading', question: 'Coco Chanel a révolutionné la mode féminine.', answer: 'Coco Chanel', instruction: 'Mode/Histoire' },
    { id: 'fr8-r55', type: 'Reading', question: 'L’Intelligence Artificielle (IA) change notre futur.', answer: 'IA', instruction: 'Technologie' },
    { id: 'fr8-r56', type: 'Reading', question: 'Au Québec, on mange de la poutine délicieuse.', answer: 'Québec', instruction: 'Gastronomie' },
    { id: 'fr8-r57', type: 'Reading', question: 'La Suisse est célèbre pour son chocolat et ses montagnes.', answer: 'Suisse', instruction: 'Géographie' },
  ],
  9: [
    { id: 'fr9-r1', type: 'Reading', question: 'Je voudrais deux croissants, s’il vous plaît.', answer: 'deux croissants', instruction: 'Bestilling hos bageren' },
    { id: 'fr9-r2', type: 'Reading', question: 'Le maillot jaune du Tour de France.', answer: 'maillot jaune', instruction: 'Sport' },
    { id: 'fr9-r3', type: 'Reading', question: 'L’existentialisme est un courant philosophique.', answer: 'existentialisme', instruction: 'Philosophie' },
    { id: 'fr9-r4', type: 'Reading', question: 'Jean-Paul Sartre en est un représentant.', answer: 'Sartre', instruction: 'Philosophie' },
    { id: 'fr9-r5', type: 'Reading', question: 'L’existence précède l’essence selon lui.', answer: 'existence précède l’essence', instruction: 'Philosophie' },
    { id: 'fr9-r6', type: 'Reading', question: 'C’est une réflexion sur la liberté humaine.', answer: 'liberté humaine', instruction: 'Philosophie' },
    { id: 'fr9-r7', type: 'Reading', question: 'Albert Camus a écrit l’Étranger.', answer: 'Camus', instruction: 'Littérature' },
    { id: 'fr9-r8', type: 'Reading', question: 'Le thème de l’absurde y est central.', answer: 'thème de l’absurde', instruction: 'Littérature' },
    { id: 'fr9-r9', type: 'Reading', question: 'La France est un pays membre de l’Union Européenne.', answer: 'Union Européenne', instruction: 'Géopolitique' },
    { id: 'fr9-r10', type: 'Reading', question: 'Elle a participé à sa fondation historique.', answer: 'fondation historique', instruction: 'Histoire' },
    { id: 'fr9-r11', type: 'Reading', question: 'L’euro est la monnaie commune depuis deux mille deux.', answer: 'l’euro', instruction: 'Économie' },
    { id: 'fr9-r12', type: 'Reading', question: 'Le Parlement européen siège à Strasbourg.', answer: 'Strasbourg', instruction: 'Politique' },
    { id: 'fr9-r13', type: 'Reading', question: 'C’est un symbole de la coopération pacifique.', answer: 'coopération pacifique', instruction: 'Politique' },
    { id: 'fr9-r14', type: 'Reading', question: 'Quelles sont les réformes sociales actuelles?', answer: 'réformes sociales', instruction: 'Société' },
    { id: 'fr9-r15', type: 'Reading', question: 'Le débat sur les retraites est intense.', answer: 'débat sur les retraites', instruction: 'Politique' },
    { id: 'fr9-r16', type: 'Reading', question: 'Les syndicats organisent des manifestations.', answer: 'manifestations', instruction: 'Société' },
    { id: 'fr9-r17', type: 'Reading', question: 'Le dialogue social est parfois difficile.', answer: 'dialogue social', instruction: 'Société' },
    { id: 'fr9-r18', type: 'Reading', question: 'La protection sociale est un pilier du modèle.', answer: 'protection sociale', instruction: 'Société' },
    { id: 'fr9-r19', type: 'Reading', question: 'Le système de santé est accessible à tous.', answer: 'système de santé', instruction: 'Santé' },
    { id: 'fr9-r20', type: 'Reading', question: 'L’intelligence artificielle transforme l’économie.', answer: 'intelligence artificielle', instruction: 'Technologie' },
    { id: 'fr9-r21', type: 'Reading', question: 'Le pays investit dans les nouvelles technologies.', answer: 'nouvelles technologies', instruction: 'Innovation' },
    { id: 'fr9-r22', type: 'Reading', question: 'Les start-ups françaises sont très dynamiques.', answer: 'start-ups', instruction: 'Économie' },
    { id: 'fr9-r23', type: 'Reading', question: 'La "French Tech" est une initiative reconnue.', answer: 'French Tech', instruction: 'Économie' },
    { id: 'fr9-r24', type: 'Reading', question: 'La transition écologique est une priorité.', answer: 'transition écologique', instruction: 'Écologie' },
    { id: 'fr9-r25', type: 'Reading', question: 'Réduire les émissions de gaz à effet de serre.', answer: 'effet de serre', instruction: 'Climat' },
    { id: 'fr9-r26', type: 'Reading', question: 'Développer les énergies renouvelables.', answer: 'énergies renouvelables', instruction: 'Énergie' },
    { id: 'fr9-r27', type: 'Reading', question: 'L’énergie nucléaire reste importante en France.', answer: 'énergie nucléaire', instruction: 'Énergie' },
    { id: 'fr9-r28', type: 'Reading', question: 'C’est un sujet de débat pour l’avenir.', answer: 'débat pour l’avenir', instruction: 'Société' },
    { id: 'fr9-r29', type: 'Reading', question: 'Qu’est-ce que l’exception culturelle française?', answer: 'exception culturelle', instruction: 'Culture' },
    { id: 'fr9-r30', type: 'Reading', question: 'C’est une politique de soutien aux arts.', answer: 'soutien aux arts', instruction: 'Politique' },
    { id: 'fr9-r31', type: 'Reading', question: 'Elle protège la diversité des expressions.', answer: 'diversité', instruction: 'Culture' },
    { id: 'fr9-r32', type: 'Reading', question: 'Le prix unique du livre en fait partie.', answer: 'prix unique du livre', instruction: 'Culture' },
    { id: 'fr9-r33', type: 'Reading', question: 'Le ministère de la Culture joue un rôle clé.', answer: 'ministère de la Culture', instruction: 'Politique' },
    { id: 'fr9-r34', type: 'Reading', question: 'Quel est l’héritage des Lumières?', answer: 'héritage des Lumières', instruction: 'Histoire' },
    { id: 'fr9-r35', type: 'Reading', question: 'La raison et le progrès scientifique.', answer: 'raison et progrès', instruction: 'Philosophie' },
    { id: 'fr9-r36', type: 'Reading', question: 'Voltaire luttait contre le fanatisme.', answer: 'Voltaire', instruction: 'Histoire' },
    { id: 'fr9-r37', type: 'Reading', question: 'Rousseau a écrit le Contrat Social.', answer: 'Rousseau', instruction: 'Philosophie' },
    { id: 'fr9-r38', type: 'Reading', question: 'Ces idées ont inspiré la Révolution.', answer: 'Révolution', instruction: 'Histoire' },
    { id: 'fr9-r39', type: 'Reading', question: 'La déclaration des droits de l’homme.', answer: 'droits de l’homme', instruction: 'Histoire' },
    { id: 'fr9-r40', type: 'Reading', question: 'Elle a une portée universelle.', answer: 'portée universelle', instruction: 'Civisme' },
    { id: 'fr9-r41', type: 'Reading', question: 'Comment voyez-vous l’avenir de l’Europe?', answer: 'avenir de l’Europe', instruction: 'Prospective' },
    { id: 'fr9-r42', type: 'Reading', question: 'Vers une plus grande intégration politique?', answer: 'intégration politique', instruction: 'Politique' },
    { id: 'fr9-r43', type: 'Reading', question: 'Les défis sont nombreux et complexes.', answer: 'nombreux et complexes', instruction: 'Société' },
    { id: 'fr9-r44', type: 'Reading', question: 'La solidarité européenne est mise à l’épreuve.', answer: 'solidarité européenne', instruction: 'Géo' },
    { id: 'fr9-r45', type: 'Reading', question: 'C’est un projet de paix ambitieux.', answer: 'projet de paix', instruction: 'Hilsen' },
    { id: 'fr9-r46', type: 'Reading', question: 'La jeunesse doit s’impliquer davantage.', answer: 's’impliquer davantage', instruction: 'Société' },
    { id: 'fr9-r47', type: 'Reading', question: 'L’éducation est la clé du changement.', answer: 'clé du changement', instruction: 'Éducation' },
    { id: 'fr9-r48', type: 'Reading', question: 'Rien n’est impossible avec de la volonté.', answer: 'volonté', instruction: 'Motivation' },
    { id: 'fr9-r49', type: 'Reading', question: 'Le monde appartient à ceux qui rêvent.', answer: 'ceux qui rêvent', instruction: 'Motivation' },
    { id: 'fr9-r50', type: 'Reading', question: 'Merci d’avoir partagé ce moment.', answer: 'partagé ce moment', instruction: 'Conclusion' },
    { id: 'fr9-r51', type: 'Reading', question: 'La langue française est une fenêtre sur le monde.', answer: 'fenêtre sur le monde', instruction: 'Final' },
    { id: 'fr9-r52', type: 'Reading', question: 'Maître Gims porte toujours des lunettes noires.', answer: 'Maître Gims', instruction: 'Célébrité' },
    { id: 'fr9-r53', type: 'Reading', question: 'Omar Sy joue le rôle principal dans Intouchables.', answer: 'Omar Sy', instruction: 'Cinéma' },
    { id: 'fr9-r54', type: 'Reading', question: 'Kylian Mbappé est la star du foot français.', answer: 'Mbappé', instruction: 'Sports' },
    { id: 'fr9-r55', type: 'Reading', question: 'Le Tour de France recommence chaque été.', answer: 'Tour de France', instruction: 'Événement' },
    { id: 'fr9-r56', type: 'Reading', question: 'L’île Maurice se trouve dans l’océan Indien.', answer: 'Maurice', instruction: 'Géographie' },
    { id: 'fr9-r57', type: 'Reading', question: 'Le français est la langue officielle à Maurice.', answer: 'Maurice', instruction: 'Francophonie' },
  ]
};
