/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const TYSK_READING: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'de0-r1', type: 'Reading', question: 'Guten Tag, wie geht es dir?', answer: 'Guten Tag', instruction: 'Læs hilsnen' },
    { id: 'de0-r2', type: 'Reading', question: 'Ich sehe eine Katze.', answer: 'Katze', instruction: 'Læs ordet' },
    { id: 'de0-r3', type: 'Reading', question: 'Der Hund ist groß.', answer: 'Hund', instruction: 'Læs ordet' },
    { id: 'de0-r4', type: 'Reading', question: 'Ein roter Apfel.', answer: 'Apfel', instruction: 'Læs ordet' },
    { id: 'de0-r5', type: 'Reading', question: 'Das Auto ist blau.', answer: 'Auto', instruction: 'Læs ordet' },
    { id: 'de0-r6', type: 'Reading', question: 'Die Sonne scheint.', answer: 'Sonne', instruction: 'Læs ordet' },
    { id: 'de0-r7', type: 'Reading', question: 'Ein kleiner Vogel.', answer: 'Vogel', instruction: 'Læs ordet' },
    { id: 'de0-r8', type: 'Reading', question: 'Ich liebe Milch.', answer: 'Milch', instruction: 'Læs ordet' },
    { id: 'de0-r9', type: 'Reading', question: 'Brot und Wasser.', answer: 'Brot', instruction: 'Læs ordet' },
    { id: 'de0-r10', type: 'Reading', question: 'Das ist ein Haus.', answer: 'Haus', instruction: 'Læs ordet' },
    { id: 'de0-r11', type: 'Reading', question: 'Mein Name ist Pol.', answer: 'Pol', instruction: 'Læs ordet' },
    { id: 'de0-r12', type: 'Reading', question: 'Hallo, mein Freund.', answer: 'Freund', instruction: 'Læs ordet' },
    { id: 'de0-r13', type: 'Reading', question: 'Eins, zwei, drei.', answer: 'drei', instruction: 'Tæl med' },
    { id: 'de0-r14', type: 'Reading', question: 'Der Mond ist hell.', answer: 'Mond', instruction: 'Læs ordet' },
    { id: 'de0-r15', type: 'Reading', question: 'Ein grüner Baum.', answer: 'Baum', instruction: 'Læs ordet' },
    { id: 'de0-r16', type: 'Reading', question: 'Das Kind spielt.', answer: 'Kind', instruction: 'Læs ordet' },
    { id: 'de0-r17', type: 'Reading', question: 'Wir gehen jetzt.', answer: 'gehen', instruction: 'Læs ordet' },
    { id: 'de0-r18', type: 'Reading', question: 'Süßer kleiner Bär.', answer: 'Bär', instruction: 'Læs ordet' },
    { id: 'de0-r19', type: 'Reading', question: 'Eine gelbe Ente.', answer: 'Ente', instruction: 'Læs ordet' },
    { id: 'de0-r20', type: 'Reading', question: 'Fisch im Wasser.', answer: 'Fisch', instruction: 'Læs ordet' },
    { id: 'de0-r21', type: 'Reading', question: 'Das ist mein Buch.', answer: 'Buch', instruction: 'Læs ordet' },
    { id: 'de0-r22', type: 'Reading', question: 'Schau mal her.', answer: 'Schau', instruction: 'Læs ordet' },
    { id: 'de0-r23', type: 'Reading', question: 'Lauf so schnell.', answer: 'Lauf', instruction: 'Læs ordet' },
    { id: 'de0-r24', type: 'Reading', question: 'Komm bitte mit.', answer: 'Komm', instruction: 'Læs ordet' },
    { id: 'de0-r25', type: 'Reading', question: 'Ein schöner Tag.', answer: 'Tag', instruction: 'Læs ordet' },
    { id: 'de0-r26', type: 'Reading', question: 'Gute Nacht, Mama.', answer: 'Nacht', instruction: 'Læs ordet' },
    { id: 'de0-r27', type: 'Reading', question: 'Papa ist da.', answer: 'Papa', instruction: 'Læs ordet' },
    { id: 'de0-r28', type: 'Reading', question: 'Ich habe Hunger.', answer: 'Hunger', instruction: 'Læs ordet' },
    { id: 'de0-r29', type: 'Reading', question: 'Durst ist schlimm.', answer: 'Durst', instruction: 'Læs ordet' },
    { id: 'de0-r30', type: 'Reading', question: 'Apfelsaft ist gut.', answer: 'Saft', instruction: 'Læs ordet' },
    { id: 'de0-r31', type: 'Reading', question: 'Kuchen schmeckt süß.', answer: 'süß', instruction: 'Læs ordet' },
    { id: 'de0-r32', type: 'Reading', question: 'Das Eis ist kalt.', answer: 'Eis', instruction: 'Læs ordet' },
    { id: 'de0-r33', type: 'Reading', question: 'Feuer ist heiß.', answer: 'heiß', instruction: 'Læs ordet' },
    { id: 'de0-r34', type: 'Reading', question: 'Regen macht nass.', answer: 'Regen', instruction: 'Læs ordet' },
    { id: 'de0-r35', type: 'Reading', question: 'Schnee ist weiß.', answer: 'weiß', instruction: 'Læs ordet' },
    { id: 'de0-r36', type: 'Reading', question: 'Die Blume blüht.', answer: 'Blume', instruction: 'Læs ordet' },
    { id: 'de0-r37', type: 'Reading', question: 'Ein bunter Ball.', answer: 'Ball', instruction: 'Læs ordet' },
    { id: 'de0-r38', type: 'Reading', question: 'Vier blaue Autos.', answer: 'Vier', instruction: 'Tæl med' },
    { id: 'de0-r39', type: 'Reading', question: 'Fünf rote Äpfel.', answer: 'Fünf', instruction: 'Tæl med' },
    { id: 'de0-r40', type: 'Reading', question: 'Ich bin glücklich.', answer: 'glücklich', instruction: 'Læs ordet' },
    { id: 'de0-r41', type: 'Reading', question: 'Du bist lieb.', answer: 'lieb', instruction: 'Læs ordet' },
    { id: 'de0-r42', type: 'Reading', question: 'Wir spielen gern.', answer: 'spielen', instruction: 'Læs ordet' },
    { id: 'de0-r43', type: 'Reading', question: 'Musik ist laut.', answer: 'laut', instruction: 'Læs ordet' },
    { id: 'de0-r44', type: 'Reading', question: 'Schlaf jetzt ein.', answer: 'Schlaf', instruction: 'Læs ordet' },
    { id: 'de0-r45', type: 'Reading', question: 'Früh am Morgen.', answer: 'Morgen', instruction: 'Læs ordet' },
    { id: 'de0-r46', type: 'Reading', question: 'Spät am Abend.', answer: 'Abend', instruction: 'Læs ordet' },
    { id: 'de0-r47', type: 'Reading', question: 'Ein nettes Wort.', answer: 'Wort', instruction: 'Læs ordet' },
    { id: 'de0-r48', type: 'Reading', question: 'Gib mir die Hand.', answer: 'Hand', instruction: 'Læs ordet' },
    { id: 'de0-r49', type: 'Reading', question: 'Fuß im Schuh.', answer: 'Fuß', instruction: 'Læs ordet' },
    { id: 'de0-r50', type: 'Reading', question: 'Kopf auf Kissen.', answer: 'Kopf', instruction: 'Læs ordet' },
    { id: 'de0-r51', type: 'Reading', question: 'Das Ende ist nah.', answer: 'Ende', instruction: 'Læs ordet' },
  ],
  1: [
    { id: 'de1-r1', type: 'Reading', question: 'Die Katze schläft auf dem Sofa.', answer: 'auf dem Sofa', instruction: 'Læs sætningen' },
    { id: 'de1-r2', type: 'Reading', question: 'Der Hund rennt im Garten.', answer: 'im Garten', instruction: 'Læs sætningen' },
    { id: 'de1-r3', type: 'Reading', question: 'Ich habe einen roten Apfel.', answer: 'roten Apfel', instruction: 'Læs sætningen' },
    { id: 'de1-r4', type: 'Reading', question: 'Wir essen heute Pizza.', answer: 'essen Pizza', instruction: 'Læs sætningen' },
    { id: 'de1-r5', type: 'Reading', question: 'Die Sonne scheint heute hell.', answer: 'scheint hell', instruction: 'Læs sætningen' },
    { id: 'de1-r6', type: 'Reading', question: 'Meine Mutter ist sehr lieb.', answer: 'sehr lieb', instruction: 'Læs sætningen' },
    { id: 'de1-r7', type: 'Reading', question: 'Mein Vater arbeitet viel.', answer: 'arbeitet viel', instruction: 'Læs sætningen' },
    { id: 'de1-r8', type: 'Reading', question: 'Wir spielen im Kinderzimmer.', answer: 'im Kinderzimmer', instruction: 'Læs sætningen' },
    { id: 'de1-r9', type: 'Reading', question: 'Der Ball ist rund und bunt.', answer: 'rund und bunt', instruction: 'Læs sætningen' },
    { id: 'de1-r10', type: 'Reading', question: 'Ich gehe in den Park.', answer: 'in den Park', instruction: 'Læs sætningen' },
    { id: 'de1-r11', type: 'Reading', question: 'Ein kleiner Vogel singt.', answer: 'Vogel singt', instruction: 'Læs sætningen' },
    { id: 'de1-r12', type: 'Reading', question: 'Das Wasser ist sehr kalt.', answer: 'sehr kalt', instruction: 'Læs sætningen' },
    { id: 'de1-r13', type: 'Reading', question: 'Ich trinke kühle Milch.', answer: 'kühle Milch', instruction: 'Læs sætningen' },
    { id: 'de1-r14', type: 'Reading', question: 'Der Kuchen riecht gut.', answer: 'riecht gut', instruction: 'Læs sætningen' },
    { id: 'de1-r15', type: 'Reading', question: 'Wir basteln ein Haus.', answer: 'ein Haus', instruction: 'Læs sætningen' },
    { id: 'de1-r16', type: 'Reading', question: 'Das Auto fährt schnell.', answer: 'fährt schnell', instruction: 'Læs sætningen' },
    { id: 'de1-r17', type: 'Reading', question: 'Regen macht alles nass.', answer: 'alles nass', instruction: 'Læs sætningen' },
    { id: 'de1-r18', type: 'Reading', question: 'Im Winter liegt Schnee.', answer: 'liegt Schnee', instruction: 'Læs sætningen' },
    { id: 'de1-r19', type: 'Reading', question: 'Die Blumen blühen bunt.', answer: 'blühen bunt', instruction: 'Læs sætningen' },
    { id: 'de1-r20', type: 'Reading', question: 'Ich lese ein Buch.', answer: 'lese ein Buch', instruction: 'Læs sætningen' },
    { id: 'de1-r21', type: 'Reading', question: 'Schreib auf das Papier.', answer: 'auf das Papier', instruction: 'Læs sætningen' },
    { id: 'de1-r22', type: 'Reading', question: 'Mein Bruder hat Hunger.', answer: 'hat Hunger', instruction: 'Læs sætningen' },
    { id: 'de1-r23', type: 'Reading', question: 'Die Schwester ist klein.', answer: 'ist klein', instruction: 'Læs sætningen' },
    { id: 'de1-r24', type: 'Reading', question: 'Oma backt Kekse heute.', answer: 'backt Kekse', instruction: 'Læs sætningen' },
    { id: 'de1-r25', type: 'Reading', question: 'Opa erzählt Geschichten.', answer: 'erzählt Geschichten', instruction: 'Læs sætningen' },
    { id: 'de1-r26', type: 'Reading', question: 'Der Himmel ist blau.', answer: 'ist blau', instruction: 'Læs sætningen' },
    { id: 'de1-r27', type: 'Reading', question: 'Nachts ist es dunkel.', answer: 'ist dunkel', instruction: 'Læs sætningen' },
    { id: 'de1-r28', type: 'Reading', question: 'Sterne leuchten hell.', answer: 'leuchten hell', instruction: 'Læs sætningen' },
    { id: 'de1-r29', type: 'Reading', question: 'Der Mond ist groß.', answer: 'ist groß', instruction: 'Læs sætningen' },
    { id: 'de1-r30', type: 'Reading', question: 'Wir waschen die Hände.', answer: 'waschen Hände', instruction: 'Læs sætningen' },
    { id: 'de1-r31', type: 'Reading', question: 'Zähne putzen ist wichtig.', answer: 'ist wichtig', instruction: 'Læs sætningen' },
    { id: 'de1-r32', type: 'Reading', question: 'Zieh die Schuhe an.', answer: 'Schuhe an', instruction: 'Læs sætningen' },
    { id: 'de1-r33', type: 'Reading', question: 'Jacke zu, es ist kalt.', answer: 'es ist kalt', instruction: 'Læs sætningen' },
    { id: 'de1-r34', type: 'Reading', question: 'Komm schnell nach Hause.', answer: 'nach Hause', instruction: 'Læs sætningen' },
    { id: 'de1-r35', type: 'Reading', question: 'Der Weg ist weit.', answer: 'ist weit', instruction: 'Læs sætningen' },
    { id: 'de1-r36', type: 'Reading', question: 'Ich sehe ein Schaf.', answer: 'ein Schaf', instruction: 'Læs sætningen' },
    { id: 'de1-r37', type: 'Reading', question: 'Die Kuh macht muuh.', answer: 'macht muuh', instruction: 'Læs sætningen' },
    { id: 'de1-r38', type: 'Reading', question: 'Das Pferd ist braun.', answer: 'ist braun', instruction: 'Læs sætningen' },
    { id: 'de1-r39', type: 'Reading', question: 'Hühner legen Eier.', answer: 'legen Eier', instruction: 'Læs sætningen' },
    { id: 'de1-r40', type: 'Reading', question: 'Ich fahre Rad.', answer: 'fahre Rad', instruction: 'Læs sætningen' },
    { id: 'de1-r41', type: 'Reading', question: 'Das macht viel Spaß.', answer: 'viel Spaß', instruction: 'Læs sætningen' },
    { id: 'de1-r42', type: 'Reading', question: 'Lachen ist gesund.', answer: 'ist gesund', instruction: 'Læs sætningen' },
    { id: 'de1-r43', type: 'Reading', question: 'Wir singen ein Lied.', answer: 'ein Lied', instruction: 'Læs sætningen' },
    { id: 'de1-r44', type: 'Reading', question: 'Tanz mit mir zusammen.', answer: 'mit mir', instruction: 'Læs sætningen' },
    { id: 'de1-r45', type: 'Reading', question: 'Draußen ist es windig.', answer: 'ist windig', instruction: 'Læs sætningen' },
    { id: 'de1-r46', type: 'Reading', question: 'Ein bunter Regenbogen.', answer: 'Regenbogen', instruction: 'Læs sætningen' },
    { id: 'de1-r47', type: 'Reading', question: 'Der Wald ist grün.', answer: 'ist grün', instruction: 'Læs sætningen' },
    { id: 'de1-r48', type: 'Reading', question: 'Suche den Schatz.', answer: 'den Schatz', instruction: 'Læs sætningen' },
    { id: 'de1-r49', type: 'Reading', question: 'Guten Appetit euch.', answer: 'Appetit', instruction: 'Læs sætningen' },
    { id: 'de1-r50', type: 'Reading', question: 'Danke schön, mein Freund.', answer: 'Danke schön', instruction: 'Læs sætningen' },
    { id: 'de1-r51', type: 'Reading', question: 'Auf Wiedersehen alle.', answer: 'Wiedersehen', instruction: 'Læs sætningen' },
  ],
  2: [
    { id: 'de2-r1', type: 'Reading', question: 'Das Frühstück ist die wichtigste Mahlzeit des Tages.', answer: 'wichtigste Mahlzeit', instruction: 'Læs mere' },
    { id: 'de2-r2', type: 'Reading', question: 'In der Schule lernen wir Lesen, Schreiben und Rechnen.', answer: 'Schreiben und Rechnen', instruction: 'Skole' },
    { id: 'de2-r3', type: 'Reading', question: 'Meine Lieblingsfarbe ist ein dunkles Blau wie das Meer.', answer: 'dunkles Blau', instruction: 'Farver' },
    { id: 'de2-r4', type: 'Reading', question: 'Am Wochenende machen wir oft einen Ausflug in den Wald.', answer: 'Ausflug in Wald', instruction: 'Fritid' },
    { id: 'de2-r5', type: 'Reading', question: 'Die Vögel bauen im Frühling ihre Nester in den Bäumen.', answer: 'bauen Nester', instruction: 'Natur' },
    { id: 'de2-r6', type: 'Reading', question: 'Ein kleiner Igel sucht im Herbst unter Blättern Futter.', answer: 'sucht Futter', instruction: 'Dyr' },
    { id: 'de2-r7', type: 'Reading', question: 'Eichhörnchen sammeln Nüsse für den langen Winter.', answer: 'sammeln Nüsse', instruction: 'Dyr' },
    { id: 'de2-r8', type: 'Reading', question: 'Die Bienen fliegen von Blume zu Blume und sammeln Pollen.', answer: 'sammeln Pollen', instruction: 'Insekter' },
    { id: 'de2-r9', type: 'Reading', question: 'Schmetterlinge haben bunte Flügel und sehen sehr schön aus.', answer: 'bunte Flügel', instruction: 'Insekter' },
    { id: 'de2-r10', type: 'Reading', question: 'Der große Elefant hat einen langen Rüssel und große Ohren.', answer: 'langen Rüssel', instruction: 'Zoo' },
    { id: 'de2-r11', type: 'Reading', question: 'Giraffen fressen Blätter von den höchsten Ästen der Bäume.', answer: 'höchsten Ästen', instruction: 'Zoo' },
    { id: 'de2-r12', type: 'Reading', question: 'Im Meer schwimmen viele verschiedene bunte Fische.', answer: 'verschiedene Fische', instruction: 'Natur' },
    { id: 'de2-r13', type: 'Reading', question: 'Delfine sind sehr kluge Tiere und springen aus dem Wasser.', answer: 'kluge Tiere', instruction: 'Havet' },
    { id: 'de2-r14', type: 'Reading', question: 'Pinguine watscheln lustig über das kalte Eis.', answer: 'watscheln lustig', instruction: 'Eis' },
    { id: 'de2-r15', type: 'Reading', question: 'Der Tiger schleicht leise durch den dichten Dschungel.', answer: 'leise durch Dschungel', instruction: 'Raubtiere' },
    { id: 'de2-r16', type: 'Reading', question: 'Bären halten im Winter einen sehr langen Winterschlaf.', answer: 'Winterschlaf', instruction: 'Natur' },
    { id: 'de2-r17', type: 'Reading', question: 'Hasen können sehr weit und sehr schnell springen.', answer: 'weit springen', instruction: 'Tiere' },
    { id: 'de2-r18', type: 'Reading', question: 'Das Schaf hat weiche Wolle, die uns warm hält.', answer: 'weiche Wolle', instruction: 'Bauernhof' },
    { id: 'de2-r19', type: 'Reading', question: 'Die Kuh gibt uns jeden Tag frische und gesunde Milch.', answer: 'gesunde Milch', instruction: 'Bauernhof' },
    { id: 'de2-r20', type: 'Reading', question: 'Hühner legen Eier, die wir zum Frühstück essen.', answer: 'legen Eier', instruction: 'Bauernhof' },
    { id: 'de2-r21', type: 'Reading', question: 'In der Bibliothek gibt es viele spannende Bücher zu leihen.', answer: 'spannende Bücher', instruction: 'Lesen' },
    { id: 'de2-r22', type: 'Reading', question: 'Ich lese gern Abenteuergeschichten über tapfere Ritter.', answer: 'Abenteuergeschichten', instruction: 'Lesen' },
    { id: 'de2-r23', type: 'Reading', question: 'Zähneputzen nach dem Essen hält die Zähne gesund.', answer: 'Zähne gesund', instruction: 'Hygiene' },
    { id: 'de2-r24', type: 'Reading', question: 'Händewaschen vor dem Essen schützt uns vor Krankheiten.', answer: 'Händewaschen', instruction: 'Hygiene' },
    { id: 'de2-r25', type: 'Reading', question: 'Frisches Obst und Gemüse enthalten viele Vitamine.', answer: 'viele Vitamine', instruction: 'Gesundheit' },
    { id: 'de2-r26', type: 'Reading', question: 'Viel Wasser trinken ist gut für unseren Körper.', answer: 'gut für Körper', instruction: 'Gesundheit' },
    { id: 'de2-r27', type: 'Reading', question: 'Sport im Freien macht viel Freude und hält uns fit.', answer: 'hält uns fit', instruction: 'Sport' },
    { id: 'de2-r28', type: 'Reading', question: 'Fahrradfahren mit Helm ist sicher für alle Kinder.', answer: 'mit Helm', instruction: 'Sicherheit' },
    { id: 'de2-r29', type: 'Reading', question: 'Über die Straße gehen wir nur bei grüner Ampel.', answer: 'grüner Ampel', instruction: 'Verkehr' },
    { id: 'de2-r30', type: 'Reading', question: 'Im Bus muss man sich gut festhalten beim Fahren.', answer: 'gut festhalten', instruction: 'Verkehr' },
    { id: 'de2-r31', type: 'Reading', question: 'Züge bringen uns schnell von einer Stadt zur nächsten.', answer: 'schnell von Stadt', instruction: 'Reisen' },
    { id: 'de2-r32', type: 'Reading', question: 'Flugzeuge fliegen hoch über den weißen Wolken.', answer: 'über den Wolken', instruction: 'Reisen' },
    { id: 'de2-r33', type: 'Reading', question: 'Schiffe fahren über das weite und tiefe Meer.', answer: 'tiefe Meer', instruction: 'Reisen' },
    { id: 'de2-r34', type: 'Reading', question: 'Im Sommer bauen wir große Sandburgen am Strand.', answer: 'Sandburgen', instruction: 'Urlaub' },
    { id: 'de2-r35', type: 'Reading', question: 'Im Winter fahren wir mit dem Schlitten den Berg ab.', answer: 'mit dem Schlitten', instruction: 'Winter' },
    { id: 'de2-r36', type: 'Reading', question: 'Herbstwind lässt die bunten Drachen hoch steigen.', answer: 'Drachen steigen', instruction: 'Herbst' },
    { id: 'de2-r37', type: 'Reading', question: 'Im Frühling wachsen die ersten Blumen im Garten.', answer: 'erste Blumen', instruction: 'Frühling' },
    { id: 'de2-r38', type: 'Reading', question: 'Geburtstagsfeiern mit Freunden machen immer Spaß.', answer: 'mit Freunden', instruction: 'Feiern' },
    { id: 'de2-r39', type: 'Reading', question: 'Es gibt viele Geschenke und einen großen Kuchen.', answer: 'großen Kuchen', instruction: 'Feiern' },
    { id: 'de2-r40', type: 'Reading', question: 'Wir singen gemeinsam ein schönes Geburtstagslied.', answer: 'Geburtstagslied', instruction: 'Feiern' },
    { id: 'de2-r41', type: 'Reading', question: 'Musik zu hören entspannt uns nach einem langen Tag.', answer: 'Musik entspannt', instruction: 'Hobby' },
    { id: 'de2-r42', type: 'Reading', question: 'Malen mit Wasserfarben macht die Welt bunter.', answer: 'Wasserfarben', instruction: 'Hobby' },
    { id: 'de2-r43', type: 'Reading', question: 'Bauen mit bunten Steinen fördert die Kreativität.', answer: 'Kreativität', instruction: 'Spielen' },
    { id: 'de2-r44', type: 'Reading', question: 'Verstecken spielen im ganzen Haus ist aufregend.', answer: 'Verstecken spielen', instruction: 'Spielen' },
    { id: 'de2-r45', type: 'Reading', question: 'Den Tisch decken hilft den Eltern bei der Arbeit.', answer: 'Tisch decken', instruction: 'Haushalt' },
    { id: 'de2-r46', type: 'Reading', question: 'Mein Zimmer aufräumen macht alles wieder ordentlich.', answer: 'wieder ordentlich', instruction: 'Haushalt' },
    { id: 'de2-r47', type: 'Reading', question: 'Pflanzen gießen ist wichtig damit sie nicht vertrocknen.', answer: 'Pflanzen gießen', instruction: 'Natur' },
    { id: 'de2-r48', type: 'Reading', question: 'Tiere füttern ist eine große Verantwortung für uns.', answer: 'Verantwortung', instruction: 'Dyr' },
    { id: 'de2-r49', type: 'Reading', question: 'Höflich sein bedeutet "Bitte" und "Danke" zu sagen.', answer: 'Bitte und Danke', instruction: 'Umgang' },
    { id: 'de2-r50', type: 'Reading', question: 'Anderen helfen macht uns selbst auch glücklich.', answer: 'selbst glücklich', instruction: 'Umgang' },
    { id: 'de2-r51', type: 'Reading', question: 'Zusammenhalt in der Familie ist das Wichtigste.', answer: 'Zusammenhalt', instruction: 'Familie' },
  ],
  3: [
    { id: 'de3-r1', type: 'Reading', question: 'In Deutschland gibt es viele alte und historische Schlösser.', answer: 'historische Schlösser', instruction: 'Landeskunde' },
    { id: 'de3-r2', type: 'Reading', question: 'Berlin ist die Hauptstadt von Deutschland und sehr groß.', answer: 'Berlin', instruction: 'Städte' },
    { id: 'de3-r3', type: 'Reading', question: 'Der Rhein ist einer der längsten Flüsse in ganz Europa.', answer: 'Der Rhein', instruction: 'Geografie' },
    { id: 'de3-r4', type: 'Reading', question: 'In den Alpen kann man im Winter wunderbar Ski fahren.', answer: 'In den Alpen', instruction: 'Natur' },
    { id: 'de3-r5', type: 'Reading', question: 'Die Nordsee und die Ostsee liegen im Norden von Deutschland.', answer: 'Nordsee und Ostsee', instruction: 'Geografie' },
    { id: 'de3-r6', type: 'Reading', question: 'München ist berühmt für seine Parks und das Oktoberfest.', answer: 'München', instruction: 'Städte' },
    { id: 'de3-r7', type: 'Reading', question: 'Hamburger sind eine Spezialität aus der Stadt Hamburg.', answer: 'Hamburg', instruction: 'Essen' },
    { id: 'de3-r8', type: 'Reading', question: 'Gutenberg erfand den Buchdruck vor vielen hundert Jahren.', answer: 'Buchdruck', instruction: 'Geschichte' },
    { id: 'de3-r9', type: 'Reading', question: 'Die Gebrüder Grimm sammelten viele bekannte Märchen.', answer: 'Gebrüder Grimm', instruction: 'Literatur' },
    { id: 'de3-r10', type: 'Reading', question: 'Rotkäppchen begegnet im dunklen Wald dem bösen Wolf.', answer: 'Rotkäppchen', instruction: 'Märchen' },
    { id: 'de3-r11', type: 'Reading', question: 'Hänsel und Gretel fanden ein Knusperhaus im tiefen Wald.', answer: 'Knusperhaus', instruction: 'Märchen' },
    { id: 'de3-r12', type: 'Reading', question: 'Schneewittchen wohnte bei den sieben kleinen Zwergen.', answer: 'sieben Zwergen', instruction: 'Märchen' },
    { id: 'de3-r13', type: 'Reading', question: 'Aschenputtel verlor ihren gläsernen Schuh auf der Treppe.', answer: 'gläsernen Schuh', instruction: 'Märchen' },
    { id: 'de3-r14', type: 'Reading', question: 'Die Bremer Stadtmusikanten wollten in Bremen Musik machen.', answer: 'Stadtmusikanten', instruction: 'Märchen' },
    { id: 'de3-r15', type: 'Reading', question: 'Im Sachunterricht lernen wir viel über die Natur und Tiere.', answer: 'Natur und Tiere', instruction: 'Schule' },
    { id: 'de3-r16', type: 'Reading', question: 'Der Wasserkreislauf erklärt wie Regen und Wolken entstehen.', answer: 'Wasserkreislauf', instruction: 'Wissenschaft' },
    { id: 'de3-r17', type: 'Reading', question: 'Pflanzen brauchen Licht, Wasser und Erde zum Wachsen.', answer: 'Licht und Wasser', instruction: 'Biologie' },
    { id: 'de3-r18', type: 'Reading', question: 'Die Photosynthese findet in den grünen Blättern statt.', answer: 'Photosynthese', instruction: 'Biologie' },
    { id: 'de3-r19', type: 'Reading', question: 'Insekten haben sechs Beine und oft zwei Paar Flügel.', answer: 'sechs Beine', instruction: 'Tiere' },
    { id: 'de3-r20', type: 'Reading', question: 'Säugetiere bringen lebende Junge zur Welt und säugen sie.', answer: 'Säugetiere', instruction: 'Tiere' },
    { id: 'de3-r21', type: 'Reading', question: 'Vögel haben Federn und legen Eier in ihre Nester.', answer: 'Federn und Eier', instruction: 'Tiere' },
    { id: 'de3-r22', type: 'Reading', question: 'Reptilien sind wechselwarme Tiere mit trockener Schuppenhaut.', answer: 'Schuppenhaut', instruction: 'Tiere' },
    { id: 'de3-r23', type: 'Reading', question: 'Amphibien wie Frösche leben im Wasser und an Land.', answer: 'Wasser und Land', instruction: 'Tiere' },
    { id: 'de3-r24', type: 'Reading', question: 'Wir recyceln Müll um die Umwelt und Natur zu schützen.', answer: 'Müll recyceln', instruction: 'Umwelt' },
    { id: 'de3-r25', type: 'Reading', question: 'Papier gehört in die blaue Tonne für Altpapier.', answer: 'blaue Tonne', instruction: 'Umwelt' },
    { id: 'de3-r26', type: 'Reading', question: 'In Deutschland wird viel Brot in verschiedenen Sorten gegessen.', answer: 'viel Brot', instruction: 'Kultur' },
    { id: 'de3-r27', type: 'Reading', question: 'Bretzeln sind ein typisch bayerisches Gebäck mit Salz.', answer: 'Bretzeln', instruction: 'Essen' },
    { id: 'de3-r28', type: 'Reading', question: 'Fußball ist der beliebteste Sport bei vielen Kindern.', answer: 'Fußball', instruction: 'Sport' },
    { id: 'de3-r29', type: 'Reading', question: 'Die Nationalmannschaft hat schon oft Titel gewonnen.', answer: 'Nationalmannschaft', instruction: 'Sport' },
    { id: 'de3-r30', type: 'Reading', question: 'Im Sommer gehen viele Menschen gern ins Freibad schwimmen.', answer: 'Freibad', instruction: 'Freizeit' },
    { id: 'de3-r31', type: 'Reading', question: 'Zum Frühstück essen Deutsche oft Brötchen mit Marmelade.', answer: 'Brötchen', instruction: 'Frühstück' },
    { id: 'de3-r32', type: 'Reading', question: 'Mittagessen ist meistens die warme Hauptmahlzeit am Tag.', answer: 'Hauptmahlzeit', instruction: 'Essen' },
    { id: 'de3-r33', type: 'Reading', question: 'Abendbrot besteht oft aus Brot, Käse und Wurst.', answer: 'Abendbrot', instruction: 'Essen' },
    { id: 'de3-r34', type: 'Reading', question: 'Der Nikolaus bringt kleinen Kindern am 6. Dezember Süßes.', answer: 'Nikolaus', instruction: 'Feste' },
    { id: 'de3-r35', type: 'Reading', question: 'Zu Weihnachten steht ein geschmückter Tannenbaum im Zimmer.', answer: 'Tannenbaum', instruction: 'Feste' },
    { id: 'de3-r36', type: 'Reading', question: 'Ostern suchen Kinder bunte Eier im Garten oder Haus.', answer: 'bunte Eier', instruction: 'Feste' },
    { id: 'de3-r37', type: 'Reading', question: 'Karneval verkleiden sich die Menschen mit bunten Kostümen.', answer: 'Kostümen', instruction: 'Feste' },
    { id: 'de3-r38', type: 'Reading', question: 'Sankt Martin reitet auf einem Pferd durch die Stadt.', answer: 'Sankt Martin', instruction: 'Feste' },
    { id: 'de3-r39', type: 'Reading', question: 'Laternenumzüge leuchten hell in der dunklen Nacht.', answer: 'Laternenumzüge', instruction: 'Tradition' },
    { id: 'de3-r40', type: 'Reading', question: 'Die Landeshauptstadt von Bayern ist die Stadt München.', answer: 'München', instruction: 'Länder' },
    { id: 'de3-r41', type: 'Reading', question: 'Stuttgart liegt im Bundesland Baden-Württemberg im Süden.', answer: 'Stuttgart', instruction: 'Länder' },
    { id: 'de3-r42', type: 'Reading', question: 'In Dresden kann man die berühmte Frauenkirche sehen.', answer: 'Frauenkirche', instruction: 'Architektur' },
    { id: 'de3-r43', type: 'Reading', question: 'Der Kölner Dom ist eine sehr große und alte Kirche.', answer: 'Kölner Dom', instruction: 'Architektur' },
    { id: 'de3-r44', type: 'Reading', question: 'Schloss Neuschwanstein sieht aus wie ein Märchenschloss.', answer: 'Neuschwanstein', instruction: 'Burgen' },
    { id: 'de3-r45', type: 'Reading', question: 'Museen zeigen uns viele interessante Dinge aus der Vergangenheit.', answer: 'Interessante Dinge', instruction: 'Kultur' },
    { id: 'de3-r46', type: 'Reading', question: 'Über das Internet können wir Informationen schnell finden.', answer: 'Informationen finden', instruction: 'Technik' },
    { id: 'de3-r47', type: 'Reading', question: 'Computer helfen uns bei den Hausaufgaben und beim Lernen.', answer: 'Computer helfen', instruction: 'Schule' },
    { id: 'de3-r48', type: 'Reading', question: 'Handys nutzen wir um mit Freunden zu kommunizieren.', answer: 'Handys nutzen', instruction: 'Technik' },
    { id: 'de3-r49', type: 'Reading', question: 'Fernsehen schauen wir meistens zur Entspannung am Abend.', answer: 'Fernsehen schauen', instruction: 'Medien' },
    { id: 'de3-r50', type: 'Reading', question: 'Radio hören wir oft beim Autofahren oder beim Frühstück.', answer: 'Radio hören', instruction: 'Medien' },
    { id: 'de3-r51', type: 'Reading', question: 'Zeitschriften enthalten viele Bilder und kurze Artikel.', answer: 'Zeitschriften', instruction: 'Lesen' },
  ],
  4: [
    { id: 'de4-r1', type: 'Reading', question: 'Die Demokratie ist eine Staatsform, in der das Volk regiert.', answer: 'Volk regiert', instruction: 'Politik' },
    { id: 'de4-r2', type: 'Reading', question: 'Der Bundestag ist das Parlament von Deutschland in Berlin.', answer: 'Parlament', instruction: 'Politik' },
    { id: 'de4-r3', type: 'Reading', question: 'Gesetze regeln das Zusammenleben der Menschen im Land.', answer: 'Zusammenleben', instruction: 'Recht' },
    { id: 'de4-r4', type: 'Reading', question: 'In der Grundschulzeit lernen wir die Basis für das Leben.', answer: 'Basis für Leben', instruction: 'Schule' },
    { id: 'de4-r5', type: 'Reading', question: 'Nach der vierten Klasse wechseln viele Kinder die Schule.', answer: 'vierte Klasse', instruction: 'Schule' },
    { id: 'de4-r6', type: 'Reading', question: 'Es gibt Gymnasien, Realschulen und auch Hauptschulen.', answer: 'Gymnasien', instruction: 'Bildung' },
    { id: 'de4-r7', type: 'Reading', question: 'Mathematik hilft uns, komplexe Probleme logisch zu lösen.', answer: 'logisch lösen', instruction: 'Mathe' },
    { id: 'de4-r8', type: 'Reading', question: 'Im Deutschunterricht analysieren wir Texte und Gedichte.', answer: 'analysieren Texte', instruction: 'Sprache' },
    { id: 'de4-r9', type: 'Reading', question: 'Englisch ist eine Weltsprache, die viele Menschen lernen.', answer: 'Weltsprache', instruction: 'Sprachen' },
    { id: 'de4-r10', type: 'Reading', question: 'Sportunterricht fördert die Fitness und den Teamgeist.', answer: 'Teamgeist', instruction: 'Sport' },
    { id: 'de4-r11', type: 'Reading', question: 'Im Kunstunterricht drücken wir unsere Gefühle kreativ aus.', answer: 'kreativ aus', instruction: 'Kunst' },
    { id: 'de4-r12', type: 'Reading', question: 'Musikunterricht bringt uns die Welt der Töne näher.', answer: 'Welt der Töne', instruction: 'Musik' },
    { id: 'de4-r13', type: 'Reading', question: 'Geschichte lehrt uns aus den Fehlern der Vergangenheit.', answer: 'Fehlern lernen', instruction: 'Historie' },
    { id: 'de4-r14', type: 'Reading', question: 'Erdkunde zeigt uns die verschiedenen Länder der Erde.', answer: 'Länder der Erde', instruction: 'Geografie' },
    { id: 'de4-r15', type: 'Reading', question: 'Europa ist ein Kontinent mit vielen verschiedenen Kulturen.', answer: 'viele Kulturen', instruction: 'Welt' },
    { id: 'de4-r16', type: 'Reading', question: 'Die Europäische Union verbindet viele Länder miteinander.', answer: 'Länder verbinden', instruction: 'Politik' },
    { id: 'de4-r17', type: 'Reading', question: 'Asien ist der größte und bevölkerungsreichste Kontinent.', answer: 'größte Kontinent', instruction: 'Welt' },
    { id: 'de4-r18', type: 'Reading', question: 'Afrika beeindruckt durch seine vielfältige Tierwelt.', answer: 'Tierwelt', instruction: 'Natur' },
    { id: 'de4-r19', type: 'Reading', question: 'Amerika teilt sich in Nordamerika und Südamerika auf.', answer: 'Nord und Süd', instruction: 'Geografie' },
    { id: 'de4-r20', type: 'Reading', question: 'Australien ist ein Land und ein ganzer Kontinent zugleich.', answer: 'Land und Kontinent', instruction: 'Geografie' },
    { id: 'de4-r21', type: 'Reading', question: 'Die Antarktis ist fast vollständig mit dickem Eis bedeckt.', answer: 'dickem Eis', instruction: 'Natur' },
    { id: 'de4-r22', type: 'Reading', question: 'Der Klimawandel stellt eine große Gefahr für uns alle dar.', answer: 'große Gefahr', instruction: 'Umwelt' },
    { id: 'de4-r23', type: 'Reading', question: 'Energiesparen hilft dabei, unsere Ressourcen zu schonen.', answer: 'Ressourcen schonen', instruction: 'Umwelt' },
    { id: 'de4-r24', type: 'Reading', question: 'Nachhaltigkeit bedeutet, an die Zukunft zu denken.', answer: 'Zukunft denken', instruction: 'Ideen' },
    { id: 'de4-r25', type: 'Reading', question: 'Plastikmüll in den Ozeanen schadet vielen Wassertieren.', answer: 'Plastikmüll', instruction: 'Umwelt' },
    { id: 'de4-r26', type: 'Reading', question: 'Regenwälder werden oft für die Landwirtschaft abgeholzt.', answer: 'abgeholzt', instruction: 'Umwelt' },
    { id: 'de4-r27', type: 'Reading', question: 'Die Sonnenenergie ist eine saubere Quelle für Strom.', answer: 'saubere Quelle', instruction: 'Energie' },
    { id: 'de4-r28', type: 'Reading', question: 'Windräder nutzen die Kraft des Windes zur Erzeugung.', answer: 'Kraft des Windes', instruction: 'Energie' },
    { id: 'de4-r29', type: 'Reading', question: 'Wasserkraftwerke nutzen fließendes Wasser für Energie.', answer: 'fließendes Wasser', instruction: 'Energie' },
    { id: 'de4-r30', type: 'Reading', question: 'Elektroautos stoßen beim Fahren keine Abgase direkt aus.', answer: 'keine Abgase', instruction: 'Verkehr' },
    { id: 'de4-r31', type: 'Reading', question: 'Zu Fuß gehen oder Radfahren ist gesund für Mensch und Natur.', answer: 'Mensch und Natur', instruction: 'Gesundheit' },
    { id: 'de4-r32', type: 'Reading', question: 'Eine gesunde Ernährung beugt vielen Krankheiten vor.', answer: 'vielen Krankheiten', instruction: 'Gesundheit' },
    { id: 'de4-r33', type: 'Reading', question: 'Vitamine finden wir vor allem in frischem Obst und Gemüse.', answer: 'frischem Obst', instruction: 'Ernährung' },
    { id: 'de4-r34', type: 'Reading', question: 'Kohlenhydrate liefern die nötige Energie für den Sport.', answer: 'nötige Energie', instruction: 'Biologie' },
    { id: 'de4-r35', type: 'Reading', question: 'Eiweiß ist wichtig für den Aufbau unserer Muskeln.', answer: 'Aufbau Muskeln', instruction: 'Biologie' },
    { id: 'de4-r36', type: 'Reading', question: 'Fette sind Reserven, die unser Körper für Notfälle speichert.', answer: 'Reserven speichern', instruction: 'Biologie' },
    { id: 'de4-r37', type: 'Reading', question: 'Hautschutz bei starker Sonne verhindert Sonnenbrand.', answer: 'Sonnenbrand', instruction: 'Gesundheit' },
    { id: 'de4-r38', type: 'Reading', question: 'Regelmäßiger Schlaf regeneriert unseren Körper über Nacht.', answer: 'regeneriert Körper', instruction: 'Biologie' },
    { id: 'de4-r39', type: 'Reading', question: 'Drogen und Alkohol schädigen die Gesundheit massiv.', answer: 'Gesundheit schädigen', instruction: 'Sucht' },
    { id: 'de4-r40', type: 'Reading', question: 'Rauchen verdeckt die Lungen und verursacht oft Krebs.', answer: 'verursacht Krebs', instruction: 'Sucht' },
    { id: 'de4-r41', type: 'Reading', question: 'Freundschaften geben uns Halt in schwierigen Zeiten.', answer: 'Halt geben', instruction: 'Soziales' },
    { id: 'de4-r42', type: 'Reading', question: 'Streit schlichten erfordert Geduld und Verständnis.', answer: 'Geduld zeigen', instruction: 'Soziales' },
    { id: 'de4-r43', type: 'Reading', question: 'Hilfsbereitschaft macht das Zusammenleben angenehmer.', answer: 'angenehmer', instruction: 'Umgang' },
    { id: 'de4-r44', type: 'Reading', question: 'Respekt vor anderen ist die Basis jeder Kommunikation.', answer: 'Basis jeder', instruction: 'Umgang' },
    { id: 'de4-r45', type: 'Reading', question: 'Ehrlichkeit baut Vertrauen zwischen den Menschen auf.', answer: 'baut Vertrauen', instruction: 'Umgang' },
    { id: 'de4-r46', type: 'Reading', question: 'Hobbys helfen uns, vom stressigen Alltag abzuschalten.', answer: 'Alltag abschalten', instruction: 'Freizeit' },
    { id: 'de4-r47', type: 'Reading', question: 'Lesen erweitert unseren Horizont und fördert Fantasie.', answer: 'Format Fantasie', instruction: 'Hobby' },
    { id: 'de4-r48', type: 'Reading', question: 'Singen verbessert die Laune und stärkt die Stimme.', answer: 'verbessert Laune', instruction: 'Hobby' },
    { id: 'de4-r49', type: 'Reading', question: 'Tanzen ist eine tolle Art der körperlichen Bewegung.', answer: 'körperliche Bewegung', instruction: 'Hobby' },
    { id: 'de4-r50', type: 'Reading', question: 'Reisen ermöglicht uns, neue Perspektiven zu gewinnen.', answer: 'neue Perspektiven', instruction: 'Hobby' },
    { id: 'de4-r51', type: 'Reading', question: 'Die Welt zu entdecken ist ein Abenteuer fürs ganze Leben.', answer: 'Leben lang', instruction: 'Hobby' },
  ],
  5: [
    { id: 'de5-r1', type: 'Reading', question: 'Das Sonnensystem hat acht Planeten, die die Sonne umkreisen.', answer: 'acht Planeten', instruction: 'Weltraum' },
    { id: 'de5-r2', type: 'Reading', question: 'Die Erde ist der einzige bekannte Planet mit flüssigem Wasser.', answer: 'flüssiges Wasser', instruction: 'Astronomie' },
    { id: 'de5-r3', type: 'Reading', question: 'Der Mars wird oft als der Rote Planet bezeichnet.', answer: 'Rote Planet', instruction: 'Weltraum' },
    { id: 'de5-r4', type: 'Reading', question: 'Jupiter ist der größte Planet in unserem gesamten System.', answer: 'größte Planet', instruction: 'Weltraum' },
    { id: 'de5-r5', type: 'Reading', question: 'Sterne sind riesige Kugeln aus brennendem, heißem Gas.', answer: 'brennendem Gas', instruction: 'Astronomie' },
    { id: 'de5-r6', type: 'Reading', question: 'Die Milchstraße ist die Galaxie, in der wir zu Hause sind.', answer: 'unsere Galaxie', instruction: 'Weltraum' },
    { id: 'de5-r7', type: 'Reading', question: 'Schwarze Löcher haben eine extrem starke Anziehungskraft.', answer: 'Anziehungskraft', instruction: 'Physik' },
    { id: 'de5-r8', type: 'Reading', question: 'Lichtjahre messen die enormen Distanzen im Universum.', answer: 'Distanzen messen', instruction: 'Wissenschaft' },
    { id: 'de5-r9', type: 'Reading', question: 'Astronauten reisen in den Weltraum um ihn zu erforschen.', answer: 'Weltraum erforschen', instruction: 'Berufe' },
    { id: 'de5-r10', type: 'Reading', question: 'Teleskope erlauben uns weit entfernte Galaxien zu sehen.', answer: 'Galaxien sehen', instruction: 'Technik' },
    { id: 'de5-r11', type: 'Reading', question: 'Die Atmosphäre schützt die Erde vor gefährlicher Strahlung.', answer: 'schützt Erde', instruction: 'Wissenschaft' },
    { id: 'de5-r12', type: 'Reading', question: 'Sauerstoff ist lebensnotwendig für fast alles Leben.', answer: 'lebensnotwendig', instruction: 'Biologie' },
    { id: 'de5-r13', type: 'Reading', question: 'Vulkane schleudern heiße Lava und Asche in die Luft.', answer: 'heiße Lava', instruction: 'Vulkane' },
    { id: 'de5-r14', type: 'Reading', question: 'Erdbeben entstehen durch Bewegungen der Erdplatten.', answer: 'Erdplatten', instruction: 'Geografie' },
    { id: 'de5-r15', type: 'Reading', question: 'Tsunamis sind riesige Wellen, die durch Beben entstehen.', answer: 'riesige Wellen', instruction: 'Gefahren' },
    { id: 'de5-r16', type: 'Reading', question: 'Das Wetter wird durch Temperatur und Luftdruck bestimmt.', answer: 'Luftdruck', instruction: 'Meteorologie' },
    { id: 'de5-r17', type: 'Reading', question: 'Wirbelstürme erreichen extrem hohe Geschwindigkeiten.', answer: 'hohe Geschwindigkeiten', instruction: 'Wetter' },
    { id: 'de5-r18', type: 'Reading', question: 'Dürreperioden führen oft zu Wassermangel in Regionen.', answer: 'Wassermangel', instruction: 'Natur' },
    { id: 'de5-r19', type: 'Reading', question: 'Überschwemmungen können ganze Dörfer und Städte fluten.', answer: 'Städte fluten', instruction: 'Gefahren' },
    { id: 'de5-r20', type: 'Reading', question: 'Die Ozonschicht filtert ultraviolette Strahlen der Sonne.', answer: 'filtriert Strahlen', instruction: 'Umwelt' },
    { id: 'de5-r21', type: 'Reading', question: 'Treibhausgase tragen zur Erwärmung der Erde bei.', answer: 'Erwärmung Erde', instruction: 'Klima' },
    { id: 'de5-r22', type: 'Reading', question: 'Der Nordpol liegt inmitten des Arktischen Ozeans.', answer: 'Nordpol', instruction: 'Erde' },
    { id: 'de5-r23', type: 'Reading', question: 'Der Südpol befindet sich auf dem Kontinent Antarktis.', answer: 'Südpol', instruction: 'Erde' },
    { id: 'de5-r24', type: 'Reading', question: 'Der Äquator teilt die Erde in Nord und Süd auf.', answer: 'Äquator', instruction: 'Geografie' },
    { id: 'de5-r25', type: 'Reading', question: 'Längengrade verlaufen von Pol zu Pol über die Erde.', answer: 'von Pol zu Pol', instruction: 'Karte' },
    { id: 'de5-r26', type: 'Reading', question: 'Breitengrade verlaufen parallel zum Äquator um Erde.', answer: 'parallel Äquator', instruction: 'Karte' },
    { id: 'de5-r27', type: 'Reading', question: 'Ozeane bedecken mehr als siebzig Prozent der Erdoberfläche.', answer: 'siebzig Prozent', instruction: 'Geografie' },
    { id: 'de5-r28', type: 'Reading', question: 'Der Mariannengraben ist die tiefste Stelle aller Meere.', answer: 'tiefste Stelle', instruction: 'Ozean' },
    { id: 'de5-r29', type: 'Reading', question: 'Korallenriffe sind komplexe und bunte Lebensräume im Meer.', answer: 'Korallenriffe', instruction: 'Ozean' },
    { id: 'de5-r30', type: 'Reading', question: 'Wale singen um über weite Strecken zu kommunizieren.', answer: 'Wale singen', instruction: 'Tiere' },
    { id: 'de5-r31', type: 'Reading', question: 'Haie regeln das Gleichgewicht der marinen Ökosysteme.', answer: 'Gleichgewicht', instruction: 'Tiere' },
    { id: 'de5-r32', type: 'Reading', question: 'Plankton ist die Nahrungsgrundlage für viele Lebewesen.', answer: 'Nahrungsgrundlage', instruction: 'Meeresbiologie' },
    { id: 'de5-r33', type: 'Reading', question: 'Mikroplastik ist ein unsichtbares Problem in Ozeanen.', answer: 'unsichtbares Problem', instruction: 'Ökologie' },
    { id: 'de5-r34', type: 'Reading', question: 'Überfischung bedroht viele Fischbestände weltweit.', answer: 'bedroht Fisch', instruction: 'Ökologie' },
    { id: 'de5-r35', type: 'Reading', question: 'Der Schutz der Meere ist eine globale Verpflichtung.', answer: 'Schutz der Meere', instruction: 'Politik' },
    { id: 'de5-r36', type: 'Reading', question: 'Nationalparks bewahren unberührte Natur für die Zukunft.', answer: 'unberührte Natur', instruction: 'Natur' },
    { id: 'de5-r37', type: 'Reading', question: 'Wanderwege laden ein die Bergwelt sicher zu erkunden.', answer: 'Bergwelt erkunden', instruction: 'Freizeit' },
    { id: 'de5-r38', type: 'Reading', question: 'Klettern in den Bergen erfordert Kraft und Konzentration.', answer: 'Kraft und Fokus', instruction: 'Alpin' },
    { id: 'de5-r39', type: 'Reading', question: 'Hütten bieten Schutz bei plötzlichem Wetterumschwung.', answer: 'Schutz bieten', instruction: 'Regeln' },
    { id: 'de5-r40', type: 'Reading', question: 'Alpine Gefahren wie Lawinen müssen beachtet werden.', answer: 'Lawinen', instruction: 'Sicherheit' },
    { id: 'de5-r41', type: 'Reading', question: 'Der Tourismus ist wichtig für die Wirtschaft der Region.', answer: 'Wirtschaft', instruction: 'Ökonomie' },
    { id: 'de5-r42', type: 'Reading', question: 'Massenmedien beeinflussen unsere Sicht auf die Welt.', answer: 'beeinflussen Sicht', instruction: 'Medien' },
    { id: 'de5-r43', type: 'Reading', question: 'Werbung versucht uns Produkte schmackhaft zu machen.', answer: 'Produkte kaufen', instruction: 'Marketing' },
    { id: 'de5-r44', type: 'Reading', question: 'Soziale Netzwerke können süchtig und einsam machen.', answer: 'süchtig machen', instruction: 'Psychologie' },
    { id: 'de5-r45', type: 'Reading', question: 'Cybermobbing ist ein großes Problem unter Jugendlichen.', answer: 'Cybermobbing', instruction: 'IT-Sicherheit' },
    { id: 'de5-r46', type: 'Reading', question: 'Datenschutz ist wichtig um unsere Privatsphäre zu bewahren.', answer: 'Privatsphäre', instruction: 'Recht' },
    { id: 'de5-r47', type: 'Reading', question: 'Passwörter sollten sicher und für andere geheim sein.', answer: 'Passwörter', instruction: 'Hausregeln' },
    { id: 'de5-r48', type: 'Reading', question: 'Künstliche Intelligenz kann Texte und Bilder generieren.', answer: 'KI kann das', instruction: 'Technik' },
    { id: 'de5-r49', type: 'Reading', question: 'Robotik kommt in der Industrie oft zum Einsatz heute.', answer: 'Robotik', instruction: 'Technik' },
    { id: 'de5-r50', type: 'Reading', question: 'Digitalisierung verändert fast alle Bereiche des Lebens.', answer: 'verändert Leben', instruction: 'Wandel' },
    { id: 'de5-r51', type: 'Reading', question: 'Fortschritt sollte immer dem Wohl der Menschen dienen.', answer: 'Wohl von allen', instruction: 'Ethik' },
  ],
  6: [
    { id: 'de6-r1', type: 'Reading', question: 'Migration ist ein globales Phänomen mit vielen Ursachen.', answer: 'vielen Ursachen', instruction: 'Soziologie' },
    { id: 'de6-r2', type: 'Reading', question: 'Menschen verlassen ihre Heimat oft wegen Kriegen oder Not.', answer: 'Heimat verlassen', instruction: 'Politik' },
    { id: 'de6-r3', type: 'Reading', question: 'Integration bedeutet das Einleben in eine neue Gesellschaft.', answer: 'neue Gesellschaft', instruction: 'Soziales' },
    { id: 'de6-r4', type: 'Reading', question: 'Vielfalt bereichert das kulturelle Leben in einer Stadt.', answer: 'Vielfalt bereichert', instruction: 'Kultur' },
    { id: 'de6-r5', type: 'Reading', question: 'Toleranz gegenüber anderen Religionen ist sehr wichtig.', answer: 'Toleranz gegenüber', instruction: 'Religionen' },
    { id: 'de6-r6', type: 'Reading', question: 'Religionsfreiheit ist ein grundlegendes Menschenrecht.', answer: 'Menschenrecht', instruction: 'Recht' },
    { id: 'de6-r7', type: 'Reading', question: 'Demokratische Werte müssen jeden Tag neu gelebt werden.', answer: 'Werte leben', instruction: 'Politik' },
    { id: 'de6-r8', type: 'Reading', question: 'Wahlen sind das Herzstück einer jeden freien Demokratie.', answer: 'Wahlen', instruction: 'Politik' },
    { id: 'de6-r9', type: 'Reading', question: 'Opposition kontrolliert die Arbeit der aktuellen Regierung.', answer: 'Regierung', instruction: 'Politik' },
    { id: 'de6-r10', type: 'Reading', question: 'Gewaltenteilung verhindert die Konzentration von Macht.', answer: 'Macht', instruction: 'Politik' },
    { id: 'de6-r11', type: 'Reading', question: 'Globalisierung führt zu einer weltweiten Vernetzung.', answer: 'Vernetzung', instruction: 'Wirtschaft' },
    { id: 'de6-r12', type: 'Reading', question: 'Handelsabkommen regeln den Austausch von Waren heute.', answer: 'Austausch Waren', instruction: 'Wirtschaft' },
    { id: 'de6-r13', type: 'Reading', question: 'Lieferketten sind oft sehr komplex und über Kontinente.', answer: 'sehr komplex', instruction: 'Wirtschaft' },
    { id: 'de6-r14', type: 'Reading', question: 'Zölle können den Import von Produkten teurer machen.', answer: 'Import teurer', instruction: 'Wirtschaft' },
    { id: 'de6-r15', type: 'Reading', question: 'Inflation führt zu einem allgemeinen Preisanstieg im Land.', answer: 'Preisanstieg', instruction: 'Wirtschaft' },
    { id: 'de6-r16', type: 'Reading', question: 'Steuern finanzieren wichtige staatliche Aufgaben für alle.', answer: 'staatliche Aufgaben', instruction: 'Wirtschaft' },
    { id: 'de6-r17', type: 'Reading', question: 'Subventionen unterstützen bestimmte Branchen finanziell.', answer: 'Branchen', instruction: 'Wirtschaft' },
    { id: 'de6-r18', type: 'Reading', question: 'Innovationen sichern die Wettbewerbsfähigkeit von Firmen.', answer: 'Wettbewerb', instruction: 'Business' },
    { id: 'de6-r19', type: 'Reading', question: 'Unternehmergeist treibt den wirtschaftlichen Fortschritt.', answer: 'Fortschritt', instruction: 'Business' },
    { id: 'de6-r20', type: 'Reading', question: 'Industrie 4.0 bezeichnet die vierte industrielle Phase.', answer: 'vierte Phase', instruction: 'Technik' },
    { id: 'de6-r21', type: 'Reading', question: 'Automatisierung ersetzt oft monotone menschliche Arbeit.', answer: 'menschliche Arbeit', instruction: 'Technik' },
    { id: 'de6-r22', type: 'Reading', question: 'Fachkräftemangel stellt eine Hürde für das Wachstum dar.', answer: 'Hürde Wachstum', instruction: 'Wirtschaft' },
    { id: 'de6-r23', type: 'Reading', question: 'Fortbildung ist wichtig in einer sich wandelnden Welt.', answer: 'wandelnden Welt', instruction: 'Bildung' },
    { id: 'de6-r24', type: 'Reading', question: 'Lebenslanges Lernen ist heute eine Notwendigkeit im Job.', answer: 'Notwendigkeit', instruction: 'Bildung' },
    { id: 'de6-r25', type: 'Reading', question: 'Soft Skills sind im Berufsleben genauso wichtig wie Fach.', answer: 'Soft Skills', instruction: 'Karriere' },
    { id: 'de6-r26', type: 'Reading', question: 'Empathie fördert ein gutes Klima in jedem Arbeitsteam.', answer: 'gutes Klima', instruction: 'Karriere' },
    { id: 'de6-r27', type: 'Reading', question: 'Kommunikationsfähigkeit ist der Schlüssel zum Erfolg hier.', answer: 'Erfolg', instruction: 'Karriere' },
    { id: 'de6-r28', type: 'Reading', question: 'Konfliktmanagement hilft Probleme sachlich zu lösen.', answer: 'sachlich lösen', instruction: 'Karriere' },
    { id: 'de6-r29', type: 'Reading', question: 'Work-Life-Balance ist essenziell für die Gesundheit.', answer: 'Gesundheit', instruction: 'Lifestyle' },
    { id: 'de6-r30', type: 'Reading', question: 'Stressbewältigung beugt einem Burnout effektiv vor.', answer: 'Burnout vor', instruction: 'Psychologie' },
    { id: 'de6-r31', type: 'Reading', question: 'Ehrenamtliches Engagement stärkt den sozialen Kitt.', answer: 'sozialen Kitt', instruction: 'Gesellschaft' },
    { id: 'de6-r32', type: 'Reading', question: 'Zivilcourage bedeutet für die eigenen Werte einzustehen.', answer: 'Werte einstehen', instruction: 'Ethik' },
    { id: 'de6-r33', type: 'Reading', question: 'Umweltschutz beginnt im Kleinen bei jedem Einzelnen.', answer: 'jedem Einzelnen', instruction: 'Umwelt' },
    { id: 'de6-r34', type: 'Reading', question: 'Müllvermeidung schont die Knappen Ressourcen der Erde.', answer: 'Ressourcen', instruction: 'Umwelt' },
    { id: 'de6-r35', type: 'Reading', question: 'Bio-Produkte werden meist ohne Pestizide angebaut.', answer: 'Bio-Produkte', instruction: 'Essen' },
    { id: 'de6-r36', type: 'Reading', question: 'Regionale Lebensmittel reduzieren lange Transportwege.', answer: 'Transportwege', instruction: 'Ökologie' },
    { id: 'de6-r37', type: 'Reading', question: 'Saisonale Ernährung ist im Einklang mit der Natur.', answer: 'Einklang Natur', instruction: 'Ökologie' },
    { id: 'de6-r38', type: 'Reading', question: 'Veganismus verzichtet ganz auf tierische Produkte hier.', answer: 'tierische Produkte', instruction: 'Ernährung' },
    { id: 'de6-r39', type: 'Reading', question: 'Vegetarier essen Fleisch nicht, aber oft Eier und Käse.', answer: 'Fleisch nicht', instruction: 'Ernährung' },
    { id: 'de6-r40', type: 'Reading', question: 'Gesunde Ernährung braucht Zeit für Vorbereitung und Genuss.', answer: 'Vorbereitung', instruction: 'Lifestyle' },
    { id: 'de6-r41', type: 'Reading', question: 'Slow Food setzt auf Qualität statt auf Schnelligkeit.', answer: 'Qualität', instruction: 'Kultur' },
    { id: 'de6-r42', type: 'Reading', question: 'Fairer Handel garantiert gerechte Löhne für Bauern da.', answer: 'gerechte Löhne', instruction: 'Wirtschaft' },
    { id: 'de6-r43', type: 'Reading', question: 'Ethik im Handel wird für viele Käufer immer wichtiger.', answer: 'wichtiger', instruction: 'Wirtschaft' },
    { id: 'de6-r44', type: 'Reading', question: 'Nachhaltiges Investment fördert Umweltprojekte weltweit.', answer: 'Umweltprojekte', instruction: 'Finanzen' },
    { id: 'de6-r45', type: 'Reading', question: 'Minimalismus befreit von unnötigem materiellen Ballast.', answer: 'Ballast free', instruction: 'Lifestyle' },
    { id: 'de6-r46', type: 'Reading', question: 'Upcycling macht aus alten Dingen etwas völlig Neues.', answer: 'völlig Neues', instruction: 'Hobby' },
    { id: 'de6-r47', type: 'Reading', question: 'Second-Hand-Kleidung ist eine ökologische Alternative.', answer: 'ökologische', instruction: 'Lifestyle' },
    { id: 'de6-r48', type: 'Reading', question: 'Leitungswasser zu trinken spart viel Plastik und Geld.', answer: 'Plastik Müll', instruction: 'Tipp' },
    { id: 'de6-r49', type: 'Reading', question: 'Fahrradfahren in der Stadt ist oft schneller als Stau.', answer: 'schneller Stau', instruction: 'Verkehr' },
    { id: 'de6-r50', type: 'Reading', question: 'Bahnreisen schont das Klima mehr als Fliegen es tut.', answer: 'Klima schont', instruction: 'Reisen' },
    { id: 'de6-r51', type: 'Reading', question: 'Zukunft gestalten heißt heute die Weichen richtig stellen.', answer: 'Weichen stellen', instruction: 'Motivation' },
  ],
  7: [
    { id: 'de7-r1', type: 'Reading', question: 'Die Französische Revolution markiert das Ende einer Ära.', answer: 'Ende Ära', instruction: 'Geschichte' },
    { id: 'de7-r2', type: 'Reading', question: 'Napoleon Bonaparte krönte sich selbst zum Kaiser hier.', answer: 'Kaiser', instruction: 'Geschichte' },
    { id: 'de7-r3', type: 'Reading', question: 'Der Erste Weltkrieg dauerte von neunzehnhundertvierzehn an.', answer: 'neunzehnhundertv.', instruction: 'Geschichte' },
    { id: 'de7-r4', type: 'Reading', question: 'Der Versailler Vertrag beendete diesen großen Krieg dann.', answer: 'Versailler Vertrag', instruction: 'Geschichte' },
    { id: 'de7-r5', type: 'Reading', question: 'Die Weimarer Republik war die erste deutsche Demokratie.', answer: 'erste Demokratie', instruction: 'Geschichte' },
    { id: 'de7-r6', type: 'Reading', question: 'Die Weltwirtschaftskrise neunzehnhundertneunundzwanzig traf hart.', answer: 'traf hart', instruction: 'Geschichte' },
    { id: 'de7-r7', type: 'Reading', question: 'Nationalsozialismus führte in die Katastrophe des Krieges.', answer: 'Katastrophe', instruction: 'Geschichte' },
    { id: 'de7-r8', type: 'Reading', question: 'Nach dem Zweiten Weltkrieg wurde Deutschland geteilt.', answer: 'geteilt', instruction: 'Geschichte' },
    { id: 'de7-r9', type: 'Reading', question: 'Der Bau der Berliner Mauer trennte Ost und West Berlin.', answer: 'trennter Ost/West', instruction: 'Geschichte' },
    { id: 'de7-r10', type: 'Reading', question: 'Die Wiedervereinigung geschah neunzehnhundertneunzig endlich.', answer: 'neunzig', instruction: 'Geschichte' },
    { id: 'de7-r11', type: 'Reading', question: 'Johann Wolfgang von Goethe war ein berühmter Dichter.', answer: 'Goethe', instruction: 'Literatur' },
    { id: 'de7-r12', type: 'Reading', question: 'Friedrich Schiller schrieb das Drama Die Räuber damals.', answer: 'Die Räuber', instruction: 'Literatur' },
    { id: 'de7-r13', type: 'Reading', question: 'Sturm und Drang war eine junge literarische Epoche.', answer: 'Sturm und Drang', instruction: 'Literatur' },
    { id: 'de7-r14', type: 'Reading', question: 'Die Epoche der Romantik betonte Gefühle und Sehnsucht.', answer: 'Romantik', instruction: 'Literatur' },
    { id: 'de7-r15', type: 'Reading', question: 'Realismus beschreibt die Wirklichkeit so wie sie eben ist.', answer: 'Realismus', instruction: 'Literatur' },
    { id: 'de7-r16', type: 'Reading', question: 'Naturalismus zeigt auch das Hässliche und Elend detailliert.', answer: 'Naturalismus', instruction: 'Literatur' },
    { id: 'de7-r17', type: 'Reading', question: 'Expressionismus drückt die innere Zerrissenheit klar aus.', answer: 'Expressionismus', instruction: 'Literatur' },
    { id: 'de7-r18', type: 'Reading', question: 'Thomas Mann erhielt den Nobelpreis für sein großes Werk.', answer: 'Thomas Mann', instruction: 'Literatur' },
    { id: 'de7-r19', type: 'Reading', question: 'Franz Kafka beschrieb oft surreale und Ängstliche Welten.', answer: 'Kafka', instruction: 'Literatur' },
    { id: 'de7-r20', type: 'Reading', question: 'Heinrich Böll war ein kritischer Geist nach dem Krieg hier.', answer: 'Heinrich Böll', instruction: 'Literatur' },
    { id: 'de7-r21', type: 'Reading', question: 'Die Relativitätstheorie veränderte unser Bild vom Licht.', answer: 'Relativität', instruction: 'Physik' },
    { id: 'de7-r22', type: 'Reading', question: 'Quantenphysik beschäftigt sich mit den kleinsten Teilchen.', answer: 'kleinste Teilchen', instruction: 'Physik' },
    { id: 'de7-r23', type: 'Reading', question: 'Genetik erklärt wie Eigenschaften weitergegeben werden.', answer: 'Eigenschaften', instruction: 'Biologie' },
    { id: 'de7-r24', type: 'Reading', question: 'Die Evolutionstheorie von Darwin war damals revolutionär.', answer: 'Evolution', instruction: 'Biologie' },
    { id: 'de7-r25', type: 'Reading', question: 'Mikrobiologie untersucht Kleinstlebewesen wie Bakterien.', answer: 'Bakterien', instruction: 'Biologie' },
    { id: 'de7-r26', type: 'Reading', question: 'Neurowissenschaften erforschen das menschliche Gehirn aktiv.', answer: 'Gehirn', instruction: 'Biologie' },
    { id: 'de7-r27', type: 'Reading', question: 'Psychologie ist die Wissenschaft vom Erleben und Verhalten.', answer: 'Erleben', instruction: 'Soziales' },
    { id: 'de7-r28', type: 'Reading', question: 'Philosophie stellt grundlegende Fragen nach dem Sein.', answer: 'Fragen Sein', instruction: 'Geistesw.' },
    { id: 'de7-r29', type: 'Reading', question: 'Immanuel Kant schrieb die Kritik der reinen Vernunft.', answer: 'Kant', instruction: 'Philosophie' },
    { id: 'de7-r30', type: 'Reading', question: 'Friedrich Nietzsche proklamierte das Ende der Götter.', answer: 'Nietzsche', instruction: 'Philosophie' },
    { id: 'de7-r31', type: 'Reading', question: 'Existentialismus betont die Freiheit des Einzelnen heute.', answer: 'Freiheit', instruction: 'Philosophie' },
    { id: 'de7-r32', type: 'Reading', question: 'Ethik befasst sich mit der Moral und dem Handeln an sich.', answer: 'Ethik', instruction: 'Philosophie' },
    { id: 'de7-r33', type: 'Reading', question: 'Soziologie untersucht das Miteinander in Gesellschaften.', answer: 'Miteinander', instruction: 'Soziales' },
    { id: 'de7-r34', type: 'Reading', question: 'Politikwissenschaft analysiert Machtstrukturen im Staat.', answer: 'Machtstrukturen', instruction: 'Soziales' },
    { id: 'de7-r35', type: 'Reading', question: 'Rechtswissenschaft legt die Regeln des Staates genau fest.', answer: 'Regeln Staat', instruction: 'Recht' },
    { id: 'de7-r36', type: 'Reading', question: 'Grundrechte sind im Grundgesetz fest verankert worden.', answer: 'Grundgesetz', instruction: 'Recht' },
    { id: 'de7-r37', type: 'Reading', question: 'Die EU ist ein wirtschaftlicher und politischer Verbund.', answer: 'Verbund', instruction: 'Europa' },
    { id: 'de7-r38', type: 'Reading', question: 'Der Binnenmarkt ermöglicht freien Handel in Europa.', answer: 'Binnenmarkt', instruction: 'Wirtschaft' },
    { id: 'de7-r39', type: 'Reading', question: 'Der Euro ist die gemeinsame Währung vieler EU-Staaten.', answer: 'Euro', instruction: 'Finanzen' },
    { id: 'de7-r40', type: 'Reading', question: 'Schengen bedeutet Reisen ohne Grenzkontrollen im Inneren.', answer: 'Schengen', instruction: 'Reisen' },
    { id: 'de7-r41', type: 'Reading', question: 'Kulturwissenschaft untersucht kulturelle Phänomene breit.', answer: 'Kultur', instruction: 'Soziales' },
    { id: 'de7-r42', type: 'Reading', question: 'Architektur spiegelt den Geist einer Zeit im Bauwerk.', answer: 'Geist Zeit', instruction: 'Kunst' },
    { id: 'de7-r43', type: 'Reading', question: 'Malerei im Impressionismus fing das Licht und Moment ein.', answer: 'Impressionismus', instruction: 'Kunst' },
    { id: 'de7-r44', type: 'Reading', question: 'Kubismus zerlegte Formen in ihre geometrischen Teile.', answer: 'Kubismus', instruction: 'Kunst' },
    { id: 'de7-r45', type: 'Reading', question: 'Moderne Kunst ist oft abstrakt und provoziert Fragen.', answer: 'provoziert', instruction: 'Kunst' },
    { id: 'de7-r46', type: 'Reading', question: 'Kino ist eine junge Kunstform des zwanzigsten Jahrhunderts.', answer: 'Kino', instruction: 'Medien' },
    { id: 'de7-r47', type: 'Reading', question: 'Das Fernsehen wurde zum Massenmedium Nummer eins damals.', answer: 'Massenmedium', instruction: 'Medien' },
    { id: 'de7-r48', type: 'Reading', question: 'Die Pressefreiheit ist ein hohes Gut freier Völker.', answer: 'Pressefreiheit', instruction: 'Politik' },
    { id: 'de7-r49', type: 'Reading', question: 'Fake News sind eine Gefahr für den Diskurs geworden.', answer: 'Fake News', instruction: 'Gesellschaft' },
    { id: 'de7-r50', type: 'Reading', question: 'Kritikfähigkeit schützt vor Manipulation durch Dritte.', answer: 'Kritikfähigkeit', instruction: 'Advice' },
    { id: 'de7-r51', type: 'Reading', question: 'Das Leben genießen heißt auch mal Pausen zu machen.', answer: 'Pausen machen', instruction: 'Advice' },
  ],
  8: [
    { id: 'de8-r1', type: 'Reading', question: 'Sein oder Nichtsein, das ist hier die Frage.', answer: 'Sein oder Nichtsein', instruction: 'Shakespeare' },
    { id: 'de8-r2', type: 'Reading', question: 'Die Welt ist eine Bühne und alle sind bloß Spieler.', answer: 'bloß Spieler', instruction: 'Shakespeare' },
    { id: 'de8-r3', type: 'Reading', question: 'Wissen ist Macht, aber Charakter ist noch viel mehr.', answer: 'Wissen Macht', instruction: 'Philosophie' },
    { id: 'de8-r4', type: 'Reading', question: 'Der Stärkere gewinnt nicht immer am Ende der Schlacht.', answer: 'Schlacht', instruction: 'Strategie' },
    { id: 'de8-r5', type: 'Reading', question: 'Gerechtigkeit ist das Fundament eines jeden Staates.', answer: 'Gerechtigkeit', instruction: 'Recht' },
    { id: 'de8-r6', type: 'Reading', question: 'Freiheit bedeutet auch Verantwortung für sein Handeln.', answer: 'Verantwortung', instruction: 'Ethik' },
    { id: 'de8-r7', type: 'Reading', question: 'Mut ist nicht die Abwesenheit von Angst sondern Trotz.', answer: 'Trotz', instruction: 'Psychologie' },
    { id: 'de8-r8', type: 'Reading', question: 'In der Ruhe liegt die Kraft des Weisen verborgen.', answer: 'Kraft Weisen', instruction: 'Advice' },
    { id: 'de8-r9', type: 'Reading', question: 'Die Zeit heilt alle Wunden die das Schicksal schlägt.', answer: 'Zeit heilt', instruction: 'Quotes' },
    { id: 'de8-r10', type: 'Reading', question: 'Träume nicht dein Leben, sondern lebe deinen Traum.', answer: 'lebe Traum', instruction: 'Quotes' },
    { id: 'de8-r11', type: 'Reading', question: 'Wer rastet, der rostet in der heutigen schnellen Welt.', answer: 'rastet rostet', instruction: 'Quotes' },
    { id: 'de8-r12', type: 'Reading', question: 'Ein Lächeln ist die kürzeste Verbindung zwischen uns.', answer: 'Verbindung', instruction: 'Social' },
    { id: 'de8-r13', type: 'Reading', question: 'Der Klügere gibt nach bis er am Ende der Dumme ist.', answer: 'Klügere nach', instruction: 'Quotes' },
    { id: 'de8-r14', type: 'Reading', question: 'Alles hat ein Ende, nur die Wurst hat eben zwei.', answer: 'zwei Enden', instruction: 'Humor' },
    { id: 'de8-r15', type: 'Reading', question: 'Reden ist Silber, aber Schweigen ist oft Gold wert.', answer: 'Gold wert', instruction: 'Quotes' },
    { id: 'de8-r16', type: 'Reading', question: 'Ubung macht den Meister in jedem Fach der Welt.', answer: 'Ubung Meister', instruction: 'Motivation' },
    { id: 'de8-r17', type: 'Reading', question: 'Wer zuerst kommt, mahlt zuerst in der Mühle hier.', answer: 'mahlt zuerst', instruction: 'Quotes' },
    { id: 'de8-r18', type: 'Reading', question: 'Ohne Fleiß kein Preis im harten täglichen Leben heut.', answer: 'kein Preis', instruction: 'Quotes' },
    { id: 'de8-r19', type: 'Reading', question: 'Kleider machen Leute in unserer modernen Gesellschaft.', answer: 'Kleider Leute', instruction: 'Quotes' },
    { id: 'de8-r20', type: 'Reading', question: 'Man soll den Tag nicht vor dem Abend loben hier.', answer: 'Abend loben', instruction: 'Quotes' },
    { id: 'de8-r21', type: 'Reading', question: 'Innovation unterscheidet den Leader vom Follower heut.', answer: 'Innovation', instruction: 'Job' },
    { id: 'de8-r22', type: 'Reading', question: 'Das Ganze ist mehr als die Summe seiner Teile nur.', answer: 'Summe Teile', instruction: 'Philosophie' },
    { id: 'de8-r23', type: 'Reading', question: 'Panta rhei bedeutet alles fließt im ewigen Wandel hier.', answer: 'alles fließt', instruction: 'Griechisch' },
    { id: 'de8-r24', type: 'Reading', question: 'Carpe diem fordert uns auf den Tag zu nutzen.', answer: 'Carpe diem', instruction: 'Latein' },
    { id: 'de8-r25', type: 'Reading', question: 'Veni vidi vici ist die berühmte Cäsar Meldung damals.', answer: 'Cäsar', instruction: 'Geschichte' },
    { id: 'de8-r26', type: 'Reading', question: 'Global Governance braucht internationale Kooperation heut.', answer: 'Kooperation', instruction: 'Global' },
    { id: 'de8-r27', type: 'Reading', question: 'Künstliche Intelligenz birgt Chancen und große Risiken.', answer: 'Chancen Risiken', instruction: 'Technik' },
    { id: 'de8-r28', type: 'Reading', question: 'Big Data ermöglicht präzise Analysen von Trends jetzt.', answer: 'Big Data', instruction: 'IT' },
    { id: 'de8-r29', type: 'Reading', question: 'Cybersecurity schützt sensible Daten vor fremden Zugriff.', answer: 'Cybersecurity', instruction: 'IT' },
    { id: 'de8-r30', type: 'Reading', question: 'Blockchain-Technologie ist die Basis für Krypto heute.', answer: 'Basis Krypto', instruction: 'Finanzen' },
    { id: 'de8-r31', type: 'Reading', question: 'Smart Cities nutzen Technik für ein besseres Wohnen.', answer: 'Smart Cities', instruction: 'Wohnen' },
    { id: 'de8-r32', type: 'Reading', question: 'Renewable Energies sind der Schlüssel zur Wende jetzt.', answer: 'Schlüssel Wende', instruction: 'Klima' },
    { id: 'de8-r33', type: 'Reading', question: 'Circular Economy vermeidet Abfall durch kluge Kreisläufe.', answer: 'Kreisläufe', instruction: 'Umwelt' },
    { id: 'de8-r34', type: 'Reading', question: 'Corporate Social Responsibility ist Pflicht für Firmen.', answer: 'CSR Pflicht', instruction: 'Business' },
    { id: 'de8-r35', type: 'Reading', question: 'Design Thinking ist eine Methode zur Problemlösung neu.', answer: 'Design Thinking', instruction: 'Business' },
    { id: 'de8-r36', type: 'Reading', question: 'Home Office verändert die moderne Arbeitswelt von heute.', answer: 'Home Office', instruction: 'Arbeit' },
    { id: 'de8-r37', type: 'Reading', question: 'Agile Methoden machen Teams oft flexibler und schneller.', answer: 'flexibler', instruction: 'Arbeit' },
    { id: 'de8-r38', type: 'Reading', question: 'Digitaler Nomadismus ist ein Trend bei jungen Leuten.', answer: 'Nomadismus', instruction: 'Lifestyle' },
    { id: 'de8-r39', type: 'Reading', question: 'Vanlife bedeutet das Leben im ausgebauten Campervan.', answer: 'Vanlife', instruction: 'Lifestyle' },
    { id: 'de8-r40', type: 'Reading', question: 'Slow Living entschleunigt den hektischen Alltag draußen.', answer: 'Entschleunigt', instruction: 'Lifestyle' },
    { id: 'de8-r41', type: 'Reading', question: 'Personal Branding ist heute wichtig für die Kariere.', answer: 'Personal Brand', instruction: 'Job' },
    { id: 'de8-r42', type: 'Reading', question: 'Networking erweitert den beruflichen Horizont von uns.', answer: 'Networking', instruction: 'Job' },
    { id: 'de8-r43', type: 'Reading', question: 'Public Relations pflegt das Bild in der Öffentlichkeit.', answer: 'PR Image', instruction: 'Medien' },
    { id: 'de8-r44', type: 'Reading', question: 'Interkulturelle Kompetenz ist nötig in einer Welt.', answer: 'Kompetenz', instruction: 'Global' },
    { id: 'de8-r45', type: 'Reading', question: 'Gender Mainstreaming fördert die Gleichstellung aktiv hier.', answer: 'Gleichstellung', instruction: 'Politik' },
    { id: 'de8-r46', type: 'Reading', question: 'Demografischer Wandel führt zur Alterung der Leute.', answer: 'Alterung', instruction: 'Social' },
    { id: 'de8-r47', type: 'Reading', question: 'Individualisierung prägt die moderne westliche Kultur.', answer: 'Kultur', instruction: 'Social' },
    { id: 'de8-r48', type: 'Reading', question: 'Wohlstandsgesellschaft konsumiert oft mehr als gesund ist.', answer: 'Konsum', instruction: 'Social' },
    { id: 'de8-r49', type: 'Reading', question: 'Prekariat beschreibt Menschen in unsicheren Jobs heut.', answer: 'unsichere Jobs', instruction: 'Social' },
    { id: 'de8-r50', type: 'Reading', question: 'Zivilgesellschaft übernimmt wichtige soziale Aufgaben.', answer: 'Zivilgesellschaft', instruction: 'Social' },
    { id: 'de8-r51', type: 'Reading', question: 'Humanitas bedeutet Menschlichkeit als oberstes Gebot.', answer: 'Humanitas', instruction: 'Ethik' },
  ],
  9: [
    { id: 'de9-r1', type: 'Reading', question: 'Postkoloniale Literatur analysiert Machtstrukturen heute.', answer: 'Machtstrukturen', instruction: 'Literatur' },
    { id: 'de9-r2', type: 'Reading', question: 'Magischer Realismus vermischt Alltag mit Phantastik.', answer: 'Vermischt Alltag', instruction: 'Literatur' },
    { id: 'de9-r3', type: 'Reading', question: 'Dystopien entwerfen oft düstere Zukunftsszenarien hier.', answer: 'Zukunftsszenarien', instruction: 'Literatur' },
    { id: 'de9-r4', type: 'Reading', question: 'Intertextualität bezeichnet Bezüge zwischen Texten.', answer: 'Bezüge', instruction: 'Literatur' },
    { id: 'de9-r5', type: 'Reading', question: 'Hermeneutik ist die Kunst des Verstehens von Texten.', answer: 'Kunst Verstehens', instruction: 'Philosophie' },
    { id: 'de9-r6', type: 'Reading', question: 'Dekonstruktion hinterfragt feste Bedeutungen in Texten.', answer: 'hinterfragt', instruction: 'Philosophie' },
    { id: 'de9-r7', type: 'Reading', question: 'Phänomenologie untersucht Strukturen des Bewusstseins.', answer: 'Strukturen', instruction: 'Philosophie' },
    { id: 'de9-r8', type: 'Reading', question: 'Diskursanalyse untersucht wie Wissen produziert wird.', answer: 'Wissen', instruction: 'Soziologie' },
    { id: 'de9-r9', type: 'Reading', question: 'Paradigmawechsel bedeutet ein völlig neues Weltbild.', answer: 'neues Weltbild', instruction: 'Wissenschaft' },
    { id: 'de9-r10', type: 'Reading', question: 'Das anthropozäne Zeitalter ist vom Menschen geprägt.', answer: 'vom Menschen', instruction: 'Ökologie' },
    { id: 'de9-r11', type: 'Reading', question: 'Kybernetik befasst sich mit Steuerungsmechanismen.', answer: 'Steuerung', instruction: 'Technik' },
    { id: 'de9-r12', type: 'Reading', question: 'Entropie ist ein Maß für die Unordnung im System.', answer: 'Unordnung', instruction: 'Physik' },
    { id: 'de9-r13', type: 'Reading', question: 'Osmose ist der Ausgleich von Konzentrationen hier.', answer: 'Ausgleich', instruction: 'Biologie' },
    { id: 'de9-r14', type: 'Reading', question: 'Metabolismus bezeichnet den gesamten Stoffwechsel heut.', answer: 'Stoffwechsel', instruction: 'Biologie' },
    { id: 'de9-r15', type: 'Reading', question: 'Kognition umfasst alle Prozesse der Informationsaufnahme.', answer: 'Informationsaufn.', instruction: 'Psychologie' },
    { id: 'de9-r16', type: 'Reading', question: 'Behaviorismus fokussiert sich auf beobachtbares Tun.', answer: 'Beobachtbares', instruction: 'Psychologie' },
    { id: 'de9-r17', type: 'Reading', question: 'Konstruktivismus besagt, dass wir Realität erschaffen.', answer: 'Realität erschaffen', instruction: 'Philosophie' },
    { id: 'de9-r18', type: 'Reading', question: 'Pragmatismus bewertet Ideen nach ihrem praktischen Nutzen.', answer: 'praktischer Nutzen', instruction: 'Philosophie' },
    { id: 'de9-r19', type: 'Reading', question: 'Nihilismus verneint jegliche absolute Sinngebung hier.', answer: 'verneint Sinn', instruction: 'Philosophie' },
    { id: 'de9-r20', type: 'Reading', question: 'Hedonismus stellt das Streben nach Genuss ins Zentrum.', answer: 'Streben Genuss', instruction: 'Ethik' },
    { id: 'de9-r21', type: 'Reading', question: 'Stoizismus lehrt Abgeklärtheit gegenüber dem Schicksal.', answer: 'Abgeklärtheit', instruction: 'Ethik' },
    { id: 'de9-r22', type: 'Reading', question: 'Aufklärung forderte den Ausgang aus Unmündigkeit.', answer: 'Ausgang Unmündigk.', instruction: 'Geschichte' },
    { id: 'de9-r23', type: 'Reading', question: 'Säkularisierung trennt die Kirche strikt vom Staat.', answer: 'trennt Kirche', instruction: 'Politik' },
    { id: 'de9-r24', type: 'Reading', question: 'Pluralismus erkennt verschiedene Lebensentwürfe an.', answer: 'Lebensentwürfe', instruction: 'Gesellschaft' },
    { id: 'de9-r25', type: 'Reading', question: 'Egalitarismus strebt soziale Gleichheit für alle an.', answer: 'Gleichheit', instruction: 'Politik' },
    { id: 'de9-r26', type: 'Reading', question: 'Meritokratie belohnt Leistung statt herkunft oder Adel.', answer: 'belohnt Leistung', instruction: 'Soziologie' },
    { id: 'de9-r27', type: 'Reading', question: 'Neoliberalismus setzt auf freien Markt und Wettbewerb.', answer: 'freier Markt', instruction: 'Wirtschaft' },
    { id: 'de9-r28', type: 'Reading', question: 'Keynesianismus befürwortet Staatsinterventionen klug.', answer: 'Staatsintervention', instruction: 'Wirtschaft' },
    { id: 'de9-r29', type: 'Reading', question: 'Gentrifizierung verändert die Sozialstruktur in Kiez.', answer: 'Sozialstruktur', instruction: 'Urbanistik' },
    { id: 'de9-r30', type: 'Reading', question: 'Transhumanismus will menschliche Grenzen überwinden.', answer: 'Grenzen überwinden', instruction: 'Zukunft' },
    { id: 'de9-r31', type: 'Reading', question: 'Singularität ist der Punkt an dem KI uns überholt.', answer: 'Punkt KI überholt', instruction: 'Zukunft' },
    { id: 'de9-r32', type: 'Reading', question: 'Algorithmen steuern heute viele unserer Handlungen.', answer: 'steuern Handlungen', instruction: 'Digitalität' },
    { id: 'de9-r33', type: 'Reading', question: 'Echo-Kammern verstärken oft die eigene Meinung extrem.', answer: 'eigene Meinung', instruction: 'Social Media' },
    { id: 'de9-r34', type: 'Reading', question: 'Überwachungskapitalismus nutzt Daten für Profit aus.', answer: 'nutzt Daten', instruction: 'Kritik' },
    { id: 'de9-r35', type: 'Reading', question: 'Resilienz hilft Krisen unbeschadet zu überstehen.', answer: 'Krisen überstehen', instruction: 'Psychologie' },
    { id: 'de9-r36', type: 'Reading', question: 'Achtsamkeit bedeutet volle Präsenz im jetzigen Moment.', answer: 'volle Präsenz', instruction: 'Lifestyle' },
    { id: 'de9-r37', type: 'Reading', question: 'Nachhaltige Mode setzt på Bio-Stoffe und fairen Lohn.', answer: 'Fairen Lohn', instruction: 'Lifestyle' },
    { id: 'de9-r38', type: 'Reading', question: 'Urban Gardening bringt die Natur zurück in die Stadt.', answer: 'Natur in Stadt', instruction: 'Lifestyle' },
    { id: 'de9-r39', type: 'Reading', question: 'Sharing Economy teilt Güter statt sie nur zu besitzen.', answer: 'Güter teilen', instruction: 'Wirtschaft' },
    { id: 'de9-r40', type: 'Reading', question: 'Klimaneutralität ist das Ziel vieler moderner Staaten.', answer: 'Ziel Staaten', instruction: 'Politik' },
    { id: 'de9-r41', type: 'Reading', question: 'Biodiversität schützt die Vielfalt der Arten weltweit.', answer: 'Vielfalt Arten', instruction: 'Umwelt' },
    { id: 'de9-r42', type: 'Reading', question: 'Permakultur ahmt natürliche Kreisläufe im Garten nach.', answer: 'Kreisläufe', instruction: 'Ökologie' },
    { id: 'de9-r43', type: 'Reading', question: 'Geopolitische Spannungen beeinflussen den Welthandel.', answer: 'Welthandel', instruction: 'Politik' },
    { id: 'de9-r44', type: 'Reading', question: 'Humanitäre Hilfe rettet Leben in vielen Krisengebieten.', answer: 'rettet Leben', instruction: 'Global' },
    { id: 'de9-r45', type: 'Reading', question: 'Völkerrecht regelt die Beziehungen zwischen Nationen.', answer: 'Beziehungen', instruction: 'Recht' },
    { id: 'de9-r46', type: 'Reading', question: 'Pazifismus lehnt Gewalt als Mittel der Politik ab.', answer: 'lehnt Gewalt ab', instruction: 'Ethik' },
    { id: 'de9-r47', type: 'Reading', question: 'Weltschmerz beschreibt das Leiden an der Welt an sich.', answer: 'Leiden an Welt', instruction: 'Gefühl' },
    { id: 'de9-r48', type: 'Reading', question: 'Fernweh ist die Sehnsucht nach fernen Ländern hier.', answer: 'Sehnsucht Ferne', instruction: 'Gefühl' },
    { id: 'de9-r49', type: 'Reading', question: 'Heimat ist dort, wo man sich geborgen und sicher fühlt.', answer: 'geborgen fühlen', instruction: 'Gefühl' },
    { id: 'de9-r50', type: 'Reading', question: 'Zivilcourage ist heute wichtiger denn je in unserer Welt.', answer: 'Wichtiger denn je', instruction: 'Moral' },
    { id: 'de9-r51', type: 'Reading', question: 'Die Zukunft liegt in unseren Händen, gestalten wir sie!', answer: 'unsere Händen', instruction: 'Appell' },
  ],
};
