/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const DANSK_CLOZE_P3: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'da0-c52', type: 'Cloze', question: 'Jeg kan ___ lide æbler.', answer: 'godt', options: ['godt', 'ikke', 'måske'], instruction: 'Hvad kan du?' },
    { id: 'da0-c53', type: 'Cloze', question: 'Min bamse er ___.', answer: 'blød', options: ['blød', 'hård', 'kold'], instruction: 'Beskrivelse' },
    { id: 'da0-c54', type: 'Cloze', question: 'Jeg ___ i min seng.', answer: 'sover', options: ['sover', 'hopper', 'spiser'], instruction: 'Handling' },
    { id: 'da0-c55', type: 'Cloze', question: 'Mælken er ___.', answer: 'hvid', options: ['hvid', 'sort', 'rød'], instruction: 'Farve' },
    { id: 'da0-c56', type: 'Cloze', question: 'Jeg har ___ øjne.', answer: 'to', options: ['to', 'tre', 'en'], instruction: 'Krop' },
    { id: 'da0-c57', type: 'Cloze', question: 'Katten ___ mælk.', answer: 'drikker', options: ['drikker', 'spiser', 'læser'], instruction: 'Handling' },
    { id: 'da0-c58', type: 'Cloze', question: 'Hunden har en ___ hale.', answer: 'lang', options: ['lang', 'kort', 'ingen'], instruction: 'Beskrivelse' },
    { id: 'da0-c59', type: 'Cloze', question: 'Jeg ___ på en stol.', answer: 'sidder', options: ['sidder', 'står', 'går'], instruction: 'Handling' },
    { id: 'da0-c60', type: 'Cloze', question: 'Solen ___ på himlen.', answer: 'lyser', options: ['lyser', 'sover', 'spiser'], instruction: 'Natur' },
    { id: 'da0-c61', type: 'Cloze', question: 'Jeg tegner med en ___.', answer: 'blyant', options: ['blyant', 'gaffel', 'ske'], instruction: 'Skole' },
    { id: 'da0-c62', type: 'Cloze', question: 'Æblet smager ___.', answer: 'sødt', options: ['sødt', 'surt', 'stærkt'], instruction: 'Smag' },
    { id: 'da0-c63', type: 'Cloze', question: 'Jeg har en ___ taske.', answer: 'blå', options: ['blå', 'rød', 'gul'], instruction: 'Farve' },
    { id: 'da0-c64', type: 'Cloze', question: 'Min far er ___.', answer: 'stor', options: ['stor', 'lille', 'blå'], instruction: 'Beskrivelse' },
    { id: 'da0-c65', type: 'Cloze', question: 'Jeg ___ en sang.', answer: 'synger', options: ['synger', 'spiser', 'sover'], instruction: 'Handling' },
    { id: 'da0-c66', type: 'Cloze', question: 'Vandet er ___.', answer: 'koldt', options: ['koldt', 'varmt', 'tørt'], instruction: 'Vejr' },
    { id: 'da0-c67', type: 'Cloze', question: 'Jeg ___ på legepladsen.', answer: 'leger', options: ['leger', 'sover', 'læser'], instruction: 'Handling' },
    { id: 'da0-c68', type: 'Cloze', question: 'Blomsten er ___.', answer: 'smuk', options: ['smuk', 'grim', 'vild'], instruction: 'Beskrivelse' },
    { id: 'da0-c69', type: 'Cloze', question: 'Jeg ___ min far.', answer: 'ser', options: ['ser', 'hører', 'smager'], instruction: 'Sans' },
    { id: 'da0-c70', type: 'Cloze', question: 'Bilen har ___ hjul.', answer: 'fire', options: ['fire', 'to', 'seks'], instruction: 'Bil' },
    { id: 'da0-c71', type: 'Cloze', question: 'Jeg ___ madpakke.', answer: 'har', options: ['har', 'er', 'kan'], instruction: 'Mad' },
    { id: 'da0-c72', type: 'Cloze', question: 'Katten er ___.', answer: 'sød', options: ['sød', 'sur', 'blå'], instruction: 'Dyr' },
    { id: 'da0-c73', type: 'Cloze', question: 'Jeg ___ glad i dag.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Følelse' },
    { id: 'da0-c74', type: 'Cloze', question: 'Det ___ udenfor.', answer: 'regner', options: ['regner', 'blæser', 'lyser'], instruction: 'Vejr' },
    { id: 'da0-c75', type: 'Cloze', question: 'Jeg ___ en bog.', answer: 'læser', options: ['læser', 'spiser', 'hopper'], instruction: 'Handling' },
    { id: 'da0-c76', type: 'Cloze', question: 'Fisken er i ___.', answer: 'vandet', options: ['vandet', 'luften', 'skoven'], instruction: 'Natur' },
    { id: 'da0-c77', type: 'Cloze', question: 'Jeg ___ til musik.', answer: 'danser', options: ['danser', 'sover', 'læser'], instruction: 'Handling' },
    { id: 'da0-c78', type: 'Cloze', question: 'Græsset er ___.', answer: 'grønt', options: ['grønt', 'gult', 'blåt'], instruction: 'Farve' },
    { id: 'da0-c79', type: 'Cloze', question: 'Mine sko er ___.', answer: 'sorte', options: ['sorte', 'hvide', 'røde'], instruction: 'Tøj' },
    { id: 'da0-c80', type: 'Cloze', question: 'Jeg ___ på tavlen.', answer: 'kigger', options: ['kigger', 'spiser', 'sover'], instruction: 'Skole' },
    { id: 'da0-c81', type: 'Cloze', question: 'Døren er ___.', answer: 'lukket', options: ['lukket', 'åben', 'blå'], instruction: 'Hus' },
    { id: 'da0-c82', type: 'Cloze', question: 'Jeg ___ mælk.', answer: 'vil have', options: ['vil have', 'fik', 'har'], instruction: 'Lyst' },
    { id: 'da0-c83', type: 'Cloze', question: 'Hestene ___ hurtigt.', answer: 'løber', options: ['løber', 'flyver', 'svømmer'], instruction: 'Dyr' },
    { id: 'da0-c84', type: 'Cloze', question: 'Jeg ___ min mor.', answer: 'hjælper', options: ['hjælper', 'slår', 'bider'], instruction: 'Handling' },
    { id: 'da0-c85', type: 'Cloze', question: 'Æblet er ___ og rundt.', answer: 'rødt', options: ['rødt', 'blåt', 'sort'], instruction: 'Beskrivelse' },
    { id: 'da0-c86', type: 'Cloze', question: 'Jeg ___ i skole.', answer: 'går', options: ['går', 'spiser', 'sover'], instruction: 'Handling' },
    { id: 'da0-c87', type: 'Cloze', question: 'Tasken er ___.', answer: 'tung', options: ['tung', 'let', 'blå'], instruction: 'Vægt' },
    { id: 'da0-c88', type: 'Cloze', question: 'Jeg ___ saft.', answer: 'drikker', options: ['drikker', 'spiser', 'læser'], instruction: 'Handling' },
    { id: 'da0-c89', type: 'Cloze', question: 'Hunden ___ glad.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Tilstand' },
    { id: 'da0-c90', type: 'Cloze', question: 'Isen ___ kold.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Tilstand' },
    { id: 'da0-c91', type: 'Cloze', question: 'Vi ___ en leg.', answer: 'legede', options: ['legede', 'spiste', 'sov'], instruction: 'Handling' },
    { id: 'da0-c92', type: 'Cloze', question: 'Min ven er ___.', answer: 'sød', options: ['sød', 'dum', 'blå'], instruction: 'Ven' },
    { id: 'da0-c93', type: 'Cloze', question: 'Jeg ___ mine hænder.', answer: 'vasker', options: ['vasker', 'spiser', 'hopper'], instruction: 'Hygiejne' },
    { id: 'da0-c94', type: 'Cloze', question: 'Lyset er ___.', answer: 'tændt', options: ['tændt', 'slukket', 'gult'], instruction: 'Hus' },
    { id: 'da0-c95', type: 'Cloze', question: 'Vi ___ en historie.', answer: 'hører', options: ['hører', 'spiser', 'sover'], instruction: 'Handling' },
    { id: 'da0-c96', type: 'Cloze', question: 'Grøden er ___.', answer: 'varm', options: ['varm', 'kold', 'blå'], instruction: 'Mad' },
    { id: 'da0-c97', type: 'Cloze', question: 'Jeg ___ træt nu.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Følelse' },
    { id: 'da0-c98', type: 'Cloze', question: 'Godnat, mor og ___.', answer: 'far', options: ['far', 'bil', 'hund'], instruction: 'Familie' },
    { id: 'da0-c99', type: 'Cloze', question: 'Jeg ___ i morgen.', answer: 'kommer', options: ['kommer', 'gik', 'sov'], instruction: 'Tid' },
    { id: 'da0-c100', type: 'Cloze', question: 'Dansk 0 er ___!', answer: 'slut', options: ['slut', 'start', 'midt'], instruction: 'Meta' },
  ],
  1: [
    { id: 'da1-c52', type: 'Cloze', question: 'Jeg ___ en spændende bog.', answer: 'læser', options: ['læser', 'spiser', 'løber'], instruction: 'Skole' },
    { id: 'da1-c53', type: 'Cloze', question: 'Min ven ___ glad i dag.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Tilstand' },
    { id: 'da1-c54', type: 'Cloze', question: 'Vi ___ fodbold i går.', answer: 'spillede', options: ['spillede', 'spiser', 'sover'], instruction: 'Handling' },
    { id: 'da1-c55', type: 'Cloze', question: 'Hunden ___ efter bolden.', answer: 'løber', options: ['løber', 'flyver', 'svømmer'], instruction: 'Dyr' },
    { id: 'da1-c56', type: 'Cloze', question: 'Jeg ___ min mormor.', answer: 'besøger', options: ['besøger', 'spiser', 'glemmer'], instruction: 'Familie' },
    { id: 'da1-c57', type: 'Cloze', question: 'Æblet er ___ og sødt.', answer: 'rødt', options: ['rødt', 'blåt', 'sort'], instruction: 'Beskrivelse' },
    { id: 'da1-c58', type: 'Cloze', question: 'Vi ___ en sang sammen.', answer: 'synger', options: ['synger', 'spiser', 'sover'], instruction: 'Skole' },
    { id: 'da1-c59', type: 'Cloze', question: 'Det ___ meget i går.', answer: 'regnede', options: ['regnede', 'skinnede', 'blæste'], instruction: 'Vejr' },
    { id: 'da1-c60', type: 'Cloze', question: 'Min far ___ i haven.', answer: 'arbejder', options: ['arbejder', 'sover', 'spiser'], instruction: 'Handling' },
    { id: 'da1-c61', type: 'Cloze', question: 'Tasken er ___ at bære.', answer: 'tung', options: ['tung', 'let', 'blå'], instruction: 'Beskrivelse' },
    { id: 'da1-c62', type: 'Cloze', question: 'Jeg ___ mine lektier nu.', answer: 'laver', options: ['laver', 'glemmer', 'spiser'], instruction: 'Handling' },
    { id: 'da1-c63', type: 'Cloze', question: 'Katten ___ mælk i skålen.', answer: 'drikker', options: ['drikker', 'spiser', 'sover'], instruction: 'Dyr' },
    { id: 'da1-c64', type: 'Cloze', question: 'Vi ___ til stranden i morgen.', answer: 'skal', options: ['skal', 'var', 'er'], instruction: 'Tid' },
    { id: 'da1-c65', type: 'Cloze', question: 'Bilen ___ stærkt på vejen.', answer: 'kører', options: ['kører', 'hopper', 'synger'], instruction: 'Transport' },
    { id: 'da1-c66', type: 'Cloze', question: 'Jeg ___ min madpakke i skolen.', answer: 'spiser', options: ['spiser', 'smider', 'glemmer'], instruction: 'Handling' },
    { id: 'da1-c67', type: 'Cloze', question: 'Blomsterne ___ i haven.', answer: 'vokser', options: ['vokser', 'sover', 'løber'], instruction: 'Natur' },
    { id: 'da1-c68', type: 'Cloze', question: 'Jeg ___ en gave til min ven.', answer: 'har', options: ['har', 'er', 'kan'], instruction: 'Social' },
    { id: 'da1-c69', type: 'Cloze', question: 'Det er ___ at lege med venner.', answer: 'sjovt', options: ['sjovt', 'trist', 'kedeligt'], instruction: 'Følelse' },
    { id: 'da1-c70', type: 'Cloze', question: 'Isen ___ i solen.', answer: 'smelter', options: ['smelter', 'fryser', 'vokser'], instruction: 'Fysik' },
    { id: 'da1-c71', type: 'Cloze', question: 'Jeg ___ min mors hånd.', answer: 'holder', options: ['holder', 'spiser', 'smider'], instruction: 'Handling' },
    { id: 'da1-c72', type: 'Cloze', question: 'Fuglene ___ mod syd.', answer: 'flyver', options: ['flyver', 'svømmer', 'løber'], instruction: 'Dyr' },
    { id: 'da1-c73', type: 'Cloze', question: 'Vi ___ en film i går.', answer: 'så', options: ['så', 'ser', 'skal se'], instruction: 'Tid' },
    { id: 'da1-c74', type: 'Cloze', question: 'Min bror ___ meget hurtigt.', answer: 'løber', options: ['løber', 'flyver', 'sover'], instruction: 'Handling' },
    { id: 'da1-c75', type: 'Cloze', question: 'Jeg ___ tørstig nu.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Tilstand' },
    { id: 'da1-c76', type: 'Cloze', question: 'Det er ___ vejr i dag.', answer: 'dejligt', options: ['dejligt', 'sur', 'trist'], instruction: 'Vejr' },
    { id: 'da1-c77', type: 'Cloze', question: 'Vi ___ vores tøj i vasken.', answer: 'lægger', options: ['lægger', 'spiser', 'smider'], instruction: 'Orden' },
    { id: 'da1-c78', type: 'Cloze', question: 'Jeg ___ hej til min nabo.', answer: 'siger', options: ['siger', 'hører', 'spiser'], instruction: 'Social' },
    { id: 'da1-c79', type: 'Cloze', question: 'Katten ___ på sengen.', answer: 'sover', options: ['sover', 'danser', 'løber'], instruction: 'Handling' },
    { id: 'da1-c80', type: 'Cloze', question: 'Vi ___ opvasken sammen.', answer: 'tager', options: ['tager', 'spiser', 'glemmer'], instruction: 'Handling' },
    { id: 'da1-c81', type: 'Cloze', question: 'Jeg ___ min cykel.', answer: 'pudser', options: ['pudser', 'spiser', 'smider'], instruction: 'Handling' },
    { id: 'da1-c82', type: 'Cloze', question: 'Det ___ i nat.', answer: 'sneede', options: ['sneede', 'lyste', 'skinnede'], instruction: 'Vejr' },
    { id: 'da1-c83', type: 'Cloze', question: 'Jeg ___ en god karakter.', answer: 'fik', options: ['fik', 'er', 'har'], instruction: 'Skole' },
    { id: 'da1-c84', type: 'Cloze', question: 'Min søster ___ klaver.', answer: 'spiller', options: ['spiller', 'læser', 'spiser'], instruction: 'Musik' },
    { id: 'da1-c85', type: 'Cloze', question: 'Vi ___ til bedstemor.', answer: 'skriver', options: ['skriver', 'spiser', 'sover'], instruction: 'Social' },
    { id: 'da1-c86', type: 'Cloze', question: 'Bussen ___ klokken otte.', answer: 'kommer', options: ['kommer', 'går', 'flyver'], instruction: 'Tid' },
    { id: 'da1-c87', type: 'Cloze', question: 'Jeg ___ rød saft.', answer: 'vil have', options: ['vil have', 'fik', 'har'], instruction: 'Lyst' },
    { id: 'da1-c88', type: 'Cloze', question: 'Det er ___ at lære nyt.', answer: 'godt', options: ['godt', 'dumt', 'skidt'], instruction: 'Mening' },
    { id: 'da1-c89', type: 'Cloze', question: 'Vi ___ mælk hver dag.', answer: 'drikker', options: ['drikker', 'spiser', 'læser'], instruction: 'Vane' },
    { id: 'da1-c90', type: 'Cloze', question: 'Jeg ___ glæder mig!', answer: 'rigtig', options: ['rigtig', 'ikke', 'lidt'], instruction: 'Følelse' },
    { id: 'da1-c91', type: 'Cloze', question: 'Min lærer ___ pænt.', answer: 'smiler', options: ['smiler', 'råber', 'slår'], instruction: 'Social' },
    { id: 'da1-c92', type: 'Cloze', question: 'Vi ___ vores hænder.', answer: 'vasker', options: ['vasker', 'spiser', 'smider'], instruction: 'Hygiejne' },
    { id: 'da1-c93', type: 'Cloze', question: 'Det er ___ at hjælpe.', answer: 'pænt', options: ['pænt', 'grimt', 'dumt'], instruction: 'Mening' },
    { id: 'da1-c94', type: 'Cloze', question: 'Jeg ___ i sengen.', answer: 'ligger', options: ['ligger', 'står', 'løber'], instruction: 'Handling' },
    { id: 'da1-c95', type: 'Cloze', question: 'Solen ___ os varme.', answer: 'giver', options: ['giver', 'tager', 'fjerner'], instruction: 'Natur' },
    { id: 'da1-c96', type: 'Cloze', question: 'Vi ___ en god dag.', answer: 'har', options: ['har', 'er', 'fik'], instruction: 'Social' },
    { id: 'da1-c97', type: 'Cloze', question: 'Jeg ___ klar nu.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Tilstand' },
    { id: 'da1-c98', type: 'Cloze', question: 'Kom ___ nu!', answer: 'så', options: ['så', 'ikke', 'nu'], instruction: 'Råb' },
    { id: 'da1-c99', type: 'Cloze', question: 'Vi ses ___!', answer: 'snart', options: ['snart', 'aldrig', 'altid'], instruction: 'Hilsen' },
    { id: 'da1-c100', type: 'Cloze', question: 'Dansk 1 er ___!', answer: 'færdig', options: ['færdig', 'startet', 'midt'], instruction: 'Meta' },
  ],
  2: [
    { id: 'da2-c52', type: 'Cloze', question: 'Jeg ___ til musik hver dag.', answer: 'lytter', options: ['lytter', 'ser', 'taler'], instruction: 'Sans' },
    { id: 'da2-c53', type: 'Cloze', question: 'Min bror ___ en hurtig bil.', answer: 'har', options: ['har', 'er', 'kan'], instruction: 'Eje' },
    { id: 'da2-c54', type: 'Cloze', question: 'Vi ___ en stor kage i går.', answer: 'bagte', options: ['bagte', 'bager', 'vil bage'], instruction: 'Tid' },
    { id: 'da2-c55', type: 'Cloze', question: 'Det er ___ at læse bøger.', answer: 'vigtigt', options: ['vigtigt', 'dumt', 'blåt'], instruction: 'Mening' },
    { id: 'da2-c56', type: 'Cloze', question: 'Hunden ___ højt i haven.', answer: 'gøede', options: ['gøede', 'sang', 'sov'], instruction: 'Dyr' },
    { id: 'da2-c57', type: 'Cloze', question: 'Jeg ___ min bedste ven i dag.', answer: 'møder', options: ['møder', 'mødte', 'skal møde'], instruction: 'Tid' },
    { id: 'da2-c58', type: 'Cloze', question: 'Vi ___ mange æbler i år.', answer: 'fik', options: ['fik', 'får', 'mister'], instruction: 'Tid' },
    { id: 'da2-c59', type: 'Cloze', question: 'Bilen ___ ikke køre længere.', answer: 'kan', options: ['kan', 'vil', 'skal'], instruction: 'Tilstand' },
    { id: 'da2-c60', type: 'Cloze', question: 'Det er ___ koldt udenfor.', answer: 'meget', options: ['meget', 'lidt', 'mange'], instruction: 'Mængde' },
    { id: 'da2-c61', type: 'Cloze', question: 'Jeg ___ mine lektier før aftensmad.', answer: 'laver', options: ['laver', 'glemmer', 'spiser'], instruction: 'Handling' },
    { id: 'da2-c62', type: 'Cloze', question: 'Vi ___ til fest på lørdag.', answer: 'skal', options: ['skal', 'var', 'er'], instruction: 'Tid' },
    { id: 'da2-c63', type: 'Cloze', question: 'Husk at ___ døren efter dig.', answer: 'lukke', options: ['lukke', 'åbne', 'smide'], instruction: 'Handling' },
    { id: 'da2-c64', type: 'Cloze', question: 'Maden ___ helt fantastisk.', answer: 'smagte', options: ['smagte', 'hørte', 'så'], instruction: 'Sans' },
    { id: 'da2-c65', type: 'Cloze', question: 'Jeg ___ en rød cykel.', answer: 'ønsker mig', options: ['ønsker mig', 'er', 'kan'], instruction: 'Lyst' },
    { id: 'da2-c66', type: 'Cloze', question: 'Vi ___ en film i biografen.', answer: 'så', options: ['så', 'ser', 'skal se'], instruction: 'Tid' },
    { id: 'da2-c67', type: 'Cloze', question: 'Det ___ kraftigt i nat.', answer: 'blæste', options: ['blæste', 'skinnede', 'lyste'], instruction: 'Vejr' },
    { id: 'da2-c68', type: 'Cloze', question: 'Jeg ___ glad for gaven.', answer: 'blev', options: ['blev', 'er', 'bliver'], instruction: 'Tid' },
    { id: 'da2-c69', type: 'Cloze', question: 'Katten ___ musen på marken.', answer: 'fangede', options: ['fangede', 'hjalp', 'spiste'], instruction: 'Dyr' },
    { id: 'da2-c70', type: 'Cloze', question: 'Vi ___ altid sammen i skolen.', answer: 'spiser', options: ['spiser', 'sover', 'løber'], instruction: 'Social' },
    { id: 'da2-c71', type: 'Cloze', question: 'Jeg ___ min mor med indkøb.', answer: 'hjælper', options: ['hjælper', 'slår', 'glemmer'], instruction: 'Social' },
    { id: 'da2-c72', type: 'Cloze', question: 'Det er ___ at cykle hurtigt.', answer: 'svært', options: ['svært', 'nemt', 'rødt'], instruction: 'Følelse' },
    { id: 'da2-c73', type: 'Cloze', question: 'Jeg ___ spise en is.', answer: 'vil gerne', options: ['vil gerne', 'skal ikke', 'må ikke'], instruction: 'Lyst' },
    { id: 'da2-c74', type: 'Cloze', question: 'Himlen er ___ i dag.', answer: 'blå', options: ['blå', 'rød', 'sort'], instruction: 'Farve' },
    { id: 'da2-c75', type: 'Cloze', question: 'Min taske er ___ at bære.', answer: 'tung', options: ['tung', 'let', 'blå'], instruction: 'Vægt' },
    { id: 'da2-c76', type: 'Cloze', question: 'Vi ___ en sang til koncerten.', answer: 'sang', options: ['sang', 'spiste', 'læste'], instruction: 'Handling' },
    { id: 'da2-c77', type: 'Cloze', question: 'Jeg ___ tørstig efter løb.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Tilstand' },
    { id: 'da2-c78', type: 'Cloze', question: 'Det ___ i morges.', answer: 'regnede', options: ['regnede', 'lyste', 'skinnede'], instruction: 'Vejr' },
    { id: 'da2-c79', type: 'Cloze', question: 'Jeg ___ min søster med lektier.', answer: 'hjælper', options: ['hjælper', 'fodrer', 'slår'], instruction: 'Social' },
    { id: 'da2-c80', type: 'Cloze', question: 'Bogen ___ på bordet.', answer: 'ligger', options: ['ligger', 'står', 'hænger'], instruction: 'Sted' },
    { id: 'da2-c81', type: 'Cloze', question: 'Vi ___ ferie i Italien.', answer: 'holdt', options: ['holdt', 'fik', 'spiste'], instruction: 'Tid' },
    { id: 'da2-c82', type: 'Cloze', question: 'Jeg ___ min adresse.', answer: 'kender', options: ['kender', 'glemmer', 'taber'], instruction: 'Viden' },
    { id: 'da2-c83', type: 'Cloze', question: 'Det er ___ at tale pænt.', answer: 'vigtigt', options: ['vigtigt', 'dumt', 'skidt'], instruction: 'Mening' },
    { id: 'da2-c84', type: 'Cloze', question: 'Jeg ___ op klokken syv.', answer: 'står', options: ['står', 'ligger', 'sidder'], instruction: 'Vane' },
    { id: 'da2-c85', type: 'Cloze', question: 'Vi ___ til bussen hver dag.', answer: 'går', options: ['går', 'løber', 'flyver'], instruction: 'Vane' },
    { id: 'da2-c86', type: 'Cloze', question: 'Jeg ___ min fødselsdag.', answer: 'elsker', options: ['elsker', 'hader', 'bor'], instruction: 'Følelse' },
    { id: 'da2-c87', type: 'Cloze', question: 'Mælken er ___.', answer: 'kold', options: ['kold', 'varm', 'sur'], instruction: 'Tilstand' },
    { id: 'da2-c88', type: 'Cloze', question: 'Vi ___ i gården i pausen.', answer: 'leger', options: ['leger', 'sover', 'spiser'], instruction: 'Skole' },
    { id: 'da2-c89', type: 'Cloze', question: 'Det er ___ at vinde.', answer: 'sjovt', options: ['sjovt', 'trist', 'kedeligt'], instruction: 'Følelse' },
    { id: 'da2-c90', type: 'Cloze', question: 'Jeg ___ tak for hjælpen.', answer: 'siger', options: ['siger', 'hører', 'ser'], instruction: 'Social' },
    { id: 'da2-c91', type: 'Cloze', question: 'Vandet ___ i kanden.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Tilstand' },
    { id: 'da2-c92', type: 'Cloze', question: 'Vi ___ en historie i skolen.', answer: 'hørte', options: ['hørte', 'spiste', 'sov'], instruction: 'Tid' },
    { id: 'da2-c93', type: 'Cloze', question: 'Jeg ___ mit navn her.', answer: 'skriver', options: ['skriver', 'læser', 'spiser'], instruction: 'Handling' },
    { id: 'da2-c94', type: 'Cloze', question: 'Bordet er ___ af træ.', answer: 'lavet', options: ['lavet', 'spist', 'købt'], instruction: 'Beskrivelse' },
    { id: 'da2-c95', type: 'Cloze', question: 'Jeg ___ mæt nu.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Tilstand' },
    { id: 'da2-c96', type: 'Cloze', question: 'Vi ___ til sommer.', answer: 'rejser', options: ['rejser', 'bor', 'lever'], instruction: 'Fremtid' },
    { id: 'da2-c97', type: 'Cloze', question: 'Min taske ___ blå.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Farve' },
    { id: 'da2-c98', type: 'Cloze', question: 'Husk ___ taske!', answer: 'din', options: ['din', 'min', 'sin'], instruction: 'Eje' },
    { id: 'da2-c99', type: 'Cloze', question: 'Vi ses ___!', answer: 'igen', options: ['igen', 'aldrig', 'altid'], instruction: 'Social' },
    { id: 'da2-c100', type: 'Cloze', question: 'Dansk 2 er ___!', answer: 'færdig', options: ['færdig', 'startet', 'midt'], instruction: 'Meta' },
  ],
  3: [
    { id: 'da3-c52', type: 'Cloze', question: 'Jeg kan $(\dots)$ lide at læse bøger.', answer: 'godt', options: ['godt', 'ikke', 'aldrig'], instruction: 'Mening' },
    { id: 'da3-c53', type: 'Cloze', question: 'Min ven $(\dots)$ i samme klasse som mig.', answer: 'går', options: ['går', 'er', 'bor'], instruction: 'Skole' },
    { id: 'da3-c54', type: 'Cloze', question: 'Vi $(\dots)$ altid vores madpakker i pausen.', answer: 'spiser', options: ['spiser', 'drikker', 'smider'], instruction: 'Handling' },
    { id: 'da3-c55', type: 'Cloze', question: 'Hunden $(\dots)$ stærkt efter haren.', answer: 'løb', options: ['løb', 'sov', 'spiste'], instruction: 'Datid' },
    { id: 'da3-c56', type: 'Cloze', question: 'I går $(\dots)$ det hele dagen.', answer: 'regnede', options: ['regnede', 'skinnede', 'blæste'], instruction: 'Vejr' },
    { id: 'da3-c57', type: 'Cloze', question: 'Min mor $(\dots)$ en lækker kage til os.', answer: 'bagte', options: ['bagte', 'købte', 'spiste'], instruction: 'Handling' },
    { id: 'da3-c58', type: 'Cloze', question: 'Vi $(\dots)$ en spændende film i aften.', answer: 'skal se', options: ['skal se', 'så', 'ser'], instruction: 'Fremtid' },
    { id: 'da3-c59', type: 'Cloze', question: 'Barnet $(\dots)$ fordi det var træt.', answer: 'græd', options: ['græd', 'grinede', 'sov'], instruction: 'Følelse' },
    { id: 'da3-c60', type: 'Cloze', question: 'Solen $(\dots)$ meget skarpt her til morgen.', answer: 'skinner', options: ['skinner', 'regner', 'blæser'], instruction: 'Vejr' },
    { id: 'da3-c61', type: 'Cloze', question: 'Jeg $(\dots)$ mine lektier før jeg må lege.', answer: 'laver', options: ['laver', 'glemmer', 'mister'], instruction: 'Handling' },
    { id: 'da3-c62', type: 'Cloze', question: 'Husk at $(\dots)$ dine hænder før maden.', answer: 'vaske', options: ['vaske', 'spise', 'smøre'], instruction: 'Hygiejne' },
    { id: 'da3-c63', type: 'Cloze', question: 'Katten $(\dots)$ musen i haven.', answer: 'fangede', options: ['fangede', 'hjalp', 'spiste'], instruction: 'Handling' },
    { id: 'da3-c64', type: 'Cloze', question: 'Vi $(\dots)$ til stranden i sommerferien.', answer: 'rejste', options: ['rejste', 'blev', 'sov'], instruction: 'Handling' },
    { id: 'da3-c65', type: 'Cloze', question: 'Det er $(\dots)$ at få nye venner.', answer: 'dejligt', options: ['dejligt', 'trist', 'kedeligt'], instruction: 'Følelse' },
    { id: 'da3-c66', type: 'Cloze', question: 'Bilen $(\dots)$ ikke køre længere.', answer: 'kunne', options: ['kunne', 'ville', 'skulle'], instruction: 'Tilstand' },
    { id: 'da3-c67', type: 'Cloze', question: 'Jeg $(\dots)$ min far i haven.', answer: 'hjalp', options: ['hjalp', 'fodrede', 'spiste'], instruction: 'Handling' },
    { id: 'da3-c68', type: 'Cloze', question: 'Blomsterne $(\dots)$ smukt i bedet.', answer: 'blomstrer', options: ['blomstrer', 'visner', 'sover'], instruction: 'Tilstand' },
    { id: 'da3-c69', type: 'Cloze', question: 'Maden $(\dots)$ rigtig godt i dag.', answer: 'smager', options: ['smager', 'hører', 'ser'], instruction: 'Sans' },
    { id: 'da3-c70', type: 'Cloze', question: 'Vi $(\dots)$ hej til naboen.', answer: 'sagde', options: ['sagde', 'hørte', 'spiste'], instruction: 'Social' },
    { id: 'da3-c71', type: 'Cloze', question: 'Det er vigtigt at $(\dots)$ ordentligt.', answer: 'overføre', options: ['opføre', 'spise', 'sove'], instruction: 'Social' },
    { id: 'da3-c72', type: 'Cloze', question: 'Hvad $(\dots)$ klokken egentlig?', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Tid' },
    { id: 'da3-c73', type: 'Cloze', question: 'Bogen $(\dots)$ på min natbord.', answer: 'ligger', options: ['ligger', 'står', 'hænger'], instruction: 'Sted' },
    { id: 'da3-c74', type: 'Cloze', question: 'Jeg $(\dots)$ mig til min fødselsdag.', answer: 'glæder', options: ['glæder', 'gruer', 'hader'], instruction: 'Følelse' },
    { id: 'da3-c75', type: 'Cloze', question: 'Vi $(\dots)$ altid pænt tak.', answer: 'siger', options: ['siger', 'hører', 'glemmer'], instruction: 'Høflig' },
    { id: 'da3-c76', type: 'Cloze', question: 'Tasken $(\dots)$ alt for meget.', answer: 'vejer', options: ['vejer', 'fylder', 'er'], instruction: 'Tilstand' },
    { id: 'da3-c77', type: 'Cloze', question: 'Kan du $(\dots)$ mig med dette?', answer: 'hjælpe', options: ['hjælpe', 'fodre', 'slå'], instruction: 'Handling' },
    { id: 'da3-c78', type: 'Cloze', question: 'Det $(\dots)$ at blæse op nu.', answer: 'begynder', options: ['begynder', 'slutter', 'lader'], instruction: 'Vejr' },
    { id: 'da3-c79', type: 'Cloze', question: 'Jeg $(\dots)$ den rigtige dør.', answer: 'fandt', options: ['fandt', 'mistede', 'glemte'], instruction: 'Handling' },
    { id: 'da3-c80', type: 'Cloze', question: 'Husk at $(\dots)$ lyset bagefter.', answer: 'slukke', options: ['slukke', 'tænde', 'spise'], instruction: 'Handling' },
    { id: 'da3-c81', type: 'Cloze', question: 'Vi $(\dots)$ en tur i skoven.', answer: 'gik', options: ['gik', 'løb', 'fløj'], instruction: 'Handling' },
    { id: 'da3-c82', type: 'Cloze', question: 'Det er $(\dots)$ vejr i dag.', answer: 'flot', options: ['flot', 'trist', 'kedeligt'], instruction: 'Vejr' },
    { id: 'da3-c83', type: 'Cloze', question: 'Jeg $(\dots)$ en god ven.', answer: 'fik', options: ['fik', 'er', 'har'], instruction: 'Social' },
    { id: 'da3-c84', type: 'Cloze', question: 'Min taske $(\dots)$ på gulvet.', answer: 'ligger', options: ['ligger', 'står', 'hænger'], instruction: 'Sted' },
    { id: 'da3-c85', type: 'Cloze', question: 'Vi $(\dots)$ om fremtiden.', answer: 'drømmer', options: ['drømmer', 'husker', 'glemmer'], instruction: 'Tanke' },
    { id: 'da3-c86', type: 'Cloze', question: 'Husk at $(\dots)$ dine sko.', answer: 'binde', options: ['binde', 'spise', 'smide'], instruction: 'Handling' },
    { id: 'da3-c87', type: 'Cloze', question: 'Det $(\dots)$ at være forår.', answer: 'begynder', options: ['begynder', 'slutter', 'lader'], instruction: 'Vejr' },
    { id: 'da3-c88', type: 'Cloze', question: 'Jeg $(\dots)$ glad for dig.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Følelse' },
    { id: 'da3-c89', type: 'Cloze', question: 'Vi $(\dots)$ en film sammen.', answer: 'ser', options: ['ser', 'hører', 'smager'], instruction: 'Handling' },
    { id: 'da3-c90', type: 'Cloze', question: 'Katten $(\dots)$ mælk nu.', answer: 'drikker', options: ['drikker', 'spiser', 'sover'], instruction: 'Handling' },
    { id: 'da3-c91', type: 'Cloze', question: 'Tasken er $(\dots)$ tung.', answer: 'meget', options: ['meget', 'lidt', 'mange'], instruction: 'Mængde' },
    { id: 'da3-c92', type: 'Cloze', question: 'Husk at $(\dots)$ madpakken.', answer: 'huske', options: ['huske', 'glemme', 'spise'], instruction: 'Handling' },
    { id: 'da3-c93', type: 'Cloze', question: 'Det $(\dots)$ at regne.', answer: 'begyndte', options: ['begyndte', 'sluttede', 'skinnede'], instruction: 'Vejr' },
    { id: 'da3-c94', type: 'Cloze', question: 'Jeg $(\dots)$ mit navn.', answer: 'skriver', options: ['skriver', 'læser', 'spiser'], instruction: 'Handling' },
    { id: 'da3-c95', type: 'Cloze', question: 'Vi $(\dots)$ i klassen.', answer: 'sidder', options: ['sidder', 'står', 'løber'], instruction: 'Skole' },
    { id: 'da3-c96', type: 'Cloze', question: 'Lyset er $(\dots)$.', answer: 'tændt', options: ['tændt', 'slukket', 'blåt'], instruction: 'Tilstand' },
    { id: 'da3-c97', type: 'Cloze', question: 'Jeg $(\dots)$ træt nu.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Følelse' },
    { id: 'da3-c98', type: 'Cloze', question: 'Godnat min $(\dots)$ ven.', answer: 'kære', options: ['kære', 'dumme', 'blå'], instruction: 'Social' },
    { id: 'da3-c99', type: 'Cloze', question: 'Ses $(\dots)$ i morgen!', answer: 'vi', options: ['vi', 'du', 'jeg'], instruction: 'Social' },
    { id: 'da3-c100', type: 'Cloze', question: 'Dansk 3 er $(\dots)$!', answer: 'færdig', options: ['færdig', 'startet', 'midt'], instruction: 'Meta' },
  ],
  4: [
    { id: 'da4-c52', type: 'Cloze', question: 'Jeg $(\dots)$ meget frem til ferien.', answer: 'glæder mig', options: ['glæder mig', 'hader', 'bor'], instruction: 'Følelse' },
    { id: 'da4-c53', type: 'Cloze', question: 'Min ven $(\dots)$ altid med mig.', answer: 'leger', options: ['leger', 'sover', 'spiser'], instruction: 'Social' },
    { id: 'da4-c54', type: 'Cloze', question: 'Vi $(\dots)$ opgaverne i skolen.', answer: 'løser', options: ['løser', 'spiser', 'drikker'], instruction: 'Handling' },
    { id: 'da4-c55', type: 'Cloze', question: 'Hunden $(\dots)$ glad når jeg kommer hjem.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Tilstand' },
    { id: 'da4-c56', type: 'Cloze', question: 'I går $(\dots)$ vi en lang tur.', answer: 'gik', options: ['gik', 'løb', 'sov'], instruction: 'Datid' },
    { id: 'da4-c57', type: 'Cloze', question: 'Min mor $(\dots)$ til aftensmad i dag.', answer: 'laver', options: ['laver', 'spiser', 'sover'], instruction: 'Handling' },
    { id: 'da4-c58', type: 'Cloze', question: 'Vi $(\dots)$ til koncert på fredag.', answer: 'skal', options: ['skal', 'var', 'er'], instruction: 'Fremtid' },
    { id: 'da4-c59', type: 'Cloze', question: 'Barnet $(\dots)$ fordi det var bange.', answer: 'råbte', options: ['råbte', 'hviskede', 'sov'], instruction: 'Følelse' },
    { id: 'da4-c60', type: 'Cloze', question: 'Solen $(\dots)$ meget kraftigt i dag.', answer: 'skinner', options: ['skinner', 'regner', 'blæser'], instruction: 'Vejr' },
    { id: 'da4-c61', type: 'Cloze', question: 'Jeg $(\dots)$ mine lektier med det samme.', answer: 'laver', options: ['laver', 'glemmer', 'spiser'], instruction: 'Handling' },
    { id: 'da4-c62', type: 'Cloze', question: 'Husk at $(\dots)$ vinduet før du går.', answer: 'lukke', options: ['lukke', 'åbne', 'smide'], instruction: 'Handling' },
    { id: 'da4-c63', type: 'Cloze', question: 'Katten $(\dots)$ i solen hele dagen.', answer: 'lå', options: ['lå', 'løb', 'sang'], instruction: 'Datid' },
    { id: 'da4-c64', type: 'Cloze', question: 'Vi $(\dots)$ en ny sang i skolen.', answer: 'lærte', options: ['lærte', 'glemte', 'spiste'], instruction: 'Tid' },
    { id: 'da4-c65', type: 'Cloze', question: 'Det er $(\dots)$ at hjælpe andre.', answer: 'vigtigt', options: ['vigtigt', 'dumt', 'skidt'], instruction: 'Mening' },
    { id: 'da4-c66', type: 'Cloze', question: 'Bilen $(\dots)$ mærkeligt i morges.', answer: 'lød', options: ['lød', 'så', 'smagte'], instruction: 'Datid' },
    { id: 'da4-c67', type: 'Cloze', question: 'Jeg $(\dots)$ min far med haven.', answer: 'hjælper', options: ['hjælper', 'fodrer', 'slår'], instruction: 'Handling' },
    { id: 'da4-c68', type: 'Cloze', question: 'Blomsterne $(\dots)$ smukt lige nu.', answer: 'blomstrer', options: ['blomstrer', 'visner', 'sover'], instruction: 'Tilstand' },
    { id: 'da4-c69', type: 'Cloze', question: 'Maden $(\dots)$ helt fantastisk.', answer: 'smagte', options: ['smagte', 'hørte', 'så'], instruction: 'Sans' },
    { id: 'da4-c70', type: 'Cloze', question: 'Vi $(\dots)$ hej til alle vi møder.', answer: 'siger', options: ['siger', 'hører', 'spiser'], instruction: 'Social' },
    { id: 'da4-c71', type: 'Cloze', question: 'Det er vigtigt at $(\dots)$ pænt.', answer: 'tale', options: ['tale', 'råbe', 'skubbe'], instruction: 'Social' },
    { id: 'da4-c72', type: 'Cloze', question: 'Hvad $(\dots)$ vi egentlig i dag?', answer: 'skal', options: ['skal', 'var', 'er'], instruction: 'Tid' },
    { id: 'da4-c73', type: 'Cloze', question: 'Bogen $(\dots)$ i min taske.', answer: 'ligger', options: ['ligger', 'står', 'hænger'], instruction: 'Sted' },
    { id: 'da4-c74', type: 'Cloze', question: 'Jeg $(\dots)$ mig til festen i aften.', answer: 'glæder', options: ['glæder', 'gruer', 'hader'], instruction: 'Følelse' },
    { id: 'da4-c75', type: 'Cloze', question: 'Vi $(\dots)$ altid mælk til kagen.', answer: 'drikker', options: ['drikker', 'spiser', 'læser'], instruction: 'Handling' },
    { id: 'da4-c76', type: 'Cloze', question: 'Tasken $(\dots)$ næsten ingenting.', answer: 'vejer', options: ['vejer', 'fylder', 'er'], instruction: 'Tilstand' },
    { id: 'da4-c77', type: 'Cloze', question: 'Kan du $(\dots)$ mig med dette?', answer: 'hjælpe', options: ['hjælpe', 'fodre', 'slå'], instruction: 'Handling' },
    { id: 'da4-c78', type: 'Cloze', question: 'Det $(\dots)$ at regne igen.', answer: 'begynder', options: ['begynder', 'slutter', 'lader'], instruction: 'Vejr' },
    { id: 'da4-c79', type: 'Cloze', question: 'Jeg $(\dots)$ den rigtige vej.', answer: 'fandt', options: ['fandt', 'mistede', 'glemte'], instruction: 'Handling' },
    { id: 'da4-c80', type: 'Cloze', question: 'Husk at $(\dots)$ for maden.', answer: 'betale', options: ['betale', 'spise', 'smide'], instruction: 'Handling' },
    { id: 'da4-c81', type: 'Cloze', question: 'Vi $(\dots)$ en tur i parken.', answer: 'gik', options: ['gik', 'løb', 'sov'], instruction: 'Handling' },
    { id: 'da4-c82', type: 'Cloze', question: 'Det er $(\dots)$ vejr i dag.', answer: 'flot', options: ['flot', 'trist', 'kedeligt'], instruction: 'Vejr' },
    { id: 'da4-c83', type: 'Cloze', question: 'Jeg $(\dots)$ en ny opgave.', answer: 'fik', options: ['fik', 'er', 'har'], instruction: 'Handling' },
    { id: 'da4-c84', type: 'Cloze', question: 'Min taske $(\dots)$ på stolen.', answer: 'ligger', options: ['ligger', 'står', 'hænger'], instruction: 'Sted' },
    { id: 'da4-c85', type: 'Cloze', question: 'Vi $(\dots)$ om ferien.', answer: 'taler', options: ['taler', 'sover', 'spiser'], instruction: 'Social' },
    { id: 'da4-c86', type: 'Cloze', question: 'Husk at $(\dots)$ dine hænder.', answer: 'vaske', options: ['vaske', 'spise', 'smide'], instruction: 'Handling' },
    { id: 'da4-c87', type: 'Cloze', question: 'Det $(\dots)$ at blive koldt.', answer: 'begynder', options: ['begynder', 'slutter', 'lader'], instruction: 'Vejr' },
    { id: 'da4-c88', type: 'Cloze', question: 'Jeg $(\dots)$ mæt nu.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Tilstand' },
    { id: 'da4-c89', type: 'Cloze', question: 'Vi $(\dots)$ en film sammen.', answer: 'ser', options: ['ser', 'hører', 'smager'], instruction: 'Handling' },
    { id: 'da4-c90', type: 'Cloze', question: 'Katten $(\dots)$ mælk nu.', answer: 'drikker', options: ['drikker', 'spiser', 'sover'], instruction: 'Handling' },
    { id: 'da4-c91', type: 'Cloze', question: 'Tasken er $(\dots)$ tung.', answer: 'meget', options: ['meget', 'lidt', 'mange'], instruction: 'Mængde' },
    { id: 'da4-c92', type: 'Cloze', question: 'Husk at $(\dots)$ madpakken.', answer: 'huske', options: ['huske', 'glemme', 'spise'], instruction: 'Handling' },
    { id: 'da4-c93', type: 'Cloze', question: 'Det $(\dots)$ at regne.', answer: 'begyndte', options: ['begyndte', 'sluttede', 'skinnede'], instruction: 'Vejr' },
    { id: 'da4-c94', type: 'Cloze', question: 'Jeg $(\dots)$ mit navn.', answer: 'skriver', options: ['skriver', 'læser', 'spiser'], instruction: 'Handling' },
    { id: 'da4-c95', type: 'Cloze', question: 'Vi $(\dots)$ i klassen.', answer: 'sidder', options: ['sidder', 'står', 'løber'], instruction: 'Skole' },
    { id: 'da4-c96', type: 'Cloze', question: 'Lyset er $(\dots)$.', answer: 'tændt', options: ['tændt', 'slukket', 'blåt'], instruction: 'Tilstand' },
    { id: 'da4-c97', type: 'Cloze', question: 'Jeg $(\dots)$ træt nu.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Følelse' },
    { id: 'da4-c98', type: 'Cloze', question: 'Godnat min $(\dots)$ ven.', answer: 'bedste', options: ['bedste', 'dumme', 'blå'], instruction: 'Social' },
    { id: 'da4-c99', type: 'Cloze', question: 'Ses $(\dots)$ i morgen!', answer: 'vi', options: ['vi', 'du', 'jeg'], instruction: 'Social' },
    { id: 'da4-c100', type: 'Cloze', question: 'Dansk 4 er $(\dots)$!', answer: 'slut', options: ['slut', 'start', 'midt'], instruction: 'Meta' },
  ],
  5: [
    { id: 'da5-c52', type: 'Cloze', question: 'Astronauten $(\dots)$ ud i rummet.', answer: 'kiggede', options: ['kiggede', 'spiste', 'sov'], instruction: 'Videnskab' },
    { id: 'da5-c53', type: 'Cloze', question: 'Vulkanen $(\dots)$ aske og røg.', answer: 'udspyede', options: ['udspyede', 'sang', 'sov'], instruction: 'Natur' },
    { id: 'da5-c54', type: 'Cloze', question: 'Jorden $(\dots)$ om sin egen akse.', answer: 'drejer', options: ['drejer', 'står', 'hænger'], instruction: 'Videnskab' },
    { id: 'da5-c55', type: 'Cloze', question: 'Månen $(\dots)$ ikke sit eget lys.', answer: 'har', options: ['har', 'er', 'kan'], instruction: 'Videnskab' },
    { id: 'da5-c56', type: 'Cloze', question: 'Planterne $(\dots)$ vand fra jorden.', answer: 'suger', options: ['suger', 'giver', 'mister'], instruction: 'Biologi' },
    { id: 'da5-c57', type: 'Cloze', question: 'Mennesket $(\dots)$ mad for at få energi.', answer: 'bruger', options: ['bruger', 'glemmer', 'taber'], instruction: 'Biologi' },
    { id: 'da5-c58', type: 'Cloze', question: 'Hjertet $(\dots)$ hele tiden.', answer: 'slår', options: ['slår', 'sover', 'spiser'], instruction: 'Biologi' },
    { id: 'da5-c59', type: 'Cloze', question: 'Hjernen $(\dots)$ mange informationer.', answer: 'modtager', options: ['modtager', 'mister', 'taber'], instruction: 'Biologi' },
    { id: 'da5-c60', type: 'Cloze', question: 'Skelettet $(\dots)$ organerne.', answer: 'beskytter', options: ['beskytter', 'spiser', 'slår'], instruction: 'Biologi' },
    { id: 'da5-c61', type: 'Cloze', question: 'Musklerne $(\dots)$ sig sammen når vi bevæger os.', answer: 'trækker', options: ['trækker', 'skubber', 'giver'], instruction: 'Biologi' },
    { id: 'da5-c62', type: 'Cloze', question: 'Maden $(\dots)$ i maven.', answer: 'nedbrydes', options: ['nedbrydes', 'bygges', 'sover'], instruction: 'Biologi' },
    { id: 'da5-c63', type: 'Cloze', question: 'Blodet $(\dots)$ ilt til cellerne.', answer: 'fører', options: ['fører', 'henter', 'fjerner'], instruction: 'Biologi' },
    { id: 'da5-c64', type: 'Cloze', question: 'Vi $(\dots)$ med vores næse.', answer: 'lugter', options: ['lugter', 'smager', 'ser'], instruction: 'Sanser' },
    { id: 'da5-c65', type: 'Cloze', question: 'Vi $(\dots)$ forskel på sødt og surt.', answer: 'kan smage', options: ['kan smage', 'ser', 'hører'], instruction: 'Sanser' },
    { id: 'da5-c66', type: 'Cloze', question: 'Vi $(\dots)$ lyde med ørerne.', answer: 'opfatter', options: ['opfatter', 'smager', 'lugter'], instruction: 'Sanser' },
    { id: 'da5-c67', type: 'Cloze', question: 'Vi $(\dots)$ farver med øjnene.', answer: 'ser', options: ['ser', 'hører', 'smager'], instruction: 'Sanser' },
    { id: 'da5-c68', type: 'Cloze', question: 'Vi $(\dots)$ varme med huden.', answer: 'føler', options: ['føler', 'ser', 'hører'], instruction: 'Sanser' },
    { id: 'da5-c69', type: 'Cloze', question: 'Det er $(\dots)$ at få frugt og grønt.', answer: 'sundt', options: ['sundt', 'usundt', 'blåt'], instruction: 'Sundhed' },
    { id: 'da5-c70', type: 'Cloze', question: 'Motion $(\dots)$ humøret.', answer: 'forbedrer', options: ['forbedrer', 'ødelægger', 'fjerner'], instruction: 'Sundhed' },
    { id: 'da5-c71', type: 'Cloze', question: 'Søvn $(\dots)$ os energi.', answer: 'giver', options: ['giver', 'tager', 'fjerner'], instruction: 'Sundhed' },
    { id: 'da5-c72', type: 'Cloze', question: 'Tænderne skal $(\dots)$ hver dag.', answer: 'børstes', options: ['børstes', 'vaskes', 'spises'], instruction: 'Sundhed' },
    { id: 'da5-c73', type: 'Cloze', question: 'Vi $(\dots)$ hænder for at undgå smitte.', answer: 'vasker', options: ['vasker', 'spiser', 'drikker'], instruction: 'Sundhed' },
    { id: 'da5-c74', type: 'Cloze', question: 'Vand $(\dots)$ tørsten bedst.', answer: 'slukker', options: ['slukker', 'skaber', 'øger'], instruction: 'Sundhed' },
    { id: 'da5-c75', type: 'Cloze', question: 'Frisk luft $(\dots)$ hovedet.', answer: 'renser', options: ['renser', 'fylder', 'roder'], instruction: 'Sundhed' },
    { id: 'da5-c76', type: 'Cloze', question: 'For meget sukker $(\dots)$ tænderne.', answer: 'skader', options: ['skader', 'hjælper', 'bygger'], instruction: 'Sundhed' },
    { id: 'da5-c77', type: 'Cloze', question: 'Vi $(\dots)$ fællesskabet i klassen.', answer: 'styrker', options: ['styrker', 'ødelægger', 'fjerner'], instruction: 'Socialt' },
    { id: 'da5-c78', type: 'Cloze', question: 'Man skal $(\dots)$ pænt til alle.', answer: 'tale', options: ['tale', 'råbe', 'slå'], instruction: 'Socialt' },
    { id: 'da5-c79', type: 'Cloze', question: 'Gode venner $(\dots)$ hinanden.', answer: 'støtter', options: ['støtter', 'hader', 'slår'], instruction: 'Socialt' },
    { id: 'da5-c80', type: 'Cloze', question: 'Det $(\dots)$ at være en del af holdet.', answer: 'betyder meget', options: ['betyder meget', 'er ligegyldigt', 'er dumt'], instruction: 'Socialt' },
    { id: 'da5-c81', type: 'Cloze', question: 'Vi $(\dots)$ mobning i skolen.', answer: 'bekæmper', options: ['bekæmper', 'støtter', 'elsker'], instruction: 'Socialt' },
    { id: 'da5-c82', type: 'Cloze', question: 'Vi $(\dots)$ problemerne ved at snakke.', answer: 'løser', options: ['løser', 'glemmer', 'skaber'], instruction: 'Socialt' },
    { id: 'da5-c83', type: 'Cloze', question: 'Samarbejde $(\dots)$ os hurtigere i mål.', answer: 'fører', options: ['fører', 'stopper', 'vender'], instruction: 'Socialt' },
    { id: 'da5-c84', type: 'Cloze', question: 'Alle $(\dots)$ være med i fællesskabet.', answer: 'skal', options: ['skal', 'må ikke', 'aldrig'], instruction: 'Socialt' },
    { id: 'da5-c85', type: 'Cloze', question: 'Respekt $(\dots)$ os til at forstå andre.', answer: 'hjælper', options: ['hjælper', 'stopper', 'gør'], instruction: 'Socialt' },
    { id: 'da5-c86', type: 'Cloze', question: 'Empati $(\dots)$ vores relationer.', answer: 'styrker', options: ['styrker', 'fjerner', 'ødelægger'], instruction: 'Socialt' },
    { id: 'da5-c87', type: 'Cloze', question: 'Vi $(\dots)$ hinandens succes.', answer: 'fejrer', options: ['fejrer', 'hader', 'glemmer'], instruction: 'Socialt' },
    { id: 'da5-c88', type: 'Cloze', question: 'Julen $(\dots)$ os sammen i familien.', answer: 'samler', options: ['samler', 'skiller', 'fjerner'], instruction: 'Kultur' },
    { id: 'da5-c89', type: 'Cloze', question: 'Påsken $(\dots)$ med gode traditioner.', answer: 'fejres', options: ['fejres', 'glemmes', 'hades'], instruction: 'Kultur' },
    { id: 'da5-c90', type: 'Cloze', question: 'Fastelavn $(\dots)$ børnene ud.', answer: 'klæder', options: ['klæder', 'spiser', 'sover'], instruction: 'Kultur' },
    { id: 'da5-c91', type: 'Cloze', question: 'Sankt Hans $(\dots)$ sommeren i gang.', answer: 'skyder', options: ['skyder', 'stopper', 'flytter'], instruction: 'Kultur' },
    { id: 'da5-c92', type: 'Cloze', question: 'Grundlovsdag $(\dots)$ vores demokrati.', answer: 'markerer', options: ['markerer', 'fjerner', 'glemmer'], instruction: 'Kultur' },
    { id: 'da5-c93', type: 'Cloze', question: 'Dannebrog $(\dots)$ i vinden.', answer: 'vejrer', options: ['vejrer', 'sover', 'spiser'], instruction: 'Kultur' },
    { id: 'da5-c94', type: 'Cloze', question: 'Statsministeren $(\dots)$ en tale.', answer: 'holder', options: ['holder', 'spiser', 'sover'], instruction: 'Samfund' },
    { id: 'da5-c95', type: 'Cloze', question: 'Kongen $(\dots)$ landet ved festlige lejligheder.', answer: 'repræsenterer', options: ['repræsenterer', 'bygger', 'spiser'], instruction: 'Samfund' },
    { id: 'da5-c96', type: 'Cloze', question: 'Folketinget $(\dots)$ lovene.', answer: 'vedtager', options: ['vedtager', 'glemmer', 'mister'], instruction: 'Samfund' },
    { id: 'da5-c97', type: 'Cloze', question: 'Demokrati $(\dots)$ at vi alle har en stemme.', answer: 'betyder', options: ['betyder', 'fjerner', 'glemmer'], instruction: 'Samfund' },
    { id: 'da5-c98', type: 'Cloze', question: 'Ytringsfrihed $(\dots)$ os ret til at tale frit.', answer: 'giver', options: ['giver', 'tager', 'fjerner'], instruction: 'Samfund' },
    { id: 'da5-c99', type: 'Cloze', question: 'Lighed $(\dots)$ at alle får de samme muligheder.', answer: 'sikrer', options: ['sikrer', 'fjerner', 'stopper'], instruction: 'Samfund' },
    { id: 'da5-c100', type: 'Cloze', question: 'Dansk 5 er $(\dots)$!', answer: 'Færdig', options: ['Færdig', 'Starte', 'Midt'], instruction: 'Meta' },
  ],
  6: [
    { id: 'da6-c52', type: 'Cloze', question: 'Forfatteren $(\dots)$ læseren med ind i historien.', answer: 'drager', options: ['drager', 'smider', 'spiser'], instruction: 'Litteratur' },
    { id: 'da6-c53', type: 'Cloze', question: 'Hovedpersonen $(\dots)$ meget undervejs.', answer: 'lærer', options: ['lærer', 'glemmer', 'mister'], instruction: 'Analyse' },
    { id: 'da6-c54', type: 'Cloze', question: 'Handlingen $(\dots)$ i en mørk skov.', answer: 'foregår', options: ['foregår', 'stopper', 'starter'], instruction: 'Analyse' },
    { id: 'da6-c55', type: 'Cloze', question: 'Budskabet $(\dots)$ os til at tænke os om.', answer: 'får', options: ['får', 'glemmer', 'minder'], instruction: 'Analyse' },
    { id: 'da6-c56', type: 'Cloze', question: 'Digteren $(\dots)$ fine ord.', answer: 'bruger', options: ['bruger', 'spiser', 'sover'], instruction: 'Poesi' },
    { id: 'da6-c57', type: 'Cloze', question: 'Novellen $(\dots)$ meget pludseligt.', answer: 'slutter', options: ['slutter', 'starter', 'varer'], instruction: 'Genre' },
    { id: 'da6-c58', type: 'Cloze', question: 'Eventyr $(\dots)$ ofte med en lykkelig slutning.', answer: 'ender', options: ['ender', 'starter', 'midt'], instruction: 'Genre' },
    { id: 'da6-c59', type: 'Cloze', question: 'Fabelen $(\dots)$ os en vigtig lektie.', answer: 'giver', options: ['giver', 'tager', 'glemmer'], instruction: 'Genre' },
    { id: 'da6-c60', type: 'Cloze', question: 'Romanen $(\dots)$ over mange sider.', answer: 'strækker sig', options: ['strækker sig', 'stopper', 'gik'], instruction: 'Litteratur' },
    { id: 'da6-c61', type: 'Cloze', question: 'Historien $(\dots)$ fra barnets synsvinkel.', answer: 'fortælles', options: ['fortælles', 'glemmes', 'tabes'], instruction: 'Analyse' },
    { id: 'da6-c62', type: 'Cloze', question: 'Vi $(\dots)$ tekstens mange lag.', answer: 'undersøger', options: ['undersøger', 'spiser', 'slår'], instruction: 'Analyse' },
    { id: 'da6-c63', type: 'Cloze', question: 'Temaet $(\dots)$ sig gennem hele bogen.', answer: 'gentager', options: ['gentager', 'stopper', 'fjerner'], instruction: 'Analyse' },
    { id: 'da6-c64', type: 'Cloze', question: 'Sproget $(\dots)$ en helt særlig stemning.', answer: 'skaber', options: ['skaber', 'ødelægger', 'fjerner'], instruction: 'Analyse' },
    { id: 'da6-c65', type: 'Cloze', question: 'Vi $(\dots)$ personerne i teksten.', answer: 'følger', options: ['følger', 'overhaler', 'glemmer'], instruction: 'Analyse' },
    { id: 'da6-c66', type: 'Cloze', question: 'Miljøbeskrivelsen $(\dots)$ os til at forstå tiden.', answer: 'hjælper', options: ['hjælper', 'stopper', 'fjerner'], instruction: 'Analyse' },
    { id: 'da6-c67', type: 'Cloze', question: 'Konflikten $(\dots)$ mere og mere.', answer: 'vokser', options: ['vokser', 'svinder', 'stopper'], instruction: 'Analyse' },
    { id: 'da6-c68', type: 'Cloze', question: 'Vendepunktet $(\dots)$ alting på hovedet.', answer: 'vender', options: ['vender', 'lader', 'ser'], instruction: 'Analyse' },
    { id: 'da6-c69', type: 'Cloze', question: 'Afslutningen $(\dots)$ alle løse ender.', answer: 'samler', options: ['samler', 'skiller', 'fjerner'], instruction: 'Analyse' },
    { id: 'da6-c70', type: 'Cloze', question: 'Vi $(\dots)$ ordklasser i grammatik.', answer: 'lærer', options: ['lærer', 'glemmer', 'spiser'], instruction: 'Sprog' },
    { id: 'da6-c71', type: 'Cloze', question: 'Et navneord $(\dots)$ en genstand eller person.', answer: 'betegner', options: ['betegner', 'spiser', 'danser'], instruction: 'Grammatik' },
    { id: 'da6-c72', type: 'Cloze', question: 'Et udsagnsord $(\dots)$ om tid og handling.', answer: 'fortæller', options: ['fortæller', 'glemmer', 'mister'], instruction: 'Grammatik' },
    { id: 'da6-c73', type: 'Cloze', question: 'Et tillægsord $(\dots)$ os noget om navneordet.', answer: 'fortæller', options: ['fortæller', 'fjerner', 'ødelægger'], instruction: 'Grammatik' },
    { id: 'da6-c74', type: 'Cloze', question: 'Biord $(\dots)$ udsagnsordet nærmere.', answer: 'beskriver', options: ['beskriver', 'fjerner', 'stopper'], instruction: 'Grammatik' },
    { id: 'da6-c75', type: 'Cloze', question: 'Forholdsord $(\dots)$ hvor noget er placeret.', answer: 'viser', options: ['viser', 'skjuler', 'fjerner'], instruction: 'Grammatik' },
    { id: 'da6-c76', type: 'Cloze', question: 'Stedord $(\dots)$ for navneordet.', answer: 'står i stedet', options: ['står i stedet', 'løber', 'flyver'], instruction: 'Grammatik' },
    { id: 'da6-c77', type: 'Cloze', question: 'Bindeord $(\dots)$ sætningsdele sammen.', answer: 'knytter', options: ['knytter', 'skiller', 'fjerner'], instruction: 'Grammatik' },
    { id: 'da6-c78', type: 'Cloze', question: 'Udråbsord $(\dots)$ stærke reaktioner.', answer: 'udtrykker', options: ['udtrykker', 'gemmer', 'fjerner'], instruction: 'Grammatik' },
    { id: 'da6-c79', type: 'Cloze', question: 'Vi $(\dots)$ komma for at gøre teksten læselig.', answer: 'bruger', options: ['bruger', 'glemmer', 'spiser'], instruction: 'Grammatik' },
    { id: 'da6-c80', type: 'Cloze', question: 'Punktum $(\dots)$ en hel tanke.', answer: 'afslutter', options: ['afslutter', 'starter', 'midt'], instruction: 'Grammatik' },
    { id: 'da6-c81', type: 'Cloze', question: 'Spørgsmålstegn $(\dots)$ at vi søger svar.', answer: 'viser', options: ['viser', 'skjuler', 'fjerner'], instruction: 'Grammatik' },
    { id: 'da6-c82', type: 'Cloze', question: 'Udråbstegn $(\dots)$ opmærksomhed.', answer: 'kræver', options: ['kræver', 'glemmer', 'fjerner'], instruction: 'Grammatik' },
    { id: 'da6-c83', type: 'Cloze', question: 'Vi $(\dots)$ kendskab til litteraturhistorien.', answer: 'får', options: ['får', 'taber', 'mister'], instruction: 'Litteratur' },
    { id: 'da6-c84', type: 'Cloze', question: 'H.C. Andersen $(\dots)$ ud i hele verden.', answer: 'nåede', options: ['nåede', 'gik', 'sov'], instruction: 'Litteratur' },
    { id: 'da6-c85', type: 'Cloze', question: 'Karen Blixen $(\dots)$ manges hjerter.', answer: 'rørte', options: ['rørte', 'spiste', 'slog'], instruction: 'Litteratur' },
    { id: 'da6-c86', type: 'Cloze', question: 'Tove Ditlevsen $(\dots)$ ærligt om sit liv.', answer: 'skrev', options: ['skrev', 'sang', 'sov'], instruction: 'Litteratur' },
    { id: 'da6-c87', type: 'Cloze', question: 'Dan Turell $(\dots)$ vores måde at se byen på.', answer: 'ændrede', options: ['ændrede', 'bevarede', 'glemte'], instruction: 'Litteratur' },
    { id: 'da6-c88', type: 'Cloze', question: 'Klaus Rifbjerg $(\dots)$ mange genrer.', answer: 'mestrede', options: ['mestrede', 'opgav', 'lærte'], instruction: 'Litteratur' },
    { id: 'da6-c89', type: 'Cloze', question: 'Vi $(\dots)$ på nyheder hver dag.', answer: 'ser', options: ['ser', 'spiser', 'hører'], instruction: 'Medier' },
    { id: 'da6-c90', type: 'Cloze', question: 'En artikel $(\dots)$ os vigtig info.', answer: 'giver', options: ['giver', 'tager', 'fjerner'], instruction: 'Journalistik' },
    { id: 'da6-c91', type: 'Cloze', question: 'Journalisten $(\dots)$ sandheden frem.', answer: 'bringer', options: ['bringer', 'gemmer', 'stopper'], instruction: 'Journalistik' },
    { id: 'da6-c92', type: 'Cloze', question: 'Nyhedssproget $(\dots)$ være klart.', answer: 'skal', options: ['skal', 'må ikke', 'aldrig'], instruction: 'Journalistik' },
    { id: 'da6-c93', type: 'Cloze', question: 'Lederen $(\dots)$ avisens holdning.', answer: 'udtrykker', options: ['udtrykker', 'skjuler', 'glemmer'], instruction: 'Journalistik' },
    { id: 'da6-c94', type: 'Cloze', question: 'Læserbrevet $(\dots)$ en debat.', answer: 'starter', options: ['starter', 'slutter', 'stopper'], instruction: 'Journalistik' },
    { id: 'da6-c95', type: 'Cloze', question: 'Anmeldelsen $(\dots)$ hvad vi skal se.', answer: 'anbefaler', options: ['anbefaler', 'forbyder', 'glemmer'], instruction: 'Journalistik' },
    { id: 'da6-c96', type: 'Cloze', question: 'Reportagen $(\dots)$ os med på stedet.', answer: 'tager', options: ['tager', 'afviser', 'glemmer'], instruction: 'Journalistik' },
    { id: 'da6-c97', type: 'Cloze', question: 'Layoutet $(\dots)$ læsevenligheden.', answer: 'øger', options: ['øger', 'mindsker', 'fjerner'], instruction: 'Journalistik' },
    { id: 'da6-c98', type: 'Cloze', question: 'Billederne $(\dots)$ ordene.', answer: 'supplerer', options: ['supplerer', 'ødelægger', 'modvder'], instruction: 'Journalistik' },
    { id: 'da6-c99', type: 'Cloze', question: 'Vi $(\dots)$ kildekritik hver dag.', answer: 'bruger', options: ['bruger', 'glemmer', 'spiser'], instruction: 'Journalistik' },
    { id: 'da6-c100', type: 'Cloze', question: 'Dansk 6 er $(\dots)$!', answer: 'Done', options: ['Done', 'Start', 'Nu'], instruction: 'Meta' },
  ],
  7: [
    { id: 'da7-c52', type: 'Cloze', question: 'Idéhistorien $(\dots)$ os i fortiden.', answer: 'rødder', options: ['rødder', 'huse', 'penge'], instruction: 'Filosofi' },
    { id: 'da7-c53', type: 'Cloze', question: 'Filosoffer $(\dots)$ altid nye veje.', answer: 'søger', options: ['søger', 'finder', 'stopper'], instruction: 'Filosofi' },
    { id: 'da7-c54', type: 'Cloze', question: 'Etikken $(\dots)$ vores valg.', answer: 'styrer', options: ['styrer', 'glemmer', 'mister'], instruction: 'Filosofi' },
    { id: 'da7-c55', type: 'Cloze', question: 'Moralen $(\dots)$ os hvordan vi skal leve.', answer: 'viser', options: ['viser', 'skjuler', 'spørger'], instruction: 'Filosofi' },
    { id: 'da7-c56', type: 'Cloze', question: 'Eksistens $(\dots)$ menneskets grundvilkår.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Filosofi' },
    { id: 'da7-c57', type: 'Cloze', question: 'Frihed $(\dots)$ modet til at vælge.', answer: 'kræver', options: ['kræver', 'fjerner', 'stopper'], instruction: 'Filosofi' },
    { id: 'da7-c58', type: 'Cloze', question: 'Sandheden $(\dots)$ svær at finde.', answer: 'kan være', options: ['kan være', 'er altid', 'er aldrig'], instruction: 'Filosofi' },
    { id: 'da7-c59', type: 'Cloze', question: 'Retorikken $(\dots)$ vores sprog.', answer: 'farver', options: ['farver', 'renser', 'fjerner'], instruction: 'Argumentation' },
    { id: 'da7-c60', type: 'Cloze', question: 'Argumentet $(\dots)$ modtageren.', answer: 'overbeviser', options: ['overbeviser', 'skræmmer', 'glemmer'], instruction: 'Argumentation' },
    { id: 'da7-c61', type: 'Cloze', question: 'Påstanden $(\dots)$ bevises.', answer: 'skal', options: ['skal', 'må ikke', 'aldrig'], instruction: 'Argumentation' },
    { id: 'da7-c62', type: 'Cloze', question: 'Gendrivelsen $(\dots)$ modstanderen.', answer: 'stopper', options: ['stopper', 'hjælper', 'fodrer'], instruction: 'Argumentation' },
    { id: 'da7-c63', type: 'Cloze', question: 'Bedre vidende $(\dots)$ altid debatten.', answer: 'vinder', options: ['vinder', 'taber', 'stopper'], instruction: 'Argumentation' },
    { id: 'da7-c64', type: 'Cloze', question: 'Saglighed $(\dots)$ diskussionen lødig.', answer: 'gør', options: ['gør', 'fjerner', 'ødelægger'], instruction: 'Argumentation' },
    { id: 'da7-c65', type: 'Cloze', question: 'Afsenderen $(\dots)$ sit budskab tydeligt.', answer: 'sender', options: ['sender', 'gemmer', 'glemmer'], instruction: 'Argumentation' },
    { id: 'da7-c66', type: 'Cloze', question: 'Manipulation $(\dots)$ dagsordenen.', answer: 'skifter', options: ['skifter', 'bevarer', 'stopper'], instruction: 'Argumentation' },
    { id: 'da7-c67', type: 'Cloze', question: 'Virkemidlerne $(\dots)$ teksten levende.', answer: 'gør', options: ['gør', 'fjerner', 'stopper'], instruction: 'Argumentation' },
    { id: 'da7-c68', type: 'Cloze', question: 'Etos $(\dots)$ talerens fundament.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Retorik' },
    { id: 'da7-c69', type: 'Cloze', question: 'Logos $(\dots)$ på hårde facts.', answer: 'bygger', options: ['bygger', 'falder', 'stopper'], instruction: 'Retorik' },
    { id: 'da7-c70', type: 'Cloze', question: 'Patos $(\dots)$ i vores følelser.', answer: 'rører', options: ['rører', 'spiser', 'slår'], instruction: 'Retorik' },
    { id: 'da7-c71', type: 'Cloze', question: 'Metaforer $(\dots)$ sproget billedligt.', answer: 'gør', options: ['gør', 'fjerner', 'stopper'], instruction: 'Sprog' },
    { id: 'da7-c72', type: 'Cloze', question: 'Personificering $(\dots)$ tingene liv.', answer: 'giver', options: ['giver', 'tager', 'fjerner'], instruction: 'Sprog' },
    { id: 'da7-c73', type: 'Cloze', question: 'Ironien $(\dots)$ en skarp kant.', answer: 'giver', options: ['giver', 'tager', 'fjerner'], instruction: 'Sprog' },
    { id: 'da7-c74', type: 'Cloze', question: 'Sarkasmen $(\dots)$ ofte modtageren.', answer: 'rammer', options: ['rammer', 'misser', 'hjælper'], instruction: 'Sprog' },
    { id: 'da7-c75', type: 'Cloze', question: 'Underdrivelsen $(\dots)$ voldsomheden.', answer: 'fjerner', options: ['fjerner', 'øger', 'bevarer'], instruction: 'Sprog' },
    { id: 'da7-c76', type: 'Cloze', question: 'Overdrivelsen $(\dots)$ opmærksomheden.', answer: 'fanger', options: ['fanger', 'mister', 'glemmer'], instruction: 'Sprog' },
    { id: 'da7-c77', type: 'Cloze', question: 'Den komplekse opbygning $(\dots)$ læseren.', answer: 'udfordrer', options: ['udfordrer', 'sover', 'spiser'], instruction: 'Analyse' },
    { id: 'da7-c78', type: 'Cloze', question: 'Virkeligheden $(\dots)$ i litteraturen.', answer: 'spejles', options: ['spejles', 'gemmes', 'tabes'], instruction: 'Litteratur' },
    { id: 'da7-c79', type: 'Cloze', question: 'Symbolerne $(\dots)$ til en dybere mening.', answer: 'viser vej', options: ['viser vej', 'stopper', 'glemmer'], instruction: 'Analyse' },
    { id: 'da7-c80', type: 'Cloze', question: 'Fortolkningen $(\dots)$ mange muligheder.', answer: 'åbner', options: ['åbner', 'lukker', 'stopper'], instruction: 'Analyse' },
    { id: 'da7-c81', type: 'Cloze', question: 'Intertekstualitet $(\dots)$ broer mellem værker.', answer: 'bygger', options: ['bygger', 'fjerner', 'ødelægger'], instruction: 'Analyse' },
    { id: 'da7-c82', type: 'Cloze', question: 'Idealerne $(\dots)$ gennem tiden.', answer: 'skifter', options: ['skifter', 'står fast', 'forsvinder'], instruction: 'Litteratur' },
    { id: 'da7-c83', type: 'Cloze', question: 'Følelserne $(\dots)$ i romantikken.', answer: 'dominerede', options: ['dominerede', 'forsvandt', 'sov'], instruction: 'Litteratur' },
    { id: 'da7-c84', type: 'Cloze', question: 'Problemerne $(\dots)$ debat.', answer: 'skaber', options: ['skaber', 'stopper', 'fjerner'], instruction: 'Litteratur' },
    { id: 'da7-c85', type: 'Cloze', question: 'Realisme $(\dots)$ verden som den er.', answer: 'viser', options: ['viser', 'skjuler', 'pynter'], instruction: 'Litteratur' },
    { id: 'da7-c86', type: 'Cloze', question: 'Central $(\dots)$ i historien er ofte ukendt.', answer: 'viden', options: ['viden', 'tal', 'sko'], instruction: 'Litteratur' },
    { id: 'da7-c87', type: 'Cloze', question: 'Skæbnen $(\dots)$ os mange veje.', answer: 'fører', options: ['fører', 'stopper', 'vender'], instruction: 'Litteratur' },
    { id: 'da7-c88', type: 'Cloze', question: 'Stilen $(\dots)$ forfatterens særtræk.', answer: 'viser', options: ['viser', 'skjuler', 'glemmer'], instruction: 'Litteratur' },
    { id: 'da7-c89', type: 'Cloze', question: 'Stilistikken $(\dots)$ i analysen.', answer: 'bruges', options: ['bruges', 'spises', 'glemmes'], instruction: 'Analyse' },
    { id: 'da7-c90', type: 'Cloze', question: 'Synsvinklen $(\dots)$ læserens oplevelse.', answer: 'styrer', options: ['styrer', 'ødelægger', 'fjerner'], instruction: 'Analyse' },
    { id: 'da7-c91', type: 'Cloze', question: 'Pålideligheden $(\dots)$ for vores tillid.', answer: 'betyder meget', options: ['betyder meget', 'er ligegyldig', 'er dum'], instruction: 'Analyse' },
    { id: 'da7-c92', type: 'Cloze', question: 'Handlinger $(\dots)$ os om personerne.', answer: 'fortæller', options: ['fortæller', 'glemmer', 'mister'], instruction: 'Analyse' },
    { id: 'da7-c93', type: 'Cloze', question: 'Underteksten $(\dots)$ mellem linjerne.', answer: 'findes', options: ['findes', 'forsvinder', 'stopper'], instruction: 'Analyse' },
    { id: 'da7-c94', type: 'Cloze', question: 'Spændingen $(\dots)$ hele vejen igennem.', answer: 'holdes', options: ['holdes', 'tabes', 'glemmes'], instruction: 'Analyse' },
    { id: 'da7-c95', type: 'Cloze', question: 'Læsningen $(\dots)$ citaterne.', answer: 'finder', options: ['finder', 'mister', 'glemmer'], instruction: 'Analyse' },
    { id: 'da7-c96', type: 'Cloze', question: 'Analysen $(\dots)$ documentation.', answer: 'kræver', options: ['kræver', 'fjerner', 'stopper'], instruction: 'Analyse' },
    { id: 'da7-c97', type: 'Cloze', question: 'Fortolkningen $(\dots)$ bevises.', answer: 'skal', options: ['skal', 'må ikke', 'aldrig'], instruction: 'Analyse' },
    { id: 'da7-c98', type: 'Cloze', question: 'Linjerne $(\dots)$ litteraturhistorien.', answer: 'tegner', options: ['tegner', 'sletter', 'fjerner'], instruction: 'Litteratur' },
    { id: 'da7-c99', type: 'Cloze', question: 'Perioderne $(\dots)$ forskelligheder.', answer: 'viser', options: ['viser', 'skjuler', 'glemmer'], instruction: 'Litteratur' },
    { id: 'da7-c100', type: 'Cloze', question: 'Dansk 7 er $(\dots)$!', answer: 'Slut', options: ['Slut', 'Start', 'Vak'], instruction: 'Meta' },
  ],
  8: [
    { id: 'da8-c52', type: 'Cloze', question: 'Identitet $(\dots)$ sig gennem hele livet.', answer: 'udvikler', options: ['udvikler', 'stopper', 'fjerner'], instruction: 'Tema' },
    { id: 'da8-c53', type: 'Cloze', question: 'Spørgsmålet $(\dots)$ os i tanken.', answer: 'fanger', options: ['fanger', 'slipper', 'glemmer'], instruction: 'Tema' },
    { id: 'da8-c54', type: 'Cloze', question: 'Globalisering $(\dots)$ os tættere sammen.', answer: 'binder', options: ['binder', 'skiller', 'fjerner'], instruction: 'Samfund' },
    { id: 'da8-c55', type: 'Cloze', question: 'Forståelse $(\dots)$ konflikterne.', answer: 'mindsker', options: ['mindsker', 'øger', 'starter'], instruction: 'Samfund' },
    { id: 'da8-c56', type: 'Cloze', question: 'Magten $(\dots)$ hos medierne.', answer: 'ligger', options: ['ligger', 'står', 'hænger'], instruction: 'Samfund' },
    { id: 'da8-c57', type: 'Cloze', question: 'Net-adfærd $(\dots)$ vores profil.', answer: 'viser', options: ['viser', 'skjuler', 'glemmer'], instruction: 'Samfund' },
    { id: 'da8-c58', type: 'Cloze', question: 'Kildekritikken $(\dots)$ sandheden.', answer: 'finder', options: ['finder', 'skjuler', 'stopper'], instruction: 'Samfund' },
    { id: 'da8-c59', type: 'Cloze', question: 'Demokratiet $(\dots)$ af løgne.', answer: 'skades', options: ['skades', 'hjælpes', 'bygge'], instruction: 'Samfund' },
    { id: 'da8-c60', type: 'Cloze', question: 'Fællesskaberne $(\dots)$ på nettet.', answer: 'trives', options: ['trives', 'dør', 'stopper'], instruction: 'Samfund' },
    { id: 'da8-c61', type: 'Cloze', question: 'Datasikkerhed $(\dots)$ vigtigere nu.', answer: 'er blevet', options: ['er blevet', 'er forsvundet', 'er glemt'], instruction: 'Samfund' },
    { id: 'da8-c62', type: 'Cloze', question: 'Algoritmerne $(\dots)$ vores valg.', answer: 'styrer', options: ['styrer', 'fjerner', 'stopper'], instruction: 'Samfund' },
    { id: 'da8-c63', type: 'Cloze', question: 'Holdningerne $(\dots)$ i ekkokamrene.', answer: 'forstærkes', options: ['forstærkes', 'svækkes', 'forsvinder'], instruction: 'Samfund' },
    { id: 'da8-c64', type: 'Cloze', question: 'Kritisk tænkning $(\dots)$ os.', answer: 'redder', options: ['redder', 'dræber', 'fjerner'], instruction: 'Samfund' },
    { id: 'da8-c65', type: 'Cloze', question: 'Behovene $(\dots)$ af reklamerne.', answer: 'skabes', options: ['skabes', 'fjernes', 'mættes'], instruction: 'Samfund' },
    { id: 'da8-c66', type: 'Cloze', question: 'Virksomhederne $(\dots)$ deres brand.', answer: 'bygger', options: ['bygger', 'river', 'glemmer'], instruction: 'Økonomi' },
    { id: 'da8-c67', type: 'Cloze', question: 'Samfundet $(\dots)$ af forbrug.', answer: 'præges', options: ['præges', 'skånes', 'fjerner'], instruction: 'Samfund' },
    { id: 'da8-c68', type: 'Cloze', question: 'Nødvendigheden $(\dots)$ os til handling.', answer: 'tvinger', options: ['tvinger', 'beder', 'lader'], instruction: 'Miljø' },
    { id: 'da8-c69', type: 'Cloze', question: 'Handling $(\dots)$ her og nu.', answer: 'kræves', options: ['kræves', 'gives', 'får'], instruction: 'Politik' },
    { id: 'da8-c70', type: 'Cloze', question: 'Ansvar $(\dots)$ til alle.', answer: 'hører', options: ['hører', 'går', 'flyver'], instruction: 'Etik' },
    { id: 'da8-c71', type: 'Cloze', question: 'De svageste $(\dots)$ hjælpen.', answer: 'mangler', options: ['mangler', 'har', 'får'], instruction: 'Etik' },
    { id: 'da8-c72', type: 'Cloze', question: 'Grundprincippet $(\dots)$ os.', answer: 'leder', options: ['leder', 'stopper', 'vender'], instruction: 'Politik' },
    { id: 'da8-c73', type: 'Cloze', question: 'Loven $(\dots)$ alle.', answer: 'beskytter', options: ['beskytter', 'angriber', 'glemmer'], instruction: 'Politik' },
    { id: 'da8-c74', type: 'Cloze', question: 'Menneskerettighederne $(\dots)$ universelle.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Politik' },
    { id: 'da8-c75', type: 'Cloze', question: 'Borgere $(\dots)$ i samfundet.', answer: 'deltager', options: ['deltager', 'sover', 'spiser'], instruction: 'Samfund' },
    { id: 'da8-c76', type: 'Cloze', question: 'Grænserne $(\dots)$ for friheden.', answer: 'viser vej', options: ['viser vej', 'stopper', 'fjerner'], instruction: 'Lov' },
    { id: 'da8-c77', type: 'Cloze', question: 'Offentlig debat $(\dots)$ lødighed.', answer: 'kræver', options: ['kræver', 'fjerner', 'stopper'], instruction: 'Socialt' },
    { id: 'da8-c78', type: 'Cloze', question: 'Forskelligheder $(\dots)$ os.', answer: 'beriger', options: ['beriger', 'skader', 'fjerner'], instruction: 'Socialt' },
    { id: 'da8-c79', type: 'Cloze', question: 'Mennesker $(\dots)$ i solidaritet.', answer: 'står sammen', options: ['står sammen', 'går hver til sit', 'sover'], instruction: 'Socialt' },
    { id: 'da8-c80', type: 'Cloze', question: 'Uligheden $(\dots)$ bekæmpes.', answer: 'skal', options: ['skal', 'må ikke', 'aldrig'], instruction: 'Politik' },
    { id: 'da8-c81', type: 'Cloze', question: 'Fremtiden $(\dots)$ god ud.', answer: 'ser', options: ['ser', 'hører', 'sover'], instruction: 'Fremtid' },
    { id: 'da8-c82', type: 'Cloze', question: 'Mening $(\dots)$ os styrke.', answer: 'giver', options: ['giver', 'tager', 'fjerner'], instruction: 'Samfund' },
    { id: 'da8-c83', type: 'Cloze', question: 'Tryghed $(\dots)$ af velfærden.', answer: 'skabes', options: ['skabes', 'fjernes', 'stopper'], instruction: 'Økonomi' },
    { id: 'da8-c84', type: 'Cloze', question: 'Økonomien $(\dots)$ vækst.', answer: 'ønsker', options: ['ønsker', 'hader', 'frygter'], instruction: 'Økonomi' },
    { id: 'da8-c85', type: 'Cloze', question: 'Landet $(\dots)$ sig hele tiden.', answer: 'udvikler', options: ['udvikler', 'bevarer', 'stopper'], instruction: 'Økonomi' },
    { id: 'da8-c86', type: 'Cloze', question: 'Livet $(\dots)$ af teknologien.', answer: 'ændres', options: ['ændres', 'bevares', 'stoppes'], instruction: 'Technologi' },
    { id: 'da8-c87', type: 'Cloze', question: 'Udviklingen $(\dots)$ mod fremtiden.', answer: 'peger', options: ['peger', 'vender', 'stopper'], instruction: 'Videnskab' },
    { id: 'da8-c88', type: 'Cloze', question: 'Verden $(\dots)$ på ny viden.', answer: 'venter', options: ['venter', 'sover', 'spiser'], instruction: 'Videnskab' },
    { id: 'da8-c89', type: 'Cloze', question: 'Eksperimenter $(\dots)$ i laboratoriet.', answer: 'udføres', options: ['udføres', 'glemmes', 'tabes'], instruction: 'Videnskab' },
    { id: 'da8-c90', type: 'Cloze', question: 'Virkeligheden $(\dots)$ hypotesen.', answer: 'bekræfter', options: ['bekræfter', 'fjerner', 'stopper'], instruction: 'Videnskab' },
    { id: 'da8-c91', type: 'Cloze', question: 'Forskere $(\dots)$ deres resultater.', answer: 'deler', options: ['deler', 'gemmer', 'glemmer'], instruction: 'Videnskab' },
    { id: 'da8-c92', type: 'Cloze', question: 'Forskning $(\dots)$ etisk ansvar.', answer: 'kræver', options: ['kræver', 'fjerner', 'stopper'], instruction: 'Etik' },
    { id: 'da8-c93', type: 'Cloze', question: 'Valgene $(\dots)$ vores fremtid.', answer: 'former', options: ['former', 'sletter', 'stopper'], instruction: 'Tanke' },
    { id: 'da8-c94', type: 'Cloze', question: 'Historien $(\dots)$ os vigtige ting.', answer: 'lærer', options: ['lærer', 'glemmer', 'mister'], instruction: 'Tanke' },
    { id: 'da8-c95', type: 'Cloze', question: 'Erfaringen $(\dots)$ os viden.', answer: 'giver', options: ['giver', 'tager', 'fjerner'], instruction: 'Tanke' },
    { id: 'da8-c96', type: 'Cloze', question: 'Indsigt $(\dots)$ med tiden.', answer: 'kommer', options: ['kommer', 'går', 'forsvinder'], instruction: 'Tanke' },
    { id: 'da8-c97', type: 'Cloze', question: 'Ordsproget $(\dots)$ stadig i dag.', answer: 'gælder', options: ['gælder', 'fejler', 'stopper'], instruction: 'Tanke' },
    { id: 'da8-c98', type: 'Cloze', question: 'Håbet $(\dots)$ aldrig.', answer: 'dør', options: ['dør', 'vliver', 'skinner'], instruction: 'Tanke' },
    { id: 'da8-c99', type: 'Cloze', question: 'Sig selv $(\dots)$ er en rejse.', answer: 'at finde', options: ['at finde', 'at tabe', 'at glemme'], instruction: 'Tanke' },
    { id: 'da8-c100', type: 'Cloze', question: 'Dansk 8 er $(\dots)$!', answer: 'Sluuuuut', options: ['Sluuuuut', 'Nu', 'Der'], instruction: 'Meta' },
  ],
  9: [
    { id: 'da9-c52', type: 'Cloze', question: 'Valgene $(\dots)$ vores skæbne.', answer: 'styrer', options: ['styrer', 'glemmer', 'mister'], instruction: 'Filosofi' },
    { id: 'da9-c53', type: 'Cloze', question: 'Friheden $(\dots)$ et stort ansvar.', answer: 'bærer', options: ['bærer', 'fjerner', 'stopper'], instruction: 'Filosofi' },
    { id: 'da9-c54', type: 'Cloze', question: 'Meningen $(\dots)$ i livet.', answer: 'skabes', options: ['skabes', 'forsvinder', 'stopper'], instruction: 'Filosofi' },
    { id: 'da9-c55', type: 'Cloze', question: 'Verden $(\dots)$ ofte absurd.', answer: 'føles', options: ['føles', 'er altid', 'er aldrig'], instruction: 'Filosofi' },
    { id: 'da9-c56', type: 'Cloze', question: 'Acceptere $(\dots)$ er en dyd.', answer: 'det uundgåelige', options: ['det uundgåelige', 'alt', 'intet'], instruction: 'Filosofi' },
    { id: 'da9-c57', type: 'Cloze', question: 'Nydelsen $(\dots)$ i centrum.', answer: 'står', options: ['står', 'falder', 'stopper'], instruction: 'Filosofi' },
    { id: 'da9-c58', type: 'Cloze', question: 'Fornuften $(\dots)$ os sandheden.', answer: 'viser', options: ['viser', 'skjuler', 'fjerner'], instruction: 'Filosofi' },
    { id: 'da9-c59', type: 'Cloze', question: 'Erfaringen $(\dots)$ os viden.', answer: 'giver', options: ['giver', 'tager', 'fjerner'], instruction: 'Filosofi' },
    { id: 'da9-c60', type: 'Cloze', question: 'Tingene $(\dots)$ for os som de er.', answer: 'fremtræder', options: ['fremtræder', 'forsvinder', 'stopper'], instruction: 'Filosofi' },
    { id: 'da9-c61', type: 'Cloze', question: 'Væren $(\dots)$ alt der eksisterer.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Filosofi' },
    { id: 'da9-c62', type: 'Cloze', question: 'Videns $(\dots)$ er dyb.', answer: 'natur', options: ['natur', 'vægt', 'farve'], instruction: 'Filosofi' },
    { id: 'da9-c63', type: 'Cloze', question: 'Sjælen $(\dots)$ fra kroppen.', answer: 'skilles', options: ['skilles', 'samles', 'stopper'], instruction: 'Filosofi' },
    { id: 'da9-c64', type: 'Cloze', question: 'Bestemt $(\dots)$ af skæbnen.', answer: 'er vi', options: ['er vi', 'er vi ikke', 'måske'], instruction: 'Filosofi' },
    { id: 'da9-c65', type: 'Cloze', question: 'Antitesen $(\dots)$ tesen.', answer: 'modvirker', options: ['modvirker', 'støtter', 'fjerner'], instruction: 'Filosofi' },
    { id: 'da9-c66', type: 'Cloze', question: 'Fortolkning $(\dots)$ teksten.', answer: 'åbner', options: ['åbner', 'lukker', 'stopper'], instruction: 'Filosofi' },
    { id: 'da9-c67', type: 'Cloze', question: 'Almen $(\dots)$ er målet for handlingen.', answer: 'lykke', options: ['lykke', 'vrede', 'sorg'], instruction: 'Filosofi' },
    { id: 'da9-c68', type: 'Cloze', question: 'Lykke $(\dots)$ alle.', answer: 'ønskes for', options: ['ønskes for', 'tages fra', 'fjerner'], instruction: 'Filosofi' },
    { id: 'da9-c69', type: 'Cloze', question: 'Moral $(\dots)$ hos os selv.', answer: 'bor', options: ['bor', 'går', 'flyver'], instruction: 'Filosofi' },
    { id: 'da9-c70', type: 'Cloze', question: 'Biologiske $(\dots)$ forklarer meget.', answer: 'mønstre', options: ['mønstre', 'huse', 'penge'], instruction: 'Videnskab' },
    { id: 'da9-c71', type: 'Cloze', question: 'Det ubevidste $(\dots)$ os.', answer: 'påvirker', options: ['påvirker', 'glemmer', 'mister'], instruction: 'Psykologi' },
    { id: 'da9-c72', type: 'Cloze', question: 'Adfærd $(\dots)$ tydeligt.', answer: 'ses', options: ['ses', 'høres', 'smages'], instruction: 'Psykologi' },
    { id: 'da9-c73', type: 'Cloze', question: 'Mentale $(\dots)$ er komplekse.', answer: 'processer', options: ['processer', 'madvarer', 'sko'], instruction: 'Psykologi' },
    { id: 'da9-c74', type: 'Cloze', question: 'Strukturer $(\dots)$ samfundet.', answer: 'bygger', options: ['bygger', 'river', 'fjerner'], instruction: 'Sociologi' },
    { id: 'da9-c75', type: 'Cloze', question: 'Mønstre $(\dots)$ sig.', answer: 'gentager', options: ['gentager', 'stopper', 'fjerner'], instruction: 'Sociologi' },
    { id: 'da9-c76', type: 'Cloze', question: 'Afviser $(\dots)$ de gamle normer.', answer: 'vi', options: ['vi', 'du', 'jeg'], instruction: 'Filosofi' },
    { id: 'da9-c77', type: 'Cloze', question: 'Betydninger $(\dots)$ mange.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Filosofi' },
    { id: 'da9-c78', type: 'Cloze', question: 'Verden $(\dots)$ forbundet.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Samfund' },
    { id: 'da9-c79', type: 'Cloze', question: 'Eftervirkninger $(\dots)$ stadig.', answer: 'mærkes', options: ['mærkes', 'glemmes', 'tabes'], instruction: 'Historie' },
    { id: 'da9-c80', type: 'Cloze', question: 'Ligestilling $(\dots)$ for alle.', answer: 'kræves', options: ['kræves', 'fjernes', 'glemtes'], instruction: 'Samfund' },
    { id: 'da9-c81', type: 'Cloze', question: 'Litteraturen $(\dots)$ os ind i naturen.', answer: 'fører', options: ['fører', 'stopper', 'vender'], instruction: 'Analyse' },
    { id: 'da9-c82', type: 'Cloze', question: 'Skræmmende $(\dots)$ kan være tankevækkende.', answer: 'fremtider', options: ['fremtider', 'dage', 'timer'], instruction: 'Genre' },
    { id: 'da9-c83', type: 'Cloze', question: 'Perfekte $(\dots)$ findes kun i drømme.', answer: 'samfund', options: ['samfund', 'huse', 'biler'], instruction: 'Genre' },
    { id: 'da9-c84', type: 'Cloze', question: 'Humor $(\dots)$ kritikken.', answer: 'blødgør', options: ['blødgør', 'øger', 'fjerner'], instruction: 'Genre' },
    { id: 'da9-c85', type: 'Cloze', question: 'Effektivt $(\dots)$ er ordet.', answer: 'brugt', options: ['brugt', 'glemt', 'tabt'], instruction: 'Sprog' },
    { id: 'da9-c86', type: 'Cloze', question: 'Fortællinger $(\dots)$ mennesket.', answer: 'former', options: ['former', 'sletter', 'stopper'], instruction: 'Analyse' },
    { id: 'da9-c87', type: 'Cloze', question: 'Måde $(\dots)$ er vigtig.', answer: 'det gøres på', options: ['det gøres på', 'det glemmes', 'det tabes'], instruction: 'Sprog' },
    { id: 'da9-c88', type: 'Cloze', question: 'Magten $(\dots)$ bag ordene.', answer: 'gemmer sig', options: ['gemmer sig', 'står frem', 'råber'], instruction: 'Analyse' },
    { id: 'da9-c89', type: 'Cloze', question: 'Ansete $(\dots)$ værker læses stadig.', answer: 'gamle', options: ['gamle', 'nye', 'skøre'], instruction: 'Litteratur' },
    { id: 'da9-c90', type: 'Cloze', question: 'Løbende $(\dots)$ debatten.', answer: 'fortsætter', options: ['fortsætter', 'stopper', 'vender'], instruction: 'Litteratur' },
    { id: 'da9-c91', type: 'Cloze', question: 'Forandre $(\dots)$ målet for kunsten.', answer: 'kan være', options: ['kan være', 'er aldrig', 'måske'], instruction: 'Kunst' },
    { id: 'da9-c92', type: 'Cloze', question: 'Kunsten for $(\dots)$ egen skyld er vigtig.', answer: 'kunstens', options: ['kunstens', 'min', 'din'], instruction: 'Kunst' },
    { id: 'da9-c93', type: 'Cloze', question: 'Skønne $(\dots)$ oplevelser beriger.', answer: 'æstetiske', options: ['æstetiske', 'grimme', 'vilde'], instruction: 'Kunst' },
    { id: 'da9-c94', type: 'Cloze', question: 'Traditionelle $(\dots)$ brydes.', answer: 'grænser', options: ['grænser', 'veje', 'huse'], instruction: 'Litteratur' },
    { id: 'da9-c95', type: 'Cloze', question: 'Meningsløshed $(\dots)$ os.', answer: 'udfordrer', options: ['udfordrer', 'sover', 'spiser'], instruction: 'Litteratur' },
    { id: 'da9-c96', type: 'Cloze', question: 'Hverdag $(\dots)$ med magi.', answer: 'blandes', options: ['blandes', 'skilles', 'fjerner'], instruction: 'Litteratur' },
    { id: 'da9-c97', type: 'Cloze', question: 'Få $(\dots)$ kan sige meget.', answer: 'ord', options: ['ord', 'sætninger', 'bøger'], instruction: 'Litteratur' },
    { id: 'da9-c98', type: 'Cloze', question: 'Vigtigt $(\dots)$ er det at skrive.', answer: 'råd', options: ['råd', 'bud', 'krav'], instruction: 'Skrivekunst' },
    { id: 'da9-c99', type: 'Cloze', question: 'Tålmodighed $(\dots)$ sig.', answer: 'lønner', options: ['lønner', 'hævner', 'glemmer'], instruction: 'Skrivekunst' },
    { id: 'da9-c100', type: 'Cloze', question: 'Dansk 9 er $(\dots)$ færdig!', answer: 'helt', options: ['helt', 'ikke', 'næsten'], instruction: 'Meta' },
  ],
};
