/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const DANSK_CLOZE_P2: Partial<Record<Grade, GameContent[]>> = {
  5: [
    { id: 'da5-c3', type: 'Cloze', question: 'Astronauten ___ vægtløs i rummet.', answer: 'svæver', options: ['svæver', 'løber', 'falder'], instruction: 'Videnskab' },
    { id: 'da5-c4', type: 'Cloze', question: 'Vulkanen ___ og spyede lava.', answer: 'eruptede', options: ['eruptede', 'sov', 'sang'], instruction: 'Natur' },
    { id: 'da5-c5', type: 'Cloze', question: 'Jorden ___ omkring solen.', answer: 'roterer', options: ['roterer', 'står', 'hænger'], instruction: 'Videnskab' },
    { id: 'da5-c6', type: 'Cloze', question: 'Månen er ___ satellit.', answer: 'jordens', options: ['jordens', 'solens', 'mars'], instruction: 'Videnskab' },
    { id: 'da5-c7', type: 'Cloze', question: 'Planterne bruger ___ til fotosyntese.', answer: 'sollys', options: ['sollys', 'mørke', 'mælk'], instruction: 'Biologi' },
    { id: 'da5-c8', type: 'Cloze', question: 'Mennesket trækker ___ gennem lungerne.', answer: 'vejret', options: ['vejret', 'vand', 'mad'], instruction: 'Biologi' },
    { id: 'da5-c9', type: 'Cloze', question: 'Hjertet ___ blod rundt i kroppen.', answer: 'pumper', options: ['pumper', 'suger', 'renser'], instruction: 'Biologi' },
    { id: 'da5-c10', type: 'Cloze', question: 'Hjernen ___ vores tanker og følelser.', answer: 'styrer', options: ['styrer', 'glemmer', 'mister'], instruction: 'Biologi' },
    { id: 'da5-c11', type: 'Cloze', question: 'Skelettet ___ vores krop oprejst.', answer: 'holder', options: ['holder', 'taber', 'lægger'], instruction: 'Biologi' },
    { id: 'da5-c12', type: 'Cloze', question: 'Musklerne gør os i stand til at ___.', answer: 'bevæge os', options: ['bevæge os', 'tænke', 'sove'], instruction: 'Biologi' },
    { id: 'da5-c13', type: 'Cloze', question: 'Fordøjelsen starter i ___.', answer: 'munden', options: ['munden', 'maven', 'tarmen'], instruction: 'Biologi' },
    { id: 'da5-c14', type: 'Cloze', question: 'Blodet indeholder ___ der bærer ilt.', answer: 'jern', options: ['jern', 'guld', 'sølv'], instruction: 'Biologi' },
    { id: 'da5-c15', type: 'Cloze', question: 'Vi lugter med vores ___.', answer: 'næse', options: ['næse', 'mund', 'øje'], instruction: 'Sanser' },
    { id: 'da5-c16', type: 'Cloze', question: 'Vi smager med vores ___.', answer: 'tunge', options: ['tunge', 'tænder', 'læber'], instruction: 'Sanser' },
    { id: 'da5-c17', type: 'Cloze', question: 'Vi hører med vores ___.', answer: 'ører', options: ['ører', 'øjne', 'næse'], instruction: 'Sanser' },
    { id: 'da5-c18', type: 'Cloze', question: 'Vi ser med vores ___.', answer: 'øjne', options: ['øjne', 'ører', 'mund'], instruction: 'Sanser' },
    { id: 'da5-c19', type: 'Cloze', question: 'Vi føler med vores ___.', answer: 'hud', options: ['hud', 'hår', 'negle'], instruction: 'Sanser' },
    { id: 'da5-c20', type: 'Cloze', question: 'Det er vigtigt at ___ sundt.', answer: 'spise', options: ['spise', 'sove', 'løbe'], instruction: 'Sundhed' },
    { id: 'da5-c21', type: 'Cloze', question: 'Motion gør kroppen ___.', answer: 'stærk', options: ['stærk', 'svag', 'blå'], instruction: 'Sundhed' },
    { id: 'da5-c22', type: 'Cloze', question: 'Søvn er vigtig for ___ genopbygning.', answer: 'kroppens', options: ['kroppens', 'bilens', 'husets'], instruction: 'Sundhed' },
    { id: 'da5-c23', type: 'Cloze', question: 'Børst tænder to ___ om dagen.', answer: 'gange', options: ['gange', 'timer', 'dage'], instruction: 'Sundhed' },
    { id: 'da5-c24', type: 'Cloze', question: 'Vask hænder før ___.', answer: 'maden', options: ['maden', 'natten', 'leg'], instruction: 'Sundhed' },
    { id: 'da5-c25', type: 'Cloze', question: 'Drik masser af ___ når det er varmt.', answer: 'vand', options: ['vand', 'saft', 'kaffe'], instruction: 'Sundhed' },
    { id: 'da5-c26', type: 'Cloze', question: 'Frisk luft er ___ for helbredet.', answer: 'godt', options: ['godt', 'skidt', 'farligt'], instruction: 'Sundhed' },
    { id: 'da5-c27', type: 'Cloze', question: 'Slik og kage indeholder meget ___.', answer: 'sukker', options: ['sukker', 'salt', 'peber'], instruction: 'Sundhed' },
    { id: 'da5-c28', type: 'Cloze', question: 'Hvert år holdes der ___ i skolen.', answer: 'idrætsdag', options: ['idrætsdag', 'nattefest', 'sovedag'], instruction: 'Skole' },
    { id: 'da5-c29', type: 'Cloze', question: 'Vi skal ___ pænt til hinanden.', answer: 'tale', options: ['tale', 'råbe', 'slå'], instruction: 'Socialt' },
    { id: 'da5-c30', type: 'Cloze', question: 'Man skal ___ på sine venner.', answer: 'passe', options: ['passe', 'hvine', 'hader'], instruction: 'Socialt' },
    { id: 'da5-c31', type: 'Cloze', question: 'Det er ___ at være en god kammerat.', answer: 'vigtigt', options: ['vigtigt', 'dumt', 'ligegyldigt'], instruction: 'Socialt' },
    { id: 'da5-c32', type: 'Cloze', question: 'Mobning er ___ i vores skole.', answer: 'forbudt', options: ['forbudt', 'lovligt', 'godt'], instruction: 'Socialt' },
    { id: 'da5-c33', type: 'Cloze', question: 'Vi løser ___ ved at tale sammen.', answer: 'konflikter', options: ['konflikter', 'maden', 'lektierne'], instruction: 'Socialt' },
    { id: 'da5-c34', type: 'Cloze', question: 'Vi ___ i grupper i klassen.', answer: 'samarbejder', options: ['samarbejder', 'sover', 'spiser'], instruction: 'Socialt' },
    { id: 'da5-c35', type: 'Cloze', question: 'Alle skal ___ være med i legen.', answer: 'have lov til at', options: ['have lov til at', 'ikke', 'aldrig'], instruction: 'Socialt' },
    { id: 'da5-c36', type: 'Cloze', question: 'Respekt betyder at ___ andre.', answer: 'acceptere', options: ['acceptere', 'hader', 'slå'], instruction: 'Socialt' },
    { id: 'da5-c37', type: 'Cloze', question: 'Empati er at kunne ___ andres følelser.', answer: 'forstå', options: ['forstå', 'glemme', 'overse'], instruction: 'Socialt' },
    { id: 'da5-c38', type: 'Cloze', question: 'Vi fejrer ___ i klassen.', answer: 'fødselsdage', options: ['fødselsdage', 'nætterne', 'regnvejr'], instruction: 'Socialt' },
    { id: 'da5-c39', type: 'Cloze', question: 'Julen er hjerternes ___.', answer: 'fest', options: ['fest', 'dag', 'uge'], instruction: 'Kultur' },
    { id: 'da5-c40', type: 'Cloze', question: 'Påsken fejres med ___ og hare.', answer: 'æg', options: ['æg', 'bil', 'hat'], instruction: 'Kultur' },
    { id: 'da5-c41', type: 'Cloze', question: 'Fastelavn er ___.', answer: 'mit navn', options: ['mit navn', 'din hat', 'en fest'], instruction: 'Kultur' },
    { id: 'da5-c42', type: 'Cloze', question: 'Sankt Hans fejres med ___.', answer: 'bål', options: ['bål', 'vand', 'sne'], instruction: 'Kultur' },
    { id: 'da5-c43', type: 'Cloze', question: 'Grundlovsdag er den femte ___.', answer: 'juni', options: ['juni', 'juli', 'maj'], instruction: 'Kultur' },
    { id: 'da5-c44', type: 'Cloze', question: 'Danmarks flag hedder ___.', answer: 'Dannebrog', options: ['Dannebrog', 'Norge', 'Sverige'], instruction: 'Kultur' },
    { id: 'da5-c45', type: 'Cloze', question: 'Statsministeren ___ landet.', answer: 'leder', options: ['leder', 'spiser', 'bygger'], instruction: 'Samfund' },
    { id: 'da5-c46', type: 'Cloze', question: 'Kongen bor på et ___.', answer: 'slot', options: ['slot', 'hus', 'telt'], instruction: 'Samfund' },
    { id: 'da5-c47', type: 'Cloze', question: 'Folketinget ligger på ___.', answer: 'Christiansborg', options: ['Christiansborg', 'Rådhuset', 'Skolen'], instruction: 'Samfund' },
    { id: 'da5-c48', type: 'Cloze', question: 'Danmark er et ___.', answer: 'demokrati', options: ['demokrati', 'kongedømme', 'dikatur'], instruction: 'Samfund' },
    { id: 'da5-c49', type: 'Cloze', question: 'Vi har ___ i Danmark.', answer: 'ytringsfrihed', options: ['ytringsfrihed', 'ingen mad', 'ingen skole'], instruction: 'Samfund' },
    { id: 'da5-c50', type: 'Cloze', question: 'Man skal være ___ år for at stemme.', answer: 'atten', options: ['atten', 'seks', 'fem'], instruction: 'Samfund' },
    { id: 'da5-c51', type: 'Cloze', question: 'Vi betaler ___ til staten.', answer: 'skat', options: ['skat', 'penge', 'slik'], instruction: 'Samfund' },
  ],
  6: [
    { id: 'da6-c1', type: 'Cloze', question: 'Forfatteren benytter ___ til at skabe billeder.', answer: 'metaforer', options: ['metaforer', 'tal', 'farve'], instruction: 'Litteratur' },
    { id: 'da6-c2', type: 'Cloze', question: 'Hovedpersonen gennemgår en stor ___.', answer: 'udvikling', options: ['udvikling', 'bil', 'middag'], instruction: 'Analyse' },
    { id: 'da6-c3', type: 'Cloze', question: 'Handlingen foregår i et ___ miljø.', answer: 'trist', options: ['trist', 'glad', 'sjovt'], instruction: 'Analyse' },
    { id: 'da6-c4', type: 'Cloze', question: 'Budskabet i teksten er ___ vigtigt.', answer: 'meget', options: ['meget', 'aldrig', 'blåt'], instruction: 'Analyse' },
    { id: 'da6-c5', type: 'Cloze', question: 'Digteren bruger ___ til at skabe rytme.', answer: 'rim', options: ['rim', 'ord', 'sang'], instruction: 'Poesi' },
    { id: 'da6-c6', type: 'Cloze', question: 'Novellen slutter med en ___.', answer: 'overraskelse', options: ['overraskelse', 'begyndelse', 'vask'], instruction: 'Genre' },
    { id: 'da6-c7', type: 'Cloze', question: 'Eventyr starter ofte med "Der var ___".', answer: 'engang', options: ['engang', 'aldrig', 'nu'], instruction: 'Genre' },
    { id: 'da6-c8', type: 'Cloze', question: 'Fabelen har ofte en ___ morale.', answer: 'tydelig', options: ['tydelig', 'hemmelig', 'skør'], instruction: 'Genre' },
    { id: 'da6-c9', type: 'Cloze', question: 'Romanen er opdelt i ___.', answer: 'kapitler', options: ['kapitler', 'sider', 'ord'], instruction: 'Litteratur' },
    { id: 'da6-c10', type: 'Cloze', question: 'Historien bliver fortalt af en ___.', answer: 'fortæller', options: ['fortæller', 'læser', 'bil'], instruction: 'Analyse' },
    { id: 'da6-c11', type: 'Cloze', question: 'Vi analyserer tekstens ___.', answer: 'komposition', options: ['komposition', 'farve', 'vægt'], instruction: 'Analyse' },
    { id: 'da6-c12', type: 'Cloze', question: 'Temaet i bogen er ___.', answer: 'venskab', options: ['venskab', 'mad', 'vejr'], instruction: 'Analyse' },
    { id: 'da6-c13', type: 'Cloze', question: 'Sproget i teksten er ___ og malende.', answer: 'billedrigt', options: ['billedrigt', 'kedeligt', 'stift'], instruction: 'Analyse' },
    { id: 'da6-c14', type: 'Cloze', question: 'Vi ser på personernes ___ i teksten.', answer: 'relationer', options: ['relationer', 'sko', 'huse'], instruction: 'Analyse' },
    { id: 'da6-c15', type: 'Cloze', question: 'Miljøbeskrivelsen er meget ___.', answer: 'detaljeret', options: ['detaljeret', 'overfladisk', 'blå'], instruction: 'Analyse' },
    { id: 'da6-c16', type: 'Cloze', question: 'Konflikten opstår da ___ sker.', answer: 'noget', options: ['noget', 'intet', 'alt'], instruction: 'Analyse' },
    { id: 'da6-c17', type: 'Cloze', question: 'Vendepunktet er hvor historien ___.', answer: 'skifter', options: ['skifter', 'stopper', 'starter'], instruction: 'Analyse' },
    { id: 'da6-c18', type: 'Cloze', question: 'Afslutningen binder ___ på historien.', answer: 'knude', options: ['knude', 'sløjfe', 'tråd'], instruction: 'Analyse' },
    { id: 'da6-c19', type: 'Cloze', question: 'Vi arbejder med ___ i dansk.', answer: 'grammatik', options: ['grammatik', 'madlavning', 'sport'], instruction: 'Sprog' },
    { id: 'da6-c20', type: 'Cloze', question: 'Et navneord er noget man kan ___ foran.', answer: 'sætte en eller et', options: ['sætte en eller et', 'løbe', 'spise'], instruction: 'Grammatik' },
    { id: 'da6-c21', type: 'Cloze', question: 'Et udsagnsord fortæller hvad man ___.', answer: 'gør', options: ['gør', 'er', 'har'], instruction: 'Grammatik' },
    { id: 'da6-c22', type: 'Cloze', question: 'Et tillægsord ___ navneordet.', answer: 'beskriver', options: ['beskriver', 'flytter', 'sletter'], instruction: 'Grammatik' },
    { id: 'da6-c23', type: 'Cloze', question: 'Biord fortæller om ___ og sted.', answer: 'tid', options: ['tid', 'mad', 'tøj'], instruction: 'Grammatik' },
    { id: 'da6-c24', type: 'Cloze', question: 'Forholdsord fortæller om ___ forhold.', answer: 'rumlige', options: ['rumlige', 'muntre', 'sure'], instruction: 'Grammatik' },
    { id: 'da6-c25', type: 'Cloze', question: 'Stedord ___ navneordet.', answer: 'erstatter', options: ['erstatter', 'hjælper', 'rammer'], instruction: 'Grammatik' },
    { id: 'da6-c26', type: 'Cloze', question: 'Bindeord ___ to sætninger.', answer: 'forbinder', options: ['forbinder', 'adskiller', 'fjerner'], instruction: 'Grammatik' },
    { id: 'da6-c27', type: 'Cloze', question: 'Udråbsord udtrykker en ___ følelse.', answer: 'stærk', options: ['stærk', 'svag', 'blå'], instruction: 'Grammatik' },
    { id: 'da6-c28', type: 'Cloze', question: 'Vi skal sætte ___ i sætningen.', answer: 'komma', options: ['komma', 'mad', 'sko'], instruction: 'Grammatik' },
    { id: 'da6-c29', type: 'Cloze', question: 'Punktum markerer sætningens ___.', answer: 'slutning', options: ['slutning', 'start', 'midte'], instruction: 'Grammatik' },
    { id: 'da6-c30', type: 'Cloze', question: 'Spørgsmålstegn bruges ved ett ___.', answer: 'spørgsmål', options: ['spørgsmål', 'svar', 'råb'], instruction: 'Grammatik' },
    { id: 'da6-c31', type: 'Cloze', question: 'Udråbstegn bruges ved et ___.', answer: 'råb', options: ['råb', 'hvisk', 'suk'], instruction: 'Grammatik' },
    { id: 'da6-c32', type: 'Cloze', question: 'Vi skriver i ___ gennembrud.', answer: 'det moderne', options: ['det moderne', 'romantikken', 'barokken'], instruction: 'Litteratur' },
    { id: 'da6-c33', type: 'Cloze', question: 'H.C. Andersen skrev mange ___.', answer: 'eventyr', options: ['eventyr', 'aviser', 'breve'], instruction: 'Litteratur' },
    { id: 'da6-c34', type: 'Cloze', question: 'Karen Blixen er en ___ forfatter.', answer: 'kendt', options: ['kendt', 'ukendt', 'ny'], instruction: 'Litteratur' },
    { id: 'da6-c35', type: 'Cloze', question: 'Tove Ditlevsen skrev om ___.', answer: 'hverdagen', options: ['hverdagen', 'rummet', 'fortiden'], instruction: 'Litteratur' },
    { id: 'da6-c36', type: 'Cloze', question: 'Dan Turell var en ___ personlighed.', answer: 'farverig', options: ['farverig', 'kedelig', 'grå'], instruction: 'Litteratur' },
    { id: 'da6-c37', type: 'Cloze', question: 'Klaus Rifbjerg var en ___ forfatter.', answer: 'moderne', options: ['moderne', 'gammel', 'antik'], instruction: 'Litteratur' },
    { id: 'da6-c38', type: 'Cloze', question: 'Vi læser også ___ i dansk.', answer: 'nyheder', options: ['nyheder', 'opskrifter', 'reklamer'], instruction: 'Medier' },
    { id: 'da6-c39', type: 'Cloze', question: 'En artikel skal have en god ___.', answer: 'overskrift', options: ['overskrift', 'bund', 'side'], instruction: 'Journalistik' },
    { id: 'da6-c40', type: 'Cloze', question: 'Journalisten ___ kilderne.', answer: 'interviewer', options: ['interviewer', 'spiser', 'slår'], instruction: 'Journalistik' },
    { id: 'da6-c41', type: 'Cloze', question: 'Nyhedsartiklen skal være ___ i sit sprog.', answer: 'objektiv', options: ['objektiv', 'subjektiv', 'sjov'], instruction: 'Journalistik' },
    { id: 'da6-c42', type: 'Cloze', question: 'Lederen udtrykker avisens ___.', answer: 'holdning', options: ['holdning', 'tal', 'vejr'], instruction: 'Journalistik' },
    { id: 'da6-c43', type: 'Cloze', question: 'Læserbrevet er skrevet af en ___.', answer: 'læser', options: ['læser', 'hund', 'bil'], instruction: 'Journalistik' },
    { id: 'da6-c44', type: 'Cloze', question: 'Anmeldelsen ___ en bog eller film.', answer: 'vurderer', options: ['vurderer', 'køber', 'sælger'], instruction: 'Journalistik' },
    { id: 'da6-c45', type: 'Cloze', question: 'Reportagen er en ___ beretning.', answer: 'øøjenvidne-', options: ['øøjenvidne-', 'falsk', 'gammelt'], instruction: 'Journalistik' },
    { id: 'da6-c46', type: 'Cloze', question: 'Layoutet betyder tekstens ___.', answer: 'opsætning', options: ['opsætning', 'farve', 'vægt'], instruction: 'Journalistik' },
    { id: 'da6-c47', type: 'Cloze', question: 'Billederne i avisen ___ teksten.', answer: 'understøtter', options: ['understøtter', 'ødelægger', 'fjerner'], instruction: 'Journalistik' },
    { id: 'da6-c48', type: 'Cloze', question: 'Kildekritik er ___ i dag.', answer: 'vigtigt', options: ['vigtigt', 'ligegyldigt', 'dumt'], instruction: 'Journalistik' },
    { id: 'da6-c49', type: 'Cloze', question: 'Sociale medier ___ hurtigt nyheder.', answer: 'spreder', options: ['spreder', 'gemmer', 'stopper'], instruction: 'Medier' },
    { id: 'da6-c50', type: 'Cloze', question: 'Vær opmærksom på ___ nyheder.', answer: 'falske', options: ['falske', 'gode', 'rigtige'], instruction: 'Medier' },
    { id: 'da6-c51', type: 'Cloze', question: 'Netto-etikette handler om ___ opførsel.', answer: 'god', options: ['god', 'dårlig', 'vild'], instruction: 'Medier' },
  ],
  7: [
    { id: 'da7-c1', type: 'Cloze', question: 'Idéhistorien undersøger menneskets ___ gennem tiderne.', answer: 'tanker', options: ['tanker', 'huse', 'penge'], instruction: 'Filosofi' },
    { id: 'da7-c2', type: 'Cloze', question: 'Filosoffer stiller ___ til livet.', answer: 'spørgsmål', options: ['spørgsmål', 'svar', 'krav'], instruction: 'Filosofi' },
    { id: 'da7-c3', type: 'Cloze', question: 'Etik handler om hvad der er ___ og forkert.', answer: 'rigtigt', options: ['rigtigt', 'sjovt', 'nemt'], instruction: 'Filosofi' },
    { id: 'da7-c4', type: 'Cloze', question: 'Moral er de ___ vi lever efter.', answer: 'regler', options: ['regler', 'vande', 'sko'], instruction: 'Filosofi' },
    { id: 'da7-c5', type: 'Cloze', question: 'Eksistens betyder menneskets ___ i verden.', answer: 'tilværelse', options: ['tilværelse', 'bil', 'mad'], instruction: 'Filosofi' },
    { id: 'da7-c6', type: 'Cloze', question: 'Frihed kræver også ___.', answer: 'ansvar', options: ['ansvar', 'penge', 'slik'], instruction: 'Filosofi' },
    { id: 'da7-c7', type: 'Cloze', question: 'Hvad er ___? Det debatteres ofte.', answer: 'sandhed', options: ['sandhed', 'løgn', 'farve'], instruction: 'Filosofi' },
    { id: 'da7-c8', type: 'Cloze', question: 'Vi bruger ___ til at vinde en debat.', answer: 'retorik', options: ['retorik', 'mad', 'våben'], instruction: 'Argumentation' },
    { id: 'da7-c9', type: 'Cloze', question: 'Argumentet skal være ___ for at overbevise.', answer: 'logisk', options: ['logisk', 'skørt', 'blåt'], instruction: 'Argumentation' },
    { id: 'da7-c10', type: 'Cloze', question: 'Påstanden skal ___ af belæg.', answer: 'støttes', options: ['støttes', 'angribes', 'fjernes'], instruction: 'Argumentation' },
    { id: 'da7-c11', type: 'Cloze', question: 'Gendrivelsen fjerner modstanderens ___.', answer: 'argument', options: ['argument', 'tøj', 'bil'], instruction: 'Argumentation' },
    { id: 'da7-c12', type: 'Cloze', question: 'At tale mod bedre ___ er ikke godt.', answer: 'vidende', options: ['vidende', 'mad', 'vejr'], instruction: 'Argumentation' },
    { id: 'da7-c13', type: 'Cloze', question: 'Saglighed er ___ i en diskussion.', answer: 'vigtig', options: ['vigtig', 'dum', 'blå'], instruction: 'Argumentation' },
    { id: 'da7-c14', type: 'Cloze', question: 'Afsenderen vil ___ modtageren.', answer: 'påvirke', options: ['påvirke', 'spise', 'sove'], instruction: 'Argumentation' },
    { id: 'da7-c15', type: 'Cloze', question: 'Sproget kan være ___ i en tale.', answer: 'manipulerende', options: ['manipulerende', 'godt', 'rødt'], instruction: 'Argumentation' },
    { id: 'da7-c16', type: 'Cloze', question: 'Vi analyserer ___ i politiske taler.', answer: 'virkemidler', options: ['virkemidler', 'mad', 'sko'], instruction: 'Argumentation' },
    { id: 'da7-c17', type: 'Cloze', question: 'Etos handler om talerens ___.', answer: 'troværdighed', options: ['troværdighed', 'penge', 'udseende'], instruction: 'Retorik' },
    { id: 'da7-c18', type: 'Cloze', question: 'Logos handler om de ___ fakta.', answer: 'logiske', options: ['logiske', 'skøre', 'blå'], instruction: 'Retorik' },
    { id: 'da7-c19', type: 'Cloze', question: 'Patos appellerer til følelserne hos ___.', answer: 'tilhørerne', options: ['tilhørerne', 'dyrene', 'bilerne'], instruction: 'Retorik' },
    { id: 'da7-c20', type: 'Cloze', question: 'En metafor er en ___ sammenligning.', answer: 'indforstået', options: ['indforstået', 'dum', 'blå'], instruction: 'Sprog' },
    { id: 'da7-c21', type: 'Cloze', question: 'Personificering giver ___ liv til ting.', answer: 'menneskeligt', options: ['menneskeligt', 'dyrisk', 'dødt'], instruction: 'Sprog' },
    { id: 'da7-c22', type: 'Cloze', question: 'Ironi er at sige det ___ af det man mener.', answer: 'modsatte', options: ['modsatte', 'samme', 'blå'], instruction: 'Sprog' },
    { id: 'da7-c23', type: 'Cloze', question: 'Sarkasme er en ___ form for ironi.', answer: 'hånlig', options: ['hånlig', 'sød', 'glad'], instruction: 'Sprog' },
    { id: 'da7-c24', type: 'Cloze', question: 'Underdrivelse mindsker et ___ fænomen.', answer: 'stort', options: ['stort', 'lille', 'blåt'], instruction: 'Sprog' },
    { id: 'da7-c25', type: 'Cloze', question: 'Overdrivelse gør alting ___ end det er.', answer: 'større', options: ['større', 'mindre', 'blå'], instruction: 'Sprog' },
    { id: 'da7-c26', type: 'Cloze', question: 'Vi analyserer tekstens ___ opbygning.', answer: 'komplekse', options: ['komplekse', 'enkle', 'røde'], instruction: 'Analyse' },
    { id: 'da7-c27', type: 'Cloze', question: 'Litteraturen afspejler den ___ virkelighed.', answer: 'historiske', options: ['historiske', 'fremtidige', 'hemmelige'], instruction: 'Litteratur' },
    { id: 'da7-c28', type: 'Cloze', question: 'Symbolerne bærer på en ___ betydning.', answer: 'skjult', options: ['skjult', 'åbenlys', 'blå'], instruction: 'Analyse' },
    { id: 'da7-c29', type: 'Cloze', question: 'Fortolkningen kræver en ___ læsning.', answer: 'dybdegående', options: ['dybdegående', 'hurtig', 'glad'], instruction: 'Analyse' },
    { id: 'da7-c30', type: 'Cloze', question: 'Intertekstualitet er når tekster ___ hinanden.', answer: 'refererer til', options: ['refererer til', 'spiser', 'ødelægger'], instruction: 'Analyse' },
    { id: 'da7-c31', type: 'Cloze', question: 'Litterære perioder har forskellige ___.', answer: 'idealer', options: ['idealer', 'madvarer', 'sko'], instruction: 'Litteratur' },
    { id: 'da7-c32', type: 'Cloze', question: 'Romantikken fokuserede på ___ og natur.', answer: 'følelser', options: ['følelser', 'maskiner', 'penge'], instruction: 'Litterature' },
    { id: 'da7-c33', type: 'Cloze', question: 'Det moderne gennembrud handlede om ___.', answer: 'problemer', options: ['problemer', 'eventyr', 'mad'], instruction: 'Litteratur' },
    { id: 'da7-c34', type: 'Cloze', question: 'Realisme forsøger at beskrive verden ___ som den er.', answer: 'præcis', options: ['præcis', 'skørt', 'aldrig'], instruction: 'Litteratur' },
    { id: 'da7-c35', type: 'Cloze', question: 'Pontoppidan var en ___ skikkelse i dansk litteratur.', answer: 'central', options: ['central', 'ubetydelig', 'hemmelig'], instruction: 'Litteratur' },
    { id: 'da7-c36', type: 'Cloze', question: 'J.P. Jacobsen skrev om ___ i skæbnen.', answer: 'trolden', options: ['trolden', 'lykken', 'bilen'], instruction: 'Litteratur' },
    { id: 'da7-c37', type: 'Cloze', question: 'Herman Bang er kendt for sin ___ stil.', answer: 'impressionistiske', options: ['impressionistiske', 'hårde', 'stive'], instruction: 'Litteratur' },
    { id: 'da7-c38', type: 'Cloze', question: 'Vi ser på sprogets ___ i analysen.', answer: 'stilistik', options: ['stilistik', 'farve', 'vægt'], instruction: 'Analyse' },
    { id: 'da3-c39', type: 'Cloze', question: 'Synsvinklen kan være ___ eller personal.', answer: 'altvidende', options: ['altvidende', 'blind', 'døv'], instruction: 'Analyse' },
    { id: 'da7-c40', type: 'Cloze', question: 'Fortælleren kan være ___ eller utroværdig.', answer: 'pålidelig', options: ['pålidelig', 'falsk', 'tyk'], instruction: 'Analyse' },
    { id: 'da7-c41', type: 'Cloze', question: 'Miljøet påvirker personernes ___.', answer: 'handlinger', options: ['handlinger', 'tænder', 'sko'], instruction: 'Analyse' },
    { id: 'da7-c42', type: 'Cloze', question: 'Tekstens undertekst er det der ___ skrives.', answer: 'ikke direkte', options: ['ikke direkte', 'faktisk', 'altid'], instruction: 'Analyse' },
    { id: 'da7-c43', type: 'Cloze', question: 'Modsætninger skaber ___ i en tekst.', answer: 'spænding', options: ['spænding', 'ro', 'søvn'], instruction: 'Analyse' },
    { id: 'da7-c44', type: 'Cloze', question: 'Vi bruger ___ til at finde citater.', answer: 'tekstlæsning', options: ['tekstlæsning', 'gætteri', 'mad'], instruction: 'Analyse' },
    { id: 'da7-c45', type: 'Cloze', question: 'Dokumentation er ___ for analysen.', answer: 'nødvendig', options: ['nødvendig', 'dum', 'blå'], instruction: 'Analyse' },
    { id: 'da7-c46', type: 'Cloze', question: 'Vi skal kunne ___ vores fortolkning.', answer: 'begrunde', options: ['begrunde', 'glemme', 'tabe'], instruction: 'Analyse' },
    { id: 'da7-c47', type: 'Cloze', question: 'Litteraturhistoriens ___ er vigtige at kende.', answer: 'linjer', options: ['linjer', 'sko', 'huse'], instruction: 'Litteratur' },
    { id: 'da7-c48', type: 'Cloze', question: 'Vi sammenligner tekster fra ___ perioder.', answer: 'forskellige', options: ['forskellige', 'samme', 'røde'], instruction: 'Litteratur' },
    { id: 'da7-c49', type: 'Cloze', question: 'Budskabet rækker ud over ___ tid.', answer: 'sin egen', options: ['sin egen', 'aldrig', 'altid'], instruction: 'Litteratur' },
    { id: 'da7-c50', type: 'Cloze', question: 'Kanon-forfattere er ___ i skolen.', answer: 'obligatoriske', options: ['obligatoriske', 'forbudte', 'sjove'], instruction: 'Litteratur' },
    { id: 'da7-c51', type: 'Cloze', question: 'Læsning giver ___ til verden.', answer: 'indsigt', options: ['indsigt', 'udsigtsløshed', 'sko'], instruction: 'Besked' },
  ],
  8: [
    { id: 'da8-c2', type: 'Cloze', question: 'Identitet er et ___ emne i moderne litteratur.', answer: 'centralt', options: ['centralt', 'ukendt', 'blåt'], instruction: 'Tema' },
    { id: 'da8-c3', type: 'Cloze', question: 'Hvem er jeg? Det er et ___ spørgsmål.', answer: 'eksistentielt', options: ['eksistentielt', 'dumt', 'nemt'], instruction: 'Tema' },
    { id: 'da8-c4', type: 'Cloze', question: 'Globalisering gør verden ___ for os.', answer: 'mindre', options: ['mindre', 'større', 'blå'], instruction: 'Samfund' },
    { id: 'da8-c5', type: 'Cloze', question: 'Kultursammenstød kan skabe både ___ og konflikt.', answer: 'forståelse', options: ['forståelse', 'had', 'krig'], instruction: 'Samfund' },
    { id: 'da8-c6', type: 'Cloze', question: 'Mediernes magt er ___ i dag.', answer: 'stor', options: ['stor', 'lille', 'blå'], instruction: 'Samfund' },
    { id: 'da8-c7', type: 'Cloze', question: 'Digital dannelse handler om at ___ sig på nettet.', answer: 'opføre', options: ['opføre', 'spise', 'sove'], instruction: 'Samfund' },
    { id: 'da8-c8', type: 'Cloze', question: 'Kildekritik er ___ når man bruger internettet.', answer: 'afgørende', options: ['afgørende', 'ligegyldig', 'sjov'], instruction: 'Samfund' },
    { id: 'da8-c9', type: 'Cloze', question: 'Falske nyheder kan ___ vores demokrati.', answer: 'skade', options: ['skade', 'hjælpe', 'bygge'], instruction: 'Samfund' },
    { id: 'da8-c10', type: 'Cloze', question: 'Sociale medier skaber ___ fællesskaber.', answer: 'digitale', options: ['digitale', 'fysiske', 'ingen'], instruction: 'Samfund' },
    { id: 'da8-c11', type: 'Cloze', question: 'Persondata skal ___ på nettet.', answer: 'beskyttes', options: ['beskyttes', 'deles', 'sælges'], instruction: 'Samfund' },
    { id: 'da8-c12', type: 'Cloze', question: 'Algoritmer styrer hvad vi ___ på nettet.', answer: 'ser', options: ['ser', 'spiser', 'hører'], instruction: 'Samfund' },
    { id: 'da8-c13', type: 'Cloze', question: 'Ekkokamre forstærker vores egne ___.', answer: 'holdninger', options: ['holdninger', 'sko', 'huse'], instruction: 'Samfund' },
    { id: 'da8-c14', type: 'Cloze', question: 'Kritisk tænkning er et ___ mod manipulation.', answer: 'værn', options: ['værn', 'angreb', 'hul'], instruction: 'Samfund' },
    { id: 'da8-c15', type: 'Cloze', question: 'Reklamer forsøger at ___ vores behov.', answer: 'skabe', options: ['skabe', 'fjerne', 'mætte'], instruction: 'Samfund' },
    { id: 'da8-c16', type: 'Cloze', question: 'Branding er vigtigt for ___ virksomheder.', answer: 'moderne', options: ['moderne', 'gamle', 'små'], instruction: 'Økonomi' },
    { id: 'da8-c17', type: 'Cloze', question: 'Forbrugerisme præger vores ___ samfund.', answer: 'vestlige', options: ['vestlige', 'vilde', 'stille'], instruction: 'Samfund' },
    { id: 'da8-c18', type: 'Cloze', question: 'Bæredygtighed er en ___ nødvendighed.', answer: 'global', options: ['global', 'lokal', 'blå'], instruction: 'Miljø' },
    { id: 'da8-c19', type: 'Cloze', question: 'Klimaforandringer kræver ___ handling nu.', answer: 'politisk', options: ['politisk', 'ingen', 'langsom'], instruction: 'Politik' },
    { id: 'da8-c20', type: 'Cloze', question: 'Individet har et ___ over for miljøet.', answer: 'ansvar', options: ['ansvar', 'mad', 'tøj'], instruction: 'Etik' },
    { id: 'da8-c21', type: 'Cloze', question: 'Fællesskabet skal ___ de svageste.', answer: 'hjælpe', options: ['hjælpe', 'overse', 'slå'], instruction: 'Etik' },
    { id: 'da8-c22', type: 'Cloze', question: 'Retfærdighed er et ___ i samfundet.', answer: 'grundprincip', options: ['grundprincip', 'spil', 'mad'], instruction: 'Politik' },
    { id: 'da8-c23', type: 'Cloze', question: 'Lighed for loven gælder for ___.', answer: 'alle', options: ['alle', 'ingen', 'få'], instruction: 'Politik' },
    { id: 'da8-c24', type: 'Cloze', question: 'Menneskerettighederne skal ___ overalt.', answer: 'respekteres', options: ['respekteres', 'brydes', 'glemmes'], instruction: 'Politik' },
    { id: 'da8-c25', type: 'Cloze', question: 'Demokratiet kræver ___ borgere.', answer: 'aktive', options: ['aktive', 'passive', 'sovende'], instruction: 'Samfund' },
    { id: 'da8-c26', type: 'Cloze', question: 'Ytringsfriheden har også sine ___.', answer: 'grænser', options: ['grænser', 'veje', 'sko'], instruction: 'Lov' },
    { id: 'da8-c27', type: 'Cloze', question: 'Hadesprog er ___ i den offentlige debat.', answer: 'uacceptabelt', options: ['uacceptabelt', 'velkomment', 'sjovt'], instruction: 'Socialt' },
    { id: 'da8-c28', type: 'Cloze', question: 'Tolerance betyder at ___ forskelligheder.', answer: 'rumme', options: ['rumme', 'fjerne', 'hader'], instruction: 'Socialt' },
    { id: 'da8-c29', type: 'Cloze', question: 'Solidaritet binder ___ sammen.', answer: 'mennesker', options: ['mennesker', 'biler', 'huse'], instruction: 'Socialt' },
    { id: 'da8-c30', type: 'Cloze', question: 'Vi skal kæmpe mod ___ i samfundet.', answer: 'ulighed', options: ['ulighed', 'lighed', 'mad'], instruction: 'Politik' },
    { id: 'da8-c31', type: 'Cloze', question: 'Uddannelse er vejen til en ___ fremtid.', answer: 'bedre', options: ['bedre', 'værre', 'blå'], instruction: 'Fremtid' },
    { id: 'da8-c32', type: 'Cloze', question: 'Arbejde giver ___ og mening.', answer: 'indhold', options: ['indhold', 'mad', 'tøj'], instruction: 'Samfund' },
    { id: 'da8-c33', type: 'Cloze', question: 'Velfærdsstaten ___ borgerne tryghed.', answer: 'sikrer', options: ['sikrer', 'fjerner', 'ødelægger'], instruction: 'Økonomi' },
    { id: 'da8-c34', type: 'Cloze', question: 'Økonomien skal være ___ for at vokse.', answer: 'stabil', options: ['stabil', 'nervøs', 'rød'], instruction: 'Økonomi' },
    { id: 'da8-c35', type: 'Cloze', question: 'Investeringer skaber ___ i landet.', answer: 'arbejdspladser', options: ['arbejdspladser', 'krig', 'sygdom'], instruction: 'Økonomi' },
    { id: 'da8-c36', type: 'Cloze', question: 'Teknologien ændrer vores ___ hver dag.', answer: 'liv', options: ['liv', 'sko', 'huse'], instruction: 'Technologi' },
    { id: 'da8-c37', type: 'Cloze', question: 'Innovation driver ___ fremad.', answer: 'udviklingen', options: ['udviklingen', 'bilen', 'maden'], instruction: 'Videnskab' },
    { id: 'da8-c38', type: 'Cloze', question: 'Videnskaben søger efter ___ om verden.', answer: 'viden', options: ['viden', 'guld', 'mad'], instruction: 'Videnskab' },
    { id: 'da8-c39', type: 'Cloze', question: 'Laboratoriet er hvor ___ foregår.', answer: 'eksperimenter', options: ['eksperimenter', 'madlavning', 'dans'], instruction: 'Videnskab' },
    { id: 'da8-c40', type: 'Cloze', question: 'Hypotesen skal ___ i virkeligheden.', answer: 'testes', options: ['testes', 'glemmes', 'tabes'], instruction: 'Videnskab' },
    { id: 'da8-c41', type: 'Cloze', question: 'Resultaterne skal være ___ for andre.', answer: 'gængelige', options: ['gængelige', 'hemmelige', 'farlige'], instruction: 'Videnskab' },
    { id: 'da8-c42', type: 'Cloze', question: 'Etik i forskning er ___ vigtigt.', answer: 'meget', options: ['meget', 'aldrig', 'blåt'], instruction: 'Etik' },
    { id: 'da8-c43', type: 'Cloze', question: 'Fremtiden er ___ af vores valg i dag.', answer: 'præget', options: ['præget', 'uafhængig', 'blå'], instruction: 'Tanke' },
    { id: 'da8-c44', type: 'Cloze', question: 'Vi skal tage ved ___ af historien.', answer: 'lære', options: ['lære', 'mad', 'sko'], instruction: 'Tanke' },
    { id: 'da8-c45', type: 'Cloze', question: 'Erfaring er den bedste ___.', answer: 'lærer', options: ['lærer', 'elev', 'bog'], instruction: 'Tanke' },
    { id: 'da8-c46', type: 'Cloze', question: 'Visdom kommer med ___ og alder.', answer: 'indsigt', options: ['indsigt', 'tænder', 'hår'], instruction: 'Tanke' },
    { id: 'da8-c47', type: 'Cloze', question: 'Forandring fryder, siger et ___ ordsprog.', answer: 'gammelt', options: ['gammelt', 'nyt', 'skørt'], instruction: 'Tanke' },
    { id: 'da8-c48', type: 'Cloze', question: 'Håbet lever til ___ sidst.', answer: 'det', options: ['det', 'ikke', 'en'], instruction: 'Tanke' },
    { id: 'da8-c49', type: 'Cloze', question: 'Lykken er at ___ sig selv.', answer: 'finde', options: ['finde', 'tabe', 'sælge'], instruction: 'Tanke' },
    { id: 'da8-c50', type: 'Cloze', question: 'Kærlighed overvinder ___ alt.', answer: 'næsten', options: ['næsten', 'aldrig', 'altid'], instruction: 'Tanke' },
    { id: 'da8-c51', type: 'Cloze', question: 'Slut for ___ niveau.', answer: 'dette', options: ['dette', 'det', 'en'], instruction: 'Besked' },
  ],
  9: [
    { id: 'da9-c1', type: 'Cloze', question: 'Eksistensialismen fokuserer på menneskets ___ valg.', answer: 'frie', options: ['frie', 'tvungne', 'ingen'], instruction: 'Filosofi' },
    { id: 'da9-c2', type: 'Cloze', question: 'Sartre mente at mennesket er ___ til frihed.', answer: 'dømt', options: ['dømt', 'valgt', 'født'], instruction: 'Filosofi' },
    { id: 'da9-c3', type: 'Cloze', question: 'Nihilismen hævder at livet er ___ mening.', answer: 'uden', options: ['uden', 'med', 'fuld af'], instruction: 'Filosofi' },
    { id: 'da9-c4', type: 'Cloze', question: 'Absurdismen ser en ___ mellem mennesket og verden.', answer: 'konflikt', options: ['konflikt', 'harmoni', 'fred'], instruction: 'Filosofi' },
    { id: 'da9-c5', type: 'Cloze', question: 'Stoicismen lærer os at ___ det uundgåelige.', answer: 'acceptere', options: ['acceptere', 'bekæmpe', 'flygte fra'], instruction: 'Filosofi' },
    { id: 'da9-c6', type: 'Cloze', question: 'Epikuræismen søger efter ___ og fravær af smerte.', answer: 'nydelse', options: ['nydelse', 'lidelse', 'arbejde'], instruction: 'Filosofi' },
    { id: 'da9-c7', type: 'Cloze', question: 'Rationalismen bygger på ___ som kilde til erkendelse.', answer: 'fornuft', options: ['fornuft', 'følelse', 'tro'], instruction: 'Filosofi' },
    { id: 'da9-c8', type: 'Cloze', question: 'Empirismen vægter ___ og observation højest.', answer: 'erfaring', options: ['erfaring', 'tænkning', 'drømme'], instruction: 'Filosofi' },
    { id: 'da9-c9', type: 'Cloze', question: 'Fænomenologien undersøger ___ af tingene.', answer: 'fremtræden', options: ['fremtræden', 'kerne', 'pris'], instruction: 'Filosofi' },
    { id: 'da9-c10', type: 'Cloze', question: 'Ontologien er læren om ___.', answer: 'væren', options: ['væren', 'viden', 'moral'], instruction: 'Filosofi' },
    { id: 'da9-c11', type: 'Cloze', question: 'Epistemologien beskæftiger sig med ___ natur.', answer: 'videns', options: ['videns', 'kroppens', 'sjælens'], instruction: 'Filosofi' },
    { id: 'da9-c12', type: 'Cloze', question: 'Dualismen skelner mellem ___ og krop.', answer: 'sjæl', options: ['sjæl', 'hår', 'fod'], instruction: 'Filosofi' },
    { id: 'da9-c13', type: 'Cloze', question: 'Determinismen påstår at alt er ___ forud.', answer: 'bestemt', options: ['bestemt', 'tilfældigt', 'skjult'], instruction: 'Filosofi' },
    { id: 'da9-c14', type: 'Cloze', question: 'Dialektikken arbejder med ___ og syntese.', answer: 'antitese', options: ['antitese', 'historie', 'mad'], instruction: 'Filosofi' },
    { id: 'da9-c15', type: 'Cloze', question: 'Hermeneutikken er læren om ___.', answer: 'fortolkning', options: ['fortolkning', 'skabelse', 'salg'], instruction: 'Filosofi' },
    { id: 'da9-c16', type: 'Cloze', question: 'Kants kategoriske imperativ handler om ___ handlemåde.', answer: 'almen', options: ['almen', 'personlig', 'hemmelig'], instruction: 'Filosofi' },
    { id: 'da9-c17', type: 'Cloze', question: 'Utilitarismen søger størst mulig ___ for flest mulige.', answer: 'lykke', options: ['lykke', 'penge', 'magt'], instruction: 'Filosofi' },
    { id: 'da9-c18', type: 'Cloze', question: 'Dydsetik fokuserer på karakter og ___.', answer: 'moral', options: ['moral', 'udseende', 'rigdom'], instruction: 'Filosofi' },
    { id: 'da9-c19', type: 'Cloze', question: 'Sociobiologien ser på den ___ baggrund for adfærd.', answer: 'biologiske', options: ['biologiske', 'kulturelle', 'økonomiske'], instruction: 'Videnskab' },
    { id: 'da9-c20', type: 'Cloze', question: 'Psykoanalysen dykker ned i det ___.', answer: 'ubevidste', options: ['ubevidste', 'bevidste', 'fysiske'], instruction: 'Psykologi' },
    { id: 'da9-c21', type: 'Cloze', question: 'Behaviorismen studerer ___ adfærd.', answer: 'observerbar', options: ['observerbar', 'skjult', 'indre'], instruction: 'Psykologi' },
    { id: 'da9-c22', type: 'Cloze', question: 'Kognitionspsykologi ser på ___ processer.', answer: 'mentale', options: ['mentale', 'fysiske', 'sociale'], instruction: 'Psykologi' },
    { id: 'da9-c23', type: 'Cloze', question: 'Sociologien undersøger ___ i samfundet.', answer: 'strukturer', options: ['strukturer', 'individer', 'dyr'], instruction: 'Sociologi' },
    { id: 'da9-c24', type: 'Cloze', question: 'Strukturalismen ser på de ___ mønstre.', answer: 'underliggende', options: ['underliggende', 'synlige', 'nye'], instruction: 'Sociologi' },
    { id: 'da9-c25', type: 'Cloze', question: 'Postmodernismen ___ de store fortællinger.', answer: 'afviser', options: ['afviser', 'hylder', 'støtter'], instruction: 'Filosofi' },
    { id: 'da9-c26', type: 'Cloze', question: 'Dekonstruktion åbner for ___ betydninger.', answer: 'flertydige', options: ['flertydige', 'enkelte', 'ingen'], instruction: 'Filosofi' },
    { id: 'da9-c27', type: 'Cloze', question: 'Globaliseringen skaber en ___ verden.', answer: 'sammenhængende', options: ['sammenhængende', 'isoleret', 'lukket'], instruction: 'Samfund' },
    { id: 'da9-c28', type: 'Cloze', question: 'Postkolonialismen ser på ___ af kolonitiden.', answer: 'eftervirkninger', options: ['eftervirkninger', 'fordele', 'starten'], instruction: 'Historie' },
    { id: 'da9-c29', type: 'Cloze', question: 'Feminismen kæmper for ___ mellem kønnene.', answer: 'ligestilling', options: ['ligestilling', 'forskel', 'kamp'], instruction: 'Samfund' },
    { id: 'da9-c30', type: 'Cloze', question: 'Økokritik analyserer ___ forhold til naturen.', answer: 'litteraturens', options: ['litteraturens', 'bilens', 'madens'], instruction: 'Analyse' },
    { id: 'da9-c31', type: 'Cloze', question: 'Dystopien beskriver en ___ fremtid.', answer: 'skræmmende', options: ['skræmmende', 'lykkelig', 'lys'], instruction: 'Genre' },
    { id: 'da9-c32', type: 'Cloze', question: 'Utopien er det ___ samfund.', answer: 'perfekte', options: ['perfekte', 'ødelagte', 'mørke'], instruction: 'Genre' },
    { id: 'da9-c33', type: 'Cloze', question: 'Satire bruger ___ til at kritisere.', answer: 'humor', options: ['humor', 'vold', 'trusler'], instruction: 'Genre' },
    { id: 'da9-c34', type: 'Cloze', question: 'Ironien er et ___ redskab i litteraturen.', answer: 'effektivt', options: ['effektivt', 'ubrugeligt', 'træls'], instruction: 'Sprog' },
    { id: 'da9-c35', type: 'Cloze', question: 'Narratologi er læren om ___.', answer: 'fortællinger', options: ['fortællinger', 'ord', 'rim'], instruction: 'Analyse' },
    { id: 'da9-c36', type: 'Cloze', question: 'Diskurs er den ___ vi taler om tingene på.', answer: 'måde', options: ['måde', 'dag', 'uge'], instruction: 'Sprog' },
    { id: 'da9-c37', type: 'Cloze', question: 'Ideologikritik afslører ___ bag teksten.', answer: 'magten', options: ['magten', 'historien', 'maden'], instruction: 'Analyse' },
    { id: 'da9-c38', type: 'Cloze', question: 'Kanonen er de ___ vigtigste værker.', answer: 'ansete', options: ['ansete', 'glemte', 'skøre'], instruction: 'Litteratur' },
    { id: 'da9-c39', type: 'Cloze', question: 'Litteraturens rolle debatteres ___ i samfundet.', answer: 'løbende', options: ['løbende', 'aldrig', 'sjældent'], instruction: 'Litteratur' },
    { id: 'da9-c40', type: 'Cloze', question: 'Kunsten skal ___ verden, sagde nogle.', answer: 'forandre', options: ['forandre', 'pynte', 'bevare'], instruction: 'Kunst' },
    { id: 'da9-c41', type: 'Cloze', question: 'L\'art pur er kunsten for ___ egen skyld.', answer: 'kunstens', options: ['kunstens', 'min', 'din'], instruction: 'Kunst' },
    { id: 'da9-c42', type: 'Cloze', question: 'Æstetikken er læren om det ___.', answer: 'skønne', options: ['skønne', 'grimme', 'vilde'], instruction: 'Kunst' },
    { id: 'da9-c43', type: 'Cloze', question: 'Modernismen brød med ___ former.', answer: 'traditionelle', options: ['traditionelle', 'nye', 'vilde'], instruction: 'Litteratur' },
    { id: 'da9-c44', type: 'Cloze', question: 'Det absurde teater viser livets ___.', answer: 'meningsløshed', options: ['meningsløshed', 'glæde', 'skønhed'], instruction: 'Litteratur' },
    { id: 'da9-c45', type: 'Cloze', question: 'Magisk realisme blander ___ og magi.', answer: 'hverdag', options: ['hverdag', 'rummet', 'fortiden'], instruction: 'Litteratur' },
    { id: 'da9-c46', type: 'Cloze', question: 'Minimalismen bruger ___ ord.', answer: 'få', options: ['få', 'mange', 'lange'], instruction: 'Litteratur' },
    { id: 'da9-c47', type: 'Cloze', question: 'Show, don\'t tell er et ___ råd.', answer: 'vigtigt', options: ['vigtigt', 'dumt', 'ligegyldigt'], instruction: 'Skrivekunst' },
    { id: 'da9-c48', type: 'Cloze', question: 'Skriveprocessen kræver ___ og flid.', answer: 'tålmodighed', options: ['tålmodighed', 'fart', 'penge'], instruction: 'Skrivekunst' },
    { id: 'da9-c49', type: 'Cloze', question: 'Redigering er ___ for det færdige resultat.', answer: 'afgørende', options: ['afgørende', 'ligegyldig', 'sjov'], instruction: 'Skrivekunst' },
    { id: 'da9-c50', type: 'Cloze', question: 'Læsningen giver os ___ liv.', answer: 'mange', options: ['mange', 'et', 'ingen'], instruction: 'Filosofi' },
    { id: 'da9-c51', type: 'Cloze', question: 'Held og lykke ___ eksamen!', answer: 'til', options: ['til', 'med', 'for'], instruction: 'Besked' },
  ],
};
