/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const DANSK_CLOZE_P1: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'da0-c1', type: 'Cloze', question: 'Jeg kan ___ en hund.', answer: 'se', options: ['se', 'have', 'gå'], instruction: 'Hvad kan du?' },
    { id: 'da0-c2', type: 'Cloze', question: 'Hunden siger ___.', answer: 'vov', options: ['vov', 'miau', 'øf'], instruction: 'Lyd' },
    { id: 'da0-c3', type: 'Cloze', question: 'Min mor er ___.', answer: 'sød', options: ['sød', 'sur', 'blå'], instruction: 'Beskrivelse' },
    { id: 'da0-c4', type: 'Cloze', question: 'Æblet er ___.', answer: 'rødt', options: ['rødt', 'blåt', 'sort'], instruction: 'Farve' },
    { id: 'da0-c5', type: 'Cloze', question: 'Solen er ___.', answer: 'gul', options: ['gul', 'grøn', 'lilla'], instruction: 'Farve' },
    { id: 'da0-c6', type: 'Cloze', question: 'Farverne er ___ og blå.', answer: 'rød', options: ['rød', 'ost', 'bog'], instruction: 'Farve' },
    { id: 'da0-c7', type: 'Cloze', question: 'Jeg ___ en is.', answer: 'spiser', options: ['spiser', 'læser', 'kører'], instruction: 'Handling' },
    { id: 'da0-c8', type: 'Cloze', question: 'Bilen ___ stærkt.', answer: 'kører', options: ['kører', 'sover', 'spiser'], instruction: 'Handling' },
    { id: 'da0-c9', type: 'Cloze', question: 'En ko ___ mælk.', answer: 'giver', options: ['giver', 'tager', 'læser'], instruction: 'Handling' },
    { id: 'da0-c10', type: 'Cloze', question: 'Jeg har en ___ kat.', answer: 'lille', options: ['lille', 'stort', 'rødt'], instruction: 'Beskrivelse' },
    { id: 'da0-c11', type: 'Cloze', question: 'Huset er ___.', answer: 'stort', options: ['stort', 'lillebitte', 'blå'], instruction: 'Beskrivelse' },
    { id: 'da0-c12', type: 'Cloze', question: 'Græsset er ___.', answer: 'grønt', options: ['grønt', 'gult', 'sort'], instruction: 'Farve' },
    { id: 'da0-c13', type: 'Cloze', question: 'Himlen er ___.', answer: 'blå', options: ['blå', 'rød', 'hvid'], instruction: 'Farve' },
    { id: 'da0-c14', type: 'Cloze', question: 'Sneen er ___.', answer: 'hvid', options: ['hvid', 'sort', 'gul'], instruction: 'Farve' },
    { id: 'da0-c15', type: 'Cloze', question: 'Jeg ___ min mor.', answer: 'elsker', options: ['elsker', 'hader', 'bor'], instruction: 'Følelse' },
    { id: 'da0-c16', type: 'Cloze', question: 'Pigen ___ en pæn kjole.', answer: 'har', options: ['har', 'er', 'kan'], instruction: 'Ord' },
    { id: 'da0-c17', type: 'Cloze', question: 'Drengen ___ glad.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Ord' },
    { id: 'da0-c18', type: 'Cloze', question: 'Vi ___ i skole.', answer: 'går', options: ['går', 'spiser', 'sover'], instruction: 'Handling' },
    { id: 'da0-c19', type: 'Cloze', question: 'Fisken ___ i vandet.', answer: 'svømmer', options: ['svømmer', 'flyver', 'løber'], instruction: 'Handling' },
    { id: 'da0-c20', type: 'Cloze', question: 'Fuglen ___ i luften.', answer: 'flyver', options: ['flyver', 'svømmer', 'kryber'], instruction: 'Handling' },
    { id: 'da0-c21', type: 'Cloze', question: 'Slangen ___ på jorden.', answer: 'kryber', options: ['kryber', 'hopper', 'flyver'], instruction: 'Handling' },
    { id: 'da0-c22', type: 'Cloze', question: 'Frøen ___.', answer: 'hopper', options: ['hopper', 'løber', 'flyver'], instruction: 'Handling' },
    { id: 'da0-c23', type: 'Cloze', question: 'Kaninen har ___ ører.', answer: 'lange', options: ['lange', 'runde', 'kantede'], instruction: 'Krop' },
    { id: 'da0-c24', type: 'Cloze', question: 'Elefanten er ___.', answer: 'grå', options: ['grå', 'pink', 'orange'], instruction: 'Farve' },
    { id: 'da0-c25', type: 'Cloze', question: 'Grisen er ___.', answer: 'lyserød', options: ['lyserød', 'blå', 'brun'], instruction: 'Farve' },
    { id: 'da0-c26', type: 'Cloze', question: 'Bjørnen er ___.', answer: 'brun', options: ['brun', 'hvid', 'lilla'], instruction: 'Farve' },
    { id: 'da0-c27', type: 'Cloze', question: 'Isbjørnen er ___.', answer: 'hvid', options: ['hvid', 'sort', 'blå'], instruction: 'Farve' },
    { id: 'da0-c28', type: 'Cloze', question: 'Tigeren har ___.', answer: 'striber', options: ['striber', 'prikker', 'tern'], instruction: 'Mønster' },
    { id: 'da0-c29', type: 'Cloze', question: 'Leoparden har ___.', answer: 'prikker', options: ['prikker', 'striber', 'tern'], instruction: 'Mønster' },
    { id: 'da0-c30', type: 'Cloze', question: 'Jeg kan ___ lide kage.', answer: 'godt', options: ['godt', 'skidt', 'ikke'], instruction: 'Smag' },
    { id: 'da0-c31', type: 'Cloze', question: 'Bogen er ___.', answer: 'god', options: ['god', 'dum', 'blå'], instruction: 'Mening' },
    { id: 'da0-c32', type: 'Cloze', question: 'Det er ___ vejr.', answer: 'dejligt', options: ['dejligt', 'sur', 'trist'], instruction: 'Vejr' },
    { id: 'da0-c33', type: 'Cloze', question: 'Det ___ i dag.', answer: 'regner', options: ['regner', 'blæser', 'lyser'], instruction: 'Vejr' },
    { id: 'da0-c34', type: 'Cloze', question: 'Det ___ i morgen.', answer: 'sner', options: ['sner', 'regner', 'lyser'], instruction: 'Vejr' },
    { id: 'da0-c35', type: 'Cloze', question: 'Jeg er ___ år.', answer: 'seks', options: ['seks', 'blå', 'hund'], instruction: 'Tal' },
    { id: 'da0-c36', type: 'Cloze', question: 'Min fødselsdag er ___.', answer: 'i dag', options: ['i dag', 'i går', 'aldrig'], instruction: 'Tid' },
    { id: 'da0-c37', type: 'Cloze', question: 'Jeg går i ___ klasse.', answer: 'nulte', options: ['nulte', 'voksen', 'stor'], instruction: 'Skole' },
    { id: 'da0-c38', type: 'Cloze', question: 'Min lærer hedder ___.', answer: 'Mette', options: ['Mette', 'Bil', 'Kat'], instruction: 'Navn' },
    { id: 'da0-c39', type: 'Cloze', question: 'Jeg skriver med min ___.', answer: 'blyant', options: ['blyant', 'sko', 'mad'], instruction: 'Skole' },
    { id: 'da0-c40', type: 'Cloze', question: 'Jeg tegner på ___.', answer: 'papir', options: ['papir', 'gulv', 'loft'], instruction: 'Skole' },
    { id: 'da0-c41', type: 'Cloze', question: 'Jeg sidder på en ___.', answer: 'stol', options: ['stol', 'bord', 'bil'], instruction: 'Møbel' },
    { id: 'da0-c42', type: 'Cloze', question: 'Jeg har min mad i en ___.', answer: 'madpakke', options: ['madpakke', 'taske', 'sko'], instruction: 'Skole' },
    { id: 'da0-c43', type: 'Cloze', question: 'Jeg drikker ___ af min flaske.', answer: 'vand', options: ['vand', 'mjød', 'benzin'], instruction: 'Drik' },
    { id: 'da0-c44', type: 'Cloze', question: 'Jeg leger i ___.', answer: 'gården', options: ['gården', 'huset', 'skoven'], instruction: 'Skole' },
    { id: 'da0-c45', type: 'Cloze', question: 'Vi ___ sange.', answer: 'synger', options: ['synger', 'løber', 'sover'], instruction: 'Musik' },
    { id: 'da0-c46', type: 'Cloze', question: 'Det er ___ at lege.', answer: 'sjovt', options: ['sjovt', 'kedeligt', 'trist'], instruction: 'Følelse' },
    { id: 'da0-c47', type: 'Cloze', question: 'Jeg er ___.', answer: 'glad', options: ['glad', 'trist', 'sur'], instruction: 'Følelse' },
    { id: 'da0-c48', type: 'Cloze', question: 'Du er min ___.', answer: 'ven', options: ['ven', 'fjende', 'bil'], instruction: 'Forhold' },
    { id: 'da0-c49', type: 'Cloze', question: 'Husk at sige ___.', answer: 'tak', options: ['tak', 'nej', 'hej'], instruction: 'Høflig' },
    { id: 'da0-c50', type: 'Cloze', question: 'Goddag, jeg ___ Peter.', answer: 'hedder', options: ['hedder', 'er', 'har'], instruction: 'Navn' },
    { id: 'da0-c51', type: 'Cloze', question: 'Farvel og ___ dag.', answer: 'god', options: ['god', 'dårlig', 'blå'], instruction: 'Hilsen' },
  ],
  1: [
    { id: 'da1-c1', type: 'Cloze', question: 'Hunden ___ efter katten.', answer: 'løber', options: ['løber', 'flyver', 'svømmer'], instruction: 'Handling' },
    { id: 'da1-c2', type: 'Cloze', question: 'Katten ___ op i træet.', answer: 'klatrer', options: ['klatrer', 'cykler', 'svømmer'], instruction: 'Handling' },
    { id: 'da1-c3', type: 'Cloze', question: 'Jeg har ___ mønter.', answer: 'mange', options: ['mange', 'stor', 'blå'], instruction: 'Mængde' },
    { id: 'da1-c4', type: 'Cloze', question: 'Han har ___ penge.', answer: 'få', options: ['få', 'meget', 'lang'], instruction: 'Mængde' },
    { id: 'da1-c5', type: 'Cloze', question: 'Bilen er meget ___.', answer: 'hurtig', options: ['hurtig', 'langsom', 'syg'], instruction: 'Fart' },
    { id: 'da1-c6', type: 'Cloze', question: 'Sneglen er meget ___.', answer: 'langsom', options: ['langsom', 'hurtig', 'varm'], instruction: 'Fart' },
    { id: 'da1-c7', type: 'Cloze', question: 'Det er ___ i dag.', answer: 'varmt', options: ['varmt', 'koldt', 'vådt'], instruction: 'Vejr' },
    { id: 'da1-c8', type: 'Cloze', question: 'Det er ___ om vinteren.', answer: 'koldt', options: ['koldt', 'varmt', 'tørt'], instruction: 'Vejr' },
    { id: 'da1-c9', type: 'Cloze', question: 'Jeg skal ___ i seng nu.', answer: 'i', options: ['i', 'på', 'under'], instruction: 'Forholdsord' },
    { id: 'da1-c10', type: 'Cloze', question: 'Bogen ligger ___ bordet.', answer: 'på', options: ['på', 'under', 'i'], instruction: 'Forholdsord' },
    { id: 'da1-c11', type: 'Cloze', question: 'Hunden sover ___ bordet.', answer: 'under', options: ['under', 'over', 'indeni'], instruction: 'Forholdsord' },
    { id: 'da1-c12', type: 'Cloze', question: 'Vi skal ___ til farmor.', answer: 'hjem', options: ['hjem', 'væk', 'ud'], instruction: 'Retning' },
    { id: 'da1-c13', type: 'Cloze', question: 'Jeg ___ en rød cykel.', answer: 'ønsker mig', options: ['ønsker mig', 'er', 'kan'], instruction: 'Lyst' },
    { id: 'da1-c14', type: 'Cloze', question: 'Min far ___ i haven.', answer: 'arbejder', options: ['arbejder', 'sover', 'spiser'], instruction: 'Handling' },
    { id: 'da1-c15', type: 'Cloze', question: 'Min mor ___ mad.', answer: 'laver', options: ['laver', 'læser', 'hopper'], instruction: 'Handling' },
    { id: 'da1-c16', type: 'Cloze', question: 'Jeg ___ min lillebror.', answer: 'hjælper', options: ['hjælper', 'slår', 'bider'], instruction: 'Handling' },
    { id: 'da1-c17', type: 'Cloze', question: 'Babyen ___ meget.', answer: 'sover', options: ['sover', 'arbejder', 'kører'], instruction: 'Handling' },
    { id: 'da1-c18', type: 'Cloze', question: 'Vi ___ mælk hver dag.', answer: 'drikker', options: ['drikker', 'spiser', 'læser'], instruction: 'Handling' },
    { id: 'da1-c19', type: 'Cloze', question: 'Kan du ___ mig sandheden?', answer: 'sige', options: ['sige', 'høre', 'se'], instruction: 'Sprog' },
    { id: 'da1-c20', type: 'Cloze', question: 'Jeg ___ på musik.', answer: 'lytter', options: ['lytter', 'ser', 'taler'], instruction: 'Sans' },
    { id: 'da1-c21', type: 'Cloze', question: 'Jeg ___ en fugl i træet.', answer: 'ser', options: ['ser', 'hører', 'smager'], instruction: 'Sans' },
    { id: 'da1-c22', type: 'Cloze', question: 'Blomsten ___ dejligt.', answer: 'dufter', options: ['dufter', 'lyser', 'larmer'], instruction: 'Sans' },
    { id: 'da1-c23', type: 'Cloze', question: 'Maden ___ godt.', answer: 'smager', options: ['smager', 'hører', 'ser'], instruction: 'Sans' },
    { id: 'da1-c24', type: 'Cloze', question: 'Min taske er ___.', answer: 'tung', options: ['tung', 'let', 'blå'], instruction: 'Beskrivelse' },
    { id: 'da1-c25', type: 'Cloze', question: 'En fjer er ___.', answer: 'let', options: ['let', 'tung', 'rød'], instruction: 'Beskrivelse' },
    { id: 'da1-c26', type: 'Cloze', question: 'Vandet er ___.', answer: 'vådt', options: ['vådt', 'tørt', 'hårdt'], instruction: 'Beskrivelse' },
    { id: 'da1-c27', type: 'Cloze', question: 'Sandet er ___.', answer: 'tørt', options: ['tørt', 'vådt', 'blødt'], instruction: 'Beskrivelse' },
    { id: 'da1-c28', type: 'Cloze', question: 'Stenen er ___.', answer: 'hård', options: ['hård', 'blød', 'varm'], instruction: 'Beskrivelse' },
    { id: 'da1-c29', type: 'Cloze', question: 'Puden er ___.', answer: 'blød', options: ['blød', 'hård', 'kold'], instruction: 'Beskrivelse' },
    { id: 'da1-c30', type: 'Cloze', question: 'Jeg har ___ fingre.', answer: 'ti', options: ['ti', 'to', 'fem'], instruction: 'Tal' },
    { id: 'da1-c31', type: 'Cloze', question: 'Jeg har ___ ben.', answer: 'to', options: ['to', 'fire', 'otte'], instruction: 'Tal' },
    { id: 'da1-c32', type: 'Cloze', question: 'En edderkop har ___ ben.', answer: 'otte', options: ['otte', 'seks', 'fire'], instruction: 'Tal' },
    { id: 'da1-c33', type: 'Cloze', question: 'En flue har ___ ben.', answer: 'seks', options: ['seks', 'otte', 'to'], instruction: 'Tal' },
    { id: 'da1-c34', type: 'Cloze', question: 'Jeg ___ en is i går.', answer: 'fik', options: ['fik', 'får', 'skal have'], instruction: 'Tid' },
    { id: 'da1-c35', type: 'Cloze', question: 'Jeg ___ en is nu.', answer: 'får', options: ['får', 'fik', 'vil have'], instruction: 'Tid' },
    { id: 'da1-c36', type: 'Cloze', question: 'Jeg ___ en is i morgen.', answer: 'vil have', options: ['vil have', 'fik', 'får'], instruction: 'Tid' },
    { id: 'da1-c37', type: 'Cloze', question: 'Det er ___ dag i dag.', answer: 'min', options: ['min', 'din', 'hans'], instruction: 'Eje' },
    { id: 'da1-c38', type: 'Cloze', question: 'Er det ___ cykel?', answer: 'din', options: ['din', 'min', 'hendes'], instruction: 'Eje' },
    { id: 'da1-c39', type: 'Cloze', question: 'Det er ___ hus.', answer: 'vores', options: ['vores', 'deres', 'jeres'], instruction: 'Eje' },
    { id: 'da1-c40', type: 'Cloze', question: 'Katten leger med ___ legetøj.', answer: 'sit', options: ['sit', 'mit', 'dit'], instruction: 'Eje' },
    { id: 'da1-c41', type: 'Cloze', question: 'Jeg kan ___ cykle.', answer: 'godt', options: ['godt', 'ikke', 'aldrig'], instruction: 'Evne' },
    { id: 'da1-c42', type: 'Cloze', question: 'Jeg kan ___ flyve.', answer: 'ikke', options: ['ikke', 'godt', 'altid'], instruction: 'Evne' },
    { id: 'da1-c43', type: 'Cloze', question: 'Vi ___ altid sammen.', answer: 'leger', options: ['leger', 'sover', 'spiser'], instruction: 'Handling' },
    { id: 'da1-c44', type: 'Cloze', question: 'Døren er ___.', answer: 'lukket', options: ['lukket', 'åben', 'blå'], instruction: 'Tilstand' },
    { id: 'da1-c45', type: 'Cloze', question: 'Vinduet er ___.', answer: 'åbent', options: ['åbent', 'lukket', 'rødt'], instruction: 'Tilstand' },
    { id: 'da1-c46', type: 'Cloze', question: 'Lyset er ___.', answer: 'tændt', options: ['tændt', 'slukket', 'gult'], instruction: 'Tilstand' },
    { id: 'da1-c47', type: 'Cloze', question: 'Natten er ___.', answer: 'mørk', options: ['mørk', 'lys', 'varm'], instruction: 'Beskrivelse' },
    { id: 'da1-c48', type: 'Cloze', question: 'Dagen er ___.', answer: 'lys', options: ['lys', 'mørk', 'kold'], instruction: 'Beskrivelse' },
    { id: 'da1-c49', type: 'Cloze', question: 'Jeg er ___ for mørke.', answer: 'bange', options: ['bange', 'glad', 'sur'], instruction: 'Følelse' },
    { id: 'da1-c50', type: 'Cloze', question: 'Jeg er ___ for dig.', answer: 'glad', options: ['glad', 'bange', 'sur'], instruction: 'Følelse' },
    { id: 'da1-c51', type: 'Cloze', question: 'Tak ___ hjælpen.', answer: 'for', options: ['for', 'med', 'til'], instruction: 'Forholdsord' },
  ],
  2: [
    { id: 'da2-c1', type: 'Cloze', question: 'Jeg ___ en bog nu.', answer: 'læser', options: ['læser', 'læste', 'vil læse'], instruction: 'Nutid' },
    { id: 'da2-c2', type: 'Cloze', question: 'Katten ___ mælk hver dag.', answer: 'drikker', options: ['drikker', 'drak', 'drukket'], instruction: 'Nutid' },
    { id: 'da2-c3', type: 'Cloze', question: 'Pigen ___ sin mor med opvasken.', answer: 'hjalp', options: ['hjalp', 'hjælper', 'vil hjælpe'], instruction: 'Datid' },
    { id: 'da2-c4', type: 'Cloze', question: 'I går ___ vi en stor kage.', answer: 'bagte', options: ['bagte', 'bager', 'vil bage'], instruction: 'Datid' },
    { id: 'da2-c5', type: 'Cloze', question: 'Min bror ___ meget hurtigt.', answer: 'løber', options: ['løber', 'løb', 'har løbet'], instruction: 'Nutid' },
    { id: 'da2-c6', type: 'Cloze', question: 'Vi ___ en film i aften.', answer: 'skal se', options: ['skal se', 'så', 'ser'], instruction: 'Fremtid' },
    { id: 'da2-c7', type: 'Cloze', question: 'Hestene ___ på marken.', answer: 'græsser', options: ['græsser', 'græssede', 'har græsset'], instruction: 'Nutid' },
    { id: 'da2-c8', type: 'Cloze', question: 'Barnet ___ efter sin bamse.', answer: 'leder', options: ['leder', 'ledte', 'har ledt'], instruction: 'Nutid' },
    { id: 'da2-c9', type: 'Cloze', question: 'Mormor ___ os en historie.', answer: 'fortalte', options: ['fortalte', 'fortæller', 'fortælt'], instruction: 'Datid' },
    { id: 'da2-c10', type: 'Cloze', question: 'Læreren ___ på tavlen.', answer: 'skriver', options: ['skriver', 'skrev', 'skrevet'], instruction: 'Nutid' },
    { id: 'da2-c11', type: 'Cloze', question: 'Eleverne ___ i klassen.', answer: 'sidder', options: ['sidder', 'sad', 'siddet'], instruction: 'Nutid' },
    { id: 'da2-c12', type: 'Cloze', question: 'Klokken ___ til pause.', answer: 'ringer', options: ['ringer', 'ringede', 'ringet'], instruction: 'Nutid' },
    { id: 'da2-c13', type: 'Cloze', question: 'Vi ___ sammen på legepladsen.', answer: 'leger', options: ['leger', 'legede', 'leget'], instruction: 'Nutid' },
    { id: 'da2-c14', type: 'Cloze', question: 'Fuglen har ___ en rede.', answer: 'bygget', options: ['bygget', 'bygger', 'byggede'], instruction: 'Førnutid' },
    { id: 'da2-c15', type: 'Cloze', question: 'Vandet i søen er ___ koldt.', answer: 'meget', options: ['meget', 'lidt', 'mange'], instruction: 'Mængde' },
    { id: 'da2-c16', type: 'Cloze', question: 'Der er ___ biler på vejen.', answer: 'mange', options: ['mange', 'meget', 'stor'], instruction: 'Mængde' },
    { id: 'da2-c17', type: 'Cloze', question: 'Jeg kan ___ lide æbler.', answer: 'godt', options: ['godt', 'ikke', 'måske'], instruction: 'Mening' },
    { id: 'da2-c18', type: 'Cloze', question: 'Han ___ aldrig sine lektier.', answer: 'glemmer', options: ['glemmer', 'husker', 'laver'], instruction: 'Handling' },
    { id: 'da2-c19', type: 'Cloze', question: 'Husk at ___ din madpakke.', answer: 'spise', options: ['spise', 'drikke', 'smide'], instruction: 'Handling' },
    { id: 'da2-c20', type: 'Cloze', question: 'Må jeg ___ din blyant?', answer: 'låne', options: ['låne', 'købe', 'ødelægge'], instruction: 'Høflig' },
    { id: 'da2-c21', type: 'Cloze', question: 'Tak ___ lånet.', answer: 'for', options: ['for', 'til', 'med'], instruction: 'Høflig' },
    { id: 'da2-c22', type: 'Cloze', question: 'Jeg ___ fra Danmark.', answer: 'kommer', options: ['kommer', 'går', 'bor'], instruction: 'Oprindelse' },
    { id: 'da2-c23', type: 'Cloze', question: 'Hvor ___ du?', answer: 'bor', options: ['bor', 'er', 'har'], instruction: 'Bopæl' },
    { id: 'da2-c24', type: 'Cloze', question: 'Min fødselsdag er ___ juni.', answer: 'i', options: ['i', 'på', 'om'], instruction: 'Tid' },
    { id: 'da2-c25', type: 'Cloze', question: 'Vi skal til fest ___ lørdag.', answer: 'på', options: ['på', 'i', 'om'], instruction: 'Tid' },
    { id: 'da2-c26', type: 'Cloze', question: 'Det bliver mørkt ___ aftenen.', answer: 'om', options: ['om', 'på', 'i'], instruction: 'Tid' },
    { id: 'da2-c27', type: 'Cloze', question: 'Solen står op ___ øst.', answer: 'i', options: ['i', 'på', 'ved'], instruction: 'Retning' },
    { id: 'da2-c28', type: 'Cloze', question: 'Månen lyser ___ natten.', answer: 'om', options: ['om', 'i', 'på'], instruction: 'Tid' },
    { id: 'da2-c29', type: 'Cloze', question: 'En giraffe har en ___ hals.', answer: 'lang', options: ['lang', 'kort', 'tyk'], instruction: 'Krop' },
    { id: 'da2-c30', type: 'Cloze', question: 'Et pindsvin har ___ pigge.', answer: 'mange', options: ['mange', 'få', 'bløde'], instruction: 'Krop' },
    { id: 'da2-c31', type: 'Cloze', question: 'En elefant har en ___ snabel.', answer: 'lang', options: ['lang', 'rød', 'lille'], instruction: 'Krop' },
    { id: 'da2-c32', type: 'Cloze', question: 'Vi ser med ___ øjne.', answer: 'vores', options: ['vores', 'jeres', 'deres'], instruction: 'Eje' },
    { id: 'da2-c33', type: 'Cloze', question: 'Du lytter med ___ ører.', answer: 'dine', options: ['dine', 'mine', 'hans'], instruction: 'Eje' },
    { id: 'da2-c34', type: 'Cloze', question: 'Han går med ___ hund.', answer: 'sin', options: ['sin', 'hans', 'min'], instruction: 'Eje' },
    { id: 'da2-c35', type: 'Cloze', question: 'Hun leger med ___ dukke.', answer: 'sin', options: ['sin', 'hendes', 'din'], instruction: 'Eje' },
    { id: 'da2-c36', type: 'Cloze', question: 'Børnene leger i ___ have.', answer: 'deres', options: ['deres', 'vores', 'mit'], instruction: 'Eje' },
    { id: 'da2-c37', type: 'Cloze', question: 'Hvad ___ klokken?', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Tid' },
    { id: 'da2-c38', type: 'Cloze', question: 'Klokken er ___ to.', answer: 'snart', options: ['snart', 'aldrig', 'altid'], instruction: 'Tid' },
    { id: 'da2-c39', type: 'Cloze', question: 'Jeg kan ___ klokken.', answer: 'se', options: ['se', 'høre', 'smage'], instruction: 'Handling' },
    { id: 'da2-c40', type: 'Cloze', question: 'Han er ___ til at løbe.', answer: 'god', options: ['god', 'dum', 'blå'], instruction: 'Evne' },
    { id: 'da2-c41', type: 'Cloze', question: 'Hun er ___ til at tegne.', answer: 'dygtig', options: ['dygtig', 'sur', 'træt'], instruction: 'Evne' },
    { id: 'da2-c42', type: 'Cloze', question: 'Det er ___ at regne.', answer: 'svært', options: ['svært', 'nemt', 'rødt'], instruction: 'Skole' },
    { id: 'da2-c43', type: 'Cloze', question: 'Jeg kan ___ læse.', answer: 'godt', options: ['godt', 'ikke', 'aldrig'], instruction: 'Evne' },
    { id: 'da2-c44', type: 'Cloze', question: 'Vil du ___ med mig?', answer: 'lege', options: ['lege', 'slås', 'bide'], instruction: 'Social' },
    { id: 'da2-c45', type: 'Cloze', question: 'Vi er ___ venner.', answer: 'gode', options: ['gode', 'dårlige', 'sur'], instruction: 'Social' },
    { id: 'da2-c46', type: 'Cloze', question: 'Jeg vil ___ have en is.', answer: 'gerne', options: ['gerne', 'ikke', 'aldrig'], instruction: 'Lyst' },
    { id: 'da2-c47', type: 'Cloze', question: 'Må jeg ___ få et æble?', answer: 'godt', options: ['godt', 'ikke', 'måske'], instruction: 'Høflig' },
    { id: 'da2-c48', type: 'Cloze', question: 'Værsgo, her ___ det.', answer: 'er', options: ['er', 'var', 'bliver'], instruction: 'Høflig' },
    { id: 'da2-c49', type: 'Cloze', question: 'Tak ___ maden.', answer: 'for', options: ['for', 'til', 'med'], instruction: 'Høflig' },
    { id: 'da2-c50', type: 'Cloze', question: 'Velbekomme, det var så ___.', answer: 'lidt', options: ['lidt', 'meget', 'stort'], instruction: 'Høflig' },
    { id: 'da2-c51', type: 'Cloze', question: 'Hav en ___ dag.', answer: 'god', options: ['god', 'træls', 'blå'], instruction: 'Hilsen' },
    { id: 'da2-c101', type: 'Cloze', question: 'Jeg ___ min ven i skolen.', answer: 'mødte', options: ['mødte', 'møder', 'vil møde'], instruction: 'Datid' },
    { id: 'da2-c102', type: 'Cloze', question: 'Vi ___ en opgave sammen.', answer: 'løste', options: ['løste', 'løser', 'løst'], instruction: 'Datid' },
    { id: 'da2-c103', type: 'Cloze', question: 'Hestene ___ hurtigt på marken.', answer: 'galoperede', options: ['galoperede', 'galoperer', 'galoperet'], instruction: 'Datid' },
    { id: 'da2-c104', type: 'Cloze', question: 'Jeg ___ en tegning til dig.', answer: 'tegner', options: ['tegner', 'tegnede', 'tegnet'], instruction: 'Nutid' },
    { id: 'da2-c105', type: 'Cloze', question: 'Solen ___ lige nu.', answer: 'skinner', options: ['skinner', 'skinnede', 'skinnet'], instruction: 'Nutid' },
    { id: 'da2-c106', type: 'Cloze', question: 'Vi ___ altid pænt goddag.', answer: 'siger', options: ['siger', 'sagde', 'sagt'], instruction: 'Nutid' },
    { id: 'da2-c107', type: 'Cloze', question: 'Husk at ___ dine hænder.', answer: 'vaske', options: ['vaske', 'spise', 'sove'], instruction: 'Handling' },
    { id: 'da2-c108', type: 'Cloze', question: 'Bogen ___ på den øverste hylde.', answer: 'står', options: ['står', 'ligger', 'hænger'], instruction: 'Sted' },
    { id: 'da2-c109', type: 'Cloze', question: 'Jeg ___ mig meget til jul.', answer: 'glæder', options: ['glæder', 'hader', 'bor'], instruction: 'Følelse' },
    { id: 'da2-c110', type: 'Cloze', question: 'Isen ___ i solskinstimerne.', answer: 'smelter', options: ['smelter', 'fryser', 'vokser'], instruction: 'Tilstand' },
    { id: 'da2-c111', type: 'Cloze', question: 'Fuglene ___ mod varmere lande.', answer: 'flyver', options: ['flyver', 'svømmer', 'løber'], instruction: 'Handling' },
    { id: 'da2-c112', type: 'Cloze', question: 'Hvad $(\dots)$ i fjernsynet i aften?', answer: 'kommer', options: ['kommer', 'går', 'ser'], instruction: 'Tid' },
    { id: 'da2-c113', type: 'Cloze', question: 'Vi $(\dots)$ kage for at fejre det.', answer: 'spiser', options: ['spiser', 'drikker', 'læser'], instruction: 'Handling' },
    { id: 'da2-c114', type: 'Cloze', question: ' $(\dots)$ må jeg få en is?', answer: 'Må', options: ['Må', 'Skal', 'Kan'], instruction: 'Høflig' },
    { id: 'da2-c115', type: 'Cloze', question: 'Jeg $(\dots)$ ikke lide sur mælk.', answer: 'kan', options: ['kan', 'vil', 'skal'], instruction: 'Mening' },
    { id: 'da2-c116', type: 'Cloze', question: 'Hvor $(\dots)$ din cykel?', answer: 'er', options: ['er', 'har', 'bor'], instruction: 'Spørgsmål' },
    { id: 'da2-c117', type: 'Cloze', question: 'Tasken $(\dots)$ i hjørnet.', answer: 'står', options: ['står', 'ligger', 'hænger'], instruction: 'Sted' },
    { id: 'da2-c118', type: 'Cloze', question: 'Mine sko $(\dots)$ våde.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Tilstand' },
    { id: 'da2-c119', type: 'Cloze', question: 'Det $(\dots)$ at sne.', answer: 'begynder', options: ['begynder', 'slutter', 'lader'], instruction: 'Vejr' },
    { id: 'da2-c120', type: 'Cloze', question: 'Husk at $(\dots)$ madpakken frem.', answer: 'tage', options: ['tage', 'glemme', 'smide'], instruction: 'Handling' },
    { id: 'da2-c121', type: 'Cloze', question: 'Jeg $(\dots)$ min bedste ven.', answer: 'savner', options: ['savner', 'elsker', 'hader'], instruction: 'Følelse' },
    { id: 'da2-c122', type: 'Cloze', question: 'Kan du $(\dots)$ mig en historie?', answer: 'fortælle', options: ['fortælle', 'læse', 'se'], instruction: 'Social' },
    { id: 'da2-c123', type: 'Cloze', question: 'Vi $(\dots)$ en tur i skoven.', answer: 'gik', options: ['gik', 'løb', 'fløj'], instruction: 'Handling' },
    { id: 'da2-c124', type: 'Cloze', question: 'Blomsterne $(\dots)$ vand.', answer: 'skal have', options: ['skal have', 'fik', 'har'], instruction: 'Behov' },
    { id: 'da2-c125', type: 'Cloze', question: 'Det er $(\dots)$ at lege sammen.', answer: 'sjovt', options: ['sjovt', 'trist', 'kedeligt'], instruction: 'Social' },
    { id: 'da2-c126', type: 'Cloze', question: 'Jeg $(\dots)$ meget efter skole.', answer: 'sover', options: ['sover', 'løber', 'arbejder'], instruction: 'Handling' },
    { id: 'da2-c127', type: 'Cloze', question: 'Husk $(\dots)$ jakke.', answer: 'din', options: ['din', 'min', 'sin'], instruction: 'Eje' },
    { id: 'da2-c128', type: 'Cloze', question: 'Døren $(\dots)$ være lukket.', answer: 'skal', options: ['skal', 'må', 'kan'], instruction: 'Regel' },
    { id: 'da2-c129', type: 'Cloze', question: 'Vinduet $(\dots)$ åbent.', answer: 'er', options: ['er', 'har', 'bliver'], instruction: 'Tilstand' },
    { id: 'da2-c130', type: 'Cloze', question: 'Vi $(\dots)$ pænt i køen.', answer: 'venter', options: ['venter', 'løber', 'skubber'], instruction: 'Social' },
    { id: 'da2-c131', type: 'Cloze', question: 'Jeg $(\dots)$ på tavlen.', answer: 'kigger', options: ['kigger', 'hører', 'smager'], instruction: 'Sans' },
    { id: 'da2-c132', type: 'Cloze', question: 'Læreren $(\dots)$ om dyrene.', answer: 'fortæller', options: ['fortæller', 'glemmer', 'mister'], instruction: 'Skole' },
    { id: 'da2-c133', type: 'Cloze', question: 'Vi $(\dots)$ i vores bøger.', answer: 'skriver', options: ['skriver', 'læser', 'spiser'], instruction: 'Skole' },
    { id: 'da2-c134', type: 'Cloze', question: 'Matematik $(\dots)$ svært i dag.', answer: 'var', options: ['var', 'er', 'bliver'], instruction: 'Tid' },
    { id: 'da2-c135', type: 'Cloze', question: 'Dansk $(\dots)$ mit yndlingsfag.', answer: 'er', options: ['er', 'har', 'kan'], instruction: 'Skole' },
    { id: 'da2-c136', type: 'Cloze', question: 'Pauserne $(\dots)$ alt for korte.', answer: 'er', options: ['er', 'har', 'bliver'], instruction: 'Tid' },
    { id: 'da2-c137', type: 'Cloze', question: 'Vi $(\dots)$ fodbold i går.', answer: 'spillede', options: ['spillede', 'spilte', 'spillet'], instruction: 'Datid' },
    { id: 'da2-c138', type: 'Cloze', question: 'Pigerne $(\dots)$ med dukker.', answer: 'leger', options: ['leger', 'legede', 'leget'], instruction: 'Nutid' },
    { id: 'da2-c139', type: 'Cloze', question: 'Drengene $(\dots)$ hurtigt.', answer: 'løber', options: ['løber', 'løb', 'har løbet'], instruction: 'Nutid' },
    { id: 'da2-c140', type: 'Cloze', question: 'Barnet $(\dots)$ en kiks.', answer: 'fik', options: ['fik', 'får', 'skal have'], instruction: 'Tid' },
    { id: 'da2-c141', type: 'Cloze', question: 'Isen $(\dots)$ dejligt.', answer: 'smager', options: ['smager', 'hører', 'ser'], instruction: 'Sans' },
    { id: 'da2-c142', type: 'Cloze', question: 'Husk at $(\dots)$ hej.', answer: 'sige', options: ['sige', 'høre', 'gribe'], instruction: 'Social' },
    { id: 'da2-c143', type: 'Cloze', question: 'Tasken $(\dots)$ på gulvet.', answer: 'ligger', options: ['ligger', 'står', 'hænger'], instruction: 'Sted' },
    { id: 'da2-c144', type: 'Cloze', question: 'Jeg $(\dots)$ træt nu.', answer: 'er', options: ['er', 'har', 'bliver'], instruction: 'Tilstand' },
    { id: 'da2-c145', type: 'Cloze', question: 'Det $(\dots)$ at regne.', answer: 'begynder', options: ['begynder', 'slutter', 'lader'], instruction: 'Vejr' },
    { id: 'da2-c146', type: 'Cloze', question: 'Husk at $(\dots)$ madpakken.', answer: 'huske', options: ['huske', 'glemme', 'spise'], instruction: 'Handling' },
    { id: 'da2-c147', type: 'Cloze', question: 'Vi $(\dots)$ en film i biografen.', answer: 'så', options: ['så', 'ser', 'skal se'], instruction: 'Tid' },
    { id: 'da2-c148', type: 'Cloze', question: 'Isen $(\dots)$ i solen.', answer: 'smelter', options: ['smelter', 'fryser', 'vokser'], instruction: 'Tilstand' },
    { id: 'da2-c149', type: 'Cloze', question: 'Godnat $(\dots)$ sov godt.', answer: 'og', options: ['og', 'men', 'eller'], instruction: 'Hilsen' },
    { id: 'da2-c150', type: 'Cloze', question: 'Vi ses $(\dots)$ i morgen.', answer: 'igen', options: ['igen', 'aldrig', 'altid'], instruction: 'Social' },
    { id: 'da2-c151', type: 'Cloze', question: 'Dansk Grade 2 $(\dots)$ færdig.', answer: 'er', options: ['er', 'har', 'bliver'], instruction: 'Meta' },
  ],
  3: [
    { id: 'da3-c1', type: 'Cloze', question: 'Huset ___ af røde mursten.', answer: 'er bygget', options: ['er bygget', 'er spist', 'er løbet'], instruction: 'Tilstand' },
    { id: 'da3-c2', type: 'Cloze', question: 'Bilen ___ hurtigt hen ad vejen.', answer: 'kørte', options: ['kørte', 'fløj', 'svømmede'], instruction: 'Datid' },
    { id: 'da3-c3', type: 'Cloze', question: 'Vi ___ en spændende bog i skolen.', answer: 'læser', options: ['læser', 'spiser', 'drikker'], instruction: 'Handling' },
    { id: 'da3-c4', type: 'Cloze', question: 'I går ___ det hele dagen.', answer: 'regnede', options: ['regnede', 'skinnede', 'blæste'], instruction: 'Vejr' },
    { id: 'da3-c5', type: 'Cloze', question: 'Min mor ___ en lækker kage.', answer: 'bagte', options: ['bagte', 'købte', 'fandt'], instruction: 'Handling' },
    { id: 'da3-c6', type: 'Cloze', question: 'Hunden ___ efter bolden.', answer: 'løb', options: ['løb', 'sov', 'spiste'], instruction: 'Handling' },
    { id: 'da3-c7', type: 'Cloze', question: 'Solen ___ fra en skyfri himmel.', answer: 'skinner', options: ['skinner', 'regner', 'blæser'], instruction: 'Vejr' },
    { id: 'da3-c8', type: 'Cloze', question: 'Vi ___ altid vores lektier.', answer: 'laver', options: ['laver', 'glemmer', 'mister'], instruction: 'Handling' },
    { id: 'da3-c9', type: 'Cloze', question: 'I frikvarteret ___ vi fodbold.', answer: 'spiller', options: ['spiller', 'læser', 'sover'], instruction: 'Handling' },
    { id: 'da3-c10', type: 'Cloze', question: 'Min far ___ i et stort firma.', answer: 'arbejder', options: ['arbejder', 'bor', 'spiser'], instruction: 'Handling' },
    { id: 'da3-c11', type: 'Cloze', question: 'De ___ til udlandet i sommerferien.', answer: 'rejste', options: ['rejste', 'blev', 'sov'], instruction: 'Handling' },
    { id: 'da3-c12', type: 'Cloze', question: 'Jeg ___ mig meget til jul.', answer: 'glæder', options: ['glæder', 'gruer', 'hader'], instruction: 'Følelse' },
    { id: 'da3-c13', type: 'Cloze', question: 'Barnet ___ fordi det slog sig.', answer: 'græder', options: ['græder', 'griner', 'sover'], instruction: 'Handling' },
    { id: 'da3-c14', type: 'Cloze', question: 'Vi ___ en sang til fødselsdagen.', answer: 'sang', options: ['sang', 'spiste', 'læste'], instruction: 'Handling' },
    { id: 'da3-c15', type: 'Cloze', question: 'Husk at ___ døren efter dig.', answer: 'lukke', options: ['lukke', 'åbne', 'låse'], instruction: 'Handling' },
    { id: 'da3-c16', type: 'Cloze', question: 'Lyset skal ___ når man går.', answer: 'slukkes', options: ['slukkes', 'tændes', 'flyttes'], instruction: 'Handling' },
    { id: 'da3-c17', type: 'Cloze', question: 'Vandet i elkedlen ___.', answer: 'koger', options: ['koger', 'fryser', 'smager'], instruction: 'Tilstand' },
    { id: 'da3-c18', type: 'Cloze', question: 'Isen ___ i solskinnet.', answer: 'smelter', options: ['smelter', 'fryser', 'vokser'], instruction: 'Tilstand' },
    { id: 'da3-c19', type: 'Cloze', question: 'Blomsterne ___ smukt i haven.', answer: 'blomstrer', options: ['blomstrer', 'visner', 'sover'], instruction: 'Tilstand' },
    { id: 'da3-c20', type: 'Cloze', question: 'Blade falder af træerne om ___.', answer: 'efteråret', options: ['efteråret', 'foråret', 'sommeren'], instruction: 'Årstid' },
    { id: 'da3-c21', type: 'Cloze', question: 'Alt bliver grønt om ___.', answer: 'foråret', options: ['foråret', 'vinteren', 'efteråret'], instruction: 'Årstid' },
    { id: 'da3-c22', type: 'Cloze', question: 'Vi bader i havet om ___.', answer: 'sommeren', options: ['sommeren', 'vinteren', 'efteråret'], instruction: 'Årstid' },
    { id: 'da3-c23', type: 'Cloze', question: 'Der er sne om ___.', answer: 'vinteren', options: ['vinteren', 'sommeren', 'foråret'], instruction: 'Årstid' },
    { id: 'da3-c24', type: 'Cloze', question: 'En uge har ___ dage.', answer: 'syv', options: ['syv', 'fem', 'ti'], instruction: 'Tal' },
    { id: 'da3-c25', type: 'Cloze', question: 'Et år har tolv ___.', answer: 'måneder', options: ['måneder', 'uger', 'dage'], instruction: 'Tid' },
    { id: 'da3-c26', type: 'Cloze', question: 'En time har tres ___.', answer: 'minutter', options: ['minutter', 'sekunder', 'timer'], instruction: 'Tid' },
    { id: 'da3-c27', type: 'Cloze', question: 'Et minut har tres ___.', answer: 'sekunder', options: ['sekunder', 'minutter', 'timer'], instruction: 'Tid' },
    { id: 'da3-c28', type: 'Cloze', question: 'I dag er det ___, i går var det fredag.', answer: 'lørdag', options: ['lørdag', 'søndag', 'mandag'], instruction: 'Ugedag' },
    { id: 'da3-c29', type: 'Cloze', question: 'I morgen er det ___, i dag er det onsdag.', answer: 'torsdag', options: ['torsdag', 'tirsdag', 'fredag'], instruction: 'Ugedag' },
    { id: 'da3-c30', type: 'Cloze', question: 'Januar er den ___ måned i året.', answer: 'første', options: ['første', 'sidste', 'anden'], instruction: 'Ordenstal' },
    { id: 'da3-c31', type: 'Cloze', question: 'December er den ___ måned i året.', answer: 'sidste', options: ['sidste', 'første', 'midterste'], instruction: 'Ordenstal' },
    { id: 'da3-c32', type: 'Cloze', question: 'Vi spiser frokost midt på ___.', answer: 'dagen', options: ['dagen', 'natten', 'morgenen'], instruction: 'Tid' },
    { id: 'da3-c33', type: 'Cloze', question: 'Stjernerne lyser om ___.', answer: 'natten', options: ['natten', 'dagen', 'aftenen'], instruction: 'Tid' },
    { id: 'da3-c34', type: 'Cloze', question: 'Solen står op om ___.', answer: 'morgenen', options: ['morgenen', 'aftenen', 'natten'], instruction: 'Tid' },
    { id: 'da3-c35', type: 'Cloze', question: 'Solen går ned om ___.', answer: 'aftenen', options: ['aftenen', 'morgenen', 'middagen'], instruction: 'Tid' },
    { id: 'da3-c36', type: 'Cloze', question: 'Mælken står i ___.', answer: 'køleskabet', options: ['køleskabet', 'ovnen', 'sengen'], instruction: 'Hjem' },
    { id: 'da3-c37', type: 'Cloze', question: 'Maden laves på ___.', answer: 'komfuret', options: ['komfuret', 'bordet', 'gulvet'], instruction: 'Hjem' },
    { id: 'da3-c38', type: 'Cloze', question: 'Vi sover i en ___.', answer: 'seng', options: ['seng', 'stol', 'bil'], instruction: 'Hjem' },
    { id: 'da3-c39', type: 'Cloze', question: 'Vi børster tænder på ___.', answer: 'badeværelset', options: ['badeværelset', 'køkkenet', 'stuen'], instruction: 'Hjem' },
    { id: 'da3-c40', type: 'Cloze', question: 'Vi ser fjernsyn i ___.', answer: 'stuen', options: ['stuen', 'haven', 'skuret'], instruction: 'Hjem' },
    { id: 'da3-c41', type: 'Cloze', question: 'Bilen holder i ___.', answer: 'garagen', options: ['garagen', 'stuen', 'køkkenet'], instruction: 'Hjem' },
    { id: 'da3-c42', type: 'Cloze', question: 'Tøjet ligger i ___.', answer: 'skabet', options: ['skabet', 'madkassen', 'vasken'], instruction: 'Hjem' },
    { id: 'da3-c43', type: 'Cloze', question: 'Vi vasker tøj i ___.', answer: 'vaskemaskinen', options: ['vaskemaskinen', 'opvaskemaskinen', 'ovnen'], instruction: 'Hjem' },
    { id: 'da3-c44', type: 'Cloze', question: 'Tallerkenerne vaskes i ___.', answer: 'opvaskemaskinen', options: ['opvaskemaskinen', 'vaskemaskinen', 'tørretumbleren'], instruction: 'Hjem' },
    { id: 'da3-c45', type: 'Cloze', question: 'Støvsugeren fjerner ___.', answer: 'støv', options: ['støv', 'vand', 'mad'], instruction: 'Hjem' },
    { id: 'da3-c46', type: 'Cloze', question: 'Vi bager brød i ___.', answer: 'ovnen', options: ['ovnen', 'køleskabet', 'vasken'], instruction: 'Hjem' },
    { id: 'da3-c47', type: 'Cloze', question: 'Grøntsagerne vokser i ___.', answer: 'haven', options: ['haven', 'stuen', 'loftet'], instruction: 'Hjem' },
    { id: 'da3-c48', type: 'Cloze', question: 'Posten kommer i ___.', answer: 'postkassen', options: ['postkassen', 'skraldespanden', 'vasken'], instruction: 'Hjem' },
    { id: 'da3-c49', type: 'Cloze', question: 'Skraldet smides i ___.', answer: 'skraldespanden', options: ['skraldespanden', 'postkassen', 'skabet'], instruction: 'Hjem' },
    { id: 'da3-c50', type: 'Cloze', question: 'Døren åbnes med en ___.', answer: 'nøgle', options: ['nøgle', 'ske', 'bog'], instruction: 'Hjem' },
    { id: 'da3-c51', type: 'Cloze', question: 'Vi ringer på ___.', answer: 'dørklokken', options: ['dørklokken', 'vinduet', 'taget'], instruction: 'Hjem' },
  ],
  4: [
    { id: 'da4-c1', type: 'Cloze', question: 'Hvilken ___ er din yndlings?', answer: 'farve', options: ['farve', 'bil', 'mad'], instruction: 'Spørgsmål' },
    { id: 'da4-c2', type: 'Cloze', question: 'Hvor ___ du henne i går?', answer: 'var', options: ['var', 'er', 'bliver'], instruction: 'Tid' },
    { id: 'da4-c3', type: 'Cloze', question: 'Hvem ___ du i telefonen?', answer: 'talte med', options: ['talte med', 'spiste med', 'sov med'], instruction: 'Handling' },
    { id: 'da4-c4', type: 'Cloze', question: 'Hvornår ___ du i skole?', answer: 'møder', options: ['møder', 'sover', 'spiser'], instruction: 'Skole' },
    { id: 'da4-c5', type: 'Cloze', question: 'Hvad ___ du til aftensmad?', answer: 'fik', options: ['fik', 'er', 'går'], instruction: 'Handling' },
    { id: 'da4-c6', type: 'Cloze', question: 'Hvorfor ___ du?', answer: 'griner', options: ['griner', 'sover', 'kører'], instruction: 'Følelse' },
    { id: 'da4-c7', type: 'Cloze', question: 'Hvordan ___ man denne opgave?', answer: 'løser', options: ['løser', 'spiser', 'drikker'], instruction: 'Skole' },
    { id: 'da4-c8', type: 'Cloze', question: 'Jeg ___ at spille computer.', answer: 'elsker', options: ['elsker', 'hader', 'bor'], instruction: 'Lyst' },
    { id: 'da4-c9', type: 'Cloze', question: 'Min hund ___ meget højt.', answer: 'gør', options: ['gør', 'mjavre', 'piber'], instruction: 'Lyd' },
    { id: 'da4-c10', type: 'Cloze', question: 'Katten ___ når den er glad.', answer: 'spinder', options: ['spinder', 'gør', 'hveser'], instruction: 'Lyd' },
    { id: 'da4-c11', type: 'Cloze', question: 'Hesten ___ hen over marken.', answer: 'galoperer', options: ['galoperer', 'svømmer', 'flyver'], instruction: 'Handling' },
    { id: 'da4-c12', type: 'Cloze', question: 'Fuglen har ___ æg i reden.', answer: 'lagt', options: ['lagt', 'spist', 'mistet'], instruction: 'Natur' },
    { id: 'da4-c13', type: 'Cloze', question: 'Koen ___ på sit græs.', answer: 'tygger', options: ['tygger', 'læser', 'hopper'], instruction: 'Natur' },
    { id: 'da4-c14', type: 'Cloze', question: 'Fåret har meget ___ uld.', answer: 'blødt', options: ['blødt', 'hårdt', 'blåt'], instruction: 'Natur' },
    { id: 'da4-c15', type: 'Cloze', question: 'Grisen ___ i mudderet.', answer: 'ruller sig', options: ['ruller sig', 'vasker sig', 'flyver'], instruction: 'Natur' },
    { id: 'da4-c16', type: 'Cloze', question: 'Bonden ___ kornet på marken.', answer: 'høster', options: ['høster', 'sår', 'spiser'], instruction: 'Erhverv' },
    { id: 'da4-c17', type: 'Cloze', question: 'Gartneren ___ blomsterne.', answer: 'vander', options: ['vander', 'spiser', 'klipper'], instruction: 'Erhverv' },
    { id: 'da4-c18', type: 'Cloze', question: 'Bageren bager ___ hver morgen.', answer: 'brød', options: ['brød', 'sten', 'sko'], instruction: 'Erhverv' },
    { id: 'da4-c19', type: 'Cloze', question: 'Politiet ___ de kriminelle.', answer: 'fanger', options: ['fanger', 'hjælper', 'fodrer'], instruction: 'Erhverv' },
    { id: 'da4-c20', type: 'Cloze', question: 'Lægen ___ de syge folk.', answer: 'undersøger', options: ['undersøger', 'spiser', 'slår'], instruction: 'Erhverv' },
    { id: 'da4-c21', type: 'Cloze', question: 'Brandmanden ___ ilden.', answer: 'slukker', options: ['slukker', 'tænder', 'ser på'], instruction: 'Erhverv' },
    { id: 'da4-c22', type: 'Cloze', question: 'Frisøren ___ mit hår.', answer: 'klipper', options: ['klipper', 'vasker', 'farver'], instruction: 'Erhverv' },
    { id: 'da4-c23', type: 'Cloze', question: 'Tømreren ___ et nyt hus.', answer: 'bygger', options: ['bygger', 'spiser', 'tegner'], instruction: 'Erhverv' },
    { id: 'da4-c24', type: 'Cloze', question: 'Mureren bruger ___ til muren.', answer: 'sten', options: ['sten', 'træ', 'glas'], instruction: 'Erhverv' },
    { id: 'da4-c25', type: 'Cloze', question: 'Maleren maler ___ på væggen.', answer: 'maling', options: ['maling', 'vand', 'mad'], instruction: 'Erhverv' },
    { id: 'da4-c26', type: 'Cloze', question: 'Kokken laver ___ mad.', answer: 'lækker', options: ['lækker', 'dårlig', 'blå'], instruction: 'Erhverv' },
    { id: 'da4-c27', type: 'Cloze', question: 'Tjeneren ___ maden ved bordet.', answer: 'serverer', options: ['serverer', 'spiser', 'kaster'], instruction: 'Erhverv' },
    { id: 'da4-c28', type: 'Cloze', question: 'Chaufføren ___ bussen.', answer: 'kører', options: ['kører', 'flyver', 'svømmer'], instruction: 'Erhverv' },
    { id: 'da4-c29', type: 'Cloze', question: 'Piloten flyver med et ___.', answer: 'fly', options: ['fly', 'skib', 'tog'], instruction: 'Erhverv' },
    { id: 'da4-c30', type: 'Cloze', question: 'Sømanden sejler på et ___.', answer: 'skib', options: ['skib', 'fly', 'bil'], instruction: 'Erhverv' },
    { id: 'da4-c31', type: 'Cloze', question: 'Læreren ___ os nye ting.', answer: 'lærer', options: ['lærer', 'glemmer', 'slår'], instruction: 'Erhverv' },
    { id: 'da4-c32', type: 'Cloze', question: 'Eleverne ___ lektier hver dag.', answer: 'laver', options: ['laver', 'læser', 'spiser'], instruction: 'Skole' },
    { id: 'da4-c33', type: 'Cloze', question: 'Vi skriver i vores ___.', answer: 'hæfter', options: ['hæfter', 'bøger', 'munde'], instruction: 'Skole' },
    { id: 'da4-c34', type: 'Cloze', question: 'Vi læser i spændende ___.', answer: 'bøger', options: ['bøger', 'hæfter', 'blade'], instruction: 'Skole' },
    { id: 'da4-c35', type: 'Cloze', question: 'Biblioteket har mange ___.', answer: 'bøger', options: ['bøger', 'madpakker', 'sko'], instruction: 'Skole' },
    { id: 'da4-c36', type: 'Cloze', question: 'Vi ___ matematik i skolen.', answer: 'regner', options: ['regner', 'synger', 'danser'], instruction: 'Skole' },
    { id: 'da4-c37', type: 'Cloze', question: 'Vi ___ dansk i skolen.', answer: 'lærer', options: ['lærer', 'glemmer', 'taber'], instruction: 'Skole' },
    { id: 'da4-c38', type: 'Cloze', question: 'Vi ___ engelsk i skolen.', answer: 'taler', options: ['taler', 'spiser', 'løber'], instruction: 'Skole' },
    { id: 'da4-c39', type: 'Cloze', question: 'Idræt er ___ i gymnastiksalen.', answer: 'sjovt', options: ['sjovt', 'kedeligt', 'trist'], instruction: 'Skole' },
    { id: 'da4-c40', type: 'Cloze', question: 'Musik er godt at ___ til.', answer: 'danse', options: ['danse', 'sove', 'læse'], instruction: 'Skole' },
    { id: 'da4-c41', type: 'Cloze', question: 'Vi tegner i ___.', answer: 'billedkunst', options: ['billedkunst', 'matematik', 'idræt'], instruction: 'Skole' },
    { id: 'da4-c42', type: 'Cloze', question: 'Natur og teknik handler om ___.', answer: 'naturen', options: ['naturen', 'historie', 'musik'], instruction: 'Skole' },
    { id: 'da4-c43', type: 'Cloze', question: 'Historie handler om ___.', answer: 'fortiden', options: ['fortiden', 'fremtiden', 'nuet'], instruction: 'Skole' },
    { id: 'da4-c44', type: 'Cloze', question: 'Geografi handler om ___.', answer: 'verden', options: ['verden', 'tal', 'ord'], instruction: 'Skole' },
    { id: 'da4-c45', type: 'Cloze', question: 'Kristendom handler om ___.', answer: 'tro', options: ['tro', 'videnskab', 'mad'], instruction: 'Skole' },
    { id: 'da4-c46', type: 'Cloze', question: 'Pauserne er gode til at ___ i.', answer: 'lege', options: ['lege', 'sove', 'arbejde'], instruction: 'Skole' },
    { id: 'da4-c47', type: 'Cloze', question: 'SFO er efter ___.', answer: 'skole', options: ['skole', 'nat', 'ferie'], instruction: 'Skole' },
    { id: 'da4-c48', type: 'Cloze', question: 'Ferierne er ___.', answer: 'lange', options: ['lange', 'korte', 'blå'], instruction: 'Skole' },
    { id: 'da4-c49', type: 'Cloze', question: 'Skolen starter klokken ___.', answer: 'otte', options: ['otte', 'ti', 'tolv'], instruction: 'Skole' },
    { id: 'da4-c50', type: 'Cloze', question: 'Vi glæder os til ___.', answer: 'weekend', options: ['weekend', 'lektier', 'mandag'], instruction: 'Skole' },
    { id: 'da4-c51', type: 'Cloze', question: 'Husk at ___ din bog.', answer: 'læse', options: ['læse', 'spise', 'smide'], instruction: 'Skole' },
  ],
};
