/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const ENGELSK_CLOZE_P2: Partial<Record<Grade, GameContent[]>> = {
  5: [
    { id: 'en5-c1', type: 'Cloze', question: 'The astronaut ___ in space.', answer: 'floats', options: ['floats', 'runs', 'falls'], instruction: 'Science' },
    { id: 'en5-c2', type: 'Cloze', question: 'The volcano ___ and emitted lava.', answer: 'erupted', options: ['erupted', 'slept', 'sang'], instruction: 'Nature' },
    { id: 'en5-c3', type: 'Cloze', question: 'The Earth ___ around the sun.', answer: 'rotates', options: ['rotates', 'stands', 'hangs'], instruction: 'Science' },
    { id: 'en5-c4', type: 'Cloze', question: 'The moon is ___ satellite.', answer: 'Earth\'s', options: ['Earth\'s', 'Sun\'s', 'Mars'], instruction: 'Science' },
    { id: 'en5-c5', type: 'Cloze', question: 'Plants use ___ for photosynthesis.', answer: 'sunlight', options: ['sunlight', 'darkness', 'milk'], instruction: 'Biology' },
    { id: 'en5-c6', type: 'Cloze', question: 'Humans breathe ___ through lungs.', answer: 'air', options: ['air', 'water', 'food'], instruction: 'Biology' },
    { id: 'en5-c7', type: 'Cloze', question: 'The heart ___ blood around the body.', answer: 'pumps', options: ['pumps', 'sucks', 'cleans'], instruction: 'Biology' },
    { id: 'en5-c8', type: 'Cloze', question: 'The brain ___ our thoughts and feelings.', answer: 'controls', options: ['controls', 'forgets', 'loses'], instruction: 'Biology' },
    { id: 'en5-c9', type: 'Cloze', question: 'The skeleton ___ our body upright.', answer: 'holds', options: ['holds', 'drops', 'lays'], instruction: 'Biology' },
    { id: 'en5-c10', type: 'Cloze', question: 'Muscles enable us to ___.', answer: 'move', options: ['move', 'think', 'sleep'], instruction: 'Biology' },
    { id: 'en5-c11', type: 'Cloze', question: 'Digestion starts in the ___.', answer: 'mouth', options: ['mouth', 'stomach', 'intestine'], instruction: 'Biology' },
    { id: 'en5-c12', type: 'Cloze', question: 'Blood contains ___ that carries oxygen.', answer: 'iron', options: ['iron', 'gold', 'silver'], instruction: 'Biology' },
    { id: 'en5-c13', type: 'Cloze', question: 'We smell with our ___.', answer: 'nose', options: ['nose', 'mouth', 'eye'], instruction: 'Senses' },
    { id: 'en5-c14', type: 'Cloze', question: 'We taste with our ___.', answer: 'tongue', options: ['tongue', 'teeth', 'lips'], instruction: 'Senses' },
    { id: 'en5-c15', type: 'Cloze', question: 'We hear with our ___.', answer: 'ears', options: ['ears', 'eyes', 'nose'], instruction: 'Senses' },
    { id: 'en5-c16', type: 'Cloze', question: 'We see with our ___.', answer: 'eyes', options: ['eyes', 'ears', 'mouth'], instruction: 'Senses' },
    { id: 'en5-c17', type: 'Cloze', question: 'We feel with our ___.', answer: 'skin', options: ['skin', 'hair', 'nails'], instruction: 'Senses' },
    { id: 'en5-c18', type: 'Cloze', question: 'It is important to ___ healthily.', answer: 'eat', options: ['eat', 'sleep', 'run'], instruction: 'Health' },
    { id: 'en5-c19', type: 'Cloze', question: 'Exercise makes the body ___.', answer: 'strong', options: ['strong', 'weak', 'blue'], instruction: 'Health' },
    { id: 'en5-c20', type: 'Cloze', question: 'Sleep is important for the body\'s ___.', answer: 'recovery', options: ['recovery', 'car', 'house'], instruction: 'Health' },
    { id: 'en5-c21', type: 'Cloze', question: 'Brush teeth two ___ a day.', answer: 'times', options: ['times', 'hours', 'days'], instruction: 'Health' },
    { id: 'en5-c22', type: 'Cloze', question: 'Wash hands before ___.', answer: 'meals', options: ['meals', 'night', 'play'], instruction: 'Health' },
    { id: 'en5-c23', type: 'Cloze', question: 'Drink plenty of ___ when it is hot.', answer: 'water', options: ['water', 'juice', 'coffee'], instruction: 'Health' },
    { id: 'en5-c24', type: 'Cloze', question: 'Fresh air is ___ for health.', answer: 'good', options: ['good', 'bad', 'dangerous'], instruction: 'Health' },
    { id: 'en5-c25', type: 'Cloze', question: 'Sweets and cake contain a lot of ___.', answer: 'sugar', options: ['sugar', 'salt', 'pepper'], instruction: 'Health' },
    { id: 'en5-c26', type: 'Cloze', question: 'Every year a ___ day is held at school.', answer: 'sports', options: ['sports', 'night', 'sleep'], instruction: 'School' },
    { id: 'en5-c27', type: 'Cloze', question: 'We should ___ nicely to each other.', answer: 'speak', options: ['speak', 'shout', 'hit'], instruction: 'Social' },
    { id: 'en5-c28', type: 'Cloze', question: 'One should ___ for one\'s friends.', answer: 'care', options: ['care', 'hate', 'scream'], instruction: 'Social' },
    { id: 'en5-c29', type: 'Cloze', question: 'It is ___ to be a good friend.', answer: 'important', options: ['important', 'stupid', 'irrelevant'], instruction: 'Social' },
    { id: 'en5-c30', type: 'Cloze', question: 'Bullying is ___ in our school.', answer: 'forbidden', options: ['forbidden', 'allowed', 'good'], instruction: 'Social' },
    { id: 'en5-c31', type: 'Cloze', question: 'We solve ___ by talking together.', answer: 'conflicts', options: ['conflicts', 'food', 'homework'], instruction: 'Social' },
    { id: 'en5-c32', type: 'Cloze', question: 'We ___ in groups in the class.', answer: 'collaborate', options: ['collaborate', 'sleep', 'eat'], instruction: 'Social' },
    { id: 'en5-c33', type: 'Cloze', question: 'Everyone should ___ be part of the play.', answer: 'be allowed to', options: ['be allowed to', 'not', 'never'], instruction: 'Social' },
    { id: 'en5-c34', type: 'Cloze', question: 'Respect means to ___ others.', answer: 'accept', options: ['accept', 'hate', 'hit'], instruction: 'Social' },
    { id: 'en5-c35', type: 'Cloze', question: 'Empathy is being able to ___ others\' feelings.', answer: 'understand', options: ['understand', 'forget', 'overlook'], instruction: 'Social' },
    { id: 'en5-c36', type: 'Cloze', question: 'We celebrate ___ in the class.', answer: 'birthdays', options: ['birthdays', 'nights', 'rain'], instruction: 'Social' },
    { id: 'en5-c37', type: 'Cloze', question: 'Christmas is the ___ of hearts.', answer: 'festival', options: ['festival', 'day', 'week'], instruction: 'Culture' },
    { id: 'en5-c38', type: 'Cloze', question: 'Easter is celebrated with ___ and hares.', answer: 'eggs', options: ['eggs', 'cars', 'hats'], instruction: 'Culture' },
    { id: 'en5-c39', type: 'Cloze', question: 'Halloween is ___ at night.', answer: 'scary', options: ['scary', 'nice', 'pink'], instruction: 'Culture' },
    { id: 'en5-c40', type: 'Cloze', question: 'Saint John\'s Eve is celebrated with a ___.', answer: 'bonfire', options: ['bonfire', 'water', 'snow'], instruction: 'Culture' },
    { id: 'en5-c41', type: 'Cloze', question: 'Constitution Day is on the fifth of ___.', answer: 'June', options: ['June', 'July', 'May'], instruction: 'Culture' },
    { id: 'en5-c42', type: 'Cloze', question: 'Denmark\'s flag is called ___.', answer: 'Dannebrog', options: ['Dannebrog', 'Union Jack', 'Stars and Stripes'], instruction: 'Culture' },
    { id: 'en5-c43', type: 'Cloze', question: 'The Prime Minister ___ the country.', answer: 'leads', options: ['leads', 'eats', 'builds'], instruction: 'Society' },
    { id: 'en5-c44', type: 'Cloze', question: 'The King lives in a ___.', answer: 'castle', options: ['castle', 'house', 'tent'], instruction: 'Society' },
    { id: 'en5-c45', type: 'Cloze', question: 'The Parliament is located at ___.', answer: 'Christiansborg', options: ['Christiansborg', 'City Hall', 'School'], instruction: 'Society' },
    { id: 'en5-c46', type: 'Cloze', question: 'Denmark is a ___.', answer: 'democracy', options: ['democracy', 'monarchy', 'dictatorship'], instruction: 'Society' },
    { id: 'en5-c47', type: 'Cloze', question: 'We have ___ in Denmark.', answer: 'freedom of speech', options: ['freedom of speech', 'no food', 'no school'], instruction: 'Society' },
    { id: 'en5-c48', type: 'Cloze', question: 'You must be ___ years old to vote.', answer: 'eighteen', options: ['eighteen', 'six', 'five'], instruction: 'Society' },
    { id: 'en5-c49', type: 'Cloze', question: 'We pay ___ to the state.', answer: 'taxes', options: ['taxes', 'money', 'sweets'], instruction: 'Society' },
    { id: 'en5-c50', type: 'Cloze', question: 'The capital of England is ___.', answer: 'London', options: ['London', 'Paris', 'Berlin'], instruction: 'Geography' },
    { id: 'en5-c51', type: 'Cloze', question: 'The capital of America is ___.', answer: 'Washington D.C.', options: ['Washington D.C.', 'New York', 'Los Angeles'], instruction: 'Geography' },
  ],
  6: [
    { id: 'en6-c1', type: 'Cloze', question: 'The author uses ___ to create images.', answer: 'metaphors', options: ['metaphors', 'numbers', 'colors'], instruction: 'Literature' },
    { id: 'en6-c2', type: 'Cloze', question: 'The protagonist undergoes a major ___.', answer: 'development', options: ['development', 'car', 'dinner'], instruction: 'Analysis' },
    { id: 'en6-c3', type: 'Cloze', question: 'The action takes place in a ___ environment.', answer: 'sad', options: ['sad', 'happy', 'funny'], instruction: 'Analysis' },
    { id: 'en6-c4', type: 'Cloze', question: 'The message in the text is ___ important.', answer: 'very', options: ['very', 'never', 'blue'], instruction: 'Analysis' },
    { id: 'en6-c5', type: 'Cloze', question: 'The poet uses ___ to create rhythm.', answer: 'rhymes', options: ['rhymes', 'words', 'songs'], instruction: 'Poetry' },
    { id: 'en6-c6', type: 'Cloze', question: 'The short story ends with a ___.', answer: 'surprise', options: ['surprise', 'beginning', 'wash'], instruction: 'Genre' },
    { id: 'en6-c7', type: 'Cloze', question: 'Fairytales often start with "Once upon a ___".', answer: 'time', options: ['time', 'never', 'now'], instruction: 'Genre' },
    { id: 'en6-c8', type: 'Cloze', question: 'The fable often has a ___ moral.', answer: 'clear', options: ['clear', 'secret', 'crazy'], instruction: 'Genre' },
    { id: 'en6-c9', type: 'Cloze', question: 'The novel is divided into ___.', answer: 'chapters', options: ['chapters', 'pages', 'words'], instruction: 'Literature' },
    { id: 'en6-c10', type: 'Cloze', question: 'The story is told by a ___.', answer: 'narrator', options: ['narrator', 'reader', 'car'], instruction: 'Analysis' },
    { id: 'en6-c11', type: 'Cloze', question: 'We analyze the text\'s ___.', answer: 'composition', options: ['composition', 'color', 'weight'], instruction: 'Analysis' },
    { id: 'en6-c12', type: 'Cloze', question: 'The theme of the book is ___.', answer: 'friendship', options: ['friendship', 'food', 'weather'], instruction: 'Analysis' },
    { id: 'en6-c13', type: 'Cloze', question: 'The language in the text is ___ and descriptive.', answer: 'vivid', options: ['vivid', 'boring', 'stiff'], instruction: 'Analysis' },
    { id: 'en6-c14', type: 'Cloze', question: 'We look at the characters\' ___ in the text.', answer: 'relationships', options: ['relationships', 'shoes', 'houses'], instruction: 'Analysis' },
    { id: 'en6-c15', type: 'Cloze', question: 'The setting description is very ___.', answer: 'detailed', options: ['detailed', 'superficial', 'blue'], instruction: 'Analysis' },
    { id: 'en6-c16', type: 'Cloze', question: 'The conflict arises when ___ happens.', answer: 'something', options: ['something', 'nothing', 'everything'], instruction: 'Analysis' },
    { id: 'en6-c17', type: 'Cloze', question: 'The turning point is where the story ___.', answer: 'changes', options: ['changes', 'stops', 'starts'], instruction: 'Analysis' },
    { id: 'en6-c18', type: 'Cloze', question: 'The ending ties a ___ on the story.', answer: 'knot', options: ['knot', 'bow', 'thread'], instruction: 'Analysis' },
    { id: 'en6-c19', type: 'Cloze', question: 'We work with ___ in English.', answer: 'grammar', options: ['grammar', 'cooking', 'sport'], instruction: 'Language' },
    { id: 'en6-c20', type: 'Cloze', question: 'A noun is something you can put "a" or "an" ___ of.', answer: 'in front', options: ['in front', 'behind', 'inside'], instruction: 'Grammar' },
    { id: 'en6-c21', type: 'Cloze', question: 'A verb tells what you ___.', answer: 'do', options: ['do', 'are', 'have'], instruction: 'Grammar' },
    { id: 'en6-c22', type: 'Cloze', question: 'An adjective ___ the noun.', answer: 'describes', options: ['describes', 'moves', 'deletes'], instruction: 'Grammar' },
    { id: 'en6-c23', type: 'Cloze', question: 'Adverbs tell about time and ___.', answer: 'place', options: ['place', 'food', 'clothes'], instruction: 'Grammar' },
    { id: 'en6-c24', type: 'Cloze', question: 'Prepositions tell about ___ relationships.', answer: 'spatial', options: ['spatial', 'cheerful', 'angry'], instruction: 'Grammar' },
    { id: 'en6-c25', type: 'Cloze', question: 'Pronouns ___ the noun.', answer: 'replace', options: ['replace', 'help', 'hit'], instruction: 'Grammar' },
    { id: 'en6-c26', type: 'Cloze', question: 'Conjunctions ___ two sentences.', answer: 'connect', options: ['connect', 'separate', 'remove'], instruction: 'Grammar' },
    { id: 'en6-c27', type: 'Cloze', question: 'Interjections express a ___ feeling.', answer: 'strong', options: ['strong', 'weak', 'blue'], instruction: 'Grammar' },
    { id: 'en6-c28', type: 'Cloze', question: 'We must put a ___ in the sentence.', answer: 'comma', options: ['comma', 'food', 'shoe'], instruction: 'Grammar' },
    { id: 'en6-c29', type: 'Cloze', question: 'A full stop marks the end of a ___.', answer: 'sentence', options: ['sentence', 'start', 'middle'], instruction: 'Grammar' },
    { id: 'en6-c30', type: 'Cloze', question: 'A question mark is used at a ___.', answer: 'question', options: ['question', 'answer', 'shout'], instruction: 'Grammar' },
    { id: 'en6-c31', type: 'Cloze', question: 'An exclamation mark is used at a ___.', answer: 'shout', options: ['shout', 'whisper', 'sigh'], instruction: 'Grammar' },
    { id: 'en6-c32', type: 'Cloze', question: 'Shakespeare wrote many ___.', answer: 'plays', options: ['plays', 'newspapers', 'letters'], instruction: 'Literature' },
    { id: 'en6-c33', type: 'Cloze', question: 'Jane Austen is a ___ author.', answer: 'famous', options: ['famous', 'unknown', 'new'], instruction: 'Literature' },
    { id: 'en6-c34', type: 'Cloze', question: 'Charles Dickens wrote about ___.', answer: 'daily life', options: ['daily life', 'space', 'the past'], instruction: 'Literature' },
    { id: 'en6-c35', type: 'Cloze', question: 'Roald Dahl was a ___ personality.', answer: 'colorful', options: ['colorful', 'boring', 'grey'], instruction: 'Literature' },
    { id: 'en6-c36', type: 'Cloze', question: 'Ernest Hemingway was a ___ author.', answer: 'modern', options: ['modern', 'old', 'ancient'], instruction: 'Literature' },
    { id: 'en6-c37', type: 'Cloze', question: 'We also read ___ in English.', answer: 'news', options: ['news', 'recipes', 'advertisements'], instruction: 'Media' },
    { id: 'en6-c38', type: 'Cloze', question: 'An article must have a good ___.', answer: 'headline', options: ['headline', 'bottom', 'page'], instruction: 'Journalism' },
    { id: 'en6-c39', type: 'Cloze', question: 'The journalist ___ the sources.', answer: 'interviews', options: ['interviews', 'eats', 'hits'], instruction: 'Journalism' },
    { id: 'en6-c40', type: 'Cloze', question: 'The news article must be ___ in its language.', answer: 'objective', options: ['objective', 'subjective', 'funny'], instruction: 'Journalism' },
    { id: 'en6-c41', type: 'Cloze', question: 'The editorial expresses the newspaper\'s ___.', answer: 'opinion', options: ['opinion', 'numbers', 'weather'], instruction: 'Journalism' },
    { id: 'en6-c42', type: 'Cloze', question: 'The letter to the editor is written by a ___.', answer: 'reader', options: ['reader', 'dog', 'car'], instruction: 'Journalism' },
    { id: 'en6-c43', type: 'Cloze', question: 'The review ___ a book or film.', answer: 'evaluates', options: ['evaluates', 'buys', 'sells'], instruction: 'Journalism' },
    { id: 'en6-c44', type: 'Cloze', question: 'The reportage is an ___ account.', answer: 'eyewitness', options: ['eyewitness', 'false', 'old'], instruction: 'Journalism' },
    { id: 'en6-c45', type: 'Cloze', question: 'The layout means the text\'s ___.', answer: 'setup', options: ['setup', 'color', 'weight'], instruction: 'Journalism' },
    { id: 'en6-c46', type: 'Cloze', question: 'Images in the newspaper ___ the text.', answer: 'support', options: ['support', 'destroy', 'remove'], instruction: 'Journalism' },
    { id: 'en6-c47', type: 'Cloze', question: 'Source criticism is ___ today.', answer: 'important', options: ['important', 'irrelevant', 'stupid'], instruction: 'Journalism' },
    { id: 'en6-c48', type: 'Cloze', question: 'Social media ___ news quickly.', answer: 'spreads', options: ['spreads', 'hides', 'stops'], instruction: 'Media' },
    { id: 'en6-c49', type: 'Cloze', question: 'Be aware of ___ news.', answer: 'fake', options: ['fake', 'good', 'real'], instruction: 'Media' },
    { id: 'en6-c50', type: 'Cloze', question: 'Netiquette is about ___ behavior.', answer: 'good', options: ['good', 'bad', 'wild'], instruction: 'Media' },
    { id: 'en6-c51', type: 'Cloze', question: 'English is a ___ language.', answer: 'world', options: ['world', 'small', 'dead'], instruction: 'English' },
  ],
  7: [
    { id: 'en7-c1', type: 'Cloze', question: 'The history of ideas examines human ___ through the ages.', answer: 'thoughts', options: ['thoughts', 'houses', 'money'], instruction: 'Philosophy' },
    { id: 'en7-c2', type: 'Cloze', question: 'Philosophers ask ___ about life.', answer: 'questions', options: ['questions', 'answers', 'demands'], instruction: 'Philosophy' },
    { id: 'en7-c3', type: 'Cloze', question: 'Ethics is about what is ___ and wrong.', answer: 'right', options: ['right', 'funny', 'easy'], instruction: 'Philosophy' },
    { id: 'en7-c4', type: 'Cloze', question: 'Morality is the ___ we live by.', answer: 'rules', options: ['rules', 'waters', 'shoes'], instruction: 'Philosophy' },
    { id: 'en7-c5', type: 'Cloze', question: 'Existence means human ___ in the world.', answer: 'presence', options: ['presence', 'car', 'food'], instruction: 'Philosophy' },
    { id: 'en7-c6', type: 'Cloze', question: 'Freedom also requires ___.', answer: 'responsibility', options: ['responsibility', 'money', 'sweets'], instruction: 'Philosophy' },
    { id: 'en7-c7', type: 'Cloze', question: 'What is ___? It is often debated.', answer: 'truth', options: ['truth', 'lie', 'color'], instruction: 'Philosophy' },
    { id: 'en7-c8', type: 'Cloze', question: 'We use ___ to win a debate.', answer: 'rhetoric', options: ['rhetoric', 'food', 'weapons'], instruction: 'Argumentation' },
    { id: 'en7-c9', type: 'Cloze', question: 'The argument must be ___ to convince.', answer: 'logical', options: ['logical', 'crazy', 'blue'], instruction: 'Argumentation' },
    { id: 'en7-c10', type: 'Cloze', question: 'The claim must be ___ by evidence.', answer: 'supported', options: ['supported', 'attacked', 'removed'], instruction: 'Argumentation' },
    { id: 'en7-c11', type: 'Cloze', question: 'The rebuttal removes the opponent\'s ___.', answer: 'argument', options: ['argument', 'clothes', 'car'], instruction: 'Argumentation' },
    { id: 'en7-c12', type: 'Cloze', question: 'Speaking against better ___ is not good.', answer: 'judgment', options: ['judgment', 'food', 'weather'], instruction: 'Argumentation' },
    { id: 'en7-c13', type: 'Cloze', question: 'Objectivity is ___ in a discussion.', answer: 'important', options: ['important', 'stupid', 'blue'], instruction: 'Argumentation' },
    { id: 'en7-c14', type: 'Cloze', question: 'The sender wants to ___ the receiver.', answer: 'influence', options: ['influence', 'eat', 'sleep'], instruction: 'Argumentation' },
    { id: 'en7-c15', type: 'Cloze', question: 'Language can be ___ in a speech.', answer: 'manipulative', options: ['manipulative', 'good', 'red'], instruction: 'Argumentation' },
    { id: 'en7-c16', type: 'Cloze', question: 'We analyze ___ in political speeches.', answer: 'rhetorical devices', options: ['rhetorical devices', 'food', 'shoes'], instruction: 'Argumentation' },
    { id: 'en7-c17', type: 'Cloze', question: 'Ethos is about the speaker\'s ___.', answer: 'credibility', options: ['credibility', 'money', 'appearance'], instruction: 'Rhetoric' },
    { id: 'en7-c18', type: 'Cloze', question: 'Logos is about the ___ facts.', answer: 'logical', options: ['logical', 'crazy', 'blue'], instruction: 'Rhetoric' },
    { id: 'en7-c19', type: 'Cloze', question: 'Pathos appeals to the feelings of the ___.', answer: 'audience', options: ['audience', 'animals', 'cars'], instruction: 'Rhetoric' },
    { id: 'en7-c20', type: 'Cloze', question: 'A metaphor is an ___ comparison.', answer: 'implied', options: ['implied', 'stupid', 'blue'], instruction: 'Language' },
    { id: 'en7-c21', type: 'Cloze', question: 'Personification gives ___ life to things.', answer: 'human', options: ['human', 'animal', 'dead'], instruction: 'Language' },
    { id: 'en7-c22', type: 'Cloze', question: 'Irony is saying the ___ of what you mean.', answer: 'opposite', options: ['opposite', 'same', 'blue'], instruction: 'Language' },
    { id: 'en7-c23', type: 'Cloze', question: 'Sarcasm is a ___ form of irony.', answer: 'mocking', options: ['mocking', 'sweet', 'happy'], instruction: 'Language' },
    { id: 'en7-c24', type: 'Cloze', question: 'Understatement diminishes a ___ phenomenon.', answer: 'large', options: ['large', 'small', 'blue'], instruction: 'Language' },
    { id: 'en7-c25', type: 'Cloze', question: 'Hyperbole makes everything ___ than it is.', answer: 'larger', options: ['larger', 'smaller', 'blue'], instruction: 'Language' },
    { id: 'en7-c26', type: 'Cloze', question: 'We analyze the text\'s ___ structure.', answer: 'complex', options: ['complex', 'simple', 'red'], instruction: 'Analysis' },
    { id: 'en7-c27', type: 'Cloze', question: 'Literature reflects ___ reality.', answer: 'historical', options: ['historical', 'future', 'secret'], instruction: 'Literature' },
    { id: 'en7-c28', type: 'Cloze', question: 'Symbols carry a ___ meaning.', answer: 'hidden', options: ['hidden', 'obvious', 'blue'], instruction: 'Analysis' },
    { id: 'en7-c29', type: 'Cloze', question: 'Interpretation requires an ___ reading.', answer: 'in-depth', options: ['in-depth', 'fast', 'happy'], instruction: 'Analysis' },
    { id: 'en7-c30', type: 'Cloze', question: 'Intertextuality is when texts ___ each other.', answer: 'refer to', options: ['refer to', 'eat', 'destroy'], instruction: 'Analysis' },
    { id: 'en7-c31', type: 'Cloze', question: 'Literary periods have different ___.', answer: 'ideals', options: ['ideals', 'foodstuffs', 'shoes'], instruction: 'Literature' },
    { id: 'en7-c32', type: 'Cloze', question: 'Romanticism focused on ___ and nature.', answer: 'feelings', options: ['feelings', 'machines', 'money'], instruction: 'Literature' },
    { id: 'en7-c33', type: 'Cloze', question: 'The modern breakthrough was about ___.', answer: 'problems', options: ['problems', 'fairytales', 'food'], instruction: 'Literature' },
    { id: 'en7-c34', type: 'Cloze', question: 'Realism tries to describe the world ___ as it is.', answer: 'exactly', options: ['exactly', 'crazy', 'never'], instruction: 'Literature' },
    { id: 'en7-c35', type: 'Cloze', question: 'Hemingway was a ___ figure in American literature.', answer: 'central', options: ['central', 'insignificant', 'secret'], instruction: 'Literature' },
    { id: 'en7-c36', type: 'Cloze', question: 'J.K. Rowling wrote about ___ and magic.', answer: 'wizards', options: ['wizards', 'potatoes', 'cars'], instruction: 'Literature' },
    { id: 'en7-c37', type: 'Cloze', question: 'Virginia Woolf is known for her ___ style.', answer: 'innovative', options: ['innovative', 'hard', 'stiff'], instruction: 'Literature' },
    { id: 'en7-c38', type: 'Cloze', question: 'We look at the language\'s ___ in the analysis.', answer: 'stylistics', options: ['stylistics', 'color', 'weight'], instruction: 'Analysis' },
    { id: 'en7-c39', type: 'Cloze', question: 'The point of view can be ___ or personal.', answer: 'omniscient', options: ['omniscient', 'blind', 'deaf'], instruction: 'Analysis' },
    { id: 'en7-c40', type: 'Cloze', question: 'The narrator can be ___ or unreliable.', answer: 'reliable', options: ['reliable', 'false', 'thick'], instruction: 'Analysis' },
    { id: 'en7-c41', type: 'Cloze', question: 'The environment affects the characters\' ___.', answer: 'actions', options: ['actions', 'teeth', 'shoes'], instruction: 'Analysis' },
    { id: 'en7-c42', type: 'Cloze', question: 'The subtext of the text is what is ___ written.', answer: 'not directly', options: ['not directly', 'actually', 'always'], instruction: 'Analysis' },
    { id: 'en7-c43', type: 'Cloze', question: 'Opposites create ___ in a text.', answer: 'tension', options: ['tension', 'peace', 'sleep'], instruction: 'Analysis' },
    { id: 'en7-c44', type: 'Cloze', question: 'We use ___ to find quotes.', answer: 'text reading', options: ['text reading', 'guessing', 'food'], instruction: 'Analysis' },
    { id: 'en7-c45', type: 'Cloze', question: 'Documentation is ___ for the analysis.', answer: 'necessary', options: ['necessary', 'stupid', 'blue'], instruction: 'Analysis' },
    { id: 'en7-c46', type: 'Cloze', question: 'We must be able to ___ our interpretation.', answer: 'justify', options: ['justify', 'forget', 'lose'], instruction: 'Analysis' },
    { id: 'en7-c47', type: 'Cloze', question: 'The lines of literary history are important to ___.', answer: 'know', options: ['know', 'shoes', 'houses'], instruction: 'Literature' },
    { id: 'en7-c48', type: 'Cloze', question: 'We compare texts from ___ periods.', answer: 'different', options: ['different', 'same', 'red'], instruction: 'Literature' },
    { id: 'en7-c49', type: 'Cloze', question: 'The message reaches beyond ___ time.', answer: 'its own', options: ['its own', 'never', 'always'], instruction: 'Literature' },
    { id: 'en7-c50', type: 'Cloze', question: 'Classic authors are ___ in school.', answer: 'obligatory', options: ['obligatory', 'forbidden', 'funny'], instruction: 'Literature' },
    { id: 'en7-c51', type: 'Cloze', question: 'Reading gives ___ into the world.', answer: 'insight', options: ['insight', 'ignorance', 'shoes'], instruction: 'Message' },
  ],
  8: [
    { id: 'en8-c1', type: 'Cloze', question: 'Society must ___ to the new technology.', answer: 'adapt', options: ['adapt', 'remove', 'stop'], instruction: 'Society' },
    { id: 'en8-c2', type: 'Cloze', question: 'Identity is a ___ topic in modern literature.', answer: 'central', options: ['central', 'unknown', 'blue'], instruction: 'Theme' },
    { id: 'en8-c3', type: 'Cloze', question: 'Who am I? This is an ___ question.', answer: 'existential', options: ['existential', 'stupid', 'easy'], instruction: 'Theme' },
    { id: 'en8-c4', type: 'Cloze', question: 'Globalization makes the world ___ for us.', answer: 'smaller', options: ['smaller', 'larger', 'blue'], instruction: 'Society' },
    { id: 'en8-c5', type: 'Cloze', question: 'Cultural clashes can create both ___ and conflict.', answer: 'understanding', options: ['understanding', 'hate', 'war'], instruction: 'Society' },
    { id: 'en8-c6', type: 'Cloze', question: 'The power of the media is ___ today.', answer: 'great', options: ['great', 'small', 'blue'], instruction: 'Society' },
    { id: 'en8-c7', type: 'Cloze', question: 'Digital literacy is about how to ___ on the net.', answer: 'behave', options: ['behave', 'eat', 'sleep'], instruction: 'Society' },
    { id: 'en8-c8', type: 'Cloze', question: 'Source criticism is ___ when using the internet.', answer: 'crucial', options: ['crucial', 'irrelevant', 'funny'], instruction: 'Society' },
    { id: 'en8-c9', type: 'Cloze', question: 'Fake news can ___ our democracy.', answer: 'harm', options: ['harm', 'help', 'build'], instruction: 'Society' },
    { id: 'en8-c10', type: 'Cloze', question: 'Social media creates ___ communities.', answer: 'digital', options: ['digital', 'physical', 'none'], instruction: 'Society' },
    { id: 'en8-c11', type: 'Cloze', question: 'Personal data must be ___ on the net.', answer: 'protected', options: ['protected', 'shared', 'sold'], instruction: 'Society' },
    { id: 'en8-c12', type: 'Cloze', question: 'Algorithms control what we ___ on the net.', answer: 'see', options: ['see', 'eat', 'hear'], instruction: 'Society' },
    { id: 'en8-c13', type: 'Cloze', question: 'Echo chambers reinforce our own ___.', answer: 'opinions', options: ['opinions', 'shoes', 'houses'], instruction: 'Society' },
    { id: 'en8-c14', type: 'Cloze', question: 'Critical thinking is a ___ against manipulation.', answer: 'defense', options: ['defense', 'attack', 'hole'], instruction: 'Society' },
    { id: 'en8-c15', type: 'Cloze', question: 'Advertisements try to ___ our needs.', answer: 'create', options: ['create', 'remove', 'satisfy'], instruction: 'Society' },
    { id: 'en8-c16', type: 'Cloze', question: 'Branding is important for ___ companies.', answer: 'modern', options: ['modern', 'old', 'small'], instruction: 'Economy' },
    { id: 'en8-c17', type: 'Cloze', question: 'Consumerism shapes our ___ society.', answer: 'Western', options: ['Western', 'wild', 'quiet'], instruction: 'Society' },
    { id: 'en8-c18', type: 'Cloze', question: 'Sustainability is a ___ necessity.', answer: 'global', options: ['global', 'local', 'blue'], instruction: 'Environment' },
    { id: 'en8-c19', type: 'Cloze', question: 'Climate change requires ___ action now.', answer: 'political', options: ['political', 'none', 'slow'], instruction: 'Politics' },
    { id: 'en8-c20', type: 'Cloze', question: 'Individuals have a ___ towards the environment.', answer: 'responsibility', options: ['responsibility', 'food', 'clothes'], instruction: 'Ethics' },
    { id: 'en8-c21', type: 'Cloze', question: 'The community should ___ the weakest.', answer: 'help', options: ['help', 'overlook', 'hit'], instruction: 'Ethics' },
    { id: 'en8-c22', type: 'Cloze', question: 'Justice is a ___ in society.', answer: 'fundamental principle', options: ['fundamental principle', 'game', 'food'], instruction: 'Politics' },
    { id: 'en8-c23', type: 'Cloze', question: 'Equality before the law applies to ___.', answer: 'everyone', options: ['everyone', 'no one', 'few'], instruction: 'Politics' },
    { id: 'en8-c24', type: 'Cloze', question: 'Human rights must be ___ everywhere.', answer: 'respected', options: ['respected', 'broken', 'forgotten'], instruction: 'Politics' },
    { id: 'en8-c25', type: 'Cloze', question: 'Democracy requires ___ citizens.', answer: 'active', options: ['active', 'passive', 'sleeping'], instruction: 'Society' },
    { id: 'en8-c26', type: 'Cloze', question: 'Freedom of speech also has its ___.', answer: 'limits', options: ['limits', 'roads', 'shoes'], instruction: 'Law' },
    { id: 'en8-c27', type: 'Cloze', question: 'Hate speech is ___ in public debate.', answer: 'unacceptable', options: ['unacceptable', 'welcome', 'funny'], instruction: 'Social' },
    { id: 'en8-c28', type: 'Cloze', question: 'Tolerance means to ___ differences.', answer: 'embrace', options: ['embrace', 'remove', 'hate'], instruction: 'Social' },
    { id: 'en8-c29', type: 'Cloze', question: 'Solidarity binds ___ together.', answer: 'people', options: ['people', 'cars', 'houses'], instruction: 'Social' },
    { id: 'en8-c30', type: 'Cloze', question: 'We must fight ___ in society.', answer: 'inequality', options: ['inequality', 'equality', 'food'], instruction: 'Politics' },
    { id: 'en8-c31', type: 'Cloze', question: 'Education is the way to a ___ future.', answer: 'better', options: ['better', 'worse', 'blue'], instruction: 'Future' },
    { id: 'en8-c32', type: 'Cloze', question: 'Work gives ___ and meaning.', answer: 'content', options: ['content', 'food', 'clothes'], instruction: 'Society' },
    { id: 'en8-c33', type: 'Cloze', question: 'The welfare state ___ citizens security.', answer: 'ensures', options: ['ensures', 'removes', 'destroys'], instruction: 'Economy' },
    { id: 'en8-c34', type: 'Cloze', question: 'The economy must be ___ to grow.', answer: 'stable', options: ['stable', 'nervous', 'red'], instruction: 'Economy' },
    { id: 'en8-c35', type: 'Cloze', question: 'Investments create ___ in the country.', answer: 'jobs', options: ['jobs', 'war', 'disease'], instruction: 'Economy' },
    { id: 'en8-c36', type: 'Cloze', question: 'Technology changes our ___ every day.', answer: 'lives', options: ['lives', 'shoes', 'houses'], instruction: 'Technology' },
    { id: 'en8-c37', type: 'Cloze', question: 'Innovation drives ___ forward.', answer: 'development', options: ['development', 'to car', 'to food'], instruction: 'Science' },
    { id: 'en8-c38', type: 'Cloze', question: 'Science searches for ___ about the world.', answer: 'knowledge', options: ['knowledge', 'gold', 'food'], instruction: 'Science' },
    { id: 'en8-c39', type: 'Cloze', question: 'The laboratory is where ___ occurs.', answer: 'experimentation', options: ['experimentation', 'cooking', 'dancing'], instruction: 'Science' },
    { id: 'en8-c40', type: 'Cloze', question: 'The hypothesis must be ___ in reality.', answer: 'tested', options: ['tested', 'forgotten', 'lost'], instruction: 'Science' },
    { id: 'en8-c41', type: 'Cloze', question: 'The results must be ___ to others.', answer: 'accessible', options: ['accessible', 'secret', 'dangerous'], instruction: 'Science' },
    { id: 'en8-c42', type: 'Cloze', question: 'Ethics in research is ___ important.', answer: 'very', options: ['very', 'never', 'blue'], instruction: 'Ethics' },
    { id: 'en8-c43', type: 'Cloze', question: 'The future is ___ by our choices today.', answer: 'shaped', options: ['shaped', 'independent', 'blue'], instruction: 'Thought' },
    { id: 'en8-c44', type: 'Cloze', question: 'We should ___ from history.', answer: 'learn', options: ['learn', 'food', 'shoes'], instruction: 'Thought' },
    { id: 'en8-c45', type: 'Cloze', question: 'Experience is the best ___.', answer: 'teacher', options: ['teacher', 'student', 'book'], instruction: 'Thought' },
    { id: 'en8-c46', type: 'Cloze', question: 'Wisdom comes with ___ and age.', answer: 'insight', options: ['insight', 'teeth', 'hair'], instruction: 'Thought' },
    { id: 'en8-c47', type: 'Cloze', question: 'Change is good, says an ___ proverb.', answer: 'old', options: ['old', 'new', 'crazy'], instruction: 'Thought' },
    { id: 'en8-c48', type: 'Cloze', question: 'Hope lives until the ___ end.', answer: 'very', options: ['very', 'not', 'a'], instruction: 'Thought' },
    { id: 'en8-c49', type: 'Cloze', question: 'Happiness is ___ oneself.', answer: 'finding', options: ['finding', 'losing', 'selling'], instruction: 'Thought' },
    { id: 'en8-c50', type: 'Cloze', question: 'Love conquers ___ all.', answer: 'almost', options: ['almost', 'never', 'always'], instruction: 'Thought' },
    { id: 'en8-c51', type: 'Cloze', question: 'End for ___ level.', answer: 'this', options: ['this', 'that', 'a'], instruction: 'Message' },
  ],
  9: [
    { id: 'en9-c1', type: 'Cloze', question: 'Existentialism focuses on human ___ choice.', answer: 'free', options: ['free', 'forced', 'no'], instruction: 'Philosophy' },
    { id: 'en9-c2', type: 'Cloze', question: 'Sartre believed that humans are ___ to be free.', answer: 'condemned', options: ['condemned', 'chosen', 'born'], instruction: 'Philosophy' },
    { id: 'en9-c3', type: 'Cloze', question: 'Nihilism claims that life is ___ meaning.', answer: 'without', options: ['without', 'with', 'full of'], instruction: 'Philosophy' },
    { id: 'en9-c4', type: 'Cloze', question: 'Absurdism sees a ___ between human and world.', answer: 'conflict', options: ['conflict', 'harmony', 'peace'], instruction: 'Philosophy' },
    { id: 'en9-c5', type: 'Cloze', question: 'Stoicism teaches us to ___ the inevitable.', answer: 'accept', options: ['accept', 'fight', 'flee from'], instruction: 'Philosophy' },
    { id: 'en9-c6', type: 'Cloze', question: 'Epicureanism seeks ___ and absence of pain.', answer: 'pleasure', options: ['pleasure', 'suffering', 'work'], instruction: 'Philosophy' },
    { id: 'en9-c7', type: 'Cloze', question: 'Rationalism builds on ___ as a source of knowledge.', answer: 'reason', options: ['reason', 'feeling', 'faith'], instruction: 'Philosophy' },
    { id: 'en9-c8', type: 'Cloze', question: 'Empiricism values ___ and observation highest.', answer: 'experience', options: ['experience', 'thinking', 'dreams'], instruction: 'Philosophy' },
    { id: 'en9-c9', type: 'Cloze', question: 'Phenomenology examines the ___ of things.', answer: 'appearance', options: ['appearance', 'core', 'price'], instruction: 'Philosophy' },
    { id: 'en9-c10', type: 'Cloze', question: 'Ontology is the study of ___.', answer: 'being', options: ['being', 'knowledge', 'morality'], instruction: 'Philosophy' },
    { id: 'en9-c11', type: 'Cloze', question: 'Epistemology deals with the nature of ___.', answer: 'knowledge', options: ['knowledge', 'the body', 'the soul'], instruction: 'Philosophy' },
    { id: 'en9-c12', type: 'Cloze', question: 'Dualism distinguishes between ___ and body.', answer: 'soul', options: ['soul', 'hair', 'foot'], instruction: 'Philosophy' },
    { id: 'en9-c13', type: 'Cloze', question: 'Determinism claims that everything is ___ beforehand.', answer: 'determined', options: ['determined', 'random', 'hidden'], instruction: 'Philosophy' },
    { id: 'en9-c14', type: 'Cloze', question: 'Dialectics works with ___ and synthesis.', answer: 'antithesis', options: ['antithesis', 'history', 'food'], instruction: 'Philosophy' },
    { id: 'en9-c15', type: 'Cloze', question: 'Hermeneutics is the study of ___.', answer: 'interpretation', options: ['interpretation', 'creation', 'sale'], instruction: 'Philosophy' },
    { id: 'en9-c16', type: 'Cloze', question: 'Kant\'s categorical imperative concerns ___ action.', answer: 'universal', options: ['universal', 'personal', 'secret'], instruction: 'Philosophy' },
    { id: 'en9-c17', type: 'Cloze', question: 'Utilitarianism seeks the greatest ___ for the most people.', answer: 'happiness', options: ['happiness', 'money', 'power'], instruction: 'Philosophy' },
    { id: 'en9-c18', type: 'Cloze', question: 'Virtue ethics focuses on character and ___.', answer: 'morals', options: ['morals', 'looks', 'wealth'], instruction: 'Philosophy' },
    { id: 'en9-c19', type: 'Cloze', question: 'Sociobiology looks at the ___ background for behavior.', answer: 'biological', options: ['biological', 'cultural', 'economic'], instruction: 'Science' },
    { id: 'en9-c20', type: 'Cloze', question: 'Psychoanalysis dives into the ___.', answer: 'unconscious', options: ['unconscious', 'conscious', 'physical'], instruction: 'Psychology' },
    { id: 'en9-c21', type: 'Cloze', question: 'Behaviorism studies ___ behavior.', answer: 'observable', options: ['observable', 'hidden', 'inner'], instruction: 'Psychology' },
    { id: 'en9-c22', type: 'Cloze', question: 'Cognitive psychology looks at ___ processes.', answer: 'mental', options: ['mental', 'physical', 'social'], instruction: 'Psychology' },
    { id: 'en9-c23', type: 'Cloze', question: 'Sociology examines ___ in society.', answer: 'structures', options: ['structures', 'individuals', 'animals'], instruction: 'Sociology' },
    { id: 'en9-c24', type: 'Cloze', question: 'Structuralism looks at ___ patterns.', answer: 'underlying', options: ['underlying', 'visible', 'new'], instruction: 'Sociology' },
    { id: 'en9-c25', type: 'Cloze', question: 'Postmodernism ___ the grand narratives.', answer: 'rejects', options: ['rejects', 'hails', 'supports'], instruction: 'Philosophy' },
    { id: 'en9-c26', type: 'Cloze', question: 'Deconstruction opens for ___ meanings.', answer: 'ambiguous', options: ['ambiguous', 'single', 'none'], instruction: 'Philosophy' },
    { id: 'en9-c27', type: 'Cloze', question: 'Globalization creates a ___ world.', answer: 'connected', options: ['connected', 'isolated', 'closed'], instruction: 'Society' },
    { id: 'en9-c28', type: 'Cloze', question: 'Postcolonialism looks at the ___ of colonialism.', answer: 'aftermath', options: ['aftermath', 'benefits', 'start'], instruction: 'History' },
    { id: 'en9-c29', type: 'Cloze', question: 'Feminism fights for ___ between the genders.', answer: 'equality', options: ['equality', 'difference', 'struggle'], instruction: 'Society' },
    { id: 'en9-c30', type: 'Cloze', question: 'Ecocriticism analyzes ___ relationship with nature.', answer: 'literature\'s', options: ['literature\'s', 'car\'s', 'food\'s'], instruction: 'Analysis' },
    { id: 'en9-c31', type: 'Cloze', question: 'Dystopia describes a ___ future.', answer: 'frightening', options: ['frightening', 'happy', 'bright'], instruction: 'Genre' },
    { id: 'en9-c32', type: 'Cloze', question: 'Utopia is the ___ society.', answer: 'perfect', options: ['perfect', 'broken', 'dark'], instruction: 'Genre' },
    { id: 'en9-c33', type: 'Cloze', question: 'Satire uses ___ to criticize.', answer: 'humor', options: ['humor', 'violence', 'threats'], instruction: 'Genre' },
    { id: 'en9-c34', type: 'Cloze', question: 'Irony is an ___ tool in literature.', answer: 'effective', options: ['effective', 'useless', 'annoying'], instruction: 'Language' },
    { id: 'en9-c35', type: 'Cloze', question: 'Narratology is the study of ___.', answer: 'narratives', options: ['narratives', 'words', 'rhymes'], instruction: 'Analysis' },
    { id: 'en9-c36', type: 'Cloze', question: 'Discourse is the ___ we talk about things.', answer: 'way', options: ['way', 'day', 'week'], instruction: 'Language' },
    { id: 'en9-c37', type: 'Cloze', question: 'Ideology criticism reveals ___ behind the text.', answer: 'power', options: ['power', 'history', 'food'], instruction: 'Analysis' },
    { id: 'en9-c38', type: 'Cloze', question: 'The canon is the most ___ works.', answer: 'esteemed', options: ['esteemed', 'forgotten', 'crazy'], instruction: 'Literature' },
    { id: 'en9-c39', type: 'Cloze', question: 'The role of literature is ___ debated in society.', answer: 'continually', options: ['continually', 'never', 'seldom'], instruction: 'Literature' },
    { id: 'en9-c40', type: 'Cloze', question: 'Art should ___ the world, some said.', answer: 'change', options: ['change', 'decorate', 'preserve'], instruction: 'Art' },
    { id: 'en9-c41', type: 'Cloze', question: 'L\'art pur is art for ___ own sake.', answer: 'art\'s', options: ['art\'s', 'my', 'your'], instruction: 'Art' },
    { id: 'en9-c42', type: 'Cloze', question: 'Aesthetics is the study of the ___.', answer: 'beautiful', options: ['beautiful', 'ugly', 'wild'], instruction: 'Art' },
    { id: 'en9-c43', type: 'Cloze', question: 'Modernism broke with ___ forms.', answer: 'traditional', options: ['traditional', 'new', 'wild'], instruction: 'Literature' },
    { id: 'en9-c44', type: 'Cloze', question: 'Absurdist theater shows life\'s ___.', answer: 'meaninglessness', options: ['meaninglessness', 'joy', 'beauty'], instruction: 'Literature' },
    { id: 'en9-c45', type: 'Cloze', question: 'Magical realism blends ___ and magic.', answer: 'daily life', options: ['daily life', 'space', 'the past'], instruction: 'Literature' },
    { id: 'en9-c46', type: 'Cloze', question: 'Minimalism uses ___ words.', answer: 'few', options: ['few', 'many', 'long'], instruction: 'Literature' },
    { id: 'en9-c47', type: 'Cloze', question: 'Show, don\'t tell is an ___ advice.', answer: 'important', options: ['important', 'stupid', 'irrelevant'], instruction: 'Writing art' },
    { id: 'en9-c48', type: 'Cloze', question: 'Writing requires ___ and diligence.', answer: 'patience', options: ['patience', 'speed', 'money'], instruction: 'Writing art' },
    { id: 'en9-c49', type: 'Cloze', question: 'Editing is ___ for the final result.', answer: 'crucial', options: ['crucial', 'irrelevant', 'funny'], instruction: 'Writing art' },
    { id: 'en9-c50', type: 'Cloze', question: 'Reading gives us ___ lives.', answer: 'many', options: ['many', 'one', 'no'], instruction: 'Philosophy' },
    { id: 'en9-c51', type: 'Cloze', question: 'Good luck ___ the exam!', answer: 'with', options: ['with', 'to', 'for'], instruction: 'Message' },
  ],
};
