/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const FRANSK_CLOZE_P3: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'fr0-c52', type: 'Cloze', question: 'Le ___ brille dans le ciel.', answer: 'soleil', options: ['soleil', 'poisson', 'pied'], instruction: 'Nature' },
    { id: 'fr0-c53', type: 'Cloze', question: 'La ___ est verte.', answer: 'pomme', options: ['pomme', 'avion', 'lit'], instruction: 'Food' },
    { id: 'fr0-c54', type: 'Cloze', question: 'Un petit ___ jaune.', answer: 'canard', options: ['canard', 'vélo', 'pont'], instruction: 'Animal' },
    { id: 'fr0-c55', type: 'Cloze', question: 'Je vois une ___ rouge.', answer: 'fleur', options: ['fleur', 'route', 'banane'], instruction: 'Nature' },
    { id: 'fr0-c56', type: 'Cloze', question: 'Le ___ fait miaou.', answer: 'chat', options: ['chat', 'bus', 'train'], instruction: 'Animal' },
    { id: 'fr0-c57', type: 'Cloze', question: 'La ___ est ronde.', answer: 'balle', options: ['balle', 'maison', 'main'], instruction: 'Object' },
    { id: 'fr0-c58', type: 'Cloze', question: 'Maman est ___ .', answer: 'belle', options: ['belle', 'bleue', 'auto'], instruction: 'Family' },
    { id: 'fr0-c59', type: 'Cloze', question: 'Papa est ___ .', answer: 'grand', options: ['grand', 'vert', 'petit'], instruction: 'Family' },
    { id: 'fr0-c60', type: 'Cloze', question: 'Un gros ___ brun.', answer: 'ours', options: ['ours', 'oiseau', 'lapin'], instruction: 'Animal' },
    { id: 'fr0-c61', type: 'Cloze', question: 'Le ___ est bleu.', answer: 'ciel', options: ['ciel', 'gazon', 'lait'], instruction: 'Nature' },
    { id: 'fr0-c62', type: 'Cloze', question: 'Je mange du ___ .', answer: 'pain', options: ['pain', 'stylo', 'mur'], instruction: 'Food' },
    { id: 'fr0-c63', type: 'Cloze', question: 'Boire un ___ de lait.', answer: 'verre', options: ['verre', 'sac', 'dent'], instruction: 'Drink' },
    { id: 'fr0-c64', type: 'Cloze', question: 'Ma ___ est chaude.', answer: 'soupe', options: ['soupe', 'chaussure', 'table'], instruction: 'Food' },
    { id: 'fr0-c65', type: 'Cloze', question: 'Le ___ est sur la table.', answer: 'livre', options: ['livre', 'vent', 'mer'], instruction: 'Object' },
    { id: 'fr0-c66', type: 'Cloze', question: 'Je joue avec mon ___ .', answer: 'chien', options: ['chien', 'avion', 'chapeau'], instruction: 'Activity' },
    { id: 'fr0-c67', type: 'Cloze', question: 'Il y a une ___ dans le jardin.', answer: 'vache', options: ['vache', 'lampe', 'fenêtre'], instruction: 'Animal' },
    { id: 'fr0-c68', type: 'Cloze', question: 'La ___ est blanche.', answer: 'neige', options: ['neige', 'feuille', 'bouche'], instruction: 'Nature' },
    { id: 'fr0-c69', type: 'Cloze', question: 'Une petite ___ bleue.', answer: 'voiture', options: ['voiture', 'pomme', 'oreille'], instruction: 'Object' },
    { id: 'fr0-c70', type: 'Cloze', question: 'Je dors dans mon ___ .', answer: 'lit', options: ['lit', 'four', 'jardin'], instruction: 'Home' },
    { id: 'fr0-c71', type: 'Cloze', question: 'Le ___ est blanc.', answer: 'lapin', options: ['lapin', 'soleil', 'ciel'], instruction: 'Animal' },
    { id: 'fr0-c72', type: 'Cloze', question: 'Un ___ d\'eau froide.', answer: 'verre', options: ['verre', 'nuage', 'cheval'], instruction: 'Drink' },
    { id: 'fr0-c73', type: 'Cloze', question: 'Regarde le ___ oiseau.', answer: 'petit', options: ['petit', 'grand', 'gros'], instruction: 'Description' },
    { id: 'fr0-c74', type: 'Cloze', question: 'Le ___ est dans son nid.', answer: 'oiseau', options: ['oiseau', 'poisson', 'lion'], instruction: 'Animal' },
    { id: 'fr0-c75', type: 'Cloze', question: 'J\'aime les ___ .', answer: 'fraises', options: ['fraises', 'pierres', 'murs'], instruction: 'Food' },
    { id: 'fr0-c76', type: 'Cloze', question: 'La ___ est sucrée.', answer: 'banane', options: ['banane', 'soupe', 'terre'], instruction: 'Food' },
    { id: 'fr0-c77', type: 'Cloze', question: 'Le ___ est fort.', answer: 'lion', options: ['lion', 'chat', 'souris'], instruction: 'Animal' },
    { id: 'fr0-c78', type: 'Cloze', question: 'Une ___ sur le mur.', answer: 'mouche', options: ['mouche', 'montagne', 'maison'], instruction: 'Bug' },
    { id: 'fr0-c79', type: 'Cloze', question: 'Le ___ est noir.', answer: 'pantalon', options: ['pantalon', 'soleil', 'lait'], instruction: 'Clothing' },
    { id: 'fr0-c80', type: 'Cloze', question: 'Je porte mes ___ .', answer: 'chaussures', options: ['chaussures', 'mains', 'oreilles'], instruction: 'Clothing' },
    { id: 'fr0-c81', type: 'Cloze', question: 'Il fait ___ dehors.', answer: 'froid', options: ['froid', 'chaud', 'beau'], instruction: 'Weather' },
    { id: 'fr0-c82', type: 'Cloze', question: 'La ___ lune brille.', answer: 'belle', options: ['belle', 'bleue', 'grise'], instruction: 'Nature' },
    { id: 'fr0-c83', type: 'Cloze', question: 'Un ___ de bonbons.', answer: 'sac', options: ['sac', 'pied', 'cheveu'], instruction: 'Object' },
    { id: 'fr0-c84', type: 'Cloze', question: 'Ma ___ est rose.', answer: 'chemise', options: ['chemise', 'banane', 'lune'], instruction: 'Clothing' },
    { id: 'fr0-c85', type: 'Cloze', question: 'Une ___ dans le seau.', answer: 'pelle', options: ['pelle', 'maison', 'vache'], instruction: 'Object' },
    { id: 'fr0-c86', type: 'Cloze', question: 'Le ___ est rigolo.', answer: 'clown', options: ['clown', 'pain', 'pont'], instruction: 'Person' },
    { id: 'fr0-c87', type: 'Cloze', question: 'Je monte dans le ___ .', answer: 'bus', options: ['bus', 'poisson', 'lit'], instruction: 'Travel' },
    { id: 'fr0-c88', type: 'Cloze', question: 'Une ___ de chocolat.', answer: 'tablette', options: ['tablette', 'chaise', 'fenêtre'], instruction: 'Food' },
    { id: 'fr0-c89', type: 'Cloze', question: 'Le ___ est sur le toit.', answer: 'chat', options: ['chat', 'poisson', 'train'], instruction: 'Animal' },
    { id: 'fr0-c90', type: 'Cloze', question: 'Une ___ de riz.', answer: 'assiette', options: ['assiette', 'chaussure', 'fleur'], instruction: 'Food' },
    { id: 'fr0-c91', type: 'Cloze', question: 'Le ___ est prêt.', answer: 'dîner', options: ['dîner', 'vélo', 'nuage'], instruction: 'Food' },
    { id: 'fr0-c92', type: 'Cloze', question: 'Un ___ dans la forêt.', answer: 'arbre', options: ['arbre', 'livre', 'mur'], instruction: 'Nature' },
    { id: 'fr0-c93', type: 'Cloze', question: 'Le ___ est gris.', answer: 'nuage', options: ['nuage', 'soleil', 'pont'], instruction: 'Nature' },
    { id: 'fr0-c94', type: 'Cloze', question: 'Une ___ de jus.', answer: 'tasse', options: ['tasse', 'chaussure', 'dent'], instruction: 'Drink' },
    { id: 'fr0-c95', type: 'Cloze', question: 'Le ___ est fini.', answer: 'jeu', options: ['jeu', 'pain', 'soleil'], instruction: 'Action' },
    { id: 'fr0-c96', type: 'Cloze', question: 'Un ___ pour papa.', answer: 'cadeau', options: ['cadeau', 'bus', 'vent'], instruction: 'Object' },
    { id: 'fr0-c97', type: 'Cloze', question: 'La ___ est loin.', answer: 'ville', options: ['ville', 'pomme', 'mouche'], instruction: 'Place' },
    { id: 'fr0-c98', type: 'Cloze', question: 'Le ___ est long.', answer: 'chemin', options: ['chemin', 'chat', 'lit'], instruction: 'Place' },
    { id: 'fr0-c99', type: 'Cloze', question: 'Un ___ pour bébé.', answer: 'jouet', options: ['jouet', 'train', 'pain'], instruction: 'Object' },
    { id: 'fr0-c100', type: 'Cloze', question: 'Au ___ !', answer: 'revoir', options: ['revoir', 'bonjour', 'merci'], instruction: 'Greeting' },
  ],
  1: [
    { id: 'fr1-c52', type: 'Cloze', question: 'Nous ___ à la plage.', answer: 'allons', options: ['allons', 'mangeons', 'dormons'], instruction: 'Activity' },
    { id: 'fr1-c53', type: 'Cloze', question: 'Il ___ froid aujourd\'hui.', answer: 'fait', options: ['fait', 'est', 'va'], instruction: 'Weather' },
    { id: 'fr1-c54', type: 'Cloze', question: 'Je ___ mon petit déjeuner.', answer: 'prends', options: ['prends', 'vois', 'lis'], instruction: 'Action' },
    { id: 'fr1-c55', type: 'Cloze', question: 'Elle ___ une belle robe.', answer: 'porte', options: ['porte', 'achète', 'finit'], instruction: 'Clothing' },
    { id: 'fr1-c56', type: 'Cloze', question: 'Le chat ___ sur le tapis.', answer: 'dort', options: ['dort', 'chante', 'danse'], instruction: 'Action' },
    { id: 'fr1-c57', type: 'Cloze', question: 'Vous ___ du fromage.', answer: 'mangez', options: ['mangez', 'allez', 'lisez'], instruction: 'Food' },
    { id: 'fr1-c58', type: 'Cloze', question: 'Ils ___ dans la cour.', answer: 'jouent', options: ['jouent', 'boivent', 'dorment'], instruction: 'Action' },
    { id: 'fr1-c59', type: 'Cloze', question: 'Tu ___ un dessin animé.', answer: 'regardes', options: ['regardes', 'écoutes', 'manges'], instruction: 'Action' },
    { id: 'fr1-c60', type: 'Cloze', question: 'Nous ___ de la musique.', answer: 'écoutons', options: ['écoutons', 'voyons', 'marchons'], instruction: 'Media' },
    { id: 'fr1-c61', type: 'Cloze', question: 'Le ___ est dans le garage.', answer: 'vélo', options: ['vélo', 'pain', 'soleil'], instruction: 'Object' },
    { id: 'fr1-c62', type: 'Cloze', question: 'La ___ est sur l\'herbe.', answer: 'balle', options: ['balle', 'table', 'nuit'], instruction: 'Object' },
    { id: 'fr1-c63', type: 'Cloze', question: 'Je vais ___ l\'école.', answer: 'à', options: ['à', 'de', 'en'], instruction: 'Place' },
    { id: 'fr1-c64', type: 'Cloze', question: 'Il ___ un livre rouge.', answer: 'a', options: ['a', 'est', 'va'], instruction: 'Possession' },
    { id: 'fr1-c65', type: 'Cloze', question: 'Le ___ est délicieux.', answer: 'gâteau', options: ['gâteau', 'pont', 'vent'], instruction: 'Food' },
    { id: 'fr1-c66', type: 'Cloze', question: 'La ___ de ma mère.', answer: 'voiture', options: ['voiture', 'banane', 'oreille'], instruction: 'Object' },
    { id: 'fr1-c67', type: 'Cloze', question: 'Des ___ dans le ciel.', answer: 'oiseaux', options: ['oiseaux', 'pommes', 'lits'], instruction: 'Animal' },
    { id: 'fr1-c68', type: 'Cloze', question: 'Un ___ de pommes.', answer: 'panier', options: ['panier', 'soleil', 'pont'], instruction: 'Object' },
    { id: 'fr1-c69', type: 'Cloze', question: 'C\'est ___ pour moi.', answer: 'bon', options: ['bon', 'bleu', 'gros'], instruction: 'Description' },
    { id: 'fr1-c70', type: 'Cloze', question: 'Le ___ est dehors.', answer: 'chien', options: ['chien', 'avion', 'chapeau'], instruction: 'Animal' },
    { id: 'fr1-c71', type: 'Cloze', question: 'Maman ___ un gâteau.', answer: 'prépare', options: ['prépare', 'dort', 'danse'], instruction: 'Action' },
    { id: 'fr1-c72', type: 'Cloze', question: 'Le ___ est sur le mur.', answer: 'tableau', options: ['tableau', 'lit', 'gazon'], instruction: 'Object' },
    { id: 'fr1-c73', type: 'Cloze', question: 'Une ___ dans la boîte.', answer: 'surprise', options: ['surprise', 'route', 'vache'], instruction: 'Object' },
    { id: 'fr1-c74', type: 'Cloze', question: 'Je ___ mon vélo.', answer: 'lave', options: ['lave', 'mange', 'lis'], instruction: 'Action' },
    { id: 'fr1-c75', type: 'Cloze', question: 'Le ___ est plein.', answer: 'verre', options: ['verre', 'vent', 'mer'], instruction: 'Object' },
    { id: 'fr1-c76', type: 'Cloze', question: 'Nous ___ très vite.', answer: 'courons', options: ['courons', 'dormons', 'lisons'], instruction: 'Action' },
    { id: 'fr1-c77', type: 'Cloze', question: 'Un ___ de cerises.', answer: 'bol', options: ['bol', 'nuage', 'cheval'], instruction: 'Object' },
    { id: 'fr1-c78', type: 'Cloze', question: 'C\'est mon ___ .', answer: 'tour', options: ['tour', 'pain', 'pont'], instruction: 'Action' },
    { id: 'fr1-c79', type: 'Cloze', question: 'La ___ est allumée.', answer: 'lampe', options: ['lampe', 'pomme', 'route'], instruction: 'Home' },
    { id: 'fr1-c80', type: 'Cloze', question: 'Je regarde par la ___ .', answer: 'fenêtre', options: ['fenêtre', 'table', 'nuit'], instruction: 'Home' },
    { id: 'fr1-c81', type: 'Cloze', question: 'Le ___ est mouillé.', answer: 'sol', options: ['sol', 'ciel', 'feu'], instruction: 'Place' },
    { id: 'fr1-c82', type: 'Cloze', question: 'Une ___ de sable.', answer: 'pile', options: ['pile', 'vache', 'fleur'], instruction: 'Object' },
    { id: 'fr1-c83', type: 'Cloze', question: 'Il y a du ___ .', answer: 'vent', options: ['vent', 'sucre', 'miel'], instruction: 'Weather' },
    { id: 'fr1-c84', type: 'Cloze', question: 'C\'est ___ amusant.', answer: 'très', options: ['très', 'jamais', 'bleu'], instruction: 'Adverb' },
    { id: 'fr1-c85', type: 'Cloze', question: 'Un ___ de fleurs.', answer: 'bouquet', options: ['bouquet', 'avion', 'lit'], instruction: 'Nature' },
    { id: 'fr1-c86', type: 'Cloze', question: 'Le ___ est ouvert.', answer: 'magasin', options: ['magasin', 'soleil', 'chien'], instruction: 'Place' },
    { id: 'fr1-c87', type: 'Cloze', question: 'Je ___ une question.', answer: 'pose', options: ['pose', 'vois', 'lis'], instruction: 'Action' },
    { id: 'fr1-c88', type: 'Cloze', question: 'C\'est ___ vrai.', answer: 'tout', options: ['tout', 'rien', 'pas'], instruction: 'Adverb' },
    { id: 'fr1-c89', type: 'Cloze', question: 'Le ___ est à droite.', answer: 'chemin', options: ['chemin', 'pont', 'mur'], instruction: 'Place' },
    { id: 'fr1-c90', type: 'Cloze', question: 'Une ___ de fraises.', answer: 'boîte', options: ['boîte', 'route', 'vache'], instruction: 'Object' },
    { id: 'fr1-c91', type: 'Cloze', question: 'Il ___ des histoires.', answer: 'dit', options: ['dit', 'mange', 'boit'], instruction: 'Action' },
    { id: 'fr1-c92', type: 'Cloze', question: 'Mon ___ est neuf.', answer: 'sac', options: ['sac', 'pain', 'vent'], instruction: 'Object' },
    { id: 'fr1-c93', type: 'Cloze', question: 'Une ___ dans le ciel.', answer: 'étoile', options: ['étoile', 'banane', 'main'], instruction: 'Nature' },
    { id: 'fr1-c94', type: 'Cloze', question: 'C\'est ___ pour toi.', answer: 'mieux', options: ['mieux', 'bleu', 'gros'], instruction: 'Adverb' },
    { id: 'fr1-c95', type: 'Cloze', question: 'Je ___ à bientôt.', answer: 'dis', options: ['dis', 'vois', 'entends'], instruction: 'Action' },
    { id: 'fr1-c96', type: 'Cloze', question: 'La ___ est finie.', answer: 'pause', options: ['pause', 'route', 'main'], instruction: 'Time' },
    { id: 'fr1-c97', type: 'Cloze', question: 'Le ___ est vert.', answer: 'gazon', options: ['gazon', 'ciel', 'lait'], instruction: 'Nature' },
    { id: 'fr1-c98', type: 'Cloze', question: 'Un ___ de couleurs.', answer: 'arc-en-ciel', options: ['arc-en-ciel', 'soleil', 'pont'], instruction: 'Nature' },
    { id: 'fr1-c99', type: 'Cloze', question: 'Il ___ trop tard.', answer: 'est', options: ['est', 'a', 'va'], instruction: 'Time' },
    { id: 'fr1-c100', type: 'Cloze', question: 'Bonne ___ !', answer: 'chance', options: ['chance', 'merci', 'pain'], instruction: 'Greeting' },
  ],
  2: [
    { id: 'fr2-c52', type: 'Cloze', question: 'La semaine ___ , nous sommes allés au zoo.', answer: 'dernière', options: ['dernière', 'prochaine', 'actuelle'], instruction: 'Time' },
    { id: 'fr2-c53', type: 'Cloze', question: 'Il est important de ___ ses dents chaque jour.', answer: 'brosser', options: ['brosser', 'manger', 'perdre'], instruction: 'Health' },
    { id: 'fr2-c54', type: 'Cloze', question: 'Le train ___ à dix heures.', answer: 'part', options: ['part', 'boit', 'dort'], instruction: 'Travel' },
    { id: 'fr2-c55', type: 'Cloze', question: 'Elle ___ une belle chanson.', answer: 'chante', options: ['chante', 'court', 'saute'], instruction: 'Media' },
    { id: 'fr2-c56', type: 'Cloze', question: 'Les enfants ___ dans la rivière.', answer: 'nagent', options: ['nagent', 'mangent', 'lisent'], instruction: 'Activity' },
    { id: 'fr2-c57', type: 'Cloze', question: 'Mon ___ est dans le garage.', answer: 'papa', options: ['papa', 'pont', 'vent'], instruction: 'Family' },
    { id: 'fr2-c58', type: 'Cloze', question: 'Il faut ___ les mains avant de manger.', answer: 'laver', options: ['laver', 'salir', 'cacher'], instruction: 'Health' },
    { id: 'fr2-c59', type: 'Cloze', question: 'Je ___ un gâteau au chocolat.', answer: 'voudrais', options: ['voudrais', 'suis', 'vais'], instruction: 'Desire' },
    { id: 'fr2-c60', type: 'Cloze', question: 'Nous ___ des fleurs dans le jardin.', answer: 'plantons', options: ['plantons', 'mangeons', 'buvons'], instruction: 'Nature' },
    { id: 'fr2-c61', type: 'Cloze', question: 'Le soleil ___ fort cet après-midi.', answer: 'brille', options: ['brille', 'pleut', 'neige'], instruction: 'Weather' },
    { id: 'fr2-c62', type: 'Cloze', question: 'Une ___ de bonbons pour toi.', answer: 'pochette', options: ['pochette', 'route', 'vache'], instruction: 'Object' },
    { id: 'fr2-c63', type: 'Cloze', question: 'Il y a ___ de monde ici.', answer: 'beaucoup', options: ['beaucoup', 'rien', 'pas'], instruction: 'Quantity' },
    { id: 'fr2-c64', type: 'Cloze', question: 'Je ___ mon manteau quand il fait froid.', answer: 'mets', options: ['mets', 'mange', 'lis'], instruction: 'Clothing' },
    { id: 'fr2-c65', type: 'Cloze', question: 'C\'est ___ histoire.', answer: 'une', options: ['une', 'un', 'des'], instruction: 'Article' },
    { id: 'fr2-c66', type: 'Cloze', question: 'Les oiseaux ___ le matin.', answer: 'chantent', options: ['chantent', 'dorment', 'nagent'], instruction: 'Animal' },
    { id: 'fr2-c67', type: 'Cloze', question: 'Ma ___ est à l\'école.', answer: 'sœur', options: ['sœur', 'banane', 'main'], instruction: 'Family' },
    { id: 'fr2-c68', type: 'Cloze', question: 'Un ___ de cerises rouges.', answer: 'kilo', options: ['kilo', 'soleil', 'pont'], instruction: 'Quantity' },
    { id: 'fr2-c69', type: 'Cloze', question: 'C\'est ___ pour la santé.', answer: 'mauvais', options: ['mauvais', 'bleu', 'gros'], instruction: 'Description' },
    { id: 'fr2-c70', type: 'Cloze', question: 'Le ___ aboie fort.', answer: 'chien', options: ['chien', 'chat', 'poisson'], instruction: 'Animal' },
    { id: 'fr2-c71', type: 'Cloze', question: 'Je ___ à mes devoirs.', answer: 'travaille', options: ['travaille', 'dors', 'danse'], instruction: 'School' },
    { id: 'fr2-c72', type: 'Cloze', question: 'Le ___ est sur le bureau.', answer: 'stylo', options: ['stylo', 'avion', 'chapeau'], instruction: 'Object' },
    { id: 'fr2-c73', type: 'Cloze', question: 'Une ___ dans le tiroir.', answer: 'gomme', options: ['gomme', 'route', 'vache'], instruction: 'Object' },
    { id: 'fr2-c74', type: 'Cloze', question: 'Je ___ ma chambre tous les jours.', answer: 'range', options: ['range', 'mange', 'casse'], instruction: 'Action' },
    { id: 'fr2-c75', type: 'Cloze', question: 'Le ___ est plein d\'eau.', answer: 'seau', options: ['seau', 'vent', 'mer'], instruction: 'Object' },
    { id: 'fr2-c76', type: 'Cloze', question: 'Nous ___ à cache-cache.', answer: 'jouons', options: ['jouons', 'dormons', 'buvons'], instruction: 'Activity' },
    { id: 'fr2-c77', type: 'Cloze', question: 'Un ___ de glace.', answer: 'cube', options: ['cube', 'nuage', 'cheval'], instruction: 'Object' },
    { id: 'fr2-c78', type: 'Cloze', question: 'C\'est ___ fini.', answer: 'presque', options: ['presque', 'jamais', 'tout'], instruction: 'Adverb' },
    { id: 'fr2-c79', type: 'Cloze', question: 'La ___ est délicieuse.', answer: 'pizza', options: ['pizza', 'pomme', 'route'], instruction: 'Food' },
    { id: 'fr2-c80', type: 'Cloze', question: 'Regarde cette ___ montagne.', answer: 'grande', options: ['grande', 'bleue', 'grise'], instruction: 'Geography' },
    { id: 'fr2-c81', type: 'Cloze', question: 'Le ___ est très rapide.', answer: 'lion', options: ['lion', 'poisson', 'pont'], instruction: 'Animal' },
    { id: 'fr2-c82', type: 'Cloze', question: 'Une ___ de perles.', answer: 'boîte', options: ['boîte', 'route', 'vache'], instruction: 'Object' },
    { id: 'fr2-c83', type: 'Cloze', question: 'Il y a du ___ aujourd\'hui.', answer: 'soleil', options: ['soleil', 'sucre', 'miel'], instruction: 'Weather' },
    { id: 'fr2-c84', type: 'Cloze', question: 'C\'est ___ gentil de ta part.', answer: 'très', options: ['très', 'jamais', 'pas'], instruction: 'Adverb' },
    { id: 'fr2-c85', type: 'Cloze', question: 'Un ___ de musiciens.', answer: 'groupe', options: ['groupe', 'avion', 'lit'], instruction: 'Media' },
    { id: 'fr2-c86', type: 'Cloze', question: 'Le ___ est fermé le dimanche.', answer: 'magasin', options: ['magasin', 'soleil', 'chien'], instruction: 'Place' },
    { id: 'fr2-c87', type: 'Cloze', question: 'Je ___ une nouvelle chanson.', answer: 'apprends', options: ['apprends', 'mange', 'lis'], instruction: 'Action' },
    { id: 'fr2-c88', type: 'Cloze', question: 'C\'est ___ faux.', answer: 'totalement', options: ['totalement', 'rien', 'pas'], instruction: 'Adverb' },
    { id: 'fr2-c89', type: 'Cloze', question: 'Le ___ est à gauche.', answer: 'pont', options: ['pont', 'mur', 'pain'], instruction: 'Place' },
    { id: 'fr2-c90', type: 'Cloze', question: 'Une ___ de lait frais.', answer: 'bouteille', options: ['bouteille', 'route', 'vache'], instruction: 'Drink' },
    { id: 'fr2-c91', type: 'Cloze', question: 'Il ___ un secret.', answer: 'connaît', options: ['connaît', 'mange', 'boit'], instruction: 'Action' },
    { id: 'fr2-c92', type: 'Cloze', question: 'Mon ___ est en carton.', answer: 'jouet', options: ['jouet', 'pain', 'vent'], instruction: 'Object' },
    { id: 'fr2-c93', type: 'Cloze', question: 'Une ___ de papier.', answer: 'feuille', options: ['feuille', 'fruit', 'main'], instruction: 'Object' },
    { id: 'fr2-c94', type: 'Cloze', question: 'C\'est ___ grave.', answer: 'moins', options: ['moins', 'bleu', 'gros'], instruction: 'Adverb' },
    { id: 'fr2-c95', type: 'Cloze', question: 'Je ___ merci.', answer: 'dis', options: ['dis', 'vois', 'entends'], instruction: 'Action' },
    { id: 'fr2-c96', type: 'Cloze', question: 'La ___ est en bois.', answer: 'table', options: ['table', 'route', 'main'], instruction: 'Home' },
    { id: 'fr2-c97', type: 'Cloze', question: 'Le ___ est à l\'heure.', answer: 'train', options: ['train', 'ciel', 'lait'], instruction: 'Travel' },
    { id: 'fr2-c98', type: 'Cloze', question: 'Un ___ de couleurs vives.', answer: 'mélange', options: ['mélange', 'soleil', 'pont'], instruction: 'Description' },
    { id: 'fr2-c99', type: 'Cloze', question: 'Il ___ une idée géniale.', answer: 'a', options: ['a', 'est', 'va'], instruction: 'Possession' },
    { id: 'fr2-c100', type: 'Cloze', question: 'Bon ___ !', answer: 'voyage', options: ['voyage', 'merci', 'pain'], instruction: 'Greeting' },
  ],
  3: [
    { id: 'fr3-c52', type: 'Cloze', question: 'Le cheval ___ à travers le champ.', answer: 'galope', options: ['galope', 'dort', 'mange'], instruction: 'Action' },
    { id: 'fr3-c53', type: 'Cloze', question: 'Nous ___ demain au cinéma.', answer: 'irons', options: ['irons', 'allons', 'allions'], instruction: 'Time' },
    { id: 'fr3-c54', type: 'Cloze', question: 'L\'oiseau ___ vers le sud en automne.', answer: 'migre', options: ['migre', 'danse', 'chante'], instruction: 'Animal' },
    { id: 'fr3-c55', type: 'Cloze', question: 'Elle ___ une lettre à sa grand-mère.', answer: 'écrit', options: ['écrit', 'boit', 'court'], instruction: 'Action' },
    { id: 'fr3-c56', type: 'Cloze', question: 'Le ___ de la mer est relaxant.', answer: 'bruit', options: ['bruit', 'pain', 'pont'], instruction: 'Sense' },
    { id: 'fr3-c57', type: 'Cloze', question: 'Il faut ___ les règles de sécurité.', answer: 'suivre', options: ['suivre', 'manger', 'perdre'], instruction: 'Social' },
    { id: 'fr3-c58', type: 'Cloze', question: 'Je ___ un nouveau film hier.', answer: 'ai vu', options: ['ai vu', 'vois', 'verrai'], instruction: 'Time' },
    { id: 'fr3-c59', type: 'Cloze', question: 'Les étoiles ___ dans la nuit noire.', answer: 'scintillent', options: ['scintillent', 'murmurent', 'vont'], instruction: 'Nature' },
    { id: 'fr3-c60', type: 'Cloze', question: 'Nous ___ des carottes dans le potager.', answer: 'cueillons', options: ['cueillons', 'buvons', 'lisons'], instruction: 'Nature' },
    { id: 'fr3-c61', type: 'Cloze', question: 'Le ___ souffle fort ce soir.', answer: 'vent', options: ['vent', 'soleil', 'nuage'], instruction: 'Weather' },
    { id: 'fr3-c62', type: 'Cloze', question: 'Une ___ de souvenirs précieux.', answer: 'collection', options: ['collection', 'route', 'vache'], instruction: 'Object' },
    { id: 'fr3-c63', type: 'Cloze', question: 'Il y a ___ trop de bruit ici.', answer: 'bien', options: ['bien', 'rien', 'pas'], instruction: 'Adverb' },
    { id: 'fr3-c64', type: 'Cloze', question: 'Je ___ mes clés le matin.', answer: 'cherche', options: ['cherche', 'mange', 'lis'], instruction: 'Action' },
    { id: 'fr3-c65', type: 'Cloze', question: 'C\'est ___ décision importante.', answer: 'une', options: ['une', 'un', 'des'], instruction: 'Article' },
    { id: 'fr3-c66', type: 'Cloze', question: 'Les ___ travaillent dans la ruche.', answer: 'abeilles', options: ['abeilles', 'chiens', 'lapins'], instruction: 'Animal' },
    { id: 'fr3-c67', type: 'Cloze', question: 'Ma ___ est très gentille avec nous.', answer: 'tante', options: ['tante', 'banane', 'main'], instruction: 'Family' },
    { id: 'fr3-c68', type: 'Cloze', question: 'Un ___ de neige fraîche.', answer: 'manteau', options: ['manteau', 'soleil', 'pont'], instruction: 'Nature' },
    { id: 'fr3-c69', type: 'Cloze', question: 'C\'est ___ pour tout le monde.', answer: 'difficile', options: ['difficile', 'bleu', 'gros'], instruction: 'Description' },
    { id: 'fr3-c70', type: 'Cloze', question: 'Le ___ attend son maître.', answer: 'chien', options: ['chien', 'avion', 'chapeau'], instruction: 'Animal' },
    { id: 'fr3-c71', type: 'Cloze', question: 'Je ___ la vérité maintenant.', answer: 'connais', options: ['connais', 'dors', 'danse'], instruction: 'Action' },
    { id: 'fr3-c72', type: 'Cloze', question: 'Le ___ est bien rangé.', answer: 'classeur', options: ['classeur', 'avion', 'chapeau'], instruction: 'Object' },
    { id: 'fr3-c73', type: 'Cloze', question: 'Une ___ dans le placard.', answer: 'chemise', options: ['chemise', 'route', 'vache'], instruction: 'Clothing' },
    { id: 'fr3-c74', type: 'Cloze', question: 'Je ___ à ma maman souvent.', answer: 'téléphone', options: ['téléphone', 'mange', 'casse'], instruction: 'Action' },
    { id: 'fr3-c75', type: 'Cloze', question: 'Le ___ est à moitié vide.', answer: 'verre', options: ['verre', 'vent', 'mer'], instruction: 'Object' },
    { id: 'fr3-c76', type: 'Cloze', question: 'Nous ___ ensemble à l\'école.', answer: 'étudions', options: ['étudions', 'dormons', 'buvons'], instruction: 'School' },
    { id: 'fr3-c77', type: 'Cloze', question: 'Un ___ de sable fin.', answer: 'grain', options: ['grain', 'nuage', 'cheval'], instruction: 'Nature' },
    { id: 'fr3-c78', type: 'Cloze', question: 'C\'est ___ prêt maintenant.', answer: 'enfin', options: ['enfin', 'jamais', 'tout'], instruction: 'Adverb' },
    { id: 'fr3-c79', type: 'Cloze', question: 'La ___ est ma saison préférée.', answer: 'printemps', options: ['printemps', 'pizza', 'route'], instruction: 'Time' },
    { id: 'fr3-c80', type: 'Cloze', question: 'Regarde cette ___ baleine.', answer: 'énorme', options: ['énorme', 'bleue', 'grise'], instruction: 'Animal' },
    { id: 'fr3-c81', type: 'Cloze', question: 'Le ___ est l\'animal le plus rapide.', answer: 'guépard', options: ['guépard', 'poisson', 'pont'], instruction: 'Animal' },
    { id: 'fr3-c82', type: 'Cloze', question: 'Une ___ de perles rares.', answer: 'chaîne', options: ['chaîne', 'route', 'vache'], instruction: 'Object' },
    { id: 'fr3-c83', type: 'Cloze', question: 'Il y a de la ___ partout.', answer: 'poussière', options: ['poussière', 'sucre', 'miel'], instruction: 'Nature' },
    { id: 'fr3-c84', type: 'Cloze', question: 'C\'est ___ trop cher pour moi.', answer: 'beaucoup', options: ['beaucoup', 'jamais', 'pas'], instruction: 'Adverb' },
    { id: 'fr3-c85', type: 'Cloze', question: 'Un ___ de danseurs talentueux.', answer: 'groupe', options: ['groupe', 'avion', 'lit'], instruction: 'Media' },
    { id: 'fr3-c86', type: 'Cloze', question: 'Le ___ est mon fruit préféré.', answer: 'raisin', options: ['raisin', 'soleil', 'chien'], instruction: 'Food' },
    { id: 'fr3-c87', type: 'Cloze', question: 'Je ___ tous les jours le journal.', answer: 'lis', options: ['lis', 'mange', 'bois'], instruction: 'Action' },
    { id: 'fr3-c88', type: 'Cloze', question: 'C\'est ___ incroyable.', answer: 'absolument', options: ['absolument', 'rien', 'pas'], instruction: 'Adverb' },
    { id: 'fr3-c89', type: 'Cloze', question: 'Le ___ mène à la mer.', answer: 'sentier', options: ['sentier', 'mur', 'pain'], instruction: 'Place' },
    { id: 'fr3-c90', type: 'Cloze', question: 'Une ___ de lait chaud le soir.', answer: 'tasse', options: ['tasse', 'route', 'vache'], instruction: 'Drink' },
    { id: 'fr3-c91', type: 'Cloze', question: 'Il ___ toujours ses promesses.', answer: 'tient', options: ['tient', 'mange', 'boit'], instruction: 'Action' },
    { id: 'fr3-c92', type: 'Cloze', question: 'Mon ___ est très lourd à porter.', answer: 'sac', options: ['sac', 'pain', 'vent'], instruction: 'Object' },
    { id: 'fr3-c93', type: 'Cloze', question: 'Une ___ de papier à lettres.', answer: 'rame', options: ['rame', 'fruit', 'main'], instruction: 'Object' },
    { id: 'fr3-c94', type: 'Cloze', question: 'C\'est ___ possible.', answer: 'plutôt', options: ['plutôt', 'bleu', 'gros'], instruction: 'Adverb' },
    { id: 'fr3-c95', type: 'Cloze', question: 'Je ___ bonne nuit à tous.', answer: 'souhaite', options: ['souhaite', 'vois', 'entends'], instruction: 'Action' },
    { id: 'fr3-c96', type: 'Cloze', question: 'La ___ est en métal brillant.', answer: 'porte', options: ['porte', 'route', 'main'], instruction: 'Home' },
    { id: 'fr3-c97', type: 'Cloze', question: 'Le ___ arrive en gare maintenant.', answer: 'train', options: ['train', 'ciel', 'lait'], instruction: 'Travel' },
    { id: 'fr3-c98', type: 'Cloze', question: 'Un ___ de sons harmonieux.', answer: 'concert', options: ['concert', 'soleil', 'pont'], instruction: 'Media' },
    { id: 'fr3-c99', type: 'Cloze', question: 'Il ___ besoin de ton aide.', answer: 'a', options: ['a', 'est', 'va'], instruction: 'Possession' },
    { id: 'fr3-c100', type: 'Cloze', question: 'Bonne ___ !', answer: 'réussite', options: ['réussite', 'merci', 'pain'], instruction: 'Greeting' },
  ],
  4: [
    { id: 'fr4-c52', type: 'Cloze', question: 'L\'ordinateur ___ de l\'électricité.', answer: 'consomme', options: ['consomme', 'mange', 'dort'], instruction: 'Science' },
    { id: 'fr4-c53', type: 'Cloze', question: 'Nous ___ partir demain matin à l\'aube.', answer: 'devons', options: ['devons', 'allons', 'pouvons'], instruction: 'Social' },
    { id: 'fr4-c54', type: 'Cloze', question: 'L\'eau ___ à cent degrés Celsius.', answer: 'bout', options: ['bout', 'gèle', 'fuit'], instruction: 'Science' },
    { id: 'fr4-c55', type: 'Cloze', question: 'Elle ___ avec beaucoup d\'enthousiasme.', answer: 'travaille', options: ['travaille', 'boit', 'court'], instruction: 'Action' },
    { id: 'fr4-c56', type: 'Cloze', question: 'Le ___ d\'un moteur à réaction.', answer: 'vrombissement', options: ['vrombissement', 'pain', 'pont'], instruction: 'Sense' },
    { id: 'fr4-c57', type: 'Cloze', question: 'Il faut ___ les traditions locales.', answer: 'respecter', options: ['respecter', 'manger', 'perdre'], instruction: 'Social' },
    { id: 'fr4-c58', type: 'Cloze', question: 'Je ___ mon vélo le week-end dernier.', answer: 'ai réparé', options: ['ai réparé', 'répare', 'réparerai'], instruction: 'Time' },
    { id: 'fr4-c59', type: 'Cloze', question: 'Les lumières de la ville ___ au loin.', answer: 'brillent', options: ['brillent', 'murmurent', 'vont'], instruction: 'Nature' },
    { id: 'fr4-c60', type: 'Cloze', question: 'Nous ___ des champignons dans les bois.', answer: 'cherchons', options: ['cherchons', 'buvons', 'lisons'], instruction: 'Nature' },
    { id: 'fr4-c61', type: 'Cloze', question: 'L\'orage ___ dans le lointain.', answer: 'gronde', options: ['gronde', 'soleil', 'nuage'], instruction: 'Weather' },
    { id: 'fr4-c62', type: 'Cloze', question: 'Une ___ de livres de cuisine.', answer: 'étagère', options: ['étagère', 'route', 'vache'], instruction: 'Object' },
    { id: 'fr4-c63', type: 'Cloze', question: 'Il y a ___ trop de circulation.', answer: 'parfois', options: ['parfois', 'rien', 'pas'], instruction: 'Quantity' },
    { id: 'fr4-c64', type: 'Cloze', question: 'Je ___ mes devoirs le soir.', answer: 'fais', options: ['fais', 'mange', 'lis'], instruction: 'Action' },
    { id: 'fr4-c65', type: 'Cloze', question: 'C\'est ___ affaire sérieuse.', answer: 'une', options: ['une', 'un', 'des'], instruction: 'Article' },
    { id: 'fr4-c66', type: 'Cloze', question: 'Les ___ construisent leurs barrages.', answer: 'castors', options: ['castors', 'chiens', 'lapins'], instruction: 'Animal' },
    { id: 'fr4-c67', type: 'Cloze', question: 'Ma ___ nous raconte des histoires.', answer: 'grand-mère', options: ['grand-mère', 'banane', 'main'], instruction: 'Family' },
    { id: 'fr4-c68', type: 'Cloze', question: 'Un ___ de brouillard épais.', answer: 'nuage', options: ['nuage', 'soleil', 'pont'], instruction: 'Nature' },
    { id: 'fr4-c69', type: 'Cloze', question: 'C\'est ___ à comprendre.', answer: 'facile', options: ['facile', 'bleu', 'gros'], instruction: 'Description' },
    { id: 'fr4-c70', type: 'Cloze', question: 'Le ___ garde la ferme fidèlement.', answer: 'chien', options: ['chien', 'avion', 'chapeau'], instruction: 'Animal' },
    { id: 'fr4-c71', type: 'Cloze', question: 'Je ___ mes leçons avec soin.', answer: 'étudie', options: ['étudie', 'dors', 'danse'], instruction: 'Action' },
    { id: 'fr4-c72', type: 'Cloze', question: 'Le ___ est rempli de jouets.', answer: 'coffre', options: ['coffre', 'avion', 'chapeau'], instruction: 'Object' },
    { id: 'fr4-c73', type: 'Cloze', question: 'Une ___ dans l\'armoire.', answer: 'veste', options: ['veste', 'route', 'vache'], instruction: 'Clothing' },
    { id: 'fr4-c74', type: 'Cloze', question: 'Je ___ mon vélo souvent.', answer: 'utilise', options: ['utilise', 'mange', 'casse'], instruction: 'Action' },
    { id: 'fr4-c75', type: 'Cloze', question: 'Le ___ est cristallin ici.', answer: 'lac', options: ['lac', 'vent', 'mer'], instruction: 'Place' },
    { id: 'fr4-c76', type: 'Cloze', question: 'Nous ___ dehors pendant la récréation.', answer: 'courons', options: ['courons', 'dormons', 'buvons'], instruction: 'Activity' },
    { id: 'fr4-c77', type: 'Cloze', question: 'Un ___ de neige fraîche.', answer: 'flocon', options: ['flocon', 'nuage', 'cheval'], instruction: 'Nature' },
    { id: 'fr4-c78', type: 'Cloze', question: 'C\'est ___ terminé maintenant.', answer: 'enfin', options: ['enfin', 'jamais', 'tout'], instruction: 'Adverb' },
    { id: 'fr4-c79', type: 'Cloze', question: 'La ___ est la saison des moissons.', answer: 'été', options: ['été', 'pizza', 'route'], instruction: 'Time' },
    { id: 'fr4-c80', type: 'Cloze', question: 'Regarde cette ___ baleine bleue.', answer: 'gigantesque', options: ['gigantesque', 'bleue', 'grise'], instruction: 'Animal' },
    { id: 'fr4-c81', type: 'Cloze', question: 'Le ___ est un prédateur puissant.', answer: 'tigre', options: ['tigre', 'poisson', 'pont'], instruction: 'Animal' },
    { id: 'fr4-c82', type: 'Cloze', question: 'Une ___ de perles scintillantes.', answer: 'rivière', options: ['rivière', 'route', 'vache'], instruction: 'Object' },
    { id: 'fr4-c83', type: 'Cloze', question: 'Il y a de la ___ sur les sommets.', answer: 'neige', options: ['neige', 'sucre', 'miel'], instruction: 'Nature' },
    { id: 'fr4-c84', type: 'Cloze', question: 'C\'est ___ dommage pour lui.', answer: 'bien', options: ['bien', 'jamais', 'pas'], instruction: 'Adverb' },
    { id: 'fr4-c85', type: 'Cloze', question: 'Un ___ de chercheurs diplômés.', answer: 'groupe', options: ['groupe', 'avion', 'lit'], instruction: 'Media' },
    { id: 'fr4-c86', type: 'Cloze', question: 'Le ___ est une source de vitamines.', answer: 'kiwi', options: ['kiwi', 'soleil', 'chien'], instruction: 'Food' },
    { id: 'fr4-c87', type: 'Cloze', question: 'Je ___ mes emails quotidiennement.', answer: 'consulte', options: ['consulte', 'mange', 'bois'], instruction: 'Action' },
    { id: 'fr4-c88', type: 'Cloze', question: 'C\'est ___ incroyable à voir.', answer: 'tout', options: ['tout', 'rien', 'pas'], instruction: 'Adverb' },
    { id: 'fr4-c89', type: 'Cloze', question: 'Le ___ se perd dans la forêt.', answer: 'sentier', options: ['sentier', 'mur', 'pain'], instruction: 'Place' },
    { id: 'fr4-c90', type: 'Cloze', question: 'Une ___ de lait chaud réconfortante.', answer: 'tasse', options: ['tasse', 'route', 'vache'], instruction: 'Drink' },
    { id: 'fr4-c91', type: 'Cloze', question: 'Il ___ toujours ses engagements.', answer: 'respecte', options: ['respecte', 'mange', 'boit'], instruction: 'Action' },
    { id: 'fr4-c92', type: 'Cloze', question: 'Mon ___ est plein de trésors.', answer: 'coffre', options: ['coffre', 'pain', 'vent'], instruction: 'Object' },
    { id: 'fr4-c93', type: 'Cloze', question: 'Une ___ de papier à dessin.', answer: 'feuille', options: ['feuille', 'fruit', 'main'], instruction: 'Object' },
    { id: 'fr4-c94', type: 'Cloze', question: 'C\'est ___ grave maintenant.', answer: 'moins', options: ['moins', 'bleu', 'gros'], instruction: 'Adverb' },
    { id: 'fr4-c95', type: 'Cloze', question: 'Je ___ la bienvenue aux invités.', answer: 'souhaite', options: ['souhaite', 'vois', 'entends'], instruction: 'Action' },
    { id: 'fr4-c96', type: 'Cloze', question: 'La ___ est forgée en fer.', answer: 'grille', options: ['grille', 'route', 'main'], instruction: 'Home' },
    { id: 'fr4-c97', type: 'Cloze', question: 'Le ___ traverse la vallée.', answer: 'viaduc', options: ['viaduc', 'ciel', 'lait'], instruction: 'Travel' },
    { id: 'fr4-c98', type: 'Cloze', question: 'Un ___ de couleurs chatoyantes.', answer: 'nuancier', options: ['nuancier', 'soleil', 'pont'], instruction: 'Description' },
    { id: 'fr4-c99', type: 'Cloze', question: 'Il ___ une excellente excuse.', answer: 'a', options: ['a', 'est', 'va'], instruction: 'Possession' },
    { id: 'fr4-c100', type: 'Cloze', question: 'Bonne ___ !', answer: 'chance', options: ['chance', 'merci', 'pain'], instruction: 'Greeting' },
  ],
};
