/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const FRANSK_CLOZE_P4: Partial<Record<Grade, GameContent[]>> = {
  5: [
    { id: 'fr5-c52', type: 'Cloze', question: 'Le ___ de l\'univers est vaste.', answer: 'mystère', options: ['mystère', 'pain', 'soleil'], instruction: 'Science' },
    { id: 'fr5-c53', type: 'Cloze', question: 'Nous ___ préserver la nature environnante.', answer: 'devons', options: ['devons', 'allons', 'pouvons'], instruction: 'Social' },
    { id: 'fr5-c54', type: 'Cloze', question: 'L\'eau gèle à ___ degrés Celsius.', answer: 'zéro', options: ['zéro', 'cent', 'cinquante'], instruction: 'Science' },
    { id: 'fr5-c55', type: 'Cloze', question: 'Elle ___ avec rigueur et précision.', answer: 'travaille', options: ['travaille', 'boit', 'court'], instruction: 'Action' },
    { id: 'fr5-c56', type: 'Cloze', question: 'Le ___ d\'un réacteur nucléaire.', answer: 'fonctionnement', options: ['fonctionnement', 'pain', 'pont'], instruction: 'Science' },
    { id: 'fr5-c57', type: 'Cloze', question: 'Il faut ___ les lois en vigueur.', answer: 'observer', options: ['observer', 'manger', 'perdre'], instruction: 'Social' },
    { id: 'fr5-c58', type: 'Cloze', question: 'Je ___ mon vélo le mois dernier.', answer: 'ai réparé', options: ['ai réparé', 'répare', 'réparerai'], instruction: 'Time' },
    { id: 'fr5-c59', type: 'Cloze', question: 'Les phares du port ___ dans la brume.', answer: 'clignotent', options: ['clignotent', 'murmurent', 'vont'], instruction: 'Social' },
    { id: 'fr5-c60', type: 'Cloze', question: 'Nous ___ des herbes médicinales.', answer: 'étudions', options: ['étudions', 'buvons', 'lisons'], instruction: 'Biology' },
    { id: 'fr5-c61', type: 'Cloze', question: 'La ___ est une source d\'énergie.', answer: 'chaleur', options: ['chaleur', 'sucre', 'miel'], instruction: 'Science' },
    { id: 'fr5-c62', type: 'Cloze', question: 'Une ___ de données informatiques.', answer: 'base', options: ['base', 'route', 'vache'], instruction: 'Science' },
    { id: 'fr5-c63', type: 'Cloze', question: 'Il y a ___ trop de pollution.', answer: 'souvent', options: ['souvent', 'rien', 'pas'], instruction: 'Society' },
    { id: 'fr5-c64', type: 'Cloze', question: 'Je ___ mes devoirs sérieusement.', answer: 'fais', options: ['fais', 'mange', 'lis'], instruction: 'School' },
    { id: 'fr5-c65', type: 'Cloze', question: 'C\'est ___ décision collective.', answer: 'une', options: ['une', 'un', 'des'], instruction: 'Article' },
    { id: 'fr5-c66', type: 'Cloze', question: 'Les ___ migrent chaque année.', answer: 'baleines', options: ['baleines', 'chiens', 'lapins'], instruction: 'Animal' },
    { id: 'fr5-c67', type: 'Cloze', question: 'Ma ___ est une experte en cuisine.', answer: 'tante', options: ['tante', 'banane', 'main'], instruction: 'Family' },
    { id: 'fr5-c68', type: 'Cloze', question: 'Un ___ de brouillard sur la côte.', answer: 'banc', options: ['banc', 'soleil', 'pont'], instruction: 'Nature' },
    { id: 'fr5-c69', type: 'Cloze', question: 'C\'est ___ à démontrer mathématiquement.', answer: 'simple', options: ['simple', 'bleu', 'gros'], instruction: 'Science' },
    { id: 'fr5-c70', type: 'Cloze', question: 'Le ___ guide les explorateurs.', answer: 'boussole', options: ['boussole', 'avion', 'chapeau'], instruction: 'Object' },
    { id: 'fr5-c71', type: 'Cloze', question: 'Je ___ la solution du problème.', answer: 'cherche', options: ['cherche', 'dors', 'danse'], instruction: 'Action' },
    { id: 'fr5-c72', type: 'Cloze', question: 'Le ___ est un outil indispensable.', answer: 'clavier', options: ['clavier', 'avion', 'chapeau'], instruction: 'Object' },
    { id: 'fr5-c73', type: 'Cloze', question: 'Une ___ dans le placard à balais.', answer: 'poussière', options: ['poussière', 'route', 'vache'], instruction: 'Home' },
    { id: 'fr5-c74', type: 'Cloze', question: 'Je ___ mon vélo pour aller travailler.', answer: 'prends', options: ['prends', 'mange', 'casse'], instruction: 'Action' },
    { id: 'fr5-c75', type: 'Cloze', question: 'Le ___ est un écosystème fragile.', answer: 'lagon', options: ['lagon', 'vent', 'mer'], instruction: 'Place' },
    { id: 'fr5-c76', type: 'Cloze', question: 'Nous ___ pour la liberté.', answer: 'luttons', options: ['luttons', 'dormons', 'buvons'], instruction: 'Social' },
    { id: 'fr5-c77', type: 'Cloze', question: 'Un ___ de sable dans la montre.', answer: 'grain', options: ['grain', 'nuage', 'cheval'], instruction: 'Nature' },
    { id: 'fr5-c78', type: 'Cloze', question: 'C\'est ___ terminé pour aujourd\'hui.', answer: 'enfin', options: ['enfin', 'jamais', 'tout'], instruction: 'Adverb' },
    { id: 'fr5-c79', type: 'Cloze', question: 'La ___ est la saison des amours.', answer: 'printemps', options: ['printemps', 'pizza', 'route'], instruction: 'Time' },
    { id: 'fr5-c80', type: 'Cloze', question: 'Regarde cette ___ baleine gigantesque.', answer: 'énorme', options: ['énorme', 'bleue', 'grise'], instruction: 'Animal' },
    { id: 'fr5-c81', type: 'Cloze', question: 'Le ___ est un métal précieux.', answer: 'platine', options: ['platine', 'poisson', 'pont'], instruction: 'Science' },
    { id: 'fr5-c82', type: 'Cloze', question: 'Une ___ de perles de culture.', answer: 'longue', options: ['longue', 'route', 'vache'], instruction: 'Object' },
    { id: 'fr5-c83', type: 'Cloze', question: 'Il y a de la ___ sur les toits.', answer: 'givre', options: ['givre', 'sucre', 'miel'], instruction: 'Weather' },
    { id: 'fr5-c84', type: 'Cloze', question: 'C\'est ___ regrettable pour nous.', answer: 'bien', options: ['bien', 'jamais', 'pas'], instruction: 'Adverb' },
    { id: 'fr5-c85', type: 'Cloze', question: 'Un ___ de musiciens professionnels.', answer: 'ensemble', options: ['ensemble', 'avion', 'lit'], instruction: 'Media' },
    { id: 'fr5-c86', type: 'Cloze', question: 'Le ___ est un fruit exotique savoureux.', answer: 'manguier', options: ['manguier', 'soleil', 'chien'], instruction: 'Food' },
    { id: 'fr5-c87', type: 'Cloze', question: 'Je ___ mes factures chaque mois.', answer: 'paie', options: ['paie', 'mange', 'bois'], instruction: 'Action' },
    { id: 'fr5-c88', type: 'Cloze', question: 'C\'est ___ fantastique à entendre.', answer: 'tout', options: ['tout', 'rien', 'pas'], instruction: 'Adverb' },
    { id: 'fr5-c89', type: 'Cloze', question: 'Le ___ de randonnée est balisé.', answer: 'sentier', options: ['sentier', 'mur', 'pain'], instruction: 'Place' },
    { id: 'fr5-c90', type: 'Cloze', question: 'Une ___ de thé bien chaud.', answer: 'tasse', options: ['tasse', 'route', 'vache'], instruction: 'Drink' },
    { id: 'fr5-c91', type: 'Cloze', question: 'Il ___ toujours ses engagements solennels.', answer: 'honore', options: ['honore', 'mange', 'boit'], instruction: 'Action' },
    { id: 'fr5-c92', type: 'Cloze', question: 'Mon ___ est plein de documents.', answer: 'cartable', options: ['cartable', 'pain', 'vent'], instruction: 'Object' },
    { id: 'fr5-c93', type: 'Cloze', question: 'Une ___ de papier glacé.', answer: 'feuille', options: ['feuille', 'fruit', 'main'], instruction: 'Object' },
    { id: 'fr5-c94', type: 'Cloze', question: 'C\'est ___ important maintenant.', answer: 'moins', options: ['moins', 'bleu', 'gros'], instruction: 'Adverb' },
    { id: 'fr5-c95', type: 'Cloze', question: 'Je ___ la bienvenue aux nouveaux.', answer: 'souhaite', options: ['souhaite', 'vois', 'entends'], instruction: 'Action' },
    { id: 'fr5-c96', type: 'Cloze', question: 'La ___ est en aluminium léger.', answer: 'grille', options: ['grille', 'route', 'main'], instruction: 'Home' },
    { id: 'fr5-c97', type: 'Cloze', question: 'Le ___ traverse la plaine.', answer: 'canal', options: ['canal', 'ciel', 'lait'], instruction: 'Place' },
    { id: 'fr5-c98', type: 'Cloze', question: 'Un ___ de couleurs vives.', answer: 'palettier', options: ['palettier', 'soleil', 'pont'], instruction: 'Description' },
    { id: 'fr5-c99', type: 'Cloze', question: 'Il ___ une excellente réputation.', answer: 'a', options: ['a', 'est', 'va'], instruction: 'Possession' },
    { id: 'fr5-c100', type: 'Cloze', question: 'Bonne ___ !', answer: 'chance', options: ['chance', 'merci', 'pain'], instruction: 'Greeting' },
  ],
  6: [
    { id: 'fr6-c52', type: 'Cloze', question: 'L\'auteur ___ ses lecteurs par son style.', answer: 'captive', options: ['captive', 'fuit', 'ignore'], instruction: 'Literature' },
    { id: 'fr6-c53', type: 'Cloze', question: 'Nous ___ analyser les métaphores du texte.', answer: 'savons', options: ['savons', 'allons', 'pouvons'], instruction: 'Analysis' },
    { id: 'fr6-c54', type: 'Cloze', question: 'Le ___ de l\'histoire est complexe.', answer: 'dénouement', options: ['dénouement', 'début', 'milieu'], instruction: 'Analysis' },
    { id: 'fr6-c55', type: 'Cloze', question: 'Elle ___ avec passion ses poèmes.', answer: 'déclame', options: ['déclame', 'boit', 'court'], instruction: 'Action' },
    { id: 'fr6-c56', type: 'Cloze', question: 'Le ___ poétique est remarquable ici.', answer: 'procédé', options: ['procédé', 'pain', 'pont'], instruction: 'Poetry' },
    { id: 'fr6-c57', type: 'Cloze', question: 'Il faut ___ les intentions de l\'auteur.', answer: 'décrypter', options: ['décrypter', 'manger', 'perdre'], instruction: 'Analysis' },
    { id: 'fr6-c58', type: 'Cloze', question: 'Je ___ mon livre préféré hier.', answer: 'ai relu', options: ['ai relu', 'lis', 'lirai'], instruction: 'Time' },
    { id: 'fr6-c59', type: 'Cloze', question: 'Les alexandrins ___ dans ce poème.', answer: 'résonnent', options: ['résonnent', 'murmurent', 'vont'], instruction: 'Poetry' },
    { id: 'fr6-c60', type: 'Cloze', question: 'Nous ___ des figures de style.', answer: 'relevons', options: ['relevons', 'buvons', 'lisons'], instruction: 'Analysis' },
    { id: 'fr6-c61', type: 'Cloze', question: 'La ___ est le cœur du roman.', answer: 'intrigue', options: ['intrigue', 'sucre', 'miel'], instruction: 'Literature' },
    { id: 'fr6-c62', type: 'Cloze', question: 'Une ___ de littérature classique.', answer: 'anthologie', options: ['anthologie', 'route', 'vache'], instruction: 'Literature' },
    { id: 'fr6-c63', type: 'Cloze', question: 'Il y a ___ trop de descriptions.', answer: 'souvent', options: ['souvent', 'rien', 'pas'], instruction: 'Analysis' },
    { id: 'fr6-c64', type: 'Cloze', question: 'Je ___ l\'évolution du personnage.', answer: 'suis', options: ['suis', 'mange', 'lis'], instruction: 'Analysis' },
    { id: 'fr6-c65', type: 'Cloze', question: 'C\'est ___ œuvre majeure du siècle.', answer: 'une', options: ['une', 'un', 'des'], instruction: 'Article' },
    { id: 'fr6-c66', type: 'Cloze', question: 'Les ___ se querellent dans la pièce.', answer: 'antagonistes', options: ['antagonistes', 'chiens', 'lapins'], instruction: 'Literature' },
    { id: 'fr6-c67', type: 'Cloze', question: 'Ma ___ est une lectrice assidue.', answer: 'cousine', options: ['cousine', 'banane', 'main'], instruction: 'Family' },
    { id: 'fr6-c68', type: 'Cloze', question: 'Un ___ de poésie lyrique.', answer: 'recueil', options: ['recueil', 'soleil', 'pont'], instruction: 'Literature' },
    { id: 'fr6-c69', type: 'Cloze', question: 'C\'est ___ à interpréter diversement.', answer: 'aisé', options: ['aisé', 'bleu', 'gros'], instruction: 'Analysis' },
    { id: 'fr6-c70', type: 'Cloze', question: 'Le ___ symbolise la liberté perdue.', answer: 'vol', options: ['vol', 'avion', 'chapeau'], instruction: 'Symbolism' },
    { id: 'fr6-c71', type: 'Cloze', question: 'Je ___ le sens caché du texte.', answer: 'découvre', options: ['découvre', 'dors', 'danse'], instruction: 'Analysis' },
    { id: 'fr6-c72', type: 'Cloze', question: 'Le ___ est un élément clé ici.', answer: 'narrateur', options: ['narrateur', 'avion', 'chapeau'], instruction: 'Object' },
    { id: 'fr6-c73', type: 'Cloze', question: 'Une ___ dans le chapitre cinq.', answer: 'ellipse', options: ['ellipse', 'route', 'vache'], instruction: 'Literature' },
    { id: 'fr6-c74', type: 'Cloze', question: 'Je ___ les sources historiques citées.', answer: 'vérifie', options: ['vérifie', 'mange', 'casse'], instruction: 'Action' },
    { id: 'fr6-c75', type: 'Cloze', question: 'Le ___ est planté dès le début.', answer: 'décor', options: ['décor', 'vent', 'mer'], instruction: 'Place' },
    { id: 'fr6-c76', type: 'Cloze', question: 'Nous ___ pour comprendre le message.', answer: 'réfléchissons', options: ['réfléchissons', 'dormons', 'buvons'], instruction: 'Action' },
    { id: 'fr6-c77', type: 'Cloze', question: 'Un ___ de tragédie classique.', answer: 'ton', options: ['ton', 'nuage', 'cheval'], instruction: 'Genre' },
    { id: 'fr6-c78', type: 'Cloze', question: 'C\'est ___ presque fini le livre.', answer: 'déjà', options: ['déjà', 'jamais', 'tout'], instruction: 'Adverb' },
    { id: 'fr6-c79', type: 'Cloze', question: 'La ___ est un mouvement littéraire.', answer: 'pléiade', options: ['pléiade', 'pizza', 'route'], instruction: 'Literature' },
    { id: 'fr6-c80', type: 'Cloze', question: 'Regarde cette ___ métaphore filée.', answer: 'longue', options: ['longue', 'bleue', 'grise'], instruction: 'Analysis' },
    { id: 'fr6-c81', type: 'Cloze', question: 'Le ___ est le thème central du poème.', answer: 'temps', options: ['temps', 'poisson', 'pont'], instruction: 'Theme' },
    { id: 'fr6-c82', type: 'Cloze', question: 'Une ___ de vers bien rythmés.', answer: 'strophe', options: ['strophe', 'route', 'vache'], instruction: 'Poetry' },
    { id: 'fr6-c83', type: 'Cloze', question: 'Il y a de la ___ dans ses paroles.', answer: 'nostalgie', options: ['nostalgie', 'sucre', 'miel'], instruction: 'Feeling' },
    { id: 'fr6-c84', type: 'Cloze', question: 'C\'est ___ tout à fait juste.', answer: 'presque', options: ['presque', 'jamais', 'pas'], instruction: 'Adverb' },
    { id: 'fr6-c85', type: 'Cloze', question: 'Un ___ d\'auteurs contemporains.', answer: 'cercle', options: ['cercle', 'avion', 'lit'], instruction: 'Literature' },
    { id: 'fr6-c86', type: 'Cloze', question: 'Le ___ est un genre épistolaire.', answer: 'roman', options: ['roman', 'soleil', 'chien'], instruction: 'Genre' },
    { id: 'fr6-c87', type: 'Cloze', question: 'Je ___ mes poèmes préférés.', answer: 'recopie', options: ['recopie', 'mange', 'bois'], instruction: 'Action' },
    { id: 'fr6-c88', type: 'Cloze', question: 'C\'est ___ dommage de ne pas lire.', answer: 'tellement', options: ['tellement', 'rien', 'pas'], instruction: 'Adverb' },
    { id: 'fr6-c89', type: 'Cloze', question: 'Le ___ de lecture est agréable.', answer: 'plaisir', options: ['plaisir', 'mur', 'pain'], instruction: 'Feeling' },
    { id: 'fr6-c90', type: 'Cloze', question: 'Une ___ de littérature étrangère.', answer: 'œuvre', options: ['œuvre', 'route', 'vache'], instruction: 'Literature' },
    { id: 'fr6-c91', type: 'Cloze', question: 'Il ___ toujours ses lectures avec brio.', answer: 'commente', options: ['commente', 'mange', 'boit'], instruction: 'Action' },
    { id: 'fr6-c92', type: 'Cloze', question: 'Mon ___ de français est complet.', answer: 'manuel', options: ['manuel', 'pain', 'vent'], instruction: 'School' },
    { id: 'fr6-c93', type: 'Cloze', question: 'Une ___ de citations mémorables.', answer: 'page', options: ['page', 'fruit', 'main'], instruction: 'Literature' },
    { id: 'fr6-c94', type: 'Cloze', question: 'C\'est ___ important d\'écrire.', answer: 'plus', options: ['plus', 'bleu', 'gros'], instruction: 'Adverb' },
    { id: 'fr6-c95', type: 'Cloze', question: 'Je ___ la bienvenue aux lecteurs.', answer: 'souhaite', options: ['souhaite', 'vois', 'entends'], instruction: 'Action' },
    { id: 'fr6-c96', type: 'Cloze', question: 'La ___ est une forme de dialogue.', answer: 'tirade', options: ['tirade', 'route', 'main'], instruction: 'Theater' },
    { id: 'fr6-c97', type: 'Cloze', question: 'Le ___ est un personnage secondaire.', answer: 'valet', options: ['valet', 'ciel', 'lait'], instruction: 'Theater' },
    { id: 'fr6-c98', type: 'Cloze', question: 'Un ___ de sentiments contradictoires.', answer: 'mélange', options: ['mélange', 'soleil', 'pont'], instruction: 'Analysis' },
    { id: 'fr6-c99', type: 'Cloze', question: 'Il ___ une plume acérée.', answer: 'a', options: ['a', 'est', 'va'], instruction: 'Possession' },
    { id: 'fr6-c100', type: 'Cloze', question: 'Bonne ___ !', answer: 'lecture', options: ['lecture', 'merci', 'pain'], instruction: 'Greeting' },
  ],
  7: [
    { id: 'fr7-c52', type: 'Cloze', question: 'L\'argumentation ___ à convaincre l\'autre.', answer: 'vise', options: ['vise', 'fuit', 'ignore'], instruction: 'Argumentation' },
    { id: 'fr7-c53', type: 'Cloze', question: 'Nous ___ utiliser des exemples concrets.', answer: 'devons', options: ['devons', 'allons', 'pouvons'], instruction: 'Method' },
    { id: 'fr7-c54', type: 'Cloze', question: 'Le ___ de la pensée critique.', answer: 'développement', options: ['développement', 'début', 'milieu'], instruction: 'Philosophy' },
    { id: 'fr7-c55', type: 'Cloze', question: 'Elle ___ avec éloquence son point de vue.', answer: 'expose', options: ['expose', 'boit', 'court'], instruction: 'Action' },
    { id: 'fr7-c56', type: 'Cloze', question: 'Le ___ rhétorique est efficace ici.', answer: 'stratagème', options: ['stratagème', 'pain', 'pont'], instruction: 'Rhetoric' },
    { id: 'fr7-c57', type: 'Cloze', question: 'Il faut ___ les arguments opposés.', answer: 'anticiper', options: ['anticiper', 'mange', 'perdre'], instruction: 'Argumentation' },
    { id: 'fr7-c58', type: 'Cloze', question: 'Je ___ mon opinion hier soir.', answer: 'ai changé', options: ['ai changé', 'change', 'changerai'], instruction: 'Time' },
    { id: 'fr7-c59', type: 'Cloze', question: 'Les sophismes ___ souvent dans les débats.', answer: 'apparaissent', options: ['apparaissent', 'murmurent', 'vont'], instruction: 'Philosophy' },
    { id: 'fr7-c60', type: 'Cloze', question: 'Nous ___ des syllogismes logiques.', answer: 'étudions', options: ['étudions', 'buvons', 'lisons'], instruction: 'Logic' },
    { id: 'fr7-c61', type: 'Cloze', question: 'La ___ est essentielle pour débattre.', answer: 'rigueur', options: ['rigueur', 'sucre', 'miel'], instruction: 'Argumentation' },
    { id: 'fr7-c62', type: 'Cloze', question: 'Une ___ de philosophie antique.', answer: 'somme', options: ['somme', 'route', 'vache'], instruction: 'Philosophy' },
    { id: 'fr7-c63', type: 'Cloze', question: 'Il y a ___ trop de mauvaise foi.', answer: 'parfois', options: ['parfois', 'rien', 'pas'], instruction: 'Social' },
    { id: 'fr7-c64', type: 'Cloze', question: 'Je ___ le fil de ton raisonnement.', answer: 'comprends', options: ['comprends', 'mange', 'lis'], instruction: 'Logic' },
    { id: 'fr7-c65', type: 'Cloze', question: 'C\'est ___ question de principe.', answer: 'une', options: ['une', 'un', 'des'], instruction: 'Article' },
    { id: 'fr7-c66', type: 'Cloze', question: 'Les ___ s\'affrontent dans l\'arène.', answer: 'orateurs', options: ['orateurs', 'chiens', 'lapins'], instruction: 'Rhetoric' },
    { id: 'fr7-c67', type: 'Cloze', question: 'Ma ___ est une excellente débatteuse.', answer: 'fille', options: ['fille', 'banane', 'main'], instruction: 'Family' },
    { id: 'fr7-c68', type: 'Cloze', question: 'Un ___ de connaissances encyclopédiques.', answer: 'socle', options: ['socle', 'soleil', 'pont'], instruction: 'Education' },
    { id: 'fr7-c69', type: 'Cloze', question: 'C\'est ___ à comprendre finalement.', answer: 'facile', options: ['facile', 'bleu', 'gros'], instruction: 'Description' },
    { id: 'fr7-c70', type: 'Cloze', question: 'Le ___ est un art difficile.', answer: 'discours', options: ['discours', 'avion', 'chapeau'], instruction: 'Object' },
    { id: 'fr7-c71', type: 'Cloze', question: 'Je ___ les contradictions du texte.', answer: 'relève', options: ['relève', 'dors', 'danse'], instruction: 'Analysis' },
    { id: 'fr7-c72', type: 'Cloze', question: 'Le ___ est primordial en rhétorique.', answer: 'contexte', options: ['contexte', 'avion', 'chapeau'], instruction: 'Object' },
    { id: 'fr7-c73', type: 'Cloze', question: 'Une ___ dans le raisonnement logique.', answer: 'faille', options: ['faille', 'route', 'vache'], instruction: 'Logic' },
    { id: 'fr7-c74', type: 'Cloze', question: 'Je ___ mes sources avant de parler.', answer: 'vérifie', options: ['vérifie', 'mange', 'casse'], instruction: 'Action' },
    { id: 'fr7-c75', type: 'Cloze', question: 'Le ___ de la liberté est cher.', answer: 'prix', options: ['prix', 'vent', 'mer'], instruction: 'Philosophy' },
    { id: 'fr7-c76', type: 'Cloze', question: 'Nous ___ pour la justice sociale.', answer: 'militons', options: ['militons', 'dormons', 'buvons'], instruction: 'Social' },
    { id: 'fr7-c77', type: 'Cloze', question: 'Un ___ d\'humanité dans ce monde.', answer: 'peu', options: ['peu', 'nuage', 'cheval'], instruction: 'Philosophy' },
    { id: 'fr7-c78', type: 'Cloze', question: 'C\'est ___ terminé pour le débat.', answer: 'enfin', options: ['enfin', 'jamais', 'tout'], instruction: 'Adverb' },
    { id: 'fr7-c79', type: 'Cloze', question: 'La ___ est une vertu cardinale.', answer: 'prudence', options: ['prudence', 'pizza', 'route'], instruction: 'Philosophy' },
    { id: 'fr7-c80', type: 'Cloze', question: 'Regarde cette ___ démonstration implacable.', answer: 'brillante', options: ['brillante', 'bleue', 'grise'], instruction: 'Analysis' },
    { id: 'fr7-c81', type: 'Cloze', question: 'Le ___ est au centre de l\'éthique.', answer: 'bien', options: ['bien', 'poisson', 'pont'], instruction: 'Ethics' },
    { id: 'fr7-c82', type: 'Cloze', question: 'Une ___ de jugements moraux.', answer: 'série', options: ['série', 'route', 'vache'], instruction: 'Ethics' },
    { id: 'fr7-c83', type: 'Cloze', question: 'Il y a de la ___ dans ses propos.', answer: 'sagesse', options: ['sagesse', 'sucre', 'miel'], instruction: 'Philosophy' },
    { id: 'fr7-c84', type: 'Cloze', question: 'C\'est ___ tout à fait exceptionnel.', answer: 'presque', options: ['presque', 'jamais', 'pas'], instruction: 'Adverb' },
    { id: 'fr7-c85', type: 'Cloze', question: 'Un ___ d\'intellectuels engagés.', answer: 'groupe', options: ['groupe', 'avion', 'lit'], instruction: 'Society' },
    { id: 'fr7-c86', type: 'Cloze', question: 'Le ___ est un concept métaphysique.', answer: 'néant', options: ['néant', 'soleil', 'chien'], instruction: 'Philosophy' },
    { id: 'fr7-c87', type: 'Cloze', question: 'Je ___ mes idées par écrit.', answer: 'clarifie', options: ['clarifie', 'mange', 'bois'], instruction: 'Action' },
    { id: 'fr7-c88', type: 'Cloze', question: 'C\'est ___ tout ce dont j\'ai besoin.', answer: 'exactement', options: ['exactement', 'rien', 'pas'], instruction: 'Adverb' },
    { id: 'fr7-c89', type: 'Cloze', question: 'Le ___ du devoir nous appelle.', answer: 'sentiment', options: ['sentiment', 'mur', 'pain'], instruction: 'Ethics' },
    { id: 'fr7-c90', type: 'Cloze', question: 'Une ___ de philosophie existentielle.', answer: 'leçon', options: ['leçon', 'route', 'vache'], instruction: 'Philosophy' },
    { id: 'fr7-c91', type: 'Cloze', question: 'Il ___ toujours ses convictions profondes.', answer: 'défend', options: ['défend', 'mange', 'boit'], instruction: 'Action' },
    { id: 'fr7-c92', type: 'Cloze', question: 'Mon ___ de réflexion est ouvert.', answer: 'espace', options: ['espace', 'pain', 'vent'], instruction: 'Philosophy' },
    { id: 'fr7-c93', type: 'Cloze', question: 'Une ___ de sagesse populaire.', answer: 'parole', options: ['parole', 'fruit', 'main'], instruction: 'Philosophy' },
    { id: 'fr7-c94', type: 'Cloze', question: 'C\'est ___ important d\'écouter.', answer: 'plus', options: ['plus', 'bleu', 'gros'], instruction: 'Adverb' },
    { id: 'fr7-c95', type: 'Cloze', question: 'Je ___ bonne route aux voyageurs.', answer: 'souhaite', options: ['souhaite', 'vois', 'entends'], instruction: 'Action' },
    { id: 'fr7-c96', type: 'Cloze', question: 'La ___ est une école de pensée.', answer: 'stoïcisme', options: ['stoïcisme', 'route', 'main'], instruction: 'Philosophy' },
    { id: 'fr7-c97', type: 'Cloze', question: 'Le ___ est un disciple fidèle.', answer: 'disciple', options: ['disciple', 'ciel', 'lait'], instruction: 'Philosophy' },
    { id: 'fr7-c98', type: 'Cloze', question: 'Un ___ de cultures différentes.', answer: 'mélange', options: ['mélange', 'soleil', 'pont'], instruction: 'Society' },
    { id: 'fr7-c99', type: 'Cloze', question: 'Il ___ une vision globale.', answer: 'a', options: ['a', 'est', 'va'], instruction: 'Possession' },
    { id: 'fr7-c100', type: 'Cloze', question: 'Bonne ___ !', answer: 'chance', options: ['chance', 'merci', 'pain'], instruction: 'Greeting' },
  ],
  8: [
    { id: 'fr8-c52', type: 'Cloze', question: 'La société ___ aux défis climatiques.', answer: 'réagit', options: ['réagit', 'fuit', 'ignore'], instruction: 'Society' },
    { id: 'fr8-c53', type: 'Cloze', question: 'Nous ___ adopter des modes de vie durables.', answer: 'devons', options: ['devons', 'allons', 'pouvons'], instruction: 'Action' },
    { id: 'fr8-c54', type: 'Cloze', question: 'Le ___ technologique est exponentiel.', answer: 'progrès', options: ['progrès', 'début', 'milieu'], instruction: 'Science' },
    { id: 'fr8-c55', type: 'Cloze', question: 'Elle ___ avec détermination pour la paix.', answer: 'œuvre', options: ['œuvre', 'boit', 'court'], instruction: 'Action' },
    { id: 'fr8-c56', type: 'Cloze', question: 'Le ___ économique mondial est complexe.', answer: 'système', options: ['système', 'pain', 'pont'], instruction: 'Economy' },
    { id: 'fr8-c57', type: 'Cloze', question: 'Il faut ___ les libertés individuelles.', answer: 'protéger', options: ['protéger', 'manger', 'perdre'], instruction: 'Social' },
    { id: 'fr8-c58', type: 'Cloze', question: 'Je ___ ma voiture électrique hier.', answer: 'ai chargé', options: ['ai chargé', 'charge', 'chargerai'], instruction: 'Time' },
    { id: 'fr8-c59', type: 'Cloze', question: 'Les énergies ___ sont l\'avenir.', answer: 'vertes', options: ['vertes', 'murmurent', 'vont'], instruction: 'Science' },
    { id: 'fr8-c60', type: 'Cloze', question: 'Nous ___ des rapports sociologiques.', answer: 'rédigeons', options: ['rédigeons', 'buvons', 'lisons'], instruction: 'Society' },
    { id: 'fr8-c61', type: 'Cloze', question: 'La ___ est le pilier de la démocratie.', answer: 'loi', options: ['loi', 'sucre', 'miel'], instruction: 'Politics' },
    { id: 'fr8-c62', type: 'Cloze', question: 'Une ___ de droits fondamentaux.', answer: 'charte', options: ['charte', 'route', 'vache'], instruction: 'Politics' },
    { id: 'fr8-c63', type: 'Cloze', question: 'Il y a ___ trop d\'inégalités.', answer: 'toujours', options: ['toujours', 'rien', 'pas'], instruction: 'Society' },
    { id: 'fr8-c64', type: 'Cloze', question: 'Je ___ les tendances du marché.', answer: 'analyse', options: ['analyse', 'mange', 'lis'], instruction: 'Economy' },
    { id: 'fr8-c65', type: 'Cloze', question: 'C\'est ___ responsabilité partagée.', answer: 'une', options: ['une', 'un', 'des'], instruction: 'Article' },
    { id: 'fr8-c66', type: 'Cloze', question: 'Les ___ se mobilisent en masse.', answer: 'citoyens', options: ['citoyens', 'chiens', 'lapins'], instruction: 'Society' },
    { id: 'fr8-c67', type: 'Cloze', question: 'Ma ___ est une femme engagée.', answer: 'tante', options: ['tante', 'banane', 'main'], instruction: 'Family' },
    { id: 'fr8-c68', type: 'Cloze', question: 'Un ___ de réformes politiques.', answer: 'cycle', options: ['cycle', 'soleil', 'pont'], instruction: 'Politics' },
    { id: 'fr8-c69', type: 'Cloze', question: 'C\'est ___ à mettre en œuvre.', answer: 'ardu', options: ['ardu', 'bleu', 'gros'], instruction: 'Description' },
    { id: 'fr8-c70', type: 'Cloze', question: 'Le ___ est un enjeu majeur.', answer: 'travail', options: ['travail', 'avion', 'chapeau'], instruction: 'Object' },
    { id: 'fr8-c71', type: 'Cloze', question: 'Je ___ les injustices sociales.', answer: 'dénonce', options: ['dénonce', 'dors', 'danse'], instruction: 'Action' },
    { id: 'fr8-c72', type: 'Cloze', question: 'Le ___ est un acteur global.', answer: 'pays', options: ['pays', 'avion', 'chapeau'], instruction: 'Object' },
    { id: 'fr8-c73', type: 'Cloze', question: 'Une ___ dans le système bancaire.', answer: 'faille', options: ['faille', 'route', 'vache'], instruction: 'Economy' },
    { id: 'fr8-c74', type: 'Cloze', question: 'Je ___ mes déchets quotidiennement.', answer: 'trie', options: ['trie', 'mange', 'casse'], instruction: 'Action' },
    { id: 'fr8-c75', type: 'Cloze', question: 'Le ___ est un droit inaliénable.', answer: 'vote', options: ['vote', 'vent', 'mer'], instruction: 'Politics' },
    { id: 'fr8-c76', type: 'Cloze', question: 'Nous ___ pour un monde meilleur.', answer: 'œuvrons', options: ['œuvrons', 'dormons', 'buvons'], instruction: 'Social' },
    { id: 'fr8-c77', type: 'Cloze', question: 'Un ___ de coopération internationale.', answer: 'pacte', options: ['pacte', 'nuage', 'cheval'], instruction: 'Politics' },
    { id: 'fr8-c78', type: 'Cloze', question: 'C\'est ___ terminé pour le projet.', answer: 'presque', options: ['presque', 'jamais', 'tout'], instruction: 'Adverb' },
    { id: 'fr8-c79', type: 'Cloze', question: 'La ___ est une préoccupation majeure.', answer: 'santé', options: ['santé', 'pizza', 'route'], instruction: 'Society' },
    { id: 'fr8-c80', type: 'Cloze', question: 'Regarde cette ___ croissance économique.', answer: 'forte', options: ['forte', 'bleue', 'grise'], instruction: 'Economy' },
    { id: 'fr8-c81', type: 'Cloze', question: 'Le ___ est indispensable au bonheur.', answer: 'respect', options: ['respect', 'poisson', 'pont'], instruction: 'Ethics' },
    { id: 'fr8-c82', type: 'Cloze', question: 'Une ___ de mesures d\'urgence.', answer: 'batterie', options: ['batterie', 'route', 'vache'], instruction: 'Social' },
    { id: 'fr8-c83', type: 'Cloze', question: 'Il y a de la ___ dans l\'air.', answer: 'tension', options: ['tension', 'sucre', 'miel'], instruction: 'Weather' },
    { id: 'fr8-c84', type: 'Cloze', question: 'C\'est ___ tout à fait inouï.', answer: 'presque', options: ['presque', 'jamais', 'pas'], instruction: 'Adverb' },
    { id: 'fr8-c85', type: 'Cloze', question: 'Un ___ de citoyens motivés.', answer: 'pool', options: ['pool', 'avion', 'lit'], instruction: 'Society' },
    { id: 'fr8-c86', type: 'Cloze', question: 'Le ___ est un moteur de changement.', answer: 'jeunisme', options: ['jeunisme', 'soleil', 'chien'], instruction: 'Society' },
    { id: 'fr8-c87', type: 'Cloze', question: 'Je ___ mes habitudes de consommation.', answer: 'modifie', options: ['modifie', 'mange', 'bois'], instruction: 'Action' },
    { id: 'fr8-c88', type: 'Cloze', question: 'C\'est ___ exactement ça.', answer: 'tout', options: ['tout', 'rien', 'pas'], instruction: 'Adverb' },
    { id: 'fr8-c89', type: 'Cloze', question: 'Le ___ social doit être préservé.', answer: 'lien', options: ['lien', 'mur', 'pain'], instruction: 'Society' },
    { id: 'fr8-c90', type: 'Cloze', question: 'Une ___ de justice impartiale.', answer: 'cour', options: ['cour', 'route', 'vache'], instruction: 'Politics' },
    { id: 'fr8-c91', type: 'Cloze', question: 'Il ___ toujours ses partenaires de confiance.', answer: 'épaule', options: ['épaule', 'mange', 'boit'], instruction: 'Action' },
    { id: 'fr8-c92', type: 'Cloze', question: 'Mon ___ de travail est moderne.', answer: 'environnement', options: ['environnement', 'pain', 'vent'], instruction: 'Economy' },
    { id: 'fr8-c93', type: 'Cloze', question: 'Une ___ de nouvelles technologies.', answer: 'vague', options: ['vague', 'fruit', 'main'], instruction: 'Science' },
    { id: 'fr8-c94', type: 'Cloze', question: 'C\'est ___ facile maintenant.', answer: 'plus', options: ['plus', 'bleu', 'gros'], instruction: 'Adverb' },
    { id: 'fr8-c95', type: 'Cloze', question: 'Je ___ le plein succès au projet.', answer: 'souhaite', options: ['souhaite', 'vois', 'entends'], instruction: 'Action' },
    { id: 'fr8-c96', type: 'Cloze', question: 'La ___ est une valeur républicaine.', answer: 'fraternité', options: ['fraternité', 'route', 'main'], instruction: 'Politics' },
    { id: 'fr8-c97', type: 'Cloze', question: 'Le ___ mondial est instable.', answer: 'climat', options: ['climat', 'ciel', 'lait'], instruction: 'Society' },
    { id: 'fr8-c98', type: 'Cloze', question: 'Un ___ d\'opinions divergentes.', answer: 'panel', options: ['panel', 'soleil', 'pont'], instruction: 'Society' },
    { id: 'fr8-c99', type: 'Cloze', question: 'Il ___ une influence considérable.', answer: 'a', options: ['a', 'est', 'va'], instruction: 'Possession' },
    { id: 'fr8-c100', type: 'Cloze', question: 'Bonne ___ !', answer: 'chance', options: ['chance', 'merci', 'pain'], instruction: 'Greeting' },
  ],
  9: [
    { id: 'fr9-c52', type: 'Cloze', question: 'La pensée ___ est l\'objet de la philosophie.', answer: 'pure', options: ['pure', 'fausse', 'aucune'], instruction: 'Philosophy' },
    { id: 'fr9-c53', type: 'Cloze', question: 'Nous ___ interroger les fondements du savoir.', answer: 'savons', options: ['savons', 'allons', 'pouvons'], instruction: 'Epistemology' },
    { id: 'fr9-c54', type: 'Cloze', question: 'L\'éthique ___ sur la morale humaine.', answer: 'porte', options: ['porte', 'boit', 'court'], instruction: 'Philosophy' },
    { id: 'fr9-c55', type: 'Cloze', question: 'C\'est ___ une vérité absolue.', answer: 'presque', options: ['presque', 'jamais', 'pas'], instruction: 'Philosophy' },
    { id: 'fr9-c56', type: 'Cloze', question: 'Le ___ est un concept métaphysique profond.', answer: 'temps', options: ['temps', 'pain', 'pont'], instruction: 'Philosophy' },
    { id: 'fr9-c57', type: 'Cloze', question: 'Il faut ___ les paradigmes anciens.', answer: 'déconstruire', options: ['déconstruire', 'manger', 'perdre'], instruction: 'Philosophy' },
    { id: 'fr9-c58', type: 'Cloze', question: 'Je ___ mon opinion sur le sujet.', answer: 'ai fondé', options: ['ai fondé', 'fonde', 'fonderai'], instruction: 'Time' },
    { id: 'fr9-c59', type: 'Cloze', question: 'Les paradoxes ___ notre esprit critique.', answer: 'stimulent', options: ['stimulent', 'murmurent', 'vont'], instruction: 'Logic' },
    { id: 'fr9-c60', type: 'Cloze', question: 'Nous ___ des thèses contradictoires.', answer: 'confrontons', options: ['confrontons', 'buvons', 'lisons'], instruction: 'Philosophy' },
    { id: 'fr9-c61', type: 'Cloze', question: 'La ___ est le but de la recherche.', answer: 'vérité', options: ['vérité', 'sucre', 'miel'], instruction: 'Philosophy' },
    { id: 'fr9-c62', type: 'Cloze', question: 'Une ___ de connaissances universelles.', answer: 'encyclopédie', options: ['encyclopédie', 'route', 'vache'], instruction: 'Knowledge' },
    { id: 'fr9-c63', type: 'Cloze', question: 'Il y a ___ trop de doutes.', answer: 'parfois', options: ['parfois', 'rien', 'pas'], instruction: 'Psychology' },
    { id: 'fr9-c64', type: 'Cloze', question: 'Je ___ le sens de l\'existence.', answer: 'cherche', options: ['cherche', 'mange', 'lis'], instruction: 'Philosophy' },
    { id: 'fr9-c65', type: 'Cloze', question: 'C\'est ___ question d\'éthique.', answer: 'une', options: ['une', 'un', 'des'], instruction: 'Article' },
    { id: 'fr9-c66', type: 'Cloze', question: 'Les ___ s\'interrogent sur l\'être.', answer: 'ontologues', options: ['ontologues', 'chiens', 'lapins'], instruction: 'Philosophy' },
    { id: 'fr9-c67', type: 'Cloze', question: 'Ma ___ de la vie a changé.', answer: 'vision', options: ['vision', 'banane', 'main'], instruction: 'Philosophy' },
    { id: 'fr9-c68', type: 'Cloze', question: 'Un ___ de réflexion intense.', answer: 'moment', options: ['moment', 'soleil', 'pont'], instruction: 'Action' },
    { id: 'fr9-c69', type: 'Cloze', question: 'C\'est ___ à démontrer logiquement.', answer: 'aisé', options: ['aisé', 'bleu', 'gros'], instruction: 'Logic' },
    { id: 'fr9-c70', type: 'Cloze', question: 'Le ___ est l\'outil du langage.', answer: 'mot', options: ['mot', 'avion', 'chapeau'], instruction: 'Language' },
    { id: 'fr9-c71', type: 'Cloze', question: 'Je ___ les mystères de la nature.', answer: 'pénètre', options: ['pénètre', 'dors', 'danse'], instruction: 'Action' },
    { id: 'fr9-c72', type: 'Cloze', question: 'Le ___ de la liberté individuelle.', answer: 'concept', options: ['concept', 'avion', 'chapeau'], instruction: 'Object' },
    { id: 'fr9-c73', type: 'Cloze', question: 'Une ___ dans le système de pensée.', answer: 'brèche', options: ['brèche', 'route', 'vache'], instruction: 'Philosophy' },
    { id: 'fr9-c74', type: 'Cloze', question: 'Je ___ les arguments du texte.', answer: 'analyse', options: ['analyse', 'mange', 'casse'], instruction: 'Action' },
    { id: 'fr9-c75', type: 'Cloze', question: 'Le ___ est la fin de toute chose.', answer: 'néant', options: ['néant', 'vent', 'mer'], instruction: 'Philosophy' },
    { id: 'fr9-c76', type: 'Cloze', question: 'Nous ___ pour la clarté d\'esprit.', answer: 'luttons', options: ['luttons', 'dormons', 'buvons'], instruction: 'Action' },
    { id: 'fr9-c77', type: 'Cloze', question: 'Un ___ de sagesse antique.', answer: 'souffle', options: ['souffle', 'nuage', 'cheval'], instruction: 'Philosophy' },
    { id: 'fr9-c78', type: 'Cloze', question: 'C\'est ___ terminé pour la leçon.', answer: 'enfin', options: ['enfin', 'jamais', 'tout'], instruction: 'Adverb' },
    { id: 'fr9-c79', type: 'Cloze', question: 'La ___ est la quête du savoir.', answer: 'philosophie', options: ['philosophie', 'pizza', 'route'], instruction: 'Philosophy' },
    { id: 'fr9-c80', type: 'Cloze', question: 'Regarde cette ___ idée novatrice.', answer: 'belle', options: ['belle', 'bleue', 'grise'], instruction: 'Description' },
    { id: 'fr9-c81', type: 'Cloze', question: 'Le ___ est le moteur de l\'action.', answer: 'désir', options: ['désir', 'poisson', 'pont'], instruction: 'Psychology' },
    { id: 'fr9-c82', type: 'Cloze', question: 'Une ___ de jugements de valeur.', answer: 'série', options: ['série', 'route', 'vache'], instruction: 'Philosophy' },
    { id: 'fr9-c83', type: 'Cloze', question: 'Il y a de la ___ dans ce texte.', answer: 'beauté', options: ['beauté', 'sucre', 'miel'], instruction: 'Aesthetics' },
    { id: 'fr9-c84', type: 'Cloze', question: 'C\'est ___ tout à fait certain.', answer: 'presque', options: ['presque', 'jamais', 'pas'], instruction: 'Adverb' },
    { id: 'fr9-c85', type: 'Cloze', question: 'Un ___ de penseurs libres.', answer: 'cercle', options: ['cercle', 'avion', 'lit'], instruction: 'Society' },
    { id: 'fr9-c86', type: 'Cloze', question: 'Le ___ est au-delà du langage.', answer: 'silence', options: ['silence', 'soleil', 'chien'], instruction: 'Philosophy' },
    { id: 'fr9-c87', type: 'Cloze', question: 'Je ___ ma pensée critique.', answer: 'développe', options: ['développe', 'mange', 'bois'], instruction: 'Action' },
    { id: 'fr9-c88', type: 'Cloze', question: 'C\'est ___ exactement ce que je pense.', answer: 'tout', options: ['tout', 'rien', 'pas'], instruction: 'Adverb' },
    { id: 'fr9-c89', type: 'Cloze', question: 'Le ___ créateur est en nous.', answer: 'génie', options: ['génie', 'mur', 'pain'], instruction: 'Psychology' },
    { id: 'fr9-c90', type: 'Cloze', question: 'Une ___ de sagesse éternelle.', answer: 'source', options: ['source', 'route', 'vache'], instruction: 'Philosophy' },
    { id: 'fr9-c91', type: 'Cloze', question: 'Il ___ toujours ses principes moraux.', answer: 'suit', options: ['suit', 'mange', 'boit'], instruction: 'Action' },
    { id: 'fr9-c92', type: 'Cloze', question: 'Mon ___ est ouvert aux idées.', answer: 'esprit', options: ['esprit', 'pain', 'vent'], instruction: 'Philosophy' },
    { id: 'fr9-c93', type: 'Cloze', question: 'Une ___ de lumière dans l\'ombre.', answer: 'lueur', options: ['lueur', 'fruit', 'main'], instruction: 'Nature' },
    { id: 'fr9-c94', type: 'Cloze', question: 'C\'est ___ important d\'être soi.', answer: 'si', options: ['si', 'bleu', 'gros'], instruction: 'Philosophy' },
    { id: 'fr9-c95', type: 'Cloze', question: 'Je ___ bon vent à tous.', answer: 'souhaite', options: ['souhaite', 'vois', 'entends'], instruction: 'Action' },
    { id: 'fr9-c96', type: 'Cloze', question: 'La ___ est la fin de la route.', answer: 'paix', options: ['paix', 'route', 'main'], instruction: 'Society' },
    { id: 'fr9-c97', type: 'Cloze', question: 'Le ___ est une promesse tenue.', answer: 'mieux', options: ['mieux', 'ciel', 'lait'], instruction: 'Future' },
    { id: 'fr9-c98', type: 'Cloze', question: 'Un ___ de sons et d\'images.', answer: 'univers', options: ['univers', 'soleil', 'pont'], instruction: 'Object' },
    { id: 'fr9-c99', type: 'Cloze', question: 'Il ___ une âme de philosophe.', answer: 'a', options: ['a', 'est', 'va'], instruction: 'Possession' },
    { id: 'fr9-c100', type: 'Cloze', question: 'Bonne ___ !', answer: 'chance', options: ['chance', 'merci', 'pain'], instruction: 'Greeting' },
  ],
};
