/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const FRANSK_CLOZE_P1: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'fr0-c1', type: 'Cloze', question: 'Je ___ un chien.', answer: 'vois', options: ['vois', 'mange', 'dors'], instruction: 'Action' },
    { id: 'fr0-c2', type: 'Cloze', question: 'Le chien dit ___.', answer: 'wouf', options: ['wouf', 'miaou', 'coin'], instruction: 'Sound' },
    { id: 'fr0-c3', type: 'Cloze', question: 'Ma maman est ___.', answer: 'gentille', options: ['gentille', 'bleue', 'voiture'], instruction: 'Description' },
    { id: 'fr0-c4', type: 'Cloze', question: 'La pomme est ___.', answer: 'rouge', options: ['rouge', 'bleue', 'verte'], instruction: 'Color' },
    { id: 'fr0-c5', type: 'Cloze', question: 'Le soleil est ___.', answer: 'jaune', options: ['jaune', 'violet', 'noir'], instruction: 'Color' },
    { id: 'fr0-c6', type: 'Cloze', question: 'Le ciel est ___.', answer: 'bleu', options: ['bleu', 'rouge', 'rose'], instruction: 'Color' },
    { id: 'fr0-c7', type: 'Cloze', question: 'L\'herbe est ___.', answer: 'verte', options: ['verte', 'jaune', 'orange'], instruction: 'Color' },
    { id: 'fr0-c8', type: 'Cloze', question: 'Je ___ une glace.', answer: 'mange', options: ['mange', 'lis', 'cours'], instruction: 'Action' },
    { id: 'fr0-c9', type: 'Cloze', question: 'Le chat ___ sur le canapé.', answer: 'dort', options: ['dort', 'chante', 'danse'], instruction: 'Action' },
    { id: 'fr0-c10', type: 'Cloze', question: 'Je ___ à l\'école.', answer: 'vais', options: ['vais', 'mange', 'bois'], instruction: 'Action' },
    { id: 'fr0-c11', type: 'Cloze', question: 'Un petit ___ de lait.', answer: 'verre', options: ['verre', 'livre', 'soulier'], instruction: 'Quantity' },
    { id: 'fr0-c12', type: 'Cloze', question: 'La maison est ___.', answer: 'grande', options: ['grande', 'petite', 'bleue'], instruction: 'Description' },
    { id: 'fr0-c13', type: 'Cloze', question: 'J\'ai un ___ chat.', answer: 'petit', options: ['petit', 'grand', 'rouge'], instruction: 'Description' },
    { id: 'fr0-c14', type: 'Cloze', question: 'La ___ est belle.', answer: 'fleur', options: ['fleur', 'voiture', 'maison'], instruction: 'Noun' },
    { id: 'fr0-c15', type: 'Cloze', question: 'L\'oiseau ___ dans le ciel.', answer: 'vole', options: ['vole', 'nage', 'rampe'], instruction: 'Action' },
    { id: 'fr0-c16', type: 'Cloze', question: 'Le poisson ___ dans l\'eau.', answer: 'nage', options: ['nage', 'vole', 'marche'], instruction: 'Action' },
    { id: 'fr0-c17', type: 'Cloze', question: 'Je t\'___ beaucoup.', answer: 'aime', options: ['aime', 'hais', 'vois'], instruction: 'Feeling' },
    { id: 'fr0-c18', type: 'Cloze', question: 'Bonjour, ___ vas-tu ?', answer: 'comment', options: ['comment', 'pourquoi', 'où'], instruction: 'Question' },
    { id: 'fr0-c19', type: 'Cloze', question: 'Je ___ bien, merci.', answer: 'vais', options: ['vais', 'suis', 'ai'], instruction: 'Greeting' },
    { id: 'fr0-c20', type: 'Cloze', question: 'Un, deux, ___.', answer: 'trois', options: ['trois', 'quatre', 'cinq'], instruction: 'Number' },
    { id: 'fr0-c21', type: 'Cloze', question: 'Quatre, cinq, ___.', answer: 'six', options: ['six', 'deux', 'huit'], instruction: 'Number' },
    { id: 'fr0-c22', type: 'Cloze', question: 'Sept, huit, ___.', answer: 'neuf', options: ['neuf', 'un', 'zero'], instruction: 'Number' },
    { id: 'fr0-c23', type: 'Cloze', question: 'Dix, onze, ___.', answer: 'douze', options: ['douze', 'cinq', 'vingt'], instruction: 'Number' },
    { id: 'fr0-c24', type: 'Cloze', question: 'Le lapin a de ___ oreilles.', answer: 'longues', options: ['longues', 'courtes', 'rondes'], instruction: 'Body' },
    { id: 'fr0-c25', type: 'Cloze', question: 'L\'éléphant est ___.', answer: 'gris', options: ['gris', 'rose', 'bleu'], instruction: 'Color' },
    { id: 'fr0-c26', type: 'Cloze', question: 'Le cochon est ___.', answer: 'rose', options: ['rose', 'bleu', 'brun'], instruction: 'Color' },
    { id: 'fr0-c27', type: 'Cloze', question: 'L\'ours est ___.', answer: 'brun', options: ['brun', 'blanc', 'violet'], instruction: 'Color' },
    { id: 'fr0-c28', type: 'Cloze', question: 'L\'ours polaire est ___.', answer: 'blanc', options: ['blanc', 'noir', 'bleu'], instruction: 'Color' },
    { id: 'fr0-c29', type: 'Cloze', question: 'Le tigre a des ___.', answer: 'rayures', options: ['rayures', 'points', 'carreaux'], instruction: 'Pattern' },
    { id: 'fr0-c30', type: 'Cloze', question: 'Le léopard a des ___.', answer: 'taches', options: ['taches', 'rayures', 'carreaux'], instruction: 'Pattern' },
    { id: 'fr0-c31', type: 'Cloze', question: 'C\'est ___ gateau.', answer: 'un', options: ['un', 'une', 'des'], instruction: 'Article' },
    { id: 'fr0-c32', type: 'Cloze', question: 'C\'est ___ pomme.', answer: 'une', options: ['une', 'un', 'de'], instruction: 'Article' },
    { id: 'fr0-c33', type: 'Cloze', question: 'Ce sont ___ enfants.', answer: 'des', options: ['des', 'un', 'la'], instruction: 'Article' },
    { id: 'fr0-c34', type: 'Cloze', question: 'J\'___ un livre.', answer: 'ai', options: ['ai', 'suis', 'as'], instruction: 'Verb avoir' },
    { id: 'fr0-c35', type: 'Cloze', question: 'Tu ___ un vélo.', answer: 'as', options: ['as', 'ai', 'est'], instruction: 'Verb avoir' },
    { id: 'fr0-c36', type: 'Cloze', question: 'Il ___ un chien.', answer: 'a', options: ['a', 'est', 'as'], instruction: 'Verb avoir' },
    { id: 'fr0-c37', type: 'Cloze', question: 'Elle ___ une poupée.', answer: 'a', options: ['a', 'ai', 'as'], instruction: 'Verb avoir' },
    { id: 'fr0-c38', type: 'Cloze', question: 'Je ___ content.', answer: 'suis', options: ['suis', 'ai', 'es'], instruction: 'Verb être' },
    { id: 'fr0-c39', type: 'Cloze', question: 'Tu ___ gentil.', answer: 'es', options: ['es', 'suis', 'est'], instruction: 'Verb être' },
    { id: 'fr0-c40', type: 'Cloze', question: 'Il ___ grand.', answer: 'est', options: ['est', 'es', 'suis'], instruction: 'Verb être' },
    { id: 'fr0-c41', type: 'Cloze', question: 'Elle ___ petite.', answer: 'est', options: ['est', 'as', 'ai'], instruction: 'Verb être' },
    { id: 'fr0-c42', type: 'Cloze', question: 'Nous ___ fatigués.', answer: 'sommes', options: ['sommes', 'êtes', 'sont'], instruction: 'Verb être' },
    { id: 'fr0-c43', type: 'Cloze', question: 'Vous ___ aimables.', answer: 'êtes', options: ['êtes', 'sommes', 'sont'], instruction: 'Verb être' },
    { id: 'fr0-c44', type: 'Cloze', question: 'Ils ___ calmes.', answer: 'sont', options: ['sont', 'êtes', 'est'], instruction: 'Verb être' },
    { id: 'fr0-c45', type: 'Cloze', question: 'Elles ___ jolies.', answer: 'sont', options: ['sont', 'sommes', 'est'], instruction: 'Verb être' },
    { id: 'fr0-c46', type: 'Cloze', question: 'Le ___ est sur la table.', answer: 'crayon', options: ['crayon', 'pain', 'soleil'], instruction: 'School' },
    { id: 'fr0-c47', type: 'Cloze', question: 'Je dessine sur du ___.', answer: 'papier', options: ['papier', 'mur', 'lit'], instruction: 'School' },
    { id: 'fr0-c48', type: 'Cloze', question: 'J\'écoute la ___.', answer: 'maîtresse', options: ['maîtresse', 'balle', 'table'], instruction: 'School' },
    { id: 'fr0-c49', type: 'Cloze', question: 'Je joue dans la ___.', answer: 'cour', options: ['cour', 'classe', 'maison'], instruction: 'School' },
    { id: 'fr0-c50', type: 'Cloze', question: 'Merci ___ ton aide.', answer: 'pour', options: ['pour', 'avec', 'par'], instruction: 'Polite' },
    { id: 'fr0-c51', type: 'Cloze', question: 'Au ___ !', answer: 'revoir', options: ['revoir', 'jour', 'soir'], instruction: 'Greeting' },
  ],
  1: [
    { id: 'fr1-c1', type: 'Cloze', question: 'Le chien ___ après le chat.', answer: 'court', options: ['court', 'vole', 'nage'], instruction: 'Action' },
    { id: 'fr1-c2', type: 'Cloze', question: 'Le chat ___ à l\'arbre.', answer: 'grimpe', options: ['grimpe', 'pédale', 'nage'], instruction: 'Action' },
    { id: 'fr1-c3', type: 'Cloze', question: 'J\'ai ___ de pièces.', answer: 'beaucoup', options: ['beaucoup', 'grand', 'bleu'], instruction: 'Quantity' },
    { id: 'fr1-c4', type: 'Cloze', question: 'Il a ___ d\'argent.', answer: 'peu', options: ['peu', 'plusieurs', 'long'], instruction: 'Quantity' },
    { id: 'fr1-c5', type: 'Cloze', question: 'La voiture est très ___.', answer: 'rapide', options: ['rapide', 'lente', 'malade'], instruction: 'Speed' },
    { id: 'fr1-c6', type: 'Cloze', question: 'L\'escargot est très ___.', answer: 'lent', options: ['lent', 'rapide', 'chaud'], instruction: 'Speed' },
    { id: 'fr1-c7', type: 'Cloze', question: 'Il fait ___ aujourd\'hui.', answer: 'chaud', options: ['chaud', 'froid', 'humide'], instruction: 'Weather' },
    { id: 'fr1-c8', type: 'Cloze', question: 'Il fait ___ en hiver.', answer: 'froid', options: ['froid', 'chaud', 'sec'], instruction: 'Weather' },
    { id: 'fr1-c9', type: 'Cloze', question: 'Je vais ___ lit maintenant.', answer: 'au', options: ['au', 'sur', 'sous'], instruction: 'Preposition' },
    { id: 'fr1-c10', type: 'Cloze', question: 'Le livre est ___ la table.', answer: 'sur', options: ['sur', 'sous', 'dans'], instruction: 'Preposition' },
    { id: 'fr1-c11', type: 'Cloze', question: 'Le chien dort ___ la table.', answer: 'sous', options: ['sous', 'sur', 'dans'], instruction: 'Preposition' },
    { id: 'fr1-c12', type: 'Cloze', question: 'Nous rentrons ___ la maison.', answer: 'à', options: ['à', 'du', 'en'], instruction: 'Direction' },
    { id: 'fr1-c13', type: 'Cloze', question: 'Je ___ un vélo rouge.', answer: 'veux', options: ['veux', 'suis', 'peux'], instruction: 'Desire' },
    { id: 'fr1-c14', type: 'Cloze', question: 'Mon père ___ dans le jardin.', answer: 'travaille', options: ['travaille', 'dort', 'mange'], instruction: 'Action' },
    { id: 'fr1-c15', type: 'Cloze', question: 'Ma mère ___ la cuisine.', answer: 'fait', options: ['fait', 'lit', 'saute'], instruction: 'Action' },
    { id: 'fr1-c16', type: 'Cloze', question: 'J\'___ mon petit frère.', answer: 'aide', options: ['aide', 'frappe', 'mords'], instruction: 'Action' },
    { id: 'fr1-c17', type: 'Cloze', question: 'Le bébé ___ beaucoup.', answer: 'dort', options: ['dort', 'travaille', 'conduit'], instruction: 'Action' },
    { id: 'fr1-c18', type: 'Cloze', question: 'Nous ___ du lait chaque jour.', answer: 'buvons', options: ['buvons', 'mangeons', 'lisons'], instruction: 'Action' },
    { id: 'fr1-c19', type: 'Cloze', question: 'Peux-tu me ___ la vérité ?', answer: 'dire', options: ['dire', 'entendre', 'voir'], instruction: 'Language' },
    { id: 'fr1-c20', type: 'Cloze', question: 'J\'___ de la musique.', answer: 'écoute', options: ['écoute', 'vois', 'parle'], instruction: 'Sense' },
    { id: 'fr1-c21', type: 'Cloze', question: 'Je ___ un oiseau dans l\'arbre.', answer: 'vois', options: ['vois', 'entends', 'goûte'], instruction: 'Sense' },
    { id: 'fr1-c22', type: 'Cloze', question: 'La fleur ___ bon.', answer: 'sent', options: ['sent', 'brille', 'fait du bruit'], instruction: 'Sense' },
    { id: 'fr1-c23', type: 'Cloze', question: 'La nourriture ___ bon.', answer: 'est', options: ['est', 'entend', 'voit'], instruction: 'Sense' },
    { id: 'fr1-c24', type: 'Cloze', question: 'Mon sac est ___.', answer: 'lourd', options: ['lourd', 'léger', 'bleu'], instruction: 'Description' },
    { id: 'fr1-c25', type: 'Cloze', question: 'Une plume est ___.', answer: 'légère', options: ['légère', 'lourde', 'rouge'], instruction: 'Description' },
    { id: 'fr1-c26', type: 'Cloze', question: 'L\'eau est ___.', answer: 'mouillée', options: ['mouillée', 'sèche', 'dure'], instruction: 'Description' },
    { id: 'fr1-c27', type: 'Cloze', question: 'Le sable est ___.', answer: 'sec', options: ['sec', 'mouillé', 'mou'], instruction: 'Description' },
    { id: 'fr1-c28', type: 'Cloze', question: 'La pierre est ___.', answer: 'dure', options: ['dure', 'molle', 'chaude'], instruction: 'Description' },
    { id: 'fr1-c29', type: 'Cloze', question: 'L\'oreiller est ___.', answer: 'mou', options: ['mou', 'dur', 'froid'], instruction: 'Description' },
    { id: 'fr1-c30', type: 'Cloze', question: 'J\'ai ___ doigts.', answer: 'dix', options: ['dix', 'deux', 'cinq'], instruction: 'Number' },
    { id: 'fr1-c31', type: 'Cloze', question: 'J\'ai ___ jambes.', answer: 'deux', options: ['deux', 'quatre', 'huit'], instruction: 'Number' },
    { id: 'fr1-c32', type: 'Cloze', question: 'Une araignée a ___ pattes.', answer: 'huit', options: ['huit', 'six', 'quatre'], instruction: 'Number' },
    { id: 'fr1-c33', type: 'Cloze', question: 'Une mouche a ___ pattes.', answer: 'six', options: ['six', 'huit', 'deux'], instruction: 'Number' },
    { id: 'fr1-c34', type: 'Cloze', question: 'J\'___ eu une glace hier.', answer: 'ai', options: ['ai', 'as', 'aura'], instruction: 'Time' },
    { id: 'fr1-c35', type: 'Cloze', question: 'Je ___ une glace maintenant.', answer: 'mange', options: ['mange', 'mangeais', 'voulait'], instruction: 'Time' },
    { id: 'fr1-c36', type: 'Cloze', question: 'Je ___ une glace demain.', answer: 'mangerai', options: ['mangerai', 'ai mangé', 'mange'], instruction: 'Time' },
    { id: 'fr1-c37', type: 'Cloze', question: 'C\'est ___ jour aujourd\'hui.', answer: 'mon', options: ['mon', 'ton', 'son'], instruction: 'Possession' },
    { id: 'fr1-c38', type: 'Cloze', question: 'Est-ce ___ vélo ?', answer: 'ton', options: ['ton', 'mon', 'sa'], instruction: 'Possession' },
    { id: 'fr1-c39', type: 'Cloze', question: 'C\'est ___ maison.', answer: 'notre', options: ['notre', 'leur', 'votre'], instruction: 'Possession' },
    { id: 'fr1-c40', type: 'Cloze', question: 'Le chat joue avec ___ jouet.', answer: 'son', options: ['son', 'mon', 'votre'], instruction: 'Possession' },
    { id: 'fr1-c41', type: 'Cloze', question: 'Je peux faire du vélo très ___.', answer: 'bien', options: ['bien', 'mal', 'jamais'], instruction: 'Ability' },
    { id: 'fr1-c42', type: 'Cloze', question: 'Je ___ voler.', answer: 'ne peux pas', options: ['ne peux pas', 'peux', 'toujours'], instruction: 'Ability' },
    { id: 'fr1-c43', type: 'Cloze', question: 'Nous ___ toujours ensemble.', answer: 'jouons', options: ['jouons', 'dormons', 'mangeons'], instruction: 'Action' },
    { id: 'fr1-c44', type: 'Cloze', question: 'La porte est ___.', answer: 'fermée', options: ['fermée', 'ouverte', 'bleue'], instruction: 'State' },
    { id: 'fr1-c45', type: 'Cloze', question: 'La fenêtre est ___.', answer: 'ouverte', options: ['ouverte', 'fermée', 'rouge'], instruction: 'State' },
    { id: 'fr1-c46', type: 'Cloze', question: 'La lumière est ___.', answer: 'allumée', options: ['allumée', 'éteinte', 'jaune'], instruction: 'State' },
    { id: 'fr1-c47', type: 'Cloze', question: 'La nuit est ___.', answer: 'noire', options: ['noire', 'claire', 'chaude'], instruction: 'Description' },
    { id: 'fr1-c48', type: 'Cloze', question: 'Le jour est ___.', answer: 'clair', options: ['clair', 'noir', 'froid'], instruction: 'Description' },
    { id: 'fr1-c49', type: 'Cloze', question: 'J\'ai ___ du noir.', answer: 'peur', options: ['peur', 'joie', 'colère'], instruction: 'Feeling' },
    { id: 'fr1-c50', type: 'Cloze', question: 'Je suis ___ pour toi.', answer: 'heureux', options: ['heureux', 'triste', 'fâché'], instruction: 'Feeling' },
    { id: 'fr1-c51', type: 'Cloze', question: 'Merci ___ ton aide.', answer: 'de', options: ['de', 'avec', 'à'], instruction: 'Preposition' },
  ],
  2: [
    { id: 'fr2-c1', type: 'Cloze', question: 'La fille ___ sa mère avec la vaisselle.', answer: 'aidait', options: ['aidait', 'aide', 'aidera'], instruction: 'Past' },
    { id: 'fr2-c2', type: 'Cloze', question: 'Hier nous ___ un grand gâteau.', answer: 'avons fait', options: ['avons fait', 'faisons', 'ferons'], instruction: 'Past' },
    { id: 'fr2-c3', type: 'Cloze', question: 'Mon frère ___ très vite.', answer: 'court', options: ['court', 'courait', 'a couru'], instruction: 'Present' },
    { id: 'fr2-c4', type: 'Cloze', question: 'Nous ___ un film ce soir.', answer: 'verrons', options: ['verrons', 'avons vu', 'voyons'], instruction: 'Future' },
    { id: 'fr2-c5', type: 'Cloze', question: 'Les chevaux ___ dans le champ.', answer: 'paissent', options: ['paissent', 'paissaient', 'ont paître'], instruction: 'Present' },
    { id: 'fr2-c6', type: 'Cloze', question: 'L\'enfant ___ son ours en peluche.', answer: 'cherche', options: ['cherche', 'cherchait', 'a cherché'], instruction: 'Present' },
    { id: 'fr2-c7', type: 'Cloze', question: 'Grand-mère nous ___ une histoire.', answer: 'a raconté', options: ['a raconté', 'raconte', 'raconter'], instruction: 'Past' },
    { id: 'fr2-c8', type: 'Cloze', question: 'Le professeur ___ au tableau.', answer: 'écrit', options: ['écrit', 'a écrit', 'écrivant'], instruction: 'Present' },
    { id: 'fr2-c9', type: 'Cloze', question: 'Les élèves ___ dans la classe.', answer: 'sont assis', options: ['sont assis', 'étaient assis', 's\'asseyant'], instruction: 'Present' },
    { id: 'fr2-c10', type: 'Cloze', question: 'La cloche ___ pour la pause.', answer: 'sonne', options: ['sonne', 'a sonné', 'sonné'], instruction: 'Present' },
    { id: 'fr2-c11', type: 'Cloze', question: 'Nous ___ ensemble dans la cour.', answer: 'jouons', options: ['jouons', 'avons joué', 'jouant'], instruction: 'Present' },
    { id: 'fr2-c12', type: 'Cloze', question: 'L\'oiseau a ___ un nid.', answer: 'construit', options: ['construit', 'construit', 'construisant'], instruction: 'Past Participle' },
    { id: 'fr2-c13', type: 'Cloze', question: 'L\'eau du lac est ___ froide.', answer: 'très', options: ['très', 'peu', 'beaucoup'], instruction: 'Quantity' },
    { id: 'fr2-c14', type: 'Cloze', question: 'Il y a ___ de voitures sur la route.', answer: 'beaucoup', options: ['beaucoup', 'plusieurs', 'grand'], instruction: 'Quantity' },
    { id: 'fr2-c15', type: 'Cloze', question: 'J\'aime ___ les pommes.', answer: 'vraiment', options: ['vraiment', 'pas', 'peut-être'], instruction: 'Opinion' },
    { id: 'fr2-c16', type: 'Cloze', question: 'Il n\'___ jamais ses devoirs.', answer: 'oublie', options: ['oublie', 'souvient', 'fait'], instruction: 'Action' },
    { id: 'fr2-c17', type: 'Cloze', question: 'Pense à ___ ton déjeuner.', answer: 'manger', options: ['manger', 'boire', 'jeter'], instruction: 'Action' },
    { id: 'fr2-c18', type: 'Cloze', question: 'Puis-je ___ ton crayon ?', answer: 'emprunter', options: ['emprunter', 'acheter', 'casser'], instruction: 'Polite' },
    { id: 'fr2-c19', type: 'Cloze', question: 'Merci ___ le prêt.', answer: 'pour', options: ['pour', 'à', 'avec'], instruction: 'Polite' },
    { id: 'fr2-c20', type: 'Cloze', question: 'Je ___ d\'Angleterre.', answer: 'viens', options: ['viens', 'vais', 'habite'], instruction: 'Origin' },
    { id: 'fr2-c21', type: 'Cloze', question: 'Où ___ tu ?', answer: 'habites', options: ['habites', 'es', 'as'], instruction: 'Address' },
    { id: 'fr2-c22', type: 'Cloze', question: 'Mon anniversaire est ___ Juin.', answer: 'en', options: ['en', 'sur', 'à'], instruction: 'Time' },
    { id: 'fr2-c23', type: 'Cloze', question: 'Nous allons à une fête ___ Samedi.', answer: 'Samedi', options: ['Samedi', 'en Juin', 'à midi'], instruction: 'Time' },
    { id: 'fr2-c24', type: 'Cloze', question: 'Il fait noir ___ soir.', answer: 'le', options: ['le', 'en', 'à'], instruction: 'Time' },
    { id: 'fr2-c25', type: 'Cloze', question: 'Le soleil se lève ___ l\'est.', answer: 'à', options: ['à', 'en', 'sur'], instruction: 'Direction' },
    { id: 'fr2-c26', type: 'Cloze', question: 'La lune brille ___ nuit.', answer: 'la', options: ['la', 'en', 'sur'], instruction: 'Time' },
    { id: 'fr2-c27', type: 'Cloze', question: 'Une girafe a un ___ cou.', answer: 'long', options: ['long', 'court', 'épais'], instruction: 'Body' },
    { id: 'fr2-c28', type: 'Cloze', question: 'Un hérisson a ___ de piquants.', answer: 'beaucoup', options: ['beaucoup', 'peu', 'mous'], instruction: 'Body' },
    { id: 'fr2-c29', type: 'Cloze', question: 'Un éléphant a une ___ trompe.', answer: 'longue', options: ['longue', 'rouge', 'petite'], instruction: 'Body' },
    { id: 'fr2-c30', type: 'Cloze', question: 'Nous voyons avec ___ yeux.', answer: 'nos', options: ['nos', 'vos', 'leurs'], instruction: 'Possession' },
    { id: 'fr2-c31', type: 'Cloze', question: 'Tu écoutes avec ___ oreilles.', answer: 'tes', options: ['tes', 'mes', 'ses'], instruction: 'Possession' },
    { id: 'fr2-c32', type: 'Cloze', question: 'Il marche avec ___ chien.', answer: 'son', options: ['son', 'sa', 'mon'], instruction: 'Possession' },
    { id: 'fr2-c33', type: 'Cloze', question: 'Elle joue avec ___ poupée.', answer: 'sa', options: ['sa', 'son', 'votre'], instruction: 'Possession' },
    { id: 'fr2-c34', type: 'Cloze', question: 'Les enfants jouent dans ___ jardin.', answer: 'leur', options: ['leur', 'notre', 'mon'], instruction: 'Possession' },
    { id: 'fr2-c35', type: 'Cloze', question: 'Quelle ___ est-il ?', answer: 'heure', options: ['heure', 'a', 'peut'], instruction: 'Time' },
    { id: 'fr2-c36', type: 'Cloze', question: 'Il est ___ deux heures.', answer: 'presque', options: ['presque', 'jamais', 'toujours'], instruction: 'Time' },
    { id: 'fr2-c37', type: 'Cloze', question: 'Je peux ___ l\'horloge.', answer: 'voir', options: ['voir', 'entendre', 'goûter'], instruction: 'Action' },
    { id: 'fr2-c38', type: 'Cloze', question: 'Il est ___ à la course.', answer: 'bon', options: ['bon', 'mauvais', 'bleu'], instruction: 'Ability' },
    { id: 'fr2-c39', type: 'Cloze', question: 'Elle est ___ en dessin.', answer: 'douée', options: ['douée', 'fâchée', 'fatiguée'], instruction: 'Ability' },
    { id: 'fr2-c40', type: 'Cloze', question: 'Les maths sont ___ à faire.', answer: 'difficiles', options: ['difficiles', 'faciles', 'rouges'], instruction: 'School' },
    { id: 'fr2-c41', type: 'Cloze', question: 'Je sais ___ bien.', answer: 'lire', options: ['lire', 'pas', 'jamais'], instruction: 'Ability' },
    { id: 'fr2-c42', type: 'Cloze', question: 'Veux-tu ___ avec moi ?', answer: 'jouer', options: ['jouer', 'battre', 'mordre'], instruction: 'Social' },
    { id: 'fr2-c43', type: 'Cloze', question: 'Nous sommes de ___ amis.', answer: 'bons', options: ['bons', 'mauvais', 'fâchés'], instruction: 'Social' },
    { id: 'fr2-c44', type: 'Cloze', question: 'Je voudrais ___ une glace.', answer: 'vraiment', options: ['vraiment', 'pas', 'jamais'], instruction: 'Desire' },
    { id: 'fr2-c45', type: 'Cloze', question: 'Puis-je avoir une pomme s\'il vous ___ ?', answer: 'plaît', options: ['plaît', 'pas', 'peut-être'], instruction: 'Polite' },
    { id: 'fr2-c46', type: 'Cloze', question: 'Le ___ voici.', answer: 'voici', options: ['voici', 'était', 'est'], instruction: 'Polite' },
    { id: 'fr2-c47', type: 'Cloze', question: 'Merci ___ la nourriture.', answer: 'pour', options: ['pour', 'à', 'avec'], instruction: 'Polite' },
    { id: 'fr2-c48', type: 'Cloze', question: 'De ___.', answer: 'rien', options: ['rien', 'beaucoup', 'grand'], instruction: 'Polite' },
    { id: 'fr2-c49', type: 'Cloze', question: 'Passe une ___ journée.', answer: 'bonne', options: ['bonne', 'mauvaise', 'bleue'], instruction: 'Greeting' },
    { id: 'fr2-c50', type: 'Cloze', question: 'Je suis ___ de te rencontrer.', answer: 'heureux', options: ['heureux', 'triste', 'fâché'], instruction: 'Greeting' },
    { id: 'fr2-c51', type: 'Cloze', question: 'À ___ !', answer: 'bientôt', options: ['bientôt', 'jamais', 'hier'], instruction: 'Greeting' },
  ],
  3: [
    { id: 'fr3-c1', type: 'Cloze', question: 'La maison est ___ de briques rouges.', answer: 'construite', options: ['construite', 'mangée', 'courue'], instruction: 'State' },
    { id: 'fr3-c2', type: 'Cloze', question: 'La voiture ___ vite sur la route.', answer: 'conduisait', options: ['conduisait', 'volait', 'nageait'], instruction: 'Past' },
    { id: 'fr3-c3', type: 'Cloze', question: 'Nous ___ un livre passionnant à l\'école.', answer: 'lisons', options: ['lisons', 'mangeons', 'buvons'], instruction: 'Present' },
    { id: 'fr3-c4', type: 'Cloze', question: 'Hier il ___ toute la journée.', answer: 'a plu', options: ['a plu', 'a brillé', 'a soufflé'], instruction: 'Weather' },
    { id: 'fr3-c5', type: 'Cloze', question: 'Ma maman ___ un gâteau délicieux.', answer: 'a cuit', options: ['a cuit', 'a acheté', 'a trouvé'], instruction: 'Past' },
    { id: 'fr3-c6', type: 'Cloze', question: 'Le chien ___ après la balle.', answer: 'a couru', options: ['a couru', 'a dormi', 'a mangé'], instruction: 'Past' },
    { id: 'fr3-c7', type: 'Cloze', question: 'Le soleil ___ d\'un ciel sans nuages.', answer: 'brille', options: ['brille', 'pleut', 'souffle'], instruction: 'Weather' },
    { id: 'fr3-c8', type: 'Cloze', question: 'Nous ___ toujours nos devoirs.', answer: 'faisons', options: ['faisons', 'oublions', 'perdons'], instruction: 'Action' },
    { id: 'fr3-c9', type: 'Cloze', question: 'À la pause nous ___ au football.', answer: 'jouons', options: ['jouons', 'lisons', 'dormons'], instruction: 'Action' },
    { id: 'fr3-c10', type: 'Cloze', question: 'Mon père ___ dans une grande entreprise.', answer: 'travaille', options: ['travaille', 'habite', 'mange'], instruction: 'Action' },
    { id: 'fr3-c11', type: 'Cloze', question: 'Ils ___ à l\'étranger pendant les vacances d\'été.', answer: 'ont voyagé', options: ['ont voyagé', 'sont restés', 'ont dormi'], instruction: 'Past' },
    { id: 'fr3-c12', type: 'Cloze', question: 'J\'___ Noël avec impatience.', answer: 'attends', options: ['attends', 'redoute', 'déteste'], instruction: 'Feeling' },
    { id: 'fr3-c13', type: 'Cloze', question: 'L\'enfant ___ parce qu\'il s\'est fait mal.', answer: 'pleure', options: ['pleure', 'rit', 'dort'], instruction: 'Action' },
    { id: 'fr3-c14', type: 'Cloze', question: 'Nous ___ une chanson pour l\'anniversaire.', answer: 'avons chanté', options: ['avons chanté', 'avons mangé', 'avons lu'], instruction: 'Past' },
    { id: 'fr3-c15', type: 'Cloze', question: 'Pense à ___ la porte derrière toi.', answer: 'fermer', options: ['fermer', 'ouvrir', 'verrouiller'], instruction: 'Action' },
    { id: 'fr3-c16', type: 'Cloze', question: 'La lumière doit être ___ quand tu pars.', answer: 'éteinte', options: ['éteinte', 'allumée', 'déplacée'], instruction: 'Action' },
    { id: 'fr3-c17', type: 'Cloze', question: 'L\'eau dans la bouilloire ___.', answer: 'bout', options: ['bout', 'gèle', 'goûte'], instruction: 'State' },
    { id: 'fr3-c18', type: 'Cloze', question: 'La glace ___ au soleil.', answer: 'fond', options: ['fond', 'gèle', 'grandit'], instruction: 'State' },
    { id: 'fr3-c19', type: 'Cloze', question: 'Les fleurs ___ magnifiquement dans le jardin.', answer: 'fleurissent', options: ['fleurissent', 'flétrissent', 'dorment'], instruction: 'State' },
    { id: 'fr3-c20', type: 'Cloze', question: 'Les feuilles tombent des arbres en ___.', answer: 'automne', options: ['automne', 'printemps', 'été'], instruction: 'Season' },
    { id: 'fr3-c21', type: 'Cloze', question: 'Tout reverdit au ___.', answer: 'printemps', options: ['printemps', 'hiver', 'automne'], instruction: 'Season' },
    { id: 'fr3-c22', type: 'Cloze', question: 'Nous nageons dans la mer en ___.', answer: 'été', options: ['été', 'hiver', 'automne'], instruction: 'Season' },
    { id: 'fr3-c23', type: 'Cloze', question: 'Il y a de la neige en ___.', answer: 'hiver', options: ['hiver', 'été', 'printemps'], instruction: 'Season' },
    { id: 'fr3-c24', type: 'Cloze', question: 'Une semaine a ___ jours.', answer: 'sept', options: ['sept', 'cinq', 'dix'], instruction: 'Number' },
    { id: 'fr3-c25', type: 'Cloze', question: 'Une année a douze ___.', answer: 'mois', options: ['mois', 'semaines', 'jours'], instruction: 'Time' },
    { id: 'fr3-c26', type: 'Cloze', question: 'Une heure a soixante ___.', answer: 'minutes', options: ['minutes', 'secondes', 'heures'], instruction: 'Time' },
    { id: 'fr3-c27', type: 'Cloze', question: 'Une minute a soixante ___.', answer: 'secondes', options: ['secondes', 'minutes', 'heures'], instruction: 'Time' },
    { id: 'fr3-c28', type: 'Cloze', question: 'Aujourd\'hui c\'est ___, hier c\'était Vendredi.', answer: 'Samedi', options: ['Samedi', 'Dimanche', 'Lundi'], instruction: 'Weekday' },
    { id: 'fr3-c29', type: 'Cloze', question: 'Demain c\'est ___, aujourd\'hui c\'est Mercredi.', answer: 'Jeudi', options: ['Jeudi', 'Mardi', 'Vendredi'], instruction: 'Weekday' },
    { id: 'fr3-c30', type: 'Cloze', question: 'Janvier est le ___ mois de l\'année.', answer: 'premier', options: ['premier', 'dernier', 'deuxième'], instruction: 'Ordinal' },
    { id: 'fr3-c31', type: 'Cloze', question: 'Décembre est le ___ mois de l\'année.', answer: 'dernier', options: ['dernier', 'premier', 'milieu'], instruction: 'Ordinal' },
    { id: 'fr3-c32', type: 'Cloze', question: 'Nous déjeunons au milieu de la ___.', answer: 'journée', options: ['journée', 'nuit', 'matinée'], instruction: 'Time' },
    { id: 'fr3-c33', type: 'Cloze', question: 'Les étoiles brillent la ___.', answer: 'nuit', options: ['nuit', 'jour', 'soir'], instruction: 'Time' },
    { id: 'fr3-c34', type: 'Cloze', question: 'Le soleil se lève le ___.', answer: 'matin', options: ['matin', 'soir', 'nuit'], instruction: 'Time' },
    { id: 'fr3-c35', type: 'Cloze', question: 'Le soleil se couche le ___.', answer: 'soir', options: ['soir', 'matin', 'midi'], instruction: 'Time' },
    { id: 'fr3-c36', type: 'Cloze', question: 'Le lait est dans le ___.', answer: 'frigo', options: ['frigo', 'four', 'lit'], instruction: 'Home' },
    { id: 'fr3-c37', type: 'Cloze', question: 'La nourriture est préparée sur la ___.', answer: 'cuisinière', options: ['cuisinière', 'table', 'sol'], instruction: 'Home' },
    { id: 'fr3-c38', type: 'Cloze', question: 'Nous dormons dans un ___.', answer: 'lit', options: ['lit', 'chaise', 'voiture'], instruction: 'Home' },
    { id: 'fr3-c39', type: 'Cloze', question: 'Nous nous brossons les dents dans la de bains.', answer: 'salle', options: ['salle', 'cuisine', 'salon'], instruction: 'Home' },
    { id: 'fr3-c40', type: 'Cloze', question: 'Nous regardons la télé dans le ___.', answer: 'salon', options: ['salon', 'jardin', 'remise'], instruction: 'Home' },
    { id: 'fr3-c41', type: 'Cloze', question: 'La voiture est dans le ___.', answer: 'garage', options: ['garage', 'salon', 'cuisine'], instruction: 'Home' },
    { id: 'fr3-c42', type: 'Cloze', question: 'Les vêtements sont dans l\'___.', answer: 'armoire', options: ['armoire', 'panier', 'évier'], instruction: 'Home' },
    { id: 'fr3-c43', type: 'Cloze', question: 'Nous lavons les vêtements dans la à laver.', answer: 'machine', options: ['machine', 'lave-vaisselle', 'four'], instruction: 'Home' },
    { id: 'fr3-c44', type: 'Cloze', question: 'Les assiettes sont lavées dans le ___.', answer: 'lave-vaisselle', options: ['lave-vaisselle', 'machine à laver', 'sèche-linge'], instruction: 'Home' },
    { id: 'fr3-c45', type: 'Cloze', question: 'L\'aspirateur enlève la ___ à la maison.', answer: 'poussière', options: ['poussière', 'eau', 'nourriture'], instruction: 'Home' },
    { id: 'fr3-c46', type: 'Cloze', question: 'Nous cuisons le pain dans le ___ à la maison.', answer: 'four', options: ['four', 'frigo', 'évier'], instruction: 'Home' },
    { id: 'fr3-c47', type: 'Cloze', question: 'Les légumes poussent dans le ___ à la maison.', answer: 'jardin', options: ['jardin', 'salon', 'grenier'], instruction: 'Home' },
    { id: 'fr3-c48', type: 'Cloze', question: 'Le courrier arrive dans la aux lettres.', answer: 'boîte', options: ['boîte', 'poubelle', 'évier'], instruction: 'Home' },
    { id: 'fr3-c49', type: 'Cloze', question: 'Les déchets sont jetés dans la ___ à la maison.', answer: 'poubelle', options: ['poubelle', 'boîte aux lettres', 'armoire'], instruction: 'Home' },
    { id: 'fr3-c50', type: 'Cloze', question: 'La porte est ouverte avec une ___.', answer: 'clé', options: ['clé', 'cuillère', 'livre'], instruction: 'Home' },
    { id: 'fr3-c51', type: 'Cloze', question: 'Nous sonnons à la ___ à la maison.', answer: 'porte', options: ['porte', 'fenêtre', 'toit'], instruction: 'Home' },
  ],
  4: [
    { id: 'fr4-c1', type: 'Cloze', question: 'Quelle ___ est ta préférée ?', answer: 'couleur', options: ['couleur', 'voiture', 'nourriture'], instruction: 'Question' },
    { id: 'fr4-c2', type: 'Cloze', question: 'Où ___ tu hier ?', answer: 'étais', options: ['étais', 'es', 'être'], instruction: 'Time' },
    { id: 'fr4-c3', type: 'Cloze', question: 'À qui as-tu ___ au téléphone ?', answer: 'parlé', options: ['parlé', 'mangé avec', 'dormi avec'], instruction: 'Action' },
    { id: 'fr4-c4', type: 'Cloze', question: 'Quand ___ tu l\'école ?', answer: 'commences', options: ['commences', 'dors', 'manges'], instruction: 'School' },
    { id: 'fr4-c5', type: 'Cloze', question: 'Qu\'as-tu ___ pour le dîner ?', answer: 'mangé', options: ['mangé', 'est', 'va'], instruction: 'Action' },
    { id: 'fr4-c6', type: 'Cloze', question: 'Pourquoi ___ tu ?', answer: 'ris', options: ['ris', 'dors', 'conduis'], instruction: 'Feeling' },
    { id: 'fr4-c7', type: 'Cloze', question: 'Comment ___ tu cette tâche ?', answer: 'résous', options: ['résous', 'manges', 'bois'], instruction: 'School' },
    { id: 'fr4-c8', type: 'Cloze', question: 'J\'___ jouer aux jeux vidéo.', answer: 'adore', options: ['adore', 'déteste', 'vis'], instruction: 'Desire' },
    { id: 'fr4-c9', type: 'Cloze', question: 'Mon chien ___ très fort.', answer: 'aboie', options: ['aboie', 'miaule', 'pépie'], instruction: 'Sound' },
    { id: 'fr4-c10', type: 'Cloze', question: 'Le chat ___ quand il est content.', answer: 'ronronne', options: ['ronronne', 'aboie', 'siffle'], instruction: 'Sound' },
    { id: 'fr4-c11', type: 'Cloze', question: 'Le cheval ___ à travers le champ.', answer: 'galope', options: ['galope', 'nage', 'vole'], instruction: 'Action' },
    { id: 'fr4-c12', type: 'Cloze', question: 'L\'oiseau a ___ des œufs dans le nid.', answer: 'pondu', options: ['pondu', 'mangé', 'perdu'], instruction: 'Nature' },
    { id: 'fr4-c13', type: 'Cloze', question: 'La vache ___ son herbe.', answer: 'mâche', options: ['mâche', 'lit', 'saute'], instruction: 'Nature' },
    { id: 'fr4-c14', type: 'Cloze', question: 'Le mouton a une laine très ___.', answer: 'douce', options: ['douce', 'dure', 'bleue'], instruction: 'Nature' },
    { id: 'fr4-c15', type: 'Cloze', question: 'Le cochon se ___ dans la boue.', answer: 'roule', options: ['roule', 'lave', 'vole'], instruction: 'Nature' },
    { id: 'fr4-c16', type: 'Cloze', question: 'Le fermier ___ le grain dans le champ.', answer: 'récolte', options: ['récolte', 'sème', 'mange'], instruction: 'Profession' },
    { id: 'fr4-c17', type: 'Cloze', question: 'Le jardinier ___ les fleurs.', answer: 'arrose', options: ['arrose', 'mange', 'coupe'], instruction: 'Profession' },
    { id: 'fr4-c18', type: 'Cloze', question: 'Le boulanger cuit du ___ chaque matin.', answer: 'pain', options: ['pain', 'pierres', 'chaussures'], instruction: 'Profession' },
    { id: 'fr4-c19', type: 'Cloze', question: 'La police ___ les criminels.', answer: 'arrête', options: ['arrête', 'aide', 'nourrit'], instruction: 'Profession' },
    { id: 'fr4-c20', type: 'Cloze', question: 'Le docteur ___ les gens malades.', answer: 'examine', options: ['examine', 'mange', 'frappe'], instruction: 'Profession' },
    { id: 'fr4-c21', type: 'Cloze', question: 'Le pompier ___ le feu.', answer: 'éteint', options: ['éteint', 'allume', 'regarde'], instruction: 'Profession' },
    { id: 'fr4-c22', type: 'Cloze', question: 'Le coiffeur ___ mes cheveux.', answer: 'coupe', options: ['coupe', 'lave', 'teint'], instruction: 'Profession' },
    { id: 'fr4-c23', type: 'Cloze', question: 'Le charpentier ___ une nouvelle maison.', answer: 'construit', options: ['construit', 'mange', 'dessine'], instruction: 'Profession' },
    { id: 'fr4-c24', type: 'Cloze', question: 'Le maçon utilise des ___ pour le mur.', answer: 'pierres', options: ['pierres', 'bois', 'verre'], instruction: 'Profession' },
    { id: 'fr4-c25', type: 'Cloze', question: 'Le peintre peint de la ___ sur le mur.', answer: 'peinture', options: ['peinture', 'eau', 'nourriture'], instruction: 'Profession' },
    { id: 'fr4-c26', type: 'Cloze', question: 'Le chef fait de la cuisine ___.', answer: 'délicieuse', options: ['délicieuse', 'mauvaise', 'bleue'], instruction: 'Profession' },
    { id: 'fr4-c27', type: 'Cloze', question: 'Le serveur ___ le repas à table.', answer: 'sert', options: ['sert', 'mange', 'jette'], instruction: 'Profession' },
    { id: 'fr4-c28', type: 'Cloze', question: 'Le chauffeur ___ le bus.', answer: 'conduit', options: ['conduit', 'vole', 'nage'], instruction: 'Profession' },
    { id: 'fr4-c29', type: 'Cloze', question: 'Le pilote conduit un ___.', answer: 'avion', options: ['avion', 'navire', 'train'], instruction: 'Profession' },
    { id: 'fr4-c30', type: 'Cloze', question: 'Le marin navigue sur un ___.', answer: 'navire', options: ['navire', 'avion', 'voiture'], instruction: 'Profession' },
    { id: 'fr4-c31', type: 'Cloze', question: 'Le professeur nous ___ de nouvelles choses.', answer: 'enseigne', options: ['enseigne', 'oublie', 'frappe'], instruction: 'Profession' },
    { id: 'fr4-c32', type: 'Cloze', question: 'Les élèves ___ des devoirs chaque jour.', answer: 'font', options: ['font', 'lisent', 'mangent'], instruction: 'School' },
    { id: 'fr4-c33', type: 'Cloze', question: 'Nous écrivons dans nos ___.', answer: 'cahiers', options: ['cahiers', 'livres', 'bouches'], instruction: 'School' },
    { id: 'fr4-c34', type: 'Cloze', question: 'Nous lisons des ___ passionnants à l\'école.', answer: 'livres', options: ['livres', 'cahiers', 'magazines'], instruction: 'School' },
    { id: 'fr4-c35', type: 'Cloze', question: 'La bibliothèque a beaucoup de ___ à l\'école.', answer: 'livres', options: ['livres', 'boîtes à lunch', 'chaussures'], instruction: 'School' },
    { id: 'fr4-c36', type: 'Cloze', question: 'Nous ___ des maths à l\'école.', answer: 'faisons', options: ['faisons', 'chantons', 'dansons'], instruction: 'School' },
    { id: 'fr4-c37', type: 'Cloze', question: 'Nous ___ le Français à l\'école.', answer: 'apprenons', options: ['apprenons', 'oublions', 'perdons'], instruction: 'School' },
    { id: 'fr4-c38', type: 'Cloze', question: 'Nous ___ Français à l\'école.', answer: 'parlons', options: ['parlons', 'mangeons', 'courons'], instruction: 'School' },
    { id: 'fr4-c39', type: 'Cloze', question: 'Le sport est ___ dans la salle de sport.', answer: 'amusant', options: ['amusant', 'ennuyeux', 'triste'], instruction: 'School' },
    { id: 'fr4-c40', type: 'Cloze', question: 'La musique est bonne pour ___.', answer: 'danser', options: ['danser', 'dormir', 'lire'], instruction: 'School' },
    { id: 'fr4-c41', type: 'Cloze', question: 'Nous dessinons en cours de ___ plastique.', answer: 'arts', options: ['arts', 'maths', 'sport'], instruction: 'School' },
    { id: 'fr4-c42', type: 'Cloze', question: 'La science traite de la ___ à l\'école.', answer: 'nature', options: ['nature', 'histoire', 'musique'], instruction: 'School' },
    { id: 'fr4-c43', type: 'Cloze', question: 'L\'histoire traite du ___ à l\'école.', answer: 'passé', options: ['passé', 'futur', 'présent'], instruction: 'School' },
    { id: 'fr4-c44', type: 'Cloze', question: 'La géographie traite du ___ à l\'école.', answer: 'monde', options: ['monde', 'nombres', 'mots'], instruction: 'School' },
    { id: 'fr4-c45', type: 'Cloze', question: 'La religion traite de la ___ à l\'école.', answer: 'foi', options: ['foi', 'science', 'nourriture'], instruction: 'School' },
    { id: 'fr4-c46', type: 'Cloze', question: 'Les pauses sont bonnes pour ___ à l\'école.', answer: 'jouer', options: ['jouer', 'dormir', 'travailler'], instruction: 'School' },
    { id: 'fr4-c47', type: 'Cloze', question: 'Le périscolaire est après l\'___.', answer: 'école', options: ['école', 'nuit', 'vacances'], instruction: 'School' },
    { id: 'fr4-c48', type: 'Cloze', question: 'Les vacances sont ___ à l\'école.', answer: 'longues', options: ['longues', 'courtes', 'bleues'], instruction: 'School' },
    { id: 'fr4-c49', type: 'Cloze', question: 'L\'école commence à ___ heures.', answer: 'huit', options: ['huit', 'dix', 'douze'], instruction: 'School' },
    { id: 'fr4-c50', type: 'Cloze', question: 'Nous attendons le ___ à l\'école.', answer: 'week-end', options: ['week-end', 'devoirs', 'Lundi'], instruction: 'School' },
    { id: 'fr4-c51', type: 'Cloze', question: 'Pense à ___ ton livre.', answer: 'lire', options: ['lire', 'manger', 'jeter'], instruction: 'School' },
  ],
};
