/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const SPANSK_CLOZE_P1: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'sp0-c1', type: 'Cloze', question: 'Yo ___ un perro.', answer: 'veo', options: ['veo', 'como', 'duermo'], instruction: 'Acción' },
    { id: 'sp0-c2', type: 'Cloze', question: 'El perro dice ___.', answer: 'guau', options: ['guau', 'miau', 'cuac'], instruction: 'Sonido' },
    { id: 'sp0-c3', type: 'Cloze', question: 'Mi mamá es ___.', answer: 'buena', options: ['buena', 'azul', 'coche'], instruction: 'Descripción' },
    { id: 'sp0-c4', type: 'Cloze', question: 'La manzana es ___.', answer: 'roja', options: ['roja', 'azul', 'verde'], instruction: 'Color' },
    { id: 'sp0-c5', type: 'Cloze', question: 'El sol es ___.', answer: 'amarillo', options: ['amarillo', 'morado', 'negro'], instruction: 'Color' },
    { id: 'sp0-c6', type: 'Cloze', question: 'El cielo es ___.', answer: 'azul', options: ['azul', 'rojo', 'rosa'], instruction: 'Color' },
    { id: 'sp0-c7', type: 'Cloze', question: 'La hierba es ___.', answer: 'verde', options: ['verde', 'amarillo', 'naranja'], instruction: 'Color' },
    { id: 'sp0-c8', type: 'Cloze', question: 'Yo ___ un helado.', answer: 'como', options: ['como', 'leo', 'corro'], instruction: 'Acción' },
    { id: 'sp0-c9', type: 'Cloze', question: 'El gato ___ en el sofá.', answer: 'duerme', options: ['duerme', 'canta', 'baila'], instruction: 'Acción' },
    { id: 'sp0-c10', type: 'Cloze', question: 'Yo ___ a la escuela.', answer: 'voy', options: ['voy', 'como', 'bebo'], instruction: 'Acción' },
    { id: 'sp0-c11', type: 'Cloze', question: 'Un pequeño ___ de leche.', answer: 'vaso', options: ['vaso', 'libro', 'zapato'], instruction: 'Cantidad' },
    { id: 'sp0-c12', type: 'Cloze', question: 'La casa es ___.', answer: 'grande', options: ['grande', 'pequeña', 'azul'], instruction: 'Descripción' },
    { id: 'sp0-c13', type: 'Cloze', question: 'Tengo un gato ___.', answer: 'pequeño', options: ['pequeño', 'grande', 'rojo'], instruction: 'Descripción' },
    { id: 'sp0-c14', type: 'Cloze', question: 'La ___ es bonita.', answer: 'flor', options: ['flor', 'coche', 'casa'], instruction: 'Sustantivo' },
    { id: 'sp0-c15', type: 'Cloze', question: 'El pájaro ___ en el cielo.', answer: 'vuela', options: ['vuela', 'nada', 'gatea'], instruction: 'Acción' },
    { id: 'sp0-c16', type: 'Cloze', question: 'El pez ___ en el agua.', answer: 'nada', options: ['nada', 'vuela', 'camina'], instruction: 'Acción' },
    { id: 'sp0-c17', type: 'Cloze', question: 'Te ___ mucho.', answer: 'quiero', options: ['quiero', 'odio', 'veo'], instruction: 'Sentimiento' },
    { id: 'sp0-c18', type: 'Cloze', question: 'Hola, ¿___ estás?', answer: 'cómo', options: ['cómo', 'por qué', 'dónde'], instruction: 'Pregunta' },
    { id: 'sp0-c19', type: 'Cloze', question: 'Yo ___ bien, gracias.', answer: 'estoy', options: ['estoy', 'soy', 'tengo'], instruction: 'Saludo' },
    { id: 'sp0-c20', type: 'Cloze', question: 'Uno, dos, ___.', answer: 'tres', options: ['tres', 'cuatro', 'cinco'], instruction: 'Número' },
    { id: 'sp0-c21', type: 'Cloze', question: 'Cuatro, cinco, ___.', answer: 'seis', options: ['seis', 'dos', 'ocho'], instruction: 'Número' },
    { id: 'sp0-c22', type: 'Cloze', question: 'Siete, ocho, ___.', answer: 'nueve', options: ['nueve', 'uno', 'cero'], instruction: 'Número' },
    { id: 'sp0-c23', type: 'Cloze', question: 'Diez, once, ___.', answer: 'doce', options: ['doce', 'cinco', 'veinte'], instruction: 'Número' },
    { id: 'sp0-c24', type: 'Cloze', question: 'El conejo tiene orejas ___.', answer: 'largas', options: ['largas', 'cortas', 'redondas'], instruction: 'Cuerpo' },
    { id: 'sp0-c25', type: 'Cloze', question: 'El elefante es ___.', answer: 'gris', options: ['gris', 'rosa', 'azul'], instruction: 'Color' },
  ],
  1: [
    { id: 'sp1-c1', type: 'Cloze', question: 'El perro ___ tras el gato.', answer: 'corre', options: ['corre', 'vuela', 'nada'], instruction: 'Acción' },
    { id: 'sp1-c2', type: 'Cloze', question: 'El gato ___ al árbol.', answer: 'trepa', options: ['trepa', 'pedalea', 'nada'], instruction: 'Acción' },
    { id: 'sp1-c3', type: 'Cloze', question: 'Tengo ___ monedas.', answer: 'muchas', options: ['muchas', 'grande', 'azul'], instruction: 'Cantidad' },
    { id: 'sp1-c4', type: 'Cloze', question: 'Él tiene ___ dinero.', answer: 'poco', options: ['poco', 'varios', 'largo'], instruction: 'Cantidad' },
    { id: 'sp1-c5', type: 'Cloze', question: 'El coche es muy ___.', answer: 'rápido', options: ['rápido', 'lento', 'enfermo'], instruction: 'Velocidad' },
    { id: 'sp1-c6', type: 'Cloze', question: 'El caracol es muy ___.', answer: 'lento', options: ['lento', 'rápido', 'caliente'], instruction: 'Velocidad' },
    { id: 'sp1-c7', type: 'Cloze', question: 'Hace ___ hoy.', answer: 'calor', options: ['calor', 'frío', 'húmedo'], instruction: 'Clima' },
    { id: 'sp1-c8', type: 'Cloze', question: 'Hace ___ en invierno.', answer: 'frío', options: ['frío', 'calor', 'seco'], instruction: 'Clima' },
    { id: 'sp1-c9', type: 'Cloze', question: 'Voy ___ cama ahora.', answer: 'a la', options: ['a la', 'sobre', 'bajo'], instruction: 'Preposición' },
    { id: 'sp1-c10', type: 'Cloze', question: 'El libro está ___ la mesa.', answer: 'sobre', options: ['sobre', 'bajo', 'en'], instruction: 'Preposición' },
    { id: 'sp1-c11', type: 'Cloze', question: 'El perro duerme ___ la mesa.', answer: 'bajo', options: ['bajo', 'sobre', 'en'], instruction: 'Preposición' },
    { id: 'sp1-c12', type: 'Cloze', question: 'Nosotros volvemos ___ casa.', answer: 'a', options: ['a', 'del', 'en'], instruction: 'Dirección' },
    { id: 'sp1-c13', type: 'Cloze', question: 'Yo ___ una bicicleta roja.', answer: 'quiero', options: ['quiero', 'soy', 'puedo'], instruction: 'Deseo' },
    { id: 'sp1-c14', type: 'Cloze', question: 'Mi padre ___ en el jardín.', answer: 'trabaja', options: ['trabaja', 'duerme', 'come'], instruction: 'Acción' },
    { id: 'sp1-c15', type: 'Cloze', question: 'Mi madre ___ la comida.', answer: 'hace', options: ['hace', 'lee', 'salta'], instruction: 'Acción' },
    { id: 'sp1-c16', type: 'Cloze', question: 'Yo ___ a mi hermano pequeño.', answer: 'ayudo', options: ['ayudo', 'pego', 'muerdo'], instruction: 'Acción' },
    { id: 'sp1-c17', type: 'Cloze', question: 'El bebé ___ mucho.', answer: 'duerme', options: ['duerme', 'trabaja', 'conduce'], instruction: 'Acción' },
    { id: 'sp1-c18', type: 'Cloze', question: 'Nosotros ___ leche cada día.', answer: 'bebemos', options: ['bebemos', 'comemos', 'leemos'], instruction: 'Acción' },
    { id: 'sp1-c19', type: 'Cloze', question: '¿Puedes ___ la verdad?', answer: 'decir', options: ['decir', 'oír', 'ver'], instruction: 'Lenguaje' },
    { id: 'sp1-c20', type: 'Cloze', question: 'Yo ___ música.', answer: 'escucho', options: ['escucho', 'veo', 'hablo'], instruction: 'Sentido' },
    { id: 'sp1-c21', type: 'Cloze', question: 'Yo ___ un pájaro en el árbol.', answer: 'veo', options: ['veo', 'oigo', 'pruebo'], instruction: 'Sentido' },
    { id: 'sp1-c22', type: 'Cloze', question: 'La flor ___ bien.', answer: 'huele', options: ['huele', 'brilla', 'hace ruido'], instruction: 'Sentido' },
    { id: 'sp1-c23', type: 'Cloze', question: 'La comida ___ buena.', answer: 'está', options: ['está', 'oye', 've'], instruction: 'Sentido' },
    { id: 'sp1-c24', type: 'Cloze', question: 'Mi mochila es ___.', answer: 'pesada', options: ['pesada', 'ligera', 'azul'], instruction: 'Descripción' },
    { id: 'sp1-c25', type: 'Cloze', question: 'Una pluma es ___.', answer: 'ligera', options: ['ligera', 'pesada', 'roja'], instruction: 'Descripción' },
  ],
  2: [
    { id: 'sp2-c1', type: 'Cloze', question: 'La niña ___ a su madre con los platos.', answer: 'ayudaba', options: ['ayudaba', 'ayuda', 'ayudará'], instruction: 'Pasado' },
    { id: 'sp2-c2', type: 'Cloze', question: 'Ayer nosotros ___ un gran pastel.', answer: 'hicimos', options: ['hicimos', 'hacemos', 'haremos'], instruction: 'Pasado' },
    { id: 'sp2-c3', type: 'Cloze', question: 'Mi hermano ___ muy rápido.', answer: 'corre', options: ['corre', 'corría', 'ha corrido'], instruction: 'Presente' },
    { id: 'sp2-c4', type: 'Cloze', question: 'Nosotros ___ una película esta noche.', answer: 'veremos', options: ['veremos', 'hemos visto', 'vemos'], instruction: 'Futuro' },
    { id: 'sp2-c5', type: 'Cloze', question: 'Los caballos ___ en el campo.', answer: 'pastan', options: ['pastan', 'pastaban', 'han pastado'], instruction: 'Presente' },
    { id: 'sp2-c6', type: 'Cloze', question: 'El niño ___ su oso de peluche.', answer: 'busca', options: ['busca', 'buscaba', 'ha buscado'], instruction: 'Presente' },
    { id: 'sp2-c7', type: 'Cloze', question: 'La abuela nos ___ una historia.', answer: 'contó', options: ['contó', 'cuenta', 'contar'], instruction: 'Pasado' },
    { id: 'sp2-c8', type: 'Cloze', question: 'El profesor ___ en la pizarra.', answer: 'escribe', options: ['escribe', 'escribió', 'escribiendo'], instruction: 'Presente' },
    { id: 'sp2-c9', type: 'Cloze', question: 'Los alumnos ___ en la clase.', answer: 'están sentados', options: ['están sentados', 'estaban sentados', 'sentándose'], instruction: 'Presente' },
    { id: 'sp2-c10', type: 'Cloze', question: 'La campana ___ para el recreo.', answer: 'suena', options: ['suena', 'sonó', 'sonado'], instruction: 'Presente' },
    { id: 'sp2-c11', type: 'Cloze', question: 'Nosotros ___ juntos en el patio.', answer: 'jugamos', options: ['jugamos', 'jugamos', 'jugando'], instruction: 'Presente' },
    { id: 'sp2-c12', type: 'Cloze', question: 'El pájaro ha ___ un nido.', answer: 'construido', options: ['construido', 'construir', 'construyendo'], instruction: 'Participio' },
    { id: 'sp2-c13', type: 'Cloze', question: 'El agua del lago está ___ fría.', answer: 'muy', options: ['muy', 'poco', 'mucho'], instruction: 'Cantidad' },
    { id: 'sp2-c14', type: 'Cloze', question: 'Hay ___ coches en la carretera.', answer: 'muchos', options: ['muchos', 'varios', 'grande'], instruction: 'Cantidad' },
    { id: 'sp2-c15', type: 'Cloze', question: 'Me gustan ___ las manzanas.', answer: 'mucho', options: ['mucho', 'no', 'tal vez'], instruction: 'Opinión' },
    { id: 'sp2-c16', type: 'Cloze', question: 'Él nunca ___ sus deberes.', answer: 'olvida', options: ['olvida', 'recuerda', 'hace'], instruction: 'Acción' },
    { id: 'sp2-c17', type: 'Cloze', question: 'Recuerda ___ tu almuerzo.', answer: 'comer', options: ['comer', 'beber', 'tirar'], instruction: 'Acción' },
    { id: 'sp2-c18', type: 'Cloze', question: '¿Puedo ___ tu lápiz?', answer: 'tomar prestado', options: ['tomar prestado', 'comprar', 'romper'], instruction: 'Educación' },
    { id: 'sp2-c19', type: 'Cloze', question: 'Gracias ___ el préstamo.', answer: 'por', options: ['por', 'a', 'con'], instruction: 'Educación' },
    { id: 'sp2-c20', type: 'Cloze', question: 'Yo ___ de España.', answer: 'vengo', options: ['vengo', 'voy', 'vivo'], instruction: 'Origen' },
    { id: 'sp2-c21', type: 'Cloze', question: '¿Dónde ___?', answer: 'vives', options: ['vives', 'estás', 'tienes'], instruction: 'Dirección' },
    { id: 'sp2-c22', type: 'Cloze', question: 'Mi cumpleaños es ___ junio.', answer: 'en', options: ['en', 'sobre', 'a'], instruction: 'Tiempo' },
    { id: 'sp2-c23', type: 'Cloze', question: 'Vamos a una fiesta el ___.', answer: 'sábado', options: ['sábado', 'en junio', 'a mediodía'], instruction: 'Tiempo' },
    { id: 'sp2-c24', type: 'Cloze', question: 'Se hace oscuro por la ___.', answer: 'tarde', options: ['tarde', 'en', 'a'], instruction: 'Tiempo' },
    { id: 'sp2-c25', type: 'Cloze', question: 'El sol sale por el ___.', answer: 'este', options: ['este', 'oeste', 'norte'], instruction: 'Dirección' },
  ],
  3: [
    { id: 'sp3-c1', type: 'Cloze', question: 'La casa está ___ de ladrillos rojos.', answer: 'construida', options: ['construida', 'comida', 'corrida'], instruction: 'Estado' },
    { id: 'sp3-c2', type: 'Cloze', question: 'El coche ___ rápido por la carretera.', answer: 'conducía', options: ['conducía', 'volaba', 'nadaba'], instruction: 'Pasado' },
    { id: 'sp3-c3', type: 'Cloze', question: 'Nosotros ___ un libro apasionante en la escuela.', answer: 'leemos', options: ['leemos', 'comemos', 'bebemos'], instruction: 'Presente' },
    { id: 'sp3-c4', type: 'Cloze', question: 'Ayer ___ todo el día.', answer: 'llovió', options: ['llovió', 'brilló', 'sopló'], instruction: 'Clima' },
    { id: 'sp3-c5', type: 'Cloze', question: 'Mi mamá ___ un pastel delicioso.', answer: 'horneó', options: ['horneó', 'compró', 'encontró'], instruction: 'Pasado' },
    { id: 'sp3-c6', type: 'Cloze', question: 'El perro ___ tras la pelota.', answer: 'corrió', options: ['corrió', 'durmió', 'comió'], instruction: 'Pasado' },
    { id: 'sp3-c7', type: 'Cloze', question: 'El sol ___ en un cielo sin nubes.', answer: 'brilla', options: ['brilla', 'llueve', 'sopla'], instruction: 'Clima' },
    { id: 'sp3-c8', type: 'Cloze', question: 'Nosotros siempre ___ nuestros deberes.', answer: 'hacemos', options: ['hacemos', 'olvidamos', 'perdemos'], instruction: 'Acción' },
    { id: 'sp3-c9', type: 'Cloze', question: 'En el recreo ___ al fútbol.', answer: 'jugamos', options: ['jugamos', 'leemos', 'dormimos'], instruction: 'Acción' },
    { id: 'sp3-c10', type: 'Cloze', question: 'Mi padre ___ en una gran empresa.', answer: 'trabaja', options: ['trabaja', 'vive', 'come'], instruction: 'Acción' },
    { id: 'sp3-c11', type: 'Cloze', question: 'Ellos ___ al extranjero durante las vacaciones.', answer: 'viajaron', options: ['viajaron', 'se quedaron', 'durmieron'], instruction: 'Pasado' },
    { id: 'sp3-c12', type: 'Cloze', question: 'Yo ___ la Navidad con impaciencia.', answer: 'espero', options: ['espero', 'temo', 'odio'], instruction: 'Sentimiento' },
    { id: 'sp3-c13', type: 'Cloze', question: 'El niño ___ porque se hizo daño.', answer: 'llora', options: ['llora', 'ríe', 'duerme'], instruction: 'Acción' },
    { id: 'sp3-c14', type: 'Cloze', question: 'Nosotros ___ una canción para el cumpleaños.', answer: 'cantamos', options: ['cantamos', 'comimos', 'leímos'], instruction: 'Pasado' },
    { id: 'sp3-c15', type: 'Cloze', question: 'Recuerda ___ la puerta tras de ti.', answer: 'cerrar', options: ['cerrar', 'abrir', 'bloquear'], instruction: 'Acción' },
    { id: 'sp3-c16', type: 'Cloze', question: 'La luz debe estar ___ cuando te vayas.', answer: 'apagada', options: ['apagada', 'encendida', 'movida'], instruction: 'Acción' },
    { id: 'sp3-c17', type: 'Cloze', question: 'El agua en la tetera ___.', answer: 'hierve', options: ['hierve', 'se congela', 'sabe'], instruction: 'Estado' },
    { id: 'sp3-c18', type: 'Cloze', question: 'El helado se ___ al sol.', answer: 'derrite', options: ['derrite', 'se congela', 'crece'], instruction: 'Estado' },
    { id: 'sp3-c19', type: 'Cloze', question: 'Las flores ___ maravillosamente en el jardín.', answer: 'florecen', options: ['florecen', 'se marchitan', 'duermen'], instruction: 'Estado' },
    { id: 'sp3-c20', type: 'Cloze', question: 'Las hojas caen de los árboles en ___.', answer: 'otoño', options: ['otoño', 'primavera', 'verano'], instruction: 'Estación' },
    { id: 'sp3-c21', type: 'Cloze', question: 'Todo vuelve a estar verde en ___.', answer: 'primavera', options: ['primavera', 'invierno', 'otoño'], instruction: 'Estación' },
    { id: 'sp3-c22', type: 'Cloze', question: 'Nadamos en el mar en ___.', answer: 'verano', options: ['verano', 'invierno', 'otoño'], instruction: 'Estación' },
    { id: 'sp3-c23', type: 'Cloze', question: 'Hay nieve en ___.', answer: 'invierno', options: ['invierno', 'verano', 'primavera'], instruction: 'Estación' },
    { id: 'sp3-c24', type: 'Cloze', question: 'Una semana tiene ___ días.', answer: 'siete', options: ['siete', 'cinco', 'diez'], instruction: 'Número' },
    { id: 'sp3-c25', type: 'Cloze', question: 'Un año tiene doce ___.', answer: 'meses', options: ['meses', 'semanas', 'días'], instruction: 'Tiempo' },
  ],
  4: [
    { id: 'sp4-c1', type: 'Cloze', question: '¿Qué ___ es tu preferido?', answer: 'color', options: ['color', 'coche', 'comida'], instruction: 'Pregunta' },
    { id: 'sp4-c2', type: 'Cloze', question: '¿Dónde ___ ayer?', answer: 'estabas', options: ['estabas', 'estás', 'ser'], instruction: 'Tiempo' },
    { id: 'sp4-c3', type: 'Cloze', question: '¿Con quién ___ por teléfono?', answer: 'hablaste', options: ['hablaste', 'comiste', 'dormiste'], instruction: 'Acción' },
    { id: 'sp4-c4', type: 'Cloze', question: '¿Cuándo ___ la escuela?', answer: 'empiezas', options: ['empiezas', 'duermes', 'comes'], instruction: 'Escuela' },
    { id: 'sp4-c5', type: 'Cloze', question: '¿Qué ___ para cenar?', answer: 'comiste', options: ['comiste', 'es', 'va'], instruction: 'Acción' },
    { id: 'sp4-c6', type: 'Cloze', question: '¿Por qué te ___?', answer: 'ríes', options: ['ríes', 'duermes', 'conduces'], instruction: 'Sentimiento' },
    { id: 'sp4-c7', type: 'Cloze', question: '¿Cómo ___ esta tarea?', answer: 'resuelves', options: ['resuelves', 'comes', 'bebes'], instruction: 'Escuela' },
    { id: 'sp4-c8', type: 'Cloze', question: 'Me ___ jugar a videojuegos.', answer: 'encanta', options: ['encanta', 'disgusta', 'vivo'], instruction: 'Deseo' },
    { id: 'sp4-c9', type: 'Cloze', question: 'Mi perro ___ muy fuerte.', answer: 'ladra', options: ['ladra', 'maúlla', 'pía'], instruction: 'Sonido' },
    { id: 'sp4-c10', type: 'Cloze', question: 'El gato ___ cuando está contento.', answer: 'ronronea', options: ['ronronea', 'ladra', 'silba'], instruction: 'Sonido' },
    { id: 'sp4-c11', type: 'Cloze', question: 'El caballo ___ por el campo.', answer: 'galopa', options: ['galopa', 'nada', 'vuela'], instruction: 'Acción' },
    { id: 'sp4-c12', type: 'Cloze', question: 'El pájaro ha ___ huevos en el nido.', answer: 'puesto', options: ['puesto', 'comido', 'perdido'], instruction: 'Naturaleza' },
    { id: 'sp4-c13', type: 'Cloze', question: 'La vaca ___ su hierba.', answer: 'masca', options: ['masca', 'lee', 'salta'], instruction: 'Naturaleza' },
    { id: 'sp4-c14', type: 'Cloze', question: 'La oveja tiene una lana muy ___.', answer: 'suave', options: ['suave', 'dura', 'azul'], instruction: 'Naturaleza' },
    { id: 'sp4-c15', type: 'Cloze', question: 'El cerdo se ___ en el lodo.', answer: 'revuelca', options: ['revuelca', 'lava', 'vuela'], instruction: 'Naturaleza' },
    { id: 'sp4-c16', type: 'Cloze', question: 'El agricultor ___ el grano en el campo.', answer: 'cosecha', options: ['cosecha', 'siembra', 'come'], instruction: 'Profesión' },
    { id: 'sp4-c17', type: 'Cloze', question: 'El jardinero ___ las flores.', answer: 'riega', options: ['riega', 'come', 'corta'], instruction: 'Profesión' },
    { id: 'sp4-c18', type: 'Cloze', question: 'El panadero hornea ___ cada mañana.', answer: 'pan', options: ['pan', 'piedras', 'zapatos'], instruction: 'Profesión' },
    { id: 'sp4-c19', type: 'Cloze', question: 'La policía ___ a los criminales.', answer: 'arresta', options: ['arresta', 'ayuda', 'alimenta'], instruction: 'Profesión' },
    { id: 'sp4-c20', type: 'Cloze', question: 'El doctor ___ a la gente enferma.', answer: 'examina', options: ['examina', 'come', 'golpea'], instruction: 'Profesión' },
    { id: 'sp4-c21', type: 'Cloze', question: 'El bombero ___ el fuego.', answer: 'apaga', options: ['apaga', 'enciende', 'mira'], instruction: 'Profesión' },
    { id: 'sp4-c22', type: 'Cloze', question: 'El peluquero ___ mi cabello.', answer: 'corta', options: ['corta', 'lava', 'tiñe'], instruction: 'Profesión' },
    { id: 'sp4-c23', type: 'Cloze', question: 'El carpintero ___ una nueva casa.', answer: 'construye', options: ['construye', 'come', 'dibuja'], instruction: 'Profesión' },
    { id: 'sp4-c24', type: 'Cloze', question: 'El albañil usa ___ para el muro.', answer: 'ladrillos', options: ['ladrillos', 'madera', 'vidrio'], instruction: 'Profesión' },
    { id: 'sp4-c25', type: 'Cloze', question: 'El pintor pone ___ en la pared.', answer: 'pintura', options: ['pintura', 'agua', 'comida'], instruction: 'Profesión' },
  ],
};
