/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const SPANSK_CLOZE_P2: Partial<Record<Grade, GameContent[]>> = {
  5: [
    { id: 'sp5-c1', type: 'Cloze', question: 'El agua ___ a 100 grados centígrados.', answer: 'hierve', options: ['hierve', 'se congela', 'se derrite'], instruction: 'Ciencia' },
    { id: 'sp5-c2', type: 'Cloze', question: 'El oxígeno es un ___ que respiramos.', answer: 'gas', options: ['gas', 'líquido', 'sólido'], instruction: 'Ciencia' },
    { id: 'sp5-c3', type: 'Cloze', question: 'El astronauta ___ en el espacio.', answer: 'flota', options: ['flota', 'corre', 'cae'], instruction: 'Ciencia' },
    { id: 'sp5-c4', type: 'Cloze', question: 'El volcán ___ y expulsó lava.', answer: 'erupcionó', options: ['erupcionó', 'durmió', 'cantó'], instruction: 'Naturaleza' },
    { id: 'sp5-c5', type: 'Cloze', question: 'La Tierra ___ alrededor del sol.', answer: 'gira', options: ['gira', 'se queda', 'cuelga'], instruction: 'Ciencia' },
    { id: 'sp5-c6', type: 'Cloze', question: 'La fotosíntesis es un ___ de las plantas.', answer: 'proceso', options: ['proceso', 'animal', 'juego'], instruction: 'Ciencia' },
    { id: 'sp5-c7', type: 'Cloze', question: 'El corazón ___ sangre por el cuerpo.', answer: 'bombea', options: ['bombea', 'limpia', 'detiene'], instruction: 'Cuerpo' },
    { id: 'sp5-c8', type: 'Cloze', question: 'El esqueleto humano tiene muchos ___.', answer: 'huesos', options: ['huesos', 'músculos', 'pelos'], instruction: 'Cuerpo' },
    { id: 'sp5-c9', type: 'Cloze', question: 'Los pulmones nos ayudan a ___.', answer: 'respirar', options: ['respirar', 'comer', 'ver'], instruction: 'Cuerpo' },
    { id: 'sp5-c10', type: 'Cloze', question: 'El cerebro ___ nuestro cuerpo.', answer: 'controla', options: ['controla', 'duerme', 'come'], instruction: 'Cuerpo' },
    { id: 'sp5-c11', type: 'Cloze', question: 'La gravedad nos ___ hacia abajo.', answer: 'tira', options: ['tira', 'empuja', 'levanta'], instruction: 'Ciencia' },
    { id: 'sp5-c12', type: 'Cloze', question: 'Un imán ___ el hierro.', answer: 'atrae', options: ['atrae', 'repele', 'quema'], instruction: 'Ciencia' },
    { id: 'sp5-c13', type: 'Cloze', question: 'La luz viaja muy ___.', answer: 'rápido', options: ['rápido', 'lento', 'nada'], instruction: 'Ciencia' },
    { id: 'sp5-c14', type: 'Cloze', question: 'El sonido necesita un ___ para viajar.', answer: 'medio', options: ['medio', 'espacio', 'tiempo'], instruction: 'Ciencia' },
    { id: 'sp5-c15', type: 'Cloze', question: 'La electricidad fluye por un ___.', answer: 'circuito', options: ['circuito', 'agujero', 'camino'], instruction: 'Ciencia' },
    { id: 'sp5-c16', type: 'Cloze', question: 'Un átomo es muy ___.', answer: 'pequeño', options: ['pequeño', 'grande', 'pesado'], instruction: 'Ciencia' },
    { id: 'sp5-c17', type: 'Cloze', question: 'La química estudia la ___.', answer: 'materia', options: ['materia', 'historia', 'música'], instruction: 'Ciencia' },
    { id: 'sp5-c18', type: 'Cloze', question: 'El sistema solar tiene ocho ___.', answer: 'planetas', options: ['planetas', 'estrellas', 'lunas'], instruction: 'Espacio' },
    { id: 'sp5-c19', type: 'Cloze', question: 'La Vía Láctea es nuestra ___.', answer: 'galaxia', options: ['galaxia', 'planeta', 'estrella'], instruction: 'Espacio' },
    { id: 'sp5-c20', type: 'Cloze', question: 'Un eclipse ocurre cuando la luna ___ el sol.', answer: 'tapa', options: ['tapa', 'ilumina', 'come'], instruction: 'Espacio' },
    { id: 'sp5-c21', type: 'Cloze', question: 'La atmósfera nos ___ de la radiación.', answer: 'protege', options: ['protege', 'quema', 'enfría'], instruction: 'Ciencia' },
    { id: 'sp5-c22', type: 'Cloze', question: 'El ciclo del agua incluye la ___.', answer: 'evaporación', options: ['evaporación', 'revolución', 'nutrición'], instruction: 'Ciencia' },
    { id: 'sp5-c23', type: 'Cloze', question: 'El clima cambia con las ___.', answer: 'estaciones', options: ['estaciones', 'comidas', 'ropas'], instruction: 'Clima' },
    { id: 'sp5-c24', type: 'Cloze', question: 'La biodiversidad es ___ para el planeta.', answer: 'importante', options: ['importante', 'mala', 'desconocida'], instruction: 'Ecología' },
    { id: 'sp5-c25', type: 'Cloze', question: 'Debemos ___ para salvar el medio ambiente.', answer: 'reciclar', options: ['reciclar', 'ensuciar', 'quemar'], instruction: 'Ecología' },
  ],
  6: [
    { id: 'sp6-c1', type: 'Cloze', question: 'El ___ de la película fue sorprendente.', answer: 'final', options: ['final', 'actor', 'título'], instruction: 'Literatura' },
    { id: 'sp6-c2', type: 'Cloze', question: 'El personaje principal es el ___.', answer: 'protagonista', options: ['protagonista', 'villano', 'extra'], instruction: 'Literatura' },
    { id: 'sp6-c3', type: 'Cloze', question: 'La novela está escrita en ___.', answer: 'prosa', options: ['prosa', 'verso', 'dibujos'], instruction: 'Literatura' },
    { id: 'sp6-c4', type: 'Cloze', question: 'El poema tiene muchas ___.', answer: 'rimas', options: ['rimas', 'páginas', 'números'], instruction: 'Literatura' },
    { id: 'sp6-c5', type: 'Cloze', question: 'La metáfora es una ___ literaria.', answer: 'figura', options: ['figura', 'persona', 'comida'], instruction: 'Literatura' },
    { id: 'sp6-c6', type: 'Cloze', question: 'El autor del libro es ___.', answer: 'famoso', options: ['famoso', 'azul', 'alto'], instruction: 'Literatura' },
    { id: 'sp6-c7', type: 'Cloze', question: 'La trama de la historia es ___.', answer: 'interesante', options: ['interesante', 'roja', 'fría'], instruction: 'Literatura' },
    { id: 'sp6-c8', type: 'Cloze', question: 'El escenario es donde ___ la acción.', answer: 'ocurre', options: ['ocurre', 'termina', 'come'], instruction: 'Literatura' },
    { id: 'sp6-c9', type: 'Cloze', question: 'El conflicto es el ___ del relato.', answer: 'problema', options: ['problema', 'final', 'nombre'], instruction: 'Literatura' },
    { id: 'sp6-c10', type: 'Cloze', question: 'La resolución es cómo se ___ el conflicto.', answer: 'soluciona', options: ['soluciona', 'empeora', 'olvida'], instruction: 'Literatura' },
    { id: 'sp6-c11', type: 'Cloze', question: 'El narrador cuenta la ___.', answer: 'historia', options: ['historia', 'comida', 'cuenta'], instruction: 'Literatura' },
    { id: 'sp6-c12', type: 'Cloze', question: 'El diálogo es cuando los personajes ___.', answer: 'hablan', options: ['hablan', 'duermen', 'corren'], instruction: 'Literatura' },
    { id: 'sp6-c13', type: 'Cloze', question: 'El monólogo es cuando habla ___ sola.', answer: 'una persona', options: ['una persona', 'mucha gente', 'un perro'], instruction: 'Literatura' },
    { id: 'sp6-c14', type: 'Cloze', question: 'El drama se representa en el ___.', answer: 'teatro', options: ['teatro', 'cine', 'parque'], instruction: 'Literatura' },
    { id: 'sp6-c15', type: 'Cloze', question: 'La comedia nos hace ___.', answer: 'reír', options: ['reír', 'llorar', 'gritar'], instruction: 'Literatura' },
    { id: 'sp6-c16', type: 'Cloze', question: 'La tragedia es una historia ___.', answer: 'triste', options: ['triste', 'feliz', 'corta'], instruction: 'Literatura' },
    { id: 'sp6-c17', type: 'Cloze', question: 'La fantasía incluye elementos ___.', answer: 'mágicos', options: ['mágicos', 'reales', 'aburridos'], instruction: 'Literatura' },
    { id: 'sp6-c18', type: 'Cloze', question: 'La ciencia ficción trata del ___.', answer: 'futuro', options: ['futuro', 'pasado', 'presente'], instruction: 'Literatura' },
    { id: 'sp6-c19', type: 'Cloze', question: 'En español trabajamos la ___.', answer: 'gramática', options: ['gramática', 'cocina', 'deporte'], instruction: 'Lengua' },
    { id: 'sp6-c20', type: 'Cloze', question: 'El sustantivo nombra a cosas o ___.', answer: 'personas', options: ['personas', 'acciones', 'colores'], instruction: 'Lengua' },
    { id: 'sp6-c21', type: 'Cloze', question: 'El adjetivo describe al ___.', answer: 'sustantivo', options: ['sustantivo', 'verbo', 'adverbio'], instruction: 'Lengua' },
    { id: 'sp6-c22', type: 'Cloze', question: 'El verbo expresa una ___.', answer: 'acción', options: ['acción', 'cosa', 'nombre'], instruction: 'Lengua' },
    { id: 'sp6-c23', type: 'Cloze', question: 'El adverbio modifica al ___.', answer: 'verbo', options: ['verbo', 'nombre', 'sujeto'], instruction: 'Lengua' },
    { id: 'sp6-c24', type: 'Cloze', question: 'La preposición une ___.', answer: 'palabras', options: ['palabras', 'letras', 'párrafos'], instruction: 'Lengua' },
    { id: 'sp6-c25', type: 'Cloze', question: 'La conjunción une ___.', answer: 'oraciones', options: ['oraciones', 'letras', 'puntos'], instruction: 'Lengua' },
  ],
  7: [
    { id: 'sp7-c1', type: 'Cloze', question: 'La democracia es un sistema ___.', answer: 'político', options: ['político', 'musical', 'animal'], instruction: 'Sociedad' },
    { id: 'sp7-c2', type: 'Cloze', question: 'Los ciudadanos tienen el derecho a ___.', answer: 'votar', options: ['votar', 'correr', 'dormir'], instruction: 'Sociedad' },
    { id: 'sp7-c3', type: 'Cloze', question: 'La constitución es la ley ___.', answer: 'fundamental', options: ['fundamental', 'pequeña', 'azul'], instruction: 'Sociedad' },
    { id: 'sp7-c4', type: 'Cloze', question: 'El gobierno administra el ___.', answer: 'estado', options: ['estado', 'jardín', 'coche'], instruction: 'Sociedad' },
    { id: 'sp7-c5', type: 'Cloze', question: 'La justicia debe ser ___.', answer: 'igual para todos', options: ['igual para todos', 'cara', 'secreta'], instruction: 'Sociedad' },
    { id: 'sp7-c6', type: 'Cloze', question: 'Los derechos ___ son para todos.', answer: 'humanos', options: ['humanos', 'animales', 'digitales'], instruction: 'Sociedad' },
    { id: 'sp7-c7', type: 'Cloze', question: 'La libertad de ___ es importante.', answer: 'expresión', options: ['expresión', 'vuelo', 'salto'], instruction: 'Sociedad' },
    { id: 'sp7-c8', type: 'Cloze', question: 'La igualdad es un valor ___.', answer: 'público', options: ['público', 'privado', 'interior'], instruction: 'Sociedad' },
    { id: 'sp7-c9', type: 'Cloze', question: 'La solidaridad ayuda a la ___.', answer: 'comunidad', options: ['comunidad', 'tienda', 'calle'], instruction: 'Sociedad' },
    { id: 'sp7-c10', type: 'Cloze', question: 'La educación es una ___ al futuro.', answer: 'puerta', options: ['puerta', 'pared', 'ventana'], instruction: 'Sociedad' },
    { id: 'sp7-c11', type: 'Cloze', question: 'El respeto es la base de la ___.', answer: 'convivencia', options: ['convivencia', 'pelea', 'guerra'], instruction: 'Sociedad' },
    { id: 'sp7-c12', type: 'Cloze', question: 'La tolerancia acepta las ___.', answer: 'diferencias', options: ['diferencias', 'comidas', 'ropas'], instruction: 'Sociedad' },
    { id: 'sp7-c13', type: 'Cloze', question: 'La paz es ausencia de ___.', answer: 'guerra', options: ['guerra', 'música', 'luz'], instruction: 'Sociedad' },
    { id: 'sp7-c14', type: 'Cloze', question: 'La globalización ___ al mundo.', answer: 'conecta', options: ['conecta', 'separa', 'rompe'], instruction: 'Sociedad' },
    { id: 'sp7-c15', type: 'Cloze', question: 'Ciertas noticias pueden ser ___.', answer: 'falsas', options: ['falsas', 'buenas', 'verdes'], instruction: 'Comunicación' },
    { id: 'sp7-c16', type: 'Cloze', question: 'Los medios de comunicación informan a la ___.', answer: 'opinión pública', options: ['opinión pública', 'pared', 'mesa'], instruction: 'Comunicación' },
    { id: 'sp7-c17', type: 'Cloze', question: 'Internet ha cambiado nuestra ___ de ser.', answer: 'forma', options: ['forma', 'color', 'tamaño'], instruction: 'Comunicación' },
    { id: 'sp7-c18', type: 'Cloze', question: 'Debemos ser críticos con la ___.', answer: 'información', options: ['información', 'comida', 'música'], instruction: 'Pensamiento' },
    { id: 'sp7-c19', type: 'Cloze', question: 'La privacidad es un ___ en línea.', answer: 'derecho', options: ['derecho', 'problema', 'juego'], instruction: 'Tecnología' },
    { id: 'sp7-c20', type: 'Cloze', question: 'Una metáfora es una comparación ___.', answer: 'implícita', options: ['implícita', 'tonta', 'azul'], instruction: 'Lenguaje' },
    { id: 'sp7-c21', type: 'Cloze', question: 'La personificación da vida ___ a las cosas.', answer: 'humana', options: ['humana', 'animal', 'muerta'], instruction: 'Lenguaje' },
    { id: 'sp7-c22', type: 'Cloze', question: 'La ironía es decir lo ___ de lo que se piensa.', answer: 'contrario', options: ['contrario', 'mismo', 'azul'], instruction: 'Lenguaje' },
    { id: 'sp7-c23', type: 'Cloze', question: 'El sarcasmo es una forma ___ de ironía.', answer: 'burlona', options: ['burlona', 'dulce', 'feliz'], instruction: 'Lenguaje' },
    { id: 'sp7-c24', type: 'Cloze', question: 'El hipérbaton altera el ___ de las palabras.', answer: 'orden', options: ['orden', 'color', 'sonido'], instruction: 'Lenguaje' },
    { id: 'sp7-c25', type: 'Cloze', question: 'La hipérbole ___ la realidad.', answer: 'exagera', options: ['exagera', 'reduce', 'borra'], instruction: 'Lenguaje' },
  ],
  8: [
    { id: 'sp8-c1', type: 'Cloze', question: 'La sociedad debe ___ a la tecnología.', answer: 'adaptarse', options: ['adaptarse', 'eliminarla', 'parar'], instruction: 'Sociedad' },
    { id: 'sp8-c2', type: 'Cloze', question: 'La identidad es un tema ___ en la literatura.', answer: 'central', options: ['central', 'desconocido', 'azul'], instruction: 'Tema' },
    { id: 'sp8-c3', type: 'Cloze', question: '¿Quién soy yo? Es una pregunta ___.', answer: 'existencial', options: ['existencial', 'tonta', 'fácil'], instruction: 'Tema' },
    { id: 'sp8-c4', type: 'Cloze', question: 'La globalización hace el mundo más ___ para nosotros.', answer: 'pequeño', options: ['pequeño', 'grande', 'azul'], instruction: 'Sociedad' },
    { id: 'sp8-c5', type: 'Cloze', question: 'Los valores cambian con el ___ de las décadas.', answer: 'paso', options: ['paso', 'color', 'peso'], instruction: 'Sociedad' },
    { id: 'sp8-c6', type: 'Cloze', question: 'La ética es el estudio de la ___.', answer: 'moral', options: ['moral', 'historia', 'química'], instruction: 'Etica' },
    { id: 'sp8-c7', type: 'Cloze', question: 'La libertad conlleva ___ personal.', answer: 'responsabilidad', options: ['responsabilidad', 'dinero', 'comida'], instruction: 'Etica' },
    { id: 'sp8-c8', type: 'Cloze', question: 'El futuro es ___ para todos.', answer: 'incierto', options: ['incierto', 'claro', 'rojo'], instruction: 'Pensamiento' },
    { id: 'sp8-c9', type: 'Cloze', question: 'El conocimiento se adquiere con la ___.', answer: 'experiencia', options: ['experiencia', 'suerte', 'magia'], instruction: 'Pensamiento' },
    { id: 'sp8-c10', type: 'Cloze', question: 'La sabiduría es el uso del ___ para el bien.', answer: 'saber', options: ['saber', 'dinero', 'poder'], instruction: 'Pensamiento' },
    { id: 'sp8-c11', type: 'Cloze', question: 'El arte expresa lo que las palabras no puede ___ .', answer: 'decir', options: ['decir', 'comer', 'beber'], instruction: 'Arte' },
    { id: 'sp8-c12', type: 'Cloze', question: 'La cultura es el alma de un ___ .', answer: 'pueblo', options: ['pueblo', 'edificio', 'ordenador'], instruction: 'Cultura' },
    { id: 'sp8-c13', type: 'Cloze', question: 'La diversidad enriquece a la ___.', answer: 'sociedad', options: ['sociedad', 'pared', 'mesa'], instruction: 'Cultura' },
    { id: 'sp8-c14', type: 'Cloze', question: 'La tradición conecta el pasado con el ___ .', answer: 'presente', options: ['presente', 'futuro', 'ayer'], instruction: 'Cultura' },
    { id: 'sp8-c15', type: 'Cloze', question: 'La innovación impulsa el ___ .', answer: 'progreso', options: ['progreso', 'atraso', 'sueño'], instruction: 'Futuro' },
    { id: 'sp8-c16', type: 'Cloze', question: 'La sostenibilidad es clave para la ___ .', answer: 'supervivencia', options: ['supervivencia', 'fiesta', 'guerra'], instruction: 'Ecología' },
    { id: 'sp8-c17', type: 'Cloze', question: 'El cambio climático es un desafío ___ .', answer: 'global', options: ['global', 'fácil', 'azul'], instruction: 'Ecología' },
    { id: 'sp8-c18', type: 'Cloze', question: 'La energía renovable es la ___ del mañana .', answer: 'solución', options: ['solución', 'falla', 'noche'], instruction: 'Futuro' },
    { id: 'sp8-c19', type: 'Cloze', question: 'Las redes sociales pueden ser ___ .', answer: 'adictivas', options: ['adictivas', 'verdes', 'sabrosas'], instruction: 'Sociedad' },
    { id: 'sp8-c20', type: 'Cloze', question: 'La empatía es sentir el ___ del otro .', answer: 'dolor', options: ['dolor', 'dinero', 'calor'], instruction: 'Social' },
    { id: 'sp8-c21', type: 'Cloze', question: 'La amistad se basa en la ___ .', answer: 'confianza', options: ['confianza', 'duda', 'envidia'], instruction: 'Social' },
    { id: 'sp8-c22', type: 'Cloze', question: 'El perdón es necesario para ___ .', answer: 'avanzar', options: ['avanzar', 'parar', 'caer'], instruction: 'Social' },
    { id: 'sp8-c23', type: 'Cloze', question: 'La ambición debe tener ___ .', answer: 'límites', options: ['límites', 'dinero', 'alas'], instruction: 'Personal' },
    { id: 'sp8-c24', type: 'Cloze', question: 'La humildad es una gran ___ .', answer: 'virtud', options: ['virtud', 'mancha', 'piedra'], instruction: 'Personal' },
    { id: 'sp8-c25', type: 'Cloze', question: 'El éxito es relativo a cada ___ .', answer: 'persona', options: ['persona', 'perro', 'objeto'], instruction: 'Personal' },
  ],
  9: [
    { id: 'sp9-c1', type: 'Cloze', question: 'El existencialismo se centra en la ___ elección humana.', answer: 'libre', options: ['libre', 'forzada', 'ninguna'], instruction: 'Filosofía' },
    { id: 'sp9-c2', type: 'Cloze', question: 'La realidad es una construcción ___ .', answer: 'social', options: ['social', 'física', 'roja'], instruction: 'Filosofía' },
    { id: 'sp9-c3', type: 'Cloze', question: 'El lenguaje moldea nuestro ___ .', answer: 'pensamiento', options: ['pensamiento', 'zapato', 'viaje'], instruction: 'Filosofía' },
    { id: 'sp9-c4', type: 'Cloze', question: 'La ciencia busca la ___ objetiva .', answer: 'verdad', options: ['verdad', 'mentira', 'magia'], instruction: 'Ciencia' },
    { id: 'sp9-c5', type: 'Cloze', question: 'La teoría de la relatividad cambió la ___ .', answer: 'física', options: ['física', 'música', 'historia'], instruction: 'Ciencia' },
    { id: 'sp9-c6', type: 'Cloze', question: 'El Big Bang es el origen del ___ .', answer: 'universo', options: ['universo', 'planeta', 'sol'], instruction: 'Ciencia' },
    { id: 'sp9-c7', type: 'Cloze', question: 'La evolución es la base de la ___ .', answer: 'biología', options: ['biología', 'matemática', 'arte'], instruction: 'Ciencia' },
    { id: 'sp9-c8', type: 'Cloze', question: 'El ADN contiene la información ___ .', answer: 'genética', options: ['genética', 'secreta', 'falsa'], instruction: 'Ciencia' },
    { id: 'sp9-c9', type: 'Cloze', question: 'La inteligencia artificial imita a la ___ .', answer: 'humana', options: ['humana', 'animal', 'maquinaria'], instruction: 'Tecnología' },
    { id: 'sp9-c10', type: 'Cloze', question: 'El algoritmo decide lo que ___ en pantalla .', answer: 'vemos', options: ['vemos', 'comemos', 'oímos'], instruction: 'Tecnología' },
    { id: 'sp9-c11', type: 'Cloze', question: 'La ciberseguridad protege nuestros ___ .', answer: 'datos', options: ['datos', 'muebles', 'juguetes'], instruction: 'Tecnología' },
    { id: 'sp9-c12', type: 'Cloze', question: 'El futuro será ___ por los robots .', answer: 'influenciado', options: ['influenciado', 'comido', 'parado'], instruction: 'Tecnología' },
    { id: 'sp9-c13', type: 'Cloze', question: 'La historia es un ciclo que se ___ .', answer: 'repite', options: ['repite', 'rompe', 'para'], instruction: 'Historia' },
    { id: 'sp9-c14', type: 'Cloze', question: 'La revolución industrial cambió la ___ .', answer: 'producción', options: ['producción', 'religión', 'música'], instruction: 'Historia' },
    { id: 'sp9-c15', type: 'Cloze', question: 'La guerra fría fue un conflicto ___ .', answer: 'ideológico', options: ['ideológico', 'físico', 'caliente'], instruction: 'Historia' },
    { id: 'sp9-c16', type: 'Cloze', question: 'La caída del muro de Berlín fue ___ .', answer: 'histórica', options: ['histórica', 'triste', 'secreta'], instruction: 'Historia' },
    { id: 'sp9-c17', type: 'Cloze', question: 'La sociedad de consumo busca el ___ .', answer: 'crecimiento', options: ['crecimiento', 'ahorro', 'cambio'], instruction: 'Sociología' },
    { id: 'sp9-c18', type: 'Cloze', question: 'El capitalismo se basa en el ___ mercado .', answer: 'libre', options: ['libre', 'fijo', 'cerrado'], instruction: 'Economía' },
    { id: 'sp9-c19', type: 'Cloze', question: 'La inflación reduce el poder de ___ .', answer: 'compra', options: ['compra', 'venta', 'salto'], instruction: 'Economía' },
    { id: 'sp9-c20', type: 'Cloze', question: 'La bolsa de valores es muy ___ .', answer: 'volátil', options: ['volátil', 'estática', 'azul'], instruction: 'Economía' },
    { id: 'sp9-c21', type: 'Cloze', question: 'El derecho internacional rige las ___ .', answer: 'naciones', options: ['naciones', 'casas', 'familias'], instruction: 'Derecho' },
    { id: 'sp9-c22', type: 'Cloze', question: 'La ONU busca la paz ___ .', answer: 'mundial', options: ['mundial', 'local', 'privada'], instruction: 'Política' },
    { id: 'sp9-c23', type: 'Cloze', question: 'El feminismo lucha por la ___ .', answer: 'igualdad', options: ['igualdad', 'guerra', 'separación'], instruction: 'Sociedad' },
    { id: 'sp9-c24', type: 'Cloze', question: 'El racismo es una forma de ___ .', answer: 'discriminación', options: ['discriminación', 'unión', 'ayuda'], instruction: 'Sociedad' },
    { id: 'sp9-c25', type: 'Cloze', question: 'La justicia social es un ___ noble .', answer: 'ideal', options: ['ideal', 'error', 'objeto'], instruction: 'Sociedad' },
  ],
};
