/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const TYSK_CLOZE_P2: Partial<Record<Grade, GameContent[]>> = {
  5: [
    { id: 'ty5-c1', type: 'Cloze', question: 'Der Astronaut ___ im Weltraum.', answer: 'schwebt', options: ['schwebt', 'rennt', 'fällt'], instruction: 'Science' },
    { id: 'ty5-c2', type: 'Cloze', question: 'Der Vulkan ist ___ und hat Lava ausgespuckt.', answer: 'ausgebrochen', options: ['ausgebrochen', 'eingeschlafen', 'gesungen'], instruction: 'Nature' },
    { id: 'ty5-c3', type: 'Cloze', question: 'Die Erde ___ sich um die Sonne.', answer: 'dreht', options: ['dreht', 'bleibt', 'hängt'], instruction: 'Science' },
    { id: 'ty5-c4', type: 'Cloze', question: 'Der Mond ist der Satellit der ___ .', answer: 'Erde', options: ['Erde', 'Sonne', 'Mars'], instruction: 'Science' },
    { id: 'ty5-c5', type: 'Cloze', question: 'Pflanzen nutzen ___ für die Photosynthese.', answer: 'Licht', options: ['Licht', 'Dunkelheit', 'Milch'], instruction: 'Biology' },
    { id: 'ty5-c6', type: 'Cloze', question: 'Der Mensch atmet durch die ___ .', answer: 'Lungen', options: ['Lungen', 'Ohren', 'Füße'], instruction: 'Biology' },
    { id: 'ty5-c7', type: 'Cloze', question: 'Das Herz ___ das Blut durch den Körper.', answer: 'pumpt', options: ['pumpt', 'saugt', 'reinigt'], instruction: 'Biology' },
    { id: 'ty5-c8', type: 'Cloze', question: 'Das Gehirn ___ unsere Gedanken.', answer: 'steuert', options: ['steuert', 'vergisst', 'verliert'], instruction: 'Biology' },
    { id: 'ty5-c9', type: 'Cloze', question: 'Das Skelett ___ unseren Körper aufrecht.', answer: 'hält', options: ['hält', 'fällt', 'stellt'], instruction: 'Biology' },
    { id: 'ty5-c10', type: 'Cloze', question: 'Muskeln ermöglichen uns die ___ .', answer: 'Bewegung', options: ['Bewegung', 'Gedanken', 'Schlaf'], instruction: 'Biology' },
    { id: 'ty5-c11', type: 'Cloze', question: 'Die Verdauung beginnt im ___ .', answer: 'Mund', options: ['Mund', 'Magen', 'Darm'], instruction: 'Biology' },
    { id: 'ty5-c12', type: 'Cloze', question: 'Das Blut enthält ___ , das Sauerstoff transportiert.', answer: 'Eisen', options: ['Eisen', 'Gold', 'Silber'], instruction: 'Biology' },
    { id: 'ty5-c13', type: 'Cloze', question: 'Wir riechen mit unserer ___ .', answer: 'Nase', options: ['Nase', 'Mund', 'Auge'], instruction: 'Senses' },
    { id: 'ty5-c14', type: 'Cloze', question: 'Wir schmecken mit unserer ___ .', answer: 'Zunge', options: ['Zunge', 'Zähnen', 'Lippen'], instruction: 'Senses' },
    { id: 'ty5-c15', type: 'Cloze', question: 'Wir hören mit unseren ___ .', answer: 'Ohren', options: ['Ohren', 'Augen', 'Nase'], instruction: 'Senses' },
    { id: 'ty5-c16', type: 'Cloze', question: 'Wir sehen mit unseren ___ .', answer: 'Augen', options: ['Augen', 'Ohren', 'Mund'], instruction: 'Senses' },
    { id: 'ty5-c17', type: 'Cloze', question: 'Wir fühlen mit unserer ___ .', answer: 'Haut', options: ['Haut', 'Haaren', 'Nägeln'], instruction: 'Senses' },
    { id: 'ty5-c18', type: 'Cloze', question: 'Es ist wichtig, sich gesund zu ___ .', answer: 'ernähren', options: ['ernähren', 'schlafen', 'rennen'], instruction: 'Health' },
    { id: 'ty5-c19', type: 'Cloze', question: 'Bewegung macht den Körper ___ .', answer: 'stark', options: ['stark', 'schwach', 'blau'], instruction: 'Health' },
    { id: 'ty5-c20', type: 'Cloze', question: 'Schlaf ist wichtig für die ___ des Körpers.', answer: 'Erholung', options: ['Erholung', 'Auto', 'Haus'], instruction: 'Health' },
    { id: 'ty5-c21', type: 'Cloze', question: 'Putz dir zweimal am Tag die ___ .', answer: 'Zähne', options: ['Zähne', 'Hände', 'Haare'], instruction: 'Health' },
    { id: 'ty5-c22', type: 'Cloze', question: 'Wasch dir vor dem ___ die Hände.', answer: 'Essen', options: ['Essen', 'Schlaf', 'Spiel'], instruction: 'Health' },
    { id: 'ty5-c23', type: 'Cloze', question: 'Trink viel ___ , wenn es heiß ist.', answer: 'Wasser', options: ['Wasser', 'Saft', 'Kaffee'], instruction: 'Health' },
    { id: 'ty5-c24', type: 'Cloze', question: 'Frische Luft ist ___ für die Gesundheit.', answer: 'gut', options: ['gut', 'schlecht', 'gefährlich'], instruction: 'Health' },
    { id: 'ty5-c25', type: 'Cloze', question: 'Süßigkeiten enthalten viel ___ .', answer: 'Zucker', options: ['Zucker', 'Salz', 'Pfeffer'], instruction: 'Health' },
    { id: 'ty5-c26', type: 'Cloze', question: 'Jedes Jahr gibt es einen ___ in der Schule.', answer: 'Sporttag', options: ['Sporttag', 'Schlaftag', 'Nachttag'], instruction: 'School' },
    { id: 'ty5-c27', type: 'Cloze', question: 'Wir sollten ___ mit anderen sprechen.', answer: 'höflich', options: ['höflich', 'schreiend', 'schlagend'], instruction: 'Social' },
    { id: 'ty5-c28', type: 'Cloze', question: 'Man soll sich um seine Freunde ___ .', answer: 'kümmern', options: ['kümmern', 'hassen', 'anschreien'], instruction: 'Social' },
    { id: 'ty5-c29', type: 'Cloze', question: 'Es ist ___ , ein guter Kamerad zu sein.', answer: 'wichtig', options: ['wichtig', 'dumm', 'egal'], instruction: 'Social' },
    { id: 'ty5-c30', type: 'Cloze', question: 'Mobbing ist in unserer Schule ___ .', answer: 'verboten', options: ['verboten', 'erlaubt', 'gut'], instruction: 'Social' },
    { id: 'ty5-c31', type: 'Cloze', question: 'Wir lösen ___ durch Reden.', answer: 'Konflikte', options: ['Konflikte', 'Essen', 'Hausaufgaben'], instruction: 'Social' },
    { id: 'ty5-c32', type: 'Cloze', question: 'Wir ___ in Gruppen in der Klasse.', answer: 'arbeiten', options: ['arbeiten', 'schlafen', 'essen'], instruction: 'Social' },
    { id: 'ty5-c33', type: 'Cloze', question: 'Jeder soll das ___ haben, mitzumachen.', answer: 'Recht', options: ['Recht', 'nein', 'nie'], instruction: 'Social' },
    { id: 'ty5-c34', type: 'Cloze', question: 'Respekt bedeutet, andere zu ___ .', answer: 'akzeptieren', options: ['akzeptieren', 'hassen', 'schlagen'], instruction: 'Social' },
    { id: 'ty5-c35', type: 'Cloze', question: 'Empathie ist, die ___ anderer verstehen zu können.', answer: 'Gefühle', options: ['Gefühle', 'Schuhe', 'Häuser'], instruction: 'Social' },
    { id: 'ty5-c36', type: 'Cloze', question: 'Wir feiern ___ in der Klasse.', answer: 'Geburtstage', options: ['Geburtstage', 'Nächte', 'Regen'], instruction: 'Social' },
    { id: 'ty5-c37', type: 'Cloze', question: 'Weihnachten ist das Fest des ___ .', answer: 'Herzens', options: ['Herzens', 'Tages', 'Woche'], instruction: 'Culture' },
    { id: 'ty5-c38', type: 'Cloze', question: 'Ostern wird mit ___ und Hasen gefeiert.', answer: 'Eiern', options: ['Eiern', 'Autos', 'Hüten'], instruction: 'Culture' },
    { id: 'ty5-c39', type: 'Cloze', question: 'Halloween ist ___ in der Nacht.', answer: 'gruselig', options: ['gruselig', 'gut', 'rosa'], instruction: 'Culture' },
    { id: 'ty5-c40', type: 'Cloze', question: 'Sankt Martin wird mit einem ___ gefeiert.', answer: 'Laternenumzug', options: ['Laternenumzug', 'Auto', 'Schiff'], instruction: 'Culture' },
    { id: 'ty5-c41', type: 'Cloze', question: 'Der 3. Oktober ist der Tag der Deutschen ___ .', answer: 'Einheit', options: ['Einheit', 'Woche', 'Monat'], instruction: 'Culture' },
    { id: 'ty5-c42', type: 'Cloze', question: 'Die deutsche Flagge ist Schwarz-Rot- ___ .', answer: 'Gold', options: ['Gold', 'Gelb', 'Blau'], instruction: 'Culture' },
    { id: 'ty5-c43', type: 'Cloze', question: 'Der Bundeskanzler ___ das Land.', answer: 'leitet', options: ['leitet', 'isst', 'baut'], instruction: 'Society' },
    { id: 'ty5-c44', type: 'Cloze', question: 'Der Bundespräsident wohnt in einem ___ .', answer: 'Schloss', options: ['Schloss', 'Haus', 'Zelt'], instruction: 'Society' },
    { id: 'ty5-c45', type: 'Cloze', question: 'Der Bundestag ist in ___ .', answer: 'Berlin', options: ['Berlin', 'München', 'Hamburg'], instruction: 'Society' },
    { id: 'ty5-c46', type: 'Cloze', question: 'Deutschland ist eine ___ .', answer: 'Demokratie', options: ['Demokratie', 'Monarchie', 'Diktatur'], instruction: 'Society' },
    { id: 'ty5-c47', type: 'Cloze', question: 'Wir haben ___ der Rede.', answer: 'Freiheit', options: ['Freiheit', 'Hunger', 'Angst'], instruction: 'Society' },
    { id: 'ty5-c48', type: 'Cloze', question: 'Man muss ___ Jahre alt sein, um zu wählen.', answer: 'achtzehn', options: ['achtzehn', 'sechs', 'fünf'], instruction: 'Society' },
    { id: 'ty5-c49', type: 'Cloze', question: 'Wir zahlen ___ an den Staat.', answer: 'Steuern', options: ['Steuern', 'Geld', 'Bonbons'], instruction: 'Society' },
    { id: 'ty5-c50', type: 'Cloze', question: 'Die Hauptstadt von Deutschland ist ___ .', answer: 'Berlin', options: ['Berlin', 'London', 'Paris'], instruction: 'Geography' },
    { id: 'ty5-c51', type: 'Cloze', question: 'Deutschland liegt in ___ .', answer: 'Europa', options: ['Europa', 'Afrika', 'Asien'], instruction: 'Geography' },
  ],
  6: [
    { id: 'ty6-c1', type: 'Cloze', question: 'Der Autor benutzt ___ , um Bilder zu erzeugen.', answer: 'Metaphern', options: ['Metaphern', 'Zahlen', 'Farben'], instruction: 'Literature' },
    { id: 'ty6-c2', type: 'Cloze', question: 'Der Protagonist durchläuft eine große ___ .', answer: 'Entwicklung', options: ['Entwicklung', 'Auto', 'Abendessen'], instruction: 'Analysis' },
    { id: 'ty6-c3', type: 'Cloze', question: 'Die Handlung spielt in einem ___ Milieu.', answer: 'traurigen', options: ['traurigen', 'frohen', 'lustigen'], instruction: 'Analysis' },
    { id: 'ty6-c4', type: 'Cloze', question: 'Die Botschaft des Textes ist ___ wichtig.', answer: 'sehr', options: ['sehr', 'nie', 'blau'], instruction: 'Analysis' },
    { id: 'ty6-c5', type: 'Cloze', question: 'Der Dichter benutzt ___ , um Rhythmus zu erzeugen.', answer: 'Reime', options: ['Reime', 'Wörter', 'Gesang'], instruction: 'Poetry' },
    { id: 'ty6-c6', type: 'Cloze', question: 'Die Kurzgeschichte endet mit einer ___ .', answer: 'Überraschung', options: ['Überraschung', 'Anfang', 'Wäsche'], instruction: 'Genre' },
    { id: 'ty6-c7', type: 'Cloze', question: 'Märchen beginnen oft mit "Es war ___ ein Mal".', answer: 'ein', options: ['ein', 'kein', 'nie'], instruction: 'Genre' },
    { id: 'ty6-c8', type: 'Cloze', question: 'Die Fabel hat oft eine ___ Moral.', answer: 'klare', options: ['klare', 'geheime', 'verrückte'], instruction: 'Genre' },
    { id: 'ty6-c9', type: 'Cloze', question: 'Der Roman ist in ___ unterteilt.', answer: 'Kapitel', options: ['Kapitel', 'Seiten', 'Wörter'], instruction: 'Literature' },
    { id: 'ty6-c10', type: 'Cloze', question: 'Die Geschichte wird von einem ___ erzählt.', answer: 'Erzähler', options: ['Erzähler', 'Leser', 'Auto'], instruction: 'Analysis' },
    { id: 'ty6-c11', type: 'Cloze', question: 'Wir analysieren den ___ des Textes.', answer: 'Aufbau', options: ['Aufbau', 'Farbe', 'Gewicht'], instruction: 'Analysis' },
    { id: 'ty6-c12', type: 'Cloze', question: 'Das Thema des Buches ist ___ .', answer: 'Freundschaft', options: ['Freundschaft', 'Essen', 'Wetter'], instruction: 'Analysis' },
    { id: 'ty6-c13', type: 'Cloze', question: 'Die Sprache im Text ist ___ und beschreibend.', answer: 'lebendig', options: ['lebendig', 'langweilig', 'starr'], instruction: 'Analysis' },
    { id: 'ty6-c14', type: 'Cloze', question: 'Wir schauen uns die ___ der Personen an.', answer: 'Beziehungen', options: ['Beziehungen', 'Schuhe', 'Häuser'], instruction: 'Analysis' },
    { id: 'ty6-c15', type: 'Cloze', question: 'Die Milieubeschreibung ist sehr ___ .', answer: 'detailliert', options: ['detailliert', 'oberflächlich', 'blau'], instruction: 'Analysis' },
    { id: 'ty6-c16', type: 'Cloze', question: 'Der Konflikt entsteht, wenn ___ passiert.', answer: 'etwas', options: ['etwas', 'nichts', 'alles'], instruction: 'Analysis' },
    { id: 'ty6-c17', type: 'Cloze', question: 'Der Wendepunkt ist da, wo die Geschichte ___ .', answer: 'umschlägt', options: ['umschlägt', 'stoppt', 'beginnt'], instruction: 'Analysis' },
    { id: 'ty6-c18', type: 'Cloze', question: 'Das Ende bindet einen ___ um die Geschichte.', answer: 'Knoten', options: ['Knoten', 'Schleife', 'Faden'], instruction: 'Analysis' },
    { id: 'ty6-c19', type: 'Cloze', question: 'Wir arbeiten mit ___ im Deutschunterricht.', answer: 'Grammatik', options: ['Grammatik', 'Kochen', 'Sport'], instruction: 'Language' },
    { id: 'ty6-c20', type: 'Cloze', question: 'Ein Nomen ist etwas, vor das man "der" , "die" oder "___" setzen kann.', answer: 'das', options: ['das', 'ein', 'eine'], instruction: 'Grammar' },
    { id: 'ty6-c21', type: 'Cloze', question: 'Ein Verb sagt aus, was man ___ .', answer: 'tut', options: ['tut', 'ist', 'hat'], instruction: 'Grammar' },
    { id: 'ty6-c22', type: 'Cloze', question: 'Ein Adjektiv ___ das Nomen.', answer: 'beschreibt', options: ['beschreibt', 'bewegt', 'löscht'], instruction: 'Grammar' },
    { id: 'ty6-c23', type: 'Cloze', question: 'Adverbien sagen etwas über Zeit und ___ aus.', answer: 'Ort', options: ['Ort', 'Essen', 'Kleidung'], instruction: 'Grammar' },
    { id: 'ty6-c24', type: 'Cloze', question: 'Präpositionen geben ___ Verhältnisse an.', answer: 'räumliche', options: ['räumliche', 'frohe', 'saure'], instruction: 'Grammar' },
    { id: 'ty6-c25', type: 'Cloze', question: 'Pronomen ___ das Nomen.', answer: 'ersetzen', options: ['ersetzen', 'helfen', 'schlagen'], instruction: 'Grammar' },
    { id: 'ty6-c26', type: 'Cloze', question: 'Konjunktionen ___ zwei Sätze.', answer: 'verbinden', options: ['verbinden', 'trennen', 'entfernen'], instruction: 'Grammar' },
    { id: 'ty6-c27', type: 'Cloze', question: 'Interjektionen drücken ein ___ Gefühl aus.', answer: 'starkes', options: ['starkes', 'schwaches', 'blaues'], instruction: 'Grammar' },
    { id: 'ty6-c28', type: 'Cloze', question: 'Man muss ein ___ in den Satz setzen.', answer: 'Komma', options: ['Komma', 'Essen', 'Schuh'], instruction: 'Grammar' },
    { id: 'ty6-c29', type: 'Cloze', question: 'Der Punkt markiert das Ende eines ___ .', answer: 'Satzes', options: ['Satzes', 'Anfangs', 'Mittes'], instruction: 'Grammar' },
    { id: 'ty6-c30', type: 'Cloze', question: 'Das Fragezeichen wird bei einer ___ benutzt.', answer: 'Frage', options: ['Frage', 'Antwort', 'Schrei'], instruction: 'Grammar' },
    { id: 'ty6-c31', type: 'Cloze', question: 'Das Ausrufezeichen wird bei einem ___ benutzt.', answer: 'Schrei', options: ['Schrei', 'Flüstern', 'Seufzer'], instruction: 'Grammar' },
    { id: 'ty6-c32', type: 'Cloze', question: 'Goethe hat viele ___ geschrieben.', answer: 'Gedichte', options: ['Gedichte', 'Zeitungen', 'Briefe'], instruction: 'Literature' },
    { id: 'ty6-c33', type: 'Cloze', question: 'Schiller ist ein ___ Autor.', answer: 'berühmter', options: ['berühmter', 'unbekannter', 'neuer'], instruction: 'Literature' },
    { id: 'ty6-c34', type: 'Cloze', question: 'Kafka schrieb über das ___ Leben.', answer: 'alltägliche', options: ['alltägliche', 'Weltraum', 'Vergangenheit'], instruction: 'Literature' },
    { id: 'ty6-c35', type: 'Cloze', question: 'Brecht war eine ___ Persönlichkeit.', answer: 'inspirierende', options: ['inspirierende', 'langweilige', 'graue'], instruction: 'Literature' },
    { id: 'ty6-c36', type: 'Cloze', question: 'Thomas Mann war ein ___ Autor.', answer: 'moderner', options: ['moderner', 'alter', 'antiker'], instruction: 'Literature' },
    { id: 'ty6-c37', type: 'Cloze', question: 'Wir lesen auch ___ im Deutschunterricht.', answer: 'Nachrichten', options: ['Nachrichten', 'Rezepte', 'Werbung'], instruction: 'Media' },
    { id: 'ty6-c38', type: 'Cloze', question: 'Ein Artikel muss eine gute ___ haben.', answer: 'Überschrift', options: ['Überschrift', 'Hintergrund', 'Seite'], instruction: 'Journalism' },
    { id: 'ty6-c39', type: 'Cloze', question: 'Der Journalist ___ die Quellen.', answer: 'interviewt', options: ['interviewt', 'isst', 'schlägt'], instruction: 'Journalism' },
    { id: 'ty6-c40', type: 'Cloze', question: 'Der Artikel muss ___ in seiner Sprache sein.', answer: 'objektiv', options: ['objektiv', 'subjektiv', 'lustig'], instruction: 'Journalism' },
    { id: 'ty6-c41', type: 'Cloze', question: 'Der Leitartikel drückt die ___ der Zeitung aus.', answer: 'Meinung', options: ['Meinung', 'Zahlen', 'Wetter'], instruction: 'Journalism' },
    { id: 'ty6-c42', type: 'Cloze', question: 'Der Leserbrief wird von einem ___ geschrieben.', answer: 'Leser', options: ['Leser', 'Hund', 'Auto'], instruction: 'Journalism' },
    { id: 'ty6-c43', type: 'Cloze', question: 'Die Rezension ___ ein Buch oder einen Film.', answer: 'beurteilt', options: ['beurteilt', 'kauft', 'verkauft'], instruction: 'Journalism' },
    { id: 'ty6-c44', type: 'Cloze', question: 'Die Reportage ist ein ___ Bericht.', answer: 'Augenzeugenbericht', options: ['Augenzeugenbericht', 'falscher', 'alter'], instruction: 'Journalism' },
    { id: 'ty6-c45', type: 'Cloze', question: 'Das Layout bedeutet die ___ des Textes.', answer: 'Anordnung', options: ['Anordnung', 'Farbe', 'Gewicht'], instruction: 'Journalism' },
    { id: 'ty6-c46', type: 'Cloze', question: 'Bilder in der Zeitung ___ den Text.', answer: 'unterstützen', options: ['unterstützen', 'zerstören', 'entfernen'], instruction: 'Journalism' },
    { id: 'ty6-c47', type: 'Cloze', question: 'Quellenkritik ist heute ___ .', answer: 'wichtig', options: ['wichtig', 'egal', 'dumm'], instruction: 'Journalism' },
    { id: 'ty6-c48', type: 'Cloze', question: 'Soziale Medien ___ Nachrichten schnell.', answer: 'verbreiten', options: ['verbreiten', 'verstecken', 'stoppen'], instruction: 'Media' },
    { id: 'ty6-c49', type: 'Cloze', question: 'Vorsicht vor ___ Nachrichten.', answer: 'falschen', options: ['falschen', 'guten', 'echten'], instruction: 'Media' },
    { id: 'ty6-c50', type: 'Cloze', question: 'Netiquette handelt von ___ Benehmen.', answer: 'gutem', options: ['gutem', 'schlechtem', 'wildem'], instruction: 'Media' },
    { id: 'ty6-c51', type: 'Cloze', question: 'Deutsch ist eine ___ Sprache.', answer: 'welteite', options: ['weltweite', 'kleine', 'tote'], instruction: 'Deutsch' },
  ],
  7: [
    { id: 'ty7-c1', type: 'Cloze', question: 'Die Ideengeschichte untersucht menschliche ___ im Wandel der Zeit.', answer: 'Gedanken', options: ['Gedanken', 'Häuser', 'Geld'], instruction: 'Philosophy' },
    { id: 'ty7-c2', type: 'Cloze', question: 'Philosophen stellen ___ über das Leben.', answer: 'Fragen', options: ['Fragen', 'Antworten', 'Forderungen'], instruction: 'Philosophy' },
    { id: 'ty7-c3', type: 'Cloze', question: 'Ethik handelt davon, was ___ und was schlecht ist.', answer: 'gut', options: ['gut', 'lustig', 'leicht'], instruction: 'Philosophy' },
    { id: 'ty7-c4', type: 'Cloze', question: 'Moral sind die ___ , nach denen wir leben.', answer: 'Regeln', options: ['Regeln', 'Wasser', 'Schuhe'], instruction: 'Philosophy' },
    { id: 'ty7-c5', type: 'Cloze', question: 'Existenz bedeutet menschliche ___ in der Welt.', answer: 'Gegenwart', options: ['Gegenwart', 'Auto', 'Essen'], instruction: 'Philosophy' },
    { id: 'ty7-c6', type: 'Cloze', question: 'Freiheit erfordert auch ___ .', answer: 'Verantwortung', options: ['Verantwortung', 'Geld', 'Bonbons'], instruction: 'Philosophy' },
    { id: 'ty7-c7', type: 'Cloze', question: 'Was ist ___? Das wird oft diskutiert.', answer: 'Wahrheit', options: ['Wahrheit', 'Lüge', 'Farbe'], instruction: 'Philosophy' },
    { id: 'ty7-c8', type: 'Cloze', question: 'Man benutzt ___ , um eine Debatte zu gewinnen.', answer: 'Rhetorik', options: ['Rhetorik', 'Essen', 'Waffen'], instruction: 'Argumentation' },
    { id: 'ty7-c9', type: 'Cloze', question: 'Das Argument muss ___ sein, um zu überzeugen.', answer: 'logisch', options: ['logisch', 'verrückt', 'blau'], instruction: 'Argumentation' },
    { id: 'ty7-c10', type: 'Cloze', question: 'Die Behauptung muss durch Belege ___ werden.', answer: 'gestützt', options: ['gestützt', 'angegriffen', 'entfernt'], instruction: 'Argumentation' },
    { id: 'ty7-c11', type: 'Cloze', question: 'Die Widerlegung fegt das ___ des Gegners weg.', answer: 'Argument', options: ['Argument', 'Kleidung', 'Auto'], instruction: 'Argumentation' },
    { id: 'ty7-c12', type: 'Cloze', question: 'Gegen seine eigene ___ zu reden, ist nicht gut.', answer: 'Überzeugung', options: ['Überzeugung', 'Essen', 'Zeit'], instruction: 'Argumentation' },
    { id: 'ty7-c13', type: 'Cloze', question: 'Objektivität ist ___ in einer Diskussion.', answer: 'wichtig', options: ['wichtig', 'dumm', 'blau'], instruction: 'Argumentation' },
    { id: 'ty7-c14', type: 'Cloze', question: 'Der Absender will den Empfänger ___ .', answer: 'beeinflussen', options: ['beeinflussen', 'essen', 'schlafen'], instruction: 'Argumentation' },
    { id: 'ty7-c15', type: 'Cloze', question: 'Die Sprache kann in einer Rede ___ sein.', answer: 'manipulativ', options: ['manipulativ', 'gut', 'rot'], instruction: 'Argumentation' },
    { id: 'ty7-c16', type: 'Cloze', question: 'Wir analysieren ___ in politischen Reden.', answer: 'rhetorische Mittel', options: ['rhetorische Mittel', 'Essen', 'Schuhe'], instruction: 'Argumentation' },
    { id: 'ty7-c17', type: 'Cloze', question: 'Ethos handelt von der ___ des Sprechers.', answer: 'Glaubwürdigkeit', options: ['Glaubwürdigkeit', 'Geld', 'Aussehen'], instruction: 'Rhetoric' },
    { id: 'ty7-c18', type: 'Cloze', question: 'Logos handelt von logischen ___ .', answer: 'Fakten', options: ['Fakten', 'Verrückten', 'Blauen'], instruction: 'Rhetoric' },
    { id: 'ty7-c19', type: 'Cloze', question: 'Pathos appelliert an die Gefühle der ___ .', answer: 'Zuhörer', options: ['Zuhörer', 'Tiere', 'Autos'], instruction: 'Rhetoric' },
    { id: 'ty7-c20', type: 'Cloze', question: 'Eine Metaphor ist ein ___ Vergleich.', answer: 'bildlicher', options: ['bildlicher', 'dummer', 'blauer'], instruction: 'Language' },
    { id: 'ty7-c21', type: 'Cloze', question: 'Personifikation haucht Dingen ___ Leben ein.', answer: 'menschliches', options: ['menschliches', 'tierisches', 'totes'], instruction: 'Language' },
    { id: 'ty7-c22', type: 'Cloze', question: 'Ironie ist, das ___ von dem zu sagen, was man meint.', answer: 'Gegenteil', options: ['Gegenteil', 'Gleiche', 'Blaues'], instruction: 'Language' },
    { id: 'ty7-c23', type: 'Cloze', question: 'Sarkasmus ist eine ___ Form der Ironie.', answer: 'spöttische', options: ['spöttische', 'sanfte', 'frohe'], instruction: 'Language' },
    { id: 'ty7-c24', type: 'Cloze', question: 'Understatement macht ein Phänomen ___ .', answer: 'kleiner', options: ['kleiner', 'größer', 'blau'], instruction: 'Language' },
    { id: 'ty7-c25', type: 'Cloze', question: 'Hyperbel macht alles ___ als es ist.', answer: 'größer', options: ['größer', 'kleiner', 'blau'], instruction: 'Language' },
    { id: 'ty7-c26', type: 'Cloze', question: 'Wir analysieren den ___ Aufbau des Textes.', answer: 'komplexen', options: ['komplexen', 'einfachen', 'roten'], instruction: 'Analysis' },
    { id: 'ty7-c27', type: 'Cloze', question: 'Literatur spiegelt die ___ Realität wider.', answer: 'historische', options: ['historische', 'zukünftige', 'geheime'], instruction: 'Literature' },
    { id: 'ty7-c28', type: 'Cloze', question: 'Symbole tragen eine ___ Bedeutung.', answer: 'verborgene', options: ['verborgene', 'offensichtliche', 'blaue'], instruction: 'Analysis' },
    { id: 'ty7-c29', type: 'Cloze', question: 'Interpretation erfordert ein ___ Lesen.', answer: 'gründliches', options: ['gründliches', 'schnelles', 'frohes'], instruction: 'Analysis' },
    { id: 'ty7-c30', type: 'Cloze', question: 'Intertextualität ist, wenn Texte aufeinander ___ .', answer: 'verweisen', options: ['verweisen', 'essen', 'zerstören'], instruction: 'Analysis' },
    { id: 'ty7-c31', type: 'Cloze', question: 'Literarische Epochen haben unterschiedliche ___ .', answer: 'Ideale', options: ['Ideale', 'Lebensmittel', 'Schuhe'], instruction: 'Literature' },
    { id: 'ty7-c32', type: 'Cloze', question: 'Die Romantik konzentrierte sich auf ___ und Natur.', answer: 'Gefühle', options: ['Gefühle', 'Maschinen', 'Geld'], instruction: 'Literature' },
    { id: 'ty7-c33', type: 'Cloze', question: 'Realismus versucht, die Welt ___ zu beschreiben, wie sie ist.', answer: 'genau', options: ['genau', 'verrückt', 'nie'], instruction: 'Literature' },
    { id: 'ty7-c34', type: 'Cloze', question: 'Theodor Fontane war eine ___ Figur der deutschen Literatur.', answer: 'zentrale', options: ['zentrale', 'unbedeutende', 'geheime'], instruction: 'Literature' },
    { id: 'ty7-c35', type: 'Cloze', question: 'Gerhart Hauptmann schrieb über soziale ___ .', answer: 'Probleme', options: ['Probleme', 'Zauberer', 'Essen'], instruction: 'Literature' },
    { id: 'ty7-c36', type: 'Cloze', question: 'Thomas Mann ist für seinen ___ Stil bekannt.', answer: 'innovativen', options: ['innovativen', 'harten', 'starren'], instruction: 'Literature' },
    { id: 'ty7-c37', type: 'Cloze', question: 'Wir schauen uns die ___ der Sprache in der Analyse an.', answer: 'Stilistik', options: ['Stilistik', 'Farbe', 'Gewicht'], instruction: 'Analysis' },
    { id: 'ty7-c38', type: 'Cloze', question: 'Die Erzählperspektive kann ___ oder persönlich sein.', answer: 'allwissend', options: ['allwissend', 'blind', 'taub'], instruction: 'Analysis' },
    { id: 'ty7-c39', type: 'Cloze', question: 'Der Erzähler kann ___ oder unzuverlässig sein.', answer: 'zuverlässig', options: ['zuverlässig', 'falsch', 'dick'], instruction: 'Analysis' },
    { id: 'ty7-c40', type: 'Cloze', question: 'Das Umfeld beeinflusst die ___ der Personen.', answer: 'Handlungen', options: ['Handlungen', 'Zähne', 'Schuhe'], instruction: 'Analysis' },
    { id: 'ty7-c41', type: 'Cloze', question: 'Der Subtext des Textes ist das, was nicht ___ dasteht.', answer: 'direkt', options: ['direkt', 'wirklich', 'immer'], instruction: 'Analysis' },
    { id: 'ty7-c42', type: 'Cloze', question: 'Gegensätze erzeugen eine ___ im Text.', answer: 'Spannung', options: ['Spannung', 'Ruhe', 'Schlaf'], instruction: 'Analysis' },
    { id: 'ty7-c43', type: 'Cloze', question: 'Man benutzt ___ am Text, um Zitate zu finden.', answer: 'Belege', options: ['Belege', 'Raten', 'Essen'], instruction: 'Analysis' },
    { id: 'ty7-c44', type: 'Cloze', question: 'Dokumentation ist ___ für die Analyse.', answer: 'notwendig', options: ['notwendig', 'dumm', 'blau'], instruction: 'Analysis' },
    { id: 'ty7-c45', type: 'Cloze', question: 'Man muss seine Interpretation ___ können.', answer: 'begründen', options: ['begründen', 'vergessen', 'verlieren'], instruction: 'Analysis' },
    { id: 'ty7-c46', type: 'Cloze', question: 'Die großen Linien der Literaturgeschichte sind wichtig zu ___ .', answer: 'kennen', options: ['kennen', 'Schuhe', 'Häuser'], instruction: 'Literature' },
    { id: 'ty7-c47', type: 'Cloze', question: 'Man vergleicht Texte aus ___ Epochen.', answer: 'verschiedenen', options: ['verschiedenen', 'gleichen', 'roten'], instruction: 'Literature' },
    { id: 'ty7-c48', type: 'Cloze', question: 'Die Botschaft geht über ___ eigene Zeit hinaus.', answer: 'ihre', options: ['ihre', 'nie', 'immer'], instruction: 'Literature' },
    { id: 'ty7-c49', type: 'Cloze', question: 'Klassische Autoren sind ___ in der Schule.', answer: 'Pflicht', options: ['Pflicht', 'verboten', 'lustig'], instruction: 'Literature' },
    { id: 'ty7-c50', type: 'Cloze', question: 'Lesen gibt einen ___ in die Welt.', answer: 'Einblick', options: ['Einblick', 'Unwissenheit', 'Schuh'], instruction: 'Message' },
    { id: 'ty7-c51', type: 'Cloze', question: 'Lesen lässt einen die Welt besser ___ .', answer: 'verstehen', options: ['verstehen', 'sehen', 'essen'], instruction: 'Philosophy' },
  ],
  8: [
    { id: 'ty8-c1', type: 'Cloze', question: 'Identität ist ein zentrales ___ in der modernen Literatur.', answer: 'Thema', options: ['Thema', 'Unbekanntes', 'Blaues'], instruction: 'Theme' },
    { id: 'ty8-c2', type: 'Cloze', question: 'Wer bin ich? Das ist eine ___ Frage.', answer: 'existenzielle', options: ['existenzielle', 'dumme', 'leichte'], instruction: 'Theme' },
    { id: 'ty8-c3', type: 'Cloze', question: 'Globalisierung macht die Welt ___ für uns.', answer: 'kleiner', options: ['kleiner', 'größer', 'blau'], instruction: 'Society' },
    { id: 'ty8-c4', type: 'Cloze', question: 'Kulturclashes können ___ und Konflikte erzeugen.', answer: 'Missverständnisse', options: ['Missverständnisse', 'Hass', 'Krieg'], instruction: 'Society' },
    { id: 'ty8-c5', type: 'Cloze', question: 'Die Macht der Medien ist heute ___ .', answer: 'groß', options: ['groß', 'klein', 'blau'], instruction: 'Society' },
    { id: 'ty8-c6', type: 'Cloze', question: 'Digitale Alphabetisierung handelt von ___ im Netz.', answer: 'Benehmen', options: ['Benehmen', 'Essen', 'Schlafen'], instruction: 'Society' },
    { id: 'ty8-c7', type: 'Cloze', question: 'Quellenkritik ist im Internet ___ .', answer: 'entscheidend', options: ['entscheidend', 'egal', 'lustig'], instruction: 'Society' },
    { id: 'ty8-c8', type: 'Cloze', question: 'Fake News können unserer Demokratie ___ .', answer: 'schaden', options: ['schaden', 'helfen', 'bauen'], instruction: 'Society' },
    { id: 'ty8-c9', type: 'Cloze', question: 'Soziale Medien schaffen ___ Gemeinschaften.', answer: 'digitale', options: ['digitale', 'physische', 'keine'], instruction: 'Society' },
    { id: 'ty8-c10', type: 'Cloze', question: 'Personenbezogene Daten müssen im Netz ___ werden.', answer: 'geschützt', options: ['geschützt', 'geteilt', 'verkauft'], instruction: 'Society' },
    { id: 'ty8-c11', type: 'Cloze', question: 'Algorithmen steuern, was wir im Netz ___ .', answer: 'sehen', options: ['sehen', 'essen', 'hören'], instruction: 'Society' },
    { id: 'ty8-c12', type: 'Cloze', question: 'Echokammern verstärken unsere eigenen ___ .', answer: 'Meinungen', options: ['Meinungen', 'Schuhe', 'Häuser'], instruction: 'Society' },
    { id: 'ty8-c13', type: 'Cloze', question: 'Kritisches Denken ist ein ___ gegen Manipulation.', answer: 'Schutzschild', options: ['Schutzschild', 'Angriff', 'Loch'], instruction: 'Society' },
    { id: 'ty8-c14', type: 'Cloze', question: 'Werbung versucht, Bedürfnisse bei uns zu ___ .', answer: 'wecken', options: ['wecken', 'entfernen', 'befriedigen'], instruction: 'Society' },
    { id: 'ty8-c15', type: 'Cloze', question: 'Branding ist wichtig für ___ Unternehmen.', answer: 'moderne', options: ['moderne', 'alte', 'kleine'], instruction: 'Economy' },
    { id: 'ty8-c16', type: 'Cloze', question: 'Konsumismus prägt unsere ___ Gesellschaft.', answer: 'westliche', options: ['westliche', 'wilde', 'ruhige'], instruction: 'Society' },
    { id: 'ty8-c17', type: 'Cloze', question: 'Nachhaltigkeit ist eine ___ Notwendigkeit.', answer: 'globale', options: ['globale', 'lokale', 'blaue'], instruction: 'Environment' },
    { id: 'ty8-c18', type: 'Cloze', question: 'Klimawandel erfordert jetzt ___ Handeln.', answer: 'politisches', options: ['politisches', 'kein', 'langsames'], instruction: 'Politics' },
    { id: 'ty8-c19', type: 'Cloze', question: 'Der Einzelne hat eine ___ gegenüber der Umwelt.', answer: 'Verantwortung', options: ['Verantwortung', 'Essen', 'Kleidung'], instruction: 'Ethics' },
    { id: 'ty8-c20', type: 'Cloze', question: 'Die Gemeinschaft muss sich um die ___ kümmern.', answer: 'Schwächsten', options: ['Schwächsten', 'Ignoranz', 'Schlagen'], instruction: 'Ethics' },
    { id: 'ty8-c21', type: 'Cloze', question: 'Gerechtigkeit ist ein ___ in der Gesellschaft.', answer: 'Grundprinzip', options: ['Grundprinzip', 'Spiel', 'Essen'], instruction: 'Politics' },
    { id: 'ty8-c22', type: 'Cloze', question: 'Gleichheit vor dem Gesetz gilt für ___ .', answer: 'alle', options: ['alle', 'niemanden', 'wenige'], instruction: 'Politics' },
    { id: 'ty8-c23', type: 'Cloze', question: 'Menschenrechte müssen überall ___ werden.', answer: 'geachtet', options: ['geachtet', 'gebrochen', 'vergessen'], instruction: 'Politics' },
    { id: 'ty8-c24', type: 'Cloze', question: 'Demokratie erfordert ___ Bürger.', answer: 'aktive', options: ['aktive', 'passive', 'schlafende'], instruction: 'Society' },
    { id: 'ty8-c25', type: 'Cloze', question: 'Meinungsfreiheit hat auch ihre ___ .', answer: 'Grenzen', options: ['Grenzen', 'Straßen', 'Schuhe'], instruction: 'Law' },
    { id: 'ty8-c26', type: 'Cloze', question: 'Hassrede ist in der öffentlichen Debatte ___ .', answer: 'inakzeptabel', options: ['inakzeptabel', 'willkommen', 'lustig'], instruction: 'Social' },
    { id: 'ty8-c27', type: 'Cloze', question: 'Toleranz bedeutet, Unterschiede zu ___ .', answer: 'akzeptieren', options: ['akzeptieren', 'entfernen', 'hassen'], instruction: 'Social' },
    { id: 'ty8-c28', type: 'Cloze', question: 'Solidarität bindet ___ aneinander.', answer: 'Menschen', options: ['Menschen', 'Autos', 'Häuser'], instruction: 'Social' },
    { id: 'ty8-c29', type: 'Cloze', question: 'Man muss ___ in der Gesellschaft bekämpfen.', answer: 'Ungleichheit', options: ['Ungleichheit', 'Gleichheit', 'Essen'], instruction: 'Politics' },
    { id: 'ty8-c30', type: 'Cloze', question: 'Bildung ist der Weg in eine ___ Zukunft.', answer: 'bessere', options: ['bessere', 'schlechtere', 'blaue'], instruction: 'Future' },
    { id: 'ty8-c31', type: 'Cloze', question: 'Arbeit gibt ___ und Sinn.', answer: 'Inhalt', options: ['Inhalt', 'Essen', 'Kleidung'], instruction: 'Society' },
    { id: 'ty8-c32', type: 'Cloze', question: 'Der Wohlfahrtsstaat ___ die Sicherheit der Bürger.', answer: 'sichert', options: ['sichert', 'nimmt weg', 'zerstört'], instruction: 'Economy' },
    { id: 'ty8-c33', type: 'Cloze', question: 'Die Wirtschaft muss ___ sein, um zu wachsen.', answer: 'stabil', options: ['stabil', 'nervös', 'rot'], instruction: 'Economy' },
    { id: 'ty8-c34', type: 'Cloze', question: 'Investitionen schaffen ___ im Land.', answer: 'Arbeitsplätze', options: ['Arbeitsplätze', 'Krieg', 'Krankheit'], instruction: 'Economy' },
    { id: 'ty8-c35', type: 'Cloze', question: 'Technologie verändert unser ___ jeden Tag.', answer: 'Leben', options: ['Leben', 'Schuhe', 'Häuser'], instruction: 'Technology' },
    { id: 'ty8-c36', type: 'Cloze', question: 'Innovation treibt die ___ voran.', answer: 'Entwicklung', options: ['Entwicklung', 'Auto', 'Essen'], instruction: 'Science' },
    { id: 'ty8-c37', type: 'Cloze', question: 'Wissenschaft sucht nach ___ über die Welt.', answer: 'Erkenntnis', options: ['Erkenntnis', 'Gold', 'Essen'], instruction: 'Science' },
    { id: 'ty8-c38', type: 'Cloze', question: 'Das Labor ist der Ort des ___ .', answer: 'Experiments', options: ['Experiments', 'Küche', 'Tanz'], instruction: 'Science' },
    { id: 'ty8-c39', type: 'Cloze', question: 'Die Hypothese muss an der Realität ___ werden.', answer: 'geprüft', options: ['geprüft', 'vergessen', 'verloren'], instruction: 'Science' },
    { id: 'ty8-c40', type: 'Cloze', question: 'Ergebnisse müssen für andere ___ sein.', answer: 'zugänglich', options: ['zugänglich', 'geheim', 'gefährlich'], instruction: 'Science' },
    { id: 'ty8-c41', type: 'Cloze', question: 'Ethik in der Forschung ist ___ wichtig.', answer: 'sehr', options: ['sehr', 'nie', 'blau'], instruction: 'Ethics' },
    { id: 'ty8-c42', type: 'Cloze', question: 'Die Zukunft wird durch unsere heutigen Entscheidungen ___ .', answer: 'geprägt', options: ['geprägt', 'unabhängig', 'blau'], instruction: 'Thought' },
    { id: 'ty8-c43', type: 'Cloze', question: 'Man sollte aus der Geschichte ___ .', answer: 'lernen', options: ['lernen', 'Essen', 'Schuhe'], instruction: 'Thought' },
    { id: 'ty8-c44', type: 'Cloze', question: 'Erfahrung ist der beste ___ .', answer: 'Lehrer', options: ['Lehrer', 'Schüler', 'Buch'], instruction: 'Thought' },
    { id: 'ty8-c45', type: 'Cloze', question: 'Weisheit kommt mit ___ und Alter.', answer: 'Einsicht', options: ['Einsicht', 'Zähnen', 'Haaren'], instruction: 'Thought' },
    { id: 'ty8-c46', type: 'Cloze', question: 'Veränderung tut gut, sagt ein ___ Sprichwort.', answer: 'altes', options: ['altes', 'neues', 'verrücktes'], instruction: 'Thought' },
    { id: 'ty8-c47', type: 'Cloze', question: 'Die Hoffnung stirbt ___ .', answer: 'zuletzt', options: ['zuletzt', 'gar nicht', 'bald'], instruction: 'Thought' },
    { id: 'ty8-c48', type: 'Cloze', question: 'Glück ist, sich selbst zu ___ .', answer: 'finden', options: ['finden', 'verlieren', 'verkaufen'], instruction: 'Thought' },
    { id: 'ty8-c49', type: 'Cloze', question: 'Liebe besiegt ___ alles.', answer: 'fast', options: ['fast', 'nie', 'immer'], instruction: 'Thought' },
    { id: 'ty8-c50', type: 'Cloze', question: 'Ende für ___ Stufe.', answer: 'diese', options: ['diese', 'eine', 'das'], instruction: 'Message' },
  ],
  9: [
    { id: 'ty9-c1', type: 'Cloze', question: 'Existentialismus fokussiert auf die ___ menschliche Wahl.', answer: 'freie', options: ['freie', 'erzwungene', 'keine'], instruction: 'Philosophy' },
    { id: 'ty9-c2', type: 'Cloze', question: 'Sartre meinte, der Mensch sei zur Freiheit ___ .', answer: 'verdammt', options: ['verdammt', 'erwählt', 'geboren'], instruction: 'Philosophy' },
    { id: 'ty9-c3', type: 'Cloze', question: 'Nihilismus behauptet, das Leben sei ___ Sinn.', answer: 'ohne', options: ['ohne', 'mit', 'voller'], instruction: 'Philosophy' },
    { id: 'ty9-c4', type: 'Cloze', question: 'Absurdismus sieht einen ___ zwischen Mensch und Welt.', answer: 'Konflikt', options: ['Konflikt', 'Einklang', 'Frieden'], instruction: 'Philosophy' },
    { id: 'ty9-c5', type: 'Cloze', question: 'Stoizismus lehrt uns, das Unvermeidliche zu ___ .', answer: 'akzeptieren', options: ['akzeptieren', 'bekämpfen', 'fliehen'], instruction: 'Philosophy' },
    { id: 'ty9-c6', type: 'Cloze', question: 'Epikureismus sucht ___ und Abwesenheit von Schmerz.', answer: 'Lust', options: ['Lust', 'Leiden', 'Arbeit'], instruction: 'Philosophy' },
    { id: 'ty9-c7', type: 'Cloze', question: 'Rationalismus baut auf ___ als Quelle des Wissens.', answer: 'Vernunft', options: ['Vernunft', 'Gefühl', 'Glauben'], instruction: 'Philosophy' },
    { id: 'ty9-c8', type: 'Cloze', question: 'Empirismus gewichtet ___ und Beobachtung am höchsten.', answer: 'Erfahrung', options: ['Erfahrung', 'Denken', 'Traum'], instruction: 'Philosophy' },
    { id: 'ty9-c9', type: 'Cloze', question: 'Phänomenologie untersucht die ___ der Dinge.', answer: 'Erscheinung', options: ['Erscheinung', 'Kern', 'Preis'], instruction: 'Philosophy' },
    { id: 'ty9-c10', type: 'Cloze', question: 'Ontologie ist die Lehre vom ___ .', answer: 'Sein', options: ['Sein', 'Wissen', 'Moral'], instruction: 'Philosophy' },
    { id: 'ty9-c11', type: 'Cloze', question: 'Epistemologie handelt von der Natur der ___ .', answer: 'Erkenntnis', options: ['Erkenntnis', 'Körper', 'Seele'], instruction: 'Philosophy' },
    { id: 'ty9-c12', type: 'Cloze', question: 'Dualismus unterscheidet Geist vom ___ .', answer: 'Körper', options: ['Körper', 'Haar', 'Fuß'], instruction: 'Philosophy' },
    { id: 'ty9-c13', type: 'Cloze', question: 'Determinismus behauptet, alles sei im Voraus ___ .', answer: 'bestimmt', options: ['bestimmt', 'zufällig', 'versteckt'], instruction: 'Philosophy' },
    { id: 'ty9-c14', type: 'Cloze', question: 'Dialektik arbeitet mit ___ und Synthese.', answer: 'Antithese', options: ['Antithese', 'Geschichte', 'Essen'], instruction: 'Philosophy' },
    { id: 'ty9-c15', type: 'Cloze', question: 'Hermeneutik ist die Wissenschaft der ___ .', answer: 'Auslegung', options: ['Auslegung', 'Schöpfung', 'Verkauf'], instruction: 'Philosophy' },
    { id: 'ty9-c16', type: 'Cloze', question: 'Kants kategorischer Imperativ handelt von ___ Handeln.', answer: 'allgemeingültigem', options: ['allgemeingültigem', 'persönlichem', 'geheimem'], instruction: 'Philosophy' },
    { id: 'ty9-c17', type: 'Cloze', question: 'Utilitarismus sucht das größte ___ für die meisten Menschen.', answer: 'Glück', options: ['Glück', 'Geld', 'Macht'], instruction: 'Philosophy' },
    { id: 'ty9-c18', type: 'Cloze', question: 'Tugendethik setzt auf Charakter und ___ .', answer: 'Moral', options: ['Moral', 'Aussehen', 'Reichtum'], instruction: 'Philosophy' },
    { id: 'ty9-c19', type: 'Cloze', question: 'Soziobiologie betrachtet den ___ Untergrund des Verhaltens.', answer: 'biologischen', options: ['biologischen', 'kulturellen', 'wirtschaftlichen'], instruction: 'Science' },
    { id: 'ty9-c20', type: 'Cloze', question: 'Psychoanalyse taucht ins ___ ein.', answer: 'Unbewusste', options: ['Unbewusste', 'Bewusste', 'Physische'], instruction: 'Psychology' },
    { id: 'ty9-c21', type: 'Cloze', question: 'Behaviorismus untersucht ___ Verhalten.', answer: 'beobachtbares', options: ['beobachtbares', 'verborgenes', 'inneres'], instruction: 'Psychology' },
    { id: 'ty9-c22', type: 'Cloze', question: 'Kognitive Psychologie interessiert sich für ___ Prozesse.', answer: 'mentale', options: ['mentale', 'physische', 'soziale'], instruction: 'Psychology' },
    { id: 'ty9-c23', type: 'Cloze', question: 'Soziologie untersucht ___ in der Gesellschaft.', answer: 'Strukturen', options: ['Strukturen', 'Individuen', 'Tiere'], instruction: 'Sociology' },
    { id: 'ty9-c24', type: 'Cloze', question: 'Strukturalismus interessiert sich für ___ Muster.', answer: 'zugrundeliegende', options: ['zugrundeliegende', 'sichtbare', 'neue'], instruction: 'Sociology' },
    { id: 'ty9-c25', type: 'Cloze', question: 'Postmodernismus ___ die großen Erzählungen.', answer: 'lehnt ab', options: ['lehnt ab', 'begrüßt', 'stützt'], instruction: 'Philosophy' },
    { id: 'ty9-c26', type: 'Cloze', question: 'Dekonstruktion öffnet für ___ Bedeutungen.', answer: 'mehrdeutige', options: ['mehrdeutige', 'eindeutige', 'keine'], instruction: 'Philosophy' },
    { id: 'ty9-c27', type: 'Cloze', question: 'Globalisierung schafft eine ___ Welt.', answer: 'vernetzte', options: ['vernetzte', 'isolierte', 'geschlossene'], instruction: 'Society' },
    { id: 'ty9-c28', type: 'Cloze', question: 'Postkolonialismus blickt auf die ___ der Kolonialisierung.', answer: 'Folgen', options: ['Folgen', 'Vorteile', 'Anfang'], instruction: 'History' },
    { id: 'ty9-c29', type: 'Cloze', question: 'Feminismus kämpft für ___ zwischen den Geschlechtern.', answer: 'Gleichberechtigung', options: ['Gleichberechtigung', 'Unterschied', 'Kampf'], instruction: 'Society' },
    { id: 'ty9-c30', type: 'Cloze', question: 'Ökokritik analysiert das Verhältnis von ___ zur Natur.', answer: 'Literatur', options: ['Literatur', 'Auto', 'Essen'], instruction: 'Analysis' },
    { id: 'ty9-c31', type: 'Cloze', question: 'Dystopie beschreibt eine ___ Zukunft.', answer: 'erschreckende', options: ['erschreckende', 'glückliche', 'helle'], instruction: 'Genre' },
    { id: 'ty9-c32', type: 'Cloze', question: 'Utopie ist die ___ Gesellschaft.', answer: 'perfekte', options: ['perfekte', 'zerbrochene', 'schwarze'], instruction: 'Genre' },
    { id: 'ty9-c33', type: 'Cloze', question: 'Satire nutzt ___ , um zu kritisieren.', answer: 'Humor', options: ['Humor', 'Gewalt', 'Drohungen'], instruction: 'Genre' },
    { id: 'ty9-c34', type: 'Cloze', question: 'Ironie ist ein ___ Werkzeug in der Literatur.', answer: 'effektives', options: ['effektives', 'nutzloses', 'langweiliges'], instruction: 'Language' },
    { id: 'ty9-c35', type: 'Cloze', question: 'Narratologie ist die Lehre von ___ .', answer: 'Erzählungen', options: ['Erzählungen', 'Wörtern', 'Reimen'], instruction: 'Analysis' },
    { id: 'ty9-c36', type: 'Cloze', question: 'Diskurs ist die ___ , wie man über Dinge spricht.', answer: 'Art', options: ['Art', 'Tag', 'Woche'], instruction: 'Language' },
    { id: 'ty9-c37', type: 'Cloze', question: 'Ideologiekritik enthüllt die ___ hinter dem Text.', answer: 'Macht', options: ['Macht', 'Geschichte', 'Essen'], instruction: 'Analysis' },
    { id: 'ty9-c38', type: 'Cloze', question: 'Der Kanon sammelt die ___ Werke.', answer: 'geschätztesten', options: ['geschätztesten', 'vergessensten', 'verrücktesten'], instruction: 'Literature' },
    { id: 'ty9-c39', type: 'Cloze', question: 'Die Rolle der Literatur wird in der Gesellschaft ___ diskutiert.', answer: 'kontinuierlich', options: ['kontinuierlich', 'nie', 'selten'], instruction: 'Literature' },
    { id: 'ty9-c40', type: 'Cloze', question: 'Kunst sollte die Welt ___ , meinten manche.', answer: 'verändern', options: ['verändern', 'verzieren', 'bewahren'], instruction: 'Art' },
    { id: 'ty9-c41', type: 'Cloze', question: 'L\'art pour l\'art ist Kunst um der ___ willen.', answer: 'Kunst', options: ['Kunst', 'meinet', 'deinet'], instruction: 'Art' },
    { id: 'ty9-c42', type: 'Cloze', question: 'Ästhetik ist die Lehre vom ___ .', answer: 'Schönen', options: ['Schönen', 'Hässlichen', 'Wilden'], instruction: 'Art' },
    { id: 'ty9-c43', type: 'Cloze', question: 'Moderne brach mit den ___ Formen.', answer: 'traditionellen', options: ['traditionellen', 'neuen', 'wilden'], instruction: 'Literature' },
    { id: 'ty9-c44', type: 'Cloze', question: 'Das absurde Theater zeigt die ___ des Lebens.', answer: 'Sinnlosigkeit', options: ['Sinnlosigkeit', 'Freude', 'Schönheit'], instruction: 'Literature' },
    { id: 'ty9-c45', type: 'Cloze', question: 'Magischer Realismus mischt ___ und Magie.', answer: 'Alltag', options: ['Alltag', 'Weltraum', 'Vergangenheit'], instruction: 'Literature' },
    { id: 'ty9-c46', type: 'Cloze', question: 'Minimalismus nutzt ___ Wörter.', answer: 'wenige', options: ['wenige', 'viele', 'lange'], instruction: 'Literature' },
    { id: 'ty9-c47', type: 'Cloze', question: 'Show, don\'t tell ist ein ___ Rat beim Schreiben.', answer: 'wichtiger', options: ['wichtiger', 'dummer', 'egaler'], instruction: 'Writing' },
    { id: 'ty9-c48', type: 'Cloze', question: 'Schreiben erfordert ___ und Fleiß.', answer: 'Geduld', options: ['Geduld', 'Tempo', 'Geld'], instruction: 'Writing' },
    { id: 'ty9-c49', type: 'Cloze', question: 'Redigieren ist ___ für das Endergebnis.', answer: 'entscheidend', options: ['entscheidend', 'egal', 'lustig'], instruction: 'Writing' },
    { id: 'ty9-c50', type: 'Cloze', question: 'Lesen schenkt uns ___ Leben.', answer: 'viele', options: ['viele', 'eins', 'keine'], instruction: 'Philosophy' },
    { id: 'ty9-c51', type: 'Cloze', question: 'Viel Glück bei der ___ !', answer: 'Prüfung', options: ['Prüfung', 'Arbeit', 'Reise'], instruction: 'Message' },
  ],
};
