/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const TYSK_CLOZE_P1: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'ty0-c1', type: 'Cloze', question: 'Ich ___ einen Hund.', answer: 'sehe', options: ['sehe', 'esse', 'schlafe'], instruction: 'Action' },
    { id: 'ty0-c2', type: 'Cloze', question: 'Der Hund sagt ___.', answer: 'wau', options: ['wau', 'miau', 'oink'], instruction: 'Sound' },
    { id: 'ty0-c3', type: 'Cloze', question: 'Meine Mama ist ___.', answer: 'nett', options: ['nett', 'blau', 'Auto'], instruction: 'Description' },
    { id: 'ty0-c4', type: 'Cloze', question: 'Der Apfel ist ___.', answer: 'rot', options: ['rot', 'blau', 'schwarz'], instruction: 'Color' },
    { id: 'ty0-c5', type: 'Cloze', question: 'Die Sonne ist ___.', answer: 'gelb', options: ['gelb', 'grün', 'lila'], instruction: 'Color' },
    { id: 'ty0-c6', type: 'Cloze', question: 'Der Himmel ist ___.', answer: 'blau', options: ['blau', 'rot', 'weiß'], instruction: 'Color' },
    { id: 'ty0-c7', type: 'Cloze', question: 'Das Gras ist ___.', answer: 'grün', options: ['grün', 'gelb', 'braun'], instruction: 'Color' },
    { id: 'ty0-c8', type: 'Cloze', question: 'Ich ___ ein Eis.', answer: 'esse', options: ['esse', 'lese', 'fahre'], instruction: 'Action' },
    { id: 'ty0-c9', type: 'Cloze', question: 'Die Katze ___ auf dem Sofa.', answer: 'schläft', options: ['schläft', 'singt', 'tanzt'], instruction: 'Action' },
    { id: 'ty0-c10', type: 'Cloze', question: 'Ich ___ zur Schule.', answer: 'gehe', options: ['gehe', 'esse', 'trinke'], instruction: 'Action' },
    { id: 'ty0-c11', type: 'Cloze', question: 'Ein kleines ___ Milch.', answer: 'Glas', options: ['Glas', 'Buch', 'Schuh'], instruction: 'Quantity' },
    { id: 'ty0-c12', type: 'Cloze', question: 'Das Haus ist ___.', answer: 'groß', options: ['groß', 'klein', 'blau'], instruction: 'Description' },
    { id: 'ty0-c13', type: 'Cloze', question: 'Ich habe eine ___ Katze.', answer: 'kleine', options: ['kleine', 'große', 'rote'], instruction: 'Description' },
    { id: 'ty0-c14', type: 'Cloze', question: 'Die ___ ist schön.', answer: 'Blume', options: ['Blume', 'Auto', 'Haus'], instruction: 'Noun' },
    { id: 'ty0-c15', type: 'Cloze', question: 'Der Vogel ___ am Himmel.', answer: 'fliegt', options: ['fliegt', 'schwimmt', 'kriecht'], instruction: 'Action' },
    { id: 'ty0-c16', type: 'Cloze', question: 'Der Fisch ___ im Wasser.', answer: 'schwimmt', options: ['schwimmt', 'fliegt', 'geht'], instruction: 'Action' },
    { id: 'ty0-c17', type: 'Cloze', question: 'Ich ___ dich sehr.', answer: 'liebe', options: ['liebe', 'hasse', 'sehe'], instruction: 'Feeling' },
    { id: 'ty0-c18', type: 'Cloze', question: 'Hallo, ___ geht es dir?', answer: 'wie', options: ['wie', 'warum', 'wo'], instruction: 'Question' },
    { id: 'ty0-c19', type: 'Cloze', question: 'Mir geht es ___ , danke.', answer: 'gut', options: ['gut', 'schlecht', 'blau'], instruction: 'Greeting' },
    { id: 'ty0-c20', type: 'Cloze', question: 'Eins, zwei, ___.', answer: 'drei', options: ['drei', 'vier', 'fünf'], instruction: 'Number' },
    { id: 'ty0-c21', type: 'Cloze', question: 'Vier, fünf, ___.', answer: 'sechs', options: ['sechs', 'zwei', 'acht'], instruction: 'Number' },
    { id: 'ty0-c22', type: 'Cloze', question: 'Sieben, acht, ___.', answer: 'neun', options: ['neun', 'eins', 'null'], instruction: 'Number' },
    { id: 'ty0-c23', type: 'Cloze', question: 'Zehn, elf, ___.', answer: 'zwölf', options: ['zwölf', 'fünf', 'zwanzig'], instruction: 'Number' },
    { id: 'ty0-c24', type: 'Cloze', question: 'Der Hase hat ___ Ohren.', answer: 'lange', options: ['lange', 'kurze', 'runde'], instruction: 'Body' },
    { id: 'ty0-c25', type: 'Cloze', question: 'Der Elefant ist ___.', answer: 'grau', options: ['grau', 'rosa', 'blau'], instruction: 'Color' },
    { id: 'ty0-c26', type: 'Cloze', question: 'Das Schwein ist ___.', answer: 'rosa', options: ['rosa', 'blau', 'braun'], instruction: 'Color' },
    { id: 'ty0-c27', type: 'Cloze', question: 'Der Bär ist ___.', answer: 'braun', options: ['braun', 'weiß', 'lila'], instruction: 'Color' },
    { id: 'ty0-c28', type: 'Cloze', question: 'Der Eisbär ist ___.', answer: 'weiß', options: ['weiß', 'schwarz', 'blau'], instruction: 'Color' },
    { id: 'ty0-c29', type: 'Cloze', question: 'Der Tiger hat ___.', answer: 'Streifen', options: ['Streifen', 'Punkte', 'Karos'], instruction: 'Pattern' },
    { id: 'ty0-c30', type: 'Cloze', question: 'Der Leopard hat ___.', answer: 'Punkte', options: ['Punkte', 'Streifen', 'Karos'], instruction: 'Pattern' },
    { id: 'ty0-c31', type: 'Cloze', question: 'Das ist ___ Kuchen.', answer: 'ein', options: ['ein', 'eine', 'der'], instruction: 'Article' },
    { id: 'ty0-c32', type: 'Cloze', question: 'Das ist ___ Apfel.', answer: 'ein', options: ['ein', 'eine', 'das'], instruction: 'Article' },
    { id: 'ty0-c33', type: 'Cloze', question: 'Das sind ___ Kinder.', answer: 'viele', options: ['viele', 'eine', 'der'], instruction: 'Quantity' },
    { id: 'ty0-c34', type: 'Cloze', question: 'Ich ___ ein Buch.', answer: 'habe', options: ['habe', 'bin', 'hast'], instruction: 'Verb haben' },
    { id: 'ty0-c35', type: 'Cloze', question: 'Du ___ ein Fahrrad.', answer: 'hast', options: ['hast', 'habe', 'ist'], instruction: 'Verb haben' },
    { id: 'ty0-c36', type: 'Cloze', question: 'Er ___ einen Hund.', answer: 'hat', options: ['hat', 'ist', 'hast'], instruction: 'Verb haben' },
    { id: 'ty0-c37', type: 'Cloze', question: 'Sie ___ eine Puppe.', answer: 'hat', options: ['hat', 'habe', 'hast'], instruction: 'Verb haben' },
    { id: 'ty0-c38', type: 'Cloze', question: 'Ich ___ froh.', answer: 'bin', options: ['bin', 'habe', 'bist'], instruction: 'Verb sein' },
    { id: 'ty0-c39', type: 'Cloze', question: 'Du ___ nett.', answer: 'bist', options: ['bist', 'bin', 'ist'], instruction: 'Verb sein' },
    { id: 'ty0-c40', type: 'Cloze', question: 'Er ___ groß.', answer: 'ist', options: ['ist', 'bist', 'bin'], instruction: 'Verb sein' },
    { id: 'ty0-c41', type: 'Cloze', question: 'Sie ___ klein.', answer: 'ist', options: ['ist', 'hast', 'habe'], instruction: 'Verb sein' },
    { id: 'ty0-c42', type: 'Cloze', question: 'Wir ___ müde.', answer: 'sind', options: ['sind', 'seid', 'ist'], instruction: 'Verb sein' },
    { id: 'ty0-c43', type: 'Cloze', question: 'Ihr ___ lustig.', answer: 'seid', options: ['seid', 'sind', 'ist'], instruction: 'Verb sein' },
    { id: 'ty0-c44', type: 'Cloze', question: 'Sie ___ ruhig.', answer: 'sind', options: ['sind', 'ist', 'seid'], instruction: 'Verb sein' },
    { id: 'ty0-c45', type: 'Cloze', question: 'Der ___ ist auf dem Tisch.', answer: 'Stift', options: ['Stift', 'Brot', 'Sonne'], instruction: 'School' },
    { id: 'ty0-c46', type: 'Cloze', question: 'Ich zeichne auf ___.', answer: 'Papier', options: ['Papier', 'Wand', 'Bett'], instruction: 'School' },
    { id: 'ty0-c47', type: 'Cloze', question: 'Ich höre dem ___ zu.', answer: 'Lehrer', options: ['Lehrer', 'Ball', 'Tisch'], instruction: 'School' },
    { id: 'ty0-c48', type: 'Cloze', question: 'Ich spiele auf dem ___.', answer: 'Pausenhof', options: ['Pausenhof', 'Klassenzimmer', 'Haus'], instruction: 'School' },
    { id: 'ty0-c49', type: 'Cloze', question: 'Danke ___ deine Hilfe.', answer: 'für', options: ['für', 'mit', 'bei'], instruction: 'Polite' },
    { id: 'ty0-c50', type: 'Cloze', question: 'Auf ___ !', answer: 'Wiedersehen', options: ['Wiedersehen', 'Tag', 'Abend'], instruction: 'Greeting' },
    { id: 'ty0-c51', type: 'Cloze', question: 'Bis ___ !', answer: 'bald', options: ['bald', 'immer', 'damals'], instruction: 'Greeting' },
  ],
  1: [
    { id: 'ty1-c1', type: 'Cloze', question: 'Die Sonne ___ am Himmel.', answer: 'scheint', options: ['scheint', 'regnet', 'weht'], instruction: 'Weather' },
    { id: 'ty1-c2', type: 'Cloze', question: 'Es ___ heute sehr stark.', answer: 'regnet', options: ['regnet', 'scheint', 'lacht'], instruction: 'Weather' },
    { id: 'ty1-c3', type: 'Cloze', question: 'Der Wind ___ durch die Bäume.', answer: 'weht', options: ['weht', 'schläft', 'liest'], instruction: 'Weather' },
    { id: 'ty1-c4', type: 'Cloze', question: 'Ich ___ einen blauen Ball.', answer: 'habe', options: ['habe', 'bin', 'hast'], instruction: 'Possession' },
    { id: 'ty1-c5', type: 'Cloze', question: 'Wir ___ heute in die Schule.', answer: 'gehen', options: ['gehen', 'essen', 'schlafen'], instruction: 'Action' },
    { id: 'ty1-c6', type: 'Cloze', question: 'Das Kind ___ ein Lied.', answer: 'singt', options: ['singt', 'rennt', 'liest'], instruction: 'Action' },
    { id: 'ty1-c7', type: 'Cloze', question: 'Der Vater ___ die Zeitung.', answer: 'liest', options: ['liest', 'kocht', 'springt'], instruction: 'Action' },
    { id: 'ty1-c8', type: 'Cloze', question: 'Die Mutter ___ das Essen.', answer: 'kocht', options: ['kocht', 'schläft', 'fährt'], instruction: 'Action' },
    { id: 'ty1-c9', type: 'Cloze', question: 'Ich ___ meiner Oma.', answer: 'helfe', options: ['helfe', 'beiße', 'sehe'], instruction: 'Action' },
    { id: 'ty1-c10', type: 'Cloze', question: 'Das Baby ___ sehr viel.', answer: 'schläft', options: ['schläft', 'arbeitet', 'fährt'], instruction: 'Action' },
    { id: 'ty1-c11', type: 'Cloze', question: 'Wir ___ jeden Tag Milch.', answer: 'trinken', options: ['trinken', 'essen', 'lesen'], instruction: 'Action' },
    { id: 'ty1-c12', type: 'Cloze', question: 'Kannst du mir die Wahrheit ___ ?', answer: 'sagen', options: ['sagen', 'hören', 'sehen'], instruction: 'Language' },
    { id: 'ty1-c13', type: 'Cloze', question: 'Ich ___ Musik.', answer: 'höre', options: ['höre', 'sehe', 'spreche'], instruction: 'Sense' },
    { id: 'ty1-c14', type: 'Cloze', question: 'Ich ___ einen Vogel im Baum.', answer: 'sehe', options: ['sehe', 'höre', 'rieche'], instruction: 'Sense' },
    { id: 'ty1-c15', type: 'Cloze', question: 'Die Blume ___ gut.', answer: 'riecht', options: ['riecht', 'leuchtet', 'macht Krach'], instruction: 'Sense' },
    { id: 'ty1-c16', type: 'Cloze', question: 'Das Essen ___ gut.', answer: 'schmeckt', options: ['schmeckt', 'hört', 'sieht'], instruction: 'Sense' },
    { id: 'ty1-c17', type: 'Cloze', question: 'Mein Rucksack ist ___.', answer: 'schwer', options: ['schwer', 'leicht', 'blau'], instruction: 'Description' },
    { id: 'ty1-c18', type: 'Cloze', question: 'Eine Feder ist ___.', answer: 'leicht', options: ['leicht', 'schwer', 'rot'], instruction: 'Description' },
    { id: 'ty1-c19', type: 'Cloze', question: 'Das Wasser ist ___.', answer: 'nass', options: ['nass', 'trocken', 'hart'], instruction: 'Description' },
    { id: 'ty1-c20', type: 'Cloze', question: 'Der Sand ist ___.', answer: 'trocken', options: ['trocken', 'nass', 'weich'], instruction: 'Description' },
    { id: 'ty1-c21', type: 'Cloze', question: 'Der Stein ist ___.', answer: 'hart', options: ['hart', 'weich', 'heiß'], instruction: 'Description' },
    { id: 'ty1-c22', type: 'Cloze', question: 'Das Kissen ist ___.', answer: 'weich', options: ['weich', 'hart', 'kalt'], instruction: 'Description' },
    { id: 'ty1-c23', type: 'Cloze', question: 'Ich habe ___ Finger.', answer: 'zehn', options: ['zehn', 'zwei', 'fünf'], instruction: 'Number' },
    { id: 'ty1-c24', type: 'Cloze', question: 'Ich habe ___ Beine.', answer: 'zwei', options: ['zwei', 'vier', 'acht'], instruction: 'Number' },
    { id: 'ty1-c25', type: 'Cloze', question: 'Eine Spinne hat ___ Beine.', answer: 'acht', options: ['acht', 'sechs', 'vier'], instruction: 'Number' },
    { id: 'ty1-c26', type: 'Cloze', question: 'Eine Fliege hat ___ Beine.', answer: 'sechs', options: ['sechs', 'acht', 'zwei'], instruction: 'Number' },
    { id: 'ty1-c27', type: 'Cloze', question: 'Ich ___ im Bett.', answer: 'liege', options: ['liege', 'stehe', 'sitze'], instruction: 'State' },
    { id: 'ty1-c28', type: 'Cloze', question: 'Ich ___ am Tisch.', answer: 'sitze', options: ['sitze', 'liege', 'fliege'], instruction: 'State' },
    { id: 'ty1-c29', type: 'Cloze', question: 'Ich ___ an der Tür.', answer: 'stehe', options: ['stehe', 'liege', 'schwimme'], instruction: 'State' },
    { id: 'ty1-c30', type: 'Cloze', question: 'Das Buch ist ___ dem Tisch.', answer: 'auf', options: ['auf', 'unter', 'in'], instruction: 'Preposition' },
    { id: 'ty1-c31', type: 'Cloze', question: 'Die Katze ist ___ dem Tisch.', answer: 'unter', options: ['unter', 'auf', 'in'], instruction: 'Preposition' },
    { id: 'ty1-c32', type: 'Cloze', question: 'Der Apfel ist ___ der Schale.', answer: 'in', options: ['in', 'an', 'zu'], instruction: 'Preposition' },
    { id: 'ty1-c33', type: 'Cloze', question: 'Das Bild hängt ___ der Wand.', answer: 'an', options: ['an', 'in', 'auf'], instruction: 'Preposition' },
    { id: 'ty1-c34', type: 'Cloze', question: 'Ich gehe ___ meiner Mutter.', answer: 'zu', options: ['zu', 'nach', 'in'], instruction: 'Preposition' },
    { id: 'ty1-c35', type: 'Cloze', question: 'Wir fahren ___ Hause.', answer: 'nach', options: ['nach', 'zu', 'an'], instruction: 'Preposition' },
    { id: 'ty1-c36', type: 'Cloze', question: 'Ich bleibe ___ Hause.', answer: 'zu', options: ['zu', 'nach', 'in'], instruction: 'Preposition' },
    { id: 'ty1-c37', type: 'Cloze', question: 'Mein Ball ist ___.', answer: 'rund', options: ['rund', 'eckig', 'lang'], instruction: 'Shape' },
    { id: 'ty1-c38', type: 'Cloze', question: 'Ein Kasten ist ___.', answer: 'eckig', options: ['eckig', 'rund', 'kurz'], instruction: 'Shape' },
    { id: 'ty1-c39', type: 'Cloze', question: 'Die Schnur is very ___.', answer: 'lang', options: ['lang', 'kurz', 'dick'], instruction: 'Shape' },
    { id: 'ty1-c40', type: 'Cloze', question: 'Der Bleistift ist ___.', answer: 'kurz', options: ['kurz', 'lang', 'hoch'], instruction: 'Shape' },
    { id: 'ty1-c41', type: 'Cloze', question: 'Der Baum ist ___.', answer: 'hoch', options: ['hoch', 'flach', 'kurz'], instruction: 'Shape' },
    { id: 'ty1-c42', type: 'Cloze', question: 'Das Wasser im Pool ist ___.', answer: 'flach', options: ['flach', 'hoch', 'groß'], instruction: 'Shape' },
    { id: 'ty1-c43', type: 'Cloze', question: 'Ich bin ___ , du bist klein.', answer: 'groß', options: ['groß', 'klein', 'hell'], instruction: 'Comparison' },
    { id: 'ty1-c44', type: 'Cloze', question: 'Es ist ___ im Zimmer.', answer: 'hell', options: ['hell', 'dunkel', 'warm'], instruction: 'State' },
    { id: 'ty1-c45', type: 'Cloze', question: 'Es ist ___ in der Nacht.', answer: 'dunkel', options: ['dunkel', 'hell', 'kalt'], instruction: 'State' },
    { id: 'ty1-c46', type: 'Cloze', question: 'Ich bin ___ , mir geht es gut.', answer: 'zufrieden', options: ['zufrieden', 'sauer', 'müde'], instruction: 'Feeling' },
    { id: 'ty1-c47', type: 'Cloze', question: 'Ich bin ___ , ich will schlafen.', answer: 'müde', options: ['müde', 'wach', 'froh'], instruction: 'Feeling' },
    { id: 'ty1-c48', type: 'Cloze', question: 'Ich bin ___ , ich habe gegessen.', answer: 'satt', options: ['satt', 'hungrig', 'durstig'], instruction: 'Feeling' },
    { id: 'ty1-c49', type: 'Cloze', question: 'Ich bin ___ , ich will essen.', answer: 'hungrig', options: ['hungrig', 'satt', 'müde'], instruction: 'Feeling' },
    { id: 'ty1-c50', type: 'Cloze', question: 'Ich bin ___ , ich will trinken.', answer: 'durstig', options: ['durstig', 'satt', 'froh'], instruction: 'Feeling' },
    { id: 'ty1-c51', type: 'Cloze', question: 'Danke ___ alles.', answer: 'für', options: ['für', 'mit', 'zu'], instruction: 'Polite' },
  ],
  2: [
    { id: 'ty2-c1', type: 'Cloze', question: 'Das Mädchen ___ seiner Mutter beim Abwasch.', answer: 'half', options: ['half', 'hilft', 'wird helfen'], instruction: 'Past' },
    { id: 'ty2-c2', type: 'Cloze', question: 'Gestern ___ wir einen großen Kuchen.', answer: 'backten', options: ['backten', 'backen', 'werden backen'], instruction: 'Past' },
    { id: 'ty2-c3', type: 'Cloze', question: 'Mein Bruder ___ sehr schnell.', answer: 'rennt', options: ['rennt', 'rannte', 'ist gerannt'], instruction: 'Present' },
    { id: 'ty2-c4', type: 'Cloze', question: 'Wir ___ heute Abend einen Film.', answer: 'sehen', options: ['sehen', 'sahen', 'werden sehen'], instruction: 'Future (Present as Future)' },
    { id: 'ty2-c5', type: 'Cloze', question: 'Die Pferde ___ auf der Wiese.', answer: 'grasen', options: ['grasen', 'grasten', 'haben gegrast'], instruction: 'Present' },
    { id: 'ty2-c6', type: 'Cloze', question: 'Das Kind ___ seinen Teddybären.', answer: 'sucht', options: ['sucht', 'suchte', 'hat gesucht'], instruction: 'Present' },
    { id: 'ty2-c7', type: 'Cloze', question: 'Oma ___ uns eine Geschichte.', answer: 'erzählte', options: ['erzählte', 'erzählt', 'erzählen'], instruction: 'Past' },
    { id: 'ty2-c8', type: 'Cloze', question: 'Der Lehrer ___ an die Tafel.', answer: 'schreibt', options: ['schreibt', 'schrieb', 'geschrieben'], instruction: 'Present' },
    { id: 'ty2-c9', type: 'Cloze', question: 'Die Schüler ___ im Klassenzimmer.', answer: 'sitzen', options: ['sitzen', 'saßen', 'sitzend'], instruction: 'Present' },
    { id: 'ty2-c10', type: 'Cloze', question: 'Die Glocke ___ zur Pause.', answer: 'läutet', options: ['läutet', 'läutete', 'geläutet'], instruction: 'Present' },
    { id: 'ty2-c11', type: 'Cloze', question: 'Wir ___ zusammen auf dem Schulhof.', answer: 'spielen', options: ['spielen', 'spielten', 'spielend'], instruction: 'Present' },
    { id: 'ty2-c12', type: 'Cloze', question: 'Der Vogel hat ein Nest ___.', answer: 'gebaut', options: ['gebaut', 'bauen', 'bauend'], instruction: 'Past Participle' },
    { id: 'ty2-c13', type: 'Cloze', question: 'Das Wasser im See ist ___ kalt.', answer: 'sehr', options: ['sehr', 'wenig', 'viele'], instruction: 'Quantity' },
    { id: 'ty2-c14', type: 'Cloze', question: 'Es gibt ___ Autos auf der Straße.', answer: 'viele', options: ['viele', 'viel', 'groß'], instruction: 'Quantity' },
    { id: 'ty2-c15', type: 'Cloze', question: 'Ich mag Äpfel ___.', answer: 'wirklich', options: ['wirklich', 'nicht', 'vielleicht'], instruction: 'Opinion' },
    { id: 'ty2-c16', type: 'Cloze', question: 'Er ___ nie seine Hausaufgaben.', answer: 'vergisst', options: ['vergisst', 'erinnert', 'macht'], instruction: 'Action' },
    { id: 'ty2-c17', type: 'Cloze', question: 'Denk daran, dein Mittagessen zu ___ .', answer: 'essen', options: ['essen', 'trinken', 'werfen'], instruction: 'Action' },
    { id: 'ty2-c18', type: 'Cloze', question: 'Darf ich deinen Bleistift ___ ?', answer: 'ausleihen', options: ['ausleihen', 'kaufen', 'brechen'], instruction: 'Polite' },
    { id: 'ty2-c19', type: 'Cloze', question: 'Danke ___ das Leihen.', answer: 'für', options: ['für', 'zu', 'mit'], instruction: 'Polite' },
    { id: 'ty2-c20', type: 'Cloze', question: 'Ich ___ aus Deutschland.', answer: 'komme', options: ['komme', 'gehe', 'wohne'], instruction: 'Origin' },
    { id: 'ty2-c21', type: 'Cloze', question: 'Wo ___ du?', answer: 'wohnst', options: ['wohnst', 'bist', 'hast'], instruction: 'Address' },
    { id: 'ty2-c22', type: 'Cloze', question: 'Mein Geburtstag ist ___ Juni.', answer: 'im', options: ['im', 'am', 'um'], instruction: 'Time' },
    { id: 'ty2-c23', type: 'Cloze', question: 'Wir gehen am ___ zu einer Party.', answer: 'Samstag', options: ['Samstag', 'Juni', 'mittag'], instruction: 'Time' },
    { id: 'ty2-c24', type: 'Cloze', question: 'Es wird ___ Abend dunkel.', answer: 'am', options: ['am', 'im', 'um'], instruction: 'Time' },
    { id: 'ty2-c25', type: 'Cloze', question: 'Die Sonne geht ___ Osten auf.', answer: 'im', options: ['im', 'am', 'um'], instruction: 'Direction' },
    { id: 'ty2-c26', type: 'Cloze', question: 'Der Mond scheint ___ Nacht.', answer: 'in der', options: ['in der', 'am', 'im'], instruction: 'Time' },
    { id: 'ty2-c27', type: 'Cloze', question: 'Eine Giraffe hat einen ___ Hals.', answer: 'langen', options: ['langen', 'kurzen', 'dicken'], instruction: 'Body' },
    { id: 'ty2-c28', type: 'Cloze', question: 'Ein Igel hat ___ Stacheln.', answer: 'viele', options: ['viele', 'wenige', 'weiche'], instruction: 'Body' },
    { id: 'ty2-c29', type: 'Cloze', question: 'Ein Elefant hat einen ___ Rüssel.', answer: 'langen', options: ['langen', 'roten', 'kleinen'], instruction: 'Body' },
    { id: 'ty2-c30', type: 'Cloze', question: 'Wir sehen mit ___ Augen.', answer: 'unseren', options: ['unseren', 'euren', 'ihren'], instruction: 'Possession' },
    { id: 'ty2-c31', type: 'Cloze', question: 'Du hörst mit ___ Ohren.', answer: 'deinen', options: ['deinen', 'meinen', 'seinen'], instruction: 'Possession' },
    { id: 'ty2-c32', type: 'Cloze', question: 'Er geht mit ___ Hund spazieren.', answer: 'seinem', options: ['seinem', 'ihrem', 'meinem'], instruction: 'Possession' },
    { id: 'ty2-c33', type: 'Cloze', question: 'Sie spielt mit ___ Puppe.', answer: 'ihrer', options: ['ihrer', 'seiner', 'eurer'], instruction: 'Possession' },
    { id: 'ty2-c34', type: 'Cloze', question: 'Die Kinder spielen in ___ Garten.', answer: 'ihrem', options: ['ihrem', 'unserem', 'meinem'], instruction: 'Possession' },
    { id: 'ty2-c35', type: 'Cloze', question: 'Wie viel ___ ist es?', answer: 'Uhr', options: ['Uhr', 'Zeit', 'hat'], instruction: 'Time' },
    { id: 'ty2-c36', type: 'Cloze', question: 'Es ist ___ zwei Uhr.', answer: 'fast', options: ['fast', 'nie', 'immer'], instruction: 'Time' },
    { id: 'ty2-c37', type: 'Cloze', question: 'Ich kann die Uhr ___.', answer: 'sehen', options: ['sehen', 'hören', 'schmecken'], instruction: 'Action' },
    { id: 'ty2-c38', type: 'Cloze', question: 'Er ist ___ im Rennen.', answer: 'gut', options: ['gut', 'schlecht', 'blau'], instruction: 'Ability' },
    { id: 'ty2-c39', type: 'Cloze', question: 'Sie ist ___ im Zeichnen.', answer: 'begabt', options: ['begabt', 'sauer', 'müde'], instruction: 'Ability' },
    { id: 'ty2-c40', type: 'Cloze', question: 'Mathe ist ___ zu machen.', answer: 'schwer', options: ['schwer', 'leicht', 'rot'], instruction: 'School' },
    { id: 'ty2-c41', type: 'Cloze', question: 'Ich kann gut ___.', answer: 'lesen', options: ['lesen', 'nicht', 'nie'], instruction: 'Ability' },
    { id: 'ty2-c42', type: 'Cloze', question: 'Willst du mit mir ___ ?', answer: 'spielen', options: ['spielen', 'kämpfen', 'beißen'], instruction: 'Social' },
    { id: 'ty2-c43', type: 'Cloze', question: 'Wir sind ___ Freunde.', answer: 'gute', options: ['gute', 'schlechte', 'böse'], instruction: 'Social' },
    { id: 'ty2-c44', type: 'Cloze', question: 'Ich möchte ___ ein Eis.', answer: 'wirklich', options: ['wirklich', 'nicht', 'nie'], instruction: 'Desire' },
    { id: 'ty2-c45', type: 'Cloze', question: 'Darf ich ___ einen Apfel haben?', answer: 'bitte', options: ['bitte', 'nicht', 'vielleicht'], instruction: 'Polite' },
    { id: 'ty2-c46', type: 'Cloze', question: 'Hier ___ er.', answer: 'ist', options: ['ist', 'war', 'es'], instruction: 'Polite' },
    { id: 'ty2-c47', type: 'Cloze', question: 'Danke ___ das Essen.', answer: 'für', options: ['für', 'zu', 'mit'], instruction: 'Polite' },
    { id: 'ty2-c48', type: 'Cloze', question: 'Gern ___.', answer: 'geschehen', options: ['geschehen', 'viel', 'groß'], instruction: 'Polite' },
    { id: 'ty2-c49', type: 'Cloze', question: 'Hab einen ___ Tag.', answer: 'schönen', options: ['schönen', 'schlechten', 'blauen'], instruction: 'Greeting' },
    { id: 'ty2-c50', type: 'Cloze', question: 'Ich ___ mich, dich zu treffen.', answer: 'freue', options: ['freue', 'ärgere', 'traure'], instruction: 'Greeting' },
    { id: 'ty2-c51', type: 'Cloze', question: 'Bis ___ !', answer: 'bald', options: ['bald', 'nie', 'gestern'], instruction: 'Greeting' },
  ],
  3: [
    { id: 'ty3-c1', type: 'Cloze', question: 'Das Haus ist aus roten Steinen ___.', answer: 'gebaut', options: ['gebaut', 'gegessen', 'gerannt'], instruction: 'State' },
    { id: 'ty3-c2', type: 'Cloze', question: 'Das Auto ___ schnell über die Straße.', answer: 'fuhr', options: ['fuhr', 'flog', 'schwamm'], instruction: 'Past' },
    { id: 'ty3-c3', type: 'Cloze', question: 'Wir ___ ein spannendes Buch in der Schule.', answer: 'lesen', options: ['lesen', 'essen', 'trinken'], instruction: 'Present' },
    { id: 'ty3-c4', type: 'Cloze', question: 'Gestern ___ es den ganzen Tag.', answer: 'regnete', options: ['regnete', 'schien', 'wehte'], instruction: 'Weather' },
    { id: 'ty3-c5', type: 'Cloze', question: 'Meine Mama ___ einen leckeren Kuchen.', answer: 'backte', options: ['backte', 'kaufte', 'fand'], instruction: 'Past' },
    { id: 'ty3-c6', type: 'Cloze', question: 'Der Hund ___ dem Ball hinterher.', answer: 'rannte', options: ['rannte', 'schlief', 'aß'], instruction: 'Past' },
    { id: 'ty3-c7', type: 'Cloze', question: 'Die Sonne ___ von einem wolkenlosen Himmel.', answer: 'scheint', options: ['scheint', 'regnet', 'weht'], instruction: 'Weather' },
    { id: 'ty3-c8', type: 'Cloze', question: 'Wir ___ immer unsere Hausaufgaben.', answer: 'machen', options: ['machen', 'vergessen', 'verlieren'], instruction: 'Action' },
    { id: 'ty3-c9', type: 'Cloze', question: 'In der Pause ___ wir Fußball.', answer: 'spielen', options: ['spielen', 'lesen', 'schlafen'], instruction: 'Action' },
    { id: 'ty3-c10', type: 'Cloze', question: 'Mein Vater ___ in einer großen Firma.', answer: 'arbeitet', options: ['arbeitet', 'wohnt', 'isst'], instruction: 'Action' },
    { id: 'ty3-c11', type: 'Cloze', question: 'Sie ___ in den Sommerferien ins Ausland.', answer: 'reisten', options: ['reisten', 'blieben', 'schliefen'], instruction: 'Past' },
    { id: 'ty3-c12', type: 'Cloze', question: 'Ich ___ mich auf Weihnachten.', answer: 'freue', options: ['freue', 'fürchte', 'hasse'], instruction: 'Feeling' },
    { id: 'ty3-c13', type: 'Cloze', question: 'Das Kind ___ , weil es sich wehgetan hat.', answer: 'weint', options: ['weint', 'lacht', 'schläft'], instruction: 'Action' },
    { id: 'ty3-c14', type: 'Cloze', question: 'Wir ___ ein Lied zum Geburtstag.', answer: 'sangen', options: ['sangen', 'aßen', 'lasen'], instruction: 'Past' },
    { id: 'ty3-c15', type: 'Cloze', question: 'Denk daran, die Tür hinter dir zu ___ .', answer: 'schließen', options: ['schließen', 'öffnen', 'verriegeln'], instruction: 'Action' },
    { id: 'ty3-c16', type: 'Cloze', question: 'Das Licht muss ___ werden, wenn du gehst.', answer: 'ausgeschaltet', options: ['ausgeschaltet', 'eingeschaltet', 'verschoben'], instruction: 'Action' },
    { id: 'ty3-c17', type: 'Cloze', question: 'Das Wasser im Kessel ___ .', answer: 'kocht', options: ['kocht', 'friert', 'schmeckt'], instruction: 'State' },
    { id: 'ty3-c18', type: 'Cloze', question: 'Das Eis ___ im Sonnenschein.', answer: 'schmilzt', options: ['schmilzt', 'friert', 'wächst'], instruction: 'State' },
    { id: 'ty3-c19', type: 'Cloze', question: 'Die Blumen ___ herrlich im Garten.', answer: 'blühen', options: ['blühen', 'verwelken', 'schlafen'], instruction: 'State' },
    { id: 'ty3-c20', type: 'Cloze', question: 'Blätter fallen im ___ von den Bäumen.', answer: 'Herbst', options: ['Herbst', 'Frühling', 'Sommer'], instruction: 'Season' },
    { id: 'ty3-c21', type: 'Cloze', question: 'Alles wird im ___ grün.', answer: 'Frühling', options: ['Frühling', 'Winter', 'Herbst'], instruction: 'Season' },
    { id: 'ty3-c22', type: 'Cloze', question: 'Wir schwimmen im ___ im Meer.', answer: 'Sommer', options: ['Sommer', 'Winter', 'Herbst'], instruction: 'Season' },
    { id: 'ty3-c23', type: 'Cloze', question: 'Im ___ liegt Schnee.', answer: 'Winter', options: ['Winter', 'Sommer', 'Frühling'], instruction: 'Season' },
    { id: 'ty3-c24', type: 'Cloze', question: 'Eine Woche hat ___ Tage.', answer: 'sieben', options: ['sieben', 'fünf', 'zehn'], instruction: 'Number' },
    { id: 'ty3-c25', type: 'Cloze', question: 'Ein Jahr hat zwölf ___.', answer: 'Monate', options: ['Monate', 'Wochen', 'Tage'], instruction: 'Time' },
    { id: 'ty3-c26', type: 'Cloze', question: 'Eine Stunde hat sechzig ___.', answer: 'Minuten', options: ['Minuten', 'Sekunden', 'Stunden'], instruction: 'Time' },
    { id: 'ty3-c27', type: 'Cloze', question: 'Eine Minute hat sechzig ___.', answer: 'Sekunden', options: ['Sekunden', 'Minuten', 'Stunden'], instruction: 'Time' },
    { id: 'ty3-c28', type: 'Cloze', question: 'Heute ist ___ , gestern war Freitag.', answer: 'Samstag', options: ['Samstag', 'Sonntag', 'Montag'], instruction: 'Weekday' },
    { id: 'ty3-c29', type: 'Cloze', question: 'Morgen ist ___ , heute ist Mittwoch.', answer: 'Donnerstag', options: ['Donnerstag', 'Dienstag', 'Freitag'], instruction: 'Weekday' },
    { id: 'ty3-c30', type: 'Cloze', question: 'Januar ist der ___ Monat des Jahres.', answer: 'erste', options: ['erste', 'letzte', 'zweite'], instruction: 'Ordinal' },
    { id: 'ty3-c31', type: 'Cloze', question: 'Dezember ist der ___ Monat des Jahres.', answer: 'letzte', options: ['letzte', 'erste', 'mittlere'], instruction: 'Ordinal' },
    { id: 'ty3-c32', type: 'Cloze', question: 'Wir essen zu Mittag in der Mitte des ___ .', answer: 'Tages', options: ['Tages', 'Nacht', 'Morgens'], instruction: 'Time' },
    { id: 'ty3-c33', type: 'Cloze', question: 'Die Sterne leuchten in der ___ .', answer: 'Nacht', options: ['Nacht', 'Tag', 'Abend'], instruction: 'Time' },
    { id: 'ty3-c34', type: 'Cloze', question: 'Die Sonne geht am ___ auf.', answer: 'Morgen', options: ['Morgen', 'Abend', 'Nacht'], instruction: 'Time' },
    { id: 'ty3-c35', type: 'Cloze', question: 'Die Sonne geht am ___ unter.', answer: 'Abend', options: ['Abend', 'Morgen', 'Mittag'], instruction: 'Time' },
    { id: 'ty3-c36', type: 'Cloze', question: 'Die Milch ist im ___ .', answer: 'Kühlschrank', options: ['Kühlschrank', 'Ofen', 'Bett'], instruction: 'Home' },
    { id: 'ty3-c37', type: 'Cloze', question: 'Das Essen wird auf dem ___ zubereitet.', answer: 'Herd', options: ['Herd', 'Tisch', 'Boden'], instruction: 'Home' },
    { id: 'ty3-c38', type: 'Cloze', question: 'Wir schlafen in einem ___ .', answer: 'Bett', options: ['Bett', 'Stuhl', 'Auto'], instruction: 'Home' },
    { id: 'ty3-c39', type: 'Cloze', question: 'Wir putzen uns die Zähne im ___ .', answer: 'Badezimmer', options: ['Badezimmer', 'Küche', 'Wohnzimmer'], instruction: 'Home' },
    { id: 'ty3-c40', type: 'Cloze', question: 'Wir schauen fern im ___ .', answer: 'Wohnzimmer', options: ['Wohnzimmer', 'Garten', 'Schuppen'], instruction: 'Home' },
    { id: 'ty3-c41', type: 'Cloze', question: 'Das Auto steht in der ___ .', answer: 'Garage', options: ['Garage', 'Wohnzimmer', 'Küche'], instruction: 'Home' },
    { id: 'ty3-c42', type: 'Cloze', question: 'Kleidung ist im ___ .', answer: 'Schrank', options: ['Schrank', 'Brotdose', 'Spülbecken'], instruction: 'Home' },
    { id: 'ty3-c43', type: 'Cloze', question: 'Wir waschen Kleidung in der ___ .', answer: 'Waschmaschine', options: ['Waschmaschine', 'Spülmaschine', 'Ofen'], instruction: 'Home' },
    { id: 'ty3-c44', type: 'Cloze', question: 'Teller werden in der ___ gewaschen.', answer: 'Spülmaschine', options: ['Spülmaschine', 'Waschmaschine', 'Trockner'], instruction: 'Home' },
    { id: 'ty3-c45', type: 'Cloze', question: 'Der Staubsauger entfernt ___ zu Hause.', answer: 'Staub', options: ['Staub', 'Wasser', 'Essen'], instruction: 'Home' },
    { id: 'ty3-c46', type: 'Cloze', question: 'Wir backen Brot im ___ zu Hause.', answer: 'Ofen', options: ['Ofen', 'Kühlschrank', 'Spülbecken'], instruction: 'Home' },
    { id: 'ty3-c47', type: 'Cloze', question: 'Gemüse wächst im ___ zu Hause.', answer: 'Garten', options: ['Garten', 'Wohnzimmer', 'Dachboden'], instruction: 'Home' },
    { id: 'ty3-c48', type: 'Cloze', question: 'Post kommt in den ___ zu Hause.', answer: 'Briefkasten', options: ['Briefkasten', 'Mülleimer', 'Spülbecken'], instruction: 'Home' },
    { id: 'ty3-c49', type: 'Cloze', question: 'Müll wird im ___ zu Hause entsorgt.', answer: 'Mülleimer', options: ['Mülleimer', 'Briefkasten', 'Schrank'], instruction: 'Home' },
    { id: 'ty3-c50', type: 'Cloze', question: 'Die Tür wird mit einem ___ geöffnet.', answer: 'Schlüssel', options: ['Schlüssel', 'Löffel', 'Buch'], instruction: 'Home' },
    { id: 'ty3-c51', type: 'Cloze', question: 'Wir klingeln an der ___ zu Hause.', answer: 'Türklingel', options: ['Türklingel', 'Fenster', 'Dach'], instruction: 'Home' },
  ],
  4: [
    { id: 'ty4-c1', type: 'Cloze', question: 'Welche ___ ist deine Liebste?', answer: 'Farbe', options: ['Farbe', 'Auto', 'Essen'], instruction: 'Question' },
    { id: 'ty4-c2', type: 'Cloze', question: 'Wo ___ du gestern?', answer: 'warst', options: ['warst', 'bist', 'sein'], instruction: 'Time' },
    { id: 'ty4-c3', type: 'Cloze', question: 'Mit wem hast du am Telefon ___ ?', answer: 'gesprochen', options: ['gesprochen', 'gegessen', 'geschlafen'], instruction: 'Action' },
    { id: 'ty4-c4', type: 'Cloze', question: 'Wann ___ du mit der Schule?', answer: 'beginnst', options: ['beginnst', 'schläfst', 'isst'], instruction: 'School' },
    { id: 'ty4-c5', type: 'Cloze', question: 'Was hast du zum Abendessen ___ ?', answer: 'gehabt', options: ['gehabt', 'ist', 'geht'], instruction: 'Action' },
    { id: 'ty4-c6', type: 'Cloze', question: 'Warum ___ du?', answer: 'lachst', options: ['lachst', 'schläfst', 'fährst'], instruction: 'Feeling' },
    { id: 'ty4-c7', type: 'Cloze', question: 'Wie ___ du diese Aufgabe?', answer: 'löst', options: ['löst', 'isst', 'trinkst'], instruction: 'School' },
    { id: 'ty4-c8', type: 'Cloze', question: 'Ich ___ es, Computerspiele zu spielen.', answer: 'liebe', options: ['liebe', 'hasse', 'wohne'], instruction: 'Desire' },
    { id: 'ty4-c9', type: 'Cloze', question: 'Mein Hund ___ sehr laut.', answer: 'bellt', options: ['bellt', 'miaut', 'zwitschert'], instruction: 'Sound' },
    { id: 'ty4-c10', type: 'Cloze', question: 'Die Katze ___ , wenn sie glücklich ist.', answer: 'schnurrt', options: ['schnurrt', 'bellt', 'faucht'], instruction: 'Sound' },
    { id: 'ty4-c11', type: 'Cloze', question: 'Das Pferd ___ über das Feld.', answer: 'galoppiert', options: ['galoppiert', 'schwimmt', 'fliegt'], instruction: 'Action' },
    { id: 'ty4-c12', type: 'Cloze', question: 'Der Vogel hat Eier im Nest ___.', answer: 'gelegt', options: ['gelegt', 'gegessen', 'verloren'], instruction: 'Nature' },
    { id: 'ty4-c13', type: 'Cloze', question: 'Die Kuh ___ an ihrem Gras.', answer: 'kaut', options: ['kaut', 'liest', 'springt'], instruction: 'Nature' },
    { id: 'ty4-c14', type: 'Cloze', question: 'Das Schaf hat sehr ___ Wolle.', answer: 'weiche', options: ['weiche', 'harte', 'blaue'], instruction: 'Nature' },
    { id: 'ty4-c15', type: 'Cloze', question: 'Das Schwein ___ sich im Schlamm.', answer: 'wälzt', options: ['wälzt', 'wäscht', 'fliegt'], instruction: 'Nature' },
    { id: 'ty4-c16', type: 'Cloze', question: 'Der Bauer ___ das Getreide auf dem Feld.', answer: 'erntet', options: ['erntet', 'sät', 'isst'], instruction: 'Profession' },
    { id: 'ty4-c17', type: 'Cloze', question: 'Der Gärtner ___ die Blumen.', answer: 'gießt', options: ['gießt', 'isst', 'schneidet'], instruction: 'Profession' },
    { id: 'ty4-c18', type: 'Cloze', question: 'Der Bäcker backt jeden Morgen ___ .', answer: 'Brot', options: ['Brot', 'Steine', 'Schuhe'], instruction: 'Profession' },
    { id: 'ty4-c19', type: 'Cloze', question: 'Die Polizei ___ Kriminelle.', answer: 'fängt', options: ['fängt', 'hilft', 'füttert'], instruction: 'Profession' },
    { id: 'ty4-c20', type: 'Cloze', question: 'Der Doktor ___ kranke Menschen.', answer: 'untersucht', options: ['untersucht', 'isst', 'schlägt'], instruction: 'Profession' },
    { id: 'ty4-c21', type: 'Cloze', question: 'Die Feuerwehr ___ das Feuer.', answer: 'löscht', options: ['löscht', 'zündet an', 'schaut an'], instruction: 'Profession' },
    { id: 'ty4-c22', type: 'Cloze', question: 'Der Friseur ___ meine Haare.', answer: 'schneidet', options: ['schneidet', 'wäscht', 'färbt'], instruction: 'Profession' },
    { id: 'ty4-c23', type: 'Cloze', question: 'Der Zimmermann ___ ein neues Haus.', answer: 'baut', options: ['baut', 'isst', 'zeichnet'], instruction: 'Profession' },
    { id: 'ty4-c24', type: 'Cloze', question: 'Der Maurer benutzt ___ für die Mauer.', answer: 'Steine', options: ['Steine', 'Holz', 'Glas'], instruction: 'Profession' },
    { id: 'ty4-c25', type: 'Cloze', question: 'Der Maler streicht ___ an die Wand.', answer: 'Farbe', options: ['Farbe', 'Wasser', 'Essen'], instruction: 'Profession' },
    { id: 'ty4-c26', type: 'Cloze', question: 'Der Chefkoch macht ___ Essen.', answer: 'leckeres', options: ['leckeres', 'schlechtes', 'blaues'], instruction: 'Profession' },
    { id: 'ty4-c27', type: 'Cloze', question: 'Der Kellner ___ das Essen am Tisch.', answer: 'serviert', options: ['serviert', 'isst', 'wirft'], instruction: 'Profession' },
    { id: 'ty4-c28', type: 'Cloze', question: 'Der Fahrer ___ den Bus.', answer: 'fährt', options: ['fährt', 'fliegt', 'schwimmt'], instruction: 'Profession' },
    { id: 'ty4-c29', type: 'Cloze', question: 'Der Pilot fliegt ein ___ .', answer: 'Flugzeug', options: ['Flugzeug', 'Schiff', 'Zug'], instruction: 'Profession' },
    { id: 'ty4-c30', type: 'Cloze', question: 'Der Seemann segelt auf einem ___ .', answer: 'Schiff', options: ['Schiff', 'Flugzeug', 'Auto'], instruction: 'Profession' },
    { id: 'ty4-c31', type: 'Cloze', question: 'Der Lehrer ___ uns neue Dinge.', answer: 'lehrt', options: ['lehrt', 'vergisst', 'schlägt'], instruction: 'Profession' },
    { id: 'ty4-c32', type: 'Cloze', question: 'Die Schüler ___ jeden Tag Hausaufgaben.', answer: 'machen', options: ['machen', 'lesen', 'essen'], instruction: 'School' },
    { id: 'ty4-c33', type: 'Cloze', question: 'Wir schreiben in unsere ___ .', answer: 'Hefte', options: ['Hefte', 'Bücher', 'Münder'], instruction: 'School' },
    { id: 'ty4-c34', type: 'Cloze', question: 'Wir lesen spannende ___ in der Schule.', answer: 'Bücher', options: ['Bücher', 'Hefte', 'Zeitschriften'], instruction: 'School' },
    { id: 'ty4-c35', type: 'Cloze', question: 'Die Bibliothek hat viele ___ in der Schule.', answer: 'Bücher', options: ['Bücher', 'Brotdosen', 'Schuhe'], instruction: 'School' },
    { id: 'ty4-c36', type: 'Cloze', question: 'Wir ___ Mathe in der Schule.', answer: 'machen', options: ['machen', 'singen', 'tanzen'], instruction: 'School' },
    { id: 'ty4-c37', type: 'Cloze', question: 'Wir ___ Deutsch in der Schule.', answer: 'lernen', options: ['lernen', 'vergessen', 'verlieren'], instruction: 'School' },
    { id: 'ty4-c38', type: 'Cloze', question: 'Wir ___ Deutsch in der Schule.', answer: 'sprechen', options: ['sprechen', 'essen', 'rennen'], instruction: 'School' },
    { id: 'ty4-c39', type: 'Cloze', question: 'Sport macht ___ in der Turnhalle.', answer: 'Spaß', options: ['Spaß', 'langweilig', 'traurig'], instruction: 'School' },
    { id: 'ty4-c40', type: 'Cloze', question: 'Musik ist gut zum ___ .', answer: 'Tanzen', options: ['Tanzen', 'Schlafen', 'Lesen'], instruction: 'School' },
    { id: 'ty4-c41', type: 'Cloze', question: 'Wir zeichnen im ___ .', answer: 'Kunstunterricht', options: ['Kunstunterricht', 'Mathe', 'Sport'], instruction: 'School' },
    { id: 'ty4-c42', type: 'Cloze', question: 'Naturwissenschaft handelt von der ___ in der Schule.', answer: 'Natur', options: ['Natur', 'Geschichte', 'Musik'], instruction: 'School' },
    { id: 'ty4-c43', type: 'Cloze', question: 'Geschichte handelt von der ___ in der Schule.', answer: 'Vergangenheit', options: ['Vergangenheit', 'Zukunft', 'Gegenwart'], instruction: 'School' },
    { id: 'ty4-c44', type: 'Cloze', question: 'Geographie handelt von der ___ in der Schule.', answer: 'Welt', options: ['Welt', 'Zahlen', 'Wörtern'], instruction: 'School' },
    { id: 'ty4-c45', type: 'Cloze', question: 'Religion handelt vom ___ in der Schule.', answer: 'Glauben', options: ['Glauben', 'Wissenschaft', 'Essen'], instruction: 'School' },
    { id: 'ty4-c46', type: 'Cloze', question: 'Pausen sind gut zum ___ in der Schule.', answer: 'Spielen', options: ['Spielen', 'Schlafen', 'Arbeiten'], instruction: 'School' },
    { id: 'ty4-c47', type: 'Cloze', question: 'Der Hort ist nach der ___ .', answer: 'Schule', options: ['Schule', 'Nacht', 'Ferien'], instruction: 'School' },
    { id: 'ty4-c48', type: 'Cloze', question: 'Ferien sind ___ in der Schule.', answer: 'lang', options: ['lang', 'kurz', 'blau'], instruction: 'School' },
    { id: 'ty4-c49', type: 'Cloze', question: 'Die Schule beginnt um ___ Uhr.', answer: 'acht', options: ['acht', 'zehn', 'zwölf'], instruction: 'School' },
    { id: 'ty4-c50', type: 'Cloze', question: 'Wir freuen uns auf das ___ in der Schule.', answer: 'Wochenende', options: ['Wochenende', 'Hausaufgaben', 'Montag'], instruction: 'School' },
    { id: 'ty4-c51', type: 'Cloze', question: 'Denk daran, dein Buch zu ___ .', answer: 'lesen', options: ['lesen', 'essen', 'werfen'], instruction: 'School' },
  ],
};
