/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameContent, Grade } from '../../../../types';

export const TYSK_CLOZE_P3: Partial<Record<Grade, GameContent[]>> = {
  0: [
    { id: 'ty0-c52', type: 'Cloze', question: 'Die ___ scheint am Himmel.', answer: 'Sonne', options: ['Sonne', 'Fisch', 'Fuß'], instruction: 'Nature' },
    { id: 'ty0-c53', type: 'Cloze', question: 'Der ___ ist grün.', answer: 'Apfel', options: ['Apfel', 'Flugzeug', 'Bett'], instruction: 'Food' },
    { id: 'ty0-c54', type: 'Cloze', question: 'Eine kleine gelbe ___.', answer: 'Ente', options: ['Ente', 'Fahrrad', 'Brücke'], instruction: 'Animal' },
    { id: 'ty0-c55', type: 'Cloze', question: 'Ich sehe eine rote ___.', answer: 'Blume', options: ['Blume', 'Straße', 'Banane'], instruction: 'Nature' },
    { id: 'ty0-c56', type: 'Cloze', question: 'Die ___ macht miau.', answer: 'Katze', options: ['Katze', 'Bus', 'Zug'], instruction: 'Animal' },
    { id: 'ty0-c57', type: 'Cloze', question: 'Der ___ ist rund.', answer: 'Ball', options: ['Ball', 'Haus', 'Hand'], instruction: 'Object' },
    { id: 'ty0-c58', type: 'Cloze', question: 'Meine Mama ist ___ .', answer: 'schön', options: ['schön', 'blau', 'Auto'], instruction: 'Family' },
    { id: 'ty0-c59', type: 'Cloze', question: 'Mein Papa ist ___ .', answer: 'groß', options: ['groß', 'grün', 'klein'], instruction: 'Family' },
    { id: 'ty0-c60', type: 'Cloze', question: 'Ein großer brauner ___.', answer: 'Bär', options: ['Bär', 'Vogel', 'Hase'], instruction: 'Animal' },
    { id: 'ty0-c61', type: 'Cloze', question: 'Der ___ ist blau.', answer: 'Himmel', options: ['Himmel', 'Rasen', 'Milch'], instruction: 'Nature' },
    { id: 'ty0-c62', type: 'Cloze', question: 'Ich esse ___ .', answer: 'Brot', options: ['Brot', 'Stift', 'Wand'], instruction: 'Food' },
    { id: 'ty0-c63', type: 'Cloze', question: 'Ein ___ Milch trinken.', answer: 'Glas', options: ['Glas', 'Tasche', 'Zahn'], instruction: 'Drink' },
    { id: 'ty0-c64', type: 'Cloze', question: 'Meine ___ ist warm.', answer: 'Suppe', options: ['Suppe', 'Schuh', 'Tisch'], instruction: 'Food' },
    { id: 'ty0-c65', type: 'Cloze', question: 'Das ___ liegt auf dem Tisch.', answer: 'Buch', options: ['Buch', 'Wind', 'Meer'], instruction: 'Object' },
    { id: 'ty0-c66', type: 'Cloze', question: 'Ich spiele mit meinem ___ .', answer: 'Hund', options: ['Hund', 'Flugzeug', 'Hut'], instruction: 'Activity' },
    { id: 'ty0-c67', type: 'Cloze', question: 'Da ist eine ___ auf der Wiese.', answer: 'Kuh', options: ['Kuh', 'Lampe', 'Fenster'], instruction: 'Animal' },
    { id: 'ty0-c68', type: 'Cloze', question: 'Der ___ ist weiß.', answer: 'Schnee', options: ['Schnee', 'Blatt', 'Mund'], instruction: 'Nature' },
    { id: 'ty0-c69', type: 'Cloze', question: 'Ein kleines blaues ___ .', answer: 'Auto', options: ['Auto', 'Apfel', 'Ohr'], instruction: 'Object' },
    { id: 'ty0-c70', type: 'Cloze', question: 'Ich schlafe in meinem ___ .', answer: 'Bett', options: ['Bett', 'Ofen', 'Garten'], instruction: 'Home' },
    { id: 'ty0-c71', type: 'Cloze', question: 'Der ___ ist weiß.', answer: 'Hase', options: ['Hase', 'Sonne', 'Himmel'], instruction: 'Animal' },
    { id: 'ty0-c72', type: 'Cloze', question: 'Ein ___ kaltes Wasser.', answer: 'Glas', options: ['Glas', 'Wolke', 'Pferd'], instruction: 'Drink' },
    { id: 'ty0-c73', type: 'Cloze', question: 'Schau mal, der ___ Vogel.', answer: 'kleine', options: ['kleine', 'große', 'dicke'], instruction: 'Description' },
    { id: 'ty0-c74', type: 'Cloze', question: 'Der ___ sitzt im Nest.', answer: 'Vogel', options: ['Vogel', 'Fisch', 'Löwe'], instruction: 'Animal' },
    { id: 'ty0-c75', type: 'Cloze', question: 'Ich mag ___ .', answer: 'Erdbeeren', options: ['Erdbeeren', 'Steine', 'Wände'], instruction: 'Food' },
    { id: 'ty0-c76', type: 'Cloze', question: 'Die ___ ist süß.', answer: 'Banane', options: ['Banane', 'Suppe', 'Erde'], instruction: 'Food' },
    { id: 'ty0-c77', type: 'Cloze', question: 'Der ___ ist stark.', answer: 'Löwe', options: ['Löwe', 'Katze', 'Maus'], instruction: 'Animal' },
    { id: 'ty0-c78', type: 'Cloze', question: 'Eine ___ an der Wand.', answer: 'Fliege', options: ['Fliege', 'Berg', 'Haus'], instruction: 'Bug' },
    { id: 'ty0-c79', type: 'Cloze', question: 'Die ___ ist schwarz.', answer: 'Hose', options: ['Hose', 'Sonne', 'Milch'], instruction: 'Clothing' },
    { id: 'ty0-c80', type: 'Cloze', question: 'Ich trage meine ___ .', answer: 'Schuhe', options: ['Schuhe', 'Hände', 'Ohren'], instruction: 'Clothing' },
    { id: 'ty0-c81', type: 'Cloze', question: 'Es ist ___ draußen.', answer: 'kalt', options: ['kalt', 'heiß', 'schön'], instruction: 'Weather' },
    { id: 'ty0-c82', type: 'Cloze', question: 'Der schöne ___ scheint.', answer: 'Mond', options: ['Mond', 'blaues', 'graues'], instruction: 'Nature' },
    { id: 'ty0-c83', type: 'Cloze', question: 'Eine ___ voller Bonbons.', answer: 'Tüte', options: ['Tüte', 'Fuß', 'Haar'], instruction: 'Object' },
    { id: 'ty0-c84', type: 'Cloze', question: 'Mein ___ ist rosa.', answer: 'Hemd', options: ['Hemd', 'Banane', 'Mond'], instruction: 'Clothing' },
    { id: 'ty0-c85', type: 'Cloze', question: 'Eine ___ im Sandkasten.', answer: 'Schaufel', options: ['Schaufel', 'Haus', 'Kuh'], instruction: 'Object' },
    { id: 'ty0-c86', type: 'Cloze', question: 'Der ___ ist lustig.', answer: 'Clown', options: ['Clown', 'Brot', 'Brücke'], instruction: 'Person' },
    { id: 'ty0-c87', type: 'Cloze', question: 'Ich steige in den ___ .', answer: 'Bus', options: ['Bus', 'Fisch', 'Bett'], instruction: 'Travel' },
    { id: 'ty0-c88', type: 'Cloze', question: 'Eine ___ Schokolade.', answer: 'Tafel', options: ['Tafel', 'Stuhl', 'Fenster'], instruction: 'Food' },
    { id: 'ty0-c89', type: 'Cloze', question: 'Die ___ sitzt auf dem Dach.', answer: 'Katze', options: ['Katze', 'Fisch', 'Zug'], instruction: 'Animal' },
    { id: 'ty0-c90', type: 'Cloze', question: 'Ein ___ Reis.', answer: 'Teller', options: ['Teller', 'Schuh', 'Blume'], instruction: 'Food' },
    { id: 'ty0-c91', type: 'Cloze', question: 'Das ___ ist fertig.', answer: 'Abendessen', options: ['Abendessen', 'Fahrrad', 'Wolke'], instruction: 'Food' },
    { id: 'ty0-c92', type: 'Cloze', question: 'Ein ___ im Wald.', answer: 'Baum', options: ['Baum', 'Buch', 'Wand'], instruction: 'Nature' },
    { id: 'ty0-c93', type: 'Cloze', question: 'Die ___ ist grau.', answer: 'Wolke', options: ['Wolke', 'Sonne', 'Brücke'], instruction: 'Nature' },
    { id: 'ty0-c94', type: 'Cloze', question: 'Eine ___ Saft.', answer: 'Tasse', options: ['Tasse', 'Schuh', 'Zahn'], instruction: 'Drink' },
    { id: 'ty0-c95', type: 'Cloze', question: 'Das ___ ist zu Ende.', answer: 'Spiel', options: ['Spiel', 'Brot', 'Sonne'], instruction: 'Action' },
    { id: 'ty0-c96', type: 'Cloze', question: 'Ein ___ für Papa.', answer: 'Geschenk', options: ['Geschenk', 'Bus', 'Wind'], instruction: 'Object' },
    { id: 'ty0-c97', type: 'Cloze', question: 'Die ___ ist weit weg.', answer: 'Stadt', options: ['Stadt', 'Apfel', 'Fliege'], instruction: 'Place' },
    { id: 'ty0-c98', type: 'Cloze', question: 'Der ___ ist lang.', answer: 'Weg', options: ['Weg', 'Katze', 'Bett'], instruction: 'Place' },
    { id: 'ty0-c99', type: 'Cloze', question: 'Ein ___ für das Baby.', answer: 'Spielzeug', options: ['Spielzeug', 'Zug', 'Brot'], instruction: 'Object' },
    { id: 'ty0-c100', type: 'Cloze', question: 'Auf ___ !', answer: 'Wiedersehen', options: ['Wiedersehen', 'Hallo', 'Danke'], instruction: 'Greeting' },
  ],
  1: [
    { id: 'ty1-c52', type: 'Cloze', question: 'Wir ___ zum Strand.', answer: 'gehen', options: ['gehen', 'essen', 'schlafen'], instruction: 'Activity' },
    { id: 'ty1-c53', type: 'Cloze', question: 'Heute ___ es kalt.', answer: 'ist', options: ['ist', 'macht', 'geht'], instruction: 'Weather' },
    { id: 'ty1-c54', type: 'Cloze', question: 'Ich ___ mein Frühstück.', answer: 'esse', options: ['esse', 'sehe', 'lese'], instruction: 'Action' },
    { id: 'ty1-c55', type: 'Cloze', question: 'Sie ___ ein schönes Kleid.', answer: 'trägt', options: ['trägt', 'kauft', 'beendet'], instruction: 'Clothing' },
    { id: 'ty1-c56', type: 'Cloze', question: 'Die Katze ___ auf dem Teppich.', answer: 'schläft', options: ['schläft', 'singt', 'tanzt'], instruction: 'Action' },
    { id: 'ty1-c57', type: 'Cloze', question: 'Ihr ___ Käse.', answer: 'esst', options: ['esst', 'geht', 'lest'], instruction: 'Food' },
    { id: 'ty1-c58', type: 'Cloze', question: 'Sie ___ auf dem Hof.', answer: 'spielen', options: ['spielen', 'trinken', 'schlafen'], instruction: 'Action' },
    { id: 'ty1-c59', type: 'Cloze', question: 'Du ___ einen Trickfilm.', answer: 'schaust', options: ['schaust', 'hörst', 'esst'], instruction: 'Action' },
    { id: 'ty1-c60', type: 'Cloze', question: 'Wir ___ Musik.', answer: 'hören', options: ['hören', 'sehen', 'laufen'], instruction: 'Media' },
    { id: 'ty1-c61', type: 'Cloze', question: 'Das ___ steht in der Garage.', answer: 'Fahrrad', options: ['Fahrrad', 'Brot', 'Sonne'], instruction: 'Object' },
    { id: 'ty1-c62', type: 'Cloze', question: 'Der ___ liegt auf dem Rasen.', answer: 'Ball', options: ['Ball', 'Tisch', 'Nacht'], instruction: 'Object' },
    { id: 'ty1-c63', type: 'Cloze', question: 'Ich gehe ___ Schule.', answer: 'zur', options: ['zur', 'von', 'in'], instruction: 'Place' },
    { id: 'ty1-c64', type: 'Cloze', question: 'Er ___ ein rotes Buch.', answer: 'hat', options: ['hat', 'ist', 'geht'], instruction: 'Possession' },
    { id: 'ty1-c65', type: 'Cloze', question: 'Der ___ schmeckt lecker.', answer: 'Kuchen', options: ['Kuchen', 'Brücke', 'Wind'], instruction: 'Food' },
    { id: 'ty1-c66', type: 'Cloze', question: 'Das ___ meiner Mutter.', answer: 'Auto', options: ['Auto', 'Banane', 'Ohr'], instruction: 'Object' },
    { id: 'ty1-c67', type: 'Cloze', question: '___ am Himmel.', answer: 'Vögel', options: ['Vögel', 'Äpfel', 'Betten'], instruction: 'Animal' },
    { id: 'ty1-c68', type: 'Cloze', question: 'Ein ___ voller Äpfel.', answer: 'Korb', options: ['Korb', 'Sonne', 'Brücke'], instruction: 'Object' },
    { id: 'ty1-c69', type: 'Cloze', question: 'Das ist ___ für mich.', answer: 'gut', options: ['gut', 'blau', 'groß'], instruction: 'Description' },
    { id: 'ty1-c70', type: 'Cloze', question: 'Der ___ ist draußen.', answer: 'Hund', options: ['Hund', 'Flugzeug', 'Hut'], instruction: 'Animal' },
    { id: 'ty1-c71', type: 'Cloze', question: 'Mama ___ einen Kuchen.', answer: 'backt', options: ['backt', 'schläft', 'tanzt'], instruction: 'Action' },
    { id: 'ty1-c72', type: 'Cloze', question: 'Das ___ hängt an der Wand.', answer: 'Bild', options: ['Bild', 'Bett', 'Rasen'], instruction: 'Object' },
    { id: 'ty1-c73', type: 'Cloze', question: 'Eine ___ in der Schachtel.', answer: 'Überraschung', options: ['Überraschung', 'Straße', 'Kuh'], instruction: 'Object' },
    { id: 'ty1-c74', type: 'Cloze', question: 'Ich ___ mein Fahrrad.', answer: 'wasche', options: ['wasche', 'esse', 'lese'], instruction: 'Action' },
    { id: 'ty1-c75', type: 'Cloze', question: 'Das ___ ist voll.', answer: 'Glas', options: ['Glas', 'Wind', 'Meer'], instruction: 'Object' },
    { id: 'ty1-c76', type: 'Cloze', question: 'Wir ___ sehr schnell.', answer: 'laufen', options: ['laufen', 'schlafen', 'lesen'], instruction: 'Action' },
    { id: 'ty1-c77', type: 'Cloze', question: 'Eine ___ Kirschen.', answer: 'Schale', options: ['Schale', 'Wolke', 'Pferd'], instruction: 'Object' },
    { id: 'ty1-c78', type: 'Cloze', question: 'Ich bin ___ .', answer: 'dran', options: ['dran', 'Brot', 'Brücke'], instruction: 'Action' },
    { id: 'ty1-c79', type: 'Cloze', question: 'Die ___ brennt.', answer: 'Lampe', options: ['Lampe', 'Apfel', 'Straße'], instruction: 'Home' },
    { id: 'ty1-c80', type: 'Cloze', question: 'Ich schaue aus dem ___ .', answer: 'Fenster', options: ['Fenster', 'Tisch', 'Nacht'], instruction: 'Home' },
    { id: 'ty1-c81', type: 'Cloze', question: 'Der ___ ist nass.', answer: 'Boden', options: ['Boden', 'Himmel', 'Feuer'], instruction: 'Place' },
    { id: 'ty1-c82', type: 'Cloze', question: 'Ein ___ Sand.', answer: 'Haufen', options: ['Haufen', 'Kuh', 'Blume'], instruction: 'Object' },
    { id: 'ty1-c83', type: 'Cloze', question: 'Es ist ___ .', answer: 'windig', options: ['windig', 'Zucker', 'Honig'], instruction: 'Weather' },
    { id: 'ty1-c84', type: 'Cloze', question: 'Das ist ___ lustig.', answer: 'sehr', options: ['sehr', 'nie', 'blau'], instruction: 'Adverb' },
    { id: 'ty1-c85', type: 'Cloze', question: 'Ein ___ Blumen.', answer: 'Strauß', options: ['Strauß', 'Flugzeug', 'Bett'], instruction: 'Nature' },
    { id: 'ty1-c86', type: 'Cloze', question: 'Der ___ ist offen.', answer: 'Laden', options: ['Laden', 'Sonne', 'Hund'], instruction: 'Place' },
    { id: 'ty1-c87', type: 'Cloze', question: 'Ich ___ eine Frage.', answer: 'stelle', options: ['stelle', 'sehe', 'lese'], instruction: 'Action' },
    { id: 'ty1-c88', type: 'Cloze', question: 'Es ist ___ wahr.', answer: 'wirklich', options: ['wirklich', 'nichts', 'nicht'], instruction: 'Adverb' },
    { id: 'ty1-c89', type: 'Cloze', question: 'Der ___ geht nach rechts.', answer: 'Weg', options: ['Weg', 'Brücke', 'Wand'], instruction: 'Place' },
    { id: 'ty1-c90', type: 'Cloze', question: 'Eine ___ Erdbeeren.', answer: 'Schale', options: ['Schale', 'Straße', 'Kuh'], instruction: 'Object' },
    { id: 'ty1-c91', type: 'Cloze', question: 'Er ___ eine Geschichte.', answer: 'erzählt', options: ['erzählt', 'isst', 'trinkt'], instruction: 'Action' },
    { id: 'ty1-c92', type: 'Cloze', question: 'Meine ___ ist neu.', answer: 'Tasche', options: ['Tasche', 'Brot', 'Wind'], instruction: 'Object' },
    { id: 'ty1-c93', type: 'Cloze', question: 'Ein ___ am Himmel.', answer: 'Stern', options: ['Stern', 'Banane', 'Hand'], instruction: 'Nature' },
    { id: 'ty1-c94', type: 'Cloze', question: 'Das ist ___ für dich.', answer: 'besser', options: ['besser', 'blau', 'groß'], instruction: 'Adverb' },
    { id: 'ty1-c95', type: 'Cloze', question: 'Ich ___ "Bis bald".', answer: 'sage', options: ['sage', 'sehe', 'höre'], instruction: 'Action' },
    { id: 'ty1-c96', type: 'Cloze', question: 'Die ___ ist vorbei.', answer: 'Pause', options: ['Pause', 'Straße', 'Hand'], instruction: 'Time' },
    { id: 'ty1-c97', type: 'Cloze', question: 'Der ___ ist grün.', answer: 'Rasen', options: ['Rasen', 'Himmel', 'Milch'], instruction: 'Nature' },
    { id: 'ty1-c98', type: 'Cloze', question: 'Ein ___ am Himmel.', answer: 'Regenbogen', options: ['Regenbogen', 'Sonne', 'Brücke'], instruction: 'Nature' },
    { id: 'ty1-c99', type: 'Cloze', question: 'Es ___ zu spät.', answer: 'ist', options: ['ist', 'hat', 'geht'], instruction: 'Time' },
    { id: 'ty1-c100', type: 'Cloze', question: 'Viel ___ !', answer: 'Glück', options: ['Glück', 'Danke', 'Brot'], instruction: 'Greeting' },
  ],
  2: [
    { id: 'ty2-c52', type: 'Cloze', question: '___ Woche waren wir im Zoo.', answer: 'Letzte', options: ['Letzte', 'Nächste', 'Aktuelle'], instruction: 'Time' },
    { id: 'ty2-c53', type: 'Cloze', question: 'Es ist wichtig, jeden Tag die Zähne zu ___ .', answer: 'putzen', options: ['putzen', 'essen', 'verlieren'], instruction: 'Health' },
    { id: 'ty2-c54', type: 'Cloze', question: 'Der Zug ___ um zehn Uhr ab.', answer: 'fährt', options: ['fährt', 'trinkt', 'schläft'], instruction: 'Travel' },
    { id: 'ty2-c55', type: 'Cloze', question: 'Sie ___ ein schönes Lied.', answer: 'singt', options: ['singt', 'rennt', 'springt'], instruction: 'Media' },
    { id: 'ty2-c56', type: 'Cloze', question: 'Die Kinder ___ im Fluss.', answer: 'schwimmen', options: ['schwimmen', 'essen', 'lesen'], instruction: 'Activity' },
    { id: 'ty2-c57', type: 'Cloze', question: 'Mein ___ ist in der Garage.', answer: 'Papa', options: ['Papa', 'Brücke', 'Wind'], instruction: 'Family' },
    { id: 'ty2-c58', type: 'Cloze', question: 'Man muss die Hände vor dem Essen ___ .', answer: 'waschen', options: ['waschen', 'schmutzig machen', 'verstecken'], instruction: 'Health' },
    { id: 'ty2-c59', type: 'Cloze', question: 'Ich ___ gerne einen Schokoladenkuchen.', answer: 'hätte', options: ['hätte', 'bin', 'gehe'], instruction: 'Desire' },
    { id: 'ty2-c60', type: 'Cloze', question: 'Wir ___ Blumen im Garten.', answer: 'pflanzen', options: ['pflanzen', 'essen', 'trinken'], instruction: 'Nature' },
    { id: 'ty2-c61', type: 'Cloze', question: 'Die Sonne ___ heute Nachmittag stark.', answer: 'scheint', options: ['scheint', 'regnet', 'schneit'], instruction: 'Weather' },
    { id: 'ty2-c62', type: 'Cloze', question: 'Eine ___ Bonbons für dich.', answer: 'Tüte', options: ['Tüte', 'Straße', 'Kuh'], instruction: 'Object' },
    { id: 'ty2-c63', type: 'Cloze', question: 'Hier sind ___ Leute.', answer: 'viele', options: ['viele', 'nichts', 'nicht'], instruction: 'Quantity' },
    { id: 'ty2-c64', type: 'Cloze', question: 'Ich ___ meine Jacke an, wenn es kalt ist.', answer: 'ziehe', options: ['ziehe', 'esse', 'lese'], instruction: 'Clothing' },
    { id: 'ty2-c65', type: 'Cloze', question: 'Das ist ___ Geschichte.', answer: 'eine', options: ['une', 'ein', 'die'], instruction: 'Article' },
    { id: 'ty2-c66', type: 'Cloze', question: 'Die Vögel ___ am Morgen.', answer: 'singen', options: ['singen', 'schlafen', 'schwimmen'], instruction: 'Animal' },
    { id: 'ty2-c67', type: 'Cloze', question: 'Meine ___ ist in der Schule.', answer: 'Schwester', options: ['Schwester', 'Banane', 'Hand'], instruction: 'Family' },
    { id: 'ty2-c68', type: 'Cloze', question: 'Ein ___ rote Kirschen.', answer: 'Kilo', options: ['Kilo', 'Sonne', 'Brücke'], instruction: 'Quantity' },
    { id: 'ty2-c69', type: 'Cloze', question: 'Das ist ___ für die Gesundheit.', answer: 'schlecht', options: ['schlecht', 'blau', 'groß'], instruction: 'Description' },
    { id: 'ty2-c70', type: 'Cloze', question: 'Der Hund ___ laut.', answer: 'bellt', options: ['bellt', 'miaut', 'schwimmt'], instruction: 'Animal' },
    { id: 'ty2-c71', type: 'Cloze', question: 'Ich ___ an meinen Hausaufgaben.', answer: 'arbeite', options: ['arbeite', 'schlafe', 'tanze'], instruction: 'School' },
    { id: 'ty2-c72', type: 'Cloze', question: 'Der ___ liegt auf dem Schreibtisch.', answer: 'Stift', options: ['Stift', 'Flugzeug', 'Hut'], instruction: 'Object' },
    { id: 'ty2-c73', type: 'Cloze', question: 'Ein ___ in der Schublade.', answer: 'Radiergummi', options: ['Radiergummi', 'Straße', 'Kuh'], instruction: 'Object' },
    { id: 'ty2-c74', type: 'Cloze', question: 'Ich ___ jeden Tag mein Zimmer auf.', answer: 'räume', options: ['räume', 'esse', 'mache kaputt'], instruction: 'Action' },
    { id: 'ty2-c75', type: 'Cloze', question: 'Der ___ ist voll Wasser.', answer: 'Eimer', options: ['Eimer', 'Wind', 'Meer'], instruction: 'Object' },
    { id: 'ty2-c76', type: 'Cloze', question: 'Wir ___ Verstecken.', answer: 'spielen', options: ['spielen', 'schlafen', 'trinken'], instruction: 'Activity' },
    { id: 'ty2-c77', type: 'Cloze', question: 'Ein ___ Eis.', answer: 'Würfel', options: ['Würfel', 'Wolke', 'Pferd'], instruction: 'Object' },
    { id: 'ty2-c78', type: 'Cloze', question: 'Es ist ___ fertig.', answer: 'fast', options: ['fast', 'nie', 'alles'], instruction: 'Adverb' },
    { id: 'ty2-c79', type: 'Cloze', question: 'Die ___ schmeckt köstlich.', answer: 'Pizza', options: ['Pizza', 'Apfel', 'Straße'], instruction: 'Food' },
    { id: 'ty2-c80', type: 'Cloze', question: 'Schau dir diesen ___ Berg an.', answer: 'hohen', options: ['hohen', 'blauen', 'grauen'], instruction: 'Geography' },
    { id: 'ty2-c81', type: 'Cloze', question: 'Der ___ ist sehr schnell.', answer: 'Löwe', options: ['Löwe', 'Fisch', 'Brücke'], instruction: 'Animal' },
    { id: 'ty2-c82', type: 'Cloze', question: 'Eine ___ voller Perlen.', answer: 'Schachtel', options: ['Schachtel', 'Straße', 'Kuh'], instruction: 'Object' },
    { id: 'ty2-c83', type: 'Cloze', question: 'Heute ___ die Sonne.', answer: 'scheint', options: ['scheint', 'Zucker', 'Honig'], instruction: 'Weather' },
    { id: 'ty2-c84', type: 'Cloze', question: 'Das ist ___ nett von dir.', answer: 'sehr', options: ['sehr', 'nie', 'nicht'], instruction: 'Adverb' },
    { id: 'ty2-c85', type: 'Cloze', question: 'Eine ___ Musiker.', answer: 'Gruppe', options: ['Gruppe', 'Flugzeug', 'Bett'], instruction: 'Media' },
    { id: 'ty2-c86', type: 'Cloze', question: 'Der ___ ist sonntags geschlossen.', answer: 'Laden', options: ['Laden', 'Sonne', 'Hund'], instruction: 'Place' },
    { id: 'ty2-c87', type: 'Cloze', question: 'Ich ___ ein neues Lied.', answer: 'lerne', options: ['lerne', 'esse', 'lese'], instruction: 'Action' },
    { id: 'ty2-c88', type: 'Cloze', question: 'Das ist ___ falsch.', answer: 'völlig', options: ['völlig', 'nichts', 'nicht'], instruction: 'Adverb' },
    { id: 'ty2-c89', type: 'Cloze', question: 'Die ___ ist links.', answer: 'Brücke', options: ['Brücke', 'Wand', 'Brot'], instruction: 'Place' },
    { id: 'ty2-c90', type: 'Cloze', question: 'Eine ___ frische Milch.', answer: 'Flasche', options: ['Flasche', 'Straße', 'Kuh'], instruction: 'Drink' },
    { id: 'ty2-c91', type: 'Cloze', question: 'Er ___ ein Geheimnis.', answer: 'kennt', options: ['kennt', 'isst', 'trinkt'], instruction: 'Action' },
    { id: 'ty2-c92', type: 'Cloze', question: 'Mein ___ ist aus Pappe.', answer: 'Spielzeug', options: ['Spielzeug', 'Brot', 'Wind'], instruction: 'Object' },
    { id: 'ty2-c93', type: 'Cloze', question: 'Ein ___ Papier.', answer: 'Blatt', options: ['Blatt', 'Frucht', 'Hand'], instruction: 'Object' },
    { id: 'ty2-c94', type: 'Cloze', question: 'Es ist ___ schlimm.', answer: 'weniger', options: ['weniger', 'blau', 'groß'], instruction: 'Adverb' },
    { id: 'ty2-c95', type: 'Cloze', question: 'Ich ___ Danke.', answer: 'sage', options: ['sage', 'sehe', 'höre'], instruction: 'Action' },
    { id: 'ty2-c96', type: 'Cloze', question: 'Der ___ ist aus Holz.', answer: 'Tisch', options: ['Tisch', 'Straße', 'Hand'], instruction: 'Home' },
    { id: 'ty2-c97', type: 'Cloze', question: 'Der ___ ist pünktlich.', answer: 'Zug', options: ['Zug', 'Himmel', 'Milch'], instruction: 'Travel' },
    { id: 'ty2-c98', type: 'Cloze', question: 'Eine ___ kräftiger Farben.', answer: 'Mischung', options: ['Mischung', 'Sonne', 'Brücke'], instruction: 'Description' },
    { id: 'ty2-c99', type: 'Cloze', question: 'Er ___ eine tolle Idee.', answer: 'hat', options: ['hat', 'ist', 'geht'], instruction: 'Possession' },
    { id: 'ty2-c100', type: 'Cloze', question: 'Gute ___ !', answer: 'Reise', options: ['Reise', 'Danke', 'Brot'], instruction: 'Greeting' },
  ],
  3: [
    { id: 'ty3-c52', type: 'Cloze', question: 'Das Pferd ___ über das Feld.', answer: 'galoppiert', options: ['galoppiert', 'schläft', 'isst'], instruction: 'Action' },
    { id: 'ty3-c53', type: 'Cloze', question: 'Wir ___ morgen ins Kino gehen.', answer: 'werden', options: ['werden', 'gehen', 'gingen'], instruction: 'Time' },
    { id: 'ty3-c54', type: 'Cloze', question: 'Der Vogel ___ im Herbst nach Süden.', answer: 'zieht', options: ['zieht', 'tanzt', 'singt'], instruction: 'Animal' },
    { id: 'ty3-c55', type: 'Cloze', question: 'Sie ___ einen Brief an ihre Oma.', answer: 'schreibt', options: ['schreibt', 'trinkt', 'rennt'], instruction: 'Action' },
    { id: 'ty3-c56', type: 'Cloze', question: 'Das ___ des Meeres ist beruhigend.', answer: 'Rauschen', options: ['Rauschen', 'Brot', 'Brücke'], instruction: 'Sense' },
    { id: 'ty3-c57', type: 'Cloze', question: 'Man muss Sicherheitsregeln ___ .', answer: 'befolgen', options: ['befolgen', 'essen', 'verlieren'], instruction: 'Social' },
    { id: 'ty3-c58', type: 'Cloze', question: 'Ich ___ gestern einen neuen Film.', answer: 'sah', options: ['sah', 'sehe', 'werde sehen'], instruction: 'Time' },
    { id: 'ty3-c59', type: 'Cloze', question: 'Die Sterne ___ in der dunklen Nacht.', answer: 'funkeln', options: ['funkeln', 'flüstern', 'gehen'], instruction: 'Nature' },
    { id: 'ty3-c60', type: 'Cloze', question: 'Wir ___ Karotten im Gemüsegarten.', answer: 'pflücken', options: ['pflücken', 'trinken', 'lesen'], instruction: 'Nature' },
    { id: 'ty3-c61', type: 'Cloze', question: 'Der ___ weht heute Abend stark.', answer: 'Wind', options: ['Wind', 'Sonne', 'Wolke'], instruction: 'Weather' },
    { id: 'ty3-c62', type: 'Cloze', question: 'Eine ___ wertvoller Erinnerungen.', answer: 'Sammlung', options: ['Sammlung', 'Straße', 'Kuh'], instruction: 'Object' },
    { id: 'ty3-c63', type: 'Cloze', question: 'Hier ist es ___ zu laut.', answer: 'viel', options: ['viel', 'nichts', 'nicht'], instruction: 'Adverb' },
    { id: 'ty3-c64', type: 'Cloze', question: 'Ich ___ morgens meine Schlüssel.', answer: 'suche', options: ['suche', 'esse', 'lese'], instruction: 'Action' },
    { id: 'ty3-c65', type: 'Cloze', question: 'Das ist ___ wichtige Entscheidung.', answer: 'eine', options: ['eine', 'ein', 'die'], instruction: 'Article' },
    { id: 'ty3-c66', type: 'Cloze', question: 'Die ___ arbeiten im Bienenstock.', answer: 'Bienen', options: ['Bienen', 'Hunde', 'Hasen'], instruction: 'Animal' },
    { id: 'ty3-c67', type: 'Cloze', question: 'Meine ___ ist sehr nett zu uns.', answer: 'Tante', options: ['Tante', 'Banane', 'Hand'], instruction: 'Family' },
    { id: 'ty3-c68', type: 'Cloze', question: 'Eine ___ aus frischem Schnee.', answer: 'Decke', options: ['Decke', 'Sonne', 'Brücke'], instruction: 'Nature' },
    { id: 'ty3-c69', type: 'Cloze', question: 'Das ist ___ für alle zu verstehen.', answer: 'schwierig', options: ['schwierig', 'blau', 'groß'], instruction: 'Description' },
    { id: 'ty3-c70', type: 'Cloze', question: 'Der ___ wartet auf sein Herrchen.', answer: 'Hund', options: ['Hund', 'Flugzeug', 'Hut'], instruction: 'Animal' },
    { id: 'ty3-c71', type: 'Cloze', question: 'Ich ___ jetzt die Wahrheit.', answer: 'kenne', options: ['kenne', 'schlafe', 'tanze'], instruction: 'Action' },
    { id: 'ty3-c72', type: 'Cloze', question: 'Der ___ ist ordentlich sortiert.', answer: 'Ordner', options: ['Ordner', 'Flugzeug', 'Hut'], instruction: 'Object' },
    { id: 'ty3-c73', type: 'Cloze', question: 'Ein ___ im Schrank.', answer: 'Hemd', options: ['Hemd', 'Straße', 'Kuh'], instruction: 'Clothing' },
    { id: 'ty3-c74', type: 'Cloze', question: 'Ich ___ oft mit meiner Mama.', answer: 'telefoniere', options: ['telefoniere', 'esse', 'mache kaputt'], instruction: 'Action' },
    { id: 'ty3-c75', type: 'Cloze', question: 'Das ___ ist halb leer.', answer: 'Glas', options: ['Glas', 'Wind', 'Meer'], instruction: 'Object' },
    { id: 'ty3-c76', type: 'Cloze', question: 'Wir ___ zusammen in der Schule.', answer: 'lernen', options: ['lernen', 'schlafen', 'trinken'], instruction: 'School' },
    { id: 'ty3-c77', type: 'Cloze', question: 'Ein ___ feiner Sand.', answer: 'Korn', options: ['Korn', 'Wolke', 'Pferd'], instruction: 'Nature' },
    { id: 'ty3-c78', type: 'Cloze', question: 'Es ist ___ jetzt fertig.', answer: 'endlich', options: ['endlich', 'nie', 'alles'], instruction: 'Adverb' },
    { id: 'ty3-c79', type: 'Cloze', question: 'Der ___ ist meine Lieblingsjahreszeit.', answer: 'Frühling', options: ['Frühling', 'Pizza', 'Straße'], instruction: 'Time' },
    { id: 'ty3-c80', type: 'Cloze', question: 'Schau dir diesen ___ Blauwal an.', answer: 'riesigen', options: ['riesigen', 'blauen', 'grauen'], instruction: 'Animal' },
    { id: 'ty3-c81', type: 'Cloze', question: 'Der ___ ist das schnellste Tier.', answer: 'Gepard', options: ['Gepard', 'Fisch', 'Brücke'], instruction: 'Animal' },
    { id: 'ty3-c82', type: 'Cloze', question: 'Eine ___ seltener Perlen.', answer: 'Kette', options: ['Kette', 'Straße', 'Kuh'], instruction: 'Object' },
    { id: 'ty3-c83', type: 'Cloze', question: 'Hier ist überall ___ .', answer: 'Staub', options: ['Staub', 'Zucker', 'Honig'], instruction: 'Nature' },
    { id: 'ty3-c84', type: 'Cloze', question: 'Das ist ___ zu teuer für mich.', answer: 'viel', options: ['viel', 'nie', 'nicht'], instruction: 'Adverb' },
    { id: 'ty3-c85', type: 'Cloze', question: 'Eine ___ talentierter Tänzer.', answer: 'Gruppe', options: ['Gruppe', 'Flugzeug', 'Bett'], instruction: 'Media' },
    { id: 'ty3-c86', type: 'Cloze', question: 'Die ___ ist meine Lieblingsfrucht.', answer: 'Weintraube', options: ['Weintraube', 'Sonne', 'Hund'], instruction: 'Food' },
    { id: 'ty3-c87', type: 'Cloze', question: 'Ich ___ jeden Tag die Zeitung.', answer: 'lese', options: ['lese', 'esse', 'trinke'], instruction: 'Action' },
    { id: 'ty3-c88', type: 'Cloze', question: 'Das ist ___ unglaublich.', answer: 'absolut', options: ['absolut', 'nichts', 'nicht'], instruction: 'Adverb' },
    { id: 'ty3-c89', type: 'Cloze', question: 'Der ___ führt zum Meer.', answer: 'Pfad', options: ['Pfad', 'Wand', 'Brot'], instruction: 'Place' },
    { id: 'ty3-c90', type: 'Cloze', question: 'Eine ___ warme Milch am Abend.', answer: 'Tasse', options: ['Tasse', 'Straße', 'Kuh'], instruction: 'Drink' },
    { id: 'ty3-c91', type: 'Cloze', question: 'Er ___ immer seine Versprechen.', answer: 'hält', options: ['hält', 'isst', 'trinkt'], instruction: 'Action' },
    { id: 'ty3-c92', type: 'Cloze', question: 'Meine ___ ist sehr schwer zu tragen.', answer: 'Tasche', options: ['Tasche', 'Brot', 'Wind'], instruction: 'Object' },
    { id: 'ty3-c93', type: 'Cloze', question: 'Ein ___ Briefpapier.', answer: 'Satz', options: ['Satz', 'Frucht', 'Hand'], instruction: 'Object' },
    { id: 'ty3-c94', type: 'Cloze', question: 'Das ist ___ möglich.', answer: 'eher', options: ['eher', 'blau', 'groß'], instruction: 'Adverb' },
    { id: 'ty3-c95', type: 'Cloze', question: 'Ich ___ allen eine gute Nacht.', answer: 'wünsche', options: ['wünsche', 'sehe', 'höre'], instruction: 'Action' },
    { id: 'ty3-c96', type: 'Cloze', question: 'Die ___ ist aus glänzendem Metall.', answer: 'Tür', options: ['Tür', 'Straße', 'Hand'], instruction: 'Home' },
    { id: 'ty3-c97', type: 'Cloze', question: 'Der ___ fährt jetzt in den Bahnhof ein.', answer: 'Zug', options: ['Zug', 'Himmel', 'Milch'], instruction: 'Travel' },
    { id: 'ty3-c98', type: 'Cloze', question: 'Ein ___ harmonischer Klänge.', answer: 'Konzert', options: ['Konzert', 'Sonne', 'Brücke'], instruction: 'Media' },
    { id: 'ty3-c99', type: 'Cloze', question: 'Er ___ deine Hilfe nötig.', answer: 'hat', options: ['hat', 'ist', 'geht'], instruction: 'Possession' },
    { id: 'ty3-c100', type: 'Cloze', question: 'Viel ___ !', answer: 'Erfolg', options: ['Erfolg', 'Danke', 'Brot'], instruction: 'Greeting' },
  ],
  4: [
    { id: 'ty4-c52', type: 'Cloze', question: 'Der Computer ___ Strom.', answer: 'verbraucht', options: ['verbraucht', 'isst', 'schläft'], instruction: 'Science' },
    { id: 'ty4-c53', type: 'Cloze', question: 'Wir ___ morgen früh bei Tagesanbruch aufbrechen.', answer: 'müssen', options: ['müssen', 'werden', 'können'], instruction: 'Social' },
    { id: 'ty4-c54', type: 'Cloze', question: 'Wasser ___ bei hundert Grad Celsius.', answer: 'kocht', options: ['kocht', 'friert', 'läuft aus'], instruction: 'Science' },
    { id: 'ty4-c55', type: 'Cloze', question: 'Sie ___ mit viel Enthusiasmus.', answer: 'arbeitet', options: ['arbeitet', 'trinkt', 'rennt'], instruction: 'Action' },
    { id: 'ty4-c56', type: 'Cloze', question: 'Das ___ eines Düsentriebwerks.', answer: 'Dröhnen', options: ['Dröhnen', 'Brot', 'Brücke'], instruction: 'Sense' },
    { id: 'ty4-c57', type: 'Cloze', question: 'Man muss lokale Traditionen ___ .', answer: 'respektieren', options: ['respektieren', 'essen', 'verlieren'], instruction: 'Social' },
    { id: 'ty4-c58', type: 'Cloze', question: 'Ich ___ letztes Wochenende mein Fahrrad.', answer: 'reparierte', options: ['reparierte', 'repariere', 'werde reparieren'], instruction: 'Time' },
    { id: 'ty4-c59', type: 'Cloze', question: 'Die Lichter der Stadt ___ in der Ferne.', answer: 'leuchten', options: ['leuchten', 'flüstern', 'gehen'], instruction: 'Nature' },
    { id: 'ty4-c60', type: 'Cloze', question: 'Wir ___ Pilze im Wald.', answer: 'suchen', options: ['suchen', 'trinken', 'lesen'], instruction: 'Nature' },
    { id: 'ty4-c61', type: 'Cloze', question: 'Das Gewitter ___ in der Ferne.', answer: 'grollt', options: ['grollt', 'Sonne', 'Wolke'], instruction: 'Weather' },
    { id: 'ty4-c62', type: 'Cloze', question: 'Ein ___ mit Kochbüchern.', answer: 'Regal', options: ['Regal', 'Straße', 'Kuh'], instruction: 'Object' },
    { id: 'ty4-c63', type: 'Cloze', question: 'Es herrscht ___ zu viel Verkehr.', answer: 'manchmal', options: ['manchmal', 'nichts', 'nicht'], instruction: 'Quantity' },
    { id: 'ty4-c64', type: 'Cloze', question: 'Ich ___ abends meine Hausaufgaben.', answer: 'mache', options: ['mache', 'esse', 'lese'], instruction: 'Action' },
    { id: 'ty4-c65', type: 'Cloze', question: 'Das ist ___ ernste Angelegenheit.', answer: 'eine', options: ['eine', 'ein', 'die'], instruction: 'Article' },
    { id: 'ty4-c66', type: 'Cloze', question: 'Die ___ bauen ihre Dämme.', answer: 'Biber', options: ['Biber', 'Hunde', 'Hasen'], instruction: 'Animal' },
    { id: 'ty4-c67', type: 'Cloze', question: 'Meine ___ erzählt uns Geschichten.', answer: 'Großmutter', options: ['Großmutter', 'Banane', 'Hand'], instruction: 'Family' },
    { id: 'ty4-c68', type: 'Cloze', question: 'Ein ___ dichter Nebel.', answer: 'Schleier', options: ['Schleier', 'Sonne', 'Brücke'], instruction: 'Nature' },
    { id: 'ty4-c69', type: 'Cloze', question: 'Das ist ___ zu verstehen.', answer: 'einfach', options: ['einfach', 'blau', 'groß'], instruction: 'Description' },
    { id: 'ty4-c70', type: 'Cloze', question: 'Der ___ bewacht den Bauernhof treu.', answer: 'Hund', options: ['Hund', 'Flugzeug', 'Hut'], instruction: 'Animal' },
    { id: 'ty4-c71', type: 'Cloze', question: 'Ich ___ meine Lektionen mit Sorgfalt.', answer: 'lerne', options: ['lerne', 'schlafe', 'tanze'], instruction: 'Action' },
    { id: 'ty4-c72', type: 'Cloze', question: 'Die ___ ist voller Spielzeug.', answer: 'Kiste', options: ['Kiste', 'Flugzeug', 'Hut'], instruction: 'Object' },
    { id: 'ty4-c73', type: 'Cloze', question: 'Eine ___ im Schrank.', answer: 'Jacke', options: ['Jacke', 'Straße', 'Kuh'], instruction: 'Clothing' },
    { id: 'ty4-c74', type: 'Cloze', question: 'Ich ___ oft mein Fahrrad.', answer: 'benutze', options: ['benutze', 'esse', 'mache kaputt'], instruction: 'Action' },
    { id: 'ty4-c75', type: 'Cloze', question: 'Der ___ ist hier glasklar.', answer: 'See', options: ['See', 'Wind', 'Meer'], instruction: 'Place' },
    { id: 'ty4-c76', type: 'Cloze', question: 'Wir ___ draußen in der Pause.', answer: 'laufen', options: ['laufen', 'schlafen', 'trinken'], instruction: 'Activity' },
    { id: 'ty4-c77', type: 'Cloze', question: 'Eine ___ frischer Schnee.', answer: 'Flocke', options: ['Flocke', 'Wolke', 'Pferd'], instruction: 'Nature' },
    { id: 'ty4-c78', type: 'Cloze', question: 'Es ist ___ jetzt beendet.', answer: 'endlich', options: ['endlich', 'nie', 'alles'], instruction: 'Adverb' },
    { id: 'ty4-c79', type: 'Cloze', question: 'Der ___ ist die Erntezeit.', answer: 'Sommer', options: ['Sommer', 'Pizza', 'Straße'], instruction: 'Time' },
    { id: 'ty4-c80', type: 'Cloze', question: 'Schau dir diesen ___ Blauwal an.', answer: 'gigantischen', options: ['gigantischen', 'blauen', 'grauen'], instruction: 'Animal' },
    { id: 'ty4-c81', type: 'Cloze', question: 'Der ___ ist ein mächtiges Raubtier.', answer: 'Tiger', options: ['Tiger', 'Fisch', 'Brücke'], instruction: 'Animal' },
    { id: 'ty4-c82', type: 'Cloze', question: 'Eine ___ funkelnder Perlen.', answer: 'Kette', options: ['Kette', 'Straße', 'Kuh'], instruction: 'Object' },
    { id: 'ty4-c83', type: 'Cloze', question: 'Auf den Gipfeln liegt ___ .', answer: 'Schnee', options: ['Schnee', 'Zucker', 'Honig'], instruction: 'Nature' },
    { id: 'ty4-c84', type: 'Cloze', question: 'Das ist ___ schade für ihn.', answer: 'sehr', options: ['sehr', 'nie', 'nicht'], instruction: 'Adverb' },
    { id: 'ty4-c85', type: 'Cloze', question: 'Eine ___ von Forscher.', answer: 'Gruppe', options: ['Gruppe', 'Flugzeug', 'Bett'], instruction: 'Media' },
    { id: 'ty4-c86', type: 'Cloze', question: 'Die ___ ist eine Vitaminquelle.', answer: 'Kiwi', options: ['Kiwi', 'Sonne', 'Hund'], instruction: 'Food' },
    { id: 'ty4-c87', type: 'Cloze', question: 'Ich ___ täglich meine E-Mails.', answer: 'prüfe', options: ['prüfe', 'esse', 'trinke'], instruction: 'Action' },
    { id: 'ty4-c88', type: 'Cloze', question: 'Das ist ___ toll anzusehen.', answer: 'wirklich', options: ['wirklich', 'nichts', 'nicht'], instruction: 'Adverb' },
    { id: 'ty4-c89', type: 'Cloze', question: 'Der ___ verliert sich im Wald.', answer: 'Pfad', options: ['Pfad', 'Wand', 'Brot'], instruction: 'Place' },
    { id: 'ty4-c90', type: 'Cloze', question: 'Eine ___ beruhigende warme Milch.', answer: 'Tasse', options: ['Tasse', 'Straße', 'Kuh'], instruction: 'Drink' },
    { id: 'ty4-c91', type: 'Cloze', question: 'Er ___ immer seine Zusagen.', answer: 'hält', options: ['hält', 'isst', 'trinkt'], instruction: 'Action' },
    { id: 'ty4-c92', type: 'Cloze', question: 'Meine ___ steckt voller Schätze.', answer: 'Kiste', options: ['Kiste', 'Brot', 'Wind'], instruction: 'Object' },
    { id: 'ty4-c93', type: 'Cloze', question: 'Ein ___ Zeichenpapier.', answer: 'Blatt', options: ['Blatt', 'Frucht', 'Hand'], instruction: 'Object' },
    { id: 'ty4-c94', type: 'Cloze', question: 'Es ist ___ schlimm jetzt.', answer: 'weniger', options: ['weniger', 'blau', 'groß'], instruction: 'Adverb' },
    { id: 'ty4-c95', type: 'Cloze', question: 'Ich ___ den Gästen ein Herzliches Willkommen.', answer: 'wünsche', options: ['wünsche', 'sehe', 'höre'], instruction: 'Action' },
    { id: 'ty4-c96', type: 'Cloze', question: 'Das ___ ist aus geschmiedetem Eisen.', answer: 'Gitter', options: ['Gitter', 'Straße', 'Hand'], instruction: 'Home' },
    { id: 'ty4-c97', type: 'Cloze', question: 'Das ___ führt über das Tal.', answer: 'Viadukt', options: ['Viadukt', 'Himmel', 'Milch'], instruction: 'Travel' },
    { id: 'ty4-c98', type: 'Cloze', question: 'Ein ___ schimmernder Farben.', answer: 'Fächer', options: ['Fächer', 'Sonne', 'Brücke'], instruction: 'Description' },
    { id: 'ty4-c99', type: 'Cloze', question: 'Er ___ eine hervorragende Ausrede.', answer: 'hat', options: ['hat', 'ist', 'geht'], instruction: 'Possession' },
    { id: 'ty4-c100', type: 'Cloze', question: 'Viel ___ !', answer: 'Glück', options: ['Glück', 'Danke', 'Brot'], instruction: 'Greeting' },
  ],
};
